### ISSUE TITLE
Next io.js / Node.js build / CI reconcilliation meeting

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#100]
Anyone from @nodejs/build and beyond who is interested in helping with this effort, please respond to the doodle: http://doodle.com/y5earkqp4d2mhg23

Video of previous meeting is @ http://www.youtube.com/watch?v=8dxkM9vHmrY - we'll try and get more detailed agenda heading in to it.

**Comment by Fishrock123** [comment]
Pull me in if npm testing will be discussed, otherwise I don't have much to add.

**Comment by misterdjules** [comment]
I've been sick for the past few days, I'll update the doodle when I feel better. Don't let that block any meeting though.

**Comment by rvagg** [comment]
my schedule is spotty this week due to travel and CampJS on the weekend, next week and beyond is much more settled though because I'll be home finally; but the doodle should represent my estimated availability though

**Comment by Starefossen** [comment]
I responded to the doodle as well as a representative from the Docker WG. I'm interested in helping out wherever possible as well.

**Comment by rvagg** [comment]
might be good to have a rep from @nodejs/website on this as well because of the overlap

**Comment by robertkowalski** [comment]
yo, responded :)

**Comment by orangemocha** [comment]
So it looks like Monday 9pm-10pm UTC (2pm-3pm PST) works for everybody (except for @misterdjules who will be on vacation). Not sure how to send an invite through github, so consider this it :)

**Comment by Starefossen** [comment]
Where will the meeting take place today? Hangouts?

**Comment by mhdawson** [comment]
I also need the meeting details

**Comment by orangemocha** [comment]
https://plus.google.com/hangouts/_/g77deac75xhp62i62uzoa4oopea

**Comment by rvagg** [comment]
Sorry for being so unhelpful this time around @orangemocha, I've been super disorganised with nearly a month away from home. Got back last night and only just tuned in to the fact that this meeting is happening now.

I've rallied folks in https://gitter.im/nodejs/build, hopefully we'll have a good turn-out. If you have thoughts on an agenda could you drop them in here?

**Comment by orangemocha** [comment]
Sorry, I didn't have a lot of time to prepare either. But I jotted down a couple of agenda items. Perhaps we can take notes during the call and post them here afterwards.

**Comment by rvagg** [comment]
# Minutes 2015-05-25

## Agenda

* Make io.js CI infra work with joyent/node
  - Tests - Alexis
  - Releases - Julien + Rod
* Hardware
  - PowerPC (IBM)
  - Azure
* Jenkins + Windows uncertainty
  - Flakey tests?
* Secrets and asset management
* Group interaction going forward

## Present

* Alexis Campala
* Forrest Norvel
* Rod Vagg
* Johan Bergstrom
* Hans Kristian Flaatten
* Jeremiah Senkpiel
* Michael Dawson

## Make io.js CI infra work with joyent/node
* Alexis to make a test job work. Make a copy of iojs-any-pr-multi, to work with joyent\node
* Rod to work with Julien towards releases
* Rod: note ignore the build labels prefixed with “iojs-”, we’re migrating to plain names, like “ubuntu1404-64”

## Hardware
* Michael requested two machines from IBM - PowerPC le and be
* Build machines to be managed by the build team
* Ideally make setup ansible
* Johan to help out with Michael on Ansible setup
* `next` branch on io.js has V8 4.3
* Would be good to have these machines testing that
create a list of hardware we would be interested in adding (additional architectures or improve parallelism) - Johan to work on updating README

## Jenkins + Windows uncertainty
* A few tests failing when Jenkins runs as a service . Sometimes it takes a few days before the issue surfaces. Can’t replicate outside of Jenkins . Environmental issue- Alexis to investigate
*  File an issue in the build repo to collect details of consistent failures
  - johan will collect all possibly “jenkins”-related failures
  - johan to collect data on -J / parallel test failures on the machines
* Flaky tests: bring node-accept-pull-request over to the io.js CI

## Secrets and asset management

* Rod to work on maintaining a secrets document / spreadsheet for io.js infra
* Rod to work on maintaining an assets list for build infra
* Rod to push forward with signing keys for Windows, Apple Mac Developer Program account
* Rod to push forward with ssl certs / wildcard or otherwise for nodejs.org iojs.org
move jenkins to nodejs.org domain

## Group interaction going forward

* GitHub issues
* https://gitter.im/nodejs/build

## Next meeting

in 8 days, one hour earlier

## Agenda items for next meeting

* node accept PR (Alexis to integrate with io.js Jenkins for joyent/node)
  - flakey tests
* npm integration - how it’s being tested on both sides and how to improve it (Forrest, Jeremiah)
* testing for website (Robert)

**Comment by robertkowalski** [comment]
@rvagg oh sorry please remove `testing for website` - i meant: this will probably be a topic in the long term. 

and i forgot to say: as we just build the website for one target we could use something like travis.

**Comment by jbergstroem** [comment]
(work in progress) build flakiness status here: https://gist.github.com/jbergstroem/d16518d38ef6ddc0e697

**Comment by orangemocha** [comment]
Hangout URL: https://plus.google.com/hangouts/_/g77deac75xhp62i62uzoa4oopea

**Comment by orangemocha** [comment]
Meeting canceled today because of low attendance. Let's reschedule.

**Comment by jbergstroem** [comment]
@orangemocha isn't the meeting in 24 hours (I also thought it was today)?

**Comment by Starefossen** [comment]
No, I think we scheduled the meeting for today, Tuesday one hour before the last time.

**Comment by Fishrock123** [comment]
@mhdawson @othiym23 I think it's mainly just us hashing out npm stuff.. Michael, will you be at Nodeconf Adventure next week by any chance? If so, we could probably hash some of it out there..

(That goes for the rest too, I'm definitely not expecting anyone to be there, but if people are.. \o/)

**Comment by mhdawson** [comment]
@Fishrock123 Unfortunately I won't be there.   Does it make sense if I sent out a doodle to agree on a time to talk specifically about npm testing ?  I'm thinking we want you, @othiym23 and whoever else is interested.

@orangemocha.  Sorry if I was confused about the time. Is the plan every Tuesday at 4 EST, if so I'll add to my calendar.

**Comment by rvagg** [comment]
sorry, I didn't make it either .. I live by my calendar these days and it wasn't on there

**Comment by orangemocha** [comment]
Let's try with an iCalendar file. Does this work? https://www.dropbox.com/s/2kguf6kp5jjabtx/Reconciling%20CI%20meeting.ics?dl=0

**Comment by robertkowalski** [comment]
hey - i am on vacations. i am not sure if you still need someone from the website team...

**Comment by misterdjules** [comment]
@orangemocha I was able to add it to my calendar, but I don't think I could reply to accept the meeting, so you probably didn't get notified too.

**Comment by othiym23** [comment]
I didn't see this until now because I'm way behind on my notifications (I've been on boarding a new npm CLI team member this week!), but I'm happy to meet with @mhdawson and @Fishrock123 separately from the rest of @iojs/build to talk npm testing. Mon-We'd next week work best for me, because as Jeremiah said Thu-Fri are NodeConf Adventure, and the wifi will be dodgy.

**Comment by Fishrock123** [comment]
I might be around Tuesday next week. Monday and Wednesday are going to be primarily filled with travel.

**Comment by mhdawson** [comment]
Would Tuesday 1 or 2 PM EST work for you two ?

**Comment by othiym23** [comment]
@mhdawson either works for me.

**Comment by mhdawson** [comment]
I'll try to catch @othiym23  and @Fishrock123 at ~1:15 EST on Tuesday through hangouts (I have to drive between buildings just before that time but I'm hoping 1:15 should be safe)

**Comment by Fishrock123** [comment]
1-2 EST (currently 10-11 PST for me) should work.

**Comment by jbergstroem** [comment]
I'm confused. Can we confirm tomorrows meeting at in roughly 14 hours?

**Comment by misterdjules** [comment]
@orangemocha had shared [in his latest comment](https://github.com/nodejs/build/issues/100#issuecomment-108856033) a calendar entry scheduled for 1:00pm (not sure about the timezone, I assumed PDT). What happened with that?

**Comment by orangemocha** [comment]
@jbergstroem , our CI reconciliation meeting is confirmed. I think @mhdawson @othiym23 and @Fishrock123  were discussing a separate meeting to talk about npm testing.

This is the calendar event for the CI reconciliation call: https://www.dropbox.com/s/2kguf6kp5jjabtx/Reconciling%20CI%20meeting.ics?dl=0

**Comment by rvagg** [comment]
Google+ Event: https://plus.google.com/b/101986715696875566237/events/cb6vrd2pifbd2avthg3ik7qlhu0

Hangouts On Air: https://plus.google.com/hangouts/_/hoaevent/AP36tYeR6xykEAGB7R_JgaewHH0WnzHt1PwZOSV_6kBTJXTptayM_Q

***Ignore the Hangouts link in the invite, use the above instead***

**Comment by rvagg** [comment]
I've sent a new invite via Google Calendar to a bunch of people who _may_ be interested in attending (sorry @orangemocha, the .ics file was a tiny bit painful), it's set to repeat each week for now. If you received the invite and you're not interested then feel free to ignore it, remove yourself, or ask to be taken off it.

**Comment by othiym23** [comment]
@mhdawson @Fishrock123 I'm still in transit and won't be available for hangout until 10:25.

**Comment by Fishrock123** [comment]
@mhdawson @othiym23 I don't know ether of your google accounts. Mine is jeremiah.senkpiel@gmail.com.

**Comment by othiym23** [comment]
@Fishrock123 For future reference, either forrest@npmjs.com or othiym23@gmail.com will work for Hangout invites.

**Comment by rvagg** [comment]
http://www.youtube.com/watch?v=3V6EmRH0_60

https://docs.google.com/document/d/1zuUujd6XEdOJnvT6E_TzveZ8LGanhHGaOds69IyaVIw/edit#

**Comment by mhdawson** [comment]
@jbergstroem can you ping me at michael_dawson@ca.ibm.com to setup a time to go through adding the PPC LE and PPC BE machines.  Thye are ubuntu 14.04 and Fedora 20 so I'm thinking the existing playbooks will be pretty close to what we need.

**Comment by jbergstroem** [comment]
Closing, irrelevant as of now.
