### ISSUE TITLE
RFC: Rename build status labels

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1008]
Was looking at the build status labels used on nodejs/node PRs, and wanted to discuss a few possible changes:

- rename current status labels
  - rename `linter` to `node-test-commit-linter`
  - rename `test/*` to `node-test-commit-*`
- send new status labels
  - send `node-test-commit` overall job as `node-test-commit`
  - send `node-test-pull-request` overall job as `node-test-pull-request`
  - send `node-test-commit-v8-linux` overall job as `node-test-commit-v8-linux`

Thoughts?

**Comment by gibfahn** [comment]
So rename the labels to the Jenkins job name? Seems reasonable.

**Comment by maclover7** [comment]
> So rename the labels to the Jenkins job name? Seems reasonable.

Exactly, not sure why I didn't just say that from the beginning 😄

**Comment by maclover7** [comment]
completed
