### ISSUE TITLE
[libuv] rebase option in /view/libuv/job/libuv-test-commit/build

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1010]
Oh hai.  Can we get a REBASE_ONTO field like there is [here](https://ci.nodejs.org/job/node-test-commit/build)?  Thanks!

**Comment by rvagg** [comment]
@nodejs/build someone got time to add this? it might need to be added down into the subjobs too. If we have a volunteer in @nodejs/build who doesn't have @nodejs/jenkins-admins then perhaps we can up your privs for at least these jobs.

**Comment by Trott** [comment]
/ping @nodejs/build! Anyone up for doing this? (@bnoordhuis I assume there's still a need.)

**Comment by bnoordhuis** [comment]
Yes, I still very much would like to have that option.
