### ISSUE TITLE
Add new 10.10 machines from macstadium to CI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1011]
We still have some work to do like adding ccache to the machines, but tests are now
passing on 10.10.  See https://ci.nodejs.org/view/All/job/node-test-commit-osx-macstadium/nodes=macstadium-osx1010/

They run in about 30 minutes (possibly because we don't have ccache setup in ansible yet) which is longer than the existing machine at ~15 min.  However, jobs often have to wait for the existing machine so elapsed time ends up being much longer.

I think we should go ahead an add them.  It will make it a bit more work (disable/enable/test) to do the remaining updates (although we have enough resources we could just create a few more machines if it is a real problem anyway) but I think its worth it.

Any objections to adding them so they are used by the regular CI jobs ? 

@nodejs/build 
@nodejs/testing 
@gdams

**Comment by gdams** [comment]
I will add ccache to the ansible playbook for macOS and see if the build times are any better

**Comment by rvagg** [comment]
ccache would fix that delta I reckon, maybe even improve on the 15 mins as 30 mins without ccache is pretty decent

+1 to adding them to CI, thanks for all the hard work on this @gdams et. al.! This fantastic. I'd love to explore ways to share the knowledge of the MacStadium setup across the team a bit because it's so darn complicated. Any thoughts on that?

**Comment by mhdawson** [comment]
@rvagg I think we should walk the overall team through the setup in the next build WG meeting, and as part of doing that come up with the key points that need more documentation.  I was planning to write up a doc, but that would make sure we cover the key points.

**Comment by gdams** [comment]
yeah that sounds good with me :)

**Comment by mhdawson** [comment]
@nodejs/collaborators just added 2 new osx 1010 test machines.  Let us know if you see problems that might be related (unexpected failures on the osx macstadium machines)

**Comment by mhdawson** [comment]
Closing as the machines have been in the CI for a while.
