### ISSUE TITLE
Add blue ocean plugin to Jenkins

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1012]
Using Blue Ocean (a rethink of the Jenkins UI) would be helpful as I am playing around with libuv-test-pipeline, as it provides new page layouts for complex pipeline stages. Per the [announcement blog post](https://jenkins.io/blog/2016/05/26/introducing-blue-ocean/) and [documentation](https://jenkins.io/doc/book/blueocean/getting-started/#start-blueocean):

> While this project is in the alpha stage of development, the intent is that Jenkins users can install Blue Ocean side-by-side with the Jenkins Classic UI via a plugin.

The Blue Ocean UI should be available under the `/blue` route, and should not interfere with any normal behavior. If when the plugin is installed it is causing problems, then it should be removed, no questions asked :)

cc @nodejs/jenkins-admins

**Comment by gibfahn** [comment]
+1 to installing this, Blue Ocean is where Jenkins is apparently headed, we should be trying it out. And as it's just a UI layer, it shouldn't change our existing setup.

I thought @refack was already playing with Blue ocean, maybe I remember wrong.

I would say that I've never actually managed to get useful information out of it, and always fallen back to the existing console log, but maybe that's improving.

**Comment by mhdawson** [comment]
@maclover7 once you are confortable with 'Blue Ocean' it would be great if you could schedule taking the build team through it in one of the build WG meetings

**Comment by maclover7** [comment]
> I thought @refack was already playing with Blue ocean, maybe I remember wrong.

@gibfahn `https://ci.nodejs.org/blue` 404s 😬 

> once you are confortable with 'Blue Ocean' it would be great if you could schedule taking the build team through it in one of the build WG meetings

@mhdawson sure, no problem!

**Comment by rvagg** [comment]
I've installed it for you to play with. I've got no problems having it installed as long as it's being used and gets updated regularly (@nodejs/jenkins-admins - update plugins regularly pls). I've installed some of its associated plugins too but none of the API ones. IF you need them then let us know.

I've not found Blue Ocean very useful, quite the opposite, but perhaps it's improved of late and perhaps you can pull off some creative pipeline configs to make it make sense for us! Please show us if you come up with something compelling.

https://ci.nodejs.org/blue/organizations/jenkins/

**Comment by gibfahn** [comment]
>(@nodejs/jenkins-admins - update plugins regularly pls).

I find plugin updates regularly break things, so I wasn't really comfortable doing it without access to the machine itself in case things go wrong (I've had to manually copy `jpi` files over to fix things before, most recently [JENKINS-479500](https://issues.jenkins-ci.org/browse/JENKINS-479500).

**Comment by maclover7** [comment]
Closing this for now, plugin working nicely for me.
