### ISSUE TITLE
Jenkins jobs cleanup

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1014]
As part of the ongoing move to pipelines, trying to sort out which Jenkins jobs on the public CI are personal, and which do need to be converted over.

Some which (maybe?) could get the axe are:

- [ ] benchmark-footprint-experimental-TCP_NODELAY
- [x] benchmark-footprint-experimental-test
- [x] benchmark-node-dc-eis
- [ ] citgm-continuous-integration-gh-bot-test
- [ ] jbergstroem-test-commit-debug
- [x] kunalspathak-cctest
- [x] kunalspathak-libuv-test-commit
- [x] kunalspathak-libuv-test-commit-windows
- [x] kunalspathak-node-compile-windows
- [x] kunalspathak-node-test-binary-windows
- [x] kunalspathak-node-test-commit-windows-fanned
- [ ] node-test-commit-arm-gh-bot-test
- [ ] node-test-commit-linux-abi-gabriel
- [x] node-test-commit-linux-coverage-mdawson
- [ ] node-test-commit-linux-gibson
- [x] node-test-commit-linux-mdawson
- [x] refack-node-test-library

Please comment your thoughts... if jobs are being used, then they should definitely not be removed 😄

cc @nodejs/build @gabrielschulhof @kunalspathak

**Comment by mhdawson** [comment]
Deleted:
node-test-commit-linux-coverage-mdawson
node-test-commit-linux-mdawson
benchmark-footprint-experimental-test
benchmark-node-dc-eis

I'd like to keep benchmark-footprint-experimental-TCP_NODELAY as I think we may still want some additional runs and it may provide context for how to set those up.

**Comment by refack** [comment]
deleted `refack-node-test-library`

**Comment by kunalspathak** [comment]
deleted 
```
 kunalspathak-cctest
 kunalspathak-libuv-test-commit
 kunalspathak-libuv-test-commit-windows
 kunalspathak-node-compile-windows
 kunalspathak-node-test-binary-windows
 kunalspathak-node-test-commit-windows-fanned
```

**Comment by maclover7** [comment]
Pretty good cleanup, going to close for now.
