### ISSUE TITLE
platform coverage: we have only 1 platform with python2.6

### ISSUE THREAD

**Issue by refack** [nodejs/build#1018]
Only the `centos6-64` workers use python2.6. Temporarily I've configured them to use python2.7 while we're fixing an incompatibility in core.
Should we bump the requirements to include only python2.7, or should we add python2.6 usage to other platforms?
Need to figure out if python2.7 is available for all our platforms (for CentOS for example it's available only as side-by-side via SCL)

**Comment by refack** [comment]
So apparently it's not simple to upgrade CentOS6 to python2.7, so I restored them to python2.6.

**Comment by gibfahn** [comment]
Sounds like we need to keep allowing Python 2.6 for the life of CentOS 6 then.

Why would we need more workers though? seems like what we need is to get CI green enough that people notice test failures.

**Comment by refack** [comment]
I'd say support 2.6 until we have a very good reason to stop. But in any case we should have some explicit tests. CentOS6 is an implicit test, and apparently it's easy to miss.

**Comment by maclover7** [comment]
Seems like there's nothing really actionable here? Please reopen if I'm mistaken
