### ISSUE TITLE
Request: job to test libuv commit with Node.js

### ISSUE THREAD

**Issue by cjihrig** [nodejs/build#1019]
Bringing the conversation from https://github.com/libuv/libuv/issues/1486 here at the request of @mhdawson.

**The Request**: It would be awesome if we could test a given libuv commit in the context of Node. This would mostly be used to test libuv release candidates.

**Why?**:
- Node's test suite is much more thorough than libuv's, and it's easier to test certain things in JavaScript compared to C.
- Node is the primary user of libuv.
- It would (hopefully) prevent release-fix-release cycles in libuv.

**Comment by refack** [comment]
https://ci.nodejs.org/job/node-test-commit-v8-linux/ style? i.e.
1. checkout a node revision
2. vendor in the specified uv version
3. build & test node

Would you like to have control over the node version, or just taking `master` is good enough?

**Comment by cjihrig** [comment]
`master` should be fine for my use case. I want to test libuv in the context of Node before I make a libuv release and open a PR against Node's `master` branch.

**Comment by maclover7** [comment]
Interesting idea -- would be great to implement this as a pipeline in Jenkins.

Any thoughts on which platforms this should be run on?

**Comment by refack** [comment]
I thought about manipulation the temp git branch in the parent job, then just running `node-test-commit`. Can a pipeline call a regular job?

**Comment by cjihrig** [comment]
All of the platforms would be ideal since there is a lot of low level and platform specific code in libuv.

**Comment by gibfahn** [comment]
>Can a pipeline call a regular job?

Yep, really easy, just do `build(job: 'job-name')`, you can do some more complex things (pass custom parameters, run jobs in parallel, assign labels to jobs, not fail on flaky etc.

I've been playing with pipelines quite a bit recently, maybe we could pair on this.

Example:

https://github.com/gibfahn/build/blob/custom-config/jenkins/pipelines/node-test-commit.jenkinsfile

**Comment by cjihrig** [comment]
Is there any update on this? It would still be great to have.

**Comment by joaocgreis** [comment]
I created a job, but we need a repository on GitHub to store the temporary commit with changed libuv.

Can someone with permission create a repository in the libuv organization? I think it makes more sense in libuv, but could be anywhere. It can be named something like `ci-tmp-libuv-node`. Please add @nodejs-ci as a collaborator. When this is done, I'll test the job and share the link.

**Comment by cjihrig** [comment]
@bnoordhuis could you do what @joaocgreis is asking? I don't have the necessary permissions in the libuv org.

**Comment by bnoordhuis** [comment]
@cjihrig I made you an owner.

**Comment by cjihrig** [comment]
Thanks Ben!

@joaocgreis here you go: https://github.com/libuv/ci-tmp-libuv-node

**Comment by joaocgreis** [comment]
Thanks, here it is: https://ci.nodejs.org/view/libuv/job/libuv-in-node/

Didn't finish the test runs because CI is extremely busy at the moment, but it looks ok until launching `node-test-commit`. Let me know if there's any issue with it.

**Comment by cjihrig** [comment]
Thanks a ton @joaocgreis. It looks like the job you started got killed, but I reran it and it looks pretty good - https://ci.nodejs.org/view/libuv/job/libuv-in-node/10/.
