### ISSUE TITLE
Power BE and LE machines

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#102]
I had requested and received 2 Power machines from http://osuosl.org on behalf of Node.js. I was planning on hooking them up to the existing joyent/node build infrastructure but given things are coming together under the foundation it probably makes more sense to add to the converged build infrastructure.

Once added, my plans were to try to add builds that would use the latest 0.12.X Node source, pulling in the required V8 from https://github.com/andrewlow/v8ppc.  This would provide some regression tests until Node moves up to a level where V8 includes full PPC support natively (4.3 and later).

I'm opening this to ask how I get the level of access required to add these machines and then add the builds mentioned.

**Comment by bnoordhuis** [comment]
Wouldn't it be less effort to start with the io.js next branch?  It bundles V8 4.3.61.21.

**Comment by jbergstroem** [comment]
Awesome! If possible, it'd be great to hook it up similar to what we've done with the other machines and ansible.

**Comment by mhdawson** [comment]
My first step was to get some builds working in the environment that I'm familiar with (our internal jenkins) using io.js next. 

 I have them building/testing after applying what looked to be the minimal set of patches to add ppc as a supported platform for Node  (excluding the ones for AIX which I'll add in later) but I have about 6 crypto related failures on ppc that I don't see on x.  My next step is to figure out if they are because I'm missing some additional patches or something else.  Once I get that sorted I'll start looking at getting the machines added to the converged build infrastructure and adding ppc as a platform that the builds for next run on.

**Comment by mhdawson** [comment]
Going to close this since I have the required access
