### ISSUE TITLE
3/4 ARM6 release machines (requireio) offline

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1021]
release-requireio_rvagg-debian7-arm_pi1p-1
release-requireio_andineck-debian7-arm_pi1p-1
release-requireio_andineck-debian7-arm_pi1p_backup-1

all all off-line.

@rvagg 

We still have 1 ARM6 Pi1 running but it can't keep up.

**Comment by rvagg** [comment]
Power outage caused havoc, I'm afk but will fix asap.

**Comment by rvagg** [comment]
got it all sorted now I think
