### ISSUE TITLE
upgrade testing: uv testing has more deps, so we should test `libuv-test-commit` after upgrade

### ISSUE THREAD

**Issue by refack** [nodejs/build#1022]
Refs: https://github.com/libuv/libuv/pull/1656
job: https://ci.nodejs.org/job/libuv-test-commit/607/
Fails on the upgrade ubuntu1404 (ppc and intel), and the new macstadium macs

**Comment by refack** [comment]
Refs: https://github.com/libuv/libuv/pull/1656
job: https://ci.nodejs.org/job/libuv-test-commit/607/
Fails on the upgrade ubuntu1404 (ppc and intel), and the new macstadium macs

**Comment by maclover7** [comment]
I believe that the https://ci.nodejs.org/view/All/job/libuv-in-node/ job solves this -- @cjihrig @bnoordhuis?

**Comment by cjihrig** [comment]
I think this can be closed, but, PLEASE take a look at https://github.com/nodejs/build/issues/1186

**Comment by maclover7** [comment]
Will do. Closing this and taking a look at the other issue.
