### ISSUE TITLE
linuxOne: gcc upgrade

### ISSUE THREAD

**Issue by jBarz** [nodejs/build#1023]
Create ansible scripts to install 2 versions of gcc on the same machine.

gcc v4.8.5 (Used by node 4.x, 6.x)
gcc v4.9.4 (Used by node 8.x and above)

**Comment by mhdawson** [comment]
@jBarz hopefully we can use the same approach or something very similar for the PPC LE machine as discussed in https://github.com/nodejs/build/issues/1020

**Comment by Trott** [comment]
Since Node.js 4.x and 6.x are out of support, I'm going to close this. By all means, re-open and/or comment if that's the wrong thing to do.
