### ISSUE TITLE
LinuxOne Scheduled Maintenance - scheduled maintenance on December 8-10

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1024]
>You are receiving this email because you have an active registration with the IBM Z Community Cloud.  If you do not have an active Analytics,  Machine Learning or other instances running in the cloud, please feel free to ignore this notice.
>
>We will be performing scheduled maintenance on December 8-10 .  All systems, servers and instances  will be shut down and the cloud will not be available.   The start time for the outage is Friday, 12/08 at 9:00 AM ET.  Estimated time for the cloud to be available again is Monday, 12/11 at 10:00 AM ET .  Any data or programs installed on the server should be safe.   We recommend that you back up anything important to your local computer before the scheduled shutdown.   Thank you for your cooperation.

**Comment by maclover7** [comment]
@mhdawson Can this be closed? Looks like maintenance already happened.

**Comment by mhdawson** [comment]
closing
