### ISSUE TITLE
New OSX infra walkthrough

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1026]
Placeholder issue so that this appears on next meeting agenda

* Walk build team through new OSX infra
* Identify key items to be documented

**Comment by mhdawson** [comment]
@gdams FYI hope you can make it to the meeting to help with the walkthrough

**Comment by mhdawson** [comment]
Done

**Comment by joaocgreis** [comment]
Happened in https://github.com/nodejs/build/issues/1209 . Meeting video: https://youtu.be/mlnbOhGZlRU .
