### ISSUE TITLE
Skip VS2015 build if node version is >= 10

### ISSUE THREAD

**Issue by targos** [nodejs/build#1029]
I'm working on the update to V8 6.4 (should be ready in 6-7 weeks) and only VS2017 is able to compile this version.
You can see the windows test job is already failing with the canary branch: https://ci.nodejs.org/job/node-test-commit-windows-fanned/13987/

Edit: CI with my [6.4 branch](https://github.com/targos/node/commits/v8-6.4): https://ci.nodejs.org/job/node-test-commit/14548/

**Comment by joaocgreis** [comment]
VS2017 release machines have been active for a few days, nightlies of v10 are built with them. I haven't seen issues, I'll move forward with adapting the test CI (this will also unlock https://github.com/nodejs/node/pull/16969).

**Comment by joaocgreis** [comment]
Done, for node >= 10 only VS2017 is used now.

Here is a rebuild of the job mentioned above: https://ci.nodejs.org/job/node-test-commit-windows-fanned/14079/
