### ISSUE TITLE
Versions of OSX to support

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1030]
We now have machines for 10.8 through 10.12.  There was a failure on 10.8 and 10.9 and there was some discussion as to whether we should support 10.8 or 10.9. Opening to discus.

There is always the question as to whether we should use the next machines to test for older releases...

**Comment by gdams** [comment]
10.9 looks pretty good with the test suite right? It's only that single test failure which should be easy enough to fix.

**Comment by mhdawson** [comment]
CI run here.  Single failures on 10.9 (sequential/test-inspector-port-zero).  Compile failure on 10.8 but I think you had mentioned that was something to do with the machine setup.

**Comment by rvagg** [comment]
Apple have got a pretty solid pipeline these days that they push people through for upgrades. Does anyone have a link to credible adoption numbers that we can look at?

**Comment by jsumners** [comment]
Probably the closest thing to credible OS release adoption numbers is going to be https://update.omnigroup.com/. According to that page, 10.8 is basically unused and 10.9 is similarly unused. Another major macOS software developer with trustworthy numbers is https://library.panic.com/general/os-compatibility/ (considering the supported OSes for Transmit 5).

General searching leads to a general consensus that Apple only provides support for the most recent three major versions. Thus, they may only be supporting back to 10.11 at this point. That could be gauged by sorting through the mess at https://support.apple.com/en-us/HT201222.

If a definitive source is needed to say "we no longer support systems older than 10.x" I put forth http://news.fnal.gov/2016/08/mac-os-x-mavericks-v10-9-end-life-dec-1-2016/ . Fermilab is evidently requiring systems on their network to be running at least 10.11.

I would say it's safe to drop support for anything less than macOS 10.11.

**Comment by mhdawson** [comment]
These are good numbers to have. The discussion that has been had in benchmarking meetings was to not include 10.8 and 10.9 in the CI.

**Comment by mhdawson** [comment]
@gdams I don't think we can to a final agreement although I expect everybody likely agrees with:

* Prior to 11.X only build/testing on 10.10 and above. 
* For 11.X and higher only build/test on 10.11 and higher.

We might even get agreement to move up and release prior to 11.x but that would require additional/work testing to make sure we believe all will work as expected. It may also require some additional installs on our 10.11 release machine.

So, to answer the original question I think we should update docs somewhere to reflect the levels that we build/test on (and possibly the supported) levels and then close this after that PR lands.

**Comment by refack** [comment]
Any chance we could turn off the 10.08 an 10.09, and add virtual cores to the 10.11 & 10.latest?
Currently they are running with 2 cores, but there are interesting scheduling issues (probably because it's freeBSD based) maybe more cores will uncover more.

**Comment by mhdawson** [comment]
@gdams not sure how easy it is to add virtual cores.  Can you add that to the list of things we look at when we get together to add 10.13 or 10.14?

**Comment by refack** [comment]
So it's been a year and we didn't add 10.8 & 10.9 to the matrix (or AFAIK even used to manually repro stuff). I move we de-provision them, or at least remove from Jenkins to reduce "machine offline" noise.

**Comment by Trott** [comment]
Seems like this is close-able at this point. By all means, re-open if I'm wrong.
