### ISSUE TITLE
Jenkins lock-down during security release this week

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1031]
@nodejs/collaborators 

You may have seen the security announcement yesterday: https://nodejs.org/en/blog/vulnerability/december-2017-security-releases/

The update will be pretty straightforward but we'd like to lock down Jenkins during this period to avoid leaking sensitive vulnerability information that pertains to Node.js specifically. So, Jenkins will be unavailable to everyone but those in nodejs/security and nodejs/jenkins-admins during the release preparation period.

This window will last from the moment that OpenSSL 1.0.2n is released (Thursday "7th December 2017 between approximately 1300-1700 UTC") to when the final Node.js version is released. We have 4, 6, 8 and 9 to prepare but I expect this to be fairly straightforward and be over by some time on Friday UTC.

Sorry for the inconvenience!

**Comment by gibfahn** [comment]
I'm happy to handle this once releasers are ready

**Comment by rvagg** [comment]
Thanks @gibfahn, I likely be on a plane for the duration anyway.
