### ISSUE TITLE
Access to PPC machine for @jBarz

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1032]
test-osuosl-ubuntu14-ppc64_le-3

It is a new machine I've setup to test out concurrent support for 4.8 and 4.9 compilers as well as the new ansible scripts.  It is not connected to the CI yet, but will be as we get through this work.

John Barboza works at IBM with me and need access to a PPCBE machines in order to help with the work to have concurrent versions of the compilers and switch between them base on which version we are building.

I think he meets the requirements for temporary access in: https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md based on this subset of the criteria:

Length and consistency of involvement with Node.js working groups and/or community.
 * He has contributed the z/OS port for libuv over the last year.

Consequences to the individual in case of mis-bahaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way

* He works at IBM in the Node.js Runtime technologies group. Being banned would
  definitely have an impact

Are there collaborators who work with the individual and can vouch for them.
*  I'll vouch for him

@nodejs/build can I get an approver ?

**Comment by richardlau** [comment]
> ohn Barboza Gireesh

Copy/paste error?

**Comment by mhdawson** [comment]
Fixed

**Comment by Trott** [comment]
No objection from me whatsoever, but it does seem odd to point to a closed issue as the reason to give access...

**Comment by mhdawson** [comment]
Opps , that was a cut and paste issue on my front.  Updating.

**Comment by mhdawson** [comment]
@nodejs/build ping

**Comment by Trott** [comment]
SGTM

**Comment by mhdawson** [comment]
Will catch up with @jbarz this week to get started.

**Comment by seishun** [comment]
@mhdawson Any news?

**Comment by jBarz** [comment]
I have an ansible script working (https://github.com/nodejs/build/pull/1075) need to make some more minor changes. Will attempt to get it done early this week.

**Comment by maclover7** [comment]
Moving this to #1261 where other accesses are tracked
