### ISSUE TITLE
Release requireio ARM6 machines off line

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1033]
Seem to be off line again as of Wed Dec 6 at 10:50 EST.

@rvagg

**Comment by rvagg** [comment]
thanks @mhdawson, disk filled up, it turns out that they don't have nfs mounted, so I'm cleaning it up and remounting and they'll be back online soon

**Comment by rvagg** [comment]
Turns out that that none of them have nfs mounted so the pi's have probably been a little slower than normal, I'm going to have to take them all offline and do some cleanup. This will go back to our power outage last week.

**Comment by rvagg** [comment]
all cleaned up and back online now

@Trott I've brought all the pi's back online that you took offline because I believe the reason for the failures was most likely the lack of nfs. We had a bunch more that were pushed offline due to filled up disks but we're all back now with only 2 missing.

**Comment by Trott** [comment]
@rvagg They're all failing again.  :-(

**Comment by Trott** [comment]
("All" might be an illusion caused by a few working devices being busy building/testing and a few broken hosts failing quickly so failing a whole bunch of things one after the other while the good devices are busy.)
