### ISSUE TITLE
Add a Windows bot to citgm-smoker-nobuild

### ISSUE THREAD

**Issue by targos** [nodejs/build#1035]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/

This is the job used by citgm-smoker-pipeline and I would like to be able to run it on Windows

**Comment by targos** [comment]
@nodejs/build

**Comment by rvagg** [comment]
what's the ask here @targos? is it just to add a Windows machine into Jenkins for it or something more than that?

**Comment by gibfahn** [comment]
I think it's just to modify the citgm job to make it also run on one of the windows labels.

The job itself may well need to be modified to work on windows.

**Comment by targos** [comment]
> I think it's just to modify the citgm job to make it also run on one of the windows labels.

Exactly

**Comment by joaocgreis** [comment]
Done. @targos let me know if there's any issue or I missed something.

Added two labels, to test both VS2015 and 2017 on an old version of Windows (2008) and a new one (10).

**Comment by targos** [comment]
Thank you, that's perfect!
