### ISSUE TITLE
node-test-commit-linux-fips - missing from node-test-commit ?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1038]
Was this removed on purpose ? 

If I don't hear otherwise I'm going to add it back in

@rvagg

**Comment by rvagg** [comment]
it's run as part of https://ci.nodejs.org/job/node-test-commit-linux-linked/ now, it uses the pool of sharedlibs docker containers that are also used for openssl 1.1.0, debug builds and will be used for zlib, c-ares and others.

**Comment by mhdawson** [comment]
Is it possible to have the job be named something other than having 'sharedlibs" in the name as I believe it is not using shared libraries in this case ? 

Maybe 'docker' instead of 'sharedlibs' in the name ?

**Comment by gibfahn** [comment]
The job doesn't have `sharedlibs` in the name does it? It's called `node-test-commit-linux-linked`.

**Comment by mhdawson** [comment]
Look at the subjob -> https://ci.nodejs.org/job/node-test-commit-linux-linked/nodes=ubuntu1604_sharedlibs_fips20_x64/

**Comment by mhdawson** [comment]
So I guess its not the 'job' but the 'node' but the visible naming is what I was thinking was misleading.

**Comment by gibfahn** [comment]
If we call it `node-test-commit-linux-docker`, that suggests to me that it's testing the node docker images, but maybe that's the least bad option, in absence of a better name I'd be fine with that.

Definitely agree that the "sharedlibs" doesn't really make sense as a general name for the fips docker container, unless shared libraries are actually being used.

**Comment by mhdawson** [comment]
maybe 'node-test-commit-linux-variant-using-containers'.  

Its a bit of a mouthful but might be more accurate.

**Comment by rvagg** [comment]
how about node-test-commit-linux-container-variants then? I'm happy either way, although we do have to be a little conscious of length as there are various situations where longer strings can cause problems

**Comment by gibfahn** [comment]
>how about node-test-commit-linux-container-variants then?

I think we can drop the `variants`, not sure that adds any info.

**Comment by rvagg** [comment]
I'd like to find a way to make this not sound like it's about testing containers if we can. Remember that we have Alpine containers in our test-commit-linux mix already.

Does "containered" make any difference?

**Comment by mhdawson** [comment]
node-test-commit-linux-containered would work for me.

**Comment by rvagg** [comment]
https://ci.nodejs.org/job/node-test-commit-linux-containered/1314/ done!

**Comment by mhdawson** [comment]
Thanks looks good.
