### ISSUE TITLE
Centos 5 / 6 not running TAP tests

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#104]
@evanlucas made a good find just now.

These build machines have not been running any tap tests under test-ci:

Centos5-32
Centos5-64
Centos6-64

https://jenkins-iojs.nodesource.com/view/iojs/job/iojs+any-pr+multi/nodes=centos5-32/731/
https://jenkins-iojs.nodesource.com/view/iojs/job/iojs+any-pr+multi/nodes=centos5-64/731/
https://jenkins-iojs.nodesource.com/view/iojs/job/iojs+any-pr+multi/nodes=centos6-64/731/

I looked back and this appears to be the case all the way back to late April when we started using test-ci + tap tests again.

Can we have Jenkins error if no tests were run? this just seems bad.

Centos7-64 however seems ok, it is showing tests run.

@rvagg / @jbergstroem / @nodejs/build

**Comment by jbergstroem** [comment]
Investigating. Looks like the test runner bails:
```
/home/iojs/bin/python tools/test.py -p tap --logfile test.tap --mode=release message parallel sequential
make: *** [test-ci] Error 1
Build step 'Conditional steps (multiple)' marked build as failure
```

The annoying part is that the tap collector seems to pick up an empty tap file and seems happy to. It should not be run at all at that point.

**Comment by jbergstroem** [comment]
`-p tap` just doesn't seem to produce output (but tests are being run successfully). I'll see what I can do.

**Comment by rvagg** [comment]
eek, do we need to do something like `test.py ... || echo "not ok >> test.tap` to make sure the failure bubbles up?

**Comment by jbergstroem** [comment]
@rvagg We can move the tap file creation further down or just remove the file if `test.py` exits abnormally . First I just want to figure out why `logging` behaves differently on the python versions we're running on centos. I'll have a look in an hour.

**Comment by jbergstroem** [comment]
@rvagg actually - as long as we make sure output is written to the tap-file, it should stay regardless so we know what's going on.

**Comment by jbergstroem** [comment]
Fixed with nodejs/io.js@8606793999979829df002c2ab69235a05605fc4d.
