### ISSUE TITLE
Latest blog post not showing on nodejs.org

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1040]
Issue on nodejs.org tracker https://github.com/nodejs/nodejs.org/issues/1516

**Comment by maclover7** [comment]
cc @rvagg

**Comment by rvagg** [comment]
yeah, on it already

**Comment by rvagg** [comment]
Ah, so this was a matter of commits bunching up too close and it refusing to double-process. We don't have a fancy queueing mechanism in place so it just says: _if I'm already processing a commit, don't process another_.

So I've manually processed it on the server, but this could be done by pushing another commit to HEAD _or_ redelivering the github webhook if you have access to them @ https://github.com/nodejs/nodejs.org/settings/hooks (find the last "push" and redeliver it).

Implementing a queue or a retry-wait might be a good task for someone that knows Bash and wants to contribute: https://github.com/nodejs/build/blob/master/setup/www/resources/scripts/build-site.sh

**Comment by MylesBorins** [comment]
@rvagg do you think it would make sense to document that process in the readme in case anyone needs to trouble shoot in the future?
