### ISSUE TITLE
Windows & Linux build systems down

### ISSUE THREAD

**Issue by apapirovski** [nodejs/build#1046]
See https://ci.nodejs.org/job/node-test-commit/14829/, more specifically:

https://ci.nodejs.org/job/node-test-commit-linux/14956/
https://ci.nodejs.org/job/node-test-commit-windows-fanned/14294/

**Comment by apapirovski** [comment]
I take @mhdawson's inquiries in https://github.com/nodejs/build/issues/1045 are related

**Comment by mhdawson** [comment]
We have ~24 windows machines and 11 linux machines at rackspace .....

**Comment by mhdawson** [comment]
Looks like all but our release machines are back.

CI run to validate things look like they are back to normal https://ci.nodejs.org/job/node-test-commit-linux/14958/

**Comment by apapirovski** [comment]
We're still seeing some weirdness with Windows it seems.

**Comment by mhdawson** [comment]
@joaocgreis can you take a look at the windows issues ?

**Comment by joaocgreis** [comment]
A manual run of `git-clean-windows` fixed it. https://ci.nodejs.org/job/node-test-binary-windows/13638/ happened to run right after, validating it.
