### ISSUE TITLE
Both z/OS workers are currently offline

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#1047]
https://ci.nodejs.org/label/zos-s390x/ has no online workers. When Jenkins can't find a worker to run some job and it stays the in build queue for some time, it completely stops executing new jobs (even completely unrelated jobs). This happened now because of a [`libuv-test-commit-zos`](https://ci.nodejs.org/view/All/job/libuv-test-commit-zos/) that was in the queue for 2 days.

I aborted that job and disabled https://ci.nodejs.org/view/All/job/libuv-test-commit-zos/ (disabling a sub-job also makes `libuv-test-commit` not run it). I could not find a way to bring the workers back online.

cc @mhdawson @gibfahn @gdams

**Comment by mhdawson** [comment]
Thanks for the heads up.  Sorry was away on holiday, checking now.

To bring them back online ssh to the machine and then run

sh /u/iojs/start.sh

**Comment by mhdawson** [comment]
They are both back online now.  Just kicking off builds to validate things run/build ok.

**Comment by mhdawson** [comment]
One machine seems ok.  Seeing failure on other one in a test but will deal with that under: https://github.com/libuv/libuv/issues/1692.  Closing this issue/
