### ISSUE TITLE
Unable to create '/home/iojs/build/workspace/node-test-binary-arm/.git/index.lock': File exists.

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1048]
I've seen this a few times in the past days now:
```
+ ps -ef
+ grep '\[node\] <defunct>'
+ awk '{print $2}'
+ xargs -rl kill
+ rm -f ****
+ git checkout -f refs/remotes/jenkins_tmp
fatal: Unable to create '/home/iojs/build/workspace/node-test-binary-arm/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Build step 'Execute shell' marked build as failure
```
https://ci.nodejs.org/job/node-test-binary-arm/12698/RUN_SUBSET=2,label=pi1-raspbian-wheezy/consoleText

**Comment by Trott** [comment]
I'm removing stale .git/index.lock on the Raspberry Pi devices as I find them, but I don't know the cause.

**Comment by Trott** [comment]
@rvagg

**Comment by Trott** [comment]
Also Ref: https://github.com/nodejs/build/issues/951

**Comment by Trott** [comment]
I've removed all the stale `index.lock` files I could find. and CI is heading towards green again. https://ci.nodejs.org/job/node-test-binary-arm/12703/

I'm going to close this as the immediate issue is resolved, but the root cause still needs to be found, and that is being tracked in #951.

**Comment by rvagg** [comment]
Sorry @trott, was asleep at the time this hit. I did restart the nfs server and all of the pi's yesterday so I guess it's related to that, glad it's fixed now.
