### ISSUE TITLE
Raspberry Pi setup TODOs

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#105]
Making a list here of things I need to get to for ansible for RPi, doing each of these manually.

* setup .ssh/config for `iojs-www`, currently missing from automatic setup
* change `/etc/dphys-swapfile` to be 512Mb and setup with `/etc/init.d/dphys-swapfile`
* clone initial bare mirror of io.js.git to `~/git/io.js.reference/`

**Comment by rvagg** [comment]
* `Host key verification failed.` on `iojs-www` .. so prime with a host key??

**Comment by rvagg** [comment]
* Add `id_rsa` for staging

**Comment by Trott** [comment]
This hasn't been updated in over a year, and I *think* these things are all in ansible now. Closing, but feel free to re-open of course if I'm mistaken.
