### ISSUE TITLE
nginx config: Change `/api` route to also support LTS docs?

### ISSUE THREAD

**Issue by fhemberger** [nodejs/build#1051]
Revisiting old nodejs.org website issues, I came across [#309](https://github.com/nodejs/nodejs.org/issues/309).

Do we know how many people access the documentation via `/api`? Currently, this link points to `https://nodejs.org/dist/latest/docs/api/`. Would it make sense to change this behavior?

```
/api -> /api/latest
/api/latest -> https://nodejs.org/dist/latest/docs/api/
/api/lts -> https://nodejs.org/dist/lts/docs/api/
```

The link `/dist/lts` would still be required (for now pointing to `/dist/latest-carbon/`).

That would also make it possible to offer a stable link inside the docs to switch between latest/LTS pages.

**Comment by rvagg** [comment]
fwiw I use https://nodejs.org/docs/ to navigate to the ones I want, it's got all of the helpful links like "latest", "latest-argon", etc.

I don't mind making /api easier as per your proposal, we just don't have "lts" one you're wanting.  If you want you could add it here to make it happen: https://github.com/nodejs/nodejs-latest-linker/, maybe "latest-lts"?

**Comment by fhemberger** [comment]
Sure, I could add it.

On the other hand, maybe we should decide on one canonical URL for the docs and just axe (i.e. redirect) the other ones. Are there any nginx stats about the most common ways to reach the docs?

(maybe we could get rid of the additional `/api` as well, which we just keep because of old 0.x docs)

**Comment by rvagg** [comment]
I don't mind a general cleanup, we should probably document all the ways you can do it and then come up with a clear plan for rationalising it. However, you're going to want to go through older docs dirs and see what's there first and figure out if we need to preserve access to anything.

For instance, in older releases the full website (I think) came with the /docs/ directories, see https://nodejs.org/docs/v0.10.0/ for example. Then it was trimmed down a bit but even by the end of 0.10 and 0.12 we were shipping some extra html in the form of a changelog and some .js stuff files: https://nodejs.org/docs/latest-v0.12.x/ for example.

If we change the way /docs/ works then we have to be comfortable with removing that access to those files. They are still accessible via the binary download directory, e.g. https://nodejs.org/docs/latest-v0.12.x/ is really https://nodejs.org/dist/latest-v0.12.x/docs/, so they're never going to be gone forever (I don't think we should be adding redirects to anything old in /dist / /downloads).

Regarding the common ways to reach them, here's my attempt at figuring that out.

Taking a single day, Dec 1st (no particular reason), I'm using this command to extract the following data: `xzcat nodejs.org-access.log.20171201.1512131101.xz | grep -E 'GET [^ ]+/http\.html HTTP\/1\.1" 200 [^0]' | awk '{gsub(/v[0-9]+\.[0-9]+\.[0-9]+(-(nightly|v8-canary|rc)[^/]+)?/,"VERSION", $7); gsub(/latest-v[0-9.]+\.x/, "latest-MAJOR", $7); gsub(/latest-[a-z]+/, "latest-CODENAME", $7); gsub(/\/download\/(release|nightly|v8-canary|rc)\//, "/download/TYPE/", $7); print $7}' | sort | uniq -c | sort -nr`

Hopefully the capitalised generic substitutions make sense, they're helping distill all of the version variants.

```
   2480 /dist/VERSION/docs/api/http.html
   2359 /api/http.html
   1481 /download/TYPE/VERSION/docs/api/http.html
    722 /dist/latest-MAJOR/docs/api/http.html
    309 /dist/VERSION/docs/doc/api/http.html
    193 /docs/VERSION/api/http.html
    159 /docs/latest-MAJOR/api/http.html
    140 /download/TYPE/VERSION/docs/doc/api/http.html
     75 /docs/latest/api/http.html
     56 /download/docs/VERSION/api/http.html
     48 /download/TYPE/latest-MAJOR/docs/api/http.html
     31 /dist/latest-CODENAME/docs/api/http.html
     25 /dist/latest/docs/api/http.html
     18 /download/TYPE/latest-CODENAME/docs/api/http.html
      9 /dist/latest-MAJOR/docs/doc/api/http.html
      8 /dist/VERSION-isaacs-manual/docs/api/http.html
      6 /download/TYPE/VERSION-isaacs-manual/docs/api/http.html
      6 /download/TYPE/latest/docs/api/http.html
      6 /download/docs/VERSION/doc/api/http.html
      4 /download/TYPE/latest-MAJOR/docs/doc/api/http.html
      2 /docs/VERSION/doc/api/http.html
      1 /download/docs/latest-MAJOR/api/http.html
      1 /docs/latest-CODENAME/api/http.html
```

I'm pretty surprised that /dist/VERSION/docs/api/ is the top ranking one here. So here's the user-agent ranking for that path type:

```
    894 Wget/1.15 (linux-gnu)
    526 Wget/1.17.1 (linux-gnu)
    526 Wget/1.12 (linux-gnu)
    327 Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)
    156 Wget/1.18 (linux-gnu)
     43 Wget/1.13.4 (linux-gnu)
      2 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      1 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
      1 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.89 Chrome/62.0.3202.89 Safari/537.36
      1 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      1 Mozilla/5.0 (Windows; U; MSIE 9.0; WIndows NT 9.0; en-US))
      1 Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
      1 Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```

The bulk of those requests came from just 7 different IP addresses.. And the browser user-agents at the end of that list above suggest that only a trickle of real users are using this route.

Summary for now: _shrug_. I might have to revisit this and remove some of the bot and non-browser user-agents to get higher quality data.

**Comment by fhemberger** [comment]
Wow, that's a looooot of different ways to access the docs. What is `VERSION-isaacs-manual` about?

My 2 cents:
- Get rid of all `/download/*` routes (redirect to `/dist/*` or `/docs/*`).
- Redirect `/docs/doc/api/*` to `/docs/api/*` (avoid duplicate 'doc')
- Redirect `/api/*` to `/dist/latest/*` or `/docs/latest/*` (more comprehensible)
- Redirect `/docs/VERSION/doc/api/*` to `/docs/VERSION/api/*` (avoid duplicate 'doc')

That would reduce entry points to eight (four for each 'dist' and 'docs'), maybe we can even decide on one prefix in a second step.

It would be nice, if we could get rid of the `/api` path segment as well. It's only there for legacy compatibility with 0.x versions. And documents outside of that `/api` path are basically the rest of the website IIRC.

**Comment by rvagg** [comment]
https://nodejs.org/download/release/v0.10.16-isaacs-manual/ is the isaacs-manual one.

My preference would be to shift to `/download/` rather than `/dist/`, we've been pushing that way since we started distributing more than just `release` builds as there's no room in `/dist/` to differentiate. Note the `TYPE` in the list, that includes `nightly`, `v8-canary`, `rc` and a couple of others.

tbh I didn't know that `/api` was being downplayed, I've been using it as a quick shortcut forever.

This seems like something we should pull in a bigger group to discuss, although I'm not sure who!

**Comment by fhemberger** [comment]
Hmm, not sure about `/download` (since you usually don't download the docs but read them online).

/cc @nodejs/tsc @nodejs/website @nodejs/documentation

**Comment by gibfahn** [comment]
I like https://nodejs.org/api/ as the quick link to the latest api docs.

>>My preference would be to shift to /download/ rather than /dist/

>Hmm, not sure about /download (since you usually don't download the docs but read them online).

But people would never actually go to `/download/docs` right? If we had:
- `/api` -> `/docs/release/latest/`
- `/docs/<type>/<version>/` -> `/download/<type>/<version>/docs/`
- `/docs/<version>/` -> `/download/release/<version>/docs/`

Then people would use `nodejs.org/api` for api docs (when they didn't care about the version), and `nodejs.org/docs` to choose a specific set of docs. Then if people wanted to crawl all the artifacts from a release, they'd go to `/download/<version>/` and get everything, including the docs.

I'd like `/download/<type>/<version>/` to contain all the artifacts for all the releases, and not have to understand what `/dist` is 😁 .

Either way it'd be great to reduce some of the duplication in URLs like  https://nodejs.org/docs/v6.9.5/doc/api/

**Comment by fhemberger** [comment]
I think this topic will come up again during the relaunch of the Node.js website. There will be some redirects anyway, so we should take our time to sort this out.

**Comment by lordKnighton** [comment]
ta
