### ISSUE TITLE
Automatic testing and merging of pull requests (+assigning reviewers)

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#106]
I'd very much like for us to adopt http://huonw.github.io/blog/2015/03/rust-infrastructure-can-be-your-infrastructure/ (but with fast-forwards, not merges.  Merges!  Blasphemy!)
 
In a nutshell:

1. [highfive](https://github.com/nrc/highfive) assigns reviewers.
2. Reviewers review and eventually LGTM the pull request.
3. [homu](https://github.com/barosl/homu) runs tests and lint and lands on success.

We'd need a way to add PR-URL and Reviewed-By tags but that's just a Small Matter Of Programming (although it's an open question how to handle multiple LGTMs.)

It would be nice but not crucial when:

1. R= in the description overrides the default reviewers.
2. The lint check fixes up style issues automatically.

I ask because the CI is currently not nearly used enough to my liking and I get bored of amending commits the whole time.

/cc @orangemocha - I believe you have worked on this.

**Comment by jbergstroem** [comment]
Thanks for this. Looks great. In the above workflow I kind of miss having tests being run against a PR before reviewers start crunching their bits. That way, we can pass linting and testing feedback straight to author before reviewers have to point anything out.

**Comment by Qard** [comment]
Perhaps there could be a separate linting process that runs automatically on each new commit to a PR? The final CI step would still do its own linting, but the per-commit ones could just provide some quick feedback.

I would also suggest splitting CI runs from release. We've been avoiding automatic CI just for security, but it would be nice to be able to just do a quick sanity check and send to CI without needing the full review.

Not sure how possible it is, but it'd be cool if you could use some command to tell it to try a release and it'd count LGTMs, check lint, and check CI results since the last commit in the PR. If those checks don't pass, it complains.

**Comment by jbergstroem** [comment]
@Qard automatically running PR's from collaborators/approved users could be a start.

**Comment by jbergstroem** [comment]
Also, homu doesn't seem to support jenkins.

**Comment by orangemocha** [comment]
I have done something similar on jenkins.nodejs.org with node-accept-pullrequest. It does this part:
> homu runs tests and lint and lands on success.

It also automatically rewords all the commit to include the PR url, and the Reviewed-By. The content for Reviewed-By needs to be entered manually on the form. It shouldn't be too difficult to parse the PR comments and recognize the LGTMs (or another syntax we choose).

It doesn't do any of the highfive / assigning reviewers stuff.

**Comment by Fishrock123** [comment]
So, just a thought.. This will choke if the PR has conflicts, right? Sometime's there will be a PR that is valid, and we'll still want to merge, but the author has gone AWOL, what then? Open a new PR?

**Comment by orangemocha** [comment]
If you need to modify the source for the PR to merge cleanly, then yes, you'll need a new PR unless you can push to the original branch.

**Comment by bnoordhuis** [comment]
> Also, homu doesn't seem to support jenkins.

It doesn't but I don't think that's a big obstacle.  It's pretty agnostic when it comes to CI systems, adding Jenkins support shouldn't be difficult.  I'd be happy to do the work on that.

**Comment by mhdawson** [comment]
In relation to the comment by  @jbergstroem giving PR authors the ability to run tests across the platforms, at least in some specific cases,  is likely to be needed.  If the author only has access to a subset of the platforms and the tests fail on one they don't have access to we likely need to give them access to the failing platform to investigate/resolve and once they believe they have resolved confirm tests pass across the core platforms.

**Comment by indutny** [comment]
We may use https://github.com/indutny/caine, and modify it a bit to support LGTM and CI. Should be very easy!

**Comment by wblankenship** [comment]
This sounds fantastic! :+1:

Great suggestion @bnoordhuis

**Comment by brendanashworth** [comment]
I'd like to try and take on the reviewer assigning / highfive / caine, is that okay?

> although it's an open question how to handle multiple LGTMs

As a suggestion, the golang project uses a +1 and +2 system, where +1 = LGTM but needs another sign-off, +2 = LGTM and can land as-is without more review.

**Comment by bnoordhuis** [comment]
@brendanashworth You have my blessing and encouragement.  The +1/+2 approach sounds good to me.

**Comment by jbergstroem** [comment]
sounds like a plan

**Comment by orangemocha** [comment]
@brendanashworth that sounds good. How would that be implemented? FYI, there's also a Jenkins plugin that can be configured to trigger jobs based on comments given in pull request comments: https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by orangemocha** [comment]
We now have [merging of pull requests via CI](https://github.com/nodejs/node/wiki/Merging-pull-requests-with-Jenkins). Not automated though, in the sense that someone needs to trigger the job from Jenkins.

Do we want to keep this issue open? To track triggering the test jobs via comments? Or anything else?

FYI I also logged an idea at https://github.com/nodejs/build/issues/176 to potentially simplify the selection of reviewers based on LGTM.

**Comment by bnoordhuis** [comment]
> To track triggering the test jobs via comments?

That would be a great time saver.  I'm alright with opening a separate, more focused issue for that and closing this one.
