### ISSUE TITLE
Worker machine terminology

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#1060]
Hey everyone again!

Last year, in an effort to remove participation barriers (and because we all agree to make the use of welcoming and inclusive language a goal inside this github org), we replaced all occurrences of  terminology around the word ‘slave’ in the main nodejs/node repository, outside of dependency sources.

I understand that this kind of terminology still pops up kind of frequently around the Build WG in part because of our use of Jenkins; however, from a quick look through their issue tracker it seems like they have moved and/or are moving away from it as well.

So here’s my question: What would be needed make such an effort in this repository? I imagine it’s probably not quite as easy as a simple search + replace and that things such as filenames are expected by some scripts? Are there be any resources that would be helpful to have, besides people’s time?

**Comment by maclover7** [comment]
+1 to changing the language, agree with point about dependency sources. I think the biggest issue is that most Jenkins endpoints used by worker machines contain this terminology (especially the word "slave") in some form (ex: slave.jar, slave-agent.jnlp), so it is a bit unavoidable. If Jenkins updates their endpoints or provides alternate ones, a simple copy/paste should cover almost all uses.

**Comment by gibfahn** [comment]
>Jenkins; however, from a quick look through their issue tracker it seems like they have moved and/or are moving away from it as well.

Looks like `slave.jar` is becoming `agent.jar`, once that's done (and has landed in both our jenkins instances) we can change that.

https://github.com/jenkinsci/jenkins/pull/3004
https://github.com/jenkinsci/windows-slaves-plugin/pull/7

Marking as a `good first issue`, as there are lots of uses in `doc/` (e.g. meeting notes) and doc files elsewhere, which can be changed now by anyone willing to raise a PR.

**Comment by mhdawson** [comment]
+1

**Comment by maclover7** [comment]
Did a little more digging, it looks like `agent.jar` has [landed in Jenkins v2.78](https://jenkins.io/changelog/), and `ci.nodejs.org` is running v2.99, so I think we can update all of our docs to make use of the new endpoint. This would also be a great opportunity to (wink wink nudge nudge) make use of our Ansible scripts, in updating them and then running to do the migration. 🎉 🎉

**Comment by BridgeAR** [comment]
I would also like this to be switched. Is there any status update on this?

**Comment by addaleax** [comment]
@BridgeAR I think it’s mostly waiting for somebody to have the time to do this …

**Comment by maclover7** [comment]
@addaleax @BridgeAR Yep, this is just waiting for someone to PR in the changes, and then to roll it out. For anyone who may want to pick this up, you basically need to run a find and replace swap in `ansible`, changing `slave.jar` to `agent.jar`. Feel free to cc me on any PR

**Comment by juggernaut451** [comment]
@maclover7  working on this
