### ISSUE TITLE
Softlayer emergency maintenance - FYI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1065]
Customer Identification: SoftLayer Internal - Node.js Community Account
Start Date: Friday 05-Jan-2018 06:00 UTC
End Date: Monday 08-Jan-2018 09:30 UTC
Duration: 3 days
Event Type: Planned Event
Subject: Event 53074501 - Emergency Maintenance -- Service Disruption, VSI Reboots Required

=================================================================
/ Event Description /
IBM Cloud Systems Engineers have been notified of a potential security vulnerability affecting all Cloud Hosts. Due to the nature of this vulnerability and the components which are affected, we are not able to mitigate this potential vulnerability via Hot Patching and Cloud Hosts reboots are required. Each maintenance window is scheduled for 90 minutes, with individual Virtual Server Instances (VSIs) completing during the scheduled maintenance window. While we do not foresee any issues with the scheduled reboots, all customers should create a backup of all data on their Virtual Server Instances as a precaution.  

This affects all of our soft-layer machines

=================================================================
The times above are shown in UTC/GMT. Please visit http://www.timeanddate.com/worldclock/converter.html?iso=20180105T0600&p1=0 to convert start time of this event to your local time.

**Comment by richardlau** [comment]
Duplicate of https://github.com/nodejs/build/issues/1062?

**Comment by mhdawson** [comment]
Seems like it, should have looked first.
