### ISSUE TITLE
Don't test ppcbe for node >7

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1068]
Should we stop running CI for Node > 7.x? We have this code in our release job:

```bash
if [[ $ARCH == ppc64 && ${NODE_MAJOR_VERSION} -gt 7 ]]; then
  echo "Not building $disttype on PPC Big Endian slave $NODE_NAME as not supported for v8.x and later"
  exit 0
fi
```

**Comment by gibfahn** [comment]
@mhdawson if we already discussed this somewhere else and I forgot let me know.

**Comment by mhdawson** [comment]
I've been doing it in stages without a rush.

1) remove from main download page wait to see if we get any complaints
2) remove generation of builds in releases, wait to see if we get any complaints..

next is remove from testing for >= 8  (not >- 7.x as you say above).  I'm in no rush, but we probably have had enough time pass that stopping testing for >=8 is ok.

**Comment by gibfahn** [comment]
>not >- 7.x as you say above

Edited.

**Comment by maclover7** [comment]
@gibfahn @mhdawson Has node-test-commit been updated with these changes?

**Comment by mhdawson** [comment]
Yes this is done closing.
