### ISSUE TITLE
Jenkins backups

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1071]
How do we currently back up our Jenkins configs? I assume/hope they go somewhere, but wanted to check, as backing up our XML files is a prerequisite of culling pre-V4 jobs (https://github.com/nodejs/build/issues/926).

**Comment by gibfahn** [comment]
Internally we use a backup plugin, but I don't entirely trust it, so I just manually push changes to a private git repo every now and again (obviously having a good `.gitignore` is crucial for that).

**Comment by gdams** [comment]
I've used https://wiki.jenkins.io/display/JENKINS/thinBackup with no issues before. It looks like it's what we use internally but I've been using it on both ci's at AdoptOpenJDK with no issues so far.

**Comment by gibfahn** [comment]
Yeah we use that internally, but it looks like it failed for a few months without anyone noticing.

**Comment by maclover7** [comment]
Obviously with pipelines this is moot, but I like the idea of saving XML dumps of jobs (in `nodejs/build`) in the meantime.

**Comment by gibfahn** [comment]
>Obviously with pipelines this is moot, but I like the idea of saving XML dumps of jobs (in nodejs/build) in the meantime.

Saving the xml files makes sense, the blocker for that is that someone has to go through them to make sure there's nothing there we wouldn't want to publicize.

Having said that, maybe the easy answer is to save all the xml files to build-private, that way we don't have to worry about exposing something. I feel like anything that requires manual effort on a large scale is going to stall.

**Comment by maclover7** [comment]
👍 to build-private, just easier for now

**Comment by rvagg** [comment]
Yes, they are backed up off-server. @gibfahn log in to infra-joyent-smartos15-x64-1 and have a poke around. Crontab is @ /var/spool/cron/crontabs/root, rsnapshot config is /opt/local/etc/rsnapshot.conf, there's a script @ /root/backup_scripts/remove_old.sh that does the old-job pruning. Feel free to tweak or propose changes.
