### ISSUE TITLE
Access to OSX 10.8 machine for @anisha-rohra

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1077]
Anisha works at IBM with me and need access to an OSX 10.8 machine in order to to investigate an issue reported on the N-API sqlite port

Of note we are not planning to add OSX 10.8 machines to the CI but we had created some in advance of making that decision. Having them around to investigate issues may still make sense.

I thinks he meets the requirements for temporary access in: https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md based on this subset of the criteria:

* Length and consistency of involvement with Node.js working groups and/or community.
  * She has been helping with the N-API work, participating in meetings for over 4 months.

* Consequences to the individual in case of mis-bahaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way

  * She works at IBM in the Node.js Runtime technologies group. Being banned would
    definitely have an impact

* Are there collaborators who work with the individual and can vouch for them.

    * I'll vouch for her

@nodejs/build can I get an approver ?

**Comment by gibfahn** [comment]
SGTM

**Comment by joaocgreis** [comment]
I approve

**Comment by mhdawson** [comment]
Added Anisha's key to test-macstadium-macos10.08-x64-1

**Comment by maclover7** [comment]
@mhdawson @anisha-rohra Is machine access still needed?

**Comment by mhdawson** [comment]
I think we can remove this now. Key removed.
