### ISSUE TITLE
Ongoing access to z/OS machines for @jbarz

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1081]
It would be helpful if @jbarz could have ongoing access to the z/OS machines.  I need some help in maintaining them etc and he is the most knowledgeable team member available.

John Barboza works at IBM.  I think he meets the requirements for temporary access as defined in: https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md based on this subset of the criteria:

Length and consistency of involvement with Node.js working groups and/or community.

He has contributed the z/OS port for libuv over the last year.
Consequences to the individual in case of mis-behaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer? Would being banned from involvement in the Node.js community negatively affect them personally in some other way

He works at IBM in the Node.js Runtime technologies group. Being banned would
definitely have an impact
Are there collaborators who work with the individual and can vouch for them.

I'll vouch for him
@nodejs/build can I get an approver?

**Comment by joaocgreis** [comment]
I approve.

**Comment by gibfahn** [comment]
SGTM

**Comment by gdams** [comment]
I approve

**Comment by maclover7** [comment]
SGTM

**Comment by jBarz** [comment]
Could someone give me access to the machine? (148.100.36.133)
Libuv tests are failing due to timeout so I need to investigate that.
Let me know if i should provide my public key

**Comment by mhdawson** [comment]
Added key for @jBarz to test-marist-zos13-s390x-1 and test-marist-zos13-s390x-2

**Comment by maclover7** [comment]
Moving this to #1261 where other accesses are tracked
