### ISSUE TITLE
Clarify email aliases (e.g. build@iojs.org)

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1084]
See https://github.com/nodejs/build/issues/1045#issuecomment-351834441

`build@iojs.org` , `accounts@iojs.org`, and `admin@iojs.org` all point to the same group, which I guess is the infra team.

We could do with an alias for the whole build team, and `build@iojs.org` would make sense for that (not sure what it's currently used for other than the rackspace account).

I'll raise a PR to document that infra admins should PR themselves to those lists.

https://github.com/nodejs/email/blob/master/iojs.org/aliases.json#L76-L80

**Comment by maclover7** [comment]
Tagging this `build-agenda` so we can see if this can be resolved during next meeting

**Comment by mhdawson** [comment]
Rod is going to PR comments into the email alias file to doc how they are used.

Gibson is going to PR doc on how people should be added.

**Comment by rvagg** [comment]
https://github.com/nodejs/email/pull/87
