### ISSUE TITLE
Minimum libc and compiler for Node 10 implications for support platforms

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1087]
We need to resolve this or we're likely going to lock ourselves into deep pain for Node 10 https://github.com/nodejs/node/pull/14901#issuecomment-358628034

> For Node 10 we're going to need to make a call on this which will probably mean decisively cutting off Wheezy, Ubuntu 12.04 and possibly even RHEL 6 which is the same era but is supposed to be supported till the end of 2020 (and 2024 in extended!). So that's fun .. It'd be nice if we could slow down on this compiler creep though.

**Comment by targos** [comment]
See https://github.com/nodejs/build/issues/945#issuecomment-357684125

I think it's important that the minimum compiler for Node 10 fully supports C++14.

/cc @fhinkel

**Comment by bnoordhuis** [comment]
We can basically pick whatever we think is needed.  Worst case, we build clang++ from source and use that on the old machines.  Handwave-y summary:

1. Build statically linked clang.
2. Tar up with devel headers.
3. Copy over and extract.

libstdc++ might become an issue but we can start statically linking against libc++ if needed.

**Comment by sam-github** [comment]
Seems  long out of date, 10.x is LTS.
