### ISSUE TITLE
citgm-smoker failing on Windows

### ISSUE THREAD

**Issue by targos** [nodejs/build#1091]
See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1226/nodes=win-vs2015/console

The error is:
```
c:\workspace\citgm-smoker\nodes\win-vs2015\node>call vcbuild release nosign x64 
Note: vcbuild no longer signs by default. "nosign" is redundant.
Looking for Visual Studio 2017
could not find "vswhere"
Failed to find a suitable Visual Studio installation.
Try to run in a "Developer Command Prompt" or consult
https://github.com/nodejs/node/blob/master/BUILDING.md#windows-1
```

**Comment by sethbrenith** [comment]
Looks like it's still trying to use VS 2015, but support for that was [removed](https://github.com/nodejs/node/commit/b13233aa39d54262d5b38c4d8a23450a040be2b3).

**Comment by gibfahn** [comment]
So it's running on win-vs2015, with a version of Node that doesn't work with VS2015. Sounds like we need to set the labels to only run on vs2017 machines on master.

**Comment by joaocgreis** [comment]
Added a VS2017 worker and some lines to the Windows script to use VS2015 up to v9 and VS2017 for v10. Please reopen if there's any issue with it.
