### ISSUE TITLE
node-chakracore nightly builds failing due to lack of vs2017

### ISSUE THREAD

**Issue by MSLaguana** [nodejs/build#1092]
For the past few days the node-chakracore windows nightly builds have been failing because they use VS2015 machines, while node now requires VS2017.

**Comment by joaocgreis** [comment]
Update the release script and added support to compile for ARM to all VS2017 machines. With this, node-chakracore should be able to support the same Windows and VS versions as node-v8 for all versions, let me know if you notice any discrepancies. Thanks!
