### ISSUE TITLE
ubuntu1604-arm64_odroid_c2 consistently failing

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1093]
should we disable?

**Comment by mhdawson** [comment]
@rvagg which arm levels does this give us coverage for ?

**Comment by MylesBorins** [comment]
ping on this. I think we should disable... still getting consistent failures and red CI

**Comment by Trott** [comment]
@MylesBorins I took the host offline a few minutes ago. Hopefully someone will fix it. In the meantime, you shouldn't be getting red anymore.

**Comment by Trott** [comment]
For anyone who can/wants to fix it, it looks like the problem is that the filesystem with the `.git` directory is read-only.

**Comment by Trott** [comment]
(I am unfortunately unable to SSH into the machine myself. Not sure what the issue is. Perhaps I need to update my secrets or something.)

**Comment by mhdawson** [comment]
It is strange I can ssh into the '-1', and  '-2' while '-3' the one with the problem asks me for a password.

ping @rvagg

**Comment by MylesBorins** [comment]
Now seeing failures on master with openssl not building

https://ci.nodejs.org/job/node-test-commit-arm/13642/nodes=ubuntu1604-arm64_odroid_c2/console

**Comment by Trott** [comment]
22 consecutive failures over the last 2 days. Taking it offline.

**Comment by mhdawson** [comment]
Issue in Node repo for compile failure, I was thinking it would be a separate issue but not sure. https://github.com/nodejs/node/issues/18584

**Comment by rvagg** [comment]
@mhdawson re password, re-run your ansible ssh config setup, that particular one uses a newer image and defaults to user `ubuntu` while the others are simply `root`.

I've taken the C2's out of circulation for now, as discussed in this week's meeting, too much grief and I'm so sick of fixing them up, it's become a weekly (at least) chore.
