### ISSUE TITLE
nodejs-ci cannot push to node-v8

### ISSUE THREAD

**Issue by targos** [nodejs/build#1102]
I suspect this is because of the recent 2FA enforcement.
The nightly canary update is pushed by the [nodejs-ci](https://github.com/nodejs-ci) user and has been failing in the last couple of days ([example](https://ci.nodejs.org/view/MyJobs/job/node-update-v8-canary/337/console)).
To fix this, I invited nodejs-ci as an external collaborator to node-v8. Could someone please login with this user and accept the invitation?

/cc @nodejs/build

**Comment by rvagg** [comment]
@joaocgreis I think this one is on you. See https://github.com/nodejs/build/issues/943 for some background. I set up 2fa for the node-forward-build github account already and put the creds, 2fa seed and recovery codes into secrets/infra/node-forward-build_github_account.md. Could you do the same for the node-ci user please? I don't have password for it (at least I don't think I do) so can't do it.

**Comment by mhdawson** [comment]
@joaocgreis while you are at it I assume you should probably add the password to the secrets repo.

**Comment by joaocgreis** [comment]
Enabled 2fa for @nodejs-ci (key and codes added to secrets) and accepted the invitation to node-v8.

V8 canary updated successfully: https://ci.nodejs.org/view/All/job/node-update-v8-canary/339/

The details for @nodejs-ci live in `secrets/build/infra/ci-iojs-org*` (GH details +pub/priv keys associated with the email).
