### ISSUE TITLE
Using SCLs on CentOS6 machines

### ISSUE THREAD

**Issue by kasicka** [nodejs/build#1104]
Is there any reason why SCLs used on CentOS 6 are not installed from official repositories?

**Comment by maclover7** [comment]
@kasicka Hi! For reference, can you point out which lines in our Ansible playbooks you are speaking to?

**Comment by kasicka** [comment]
Got confused by [this](https://github.com/nodejs/build/blob/master/ansible/roles/baselayout/tasks/partials/repo/centos6.yml) and [this](https://github.com/nodejs/build/pull/1076/files#diff-3f609b44710f4842b29acb45ea1a2952) while there is official repo in the [playbook](https://github.com/nodejs/build/blob/f6f19abe31fa514b18064de2cad7e458b506e192/setup/centos6/ansible-playbook.yaml)

**Comment by sam-github** [comment]
Closing as stale, ping if I misunderstand.
