### ISSUE TITLE
IOJS release has over 4k jobs in the queue

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1109]
down to 2.5k right now with some manual killing

there is a plugin to flush the entire queue

**Comment by maclover7** [comment]
cc @nodejs/jenkins-admins

**Comment by maclover7** [comment]
ping @MylesBorins -- is this still an issue?

**Comment by MylesBorins** [comment]
Nope, was more of an FYI. Not sure if there is still any research to do on
why this happened

**Comment by maclover7** [comment]
Ok, no problem -- going to close for now since there doesn't seem to be any further actions steps.
