### ISSUE TITLE
node-test-commit-linux-containered failing with wrong openssl version

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1115]
https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_openssl102_x64/2191/
https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_openssl102_x64/2189/
https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_openssl102_x64/2188/

```
17:10:51 + OPENSSL_VERSION='  openssl: '\''1.0.2n'\'','
17:10:51 + echo 'OpenSSL Version:   openssl: '\''1.0.2n'\'','
17:10:51 OpenSSL Version:   openssl: '1.0.2n',
17:10:51 ++ echo openssl: ''\''1.0.2n'\'','
17:10:51 ++ grep 1.0.2m
17:10:51 + '[' X = X ']'
17:10:51 + FAIL_MSG='Not built with OpenSSL 1.0.2m, exiting'
17:10:51 + echo Not built with OpenSSL 1.0.2m, exiting
17:10:51 Not built with OpenSSL 1.0.2m, exiting
17:10:51 + echo 1..1
17:10:51 + echo 'not ok 1 Not built with OpenSSL 1.0.2m, exiting'
```

Is there more than one worker for this job? Does one have an old config?

**Comment by maclover7** [comment]
cc @rvagg, maybe something got messed up with rolling out #1052?

**Comment by rvagg** [comment]
Yeah, I think I fixed that while your particular job was running and it shouldn't be a problem anymore. I did have two lots of those machines running 1.0.2n and another lot running 1.0.2m. In the end I just made it check for 1.0.2 so we don't have to remember to update Jenkins when we upgrade the containers.
