### ISSUE TITLE
canary test job disappeared

### ISSUE THREAD

**Issue by targos** [nodejs/build#1116]
[`node-test-commit-node-v8`](https://ci.nodejs.org/job/node-test-commit-node-v8/) is no more :(
It is supposed to be triggered daily by [`node-update-v8-canary`](https://ci.nodejs.org/job/node-update-v8-canary/).

**Comment by gibfahn** [comment]
Someone with admin access can check the [deleted job history](https://ci.nodejs.org/jobConfigHistory/?filter=deleted) (it's not loading for me, ci seems to be having issues).

**Comment by gibfahn** [comment]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/15943089/36141530-f3db6462-109c-11e8-9e1f-ff4e188687bc.png">


@rvagg was this intentional? I'm going to assume not and restore, but I know you were doing maintenance on the jobs yesterday.

**Comment by gibfahn** [comment]
I've restored the job but left it disabled, I don't want to bring it back in case it was causing issues.

**Comment by rvagg** [comment]
oh .. I deleted the fips job tied to the v8 one as it's redundant now so I guess I somehow did this one as well? so sorry everyone.
