### ISSUE TITLE
FYI - LinuxOne machine updates - Sunday Feb 25

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1119]
LinuxONE Community Project Cloud users,

As communicated to you in November 2017, we are rolling out a process to regularly apply critical maintenance updates from each Linux distributor to your servers,   Next on the schedule will be to upgrade all servers to the latest supported Linux release, eliminating older releases that have gone out of service.  A scheduled maintenance window is planned for **Sunday, February 25, 20:00-22:00** ET. Your servers will be rebooted. Please backup any important work or data as needed, 

Upon completion, the following Linux images will be supported until the release reaches End of Service: 

RHEL 6.7 -> RHEL 6.9  
RHEL 7.2 -> RHEL 7.4
SLES 11 SP4 
SLES 12 SP1 -> SLES 12 SP3
Ubuntu 16.04 LTS

**Comment by maclover7** [comment]
Feb 25 is in the past now, so going to close this out.
