### ISSUE TITLE
Artifacts in staging

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1123]
There's a ton of artifacts in staging, 80 in total (including a few win-* directories), 22 of them don't have equivalent files in dist. Below are those files and they may need to be promoted by the releaser of these versions. I don't have time right now to cross-reference who the releasers were so if someone else could do that I would greatly appreciate it! If you see any of yours in here can you please make a judgement call about promotion. Remember that you'll need to update the shasums content in the release blog post for that version as well. 

v4.2.2/node-v4.2.2-linux-ppc64le.tar.gz
v4.2.2/node-v4.2.2-linux-ppc64le.tar.xz
v4.2.2/node-v4.2.2-linux-ppc64.tar.gz
v4.2.2/node-v4.2.2-linux-ppc64.tar.xz
v4.3.0/node-v4.3.0-linux-ppc64le.tar.gz
v4.3.0/node-v4.3.0-linux-ppc64le.tar.xz
v4.3.0/node-v4.3.0-linux-ppc64.tar.gz
v4.3.0/node-v4.3.0-linux-ppc64.tar.xz
v4.3.1/node-v4.3.1-linux-ppc64le.tar.gz
v4.3.1/node-v4.3.1-linux-ppc64le.tar.xz
v5.0.0/node-v5.0.0-linux-ppc64le.tar.gz
v5.0.0/node-v5.0.0-linux-ppc64le.tar.xz
v5.0.0/node-v5.0.0-linux-ppc64.tar.gz
v5.0.0/node-v5.0.0-linux-ppc64.tar.xz
v5.6.0/node-v5.6.0-linux-ppc64le.tar.gz
v5.6.0/node-v5.6.0-linux-ppc64le.tar.xz
v5.8.1/node-v5.8.1-linux-ppc64le.tar.gz
v5.8.1/node-v5.8.1-linux-ppc64le.tar.xz
v5.8.1/node-v5.8.1-linux-x64.tar.gz
v5.8.1/node-v5.8.1-linux-x64.tar.xz
v6.5.0/node-v6.5.0-linux-s390x.tar.gz
v6.5.0/node-v6.5.0-linux-s390x.tar.xz

**Comment by rvagg** [comment]
mean to ping @nodejs/release ^ please check above for your versions and publish artifacts that you should and let me know what isn't going to be published so we can clean up.

**Comment by maclover7** [comment]
Per nodejs/nodejs.org blog posts:

@jasnell released v4.2.2, 4.3.0, v5.6.0
@MylesBorins released v4.3.1
@rvagg released v5.0.0
@evanlucas released v6.5.0

Please check in about the files for your release and see if files need to be promoted. Would be great to clean out these files.

cc @nodejs/release

**Comment by rvagg** [comment]
The only files remaining in there now are for node-v9.6.0-linux-armv6l and they are missing from the v9.6.0 release. @MylesBorins would you mind running tools/release.sh and getting them out, followed by a nodejs.org blog post update?

**Comment by MylesBorins** [comment]
done
