### ISSUE TITLE
node-test-commit-osx "No space left on device"

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1124]
Mac OSX build is crashing:

```
stderr: error: could not lock config file .git/config: No space left on device
```

 Disk space problems on OSX have been reported before (#899 and #953). Not sure if related or not though.

Related CI run: https://ci.nodejs.org/job/node-test-pull-request/13184/

**Comment by mhdawson** [comment]
Looks like it ran on test-macstadium-macos10.10-x64-1

Space looks ok:

adminisorsMac10:~ iojs$ df -k
Filesystem    1024-blocks     Used Available Capacity iused      ifree %iused  Mounted on
/dev/disk0s2     51589192 15240276  36092916    30%  525881 4294441398    0%   /
devfs                 175      175         0   100%     608          0  100%   /dev
map -hosts              0        0         0   100%       0          0  100%   /net
map auto_home           0        0         0   100%       0          0  100%   /home

Looking for the git file, I see that the worspace no longer exists so I'm guessing somebody deleted the workspaces. 

I don't think there is any data left to look at so we'll need to wait until the next time to investigate.

**Comment by mhdawson** [comment]
Still seems to be failing, strange : https://ci.nodejs.org/job/node-test-commit-osx/16340/nodes=osx1010/console

**Comment by mhdawson** [comment]
It does not look like the workspace is being created

**Comment by mhdawson** [comment]
Cloning manually seems to be just fine so no reason why io.js user cannot clone from the node repo/and or write to the disk.  Going to try rebooting.

**Comment by mhdawson** [comment]
Seems I was on the wrong machine :(
I cleaned the workspace and now it seems to be ok

**Comment by mhdawson** [comment]
Disk on the correct machine is much more filled up and has a lot more workspaces:

administorsMac3:workspace iojs$ ls
chakracore-test-osx		citgm-smoker			node-stress-single-test		node-test-node-addon-api
citgm-abi-smoker		citgm-smoker-nobuild		node-test-commit-osx		run-script-on-all
citgm-continuous-integration	libuv-test-commit-osx		node-test-commit-osx-macstadium

**Comment by mhdawson** [comment]
removed one workspace that we don't need to help free up a bit of space, but we may need to see if we need more space in general on the macos machines.

**Comment by maclover7** [comment]
_Seems_ like coast is clear, going to close this for now. Please reopen if I'm mistaken.
