### ISSUE TITLE
Containerize our infra

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1130]
Currently we have lots of long living VMs for our CI workers... they can get weird over time. There are also security concerns related to these environments not being fresh on each run. For example a recent vulnerability in an npm repo could have resulted in our infra mining crypto currency, afaik it didn't, but the risk is there.

I'd like to propose that we explore replacing some of our infra with a container based approach, which could give us fresh environment for each run, and kill any potentially rogue processes before they spread.

I'm going to check internally to see if there are resources google can offer (both human + technological) and will check back

**Comment by maclover7** [comment]
SGTM. I am focusing all of my time/contributions right now on being able to standup all of our machines with the same ansible playbook, so that we can hopefully get to being able to run containers.
