### ISSUE TITLE
Raspbian running forever

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1135]
Seems like something went wrong here: https://ci.nodejs.org/job/node-test-binary-arm/13674/

There is nothing indicating any problems but at some point every process stopped working and did not report back at all anymore.

**Comment by maclover7** [comment]
Build queue currently at 310 jobs, almost all waiting for raspbian, remedying...

**Comment by maclover7** [comment]
Cleared out job queue, loads of Pi jobs somehow got stalled up. Going to leave this open to try and document what went wrong. @rvagg, would you be able to help look into this?

**Comment by Trott** [comment]
I'm still unable to start a new `node-stress-single-test-pi1-fanned` job. Hopefully @rvagg has the answer and hopefully it's not something that only he can do. :-D

**Comment by Trott** [comment]
Thanks, @rvagg! Just to confirm, I can now start `node-stress-single-test-pi1-fanned` jobs again.

(There's nothing to be done about it remotely when it comes up other than to ping you?)

**Comment by Trott** [comment]
(I guess the thing that can be done about it is to reboot the machine that hosts nfs? I suppose that can be done remotely.)

**Comment by rvagg** [comment]
@trott no, can't even do that, it locks up and you need to physically force a reboot and even then it's hard to get it back online with multiple reboots required .. anyway, I've successfully moved over nfs to a new host that I'm working on, all except for one pi that you're doing a stress test on. This new machine should be much more stable. Will hopefully have it fully replaced in the next few days.

**Comment by rvagg** [comment]
all looking good .. I have two Pi1's taken offline that need a full hardware check and SD card r/w test and reprovision. The other machines that were offline have been "cleaned" and a couple of parallel builds that exercised the whole cluster showed up all green so we're good for now. My comfort level in this new nfs server is significantly higher.

**Comment by Trott** [comment]
Thanks, @rvagg! FWIW, my stress test has finished.
