### ISSUE TITLE
Missing rackspace Ubuntu 12.04

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1139]
I can't work this out, [test-rackspace-ubuntu12-x64-1](https://ci.nodejs.org/computer/test-rackspace-ubuntu12-x64-1) has been offline for 2 days now (there are builds older than 2 days so it has been in use) but I can't find it in my Ansible config and I can't find it in Rackspace admin portal either! We have [test-rackspace-ubuntu1204-x64-1/](https://ci.nodejs.org/computer/test-rackspace-ubuntu1204-x64-1/) and it's online and in Ansible config as `ubuntu1204_clang341-x64-1` and it's online and running and in the Rackspace portal.

Now, I recall doing some renaming a while back, related to ubuntu12 -> ubuntu1204, but that was a few months ago and it's only now that I've been seeing this host missing.

Has anyone done anything with ubuntu12 hosts in Jenkins or Rackspace recently? @nodejs/jenkins-admins 

If not, I guess we'll write this off as a strange config mixup due to my renaming.

**Comment by maclover7** [comment]
That was me -- I renamed `ubuntu12` to `ubuntu1204` so the Ansible scripts would work properly

**Comment by maclover7** [comment]
I believe I updated the inventory to remove the `clang` part

**Comment by rvagg** [comment]
ok, fine by me, if you have access can you remove the old node in Jenkins so it doesn't show up now?

**Comment by maclover7** [comment]
No problem, done.
