### ISSUE TITLE
Build for musl libc

### ISSUE THREAD

**Issue by asottile** [nodejs/build#1140]
Copying from https://github.com/nodejs/nodejs.org/issues/1569#issuecomment-367026204

-----

The current binaries provided at http://nodejs.org/dist/v9.5.0/ are all `glibc` binaries and do not function inside `alpine` docker containers.  Executing the binary after extraction leads to:

```console
# ./node --version
sh: ./node: not found
```

Here's the specific operating system in question:

```
$ docker run -ti py:2.7.14-alpine3.7 sh -xc 'uname -a && cat /etc/os-release'
+ uname -a
Linux 6913c996248d 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 Linux
+ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

-----

While the `node:x.x-alpine` images are nice, they don't satisfy all the usecases I'd like these to handle:

- using _some other_ alpine docker image (in this specific instance, I'd like to use the `python` alpine images)
- using some other platform which also uses muslc and is neither docker nor alpine (gentoo musl for instance)

-----

My actual usecase is with `nodeenv`, the rabbit hole so far:
- https://github.com/nodejs/nodejs.org/issues/1569
- https://github.com/ekalinin/nodeenv/issues/204
- https://github.com/pre-commit/mirrors-jshint/issues/4

**Comment by rvagg** [comment]
fwiw this has been discussed a few times before, see https://github.com/nodejs/build/search?q=musl&type=Issues

I'm not entirely opposed to this but there is a potential permutation explosion problem here, do we need musl x64 _and_ x86? What about musl on ARM, I bet that's a thing that people are using. Does that mean we're stuck with shipping 10 (whatever) more files in each of our release directories? How do we keep that at a minimum so as not to saddle ourselves with the maintenance burden.

Perhaps you should just do a compile from source in your container builds? It's really not that complicated and shouldn't be too hard to remove the build dependencies after it's done. Maybe that's something we can help with providing instructions or examples for.

**Comment by asottile** [comment]
x64 is probably sufficient, x86 would be a nice to have.  I'm not sure arm would be necessary (maybe the first push of this doesn't need arm?)

I could already compile from source, but that takes ~30 minutes.  Most of the goal of nodeenv is to avoid needing to maintain build infrastructure due to being able to leverage prebuilt packages -- it already works great for other linux / windows / mac clients due to the binaries provided for them :)

**Comment by rvagg** [comment]
> x64 is probably sufficient, x86 would be a nice to have. I'm not sure arm would be necessary

That's you, but this really is a slippery slope problem, you may be fine with x64 but if we go out with only that then it's not a hard argument to make to expand it to all of the rest of these platforms. There's a limit to our infrastructure, the time we're willing to let release builds take (if we double-up our infra to make this work) and our ability to keep our infra maintained. This is a non-trivial addition and it's easy to see it expanding.

**Comment by asottile** [comment]
Ah yes of course, understood.  I'm not familiar with your current setup so I don't know the costs associated with scaling -- does it utilize resources such as travis or are there custom build servers?

**Comment by piranna** [comment]
If it's useful or of your interest, at https://github.com/NodeOS/nodejs I have automated builds of Node.js using musl for x86, x64 and arm. The scripts check each night if there was a new stable version and compile, pack and publish them both on [npm](https://www.npmjs.com/package/nodeos-nodejs) and as Github. I'm using them to don't need to compile Node.js each time I do a new release of [NodeOS](http://node-os.com/).

**Comment by SimenB** [comment]
The build time of the alpine images has been mentioned as what takes the most time when getting security updates out for the docker images (beyond getting humans to merge PRs), see https://github.com/nodejs/security-wg/issues/168#issuecomment-385080200.

The list of arches for docker images and alpine is somewhat extensive (https://github.com/nodejs/docker-node/blob/master/architectures), but every prebuilt binary helps.

**Comment by richardlau** [comment]
x64 musl binaries are now built unofficially and distributed on https://unofficial-builds.nodejs.org/.
