### ISSUE TITLE
Jenkins build pruning strategy

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1143]
I have a theory that the way we currently prune Jenkins builds is causing problems with our Jenkins queue and it's getting increasingly frustrating for users. For example, yesterday @Trott submitted a bunch of node-stress-single-test-pi1-fanned jobs and none of them showed up on the [node-stress-single-test-pi1-fanned page](https://ci.nodejs.org/view/All/job/node-stress-single-test-pi1-fanned/) but they _did_ show up in the job queue list on the left side of the Dashboard if you scroll down to see what's currently running. On top of that, when you clicked through to the build page for each of the running ones only the first 3 showed up with the rest doing a 404, yet they were still running and ended up showing up today when you used direct URLs but nof via the node-stress-single-test-pi1-fanned page. However, when I restarted Jenkins fully just now everything showed up properly as it should.

This invisible queue problem keeps on happening and is terrible for users during high load and often ends up with users submitting multiple builds with the same parameters because it looks like their request has been ignored--it's just secretly running in the background somewhere.

So, my theory is that it could be to do with how we're pruning old builds. We instituted this strategy a while back because we noticed that having a long history of builds really slowed Jenkins down because it has to load all of the XML (and our XML contains lots of garbage logs so are massive). We were also having space problems on the Jenkins master. The space problems have been fixed by using the 3 jenkins-workspace machines to _run_ the jobs while the master really is just coordinator and holder of configuration.

We have this script on our backup machine that runs every day:

```
HOST=$1
DAYS=7
ROOTDIR=/var/lib/jenkins/jobs
REGEX="${ROOTDIR}/.*/builds/[0-9]+"
CREDENTIALS=$(</root/.jenkins_credentials)
ssh -i /root/.ssh/nodejs_build_backup $HOST find "$ROOTDIR" -depth -type d -regex "$REGEX" -mtime +$DAYS -exec "rm -rf '{}' \;"
JENKINS_CRUMB=$(curl -sL --user "$CREDENTIALS" https://$HOST/'crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
curl -X POST -q --user "$CREDENTIALS" -H "$JENKINS_CRUMB" https://$HOST/reload
```

i.e. it uses `find` to remove build directories that are older than 7 days, _then_ it tells Jenkins, via its API, to perform a "reload". To the user of Jenkins this looks like a restart, with the plain page that shows "Jenkins is restarting..." but I'm pretty sure it's just a file reload.

I think that process is flawed and Jenkins doesn't handle the reload properly and this may be the cause of some of our build ghosting.

So, there's an alternative--use Jenkins' built-in pruning mechanism:

![screenshot from 2018-02-23 11-41-39](https://user-images.githubusercontent.com/495647/36572415-cb0caa1e-188f-11e8-9130-b2d2c4adebf0.png)

Unfortunately this is set on a per-job basis, so we'd have to go through every job and set this up. On the other hand, that's not such a bad thing because we really only _need_ this on the frequently run jobs and we have a bunch of jobs that are hardly ever run.

I don't have any experience with this mechanism and I can't recall the history of why we set up our cleaning routine the way we did. @jbergstroem may be able to help with some context.

Any thoughts?

**Comment by rvagg** [comment]
A thought: we could test my theory by changing our build-pruning to be weekly rather than daily and see if anything changes. Perhaps ~4am UTC on a weekend (low-use time). Any objections to at least trying that?

**Comment by rvagg** [comment]
For now I've just shifted the pruning to follow the weekly rsnapshot run instead of the daily. That means it'll go just before midnight UTC on Saturdays. I'll try and restart Jenkins when I see it free next so we get as much of this week without the prune running as we can and see how it goes.

**Comment by rvagg** [comment]
restarted jenkins, let's see how this week goes! @trott you seem to notice this the most, pls report if you see it before next weekend.

**Comment by joaocgreis** [comment]
The change to weekly sounds good. Jenkins might slow down too much towards the end of the week, when it has almost 2 weeks of history.

Using the built-in pruning sounds good. I suggest we use it defined to 6 days, in addition to the current mechanism. This way, the current script will have to delete very little or nothing, but will still catch files for any job where we forget to define the built in. If this proves insufficient, we can reevaluate. I went ahead and added this to https://ci.nodejs.org/view/All/job/node-daily-v4.x-staging/, since it runs daily and should not be a big issue if something goes wrong (it now starts at build 553, dated Feb 19). If all looks good tomorrow we can start to apply this to other jobs.

**Comment by rvagg** [comment]
It's hard to say for sure but my impression is that Jenkins has been much more well behaved since this change to weekly pruning. Will keep on monitoring but I reckon we should start to switch to the internal pruning mechanism like @joaocgreis has done above. We can roll it out over time and when we remove the external pruner we can just keep track of the filesystem and count old builds per jobs to figure out the right prune duration.
