### ISSUE TITLE
Install h2load on benchmarking machine

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#1147]
Hey, I think I remember a similar issue being opened about one of the other benchmarkers, but I can’t find it right now. Anyway, it would be nice to have `h2load` installed on the benchmarking machine so that we can run the HTTP/2 benchmarks there?

Otherwise the result is something like https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/128/console

**Comment by maclover7** [comment]
I'd be happy to take care of this, but I don't seem to have access to the machine (`ssh root@50.23.85.254 -i /Users/jon/.ssh/nodejs_build_test` isn't working.)

cc @mhdawson @rvagg

**Comment by rvagg** [comment]
It's in the infra group. I've added the keys you have in GitHub onto the host so you can get in (maybe you should remove the one you don't need from there). Try to avoid the work if you see it working on any benchmarking tasks.

**Comment by mhdawson** [comment]
I do have an action to add keys specific to the benchmarking WG onto those machines but I have just never had time to get to it.  I added a comment to https://github.com/nodejs/build/issues/1147 so if we ever get around to the ansible scripts we don't forget to add to the list of ones that should be installed.

There are 3 benchmarking machines now, the original one and the 2 new ones from Intel.  Its the 2 Intel ones that run the microbenchmarks job so we need to install on both of those.

**Comment by addaleax** [comment]
Anything I can help with here? It would be nice to have the benchmarking machine available for https://github.com/nodejs/node/pull/18936. :)

**Comment by mhdawson** [comment]
@maclover7 you still planning to get to this ?

**Comment by addaleax** [comment]
Hm … gentle ping @nodejs/build again :)

**Comment by mhdawson** [comment]
@addaleax have you installed this before.  I was looking to see if it as simple as installing with apt-get but all of the instructions I can find require building along with http2 and doing a full install of http2.

**Comment by addaleax** [comment]
@mhdawson What I did locally was building directly from a https://github.com/nghttp2/nghttp2 checkout and installing it (maybe even manually `cp`’ed the `h2load` binary, not sure), that worked well enough for me

**Comment by maclover7** [comment]
Sorry for not getting back to this. This is already in progress via #1171, just haven't had time to get back to it. Will take a look now
