### ISSUE TITLE
Offline CI hosts

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1152]
@gibfahn @mhdawson these are yours I think, would you mind having a look because they've been offline for some time now:

* [test-macstadium-macos10.08-x64-1] - "Jan 11, 2018 4:19:53 PM Disconnected by mhdawson : Disconnecting so that it can be used for investigation"
* test-marist-zos13-s390x-2
* test-osuosl-ubuntu14-ppc64_le-2

Is there someone else we should be pinging for these IBM machines when they go offline?

**Comment by mhdawson** [comment]
Looking, still trying to catch up having been out of the office last week.

**Comment by mhdawson** [comment]
* We've never added 10.08 to any of the test jobs and have decided only to add for 10.10 and above.  test-macstadium-macos10.08-x64-1 was disabled to allow @anisha-rohra to investigate issues that were reported with respect to building a module with N-API on 10.08 (see https://github.com/nodejs/build/issues/1077).  Added link to issue in notes for machine.  @anisha-rohra do you still need the machine ? 

* test-marist-zos13-s390x-2 has been offline as it was failing the libuv tests and we could not figure out why.  We took another look earlier this week and tests seem to be passing so possible some of the security/os fixes that were applied helped.  In any case it is enabled again.  You can ping @jBarz with respect to the marist-zos machines.

* test-osuosl-ubuntu14-ppc64_le-2 looks to be an old name as our 2 currently active ppc64_le 
   are all on-line and working fine.  Node sure if I forgot to delete this as part of a past rename or they
   were renamed more recently, but in any case I've deleted this old one.


I liked when we got on/offline messages as that made it easier to keep on top of when machines were not available.

**Comment by mhdawson** [comment]
Closing as I think I've addressed the issues noted, 1 is back online, 1 is deleted and the other has the notes updated to link to the issue with more information about why it is off-line.
