### ISSUE TITLE
Compilation fails on nodejs-scaleway-armv7-wheezy-1

### ISSUE THREAD

**Issue by targos** [nodejs/build#1161]
Examples:
https://ci.nodejs.org/job/node-test-commit-arm/14266/nodes=armv7-wheezy/console
https://ci.nodejs.org/job/node-test-commit-arm/14260/nodes=armv7-wheezy/console

Fails with:
```
cc1plus: error: unrecognized command line option ‘-std=gnu++1y’
```

This only happens with the wheezy-1 host. wheezy-2 is okay.

**Comment by targos** [comment]
@nodejs/build

**Comment by maclover7** [comment]
cc @rvagg

**Comment by rvagg** [comment]
pretty sure I'm to blame for this and I'm pretty sure it's fixed now, here's both of them running:

https://ci.nodejs.org/job/node-test-commit-arm/14316/nodes=armv7-wheezy/
https://ci.nodejs.org/job/node-test-commit-arm/14317/nodes=armv7-wheezy/

sorry for the disruption, I should have noticed this earlier
