### ISSUE TITLE
glibc version on arm64

### ISSUE THREAD

**Issue by gdams** [nodejs/build#1164]
So I was looking at https://github.com/nodejs/node/blob/master/BUILDING.md and I noticed that the supported glibc versions is `glibc >= 2.12` on arm64. Looking at the inventory.yml, it would suggest that we build on centos7 which has a glibc version of `2.17`.

Would someone be able to confirm if in fact we do have an arm64 machine capable of building at that level otherwise we should probably update that table.

**Comment by gibfahn** [comment]
Probably a question for @rvagg or @mhdawson

**Comment by gdams** [comment]
from @gibfahn 
```bash
[root@release-packetnet-centos7-arm64-1 ~]# /lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-16).
Compiled on a Linux 4.5.0 system on 2017-08-24.
Available extensions:
    The C stubs add-on version 2.1.2.
    crypt add-on version 2.1 by Michael Glad and others
    GNU Libidn by Simon Josefsson
    Native POSIX Threads Library by Ulrich Drepper et al
    BIND-8.2.3-T5B
libc ABIs: UNIQUE
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

**Comment by rvagg** [comment]
Yeah, that's the oldest we have for arm64, we used to use ubuntu 14.04 but that was even newer, 2.19. We're not going to go an older than CentOS 7, we already resolved that in an earlier discussion with someone that wanted a more ancient libc iirc, so I'm +1 on updating the docs.

**Comment by BethGriggs** [comment]
Can someone take a look at the updated docs for v8.x to confirm they are accurate? https://github.com/nodejs/node/pull/23275
