### ISSUE TITLE
Jenkins jobs cleanup: Round II

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1165]
Did another index of all CI Jenkins jobs, and trying to sort out which Jenkins jobs on the public CI are personal or are being used in another fashion. Please comment below if you are removing jobs or don't need them anymore. I think if no response is heard in one or two weeks that the job script could be archived somewhere, and then the job can be deleted.

cc @nodejs/build 

**not needed, need to be archived/removed:**
- [x] test-machine-pipeline
- [x] smoketest-release
- [x] smoker
- [x] serialport-test-commit-windows
- [x] serialport-daily-master
- [x] node-test-commit-smartos-abort-on-timeout
- [x] node-test-commit-linux-abi-gabriel
- [ ] node-test-commit-gib
- [x] node-test-commit-arm-gh-bot-test
- [x] jbergstroem-test-commit-debug
- [x] citgm-continuous-integration-gh-bot-test

**not needed, already removed:**
reis-citgm-smoker-nobuild
node-test-commit-plinux_mdawson

**needed:**
node-inspect-continuous-integration
node-inspect

**not sure if needed or not:**
citgm-abi-smoker-forward-compat

**Comment by rvagg** [comment]
I'd check on node-inspect-continuous-integration and node-inspect with the node-inspect team, but other than that +1 for removing all of these

**Comment by gibfahn** [comment]
cc/ @nodejs/citgm for 

>citgm-continuous-integration-gh-bot-test
>citgm-abi-smoker-forward-compat

**Comment by phillipj** [comment]
The gh-bot jobs should not be needed anymore.

**Comment by maclover7** [comment]
cc @jkrems @ofrobots @bnoordhuis for node-inspect jobs

**Comment by jkrems** [comment]
* `node-inspect-continuous-integration`: The official and original CI job for testing changes to [`nodejs/node-inspect`](https://github.com/nodejs/node-inspect).
* `node-inspect`: An experimental replacement of the above with a pipeline script. Progress right now stalled but I think it's the likely future direction.

**Comment by joaocgreis** [comment]
I deleted `reis-citgm-smoker-nobuild`.

Please don't just delete the `serialport-*` jobs. They could be archived somewhere, as they are not currently used, but the scripts should be mostly functional and can be a great help if someone wants to pick up testing serialport again.

**Comment by mhdawson** [comment]
Deleted node-test-commit-plinux_mdawson

**Comment by maclover7** [comment]
Jobs to be removed have had that done, relevant archives taken care of via 96fd5e43f1cb614c1a197aa1c8240c9ae4f81a1f
