### ISSUE TITLE
Release Job Update - FYI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1169]
Planning to add this for in the release job for the linux platforms:

```bash
  rm -rf build
  git clone https://github.com/nodejs/build.git
  . ./build/jenkins/scripts/select-compiler.sh
```

It clones the build repo, and then uses one of the included scripts to set the compiler level for PPC.  Should only affect power due to this switch:

```bash
case $NODE_NAME in
  *ppc64_le* ) SELECT_ARCH=PPC64LE ;;
esac

if [ "$SELECT_ARCH" = "PPC64LE" ]; then
.
.
.
```

This will later be expanded to include s390 as well .

This script is already being used in the test jobs to select the correct compiler based on the version of Node.js.

Plan to update the PPCle release machine to add the 4.9 compiler (using the updated ansible scripts) and then add this section to the build job.

**Comment by rvagg** [comment]
OK, I can see ways this could be optimised with existing variables, perhaps even integrating with the Groovy version selector thing, but this seems inoffensive enough for a start. It does raise one question, however, is ccache installed on these machines? I see we're reaching straight for the versioned compiler binary in /usr/bin/ so I guess not? Is that something we could rectify or is it too difficult on these platforms?

**Comment by mhdawson** [comment]
It may be as simple as removing the /usr/bin/ from the paths were we set in these lines:
```
 export CC=/usr/bin/gcc-${COMPILER_LEVEL}
  export CXX=/usr/bin/g++-${COMPILER_LEVEL}
  export LINK=/usr/bin/g++-${COMPILER_LEVEL}
```
as I see this:

```
root@test-osuosl-ubuntu1404-ppc64-le-1:/etc/init# ls -l /usr/lib/ccache
total 0
lrwxrwxrwx 1 root root 16 Nov 30 01:49 c++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 30 01:49 c89-gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 30 01:49 c99-gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 30 01:49 cc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 30 01:49 g++ -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 30 01:49 g++-4.8 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 29 01:39 g++-4.9 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 30 01:49 gcc -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 30 01:49 gcc-4.8 -> ../../bin/ccache
lrwxrwxrwx 1 root root 16 Nov 29 01:39 gcc-4.9 -> ../../bin/ccache
```

@jBarz if you can confirm that will work ok let me know and I'll remove from the script that sets the version.

**Comment by mhdawson** [comment]
Ok will update script

**Comment by mhdawson** [comment]
PR to fix up https://github.com/nodejs/build/pull/1175
