### ISSUE TITLE
Build fails on current android ndk-bundle

### ISSUE THREAD

**Issue by dashxdr** [nodejs/build#1170]
ndk-bundle 16.1.4479499
node-v9.7.1

`  /ram/node-v9.7.1/android-toolchain/bin/arm-linux-androideabi-gcc '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=0' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil  -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fPIE  -MMD -MF /ram/node-v9.7.1/out/Release/.deps//ram/node-v9.7.1/out/Release/obj.host/genccode/deps/icu-small/source/tools/genccode/genccode.o.d.raw   -c -o /ram/node-v9.7.1/out/Release/obj.host/genccode/deps/icu-small/source/tools/genccode/genccode.o ../deps/icu-small/source/tools/genccode/genccode.c
  /ram/node-v9.7.1/android-toolchain/bin/arm-linux-androideabi-g++ '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=0' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil  -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fPIE -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /ram/node-v9.7.1/out/Release/.deps//ram/node-v9.7.1/out/Release/obj.host/genccode/tools/icu/no-op.o.d.raw   -c -o /ram/node-v9.7.1/out/Release/obj.host/genccode/tools/icu/no-op.o ../tools/icu/no-op.cc
  /ram/node-v9.7.1/android-toolchain/bin/arm-linux-androideabi-g++ -rdynamic -fPIE -pie  -o /ram/node-v9.7.1/out/Release/genccode /ram/node-v9.7.1/out/Release/obj.host/genccode/deps/icu-small/source/tools/genccode/genccode.o /ram/node-v9.7.1/out/Release/obj.host/genccode/tools/icu/no-op.o /ram/node-v9.7.1/out/Release/obj.host/tools/icu/libicutools.a 
/ram/node-v9.7.1/out/Release/obj.host/genccode/deps/icu-small/source/tools/genccode/genccode.o:genccode.c:function main: error: undefined reference to 'stdout'
/ram/node-v9.7.1/out/Release/obj.host/genccode/deps/icu-small/source/tools/genccode/genccode.o:genccode.c:function main: error: undefined reference to 'stderr'
/ram/node-v9.7.1/out/Release/obj.host/tools/icu/libicutools.a(/ram/node-v9.7.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/toolutil.o):toolutil.cpp:function icu_60::IcuToolErrorCode::handleFailure() const: error: undefined reference to 'stderr'
/ram/node-v9.7.1/out/Release/obj.host/tools/icu/libicutools.a(/ram/node-v9.7.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/toolutil.o):toolutil.cpp:function utm_open: error: undefined reference to 'stderr'
/ram/node-v9.7.1/out/Release/obj.host/tools/icu/libicutools.a(/ram/node-v9.7.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/toolutil.o):toolutil.cpp:function utm_alloc: error: undefined reference to 'stderr'
/ram/node-v9.7.1/out/Release/obj.host/tools/icu/libicutools.a(/ram/node-v9.7.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/filestrm.o):filestrm.cpp:function T_FileStream_stdin: error: undefined reference to 'stdin'
/ram/node-v9.7.1/out/Release/obj.host/tools/icu/libicutools.a(/ram/node-v9.7.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/filestrm.o):filestrm.cpp:function T_FileStream_stdout: error: undefined reference to 'stdout'
collect2: error: ld returned 1 exit status
tools/icu/genccode.host.mk:127: recipe for target '/ram/node-v9.7.1/out/Release/genccode' failed
make[1]: *** [/ram/node-v9.7.1/out/Release/genccode] Error 1
rm 36b14432e340fa617cb61b68adde2dbc2357d382.intermediate
Makefile:90: recipe for target 'node' failed
make: *** [node] Error 2
`

Ideas?
ETA: Not sure if it's relevant but the android-configure calls for platform-21 but I only have platform-25 installed...

**Comment by dashxdr** [comment]
What would be nice would be a HOWTO that would work to build ANY version of node.js, ANY version of android platform, ANY version of ndk tools...

As it is, ALL combinations of versions fail, the only question is in what details...

**Comment by rvagg** [comment]
Hey @dashxdr, I believe there's some awkwardness with cross-compile ICU and it looks like you might be running into that. Can you try `configure` with --without-intl` to skip ICU entirely? You'll be without the `Intl` object and some i18n functionality on `String` and `Number` but they're not commonly used functions.

**Comment by rvagg** [comment]
Regarding your request for documentation, perhaps you could invest some time working it out for us and contribute some doc's? Android is not an officially supported platform and we have no regular contributors here or on nodejs/node that use it at all so we rely on casual contributions from people like yourself that discover flaws and come up with fixes.

**Comment by dashxdr** [comment]
Look, you guys have this "android-configure" script. It's like an attractive nuissance. It doesn't work on any combination I've tried. You'd be better of deleting it so people like me aren't tricked into wasting our time.

You put the script in your project. If it's there, I'd think the onus is on you to maintain it. I'm not an up to date expert on either android OR your build machinery. At least you guys know how your s**t works, that's a major advantage over me trying to fix this. I don't know whether the problem is on your side or android's side.

You can easily reproduce the failure by just installing the android studio command line tools from here:
https://developer.android.com/studio/index.html
Here's a direct DL link for linux:
https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip

You unpack that somewhere then just use the tools/bin/sdkmanager to install other components, like the ndk-bundle. Your android script then is supposed to be launched with an argument pointing to that directory.

**Comment by rvagg** [comment]
I think you might be misunderstanding how open source works. If you disagree with how something is shipped, then your best path forward is to submit a pull request to change it. If you think removal of the script is a good thing for us to do then you're welcome to propose it. I suggest you might get more traction with the broader group by adding a message at the top of the script or on the output of the script about how it's not officially supported so caveat emptor.

As I said previously, Android is not one of the officially supported platforms but we welcome contributions from people who find it useful and want to run the Node + Android combination. We do the same thing with MIPS support, with LibreSSL support and a number of other non-standard ways that people want to compile and run Node. For those of us who like to spend our time (a very large portion of us spend our own free time on this, just for "fun"), there's a limit to how thin we're willing to spread ourselves. Unfortunately Android hasn't made the cut for anyone who regularly contributes around here as far as I know. You're welcome to look at commit histories and find someone else interested. However, I suspect that your attitude and language might be a barrier to getting any further than this. But good luck.
