### ISSUE TITLE
curl not found on test-softlayer-debian9-x64-1

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1172]
e.g. https://ci.nodejs.org/job/citgm-continuous-integration/71/MACHINE=debian9-64/console

```bash
Building remotely on test-softlayer-debian9-x64-1 (debian9-64) in workspace /home/iojs/build/workspace/citgm-continuous-integration/MACHINE/debian9-64
+ curl https://nodejs.org/download/release/
/tmp/jenkins1960265235314734632.sh: 1: /tmp/jenkins1960265235314734632.sh: + tr -d /
curl: not found
```

Not sure if the machine was provisioned with the new set of ansible script, but either way, hopefully this can be fixed with them.

Maybe cc/ @rvagg @maclover7

**Comment by maclover7** [comment]
I believe @rvagg was the one who setup the machine, not sure if he used `playbooks/jenkins/worker/create.yml` or not

**Comment by rvagg** [comment]
yep, it was, looks like we need to add curl to the vars for debian9. I've just added `curl` to the `debian9` list in ./roles/baselayout/vars/main.yml and am running that now. If all goes well I'll push that commit. It's unfortunate that we're back in the default-no-curl situation with Debian, I thought they stopped doing that back in 7 and shipped curl by default.
