### ISSUE TITLE
node-test-commit-v8-linux-fedora changes

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1173]
@mhdawson I think this is for you to answer since the job config history has your name all over it.

[node-test-commit-v8-linux-fedora](https://ci.nodejs.org/job/node-test-commit-v8-linux-fedora/) was called node-test-commit-v8-linux-fedora24 until yesterday. Fedora 24 has been removed from CI and I've hooked this job up with fedora-latest-x64 instead so it'll track the latest. Unfortunately it got a bit broken, it had a double-matrix that required both the `fedora24` and `v8test` labels and that was changed to `fedora-latest-x64` and `v8test` but no such combination exists in our current range of builders. It runs on a schedule so it was paused waiting for an available builder in the queue today.

I don't know what the purpose of the `v8test` label was here. I don't even know what the purpose of this job is. Does it get used by anything else in our infra? Does anyone look at it? It's been red for a very long time. Can we remove it, or at least remove the schedule, so that it doesn't take up resources?

**Comment by mhdawson** [comment]
The one that I'm most aware of is https://ci.nodejs.org/job/node-test-commit-v8-linux/.

There was the desire at some point to add more coverage and my guess is that somebody made a clone of node-test-commit-v8-linux to work on this and got the schedule along with it.  I don't think it was me so as far as I'm concernd its ok to disable/delete.  If I remember correctly v8test is used to limit it to machines that had more CPUs/memory.

I'll disable the scheduled run as I don't think the fedora job is being used as part of the v8 work and we can delete if nobody complains in a little while.

**Comment by rvagg** [comment]
:thumbsup: thanks @mhdawson
