### ISSUE TITLE
Change nodejs/release to nodejs/releasers

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1177]
https://github.com/nodejs/admin/issues/84#issuecomment-370971395

We need to make sure any accesses we have are updated, it should just be the access permissions in ci.nodejs.org and ci-release.nodejs.org, but maybe there are others.

I don't think the other name/team changes should cause any issues.

**Comment by gibfahn** [comment]
Current access permissions:

### ci-release

![image](https://user-images.githubusercontent.com/15943089/37210499-d6230fee-23a0-11e8-8eab-41a11f71ad6f.png)

### ci

![image](https://user-images.githubusercontent.com/15943089/37210513-ed821ebe-23a0-11e8-89fb-45d51682c5c7.png)

**Comment by maclover7** [comment]
ping @gibfahn

**Comment by MylesBorins** [comment]
I've updated all the IAM roles on github and updated the permissions in both ci && ci-release
