### ISSUE TITLE
Rename node-test-commit-light to node-test-commit-lite

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1178]
I'm not a huge fan of `lite` vs `light`, but given that [`node-test-pull-request-lite`](https://ci.nodejs.org/job/node-test-pull-request-lite/) uses that spelling, we should probably be consistent and change [`node-test-commit-light`](https://ci.nodejs.org/job/node-test-commit-light/) (and changing the `pull-request` link is likely to break more things).

**Comment by gibfahn** [comment]
Now done, hopefully this doesn't break anything.

**Comment by richardlau** [comment]
Won't this break any existing links in PR's? 

This will affect https://github.com/nodejs/node-core-utils/pull/171

**Comment by gibfahn** [comment]
>Won't this break any existing links in PR's?

Yes, but they all stop working after a few days anyway when the Jenkins history gets overridden, so probably not a big issue.

Also most people don't directly link to the commit-lite url (they link to the pull-request-lite url).

>This will affect nodejs/node-core-utils#171

Yep, that's why I did it 😁 .
