### ISSUE TITLE
Node.js distribution binary

### ISSUE THREAD

**Issue by bastup** [nodejs/build#1179]
Hello,

I have node project running on a MIPS architecture, it is a little slow with the FPU emulation but it works.
I am wondering if it is possible to make a binary of my node.js project? I have tried to google it but all binary distribution tools I have found only support the ARM architecture. 

All help is appreciated /Bastu

**Comment by maclover7** [comment]
Hi @bastup -- unfortunately we have no MIPS machines in our build matrix. There are issues like nodejs/node#13488 that deal with MIPS compilation, but it is not directly supported by our build infrastructure. My suggestion would be to try StackOVerflow and see if you can get any help there.
