### ISSUE TITLE
Allow CI testing without worrying about the linter.

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#118]
I'm not really so keen on the new setup.

There are times where I'll just want to test the functionality of a PR without caring if the author has perfect style. Could we do that somehow?

**Comment by rvagg** [comment]
you could trigger a build with one of the subgroups, like https://jenkins-iojs.nodesource.com/job/iojs+pr+linux/, on the positive side you'll get faster feedback, on the negative you won't get full coverage.

We could add a "no lint" parameter at the top level if necessary.

**Comment by jbergstroem** [comment]
Another alternative would be what we brought up in the last build meeting -- continue building regardless of lint output.

**Comment by rvagg** [comment]
until we really have resource problems I don't mind; I'll go undo that fast-fail restriction now

**Comment by joaocgreis** [comment]
The linter was moved to run in parallel, so I believe this can be closed. @Fishrock123 please reopen if I'm wrong!
