### ISSUE TITLE
When adding new targets, can we ensure they work on all release lines

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1182]
Hey All,

I just noticed we introduced a new target (for testing without intl) and it is broken for 6.x

https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_withoutintl_x64/2888/

Having new targets that are broken show up can make LTS stuff a bit harder, and it would be nice to be proactive about fixing this rather than reactive when trying to land code.

Is there a way we can ensure new targets are working or being skipped / marked as flaky on all supported release lines before deploying?

**Comment by gibfahn** [comment]
>Is there a way we can ensure new targets are working or being skipped / marked as flaky on all supported release lines before deploying?

I think the answer is that we need to remember to check this when we add new jobs and configurations. I know I tend to mostly run master to test things, and I should definitely run v*.x as well to check.

cc/ also @rvagg and @maclover7 , as I think we're the ones that are most commonly changing jobs these days.

Long term if we're checking things into this repo then we can have PRs and reviews and enforce checks, but as it stands I'm not sure there's much we can do other than to keep it in mind.

Maybe we could document it as a first step.

**Comment by gibfahn** [comment]
Discussed in the Build WG meeting, minutes here: https://github.com/nodejs/build/blob/master/doc/meetings/build-wg-meeting-2018-03-20.md#when-adding-new-targets-can-we-ensure-they-work-on-all-release-lines-1182

Basically we need to have a discussion between the releasers and build to try to work out what we think should happen here.
