### ISSUE TITLE
When do we re-run ./configure

### ISSUE THREAD

**Issue by atvoicu** [nodejs/build#1185]
Hello,

I have a question regarding the best practices (and needs) to re-run ./configure.

Here is our use-case. We have two Docker images: an OS image (Ubuntu 16.04.1) and a Runtime image (Node.js 8.10.0) which builds Node from source on top of the OS image.
When we update the OS image (say to Ubuntu 16.04.2) do we need to rebuild Node (or re-run ./configure) or can we just use the existing version (which was built on Ubuntu 16.04.1).
Form what I understand we shouldn't need rebuilding since the binary offered on https://nodejs.org/en/download/ works independent on the OS distribution it was built on.
Could you confirm this?

Thank you for your help!
Alex.

**Comment by mhdawson** [comment]
We build the binaries on an older OS version so I think as long as you are moving to a NEWER version of the OS I don't think you need to recompile.

Having said that, I think you would still have to rebuild your docker image as I don't think you can update a lower level image and have those changes inherited by images that were derived from the lower level image in docker.  So you can use the existing Node.js binary, but you would need to rebuild images that are based on the updated OS image.

**Comment by atvoicu** [comment]
Thank you for your reply Michael.

> Having said that, I think you would still have to rebuild your docker image as I don't think you can update a lower level image and have those changes inherited by images that were derived from the lower level image in docker.
I was planning to do an image rebase using this GitHub project: https://github.com/google/image-rebase. From what I understand that should work.

**Comment by maclover7** [comment]
Looks like this has been solved -- please reopen if I'm wrong
