### ISSUE TITLE
shortage of ubuntu 1604 executors

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1188]
looks like we only have one executor at the moment.

this is causing a massive backlog in CI atm

**Comment by gibfahn** [comment]
Next time this happens can you link to the specific label that is a problem?

[ubuntu1604-64](https://ci.nodejs.org/label/ubuntu1604-64/) has 2 executors, I'm guess this is about [ubuntu1604-32](https://ci.nodejs.org/label/ubuntu1604-32/) which currently has only 1.
