### ISSUE TITLE
Install nasm on Windows for OpenSSL-1.1.0

### ISSUE THREAD

**Issue by shigeki** [nodejs/build#1190]
OpenSSL-1.1.0 require the NASM http://www.nasm.us/ for building assemble codes as described in 
https://github.com/openssl/openssl/blob/1bfb7860cb81cf6431308c244a4967e41806a919/NOTES.WIN#L21-L24
It also needs for Node build after upgradeing OpenSSL-1.1.0.

Please install it on the all Windows machines for ci checking and release building. The current latest stable version is 2.13.03.

**Comment by joaocgreis** [comment]
PR: https://github.com/nodejs/build/pull/1192

Script already run on all machines, NASM is ready to use. Let me know if anything is wrong.

**Comment by shigeki** [comment]
@joaocgreis Thanks for your quick work.  But the configure was failed to use nasm in CI because the output of `nasm -v` cannot be obtained as https://ci.nodejs.org/job/node-compile-windows/16716/label=win-vs2017/consoleFull

```
configure  --dest-cpu=x64
WARNING: No acceptable ASM compiler found!
         Please make sure you have installed nasm from http://www.nasm.us
         and refer BUILDING.md.
```
Could you confirm the output of `nasm -v` ? 
```
C:\Users\ohtsu\Desktop\github\shigeki\node>nasm -v
NASM version 2.13.03 compiled on Feb  7 2018
```
If nasm was installed with http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-installer-x64.exe, the path is `C:\Program Files\NASM>`.

**Comment by joaocgreis** [comment]
@shigeki the NASM installer does not add the executable location to the `Path`. I could add it in all CI machines, but I believe a better solution is to look for it in the default install location. This is to make it easier for people starting in node development (for example in Code & Learn).

Here is my suggestion for how to do it: https://github.com/janeasystems/node/commit/3a2545bcedc885a38970125b1d66da3489dea37b , feel free to take any or all of it and change as you see fit. It is a fixup for your `build: add openssl-1.1.0 support` commit, also includes two lines in `BUILDING.md`.

CI: https://ci.nodejs.org/job/node-test-commit-windows-fanned/16642/

**Comment by shigeki** [comment]
@joaocgreis Thanks and I appreciate your patch.  I was not ware that `vcbuild.bat` had such a detection of commands.  CI was good in https://ci.nodejs.org/job/node-compile-windows/16744 and I also confirmed in my azure vm where the nasm path was removed.

I added your patch in https://github.com/shigeki/node/commit/c917bce1380578dfe40b996fce252b76925ce69a as to follow  the commit message guideline  and lint-md and I would like your commit to be included in my PR. 
Please let me know if word or something is wrong. Thanks, agin.

**Comment by ostropik** [comment]
Spend 2 hours, using a youtube sample which based on ActiveState perl. 
Then install:
> strawberry-perl-5.32.1.1-32bit.msi
> nasm-2.15.05-installer-x64.exe

```
perl Configure VC-WIN32 --debug --prefix=x:\WinProjects\Libs\openssl\Debug --openssldir=x:\WinProjects\Libs\openssl\SSL no-shared
echo clearing...
nmake clean
echo building...
nmake
echo installing...
nmake install
```
yeah...
