### ISSUE TITLE
Removing FIPS CI in upgrading OpenSSL-1.1.0

### ISSUE THREAD

**Issue by shigeki** [nodejs/build#1191]
OpenSSL-1.1.0 does not have FIPS support. So we can't check CI build in upgrading OpenSSL-1.1.0 and 
CI of ubuntu1604_sharedlibs_fips20_x64 would be always error. 
Can we removing it after upgrading OpenSSL-1.1.0?

**Comment by mhdawson** [comment]
Agree with @gibfahn that we should add a check for the openssl version and skip if it is 1.1.X so that we still have testing for older versions.

**Comment by shigeki** [comment]
Please let me know what is needed to check the openssl version in CI before building.
I've just made configure with checking its options and exit it as
```
  if options.openssl_fips:
     print('Error: FIPS is not supported yet in this version')
     exit(1)
```
in 
 https://github.com/shigeki/node/blob/9beb31e1f125a1a623be2bcef19dbb425fc3c5f0/configure#L1091-L1093.

**Comment by rvagg** [comment]
We have a bunch of version exclusions in node-test-commit-linux-containered already. I've added the following to the fips test which so far doesn't have any:

```sh
MAJOR_VERSION=`cat src/node_version.h | grep "#define NODE_MAJOR_VERSION" | awk '{ print $3}'`
RUN_TESTS="RUN"
if [[ ${MAJOR_VERSION} -gt 9 ]]; then
  SKIP_MESSAGE="Not valid for Node versions greater than 9"
  echo $SKIP_MESSAGE
  echo "1..1" >${WORKSPACE}/test.tap
  echo "ok 1 $SKIP_MESSAGE" >>${WORKSPACE}/test.tap
  exit 0
fi
```

Also @MylesBorins FYI I raised the `--without-intl` test runner to >=9 earlier this week so we shouldn't get the v8 failures anymore.
