### ISSUE TITLE
Moving CI temporaries repo to our own infra

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#1193]
Janea Systems received a request from GitHub to discontinue the usage pattern of `node_binary_tmp`, where we store the temporary binaries used by CI.

I will move forward by creating git repositories in our `jenkins-workspace` machines, that should have enough storage space and be adequate for this usage. For now, I'll set it up so that only one server will be used at a time. I don't see a simple way to implement a load balancing scheme resilient to server failures, and I believe this will be stable enough. If it proves to be a problem, we'll have to investigate a better way or create a dedicated git server.

**Comment by joaocgreis** [comment]
@nodejs/jenkins-admins to give us a way to change the temporaries repo to a different `jenkins-workspace` fast if needed, I added `TEMP_REPO` and `TEMP_REPO_SERVER` as global Jenkins variables, defined in _Manage Jenkins/Configure System_. I removed `TEMP_REPO` as a parameter from everywhere, I believe it was very rarely changed if at all, and the default value would be a problem here.

PR with ansible changes: https://github.com/nodejs/build/pull/1195

I'll leave this issue open until that PR lands.

**Comment by rvagg** [comment]
this sucks, is it a workload thing? they noticed that repo has a _ton_ of churn and it's all bulky?

**Comment by joaocgreis** [comment]
They don't delete the objects after they become unreferenced, so even if we remove the branches the repository grows huge in their servers. They mentioned it was at 140GB, and the servers are not designed for this usage pattern.
