### ISSUE TITLE
Linter timing out

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1197]
Examples

https://ci.nodejs.org/job/node-test-linter/17368/
https://ci.nodejs.org/job/node-test-linter/17370/
https://ci.nodejs.org/job/node-test-linter/17371/

**Comment by gibfahn** [comment]
This is weird, normally when the checkout times out the job fails.

![image](https://user-images.githubusercontent.com/15943089/37957250-62d80fea-31a5-11e8-9390-2be7d0e93395.png)

**Comment by gibfahn** [comment]
Reproduced this by running manually on the machine, the git checkout command just directly hangs.

Seems like something is up with the machine, trying a reboot.

**Comment by gibfahn** [comment]
Okay, the machine doesn't seem to have come back up.

[test-rackspace-freebsd10-x64-1](https://ci.nodejs.org/computer/test-rackspace-freebsd10-x64-1/)

**Comment by maclover7** [comment]
cc infra admins @rvagg @mhdawson @joaocgreis, this machine may need to be reprovisioned

**Comment by rvagg** [comment]
pretty sure I have this fixed now

I'd like us to move off freebsd 10 for the linter jobs, they aren't the best at staying online, perhaps this is even a job for jenkins-workspace machines

**Comment by gibfahn** [comment]
>pretty sure I have this fixed now

@rvagg what did you do to fix it?

**Comment by rvagg** [comment]
@gibfahn well .. I logged in to rackspace and hard rebooted it, then did a `pkg upgrade` and cleaned out all of the crud in ~iojs. Unfortunately I just watched a linter job stall so we're not out of the woods yet.
