### ISSUE TITLE
node-stress-single-test needs to make build-addons-napi

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#1198]
In order to stress-test a single N-API test, the N-API tests must also be built.

**Comment by gabrielschulhof** [comment]
https://ci.nodejs.org/job/node-stress-single-test/

**Comment by richardlau** [comment]
See also https://github.com/nodejs/build/issues/1097.

**Comment by gabrielschulhof** [comment]
@richardlau it does now run `make build-addons`, AFAICT, just not `make build-addons-napi`. Look for "build-addons" on this page: https://ci.nodejs.org/job/node-stress-single-test/1794/nodes=debian9-64/consoleFull - dunno about Windows though.

**Comment by gibfahn** [comment]
I've added build-addons-napi below build-addons:

```diff
  PYTHON=python make build-addons
+  PYTHON=python make build-addons-napi
```

Let me know if that doesn't fix it for you @gabrielschulhof . I didn't change the windows script.

**Comment by gabrielschulhof** [comment]
@gibfahn Great Success! Thanks!
