### ISSUE TITLE
Ability for native module developers to hook in to the build infrastructure

### ISSUE THREAD

**Issue by voodootikigod** [nodejs/build#12]
It would be grand to have the ability to provide the same build infrastructure that is used to compile node to be provided as a service for developers of native modules that implement/utilize node-pre-gyp. Happy to recommend/advise on this from experience with node-serialport, but the ideal case would be for on npm publish a web hook is triggered that would build and store the compiled module for each (or a subset thereof) the target platforms.

A thought.

**Comment by jbergstroem** [comment]
I think we're still too far away from this, but once we have the bits and bobs in place to handle a wider circle of trust this is very feasible. Closing for now since the issues mentioned travels wider than native modules.
