### ISSUE TITLE
CI linter does not run

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1206]
See e.g. https://ci.nodejs.org/job/node-test-linter/17612/console

```
12:29:27 hudson.plugins.git.GitException: Command "git checkout -f 7e5230d80163aada3c0c368945528dcafd567aef" returned status code 128:
12:29:27 stdout: 
12:29:27 stderr: fatal: Unable to create '/usr/home/iojs/build/workspace/node-test-linter/.git/index.lock': File exists.
12:29:27 
12:29:27 Another git process seems to be running in this repository, e.g.
12:29:27 an editor opened by 'git commit'. Please make sure all processes
12:29:27 are terminated then try again. If it still fails, a git process
12:29:27 may have crashed in this repository earlier:
12:29:27 remove the file manually to continue.
```

**Comment by rvagg** [comment]
That host has been causing so much pain, I can't seem to pull it out of its funk no matter what I do. I've taken it offline but now we only have the one linter host.

Working @ https://github.com/nodejs/node/pull/19746 to get Makefile ready to run these jobs on Linux hosts, when that lands and is backported where appropriate we should be able to switch to using the jenkins-workspace hosts and ditch these FreeBSD 10 machines.

**Comment by maclover7** [comment]
@BridgeAR Has this happened recently? If not, then probably safe to close for now

**Comment by maclover7** [comment]
Issue seems to have largely subsided, closing for now. Please reopen if it appears again.
