### ISSUE TITLE
Requesting access to debian8-x86 for debugging spooky failures

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#1207]
Hi everyone! If it’s cool with you, I’d like to try and dig into those spooky no-stack-trace, no-error, no-nothing failures we’ve been seeing on Linux CI machines for a long time now.

I think debian8-x86 was particularly susceptible to this… that could totally just be suspicion, but I guess it would be a good starting point? I’m happy to look into this on any machine on which it has been happening.

/cc @bridgear @Trott

**Comment by BridgeAR** [comment]
Here a overview. So this is definitely happening on `debian8-x86` often. Here is a overview of most reports:

https://ci.nodejs.org/job/node-test-commit-plinux/15536/nodes=ppcbe-ubuntu1404/console
https://ci.nodejs.org/job/node-test-commit-plinux/15046/nodes=ppcbe-ubuntu1404/console

https://ci.nodejs.org/job/node-test-commit-plinux/15171/nodes=ppcle-ubuntu1404/console

https://ci.nodejs.org/job/node-test-commit-linux/15963/nodes=ubuntu1204-64/console

https://ci.nodejs.org/job/node-test-commit-linux/16494/nodes=debian8-x86/console
https://ci.nodejs.org/job/node-test-commit-linux/16533/nodes=debian8-x86/console
https://ci.nodejs.org/job/node-test-commit-linux/16398/nodes=debian8-x86/console
https://ci.nodejs.org/job/node-test-commit-linux/16305/nodes=debian8-x86/console
https://ci.nodejs.org/job/node-test-commit-linux/16299/nodes=debian8-x86/console
https://ci.nodejs.org/job/node-test-commit-linux/15980/nodes=debian8-x86/console

https://ci.nodejs.org/job/node-test-commit-linux/15935/nodes=debian8-64/console

https://ci.nodejs.org/job/node-test-commit-linux/16309/nodes=centos6-64/console

**Comment by Trott** [comment]
> Here a overview. So this is definitely happening on debian8-x86 often. Here is a overview of most reports:

@BridgeAR Alas, those are all now 404s....

**Comment by Trott** [comment]
SGTM

**Comment by Trott** [comment]
(Ooooohhhhhh...the fact that they're 404s is not important. The fact that they are fully 50% debian8-x86 is the important part. Got it. Sorry for the noise.)

**Comment by mhdawson** [comment]
SGTM

**Comment by addaleax** [comment]
@nodejs/build What’s the process for this? It would be ideal if I could have some time to look into this over the weekend, if that’s possible at all

**Comment by addaleax** [comment]
I think I figured out everything I can in https://github.com/nodejs/node/issues/19903#issuecomment-380155540. I’d like to wait for another opinion or so, but generally I should be done with access here. If somebody else does remove me before that (which is completely fine), please make sure to remove `~iojs/debug-18998/` – it’s 1.6 GB of debugging stuff. :)

**Comment by addaleax** [comment]
Okay, I’ve removed my own access now. Thanks everyone!
