### ISSUE TITLE
Node.js Foundation Build Working Group Meeting 2015-06-23

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#121]
8PM UTC, in your timezone: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js%20Foundation%20Build%20Working%20Group%20Meeting%202015-06-23&iso=20150623T20

Agenda & Minutes doc https://docs.google.com/document/d/1BohSyYFIuDDtFRYEY_Ip9Dja6i2Vh1tF_KXNqv3FAa8/edit

Hangout: https://plus.google.com/hangouts/_/hoaevent/AP36tYftIQaR1SvCx8dtoP8U98qpPMaTq-bR_5VzucM4yBvEaTJt8w (recorded but please raise objections to this before the meeting if you are uncomfortable with recording)

YouTube feed: http://www.youtube.com/watch?v=F15S-y5JpFg (if I remember to press record)

Minutes from the meeting on the 9th are here: https://docs.google.com/document/d/1zuUujd6XEdOJnvT6E_TzveZ8LGanhHGaOds69IyaVIw - hopefully we'll have a link for the meeting last week too but I can't find it atm.

**Comment by rvagg** [comment]
Please let me know what your google login is if you can't edit that doc and can only suggest and I'll add you. Also note there is a calendar entry for this that we are sharing, if you don't have it then please speak up.

**Comment by rvagg** [comment]
Some items while I think of them:

* nodejs.org domain is in the hands of the LF, I'd prefer it to be delegated to a Build WG managed Route53 account so it can be transparently managed (and scripted like https://github.com/nodejs/email)
* nodejs.org MX is routed through Google Apps, managed by the LF, I'd prefer it to eventually move to management by the Build WG as a simple redirect service (like https://github.com/nodejs/email) rather than Google Apps but that might be for discussion with the eventual Executive Director.
* Still haven't managed to get certs (SSL and code signing) purchased by the foundation, spending is probably in a difficult phase right now but I'd really like to free this up a bit so we can get on with the job.
* Website WG now have http://new-nodejs.iojs.org/ as a placeholder for http://new.nodejs.org/ for which they will work with the community on a new design. DNS updates need to happen, wild-card SSL cert needs to happen. Currently using a mirror of the same [github-webook](https://github.com/rvagg/github-webhook) magic that deploys https://iojs.org but from https://github.com/nodejs/new.nodejs.org. Website WG is now converged, managing both main web properties. Evangelism WG is now (apparently) managing the Node.js blog but they may need access.
* Would like to discuss website architecture, DigitalOcean, Joyent, redundancy, how do we move forward from thought-bubble to architecture planning. Also includes the possibility of hosting binaries on a redundant large-file / object store (S3, Cloud Files, Manta).
* There is now a Build WG **Secrets** Google Spreadsheet that a limited number of people on this team have access to, we should (eventually?) figure out the rules for who can access this.
* Server resources have been documented in a CSV file here: https://github.com/nodejs/build/pull/120
* @rvagg TODO still pending: document release process of io.js, this is changing somewhat with https://github.com/nodejs/io.js/pull/1938 and https://github.com/nodejs/io.js/pull/1975 so I'd rather wait.
* io.js nightlies now have the ARMv7 binaries built on a Wheezy machine, making them much more compatible with older Linuxes, this still needs to happen to releases
* I'm pushing for putting header tarballs with all of our releases: https://github.com/nodejs/io.js/pull/1975 (not just io.js preferably), coupling this with node-gyp will make a much more pleasurable experience but there's lots of work to be done downstream there. Getting header files up will be the first step. Note that the layout of these tarballs is different to the source tarball layout so node-gyp needs to configure its include directories differently but I've been testing it end-to-end and it's an easy fix to make it work. https://github.com/nodejs/io.js/pull/493 has the work I started on what node-gyp needs in core, I still have to get back to this but it should enable integration with nightly and rc builds as well as io.js and Node.js all at the same time when it's done (all with a tiny header tarball download which will ultimately be optional because most installed versions of will have the headers with them anyway!).
* @mhdawson is making good progress on the PPC machines aparently, they are now listed in Jenkins and have their own project but won't be hooked up to any-pr+multi until he is satisfied they are good to go.
* @orangemocha has made excellent progress on a converged Jenkins project(s), need update on this work and what's left to be done.
* @jbergstroem has been tending to the slaves, lots of init scripting, moving on to Ansible refactoring I believe (yay!).

**Comment by misterdjules** [comment]
I'll be traveling for work and thus won't be able to attend this meeting.

**Comment by mikeal** [comment]
> nodejs.org domain is in the hands of the LF, I'd prefer it to be delegated to a Build WG managed Route53 account so it can be transparently managed (and scripted like https://github.com/nodejs/email)
> nodejs.org MX is routed through Google Apps, managed by the LF, I'd prefer it to eventually move to management by the Build WG as a simple redirect service (like https://github.com/nodejs/email) rather than Google Apps but that might be for discussion with the eventual Executive Director.

The LF can point the DNS at whatever you like, we just need to find the best way to do this with no downtime. I've spoken with Mike about this and they are willing to make any changes you request they are just very afraid of taking action that is not at your request and being responsible for nodejs.org going down :)

The best way forward here is probably to come up with a transition plan and execute on it.

**Comment by kenperkins** [comment]
I'm phone screening two candidates at this time today, I can't make it *again. #fail

**Comment by mikeal** [comment]
> Still haven't managed to get certs (SSL and code signing) purchased by the foundation, spending is probably in a difficult phase right now but I'd really like to free this up a bit so we can get on with the job.

@mkdolan who should we talk to at Let's Encrypt about getting certs?

**Comment by Starefossen** [comment]
@rvagg Should the meeting minutes eventually go into the [/doc/meetings](https://github.com/nodejs/build/tree/master/doc/meetings) dir?

**Comment by rvagg** [comment]
yep, they should, you're welcome to try and organise them, it's one of those things in the back of my mind that needs doing .. one day
