### ISSUE TITLE
9.11 x64 MSI is corrupt

### ISSUE THREAD

**Issue by refack** [nodejs/build#1211]
Ref: https://github.com/nodejs/node/issues/19816

The file _seems_ truncated (headers look visually similar), but I couldn't find a tool that would even attempt to extract it.
File does match it's published SHA256 - `27ca07f3eeac71902f6daec28e763fe1c4c19e112da89d5d226e95b4750d6961` but is missing the internal signature structure.
* x86 MSI is fine
* last two x64 nightly MSIs are fine
* 9.10.1 x64 MSI is fine

I vote to remove from site, and recommend workaround.

/CC @nodejs/release

**Comment by MylesBorins** [comment]
I don't think we should be removing assets that we have published shasums for. I'm publishing a new release, and I think we just leave the old one as is. Thoughts?

https://github.com/nodejs/node/pull/19818

**Comment by rvagg** [comment]
https://ci-release.nodejs.org/job/iojs+release/3276/nodes=vs2015-x64/console

> scp: nodejs/release/v9.11.0//node-v9.11.0-x64.msi: No space left on device

New releases make sense but don't do it just yet .. we need to sort this space problem out! https://github.com/nodejs/build/issues/1202

**Comment by rvagg** [comment]
the logs don't show it unfortunately but I'm assuming that `ssh node-www touch .../node-v9.11.0-x64.msi.done` was performed _after_ the scp failed. Not what I would have expected.

I think we're going to need a @nodejs/platform-windows expert to have a look at https://github.com/nodejs/node/blob/master/vcbuild.bat#L371 and come up with a strategy to make the batch file fail of one of these commands fail, the whole point of the `.done` is to signal that the file upload is complete.

**Comment by MylesBorins** [comment]
fixed in 9.11.1

**Comment by refack** [comment]
I'm looking into the `vcbuild` failure.
