### ISSUE TITLE
CI: node-test-commit-lite aborted by unknown user

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1230]
See https://github.com/nodejs/node/pull/19963#issuecomment-380672403 from @Trott , which references [node-test-pull-request-lite#498](https://ci.nodejs.org/job/node-test-pull-request-lite/498).

Sometimes the job seems to be aborted mysteriously, by the [unknown user](https://ci.nodejs.org/user/unknown/).

```
00:06:47 Running C++ linter on addon docs...
00:06:47 Total errors found: 0
00:07:27 Build was aborted
00:07:27 Aborted by unknown
00:07:27 Notifying upstream projects of job completion
00:07:27 Finished: ABORTED
```

**Comment by Trott** [comment]
Unfortunately, looks like it's still happening: https://ci.nodejs.org/job/node-test-pull-request-lite/507/

**Comment by refack** [comment]
Eureka, when I set the job up I was overly optimistic:
![image](https://user-images.githubusercontent.com/96947/38705301-21ebdad2-3e77-11e8-85d5-1243044aa81b.png)
I'll extend the timeout.

**Comment by refack** [comment]
So I'll be closing this for now...
