### ISSUE TITLE
Need access to debian7-docker-armv7

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#1231]
May I please have access? I cannot seem to reproduce this environment using debootstrap and qemu. I'm hoping to reproduce and address https://ci.nodejs.org/job/node-test-commit-arm/15284/nodes=debian7-docker-armv7/console.

**Comment by mhdawson** [comment]
+1, @rvagg how would we give access in the new docker approach?

**Comment by gabrielschulhof** [comment]
Actually, I've managed to reproduce the issue locally. If I still need access, I'll reopen this issue. Thanks!
