### ISSUE TITLE
Enable a CI job to verify the node executable which uses node shared lib

### ISSUE THREAD

**Issue by yhwang** [nodejs/build#1233]
When using `--shared` option, it generates not only the node shared lib but also an node executable which links to the shared lib. So the node executable which is built with `--shared` option could also be used to run through all of the existing test cases. It will help us to verify the shared lib build.

This job: [node-test-commit-linux-as-shared-lib](https://ci.nodejs.org/view/All/job/node-test-commit-linux-as-shared-lib/) has been configured to run such test in ubuntu 14.04. And by default, it only performs when the node version is greater then 9. The reason is some test cases still fail in v8.x and v6.x. Just need to wait for some changes to be backported to these version. Then this job can also apply to v8.x and v6.x.

I propose to add this CI job into regular PR build process and at least it will verify the shared lib build on ubuntu 14.04. If needed, we can also create other jobs to cover other platforms.

**Comment by mhdawson** [comment]
+1 from me. Once we have agreement I'll add to the standard regression runs

@rvagg a few questions. 

*Right now I added some simple logic to only run on 9 and above (which an option to change the default to @yhwang can continue to test with the job) as some fixes to the tests still need to be backported to 8.X and 6.X.  We'll probably still want it to not run for 4.x.  I think using the plugin would require another copy and not sure it is worth it since the config is specific to the job.  

* Can you point me at any instructions for having this job run in a container instead of as a regular job? If I can easily switch over I'll probably do that.

**Comment by rvagg** [comment]
Cool, here's what needs to be done for this:

1. Make a new label for this, "ubuntu1604_sharedlibs_shared_x64" would match what we're using for other builds with alternative `./configure` options. Unfortunately you'll have to manually go through all of the containers that run in these configs and add the new label to all of them, see https://ci.nodejs.org/label/ubuntu1604_sharedlibs_debug_x64/ for the list, make sure you have just as many with your new label.
2. Add a new config to https://ci.nodejs.org/job/node-test-commit-linux-containered/, it should be clear how to add a new config by copying one of the existing ones, just make it run when the nodes match "ubuntu1604_sharedlibs_shared_x64" and copy the important bits of the config in node-test-commit-linux-as-shared-lib that's used to make it run.
3. Edit https://github.com/nodejs/build/blob/rvagg/VersionSelectorScript.groovy/jenkins/scripts/VersionSelectorScript.groovy (I'll merge this soon so it'll be on master, for now just edit it on that branch) to make it only run for the Node versions you want. You'll see a sharedlibs section in there and it should be obvious what to do.
4. Profit .. it'll take a little while to warm up the caches for the new config, there's 4 host machines these run on and all containers on those hosts share a .ccache directory so warming up just means having them run on one of the containers on each of those 4 hosts. This isn't something you need to do manually, just be aware that the first day or so will have some slower runs as it does first-time compile.

**Comment by mhdawson** [comment]
@yhwang do the does it still fail if version is <9 ?

**Comment by yhwang** [comment]
@mhdawson yes, still fails on v8.x-staging and v6.x-staging

**Comment by mhdawson** [comment]
k thanks

**Comment by mhdawson** [comment]
Added to the regular regression run in the dockerized job.  Also added jobs to run nightly for linux and AIX.  @yhwang if it also works for windows I should probably add a nightly job to test windows as well.  It is ready for us to do that?

**Comment by mhdawson** [comment]
This is an example of the job having run in the containerized job: https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_shared_x64/4458/

**Comment by yhwang** [comment]
@mhdawson I will try to run it in my windows first and get back to you.
One question about the v6.x-staging, should we still back port changes to v6.x-staging?
For v8.x-staging, I think we still need to back port changes which fix test cases failures for shared lib case. Let me work on it. Then, at least, we can enable the build in v8.x-staging.

**Comment by mhdawson** [comment]
@yhwang thanks for the update.  Let me know when you figure it out.

**Comment by mhdawson** [comment]
@yhwang should we close this as stale?
