### ISSUE TITLE
Debian 9 failing very often

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1236]
Almost every second CI that I look at has some infrastructure problems with debian 9.

Here is one: https://ci.nodejs.org/job/node-test-commit-linux/18001/

**Comment by rvagg** [comment]
I've taken that one offline, one of the two debian9 machines fails every time, the other one is green, someone .. I guess me .. will fix it later when the more important work is out of the way

**Comment by maclover7** [comment]
@BridgeAR Has this happened recently? If not, then probably safe to close for now

**Comment by maclover7** [comment]
Issue seems to have largely subsided, closing for now. Please reopen if it appears again.
