### ISSUE TITLE
alpine-latest missing autotools, libtoolize

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1244]
Can whoever added them to the libuv CI add automake+autoconf and libtool/libtoolize?

https://ci.nodejs.org/job/libuv-test-commit-linux/833/nodes=alpine-last-latest-x64/console
https://ci.nodejs.org/job/libuv-test-commit-linux/833/nodes=alpine-latest-x64/console

Also, what's the difference between the two?  last-latest is `latest^`?

**Comment by santigimeno** [comment]
Already reported in https://github.com/nodejs/build/issues/1186

**Comment by bnoordhuis** [comment]
GitHub search... didn't turn up any issues.  I'll close this but cc @rvagg as it's still an issue.
