### ISSUE TITLE
Bots + Apps in the Org

### ISSUE THREAD

**Issue by bnb** [nodejs/build#1247]
The CommComm has had an [open discussion](https://github.com/nodejs/community-committee/issues/22) for quite a while around a bot to manage the members of the organization. In addition to @williamkapke's work on that, we've got a few other things in flight that are semi-reliant on the same discussion and decision (I believe a few of these bits have been raised to the Build WG already).

I was wondering if there's an official path or resolution around adding bots and GitHub apps at this point, and what the barriers we need to cross are to get that resolved if there hasn't been.

Could y'all help me and the CommComm understand this a bit better?

**Comment by mhdawson** [comment]
@joyeecheung I you may have some insight on this base on your work on the automation side ?

**Comment by gibfahn** [comment]
>I was wondering if there's an official path or resolution around adding bots and GitHub apps at this point, and what the barriers we need to cross are to get that resolved if there hasn't been.

I don't think there's an official path, but I'd say the de facto path is:

1. Someone who understands the bot demos it at a Build WG meeting (we should also have the current Github Bot team present, I think they're technically a team under Build). We make sure that Build are happy with it (and the infra required to run it) from a technical perspective.
2. We take it to the TSC and CommComm for review (and hopefully approval).

I think it's worth going through it with Build first, as that will (hopefully) be easier.

The biggest issue here is that it's going to take a fair amount of organisational and discussion effort that @williamkapke (understandably) doesn't have time for (see https://github.com/nodejs/community-committee/issues/22#issuecomment-361692938). I think the best path forward would be for someone to handle the organisational side, and for @williamkapke (if he's willing) to attend to discuss things from a technical perspective (in at least the build meeting).
