### ISSUE TITLE
CI reports misleading

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1249]
Yesterday I merged a [PR](https://github.com/nodejs/node/pull/20026) that had a failing CI because of a wrong report in the PR.

The report was green for `node-test-commit-linux` because it only visualized `centos7` and not all linux runs together. There was also no race condition about reporting the wrong CI back (it was the only one running and it is the [correct](https://ci.nodejs.org/job/node-test-pull-request/14434/) (and failing) CI run that is visualized.

Please have a look at this as I would rather not have any CI report than one that is misleading.

![image](https://user-images.githubusercontent.com/8822573/39174756-d88081f0-47a8-11e8-9ad6-8f0fb664f7a8.png)

**Comment by BridgeAR** [comment]
Ping

**Comment by BridgeAR** [comment]
I like the idea of only reporting failures. The `node-test-commit` should always be reported though.

**Comment by refack** [comment]
Resolved (`node-test-commit-linux` only reports failures)
