### ISSUE TITLE
Please remove the `certificate safe` check

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1256]
Every collaborator is regularly on-boarded and they should know to only start the CI in case it is safe to do so.

So it seems like this check should be removed. We actually also have the possibility to start all kinds of CI runs where we do not have this check at all.

**Comment by ChALkeR** [comment]
IMO it has value as an active reminder to take a look at the code before running it through the CI.

**Comment by mcollina** [comment]
I think it’s needed. I would not enforce it on my own PRs (it seems silly), and on other collaborators PRs.

**Comment by benjamingr** [comment]
I think just having to tick a box where you indicate you understand there might be implications of running bad code has value. I like the reminder.

**Comment by BridgeAR** [comment]
Seems like it is a clear thing that others like the check. Closing.
