### ISSUE TITLE
Download ccache

### ISSUE THREAD

**Issue by LaurentGoderre** [nodejs/build#1257]
Is it possible to download the ccache file that are generated by the build?

**Comment by bnoordhuis** [comment]
It's not a file but a tree of directories with fragments in them.  If you have ccache installed locally, go to `~/.ccache` to get an idea of what it looks like.

What do you want to do with it?

**Comment by LaurentGoderre** [comment]
Sory, I meant files, I was wondering if I could get an archive with those ccache file so that I can reuse it for docker alpine build. It might help address https://github.com/nodejs/security-wg/issues/168

**Comment by bnoordhuis** [comment]
I doubt it'd be usable since the official builds compile against glibc; details from glibc's headers end up in the cache files.  `no_system_headers` disables that but it's wildly unsafe.

Is there anything stopping you from keeping your own ccache in docker-node?

**Comment by LaurentGoderre** [comment]
I am already doing this on Travis but the official image repo don't have access to them for the official build so right now it would only benefit test builds.

**Comment by LaurentGoderre** [comment]
But anyways, I wasn't sure if the ccache worked cross libc implementation thanks for the help!
