### ISSUE TITLE
Ongoing access to AIX, PPC and z/OS machines for @jbarz

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1261]
John has been helping me with issues across the IBM platforms.  There have been a number of times that he's needed access to the community machines to help recreate problems (which we don't see on IBM internal machines).

I'd like to request ongoing access across the IBM platforms for @jBarz. He has already been approved for ongoing access for z/OS here: https://github.com/nodejs/build/issues/1081 as well as temporary access for PPC to here:  https://github.com/nodejs/build/issues/1032.

I'm hoping people agree it just makes sense to allow him access across the IBM platforms as opposed to requesting each time its needed.

The latest need it to help investigate: https://github.com/nodejs/node-v8/issues/55

**Comment by mhdawson** [comment]
@nodejs/build

**Comment by mhdawson** [comment]
@joaocgreis does this sound ok to you?

**Comment by joaocgreis** [comment]
SGTM, let's keep this open so we don't forget access has been granted.

**Comment by maclover7** [comment]
Update re machines (as previously tracked in 1032, 1081, 1313): 

- test-osuosl-aix61-ppc64_be-1
- test-marist-zos13-s390x-1
- test-marist-zos13-s390x-2
- test-osuosl-ubuntu14-ppc64_le-3

**Comment by mhdawson** [comment]
Removed from 

test-osuosl-aix61-ppc64_be-1
test-osuosl-aix61-ppc64_be-2

**Comment by gdams** [comment]
@mhdawson confirmed that the machine no longer exists
