### ISSUE TITLE
Jenkins/GitHub Bot integration with GitHub Checks API

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1262]
Yesterday GitHub released the Checks API: a new status API with a lot of cool things. It would be helpful to use this new API to provide richer CI status on PRs, like showing which tests have failed, how many times the failing tests have failed in the last X runs (to help identify flaky tests easier), etc. We might even be able to re-run CIs from the GitHub interface!

More information about the API can be found in the links below:
* https://blog.github.com/2018-05-07-introducing-checks-api/
* https://developer.github.com/v3/checks/
* https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by maclover7** [comment]
Thank you for opening this issue! Started looking into this yesterday, and seems like it would require a bunch of different changes in the infrastructure that reports CI statuses to GitHub, like creating a GitHub "app" for the CI, and reworking large parts of the github-bot integration

**Comment by JasonEtco** [comment]
Thanks for the ping @bnb - I don't yet have an example repo to point you to (@swinton :wave: were you working on a Probot app using the Checks API?) but yeah, its totally doable. @gr2m correct me if I'm wrong but `@octokit/rest` is updated with the new Checks endpoints right?

**Comment by gr2m** [comment]
Yes, there are some remaining issues with it but they should get resolved tomorrow:
- https://github.com/octokit/rest.js/issues/869
- https://github.com/octokit/rest.js/issues/862

**Comment by JasonEtco** [comment]
> it would require a bunch of different changes in the infrastructure that reports CI statuses to GitHub, like creating a GitHub "app" for the CI, and reworking large parts of the github-bot integration

Yep this is correct; the Checks API is only enabled for GitHub Apps, not OAuth integrations. I'm not sure what the current GitHub bot is but it sounds like its the latter. This would indeed make for some significant changes

**Comment by swinton** [comment]
> were you working on a Probot app using the Checks API?

Yeah - https://github.com/swinton/linter-alex

**Comment by maclover7** [comment]
Thank you for the helpful links! I've got a kinda-sorta MVP up and running [here](https://github.com/maclover7/github-bot/tree/jm-checks), still using a lot of hardcoded PR numbers/data. Feel free to submit PRs against the branch! The GitHub app situation (likely needs tsc involvement) still needs to be resolved, but can probably wait a little bit.

**Comment by mmarchini** [comment]
@maclover7 I'll be traveling this weekend, but I'll try to contribute to your branch next week! 😄

**Comment by ianfixes** [comment]
I implemented this at my company.  I can't provide source, but I summarized some of the major technical hurdles (with sample code) here: https://issues.jenkins-ci.org/browse/JENKINS-51225
