### ISSUE TITLE
Discuss: upgrade required clang to 3.9

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1264]
(not sure if this issue should go here or in nodejs/node. I can move it there if needed)

One of the blocking issues to update V8 to 6.7 is related to a behavior change on clang after 3.9. There's an upstream CL (https://chromium-review.googlesource.com/c/v8/v8/+/1050666) to fix the issue for now, but I'm sure it will happen again. Upstream patches are fine as a short-term solution, but it won't take long before we start to hit bigger issues with clang version discrepancy. Besides, we're supporting a compiler version from 2014, while our oldest active release line (v6.x) was released on 2016.

I know we can't do such a huge requirement upgrade on our current release lines, but I believe we should start to plan on upgrading our minimum clang requirement to at least 3.9 (ideally 4.0) in a future semver-major (12, 13 maybe?).

Any thoughts on this?

**Comment by mmarchini** [comment]
Another one: https://github.com/nodejs/node-v8/issues/63

Seems like `thread_local` is only available on Xcode 8 and above.

**Comment by refack** [comment]
I wanted to suggest to cump the OS version to 10.12 but it seems like 10.10 and 10.11 still have a significant market share 🤦‍♂️ 
![image](https://user-images.githubusercontent.com/96947/41379897-4516eeb2-6f31-11e8-844a-2ab12d684fe5.png)

**Comment by refack** [comment]
AFAICT this can be closed (resolution was to retire 10.10 with it limited XCode for node11)
