### ISSUE TITLE
test-osuosl-aix61-ppc64_be-1 is offline

### ISSUE THREAD

**Issue by gdams** [nodejs/build#1269]
The JNLP command doesn't appear to be running on the machine so I will restart it.

**Comment by gdams** [comment]
machine is back online. we should make the aix boxes auto reconnect if they go down

**Comment by mhdawson** [comment]
The machine seems to have been failing to build since around the time JNLP was restarted

**Comment by mhdawson** [comment]
@gdams Did you start with /etc/rc.d/rc2.d/S20jenkins start?

**Comment by mhdawson** [comment]
That did not help :(

**Comment by mhdawson** [comment]
Running configure on the machine locally seems ok so still thinking it has something to do with the JLNP config

**Comment by mhdawson** [comment]
May not have properly restarted the agent, trying again.

**Comment by mhdawson** [comment]
Ok proper restart of JLNP agent with /etc/rc.d/rc2.d/S20jenkins start seems to have resolved.

**Comment by mhdawson** [comment]
May still be a problem.  Seems that build still fails on that machine.

Running a master build on the other machine to make sure it is just the one machine.  

It is failing differently now.  Seems like the addons are not building correctly

**Comment by mhdawson** [comment]
This looks like the problem:

```
#!/bin/bash -x

FLAKY_TESTS_MODE=run
if test $IGNORE_FLAKY_TESTS = "true"; then
  FLAKY_TESTS_MODE=dontcare
fi

echo FLAKY_TESTS_MODE=$FLAKY_TESTS_MODE

if [ -z ${JOBS+x} ]; then
  JOBS=$(getconf _NPROCESSORS_ONLN)
fi

PYTHON=python \
 NODE_TEST_DIR=${HOME}/node-tmp \
 FLAKY_TESTS=$FLAKY_TESTS_MODE \
 CONFIG_FLAGS="$CONFIG_FLAGS --without-ssl" \
 make run-ci -j $JOBS --output-sync=target

HAS_OPENSSL="$(out/Release/node -p 'Boolean(process.versions.openssl)')"
echo "Has OpenSSL: $HAS_OPENSSL"
if [ X"$HAS_OPENSSL" != X"false" ]; then
  FAIL_MSG="Has an OpenSSL, exiting"
  echo $FAIL_MSG
  echo "1..1" > ${WORKSPACE}/test.tap
  echo "not ok 1 $FAIL_MSG" >> ${WORKSPACE}/test.tap
  exit -1
fi
REQUIRE_CRYPTO="$(out/Release/node -p 'require("crypto")')"
if test $? -eq 0; then
  FAIL_MSG='require("crypto") did not fail, exiting'
  echo $FAIL_MSG
  echo "1..1" > ${WORKSPACE}/test.tap
  echo "not ok 1 $FAIL_MSG" >> ${WORKSPACE}/test.tap
  exit -1
fi

````
likely because agent ran as incorrect user.

**Comment by mhdawson** [comment]
I think moving the nodes directory for the citgm job has resolved the problem
