### ISSUE TITLE
Build WG Wishlist

### ISSUE THREAD

**Issue by detrohutt** [nodejs/build#1280]
I'm working on a "Wishlist" initiative to help direct volunteers to tasks around the ecosystem where help is the most needed. I'm also working on the Mentorship team as a logical extension to that, so that I'll have a constant stream of new volunteers to direct to tasks that interest them.

In the near future I plan to have a separate nodejs/wishlist (or whatever) repo where issues can be raised by any WG or initiative, but while I wait for the ok on that from commcomm, I want to go ahead and start compiling some actionable items that the Mentorship team can have our first group of mentors/mentees help with. We're planning to kick off the first round on June 15th.

Please add any specific tasks that come up that are important but need more volunteers, as well as who to ping for more information, if needed. Thanks!

**Comment by Trott** [comment]
Re-open if still relevant, but alas, seems like this is close-able... 😞
