### ISSUE TITLE
CI job for native addon verification

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#1282]
The current native addon coverage within the regular Node.js CI run is currently not adequate to cover the typical native addon cycle. This is painfully illustrated by the issue leading up to this fix: https://github.com/nodejs/node/pull/20939.

There have been discussions in the past about improving the addons support in the regular CI, but until that happens, have a CI job that specifically covers the typical native addon workflow would be ideal.

/cc @addaleax

**Comment by maclover7** [comment]
@jasnell What would the CI job run? If it's a bash script, shouldn't be too hard to setup
