### ISSUE TITLE
Add new benchmark categories.

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1283]
Right now it is not possible to run the categories `async_hooks` and `errors` even though we have benchmarks for those.

Would it actually be possible to just get all dirs in the benchmark folders on master and use the result for the categories? That way the list would be dynamic and would automatically get updated.

**Comment by mhdawson** [comment]
Can you add links to the jobs (I'm assuming its not running the benchmarks locally).  Its probably easy to add the categories to the job, but might take longer to make it dynamically generated (if possible since this is in jenkins config).

**Comment by BridgeAR** [comment]
https://ci.nodejs.org/view/Node.js benchmark/job/benchmark-node-micro-benchmarks/

**Comment by mhdawson** [comment]
Manually added async_hooks and errors.  I don't know jenkins/jenkins scripting well enough to know what it would take to dynamically populate the Choice parameter. We can leave this open in case somebody wants to volunteer to figure that out but we have a pretty good backlog for build already so I'd suggest we close unless we have a volunteer in the next month.

**Comment by BridgeAR** [comment]
Closing as outdated and done for the specific cases.
