### ISSUE TITLE
Extensive failures in CI due to docker daemon on arm

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1284]
https://ci.nodejs.org/job/node-test-binary-arm/1409/

**Comment by maclover7** [comment]
These failures are probably coming from the Pi machines restarted by @rvagg a little while ago -- it will take a little while to run `playbooks/jenkins/worker/create.yml` on these machines, so errors may persist for a while longer

**Comment by maclover7** [comment]
```
pi@test-requireio--mhdawson-debian9-armv6l--pi1p-1:~ $ systemctl enable docker
Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Authenticating as: root
Password: 
```

Looks like root password is needed

**Comment by rvagg** [comment]
`sudo systemctl start docker` will do what you want, but there's something else going on

`journalctl -u docker -n 100` reveals:

```
May 25 01:31:02 test-requireio--mhdawson-debian9-armv6l--pi1p-1 dockerd[13704]: time="2018-05-25T01:31:02.908458392Z" level=error msg="[graphdriver] prior storage driver devicemapper failed: driver not supported"
May 25 01:31:02 test-requireio--mhdawson-debian9-armv6l--pi1p-1 dockerd[13704]: Error starting daemon: error initializing graphdriver: driver not supported
```

so there's some weird compatibility thing going on.

I'll get this all sorted out today, there's a bunch of related infra rot that I've neglected for a couple of weeks while busy so I think today will be a cleanup day.

**Comment by rvagg** [comment]
OK, so I think what might be going on here is a kernel mismatch, which is one of the most awkward parts of this NFS-boot infra setup we have.

When there's a kernel update in the OS, it gets put into /boot/ along with the other kernel/boot cruft. But the real /boot/ resources that are used are loaded via tftp off a remote server. So we can get out of sync. This can be a problem when the modules in /lib/modules/ gets out of sync with the loaded kernel (like the kernel modules for the actual kernel are auto-removed during a cleanup). I think we might have a similar case to the modules thing here, in fact it could even be specifically that.

For now I might just sync the /boot/ resources but I've been considering an option where we can mount /boot/ off nfs too so it gets updated automatically. It's complicated though, for complicated infra/network reasons.

**Comment by maclover7** [comment]
Machines are largely back up, closing for now

**Comment by rvagg** [comment]
should be better now that we have /boot/ being synced #1295 so updates should be consistent
