### ISSUE TITLE
Process to join WG

### ISSUE THREAD

**Issue by VikramTiwari** [nodejs/build#1286]
Seems like current approach is to start listening in and contributing and eventually you can request access to be part of the WG. Is there a more formal process? Anything I might be missing?

**Comment by VikramTiwari** [comment]
Found it. https://github.com/nodejs/build/blob/master/doc/process/joining_the_build_wg.md

I would like to request to be part of the working group. Thanks :)

**Comment by gooodmorningopenstack** [comment]
Hi there :handshake: 

I jump in the bandwagon but I would be very keen to also join the build WG and help the NodeJS project a bit. I'll join IRC ASAP.

@VikramTiwari we can team up for Ansible refactoring and improvements if you will.

Thanks :)

**Comment by AshCripps** [comment]
Process is here - https://github.com/nodejs/build/blob/master/GOVERNANCE.md#wg-membership. Closing as stale, feel free to reopen if you are still interested.
