### ISSUE TITLE
need to cover ninja build on windows

### ISSUE THREAD

**Issue by refack** [nodejs/build#1288]
We don't cover building with `ninja` on Windows in CI. And so it broke with https://github.com/nodejs/node/pull/17604.
Besides all the usual advantages of ninja, V8 is shifting towards ninja only build system, and in IMHO having a full node build based on ninja can reduce "impedance mismatch".

**Comment by bnoordhuis** [comment]
I don't like the idea of widening the matrix for an obscure build option.  The CI is already slow and flaky enough, it doesn't need more friction.

**Comment by refack** [comment]
> I don't like the idea of widening the matrix for an obscure build option.

How about a dedicated matrix just for the build related tools and options. We have several `configure` switches and Makefile targets that are not covered as well. I agree that they unnecessary friction WRT to actual code changes, hence to the regular `node-test-commit` matrix.

**Comment by bnoordhuis** [comment]
I'd be okay with that.
