### ISSUE TITLE
libuv: test cmake build

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1292]
From https://github.com/libuv/libuv/pull/1850:
```bash
$ mkdir -p out/cmake && cd out/cmake && cmake -DBUILD_TESTING=ON ../.. && make -j8 test
# Probably needs to be something like this on Windows:
# cmake --build . --target uv_run_tests
```
It would be great if this could be tested on the CI matrix.

**Comment by refack** [comment]
Yak still has stubble, but: https://ci.nodejs.org/job/libuv-test-commit-linux-cmake/9/nodes=ubuntu1604-intel-64/console

**Comment by bnoordhuis** [comment]
Nice, thanks.  Looks like cmake doesn't auto-build but in that case `make -j8 && make test` should do the trick (and I should update libuv's README.)

**Comment by refack** [comment]
Green: https://ci.nodejs.org/job/libuv-test-commit-linux-cmake/10/

I'll add to the libuv matrix when libuv/libuv#1850 lands.

**Comment by refack** [comment]
added to matrix - https://ci.nodejs.org/job/libuv-test-commit/934/
