### ISSUE TITLE
add cmake linux binary to /downloads

### ISSUE THREAD

**Issue by refack** [nodejs/build#1293]
There's a new libuv job that needs `cmake`
could someone add https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.tar.gz to /home/downloads/www/

/CC @mhdawson @rvagg @gibfahn

**Comment by refack** [comment]
Sorry I forgot to reference https://github.com/nodejs/build/issues/1292
The job builds `libuv` with cmake.
For isolation & encapsulation the job simply downloads and untars the `cmake` binary package.
It's a 33MB file and I assume downloading it from ci.nodejs.org/downloads should be faster
```bash
#verify that the gcc version
gcc --version || true

curl https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.tar.gz | tar xzf -

mv cmake-3.11.2-Linux-x86_64 cmake-bin/

mkdir -p out/cmake

cd out/cmake

$WORKSPACE/cmake-bin/bin/cmake -DBUILD_TESTING=ON $WORKSPACE

make -j

make test
```
https://ci.nodejs.org/job/libuv-test-commit-linux-cmake/configure

**Comment by joaocgreis** [comment]
The node-chakracore jobs also need to download files. They use a function to cache the file locally. It would be good to provide this globally for the machines, but for now feel free to include this and use it in your script:

```bash
function cache_download {
  if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "Missing argument"
    return 1
  fi
  URL=$1
  EXPECTED_SHA=$2
  DEST=$3

  mkdir -p "$HOME/cache_files"
  CACHE_FILE="$HOME/cache_files/$EXPECTED_SHA"

  CACHE_SHA="X"
  if [ -f "$CACHE_FILE" ]; then
    CACHE_SHA=`shasum -a 256 "$CACHE_FILE" | cut '-d ' -f1`
  fi

  if [ "X${CACHE_SHA}" != "X${EXPECTED_SHA}" ]; then
    rm "$CACHE_FILE" || true
    curl -L "$URL" -o "$CACHE_FILE"
    DOWNLOADED_SHA=`shasum -a 256 "$CACHE_FILE" | cut '-d ' -f1`
    if [ "X${DOWNLOADED_SHA}" != "X${EXPECTED_SHA}" ]; then
      echo Downloaded SHA256 mismatch.
      rm -v "$CACHE_FILE"
      return 1
    fi
  fi

  cp -fv "$CACHE_FILE" "$DEST"
}
```

**Comment by mhdawson** [comment]
I added it to www/x86/cmake-3.11.2-Linux-x86_64.tar.gz
