### ISSUE TITLE
node-gyp: CI job broken?

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1294]
Not sure what's going on but https://ci.nodejs.org/job/nodegyp-test-pull-request/46/ (first job in quite some time) shows nothing, just that it failed.

**Comment by richardlau** [comment]
And the job only tests on Ubuntu and Windows, which is probably good enough for the common use cases, but https://github.com/nodejs/node-gyp/pull/1451 touches code that was only previously exercised on AIX.

**Comment by refack** [comment]
I'll give it a scrub-down.

**Comment by refack** [comment]
Switched platforms to: `ubuntu1604-64` & `win2016-vs2017`
and added node 10 to matrix

![image](https://user-images.githubusercontent.com/96947/40746706-20f4e09c-6429-11e8-8243-84dd3cfb2c95.png)

<sub>also added a test that PR_ID is numeric, and unified the build script to use bash on both platforms</sub>

---

As for AIX, I'd say it could stay out of the CI, and the devs involved in patches will need to be manually test.
