### ISSUE TITLE
Request to join the team

### ISSUE THREAD

**Issue by LucaLanziani** [nodejs/build#1299]
Hello there, 

following this post https://dev.to/bnb/comment/3h78 I thought that I might be able to help a bit here.

# Me

I'm a software developer based near Rome (Italy) working with nearForm.
After many years between coding and infra management, I spent the last two years full time on managing and growing an infrastructure on aws becoming even more confident with ansible/terraform/ci/cd etc etc.

# Why am I here

Even if the tweet from @bnb and the comment on dev.to convinced me already the moment I saw this picture any doubt was gone.

![ARM cluster](https://github.com/nodejs/build/blob/master/static-assets/ns-arm-cluster.jpg?raw=true)   

I'll be more than happy to help out with whatever is needed.

**Comment by maclover7** [comment]
Excellent -- welcome @LucaLanziani! First question is what tools you have experience with. We use Ansible to manage our test and release CI clusters (the main playbook lives [here](https://github.com/nodejs/build/blob/master/ansible/playbooks/jenkins/worker/create.yml)). Next, are there any platforms that you are very familiar with? We run most common OSes as part of the clusters (Fedora, Ubuntu, Alpine, Windows, OSX, SmartOS, CentOS, etc.)

My suggestion would be to take a look around the issue tracker to see the different tasks available right now, or reading through our documentation for errors

**Comment by mcollina** [comment]
Luca works for nearForm and we trust him leading the DevOp team of our largest deployment. I highly recommend him.

**Comment by refack** [comment]
Hello @LucaLanziani and welcome.

**Comment by maclover7** [comment]
@LucaLanziani Our next build WG meeting is scheduled for 4pm EST / 8pm UTC on June 12 -- if you're not fully onboarded by then, please feel free to join anyways. Once this gets a few more +1s, then we can begin that process!

**Comment by LucaLanziani** [comment]
Thanks everyone ;)

Hello @maclover7, I would say I have some fairly good experience with Ansible, I'm a long time Linux users (mostly deb based distros but I've also used rpm based ones). 

I've some experience with Docker/Terraform/Jenkins and various programming languages (Python/JavaScript/some Ruby/etc).

I'll happily start going through the issues and the ansible playbook(s).

What's your preferred channel in case I have questions? IRC? GitHub issues?

**Comment by maclover7** [comment]
@LucaLanziani Probably IRC, but whatever's easiest. Most build team members are in the `#node-build` channel

**Comment by LucaLanziani** [comment]
I'm going to close this since https://github.com/nodejs/build/pull/1374 was merged and I'm now listed as member.
