### ISSUE TITLE
request to join the build group

### ISSUE THREAD

**Issue by danbev** [nodejs/build#1303]
I'd like to join the build working group so that I can troubleshoot failure on CI servers.

Thanks

/Dan

**Comment by Trott** [comment]
+1!

**Comment by maclover7** [comment]
Excellent -- welcome @danbev! Are there any platforms that you are very familiar with? (At some point we want to make a list of who knows which platforms very well)

Also, just so we know, are you looking to help out with the Ansible/automation side at all, or just helping with different flaky tests/failures? Both are very very useful

**Comment by Trott** [comment]
@danbev I forget, do you work on/with OpenShift?

**Comment by Trott** [comment]
There is a Build WG onboarding proess. I think @rvagg or @mhdawson might be the right person to do it? Maybe? Either of you want to volunteer?

**Comment by danbev** [comment]
> Also, just so we know, are you looking to help out with the Ansible/automation side at all, or just helping with different flaky tests/failures?

I mostly interested in being able to attempt to fix CI failures when for my pull requests instead of just reporting them as not related and moving on.

**Comment by danbev** [comment]
> I forget, do you work on/with OpenShift?

Yep, our main deployment environment is OpenShift.

**Comment by maclover7** [comment]
@danbev Our next build WG meeting is scheduled for 4pm EST / 8pm UTC on June 12 -- if you're not fully onboarded by then, please feel free to join anyways. Once this gets a few more +1s, then we can begin that process!

**Comment by refack** [comment]
Hello @danbev and welcome.

**Comment by danbev** [comment]
@refack Thanks! 😄

**Comment by Trott** [comment]
I believe @danbev is unavailable for most or all of July but hopefully we can pick this up again at the end of July or beginning of August.

**Comment by gibfahn** [comment]
+1, @danbev if you could raise a PR adding yourself to the README (like https://github.com/nodejs/build/pull/1374) then people can approve it and sort out onboarding.

**Comment by Trott** [comment]
@danbev Still interested? Is there anything we can do on the Build WG side to increase your interest?

**Comment by danbev** [comment]
@Trott Sorry, I did not realise this was still open. I don't have time at the moment I'm afraid.
