### ISSUE TITLE
Update stress-test RUN_LABEL pulldown menu

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1304]
https://ci.nodejs.org/job/node-stress-single-test/build?delay=0sec

The pulldown doesn't list all buildbots.  I wanted to stress-test on ubuntu1604_sharedlibs_debug_x64.

**Comment by maclover7** [comment]
@bnoordhuis Updated the job configuration, can you verify works for you now

**Comment by bnoordhuis** [comment]
It's there, thanks, but it's still missing the other sharedlibs builds, possibly others too.  Ideally, all individual buildbots from node-test-commit are selectable.

**Comment by maclover7** [comment]
@bnoordhuis Unfortunately that list is compiled manually, so all labels are not automatically included. If there are other labels you'd like there, just comment them here and I can add them

**Comment by bnoordhuis** [comment]
@maclover7 Can you add the other buildbots from https://ci.nodejs.org/job/node-test-commit-linux-containered/?  Cheers.

**Comment by maclover7** [comment]
@bnoordhuis updated, PTAL

**Comment by bnoordhuis** [comment]
Thanks, look good.  I'll close this out.
