### ISSUE TITLE
Build WG self-nomination: mmarchini

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1308]
From https://github.com/nodejs/summit/issues/64#issuecomment-393877576:

> I'm interested in participating more in the Build WG (currently participating in a few issues, working on a [CI Job Health Dashboard](https://nodejs-ci-health.mmarchini.me/) and llnode jobs on Jenkins (not sure we still want to pursue this last one though).
> 
> I'm also interested in helping the Commit Queue Prototyping Team, if possible.

**Comment by maclover7** [comment]
@mmarchini Our next build WG meeting is scheduled for 4pm EST / 8pm UTC on June 12 -- if you're not fully onboarded by then, please feel free to join anyways. Once this gets a few more +1s, then we can begin that process!

**Comment by mmarchini** [comment]
Looking forward to help the WG wherever I can!
