### ISSUE TITLE
Add new build jobs

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1309]
Talking to @hashseed it came up that there are multiple interesting V8 flags that could help us finding bugs early by stressing the specific issues.

Some of these are:

* `--gc-interval=value`. If we set that to e.g. 500 it will trigger a gc each 500 allocations.
* `--stress-compaction` which forces more compactions than it would do normally (it will move objects around all the time).
* `--verify-heap` to verify consistency of all objects on the heap (e.g., that all strings have a number as a length). To do this the build has to be built with the gyp flag `v8_enable_verify_heap`.

They should all be run as a debug build. Since they are pretty expensive they should only run once a day and it would probably also be enough to only running this one on linux.

Is this something you could have a look at? :-)

**Comment by maclover7** [comment]
Seems reasonable to me. If we want to only run this once a day, should this be triggered as part of `node-daily-master`?

**Comment by maclover7** [comment]
ping @BridgeAR

**Comment by BridgeAR** [comment]
@maclover7 yes, that would be ideal!
