### ISSUE TITLE
Grant jBarz access to aix61-ppc64 to investigate failures

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1313]
See https://github.com/libuv/libuv/pull/1787#issuecomment-394437377.  I vouch for @jBarz.

**Comment by maclover7** [comment]
I believe @jBarz already does have access to AIX via https://github.com/nodejs/build/issues/1261? Also, is there a specific hostname that is needed?

**Comment by jBarz** [comment]
@maclover7 
The issue in libuv is happening on ` test-osuosl-aix61-ppc64_be-2`
The issue https://github.com/nodejs/build/issues/1261 gives me access to only ` test-osuosl-aix61-ppc64_be-1`

**Comment by mhdawson** [comment]
https://github.com/nodejs/build/issues/1261 is a blanket ok for access, we just need to give him access.

**Comment by refack** [comment]
Granted

**Comment by jBarz** [comment]
Issue resolved, We can close this now.
