### ISSUE TITLE
[Request] Extra build configurations for libuv

### ISSUE THREAD

**Issue by saghul** [nodejs/build#132]
Ohai!

I have a small request. Currently we have a single configuration (or is it a "project"?) that we can use to test PRs in libuv: libuv+any-pr+multi. If possible I'd like to have a configuration that does the same but only for Windows, OSX or Linux respectively.

Thanks!

PS: If I can do this myself with my current Jenkins account please let me know so I don't bother you in the future :-) (I couldn't find how to do it so far)

**Comment by rvagg** [comment]
@saghul yep, we can do this, we've done it for the iojs ones and the upcoming converged iojs/node ones too and so far I'm liking this although @orangemocha objects to the complexity!

I have some other work I want to do to bring the libuv jobs up to scratch; how much of a hurry is this for you @saghul?

**Comment by saghul** [comment]
No rush whatsoever Rodd! Thanks for the prompt response.

**Comment by orangemocha** [comment]
Please disregard my objections :wink: I just noted that managing one job is a bit easier than managing 5 when you make configuration changes. But other folks in the build team pointed out the better reporting available with separate jobs, so I am neutral by now.

**Comment by saghul** [comment]
Since I'm here, I'll add another item to my initial request: 2 extra targets for Windows, which run the tests on the shared library build. (it should fail now, I have an open PR which will land today fixing that)

**Comment by jbergstroem** [comment]
@saghul do you support auto* on windows as well or is that gyp-only?

**Comment by saghul** [comment]
@jbergstroem We do support MinGW-w64 toolchain, but I didn't want to put more weight into the build team's shoulders :-)

**Comment by jbergstroem** [comment]
@saghul lets stick with gyp for now then. I can probably look at adding this tomorrow.

**Comment by saghul** [comment]
Great, thanks!

**Comment by rvagg** [comment]
derp

**Comment by Trott** [comment]
Looking at https://ci.nodejs.org/view/libuv/, I *think* this can be closed as I see stuff for Windows, AIX, etc. I'm going to Be Bold and close this, but feel free to re-open or comment if I'm mistaken. This issue hasn't been updated in over a year, so I strongly suspect the situation has changed since it was last updated.
