### ISSUE TITLE
Link in README returns a 404

### ISSUE THREAD

**Issue by davidwkaiser** [nodejs/build#1322]
The link in the README that promises information on how to join returns a 404 page. 

Also, I'm interested in joining.

**Comment by richardlau** [comment]
Looks like this was missed in https://github.com/nodejs/build/pull/1315 which moved the information into https://github.com/nodejs/build/blob/master/doc/access.md#joining-the-build-working-group.

**Comment by davidwkaiser** [comment]
Submitted.
