### ISSUE TITLE
SSH access to Pi 1 device for eugeneo

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1326]
To troubleshoot https://github.com/nodejs/reliability/issues/5, @eugeneo asked for SSH access to one of the Raspberry Pi 1 devices where we are seeing the failures. This seems like a low-risk no-brainer to me. If a couple other Build WG folks give this a :+1:, I'll make it happen.

**Comment by Trott** [comment]
I think this might not be necessary now, as we've figured out a few things (although not everything).

@eugeneo If I'm wrong and you still want/need access, leave a comment or re-open. Thanks!

**Comment by rvagg** [comment]
ping me on irc if this is needed, it's not too difficult
