### ISSUE TITLE
Assembler missing on smartos 16 machines?

### ISSUE THREAD

**Issue by targos** [nodejs/build#1327]
[`node-test-commit-smartos`](https://ci.nodejs.org/job/node-test-commit-smartos/) is consistently failing on `smartos16-64` with this message:

```
04:37:19 python ./configure 
04:37:20 WARNING: C++ compiler too old, need g++ 4.9.4 or clang++ 3.4.2 (CXX=g++)
04:37:20 ERROR: Did not find a new enough assembler, install one or build with
04:37:20        --openssl-no-asm.
04:37:20        Please refer to BUILDING.md
04:37:20 make: *** [Makefile:462: build-ci] Error 1
04:37:20 Build step 'Execute shell' marked build as failure
04:37:20 Checking ^not ok
```

**Comment by maclover7** [comment]
Re-running playbook on machines, hopefully may fix

**Comment by maclover7** [comment]
SmartOS rebuild: https://ci.nodejs.org/job/node-test-commit-smartos/18225/

**Comment by targos** [comment]
Looking good so far. Thanks!

**Comment by Trott** [comment]
It's back....

**Comment by Trott** [comment]
https://ci.nodejs.org/job/node-test-commit-smartos/18227/nodes=smartos16-64/console

```console
12:53:02 ERROR: Did not find a new enough assembler, install one or build with
12:53:02        --openssl-no-asm.
12:53:02        Please refer to BUILDING.md
```

**Comment by Trott** [comment]
Is the right thing to do this?

```
ansible-playbook playbooks/jenkins/worker/create.yml --limit "test-joyent-smartos16-x64-1"
```

Or something else? I'm not sure if that's the playbook to rebuild in this case. (Doesn't work for me in any event, but I'll try to figure out why that playbook doesn't work when run from my machine if it's the right one to run.)

**Comment by Trott** [comment]
Seems like `pkgin in llvm-3.8.0nb2` would be likely to fix the issue. Going to try that on test-joyent-smartos16-x64-1 and see what happens.

**Comment by Trott** [comment]
Nope, didn't fix it.

**Comment by Trott** [comment]
I did `pkgin rm llvm-3.8.0nb2` to remove the package I installed.

The problem appears to be that `configure` is not detecting that `gas` is installed. `/opt/local/bin/gas --version` reports the version as 2.26. The script wants 2.23 or later, but it appears that `get_gas_version` is returning `0`, so something is up in that function I guess?

**Comment by Trott** [comment]
I was stepping through the Python code and this started working. I hope someone fixed it... because otherwise... this is mysterious, in a bad way. :-D

**Comment by Trott** [comment]
Only login besides me is from Cambridge, Massachussetts. Sounds like @refack fixed it?

**Comment by refack** [comment]
Sorry I'm trying to fix it, but getting weird stuff

**Comment by refack** [comment]
As in I have no idea why it sometimes work, and sometimes not.

**Comment by refack** [comment]
Well it is https://github.com/nodejs/node/pull/20394.
In some situations on smartos you cannot change the locale.

**Comment by Trott** [comment]
> In some situations on smartos you cannot change the locale.

Interesting. Any idea what those conditions are?

**Comment by Trott** [comment]
Looks like it works with setting `LC_ALL` to `en_US.UTF-8` instead of just `en_US`.
