### ISSUE TITLE
Build WG: Discuss new projects

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1330]
This meeting will be to discuss the current state of the Build working group, as well as new projects and ideas moving forward. Everyone has a stake in the Build WG's continued success, given the critical infrastructure that the group provides.

Agenda items (please edit this liberally!):

|Name|Champion(s)|
|---|---|
|New members|@maclover7|
|Ansible upgrades|@maclover7, @rvagg|
Commit queue|@joyeecheung, @tniessen|
|Tracking failures in `node-test-commit` (`nodejs/reliability`, etc.)|@joyeecheung|
|`github-bot`|@maclover7, @phillipj|
|Improving current jobs|@refack|
|Auto CI|@refack, @maclover7|
|Automatic maintenance (allowing scripted `kill` and `rm` by anyone)|@refack|

@nodejs/build @nodejs/commit-queue @nodejs/tsc

**Comment by maclover7** [comment]
Please RSVP via this doodle: https://doodle.com/poll/8hgewz9nem63arb7

**Comment by ryzokuken** [comment]
I hope it's okay if outsiders join in as observers? I had stuff to talk about regarding `ncu-ci` and the bots.

**Comment by maclover7** [comment]
@ryzokuken No problem, but we will be sticking with whatever the final agenda is, given the number of topics we have to go over

**Comment by tniessen** [comment]
Something came up, I won't be able to attend that day, sorry.

**Comment by ryzokuken** [comment]
I'd love to come on as an observer today and talk about one of the things I have been talking about to @refack and @joyeecheung.

An automation for not only reporting test failures straight to the GH PRs, but more broadly to differentiate code failures from infra one, and then how to ping responsible people for infra fails (the GH path works well for code fails), and also discussion how and who to keep responsible for such stuff.

**Comment by mmarchini** [comment]
I probably won't be able to attend as well

**Comment by refack** [comment]
@mhdawson / @Trott Will you be there to broadcast?

**Comment by Trott** [comment]
This is today at 4PM Eastern/1PM Pacific, right? I probably can't make it as I have a conflicting meeting.

**Comment by refack** [comment]
https://zoom.us/j/808619262

**Comment by joyeecheung** [comment]
Minutes: https://docs.google.com/document/d/12ZyOGLl0xmqRBin71SVGJHAohgOMKMFHyxyISFKFshE/edit?usp=sharing

**Comment by refack** [comment]
Meeting part 2
https://zoom.us/j/785639351
