### ISSUE TITLE
run `make test-v8-updates` as a sub-job of `node-test-commit-v8-linux`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1342]
As discussed in https://github.com/nodejs/build/issues/1274 and https://github.com/nodejs/node/pull/20783, we should add a sub-job to `node-test-commit-v8-linux` which runs `make test-v8-updates` on a Ubuntu 16.04 machine, otherwise tests for missing postmortem metadata and for Linux perf won't run during V8 updates.

**Comment by maclover7** [comment]
@mmarchini Can you please prepare the full bash script for the job, and then I can drop that into a new job and setup the configuration for you

**Comment by mmarchini** [comment]
Sure. The script should look like https://github.com/nodejs/build/pull/1329/files, right?

**Comment by mmarchini** [comment]
`v8-updates` are running for `node-test-commit-v8-linux`, so this can be closed.

Ref: https://github.com/nodejs/build/pull/1344 and https://github.com/nodejs/build/pull/1344#issuecomment-398144436
