### ISSUE TITLE
Missing compiler on macos ??

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#1345]
See: https://ci.nodejs.org/job/node-test-commit-osx/19308/nodes=osx1010/console

```
19:13:10 ERROR: No acceptable C compiler found!
19:13:10 
19:13:10        Please make sure you have a C compiler installed on your system and/or
19:13:10        consider adjusting the CC environment variable if you installed
19:13:10        it in a non-standard prefix.
19:13:10 make: *** [build-ci] Error 1
```

**Comment by maclover7** [comment]
Hmm haven't seen this one before, taking a look

**Comment by maclover7** [comment]
Looks like the errors are only appearing on test-macstadium-macos10.10-x64-1

**Comment by maclover7** [comment]
Am able to get compiler running locally, going to try and restart the Jenkins agent

**Comment by jasnell** [comment]
Thank you @maclover7 ... definitely appreciate it. I hadn't seen it before either. Happened on two different CI runs.

**Comment by maclover7** [comment]
Hmm ran `playbooks/jenkins/worker/create.yml` and still getting errors (https://ci.nodejs.org/job/node-test-commit-osx/19311/nodes=osx1010/console)

cc @gdams @nodejs/platform-macos

**Comment by refack** [comment]
`test-macstadium-macos10.10-x64-1` has been really weird today up until [job 19303](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1010/19303/) it refused to even run `git`

**Comment by maclover7** [comment]
@jasnell I updated `node-test-commit-osx` to only build on the other 10.10 machine for now (trying a test job against master at https://ci.nodejs.org/job/node-test-commit-osx/19313/nodes=test-macstadium-macos10.10-x64-2/console). I'm rebooting and taking a closer look at the problem machine

**Comment by maclover7** [comment]
> @maclover7 FYI you can simply mark the machine as offline in https://ci.nodejs.org/computer/test-macstadium-macos10.10-x64-1/

Yep, I just wanted to see if there was a quick fix before I marked the machine offline

Fix should be in d63e66f, turns out zos scripts were being used on Mac, which didn't end well... Restarted those two OSX builds @jasnell, hopefully should be green now

**Comment by jasnell** [comment]
Thank you very much!

**Comment by gdams** [comment]
thanks for picking this up @maclover7. are the builds now passing on `test-macstadium-macos10.10-x64-1`?

**Comment by maclover7** [comment]
@gdams Builds are now passing, going to close this for now
