### ISSUE TITLE
RFE: GPG key for security@nodejs.org

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1346]
Continuing from https://github.com/nodejs-private/security/issues/79:

Set up a GPG key and publish the public key on the website so that people reporting vulnerabilities to security@nodejs.org can encrypt their email before sending.

To be resolved:

1. How to store the private key
2. How to give triagers access (subkeys?)

**Comment by maclover7** [comment]
> 1. How to store the private key

My recommendation would be in `nodejs-private/secrets`, likely in the "infra" access group, given how important it is

> 2. How to give triagers access (subkeys?)

The email configuration currently has `security@nodejs.org` being forwarded to a HackerOne email -- is it worth an email over to their support line and see whether they have any support for GPG emails?

**Comment by maclover7** [comment]
(Also, just a note, I can't see that issue)

**Comment by bnoordhuis** [comment]
You didn't miss anything, it's mostly just what I wrote. :-)  `nodejs-private/secrets` sounds like a good place.

@MylesBorins You've been in contact with the H1 people before, haven't you?

**Comment by refack** [comment]
If H1 don't have that built in then members of security@nodejs.org will need access, so maybe add and independant `/security` subdir to `secrets`

**Comment by bnoordhuis** [comment]
cc @sam-github I know you've been talking to MITRE about GPG keys and everyone else uses H1 now. You can close it out if you want if this issue is no longer relevant.

**Comment by sam-github** [comment]
Well, actually, I failed to get communication between Mitre and us, I think they were only willing to use email, so they didn't tell us about the HTTP/2 vulns.

Now, it turns out we already knew about them, so no harm done, but at least for Mitre specifically, we should set up gpg keys.

All to say, this isn't quite over.
