### ISSUE TITLE
Email for the github-bot

### ISSUE THREAD

**Issue by phillipj** [nodejs/build#1354]
Currently the @nodejs-github-bot account is setup with an alias to my @gmail.com email. That's far from ideal as no one else than me can get a hold of emails sent to that account. Recently we had a couple of important emails from GitHub (https://github.com/nodejs/build/issues/1341, https://github.com/nodejs/build/issues/1353#issuecomment-397847319) where it would have been beneficial if more people could double check the bot's inbox.

Do we have an email account suited for this already, or should we create one?

/cc @nodejs/github-bot

**Comment by richardlau** [comment]
The existing organization email addresses are mapped in https://github.com/nodejs/email

**Comment by rvagg** [comment]
yeah, just make a new alias in a PR to nodejs/email, put yourself and anyone else in the github-bot team onto it and we'll get it merged and deployed, then you can transfer it

**Comment by maclover7** [comment]
+1 to an alias, members should probably be `nodejs/github-bot`?

**Comment by phillipj** [comment]
Liked @maclover7 suggestion about the initial team members, opened https://github.com/nodejs/email/pull/102.

**Comment by mmarchini** [comment]
Closing since https://github.com/nodejs/email/pull/102 landed. Feel free to reopen if there's anything else to be done here.
