### ISSUE TITLE
OS X 10.11 inclusion timing

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#136]
We could potentially add 10.11 at any time on our current infra but given it's not released yet, _should_ we?

I'm concerned about issues like this https://github.com/nodejs/io.js/issues/2165 and am thinking that maybe we should be ahead of the curve here, like with MSVS 2015, to make sure we're ready for when it drops on users and they start using Node/io.js. My understanding is that we may have a couple of months until this drops; "fall 2015" which always feels too vague for southern hemespherians.

**Comment by jbergstroem** [comment]
I think its a great idea. The more machines we test against the better if you ask me. What we need to figure out longer term is rather which machines we deem as "must pass" versus "heads up".

**Comment by srl295** [comment]
nodejs/io.js#2165 was a bugfix (according to my sources) — it would give opportunity for node to feed bug reports upstream!  Possibly not so much OS bugs per se, but could give tooling feedback (headers and such).  Tooling fixes could prevent more headaches later.

**Comment by silverwind** [comment]
If we have the opportunity to test unreleased platforms, I'd say go for it. I need to do more research on  #2165 before I can do anything about it. Does the CI have an option to skip certain tests like because of known issues? Might be good for this case, as I don't really want to land a workaround for it.

**Comment by Trott** [comment]
Closing in favor of #367. Feel free to re-open or comment if you think that's an error.
