### ISSUE TITLE
Outgoing email address for 3rd party vulnerability notification

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1361]
We'd like to be able to send out emails from a node.js email account when we notify maintainers of 3rd party module maintainers.

I know how to setup aliases which are incoming (ie when they hit a particular address a list of people get notified). But I've not setup an outgoing one.

@rvagg @jbergstroem @joaocgreis if either of you three can point me to any existing doc (or know how to do it if there is no doc), that would be great.

**Comment by maclover7** [comment]
@mhdawson Mailgun's got an API for sending emails: https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-via-api

**Comment by rvagg** [comment]
@mhdawson what sort of tooling will be sending these emails? is there an existing application that we're just plugging an email address in to?

If we want it to come from a @nodejs.org email address then we're probably going to be best off making an email address for it in the G Suite for nodejs.org which the Foundation manages and then send email via SMTP through Google using the credentials for that account. If you don't want to do it that way then we're going to have to get the nodejs.org SPF record updated to include whatever mail sending mechanism you'd like to use. I think I'd recommend just going the SMTP route. Email the Linux Foundation helpdesk and get them to make a new email address and give you the credentials for it and enable SMTP and probably a per-app password for that account.

If you're OK sending from iojs.org then we have SPF set up for that domain to allow Mailgun sending and you can use the API that @maclover7 pointed to.

**Comment by mhdawson** [comment]
@vdeturckheim does doing "and then send email via SMTP through Google using the credentials for that account."  as suggested by @rvagg above work for the bot you have setup?

**Comment by vdeturckheim** [comment]
@rvagg @mhdawson at this tim I use mailjet API for sending emails but nodemailer should work with a G Suite email address. That's not really big changes on my side.

**Comment by rvagg** [comment]
Oh, I just remembered that we manage the DNS for both nodejs.org and iojs.org, so it's trivial for us to alter the SPF for both so we could use mailgun for @nodejs.org or even mailjet (first I've heard of them but I assume they have restrictions in place that would stop any other mailjet user from sending as @nodejs.org?).  So @vdeturckheim & @mhdawson just make a call and we'll make it happen.

**Comment by vdeturckheim** [comment]
@rvagg I'll run a quick compare between mailgun and mailjet to see which one suits our needs best here. Probably running this on the WE :)

**Comment by mhdawson** [comment]
@vdeturckheim is this something we'd still like to do?

**Comment by vdeturckheim** [comment]
Indeed this stalled and the system seems to work ATM. closing for now :)

**Comment by mhdawson** [comment]
Closing
