### ISSUE TITLE
Add my SSH keys for releases

### ISSUE THREAD

**Issue by targos** [nodejs/build#1366]
Now that I am in the Release team, can someone please add my SSH keys to the dist user on the www machine? I'm going to prepare the next v10.x release.

Ref: https://github.com/nodejs/Release/blob/master/GOVERNANCE.md#adding-new-releasers

> SSH keys need to be added to the dist user on the www machine

@nodejs/build-infra

**Comment by gibfahn** [comment]
Where are your ssh keys?

**Comment by targos** [comment]
Perfect, thank you! Is there a more memorable host name?

**Comment by gibfahn** [comment]
I always find it by looking for `www` in [inventory.yml](https://github.com/nodejs/build/blob/master/ansible/inventory.yml), I'm not aware of a better hostname.

Of course it shouldn't be too difficult to add the aliases in that file to the [ssh config playbook](https://github.com/nodejs/build/blob/master/ansible/playbooks/write-ssh-config.yml).

**Comment by refack** [comment]
> Of course it shouldn't be too difficult to add the aliases in that file to the ssh config playbook (maybe raise an issue for that).

The really interesting part is https://github.com/nodejs/build/blob/master/ansible/plugins/inventory/nodejs_yaml.py

**Comment by refack** [comment]
even better, it seems to already be there:
https://github.com/nodejs/build/blob/4f7937e0937dc65ddacfca5c50677b642f582a16/ansible/inventory.yml#L15

Should give you
```
Host infra-digitalocean-ubuntu1604-x64-1 www
```

**Comment by gibfahn** [comment]
>even better, it seems to already be there:

Good point, it totally works. Not sure how I missed that previously.

**Comment by targos** [comment]
I don't have ansible (and never used it)so I'll stick with the long name for now but it's good to know!

**Comment by gibfahn** [comment]
>I don't have ansible (and never used it)so I'll stick with the long name for now but it's good to know!

How did you get the long name in your `~/.ssh/config` if not by running the ansible script?

If you're sshing into node machines at all, it's really useful to do:

```bash
git clone https://github.com/nodejs/build && cd build
pip2 install ansible
echo "# begin: node.js template\n\n# end: node.js template" >>~/.ssh/config
ansible-playbook playbooks/write-ssh-config.yml
```

It just writes a block of code into `~/.ssh/config`.

**Comment by targos** [comment]
I just did `ssh dist@infra-digitalocean-ubuntu1604-x64-1.nodejs.org`

Will try with ansible next time. Thank you!

**Comment by joyeecheung** [comment]
@targos In case you want to know more, there is a new guide on SSH access now: https://github.com/nodejs/build/blob/master/doc/ssh.md

In terms of https://github.com/nodejs/Release/blob/master/GOVERNANCE.md#adding-new-releasers is there a reason not to add a new access group for releasers in the secrets repo and use a shared key?

**Comment by refack** [comment]
> I just did ssh dist@infra-digitalocean-ubuntu1604-x64-1.nodejs.org

😸 
In that case dist@x.nodejs.org should work just as well (nodejs.org and www.nodejs.org are CloudFlare proxies, but every other *.nodejs.org is aliased to 138.197.224.240)

**Comment by refack** [comment]
> In terms of nodejs/Release:GOVERNANCE.md@master#adding-new-releasers is there a reason not to add a new access group for releasers in the secrets repo and use a shared key?

AFAIK the use of a shared key (e.g. for `test` and `release`) was started when it was needed to allow access to many computers at the same time. If it's just the one account on the one computer IMHO `authorized_keys` is easier to manage & audit.

**Comment by gibfahn** [comment]
>If it's just the one account on the one computer IMHO authorized_keys is easier to manage & audit.

Agreed that it's probably easier to manage, but from an auditing and keeping history point of view, it's probably better to do it in secrets.
