### ISSUE TITLE
OSU - AIX Service window June 21 9-12 Pacific.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1369]
The Power hardware supporting the AIX machines for our CI (and others) needs to be patched and rebooted.  They planned window is [9-12](http://www.wolframalpha.com/input/?i=9AM+21st+June+pacific+in+local+time), but will hopefully come back earlier.

**Comment by gdams** [comment]
I'm going to shutdown the test OSUOSL AIX machines at [8:45](http://www.wolframalpha.com/input/?i=8:45AM+21st+June+pacific+in+local+time) Pacific time

**Comment by gdams** [comment]
Both AIX test machines have now returned and builds appear to be passing. I'll wait for @mhdawson who has ci-release access to confirm functionallity of the release machine and then we can close.

**Comment by mhdawson** [comment]
@gdams bit confused as both builds failed opened: https://github.com/nodejs/node/issues/21451

**Comment by mhdawson** [comment]
Job to validate release CI is ok https://ci-release.nodejs.org/job/iojs+release/3514/

**Comment by mhdawson** [comment]
There was  some "fun" with the release machine as we need to be more diligent about cleaning up `/etc/security/failedlogin`.

**Comment by mhdawson** [comment]
Release test build was ok, so looks goon on that front.  Hoping that restart of agent on test machines helps the issues we saw there.

**Comment by gdams** [comment]
test machines appear to be building okay now. closing

**Comment by refack** [comment]
> There was some "fun" with the release machine as we need to be more diligent about cleaning up /etc/security/failedlogin.

We had the same with the `test-*` machines. I changed sshd per https://github.com/nodejs/build/issues/866#issuecomment-328583989
