### ISSUE TITLE
Get VS2015 into the mix

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#137]
We have support for this in core now and we've had a testing machine trialling this but it's about to be officially launched on July the 20th: https://www.visualstudio.com/visualstudio-release-event-vs

There's no huge urgency to get it into the mix straight away but we should make an effort because we can expect people starting to build with it.

**Comment by jbergstroem** [comment]
@joaocgreis had done a great job in adding all of this through azure. Closing.
