### ISSUE TITLE
node-test-commit-v8-linux

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1370]
Looks like node-test-commit-v8-linux is failing on 10.x for x86.  

https://ci.nodejs.org/job/node-test-commit-v8-linux/1452/

I think it may be related to recent updates to tweak what tests run.  @refack can you take a look as I think you made those updates.  The job failing is: node-test-commit-custom-suites

**Comment by mmarchini** [comment]
`test/v8-updates` is not on v10.x yet and the job is trying to run them anyway. We might want to limit this job to run only on `master` for now.

**Comment by mhdawson** [comment]
Closing this is stale
