### ISSUE TITLE
Build meeting on elevated permissions

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#1373]
I set up a doodle using data from the TSC time sheet and the last doodle about build projects: <del>https://doodle.com/poll/ixwgyxa68igzrz8i</del>
New Doodle: https://doodle.com/poll/tecqbir56397b9wh

Refs: https://github.com/nodejs/build/issues/1337

Agenda:

- Reasoning and alternatives for direct access to the machines
- Reasoning and alternatives for direct access to repos
- Better organization of the ACL and secrets management
- Accountability issues
- Summary about request to the TSC or the board

@nodejs/build @nodejs/tsc

**Comment by joyeecheung** [comment]
Also cc in person @Trott @mhdawson @gibfahn @rvagg @maclover7 @refack in case notifications get lost

**Comment by Trott** [comment]
Probably a good idea to figure out ahead of time who is going to facilitate the meeting. It doesn't have to be (and perhaps shouldn't be) someone with strong opinions about the topic. Just needs to be someone who is willing to understand the concerns and have a clear idea of what the outcomes of the meeting should be.

**Comment by rvagg** [comment]
no overlapping time between myself Jon and Michael so far unfortunately

**Comment by joyeecheung** [comment]
@rvagg Do you have some time slots friendly to people in EDT? (I think that's where @maclover7 @mhdawson and @refack are in) I picked the time using the TSC time sheet but that's Wednesday only.

**Comment by joyeecheung** [comment]
@rvagg OK, I've created a new doodle (I tried to edit the original one but I think many people do not have a doodle account so they cannot edit their previous vote, so might as well create a new one)

https://doodle.com/poll/tecqbir56397b9wh

New options are:

8:30am UTC+10 - 6:30pm UTC+4
9am UTC+10 - 7pm UTC+4
10am UTC+10 - 8pm UTC+4
10pm UTC+10 - 8am UTC+4

Please update your vote there, thanks!

**Comment by joyeecheung** [comment]
Looks like we missed the time to get @rvagg and @maclover7 in the same meeting. I will close this one for now and defer to another form of meeting/emails.
