### ISSUE TITLE
Request for elevated access - gdams

### ISSUE THREAD

**Issue by gdams** [nodejs/build#1375]
There have been multiple times where I would have found having the script console available in jenkins to be very useful to diagnose jenkins issues with machines. What level of access is required to get this access and what would be the process to obtain it?

**Comment by rvagg** [comment]
jenkins-admins. I'm +1 on elevating @gdams' access.

**Comment by refack** [comment]
+1

**Comment by mhdawson** [comment]
+1, @gdams has joing IBM full time and I'm looking for him to take ownership of keeping testing on the IBM platforms in good shape as well as helping with other platforms.

**Comment by refack** [comment]
Done.
@gdams ping me, we'll do a few minutes of onboarding.
