### ISSUE TITLE
Trigger `node-test-commit-v8-linux` as a downstream project of `node-update-v8-canary`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1379]
`node-update-v8-canary` only runs `make test-ci` and `make lint-ci`. It would be nice to also run `make test-v8` and `make test-v8-updates`. Since both are run by `node-test-commit-v8-linux`, adding it as a downstream project of `node-update-v8-canary` should be enough.

If there are no objections I can work on it next week.

/cc @targos

**Comment by targos** [comment]
`node-update-v8-canary` triggers a custom version of `node-test-commit` called `node-test-commit-node-v8`. I just added `node-test-commit-v8-linux` to it. Let's see how it goes: https://ci.nodejs.org/view/MyJobs/job/node-test-commit-node-v8/60/

**Comment by targos** [comment]
New build (Jenkins was having issues): https://ci.nodejs.org/view/MyJobs/job/node-test-commit-node-v8/61/

**Comment by mmarchini** [comment]
Yep, it's working (postmortem tests reported a missing constant :) ). Thanks!

**Comment by targos** [comment]
> postmortem tests reported a missing constant :)

Where do you see that?

**Comment by targos** [comment]
Ah ok, the subjob is only accessible from the output log. Can we fix that?

**Comment by mmarchini** [comment]
You can access through the nodes=benckmark subjobs:

![image](https://user-images.githubusercontent.com/4048656/41786571-b6539ba0-75fa-11e8-9cd1-5b015590c1a9.png)

It's still kinda cumbersome, but at least we don't need to go through the output log. We probably should improve this in the future though.

**Comment by targos** [comment]
OK! I was searching for it at the bottom of the page 🙃

**Comment by targos** [comment]
Can we close this issue?
