### ISSUE TITLE
node-test-commit-v8-linux: use test-nearform_intel-ubuntu1604-x64-1 instead of infra-softlayer-ubuntu1404-x64-2

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1381]
While trying to fix the CI issues reported in https://github.com/nodejs/node/pull/21334 I found out we use an `infra-softlayer-ubuntu1404-x64-2 ` in `node-test-commit-v8-linux`. This is an infra machine, so not everyone from the Build WG has access to it. Since this is a test job and is run quite frequently, it would be a good idea to change the machine to a test machine. @refack suggested `test-nearform_intel-ubuntu1604-x64-1`.

I added `test-nearform_intel-ubuntu1604-x64-1` to `node-test-commit-v8-linux`, but kept `infra-softlayer-ubuntu1404-x64-2` since I was not sure if we needed to support Ubuntu 14.04 in that job. Can we remove `infra-softlayer-ubuntu1404-x64-2` from `node-test-commit-v8-linux`, or should we keep it?

**Comment by mhdawson** [comment]
For history, we used the benchmarking machine initially (which is now infra-softlayer-ubuntu1404-2) to avoid interference with regular CI runs.  

We want the job to run on at least one x86 linux box.  I like having it run on an older OS versus a newer one as it may be more likely to expose issues as V8 continues to push forward with using newer compiler (and possibly OS) features.

**Comment by mmarchini** [comment]
@mhdawson thanks for the context! I don't have strong opinions regarding which machine we should use, as long as it's accessible by people with `test-*` credentials.

**Comment by mhdawson** [comment]
The machine really should be benchmarking-xxxx but I'll have to see if it was always infra-xxx or was renamed to that for some reason along the way.

**Comment by refack** [comment]
Since 1404 reached EOL I believe it's time to retire it from the job.
