### ISSUE TITLE
grant ofrobots access to an aix machine

### ISSUE THREAD

**Issue by ofrobots** [nodejs/build#1386]
I need to debug this timeout that seems to be happening on AIX only: https://ci.nodejs.org/job/node-test-commit-aix/16036/nodes=aix61-ppc64/console

It would be good if I could get temporary access to an AIX machine.

**Comment by Trott** [comment]
+1

**Comment by maclover7** [comment]
+1, just double checking the host you'd like is `test-osuosl-aix61-ppc64_be-2` from that CI job

**Comment by ofrobots** [comment]
Yes, having access to the same machine would be best! Thanks!

**Comment by mhdawson** [comment]
+1

**Comment by refack** [comment]
+1
So we have 4 approvals. @ofrobots can you send me your public ssh key?

**Comment by ofrobots** [comment]
Sent via IRC.

**Comment by refack** [comment]
Key added

**Comment by refack** [comment]
@ofrobots is this still needed?

**Comment by ofrobots** [comment]
Nope. This access can be removed and the issue closed.

**Comment by refack** [comment]
Thanks.
Removed.
