### ISSUE TITLE
Node Summit - Node.js what's next

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1392]
Doing a presentation at Node Summit, have one slide on what's next for the build WG.

This is what I have, any suggestion for other things I should call out ?

![image](https://user-images.githubusercontent.com/9373002/42344747-485cba02-806b-11e8-8bca-45f45c1e9d68.png)

**Comment by joyeecheung** [comment]
Under `more automation tools/scripts`, maybe we can be more specific? Like

- Commit queue
- Tracking flakiness of CI

Refs: https://github.com/nodejs/build/issues/1330

**Comment by mmarchini** [comment]
Maybe "requirement for higher gcc and clang levels"?

**Comment by mhdawson** [comment]
@joyeecheung thanks for the suggestions, will add

**Comment by maclover7** [comment]
Nice slide! Not sure if there's enough room, but maybe mention Ansible specifically with the automation stuff?

**Comment by mhdawson** [comment]
Thanks for the feedback, incorporated.
