### ISSUE TITLE
Proposal: use Prometheus to monitor our infrastructure 

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1396]
Today our monitoring and notification system are users pinging us when a machine is defective. I think we can do better, especially for simple cases like memory and HD starvation. Prometheus ia an interesting tool we could use to monitor (almost?) all of our infrastructure. We could start using it to monitor the resources being used by our servers plus notify us when those resources reach some threshold, and since Prometheus is extensible we could collect more metrics in the future. We could also use Grafana to have some nice dashboards :)

If that’s something the working group is interested in, I can write a playbook to setup Prometheus and the exporters we would like to use.

**Comment by mhdawson** [comment]
I'm +1 general to using a tool to monitor our systems.  I think what would be good is to demo (maybe even just screenshots in this issue) how the data will be reported/surfaced.

Just want to make sure we end up with something we can take action on as there will be some additional overhead for an additional machine inters of maintenance.

**Comment by maclover7** [comment]
Great idea! I think the biggest roadblock to something like this would be platform availability. Can you double check that Prometheus could be run on all of our test and release cluster machines?

**Comment by mmarchini** [comment]
>  I think what would be good is to demo (maybe even just screenshots in this issue) how the data will be reported/surfaced.

I'll try to come up with a short demo after NodeSummit.

> Can you double check that Prometheus could be run on all of our test and release cluster machines?

Prometheus would only need to run on a single server, and we would install [node-exporter](https://github.com/prometheus/node_exporter) on the other platforms to collect metrics ([wmi_exporter](https://github.com/martinlindhe/wmi_exporter) for Windows machines). `node-exporter` is supposed to work well for *NIX systems. Regarding architectures, I believe it will work on any [platform supported by Golang](https://github.com/golang/go/wiki/MinimumRequirements). But yeah, I think we would need to test on some platforms to make sure it would work.

**Comment by gdams** [comment]
we should also consider nagios which I've successfully used on other OSS projects

**Comment by targos** [comment]
Or Icinga (it's a fork of Nagios). A big advantage that I can see with Nagios/Icinga is that you don't need to install anything on the machines that you want to monitor. It can just execute commands by ssh.

**Comment by mmarchini** [comment]
> A big advantage that I can see with Nagios/Icinga is that you don't need to install anything on the machines that you want to monitor. It can just execute commands by ssh.

Cool, I had no idea Nagios was able to do that. I suggested Prometheus because I'm  familiar with it and I think its philosophy fits well with what we need in terms of monitoring: something reliable, able to notify when things go wrong, and easy to maintain. We might want to come up with a list of upsides/downsides of each tool before deciding which one to use. We could even consider using both if we want to.

**Comment by djoq** [comment]
+1 for a tool like this. After evaluation both, nagios and grafana, I went with the later for a client wanting to monitor security and system health. Prometheus has tons of exporters available, though having this capability in node would be really conventient. The systeminformation package overlaps partially with common exporter metrics.

**Comment by bnb** [comment]
+1. Would be extremely awesome from a community engagement perspective to actually expose this to the public as well.

**Comment by bnb** [comment]
Also worth noting that Prometheus.io is a CNCF project, which is a sister Foundation to the Node.js Foundation – shouldn't inform the decision but a great story if we do indeed decide on Prometheus!🤗

**Comment by djoq** [comment]
I found this and am not a WG member so it seems public facing already.

**Comment by targos** [comment]
@djoq I think @bnb meant to expose the monitoring dashboard or metrics once they are available.

**Comment by bnb** [comment]
That is indeed what I meant – would be greta to expose the metrics publicly 😁

**Comment by mmarchini** [comment]
Closing, if anyone is working on it (or intend to work on it in the near future), feel free to reopen it
