### ISSUE TITLE
Request access to macOS machine

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#1397]
For investigating test issues with https://github.com/nodejs/node/pull/21561.

**Comment by maclover7** [comment]
+1, which host do you need access to?

**Comment by refack** [comment]
👍

**Comment by addaleax** [comment]
@maclover7 The one where https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1012/19746/ ran, maybe?

**Comment by mhdawson** [comment]
@addaleax if you still need access, if you send me your key I'll add to that machine.

**Comment by addaleax** [comment]
@mhdawson I’m not sure – depends on how things are going with @apapirovski’s investigation.

If you need keys, every user’s Github SSH keys are public, e.g. mine are at https://github.com/addaleax.keys :)

**Comment by mhdawson** [comment]
Added ssh keys and email info for getting to the machine.

**Comment by addaleax** [comment]
@mhdawson I think this can be removed/closed now. Thanks!

**Comment by mhdawson** [comment]
@addaleax thanks for the heads up.  Keys removed, closing.
