### ISSUE TITLE
test-azure_msft-win10-x64-3 - Not in inventory?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1398]
I was looking at the failure in this build https://ci.nodejs.org/job/node-test-node-addon-api/MACHINE=win10/393/console but I can't find test-azure_msft-win10-x64-3 in
https://github.com/nodejs/build/blob/master/ansible/inventory.yml

@joaocgreis can you give me info on how to connect?

**Comment by refack** [comment]
@mhdawson see https://github.com/nodejs/build/pull/1383#issuecomment-400469595
Sinse ansible isn't 100% compatible with the existing hosts (and neither is ssh) they are in `████████████/build/test/windows-servers.md`

**Comment by joaocgreis** [comment]
Exactly as @refack said. I saw that he had answered and forgot about this, sorry @mhdawson. It looks like this can be closed now.
