### ISSUE TITLE
Adding new collaborators

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#140]
@chrisdickinson @Fishrock123 a new procedure because I don't want to be a blocker on this one.

Don't email me directly any more asking to add people to Jenkins, instead, file a new issue here with the details of new people to be added and it'll be taken care of by one of the team. We have myself, @jbergstroem, @orangemocha and @misterdjules @joaocgreis all able to add new users so one of us will take care of it as soon as possible.

@jbergstroem, @orangemocha, @misterdjules @joaocgreis: when new people are added to the collaborators team, their details should be available @ https://github.com/nodejs/io.js#collaborators and they can be added to Jenkins. We're currently using plain matrix security but it's a bit of a pain to set a new user up if you haven't done it before (I'd like to investigate switching to GitHub Auth-based security because I'm having success with that on a private Jenkins we're using for work).

1. Gather GitHub username, full name, email address and make a random password by your favourite means
2. Add user: Manage Jenkins -> Manage Users -> Create User
3. Give them access to stuff: Manage Jenkins -> Configure Global Security -> Authorization
  - down the bottom there is a "User/group to add" where you need to enter their username exactly as you entered it above and click "Add"
  - Find them in the matrix and tick all of the same boxes that other collaborators have ticked
  - Click "Save"
4. Email them individually with their username & password and some basic hints, I usually just tell them about iojs+any-pr+multi and how to make that work. We may want to come up with some basic language we can copy/paste into emails for this, I never did finish writing up instructions on how to use Jenkins for io.js / Node.

**Comment by jbergstroem** [comment]
Regarding "basic hints": I wrote something similar, but linking to the collaborators guide or having more info as part of the onboarding process would be better. Since we're doing some minor changes to this workflow we should perhaps wait until that lands and then add documentation somewhere.

**Comment by rvagg** [comment]
I started docs here: https://github.com/nodejs/build/pull/48

I'm unlikely to find time to complete that in the near future though.

**Comment by orangemocha** [comment]
Great. One more prescription: the user name and email address in Jenkins need to be what you want to appear in the git logs, because node-accept-pull-request uses it to populate the committer email.

**Comment by orangemocha** [comment]
> @jbergstroem, @orangemocha and @misterdjules @joaocgreis

Shall we create a new team "jenkins-admins" or is @nodejs/build good for it?

**Comment by rvagg** [comment]
@orangemocha yes, that's a good idea

**Comment by orangemocha** [comment]
Done: https://github.com/orgs/nodejs/teams/jenkins-admins

**Comment by rvagg** [comment]
Added @mhdawson to the list

**Comment by jbergstroem** [comment]
All users mentioned above has been added. closing. Bonus points if anyone opens a PR that documents we expand our collaborator list.
