### ISSUE TITLE
nodegyp-test-commit downloads Node.js v0.10 and v0.12 from bad URLs on Windows

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1410]
Refs: https://github.com/nodejs/node-gyp/pull/1492#issuecomment-406641647

node-gyp v3.x still maintains compatibility with old versions of Node.js and the CI jobs still test against Node.js v0.10 and v0.12. On Windows for those older versions it looks like they are attempting to download from a URL such as `https://nodejs.org/dist/v0.12.18/win-x64/node.exe` but those older versions of Node.js did not upload to a `win-` prefixed directory so the correct URL should be `https://nodejs.org/dist/v0.12.18/x64/node.exe`.

e.g. https://ci.nodejs.org/job/nodegyp-test-commit/337/nodes=win2016-vs2017/console
```
11:34:30 + curl -s -L https://nodejs.org/dist/v0.12.18/win-x64/node.exe -o node.exe
11:34:31 + popd
11:34:31 /c/workspace/nodegyp-test-commit/nodes/win2016-vs2017
11:34:31 + echo Node version:
11:34:31 Node version:
11:34:31 + node -v
11:34:31 /c/workspace/nodegyp-test-commit/nodes/win2016-vs2017/local_node/node: line 1: syntax error near unexpected token `newline'
11:34:31 /c/workspace/nodegyp-test-commit/nodes/win2016-vs2017/local_node/node: line 1: `<!DOCTYPE html>'
```

**Comment by joaocgreis** [comment]
@richardlau should be fixed now. I'll close this, please reopen if I missed anything.
