### ISSUE TITLE
APPX packaged version for Windows Server 2016

### ISSUE THREAD

**Issue by nschonni** [nodejs/build#1413]
I was doing some reading for the docker-node Windows images and came across this https://blogs.technet.microsoft.com/nanoserver/2015/11/18/installing-windows-server-apps-on-nano-server/
Seems like the Nano Server won't support the MSI installation, but does have this new packaging.

Pros:
- Better install for Windows Server 2016+ 
- Maybe compat with Windows Store?

Cons:
- Another format to build
- Win 10 looks to be doing MSIX https://github.com/Microsoft/msix-packaging

**Comment by refack** [comment]
I'm +1 on migrating (as semver-major). I don't have much love for the `msi`, as IMHO it's only value is for provisioning automation, so if WSA is the successor, I say we should move to it.

**Comment by joaocgreis** [comment]
Our MSI does more than just copy files: it updates the PATH, installs ETW and PerfCtr, takes care of upgrades removing old files, and all of this in a very simple way. Thus, we can't move out of it without providing something with the same features that is as simple to use, the MSI is very useful for many of our users. For more advanced users we already have the Zip/7Z packages, but those can be confusing.

MSIX will be the successor to MSI, and we'll move to it as soon as it's ready to use and can provide us with the same features.

APPX would not be able to set the PATH or install ETW and PerfCtr, so I don't see much benefit over the Zip/7Z packages. @nschonni can you tell us about your use case, if/how APPX would be better than the packages?

**Comment by nschonni** [comment]
I'm actually not suggesting dropping the MSI, this would be in additional format it. For the MSIX stuff, replacing MSI, that would probably be a different thread (and it's not really ready yet). I use the MSI for my own machines, and don't necessarily see that changing even with this format for my regular machines.

> can you tell us about your use case, if/how APPX would be better than the packages?

- GPG on Windows does have a great story. The MSIs are signed, and so are the APPX packages so you keep the package integrity checks
- It seems to be Microsoft's recommended package format for the Windows server space

I'm not an expert in this, just reading through the docs and poking around on the official images.

**Comment by joaocgreis** [comment]
> The MSIs are signed, and so are the APPX packages so you keep the package integrity checks

That's a good point, verifying the Windows Zip/7Z packages is not so straightforward (well, it is if you have WSL available).

> It seems to be Microsoft's recommended package format for the Windows server space

I believe MSIX will take over that as well.

Given the pros and cons, I don't see a pressing need for APPX now. I don't think we should produce official APPX builds as it's one more thing to maintain and MSIX is being developed. But if someone wants to go ahead and open a PR for APPX support, it would still be a good thing to have to enable anyone to build their own.

**Comment by refack** [comment]
I was just thinking...
If we consider the front-end dev use case, where people need Node.js mostly to drive webpack or gulp or just npm, this actually might be a very interesting solution (APPX from the store for Windows 10)

**Comment by nschonni** [comment]
Looks like since you're using Wix already, it might be fairly straight forward to add support https://www.firegiant.com/products/wix-expansion-pack/appx/

**Comment by nschonni** [comment]
Shoo stale bot
