### ISSUE TITLE
release: macOS 10.10 can't compile V8 6.8

### ISSUE THREAD

**Issue by refack** [nodejs/build#1415]
Refs: https://github.com/nodejs/build/issues/1358#issuecomment-399420514
Refs: https://github.com/nodejs/build/pull/1409
Refs: https://github.com/nodejs/node/pull/21079
Refs: https://github.com/nodejs/build/issues/1264

>  V8 6.8 requires Xcode 8.x or higher but unfortunately Xcode 8.x is not supported on macOS 10.10

We only have a macOS 10.10 release machine, so ATM we can't release with V8 6.8.
The crux is the use on `thread_local` modifier for 2 variables used by `torque` which is a codegen tool used by the build process (no `thread_local` usage in the actual V8 code).
https://github.com/targos/node/blob/716948b9de79bbd327e9e496e4db8fc07e82b742/deps/v8/src/torque/contextual.h#L52-L57

We have a few options:
1. Upgrade the release machine
2. Patch the `torque` code (maybe as per https://stackoverflow.com/a/25393790/27955)
3. Cache the generated code (AFAICT it's identical when generated on macOS 10.10 and 10.11), and tweak the gyp files

/CC @nodejs/v8-update @nodejs/build-infra (specifical @targos and @rvagg)

**Comment by targos** [comment]
There is also option 4: add a new release machine.
See https://github.com/nodejs/build/pull/1391

**Comment by refack** [comment]
Closing in favor of #1391
