### ISSUE TITLE
Better CI auto run

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1418]
It is really great that the CI is automatically triggered for collaborators now. However, it is always the "lite" run and that is often not enough, even though it is a good first indicator.

I believe it would be great to check the title (or even better: the actual code diff) if only docs were changed. If that is the case: run the lite one, otherwise run the main CI. I am not sure how much load that would be for the CI but I actually doubt that it is much more than the current way.

What do others think about this?

**Comment by BridgeAR** [comment]
The lite CI as it is is good for docs and some other minor changes. So I would not want to run more things with it.

Having an outdated CI is an interesting point. I suggest to automatically start a new CI if no CI has ran for seven days. That way we'd always have an up to date one and do not have to manually trigger them because they are outdated. Should I open a new issue for this?

**Comment by refack** [comment]
> Should I open a new issue for this?

I believe this issue is good enough.
When we have the set up ready we can bring it to nodejs/node for consensus.

> The lite CI as it is is good for docs and some other minor changes. So I would not want to run more things with it.

We could add a `lite+` job that does a little bit more than the current `lite` and runs automatically. While keeping `node-test-pull-request` to be triggered manually before landing (optimally that will eventually only be run by the "commit queue")

💡 this was we could also beef up `node-test-pull-request` with more edge cases, like building with `cmake` and `ninja` for example, as those had push back against adding them to the general matrix.

**Comment by maclover7** [comment]
To add onto the outdated concern (or maybe "too much information too early"?), I believe the original idea behind having a lite job is to provide an initial indication of the pull request's status in CI. Everyone's workflow is a bit different, but when I open PRs, I am okay with just having a lite job that's autocreated until I get a couple of reviews from other collaborators, and then move onto running a full `node-test-pull-request`. Having passing linter and linuxone builds is usually a good sign that a full CI run should pass.

> I suggest to automatically start a new CI if no CI has ran for seven days.

Seems fine to me, but maybe without PRs that have the `blocked` label or that type of label? I'm happy to review any pull requests in `nodejs/github-bot` :)

**Comment by BridgeAR** [comment]
@maclover7 
> maybe without PRs that have the blocked label or that type of label

Yes, definitely.

> having a lite job that's autocreated until I get a couple of reviews from other collaborators

Well, if the bot could auto detect the very first LG and then start a full CI, that would even be better!

**Comment by BridgeAR** [comment]
I am closing this, since we slowly move towards more github actions and so far there does not seem to be a good solution otherwise.
