### ISSUE TITLE
3 last nightly builds lack some usual items

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/build#1419]
https://nodejs.org/download/nightly/v11.0.0-nightly20180725f5a2167eb5/

vs

https://nodejs.org/download/nightly/v11.0.0-nightly201807264d94bb2b1f/
https://nodejs.org/download/nightly/v11.0.0-nightly20180727c91e0ed3ad/
https://nodejs.org/download/nightly/v11.0.0-nightly20180728045b07d518/

No `docs`, `darwin`, `headers`, `.pkg` and `tar`s.

**Comment by targos** [comment]
This is https://github.com/nodejs/build/issues/1415

**Comment by vsemozhetbyt** [comment]
Including `docs`?

**Comment by targos** [comment]
Not sure but likely

**Comment by vsemozhetbyt** [comment]
I am just afraid that https://github.com/nodejs/node/commit/f41dd5592ef4df3d200269e536a1693919d73b25 may have some issues with the build infrastructure.

**Comment by targos** [comment]
I don't know what is supposed to build the release docs but currently the macOS job is skipped

**Comment by targos** [comment]
Confirmed docs came from osx1010-release-tar in previous builds

**Comment by vsemozhetbyt** [comment]
Thank you. I'll close then.
