### ISSUE TITLE
nodejs.org metrics are borked

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1423]
nodejs.org/metrics have stopped working, segfault during awk processing of summaries, I haven't looked in detail but will need to get in there and tinker soon. So FYI if you're looking at the graphs and they don't look right, this is probably why!

**Comment by mhdawson** [comment]
@rvagg I think this is long stale, although not working for other reasons now. Closing. @rvagg please let me know if that was not the right thing to do.
