### ISSUE TITLE
Use version selector script for citgm-smoker

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#1430]
A citgm-smoker job against master (ex: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1484/) will try and build against platforms that are no longer supported on that major version of Node.js (ex: ubuntu1204-64, osx1010). I _believe_ we should be able to use the [version selector script](https://github.com/nodejs/build/blob/master/jenkins/scripts/VersionSelectorScript.groovy) (originally written for node-test-commit-*) to try and avoid this

**Comment by MylesBorins** [comment]
Feel free to manually update those versions if they are out of date (in the mean time)

**Comment by refack** [comment]
Fixed by: https://github.com/nodejs/build/issues/1509
