### ISSUE TITLE
node-test-commit-custom-suites failing to fetch git repo

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1431]
https://ci.nodejs.org/job/node-test-commit-custom-suites/517/console

```
21:45:05  > git fetch --no-tags --progress git@github.com:nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/22184/head:refs/remotes/origin/_jenkins_local_branch # timeout=20
21:45:07 ERROR: Error fetching remote repo 'origin'
21:45:07 hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
21:45:07 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:889)
21:45:07 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
21:45:07 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1177)
21:45:07 	at hudson.scm.SCM.checkout(SCM.java:504)
21:45:07 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
21:45:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
21:45:07 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
21:45:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
21:45:07 	at hudson.model.Run.execute(Run.java:1798)
21:45:07 	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
21:45:07 	at hudson.model.ResourceController.execute(ResourceController.java:97)
21:45:07 	at hudson.model.Executor.run(Executor.java:429)
21:45:07 Caused by: hudson.plugins.git.GitException: Command "git fetch --no-tags --progress git@github.com:nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/22184/head:refs/remotes/origin/_jenkins_local_branch" returned status code 1:
21:45:07 stdout: 
```

**Comment by rvagg** [comment]
Could be related to https://github.com/nodejs/build/issues/1432, I don't see an env.properties in the node-test-commit hand-off for it. @gibfahn this one is yours isn't it?

Perhaps this work would be better to shoehorn into linux-containered where we do custom variations already so this would be just a matter of adding a new block in the config there and adding a new label for all of the available "sharedlibs" containers. Having multiple ways to spawn custom builds & test runs might be creating a rod for our own backs by layering complexity. I'm happy to do that work unless you have good reason for this to be a separate configuration or want to migrate the work in linux-containered to this new style.

**Comment by maclover7** [comment]
I was the one who added the worker tests to node-test-commit (tracking issue was https://github.com/nodejs/build/issues/1318)  -- just updated the job config to pass `env.properties` along.

> Perhaps this work would be better to shoehorn into linux-containered where we do custom variations  already

Not sure if it fits easily into the containers work or not -- the idea with `node-test-commit-custom-suites` is that we can run custom suites (ex: `internet`) or pass custom flags (`--worker`) to `tools/test.py`. I _believe_ one of the reasons we use containers for things like `--without-intl` or testing different versions of OpenSSL is that the actual build environment is customized, as opposed to using a regular Ubuntu 16.04 machine

**Comment by rvagg** [comment]
@maclover7 we have generic images and "sharedlibs" images in the pool, but even the "sharedlibs" ones are pretty vanilla because they just put the shared custom libaries in /opt/ (iirc) so they are suitable for this kind of thing. These custom test suites are actually pretty similar to the build variations we do like `--without-intl` and Debug, I'm not seeing a good distinction that warrants a new pool of Ubuntu 16.04 machines when we could just be expanding our Docker container pool which is more flexible and doesn't hurt our quotas on our infra providers since we just grow underlying VMs.
