### ISSUE TITLE
ci-change: Limits to CITGM job

### ISSUE THREAD

**Issue by refack** [nodejs/build#1438]
Since a CITGM run can in some cases take over 5 hours, [I've added two limits](https://ci.nodejs.org/job/citgm-smoker/jobConfigHistory/showDiffFiles?timestamp1=2018-06-25_10-37-17&timestamp2=2018-08-10_10-36-21).
1. No concurrent builds
2. Kill after 15m of inactivity.

**Comment by BridgeAR** [comment]
Sounds good to me.

**Comment by MylesBorins** [comment]
I'd like to ask that we change this to 2 concurrent builds. If we need to compare a previous release and a new release this limitation creates a lot of friction

**Comment by refack** [comment]
> I'd like to ask that we change this to 2 concurrent builds. If we need to compare a previous release and a new release this limitation creates a lot of friction

I've changed it to 2 concurrent build.

**Comment by Trott** [comment]
If I understand correctly (which is a big caveat, so others please weigh in here), two concurrent CITGM jobs use all hosts on several platforms, stalling ordinary CI pull requests until they're done. So two CITGM jobs will tie things up for, like 6 hours.

Something to at least keep an eye on?

**Comment by refack** [comment]
Done.
