### ISSUE TITLE
Monitoring Jenkins Slaves

### ISSUE THREAD

**Issue by Starefossen** [nodejs/build#144]
Kickstarting monitoring effort of Jenkins slaves as discussed in Build WG Meeting 2015-07-28 #141.

The status of all the slaves can be fetched as a JSON from the following public API endpoint: [/computer/api/json](https://jenkins-iojs.nodesource.com/computer/api/json?pretty=true). This makes it trivial to check for `offline` = `true` which indicates that a node is down.

The question is, what is the best method for notifying those who should be informed about outages? Email (jenkins@nodejs.org / build@nodejs.org)? Webhook to the nodejs/build channel on Gitter?

**Comment by mhdawson** [comment]
Except for the possible issue of getting a log of emails, why not do both ?

**Comment by rvagg** [comment]
Lets make a new email alias for this, we can easily put it @ iojs.org for now and migrate to nodejs.org when we get around to. Easy to do it here: https://github.com/nodejs/email/blob/master/iojs.org/aliases.json

Re slave status, there is prior-art here: https://github.com/nodejs/build/blob/master/tools/jenkins-status/jenkins-status.js

**Comment by bnoordhuis** [comment]
Would a hook for #io.js on freenode be possible?  Most committers, yours truly included, don't hang out in the build channel.

**Comment by Starefossen** [comment]
@bnoordhuis yes, that would absolutely be possible. Does freenode provide some kind of webhook interface or do we have to connect using an irc client?

**Comment by bnoordhuis** [comment]
Freenode offers no webhooks that I'm aware of but connecting should be easy with node-irc.

**Comment by jbergstroem** [comment]
+1 IRC as alert endpoint. I feel we would benefit from finding software that helps us here though ("if, then, else") -- getting an alert every 5 minutes is never a fun thing. Can't say I've used too many commercial monitoring websites, but perhaps theres room for a ~$30/mo thing somewhere? (lowest requirements would be being able to parse json responses)

**Comment by jbergstroem** [comment]
@Starefossen ping! can we get an alert to #node-build?

**Comment by jbergstroem** [comment]
This has been successfully running for a while. Closing.
