### ISSUE TITLE
incident: freeBSD11 machines are offline

### ISSUE THREAD

**Issue by refack** [nodejs/build#1441]
https://ci.nodejs.org/label/freebsd11-x64/
This exhausts our freeBSD repertoire (Ref: https://github.com/nodejs/build/issues/1412) so I've temporarily disabled the freeBSD tests:
* https://ci.nodejs.org/job/node-test-commit-freebsd/
* https://ci.nodejs.org/job/libuv-test-commit-freebsd/

**Comment by rvagg** [comment]
OK, so I've done a reboot and clean on all of these hosts. The DigitalOcean FreeBSD 10 one that hasn't been responsive I just rebuilt from the latest 10.4-RELEASE image and ran Ansible against it (found an Ansible bug that I'll PR in a minute). On the rest I figured out how to upgrade release versions using `freebsd-upgrade` so now we're running on 10.4-RELEASE and 11.2-RELEASE (we are mostly on 10.2 and 11.0). There's still some wonkyness with packages in these but I put that down to typical FreeBSD package management garbage. They're all back in rotation now, I've reenabled the jobs, let's see if we have improved things at all ... 🤞

**Comment by joyeecheung** [comment]
Looks like the new digital ocean freebsd machines are causing failures of `addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max-by-1-binary` (all crashed, failed 17/36 recent PRs)

https://github.com/nodejs/reliability/issues/12
