### ISSUE TITLE
Missing which command on fedora 22 machine

### ISSUE THREAD

**Issue by targos** [nodejs/build#145]
Tests are failing because of it:
```
+ which git
/tmp/hudson5087374295565828274.sh: line 3: which: command not found
```

https://jenkins-iojs.nodesource.com/job/node-test-commit-linux/62/nodes=fedora22/console
https://jenkins-iojs.nodesource.com/job/node-test-commit-linux/63/nodes=fedora22/console

**Comment by orangemocha** [comment]
Thanks for reporting this. I removed `which git` from the scripts a few days ago.

**Comment by joaocgreis** [comment]
Fixed by the removal of that line from the script. If we ever need to add it again, 0aecff5b897bd3241468190554608e90725317e1 enables it.
