### ISSUE TITLE
jenkins: node-test-commit-linux-containered should set IDENTIFIER=node-test-commit-linux-containered ?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#1452]
See https://ci.nodejs.org/job/node-test-commit-linux-containered/configure The parameters passed to `post-build-status-update` currently set `IDENTIFIER=${STATUS_LABEL}` which appear in the Github PR status as `${STATUS_LABEL}`. I believe it's supposed to be `IDENTIFIER=node-test-commit-linux-containered` instead?

<img width="680" alt="screen shot 2018-08-15 at 8 41 54 pm" src="https://user-images.githubusercontent.com/4299420/44148630-ad1181dc-a0cb-11e8-9040-d4020c836e3e.png">

**Comment by maclover7** [comment]
There's also this part of the build configuration, which I _believe_ is trying to customize the github-bot status label?

```
echo $nodes | sed -E 's/.*_(\w+)_x64$/STATUS_LABEL=node-test-linux-linked-\1/g' > env.properties
```

cc @rvagg

**Comment by refack** [comment]
Moving the aforementioned line to the top of the script should minimize such errors:
https://ci.nodejs.org/job/node-test-commit-linux-containered/jobConfigHistory/showDiffFiles?timestamp1=2018-08-16_18-01-41&timestamp2=2018-08-16_18-07-22

**Comment by refack** [comment]
Nope - https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1604_sharedlibs_openssl110_x64/6352/console
Seems like on `test-softlayer-ubuntu1604_sharedlibs_container-x64-5` the following replace fails:
```
20:54:20 + echo ubuntu1604_sharedlibs_openssl110_x64
20:54:20 + sed -E s/.*_(\w+)_x64$/STATUS_LABEL=node-test-linux-linked-\1/g
20:54:20 + echo
```
