### ISSUE TITLE
Setting `autocrlf` and `safecrlf` on workers

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#1453]
For context, see https://github.com/nodejs/reliability/issues/12 and the minutes of the last build meeting https://github.com/nodejs/build/pull/1448 It was agreed to fix those workers by configuring git to not fix the line breaks.

I'll fix the nodes manually by running

```
git config --global core.autocrlf false
git config --global core.safecrlf false
```

on nodes with trouble checking out files with CRLF. 

Feel free to add nodes in the following list if you find a new worker with this issue or have fixed a worker

- [x] test-packetnet-ubuntu1604-arm64-2
- [x] test-softlayer-ubuntu1604_sharedlibs_container-x64-2
- [x] test-softlayer-ubuntu1604_sharedlibs_container-x64-5
- [x] test-softlayer-ubuntu1604_sharedlibs_container-x64-1
- [x] test-linuxonecc-rhel72-s390x-2
- [x] test-packetnet-centos7-arm64-2
- [x] test-joyent-smartos16-x64-1
- [x] test-digitalocean-ubuntu1604_sharedlibs_container-x64-1
- [x] test-packetnet-centos7-arm64-1
- [x] test-linuxonecc-rhel72-s390x-3
- [x] test-digitalocean-ubuntu1604_sharedlibs_container-x64-3
- [x] test-digitalocean-ubuntu1604_sharedlibs_container-x64-10

**Comment by joyeecheung** [comment]
Maybe we should just put the configuration in https://github.com/nodejs/build/blob/master/jenkins/scripts/node-test-commit-pre.sh instead?

**Comment by richardlau** [comment]
+1 for configuration changes in scripts rather than manually done.

**Comment by joyeecheung** [comment]
Also, as far as I can tell the containers have their configs set in the Jenkins instead of using the script

**Comment by joaocgreis** [comment]
`autocrlf` should not be changed in the Windows machines, we want to ensure new contributors can compile with a default installation of Git (we already ask for the Unix tools, but the less of those little details the better and some people might not want to change it). I understand this does not include Windows hosts for now, but there is support to run the V8 tests on Windows and the ChakraCore nightlies seem to be failing because of this.

@joyeecheung can we instead use https://github.com/nodejs/node/blob/master/.gitattributes to specify that that file is always CRLF? This is already done for `vcbuild.bat`.

**Comment by joyeecheung** [comment]
@joaocgreis The failures in CI are caused by incorrect checkouts (not a fresh clone of nodejs/node), I don't see changing settings on our CI makes a difference since that's not how new contributors set up their environment anyway?

**Comment by joyeecheung** [comment]
> can we instead use https://github.com/nodejs/node/blob/master/.gitattributes to specify that that file is always CRLF? This is already done for vcbuild.bat.

Does that work with https://github.com/nodejs/node/blob/8a41470c85536119a6dbeaf4b40dc9ebc4c453c4/deps/v8/.gitattributes#L1-L2 ? It's a file in `deps/v8` but not actually in V8's source

**Comment by joaocgreis** [comment]
> I don't see changing settings on our CI makes a difference since that's not how new contributors set up their environment anyway?

It should be, Windows CI machines are set up in the same way that we recommend contributors to set their own (with a few additions for Jenkins). Using a different `autocrlf` setting in CI can cause tests to fail because of different line endings.

Please let me take a better look at this, I'd much rather find a solution that doesn't involve changing machine configuration.

**Comment by joyeecheung** [comment]
As it's a file maintained by us and not in V8's source, maybe we can just patch it to use LF?

**Comment by joaocgreis** [comment]
> As it's a file maintained by us and not in V8's source, maybe we can just patch it to use LF?

That sounds good to me, if @targos is ok with it.

**Comment by refack** [comment]
> we want to ensure new contributors can compile with a default installation of Git

That was my motivation as well. Setting git to not touch the files in any way would break Windows build in case file are improperly checked in (e.g. `.bat` file with just `LF`). So we will be actually testing if the code can compile even from tarball.

**Comment by richardlau** [comment]
> So we will be actually testing if the code can compile even from tarball.

Given that we have actually broken this in the past this would be better off as a separate job (that actually unpacks the tarball and attempts to compile/test it).

**Comment by refack** [comment]
> Given that we have actually broken this in the past this would be better off as a separate job (that actually unpacks the tarball and attempts to compile/test it).

Agreed WRT to the "packed" tarballs. Here I'm referring to GitHub repo tarballs. For example ATM inspecting the GitHub tarball, checking files in that directory `LICENSE` is `CR+LF`, while `AUTHORS` is `LF`
![image](https://user-images.githubusercontent.com/96947/44169683-31c66880-a0a3-11e8-82fb-2fb42efc6536.png)

**Comment by refack** [comment]
Also for good measure run with `agent.name ==~ /(?i).*linuxone.*/`:
```
################## test-linuxonecc-rhel72-s390x-1 #################


core.autocrlf=false
core.safecrlf=false


####################
################## test-linuxonecc-rhel72-s390x-2 #################


core.autocrlf=false
core.safecrlf=false


####################
################## test-linuxonecc-rhel72-s390x-3 #################


core.autocrlf=false
core.safecrlf=false


####################
```

**Comment by refack** [comment]
Help, this can't be killed:
```
[iojs@test-linuxonecc-rhel72-s390x-3 rhel72-s390x]$ git status
# HEAD detached at 4b7cd4b
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       deleted:    deps/v8/third_party/jinja2/LICENSE
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       build/
no changes added to commit (use "git add" and/or "git commit -a")
[iojs@test-linuxonecc-rhel72-s390x-3 rhel72-s390x]$ git checkout deps/v8/third_party/jinja2/LICENSE
[iojs@test-linuxonecc-rhel72-s390x-3 rhel72-s390x]$ git status
# HEAD detached at 4b7cd4b
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   deps/v8/third_party/jinja2/LICENSE
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       build/
no changes added to commit (use "git add" and/or "git commit -a")
[iojs@test-linuxonecc-rhel72-s390x-3 rhel72-s390x]$ git --version
git version 1.8.3.1
[iojs@test-linuxonecc-rhel72-s390x-3 rhel72-s390x]$ git config --global -l
core.autocrlf=false
core.safecrlf=false
core.eol=lf
[iojs@test-linuxonecc-rhel72-s390x-3 rhel72-s390x]$
```

**Comment by refack** [comment]
So apparently with git 1.8 we need to delete the workspace for the settings to work.

**Comment by joyeecheung** [comment]
I thought the errors would not appear if you are checking out from a commit without the CRLF file and not rebasing from somewhere that contains it? (but yeah, it'll appear the next time we have a file like that in deps/v8)

**Comment by refack** [comment]
> I thought the errors would not appear if you are checking out from a commit without the CRLF file and not rebasing from somewhere that contains it? (but yeah, it'll appear the next time we have a file like that in deps/v8)

I was testing explicitly with "bad" commits:
```
GIT_REMOTE_REF	4b7cd4bd60623b9c69d791112f4500575a3e9e7d
REBASE_ONTO		2ce03804a6a2e55a034814ca40fafac654321e33
```
https://ci.nodejs.org/job/node-test-commit-linuxone/4190/

When everything is setup right, it passes.
