### ISSUE TITLE
Remove non existing benchmark category

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1455]
Recently the `array` category was removed from Node core. This should therefore also be removed from the CI configuration.

I suggest to change the category to a input field instead of using the filter as it exists right now. That way we would easily be able to run new categories and do not get the old ones suggested.

**Comment by refack** [comment]
What about backports?
Anyway I've changed the type of the parameter to be a combo-box in this job https://ci.nodejs.org/job/benchmark-node-micro-benchmarks-compare

Any discussion to reference with this CR?

**Comment by BridgeAR** [comment]
@refack thanks a lot! That is definitely already a huge improvement as it's now possible to use new categories.

I would still only use the categories from master but allow other categories to be entered manually. That way it's also fine for backports. I guess an auto detection would be to much work though (even though a cron job could be run once a day to update the list by checking the benchmark folder from the master branch). Therefore I guess this could be counted as resolved?

**Comment by BridgeAR** [comment]
Closing as resolved due to the new format.
