### ISSUE TITLE
Problems with libuv-in-node job

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#1457]
I can't seem to make the `libuv-in-node` job work. Here's the [relevant failure](https://ci.nodejs.org/view/libuv/job/libuv-in-node/49/console):

```
+ mkdir deps/uv/
mkdir: cannot create directory ‘deps/uv/’: File exists
Build step 'Execute shell' marked build as failure
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 29308 killed;

[ssh-agent] Stopped.
Notifying upstream projects of job completion
Finished: FAILURE

```

**Comment by joaocgreis** [comment]
The `.git` folder in `deps/uv/` was not deleted by `git clean` nor `git rm`. So I added an explicit `rm` after the `git rm`. Should be fixed, here is a rebuild: https://ci.nodejs.org/view/libuv/job/libuv-in-node/50/

I'll close this, but let me know if there's any issue.
