### ISSUE TITLE
Git lock in test-azure_msft-win10-x64-3 exists

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#1460]
| Reason | `ERROR: Error fetching remote repo 'jenkins_tmp'` |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 7 (https://github.com/nodejs/node/pull/22287/, https://github.com/nodejs/node/pull/22340/, https://github.com/nodejs/node/pull/21397/, https://github.com/nodejs/node/pull/22348/, https://github.com/nodejs/node/pull/22359/, https://github.com/nodejs/node/pull/22373/, https://github.com/nodejs/node/pull/22368/) |
| Appeared | test-azure_msft-win10-x64-3 |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/16502/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/16514/ |

<details>
<summary>Example</summary>

```
ERROR: Error fetching remote repo 'jenkins_tmp'
hudson.plugins.git.GitException: Failed to fetch from binary_tmp@147.75.70.237:binary_tmp.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:889)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1177)
	at hudson.scm.SCM.checkout(SCM.java:504)
```
</details>

**Comment by Trott** [comment]
git lock failure. The node is offline. Someone needs to RDP in and remove the git lock or whatever.

**Comment by refack** [comment]
Churning along https://ci.nodejs.org/job/node-test-binary-windows/COMPILED_BY=vcbt2015,RUNNER=win10,RUN_SUBSET=2/19304/console
