### ISSUE TITLE
test-digitalocean-fedora27-x64-1 keeps timing out

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#1463]
Refs: https://github.com/nodejs/reliability/issues/14

| Reason | <code>Build timed out (after 120 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 3 (https://github.com/nodejs/node/pull/21593/, https://github.com/nodejs/node/pull/22340/, https://github.com/nodejs/node/pull/22373/) |
| Appeared | [test-digitalocean-fedora27-x64-1](https://ci.nodejs.org/computer/test-digitalocean-fedora27-x64-1/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/16489/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/16513/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/20818/console">Example</a></summary>

```
Build timed out (after 120 minutes). Marking the build as failed.
```
</details>

**Comment by maclover7** [comment]
Rebooted and ran Ansible playbook, hopefully should be more reliable now

**Comment by joyeecheung** [comment]
Still here..


| Reason | <code>Build timed out (after 120 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 (https://github.com/nodejs/node/pull/22197/, https://github.com/nodejs/node/pull/22359/) |
| Appeared | [test-digitalocean-fedora27-x64-1](https://ci.nodejs.org/computer/test-digitalocean-fedora27-x64-1/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/16568/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/16571/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/20881/console">Example</a></summary>

```
Build timed out (after 120 minutes). Marking the build as failed.
```
</details>
