### ISSUE TITLE
Last nightlies lack docs

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/build#1464]
Last nightly with docs:
https://nodejs.org/download/nightly/v11.0.0-nightly201808150257fd7ce9/

The next 3 lack them:

https://nodejs.org/download/nightly/v11.0.0-nightly2018081616accff90f/
https://nodejs.org/download/nightly/v11.0.0-nightly2018081738145344f1/
https://nodejs.org/download/nightly/v11.0.0-nightly201808187cbbb27c07/

**Comment by refack** [comment]
The macOS machine that builds those is down. (also no headers, tarball, or Mac `.pkg`)

**Comment by mhdawson** [comment]
I restarted the jenkins agent on the release machine, its back online now.

**Comment by refack** [comment]
Strage the headers are there as are the tarballs, and `darwin` binaries, but no `.pkg`...
