### ISSUE TITLE
Immediate failures on smartos, linux-containered, arm, and linuxone

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#1467]
https://ci.nodejs.org/job/node-test-pull-request/16595/
https://ci.nodejs.org/job/node-test-pull-request/16597/
https://ci.nodejs.org/job/node-test-pull-request/16602/
https://ci.nodejs.org/job/node-test-pull-request/16603/

On all of them, the above-mentioned platforms fail with "You have unstaged changes".

**Comment by cjihrig** [comment]
I'm not sure what caused it, but @joyeecheung left comments on a bunch of PRs last night saying to rebase the PR to make that go away. It worked for me.

**Comment by refack** [comment]
The cause is a combination of old git versions and a bad commit (that was fixed https://github.com/nodejs/node/pull/22340):
Ref: https://github.com/nodejs/build/issues/1453

**Comment by gabrielschulhof** [comment]
Thanks! I've rebased and will start a new CI.

**Comment by gabrielschulhof** [comment]
Oh, I guess the REBASE_ONTO wasn't working because the repo wasn't clean.

**Comment by refack** [comment]
> Hmmm ... why does the linuxone sub-job list a whole pile of changes?
> 
> ci.nodejs.org/job/node-test-commit-linuxone/4181

It's not an amazing feature. It compares the code to the last state of the workspace.
