### ISSUE TITLE
Jenkins slaves keep running out of room and becoming inoperable

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#147]
https://jenkins-iojs.nodesource.com/, can't run anything again because of this. IIRC it's the logs somewhere that jenkins is storing too much.

cc @nodejs/build, could someone please try to clear this out again? :/

**Comment by jbergstroem** [comment]
I recall @rvagg mentioned that he cleared 113G logs less than a week ago; can't be filling up that quickly. Guessing it might be something else?

**Comment by thefourtheye** [comment]
I remember seeing a permissions error while removing a directort

**Comment by jbergstroem** [comment]
@thefourtheye that might be a git issue. we're looking at installing a newer git version.

**Comment by saghul** [comment]
@Fishrock123 I'm trying to trigger a libuv build and nothing happens, it just silently does nothing. Is this the observed behavior?

**Comment by joaocgreis** [comment]
@saghul yes, that's it

**Comment by saghul** [comment]
Thanks, I'll keep an eye on this issue then!

**Comment by orangemocha** [comment]
@rvagg @jbergstroem @wblankenship @ryanstevens CI is blocked on this issue. You are the only ones who have access to the master machine.

**Comment by rvagg** [comment]
```
# ls -alh
total 119G
drwxr-xr-x  2 jenkins jenkins 4.0K Aug  2 06:48 .
drwxrwxr-x 12 root    syslog  4.0K Aug  2 06:49 ..
-rw-r-----  1 jenkins jenkins 111G Aug  3 07:36 jenkins.log
-rw-r-----  1 jenkins jenkins 8.1G Aug  2 06:49 jenkins.log.1
```

restarted, it'll come back online soon but this is just going to happen again unless I can find a solution

**Comment by rvagg** [comment]
@orangemocha lots of these types of errors, I think this might be a config problem on your end:

```
WARNING: Caught exception evaluating: browser.getChangeSetLink(cs) in /job/node-test-commit-windows/81/. Reason: java.net.MalformedURLException: no protocol:
```

**Comment by saghul** [comment]
@rvagg thanks for bringing it up!

**Comment by saghul** [comment]
@rvagg thanks for bringing it up!

**Comment by orangemocha** [comment]
> @orangemocha lots of these types of errors, I think this might be a config problem on your end:
>WARNING: Caught exception evaluating: browser.getChangeSetLink(cs) in /job/node-test-commit-windows/8

I will take a closer looks. At first glance, I think it's from the github repo browser not having a URL configured, which was intentional. If the exception is indeed caught then we can ignore this warning.

**Comment by rvagg** [comment]
we can ignore it, but it's filling up disk so ..

**Comment by orangemocha** [comment]
I will investigate.

**Comment by orangemocha** [comment]
> @orangemocha lots of these types of errors, I think this might be a config problem on your end:
>WARNING: Caught exception evaluating: browser.getChangeSetLink(cs) in /job/node-test-commit-windows/8

That issue should be fixed now. 
For the record, the repository browser adds a link next to every change  in the Jenkins job pages. Unfortunately it doesn't work with parametric repos, and any attempt to leave it blank will cause the warning in the log. It's silly, because the other two links work and I wish we could just remove the third link. Anyway, I hardcoded the root url to https://github.com/nodejs/node.

**Comment by jbergstroem** [comment]
How often do we read the master log? Perhaps turn it off?

@rvagg do I have ssh access to the master machine?

**Comment by rvagg** [comment]
no, just me and @wblankenship cause it's got NodeSource certs on it .. that'll change very soon when @mikeal gets the new certs paid for by the foundation, right @mikeal?

**Comment by orangemocha** [comment]
@jbergstroem rather than turning the log off, we could try to limit its size by only keep the more recent content. A quick search seems to indicate that this is possible with the logrotate utility: http://jenkins-ci.361315.n4.nabble.com/Huge-hudson-log-td3304780.html

**Comment by orangemocha** [comment]
Also, regarding artifacts, there is an option in Jenkins to only keep artifacts for the N most recent builds.

**Comment by jbergstroem** [comment]
1. The main issue was DO backup jobs -- now disabled
2. We were running into memory issues (eden size and old gc size). I've reshuffled the ratios and increased the heap sizes. Our load has gone from ~10 on active runs to <1.

I still think we should household artifacts, but that doesn't seem related to this. Closing.
