### ISSUE TITLE
Run internet tests with the CI

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1470]
Due to a comment from @cjihrig https://github.com/nodejs/node/pull/21559#issuecomment-405206308 it came to my attention that we have quite some tests that are not run with the regular CI, since they are prone to network issues. I would like to test how bad that is by running these tests with the regular CI but by just flagging them as flaky as long as they are not stable. Is that an option?

**Comment by refack** [comment]
This was brought up recently and the internet suite was added to run as part of the daily master test: https://ci.nodejs.org/job/node-daily-master/
If that is not enough, we could consider adding them as a special job, similar to the worker suite?

**Comment by joaocgreis** [comment]
Ref: https://github.com/nodejs/node/issues/13061
Last daily run: https://ci.nodejs.org/job/node-test-commit-custom-suites/656/

I believe the reason for not running them in regular CI was to not overload 3rd party servers with requests (I can't find a reference for this, probably a comment in some unrelated thread).

**Comment by refack** [comment]
> I believe the reason for not running them in regular CI was to not overload 3rd party servers with requests (I can't find a reference for this, probably a comment in some unrelated thread).

I _think_ it's also that some of our worker are behind firewalls.

**Comment by BridgeAR** [comment]
The dailies seem to be green runs. That is at least a indication that they are not as flaky as first anticipated.

I also just checked the servers that the internet tests contact and I would not bother about our requests against those.

The list currently contains these entries:

* 8.8.8.8 // Google Public DNS IPv4 address
* 2001:4860:4860::8888 //  Google Public DNS IPv6
* something.invalid // invalid host that cannot be resolved
* nodejs.org
* blog.nodejs.org
* _jabber._tcp.google.com // A host with SRV records registered
* 8.8.8.8.in-addr.arpa // A host with PTR records registered
* sip2sip.info // A host with NAPTR records registered

So I would be in favor of running these tests with the regular CI. That way their coverage should also be included in the overall coverage report, right?

**Comment by BridgeAR** [comment]
That would probably already be enough in this case :-).

**Comment by mhdawson** [comment]
As context, a number of tests were moved to internet specifically to avoid overload/loading external sites as mentioned.

**Comment by refack** [comment]
Resolved in CI:
https://ci.nodejs.org/job/node-test-commit-linux-coverage/jobConfigHistory/showDiffFiles?timestamp1=2018-09-08_19-05-38&timestamp2=2018-09-09_23-00-55
