### ISSUE TITLE
linux-s390x doesn't show up in `index.json`

### ISSUE THREAD

**Issue by kfarnung** [nodejs/build#1474]
@gdams is trying to get NVS working for s390x and while investigating I noticed that there's no entry for s390x in the `index.json` file in the release folder:

https://nodejs.org/download/release/index.json

Is there some step required to add new architectures to that file?

Refs: https://github.com/jasongin/nvs/issues/100

**Comment by refack** [comment]
@kfarnung See https://github.com/nodejs/nodejs-dist-indexer

**Comment by kfarnung** [comment]
I opened a PR: https://github.com/nodejs/nodejs-dist-indexer/pull/7

**Comment by kfarnung** [comment]
Thanks @refack!

**Comment by ljharb** [comment]
After that's updated, will previous releases that have s390x available be updated? (ie, will the bugfix be retroactive)

**Comment by rvagg** [comment]
@ljharb yep, I'll make that happen today
