### ISSUE TITLE
Jenkins slave ubuntu1504-64-1 git errors

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#148]
See https://jenkins-iojs.nodesource.com/job/node-test-commit-linux/62/nodes=ubuntu1504-64/console
It turns out this is not related to the git update. It looks more like a disk space issue. I don't have access to this machine.

@rvagg @jbergstroem can you please take a look and/or add me and @joaocgreis to the machine?

**Comment by orangemocha** [comment]
Still happening after master is fixed. This is now blocking CI

https://jenkins-iojs.nodesource.com/job/node-test-commit-linux/66/nodes=ubuntu1504-64/console

**Comment by rvagg** [comment]
I believe the 15.04 problem is simply about permissions, Jenkins seems to have been run as root at some point, making the directories and files owned by root, then running as iojs it doesn't have permission to update anything. A systemd config problem perhaps @jbergstroem? I've manually deleted the workspace and restarted using start.sh as iojs and will try again.

**Comment by orangemocha** [comment]
Perhaps we should remove 15.04 from the matrix while this issue gets resolved?

**Comment by rvagg** [comment]
nah, looking good now: https://jenkins-iojs.nodesource.com/job/node-test-commit-linux/68/nodes=ubuntu1504-64/console

**Comment by orangemocha** [comment]
Yay! I think we can proclaim the CI unblocked...

**Comment by rvagg** [comment]
not quite, linter machines are borked and failing

**Comment by orangemocha** [comment]
good thing the linter job is not blocking the rest of the job run.

**Comment by orangemocha** [comment]
@rvagg can I close this issue or do you need to track any follow-ups related to the 15.04 permission issue?

**Comment by rvagg** [comment]
will follow up later with @jbergstroem
