### ISSUE TITLE
release-macstadium-macos10.10-x64-1 - Unblock 8.12 release

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1486]
As a heads up:

* There are issues with the existing 10.10 osx machine which are blocking the release today
* Normally we would want to add a machine and test on nightlies, but we are starting to add a 10.10 machine to MacStadium as a backup.

This issue is to track/make that visible

**Comment by mhdawson** [comment]
Manual steps here: https://github.com/nodejs/build/issues/1393

**Comment by mhdawson** [comment]
Transferred 2 of the required packages to our stable storage on the ci

downloads@infra-digitalocean-ubuntu14-x64-1:~/www/osx$ ls
Packages.dmg  XZ.pkg

**Comment by gdams** [comment]
https://github.com/nodejs/build/pull/1487

**Comment by gdams** [comment]
following the steps here:

For release machines:

    

- [ ] Install PackageMaker, download "Auxiliary Tools for Xcode - Late July 2012" from the Apple Developer site to get it, put it in ~iojs/PackageMaker.app (RV: need to check whether Node 6 needs this any more, possibly that died with Node 4?)
    

- [ ] Install Packages from http://s.sudre.free.fr/Software/Packages/about.html
   

- [ ] Install xz utilities from http://macpkg.sourceforge.net/
   

- [ ] Install Node.js Foundation code signing and package signing certificates
        Available from either the secrets repository under "release" as a passwordless .p12 file
        OS X 10.10: In Keychain Access, "Import Items" and add both the Installer and Application certificates to the "System" (not "login" which is default)
        OS X 10.10: Find the private key for Node.js Foundation under System in Keychain Access, "Get Info" for it, switch to "Access Control" and allow access by all applications. This step requires a physical keyboard under El Capitan and onward.
        Command line alternative (all OS X?): sudo security import /path/to/id.p12 -k /Library/Keychains/System.keychain -T /usr/bin/codesign -T /usr/bin/productsign
    
- [ ] Add ssh_config as ~iojs/.ssh/config
- [ ] Install the staging key as ~/.ssh/id_rsa

**Comment by mhdawson** [comment]
We have created a new machine but I've tagged it so it won't be used by the regular release job since we first need to validate if PackageMaker is needed for 6.x or not.  We should also do some testing with nightly releases first.

I have created a new job called " iojs+release-new-osx-temp" that I think I have configured to use the new machine properly.

Running a test build here to see if it builds/publishes ok:  https://ci-release.nodejs.org/computer/release-macstadium-macos10.10-x64-1/

If we decide to publish the release with the new machine we should then be able to use this job to run/create the required artifacts.

**Comment by mhdawson** [comment]
Looks like the job passed @MylesBorins  FYI.

**Comment by rvagg** [comment]
👍 looking good, I also confirmed in `Makefile` that we removed the PackageMaker dependency prior to Node 6, so we can expunge that entirely from our records 🎉.
Once we get this online I'd love to get the release machine off my network, maybe the test one too. I could keep them around for backup purposes but maintaining these VMs isn't fun on macOS.

**Comment by mhdawson** [comment]
Test job for 6.x also passed.

@nodejs/build what other testing should we do before switching over to the new machine?

**Comment by mhdawson** [comment]
@nodejs/build, ping.  We might want to \switch over after the 8.12 tomorrow release so that we get a few current releases before the 10.X goes LTS.  @MylesBorins any suggestions/concerns over timing for a switch over?

**Comment by joaocgreis** [comment]
@mhdawson for Windows machines I build a test release, and make sure it can be installed and native modules can be compiled with/for it. Make sure the package is signed (ref https://github.com/nodejs/node/pull/14179, though there's not much of a conclusion there). Not sure if there's anything else specific for osx, but if the items above work it should be ok to add to the pool. I'd keep both around for a few days, since the old one is working now.

**Comment by mhdawson** [comment]
@gdams could you take the action to complete the steps that @joaocgreis suggests.  I think Rod may have validated some of those, but a complete check makes sense. Earlier test build was here: k: https://ci-release.nodejs.org/computer/release-macstadium-macos10.10-x64-1/, and one for 6.x here.  We probably also want to test 10.x: kicking off build https://ci-release.nodejs.org/job/iojs+release-new-osx-temp/3/

Let me know if you need me to kick off any other builds or need help mapping the builds to test releases published on the Node.js web site.

**Comment by MylesBorins** [comment]
@refack this rebase seems to have regressed the xz tar utility and is potentially blocking our LTS release tomorrow. Is someone able to fix this ASAP?

**Comment by MylesBorins** [comment]
It seems like the machine may need the below step manually done again.

* Install xz utilities from http://macpkg.sourceforge.net/

This is blocking the 10.13.0 LTS release, can someone please fix this ASAP

**Comment by rvagg** [comment]
FYI I've asked to break contract with my ISP over the network problem they haven't resolved, but they want one last chance to try and fix it, hoping to have it resolved this week one way or another.

**Comment by rvagg** [comment]
OK, yeah, start.sh didn't match #1511. Rebuilt @ https://ci-release.nodejs.org/job/iojs+release/3878/nodes=osx1010-release-tar/ and it's all good. You have a .xz now.

The 10.11 machine didn't match either. I updated manually (I haven't personally run Ansible on these machines so am a little wary!) I can't explain why there is a mismatch other than simply that #1511 wasn't run on the release hosts?

**Comment by MylesBorins** [comment]
quoting @rvagg in #1551 

> OK, yeah, start.sh didn't match #1511. Rebuilt @ https://ci-release.nodejs.org/job/iojs+release/3878/nodes=osx1010-release-tar/ and it's all good. You have a .xz now.

**Comment by mhdawson** [comment]
@gdams still hoping you are going to complete the planned steps, unless other people from the @nodejs/build don't think we need to as the machine is already being used for releases...

**Comment by mhdawson** [comment]
@MylesBorins looking at the issue in #1551 it sounds like the machine was fixed up and is now ok.

**Comment by mhdawson** [comment]
I think this is done, closing.
