### ISSUE TITLE
centos6-x86-1 in build CI is offline

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1490]

**Comment by refack** [comment]
we don't have and `centos6-x86`, do you mean `centos5-x86` (https://ci.nodejs.org/computer/test-digitalocean-centos5-x86-1/)?
It's been known to kill it's jenkins agent, so I've set a cron to revive it.

**Comment by rvagg** [comment]
I think maybe this was about release-digitalocean-centos6-x86-1, which was do in ci-release, along with release-digitalocean-centos5-x86-1 (which isn't actually used anymore). I've sorted that out, but we've got a similar problem with CI for centos5 and centos6--we use init and don't have monit installed so we don't get auto-restart when it dies. From memory we didn't switch to upstart on centos6 cause it's an early version of upstart and is almost as awkward as init without providing much more functionality. The lack of monit is a problem though and probably needs to be addressed in Ansible.
