### ISSUE TITLE
ci-change: try to prune `node-test-binary-windows`

### ISSUE THREAD

**Issue by refack** [nodejs/build#1493]
Tracing CPU usage seems to indicate `node-test-binary-windows` is eating a lot of CPU, so I tried to find what could be removed, so I removed references to vs2013 (which AFAIK is relevant only for node v4). We still get VS2013 addons testing with `node-gyp` CI.

https://ci.nodejs.org/job/node-test-binary-windows/jobConfigHistory/showDiffFiles?timestamp1=2018-09-08_19-05-40&timestamp2=2018-09-11_16-45-26

/CC @joaocgreis

**Comment by joaocgreis** [comment]
Reverted as discussed in IRC. I'll take a look at the workspaces.

**Comment by joaocgreis** [comment]
@refack can you provide details on how you found that CPU usage was because of `node-test-binary-windows`? I'd like to keep investigating that. Thanks!

**Comment by refack** [comment]
@joaocgreis see https://github.com/nodejs/build/issues/1488#issuecomment-420407039

**Comment by joaocgreis** [comment]
For reference, the stack is visible at https://ci.nodejs.org/monitoring?part=currentRequests . Thanks!
