### ISSUE TITLE
jenkins: e-mail notification on job completion

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1502]
I've been looking into how to easily setup #746 so collaborators get notified when a job finishes. The easiest way is to notify by e-mail and let the collaborator opt-in when they want to be notified.

To accomplish that, we need to use [Email-ext plugin](https://wiki.jenkins.io/display/JENKINS/Email-ext+plugin), because Jenkins Mailer Plugin only notifies on failures (or success builds after failures).

I tested this in a separate job and it seems to be working. Collaborators will have another field to fill when they want to be notified:

![image](https://user-images.githubusercontent.com/4048656/45821955-ccc4ea80-bcc0-11e8-9be2-c28c7d0fe6aa.png)

The e-mail will look like this (we can improve the message in the future):

![image](https://user-images.githubusercontent.com/4048656/45823314-cd12b500-bcc3-11e8-8c58-22edfd16a121.png)

Steps to add this to `node-test-pull-request`:

### Add a new paramenter `NOTIFY_EMAILS`

![image](https://user-images.githubusercontent.com/4048656/45821860-96876b00-bcc0-11e8-908e-c8615e1f1188.png)

### Add a new post-build action `Editable Email Notification`

* Set *Project Recipient List* to `$NOTIFY_EMAILS`
* Leave *Project Reply To List* empty

![image](https://user-images.githubusercontent.com/4048656/45821902-ae5eef00-bcc0-11e8-8228-9dbba7b00ebc.png)

### Advanced `Editable Email Notification` setting

* Remove all Triggers
* Add a new one
  * When: Always
  * Send to: Recipient List

![image](https://user-images.githubusercontent.com/4048656/45821923-b9198400-bcc0-11e8-9870-a42288bbecf5.png)

If @nodejs/build is fine with this approach, I can make the changes to `node-test-pull-request`.

**Comment by mhdawson** [comment]
I assume it does not affect the existing notifications on failures.  As long as that is the case +1 from me.

**Comment by mmarchini** [comment]
These settings shouldn't interfere with existing notifications.
