### ISSUE TITLE
CI Change: set description

### ISSUE THREAD

**Issue by refack** [nodejs/build#1506]
I've added code to set the description to:
```
Testing <a href=https://github.com/$TARGET_GITHUB_ORG/$TARGET_REPO_NAME/pull/$PR_ID>$PR_ID</a>
```
changeset 1: https://ci.nodejs.org/job/node-test-pull-request/jobConfigHistory/showDiffFiles?timestamp1=2018-09-11_20-24-32&timestamp2=2018-09-26_12-53-40

Changeset 2: https://ci.nodejs.org/job/node-test-commit/jobConfigHistory/showDiffFiles?timestamp1=2018-09-11_19-53-04&timestamp2=2018-09-26_12-59-09

**Comment by joaocgreis** [comment]
This is great! Thanks for the heads up.

**Comment by mhdawson** [comment]
Thanks for the heads up :)
