### ISSUE TITLE
ci: retire ubuntu17

### ISSUE THREAD

**Issue by refack** [nodejs/build#1508]
Several $REASONS:
1. We test ubuntu 16 & 18
2. Our two worker are kind of slim for they back backlogged
3. 17 is EOL

Version | Code name | Docs | Release date | End of Life date
-- | -- | -- | -- | --
Ubuntu 17.10 | Artful Aardvark | Release Notes | October 19, 2017 | July 19 2018
Ubuntu 17.04 | Zesty Zapus | Rel | April 13, 2017 | January 13, 2018

**Comment by rvagg** [comment]
yep, rip it out! our policy is to remove non-LTS Ubuntu versions pretty much as soon as they end support.

**Comment by refack** [comment]
Done.
/CC @nodejs/citgm (CITGM was the other job that used ubuntu17, which I switched to ubuntu18)
