### ISSUE TITLE
ci-change: Add groovy platform filter to CITGM

### ISSUE THREAD

**Issue by refack** [nodejs/build#1509]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/jobConfigHistory/showDiffFiles?timestamp1=2018-09-27_11-21-28&timestamp2=2018-09-27_11-30-43

Also added macOS10.11 for macOS covrage of node10 & node11.

Test job:
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1564/:
```
11:30:52 Node.js major version: 11
11:30:52 Node.js version: 11.0.0
11:30:52 Skipping osx1010 for Node.js 11
11:30:52 Skipping ppcbe-ubuntu1404 for Node.js 11
11:30:52 Skipping debian8-x86 for Node.js 11
11:30:52 Skipping ubuntu1204-64 for Node.js 11
11:30:52 Running nodes
```

**Comment by richardlau** [comment]
Refs: https://github.com/nodejs/build/issues/1430

**Comment by refack** [comment]
I did something similar to `citgm-smoker-nobuild`
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/jobConfigHistory/showDiffFiles?timestamp1=2018-09-21_11-32-06&timestamp2=2018-09-27_16-53-35

Test job https://ci.nodejs.org/job/citgm-smoker-nobuild/418/ (there is still an issue with IBM platforms, to be fixed by https://github.com/nodejs/build/pull/1510)
