### ISSUE TITLE
Access to AIX and SmartOS machine for ofrobots

### ISSUE THREAD

**Issue by ofrobots** [nodejs/build#1514]
Needed to investigate
* nodejs/node#23110
* https://github.com/libuv/libuv/pull/2003

**Comment by mhdawson** [comment]
@refack Thanks :)

**Comment by mhdawson** [comment]
@ofrobots how long do you need access for to the AIX machine?  There are only 2 and @refack took 1 of the 2 offline while you investigate.

**Comment by ofrobots** [comment]
Oh, I didn't know resources were this constrained. I started debugging on smartOS first. You can put the AIX machine back in the pool, and I will ping this thread when I am ready to debug on it.

**Comment by mhdawson** [comment]
@ofrobots thanks, re-enabled AIX for now.

**Comment by ofrobots** [comment]
@mhdawson I'm ready to debug on AIX now.. could my access be restored?

**Comment by refack** [comment]
offline - ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-1
back online - ci.nodejs.org/computer/test-joyent-smartos17-x64-2

**Comment by refack** [comment]
I'm closing this and removing the key.
Please ping me is needed again.
