### ISSUE TITLE
chore: list compiler versions used to build each node version on each platform

### ISSUE THREAD

**Issue by refack** [nodejs/build#1522]
(for new contributors, this one might require some GitHub archaeology)

**Comment by tiagorvmartins** [comment]
Hi @refack do you think I can help out in this issue? Thanks :)

**Comment by refack** [comment]
Hello @tiagorvmartins, you sure could give it a try 👍 

I'll give you some leads.
1. We started the based for this kind of list at https://github.com/nodejs/build/blob/master/doc/windows-visualstudio-supported-versions.md
2. You can see the output of our testing CI runs, for example https://ci.nodejs.org/job/node-daily-master/1361/, more specifically https://ci.nodejs.org/job/node-test-commit-osx/22932/nodes=osx1011/consoleText
   Most of those have a call to print the compiler version (or `xcode_version`).
3. The platforms in CI are selected according to this filtering script https://github.com/nodejs/build/blob/master/jenkins/scripts/VersionSelectorScript.groovy (notice it's an exclusion rules)
4. We setup our platforms with `Ansible` and the scripts are in https://github.com/nodejs/build/tree/master/ansible

I think if you can do this for node 11, and 12 (which is the current `master`) that would be amazing.

**Comment by tiagorvmartins** [comment]
Thanks for the info @refack , seems quite hard for me for a starting point (first contribution on github here xD), but after a quick investigation can you just clarify me that I only need to update the VersionSelectorScript.groovy with the new hosts from the first list you noted? Or does it involve more work beside it? Thanks!

**Comment by refack** [comment]
FTR:

Some more references:

* https://github.com/nodejs/build/commits/master/setup (this is a history of our old machine setup scripts)
* https://github.com/nodejs/build/commits/master/ansible (this is a history of our current setup scripts)
* https://github.com/nodejs/build/issues/259
* https://github.com/nodejs/build/pull/809
* https://github.com/nodejs/build/issues/1580 (wrong assumption, but has some history)
* https://github.com/nodejs/node/pull/16969
* https://github.com/nodejs/node/pull/14004
* https://github.com/nodejs/node/issues/8172
* https://github.com/nodejs/node/commits/master/BUILDING.md
* https://github.com/nodejs/build/commits/master/ansible/roles/package-upgrade/tasks/partials/brew.yml
* https://github.com/nodejs/build/pull/971


More references about the minimal supported platforms, but we sometimes test & release with newer compilers.

* https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms-1
* https://github.com/nodejs/node/blob/v11.x/BUILDING.md#supported-platforms-1
* https://github.com/nodejs/node/blob/v10.x/BUILDING.md#supported-platforms-1
* https://github.com/nodejs/node/blob/v9.x/BUILDING.md#supported-platforms-1
* https://github.com/nodejs/node/blob/v8.x/BUILDING.md#supported-platforms-1

There are older ones but they don't even have the "supported platform list"  

* https://github.com/nodejs/node/blob/v7.x/BUILDING.md#supported-platforms-1
* https://github.com/nodejs/node/blob/v6.x/BUILDING.md#supported-platforms-1

**Comment by refack** [comment]
> Thanks for the info @refack , seems quite hard for me for a starting point (first contribution on github here xD), but after a quick investigation can you just clarify me that I only need to update the VersionSelectorScript.groovy with the new hosts from the first list you noted, even though its an exclusion rule there? Or does it involve more work beside it? Thanks!

What we're looking for here is basically a text document describing in part what `VersionSelectorScript.groovy` does.
It will help us document and publish parameters that are hidden within Jenkins and Ansible, **and** help us make sure thing like https://github.com/nodejs/build/pull/1596 are correct.

**Comment by rvagg** [comment]
Oh I was toying with this yesterday while working on #1596. Here's a Groovy script that will print out what builder is used for releases of any given version of Node:

```groovy
def result = [:]
def parameters = [:]
def combinations = []

combinations.push([ nodes: 'aix61-ppc64' ])
combinations.push([ nodes: 'centos5-release-32' ])
combinations.push([ nodes: 'centos5-release-64' ])
combinations.push([ nodes: 'centos6-32-gcc48' ])
combinations.push([ nodes: 'builtcentos6-32-gcc6' ])
combinations.push([ nodes: 'centos6-64-gcc48' ])
combinations.push([ nodes: 'centos6-64-gcc6' ])
combinations.push([ nodes: 'centos7-arm64-gcc48' ])
combinations.push([ nodes: 'centos7-arm64-gcc6' ])
combinations.push([ nodes: 'cross-compiler-armv6-gcc-4.9.4' ])
combinations.push([ nodes: 'cross-compiler-armv7-gcc-4.9.4' ])
combinations.push([ nodes: 'debian7-docker-armv7' ])
combinations.push([ nodes: 'osx1010-release-pkg' ])
combinations.push([ nodes: 'osx1010-release-tar' ])
combinations.push([ nodes: 'osx1011-release-pkg' ])
combinations.push([ nodes: 'osx1011-release-tar' ])
combinations.push([ nodes: 'pi1-docker' ])
combinations.push([ nodes: 'ppcbe-ubuntu1404-release-64' ])
combinations.push([ nodes: 'ppcle-ubuntu1404-release-64' ])
combinations.push([ nodes: 'rhel72-s390x-release' ])
combinations.push([ nodes: 'smartos14-release' ])
combinations.push([ nodes: 'smartos15-release' ])
combinations.push([ nodes: 'smartos17-release' ])
combinations.push([ nodes: 'builtvs2013-x64' ])
combinations.push([ nodes: 'builtvs2013-x86' ])
combinations.push([ nodes: 'vs2015-x64' ])
combinations.push([ nodes: 'vs2015-x86' ])
combinations.push([ nodes: 'vs2017-x64' ])
combinations.push([ nodes: 'vs2017-x86' ])

parameters['NODEJS_MAJOR_VERSION'] = '10'

Binding binding = new Binding()
binding.setVariable('result', result)
binding.setVariable('parameters', parameters)
binding.setVariable('combinations', combinations)
binding.setVariable('buildType', 'release')
new GroovyShell(binding).evaluate(new File('VersionSelectorScript.groovy'))

result.nodes.each{
  println it
}
```

You get the following for `10`:

```
[nodes:vs2017-x86]
[nodes:vs2017-x64]
[nodes:builtvs2013-x86]
[nodes:builtvs2013-x64]
[nodes:smartos17-release]
[nodes:rhel72-s390x-release]
[nodes:ppcle-ubuntu1404-release-64]
[nodes:osx1010-release-tar]
[nodes:osx1010-release-pkg]
[nodes:cross-compiler-armv7-gcc-4.9.4]
[nodes:cross-compiler-armv6-gcc-4.9.4]
[nodes:centos7-arm64-gcc6]
[nodes:centos6-64-gcc6]
[nodes:aix61-ppc64]
```

It's just not quite useful enough to feed into something like #1596, but there's potential here for _something_.
