### ISSUE TITLE
Nominating @forivall for the Build WG

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1524]
Emily Klassen is interested in Build WG and I would like to nominate her. She's good with Linux build,
Python 2 migration tool stuff, and probably lots of other things that I don't even know about.

So maybe we can set her up with some stuff to review and get her as an observer at a meeting and/or have a videochat with someone who can talk to her about what the Build WG needs/paint points are and where she might be most valuable.

I believe the "stuff to read/review" list might include:

* https://github.com/nodejs/build/tree/master/doc
* What else?

**Comment by Trott** [comment]
Just in case it doesn't @-notify in the title: @forivall

**Comment by Trott** [comment]
Oh, yeah, maybe she should join #node-build on IRC and lurk or participate.

**Comment by mhdawson** [comment]
Great to have more help with things.  @gdams I wonder if there is anything on the ansible tower or keybox you might get @forivall to help out with?

**Comment by refack** [comment]
Hello @forivall, feel free to ping me on IRC with any questions.

> I believe the "stuff to read/review" list might include:
> 
> * [/doc@`master`](https://github.com/nodejs/build/tree/master/doc)
> * What else?

Specifical https://github.com/nodejs/build/blob/master/doc/services.md as an overview.

**Comment by forivall** [comment]
Yeah, i'll take a look at those things when i get the chance, either some evening or this weekend.

**Comment by Trott** [comment]
I'd still love to see @forivall get involved in the Build WG. Is there a blocker on this on the Node.js end that we might identify that could clear a path for more activity?

**Comment by forivall** [comment]
I do still need to start looking into things too -- i've unfortunately stalled out.

**Comment by sam-github** [comment]
Hi Emily, nice to see you again. I'm not sure what kinds of things there are to do, or that you are interested in, but the issue tracker is way full. It might be a good place to start looking for things to do, or even just to read through and ping people on things that need doing or issue that might be closable.
