### ISSUE TITLE
Neverending iojs+release jobs

### ISSUE THREAD

**Issue by targos** [nodejs/build#1525]
See https://ci-release.nodejs.org/job/iojs+release/
There are currently 10 jobs that are still running and it's not obvious to me what is keeping them in this state.

**Comment by refack** [comment]
I think it's because `release-macstadium-macos10.11-x64-1` is down.
@nodejs/build-infra @gdams

**Comment by mhdawson** [comment]
Brought it back on-line

@gdams could you look at the logic that should be restarting the agent as I've had to restart a number of times in the release machine.  If there is some logging I should look for to help understand what is happening just let me know.
