### ISSUE TITLE
Last Nightlies lack docs and macOS binaries

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/build#1526]
Last full build: https://nodejs.org/download/nightly/v11.0.0-nightly20181007061e09891c/

Is it worth to transfer doc building to another OS? macOS seems to fail rather often, without being noticed several days.

**Comment by refack** [comment]
This is the consequence of https://github.com/nodejs/build/issues/1525, if those jobs finish, those artifacts will might get published eventually.

**Comment by vsemozhetbyt** [comment]
Seems fixed.
