### ISSUE TITLE
Separate Jenkins task for master

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#153]
I'd like a separate jenkins task ontop of `node-test-commit` for specifically testing `master`, that way it'd be easier to tell when failures developed. Having this automatically happen nightly/daily would be nice some day.

I'd do it myself since it seems pretty easy, but I don't have access, and I don't know how to configure jenkins. :)

cc @orangemocha?

**Comment by orangemocha** [comment]
@Fishrock123 sure. Since you can sort of already do that with node-test-commit, are you looking for a simpler entry-point to test any branch, or for a job to run on daily schedule on master, or both?

**Comment by Fishrock123** [comment]
@orangemocha I mostly want an overview that shows *just master*. Then automating it would be nice.

**Comment by orangemocha** [comment]
No problem @Fishrock123 . I think running it on a fixed schedule should be easy. I can take care of it.

Note that once/if we adopt node-accept-pull-request, it will test every commit that goes into the branch so it will in theory not let any failures develop. Anyway, the master daily test can still be useful.

**Comment by orangemocha** [comment]
https://jenkins-iojs.nodesource.com/job/node-daily-master/

**Comment by Fishrock123** [comment]
\o/ Thanks @orangemocha :)

**Comment by orangemocha** [comment]
You are welcome @Fishrock123 ! It was actually really easy to make.

**Comment by Fishrock123** [comment]
@orangemocha I noticed this test runs somewhat towards the day NA time (our busiest), do you think we could schedule it for like, night-time NA?

**Comment by orangemocha** [comment]
@Fishrock123 : I changed it to 2am PST.
