### ISSUE TITLE
CI: all nodes of label 'pi3-raspbian-stretch' are offline

### ISSUE THREAD

**Issue by targos** [nodejs/build#1544]
See https://ci.nodejs.org/job/git-nodesource-update-reference/

This is blocking `node-test-commit-arm-fanned` and hence `node-test-pull-request`.

**Comment by refack** [comment]
`node-test-commit-arm-fanned` is back to `disabled` for the time being
but expect ci-release issues https://ci-release.nodejs.org/computer/
ping @rvagg

**Comment by refack** [comment]
Resolved
