### ISSUE TITLE
'GLIBCXX_3.4.20' not found on s390

### ISSUE THREAD

**Issue by targos** [nodejs/build#1548]
@nodejs/platform-s390 

The `citgm-continuous-integration` job fails on `rhel72-s390x` with a concerning error.
This happens with Node 10 and 11.

https://ci.nodejs.org/job/citgm-continuous-integration/131/MACHINE=rhel72-s390x/console

```
+ gzip -cd node-v11.0.0-linux-s390x.tar.gz
+ tar xf -
[rhel72-s390x] $ /bin/sh -xe /tmp/jenkins7985328420173854426.sh
+ cd /data/iojs/build/workspace/citgm-continuous-integration/MACHINE/rhel72-s390x/node-v11.0.0-linux-s390x/bin
+ export PATH=/data/iojs/build/workspace/citgm-continuous-integration/MACHINE/rhel72-s390x/node-v11.0.0-linux-s390x/bin:/usr/lib/ccache:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/data/iojs/build/workspace/citgm-continuous-integration/MACHINE/rhel72-s390x/node-v11.0.0-linux-s390x/bin:/usr/lib/ccache:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ cd /data/iojs/build/workspace/citgm-continuous-integration/MACHINE/rhel72-s390x
+ node -v
node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
```

**Comment by richardlau** [comment]
The job needs to run [`jenkins/scripts/select-compiler.sh`](https://github.com/nodejs/build/blob/master/jenkins/scripts/select-compiler.sh) to set the `LD_LIBRARY_PATH` to point at the gcc-4.9 runtime libraries.

**Comment by gdams** [comment]
I've added the following to the job
```bash
rm -rf build
git clone https://github.com/nodejs/build.git
. ./build/jenkins/scripts/select-compiler.sh
``` 

but it seems to be looking for `tools/getnodeversion.py` which I can't seem to find?

**Comment by richardlau** [comment]
> 
> 
> I've added the following to the job
> 
> ```shell
> rm -rf build
> git clone https://github.com/nodejs/build.git
> . ./build/jenkins/scripts/select-compiler.sh
> ```
> 
> but it seems to be looking for `tools/getnodeversion.py` which I can't seem to find?

Ah it does that if `NODEJS_MAJOR_VERSION` isn't set. `tools/getnodeversion.py` is from the main `nodejs/node` repo which this job doesn't checkout (and shouldn't) since it's running the prebuilt Node.js binaries. 

Maybe set `NODEJS_MAJOR_VERSION` by slicing off the `v` off `NODE_VERSION` (otherwise changing the `NODE_VERSION` parameter to `NODEJS_MAJOR_VERSION` and dropping the `v` prefix is a bigger job refactor)?

**Comment by mhdawson** [comment]
The job must already know/figure out what the major node version is, it should just e able to set NODEJS_MAJOR_VERSION

**Comment by mhdawson** [comment]
I'm a bit concerned that we are only discovering this now.  @targos do you know if was running ok earlier?

**Comment by targos** [comment]
I don't know. We do not execute this job very often.

**Comment by gdams** [comment]
fixed: https://ci.nodejs.org/job/citgm-continuous-integration/nodes=rhel72-s390x/139/console

**Comment by refack** [comment]
FTR: https://ci.nodejs.org/job/citgm-continuous-integration/jobConfigHistory/showDiffFiles?timestamp1=2018-10-27_09-00-33&timestamp2=2018-10-29_10-25-38
Refs: https://github.com/nodejs/build/issues/1549

**Comment by gdams** [comment]
yeah I'll copy the changes in here:

```bash
  | rm -rf build
  | export NODEJS_MAJOR_VERSION="${NODE_VERSION:1}"
  | git clone https://github.com/nodejs/build.git
  | . ./build/jenkins/scripts/select-compiler.sh
```
