### ISSUE TITLE
citgm jobs shouldn't run on ppcbe-ubuntu1404 for Node >= 8

### ISSUE THREAD

**Issue by targos** [nodejs/build#1549]
See failures:
- https://ci.nodejs.org/job/citgm-continuous-integration/129/
- https://ci.nodejs.org/job/citgm-continuous-integration/130/ 
- https://ci.nodejs.org/job/citgm-continuous-integration/131/

@nodejs/citgm-admins

**Comment by refack** [comment]
I've implemented our `VersionSelectorScript.groovy`
https://ci.nodejs.org/job/citgm-continuous-integration/jobConfigHistory/showDiffFiles?timestamp1=2018-09-08_19-05-43&timestamp2=2018-10-27_09-00-33
I've also removed `ubuntu1204` (which is EOL) and added `osx11` and `ubuntu1804`

Please reopen is you find any bugs.

**Comment by targos** [comment]
Thanks!
