### ISSUE TITLE
OSX 10.10 in release-ci is not creading tar.xz artifacts

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1551]
This seems to have regressed at some point in the last 19 days, potentially [during a rebasee](https://github.com/nodejs/build/issues/1486#issuecomment-430282578)

It seems like the machine may need the below step manually done again.

    Install xz utilities from http://macpkg.sourceforge.net/

This is blocking the 10.13.0 LTS release, can someone please fix this ASAP

**Comment by MylesBorins** [comment]
It is worth mentioning that I only discovered this during manual testing of the rc with nvm... the missing .gz artifcact caused nvm to explode.

We currently have no tests for this and we would have failed silently and potentially released with missing artifacts, if it hadn't been caught.

**Comment by rvagg** [comment]
How about let's switch the logic to fail if `xz` doesn't exist and you have to provide a flag to get around it?

**Comment by rvagg** [comment]
on that host:

```
release-macstadium-macos10:~ administrator$ which xz
/usr/local/bin/xz
release-macstadium-macos10:~ administrator$ xz --version
xz (XZ Utils) 5.0.7
liblzma 5.0.7
```

🤷‍♂️ a PATH problem maybe? digging.

**Comment by MylesBorins** [comment]
@rvagg +1 to failing if xz doesn't exist.

Is `/usr/local/bin` in the path?

**Comment by rvagg** [comment]
OK, yeah, start.sh didn't match #1511. Rebuilt @ https://ci-release.nodejs.org/job/iojs+release/3878/nodes=osx1010-release-tar/ and it's all good. You have a .xz now.

The 10.11 machine didn't match either. I updated manually (I haven't personally run Ansible on these machines so am a little wary!) I can't explain why there is a mismatch other than simply that #1511 wasn't run on the release hosts?

**Comment by mhdawson** [comment]
I don't believe I ran ansible to update the release machines (nor did I have any Idea I needed) to after #1511
