### ISSUE TITLE
Accessing to plinux and SmartOS hosts for investigation of OpenSSL-1.1.1 issues.

### ISSUE THREAD

**Issue by shigeki** [nodejs/build#1561]
CI of https://ci.nodejs.org/job/node-test-commit/22834/ shows that there are some unknown issues on plunux and SmartOS in upgrading OpenSSL-1.1.1. 

I do not have such OS and it needs for me to work on them to investigate the failures.  Can I get access to them?  My public key is https://github.com/shigeki.keys. 

Ref: https://github.com/nodejs/node/issues/18770

**Comment by mhdawson** [comment]
+1

**Comment by refack** [comment]
@shigeki 
test-osuosl-ubuntu1404-ppc64_le-2 - root@140.211.168.94
test-joyent-smartos16-x64-2 - root@72.2.113.74

**Comment by refack** [comment]
P.S. I've taken the machines off Jenkins, so please notify when you are or aren't using them:

https://ci.nodejs.org/computer/test-joyent-smartos16-x64-2/
https://ci.nodejs.org/computer/test-osuosl-ubuntu1404-ppc64_le-2/

**Comment by sam-github** [comment]
+1, /cc @nodejs/crypto

**Comment by shigeki** [comment]
@refack The issue of smartos was identified and the fix was made. Accessing to test-joyent-smartos16-x64-2 is no longer needed.  
The issue of plinux seems to be more difficult to be resolved and it needs for some time for me. Please keep my access for a while.

**Comment by refack** [comment]
@shigeki Thanks for the update, I'm updating the keys and bringing `test-joyent-smartos16-x64-2` back online.

**Comment by shigeki** [comment]
The plinux issue was identified and submited an issue to the upstream. https://github.com/openssl/openssl/issues/7584. I'm waiting for their reply.

**Comment by shigeki** [comment]
The issue was resolved by https://github.com/openssl/openssl/pull/7643. 

@refack Please remove my access on test-osuosl-ubuntu1404-ppc64_le-2. Thanks.

**Comment by refack** [comment]
Done. Thanks!
