### ISSUE TITLE
curl issues on test-requireio-osx1010-x64-1

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1563]
curl errors on test-requireio-osx1010-x64-1:
https://ci.nodejs.org/job/nodereport-continuous-integration/239/nodes=osx1010/console
```
+++ curl https://nodejs.org/download/release/
+++ tail -1
+++ sort -t. -k 1,1n -k 2,2n -k 3,3n
+++ cut '-d"' -f 2
+++ grep v8
+++ tr -d /
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0curl: (35) Server aborted the SSL handshake
++ echo
```

https://ci.nodejs.org/job/nodereport-continuous-integration/244/nodes=osx1010/console
```
+++ curl https://nodejs.org/download/release/

+++ sort -t. -k 1,1n -k 2,2n -k 3,3n

+++ grep v8

+++ tail -1
+++ cut '-d"' -f 2
+++ tr -d /

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0curl: (35) Unknown SSL protocol error in connection to nodejs.org:-36
++ echo
```

Expected behaviour:
test-macstadium-macos10.10-x64-2
https://ci.nodejs.org/job/nodereport-continuous-integration/242/nodes=osx1010/console
```
+++ curl https://nodejs.org/download/release/
+++ grep v8
+++ sort -t. -k 1,1n -k 2,2n -k 3,3n
+++ tail -1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0+++ cut '-d"' -f 2
+++ tr -d /

100 61977    0 61977    0     0   113k      0 --:--:-- --:--:-- --:--:--  113k
++ echo v8.12.0
```

**Comment by richardlau** [comment]
> BTW: we should switch this job to use NVS like https://ci.nodejs.org/job/nodegyp-test-commit/configure

Can NVS pick up the nightly (12.0.0-pre) builds?

**Comment by refack** [comment]
> Can NVS pick up the nightly (12.0.0-pre) builds?

Seems so - https://github.com/jasongin/nvs/blob/master/README.md#configurable-remotes
/ping @jasongin

**Comment by refack** [comment]
@rvagg might be time to restart `test-requireio-osx1010-x64-1`
```
USER              PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
_windowserver     137  73.4  0.5  2632800  22552   ??  Ss    4Oct18 13203:50.66 /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Resources/WindowServer -daemon
iojs            35146  66.7  0.7  4905108  28616   ??  R     8:56AM   1:51.24 /usr/bin/java -jar slave.jar -jnlpUrl https://ci.nodejs.org/computer/test-requireio-osx1010-x64-1/slave-agent.jnlp -secret f4f5e391fccc0723e964930d77b59cfb70415ca36c4ec8de
root              501  59.5  1.5  2502256  63192   ??  Rs    4Oct18 2510:07.77 /usr/libexec/systemstatsd
```

**Comment by richardlau** [comment]
FYI I tried using NVS but ran into problems on platforms that node-gyp isn't currently testing

e.g. https://ci.nodejs.org/job/nodereport-continuous-integration/251/ (ignore the Windows failures, that's a known node-report issue):
![image](https://user-images.githubusercontent.com/5445507/48015359-e317f000-e120-11e8-9686-37970c7ec122.png)

I've undone the changes because the old way worked and I don't have time right now to debug nvs remotely. In any case this issue is re. `test-requireio-osx1010-x64-1` so if anyone wants to pursue using nvs that should be a new issue.

Issues include:
- on AIX tar is native tar and not gnu tar
- ordering of the select-compiler script and nvs on AIX/LinuxOne (if run before nvs then curl fails on AIX but if run after nvs then LinuxOne can't run the bootstrap Node.js)
- no idea why os1012 and smartos are failing

**Comment by rvagg** [comment]
restarting the requireio osx hosts, but I've also signed up with another ISP which will hopefully go through in the next day or two and maybe I can move on from these connection problems.

**Comment by rvagg** [comment]
osx hosts restarted, took a little bit of yak shaving to do unfortunately

**Comment by rvagg** [comment]
going to cross fingers and say this is all fixed now that I've switched ISP
