### ISSUE TITLE
Accessing to arm64 for investing issues in TLS error.

### ISSUE THREAD

**Issue by shigeki** [nodejs/build#1567]
For further investigation of arm64 issues fo TLS error, I need to access and work on arm64 as commented in https://github.com/nodejs/node/issues/23913#issuecomment-437387238. 

CC @refack 
Ref: https://github.com/nodejs/node/issues/23913

**Comment by gdams** [comment]
I personally have no objections, can someone else from @nodejs/build approve as well?

**Comment by Trott** [comment]
+1

**Comment by refack** [comment]
+1
Will get to it later.

**Comment by refack** [comment]
Someone else already put the keys in 147.75.74.174

**Comment by shigeki** [comment]
Oops, I've forgot the same issue of https://github.com/nodejs/build/issues/842 in the Node-v8 and it occurs again in the current Node.  My key is still remained.  I will check if binaries as I did before.

**Comment by shigeki** [comment]
I've checked asm binaries have no difference between Node-v10 and bare openssl-1.1.0i as below. 
```
oot@test-packetnet-ubuntu1604-arm64-2:/var/tmp/shigeki/node# ls -l out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/*/*.o
-rw-r--r-- 1 root root   3576 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/aes/aesv8-armx.o
-rw-r--r-- 1 root root   5344 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/aes/vpaes-armv8.o
-rw-r--r-- 1 root root   5592 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/bn/armv8-mont.o
-rw-r--r-- 1 root root   8152 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/chacha/chacha-armv8.o
-rw-r--r-- 1 root root 162168 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/ec/ecp_nistz256-armv8.o
-rw-r--r-- 1 root root   1520 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/modes/ghashv8-armx.o
-rw-r--r-- 1 root root   3784 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/poly1305/poly1305-armv8.o
-rw-r--r-- 1 root root   5712 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/sha/sha1-armv8.o
-rw-r--r-- 1 root root   5544 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/sha/sha256-armv8.o
-rw-r--r-- 1 root root   5296 Nov 13 06:50 out/Release/obj.target/openssl/deps/openssl/config/archs/linux-aarch64/asm/crypto/sha/sha512-armv8.o

root@test-packetnet-ubuntu1604-arm64-2:/var/tmp/shigeki/node# ls -l ../openssl-1.1.0i/crypto/*/*.o |grep arm
-rw-r--r-- 1 root root   3576 Nov 13 06:02 ../openssl-1.1.0i/crypto/aes/aesv8-armx.o
-rw-r--r-- 1 root root   5344 Nov 13 06:02 ../openssl-1.1.0i/crypto/aes/vpaes-armv8.o
-rw-r--r-- 1 root root   5592 Nov 13 06:02 ../openssl-1.1.0i/crypto/bn/armv8-mont.o
-rw-r--r-- 1 root root   8152 Nov 13 06:02 ../openssl-1.1.0i/crypto/chacha/chacha-armv8.o
-rw-r--r-- 1 root root 162168 Nov 13 06:02 ../openssl-1.1.0i/crypto/ec/ecp_nistz256-armv8.o
-rw-r--r-- 1 root root   1520 Nov 13 06:02 ../openssl-1.1.0i/crypto/modes/ghashv8-armx.o
-rw-r--r-- 1 root root   3784 Nov 13 06:02 ../openssl-1.1.0i/crypto/poly1305/poly1305-armv8.o
-rw-r--r-- 1 root root   5712 Nov 13 06:02 ../openssl-1.1.0i/crypto/sha/sha1-armv8.o
-rw-r--r-- 1 root root   5544 Nov 13 06:02 ../openssl-1.1.0i/crypto/sha/sha256-armv8.o
-rw-r--r-- 1 root root   5296 Nov 13 06:02 ../openssl-1.1.0i/crypto/sha/sha512-armv8.o
```
In above, they are build with `Configure linux-aarch64` not `config` in order to omit `-Wa,--noexecstack` option that would be resolved in OpenSSL-1.1.1.

I had an only once test failure of TLS error during several CIi tests. I  could not succeed to reproduce the TLS error after many retries of tests by hand and TLS connection scripts. It seems to have more tests to reproduce it. 

@refack  Could you move the arm64 machine of `test-packetnet-ubuntu1604-arm64-2` out of CI for I'd like to run many CI tests and TLS connection tests for reproduction of TLS errors.

**Comment by refack** [comment]
> @refack Could you move the arm64 machine of `test-packetnet-ubuntu1604-arm64-2` out of CI for I'd like to run many CI tests and TLS connection tests for reproduction of TLS errors.

Done.
https://ci.nodejs.org/computer/test-packetnet-ubuntu1604-arm64-2/

**Comment by shigeki** [comment]
@refack Thanks. I'm going to run parallel tests with SSL debugging in `/var/tmp/shigeki/shigeki_node/node/run_test_ci.sh` for days to see if TLS errors are reproduced.

**Comment by refack** [comment]
Sill working on this?

**Comment by shigeki** [comment]
Yes, I can reproduce the issue but cannot identify its cause. It still need more time for me to investigate it.

**Comment by refack** [comment]
I had an idea, to minimize interaction with CI please stop the Jenkins agent when doing manual testing and restarting it when done.

**Comment by mhdawson** [comment]
@shigeki still working on this now ?

**Comment by shigeki** [comment]
@mhdawson Yes, I currently continue to run tests on the CI arm64 server to see if the issue is really resolved in the current master HEAD.

**Comment by mhdawson** [comment]
k thanks.
