### ISSUE TITLE
Accessing to aix61-ppc64 for investigate missing gas or llvm version detection

### ISSUE THREAD

**Issue by shigeki** [nodejs/build#1569]
This issue was found during working WIP patch upgrading OpenSSL-1.1.1 as referenced in https://github.com/nodejs/node/issues/18770. .
In aix64-ppc64, the detection of asm compiler version has an issue for  https://ci.nodejs.org/job/node-test-commit-aix/18812/nodes=aix61-ppc64/consoleFull as shows.
```
22:53:36 WARNING: Could not recognize `gas`: 
..
22:53:36                  'gas_version': '0',
22:53:36                  'llvm_version': 0,
```
It seems gas or llvm version detection has some issues. 
I'd like to have an access to login the server in order to debug the issue?

**Comment by richardlau** [comment]
This come up during the 1.1.0 update. It looked like AIX was running the native assembler and not gas: https://github.com/nodejs/node/issues/19944#issuecomment-383107363

**Comment by shigeki** [comment]
@richardlau Wow, I forgot the the issue in a half year ago. AIX also has own assembler.  Thanks for reminding me of it.

I need to know if it does not have an option of `--noexecstack` as https://ci.nodejs.org/job/node-test-commit-aix/18797/nodes=aix61-ppc64/console show the error.
If so, I have to add an exception rule of cflag not to add the option in aix.
```
04:34:07 Assembler:
04:34:07 line 1: 1252-168 --noexecstack is not a recognized flag.
04:34:07 line 1: 1252-170 Usage: as [-a{32|64}] -l[ListFile] -s[ListFile] -n Name
04:34:07 			-o ObjectFile [-w|-W] -x[XCrossFile] -u
04:34:07 			-m ModeName [-i] [-p{off|on}] [-E{off|on}] [-v] [InputFile]
04:34:07 gmake[2]: *** [/home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/bio_ssl.o] Error 1
04:34:07 gmake[2]: *** Waiting for unfinished jobs....
```

**Comment by shigeki** [comment]
I've also missed to know that AIX is based on PPC not Intel. 
The support of AVX2 in https://github.com/shigeki/node/commit/7f103fdf4e79d87f32e147b0f42299b4b4d89645 is no longer needed. I would like to check the bare openssl-1.1.1 build binaries on aix if they are the same ones built in Node.

**Comment by refack** [comment]
@nodejs/build @nodejs/platform-aix 
I would like another +1 before proceeding.

**Comment by Trott** [comment]
+1 from me.

**Comment by refack** [comment]
Keys in as root@140.211.9.101

**Comment by gdams** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by shigeki** [comment]
@refack Thanks. I can login the host and confirmed the assembler version token. I'm going to fix gyp scripts tomorrow. 

```
# gcc -Wa,-v -c -o /dev/null -x assembler /dev/null
as V6.1
```

**Comment by shigeki** [comment]
The issue was resolved by https://github.com/shigeki/node/commit/dea84b03003ffd98fb12befd0ea4876b36e81b22.

@refack Please remove my access to 140.211.9.101. I removed `/home/shigeki`. Thanks.

**Comment by refack** [comment]
Done.
Thanks for the ping.
