### ISSUE TITLE
incident: all Azure workers were offline

### ISSUE THREAD

**Issue by refack** [nodejs/build#1572]
It seems like all of our Azure hosts restarted, but did not login (jenkins runs in a logged in session).
I logged into to each of them, and made sure the jenkins client started up.

**Comment by refack** [comment]
Double checked ci-release, all workers there are rackspace, and were up.

**Comment by joaocgreis** [comment]
@refack thanks for taking care of that! This is related to the username change that broke the configured autologin. I am working on a change to make changing secrets easier.

**Comment by refack** [comment]
Concluded.
