### ISSUE TITLE
incident: arm-fanned offline - docker did not update properly on PI1

### ISSUE THREAD

**Issue by refack** [nodejs/build#1573]
Sometime around 11AM UTC 2018-11-13 the RPIs updated.
the docker service did not restart on all PI1 and at least 1 PI2

ping @rvagg

**Comment by refack** [comment]
Might be connected, but half of PIs report no free disk (although half are kind of Ok)

**Comment by rvagg** [comment]
FYI I'm working on this. Must have been triggered by me doing an update across the cluster and Docker being included in that update. I'm removing a ton of state and redeploying so it's taking a while.

**Comment by rvagg** [comment]
Update on this: it looks like Docker 18.09 is completely borked, for ARM/raspbian at least:

* On the Pi1's (armv6l / armhf) it segfaults, doesn't run at all, downgrading to 18.06 fixes it
* On the Pi2's and Pi3's it runs, but takes ages to build anything and then ends up filling up the disk, it seems to duplicate data, so I'm in the process of downgrading them too

The problematic version is docker-ce_18.09.0~3-0~raspbian-stretch_armhf.deb    
The version I'm downgrading to is docker-ce_18.06.1~ce~3-0~raspbian_armhf.deb

For now I'm putting this in `/etc/apt/preferences.d/docker` on all of them:

```
Package: docker-ce
Pin: version 18.06.*
Pin-Priority: 999
```

And re-doing all of the docker setup. The Pi1's are fine and Ansible has done its thing without problem. I'm doing the rest now.

**Comment by rvagg** [comment]
<img width="241" alt="green" src="https://user-images.githubusercontent.com/495647/48668766-c9779f00-eb49-11e8-86dd-5eac6835f76b.png">

Spent way too long making this all happy again but downgrading Docker across the board did the trick nicely.
