### ISSUE TITLE
`citgm-smoker-nobuild` is no longer working

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1577]
While "not building" is a feature of this job I think it has started to take things a little too literally. It is by default not building any platforms and when manually selecting the platforms all of them fail almost immediately due to an error in the build script.

**Comment by richardlau** [comment]
I've been [added to citgm-admins](https://github.com/nodejs/citgm/issues/622) so now am able to configure the citgm jobs. I'll look into fixing `citgm-smoker-nobuild`.

**Comment by richardlau** [comment]
> 
> 
> all of them fail almost immediately due to an error in the build script.

Extract `NODEJS_MAJOR_VERSION` from `NODE_VERSION` and pass to `select-compiler.sh` script: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/jobConfigHistory/showDiffFiles?timestamp1=2018-11-22_13-17-15&timestamp2=2018-11-22_13-54-26

**Comment by richardlau** [comment]
Test build: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/428/
(rhel72-s390x first -- will try the rest of the platforms if it succeeds).

**Comment by refack** [comment]
Waaa ??? What kind of dark magic is this? only 8 / 1326 CitGM tests failed 😨 

![image](https://user-images.githubusercontent.com/96947/48924727-49bf3c80-ee89-11e8-9f5f-ad1a408dd5f6.png)

**Comment by refack** [comment]
> I don't suppose anyone in @nodejs/citgm-admins or @nodejs/build knows why?

I think that was me in https://github.com/nodejs/build/issues/1509, trying to fix the job before we adapted `select-compiler.sh` to accept `NODEJS_MAJOR_VERSION`

**Comment by richardlau** [comment]
> 
> 
> Waaa ??? What kind of dark magic is this? only 8 / 1326 CitGM tests failed 😨
> 

😆 Well it was run on 8 LTS. Also AIX ran out of space (https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/429/MACHINE=aix61-ppc64/console) and https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/429/MACHINE=win2008r2-vs2017/ doesn't seem to have curl (so failed to even download `node`) so neither of those jobs contributed any results.

**Comment by refack** [comment]
I'm gonna fix those two

**Comment by refack** [comment]
So AIX simply had a too small ramdisk. Luckily it's easy to expand.
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/449/MACHINE=aix61-ppc64/

**Comment by richardlau** [comment]
This has been fixed, the remaining issues are covered elsewhere (e.g. https://github.com/nodejs/build/issues/1625 for AIX)

**Comment by sam-github** [comment]
Closing based on last comment, but pls reopen if I misunderstand.
