### ISSUE TITLE
Raspberry PIs need an updated git

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#158]
The Raspberry PIs are failing node-accept-pull-request, because of the same issue we saw before on Ubuntu: https://github.com/nodejs/build/issues/148

According to @joaocgreis, there is already a new version in the repositories, and all we need is to run:
`
apt-get update && apt-get install git
`

@rvagg : could you try that or give me and @joaocgreis access? Thanks!

**Comment by rvagg** [comment]
git is at 1.7.10.4 on all of these machines, there's no update available on top of that, this is Raspbian fwiw

**Comment by rvagg** [comment]
running this while I head off to bed to upgrade git from source: https://github.com/nodejs/build/pull/160

**Comment by rvagg** [comment]
they are all running 2.5.0 now

**Comment by targos** [comment]
there is a new issue:
https://jenkins-iojs.nodesource.com/job/node-test-commit-arm/253/nodes=pi1-raspbian-wheezy/console
http://stackoverflow.com/questions/8329485/git-clone-fatal-unable-to-find-remote-helper-for-https

**Comment by rvagg** [comment]
trying recompiling 2.5.0 with libcurl4-openssl-dev installed now
