### ISSUE TITLE
request for post-mortem: dropping of centos5 in CI

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1580]
Hey All,

We just finished promoting the release of 8.13.0 and were quickly notified that we were missing linux 32 binary tarballs.

Historically these have been built by centos 5. A bug in the matrix configuration stopped centos5 86 from building / testing in public CI and in turn building in our release CI.

After patching this bug we are finding that there is a bug in the libuv upgrade stopping things from building altogether.

The result of this is that we now have a pretty nasty firedrill where we need to figure out if we can even get 8.13.0 building on centos 5... if we can't we are going to need to do a quick 8.13.1 and figure out which version of libuv to revert. This could arguably be considered semver-minor though... so we may need to release an 8.14.0... pretty bad for LTS.

How did this get dropped across all the configs? This kind of silent failure is really bad.

**Comment by refack** [comment]
New insights:
https://ci-release.nodejs.org/computer/release-digitalocean-centos6-x86-1/ machine was down so it did not build and silently failed.
We assumed it should build on centos5 but that's not supported anymore.

@MylesBorins can we close.

**Comment by MylesBorins** [comment]
Yup
