### ISSUE TITLE
job-request: Windows with mingw

### ISSUE THREAD

**Issue by refack** [nodejs/build#1581]
We should have a machine with mingw (32 and or 64 and or MSYS2).
libuv semi-officially supports it, and if we have easy testing we could make node work too.

**Comment by cjihrig** [comment]
> libuv officially supports it

I was under the impression that it was a tier 3 platform (community maintained)? That said, if we could get it into the CI, I certainly wouldn't be opposed 😃

**Comment by refack** [comment]
> libuv officially supports it

Ack, corrected to `semi-officially`.

**Comment by refack** [comment]
Maybe also install https://visualstudio.microsoft.com/vs/features/python/ and figure out how to test building a python module.
