### ISSUE TITLE
Request job editing access for @richardlau

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1582]
I'm volunteering to fix (or at least attempt to fix) [`node-stress-single-test`](https://ci.nodejs.org/job/node-stress-single-test/) to help unblock https://github.com/nodejs/node/issues/24349.

See https://github.com/nodejs/node/issues/24349#issuecomment-440490499 for the changes I think are required.

I also willing to look into https://github.com/nodejs/build/issues/1577.

**Comment by refack** [comment]
For `node-stress-single-test` I'd like a concurring +1 from another @nodejs/build member.
As for CitGM jobs, @richardlau you can ask to be included in https://github.com/orgs/nodejs/teams/citgm-admins and inherit job editing permissions for all CitGM jobs.

**Comment by richardlau** [comment]
> As for CitGM jobs, @richardlau you can ask to be included in https://github.com/orgs/nodejs/teams/citgm-admins and inherit job editing permissions for all CitGM jobs.

https://github.com/nodejs/citgm/issues/622

**Comment by richardlau** [comment]
(And since I was either unaware or simply forgotten it existed, here's a link to the relevant process doc: https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuration_access.md).

**Comment by refack** [comment]
> (And since I was either unaware or simply forgotten it existed, here's a link to the relevant process doc: [/doc/process/jenkins_job_configuration_access.md@`master`](https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuration_access.md)).

WRT to `node-stress-single-test` I'm extrapolation this doc + https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md and IMO two approvals from BuildWG members (mine + 1) are sufficient.

**Comment by mmarchini** [comment]
+1

**Comment by refack** [comment]
Done

**Comment by richardlau** [comment]
> 
> 
> P.S. @richardlau I think you know this, but FTR: Even though we don't have it documented, we're trying to keep the practice of publishing `ci-change`s with a link to the job history diff, and short explanation of motivation, and effect of changes.

@refack Sorry, fell asleep waiting for the `node-stress-single-test` job I kicked off to run, but I've documented the changes (most of which you did 🙇 ) in https://github.com/nodejs/build/issues/1588.
