### ISSUE TITLE
CentOS 7 for Node 12+

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1583]
@nodejs/build @nodejs/release we should start discussion on this and get something into BUILDING.md on `master` in preparation for Node 12.

CentOS 6 is [EOL](https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d) in November 2020, which is fine for Node 10 which is EOL in April. 11 doesn't matter but 12 goes out to April 2021, leaving 5 months without updates to our CentOS 6 infra. It'd be nice not to have to hang on to CentOS 6 as long as we've had to do for CentOS 5.

CentOS 7 is kernel 3.10.0 and libc 2.17 and (I think) we're using devtoolset-6 which has GCC 6.3.1.

/cc @cjihrig anything to consider here re libuv?

**Comment by richardlau** [comment]
> but 12 goes out to April 2021, leaving 5 months without updates to our CentOS 6 infra. 

April 2021 is the maintenance start date for Node.js 12. It's EOL date is [April 2022](https://github.com/nodejs/Release#release-schedule).

**Comment by cjihrig** [comment]
> anything to consider here re libuv?

Nothing that I'm aware of, but also cc @bnoordhuis

**Comment by refack** [comment]
> we're using devtoolset-6 which has GCC 6.3.1.

Can we take this opportunity to move to devtoolset7 (https://github.com/nodejs/build/issues/1543)

**Comment by rvagg** [comment]
> Can we take this opportunity to move to devtoolset7 (#1543)

Yes, I'd like that too and it'd be a good time to do it if we're making such a big leap already.

**Comment by mhdawson** [comment]
@gdams we need to put together plans for the IBM plastforms in this context
