### ISSUE TITLE
Failures on test-rackspace-win2012r2-x64-12 - Windows

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1589]
Looks like the N-API tests fail every time they run on `test-rackspace-win2012r2-x64-12`

https://ci.nodejs.org/job/node-test-node-addon-api/1013/MACHINE=win2012r2/console

```
C:\workspace\node-test-node-addon-api\MACHINE\win2012r2\node-addon-api>if not defined npm_config_node_gyp (node "C:\workspace\node-test-node-addon-api\MACHINE\win2012r2\node-v6.14.4-win-x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild -C test )  else (node "" rebuild -C test ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\workspace\node-test-node-addon-api\MACHINE\win2012r2\node-addon-api\test\build\binding.sln]
```

@joaocgreis could you take a look?

**Comment by refack** [comment]
AFAICT the problem is the job is trying to test with node v6 on a machine that only has VS2017 and that is incompatible.

**Comment by mhdawson** [comment]
The job should only be running on machines with these tags for windows;

```
win10
win2012r2
```
Is there a better tag to use or do we have some logic that you know of that selects out machines with VS2017 when we run on 6.X.  

This has only recently become a problem,

**Comment by refack** [comment]
we have more specific: `win2012r2-vs2015` and `win2012r2-vs2017` labels, so you can filter on that.

**Comment by refack** [comment]
And AFAICT `VersionSelectorScript.groovy` already knows howto filter on these.
https://github.com/nodejs/build/blob/a203aebcf53425b45d972c567181288181d822cc/jenkins/scripts/VersionSelectorScript.groovy#L36-L40

**Comment by mhdawson** [comment]
k thanks, will try the labels as the short term fix and then will need to see if we can use the selection script in that job
