### ISSUE TITLE
Introduce version selection script for N-API testing

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1597]
Link for CI job

https://ci.nodejs.org/job/node-test-node-addon-api/

Need to add back in testing so that it runs on VS2017 and will need version selector script so that it excludes running on V6.x

**Comment by refack** [comment]
@nodejs/n-api-admins PTAL

I've played with a copy of the job - https://ci.nodejs.org/job/refack-node-test-node-addon-api/22/
1. Moved all git cloning to Jenkins
2. Replaced MACHINES filter with matrix param and the version selector script
3. Use NVS to download node

It think I got it to works on all platforms, and the whole script is now just:
```bash
#!bash -xe

ls
export NPM_CONFIG_USERCONFIG=$WORKSPACE/npmrc
export NPM_CONFIG_CACHE=$WORKSPACE/npm-cache

export npm_loglevel=error
export npm_progress=false

# Use NVS for cross platform node install
NODEJS_VERSION="$NODEJS_MAJOR_VERSION"
if [ ${NODEJS_MAJOR_VERSION} -gt "11" ]; then
  NODEJS_VERSION="nightly/$NODEJS_VERSION"
fi

echo "######### solve edge cases for nvs #########"
case $nodes in
  *s390x)
    export LD_LIBRARY_PATH=/data/gcc-4.9/lib64
  ;;
  aix*)
    # we mock uname since the native one with '-m' gives some guid
    echo '#\!bash -xe' > uname
    echo 'if [[ "$1" == "-m" ]]; then echo "ppc64"; else echo "AIX"; fi' >> uname
    chmod 755 uname
    export PATH=$PWD:$PATH
  ;;
  smart*)
    # we mock uname since the native with '-m' one says 'i86pc'
    echo '#\!bash -xe' > uname
    echo 'if [[ "$1" == "-m" ]]; then echo "x64"; else echo "SunOS"; fi' >> uname
    chmod 755 uname
    export PATH=$PWD:$PATH
  ;;
esac

export NVS_USE_XZ=0
export NVS_HOME="$PWD/temp_nvs"
. $NVS_HOME/nvs.sh add $NODEJS_VERSION
nvs use $NODEJS_VERSION

. ./build/jenkins/scripts/select-compiler.sh

cd node-addon-api
ls
node -v
npm -v

echo "################# ready to start ###########"

npm install

if [ ${NODEJS_MAJOR_VERSION} -gt "9" ]; then
  # These can run experimental tests
  npm test
else
  echo 'console.log(process.versions.napi)' >get_napi_version.js
  NAPI_VERSION_REPORTED=`node get_napi_version.js`
  npm test --NAPI_VERSION=$NAPI_VERSION_REPORTED
fi
```

**Comment by refack** [comment]
Got only 2 infra failures
* aix - `tar -z` doesn't work : `tar: Not a recognized flag: z`
* smartOS16
  `ld.so.1: node: fatal: relocation error: file /home/iojs/build/workspace/node-test-node-addon-api/temp_nvs/cache/node: symbol _ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE: referenced symbol not found`

**Comment by richardlau** [comment]
Yes, `-z` is not a valid option for AIX's `tar` command: https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.cmds5/tar.htm
Options are to either get GNU tar or pipe to `gzip`/`gunzip`.

The smartOS16 issue is https://github.com/nodejs/build/issues/1519.

**Comment by refack** [comment]
> get GNU tar

I'd rather we have this so our Jenkins scripts would be simpler.

**Comment by mhdawson** [comment]
Current job runs using the version selector script.  This is done, closing.
