### ISSUE TITLE
Allow the citgm team to edit citgm-continuous-integration-pipeline

### ISSUE THREAD

**Issue by targos** [nodejs/build#1600]
The citgm team has the rights to edit `citgm-smoker-pipeline` but not `citgm-continuous-integration-pipeline`.
I'd like to add Node 11 to the default list of NODE_VERSIONs for the job: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration-pipeline/build?delay=0sec

**Comment by refack** [comment]
Strange... this is the matrix:

![image](https://user-images.githubusercontent.com/96947/48970096-163df880-efd6-11e8-9178-52e78859f7e3.png)

**Comment by refack** [comment]
> The citgm team

Ahh, it's a `@nodejs/citgm` vs `@nodejs/citgm-admins` thing.

**Comment by refack** [comment]
So I changed `citgm-smoker-pipeline`
from:
![image](https://user-images.githubusercontent.com/96947/48971843-6c6a6600-efed-11e8-9f0a-1001afba6efb.png)
To:
![image](https://user-images.githubusercontent.com/96947/48971845-7c824580-efed-11e8-8498-20a94f88485f.png)
