### ISSUE TITLE
Meeting today at 4 EST today

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1605]
The calendar shows the meeting as scheduled for 4 EST today.  I'm not sure why the automatic meeting generation did not generate the issue.

I know its a bit late notice but should we still try to get together?

**Comment by mhdawson** [comment]
No comments in the issue and none in IRC so I don't think its going to happen.

I'm going to move to the week I'm back and if the rest of team wants to get together before then just move it earlier. 

I'll also have to figure out why the tool did not auto generate the issue.

**Comment by rvagg** [comment]
sorry! way too preoccupied with the releases, would have been a big distraction to do this anyway, skipping was appropriate
