### ISSUE TITLE
Build WG management of nodejs-ci-health.mmarchini.me

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#1613]
Mostly so others can help to fix it when it breaks. The code is [open source](https://github.com/mmarchini/nodejs-ci-health-dashboard) and can be run fairly easy, although it's missing instructions on how to install and run. The current server is the smallest droplet in DigitalOcean (1 CPU 1GB?).

I can add a README with instructions + Dockerize it before moving it to a Foundation server.

**Comment by rvagg** [comment]
Instead of a whole server for it, perhaps we can just run it in Docker on the ci server itself. If you get a working Dockerfile for it I can work on some Ansible to get it deployed there.

The only problem being that there's a limited number of people that can get into that server. Is this going to require much maintenance?

Another alternative is the github-bot server, but even the group with access there is fairly limited.

**Comment by mmarchini** [comment]
> Instead of a whole server for it, perhaps we can just run it in Docker on the ci server itself. If you get a working Dockerfile for it I can work on some Ansible to get it deployed there.

Sounds good to me.

> The only problem being that there's a limited number of people that can get into that server. Is this going to require much maintenance?

It doesn't require much maintenance, I only need to restart it once or twice a month because of some weird bug I couldn't track down yet.

**Comment by rvagg** [comment]
👍 let me know when you have a working Dockerfile.

Also you should consider moving it to the nodejs org so we can assign nodejs/build full access to maintain it. If you're willing to do that, open an issue on nodejs/admin as per https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories, you'll also probably need some basic governance files in there too as per the last 3 points @ https://github.com/nodejs/TSC/blob/master/Project-Lifecycle.md#applying-to-join (that section doesn't actually cover sub-projects of existing groups [Build] but I think you're going to get told to include those files anyway).

**Comment by maclover7** [comment]
👍 to moving to Build WG — thank you for maintaining the project so far!

I'm in favor of hosting on the github-bot server, there should still be plenty of resources available on that machine. If we have other random web apps, we can stick them there as well. Happy to help on Ansible-izing as needed :)

**Comment by Trott** [comment]
How do we move this forward? (Related: Current version stopped collecting data on December 24.)

**Comment by Trott** [comment]
/ping @nodejs/build I thought this already happened, but I guess not?

**Comment by mmarchini** [comment]
Honestly, I'd rather not move this to the foundation infra to avoid maintenance burden to the WG. Right now, I'm hosting it on Glitch (which has been zero maintenance so far), and if we move the repository to the foundation (https://github.com/nodejs/admin/issues/288) I think we should keep doing that (unless the foundation has strict rules against hosting things on Glitch).

**Comment by rvagg** [comment]
maybe a *.nodejs.org CNAME would help with visibility? I keep on forgetting about this tbh. ci-health.nodejs.org would be easy to remember.

**Comment by mmarchini** [comment]
Oh, I forgot to add a CNAME on my domain... so folks might think it's been out for a few weeks. Just updated, but might take time to propagate. The Glitch url is https://nodejs-ci-health.glitch.me/ though, if we decide to add a CNAME it should point there (instead of the `*.mmarchini.me` domain) I think.

**Comment by rvagg** [comment]
@mmarchini does glitch allow you to add additional alt names to your site? I added it as a CNAME https://ci-health.nodejs.org/ but glitch wants to look up the project by that name, which doesn't exist.

**Comment by mmarchini** [comment]
> @mmarchini does glitch allow you to add additional alt names to your site? I added it as a CNAME https://ci-health.nodejs.org/ but glitch wants to look up the project by that name, which doesn't exist.

I'm trying to unlock custom domains for my account. Might take a few hours/maybe a day.

In the meantime: should this be moved to a Foundation Glitch account?

**Comment by rvagg** [comment]
Well that brings us back to the original question! I don't have an opinion on this, I only just learnt today about Glitch. If you're wanting to offload or share maintenance burden then maybe giving multiple people access would be a good thing.

**Comment by sam-github** [comment]
When I looked last night to see what it was, https://ci-health.nodejs.org/  just had zeros for all categories, expected?

And now, it has a cert error, and when I click through, the app is missing. Ephemeral error while DNS propogates?

**Comment by mmarchini** [comment]
@sam-github yes, expected. I'm still trying to get custom domains enabled on my account.

**Comment by mmarchini** [comment]
@rvagg can you update the CNAME to point to 3wvk6zpmle2ze9jo.preview.edgeapp.net?

(for context: https://glitch.com/help/custom-domain/)

**Comment by rvagg** [comment]
done, and working http://ci-health.nodejs.org/, sweet

**Comment by mmarchini** [comment]
Great! I believe we can close this then
