### ISSUE TITLE
Trim Ubuntu 12.04 resources & usage

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1616]
We have 3 Ubuntu 12.04 machines in CI, I'd like to trim that to 2. That'll make it easier to justify expansion for real 18.04 VMs (instead of Docker containers).

Currently they are only being used to test Node 6 and 8, so they get used rarely for node-test-commit-linux. They are also in these builds and I'd like to remove it from all of them:

* citgm-abi-smoker
* citgm-abi-smoker-forward-compat
* citgm-smoker
* citgm-smoker-nobuild
* citgm-smoker-private
* citgm-smoker-private-too
* citgm-smoker-rebuild
* citgm-smoker-yarn
* libuv-test-commit-linux
* node-inspect-continuous-integration
* nodereport-continuous-integration
* node-stress-single-test
* node-test-commit-linux-napit
* node-test-commit-linux-napit
* node-test-commit-unified
* node-test-known-issues
* node-test-known-issues
* node-test-napi-modules-citgm
* node-test-napi-modules-citgm
* node-test-napi-modules-citgm-v8.x
* node-test-napi-modules-citgm-v8.x
* node-test-node-addon-api
* node-test-npm
* refack-node-test-node-addon-api
* refack-test-commit-linux

Taking a guess at who might object based on this list: @nodejs/citgm @nodejs/n-api  @cjihrig (libuv) @Trott 

If I don't get any objections in the next day or so I'm going to start pulling it out.

**Comment by Trott** [comment]
No objection from me. I'm almost always testing on master, and FWIW my bottleneck tends to be Raspberry Pi 1 devices.

**Comment by cjihrig** [comment]
No objections from me.

**Comment by mhdawson** [comment]
+1
