### ISSUE TITLE
load_secrets.py slow and leaving cruft

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1621]
I feel like pulling load_secrets.py out, it only seems to get in the way. I'm hoping the python folks here can address this. Here's my problems:

1. it's slow, doing a playbooks/write-ssh-config.yml is where it shows the most, it should be a quick operation but it has to go through decrypting and each decrypt is takes a second or so and this compounds. We don't even need secrets for that. I can't see a way to propagate "I DON'T NEED SECRETS" down into the plugin and I bet that it's not even possible.
2. It leaves cruft, and doesn't seem to do any "caching" even though it's apparently supposed to.

<img width="469" alt="screenshot 2018-12-02 13 02 08" src="https://user-images.githubusercontent.com/495647/49334803-d65cbe00-f632-11e8-96ff-30e0768ffcfe.png">

What even is this? Why can't it just create a new host_vars file for hosts that are missing there? Why does it make a new file every time and not reuse it?

All this plugin does is make me want to go and manually insert host_vars file for each of the missing hosts because it gets in the way all the time.

Give me some good reasons not to pull it out.

**Comment by rvagg** [comment]
Let me put that last statement another way: how is this not frustrating for other regular ansible/ users? Are you just accepting that this thing has to sit in the middle and working around it? Is it providing genuine benefits to your work here that outweigh its costs?

**Comment by joaocgreis** [comment]
Having the secrets managed automatically is a big advantage, mainly for Windows hosts (though the new format helps spotting inconsistencies for all platforms).

I hope this is an improvement: https://github.com/nodejs/build/pull/1624

**Comment by joaocgreis** [comment]
I believe https://github.com/nodejs/build/pull/1624 fixed this, or at least made it acceptable. Let me know if there are still issues.
