### ISSUE TITLE
addon build failures on Windows machines

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#1622]
Refs: https://github.com/nodejs/reliability/issues/19

| Reason | <code>Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 7 (https://github.com/nodejs/node/pull/24796/, https://github.com/nodejs/node/pull/24803/, https://github.com/nodejs/node/pull/24737/, https://github.com/nodejs/node/pull/24727/, https://github.com/nodejs/node/pull/24814/, https://github.com/nodejs/node/pull/20640/, https://github.com/nodejs/node/pull/24733/) |
| Appeared | [test-azure_msft-win10-x64-5](https://ci.nodejs.org/computer/test-azure_msft-win10-x64-5/), [test-rackspace-win2012r2-x64-12](https://ci.nodejs.org/computer/test-rackspace-win2012r2-x64-12/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/19147/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/19190/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows/COMPILED_BY=vcbt2015,RUNNER=win10,RUN_SUBSET=0/22176/console">Example</a></summary>

```
Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\workspace\node-test-binary-windows\deps\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.10240
```
</details>

-------

| Reason | <code>Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 3762504530</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 7 (https://github.com/nodejs/node/pull/24775/, https://github.com/nodejs/node/pull/24796/, https://github.com/nodejs/node/pull/24803/, https://github.com/nodejs/node/pull/20640/, https://github.com/nodejs/node/pull/23423/, https://github.com/nodejs/node/pull/24733/, https://github.com/nodejs/ecmascript-modules/pull/18/) |
| Appeared | [test-azure_msft-win2016-x64-6](https://ci.nodejs.org/computer/test-azure_msft-win2016-x64-6/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/19124/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/19211/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows/COMPILED_BY=vs2015,RUNNER=win2016,RUN_SUBSET=1/22176/console">Example</a></summary>

```
Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 3762504530
gyp ERR! stack     at ChildProcess.onExit (c:\workspace\node-test-binary-windows\deps\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.14393
```
</details>

The real cause seem to be either

(https://ci.nodejs.org/job/node-test-binary-windows/COMPILED_BY=vcbt2015,RUNNER=win10,RUN_SUBSET=0/22176/console)
```
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
18:29:20 gyp ERR! build error 
```

Or (https://ci.nodejs.org/job/node-test-binary-windows/COMPILED_BY=vs2015,RUNNER=win2016,RUN_SUBSET=1/22176/console)

```
Microsoft.Build.BuildEngine.InvalidToolsetDefinitionException: MSBuildToolsPath is not specified for the ToolsVersion "14.0" defined at "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0", or the value specified evaluates to the empty string.
```

**Comment by joaocgreis** [comment]
This happens only when testing v6, because the tests run on machines with VS2017 installed and it is not supported by Node v6.

This was a recent regression with agent labels and VS versions. I've fixed it for now by leaving the affected machines out of `node-test-binary-windows`, but we'll have to find a better (and less confusing) way of labeling the machines and distributing the jobs.

@joyeecheung the only PRs where I see afected by this are https://github.com/nodejs/node/pull/24796 and https://github.com/nodejs/node/pull/24803 (the only two testing v6). Unless I missed something, all others have PR related failures or unmarked flaky tests. I think these reports are automatically generated, so there might be something wrong with the tool. And thanks for reporting this!

**Comment by joyeecheung** [comment]
> Unless I missed something, all others have PR related failures or unmarked flaky tests. I think these reports are automatically generated, so there might be something wrong with the tool. 

Yes, looks like the tool is still trying to query the skipped builds for failures (e.g. for https://ci.nodejs.org/job/node-test-binary-windows/22162/ the tool does not understand that `win10-vcbt2015-1` is a skipped build and the subbuild does not actually belong to that job). I'll tweak the tool later and see if the Jenkins API has anything useful for the tool to understand that
