### ISSUE TITLE
aix consistently failing / stalling with CITGM

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1625]
e.g. https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/459/MACHINE=aix61-ppc64/

**Comment by mhdawson** [comment]
@gdams one more thing to add to your list of AIX infra things to work on.

**Comment by sam-github** [comment]
I'm not sure if this is still relevant, but I kicked off a build: https://ci.nodejs.org/job/citgm-smoker-nobuild/640/
