### ISSUE TITLE
Provide temporary access to gireeshpunathil to freebsd CI machines

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/build#1628]
I would like to access to one of the freebasd systems to debug the failures in a PR (https://github.com/nodejs/node/pull/22712).

CI failure:
https://ci.nodejs.org/job/node-test-commit-freebsd/22658/nodes=freebsd11-x64/testReport/junit/(root)/test/node_report_test_api/

I don't have a dev box locally to do this, and hence this request.

I am sure this has to do with platform specific code blocks - there are special considerations w.r.t windows, linux, aix and mac, somewhere I need to align the freebsd flow. I estimate it to be a 2 days worth effort.

I meet criteria for special access (reference: https://github.com/nodejs/build/issues/1545) ; please let me know if I need to state anything. I shall abide by the rules set while working in CI systems.

thanks in advance!

**Comment by sam-github** [comment]
@nodejs/build @nodejs/platform-freebsd  please! :-)

**Comment by Trott** [comment]
👍 SGTM

**Comment by rvagg** [comment]
Added you @gireeshpunathil, use this:

```
Host test-digitalocean-freebsd11-x64-1
  HostName 45.55.90.237
  IdentityFile <wherever your github ssh key is>
  User freebsd
```

When you're done and cleaned up, you could remove yourself from authorized_keys and close this, or ping me and I'll sort it out.

**Comment by gireeshpunathil** [comment]
@rvagg - thanks! however, I am unable to access this system, doing `ssh root@45.55.90.237` or `ssh iojs@45.55.90.237` is asking for the password for the user, not going the ssh route.

At the same time, I am working on a number of CI failures right now, and this one takes a back seat. Also given https://github.com/nodejs/build/pull/1641 in on track, I am just wondering is it enough to wait till / if that lands?

**Comment by gireeshpunathil** [comment]
ah! please ignore the previous comment, with user `freebsd` I am in. did not read your instructions enough. thanks!

**Comment by gireeshpunathil** [comment]
this is resolved long back, closing. thanks!
