### ISSUE TITLE
citgm-smoker-nobuild should not run on ppcbe for node >=8

### ISSUE THREAD

**Issue by targos** [nodejs/build#1632]
See https://ci.nodejs.org/job/citgm-smoker-nobuild/460/
It looks like the version selector script is not applied correctly.

/cc @nodejs/citgm-admins

**Comment by richardlau** [comment]
> 
> 
> See https://ci.nodejs.org/job/citgm-smoker-nobuild/460/
> It looks like the version selector script is not applied correctly.
> 
> /cc @nodejs/citgm-admins

On it. Looks like a mismatch between the configuration matrix axis name (`MACHINE`) and what the version selector script is expecting `nodes`): https://github.com/nodejs/build/blob/bcc589f90e2ff722508e78e28f0b3e7c64d1af73/jenkins/scripts/VersionSelectorScript.groovy#L97-L100

**Comment by richardlau** [comment]
Rename `MACHINE` to `nodes`: https://ci.nodejs.org/job/citgm-smoker-nobuild/jobConfigHistory/showDiffFiles?timestamp1=2018-11-29_23-18-45&timestamp2=2018-12-11_12-56-38

I see jobs are already queued up, so I'll try to keep an eye on when the next one kicks off.

**Comment by richardlau** [comment]
Looks to be working:
https://ci.nodejs.org/job/citgm-smoker-nobuild/466/console
```
13:02:31 Node.js major version: 10
13:02:31 Node.js version: v10
13:02:31 Skipping ubuntu1204-64 for Node.js 10
13:02:31 Skipping ppcbe-ubuntu1404 for Node.js 10
13:02:31 Running nodes
```

**Comment by targos** [comment]
Thank you for fixing it!
