### ISSUE TITLE
Need access to AIX again

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#1633]
I once more need access to AIX to address the failure of addons/at-exit/test in https://ci.nodejs.org/job/node-test-commit-aix/19609/nodes=aix61-ppc64/console.

**Comment by rvagg** [comment]
I'm going to leave this to one of the IBM folks, AIX is too frustrating and strange for me. Fine by me though.

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
@gdams can you take care of getting @gabrielschulhof access.

**Comment by gabrielschulhof** [comment]
@gdams Sent and thanks!

**Comment by gdams** [comment]
done, please login using `ssh root@140.211.9.101`

**Comment by sam-github** [comment]
@gdams can this be closed now?

**Comment by refack** [comment]
Key removed.
