### ISSUE TITLE
Provide temporary access to gireeshpunathil to AIX CI machines

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/build#1637]
I would like to access to one of the AIX systems to debug the failures in https://github.com/nodejs/node/issues/24921 . I tried all what I could to recreate in my local dev systems but looks like the failure has to do with peculiar execution environment in the CI.

CI failure:
https://ci.nodejs.org/job/node-test-commit-aix/19533/nodes=aix61-ppc64/console

I meet criteria for special access (reference: #1545) ; please let me know if I need to state anything. I shall abide by the rules set while working in CI systems.

thanks in advance!

**Comment by Trott** [comment]
:+1:

**Comment by gireeshpunathil** [comment]
one more issue to investigate: https://github.com/nodejs/node/issues/25029

**Comment by sam-github** [comment]
@gireeshpunathil is a member of @nodejs/platform-aix, I wonder if he can be given permanent access to the AIX build machines?

It seems to be possible according to process docs https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md

Alternatively, @gireeshpunathil, maybe if you formally joined @nodejs/build you would not have to wait for access?

**Comment by Trott** [comment]
@gabrielschulhof Are you still using your access to test-osuosl-aix61-ppc64_be-1? If not, I'll swap out your key for @gireeshpunathil's. If so, I'll put @gireeshpunathil on a different machine so one of you isn't recompiling things while the other one is trying to test...

**Comment by Trott** [comment]
@nodejs/build Can we get a second approval here?

**Comment by Trott** [comment]
> @nodejs/build Can we get a second approval here?

Actually, never mind.

@gireeshpunathil Your key is present in test-osuosl-aix61-ppc64_be-2. You should be able to log in there.  Details in https://github.com/nodejs/build/issues/1545.

**Comment by mhdawson** [comment]
+1 to getting Gireesh permanent access.

**Comment by gdams** [comment]
+1 to permanent access

**Comment by sam-github** [comment]
@gireeshpunathil I think you are on the build WG now, so this can be closed?

**Comment by gireeshpunathil** [comment]
closing; purpose resolved - for this instance and beyond!
