### ISSUE TITLE
Took test-packetnet-centos7-arm64-2 offline

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1640]
test-packetnet-centos7-arm64-2 was failing over an over on two js-native-api tests. test-packetnet-centos7-arm64-1 has been fine. I took test-packetnet-centos7-arm64-2 offline. Can someone knowledgable take a look and hopefully get it back in the rotation?

**Comment by rvagg** [comment]
updating 447 outdated packages .. will clean up workspace and restart it, re-enable it and see if that makes a difference.

**Comment by rvagg** [comment]
https://ci.nodejs.org/job/node-test-commit-arm/20917/nodes=centos7-arm64-gcc6/

crossing fingers this is sorted properly now we have a green

I also cleared out .ccache too, there's a possibility that there was a mixed up object file cached
