### ISSUE TITLE
node-test-commit-aix-shared-lib is broken

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1647]
https://ci.nodejs.org/job/node-test-commit-aix-shared-lib/ is currently broken (at least for all the build history currently kept (last 12 builds)):

![image](https://user-images.githubusercontent.com/5445507/50231441-b9e8b180-03a6-11e9-8b51-040e144ffc93.png)

e.g. https://ci.nodejs.org/job/node-test-commit-aix-shared-lib/220/nodes=aix61-ppc64/consoleFull
```
In file included from ../src/memory_tracker.h:12:0,
                 from ../src/memory_tracker-inl.h:6,
                 from ../src/base_object.h:28,
                 from ../src/async_wrap.h:27,
                 from ../src/async_wrap-inl.h:27,
                 from ../src/callback_scope.cc:2:
../src/aliased_buffer.h: At global scope:
../src/aliased_buffer.h:27:22: error: expected type-specifier
           typename = std::enable_if_t<std::is_scalar<NativeT>::value>>
```

The problem looks to be because the `select-compiler.sh` script isn't being run in bash (the `0403-004` error below suggests `ksh`) so fails to set the correct compiler:
```
+ . ./build/jenkins/scripts/select-compiler.sh
+ [  != DONT ]
+ SELECT_ARCH=AIXPPC
+ [ -z ]
/tmp/jenkins800052755859487384.sh[35]: test: 0403-004 Specify a parameter with this command.
+ [ AIXPPC = PPC64LE ]
+ [ AIXPPC = S390X ]
+ [ AIXPPC = AIXPPC ]
+ echo Setting compiler for Node version  on AIX
Setting compiler for Node version  on AIX
+ [  -gt 9 ]
+ which gcc
+ which g++
+ which g++
+ export CC=ccache /opt/freeware/bin/ccache/gcc CXX=ccache /opt/freeware/bin/ccache/g++ CXX_host=ccache /opt/freeware/bin/ccache/g++
+ echo Compiler set to default at 4.8.5
Compiler set to default at 4.8.5
+ gmake run-ci -j 5
```

I think this will be fixed by adding `#!/bin/env bash` at the start of the `Execute shell` step that calls `select-compiler.sh` (I don't have permissions to edit this job).

**Comment by richardlau** [comment]
Is this job related to https://github.com/nodejs/build/issues/1098? cc @mhdawson 

It only appears to be triggered on a timer, is not part of the normal CI and nobody else seems to have noticed that it's not working (I only noticed because it happened to be running this morning when I kicked off a different job that was waiting for an AIX executor).

**Comment by mhdawson** [comment]
@rubys is helping with the current shared library work so mentioning him for awareness.

We are only part of the way in adding test jobs for shared library support and they were not ready to be run as part of every regression run, hence running once per day.

I've updated the job to add `#!/bin/env bash` to the start.

**Comment by mhdawson** [comment]
Job now runs but all add-on tests seem to fail  @rubys could you take a look @gireeshpunathil can helpif AIX specific knowledge is required.

**Comment by mhdawson** [comment]
@yhwang you mentioned you might have some cycles, is this something you could look at?
