### ISSUE TITLE
MSBuild error MSB6006: "cmd.exe" exited with code 1

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/build#1655]
I have this error when trying to build `rename_node_bin_win.vcxproj`:
```
node.vcxproj -> C:\node-v11.6.0\Release\\node-win.exe
  rename_node_bin_win
  'mv' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,
5): error MSB6006: "cmd.exe" exited with code 1. [C:\node-v11.6.0\rename_node_bin_win.vcxproj]
```
The command for moving files and folders in Windows is `move`, people.  Not `mv`.  That might be the reason for that MSBuild error too.  

So how do I fix this error?  Anyone have any idea?

**Comment by bzoz** [comment]
Fixed in https://github.com/nodejs/node/pull/25166

**Comment by DragonOsman** [comment]
I wanted to build the latest **stable** release.  What version is that?

**Comment by bzoz** [comment]
It just landed, it will take some time to get released. You can always apply the patch yourself, it is very simple: https://github.com/nodejs/node/pull/25166/files

**Comment by DragonOsman** [comment]
I cloned the repository and built it, but ended up with the pre-release version (version 12.0.0).  I think I'll downgrade to the latest stable release and apply that patch then.

Anyway, there's this warning that comes up that I think you guys need to fix:
```
c:\node\deps\gtest\include\gtest\gtest-printers.h(778): warning C4996: 'std::tr1': warning STL4002: The non-Standard st
d::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRE
CATION_WARNING to acknowledge that you have received this warning. (compiling source file src\gtest.cc) [C:\node\deps\g
test\gtest.vcxproj]
```
`std::tr1` stuff is deprecated and will be removed in a later standard update.  I suggest you find alternatives for it.  I also have warnings about the Windows-defined macros MIN and MAX, so I want to ask: how can I add preprocessor definitions to the command line when using `vcbuld.bat`?  I want to add the that removes the defines for MIN and MAX.

**Comment by bzoz** [comment]
You should direct those questions to https://github.com/nodejs/help

**Comment by DragonOsman** [comment]
One more thing.  I have the WiX extension for Visual Studio already installed, but whenever I try to do a build of Node.js that requires it, I'm always told that I don't have it.  I do use the Developer Command Prompt for VS 2017 to do it in, by the way.

**Comment by DragonOsman** [comment]
I provided "msi" when building Node.js, but although it was all built, there's no MSI installer.  When I did it before, it built the installer as well.  Why didn't it this time?

**Comment by refack** [comment]
FTR: Git 4 Windows and the MSYS2 toolchain are currently [prerequisites for building node](https://github.com/nodejs/node/blob/master/BUILDING.md#windows-1).

@DragonOsman for further usage assistance please open as issue in https://github.com/nodejs/help

I'm closing this as non-actionable for this repo.
