### ISSUE TITLE
Tarball created on Mac throws errors when extracted on Linux

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1658]
Cross post from https://github.com/nodejs/node/issues/22805

I cc'd build without response

TL;DR we no longer have gnutar being used on OSX and it is causing errors. Fastest solution likely running `brew install gnu-tar --with-default-names` and using gnu-tar on our OSX systems

Anyone have time to look in to this?

**Comment by mhdawson** [comment]
@gdams might be able to look at this, but he needs to get the additional AIX machine added first.  We don't believe anything was changed other than moving to a new install.

If we start manually installing things it will just make it worse longer term.  First we need to agree we should move to gnu-tar, then update the Ansibile scripts to install gnu-tar (can't remember if they have brew or not).

**Comment by mhdawson** [comment]
More info, default tar version on old release machine:
```sh
release-requireio-osx1010-x64-1:~ iojs$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
release-requireio-osx1010-x64-1:~ iojs$
```
and on new release machine (OSX 10.11):

```sh
bsdtar 2.8.3 - libarchive 2.8.3
```

So looks like nothing changed from the version of tar being used.

Looking at the ansible files, at least brew is installed, but it is not immediately obvious how you would add installation of packaged with an option "--with-default-names"  so it likely needs to wait until @gdams has time to look at it or somebody else can create a PR/test the needed updates to the Ansible files.

**Comment by mscdex** [comment]
any update?

**Comment by MylesBorins** [comment]
Ping ping ping ping ping

https://github.com/nodejs/node/issues/22805

This is coming up again. Could we please change the tar version on these machines

**Comment by rvagg** [comment]
Calling this solved. As per, #1777, nightlies as of today use centos7 to generate all non-binary assets. This will apply to Node 12+. Older versions will stick with the current path.
