### ISSUE TITLE
State of the Build August 2015: ARM

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#166]
FYI https://medium.com/@rvagg/node-js-io-js-state-of-the-build-arm-2f24c18e1ab4

> My last [State of the Build](https://github.com/nodejs/build/issues/77) was in April and I wanted to get another one out but instead of doing the whole thing, which would be more effort and time than I can afford at the moment, I’m going to just bite off the ARM bits.

I started working on it here but as it got larger it felt more like a blog post so I took it to medium!

**Comment by jbergstroem** [comment]
Great post, thanks for the update.
