### ISSUE TITLE
RFC: merge the daily aix-shared-lib run with daily-master

### ISSUE THREAD

**Issue by refack** [nodejs/build#1664]
AFAICT https://ci.nodejs.org/job/node-test-commit-aix-shared-lib is equivalant to running https://ci.nodejs.org/job/node-test-commit-aix/ with `CONFIG_FLAGS=--shared`, thus it could be folded into https://ci.nodejs.org/job/node-daily-master/

/CC @nodejs/platform-aix

**Comment by mhdawson** [comment]
Today that is the case, longer term I have in mind that there will be additional shared library specific tests but I guess at that point we could pull it back out into its own job.
