### ISSUE TITLE
Request for temporary access to rhel72-s390x

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1666]
I would like to troubleshoot https://ci.nodejs.org/job/node-test-commit-v8-linux/2041/nodes=rhel72-s390x,v8test=v8test/

See https://github.com/nodejs/node/pull/24875#issuecomment-456592021

I've had temporary access to CI before: https://github.com/nodejs/build/issues/1662

**Comment by mhdawson** [comment]
+1 from me.

**Comment by refack** [comment]
+1

Added your keys to test-linuxonecc-rhel72-s390x-1 a.k.a. root@148.100.110.63

**Comment by mhdawson** [comment]
@refack thanks :)

**Comment by refack** [comment]
I had an idea, to minimize interaction with CI please stop the Jenkins agent when doing manual testing and restarting it when done.

**Comment by gireeshpunathil** [comment]
@refack - can you please provide the exact steps for this? I may want to make use of this too (zero disturbance to CI).
 - I assume this can be done via command line
 - I assume this can be done on all platforms
 - What if a CI is in progress / in pipeline ? stopping it will have adverse effects?

**Comment by mhdawson** [comment]
start /stopping is a different command on each machine.  I think we also want to make sure its only stopped while work is actively taking place that might interfere.

@gireeshpunathil  I can't remember which variant it is  for rhel off the top of my head but I think it might be 'service jenkins stop' and 'service jenkins start'

**Comment by mhdawson** [comment]
If there is a CI it would cause that job to fail.

I normally would disable the machine in the Jenkins UI but I think that requires at least test level build access. (@gireeshpunathil that might be possible for you though now as you have been onboarded as a build WG member).

**Comment by sam-github** [comment]
I have permanent access now.
