### ISSUE TITLE
Ubuntu support plan 2019-2020

### ISSUE THREAD

**Issue by refack** [nodejs/build#1668]
Ubuntu Trusty (14.04) goes EOL on April 2019

![image](https://user-images.githubusercontent.com/96947/51700274-b3201080-1fdc-11e9-911f-dadbbd80d345.png)
https://www.ubuntu.com/about/release-cycle

1. Should we keep the x64 workers, or retire them in favor of more Bionic workers?

2. From a quick audit is seems like for Linux/PPC we only have workers with Trusty (14.04), so I guess those need either an upgrade or addition of new ones.
   https://ci.nodejs.org/job/node-test-commit-plinux/
   @mhdawson what is IBM's support plan? Can we skip Xenial ahead directly to Bionic (18.04)?

P.S. what should be the plan for ARM64 https://ci.nodejs.org/job/node-test-commit-arm/ (@rvagg) ?

**Comment by refack** [comment]
Follow up to https://github.com/nodejs/build/issues/967 (non-LTS version):
Can we formally decide to only support latest non-LTS (i.e. replace 18.10 with 19.04 and so on?)

**Comment by mhdawson** [comment]
@refack we can't necessarily get rid of the older version as we'll likely need it to support older versions.  I think @rvagg also mentioned that there is quite likely going to be extended support for 14.04.

@gdams has been working on capturing our plan for what levels to move up to.  @gdams can you share that here.
