### ISSUE TITLE
Expanding tests run in coverage job

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1676]
I changed the configuration for https://ci.nodejs.org/view/All/job/node-test-commit-linux-coverage-daily/ to also run pummel and benchmark jobs.

Under "Execute Shell", I changed the last line from this:

```sh
NODE_TEST_DIR=${HOME}/node-tmp PYTHON=python COVTESTS="test-ci test-internet" make coverage -j $(getconf _NPROCESSORS_ONLN)
```

...to this:

```sh
NODE_TEST_DIR=${HOME}/node-tmp PYTHON=python COVTESTS="test-ci test-internet test-pummel test-benchmark" make coverage -j $(getconf _NPROCESSORS_ONLN)
```

Once https://github.com/nodejs/node/pull/25799 lands, we can replace the list of suites with `test-all-suites` and all tests under the `test` directory will run no matter where they are.

**Comment by Trott** [comment]
Guess I'll leave this open until we can change it to `test-all-suites`.

**Comment by Trott** [comment]
Hmmm...my change somehow added code in the `benchmark` directory to the measurements, which is definitely not what I wanted to do. Any idea how to exclude it or why it got included? @bcoe

**Comment by Trott** [comment]
Oh, I see, I need to add it as an `--exclude` in the call to `c8` in the Makefile.

**Comment by Trott** [comment]
(In the meantime, I'll remove the benchmark tests from the coverage job.)

**Comment by mhdawson** [comment]
@Trott, how much run time does adding those 2 make?

Working on https://github.com/nodejs/build/issues/1669 and just want to understand how that will affect the run time there as well.  We will also have to sync that job.

**Comment by Trott** [comment]
> @Trott, how much run time does adding those 2 make?
> 
> Working on #1669 and just want to understand how that will affect the run time there as well. We will also have to sync that job.

The whole job, start-to-finish, takes around 20 minutes give-or-take 5 minutes. My run took 19 minutes and the previous run (without these additions) was 21 minutes, so whatever additional time there is, it is negligible. On the other hand, that is odd because I believe two pummel tests timed out, so I would expect that to add 4 minutes right there. (Maybe there's some Jenkins magic there? Does this job blindly run things in parallel even though they're not parallel-safe somehow?)

**Comment by mhdawson** [comment]
@Trott key thanks, if its not significantly longer that's good.

I doubt there is "magic".

**Comment by refack** [comment]
> Looks like the different types are running in parallel which seems wrong

The change in https://github.com/nodejs/node/pull/25799 will fix that. Parallelizm will only be done by `test.py` not by `make`.
(We should make sure all `make test*` run with `-j` anyway)

**Comment by mhdawson** [comment]
I don't see how 25799 is going to fix that for the coverage jobs.  @refack is it a know problem that the suites are running in parallel?

**Comment by Trott** [comment]
@mhdawson I'd guess it will fix it because the coverage job will run only one make target (`test-all-suites`) whereas currently, make runs multiple targets (`test-pummel` and `test-internet` and so on) and ends up running multiple `test.py` instances.

**Comment by Trott** [comment]
By the way, the only thing keeping https://github.com/nodejs/node/pull/25799 from landing at this point is that it needs one more approval. @refack? @mhdawson?

**Comment by mhdawson** [comment]
Hmm, making we think a bit more about the coverage sanity job.  We want it to run as part of the regular PR validation so that tests don't get introduced that will cause the main coverage job to fail.  But if we've chosen not to run tests already it should probably not run them either, unless running a single instance (ubuntu) is ok for every PR run.

**Comment by mhdawson** [comment]
The goal is to avoid things going in that then later require cleanup by people watching the main coverage job.

**Comment by refack** [comment]
> is it a known problem that the suites are running in parallel?

Yes. It's https://github.com/nodejs/node/issues/22006 and https://github.com/nodejs/node/issues/24966

**Comment by mhdawson** [comment]
This patch is currently being applied in respect to 24966 but I guess it does not complete address the issue? https://github.com/nodejs/build/pull/1671

**Comment by refack** [comment]
> unless running a single instance (ubuntu) is ok for every PR run.

If we get to a point where the coverage jobs works with all tests passing, we could fail it on a test fail (i.e. https://github.com/nodejs/node/pull/25432) and that way we get daily sanity (even trigger it as part of the general daily master sanity)
IMO that should give us enough protection. Especially now that we don't instrument the JS code and the coverage run is much much much more robust.


> This patch is currently being applied in respect to 24966 but I guess it does not completely address the issue? #1671

It solves the one one aspect of a race while building. It does not solve the fragility of parallel `test.py` runs.

**Comment by Trott** [comment]
OK, switched the node-test-commit-linux-coverage-daily job up to use test-all-suites and running it with the publish-to-coverage.nodejs.org box unchecked: https://ci.nodejs.org/view/All/job/node-test-commit-linux-coverage-daily/24/

**Comment by Trott** [comment]
Well, that helped a little but not much. Putting the job back to this until we can figure out why it doesn't work with `test-all-suites`:

```
NODE_TEST_DIR=${HOME}/node-tmp PYTHON=python COVTESTS="test-ci test-internet test-pummel test-benchmark" make coverage -j $(getconf _NPROCESSORS_ONLN)
```

And kicking off a job to restore coverage stats: https://ci.nodejs.org/view/All/job/node-test-commit-linux-coverage-daily/27/

**Comment by Trott** [comment]
OK, so even though I was running `test-all-suites`, this showed up, I guess due to one of the prerequisites, and a test failure there ended the whole thing before it got to `test-all-suites`:

```console
make[2]: Leaving directory `/home/iojs/build/workspace/node-test-commit-linux-coverage-daily/nodes/benchmark/test/node-api/test_uv_loop/build'
/usr/bin/python2.7 tools/test.py -j 8 --mode=release js-native-api
```

**Comment by Trott** [comment]
The problem would seem to be that `test-all-suites` has `test-js-native-api` as a pre-requisite. We really just need `test-build` I think. Testing that locally with a `make clean && make test-all-suites`. If it works out, I'll open a PR, run a modified coverage job against it as part of the test, and hopefully that will finally get this done.

**Comment by Trott** [comment]
https://github.com/nodejs/node/pull/25892

**Comment by Trott** [comment]
Changed it back to `test-all-suites` and running a job against nodejs/node#25892 rather than master and with the publish checkbox unchecked: https://ci.nodejs.org/view/All/job/node-test-commit-linux-coverage-daily/28/

Will now change things back to `test-ci test-internet test-pummel test-benchmark`.

**Comment by Trott** [comment]
Coverage stats with that PR look reasonable:

```console
06:30:40 Javascript coverage %: 95.47%
06:30:40 C++ coverage %: 90.3%
```

**Comment by Trott** [comment]
(And it took 20 minutes to run, so that seems reasonable too.)

**Comment by Trott** [comment]
@refack reported that a Jenkins workspace needed attention but that things should be fine now. So, trying again: https://ci.nodejs.org/view/All/job/node-test-commit-linux-coverage-daily/31/

**Comment by Trott** [comment]
That run looks good. Optimistically closing this.

**Comment by mhdawson** [comment]
The coverage test job where we are trying to only fail if something other than test failing seems to be having problems with the updates.

In particular, this seems to be timing out after 5 mins:  test-dnsBuild timed out.  See https://ci.nodejs.org/job/node-test-commit-coverage/nodes=ubuntu1604_sharedlibs_x64/59/console

**Comment by mhdawson** [comment]
Not sure we don't see the same failure in the main coverage run.  IN any case I guess we'll investigate that separately.
