### ISSUE TITLE
Provision Jenkins Slave for Docker Testing

### ISSUE THREAD

**Issue by retrohacker** [nodejs/build#168]
From meeting notes on 2015-08-25
https://docs.google.com/document/d/1GYPt7igqna-lL1_LWs4xHCp0Gik-p-z2nOyaPdu-rtA/edit?usp=sharing

> Will presented a request from the Docker WG about getting resources for testing images. Using https://github.com/wblankenship/dante via Jenkins. We discussed repurposing an existing machine since this would be bursty work, focused mainly around releases. debian8 machine on Rackspace being an ideal candidate for now.
> * TODO: make a new user account add Docker and add account to docker user group, fire up a new Jenkins slave for that and let Will manage that in a new Jenkins job.

Reference:
* Automated Tests of Docker Images: https://github.com/nodejs/docker-iojs/issues/46
* Convergence Plans: https://github.com/nodejs/docker-iojs/issues/77
* Proposed Tests: https://github.com/wblankenship/docker-iojs/tree/tests
* Dante Binaries: https://github.com/wblankenship/dante/releases/tag/v1.0.0

// CC: @nodejs/docker @nodejs/docker-admin

**Comment by Trott** [comment]
This has been dormant for over a year. I'm going to close it. Feel absolutely free to re-open or comment if there is active work going on, or this is something that desperately needs to happen, or you otherwise feel it is a mistake to close this.
