### ISSUE TITLE
Need access to OSX

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#1683]
I need access to a machine such as https://ci.nodejs.org/job/node-test-node-addon-api/1530/MACHINE=osx1010/console to debug the issue I'm seeing there.

**Comment by mhdawson** [comment]
+1 from me.

**Comment by refack** [comment]
@gabrielschulhof I've added your GitHub public keys to https://ci.nodejs.org/computer/test-macstadium-macos10.10-x64-1/
(a.k.a. `administrator@test-macstadium-macos10.10-x64-1:10005`) or
```ini
Host test-macstadium-macos10.10-x64-1
  HostName 207.254.58.162
  User administrator
  Port 10005
```

Please stop the jenkins service while doing testing, and restart when finished.
Note: the CI runs as the `iojs` user, so either `su` as it, or make sure file permissions are intact when done.

Happy debugging 🎏

**Comment by gabrielschulhof** [comment]
@refack I believe my public key can now be removed from the machine, and this issue may be closed. Thank you!

**Comment by refack** [comment]
Key removed.
Thanks for the follow up!
