### ISSUE TITLE
Request for temporary access to alpine-latest-x64

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1684]
https://ci.nodejs.org/job/libuv-test-commit-linux/1260/nodes=alpine-latest-x64/ <- weird, unexpected system call failures that don't happen with other kernels. My hunch is a docker bug.

Of interest is that alpine 3.8.1 is supposed to ship a 4.14 kernel but `uv_os_uname()` instead reports this:
```
#   release: 4.4.0-139-generic
#   version: #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018
```

**Comment by refack** [comment]
added you GitHub registered key to
root@130.198.66.50 which is the docker host
Getting into a docker instance is documented in https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#fixing-machines-with-docker
tl;dr `docker ps` then using the container ID `docker exec -it CONTAINER_ID /bin/bash`

New SOP, please stop the jenkins agent within the container while testing, and restart when done.

**Comment by bnoordhuis** [comment]
Thanks @refack, I figured it out. My access can be revoked now.

**Comment by refack** [comment]
Done.

Thanks for following up.
