### ISSUE TITLE
Jenkins slave bailouts (process exit)

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#169]
So, what's happening is that the java process exits after negotiating with the master after a loss of connectivity. There's some noise in the jenkins issue tracker about this but I haven't really seen a solution.

This issue has been around for a while, but since we've started to use our CI more frequently this is becoming very visible since it's unfortunately blocking progress.

The only way around this for now is to either do simple process monitoring (even a cronjob would work here) or something more fancy with monit. Hopefully upstream fixes it at some point though.

```java
Exception in thread "Ping thread for channel hudson.remoting.Channel@19f6996:channel" java.lang.NullPointerException
    at jenkins.slaves.PingFailureAnalyzer.all(PingFailureAnalyzer.java:31)
    at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:111)
    at hudson.remoting.PingThread.ping(PingThread.java:125)
    at hudson.remoting.PingThread.run(PingThread.java:86)
Aug 27, 2015 10:28:47 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Terminated
Aug 27, 2015 10:28:58 PM jenkins.slaves.restarter.JnlpSlaveRestarterInstaller$2$1 onReconnect
INFO: Restarting slave via jenkins.slaves.restarter.UnixSlaveRestarter@5c5e36
Aug 27, 2015 10:29:07 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: iojs-digitalocean-centos5-32-1
Aug 27, 2015 10:29:07 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Aug 27, 2015 10:29:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [https://jenkins-iojs.nodesource.com/]
Aug 27, 2015 10:29:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to jenkins-iojs.nodesource.com:35243
Aug 27, 2015 10:29:07 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Aug 27, 2015 10:29:07 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: iojs-digitalocean-centos5-32-1 is already connected to this master. Rejecting this connection.
java.lang.Exception: The server rejected the connection: iojs-digitalocean-centos5-32-1 is already connected to this master. Rejecting this connection.
    at hudson.remoting.Engine.onConnectionRejected(Engine.java:306)
    at hudson.remoting.Engine.run(Engine.java:276)
```

**Comment by orangemocha** [comment]
When this happens, does Jenkins exit or just hangs?

**Comment by jbergstroem** [comment]
As far as I've seen the process just nopes out of there. There might be some stale state, but at some point it just exits.

**Comment by orangemocha** [comment]
In that case, we could just have a wrapper script (or the current start.sh) restart it after 30 seconds. We might want to do this only for certain exit codes.

**Comment by jbergstroem** [comment]
was thinking in similar lines -- basically crontab something that looks for the correct java process (some vm's have two) and then calls whatever way of init we have (slowly migrating to proper init scripts).

**Comment by rvagg** [comment]
So, monit basically ..

**Comment by jbergstroem** [comment]
@rvagg sure. Crontab has less deps though :)

**Comment by orangemocha** [comment]
@jbergstroem monitoring through crontab can also work, though if you do it in the wrapper script you would know immediately when the process exited. Are there any scenarios that that approach wouldn't catch?

**Comment by jbergstroem** [comment]
@orangemocha I reckon we'd do it outside of the init script. Each init would have its own way -- for instance upstart and systemd would respawn by itself. On other systems my personal preference would be doing a simple crontab job that would zap/restart the init script when needed (thinking that we'd call the cron job every 5 minutes)

**Comment by jbergstroem** [comment]
I think this was resolved by lowering the ping latency to 2 seconds (from the default 5). Closing but feel free to reopen if necessary.

**Comment by wgracelee** [comment]
From jenkins admin point of view, how I can fix it? How do I change the ping latency to 2 seconds? Thanks.

**Comment by jbergstroem** [comment]
@wgracelee we use `-Dhudson.slaves.ChannelPinger.pingInterval=2` to launch the java process.
