### ISSUE TITLE
Low disk caused all three AIX machines offline

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1693]
AIX hosts all went low on disk space and appear to have been auto-offlined. I fixed them but I imagine we want to take steps to avoid it happening again. @gdams @mhdawson 

Me in IRC this morning:

> 4:21 AM AIX queue has gotten quite long....
> 
> 4:23 AM test-osuosl-aix61-ppc64_be-1 seems idle and online but is not picking up any of the jobs. Or at least, that's what I think I'm seeing at https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-1/builds with my limited understanding of Jenkins.
> 
> 4:25 AM "All nodes of  aix61-ppc64 are offline." 
> 
> 4:25 AM https://ci.nodejs.org/label/aix61-ppc64/
> 
> 4:25 AM Low disk space on the AIX hosts, which maybe made them go auto-offline? https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-1/
> 
> 4:30 AM Following the instructions at https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#out-of-space, I'm ran `rm -rf node-test-commit*` on one of the hosts, which freed up a ton of space. Will bring it back online now and see what happens.
> 
> 4:33 AM Seems to have worked. Doing it for the other two AIX hosts. However, I imagine we'll want to take steps to keep this from happening again. I'll open an issue in the repo and ping George and Michael.

**Comment by refack** [comment]
It's a bit strange. Each one of the 3 got clogged up for different reasons, at at different times...
![image](https://user-images.githubusercontent.com/96947/52957668-36285280-3360-11e9-8461-c8dfb2ab1350.png)

I'll look into setting up some sort of alert for this kind of thing.

**Comment by refack** [comment]
P.S. all 3 are back on line.

**Comment by Trott** [comment]
> P.S. all 3 are back on line.

I logged on, did `rm -rf node-test-commit-*` in the `workspace` directory, and put them back online. I just don't know what caused the problem(s) in the first place.

**Comment by mhdawson** [comment]
@refack @Trott thanks for the effort on this front.  @refack some alerting would be great did you have something in mind?

**Comment by refack** [comment]
> @refack some alerting would be great did you have something in mind?

I think Jenkins has the capabilities for alerting... I need to dig out how to do it. I was thinking about the following:
1. Alert when node goes offline for disk space
2. Alert when all nodes in a label are offline
3. Alert if jobs fails N (3 or 4) times in a row

**Comment by refack** [comment]
FTR: this incident was has by three separate causes:
1. worker (1) has a too small ramdisk. Preemptively I've added added `rm -Rf out` to the post build task of [node-test-commit-aix-shared-lib](https://ci.nodejs.org/job/node-test-commit-aix-shared-lib/jobConfigHistory/showDiffFiles?timestamp1=2018-12-20_12-13-23&timestamp2=2019-02-18_08-33-42)
2. Worker (2) had three node worktrees created manualy by people doing debugging
3. Worker (3) a.k.a. the new one.... I don't remember what it was....

**Comment by refack** [comment]
Remembered what was wrong with worker (3) - tiny `/tmp` - https://github.com/nodejs/build/issues/1708
