### ISSUE TITLE
Add IBMi machines to CI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1697]
We have a couple of machines that we can add to the CI.  Next steps include:

- [x] configure for SSL access, add test keys
- [x] create Ansible script and configure https://github.com/nodejs/build/pull/1923
- [x] check execution time for libuv
- [x] add to libuv regression test (if execution time is acceptable) https://github.com/libuv/libuv/issues/2851
- [ ] check execution time for node.js
- [ ] add nightly build/tests for node.js

This will be good as a few weeks ago IBM i was broken by some libuv changes and we only discovered that a bit later.

**Comment by mhdawson** [comment]
@gdams is going to work @theprez to create the initial version of the Ansible scripts.

**Comment by mhdawson** [comment]
We have PR for ansible scripts(https://github.com/nodejs/build/pull/1700).  Just waiting on getting ccache rpm publicly available for IBMi.  

Current ETA is a couple of weeks.

**Comment by Trott** [comment]
@mhdawson Is this still in progress?

**Comment by mhdawson** [comment]
@Trott yes still in the works.  Obviously, my ETA was a bit optimistic.   It's now queued behind the work we are doing to switch to centos7 for PPC.

**Comment by richardlau** [comment]
I've ticked off the done items. We now have IBM i test machines in the CI and added to the libuv-test-commit job.

**Comment by richardlau** [comment]
>     * [ ]  check execution time for node.js
> 

I've created https://ci.nodejs.org/job/node-test-commit-ibmi/. It's WIP (some (known and unknown) test failures, tap2junit encoding issue) but does build and run tests.

Summary of execution times:

### Cold (no existing workspace/git checkout/ccache):
https://ci.nodejs.org/job/node-test-commit-ibmi/1/nodes=ibmi72-ppc64/
Total: 2 hours 52 mins

- 8 mins git checkout
- 2 hours 5 mins build
- 38 mins test

### Subsequent build (with existing git checkout and ccache):
https://ci.nodejs.org/job/node-test-commit-ibmi/4/nodes=ibmi72-ppc64/
Total: 1 hour 35 mins

- 30 sec git checkout
- 57 mins build
- 38 mins test

These are on the slow side, particularly the test execution times.

**Comment by richardlau** [comment]
Once https://github.com/nodejs/node/pull/34209 lands we'll have a green CI for IBM i, e.g. https://ci.nodejs.org/job/node-test-commit-ibmi/14/ for that pull request is green (🎉). 

The [build times for IBM i](https://github.com/nodejs/build/issues/1697#issuecomment-645431735) in the CI are 1 hour 35 mins at best (and ~2 hours 50 mins in the worst case) which seems too long for the IBM i job to run as part of the regular CI. Are there any objections (once we land the aforementioned PR and get green) on adding the IBM i job to the [daily master builds](https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-master/) so it is run daily? We (IBM) will commit to keeping watch on the IBM i job and promptly address issues (i.e. the IBM members of the Build WG (@AshCripps @mhdawson and @richardlau) to address machine issues and @nodejs/platform-ibmi to fix any code issues). If there are no objections by, say, Monday 13th July I'll go ahead and add starting the IBM i job to the daily master job.

cc @nodejs/build

**Comment by Trott** [comment]
No objections to node-daily-master. So long as IBM is committed to following up with any problems that arise (which it certainly seems that they are), node-taily-master seems like the right place for it given the long run time.

**Comment by richardlau** [comment]
I've added IBM i to [node-daily-master](https://ci.nodejs.org/job/node-daily-master/). 
Kicked off a test run: https://ci.nodejs.org/job/node-daily-master/2002/

**Comment by richardlau** [comment]
I'm going to close this -- we did add machines and have IBM i running on each nodejs-daily-master. Anything further than that is blocked on build execution time, but that can be a follow up issue/pull request if anything changes.
