### ISSUE TITLE
Symbol resolution failed ERROR while building ICU 51.2 on AIX with gcc8.1

### ISSUE THREAD

**Issue by HamsaN21** [nodejs/build#1704]
I am trying to build ICU 51.2 using gcc 8.1 compiler on AIX 7.2 . I have set the following environment variables.
export OBJECT_MODE=64
export CFLAGS=-maix64
export CXXFLAGS=-maix64
export LIBPATH=/opt/freeware/lib/pthread/ppc64:/opt/freeware/lib:/usr/lib:/lib

./runConfigureICU AIX/GCC ---- This ran fine .

gmake is throwing error as given below.
gcc -I../../common -I../../i18n -I./../toolutil -DU_ATTRIBUTE_DEPRECATED= -DUCONVMSG_LINK=uconvmsg -maix64 -O3 -Wall -std=c99 -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-stri
ngs -D_ALL_SOURCE -c -o uwmsg.o uwmsg.c
LIBPATH=../../lib:../../stubdata:../../tools/ctestfw:$LIBPATH ../../bin/genrb -e UTF-8 -s resources -d uconvmsg root.txt
Could not load program ../../bin/genrb:
Symbol resolution failed for ../lib/libicuuc51.a[libicuuc.so] because:
Symbol _GLOBAL__AIXI_libicudata51_2_so (number 66) is not exported from dependent
module ../../lib/libicudata51.a[libicudata.so].
Symbol _GLOBAL__AIXD_libicudata51_2_so (number 67) is not exported from dependent
module ../../lib/libicudata51.a[libicudata.so].
Examine .loader section symbols with the 'dump -Tv' command.
gmake[2]: *** [uconvmsg/root.res] Error 255
gmake[2]: Leaving directory /results/ICU_XML4C/icu/source/extra/uconv' gmake[1]: *** [all-recursive] Error 2 gmake[1]: Leaving directory /results/ICU_XML4C/icu/source/extra'
gmake: *** [all-recursive] Error 2

Could any one please suggest some pointers to resolve this issue

**Comment by mhdawson** [comment]
@gireeshpunathil could you take a look?

**Comment by gireeshpunathil** [comment]
@HamsaN21 - are you building ICU separately, or trying to build ICU part of building Node? Can you please provide the full steps you followed, for me to attempt a recreate?

**Comment by HamsaN21** [comment]
@gireeshpunathil Thanks for looking at this issue. By mistake this issue got created in nodejs section.
Its not related to nodejs. I am trying to build ICU separately. 
Now I have got some solution for the issue. I will try that and if it doesn't work out I will raise new issue where its applicable.
