### ISSUE TITLE
Jenkins race condition

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1712]
There is an interesting race condition while opening two pages in jenkins at the same time. One e.g. the regular CI and one the V8 CI. In that case both pages show the same instead of two distinct pages.

Is this something we should report upstream or is it maybe related to our setup?

**Comment by refack** [comment]
I think I've seen it before. AFAICT it's an upstream bug (content is populated with AJAX, and the requests loose context)

**Comment by BridgeAR** [comment]
Push

**Comment by targos** [comment]
I think this obly happens when your are not logged in yet. It's probably related to how jenkins stores the page to redirect you to after login

**Comment by rvagg** [comment]
I don't think there's anything we can do about this. Jenkins is very particular about the way it handles the UI and it's getting worse as Jenkins ages and they try to patch over (real and perceived) security bugs. I get burnt by this regularly, I'm often opening multiple new tabs with Jenkins links only to find they are all at the same place, then have to rewind and start again after the initial login.
