### ISSUE TITLE
infra failures on alpine x64

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1713]
https://ci.nodejs.org/job/node-test-commit-linux/25784/nodes=alpine-latest-x64/console

**Comment by refack** [comment]
This is a laftover from https://github.com/nodejs/build/issues/1682
Cleared.

**Comment by refack** [comment]
New job working - https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/25785/console
closing
