### ISSUE TITLE
infra failures on arm

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1714]
https://ci.nodejs.org/job/node-test-binary-arm/6591/RUN_SUBSET=0,label=pi3-docker/console
https://ci.nodejs.org/job/node-test-binary-arm/6591/RUN_SUBSET=0,label=pi2-docker/console

in both cases `19:55:14 warning: failed to remove out/Release/.nfs00000000000805f3000008f7`

**Comment by refack** [comment]
This usually happens when there a zombie node process. I logged in and killed one and removed the stuck file.
https://ci.nodejs.org/computer/test-requireio_svincent-debian9-armv7l_pi2-1/builds
Will follow up.

**Comment by refack** [comment]
Interesting thing is both zombies were:
```
/home/iojs/build/workspace/node-test-binary-arm/out/Release/node --experimental-modules /home/iojs/build/workspace/node-test-binary-arm/test/fixtures/es-module-url/native.mjs
```

**Comment by refack** [comment]
https://ci.nodejs.org/job/node-test-binary-arm/RUN_SUBSET=0,label=pi2-docker/6592/console is working.
Looking into https://ci.nodejs.org/computer/test-requireio_davglass-debian9-arm64_pi3-1/ again.

**Comment by refack** [comment]
https://ci.nodejs.org/job/node-test-binary-arm/RUN_SUBSET=addons,label=pi3-docker/6593/console working.
Closing
