### ISSUE TITLE
incident: two Windows rackspace hosts are down

### ISSUE THREAD

**Issue by refack** [nodejs/build#1717]
https://ci.nodejs.org/computer/test-rackspace-win2008r2-x64-4/
https://ci.nodejs.org/computer/test-rackspace-win2008r2-x64-5/

Unresponsive to pings and RDP.
Probably need a reboot.
@joaocgreis @mhdawson @rvagg @nodejs/build-infra

**Comment by refack** [comment]
also https://ci.nodejs.org/computer/test-scaleway-ubuntu1604-armv7l-1/

**Comment by rvagg** [comment]
rackspace machines marked as 'shutoff' "by user", perhaps a failed windows update reboot? weird nonetheless.
scaleway machine brought back up with a forced power cycle
