### ISSUE TITLE
Jenkins should notify of results when landing changes

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#172]
As pointed out by @trevnorris , landing changes with node-accept-pull-request or node-merge-commit doesn't provide any notification after the job completes. This means that the committer has to poll the job status, and also fetch the repo or dig through CI logs to find the landed commit ID.

We can do two things:

1. Send an email to the committer. We already have their email address. This should be easy to do with this plugin: https://wiki.jenkins-ci.org/display/JENKINS/Email-ext+plugin though we need to configure an SMTP server.
2. Post a comment on the PR, with the final status of the run, and if succeeded, the top commit ID. Note that this can be done for PRs but not for non-PR merges. This should be done with a dedicated GitHub account. We could use https://github.com/nodejs-jenkins, or https://github.com/iojs-bot, or create a new one.

Both approaches require storing some credentials in Jenkins, for the SMTP server and for the GitHub account.

**Comment by orangemocha** [comment]
@misterdjules : would it make sense to re-use https://github.com/nodejs-jenkins ? Would you be able to share the credentials?

**Comment by Starefossen** [comment]
A third option might be to look into [GitHub's Status API](https://developer.github.com/v3/repos/statuses/).

**Comment by Trott** [comment]
If I understand correctly, node-accept-pull-request and node-merge-commit aren't coming back any time soon (which makes me sad, but what can you do?) so I think this can probably be closed. Feel free to re-open or comment if I'm mistaken.
