### ISSUE TITLE
Access for @sam-github to IBM machines 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1721]
Along with @miladfarca, @sam-github  is going to be helping more with the IBM platforms.

I'd like him to help setup the new machines outlined in: #1705 so I'd like the ok to give him access to those machines as well. 

Based on our criteria in: https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md

I believe he qualifies for ongoing access as:
* He is a collaborator
* He is a long time contributor to the project
* He works on the same team as me at IBM, I'll vouge for him and there would be
   consequences for mis-behaviour.

My request is that I be able to add he's keys to all of machines supporting the IBM platforms.

**Comment by refack** [comment]
+1
Also +1 for permanent access.

**Comment by gireeshpunathil** [comment]
+1
Also +1 for permanent access.

**Comment by mhdawson** [comment]
Going to move forward with adding Sam's keys.

**Comment by sam-github** [comment]
I have keys for rhel72-s390x-3 and rhel72-s390x-1, but not -2.

**Comment by sam-github** [comment]
I'm on the build-wg, have access to build and release.
