### ISSUE TITLE
CITGM: EACCES: permission denied, mkdir '/ramdisk0/citgm' on test-osuosl-aix61-ppc64_be-1

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1726]
CITGM runs on the CI on `test-osuosl-aix61-ppc64_be-1` (I went through the available runs and [only one ran on a different host](https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=aix61-ppc64/512/console) (`test-osuosl-aix61-ppc64_be-3`) and that was a non-infra failure) are failing with `EACCES: permission denied, mkdir '/ramdisk0/citgm'`.

e.g. https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=aix61-ppc64/511/console
```console
18:53:09 + npm set progress=false
18:53:09 npm ERR! path /ramdisk0/citgm
18:53:09 npm ERR! code EACCES
18:53:09 npm ERR! errno -13
18:53:09 npm ERR! syscall mkdir
18:53:09 npm ERR! Error: EACCES: permission denied, mkdir '/ramdisk0/citgm'
18:53:09 npm ERR!  { [Error: EACCES: permission denied, mkdir '/ramdisk0/citgm']
18:53:09 npm ERR!   stack:
18:53:09 npm ERR!    'Error: EACCES: permission denied, mkdir \'/ramdisk0/citgm\'',
18:53:09 npm ERR!   errno: -13,
18:53:09 npm ERR!   code: 'EACCES',
18:53:09 npm ERR!   syscall: 'mkdir',
18:53:09 npm ERR!   path: '/ramdisk0/citgm' }
18:53:09 npm ERR! 
18:53:09 npm ERR! The operation was rejected by your operating system.
18:53:09 npm ERR! It is likely you do not have the permissions to access this file as the current user
18:53:09 npm ERR! 
18:53:09 npm ERR! If you believe this might be a permissions issue, please double-check the
18:53:09 npm ERR! permissions of the file and its containing directories, or try running
18:53:09 npm ERR! the command again as root/Administrator (though this is not recommended).
18:53:09 Build step 'Execute shell' marked build as failure
```

**Comment by refack** [comment]
It might be a tricky issue to solve long term. since after a reboot the ramisk resets it's permissions to root... I run `chown iojs.staff /ramdisk0` for now, let's see how long it keeps.

**Comment by refack** [comment]
https://ci.nodejs.org/job/citgm-smoker-nobuild/519/nodes=aix61-ppc64/console works for now.

**Comment by richardlau** [comment]
> 
> 
> https://ci.nodejs.org/job/citgm-smoker-nobuild/519/nodes=aix61-ppc64/console works for now.

That ran on `test-osuosl-aix61-ppc64_be-3` though and not `test-osuosl-aix61-ppc64_be-1`.

**Comment by refack** [comment]
🤦‍♂️ me.
1 - https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=aix61-ppc64/522/
2 - https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=aix61-ppc64/524/
3 - https://ci.nodejs.org/job/citgm-smoker-nobuild/nodes=aix61-ppc64/523/

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/citgm-smoker-nobuild/522/nodes=aix61-ppc64/console looks good (it might fail for other reasons but it's got past the ramdisk issue).

Thanks for fixing 👍 .
