### ISSUE TITLE
Test commit Linux not completing

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1727]
Had to kill a bunch or current jobs I'm CI... Test commit Linux wasn't finishing but none of the platforms seemed to still be running.

Possible that a platform is down , but couldn't figure it out on mobile

**Comment by refack** [comment]
Yes, both https://ci.nodejs.org/label/ubuntu1804-64/ workers were offline.
They are back online, but I'm tracking them till I close this incident.

**Comment by refack** [comment]
Jobs seem to be chugging along.
![image](https://user-images.githubusercontent.com/96947/54470035-a798cc80-4777-11e9-9d44-2ef33810775d.png)
Load graph back to normal
![image](https://user-images.githubusercontent.com/96947/54470037-bda68d00-4777-11e9-9a18-1ee933d8320f.png)

I call "resolved" on this incident 🎏
