### ISSUE TITLE
Many IBM platforms offline

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1729]
Specifically:

test-iinthecloud-ibmi72-ppc64_be-1
test-iinthecloud-ibmi72-ppc64_be-2
test-linuxonecc-rhel72-s390x-3
test-marist-zos13-s390x-1
test-marist-zos13-s390x-2
test-osuosl-aix61-ppc64_be-1
test-osuosl-aix61-ppc64_be-2
test-osuosl-ubuntu1404-ppc64_be-1
test-osuosl-ubuntu1404-ppc64_be-2
test-osuosl-ubuntu1404-ppc64_le-1
test-osuosl-ubuntu1404-ppc64_le-2
test-osuosl-ubuntu1404-ppc64_le-3

Mostly I think you'll find this note in Jenkins:

> Mar 16, 2019 6:55:15 PM
> This node is offline because it uses an old slave.jar

Not sure what's triggered this, a new plugin perhaps? Or maybe there's a new in-built threshold that's triggered knocking old slave.jars offline. I just went through and upgrade a bunch of others, including many of the macos and smartos platforms and a few old Ubuntus. These IBM platforms are the only ones left in the "old slave.jar" category. I have a couple of Pi's to deal with (other reasons) and a FreeBSD 11 needs rebuilding (WIP).

**Comment by rvagg** [comment]
meant to cc @nodejs/platform-ppc @nodejs/platform-s390, I think that gets to the right people?

**Comment by mhdawson** [comment]
I've fixed up all of the IBM platforms except for:

```
test-iinthecloud-ibmi72-ppc64_be-1
test-iinthecloud-ibmi72-ppc64_be-2
```

**Comment by mhdawson** [comment]
I'm going to lease the two ibmi ones until we move forward with enabling them fully.  I think @gdams was waiting for one thing to be available before landing the ansible updates for them.

**Comment by refack** [comment]
Resolved
