### ISSUE TITLE
modern macOS X (10.13, 14, 15) on MacStadium

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1732]
Current proposal is for Node.js 12 to be built on macOS 10.13 but we don't have MacStadium machines for it yet. This isn't final yet, we'll need to track the discussion about macOS minimum support but having 10.13 in our mix would be a positive anyway.

We will also probably need to change

```
'MACOSX_DEPLOYMENT_TARGET': '10.7',       # -mmacosx-version-min=10.7
```

in common.gypi to reflect a new minimum. Maybe 10.11.

**Comment by mhdawson** [comment]
@refack have you started working on this?

**Comment by refack** [comment]
yes.

**Comment by mhdawson** [comment]
:)

**Comment by mhdawson** [comment]
I don't see any new 10.13 machines in mac stadium, I guess that's your next step?

**Comment by mhdawson** [comment]
As an FYI, you may need to spin down the 10.08 machines in order to have enough disk space to create the 10.13 ones

**Comment by rvagg** [comment]
there's a 10.14 one in there too, I guess that's removable? maybe an experiment?

**Comment by mhdawson** [comment]
I believe we created that earlier but then found there was no 10.14 image.  We might want to finish that so we get 10.14 testing as I think there might now be one.  But if necessary for space it is removable.

**Comment by rvagg** [comment]
As I stated in https://github.com/nodejs/node/pull/26714#issuecomment-484726019 I've rolled back the changes to BUILDING.md to reflect the state of Node 11's macOS support, with the addition of `-mmacosx-version-min=10.10` which has been merged.

I see no evidence of movement on the 10.13 front and it seems too late to me with only a few days to go before 12. I need to get BUILDING.md merged so if anyone's going to take responsibility for changing things at this late stage then you'll have to work on additional BUILDING.md changes.

**Comment by refack** [comment]
I've been digging on this from several directions. tl;dr it seems like the only way to install 10.13 and/or 10.14 is to upgrade the ESXi server.
It should be doable remotely, but in case of failure we might have no machines until we get MacStadium support to assist.

**Comment by refack** [comment]
But we do have 10.12 machines ready https://ci.nodejs.org/label/osx1012/

**Comment by rvagg** [comment]
not for release

**Comment by mhdawson** [comment]
@refack can you clarify why an ESXi server upgrade is needed?

**Comment by cclauss** [comment]
In the past two hours GitHub Actions has upgraded all their MacStadium macOS images to Catalina.

**Comment by sam-github** [comment]
For both recent OS X hosts for build, and for recent OS X hosts as a requirement to install Xcode 10 and later, we need 10.13 or later build hosts. Note these Xcode 10 requirements from https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)

- xcode 10.0 and .1 need osx 10.13.6 or later
- xcode 10.2 and 10.3 (current) need  osx 10.14.3 or later

So, we could do releases on osx 10.13, but I suspect it would be better to get a OS X 10.14 host, and set the deployment target to os x 10.13. But maybe we should run tests on a wider set than we build on? Not sure, but I bring it up because at some point the plan will have to become more clear.

But at this point, we don't have either in macstadium, this is where I am now:

- I have secrets/infra-macstadium access
- I have setup vpn and logged in to macstadium vsphere admin console, also sshed into the jumpbox
- I see there are under "OS-tests" (?) VMs for os x 10.13 and 10.14, neither start
- I made an account with vmware, and downloaded/installed the VMWare Remote Console
- I've attempted to reboot both VMs, neither boot

This is probably where @refack got before posting https://github.com/nodejs/build/issues/1732#issuecomment-484727346, except it sounds like he knew why they didn't boot, or perhaps didn't even install?

I'll see if I can get macstadium support to give some advice here.

**Comment by sam-github** [comment]
Hm, actually, I ran through the instructions on making a new VM.

We don't have enough storage space. I'll have to delete some of the OS-test VMs or we'll have to ask for more.

Can I delete the 3 unused OS-test machines?

**Comment by cclauss** [comment]
Official announcement from GitHub Actions team... https://github.blog/changelog/2019-11-06-github-actions-macos-virtual-environment-updated-to-catalina

**Comment by rvagg** [comment]
@sam-github yes, please prune anything not being actively used and go ahead with what you think appropriate with the reclaimed resources.

**Comment by sam-github** [comment]
Cleaned up unused machines, tried Mojave installs repeatedly, seems to be in a reboot loop, goes a certain distance, restarts, then ends up back where it started....

Opened a ticket: https://portal.macstadium.com/tickets/87213

**Comment by sam-github** [comment]
ticket response:

> In order to run Mojave, you must be running at least ESXi version 6.5. In order to run Catalina, you must be running at least ESXi version 6.7U3, which is the latest release of VMware. Unfortunately, the Apple xServe hardware is not compatible with either of these versions. You would need to look into upgrading to MacPros and need a new vSphere environment deployed.  The new vSphere environment and upgrade does not have any additional charges but swapping to MacPro hardware may incur some cost changes. I can have your account manager reach out to you to discuss your options. Let me know how you would like to proceed. Thanks.

**Comment by sam-github** [comment]
@rvagg @mhdawson @MylesBorins FYI ^--- Any objections if I reply, and just find out as much information as I can about what the situation is? I don't know any of the history, I assume this was donated to "us", but whether us is io.js, joyent, linuxfoundation... I don't know any of that history.

**Comment by rvagg** [comment]
Let me deal directly with the manager of this account via email.

**Comment by sam-github** [comment]
OK, I'll leave the next steps to you, thanks @rvagg

**Comment by sam-github** [comment]
Any progress on getting more build resources from macstadium, @rvagg ?

**Comment by mhdawson** [comment]
@rvagg if you want/can pull me into the discussions I'm happy to try to help move them forward as well.  In theory we might be able to make the increase in resources temporary as we move machines from one infra to another.

**Comment by rvagg** [comment]
thanks for the reminder, email went without response, have tried again, if this one fails we can try through their support channel but I'm afraid that won't get to the right people which is why I'm not trying it first.

**Comment by mhdawson** [comment]
@rvagg thanks !

**Comment by rvagg** [comment]
Support request submitted last week, got a response that it was being handed off to the sales team but nothing further - my guess is that the sales team is just going to give us some $$. I can't get hold of the marketing director who formalised our sponsorship arrangement. So it's looking a little shaky.

**Comment by rvagg** [comment]
Seem to have found the right contact vector @ MacStadium, they'd like to set up a conference call. I'm targeting our current regular meeting time (1pm Pacific). Working on scheduling, but they seem to still be keen to continue support and hopefully that translates to positive outcomes.

**Comment by AshCripps** [comment]
Closing, Modern macos is available through orka and there are DTKs in the CI for 11.0
