### ISSUE TITLE
Windows jobs not running

### ISSUE THREAD

**Issue by cjihrig** [nodejs/build#1740]
I haven't tried any other jobs, but https://ci.nodejs.org/job/libuv-test-commit-windows/ seems to not be working.

**Comment by refack** [comment]
Strange...
Looking into that.

**Comment by refack** [comment]
Ok. seems like Jenkins just needed a swift kick in the pants (restart).
https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1283/ looks Ok (9/9 subjobs running)

**Comment by cjihrig** [comment]
Thank you. Seems to be resolved.

**Comment by refack** [comment]
Happy to help
