### ISSUE TITLE
Improve CITGM CI output

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1742]
It is currently pretty hard to see what failures are new if there are more than a few failures and even if there is the exact same amount of failures as a run before, it's still hard to identify if any regressed further.

We already have the +/- indicator for new failed tests but I wonder if it would be possible to indicate which tests failed that did not fail earlier and even more important: if a former failing test failed with identical output or if the output changed since the last run. If the output change since the last run, it would be great to highlight the changed part above the regular output.

These changes would significantly improve the experience for anyone looking at the results as soon as we once identified a test failure.

**Comment by BridgeAR** [comment]
Common failures are e.g., install failures like https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1773/nodes=debian9-64/testReport/junit/(root)/citgm/leveldown_v4_0_2/

**Comment by refack** [comment]
I had an idea of how to improve this on the CITGM side...
