### ISSUE TITLE
Weird CITGM failures

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1743]
Coffeescript frequently fails with two errors. One is a GLIBC version not being found (https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1774/nodes=rhel72-s390x/testReport/junit/(root)/citgm/coffeescript_v2_3_2/) and the other one is about not found Symbols on AIX (https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1773/nodes=aix61-ppc64/testReport/junit/(root)/citgm/coffeescript_v2_3_2/).

**Comment by richardlau** [comment]
The most likely explanation is that something is wiping out the `LD_LIBRARY_PATH`/`LIBPATH` environment variables and then trying to execute Node.js, which then cannot load the correct C/C++ runtime libraries.

**Comment by richardlau** [comment]
I think it's https://github.com/jashkenas/coffeescript/blob/7f8b36a8bde340b1039423ecc0e10ec0546e15bd/test/invocation_argument_parsing.coffee#L14-L15 but I don't really know enough about the coffeescript syntax to PR the fix to extend `process.env` instead of replacing it.

**Comment by BridgeAR** [comment]
This should be fixed in coffeescript. @richardlau thanks a lot for looking into it!

**Comment by richardlau** [comment]
Fixed in coffeescript 2.4.1.

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/564/
