### ISSUE TITLE
Build WG meeting schedule

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#175]
@nodejs/build : it seems to be that the Build WG is being very effective at making progress, and communication doesn't seem to be a problem at all, thanks to this repo and https://gitter.im/nodejs/build. Now that convergence is pretty much complete (yay!) I was wondering if it would be feasible to have less frequent meetings. Our meetings are pleasant but also very early for the folks in Australia, and very late for the folks in Europe.

So here are a few alternative proposals. Please pitch in. If we don't have a strong winner by consensus we could start a doodle.

1. No scheduled meetings at all. We can always schedule one when the need arises.
2. Keep a recurring meeting just in case, so we don't drop off the face of the Earth. Say once every 4 weeks.
3. Once every 2 weeks
4. Keep the current meeting schedule (every week)
5. Keep meeting once a week but find a different time.
...

My preference would be either 1. or 2.

**Comment by Starefossen** [comment]
My preference would be towards a recurring meeting which can be canceled if there are no items to discuss, so 2 or 3 would be my choices (in that order).

**Comment by orangemocha** [comment]
Perhaps we could combine that with a meeting-agenda label to tag issues, so that the list can drive scheduling or cancelling the meeting.

**Comment by rmg** [comment]
I like the idea of a recurring meeting that can be cancelled. I'm ok with moving the time.

I won't be able to attend today due to a lack of bandwidth.. had a major power outage in the area and I'm stuck with tethered internet off my phone.

**Comment by mhdawson** [comment]
I like the idea of a recurring meeting that is cancelled when not needed as well

**Comment by jbergstroem** [comment]
+1 to cancelling a scheduled meeting as long as we try to make it a day or two ahead.

**Comment by orangemocha** [comment]
Ok, there seem to be consenus around having a pre-scheduled tentative meeting, that is confirmed or cancelled based on whether we have items to discuss. For the last part, I assume that using a "BuildWG-agenda" label is going to be uncontroversial....

What should be the cadence of the pre-scheduled tentative meeting? Doodle poll: http://doodle.com/poll/z86pau8scmt4pmaw

**Comment by orangemocha** [comment]
It looks like we can use the `wg-agenda` label.

What should be the cadence of the pre-scheduled tentative meeting? Doodle poll: http://doodle.com/poll/z86pau8scmt4pmaw

**Comment by rvagg** [comment]
sorry, filled in the doodle, looks like we're at least agreeing to not doing it every week

I'm easy whatever we do, we seem to be making good use of gitter and github, just as long as we make sure the entry-points for newcomers are obvious

**Comment by orangemocha** [comment]
Ok, based on the poll everybody prefers the meeting to be tentatively on every 2 or 3 weeks. Given that more people liked the "every 4 weeks" option than the "every week" option, I went ahead and rescheduled the meeting for every 3 weeks, starting next Tuesday, September 29th. You should have received an updated calendar event.

I'll be sending an advance notice a few days before each occurrence (say on Thursday or Friday the week before) with a request for agenda items. If there are no agenda items by Monday, we can cancel the meeting occurrence.
