### ISSUE TITLE
can we replace George Adams to get email notification of build failures on IBM platforms?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1753]
@gdams moved on from IBM, there is no one monitoring email to his defunct @uk.ibm.com address.

@miladfar and @sam-github are now looking after these two platforms:
- https://ci.nodejs.org/job/node-test-commit-plinux/
- https://ci.nodejs.org/job/node-test-commit-linuxone/

Can our email replace George's in the above, example:

![image](https://user-images.githubusercontent.com/17607/55647687-268b8e80-5793-11e9-9971-ed5139e2c1da.png)

/cc @gdams @miladfar @mhdawson

**Comment by refack** [comment]
Are you sure. It's pretty noisy?

**Comment by sam-github** [comment]
Dawson wants us to keep an eye on it.

**Comment by mhdawson** [comment]
I switched over the main CI job for plinux, and AIX.

**Comment by mhdawson** [comment]
for @sam-github so far.
