### ISSUE TITLE
Enhance node-accept-pull-request form with a script

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#176]
I am not sure yet how it could be done, but if were able to inject a JS script on the ["Build with parameters" page](https://ci.nodejs.org/job/node-accept-pull-request/build?delay=0sec) for node-accept-pull-request, we could do a few things to facilitate the workflow for collaborators.

The script would be respond to update events on the three fields that uniquely identify a PR: TARGET_GITHUB_ORG, TARGET_REPO_NAME, PR_ID. Or maybe just PR_ID. Once an update is detected and those fields contain seemingly valid values, the script could get information about the PR from the GitHub API and allow for the following improvements:

1. Show textareas, one per commit in the PR, prepopulated with the commit messages. This would allow the committer to edit the messages there, without having to pull the changes locally. This could be implemented by having a large number of text areas (like 10) and trigger the visibility only of as many as there are commits in the PR. Then passing the contents of the text areas to the inner job (node-merge-commit), which would modify the commit messages only for non-empty arguments.
2. Find LGTM on the comments, and pre-select the reviewers in the drop-downs.

**Comment by Trott** [comment]
I'm pretty sure `node-accept-pull-request` is not coming back any time soon, so I'm going to close this. Feel free to re-open if you think it should be open.
