### ISSUE TITLE
auto-run of ci-lite prevents PRs from landing even after ci-full suceeds

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1760]
I love the ci auto-posting of results, but I've started getting auto-run of ci-lite on PRs. This is probably the wrong repo, but I'm not sure where else to ask about this.

The problem with auto-running ci-lite, is that `git node land` requires *all* ci types that were run to be green. If a PR also requires a ci-full (most do), even when the ci-full passes, the PR is unlandable if there is a failed ci-lite in the history.

I'm not sure what the fix is here, but a couple thoughts:

- I think the travis auto-run is sufficient, I don't think every PR also needs an auto-run of ci-lite.

- Given that ci-full is a *superset* of ci-lite, perhaps `git node land` should consider a passing ci-full to override older co-lite failures

@joyeecheung 

Example (for anyone who hasn't seen this), slightly abridged:

```
core/node (master $% u-6) % git node land https://github.com/nodejs/node/pull/27162
✔  Done loading data for nodejs/node/pull/27162
----------------------------------- PR info ------------------------------------
Title      src: replace FromJust() with Check() when possible (#27162)
Author     Sam Roberts <vieuxtech@gmail.com> (@sam-github)
Branch     sam-github:check-instead-of-fromjust -> nodejs:master
...
--------------------------------------------------------------------------------
   ℹ  Last Lite PR Pipeline CI on 2019-04-09T22:26:19Z: https://ci.nodejs.org/job/node-test-pull-request-lite-pipeline/3219
   ℹ  Last Full PR CI on 2019-04-11T22:10:07Z: https://ci.nodejs.org/job/node-test-pull-request/22381/
   ⚠  Commits were pushed after the last Lite PR Pipeline CI run:
   ⚠  - src: replace FromJust() with Check() when possible
   ⚠  - fixup! src: replace FromJust() with Check() when possible
   ⚠  - fixup! fixup! src: replace FromJust() with Check() when possible
...
--------------------------------------------------------------------------------
? This PR is not ready to land, do you want to continue? No
...

 ******** Manually delete the ci-lite comment using the github UI

core/node (master $% u-6) % git node land https://github.com/nodejs/node/pull/27162
✔  Done loading data for nodejs/node/pull/27162
----------------------------------- PR info ------------------------------------
Title      src: replace FromJust() with Check() when possible (#27162)
....
--------------------------------------------------------------------------------
   ℹ  Last Full PR CI on 2019-04-11T22:10:07Z: https://ci.nodejs.org/job/node-test-pull-request/22381/
...
--------------------------------------------------------------------------------
? This PR should be ready to land, do you want to continue? Yes
...
```

**Comment by mhdawson** [comment]
I don't think it prevents you from landing it, it just says it is not ready even if it is....

**Comment by richardlau** [comment]
This is a `node-core-util` bug. More specifically the date comparison that attempts to find the most recent CI is the wrong way round so it ends up comparing the commits pushed to the least recent CI: https://github.com/nodejs/node-core-utils/blob/873b22ee9c4a2101f9a31a2759013ae0fccebfd1/lib/pr_checker.js#L204

I'll PR a fix.

**Comment by richardlau** [comment]
PR to fix `node_core_utils`: https://github.com/nodejs/node-core-utils/pull/334
