### ISSUE TITLE
python couldn't run configure on freebsd11-x64

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1762]
What happened here? Is it possible python is the wrong version on this machine?

```
08:42:14 python ./configure --verbose 
08:42:14 Please use either Python 2.6 or 2.7:
08:42:14 
08:42:14   /usr/local/bin/python2 ./configure --verbose
08:42:14 Makefile:474: recipe for target 'build-ci' failed
08:42:14 gmake: *** [build-ci] Error 1
08:42:14 Build step 'Execute shell' marked build as failure
```

- https://ci.nodejs.org/job/node-test-commit-freebsd/25631/nodes=freebsd11-x64/console

**Comment by refack** [comment]
[Fixed](https://ci.nodejs.org/job/node-test-commit-freebsd/jobConfigHistory/showDiffFiles?timestamp1=2019-04-07_08-53-25&timestamp2=2019-04-15_12-53-04) by adding
```bash
which python2 && export PYTHON=python2
```
