### ISSUE TITLE
No Linux x64 nightlies after 20190411655c90b287

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1764]
https://nodejs.org/download/nightly/v12.0.0-nightly20190411655c90b287/ was the last good set of nightlies for master.

https://nodejs.org/download/nightly/v12.0.0-nightly20190412908292cf1f/ is missing Linux x64 binaries.
https://nodejs.org/download/nightly/v12.0.0-nightly201904139b6b567bc4/ is missing Linux x64 and Linux s390x binaries.
https://nodejs.org/download/nightly/v12.0.0-nightly201904141fc4255221/ is missing Linux x64 binaries.
https://nodejs.org/download/nightly/v12.0.0-nightly201904152fed83dee8/ is missing Linux x64 binaries.

**Comment by rvagg** [comment]
no centos7 in ci-release .. one of our Node 12 prep items that hasn't been ticked off!

**Comment by rvagg** [comment]
#1765 & #1766

**Comment by rvagg** [comment]
Got a CentOS 7 machine in ci-release and it's working! This is using GCC 6 for the first time for release binaries. Testing and feedback would be appreciated, I haven't had a chance to touch these yet.
https://nodejs.org/download/nightly/v12.0.0-nightly2019041653e0f632db/node-v12.0.0-nightly2019041653e0f632db-linux-x64.tar.xz

/cc @lukechilds

**Comment by richardlau** [comment]
> 
> 
> Got a CentOS 7 machine in ci-release and it's working! This is using GCC 6 for the first time for release binaries. Testing and feedback would be appreciated, I haven't had a chance to touch these yet.
> https://nodejs.org/download/nightly/v12.0.0-nightly2019041653e0f632db/node-v12.0.0-nightly2019041653e0f632db-linux-x64.tar.xz
> 
FWIW as a basic test the various Linux x64 configurations of https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/587/ all seem to be working with https://nodejs.org/download/nightly/v12.0.0-nightly2019041709cdc37824/node-v12.0.0-nightly2019041709cdc37824-linux-x64.tar.gz.
