### ISSUE TITLE
Would it be approriate for me to join the build-wg github org?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1771]
I'm not sure what the criteria is. I don't want to be responsible for breaking jenkins configuration, but since I'm not a member, I can't tick off or edit TODO checklists (https://github.com/nodejs/build/issues/1705#issuecomment-483768076) or close issues after I fix them (https://github.com/nodejs/build/issues/1757#issuecomment-483357624). I haven't tried, but I suspect I can't merge approved PRs either.

If it's too soon, that's OK, I'll continue to ping folks when I need something done.

**Comment by mhdawson** [comment]
It would make my life easier so I'm +1, but I'll defer to other Build WG members due to the potential conflict of interest :)

**Comment by rvagg** [comment]
> I don't want to be responsible for breaking jenkins configuration

it's ok, we all seem to do it on a regular basis, you just need to be able to swallow your pride and learn from mistakes

+1

**Comment by sam-github** [comment]
@refack you are the other active member, is it too early, or can I join the WG?

**Comment by rvagg** [comment]
@sam-github the entry bar is pretty low around here, just open a PR to add yourself to the list, any help will be appreciated!
