### ISSUE TITLE
DigitalOcean maintenance

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#178]
_Just received:_

Hello!

We'd like to inform you that we're performing a planned software upgrade on the hypervisor that your droplet resides on.

Expected impact:

In the course of this upgrade, please be advised that your droplet will lose network connectivity for 2-5 minutes as part of the maintenance.   Your droplet will remain powered on during this period -- only network connectivity will be lost.  As always, we will do our absolute best to minimize this downtime.

Below is the scheduled window for this maintenance:

Maintenance start: 2015-09-08 05:00 UTC
Maintenance end:  2015-09-08 12:00 UTC

Thank you,
DigitalOcean

Affected Droplets:
iojs-build-centos5-64-1
iojs-build-centos6
iojs-build-centos7
iojs-build-ubuntu1404-64-1
iojs-build-ubuntu1204-64-1
iojs-build-ubuntu1404-32-1
iojs-build-ubuntu1410-64-1
iojs-release-centos5-64-1
iojs-release-centos5-32-1
iojs-build-centos5-32-1
iojs-build-ubuntu1504-64-1
iojs-build-fedora21-1
fishrock123-perf-test
iojs-digitalocean-freebsd-linter-1
iojs-build-fedora22-1
iojs-docker-build-1

**Comment by Fishrock123** [comment]
cc @nodejs/collaborators

**Comment by mscdex** [comment]
Upgrade all the things!

**Comment by jbergstroem** [comment]
Heads up @nodejs/build -- some machines might have a dead jenkins/java process (it sometimes dies without internet connectivity). When restarting, make sure you're either calling the right init script or calling `start.sh` as the `iojs` user.

**Comment by orangemocha** [comment]
Ouch, a 7-hour window :frowning:

**Comment by jbergstroem** [comment]
@orangemocha 2-5 minutes per host though according to above. We should expect jenkins to crash...

**Comment by orangemocha** [comment]
I wish we had a way to mitigate this. Daydreaming now... but imagine if we had redundancy of slaves across clouds, meaning that for no one platform all slaves are hosted on a single cloud provider. Then we could simply turn off the digital ocean machines for one day.

**Comment by ChALkeR** [comment]
That's 2-5 minutes of network connectivity loss for each vm. Will that really crash jenkins?

**Comment by joaocgreis** [comment]
Not really crash jenkins, but if a build is executing on the slave when the connection is lost, the build will fail. And have to be manually restarted.

We might be lucky and have all the servers loosing connectivity at the same time, but it may also be each one in turn, which may cause a lot of builds to fail in that time window.

**Comment by rvagg** [comment]
Let's just make the list more complete shall we?

===========================

Hello!

We'd like to inform you that we're performing a planned software upgrade on the hypervisor that your droplet resides on.

Expected impact:

In the course of this upgrade, please be advised that your droplet will lose network connectivity for 2-5 minutes as part of the maintenance.   Your droplet will remain powered on during this period -- only network connectivity will be lost.  As always, we will do our absolute best to minimize this downtime.

Below is the scheduled window for this maintenance:

Maintenance start: 2015-09-10 08:30 UTC
Maintenance end:  2015-09-10 10:30 UTC

Thank you,
DigitalOcean

Affected Droplets:
deb
iojs-digitalocean-freebsd-linter-2

**Comment by rvagg** [comment]
We'd like to inform you that we're performing a planned software upgrade on the hypervisor that your droplet resides on.

Expected impact:

In the course of this upgrade, please be advised that your droplet will lose network connectivity for 2-5 minutes as part of the maintenance.   Your droplet will remain powered on during this period -- only network connectivity will be lost.  This will not cause a reboot of your droplet.  As always, we will do our absolute best to minimize this downtime.

Below is the scheduled window for this maintenance:

Maintenance start: 2015-09-11 09:30 UTC
Maintenance end:  2015-09-11 11:30 UTC

Thank you,
DigitalOcean

Affected Droplets:
node-jenkins
iojs-build-containers-1
iojs-build-containers-2
iojs-www

**Comment by Fishrock123** [comment]
> node-jenkins

well crap.

**Comment by jbergstroem** [comment]
Finally done!
