### ISSUE TITLE
job request: CI testing for GYP3

### ISSUE THREAD

**Issue by refack** [nodejs/build#1789]
I would like to have a job that does CI testing for [GYP3](https://github.com/refack/GYP) on the Node.js cluster.

Currently testing in done only on Windows, Ubuntu, and macOS (all on Intel X64). This is only a subset of the platforms supported by node-core. As a result bugs and regressions can only be discovered at the earliest at integration time (e.g. https://github.com/nodejs/node/pull/26620), which significantly slows down the development cycle.

Although GYP/GYP3 are not OpenJSF projects, they are is still very important for the development on node-core, and are paramount for the Node.js ecosystem via `node-gyp`.

**Comment by rvagg** [comment]
You have my ⚔️ for this. It's been discussed on and off for years but nobody has done it. I'd love to see a node-gyp job in ci and I encourage you to have a go at building it! Just be conscious of security and the risks of running arbitrary code on machines that aren't isolated between runs.

**Comment by richardlau** [comment]
> You have my ⚔️ for this. It's been discussed on and off for years but nobody has done it. I'd love to see a node-gyp job in ci and I encourage you to have a go at building it! Just be conscious of security and the risks of running arbitrary code on machines that aren't isolated between runs.

Gyp != node-gyp. We already have node-gyp testing in https://ci.nodejs.org/view/All/job/nodegyp-test-pull-request/ (which IMO we should extend to cover more platforms).

+1 for adding gyp3 testing in the CI.

**Comment by rvagg** [comment]
Oh well, it just shows how tuned in I am I guess! Well you have my +1 anyway.

**Comment by cclauss** [comment]
What help is needed?
