### ISSUE TITLE
CI custom builds do not seem up to date

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1790]
Two CI runs showed failing custom builds (https://ci.nodejs.org/job/node-test-pull-request/22625/ and https://ci.nodejs.org/job/node-test-pull-request/22644/). The failures both seem to miss some code changes even though the commit points to the correct hash. I am a bit puzzled about these failures.

PTAL

**Comment by refack** [comment]
My best guess is it comes from the rebasing procedure. I've added `git log -3` to the job so it will be possible to verify what is actually checked out.

**Comment by BridgeAR** [comment]
It seems like there is no rebase going on for this specific CI job.

See the difference here:

https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/6461/consoleFull
https://ci.nodejs.org/job/node-test-commit-linuxone/12806/nodes=rhel72-s390x/consoleFull

**Comment by rvagg** [comment]
Is there an active build contributor who is willing to maintain these "customsuites" builds? Seems like they are causing problems and active folks don't want to take responsibility for them.

**Comment by richardlau** [comment]
Looking at the job config:

![image](https://user-images.githubusercontent.com/5445507/61417796-5ef14b80-a8f0-11e9-8191-f7185706698e.png)

it's trying to execute `./build/master/jenkins/scripts/node-test-commit-pre.sh`. I think this should be `./build/jenkins/scripts/node-test-commit-pre.sh`. And it probably shouldn't be using `-s` (as nothing is being piped into it).

The equivalent in the other jobs, e.g. https://ci.nodejs.org/job/node-test-commit-linux/configure, looks like this:
```console
curl https://raw.githubusercontent.com/nodejs/build/master/jenkins/scripts/node-test-commit-pre.sh | bash -ex -s before
```

**Comment by Trott** [comment]
Making the change suggested by @richardlau (pointing it at the right script and getting rid of the `-s` stuff) seems to have fixed things. Closing, but re-open if I'm being too hasty about that.

Also, +1 to giving @richardlau access to the Jenkins configs for this stuff.

**Comment by richardlau** [comment]
> Also, +1 to giving @richardlau access to the Jenkins configs for this stuff.

Thanks @Trott. I'll raise a separate issue about access/joining the WG so it can be properly discussed/tracked.
