### ISSUE TITLE
Smooth the statistics graph in metrics

### ISSUE THREAD

**Issue by golopot** [nodejs/build#1792]
The metric stats graphs shown in https://nodejs.org/metrics/ could be more useful if the fluctuations are smoothed out, for example, by plotting [moving average](https://en.wikipedia.org/wiki/Moving_average) within a week.

![metics grpah](https://nodejs.org/metrics/summaries/version.png)

**Comment by rvagg** [comment]
This is what I always do when I plot them myself and I've always said that people should do the same if they would like to see it without the jitter. But, I don't think the raw metrics are the appropriate place to present lossy information, that should depend on how it's intended to be consumed and the .csv files are there for that purpose.

If you feel strongly enough that it should be presented on that page, then maybe you could come up with a way to plot simplified data _alongside_ the existing ones then you're welcome to have a go. The scripts are all at https://github.com/nodejs/build/tree/master/setup/www/tools/metrics (that directory will shortly be moving to ansible/www-standalone/tools/metrics though).
