### ISSUE TITLE
aix failing in CI

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1796]
WARNING: Exported symbol not defined: v8::internal::Builtins::Generate_WasmRecordWrite(v8::internal::compiler::CodeAssemblerState*)

/cc @nodejs/platform-aix

**Comment by sam-github** [comment]
It doesn't seem to always fail, or at least, there seems to be plenty of green in CI for AIX: https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/changes

The last failure seems to be a build for this PR: https://github.com/nodejs/node/pull/27405 

Every platform is failing on doc lint, but AIX in particular, see https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/22922/consoleText, has 1000s of "Export symbol not defined" warnings.

The previous PR passed, though, and it's log is also full of "Export symbol not defined" warnings:
https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/22921/

I'd like to understand what those mean, I'll keep poking, but so far they appear to be just warnings.

@MylesBorins why do you think AIX is failing in CI?

**Comment by sam-github** [comment]
I think @miladfar found the PR that failed, see https://github.com/nodejs/node/pull/27417#issuecomment-488159886 for a comment

**Comment by sam-github** [comment]
I think this isn't an issue, and nodejs/node#27417 passed on AIX in last ci, can we close this, @MylesBorins ?
