### ISSUE TITLE
request for temporary access to AIX machine

### ISSUE THREAD

**Issue by ofrobots** [nodejs/build#1801]
I need to investigate this failure that happens only on AIX: https://ci.nodejs.org/job/node-test-commit-aix/23161/nodes=aix61-ppc64/testReport/junit/(root)/test/parallel_test_http_timeout_flag/

Ref: https://github.com/nodejs/node/pull/27704

**Comment by gireeshpunathil** [comment]
+1

**Comment by sam-github** [comment]
+1

If someone documents what has to be done to give access, I'll do it. As-is, I'm not sure what the process is.

**Comment by mhdawson** [comment]
+1, Sam in the case of a former TSC member like @ofrobots I believe we can just add his key so that he can log in.

**Comment by sam-github** [comment]
@ofrobots Paster your ssh public key here, and I'll add to one of the AIX machines for you.

**Comment by ofrobots** [comment]
@sam-github GitHub makes this info public: https://github.com/ofrobots.keys

**Comment by sam-github** [comment]
@ofrobots Added your key to `test-osuosl-aix61-ppc64_be-1`, you should be able to ssh into it.

Please keep an eye on diskspace (`df`), and remove your work dirs when done.

**Comment by ofrobots** [comment]
@sam-github what's the full hostname?

**Comment by sam-github** [comment]
```
Host test-osuosl-aix61-ppc64_be-1 
  HostName 140.211.9.101
  User root
```

**Comment by ofrobots** [comment]
@sam-github :(

```
❯ ssh root@140.211.9.101
root@140.211.9.101: Permission denied (publickey).
```

Does the AIX machine support ED25519 keys?

Maybe we need to use a plain RSA key? Here's my RSA key: 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0kVeb7FjGxDbf/pzZWw7DWLjGXkQ0m/stDP/ZZxd855WXdJWiV+cg9jwGOQGwq56wjNGyLgb8rtv4P9oeqGYbqSHJEc7yaarJiVkzlDuPk0E2Upe1exIO0ls306eDIPjwXBxq3C8hM6mwjkjy49zzRxTkRDqiJ+QdBAjNISwgGYTgDL15kzwSUkTvIC57y6A45i+N9f5eo4M3B0cfXuKS4FjhUDwGD+MZOF8SXcinnTT/Xt+ePF37qh3SY3Q/8yOpHMOyL2EkeHj3YlrzTbyRYDqDzZn5bQFcelFBs6lAta/AUSsosTwPwNJsnyRNAbtH47H/MrSEz1TIaSF4BFbZK+v6xBORkRNN/kmRu8qpANXTXnZGTHEAWqsK5wR4pj6X2o9KPf5nOvC1ruYAHUGNoZZekkQpkseqnbHsR9QiOaQ1hiTMcO8X12TLZJ/OCJT3ABTWvXaP6jOvrlCk079P+zJ+PWGOHey+82Lw5GnVq4bNfwlSeGS6/tfMvKNBoHl5sEQpHSHvCR18oRBgoq6nMVzUNG1ZZw5mFfWJN92g21LULpMKHgVLE6a0FOfGUCsx0Y31P/L9CnPgpoeRrvIkWNbdEHNkKZ6cbYlegf1ipiBxuvXQnXw0rX84sqmlhFlMkeh+UJ5/1Bbc0NDsWpEJHfiM4ObR/7sBRHb4Iw5lzw== ofrobots@google.com
```

**Comment by sam-github** [comment]
@ofrobots uploaded the ssh-rsa key

**Comment by ofrobots** [comment]
I'm done with the debugging. It seems that on AIX, it is important to copy over all of the environment variables. Else `node` isn't able to launch in a child process.

**Comment by sam-github** [comment]
Yes, that is the case. 

@ofrobots I removed your keys from 140.211.9.101.
