### ISSUE TITLE
Make sure fedora-latest and fedora-last-latest are up to date

### ISSUE THREAD

**Issue by targos** [nodejs/build#1804]
I don't know how to see the versions of Fedora installed in CI but according to @refack there's at least one host with Fedora 27.

The latest Fedora is 30 so we should update the CI to have fedora-latest=30 and fedora-last-latest=29.

**Comment by rvagg** [comment]
We have a bit of a resourcing problem with this one. Rackspace is only offering 28 and we've split these in the past between Rackspace and DigitalOcean. I think we might have to trim last-latest and just go a latest with both on DO.

**Comment by rvagg** [comment]
aaaand ansible doesn't properly support fedora 30, at least the ansible I can get on my machine (2.8.0). It appears to be fixed here https://github.com/ansible/ansible/pull/49402 but I'm not sure if that's in a release or even if it works properly. `python2-dnf` isn't available on fedora 30, even though python2 is. ansible hard-wires python2-dnf as a dependency for doing any package management.

At the moment I've switched the fedora27 machines to be both last-latest and latest and remove latest from node-test-commit-linux. I have the DigitalOcean Fedora 26 machine now running on a Fedora 30 image for testing but this is blocking me for now.

**Comment by targos** [comment]
@rvagg I found this issue: https://github.com/ansible/ansible/issues/54855

They say we need to set `ansible_python_interpreter=/usr/bin/python3` to make it work.
