### ISSUE TITLE
Nodejs not building for ARM9 in yocto

### ISSUE THREAD

**Issue by ramgopikrishna** [nodejs/build#1809]
We tried building version 7.10 in yocto build. It says your CPU ARM architecture is not supported.
Our ARM architecture is ARM9(ARM926EJ), so whether nodejs supporting ARM9, if so please let us know the proper vesrion which can help us and also do we need to have any minmum requirements of RAM(Ex:256MB RAM) in device to build node-red or any other modules through npm which is part of nodejs.

**Comment by rvagg** [comment]
So the ARM926EJ core is the ARMv5TEJ architecture, i.e. ARMv5.

Node.js supports ARMv6 at a minimum and from Node.js 12, even that has been downgraded to "experimental" so is not guaranteed to not break from time to time. ARMv7 is your oldest safe version that's usable.

I'm not sure re RAM requirements for the latest Node, that likely changes as newer versions of V8 are adopted and they're targetting mobile processors for their minimums, which are always increasing. At a guess I'd say that 256M should be safe, below that and you might start running into problem territory.
