### ISSUE TITLE
macstadium machines not reachable to ssh

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1810]
As noted in #1175, the macstadium machines aren't responsive via ssh

```
$ ssh test-macstadium-macos10.09-x64-2
ssh: connect to host 207.254.58.162 port 10008: Network is unreachable
```

Something seems to be up with our jump host, or routing, or ...? @mhdawson @refack are either of you able to look into this?

**Comment by mhdawson** [comment]
Taking a look now

**Comment by mhdawson** [comment]
Looks like the issue could just be that test-macstadium-macos10.09-x64-2 has been turned off.

**Comment by mhdawson** [comment]
Other machines are accessible, for example test-macstadium-macos10.10-x61-1 on port  10005

**Comment by mhdawson** [comment]
@rvagg I think you got the wrong issue number or repo as #1175 is unrelated to osx access.

**Comment by mhdawson** [comment]
The following machines have currently been turned off:

test-macstadium-macos10.09-x64-1
test-macstadium-macos10.09-x64-2

All the other should be accessible.

**Comment by mhdawson** [comment]
Looks like those 2 are also not in the CI either...

**Comment by refack** [comment]
We are very close to our MacStedium storage quota, so when I was appempting to create 10.13 and 10.14 machine I turned them off, and removed them (IIRC we still have a saved template). Also IIRC they where never part of a CI job.
My bug that I didn't update the inventory. PR on it's way.
