### ISSUE TITLE
What exactly is plot.gp written in? (To make improvements)

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#1814]
https://github.com/nodejs/build/blob/master/setup/www/tools/metrics/plot.gp

~~As far as I can tell this is `Gofer` but I can find no suitable language reference and I have no idea how I'd test it.~~

I'd like to make the following improvements to the Node.js metrics stuff:

- More colors (or, preferably, dashed lines)
- Legend on the other (left) side, aligned to the left
- Human readable numbers
- Possible non-plotting of values below 0.01% (because versions has too many lines).

**Comment by rvagg** [comment]
http://www.gnuplot.info/
Homebrew should have gnuplot for you in macOS, but the paint engine might be different to what we have on Linux. I have `pngcairo` in plot.gp to be specific and if that works on macOS without failure then you may end up with matching graphics. Fingers crossed.
I think if you grab the summaries files you should be able to run the plots locally. https://nodejs.org/metrics/summaries/, if you can't work out how to make it run let me know and I'll try and replicate a local env.

**Comment by Fishrock123** [comment]
![version](https://user-images.githubusercontent.com/1093990/58712975-f262d180-83c1-11e9-8e10-ba62daf946eb.png)

Well, it's getting better.

**Comment by rvagg** [comment]
FYI there have been discussions about applying a 7-day moving average to the graphs at nodejs.org/metrics. My position has been that /metrics is for raw data and filtering should be done downstream if you want to present it nicely. I always put it through a 7-day moving average when I present the data and it makes it much more legible.
The mess on the right of this chart isn't getting any nicer as we add new versions and that weekly spread for Node 10 is _huge_, so the jitter seems to be increasing over time too (less casual/hobby, more professional/enterprise is my theory on this).
So if that's something you want to experiment with while you're in there then go ahead. Doing the average in gnuplot might be tricky (not something I've done before) so we may need to prefilter with awk.

**Comment by Fishrock123** [comment]
Hmmm, might be a good next step, yeah. I don't particularly know awk but my guess is also it would be better done there.
