### ISSUE TITLE
Benchmark machine is missing `perf` binary

### ISSUE THREAD

**Issue by targos** [nodejs/build#1816]
Used by `node-test-commit-v8-linux`: https://ci.nodejs.org/job/node-test-commit-v8-linux/2342/nodes=benchmark,v8test=v8test/console

```
22:01:11 + perf --version
22:01:11 /tmp/jenkins8232152946391786726.sh: 104: /tmp/jenkins8232152946391786726.sh: perf: not found
22:01:11 + exit 54
```

**Comment by rvagg** [comment]
@targos is perf a new requirement for this job or is this a new error for this job that has previously been working?

infra-softlayer-ubuntu1404-x64-2 has been around a long time and I don't see evidence that someone's been messing with installed software. We can probably install perf on it, although 14.04 is ancient now and perhaps there'll be trouble getting a perf to match the kernel with all the ppa's moving on. But first I'd like to understand why this is newly broken.

**Comment by targos** [comment]
@rvagg I don't know actually. This makes the build permanently yellow (when not red) but maybe it was always like that.
/cc @mhdawson

**Comment by sam-github** [comment]
I only spent a couple minutes, but the deps/v8 tree definitely has references to perf, such as deps/v8/tools/unittests/run_perf_test.py. It may be a test dependency. @nodejs/v8 -- do one of you know if `perf` is an expected dependency of the v8 tests? It looks like we call `deps/v8/tools/run-tests.py` to run the `mjsunit cctest debugger inspector message preparser` and `benchmarks` tests.

I'll try to repro the problems on local linux after uninstalling perf to see what happens.

/cc @miladfarca

**Comment by targos** [comment]
@sam-github it's used at least by one of our own tests that we only run in this job: `test/v8-updates/test-linux-perf`

**Comment by sam-github** [comment]
OK, so its a test dep. @targos, can you figure out from which release versions it became a test dep?

Also, is it only a perf test dep, or is it all v8 tests? I can look at how the benchmark machine is ansibled, but it would be good to know for what, and since when, perf is need, if you have the time to figure that out.

**Comment by targos** [comment]
@sam-github 

The test was added in this PR: https://github.com/nodejs/node/pull/20783
Node.js v10.5.0 (Jun 20, 2018) is the first release that contains it.
I am not certain but I think I remember V8 CI being green more recently than that.

**Comment by rvagg** [comment]
is green now https://ci.nodejs.org/job/node-test-commit-v8-linux/nodes=benchmark,v8test=v8test/2351/

I manually did a full compile from linux kernel master (same as https://github.com/nodejs/build/blob/master/ansible/roles/linux-perf/tasks/main.yml which is restricted to 16.04 machines). I don't think we have this machine ansibilised properly so manual will have to do I think. @mhdawson that's correct isn't it? It's got all the benchmark rsync stuff on it which I think is manually set up too.

**Comment by sam-github** [comment]
Great, thanks @rvagg

**Comment by targos** [comment]
Thanks a lot, Rod!
