### ISSUE TITLE
travis-ci failed to find compiler

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1819]
https://travis-ci.com/nodejs/node/jobs/205078483

`./configure`/`ccache` couldn't find `g++-6`. I'm rebuilding, but this is a strange kind of error if it is indeed ephemeral.

Has anyone seen this before?

**Comment by refack** [comment]
Yes. I've that once before last week. Seemed to me like a Travis issue since our `.travis.yml` hasn't changed...

**Comment by sam-github** [comment]
Ok, thanks @refack . It didn't happen on the next run. I'll close this, I guess there is nothing we can do.
