### ISSUE TITLE
Intermittent tty timeouts on AIX

### ISSUE THREAD

**Issue by refack** [nodejs/build#1820]
We have a different but intermittent problem on AIX:

https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23617/console
```
08:32:35 ok 2550 pseudo-tty/test-async-wrap-getasyncid-tty
08:32:35   ---
08:32:35   duration_ms: 0.166
08:32:35   ...
08:42:35 Build timed out (after 10 minutes). Marking the build as failed.
08:42:35 gmake[1]: *** [test-ci] Terminated
```

https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23618/console
```
09:35:15 ok 2550 pseudo-tty/test-async-wrap-getasyncid-tty
09:35:15   ---
09:35:15   duration_ms: 0.176
09:35:15   ...
09:45:15 Build timed out (after 10 minutes). Marking the build as failed.
09:45:15 gmake[1]: *** [test-ci] Terminated
```

https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23622/console
```
11:38:22 ok 2539 message/vm_dont_display_syntax_error
11:38:22   ---
11:38:22   duration_ms: 0.110
11:38:22   ...
11:48:22 Build timed out (after 10 minutes). Marking the build as failed.
11:48:23 gmake[1]: *** [test-ci] Terminated
```

easy to reproduce:
```bash
> su iojs
> cd /home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64
> NODE_NAME=test-osuosl-aix61-ppc64_be-3 . build/jenkins/scripts/select-compiler.sh
> python tools/test.py pseudo-tty/console-dumb-tty
```
or
```
python -m trace -t tools/test.py --report pseudo-tty
```
to see a trace of all lines. Seems like there's an issue with sub-process spawning and ptty, since the process stalls on:
```
test.py(648):   if faketty:
test.py(649):     os.close(rest['stdout'])
```
where [`rest['stdout']`](https://github.com/nodejs/node/blob/cb68c04ce1bc4534b2d92bc7319c6ff6dda0180d/tools/test.py#L648-L649) is `fd_out` created by [`(out_master, fd_out) = pty.openpty()`](https://github.com/nodejs/node/blob/cb68c04ce1bc4534b2d92bc7319c6ff6dda0180d/tools/test.py#L721-L723)

_Originally posted by @refack in https://github.com/nodejs/build/issues/1815#issuecomment-498848942_

**Comment by richardlau** [comment]
Possibly related to https://github.com/nodejs/node/issues/9728? cc @gireeshpunathil

**Comment by mhdawson** [comment]
I think @sam-github has been looking at this one.

**Comment by sam-github** [comment]
Nope, first I've heard of it.

I seem to recall that years ago, during the first ports to AIX, that there was a problem with python involving ptys. @gireeshpunathil or @richardlau, you were around then, do you remember this?

**Comment by richardlau** [comment]
> 
> 
> Nope, first I've heard of it.
> 
> I seem to recall that years ago, during the first ports to AIX, that there was a problem with python involving ptys. @gireeshpunathil or @richardlau, you were around then, do you remember this?

I think it was the https://github.com/nodejs/node/issues/9728 I referenced earlier.

**Comment by sam-github** [comment]
@refack just to be clear, `python tools/test.py --report pseudo-tty` is how to repro the issue, but its not what we are actually doing in CI? I ask, because if we were doing that, a possible workaround would be to just stop using  `--report pseudo-tty`.

**Comment by refack** [comment]
@sam-github, yes.
`--report pseudo-tty` are two independent args `--report` is just informative, `pseudo-tty` is a positional arg telling the harness which suite to run.

I updated the recipe to:
```bash
> su iojs
> cd /home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64
> NODE_NAME=test-osuosl-aix61-ppc64_be-3 . build/jenkins/scripts/select-compiler.sh
> python tools/test.py pseudo-tty/console-dumb-tty
```

**Comment by refack** [comment]
> I think @sam-github has been looking at this one.

This might be related to the issue behind https://ci.nodejs.org/job/node-test-commit-aix/23596/ 🤷‍♂ 
![image](https://user-images.githubusercontent.com/96947/58994898-1e19f900-87c0-11e9-9ffb-c1a042d5b449.png)

**Comment by sam-github** [comment]
That would nice if its true. I reset the TERM on the problem host, so I'll keep an eye on this.

**Comment by richardlau** [comment]
https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-2/ (the problematic host) is currently offline (disconnected by @joyeecheung since this morning).

**Comment by mhdawson** [comment]
@sam-github I guess  its needs another look.

**Comment by bnoordhuis** [comment]
I'll take this one.

**Comment by sam-github** [comment]
I'm not sure how to read the following failures, they have the same timed out after 10 minutes message, but they did *NOT* timeout during a tools/test.py run... So, does that mean the problem is not related to tools/test.py and python and PTYs? Or does it mean there are two problems?
```
ppc64/out/Release/obj.target/tools/v8_gypfiles/libv8_libsampler.a /home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/obj.target/tools/v8_gypfiles/libv8_compiler.a /home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/obj.target/tools/v8_gypfiles/libv8_initializers.a -latomic -ldl -lrt -lm -lperfstat
02:10:44 Build timed out (after 10 minutes). Marking the build as failed.
02:10:44 Build was aborted
```
- https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23981/console

```
ppc64/out/Release/obj.target/tools/v8_gypfiles/libv8_compiler.a /home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/obj.target/tools/v8_gypfiles/libv8_initializers.a -latomic -ldl -lrt -lm -lperfstat
09:15:14 Build timed out (after 10 minutes). Marking the build as failed.
09:15:14 Build was aborted
```
- https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/23987/console

**Comment by sam-github** [comment]
I reviewed all the failures on https://ci.nodejs.org/job/node-test-commit-aix/ from 23960 to 23988 and categorized by failure, and by node number (the `: #` refers to `....-be-#`).

during cc test compiles: Build timed out (after 10 minutes). Marking the build as failed.
- 23988: 3, 
- 23987: 1
- 23986: 3
- 23985: 3
- 23984: 3
- 23981: 1
- 23978: 3

during js tests: Build timed out (after 10 minutes). Marking the build as failed.
- 23983: 1
- 23964: 3
- 23960: 3

Those two are possibly related to PTY issues, and I'm leaving them here in this issue.

Found also
- 2 instances of https://github.com/nodejs/build/issues/1847
- 6 instances of https://github.com/nodejs/build/issues/1849

**Comment by sam-github** [comment]
@bnoordhuis This bug is easily reproduceable, as @refack says, you can do it via ssh:

```
ssh test-osuosl-aix61-ppc64_be-1
su - iojs
cd /home/iojs/build/workspace/node-stress-single-test/nodes/aix61-ppc64
export NODE_NAME=test-osuosl-aix61-ppc64_be-1
. ./build/jenkins/scripts/select-compiler.sh
time ./out/Release/node test/pseudo-tty/console-dumb-tty.js
# instantly completes
python tools/test.py -p tap --logfile testx.tap --mode=release pseudo-tty/console-dumb-tty
# hangs indefinitely
```

I added your key to the machine, see https://github.com/nodejs/build/issues/1848, and I suspect the build above will sit around for a while (until the next time a node-stress-single-test is run on that machine, which doesn't happen by default).

**Comment by bnoordhuis** [comment]
Here is what I found so far: the pty's slave fd is closed too early.

Reduced test case:
```python
BUG = True
import os, pty, subprocess
(master, slave) = pty.openpty()
proc = subprocess.Popen(['/bin/echo', 'ok'], stdin=slave, stdout=slave, stderr=slave)
if BUG: os.close(slave) # hangs!
print(proc.wait())
print(os.read(master, 256)) # '' if BUG else 'ok'
if not BUG: os.close(slave) # ok
```
This also affects e.g. macos although it only causes a slowdown there, not a hang.

**Comment by sam-github** [comment]
When this happens, the last test that completed was often addons/stringbytes-external-exceed-max/test-stringbytes-external-at-max or message/vm_dont_display_syntax_error

The test AFTER those, the one which is likely hanging, would be addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max or pseudo-tty/console-dumb-tty, @bnoordhuis do you think this is coincidence? These are two of the more common causes of spurious AIX CI failures, I'm wondering whether we should skip those two tests on AIX.

**Comment by bnoordhuis** [comment]
Here is a pure C test case that exhibits the same hang on AIX but works on other platforms:
<details>

```c
// gcc t.c && ./a.out /bin/sh -c 'echo 1; sleep 1; echo 2; sleep 1; echo 3; sleep 1'
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>

// no <err.h> on AIX
#define err(n, s) do { fprintf(stderr, s ": errno=%d\n", errno); exit(n); } while (0)

extern char **environ;

// no openty() on AIX
int
openpty(int *master, int *slave)
{
        char *name;

        *slave = -1;
        if (-1 == (*master = posix_openpt(O_NOCTTY|O_RDWR)))
                return -1;

        if (grantpt(*master))
                goto fail;

        if (unlockpt(*master))
                goto fail;

        if (!(name = ptsname(*master)))
                goto fail;

        if (-1 == (*slave = open(name, O_NOCTTY|O_RDWR)))
                goto fail;

        return 0;

fail:
        close(*master);
        *master = -1;
        return -1;
}

void
child(int slave, char **argv)
{
        int fd;

        for (fd = 0; fd <= 2; fd++)
                if (-1 == dup2(slave, fd))
                        err(1, "dup2");

        if (execve(*argv, argv, environ))
                err(1, "execve");
}

void
parent(int master, pid_t pid)
{
        char s[256];
        int status;
        ssize_t n;

        for (;;)
        {
                do
                        n = read(master, s, sizeof(s));
                while (n == -1 && errno == EINTR);

                if (n == -1 && errno == EIO)
                        break;  // okay, means EOF

                if (n == -1)
                        err(1, "read");

                if (n == 0)
                        break;

                write(1, s, n);  // taking a chance on EINTR...
        }

        do
                n = waitpid(pid, &status, 0);
        while (n == -1 && errno == EINTR);

        printf("status=%x\n", status);
}

int
main(int argc, char **argv)
{
        int master, slave;
        pid_t pid;

        if (argc < 2)
                return 0;

        if (openpty(&master, &slave))
                err(1, "openpty");

        switch (pid = fork()) {
        case -1:
                err(1, "fork");
        case 0:
#if 0  // change to 1 to enable fix
                if (close(master))
                        err(1, "close");
#endif
                child(slave, argv+1);
                break;
        default:
                if (close(slave))
                        err(1, "close");
                parent(master, pid);
                break;
        }

        return 0;
}
```

</details>

It starts to work when I close the slave fd in the master process and vice versa right after fork, see the `#if 0` directive in main().

The problem is that I can't seem to bend python to do the same. I would expect this patch that closes the master fd in `preexec_fn` to fix it but it doesn't. :-(

<details>

```diff
diff --git a/tools/test.py b/tools/test.py
index 2247db3635..46a0f457da 100755
--- a/tools/test.py
+++ b/tools/test.py
@@ -638,15 +638,12 @@ def RunProcess(context, timeout, args, **rest):
       prev_error_mode = Win32SetErrorMode(error_mode)
       Win32SetErrorMode(error_mode | prev_error_mode)
 
-  faketty = rest.pop('faketty', False)
   pty_out = rest.pop('pty_out')
 
   process = subprocess.Popen(
     args = popen_args,
     **rest
   )
-  if faketty:
-    os.close(rest['stdout'])
   if utils.IsWindows() and context.suppress_dialogs and prev_error_mode != SEM_INVALID_VALUE:
     Win32SetErrorMode(prev_error_mode)
   # Compute the end time - if the process crosses this limit we
@@ -659,7 +656,8 @@ def RunProcess(context, timeout, args, **rest):
   exit_code = None
   sleep_time = INITIAL_SLEEP_TIME
   output = ''
-  if faketty:
+  if pty_out:
+    os.close(rest['stdout'])  # Close slave fd in master process.
     while True:
       if time.time() >= end_time:
         # Kill the process and wait for it to exit.
@@ -680,6 +678,7 @@ def RunProcess(context, timeout, args, **rest):
         if not data: # EOF
           break
         output += data
+    os.close(pty_out)
 
   while exit_code is None:
     if (not end_time is None) and (time.time() >= end_time):
@@ -750,13 +749,12 @@ def Execute(args, context, timeout=None, env=None, faketty=False, disable_core_f
   for key, value in env.items():
     env_copy[key] = value
 
-  preexec_fn = None
-
-  if disable_core_files and not utils.IsWindows():
-    def disableCoreFiles():
+  def preexec_fn():
+    if pty_out:
+      os.close(pty_out)  # Close master fd in slave process.
+    if disable_core_files and not utils.IsWindows():
       import resource
       resource.setrlimit(resource.RLIMIT_CORE, (0,0))
-    preexec_fn = disableCoreFiles
 
   (process, exit_code, timed_out, output) = RunProcess(
     context,
@@ -766,12 +764,10 @@ def Execute(args, context, timeout=None, env=None, faketty=False, disable_core_f
     stdout = fd_out,
     stderr = fd_err,
     env = env_copy,
-    faketty = faketty,
     pty_out = pty_out,
     preexec_fn = preexec_fn
   )
-  if faketty:
-    os.close(out_master)
+  if pty_out:
     errors = ''
   else:
     os.close(fd_out)
```
</details>

**Comment by bnoordhuis** [comment]
Good news and bad news.

The good news: I found the magic incantation. Doing a zero read on the master fd stops `os.close(slave)` from hanging, no `preexec_fn` needed.

Probably a python quirk because it's not needed in the C test case.
```python
import errno, os, pty, subprocess, sys
(master, slave) = pty.openpty()
proc = subprocess.Popen(sys.argv[1:], stdin=slave, stdout=slave, stderr=slave)
os.read(master, 0)
os.close(slave)
while True:
  try:
    s = os.read(master, 256)
  except OSError as e:
    if e.errno == errno.EIO: break
    raise
  if not s: break
  sys.stdout.write(s)
os.close(master)
proc.wait()
```
The bad news: transplanting the logic above to tools/test.py does not fix the issue, it still hangs at `os.close(slave)` :-(

**Comment by bnoordhuis** [comment]
> The test AFTER those, the one which is likely hanging, would be addons/stringbytes-external-exceed-max/test-stringbytes-external-exceed-max or pseudo-tty/console-dumb-tty, @bnoordhuis do you think this is coincidence?

@sam-github It does seem to be a prevailing pattern, yes. Saw it happen a few more times today.

It's interesting that I don't see a hang when I run `python tools/test.py addons` or `out/Release/node test/addons/test-stringbytes-external-exceed-max.js` manually.

I can reproduce the `pseudo-tty/console-dumb-tty` hang easily though.
