### ISSUE TITLE
Need access to OSX again

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#1821]
May I please have access to an OSX machine again so I might perform the test described at https://github.com/nodejs/node-gyp/pull/1689/#issuecomment-498873009?

**Comment by gireeshpunathil** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by rvagg** [comment]
@gabrielschulhof I've the same Refael did in https://github.com/nodejs/build/issues/1683#issuecomment-462393439, so same procedure applies, have fun

**Comment by cclauss** [comment]
Can this be closed?
