### ISSUE TITLE
Migrate test-softlayer-centos5-x64-2.softlayer.com

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1824]
test-softlayer-centos5-x64-2.softlayer.com needs to be migrated before Sep 2019

Seems that the Datacenter (Dallas 1) that it is in is being retired.  Looks like our only machine there.

@rvagg can you confirm we still need this machine?

**Comment by rvagg** [comment]
I think our CentOS 5 needs died with Node 6 this year: https://github.com/nodejs/build/blob/master/jenkins/scripts/VersionSelectorScript.groovy#L15
https://ci.nodejs.org/computer/test-softlayer-centos5-x64-2/builds has no recent history of builds which seems to confirm this.
Probably safe to remove. If we ever needed CentOS 5 again for some reason I think I'd advocate for doing it in Docker, but I really hope it's fully behind us as it's been dead weight.

**Comment by mhdawson** [comment]
@rvagg I was hoping for that answer :).

**Comment by mhdawson** [comment]
Seems like this would have taken care of itself. Closing
