### ISSUE TITLE
can I get jenkins admin permissions?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1826]
They weren't given to me in https://github.com/nodejs/build/pull/1787, but it turns out they will be useful. I will be very careful with them, I promise.

It will help make small tweeks to existing config on platforms I'm helping maintain, and certain types of verification and config of releases and tests on new machines need job cloning capability.

**Comment by mhdawson** [comment]
+1 I've been having to do updates for sam (for example adding centos7-ppcle), so it would be useful if he could do them himself.

**Comment by rvagg** [comment]
I don't mind, as a TSC member, IBM employee and all round smart fella it doesn't seem like a risk. This is done by adding him to the jenkins-admins Team in the org.

Own your breakage.

**Comment by mhdawson** [comment]
Unless we have objections by Monday next week I'll go ahead an add him.

**Comment by mhdawson** [comment]
I've added same to the jekins-admin team, closing.
