### ISSUE TITLE
jenkins: gateway timeout

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#183]
Some pages seems to raise a gateway timeout - especially index pages for TAP results. Here's two pages that seems to fail for me, pretty consistently:
 - https://ci.nodejs.org/job/node-test-commit-linux/lastFailedBuild/nodes=centos5-64/tapTestReport/
 - https://jenkins-iojs.nodesource.com/computer/iojs-digitalocean-centos5-64-1/systemInfo

**Comment by joaocgreis** [comment]
The `tapTestReport` is also a problem for me, but `systemInfo` opens without any problem.

This one was failing yesterday, now seems good: https://ci.nodejs.org/job/node-test-commit-other/423/nodes=smartos14-64/tapTestReport/

**Comment by joaocgreis** [comment]
The link to specific test outputs seems to always work (just by appending `/test.tap-###/`). E. g. for the link above: https://ci.nodejs.org/job/node-test-commit-linux/lastFailedBuild/nodes=centos5-64/tapTestReport/test.tap-123/

**Comment by jbergstroem** [comment]
This was tied to a starved nursery gc size. Reckon its fixed.
