### ISSUE TITLE
Automatic CI does not always work

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1833]
At the moment our CI often replies with `Sadly, an error occurred when I tried to trigger a build. :(`. If I am correct the lite CI job is not triggered anymore.

There was definitely a recent update to the bot since it now updates the latest post with the latest CI run instead of posting new entries every time. I guess that is related?

**Comment by BridgeAR** [comment]
Refs: https://github.com/nodejs/node/pull/28181#issuecomment-500995660

**Comment by richardlau** [comment]
See https://github.com/nodejs/github-bot/issues/235 for ongoing investigation.

**Comment by rvagg** [comment]
closing in favour of nodejs/github-bot#235, I don't think we have anything new on it unfortunately
