### ISSUE TITLE
TODO: ansible config for unencrypted (was: Lost SSH access to unencrypted.nodejs.org)

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1843]
Following on from https://github.com/nodejs/nodejs.org/issues/2266

unencrypted.nodejs.org serves our downloads via HTTP, acts as an rsync mirror for downloads for those that want it, and also serves as a backup www host if the main one goes down and Cloudflare needs an end-point.

It's an Ubuntu 16.04 on Joyent, "big-disk" type that had 1.3T of root. That filled up with all our downloadables. I think that happened a couple of months ago and we were only just informed that it wasn't in sync!

Today I resized it up one tier so now it's a ~2.5T root (resize on Joyent is pretty nice, it does it in-place while the machine is running and the instance just adapts). I ran an update and decided to reboot to clean up any services that may have borked due to full disk, the machine is up again and I know that rsync is working because I watched it catch up when it had more disk available so it's working properly again. However:

```
$ ssh unencrypted
ssh: connect to host 72.2.119.21 port 22: Connection refused
```

I've done a couple of reboots and stop/starts through Joyent's admin console to no avail.

Joyent doesn't have any tools that I can use to look at the console or grab the disk and do a manual repair or rebuild. So it's stuck, apparently working, but stuck. It's probably got a console prompt asking for something before proceeding.

So, it will probably need to be rebuilt from scratch. Unfortunately there's no Ansible for this host (there's a TODO in ansible/README.md ...). I don't think we have copies of the config files (rsync and nginx being the two main configs that would be nice to have).

The key pieces that I know off the top of my head (and having just been in there):

* /home/www is a mirror of the web content on nodejs.org and nginx responds with that content when asked for "nodejs.org"
* /home/dist contains a mirror of /home/dist on nodejs.org, all the dowloadables
* There's a systemd timer task that runs on 15 minute intervals that does the rsyncing from nodejs.org server (I wouldn't mind inverting this to make it a push operation so we don't have other servers with keys into the primary server, like how we inverted this for the benchmarks content).
* The nginx config is almost exactly the same for nodejs.org as it is on the primary server, I remember doing a sync of that not too long ago to make sure it responded in the same way (an auto sync of this might be nice too because getting out of sync is annoying).
* The nginx logs are the same format and rotation rules as on nodejs.org and during the syncing operation it pushes its logs to the primary server so that they are taken into account for nodejs.org/metrics

/cc @jbergstroem just in case you happen to have any config files locally
/cc @cjihrig just in case there's some super-secret tools @ Joyent that you can use to get into this host or attach its storage to another host so we can do a rebuild. It's "infra-joyent-ubuntu1604-x64-1" / 623f2056-2097-cfb9-a604-83918ab3ca0c in our account.

**Comment by cjihrig** [comment]
@rvagg I'm reaching out internally to see if there is anything we can do to help.

**Comment by cjihrig** [comment]
@rvagg / @jbergstroem / @mhdawson it sounds like the problem can be addressed from the Joyent side if you open a ticket granting them permission to log in to the instance and fix the issue.

**Comment by jbergstroem** [comment]
@rvagg: couldn't find any config files :cry:. Lets proceed with @cjihrig's suggestion.

**Comment by jbergstroem** [comment]
So, support just got back to me:
> I logged into the instance and found that the ssh service was not running due to a bug where the /var/run/sshd directory is missing after upgrading an Ubuntu LX image. I added the directory back and this allowed me to start the ssh service inside the instance. In the future when you update an Ubuntu image verify the /var/run/sshd directory is present before rebooting the instance. I have included a screen grab of what I did to resolve this.

I can confirm that I now can log in.

**Comment by jbergstroem** [comment]
Looks like the rsync job is starting:
```console
● rsyncmirror.service - runs a rsync mirror against nodejs main server
   Loaded: loaded (/etc/systemd/system/rsyncmirror.service; static; vendor preset: enabled)
   Active: activating (start) since Wed 2019-06-19 19:43:55 UTC; 16s ago
```

I made a copy of the jobs as well as `/etc/nginx/`

**Comment by rvagg** [comment]
thanks @cjihrig and @jbergstroem! I might keep this issue open and rename it as a reminder that we need to get this in ansible.

**Comment by jbergstroem** [comment]
Tbh I prefer pulling from the machine over pushing from the host. The idea was to have a more locked-down "backup" since `www` does more than just mirror downloads.
