### ISSUE TITLE
Request AIX access

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1848]
I'd like to request access to test-osuosl-aix61-ppc64_be-1 or test-osuosl-aix61-ppc64_be-2 to debug #1820.

edit: I think test-osuosl-aix61-ppc64_be-2 is already offline? That would probably be the best one to test on then.

**Comment by gireeshpunathil** [comment]
+1

**Comment by sam-github** [comment]
+1

@bnoordhuis meets all the criteria for access (well-known, long standing involvement in Node.js, ex-TSC member, well-known employer, significant work/personal consequences if access is abused, etc.).

**Comment by mhdawson** [comment]
+1

**Comment by sam-github** [comment]
@bnoordhuis key from https://github.com/bnoordhuis.keys  added to 
```
Host test-osuosl-aix61-ppc64_be-1 
  HostName 140.211.9.101
  User root
```

**Comment by bnoordhuis** [comment]
I've removed my key from the machine again.
