### ISSUE TITLE
Discussion: Raspberry Pi 4 for CI

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1851]
The [Pi 4](https://www.raspberrypi.org/blog/raspberry-pi-4-on-sale-now-from-35/) was announced today. Pretty hefty upgrade to the 3.

One important piece of information I can't discern from any of the release announcements is whether Raspbian is going 64-bit for this. They've always shipped ARMv6-compatible binaries, running everything in 32-bit, including the Pi 3. While that's nice for maximum compatibility, that might be limiting for this newer hardware.

That might be an interesting piece of information for our purposes because if this thing is going to be running in a significantly different mode to the 4 then testing might be more worthwhile. Otherwise, it might not be unsafe to assume that our testing for the 3 is good enough to cover the 4.

On the flip side, we have some solid arm64 in our infra already, and we're doing Ubuntu and CentOS on those. They're server class processors, though.

We've stopped testing on Pi 1 B+'s for everything less than Node 12, so they get less of a workout in our infra. Perhaps we could balance resourcing by replacing between 4 and 6 of them with Pi 4's? So we end up with the same number in total.

I've ordered one to play with. I'm assuming network booting will be super simple with this so it just needs power and network (if we're lucky it'd support PoE but I doubt it). The maintenance burden is decreased if we don't need to deal with SD cards at all.

Thoughts?

**Comment by sxa555** [comment]
For what it's worth I've been using an ODROID-XU4 for building arm32 stuff and it's noticeably quicker than a Pi3 for heavy stuff (2GB RAM and 8 cores (4 faster, 4 slower) - not compared with Pi4 yet though :-)
