### ISSUE TITLE
zos python problems causing build failures

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1855]
z/os has some problems with python, caused by recent installation of python36 for https://github.com/nodejs/build/issues/1674

@miladfar is looking into this and has identified some of the problems

**Comment by miladfarca** [comment]
Python3 on `zos13-s390x-2` is installed correctly but a dependency lib is missing form the `LIB PATH`, exporting the following fixes the issue (might need to add this to Jenkins):
```
export LIBPATH=/NODEJS2/python-2017-04-12-py36/python36/lib/
```

On `zos13-s390x-1`, python 3 executable is missing altogether under this directory:
```
/NODEJS2/python-2017-04-12-py36/python36/bin/
```
However python 2 is still available under:
```
/NODEJS2/python-2017-04-12-py27/python27/bin/python
```

**Comment by richardlau** [comment]
The only jobs running on z/OS are the libuv ones, where python is needed for gyp. Is libuv using a python3 compatible gyp (does one even exist) yet?

**Comment by sam-github** [comment]
@nodejs/node-gyp @nodejs/python

**Comment by cclauss** [comment]
nodejs/node-gyp#1793 is still blocking Python 3 compatibility.  There is https://github.com/refack/GYP which should work on Python 3 but that is not (yet?) our standard gyp.

**Comment by richardlau** [comment]
libuv doesn't embed a copy of gyp (the [build instructions](https://github.com/libuv/libuv#build-instructions) say to clone gyp from `https://chromium.googlesource.com/external/gyp`).

I can't see the configuration for https://ci.nodejs.org/view/libuv/job/libuv-test-commit-zos/ but based on the most recent runs it seems to be doing this:
```console
+ rm -rf build
+ mkdir build
+ cp -R /u/iojs/gyp build
```

no idea what version of gyp is in `/u/iojs/gyp`. In any case I imagine for now we want a working Python 2.7 on the z/OS systems to unblock the libuv builds.

cc FYI @nodejs/libuv

**Comment by richardlau** [comment]
Closing. The only builds we have currently running on z/OS are the libuv ones and libuv has dropped support for gyp so no longer requires Python. Prior to gyp being removed the z/OS libuv builds using gyp (and Python) were passing.
