### ISSUE TITLE
Investigate instability of node-test-node-addon-api-new nightlies on AIX

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1856]
When the nightly (morningly?) builds of https://ci.nodejs.org/job/node-test-node-addon-api-new/ fail, it always appears to be AIX.

From https://ci.nodejs.org/job/node-test-node-addon-api-new/:
- https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=aix61-ppc64/105/console
- https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=aix61-ppc64/99/console
- https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=aix61-ppc64/96/console

The above were all built on test-osuosl-aix61-ppc64_be-1, but that's because that job seems to be sticky to that specific machine, I don't see signs that Jenkins balances the job load (be-2 doesn't seem to have a single job in its history, when be-1 and be-3 have lots, https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-2/builds).

The errors on failure are always (that I've seen):
```
+ npm test
npm WARN npm npm does not support Node.js v13.0.0-nightly20190624d4549e75d4
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/

> node-addon-api@1.6.3 pretest /home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-addon-api
> node-gyp rebuild -C test

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
gyp ERR! System AIX 6.1
gyp ERR! command "/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-v13.0.0-nightly20190624d4549e75d4-aix-ppc64/bin/node" "/home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-v13.0.0-nightly20190624d4549e75d4-aix-ppc64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-C" "test"
gyp ERR! cwd /home/iojs/build/workspace/node-test-node-addon-api-new/nodes/aix61-ppc64/node-addon-api/test
gyp ERR! node -v v13.0.0-nightly20190624d4549e75d4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! Test failed.  See above for more details.
```

**Comment by mhdawson** [comment]
Update schedule to run 2 hours later, let's see if that fixes it.

**Comment by mhdawson** [comment]
It seems to be ok now, closing.
