### ISSUE TITLE
update node-test-commit-v8-linux to not overwrite make-v8.sh with a local copy

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1857]
Follow on from https://github.com/nodejs/build/issues/1536, cc @refack @mhdawson 

https://ci.nodejs.org/job/node-test-commit-v8-linux/ is copying over make-v8.sh from a local copy, with a note about upstreaming the changes.

But @refack already upstreamed the changes.

I modified the job config to not do the copy, I'll see how it goes: https://ci.nodejs.org/job/node-test-commit-v8-linux/2391/

I don't want to carry this hack over onto the new centos7 ppcle machines.

**Comment by mhdawson** [comment]
+1 if the file is the same.  I had thought that @refack had upstreamed.

**Comment by sam-github** [comment]
Also TBD: The test-osuosl-ubuntu1404-ppc64 have copies of the pkg-config files in /home/iojs/build-tools/pkg-config-files, but the are identical to the system .pc files in `/usr/lib/powerpc64le-linux-gnu/pkgconfig`, they can be removed and the jenkins and make-v8.sh scripts simplified.

**Comment by sam-github** [comment]
see: https://github.com/nodejs/node/pull/28458

**Comment by sam-github** [comment]
https://ci.nodejs.org/job/node-test-commit-v8-linux/2396/nodes=centos7-ppcle,v8test=v8test/console Its actually building v8, that's promising, will take a while to know if it suceeds in the test.

**Comment by sam-github** [comment]
been more than a month with no complaints, must have worked.
