### ISSUE TITLE
No pgrep on AIX

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1859]
This shows up on AIX in CI:

```console
22:06:11 + pgrep node
22:06:11 /tmp/jenkins372064123762390528.sh[28]: pgrep:  not found.
```

It passes anyway because the test is for output. Since no `pgrep` means no output, the job interprets that as "no stray `node` processes running" and thinks everything is OK.

I'm not sure if the answer is to install `pgrep` on AIX or if the answer is to rewrite the check to use `ps` and `grep` instead of `pgrep`. @nodejs/build-files @nodejs/platform-aix

**Comment by bnoordhuis** [comment]
I don't know if pgrep is available for AIX. Using plain grep is finicky because `grep -E node$` won't match on AIX and just `grep node` is kind of dangerous.

Perl to the rescue!
```
$ perl -MFile::Basename -e '
  my @r = ();
  for (qx[ps ax]) {
    my @F = split;
    push @r, $F[0] if $F[4] && basename($F[4]) eq "node"
  }
  print "@r\n" if @r
'
```

**Comment by Trott** [comment]
> I don't know if pgrep is available for AIX. Using plain grep is finicky because `grep -E node$` won't match on AIX and just `grep node` is kind of dangerous.

I don't think it's dangerous here as all we're doing is "check if there are any `node` processes and if so, assume they are left over from tests and that there is therefore a bug in the tests that leaves processes running". It doesn't actually *do* anything with those processes. The doing-something-about-it happens in the `Makefile`  but there it's `ps awwx | grep Release/node`. 

I'm not sure where `pgrep` is coming from. It's not in the `Makefile`. I imagine Jenkins config somewhere?

**Comment by richardlau** [comment]
> I'm not sure where `pgrep` is coming from. It's not in the `Makefile`. I imagine Jenkins config somewhere?

Yes:

![image](https://user-images.githubusercontent.com/5445507/60521632-81277e80-9cdf-11e9-9610-aba98177a8c7.png)

I don't know the history but I suspect it was copied from the job for another platform. It looks similar to https://github.com/nodejs/build/blob/master/jenkins/scripts/node-test-commit-diagnostics.sh -- I also don't know why it's not calling that script (with any appropriate platform specifics encoded in the script).

**Comment by mhdawson** [comment]
I'll confirm this was a copy from another job.

**Comment by Trott** [comment]
Ping! Should we remove `pgrep node || true`? Or maybe change it to something like `ps awwx | grep Release/node || true`?

**Comment by sam-github** [comment]
I tend towards the "if there is no problem, don't fix it" maintenance strategy. Is something not working? A leaking process is always a symptom of an earlier failure, isn't it?

I don't have access ATM, I'm on vacation without ssh keys, but if I had to fix I'd probably take @bnoordhuis ' perl script and stick it into /usr/local/bin (or some other AIX/ node-build specific path) under the name "pgrep".

**Comment by richardlau** [comment]
> 
> 
> I tend towards the "if there is no problem, don't fix it" maintenance strategy. Is something not working? A leaking process is always a symptom of an earlier failure, isn't it?
> 
> I don't have access ATM, I'm on vacation without ssh keys, but if I had to fix I'd probably take @bnoordhuis ' perl script and stick it into /usr/local/bin (or some other AIX/ node-build specific path) under the name "pgrep".

I'd suggest sticking it in this repository (so it is version controlled), calling it from `jenkins/scripts/node-test-commit-diagnostics.sh` and make the job call that script.

**Comment by sam-github** [comment]
Note that node-test-commit-aix is now using the precommit script:
```
curl https://raw.githubusercontent.com/nodejs/build/master/jenkins/scripts/node-test-commit-pre.sh | bash -xe
```

But the script is still using pgrep, @AshCripps is looking at fixing that.
