### ISSUE TITLE
Request temporary access to fedora-last-latest-x64

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#1861]
I'm trying to figure out why the libuv tests for this [PR](https://github.com/libuv/libuv/pull/2185) are [failing](https://ci.nodejs.org/job/libuv-test-commit-linux/1497/nodes=fedora-last-latest-x64/). Thanks

**Comment by mhdawson** [comment]
+1

**Comment by sam-github** [comment]
@santigimeno You have 3 keys at https://github.com/santigimeno.keys, which would you like added to test-rackspace-fedora27-x64-1?

**Comment by santigimeno** [comment]
@sam-github the first one should do it. Thanks!

**Comment by sam-github** [comment]
@santigimeno done, please post in this issue when no longer needed.

**Comment by santigimeno** [comment]
@sam-github I'm finished. Thanks!
Refs: https://github.com/nodejs/build/pull/1869

**Comment by sam-github** [comment]
Keys removed, thanks for letting me know.
