### ISSUE TITLE
Debian 7 (wheezy) on ARM troubles

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1867]
I have an ARMv7 machine to reprovision on Scaleway because it's got a problem with the debian9 image but unfortunately I can't get past the debian7 setup.

Wheezy has always been a problem for us because getting GCC 4.8 running on it is a nightmare. We migrated to Docker running on all our Raspberry Pi's and the Scaleway ARMv7 machines. On Scaleway we run `arm32v7/debian:wheezy-backports` images while on Raspberry Pi we run `resin/rpi-raspbian:wheezy`. In both of these cases we have problems because Wheezy is now deceased so the images don't work as-is because the repos have been moved to "archive" locations, so you need to mess with sources.list to make them work. In the Scaleway case we apply a hack to get GCC-4.8 running by pulling in the Raspbian Wheezy repo and grabbing 4.8 from there. It's about the only semi-sane way to get 4.8 on Wheezy but this has lead to our Node <10 ARMv7 binaries actually being compiled as ARMv6 because in Raspbian land, everything is ARMv6. We migrated to a cross-compiler to sort this our for Node >=10. On the Raspberry Pi Docker images they are Raspbian already so have 4.8, so it's a bit easier.

For Scaleway, the problem I'm encountering is that the Raspbian Wheezy repos stopped being updated _before_ the upstream Debian armhf repos, so they no longer combine nicely. When you pull things from the Raspbian repo you get dependency mismatches with the Debian repos and what's already on the base image (including critical OS libraries such as libc6). I've tried my best to force them to work together and override dependency mismatches but I don't think I'll ever have enough time to shave that particular yak.

For the Raspberry Pi's, I don't think I've rebuilt any of the Wheezy Docker images since Wheezy was properly shelved (or since the repo was moved to an archive). I'm concerned that I'm in for more yak shavery just to make them work but it's an unknown quantity at the moment.

We drew a line under Wheezy for Node >=10 and we no longer compile natively since then either, so this really only matters for Node 8. Unfortunately it matters a lot since we compile `armv6l` binaries on the Pi's using Wheezy Docker images.

So at this stage I think I want to propose that we entirely drop Scaleway Wheezy testing. This only impacts Node 8, we have slightly less coverage.

The other problem that this issue is a heads-up for is that we may have trouble the next time I need to reprovision a Pi that gets a Wheezy Docker image. If this includes one of the two release machines then that could be a big problem. Something to explore at a later date when forced I think.

**Comment by mhdawson** [comment]
> This only impacts Node 8, we have slightly less coverage.

With only ~5 months left in the LTS cycles for 8,  I think given the challenges it makes sense.

**Comment by BridgeAR** [comment]
This seems like it could be closed?
