### ISSUE TITLE
Request: Enable travis-ci for node-inspect

### ISSUE THREAD

**Issue by jkrems** [nodejs/build#1868]
Hey,

I'm trying to get the build of `node-inspect` back into shape and would love to use travis for it. Past instructions I could find (e.g. https://github.com/nodejs/admin/issues/149) mention updates to a file in the github-bot that no longer exists so I wanted to double-check before I move the repo out of the org and set up Travis that way.

Also, I tried following this guide and it seems outdated: https://github.com/nodejs/automation/blob/master/enable-travis-under-nodejs.md. The services section no longer allows updates (?) since Github really wants people to migrate to apps afaict.

**Comment by targos** [comment]
It's okay, we have the GitHub app. An org admin should enable the repo. I can't RN from my mobile phone

**Comment by targos** [comment]
I enabled it. Let me know if there are issues.

**Comment by jkrems** [comment]
Thanks! I'm definitely seeing travis builds. Status reporting isn't quite working but given the low frequency of changes that should be okay. Thanks again for the quick help!
