### ISSUE TITLE
libuv: cmake jobs to print output on test failure

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#1870]
At the moment, [if the tests fail on the libuv cmake jobs, it's not possible to find out which test/s failed](https://ci.nodejs.org/job/libuv-test-commit-linux-cmake/522/nodes=centos7-64/console). An option is running the tests with the `CTEST_OUTPUT_ON_FAILURE` env variable set:

```sh
CTEST_OUTPUT_ON_FAILURE=1 make test
```
Would it be possible to make this change?

**Comment by rvagg** [comment]
This is what libuv-test-commit-linux-cmake's script looks like now:

```
curl https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.tar.gz | tar xzf -

mv cmake-3.11.2-Linux-x86_64 cmake-bin/

mkdir -p out/cmake

cd out/cmake

$WORKSPACE/cmake-bin/bin/cmake -DBUILD_TESTING=ON $WORKSPACE

make -j

CTEST_OUTPUT_ON_FAILURE=1 make test
```
