### ISSUE TITLE
Request temporary access to centos7-64

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#1872]
Still investigating the [CI failures](https://ci.nodejs.org/job/libuv-test-commit-linux-cmake/523/nodes=centos7-64/console) in this [libuv PR](https://github.com/libuv/libuv/pull/2185). Thanks!

**Comment by sam-github** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by rvagg** [comment]
root@50.23.85.250 @santigimeno

**Comment by santigimeno** [comment]
The test passes on the `test-softlayer-centos7-x64-1` you have given me access to, but the test failed on the `test-rackspace-centos7-x64-1`. Could you give me access to it instead? Thanks!

**Comment by rvagg** [comment]
OK @santigimeno, test-softlayer-centos7-x64-1 is root@119.9.27.82 but be aware that both you and @addaleax now have access to the same machine for debugging so try not to step on each other's toes. Ref #1875.

**Comment by santigimeno** [comment]
@rvagg that should be no problem at all. I have confirmed that this box also has the `firewalld` service installed so there lies the problem. You can remove my keys. Thanks!

**Comment by rvagg** [comment]
sorry, meant to say "OK @santigimeno, test-rackspace-centos7-x64-1 is root@119.9.27.82", but I assume from your message that you're finished with that one too now?

let's work on removing firewalld if it's installed from centos[67] as a solution to these problems, we should revert https://github.com/nodejs/build/pull/1869 in the process too. Did you just add those rules to test-rackspace-centos7-x64-1 to solve it?

**Comment by santigimeno** [comment]
> Did you just add those rules to test-rackspace-centos7-x64-1 to solve it?

No I didn't.

> let's work on removing firewalld if it's installed from centos[67] as a solution to these problems, we should revert #1869 in the process too.

I was looking into this. Where is a good place to add this modification? I was thinking on the [baselayout role](https://github.com/nodejs/build/blob/master/ansible/roles/baselayout/tasks/main.yml) but I'm not sure.

**Comment by rvagg** [comment]
Well, there is ansible/roles/bootstrap/tasks/partials/fedora.yml and ansible/roles/bootstrap/tasks/partials/centos6.yml already. They disable selinux. Maybe we can shoehorn this into that spot even though it's not _technically_ a "bootstrap" activity. So maybe just make a centos.yml and edit that and fedora.yml to remove firewalld with failures acceptable.

**Comment by santigimeno** [comment]
> we should revert #1869 in the process too

BTW I can't see this commit in master :man_shrugging:

**Comment by rvagg** [comment]
@santigimeno ah right, yes, that's my fault, I merged locally but didn't get to pushing to master after realising it wasn't quite right. I left it dangling in an unrelated branch that's sitting @ https://github.com/nodejs/build/pull/1877 for now until I figured out what to do with it. But if we get some remove-firewalld changes in then I can just drop it entirely.

**Comment by santigimeno** [comment]
@rvagg ok. One last question, is there a reason why the `raw` module is used to install packages in those partial files instead of using the specific module (`package`, `yum`, etc.)?

**Comment by rvagg** [comment]
ah, yes, because they are bootstraps and are responsible for basic things like setting up python so the normal ansible tasks can run. I don't know for sure but I think you might have to stick to raw.

**Comment by santigimeno** [comment]
Opened https://github.com/nodejs/build/pull/1879/. PTAL. Thanks!
