### ISSUE TITLE
node-test-npm, is this job used? can I delete it?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1873]
https://ci.nodejs.org/job/node-test-npm

I'm currently running it, https://ci.nodejs.org/job/node-test-npm/37/, that its build 37 is suspicious, but perhaps its only run when npm is updated, @nodejs/npm, so that's why it is infrequent?

Its already failed  on https://ci.nodejs.org/job/node-test-npm/37/node=ubuntu1204-64/console

Context: it doesn't support centos7-ppcle, but I don't want to update it if the job is not used.

**Comment by richardlau** [comment]
(As an aside, I don't think anyone in `@nodejs/npm` are involved with npm anymore.)

**Comment by sam-github** [comment]
@nodejs/collaborators does anybody use this job? https://ci.nodejs.org/job/node-test-npm  If no one speaks up for it, it will be archived and eventually deleted.

**Comment by sam-github** [comment]
archived: https://ci.nodejs.org/job/archive-node-test-npm/

to be deleted sometime
