### ISSUE TITLE
node-test-known-issues, is this job used? can it be deleted?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1874]
quoting @richardlau 

> I do wonder if that job is still in-use. known_issues tests are run by default in the CI now for Node.js 10 (since 10.9.0, https://github.com/nodejs/node/pull/21910) and above. It doesn't look like that job is chained to any of the regular CI jobs (also indicated by the low build job numbers) and if someone needs to do one-off known_issues test runs they can always use https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/.

In agreement with @rvagg 's points about the CI being too ambitious to be tractable, I'd like to delete the job if its unused -- or prefix the job name with `archived-` to indicate it isn't used or maintained, or whatever the convention here is to clean up unused jobs.

**Comment by sam-github** [comment]
@Trott in particular, do you have an opinion?

**Comment by richardlau** [comment]
(Link to the job being discussed: https://ci.nodejs.org/job/node-test-known-issues/)

**Comment by Trott** [comment]
I have not used that job in a long time, if ever. I'm totally OK with it going away.

**Comment by sam-github** [comment]
I renamed it with an `archive-` prefix, and changed the description to

> run make/vcbuild test-known-issues -- to be deleted, see https://github.com/nodejs/build/issues/1874

I'm nervous to outright delete it, do we have ways of bringing them back if some infrequent user of the job panics?
