### ISSUE TITLE
Requesting access for addaleax to debug CI failures

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#1875]
Hi all, it would help me a lot if I could get temporary debugging access to one of the hosts on which https://ci.nodejs.org/job/node-test-pull-request/24483/ failed, because I’m stuck with local debugging. One of the node-test-commit-linux nodes would be ideal (ubuntu1604-64, debian9-64, debian8-64 and centos7-64-gcc6 all would be great), but I’m happy to take what I can get. :slightly_smiling_face: 

Thank you!

**Comment by mhdawson** [comment]
+1

**Comment by rvagg** [comment]
@addaleax I've put your keys onto those machines:

test-rackspace-centos7-x64-1 root@119.9.27.82
test-digitalocean-debian8-x64-1 root@159.203.103.52
test-digitalocean-debian9-x64-1 root@138.197.97.208
test-rackspace-ubuntu1604-x64-1 root@119.9.51.176

🖖 good luck

**Comment by addaleax** [comment]
Alright, learned what I needed to know and removed my SSH keys. Thanks!
