### ISSUE TITLE
nearForm benchmarking machines offline

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1878]
test-nearform_intel-ubuntu1604-x64-1 & test-nearform_intel-ubuntu1604-x64-2 are both unavailable and I can't connect to them via ssh. @jasnell @mcollina would you mind pinging someone at nearForm HQ about these machines please?

Ref: https://github.com/nodejs/node/pull/28846#issuecomment-515302869

**Comment by jasnell** [comment]
I've asked our infrastructure guru to take a look

**Comment by jasnell** [comment]
Ok, try again! They should be back up. Looks like it was an issue with our switch.

**Comment by rvagg** [comment]
thanks @jasnell

I've updated and restarted the machines, it's been a while since they were updated
