### ISSUE TITLE
GN needs an update on some hosts

### ISSUE THREAD

**Issue by targos** [nodejs/build#1881]
The `node-test-commit-v8-linux` job doesn't work with V8 7.7 because BUILD.gn uses a function that doesn't exist in earlier versions of GN.

GN should be updated on the following nodes:
![image](https://user-images.githubusercontent.com/2352663/62374292-fa62fd00-b53b-11e9-927b-6bf3097253dc.png)

Refs: https://ci.nodejs.org/job/node-test-commit-v8-linux/2440/

**Comment by rvagg** [comment]
How does one update GN? I don't see anything in our Ansible scripts for this.

**Comment by targos** [comment]
I don't know. On my machine it is done automatically when I execute gclient.

**Comment by miladfarca** [comment]
On Intel based machines GN is part of the v8 "depot_tools" and maintained by Google, this is not the case for ppc and s390 hence we build our own GN from source on daily basis for our internal builds. I will have a discussion with our team on how GN is maintained in Nodejs CI and if we need to export our binaries.

**Comment by sam-github** [comment]
I'm looking at this job for other reasons, I'll take a look at this. I think we hand-compile gn on the box, and stick it in a pre-determined place. I can probably update it. I'll look tomorrow.

**Comment by sam-github** [comment]
Anyone know how to get gn's version? The obvious candidates (-h, -v, -V, --version) don't work.

**Comment by sam-github** [comment]
@targos see above question, as well, what is the minimal version of gn required?

Building gn requires clang++ (it seems, though maybe I can hack the ninja buildfiles to use gcc), and I am not sure clang++ exists for ppc.

**Comment by miladfarca** [comment]
clang can be overridden by setting CC and CXX like this, (using gcc 6 in this example):
```
git clone https://gn.googlesource.com/gn
cd gn
CC=gcc-6 CXX=g++-6 python build/gen.py
ninja -C out/
```

Also the version can be fetched using `--version`.

**Comment by sam-github** [comment]
```
$ ./build-tools/gn --version
UNKNOWN
```

Maybe just a build problem? I assumed it was an unknown option, but maybe its an unknown version.

Thanks for the hint, I switched to gcc 6 from devtoolset and gn is building.

**Comment by sam-github** [comment]
On test-osuosl-centos7-ppc64_le-1:
```
$ /home/iojs/gn/out/gn --version
1618 (f0a6900)
```

So, I can replace the existing gn with this one, but I'll need a plan to show its compatible, that it doesn't break any builds, and I'm not sure what builds use it. I'll do some poking around tomorrow.

**Comment by sam-github** [comment]
https://ci.nodejs.org/job/node-test-commit-v8-linux/2456/

I updated the gn version used, seems to work fine. @targos want to try what you were doing again? I pressed rebuild on https://ci.nodejs.org/job/node-test-commit-v8-linux/2440/, which kicked off  https://ci.nodejs.org/job/node-test-commit-v8-linux/2457/, maybe that will re-do what you were trying.

**Comment by sam-github** [comment]
@nodejs/v8 @nodejs/v8-update What would it take to get `gn` binaries upstreamed into google for ppc and s390x?

**Comment by sam-github** [comment]
I also asked gn-dev, I'm not sure who the right contacts are, hopefully someone will know. Maybe @ofrobots?

https://groups.google.com/a/chromium.org/forum/#!topic/gn-dev/MPE7anXl5iQ

**Comment by sam-github** [comment]
Poking around, it appears @hashseed may know something about what is required.

**Comment by targos** [comment]
@sam-github thank you. Here's a new build that's looking good https://ci.nodejs.org/job/node-test-commit-v8-linux/2462/

**Comment by sam-github** [comment]
OK, closing, open again if I misunderstand.
