### ISSUE TITLE
Allow for parallel CITGM

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1882]
I think we should allow 2 - 3 in parallel... releases are potentially blocked by CITGM backlog

**Comment by targos** [comment]
I think it was made sequential because for some platforms we don't have more than 2 hosts and CITGM was blocking other jobs

**Comment by richardlau** [comment]
These are the current config settings re. throttling:
![image](https://user-images.githubusercontent.com/5445507/62564024-11775700-b87c-11e9-9d13-3eaa22dadcd0.png)
