### ISSUE TITLE
Request access: debian9-64

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1883]
Context: https://github.com/libuv/libuv/pull/2408

The test from that PR fails on exactly one buildbot, debian9-64. I would like to investigate why.

I'd like strace if it isn't already installed.

**Comment by rvagg** [comment]
@bnoordhuis root@169.60.150.91 👍

**Comment by bnoordhuis** [comment]
Figured it out, thanks Rod! Should I remove strace again?

**Comment by sam-github** [comment]
Presence of strace shouldn't hurt anything.

@bnoordhuis Consider requesting access to join the build WG. It comes with zero responsibilities (specifically, meeting attendance is not expected), but you would have permanent access to trouble shoot on ci machines.

In the meantime, if you are done with the machine, you can remove your ssh key and close this issue.

**Comment by bnoordhuis** [comment]
Done, thanks!
