### ISSUE TITLE
nodejs.org: specify charset=utf-8 in nginx

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/build#1896]
Something like https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/media_types/character_encodings.conf

**Comment by nschonni** [comment]
I guess that would go in here https://github.com/nodejs/build/blob/master/setup/www/tasks/nginx.yaml

**Comment by rvagg** [comment]
what problem are we solving here?

**Comment by XhmikosR** [comment]
This was the de facto solution in the old days for sure. IE had some issues and retriggered the request if charset wasn't specified. Pagespeed insights warned for this BTW.

That being said, I personally always do this even today. Even if an HTML file is missing a meta charset, this would make sure everything displays correctly. The same goes for CSS and JS files.

**Comment by rvagg** [comment]
I guess a PR would be acceptable if you can confirm first that it does what's needed (I don't really like deploying untested nginx updates to the website, we've done that a bit too often)

**Comment by XhmikosR** [comment]
Happy to do it, but I'm not familiar with the codebase so I think it'd be better if someone else tackled this.
