### ISSUE TITLE
TODO: nodejs.org SSL certificates action required

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1901]
We have 3 months left on our *.nodejs.org comodo certificates that we're using on (almost?) every *nodejs.org domain. We need to decide whether to renew or switch to a free alternative.

I can't recall off the top of my head all of the complications but I think that having a wildcard allowed us to just slap it on everything we needed https for rather than wrestling with LetsEncrypt for every individual domain (it can be a pain to set it up, especially when you're managing multiple domains). We put it on our server, for https that it exposes directly and for communication with Cloudflare. And we put it on Cloudflare to its connections to end-users use our certificate.

If we switch, we're going to need to do LetsEncrypt on our own managed servers (including ci.nodejs.org, ci-release.nodejs.org and a bunch of others that are exposed directly or talk to Cloudflare), and then use Cloudflare issued certificates for sites that are exposed through there.

We switched https://dist.libuv.org/ to LetsEncrypt when its original certificate expired and that's going fine, so we have some infra in place to make this work already, it's not a start-from-scratch deal.

**Comment by nschonni** [comment]
I think Let's Encrypt also supports wildcard certs now https://www.bleepingcomputer.com/news/security/lets-encrypts-now-offers-free-wildcard-ssl-certificates-using-acmev2/ (but I've set that up)

**Comment by brianwarner** [comment]
Thanks for bringing this up, @rvagg.  It seems like a multi-year wildcard cert might be a good option here.

@mhdawson this might be a good thing to bring up in the next board meeting, not just for *.nodejs.org, but as an option for all domains managed by the Foundation.

**Comment by mhdawson** [comment]
@rvagg I'm thinking it would be easiest if we just get multi-year wildcard certs and look at how we have the Foundation manage renewals etc.  Seems like the lowest "people" time cost and would be less work for the build WG.  Does that make sense to you?

**Comment by rvagg** [comment]
@mhdawson :thumbsup: that would make it simpler on the technical front, as long as you're volunteering to manage it, because IMO it's less simple on the organisational front. Convolution and the inability to get back 100% of what I spend made me vow not to deal with the expenses process of the LF (last time I spent on certs I got back 50% of what I forked out). Last renewal of this I might have even got someone from finance @ the LF to log in to GoGetSSL and pay for what I'd already set up, so that might be an option if you have the stomach for managing it.
GoGetSSL credentials are in secrets/build/infra/admin_logins.md. It's not necessary you buy through them but they were a cheap way of getting COMODO certs.

**Comment by brianwarner** [comment]
@rvagg Yes, we can get these directly, pending approval from the OpenJS Foundation Board.

**Comment by mhdawson** [comment]
I'll talk to @brianwarner as to what we can do to simplify the renewal process.

**Comment by brianwarner** [comment]
It should be pretty straightforward... LF IT will get the cert, and then pass it along to you.  :-)

**Comment by mhdawson** [comment]
@rvagg can you confirm that this is the option we should chose 
![image](https://user-images.githubusercontent.com/9373002/65047765-01e63600-d931-11e9-9452-d0d23e681990.png)

If so I'll give Brian the login info so he can login in and order a renewal.  

I assume that we'll have the remaining 2 months to do the actual switch between the new and old certs?

**Comment by rvagg** [comment]
Yep (TIL Comodo changed their name). If you log in to the account using the credentials in secrets and go to "SSL Certificates" you should see it and an option to renew:

<img width="877" alt="Screen Shot 2019-09-18 at 1 30 52 pm" src="https://user-images.githubusercontent.com/495647/65105570-b27b3500-da18-11e9-8583-314c719f3d5a.png">

And yes, we can switch any time between getting the new and the old expiring.

**Comment by mhdawson** [comment]
@rvagg ok I'll give Brian the login info so he can do the renewals.  How many different places do we need to update/install the certs once we get them (or is there a doc which covers that?).  I'm wondering if you want to do the updates or if maybe we should do it together to get me up to speed on that as well unless it's easy/low risk and a document that I can use to make sure I've done it in all the right places.

**Comment by rvagg** [comment]
top of my head:

* cloudflare
* direct.nodejs.org and backup-www.nodejs.org (or whatever it's called) - we https between them and cloudflare, they also host multiple subdomains which may not be proxied through CF
* ci.nodejs.org and ci-release.nodejs.org

**Comment by mhdawson** [comment]
Ok shared info with Brian, he will get the certificates renewed.

**Comment by sam-github** [comment]
`Expires On	Tuesday, 18 January 2022 at 15:59:59` is the current https://nodejs.org cert, so it looks like this was done.

I'll close, but if I misunderstand, and it _wasn't_ done, the issue was opened Aug 25, 3 months later is Nov 25... and that is real soon now, and we might be in trouble.

**Comment by rvagg** [comment]
Forgot to do do ci.nodejs.org and ci-release.nodejs.org even though I mentioned them above. They've been done now, thanks Myles for pointing them out.
