### ISSUE TITLE
Add task to build asan

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/build#1906]
There is current a issue in asan build, fixed by https://github.com/nodejs/node/pull/29383.

I wonder if Jenkins can add a job to prevent future regression.
Maybe just run the build first (see https://github.com/nodejs/node/pull/29383#issuecomment-527038615).
```bash
./configure --debug --enable-asan
make -j4
```

**Comment by rvagg** [comment]
Sounds like a job for one of the sharedlibs containers, same way as we do debug builds. Maybe we should add a clang+Linux combo while we're at it since we don't cover that at all either.

**Comment by gengjiawen** [comment]
Already in github action.
