### ISSUE TITLE
Create test script to verify redirects don't break stuff

### ISSUE THREAD

**Issue by fhemberger** [nodejs/build#191]
With the huge amount of redirects from the old nodejs.org website, it can become quite tedious to check for possible side effects when changing the server config.

Current examples:
- https://github.com/nodejs/new.nodejs.org/issues/124
- https://github.com/nodejs/new.nodejs.org/issues/125

Cases which need to be tested:
- http/https links to dist tarballs
- http/https links to old windows x32/x64 builds
- http/https links to new windows x32/x64 builds (different file name/directory)
- http/https links to dist/latest/, dist/latest-v0.10.x/, dist/latest-v0.12.x/  
- http/https links to previous versions of the api docs
- http/https links for [subdomain].nodejs.org
- …

What would be the preferred way to create such a test suite? Shell script with wget/curl checking for response codes and redirect locations? Something like [supertest](https://www.npmjs.com/package/supertest)?

**Comment by leachiM2k** [comment]
+1

**Comment by fhemberger** [comment]
Maybe it would also be a good idea to put that long list of redirects into an external file and include it into  nginx.conf, to keep the main config short and clean.

**Comment by Trott** [comment]
@nodejs/build @fhemberger Should this remain open?

**Comment by fhemberger** [comment]
@Trott I still think this would be useful in the light of the planned relaunch, but in the end it depends on the needs of the build team.

**Comment by maclover7** [comment]
Closing for now as something that would be nice to have, but not currently within our means. If someone wants to tackle this, please feel free to reopen.
