### ISSUE TITLE
ci,libuv: run `make distcheck`

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1910]
https://github.com/libuv/libuv/pull/2444#pullrequestreview-285193247

> Can we get some of the buildbots using `make distcheck` instead of just `make check`

I'm sure the answer is 'yes' but I don't think I have the permissions to change that.

**Comment by rvagg** [comment]
@nodejs/build any objections to giving @bnoordhuis @nodejs/jenkins-admins privs? give access to edit ci.nodejs.org jobs.

I might give this one a try but "some of the buildbots" doesn't give me enough specificity about what to do.

**Comment by sam-github** [comment]
No objections from me.

**Comment by Trott** [comment]
Fine by me too.

**Comment by rvagg** [comment]
ok, easy then, would one of you two mind editing the team?

**Comment by bnoordhuis** [comment]
> I might give this one a try but "some of the buildbots" doesn't give me enough specificity about what to do.

I think it'd be alright to change all uses of `make check` to `make distcheck`.

**Comment by richardlau** [comment]
While editing https://ci.nodejs.org/job/libuv-test-commit-linux/ for https://github.com/nodejs/build/issues/2174 I tried replacing `make check` with `make distcheck` but this seems to introduce test failures: https://ci.nodejs.org/job/libuv-test-commit-linux/1824/

```
not ok 48 - fs_copyfile
# exit code 134
# Output from process `fs_copyfile`:
# Assertion failed in ../../test/test-fs-copyfile.c on line 156: r == 0
...
not ok 169 - pipe_connect_to_file
# exit code 134
# Output from process `pipe_connect_to_file`:
# Assertion failed in ../../test/test-pipe-connect-error.c on line 53: status == UV_ENOTSOCK || status == UV_ECONNREFUSED
```
`make check` passed all tests: https://ci.nodejs.org/job/libuv-test-commit-linux/1825/
