### ISSUE TITLE
FYI - Rackspace outage Sep 26 2019

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1911]
Maintenance window
Planned start date and time:  2019-09-26 02:00 CEST
Planned end date and time:  2019-09-26 04:00 CEST

Expected disruption
Disruption is not anticipated to last longer than one hour.

Maintenance info:
Rackspace Network Services will be performing a disruptive maintenance in our FRA data center to swap out an Public switch between 02:00 and 04:00  CEST on September 26, 2019. We have taken precautions in preparation for this maintenance and do not anticipate a disruption lasting longer than one hour. Customers affected by this maintenance will be notified by a MyRackspace ticket.
We apologize for any inconvenience.  If you have any questions, please contact your support team.

**Comment by joaocgreis** [comment]
On 9 September 2019, you received a notification regarding a scheduled maintenance in the FRA Region. This communication was sent to you in error.

The maintenance will only affect customer instances in the FRA Region.
