### ISSUE TITLE
New strategy for managing, sharing and documenting release keys needed

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1913]
Arising from @canterberry's comments @ https://github.com/nodejs/node/issues/709#issuecomment-530606948

I haven't really paid too much attention to the SKS issues except that [OpenPGP mentioned it](https://keys.openpgp.org/about/news#2019-06-12-launch) the other day, but it seems like we need a new strategy for distributing our release keys for verifying signatures and therefore shasums of downloads.

This is a tracking issue that we could use for discussion and just to make sure it doesn't get fully lost. Someone needs to take the horns of this bull and come up with a strategy, even if that's just putting the keys into the nodejs/node codebase and recommending them from there, or getting all releasers keys onto the new OpenPGP server. Docs will need to change too.

@nodejs/build @nodejs/releasers @nodejs/tsc (FYI)

**Comment by MylesBorins** [comment]
I'm a big +1 on documenting releasers + keys in the repo. We already do so in the readme. We could make adding / removing the keys part of the process of adding / removing releasers.

**Comment by rvagg** [comment]
I'm a little concerned about them going into nodejs/node given the very large collaborator group and the pace of change which means that very few people (if anyone?) see _everything_ that goes in. An alternative might be dedicated nodejs/keys that's got very restricted write access, TSC-only probably.

**Comment by canterberry** [comment]
There is already a [nodejs/Release](https://github.com/nodejs/Release) repo. This repo is pretty sparse and updated relatively infrequently. Would that be a reasonable place to keep the keys of the authorized release team? I know I find myself checking there first whenever I want to see who the authorized releasers are.

**Comment by rvagg** [comment]
might work but I think it has at least 2 additional teams that have access, Releasers (which is fine, it's their keys anyway), and LTS, or maybe it's called Release now (the repo used to be called LTS). That's still a broad group that could be pared back; but maybe it's time to revisit the purpose of that repo and who runs it.

**Comment by MylesBorins** [comment]
Taking to TSC seems reasonable to me

**Comment by richardlau** [comment]
This appears to have stalled? The last comments suggest taking to @nodejs/tsc but that doesn't appear to have happened (unless there were private discussions).

I'll tag `tsc-agenda` -- Maybe this falls under the repsonsibilities delegated to the [Release WG](https://github.com/nodejs/release)? @nodejs/tsc This issue relates to https://github.com/nodejs/node/issues/29531 and relates to the current method of distributing the @nodejs/releasers keys used to sign releases via the SKS keyserver network being no longer being viable. The proposed solution is to publish the keys somewhere under our control.
- https://github.com/nodejs/node/issues/29531 proposes adding them to the core repository, https://github.com/nodejs/node/.
- https://github.com/nodejs/build/issues/1913#issuecomment-530614328 proposes adding them to https://github.com/nodejs/Release.
- The recommendation in this issue appears to have coalesced around transferring the work done by @canterberry in https://github.com/canterberry/nodejs-keys into the organization with appropriate restrictions on write access.

**Comment by richardlau** [comment]
ping @nodejs/tsc

**Comment by mcollina** [comment]
I'm +1 on the approach @canterberry is proposing.

**Comment by mhdawson** [comment]
Discussed in TSC meeting. @BethGriggs will add to agenda for Release WG and come back with a recommendation.

**Comment by sam-github** [comment]
I'm fine with the canterberry approach, the Release WG's recommendation is fine by me.

**Comment by BethGriggs** [comment]
We [discussed this in the release meeting today](https://github.com/nodejs/Release/blob/master/doc/meetings/2019-12-05.md#nodejsbuild) - we were all +1 on the dedicated "nodejs-keys" repository approach.

**Comment by sam-github** [comment]
Should `build-agenda` be removed? The discussions all seemed to point towards an agreed approach, now it just has to be taken up by someone.

It doesn't look like anything needs to be resolved.

**Comment by sam-github** [comment]
And if the ask is to move https://github.com/canterberry/nodejs-keys into the nodejs/ org, follow the procedure described in  https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories

@canterberry Open an issue as described in above link, reference this, it should get approved pretty quickly.

**Comment by richardlau** [comment]
https://github.com/nodejs/admin/issues/456 has been opened.
