### ISSUE TITLE
Add job to test configure

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/build#1914]
Related: https://github.com/nodejs/node/pull/29414.
Just to make sure configure works as expected, no need to build.
Such as
```bash
./configure --ninja
```

cc @targos

**Comment by rvagg** [comment]
we could probably pull that off with a sharedlibs docker container. What would we be testing for? exit code or is there something else we can use to confirm success? if you can express it in bash that would be handy too.

**Comment by rvagg** [comment]
^ fwiw we do a bit of TAP output with bash in some of our tests that confirm various build properties, like when we compile with a shared openssl library we run `process.versions` and confirm that we got what we compiled and then echo some TAP output to stdout which is picked up Jenkins nicely.

**Comment by targos** [comment]
I'm not sure we can really do it. Sure, we can test for --ninja, but why not other flag combinations? It's not possible to cover everything and people using specific combinations usually find problems soon enough.

**Comment by gengjiawen** [comment]
> I'm not sure we can really do it. Sure, we can test for --ninja, but why not other flag combinations? It's not possible to cover everything and people using specific combinations usually find problems soon enough.

Yeap, the key is to test frequently used script. But should we do a poll in Node.js collaborators ?

**Comment by sam-github** [comment]
Added `help wanted`. Also, a suggestion that if someone does do that, that it be PRed into nodejs/node as a test target (so it can be developed and trouble-shooted outside of CI).

**Comment by patrickhousley** [comment]
If I am reading the code correctly, it looks like there is already a test target `tooltests`. Changing that to `@$(PYTHON) -m unittest discover -s ./test/tools` and renaming the exists test to use underscores will result in being able to run all python tests in the test/tools directory in one target. I can PR this in if that works for you @sam-github

**Comment by sam-github** [comment]
@patrickhousley That tests the stuff in tools/  or in test/tools.... how is that related to https://github.com/nodejs/build/issues/1914#issue-492552817 ? Its `./configure --ninja` and the like that were requested to be tested.

**Comment by patrickhousley** [comment]
Sorry, just getting started with the project here. The tests in `test/tools` test tools used to build the project so it seemed like the best place to put new test cases for `configure` or any of the other build tools/scripts.

**Comment by patrickhousley** [comment]
Am I over thinking this maybe? Should the test be as simple as running `./configure --ninja` and testing the exit code? Would there be any concern with `configure.py` actually writing to the workspace?

**Comment by gengjiawen** [comment]
> Am I over thinking this maybe? Should the test be as simple as running `./configure --ninja` and testing the exit code? Would there be any concern with `configure.py` actually writing to the workspace?

I think just test `./configure --ninja` should be okay.

**Comment by gengjiawen** [comment]
close in favor of https://github.com/nodejs/node/issues/29415.
