### ISSUE TITLE
Show envinfo before build

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/build#1915]
Maybe using `npx tabrindle/envinfo`, maybe customize it.

Possibly add to https://raw.githubusercontent.com/nodejs/build/master/jenkins/scripts/node-test-commit-pre.sh.

Sample out looks like
```console
  System:
    OS: Linux 4.15 Ubuntu 19.10 (Eoan Ermine)
    CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Memory: 22.45 GB / 68.69 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
  Managers:
    Apt: 1.9.2 - /usr/bin/apt
    pip3: 18.1 - /usr/bin/pip3
  Utilities:
    CMake: 3.13.4 - /usr/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.2.1 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
    Clang: 9.0.0-+rc2-1~exp1 - /usr/bin/clang
  IDEs:
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.3 - /usr/bin/bash
    Perl: 5.28.1 - /usr/bin/perl
    Python: 2.7.16+ - /usr/bin/python
    Python3: 3.7.4 - /usr/bin/python3
    R: 3.6.1 - /usr/bin/R

```

**Comment by rvagg** [comment]
`npx tabrindle/envinfo` before build is not an option, we don't keep a `node` on the build machines. I'm also not keen on pulling in some arbitrary utility from npm on every test so if we can avoid `npx` even after build that might be best. It's just another vector to get code onto our test infrastructure that we have to care about. We do run scripts from `curl` from this repo, so if you want to add something in here we could go with that maybe? Probably won't be as sophisticated as that output above.

**Comment by targos** [comment]
I'm in favor of printing something like this on every build machine. I often need to know the version of the compiler toolchain and AFAIK we can't do it without ssh-ing into the machines

**Comment by gengjiawen** [comment]
> I'm in favor of printing something like this on every build machine. I often need to know the version of the compiler toolchain and AFAIK we can't do it without ssh-ing into the machines

Same here, I want to know the Xcode version on some machine.
