### ISSUE TITLE
Strange issue with node build ending early

### ISSUE THREAD

**Issue by mscdex** [nodejs/build#1916]
https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/446/console

The PR being benchmarked here only made changes to two JS files. The node compilation step after checkout is only lasting a short time and then failing because the PR patches don't apply (which doesn't make sense). Is there a problem with free disk space or something wrong with the working directory that would be causing this?

**Comment by mhdawson** [comment]
I assume this line just needs to be changed from

```
       curl https://patch-diff.githubusercontent.com/raw/nodejs/node/pull/${PULL_ID}.patch|git apply
```

to

```
       curl https://patch-diff.githubusercontent.com/raw/nodejs/node/pull/${PULL_ID}.patch|git apply -3
```

I can submit a PR to do that if @mscdex can test after it lands.

**Comment by addaleax** [comment]
@mhdawson Yeah, that seems about right.

**Comment by mhdawson** [comment]
PR https://github.com/nodejs/benchmarking/pull/287

**Comment by mhdawson** [comment]
In terms of testing I think the change is small enough that I can just land and then start a run to make sure it's ok. Then back out if not.  @mscdex as one of the common users any objections to that?

**Comment by sam-github** [comment]
https://github.com/nodejs/benchmarking/pull/287 landed
