### ISSUE TITLE
access for @victorgomes to osx build bot

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1920]
They are chasing down the issues in https://github.com/nodejs/node/pull/29493 and want to see if they can get a patch together to get V8 7.8 working on our build machines.

**Comment by sam-github** [comment]
@MylesBorins Is the criteria met? 

- Does the scope and size of the need justify providing access.
- Is the individual a collaborator. If so then access should be allowed provided the first point is satisfied.
- Length and consistency of involvement with Node.js working groups and/or community.
- Consequences to the individual in case of misbehaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way ?
- Are there collaborators who work with the individual and can vouch for them.

From https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md

**Comment by sam-github** [comment]
@victorgomes

**Comment by MylesBorins** [comment]
* Does the scope and size of the need justify providing access.

This is to unblock the landing of V8 7.8 for Node.js 13. The work should be completed in less than a week.

* Is the individual a collaborator. If so then access should be allowed provided the first point is satisfied.

They Are not

* Length and consistency of involvement with Node.js working groups and/or community.

They are a a member of the V8 team, who was requested to handle this problem after the TSC meeting we had yesterday

* Consequences to the individual in case of misbehaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way ?

They are an employee of Google. Misbehavior would be a risk to their employment.

* Are there collaborators who work with the individual and can vouch for them.

I do

**Comment by sam-github** [comment]
That's strong enough a case I would add access immediately, except I don't have any idea how to access the OS X CI machines, and can't find any docs on them in nodejs/build. ssh didn't work, but that's not a surprise.

@nodejs/platform-macos  @nodejs/build Anyone have any ideas?

**Comment by mhdawson** [comment]
@sam-github ssh should work, let me try.

**Comment by mhdawson** [comment]
It works for our mac stadium 10.10 machines with this entry in the ssh config file

```
Host test-macstadium-macos10.10-x64-1
  HostName 207.254.58.162
  Port 10005
  IdentityFile ~/.ssh/nodejs_build_test
  User administrator
```

I've tried with `test-requireio-osx1010-x64-1`, which I think the config entry should be the following based on: https://github.com/nodejs/build/pull/1890/files.

```
Host test-requireio-osx1010-x64-1
  HostName 192.168.2.210
  IdentityFile ~/.ssh/nodejs_build_test
  User iojs
  ProxyCommand ssh -i ~/.ssh/nodejs_build_test -p 2222 jump@vagg-arm.nodejs.org nc -q0 %h %p
```

@rvagg I still can't connect with this entry, can you see what I've got wrong?


```
user1@user1-lbuntu:~/.ssh$ ssh test-requireio-osx1010-x64-1
ssh_exchange_identification: Connection closed by remote host
```

**Comment by mhdawson** [comment]
@MylesBorins was test-requireio-osx1010-x64-1 chosen for a specific reason or would be ok ? test-macstadium-macos10.10-x64-1

**Comment by sam-github** [comment]
Like @mhdawson, I can ssh into test-macstadium-macos10.10-x64-1, but not test-requireio-osx1010-x64-1:
```
ssh -vvv test-requireio-osx1010-x64-1
OpenSSH_7.9p1 Ubuntu-10, OpenSSL 1.1.1b  26 Feb 2019
debug1: Reading configuration data /home/sam/.ssh/config
debug1: /home/sam/.ssh/config line 17: Applying options for *
debug1: /home/sam/.ssh/config line 802: Applying options for test-requireio-osx1010-x64-1
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolve_canonicalize: hostname 192.168.2.210 is address
debug1: Executing proxy command: exec ssh -i ~/.ssh/ansible_ssh_private_key_file -p 2222 jump@vagg-arm.nodejs.org nc -q0 192.168.2.210 22
debug1: identity file /home/sam/.ssh/id_rsa type 0
debug1: identity file /home/sam/.ssh/id_rsa-cert type -1
debug1: identity file /home/sam/.ssh/nodejs_build_test type -1
debug1: identity file /home/sam/.ssh/nodejs_build_test-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9p1 Ubuntu-10
ssh_exchange_identification: Connection closed by remote host
```

**Comment by MylesBorins** [comment]
Any Mac machine works

**Comment by sam-github** [comment]
@victorgomes which of your keys would you like me to use? there are three at https://github.com/victorgomes.keys

**Comment by victorgomes** [comment]
@sam-github I will use the last ssh key (ending with oyUAw==).

**Comment by rvagg** [comment]
Sorry, the requireio one is intentionally offline. Can be put back into service if needed but the macstadium ones seem to be going well for us.

**Comment by Trott** [comment]
Totally-unnecessary pile-on +1 from me.

**Comment by sam-github** [comment]
@victorgomes use this config,with identity replaced with whatever yours is:
```
Host test-macstadium-macos10.10-x64-1 
  HostName 207.254.58.162
  IdentityFile ~/.ssh/nodejs_build_test
  User administrator
  Port 10005
```

Ping here when you are done and someone will remove your key (or you can remove the key then close this).

**Comment by victorgomes** [comment]
@sam-github Thanks. I will tell you when we're done.

**Comment by MylesBorins** [comment]
@mhdawson which machine do we use to build 12.x? I'm guessing it isn't 10.10... should we have given access to one of the test-macstadium-macos10.12-2 machines?

**Comment by targos** [comment]
@MylesBorins releases of 12.x are built with 10.11 machines.

**Comment by MylesBorins** [comment]
ok great. @mhdawson can we get @victorgomes access to the 10.11 machines please?

**Comment by sam-github** [comment]
@MylesBorins @victorgomes Added your key to test-macstadium-macos10.11-x64-1, removed it from test-macstadium-macos10.10-x64-1

```
Host test-macstadium-macos10.11-x64-1
  HostName 207.254.58.162
  IdentityFile ~/.ssh/nodejs_build_test
  User administrator
  Port 10003
```

**Comment by MylesBorins** [comment]
We got a working build. Feel free to remove access and close issue

**Comment by sam-github** [comment]
keys cleaned up, thanks @victorgomes
