### ISSUE TITLE
FYI - Enable travis for tap2junit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1924]
Similarly to https://github.com/nodejs/build/issues/1899 endable travis. Since we've not had objections in the past I'm going to go ahead and do it. 

If anybody objects I'll go back and disable. Unless there are objections I'll close this in a week.

**Comment by richardlau** [comment]
No objection, but does this sort of issue belong here in build or should it be in admin?

**Comment by mhdawson** [comment]
@nodejs/tsc @nodejs/community-committee thoughts.  Should this issue be in admin instead?

**Comment by Trott** [comment]
> @nodejs/tsc @nodejs/community-committee thoughts. Should this issue be in admin instead?

Yes. GitHub administration goes in the admin repo.

**Comment by mhdawson** [comment]
Replaced by https://github.com/nodejs/admin/issues/414
