### ISSUE TITLE
can I have access to ci-release?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1926]
> sam-github is missing the Overall/Read permission

on https://ci-release.nodejs.org/

Note that I already have ssh access to the release machines, or at least, the IBM platforms (I've never tried any others).

I'd like an easy way to see if jenkins jobs are currently running while doing troubleshooting and machine maintenance.

**Comment by mhdawson** [comment]
We asked for got/approval to give @sam-github ssh access in an earlier issue.  This would avoid me having to help @sam-github when necessary so I'm in favor.

**Comment by rvagg** [comment]
+1

**Comment by mhdawson** [comment]
@rvagg any thoughts on the best way to give @sam-github access.  If we want to limit it to ci-release I can just add him in specifically.

**Comment by rvagg** [comment]
@mhdawson I'm fine if you want to add him to jenkins-release-admins. Or if you have another suggestion?

**Comment by mhdawson** [comment]
@rvagg that works for me.  Added.

**Comment by sam-github** [comment]
Thanks, I can see the builds.
