### ISSUE TITLE
Switch coverage.nodejs.org to an HTML table

### ISSUE THREAD

**Issue by nschonni** [nodejs/build#1938]
The currently styling can probably be maintained, but this is better for accessibility and semantics.

https://github.com/nodejs/build/blob/238909645ec03bb9167271cb8b94b9fba2c84f96/jenkins/scripts/coverage/generate-index-html.py#L80-L101

If the preference is to keep the divs, then adding aria would be the alternate.

**Comment by richardlau** [comment]
I'm not sure why we switched from tables to divs in https://github.com/nodejs/testing/pull/41.

**Comment by nschonni** [comment]
Looks like it might have been to add a mobile experience, but I'm not sure how important that is for this data, vs. just a scrolling table
