### ISSUE TITLE
Add difference to CITGM output

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1944]
Right now CITGM shows +-n failures when finishing. The comparison is with the former run. Would it be possible to actually show the newly failed and newly passed entries? That would be an immense help while checking the results!

Another improvement would be to compare the diff with the former run that had the same base branch. That way major releases would not interfere. As an example: master has 30 failures. v10.x gets a new release and it has 10 failures. It now shows -20 failures. Now we run another CITGM against master and it has the same 30 failures as before but it highlights 20 new failures. At least that's the case as far as I know. Ideally that could be deactivated with a checkbox.

Ref: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2028/

**Comment by richardlau** [comment]
> 
> 
> Right now CITGM shows +-n failures when finishing. The comparison is with the former run. Would it be possible to actually show the newly failed and newly passed entries? That would be an immense help while checking the results!
> 

Sort of, but not in a particular nice way. And not as neatly summarised in one place as you might like.

<details>
<summary>For https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2028/ for example (multiple images)</summary>

![image](https://user-images.githubusercontent.com/5445507/66151832-0472ac00-e610-11e9-9689-cf327cb9ea59.png)
![image](https://user-images.githubusercontent.com/5445507/66151924-34ba4a80-e610-11e9-9370-4892cd234a1e.png)
![image](https://user-images.githubusercontent.com/5445507/66151992-5ca9ae00-e610-11e9-8769-7f52264b954d.png)
![image](https://user-images.githubusercontent.com/5445507/66152021-6c28f700-e610-11e9-9ec9-11a4b82e61d6.png)
![image](https://user-images.githubusercontent.com/5445507/66152080-937fc400-e610-11e9-808e-a545a1c63e43.png)
</details>

Also for an individual test you can view history:
![image](https://user-images.githubusercontent.com/5445507/66152436-5b2cb580-e611-11e9-83bb-d861510f3441.png)
[![image](https://user-images.githubusercontent.com/5445507/66152470-6f70b280-e611-11e9-96bb-69c6baecf63f.png)](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2028/nodes=centos7-ppcle/testReport/(root)/citgm/spawn_wrap_v1_4_3/history/)

but I don't know of a way of getting a summarised view.

> Another improvement would be to compare the diff with the former run that had the same base branch. That way major releases would not interfere. As an example: master has 30 failures. v10.x gets a new release and it has 10 failures. It now shows -20 failures. Now we run another CITGM against master and it has the same 30 failures as before but it highlights 20 new failures. At least that's the case as far as I know. Ideally that could be deactivated with a checkbox.

AFAIK this isn't possible with the stuff built-in to Jenkins or with any of the available plugins (I'm happy to be corrected here) and we'd have to either write our own plugin or separate visualization tool.

**Comment by mmarchini** [comment]
node-core-utils now have citgm comparison: https://github.com/nodejs/node-core-utils/pull/455. Closing, but can be reopened if that's not what you're looking for.
