### ISSUE TITLE
Prepare to forward foundation.nodejs.org to openjsf.org

### ISSUE THREAD

**Issue by brianwarner** [nodejs/build#1953]
Hi Node build WG,

I would like to open an exploratory conversation about a 301 redirect from foundation.nodejs.org to openjsf.org.  The goal is to eliminate any potential sources of confusion about which Foundation is currently active.

I believe one path to a graceful transition would be:
1. Go over the current site and determine if anything remains to be rehosted on openjsf.org
2. Move the current site somewhere it can be easily accessed if something gets missed, such as nodearchive.openjsf.org (we can do this on our end)
3. Add a 301 redirect from foundation.nodejs.org to openjsf.org

Does anybody have any thoughts about this?

**Comment by mhdawson** [comment]
Makes sense to me.  I had through the foundation.nodejs.org component was now hosted by the Foundation as opposed to the Node.js project but I'm not the expert on that front.

**Comment by brianwarner** [comment]
My understanding is that the foundation should be able to do everything except the DNS redirects, since that's delegated to CloudFlare.  But also, I wanted to make sure everyone was aware and that I'm not missing anything subtle before doing something drastic. :-)

**Comment by rvagg** [comment]
This is fine, we currently point foundation.nodejs.org (CNAME) to some host maintained by the LF so what's on there and how to manage it is in your hands already. So I believe steps 1 and 2 are out of our hands. We can just point it to one of our servers and do a full redirect of `foundation.nodejs.org/*` to `openjsf.org/`. Let us know when that's good to go and we can make that happen. I'll prepare a PR to change the web server config files and then it'll just be a DNS switch.

**Comment by brianwarner** [comment]
Checking back in one more time before we start the process of the transition.  Thanks @rvagg and @mhdawson - would anybody else like to weigh in on this?

**Comment by mhdawson** [comment]
not me.

**Comment by rvagg** [comment]
#1999 for config change, we can deploy this prior to making the actual switch, then the switch is just a DNS update.

**Comment by brianwarner** [comment]
I think at this point we're ready to go on this.  @rvagg, could I ask your assistance on adding the redirect?  Once that's redirected and replicated, I'll take care of the other parts.

**Comment by rvagg** [comment]
I briefly forgot that we control DNS too @brianwarner when I spoke to you about this last. But I've merged the change to the server(s) and updated DNS and the redirect looks like it's in place.
