### ISSUE TITLE
No space left on device while building a release

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1954]
I just got the following error while building v12.12.0:

21:32:58 /mnt/build/ws/out/Release/obj/gen/node_javascript.cc:72921:1: fatal error: error writing to /tmp/cc3j4pBT.s: No space left on device

https://ci-release.nodejs.org/job/iojs+release/4754/nodes=cross-compiler-armv7-gcc-6/console

It would be great if this could be looked at and resolved very soon.

**Comment by mhdawson** [comment]
It looks like the disk has free space.  Maybe you tried to fix by cleaning the workspace?

```
ojs@d7ed7e85-aae2-4aba-f8ee-c79ea7d1db8f:/var/log$ df -ak
Filesystem     1K-blocks     Used Available Use% Mounted on
sysfs                  0        0         0    - /sys
proc                   0        0         0    - /proc
udev             1884876        0   1884876   0% /dev
devpts                 0        0         0    - /dev/pts
tmpfs             378832    38532    340300  11% /run
/dev/vda1        7688776  5014456   2657936  66% /
securityfs             0        0         0    - /sys/kernel/security
tmpfs            1894148        0   1894148   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs            1894148        0   1894148   0% /sys/fs/cgroup
cgroup                 0        0         0    - /sys/fs/cgroup/systemd
pstore                 0        0         0    - /sys/fs/pstore
cgroup                 0        0         0    - /sys/fs/cgroup/perf_event
cgroup                 0        0         0    - /sys/fs/cgroup/pids
cgroup                 0        0         0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                 0        0         0    - /sys/fs/cgroup/cpuset
cgroup                 0        0         0    - /sys/fs/cgroup/hugetlb
cgroup                 0        0         0    - /sys/fs/cgroup/net_cls,net_prio
cgroup                 0        0         0    - /sys/fs/cgroup/blkio
cgroup                 0        0         0    - /sys/fs/cgroup/devices
cgroup                 0        0         0    - /sys/fs/cgroup/freezer
cgroup                 0        0         0    - /sys/fs/cgroup/memory
systemd-1              -        -         -    - /proc/sys/fs/binfmt_misc
hugetlbfs              0        0         0    - /dev/hugepages
mqueue                 0        0         0    - /dev/mqueue
debugfs                0        0         0    - /sys/kernel/debug
fusectl                0        0         0    - /sys/fs/fuse/connections
/dev/vdb       103081248 51121528  46716840  53% /mnt
lxcfs                  0        0         0    - /var/lib/lxcfs
binfmt_misc            0        0         0    - /proc/sys/fs/binfmt_misc
tmpfs             378832        0    378832   0% /run/user/1000
iojs@d7ed7e85-aae2-4aba-f8ee-c79ea7d1db8f:/var/log$ 
```

**Comment by BridgeAR** [comment]
@mhdawson I did not change anything. And trying to rerun the builds end up with the same failure:

https://ci-release.nodejs.org/job/iojs+release/nodes=cross-compiler-armv7-gcc-6/4755/console

**Comment by BridgeAR** [comment]
It is possible for anyone to take another look? @nodejs/build

**Comment by mhdawson** [comment]
Found I had the wrong machine as I had to manually grab the IP.  I freed a bit of space and the top consumers are:

```
4388984	/
6719512	/mnt
4390400	/mnt/.ccache
3526892	/opt
3526888	/opt/raspberrypi
2493952	/usr
1602576	/opt/raspberrypi/tools
1248712	/mnt/tmp
1248708	/mnt/tmp/node
1127984	/usr/src
```

I think only the following are on / itself (same as tmp)

```
4388984	/
3526892	/opt
3526888	/opt/raspberrypi
2493952	/usr
1602576	/opt/raspberrypi/tools
1127984	/usr/src
```

**Comment by sam-github** [comment]
I was trying, but nodejs/build membership doesn't include access to release machines, I think its these people who have access, https://github.com/nodejs/build#release-admins, in theory, but that list looks out of date.

**Comment by mhdawson** [comment]
I don't see anything obvious to clean up and I don't know the cross compilation machines well enough to start deleting things other than in /var/log but I don't see anything big there either.

I could try rebooting to see if there are some already deleted files but with the small amount of space on / I think it would be better if @rvagg took a look first to see if he can see what's up.

**Comment by BridgeAR** [comment]
@mhdawson thanks for looking into it again! The last rebuild worked and I just promoted all builds.

Is it possible for anyone to get a notification when one of the machines is running low on space?

**Comment by mhdawson** [comment]
ok, I guess the small amount that I freed up to get the du command to work was enough.

> Is it possible for anyone to get a notification when one of the machines is running low on space?

**Comment by mhdawson** [comment]
@rvagg still good if you take a look at there is only something like 40MG available in /

**Comment by rvagg** [comment]
On it

**Comment by rvagg** [comment]
On these joyent machines, because we only have a small root device, it's fine to move large, node-specific stuff onto /mnt/. I've moved /opt/raspberrypi to /mnt/ and symlinked from its original location. Our cross compiler is getting quite large and has been taking up half of the root device.

This is what it looks like now:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       7.4G  4.0G  3.5G  54% /
/dev/vdb         99G   11G   84G  12% /mnt
```

With ~iojs/build/ on /mnt, that should give us plenty of breathing room on that machine, I don't expect it to fill up again any time soon.
