### ISSUE TITLE
OSX builds take _very_ long

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1955]
Each release build is waiting on OSX to finish. All other builds finish significantly faster than OSX. It would be great if this could be looked at so that they finish around about at the same time.

**Comment by rvagg** [comment]
I believe this is fixed, installed ccache manually, also #1956. Still a bit more work needed on the ansible scripts for macos, things have marched on a bit further than when it was last used I think.

**Comment by BridgeAR** [comment]
Thanks a lot!
