### ISSUE TITLE
path length issues with CITGM and modules

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1959]
Not sure what to do about this, but we should solve it somehow. @nodejs/build @nodejs/citgm-admins @mcollina 

CITGM results for `fastify` fail when a socket path name gets truncated. See https://github.com/fastify/fastify/pull/1856#issuecomment-542354766.

`fastify` shouldn't have to protect against this in their tests in my opinion.

`citgm` probably shouldn't have to worry about it either.

Can we shorten the temp path generated in the `citgm-smoker` job?

**Comment by richardlau** [comment]
We're currently explicitly setting a temp path of `"$WORKSPACE"/citgm_tmp` everywhere apart from AIX (where it's `/ramdisk0/citgm` for performance reasons). I don't know the reason why it has been set to be in the workspace.

**Comment by Trott** [comment]
> We're currently explicitly setting a temp path of `"$WORKSPACE"/citgm_tmp` everywhere apart from AIX (where it's `/ramdisk0/citgm` for performance reasons). I don't know the reason why it has been set to be in the workspace.

Perhaps to avoid it colliding with temp paths used in other jobs?

**Comment by rvagg** [comment]
>  I don't know the reason why it has been set to be in the workspace.

I'd guess because we don't have any guarantees about there existing another unique directory on all of the hosts we may want to use? Maybe we just replace that with `${HOME}/node-tmp` like for `NODE_TEST_DIR`? or a subdir of that dir. It's on all of the machines.

**Comment by richardlau** [comment]
I'll switch the job over to using a directory in `NODE_TEST_DIR` later today (when I can keep an eye on a test CITGM build with the change).

**Comment by richardlau** [comment]
Made the change: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/jobConfigHistory/showDiffFiles?timestamp1=2019-10-02_19-32-13&timestamp2=2019-10-16_18-40-33

Test build: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2059/

**Comment by richardlau** [comment]
Looks promising:

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2056/nodes=ubuntu1604-64/testReport/(root)/citgm/fastify_v2_10_0/history/
![image](https://user-images.githubusercontent.com/5445507/66966263-803f1080-f074-11e9-8a89-fcb17bf1e525.png)

**Comment by richardlau** [comment]
No fastify failures or any new failures that look to be related to the new temp path. I believe this is resolved.

**Comment by Trott** [comment]
> No fastify failures or any new failures that look to be related to the new temp path. I believe this is resolved.

I agree. That's fantastic! Thanks!
