### ISSUE TITLE
Account for core dumps on CI machines

### ISSUE THREAD

**Issue by evanlucas** [nodejs/build#196]
Related: https://github.com/nodejs/node/pull/2776

This above PR verifies that the `--abort-on-uncaught-exception` flag works properly. If core dumps are enabled, this could begin filling up space quickly. Another option would be to change the location of core dumps to be inside the repo as they would be git cleaned on the next run.

For now, the PR put the test into `test/abort` and the test will not be run on the CI servers until we can get this sorted out per IRC.

/cc @orangemocha @trevnorris

**Comment by misterdjules** [comment]
I think that tests that are currently testing the `--abort-on-uncaught-exception` command line option don't use the core file that is produced as the result of the process aborting.  Thus, disabling core file generation on the system on which the tests run is enough to not fill up space.

This is already done in most tests of `--abort-on-uncaught-exception` by [using `ulimit -c 0` on anything except Windows](https://github.com/nodejs/node/blob/master/test/parallel/test-domain-abort-on-uncaught.js#L236-L240).

Moreover, I think core dump are _not_ generated when a process aborts on Windows unless explicitly enabled, so we should be already OK on that platform.

Thus, I think `test/abort/test-abort-uncaught-exception.js` could implement the same mechanism and be moved to a folder that contains tests that are run by the CI platform.

**Comment by gibfahn** [comment]
@misterdjules I think you are correct regarding windows not dumping with `--abort-on-uncaught-exception`, when I last checked it was impossible to enable coredumps without using an external tool (see https://github.com/nodejs/node/issues/7733).

**Comment by Trott** [comment]
Is this still an issue? Or can it be closed?

**Comment by maclover7** [comment]
Seems to be a stale issue, closing for now. Please reopen if this is still needed.
