### ISSUE TITLE
Node-daily-master always fails due to napi test in node-test-commit-custom-suite-freestyle

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#1961]
https://ci.nodejs.org/job/node-daily-master/ is failing everyday, Error looks real and probably predictable.

Example below of a common failure:

https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/9513/testReport/(root)/test/benchmark_test_benchmark_napi/

@nodejs/napi. any opinions?

**Comment by richardlau** [comment]
Related to https://github.com/nodejs/node/commit/53ca0b9ae145c430842bf78e553e3b6cbd2823aa#commitcomment-35494896?

cc @nodejs/n-api

**Comment by richardlau** [comment]
I've opened https://github.com/nodejs/node/pull/29995 to fix the break.
