### ISSUE TITLE
Supporting multiple versions of xcode

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#1964]
From disscusion here: https://github.com/nodejs/node/pull/29493#issuecomment-530862404

What is the opinion on multple xcode version?

From a bit of research you can use xcode-select to change versions inside select-compiler.sh but this requires sudo root to do so which the iojs user on the build machines does not have.

This gives two options:
 * Edit the sudoers file to whitelist xcode-select for the iojs user, and then edit select-complier to call xcode-select.
or
* Have multiple machines running different versions of xcode to run the builds

**Comment by rvagg** [comment]
I think it's safe to assume a single build will occur on a machine at one time. To be safe we should probably have a default version that is always set at the end of a run regardless of what happens, because there are numerous jobs that use the osx machines other than standard test builds, like citgm and libuv, it'd be annoying for them to have one compiler for one run and another for the next.

We could create a sudoers special-case for xcode-select, we already do that on some hosts that use Docker to switch environments, giving narrow access to a certain command https://github.com/nodejs/build/blob/ee7d97fb9d7d7f3e647b4ff39d1e2c1dee6b6828/ansible/roles/jenkins-worker/tasks/partials/docker-host.yml#L34-L38

More machines will be a bigger problem, so we should try and solve this for single machines. We need to handle this for release builds too.

**Comment by rvagg** [comment]
How do we *get* the multiple versions of xcode onto these machines? We currently have to resort to this abomination for older versions already https://github.com/nodejs/build/blob/master/ansible/roles/package-upgrade/files/install-xcode.sh, only George has experience with that one, so I guess one of us needs to upskill here, upgrade it for 10.9, 10.10, and get ansible to do the multiple-versions thing.

**Comment by sam-github** [comment]
If we are going the sudoers and less machines route, then @AshCripps is going to take a shot at figuring this out. He's not in the buildwg yet, not even a node collaborator, but he's working on our team and once he's made enough contributions to demonstrate his usefulness, we'll nominate him.

**Comment by rvagg** [comment]
oh, awesome, help managing our macstadium setup is certainly something we're in need of

**Comment by AshCripps** [comment]
Old versions of xcode can be found here - https://developer.apple.com/download/more/ 

You can scroll through the list select just the command line tools options and grab the link from there.

The link can be curled in the same way as is done in install-xcode.sh

https://github.com/nodejs/build/blob/97351053b2e723a0ec138c4fa3c56d6109913c3f/ansible/roles/package-upgrade/files/install-xcode.sh#L29-L34

Just need to update the script to install the versions of xcode we want.

Made a first pass at editing select-compiler.sh - https://github.com/nodejs/build/pull/1967

I have discovered on my local machine that xcode8 does not run on mojave so we would have to be more selective on which machines run older node version builds as newer os's cannot run some older versions of xcode

**Comment by mhdawson** [comment]
We'd want to install 2  or more versions on the same machine.  It might make sense to have ansible select which ones to install based on the osx version.  Ideally we could set a list of each OSX version that would control which xcode versions would be installed.  We would then use the selector script to build each Node.js version on machines with the right osx/xcode combinations.

**Comment by rvagg** [comment]
don't know if it's helpful but @cclauss just shared this with me: https://blog.macstadium.com/blog/catalina-released-and-live-on-orka

**Comment by cclauss** [comment]
Unfortunately, [MacStadium does not yet support macOS 10.15 Catalina](https://www.macstadium.com/configure?p=rm3) scroll down to _Choose your OS_.

**Comment by sam-github** [comment]
Conversation on getting recent OS X hosts running in macstadium is https://github.com/nodejs/build/issues/1732

**Comment by sam-github** [comment]
We don't want to do this anymore, we want to always build on a current Xcode, specifically, a current enough one to do notarization, so while experimentation was done on using xcode-select to choose an Xcode version based on the release line, that turned out to be a dead end.
