### ISSUE TITLE
No nightly tarballs for AIX

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#1965]
In https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=aix61-ppc64/781/console it looks like it's failing to download the appropriate Node.js release tarball.

Looks like the nightlies for AIX have been missing for a short while: https://github.com/nodejs/build/issues/1957#issuecomment-543013729

**Comment by rvagg** [comment]
missing for 13.0.0-rc\* builds too. @sam-github do you have access to the release machine?

**Comment by sam-github** [comment]
Yes I have access, and I believe/hope this is a symptom of https://github.com/nodejs/build/issues/1957#issuecomment-543460591

**Comment by sam-github** [comment]
duplicate of https://github.com/nodejs/build/issues/1957

**Comment by sam-github** [comment]
I built nightlies for 13.x: https://github.com/nodejs/build/issues/1957#issuecomment-543893348

Is that what you need @gabrielschulhof ?

**Comment by gabrielschulhof** [comment]
@sam-github I'll check if it causes the build for https://github.com/nodejs/node-addon-api/pull/562 to go green.

**Comment by gabrielschulhof** [comment]
@sam-github looks like it moved past the point where it was failing to find the nightly tarball.

**Comment by gabrielschulhof** [comment]
Looks like the build will be green 👍 Thanks!
