### ISSUE TITLE
Heads up: scheduled downtime for NearForm hosted build and benchmark servers

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#1968]
Just a heads up, the NearForm hosted benchmark servers and mac minis will be offline on Tuesday 22nd of Oct between 6pm - 8pm Irish Standard Time because of scheduled network maintenance at NearForm HQ.

**Comment by richardlau** [comment]
Eek that's the proposed release date for [13.0.0](https://github.com/nodejs/node/pull/29504) and [10.17.0](https://github.com/nodejs/node/pull/29875)!

cc @nodejs/releasers @BethGriggs

**Comment by rvagg** [comment]
I don't think that will impact releases, unless benchmarks are essential.

But the MacMinis are interesting, I'd forgotten we arranged those. I don't think we ever got them set up properly. @mhdawson do you recall where we got to with these? Maybe they can help with our versioning woes.

**Comment by sam-github** [comment]
@ashcripps is beginning to start on getting these running. You've seen the beginning, because a prereq is to allow xcode versions to be selectable. With the limited machines and vmware licenses, we'll need that.

**Comment by rvagg** [comment]
ah, I was imagining that was all for our MacStadium. But it has to be both I guess.

**Comment by mhdawson** [comment]
Yes, not sure which we'll get in place first but @AshCripps and @sam-github are starting to look at both. I remember @refack mentioning problems in getting OSX 10.14 vms in our existing mac stadium setup.
