### ISSUE TITLE
libuv,arm64: add arm64 buildbots to matrix

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1971]
See https://github.com/libuv/libuv/issues/2522 and https://github.com/nodejs/node/pull/29996. Node.js is tested against arm64 but libuv isn't, allowing a compile time error to slip through.

**Comment by rvagg** [comment]
k, I've added them to libuv-test-commit-linux, https://ci.nodejs.org/view/libuv/job/libuv-test-commit-linux/1671/

* centos7-arm64-gcc48
* centos7-arm64-gcc6 
* ubuntu1604-arm64 

I've added the logic into the job that selects the devtoolset to enable gcc6 and that appears to be working, at least according to the `gcc` output.

But you have persistent failures on those centos machines that will need addressing:

```
not ok 347 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)
not ok 348 - udp_multicast_join6
# timeout
# Output from process `udp_multicast_join6`: (no output)
```

You have access to those machines, see inventory.yml, so feel free to get in and poke around. If we need changes to the machine configs then let's get something into ansible for it.

**Comment by rvagg** [comment]
@joaocgreis are windows arm64 machines able to be added here too?

**Comment by richardlau** [comment]
> But you have persistent failures on those centos machines that will need addressing:
> 
> ```
> not ok 347 - udp_multicast_join
> # timeout
> # Output from process `udp_multicast_join`: (no output)
> not ok 348 - udp_multicast_join6
> # timeout
> # Output from process `udp_multicast_join6`: (no output)
> ```
> 
> You have access to those machines, see inventory.yml, so feel free to get in and poke around. If we need changes to the machine configs then let's get something into ansible for it.

Possibly related to https://github.com/nodejs/build/pull/1879?

**Comment by cjihrig** [comment]
> Possibly related to #1879?

I believe that's correct, based on https://github.com/libuv/libuv/issues/2468#issuecomment-530031340.

**Comment by rvagg** [comment]
🤦‍♂ ok, that's on me then, an overdue TODO, will try and get it sorted today

**Comment by rvagg** [comment]
got firewalld sorted and got a green on https://ci.nodejs.org/view/libuv/job/libuv-test-commit-linux/1674/

**Comment by cjihrig** [comment]
Thank you @rvagg

**Comment by bnoordhuis** [comment]
Thanks, Rod!

**Comment by joaocgreis** [comment]
Added ARM64 to the Windows job. These are just 2 machines running from my office. They have been quite stable, but please mention me if there's any issue.
