### ISSUE TITLE
custom node-test-commit run fails early

### ISSUE THREAD

**Issue by targos** [nodejs/build#1976]
See https://ci.nodejs.org/job/node-test-commit/32028/console

The error is `12:35:58 stderr: fatal: Unable to create '/home/iojs/build/workspace/node-test-commit/.git/index.lock': File exists.`

**Comment by rvagg** [comment]
ran into this myself .. one of the jenkins-workspace machines got into a bad state somehow, I've taken it offline and am cleaning it up, should be sorted out now

**Comment by rvagg** [comment]
that workspace machine is back online, all cleaned up, but I'm off to :zzz: so I'm crossing my fingers it's all good now
