### ISSUE TITLE
Windows addon tests use VS 2015 instead of VS 2017

### ISSUE THREAD

**Issue by targos** [nodejs/build#1978]
See https://ci.nodejs.org/job/node-test-binary-windows-2/3625/

```
16:30:13 gyp info it worked if it ends with ok
16:30:13 gyp info using node-gyp@5.0.5
16:30:13 gyp info using node@13.0.0-pre | win32 | x64
16:30:13 gyp info chdir c:\workspace\node-test-binary-windows-2\test\addons\01_function_arguments
16:30:13 gyp info find Python using Python version 2.7.10 found at "C:\Python27\python.exe"
16:30:13 gyp info find VS using VS2015 (14.0) found at:
16:30:13 gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
16:30:13 gyp info find VS run with --verbose for detailed information
16:30:13 gyp info spawn C:\Python27\python.exe
```

Is this a bug in node-gyp?

**Comment by targos** [comment]
@nodejs/platform-windows

**Comment by joaocgreis** [comment]
VS versions needed to build Node itself and native add-ons are different in Windows.

This used to be explicit in `BUILDING.md`, but with https://github.com/nodejs/node/pull/14764 both versions became VS2015 so the text was unified. Perhaps we should split it again. I keep a list of versions in https://github.com/nodejs/build/blob/master/doc/windows-visualstudio-supported-versions.md, but it needs to be updated for recent versions.

We could drop support for building add-ons with VS2015, but we should try to do it in a semver major release.

@targos on that CI run, the tests passed on Windows 10, which is also using VS2015. I only see errors in Windows 2016, indicating that this is probably not an issue with V8 support.

**Comment by joaocgreis** [comment]
The error appears to be caused a regression in `cl.exe` in VS2015. I can reproduce this with 19.00.24215.1 but not with 19.00.23506. Some build machines did not get the latest update of VS2015 automatically, thus CI passes.

@targos is V8 7.9 going to land in v13 or is it just being prepared for v14? It would be good to patch it to work with VS2015 if possible, but I need more time to look at this.

**Comment by targos** [comment]
I would like to land it in v13.x

**Comment by joaocgreis** [comment]
Moving the V8 discussion to https://github.com/nodejs/node/pull/30020.

Perhaps we should consider removing support to build add-ons with VS2015 for Node v14.
