### ISSUE TITLE
Help with installing the tick processor by default

### ISSUE THREAD

**Issue by matthewloring** [nodejs/build#198]
I was hoping to get the [tick processor](https://github.com/nodejs/node/blob/master/tools/v8-prof/tick-processor.js) installed by default in node installations. My hope is to follow a pattern similar to that of [gdbinit](https://github.com/nodejs/node/commit/ee3ce2ed88bcb605d611a915f9b86163cc781a7f) but installing the tick processor will involve dynamically creating a script which is the concatenation of a collection of scripts in V8. It will additionally require modifying the tick processor itself as the tool currently relies on relative paths into V8. Do you have any pointers to resources I could use to get started?

**Comment by bnoordhuis** [comment]
I'd start with `make install` first and tackle the GUI installers later.

`make install` runs tools/install.py.  You would add an action to the files() function, something like:

```python
def files(action):
  # ...
  if action == install:
    # concatenate files and install
    action(...)
  elif action == uninstall:
    # just uninstall
    action(...)
```

The install and uninstall functions only know about copying around files, you probably want to teach install how to write a string to file.

**Comment by matthewloring** [comment]
Does tools/install.py run on unixy things only or does it handle windows installations as well?

**Comment by matthewloring** [comment]
Pull request opened at nodejs/node#3032.

**Comment by matthewloring** [comment]
nodejs/node#3032 landed. Closing this.
