### ISSUE TITLE
request for macstadium access

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#1980]
Attempts to get Xcode 10 on our test/release machines is blocked on the fact that it requires OS X 10.14, and we don't have any of those.

https://github.com/nodejs/build/issues/1593#issuecomment-544673921

Its not clear if we can spin up any 10.14 machines at macstadium, https://github.com/nodejs/build/issues/1593#issuecomment-461755852, but in order to investigate I need access to macstadium, so I can try and/or so I can ask their support.

Can I have access?

Alternatively, if someone who currently haa access wants to work out how we can spin up VMs capable of having Xcode 10 installed on them, that would be very helpful!

**Comment by rvagg** [comment]
yes, and I'd be happy to expedite this if I get another +1 from infra. We have a dedicated section for it in secrets already so it's easy to share .. not so easy to use beyond that!

**Comment by mhdawson** [comment]
Created PR to add Sam: https://github.com/nodejs-private/secrets/pull/53 on the assumption that my +1 counts as what @rvagg was looking for.
