### ISSUE TITLE
How is the "date" field of release index determined?

### ISSUE THREAD

**Issue by targos** [nodejs/build#1988]
See https://nodejs.org/dist/index.json

v13.0.0 was released yesterday (2019-10-22) but the date is 2019-10-10

**Comment by rvagg** [comment]
Oldest mtime in the dist directory. https://github.com/nodejs/nodejs-dist-indexer/blob/333c71c352b250508c7dac09ff85cd46dd164c4c/dist-indexer.js#L361-L380

```
/home/dist/nodejs/release/v13.0.0# ls -altr
total 645620
drwxr-xr-x   2 dist staging     4096 Oct 10 10:19 win-x64
drwxr-xr-x   2 dist staging     4096 Oct 10 10:22 win-x86
drwxr-xr-x   3 dist staging     4096 Oct 10 10:30 docs
-rw-r--r--   1 dist staging 31784870 Oct 22 13:49 node-v13.0.0-linux-arm64.tar.gz
-rw-r--r--   1 dist staging 19519044 Oct 22 13:51 node-v13.0.0-linux-arm64.tar.xz
```

My guess is that someone might have done a test v13.0.0 release compile on the 10th and it just sat in staging? All of the files, even in those directories, are the 22nd. iirc those directories are `mkdir -p` via ssh on the builders into staging, so if they are there then they won't be re-made or touched.

So the flaw in this logic is including the directories in this calculation. I'll PR an `isFile()` and that should fix it.

**Comment by rvagg** [comment]
Yep, here it is, on the 10th: https://ci-release.nodejs.org/job/iojs+release/4749/

A fun edge-case! We might find a few dates shifted by changing this date strategy.

**Comment by targos** [comment]
Interesting!

**Comment by rvagg** [comment]
can move discussion to https://github.com/nodejs/nodejs-dist-indexer/pull/10, there's a decision to be made re rewriting history.

**Comment by rvagg** [comment]
FYI this got finally deployed https://github.com/nodejs/nodejs-dist-indexer/pull/10#issuecomment-686903601

it's not a small disruption, but we have better accuracy now.
