### ISSUE TITLE
add Node.js 13 to CITGM job configurations

### ISSUE THREAD

**Issue by targos** [nodejs/build#1989]
* NODE_VERSION in https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/build?delay=0sec
* NODE_VERSIONs in https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration-pipeline/build?delay=0sec
* NODE_VERSIONs in https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/build?delay=0sec

@nodejs/citgm-admins

**Comment by richardlau** [comment]
All done.

**Comment by targos** [comment]
thanks
