### ISSUE TITLE
remove gibfahn from build and release wg and teams

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2022]
I asked @gibfahn:

> Can you give me blanket approval to just remove you from nodejs/ org teams (other than collaborators) and move you to emeritus if I find your name in READMEs?

and he replied:

> Yep go for it. I meant to do it myself but haven't had the time.

He has more access than me, so I can't remove him from things I don't have access to myself.

What I can do:

- rm from https://github.com/orgs/nodejs/teams/build/members
- rm from https://github.com/orgs/nodejs-private/teams/build/members
- partuial rm from https://github.com/nodejs-private/secrets/pull/61

(From https://github.com/nodejs/build/pull/2018#issuecomment-548491428)

**Comment by sam-github** [comment]
- rm from https://github.com/orgs/nodejs/teams/jenkins-admins/members

**Comment by sam-github** [comment]
ncu-team sync isn't convinced yet. he's still a member of a child  team: https://github.com/orgs/nodejs/teams/build/members?query=membership:child-team

But when I go to https://github.com/orgs/nodejs/teams/build/teams I see something odd, the team count is `3`, but I only see 2 teams listed below (he's a member of neither), is it possible he is a member of a team that I can't see, or where his membership is not publicized?

I'm puzzled.

**Comment by richardlau** [comment]
@sam-github There's a twisty for `jenkins-admins` as it has a child team https://github.com/orgs/nodejs/teams/jenkins-release-admins/members that he is still a member of.

**Comment by sam-github** [comment]
- rm from https://github.com/orgs/nodejs/teams/jenkins-release-admins/members

**Comment by sam-github** [comment]
- rm from https://github.com/orgs/nodejs-private/teams/security-release/members

**Comment by Trott** [comment]
@sam-github Looks like this can now be closed?

**Comment by sam-github** [comment]
I'd have to review current state, but the comments above make it sound like at the time I was not capable of removing him from the teams, like infrastructure and release, that I am not a member of.

**Comment by Trott** [comment]
> I'd have to review current state, but the comments above make it sound like at the time I was not capable of removing him from the teams, like infrastructure and release, that I am not a member of.

I guess we could use an offboarding doc.

**Comment by BethGriggs** [comment]
Removed from Release teams - https://github.com/nodejs/Release/pull/524

@gibfahn remains in the following teams (I didn't feel like I should remove from these):
- gyp
- onboarding
- streams-admins

**Comment by sam-github** [comment]
@BethGriggs he gave permission to be removed from all nodejs org teams.... if for some reason he ever wants access again, he can just ask for perms back. I removed him from the 3 you mentioned.

**Comment by gibfahn** [comment]
Thanks for cleaning up after me, sorry I didn't do it myself! Feel free to emeritize me from any team you think reasonable.

**Comment by mmarchini** [comment]
Is there anything left to be done here?

**Comment by mhdawson** [comment]
Gibson is no longer in the build or release Node.js teams  or any of the others mentioned so I think it can be closed.
