### ISSUE TITLE
request for special access for Ash Cripps to centos7-ppcle machines

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2043]
EDIT: github ID  @AshCripps 

I'd like him to complete the ansible install of bzip2 and rebuild of python required on these machines.

The ansible draft PR is https://github.com/nodejs/build/pull/2042

The issue it should fix is 1. on https://github.com/nodejs/node/issues/30152

He would need access long enough on each one for me to disable the machine, and for him to delete python and reansible (which will rebuild python if missing).

https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md#ongoing-access

- Does the scope and size of the need justify providing access.

> I think so, the issue has been oustanding for more than a week and I haven't had time to do this.

- Is the individual a collaborator. If so then access should be allowed provided the first point is satisfied.

> No

- Consequences to the individual in case of misbehaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way ?
Are there collaborators who work with the individual and can vouch for them.

> Yes, yes, yes. Ash Cripps works with me, @mhdawson , and @richardlau  in IBM runtimes on Node.js support.

**Comment by sam-github** [comment]
The specific access required is just ssh access to the centos7-ppcle machines, I'll do  the CI disable/enable step, and also mentor him through the process.

**Comment by mhdawson** [comment]
+1

**Comment by rvagg** [comment]
+1

**Comment by sam-github** [comment]
I added his ssh key to -1 and -2 (I'll do the release machine after he's finished those two).

**Comment by richardlau** [comment]
Taken https://ci.nodejs.org/computer/test-osuosl-centos7-ppc64_le-1/ offline in Jenkins so @AshCripps can rerun ansible on it.

**Comment by AshCripps** [comment]
test-osuosl-centos7-ppc64_le-1 and 2 reansibled and now have bzip2 on them

**Comment by sam-github** [comment]
ssh keys removed, thanks for doing that @AshCripps
