### ISSUE TITLE
access request: AIX7.1 machines are being provisioned, and Ash Cripps maintain them?

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2054]
@AshCripps  is in the process of setting up 4 new AIX7.2 machines so they can be joined to CI. This should allow us to remove the AIX6.1 machines (and their recurring problems).

They aren't in CI ATM, so he hasn't needed access to any CI build secrets, but once he's got the ansible scripts and doc updates PRed, it will be time to join them to CI, and at that point his ssh access would allow him access to the jenkins secret, and just generally it would give him access to a CI build machine.

I'm requesting special access so that he can continue to maintain these machines after they are joined to the CI.

**Comment by mhdawson** [comment]
> allow us to remove the AIX6.1 machines  

At some point...

**Comment by mhdawson** [comment]
+1

**Comment by sam-github** [comment]
The machines are now AIX7.1 (because its the minimum supported platform for 10.x). It turns out we can't build on AIX7.2 and run on AIX7.1, but we can do the opposite.

@nodejs/build-wg any objections? This will mean @AshCripps has access to the jenkins secrets for the 3 test machines we will provision but *not* the release machine.

**Comment by mhdawson** [comment]
+1

**Comment by richardlau** [comment]
+1

**Comment by joaocgreis** [comment]
+1

**Comment by AshCripps** [comment]
Closing as now member of the build working group
