### ISSUE TITLE
ci.nodejs.org cert is expired

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2058]
It expired 7 minutes ago. It is a wildcard cert from Comodo

<img width="492" alt="Screen Shot 2019-11-20 at 7 06 09 PM" src="https://user-images.githubusercontent.com/498775/69288879-def22f80-0bc8-11ea-95a7-563f40a47a20.png">

**Comment by Trott** [comment]
There's a valid wildcard cert on the website that doesn't expire until 2022 so I guess maybe that cert just needs to be applied to the CI server?

**Comment by rvagg** [comment]
fixed, and ci-release
