### ISSUE TITLE
Machine issue on  test-osuosl-aix61-ppc64_be-2

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2061]
All runs seems to be failing on  test-osuosl-aix61-ppc64_be-2. Disabled

**Comment by mhdawson** [comment]
As an example:  

https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=aix61-ppc64/1108/console
https://ci.nodejs.org/job/node-test-commit-aix/26757/console

**Comment by mhdawson** [comment]
Disabled the machine for now.

**Comment by sam-github** [comment]
I can't ssh in, is there a way to reboot it?

**Comment by sam-github** [comment]
Had to have it hard-rebooted. :-(

https://ci.nodejs.org/computer/test-osuosl-aix61-ppc64_be-2/ says jenkins agent is back online, so reenabled it.

Will watch for health.

**Comment by Trott** [comment]
Oops, sorry, I took it offline again. Re-enabling

**Comment by sam-github** [comment]
Also had to re-ramdisk the machine.

**Comment by richardlau** [comment]
I think this was resolved. Please reopen otherwise.
