### ISSUE TITLE
Missing SHASUMS256.txt.sig at https://nodejs.org/dist/v13.2.0/

### ISSUE THREAD

**Issue by igsu** [nodejs/build#2065]
In addition to the missing `SHASUMS256.txt.asc` (Ref: #2059), `SHASUMS256.txt.sig` used to verify binaries was not created/uploaded. Instead there's `SHASUMS256.txt.gpg` available

**Comment by targos** [comment]
@MylesBorins

**Comment by MylesBorins** [comment]
@igsu thanks for the heads up. I just regenerated all the signatures. Going to close this. LMK if I made a mistake.

**Comment by MylesBorins** [comment]
@igsu FWIW I realized that the reason we ended up with a *.gpg rather than *.sig is because the existing readme had gone out of sync with the tool and I create the signatures manually (to ensure it worked).

I fixed the upstream docs to fix this https://github.com/nodejs/node/pull/30673
