### ISSUE TITLE
Why are we throttling node-test-commit?

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2068]
I've just increased this from 6 to 12 but I don't know why this is even here or who did it:

<img width="651" alt="throttle" src="https://user-images.githubusercontent.com/495647/69767830-32b8d600-11d2-11ea-8aca-ec788d90302a.png">

We have lots of room on jenkins-workspace machines to handle concurrent builds, maybe there's a case for throttling at the top level because it compounds when you add all of the children, but does anyone know if we were running into actual problems with this?

**Comment by rvagg** [comment]
sorry, ping @nodejs/build on the above

**Comment by mhdawson** [comment]
I don't remember why/when this was added.

**Comment by rvagg** [comment]
I found another oddity yesterday in Jenkins that I can't explain. node-test-commit-arm had a "if JOBS < 4 set JOBS=4" which wasn't great when I wanted to reduce the scaleway machines to JOBS=2 but it kept on being bumped up. I have no idea why that was in there and there were no comments about why either.

**Comment by mhdawson** [comment]
@rvagg that is odd

**Comment by rvagg** [comment]
🤷‍♂ we need to figure out how better to communicate this stuff
