### ISSUE TITLE
All fedora-last-latest-x64 nodes are offline

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#2074]
https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/

I was wondering why a CI run never finished and stumbled upon this:
`pending—All nodes of label ‘fedora-last-latest-x64’ are offline`

**Comment by richardlau** [comment]
https://ci.nodejs.org/computer/test-digitalocean-fedora27-x64-1/ and https://ci.nodejs.org/computer/test-rackspace-fedora27-x64-1/ are both online and processing jobs... maybe it was a temporary blip or someone else brought them back?

**Comment by BridgeAR** [comment]
I cancelled the last two stalled jobs. I am not sure what happened but the message was there for hours.

**Comment by joaocgreis** [comment]
I rebooted the machines. They look ok now, please reopen if not.
