### ISSUE TITLE
Request to join the build WG

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#2076]
Hi all! :wave:

It has been suggested previously that it would make sense for me to join the build WG, as I frequently request access in order to debug flaky tests or other CI issues.

I’m actually happy with the current situation, and I’d personally also quite like a solution where there’s an understanding that I can just feel feel free to ping @rvagg or @Trott or somebody else from @nodejs/build to get keys for hosts and then remove then when I’m done, without much extra process around that. I probably won’t have time to engage in “real” build WG work. But I also understand that that comes with some overhead for those that I need to ping.

I think the prerequisites listed in `access.md` are fulfilled. I hope it isn’t a bold statement to say that I’ve demonstrated technical competence around the project and have an established relationship with it :) As for my employment situation, I’m currently a contractor for NearForm, which is a foundation member company.

**Comment by richardlau** [comment]
+1

It's also possible to be granted ongoing access without joining the WG (https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md#ongoing-access).

**Comment by gireeshpunathil** [comment]
+1

**Comment by addaleax** [comment]
> It's also possible to be granted ongoing access without joining the WG (https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md#ongoing-access).

Yeah, that would work just as well for me I guess. I think it would make sense to have access to most hosts used in our regular CI, though.

**Comment by sam-github** [comment]
+1

build-wg membership doesn't come with any mandatory expectations (other than not misusing credentials or carelessly breaking things), its a direct way to indicate that you are trusted to access CI build resources, and that you semi-regularly have need of that access for various reasons.

**Comment by gireeshpunathil** [comment]
here is a `precedence`, if it helps - I joined the WG with same / similar objective. https://github.com/nodejs/build/pull/1641

**Comment by Trott** [comment]
+1 let's make this happen

**Comment by gdams** [comment]
+1 from me!

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
Just to add we may want to formalize this kind of "joining the build wg" and document on the Readme who is a member for access reasons versus helping to maintain the infrastructure.

**Comment by addaleax** [comment]
Assuming that there are no objections until then, could we maybe do the onboarding next week in Montreal? That might be easiest for everyone.

**Comment by sam-github** [comment]
I'll be there, there's an ONBOARDING.md, looks straight-forward, I can walk through it with you @addaleax

**Comment by joaocgreis** [comment]
+1

Happy to help if you need Windows access - secrets are currently outdated as I'm working on the machines but will be done in a few days.

**Comment by addaleax** [comment]
@joaocgreis Thanks, I’ll ping you when it comes up :)
