### ISSUE TITLE
Reprovision the linuxone s390x machines

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2080]
The current linuxone machines `*-rhel72-s390x-*` will be switched off in the new year and we are being migrated to a new data (EDIT(sam): "new datacentre's") machines

We have been given access to the five replacement machines and work is being undertaken to ansible them and set them up for ci

**Comment by AshCripps** [comment]
All five machine have been ansibled and a build+test passes.

Next steps:

- [ ] Add machines to Jenkins
- [ ] Test builds pass on the release and test machines
- [ ] Begin to switch over the jobs to these new machines (will need new jobs I think)
- [ ] Deprovision to old s390x machines as they will be turned off by the end of the year

**Comment by richardlau** [comment]
>  - [ ] Begin to switch over the jobs to these new machines (will need new jobs I think)

We shouldn't need new jobs.

**Comment by sam-github** [comment]
online:
- https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-1/
- https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-2/
- https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-3/
- https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-4/
- https://ci-release.nodejs.org/computer/release-ibm-rhel7-s390x-1/

**Comment by sam-github** [comment]
build: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/1/nodes=rhel7-s390x/

**Comment by sam-github** [comment]
Note: need to change the /data reference to:
> /home/iojs/git/io.js.reference

in the main job when I switch the labels.

**Comment by sam-github** [comment]
- 14.x: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/6/
- 13.x: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/7/
- 12.x: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/8/

Failed:
```
10:03:04 Started by upstream project "node-test-commit-linuxone-sam-github" build number 8
10:03:04 originally caused by:
10:03:04  Started by user Sam Roberts
10:03:04 Running as SYSTEM
10:03:04 [EnvInject] - Loading node environment variables.
10:03:04 Building remotely on test-ibm-rhel7-s390x-4 (7.7 s390x-RedHatEnterprise RedHatEnterprise-7.7 rhel7-s390x s390x-RedHatEnterprise-7.7 RedHatEnterprise s390x) in workspace /home/iojs/build/workspace/node-test-commit-linuxone-sam-github/nodes/rhel7-s390x
10:03:04 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 148.100.86.94/148.100.86.94:38882
10:03:04 java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy11
10:03:04 Caused: java.io.IOException: Remote call on JNLP4-connect connection from 148.100.86.94/148.100.86.94:38882 failed
```

Tried again, I think https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-4 is broken, taking it offline.

**Comment by sam-github** [comment]
master failed: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/1/nodes=rhel7-s390x/testReport/junit/(root)/test/sequential_test_cpu_prof_worker_argv/

I suspect a flaky test, retrying.

**Comment by sam-github** [comment]
- 12.x: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/10/ PASS
- 14.x: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/11/ PASS
- 8.x: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/12/
- 10.x: https://ci.nodejs.org/job/node-test-commit-linuxone-sam-github/13/

ci-release:
- 13.5.0: https://ci-release.nodejs.org/job/iojs+release-sam-github/1/

If builds are PASS on all the machines, I will change the build label in node-test-commit-linuxone from `rhel72-s390x` to `rhel7-s390x`. Once that's green for a while, we'll remove the old machines.

**Comment by richardlau** [comment]
> If builds are PASS on all the machines, I will change the build label in node-test-commit-linuxone from `rhel72-s390x` to `rhel7-s390x`. Once that's green for a while, we'll remove the old machines.

We will need to update the other jobs that build on Linux One (e.g. CITGM, libuv, V8, node-addons-api) before removing the old machines. I can start updating some of those in a few hours time.

**Comment by sam-github** [comment]
Thanks for the reminder, and that'd be great, thanks.

Switch node-test-commit-linuxone to the new machines:
- master: https://ci.nodejs.org/view/All/job/node-test-commit-linuxone/17833/

**Comment by richardlau** [comment]
Updated:
 - https://ci.nodejs.org/job/node-stress-single-test/
https://ci.nodejs.org/job/node-stress-single-test/jobConfigHistory/showDiffFiles?timestamp1=2019-12-17_22-42-48&timestamp2=2019-12-18_19-11-38
Test build: https://ci.nodejs.org/job/node-stress-single-test/27/nodes=rhel7-s390x/

**Comment by richardlau** [comment]
- https://ci.nodejs.org/job/node-test-commit-v8-linux/
I added a `v8test` label to https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-1/ otherwise the build wouldn't schedule onto any nodes.
Test build: https://ci.nodejs.org/job/node-test-commit-v8-linux/nodes=rhel7-s390x,v8test=v8test/2713/

**Comment by richardlau** [comment]
- https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration-latest/
Test build: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration-latest/50/

**Comment by richardlau** [comment]
- https://ci.nodejs.org/job/node-test-node-addon-api-new/
https://ci.nodejs.org/job/node-test-node-addon-api-new/jobConfigHistory/showDiffFiles?timestamp1=2019-12-11_16-01-45&timestamp2=2019-12-18_19-38-08
Test build: https://ci.nodejs.org/job/node-test-node-addon-api-new/1415/nodes=rhel7-s390x/

**Comment by richardlau** [comment]
- https://ci.nodejs.org/job/libuv-test-commit-linux/
Test build: https://ci.nodejs.org/job/libuv-test-commit-linux/1718/nodes=rhel7-s390x/
Looks like some tests failed that weren't seen before:
```console
not ok 348 - udp_multicast_join
# timeout
# Output from process `udp_multicast_join`: (no output)
not ok 349 - udp_multicast_join6
# timeout
# Output from process `udp_multicast_join6`: (no output)
```
Firewall config? cc @AshCripps @sam-github 
FYI @nodejs/libuv

**Comment by richardlau** [comment]
> 
> 
>     * https://ci.nodejs.org/job/libuv-test-commit-linux/
>       Test build: https://ci.nodejs.org/job/libuv-test-commit-linux/1718/nodes=rhel7-s390x/
>       Looks like some tests failed that weren't seen before:
> 
> 
> ```
> not ok 348 - udp_multicast_join
> # timeout
> # Output from process `udp_multicast_join`: (no output)
> not ok 349 - udp_multicast_join6
> # timeout
> # Output from process `udp_multicast_join6`: (no output)
> ```
> 
> Firewall config? cc @AshCripps @sam-github
> FYI @nodejs/libuv

Looks like we (=@miladfarca) tweaked something on the old machines: https://github.com/libuv/libuv/pull/2185#issuecomment-467290846

**Comment by AshCripps** [comment]
@richardlau thought it had to be there for areason. I can back the rules to the ansible, ill pr them in shortly.

I know they failed because the dest file `/etc/sysconfig/iptables` doesnt exist on the machines so Ill need to create it first

**Comment by AshCripps** [comment]
So ive been able to add the rules back to the ansible and the files gets updated. 
I had to the create the file using `iptables-save`

issue is now I cant restart iptables to get the rules to take effects because iptables.service is not running. From a quick google iptables.service doesnt run by defaults because firewalld is used instead so I have to install a yum package to get the service.

This is getting beyond my depth so I was wondering if anyone else had any idea or knows if Im missing anything else?

**Comment by richardlau** [comment]
The V8 job has socket time outs on the new machines (https://github.com/nodejs/build/issues/2080#issuecomment-567272844). Does anyone (@nodejs/v8-update @nodejs/platform-s390 ?) know if the `v8test` label that is on https://ci.nodejs.org/computer/test-linuxonecc-rhel72-s390x-1/ implies any additional set up that was done there that we would need to replicate to the new machines?

**Comment by sam-github** [comment]
For the v8 builds, it looks like gn and ninja need copying to all the rhel-s390x hosts. We generally do this by packing the redistributables into a package and putting them on the ci download host, but that takes infra privs. Efforts are underway by @miladfarca to get the upstream google projects to include these binaries, at which point this won't be necessary anymore.

The old machines look like:
```
% parallel-ssh -h hosts/rhel72-s390x -i ls -l '/home/iojs/build-tools/{gn,ninja}'
[1] 08:19:15 [SUCCESS] test-linuxonecc-rhel72-s390x-2
-rwx--xr-x 1 root root 4116371 Apr  3  2018 /home/iojs/build-tools/gn
-rwxr-xr-x 1 root root 3448520 Apr  3  2018 /home/iojs/build-tools/ninja
[2] 08:19:15 [FAILURE] test-linuxonecc-rhel72-s390x-3 Exited with error code 2
Stderr: ls: cannot access /home/iojs/build-tools/gn: No such file or directory
ls: cannot access /home/iojs/build-tools/ninja: No such file or directory
[3] 08:19:15 [SUCCESS] test-linuxonecc-rhel72-s390x-1
lrwxrwxrwx 1 iojs iojs      20 Aug  9 16:50 /home/iojs/build-tools/gn -> /data/iojs/gn/out/gn
-rwxr-xr-x 1 root root 3448520 Apr  3  2018 /home/iojs/build-tools/ninja
```

**Comment by richardlau** [comment]
I'll try to update the CITGM jobs later this evening (which are the remaining jobs that I know of -- please comment if there are any that have been missed).

**Comment by sam-github** [comment]
I copied the build-tools directory from `test-linuxonecc-rhel72-s390x-2` onto `test-ibm-rhel7-s390x-*`. That should unblock this for now, but the gn and ninja binaries should be curled, put into the infrastructure downloads, and ansibled.

**Comment by richardlau** [comment]
> 
> 
> I copied the build-tools directory from `test-linuxonecc-rhel72-s390x-2` onto `test-ibm-rhel7-s390x-*`. That should unblock this for now, but the gn and ninja binaries should be curled, put into the infrastructure downloads, and ansibled.

Thanks. Started another test build: https://ci.nodejs.org/job/node-test-commit-v8-linux/2717/

**Comment by richardlau** [comment]
> 
> 
> > I copied the build-tools directory from `test-linuxonecc-rhel72-s390x-2` onto `test-ibm-rhel7-s390x-*`. That should unblock this for now, but the gn and ninja binaries should be curled, put into the infrastructure downloads, and ansibled.
> 
> Thanks. Started another test build: https://ci.nodejs.org/job/node-test-commit-v8-linux/2717/

Unfortunately this has also failed with socket time outs.

**Comment by sam-github** [comment]
That sounds like a symptom of https://github.com/nodejs/build/pull/2104, @AshCripps has a plan there, he thinks he's found the right way to switch the systems from firewalld to iptables.

**Comment by richardlau** [comment]
> 
> 
> That sounds like a symptom of #2104, @AshCripps has a plan there, he thinks he's found the right way to switch the systems from firewalld to iptables.

If it helps, we remove firewalld on centos and fedora: https://github.com/nodejs/build/pull/1879
Looks like we used to tweak firewalld rules on fedora but dropped it in https://github.com/nodejs/build/pull/1977

**Comment by sam-github** [comment]
That does help. If that's what we do for them, I think we should do the same for rhel, to avoid gratuitous differences between redhat derived distros.

**Comment by richardlau** [comment]
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/
Test build: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/697/nodes=rhel7-s390x/ (looks okay)
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/
Test build: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2146/ (pending)

**Comment by AshCripps** [comment]
ive updated https://github.com/nodejs/build/pull/2104 with a fix (I think) for the iptables issue.

@richardlau can you kick off a build for me to test? I have reansibled the machines already

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/libuv-test-commit-linux/1721/nodes=rhel7-s390x/ (✔️ 🎉)

https://ci.nodejs.org/job/node-test-commit-v8-linux/2722/nodes=rhel7-s390x,v8test=v8test (in progress)

**Comment by AshCripps** [comment]
I pretty stumped with the socket time outs, no idea whats causing them or where to start looking for the cause.

**Comment by richardlau** [comment]
Me neither. Just as a further check, I've swapped the `v8test` label from `test-ibm-rhel7-s390x-1` to `test-ibm-rhel7-s390x-3` to check the results are consistent when run on one of the other hosts (we expect them to be the same).
Test build: https://ci.nodejs.org/job/node-test-commit-v8-linux/nodes=rhel7-s390x,v8test=v8test/2723/

**Comment by richardlau** [comment]
Okay, that was unexpected... the job still fails on -3 but it failed in a different way to the runs on -1:
```console
14:37:11 ERROR at //BUILD.gn:1108:14: Unknown function.
14:37:11     filetq = string_replace(file, ".tq", "-tq-csa")
14:37:11              ^-------------
14:37:11 Makefile:292: recipe for target 'v8' failed
14:37:11 make: *** [v8] Error 1
```

**Comment by richardlau** [comment]
Let's try `test-ibm-rhel7-s390x-2` and see if there's any consistency between the three new machines: https://ci.nodejs.org/job/node-test-commit-v8-linux/2725/nodes=rhel7-s390x,v8test=v8test/

**Comment by richardlau** [comment]
Behaviour on `test-ibm-rhel7-s390x-2` and `test-ibm-rhel7-s390x-3` is consistent... no idea why we have socket time outs on `test-ibm-rhel7-s390x-1`.

Without knowing more about the V8 builds the `Unknown function` error might suggest an issue with `gn`? We copied the binaries from the old machines... but are we using them?

**Comment by richardlau** [comment]
> 
> 
> I copied the build-tools directory from `test-linuxonecc-rhel72-s390x-2` onto `test-ibm-rhel7-s390x-*`. That should unblock this for now, but the gn and ninja binaries should be curled, put into the infrastructure downloads, and ansibled.

I think it's an issue with the gn binaries:

On `test-linuxonecc-rhel72-s390x-1` (which has the `v8test` label and is the old machine where the V8 tests run):
```console
[iojs@test-linuxonecc-rhel72-s390x-1 ~]$ ls -al build-tools
total 8724
drwxrwxr-x  3 iojs iojs    4096 Dec 20 15:21 .
drwx------ 34 iojs iojs    4096 Dec 20 15:41 ..
lrwxrwxrwx  1 iojs iojs      56 Dec 20 15:21 g++ -> /opt/rh/devtoolset-6/root/usr/bin/s390x-redhat-linux-g++
lrwxrwxrwx  1 iojs iojs      56 Dec 20 15:21 gcc -> /opt/rh/devtoolset-6/root/usr/bin/s390x-redhat-linux-gcc
lrwxrwxrwx  1 iojs iojs      20 Aug  9 16:50 gn -> /data/iojs/gn/out/gn
-rwx--xr-x  1 iojs iojs 5346736 May 28  2018 gn.unknown
-rwxr-xr-x  1 root root  118128 Apr  3  2018 libatomic.so.1
-rw-rw-r--  1 iojs iojs     733 Oct 16  2018 make-v8.patch
-rwxr-xr-x  1 root root 3448520 Apr  3  2018 ninja
drwxr-xr-x  2 iojs iojs    4096 May 28  2018 pkg-config
[iojs@test-linuxonecc-rhel72-s390x-1 ~]$ build-tools/gn --version
1620 (570aaed)
[iojs@test-linuxonecc-rhel72-s390x-1 ~]$
```

On `test-linuxonecc-rhel72-s390x-2`:
```console
[iojs@test-linuxonecc-rhel72-s390x-2 ~]$ ls -al build-tools
total 7512
drwxrwxr-x  2 iojs iojs    4096 Apr  3  2018 .
drwx------ 36 iojs iojs    4096 Dec 19 19:24 ..
-rwx--xr-x  1 root root 4116371 Apr  3  2018 gn
-rwxr-xr-x  1 root root  118128 Apr  3  2018 libatomic.so.1
-rwxr-xr-x  1 root root 3448520 Apr  3  2018 ninja
[iojs@test-linuxonecc-rhel72-s390x-2 ~]$ build-tools/gn --version
UNKNOWN
[iojs@test-linuxonecc-rhel72-s390x-2 ~]$
```

On `test-ibm-rhel7-s390x-2`:
```console
[iojs@test-ibm-rhel7-s390x-2 ~]$ ls -al build-tools
total 7512
drwxrwxr-x  2 iojs iojs    4096 Dec 20 15:05 .
drwx------ 13 iojs iojs    4096 Dec 20 15:05 ..
lrwxrwxrwx  1 iojs iojs      56 Dec 20 15:05 g++ -> /opt/rh/devtoolset-6/root/usr/bin/s390x-redhat-linux-g++
lrwxrwxrwx  1 iojs iojs      56 Dec 20 15:05 gcc -> /opt/rh/devtoolset-6/root/usr/bin/s390x-redhat-linux-gcc
-rwx--xr-x  1 iojs iojs 4116371 Apr  3  2018 gn
-rwxr-xr-x  1 iojs iojs  118128 Apr  3  2018 libatomic.so.1
-rwxr-xr-x  1 iojs iojs 3448520 Apr  3  2018 ninja
[iojs@test-ibm-rhel7-s390x-2 ~]$ build-tools/gn --version
UNKNOWN
[iojs@test-ibm-rhel7-s390x-2 ~]$
```

**Comment by richardlau** [comment]
Looks like we updated `gn` in https://github.com/nodejs/build/issues/1881 on `test-linuxonecc-rhel72-s390x-1`.

**Comment by richardlau** [comment]
I've renamed `build-tools/gn` to `build-tools/gn.unknown` on `test-linuxonecc-rhel72-s390x-2` and copied across the `gn` binary from `test-linuxonecc-rhel72-s390x-1`.

Build now gets further but still fails:
https://ci.nodejs.org/job/node-test-commit-v8-linux/2726/nodes=rhel7-s390x,v8test=v8test/console
```console
17:08:46 ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
17:08:46     pkgresult = exec_script(pkg_config_script, args, "value")
17:08:46                 ^----------
17:08:46 Current dir: /data/iojs/build/workspace/node-test-commit-v8-linux/nodes/rhel7-s390x/v8test/v8test/deps/v8/out.gn/s390x.release/
17:08:46 Command: python /data/iojs/build/workspace/node-test-commit-v8-linux/nodes/rhel7-s390x/v8test/v8test/deps/v8/build/config/linux/pkg-config.py glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
17:08:46 Returned 1.
17:08:46 stderr:
17:08:46 
17:08:46 Package glib-2.0 was not found in the pkg-config search path.
17:08:46 Perhaps you should add the directory containing `glib-2.0.pc'
17:08:46 to the PKG_CONFIG_PATH environment variable
17:08:46 No package 'glib-2.0' found
17:08:46 Package gmodule-2.0 was not found in the pkg-config search path.
17:08:46 Perhaps you should add the directory containing `gmodule-2.0.pc'
17:08:46 to the PKG_CONFIG_PATH environment variable
17:08:46 No package 'gmodule-2.0' found
17:08:46 Package gobject-2.0 was not found in the pkg-config search path.
17:08:46 Perhaps you should add the directory containing `gobject-2.0.pc'
17:08:46 to the PKG_CONFIG_PATH environment variable
17:08:46 No package 'gobject-2.0' found
17:08:46 Package gthread-2.0 was not found in the pkg-config search path.
17:08:46 Perhaps you should add the directory containing `gthread-2.0.pc'
17:08:46 to the PKG_CONFIG_PATH environment variable
17:08:46 No package 'gthread-2.0' found
17:08:46 Could not run pkg-config.
17:08:46 
17:08:46 See //build/config/linux/BUILD.gn:89:3: whence it was called.
17:08:46   pkg_config("glib") {
17:08:46   ^-------------------
17:08:46 See //build/config/compiler/BUILD.gn:250:18: which caused the file to be included.
17:08:46     configs += [ "//build/config/linux:compiler" ]
17:08:46                  ^------------------------------
17:08:46 Makefile:292: recipe for target 'v8' failed
```

**Comment by AshCripps** [comment]
Ive atttempted to build `gn` from source on `test-ibm-rhel7-s390x-3` but am getting some failures:

```
[iojs@test-ibm-rhel7-s390x-3 gn]$ CC=gcc CXX=g++ python build/gen.py
[iojs@test-ibm-rhel7-s390x-3 gn]$ ninja -C out
ninja: Entering directory `out'
[1/256] CXX src/base/environment.o
FAILED: src/base/environment.o
g++ -MMD -MF src/base/environment.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/base/environment.cc -o src/base/environment.o
In file included from ../src/base/environment.cc:5:0:
../src/base/environment.h:11:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
[2/256] CXX src/base/files/file_path.o
FAILED: src/base/files/file_path.o
g++ -MMD -MF src/base/files/file_path.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/base/files/file_path.cc -o src/base/files/file_path.o
In file included from ../src/base/files/file_path.cc:5:0:
../src/base/files/file_path.h:109:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
[3/256] CXX src/base/command_line.o
FAILED: src/base/command_line.o
g++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/base/command_line.cc -o src/base/command_line.o
In file included from ../src/base/command_line.cc:5:0:
../src/base/command_line.h:21:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
[4/256] CXX src/gn/inherited_libraries.o
FAILED: src/gn/inherited_libraries.o
g++ -MMD -MF src/gn/inherited_libraries.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/gn/inherited_libraries.cc -o src/gn/inherited_libraries.o
In file included from ../src/gn/target.h:13:0,
                 from ../src/gn/inherited_libraries.cc:7:
../src/base/logging.h:14:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
[5/256] CXX src/base/files/file.o
FAILED: src/base/files/file.o
g++ -MMD -MF src/base/files/file.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/base/files/file.cc -o src/base/files/file.o
In file included from ../src/base/files/file.h:12:0,
                 from ../src/base/files/file.cc:5:
../src/base/files/file_path.h:109:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
[6/256] CXX src/base/files/file_enumerator.o
FAILED: src/base/files/file_enumerator.o
g++ -MMD -MF src/base/files/file_enumerator.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -std=c++17 -c ../src/base/files/file_enumerator.cc -o src/base/files/file_enumerator.o
In file included from ../src/base/containers/vector_buffer.h:14:0,
                 from ../src/base/containers/circular_deque.h:14,
                 from ../src/base/containers/stack.h:10,
                 from ../src/base/files/file_enumerator.h:13,
                 from ../src/base/files/file_enumerator.cc:5:
../src/base/logging.h:14:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
ninja: build stopped: subcommand failed.
[iojs@test-ibm-rhel7-s390x-3 gn]$
```

I also ran `export PATH=/home/iojs/build-tools:$PATH` to make sure it was using the gcc6 and g++6 in the build tools directory

**Comment by richardlau** [comment]
https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017 says `string_view` was implemented in gcc 7.1.

**Comment by AshCripps** [comment]
> https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017 says `string_view` was implemented in gcc 7.1.

ah of course.

I guess this means I need to build gcc 7.1 on that machine? or is it worth building a higher version?

**Comment by richardlau** [comment]
> > https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017 says `string_view` was implemented in gcc 7.1.
> 
> ah of course.
> 
> I guess this means I need to build gcc 7.1 on that machine? or is it worth building a higher version?

If they’re available on s390x I would prefer we used a later devtoolset (7/8) rather than building gcc ourselves.

**Comment by sam-github** [comment]
I guess you checked, and there are no packages?

**Comment by AshCripps** [comment]
> If they’re available on s390x I would prefer we used a later devtoolset (7/8) rather than building gcc ourselves.

Ah yes forgot about devtoolset no idea where to look for that I seem to remember @rsam saying its a subscription thing you have to login to to get it

**Comment by richardlau** [comment]
> 
> 
> > If they’re available on s390x I would prefer we used a later devtoolset (7/8) rather than building gcc ourselves.
> 
> Ah yes forgot about devtoolset no idea where to look for that I seem to remember @rsam saying its a subscription thing you have to login to to get it

I think from memory @miladfarca was involved in getting devtoolset-6 onto the old s390x machines.

**Comment by AshCripps** [comment]
> Tried again, I think https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-4 is broken, taking it offline.

@rsam Had a discussion with @sxa555 and we couldn't see anything wrong with `-4` asides from a connection issues so I restarted the agent and ran a build on it which passed - https://ci.nodejs.org/view/All/job/node-test-commit-linuxone-sam-github/15/nodes=rhel7-s390x4/

**Comment by richardlau** [comment]
Reopening as the issue(s) build/testing V8 are still to be resolved.

**Comment by AshCripps** [comment]
whoops hit the wrong button

**Comment by richardlau** [comment]
> 
> 
> whoops hit the wrong button

I don't think you did -- GitHub autoclosed because https://github.com/nodejs/build/pull/2104 had a "fixes" line.

**Comment by miladfarca** [comment]
devtoolset packages are only available through Redhat. devtoolset-6 RPMs can be located on box, I have sent invites, they can be installed using `yum`. Regarding the details of devtoolset and how you can access other versions and install/use them, look under issue number `11` in our internal node zenhub page, I have added some details some time ago.

GN has started using C++17 features since around Sep and needs gcc >=7 to compile. You can use any machine with devtoolset to compile and copy the binary. Seems like the latest GN on the other s390 machines is working. We are working on adding cross compiled GN to devtoolset natively.

Regarding the  V8 failure messages, make sure you have all the pre-req packages installed (i.e pkg-config) and your env variable are set accordingly, here are the packages we install on our Ubuntu test boxes:
```
pkg-config 
libnss3-dev 
libcups2-dev 
libglib2.0-dev 
libpango1.0-dev 
libgconf2-dev
libgnome-keyring-dev
libatk1.0-dev
libgtk-3-dev
```

**Comment by AshCripps** [comment]
> ```
> pkg-config 
> libnss3-dev 
> libcups2-dev 
> libglib2.0-dev 
> libpango1.0-dev 
> libgconf2-dev
> libgnome-keyring-dev
> libatk1.0-dev
> libgtk-3-dev
> ```

I found libgconf2 was missing, when installed it installed glib as well. kicked off a build to test - https://ci.nodejs.org/job/node-test-commit-v8-linux/2746/

**Comment by AshCripps** [comment]
I have disabled the three old machines in jenkins, waiting to see if theres any fallout before deleting them but all jobs should be using the new rhel7-s390x labeled machines

**Comment by sam-github** [comment]
Took the old rhel s390x machine offline in ci-release.

The last step I need someone from @nodejs/releasers to check: is the release ssh key setup correctly?

Please try:
```
ssh release-ibm-rhel7-s390x-1
```

I'm not on releasers, so I don't have the private key, so I can't confirm. I can ssh in use the IBM mgmt key, so I copied the authorized ssh key from the AIX machines.

I think that's all the release specific setup needed.

**Comment by targos** [comment]
Releasers don't ssh into release machines. I'm not aware of having access to any of the existing ones

**Comment by sam-github** [comment]
I looked more closely, it looks like the only people with ssh access to _all_ the release machines are:
```
% ls .gpg 
'bugs@bergstroem.nu'         'reis@janeasystems.com'
'michael_dawson@ca.ibm.com'  'rod@vagg.org'
```
@jbergstroem @joaocgreis @rvagg @mhdawson --- can one of you confirm that `ssh release-ibm-rhel7-s390x-1` works for you with the `nodejs_build_release` private key?

**Comment by joaocgreis** [comment]
@sam-github it does not work for me (other release servers work though).

**Comment by sam-github** [comment]
@joaocgreis do you think you could fix that? I'm not a member of the releasers team, so I don't have access to the secrets, so I'm not in a great position to put those secrets on the machine. If my copy of the .ssh authorized keys across didn't work, I'm not sure what else I can do.

**Comment by sam-github** [comment]
@joaocgreis contacted me offline, and helped get the correct releasers key onto the release box, so any with release infrastructure access should be able to ssh in.

**Comment by mhdawson** [comment]
@sam-github ssh-d into the the release rhel7 with the nodejs_build_release key.

**Comment by sam-github** [comment]
I removed the unused https://ci-release.nodejs.org/computer/release-linuxonecc-rhel72-s390x-1/

**Comment by sam-github** [comment]
https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-1/ -- does anybody know where the labels come from?

`rhel7-s390x` is explicitly configured in https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-1/configure, and it is used, all the others are unused (they have no jobs  that use them). I was going to clean up the unused lables, but I don't see how. Its messy and confusing, but it doesn't cause any operational problems.

**Comment by sam-github** [comment]
Nothing left to do, the label cleanup is unrelated tidying.

**Comment by richardlau** [comment]
> 
> 
> https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-1/ -- does anybody know where the labels come from?
> 
> `rhel7-s390x` is explicitly configured in https://ci.nodejs.org/computer/test-ibm-rhel7-s390x-1/configure, and it is used, all the others are unused (they have no jobs that use them). I was going to clean up the unused lables, but I don't see how. Its messy and confusing, but it doesn't cause any operational problems.

I think they're coming from this plugin: https://github.com/jenkinsci/platformlabeler-plugin

**Comment by sam-github** [comment]
@richardlau OK, that makes sense. I'll assume we are using that.

**Comment by richardlau** [comment]
> 
> 
> @richardlau OK, that makes sense. I'll assume we are using that.

We are. When I first posted I was searching through the list of plugins installed in our Jenkins for the word `label` and picked out the most plausible sounding one (after reading the description on the linked page). I've subsequently found the configuration page where it's enabled and posted the screenshot as an edit to my previous comment.
