### ISSUE TITLE
Access to test-joyent-smartos18-x64-3

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#2091]
May I please have access to this machine? I need to debug an issue with node-addon-api (https://ci.nodejs.org/job/node-test-node-addon-api-new/1352/nodes=smartos18-64/console).

**Comment by gabrielschulhof** [comment]
Nevermind. @addaleax is already working on it.

**Comment by addaleax** [comment]
For future reference, https://github.com/nodejs/node/pull/30946 should address this
