### ISSUE TITLE
Update tap2junit from 0.1.4 to 0.1.5

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2092]
tap2junit 0.1.5 fixes bugs and introduces Python 3 compatibility. Can we please update?

Refs: https://github.com/nodejs/node/pull/30955#issuecomment-565689107
Maybe Refs: https://github.com/nodejs/build/issues/1847
Maybe Refs: https://github.com/nodejs/build/issues/1756
Maybe Refs: https://github.com/nodejs/build/issues/1830

**Comment by Trott** [comment]
@sam-github

**Comment by sam-github** [comment]
Work items (volunteers welcome, a number of the items below do not require build-wg membership):
- [ ] Find out how tap2junit is installed: ... (ansible on most hosts)
- [ ] Figure out if it is installed at a specific version: ... (probably its just latest at time of ansible run, but there might be a py3 and a py2 install, or possibly changes will be needed to install with both pip and pip3)
- [ ] Modify ansible files: ... (if necessary, maybe they just need re-running)
- [ ] List hosts that require update: ... (perhaps all `test-*` hosts, but we never bulk update every single host simultaneously, carnage is too likely)
- [ ] Re-ansible the hosts: ... (some hosts have been ansibled more recently than others, so this can be a bit of a nail biter, the hosts have to be checked after to ensure they still function, and sometimes the ansbile scripts don't run anymore, and troubleshooting ensues)

**Comment by richardlau** [comment]
> 
> 
> Work items (volunteers welcome, a number of the items below do not require build-wg membership):
> 
>     * [ ]  Find out how tap2junit is installed: ... (ansible on most hosts)
> 
>     * [ ]  Figure out if it is installed at a specific version: ... (probably its just latest at time of ansible run, but there might be a py3 and a py2 install, or possibly changes will be needed to install with both pip and pip3)
> 
>     * [ ]  Modify ansible files: ... (if necessary, maybe they just need re-running)

For ansinle there's several files in https://github.com/nodejs/build/tree/master/ansible/roles/jenkins-worker/tasks/partials/tap2junit

**Comment by Trott** [comment]
I updated it manually, so I'm inclined to close this. Re-open if you think it should remain open.
