### ISSUE TITLE
Broken Lite-CI

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#2093]
Our Lite-CI is currently not able to fetch origin.

E.g., https://ci.nodejs.org/job/node-test-pull-request-lite-pipeline/4110/console

**Comment by addaleax** [comment]
Suggestion: Just formalize https://github.com/nodejs/node/issues/29770 and scrap this job?

**Comment by richardlau** [comment]
> 
> 
> Suggestion: Just formalize [nodejs/node#29770](https://github.com/nodejs/node/issues/29770) and scrap this job?

It was formalized in https://github.com/nodejs/node/pull/30330?

**Comment by addaleax** [comment]
@richardlau Sorry for the confusion, there was no visible connection between the two on Github :) Can we close nodejs/node#29770 then?

**Comment by richardlau** [comment]
@addaleax There's still the issue of updating `node-core-utils` which I think will complain if it doesn't detect a full or lite CI. And probably https://github.com/nodejs/node/pull/29783 should land on `10.x` before we delete the pipeline job on the off chance a doc-only PR needs to land on `10.x`. 

I've no preference as to whether https://github.com/nodejs/node/issues/29770 is kept open to track those, or closed and new issues opened for the remainder.
