### ISSUE TITLE
Multiple releases tomorrow

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2094]
Running in CI right now and already hitting some infra issues. Is someone able to pair with me to get this out the door?

**Comment by sam-github** [comment]
I will be free in 30 min, though my infra knowlege is fairly system specific, do you have links to the broken builds?

**Comment by sam-github** [comment]
@MylesBorins still need help? I'm available.

**Comment by MylesBorins** [comment]
Having issues with pi1-docker for build on release ci... no workers are online.
