### ISSUE TITLE
Test results not visible in Jenkins for node-test-commit-osx

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2096]
https://ci.nodejs.org/job/node-test-commit-osx/ is not correctly publishing test results because of the following inconsistency between the test xml files being written and the ones being searched for to upload:
![image](https://user-images.githubusercontent.com/5445507/70951803-54cca800-205c-11ea-8bac-2058c3667c02.png)

I'll change the `Test report XMLs` from `*.junit.xml` to `out/junit/*.xml` after the security releases go out tomorrow.

**Comment by richardlau** [comment]
Made the change. Test build: https://ci.nodejs.org/job/node-test-commit-osx/30811/nodes=osx1011/

**Comment by richardlau** [comment]
Test results from the JavaScript tests are uploaded (🎉), but the cctest results are not (😞). It looks like on macOS we are running `make distclean` (see screenshot in original post), I believe to keep the workspace size down, and this wipes out the `out` directory where the cctest results were written.

**Comment by rvagg** [comment]
distclean does a `$(RM) -r out`, maybe we just move them to the top level before running the distclean?

**Comment by richardlau** [comment]
Moved the cctest xml to top level before running distclean. Changed the tap2junit commands to write to the top level (instead of out/junit).

Test build: https://ci.nodejs.org/job/node-test-commit-osx/30845/nodes=osx1011/

**Comment by richardlau** [comment]
Looks good now.
