### ISSUE TITLE
Docker Webhook

### ISSUE THREAD

**Issue by retrohacker** [nodejs/build#21]
CI servers should respond to a notification that a docker image [iojs/build](https://registry.hub.docker.com/u/iojs/build) has been pushed to on the docker registry. This will keep our containers on the CI servers in sync with the docker registry and in turn with our github repos.

What is needed:

Implement a webhook endpoint for the repository and have it initiate a `docker pull iojs` when hit. Then register the endpoint at: https://registry.hub.docker.com/u/iojs/build/settings/webhooks/

Should work on >1 server.

**Comment by jbergstroem** [comment]
Is this still relevant? We currently have no docker instances running tests.

**Comment by retrohacker** [comment]
I would like it to be. We still have it blocking a few issues in the docker project (mainly an alpine variant of our images).

I could look into a travis-ci build process to simplify the maintance if that is acceptable.

**Comment by jbergstroem** [comment]
Is this for running tests inside a docker host for alpine? That'd be awesome to have and we've definitely got room for it. Are there scripts somewhere that helps us set it up via ansible?

**Comment by retrohacker** [comment]
Ah, sorry, should have given more detail.

The nodejs/Docker group is interested in exploring an alpine image. Since alpine isn't explicitly tested for by the Node project, we want to have automated testing in place for that docker image to ensure the runtime works properly in that environment.

This was the original motivation for building [Dante](github.com/retrohacker/dante). We don't have an ansible script for it, but the workflow is this:

(On PR)
1. Checkout repo
2. Run `dante test` in base directory of repo 
3. If Dante returns 0, pass. If 1, fail.

All logs from dante go to stdout.

**Comment by maclover7** [comment]
ping -- is this still needed?
