### ISSUE TITLE
arm: warning: failed to remove out/Release/.nfs*: Device or resource busy

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2102]
node-test-binary-arm-12+ builds on
https://ci.nodejs.org/computer/test-requireio_sambthompson-debian10-armv7l_pi2-1/
https://ci.nodejs.org/computer/test-requireio_williamkapke-debian10-arm64_pi3-1/

are failing with, e.g. https://ci.nodejs.org/job/node-test-binary-arm-12+/3329/RUN_SUBSET=0,label=pi2-docker/console
```console
17:22:47 + git clean -fdx
17:22:56 warning: failed to remove out/Release/.nfs0000000000503bed000009f9: Device or resource busy
17:22:56 Removing out/junit
17:22:56 
17:22:56 real	0m9.727s
17:22:56 user	0m0.489s
17:22:56 sys	0m2.380s
17:22:57 Build step 'Execute shell' marked build as failure
```

Marking the two hosts offline for now.

cc @rvagg

**Comment by rvagg** [comment]
The way to deal with these nfs errors is to restart the hosts and cross your fingers, they're unusable anyway and if they don't come back up then you haven't lost anything.

I've restarted them and they came back online OK so I've marked them online again.
