### ISSUE TITLE
Access to test-digitalocean-freebsd11-x64-2

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#2103]
May I please have access to this machine? I need it to investigate the failure at https://ci.nodejs.org/job/node-test-commit-freebsd/30300/nodes=freebsd11-x64/console

**Comment by sam-github** [comment]
@gabrielschulhof https://github.com/gabrielschulhof.keys added to host you asked for. Ping here when you are done.

**Comment by gabrielschulhof** [comment]
@sam-github @devnexen already fixed the problem. Sorry for the superfluous request, and thank you for adding my key. Please remove it!

**Comment by gabrielschulhof** [comment]
If you haven't removed my access yet, I still need it.

**Comment by gabrielschulhof** [comment]
... and if you have, could you please put it back? Sorry about the back-and-forth!

**Comment by addaleax** [comment]
@gabrielschulhof You still have access. It would be good if you either remove your keys yourself when you’re done, or leave the issue open so that we don’t forget to remove them :)

**Comment by gabrielschulhof** [comment]
@addaleax OK. I'll remove the key when I'm done.

**Comment by gabrielschulhof** [comment]
I have removed my key.
