### ISSUE TITLE
Several OSUOSL AIX boxes offline

### ISSUE THREAD

**Issue by sxa555** [nodejs/build#2105]
Some of the older OSUOSL boxes are currently offline. My understanding is that there has been a power issue which will hopefully be resolved soon. EDIT(@sam-github): note this affects ONLY the 3 `{test,release}-osuosl-aix61-*` hosts, not centos/ubuntu ppc64 (I guess they are on different power).
![image](https://user-images.githubusercontent.com/6487691/71199008-e91d5180-228c-11ea-9125-b07eeffbca2a.png)

**Comment by sam-github** [comment]
Hopefully it won't take too long, or CI will backup. If it becomes a big issue, I'll look into how to remove node-test-commit-aix from the job deps. If there is a lightweight way to pull it out temporarily I will.

But lets see when power comes back up.

**Comment by richardlau** [comment]
> 
> 
> Hopefully it won't take too long, or CI will backup. If it becomes a big issue, I'll look into how to remove node-test-commit-aix from the job deps. If there is a lightweight way to pull it out temporarily I will.
> 
> But lets see when power comes back up.

@sam-github Just disabling the node-test-commit-aix project should be sufficient.

![image](https://user-images.githubusercontent.com/5445507/71199623-3ea62e00-228e-11ea-8092-e79b10f52d8f.png)
or 
![image](https://user-images.githubusercontent.com/5445507/71199703-6b5a4580-228e-11ea-8708-9b8377aa7c62.png)

**Comment by sam-github** [comment]
@richardlau Thanks! I'll keep an eye on https://ci.nodejs.org/job/node-test-commit-aix/, if I see the backlog grow, I'll disable it.

**Comment by sam-github** [comment]
Update: Just saw in internal chat that a manual reboot is required, and is being done now.

**Comment by sam-github** [comment]
machines are online and ramdisks are mounted:
```
% parallel-ssh -h hosts/aix61-ppc64_be -i "df | grep ram && mount | grep ram"                                                      
                                       [1] 11:43:41 [SUCCESS] test-osuosl-aix61-ppc64_be-3
/dev/ramdisk0   10000000   9956864    1%        4     1% /ramdisk0
/dev/ramdisk1   23000000  22905728    1%        4     1% /home/iojs/build
         /dev/ramdisk0    /ramdisk0        jfs2   Dec 19 11:38 rw,log=/dev/ramdisk0
         /dev/ramdisk1    /home/iojs/build jfs2   Dec 19 11:44 rw,log=/dev/ramdisk1
[2] 11:43:41 [SUCCESS] release-osuosl-aix61-ppc64_be-1
/dev/ramdisk0   10000000   9956864    1%        4     1% /ramdisk0
/dev/ramdisk1   23000000  22905728    1%        4     1% /home/iojs/build
         /dev/ramdisk0    /ramdisk0        jfs2   Dec 19 13:39 rw,log=/dev/ramdisk0
         /dev/ramdisk1    /home/iojs/build jfs2   Dec 19 13:44 rw,log=/dev/ramdisk1
[3] 11:43:41 [SUCCESS] test-osuosl-aix61-ppc64_be-1
/dev/ramdisk0   10000000   9956864    1%        4     1% /ramdisk0
/dev/ramdisk1   23000000  22883168    1%      118     1% /home/iojs/build
         /dev/ramdisk0    /ramdisk0        jfs2   Dec 19 13:38 rw,log=/dev/ramdisk0
         /dev/ramdisk1    /home/iojs/build jfs2   Dec 19 13:44 rw,log=/dev/ramdisk1
[4] 11:43:41 [SUCCESS] test-osuosl-aix61-ppc64_be-2
/dev/ramdisk0   10000000   9956864    1%        4     1% /ramdisk0
/dev/ramdisk1   23000000  22905728    1%        4     1% /home/iojs/build
         /dev/ramdisk0    /ramdisk0        jfs2   Dec 19 13:38 rw,log=/dev/ramdisk0
         /dev/ramdisk1    /home/iojs/build jfs2   Dec 19 13:44 rw,log=/dev/ramdisk1
```

**Comment by richardlau** [comment]
I resumed a build and it failed: https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/27414/console
```console
14:51:35 ccache: error: Failed to create directory /home/iojs/.ccache/tmp: No such file or directory
```

**Comment by richardlau** [comment]
> 
> 
> I resumed a build and it failed: https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/27414/console
> 
> ```
> 14:51:35 ccache: error: Failed to create directory /home/iojs/.ccache/tmp: No such file or directory
> ```

@sam-github is the above related to moving the ccache onto the ramdisk (https://github.com/nodejs/build/issues/1623#issuecomment-555805645)?

**Comment by sam-github** [comment]
It is. https://ci.nodejs.org/job/node-test-commit-aix/27416/nodes=aix61-ppc64/console is in progress.

**Comment by sam-github** [comment]
It might be slow, since ccache was destroyed on machine reboot.

**Comment by sam-github** [comment]
Build passed: https://ci.nodejs.org/job/node-test-commit-aix/27416/

Looks to be up and alive again.
