### ISSUE TITLE
aix: add AIX7.1 build machines to CI

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2110]
Plan is a gradual addion of AIX7.1 to test configs, and then an even more gradual switch over of the release builds from AIX6.1 to AIX7.1.

See this for details:
- https://github.com/nodejs/build/pull/2098#issuecomment-567672131

This is a tracking issue, to reference from pull requests, and to comment on as changeover occurs, if problems occur, or to notify interested people what is happening.

**Comment by sam-github** [comment]
I added `aix-7.1` to  the build labels for https://ci.nodejs.org/job/node-test-commit-aix/

Building:
- 14.x: https://ci.nodejs.org/job/node-test-commit-aix/27417/ (should build on 7.1)
- 12.x: https://ci.nodejs.org/job/node-test-commit-aix/27418/ (should not build on 7.1 for the moment)

**Comment by richardlau** [comment]
> 
> 
> I added `aix-7.1` to the build labels for https://ci.nodejs.org/job/node-test-commit-aix/
> 
> Building:
> 
>     * 14.x: https://ci.nodejs.org/job/node-test-commit-aix/27417/ (should build on 7.1)
> 
>     * 12.x: https://ci.nodejs.org/job/node-test-commit-aix/27418/ (should not build on 7.1 for the moment)

`aix71-ppc64` would follow the existing labelling convention.

**Comment by sam-github** [comment]
@richardlau Am I greatly misunderstanding the groovy setup?

https://github.com/nodejs/build/blob/48e99171cb768e4483a3d1afc5eca4345accf9b0/jenkins/scripts/VersionSelectorScript.groovy#L64 looks to me like it excludes aix7.1 for lt 14, but its running:
```
13:07:51 Commit message: "Working on v12.14.1"
...
13:07:56 Triggering node-test-commit-aix » aix61-ppc64
13:07:56 Triggering node-test-commit-aix » aix-7.1
```

- https://ci.nodejs.org/job/node-test-commit-aix/27418/console

... And I think I see  the problem, I selected build label `aix-7.1`, but the groovy script needs to apply to `aix71-ppc64`...

I changed the build label selected for the job.

**Comment by richardlau** [comment]
@sam-github I think the job isn't using the VersionSelectorScript -- most likely because previously we haven't had to exclude anything on AIX before.

**Comment by sam-github** [comment]
I'll go check... but I think it worked this last time:

https://ci.nodejs.org/job/node-test-commit-aix/27420/ -- aix6.1 and 7.1 configs have different colors of grey

Also, there used to be exclusions, `< 6` didn't support AIX:
> [ /aix61/,                          anyType,     lt(6)   ],

I'll go look at the jobs, try and figure out where the goovy comes in.

**Comment by sam-github** [comment]
Unsurprisingly, you are absolutely correct wrt. ci.nodejs.org.

The script is used for https://ci-release.nodejs.org/job/iojs+release/configure, probably because it is only over there that release exclusions take place.

**Comment by sam-github** [comment]
![image](https://user-images.githubusercontent.com/17607/71211764-aa73a100-2264-11ea-8f52-1fdbe770b7b6.png)

I used https://ci.nodejs.org/job/node-test-commit-smartos/configure as the example, see above, and added that stanza to the aix build. I'll kick off some more builds when the current ones are done to see if it worked.

**Comment by richardlau** [comment]
Looks like tap2junit can't be found.

e,g, https://ci.nodejs.org/job/node-test-commit-aix/27420/nodes=aix71-ppc64/console

```
17:30:27 [aix71-ppc64] $ /bin/sh -xe /tmp/jenkins5116011305803213197.sh
17:30:27 + mkdir out/junit
17:30:27 mkdir: 0653-358 Cannot create out/junit.
17:30:27 out/junit: Do not specify an existing file.
17:30:27 + true
17:30:27 + tap2junit -i test.tap -o out/junit/test.xml
17:30:27 /tmp/jenkins5116011305803213197.sh[5]: tap2junit:  not found.
17:30:28 POST BUILD TASK : FAILURE
```

**Comment by sam-github** [comment]
Path problem of some sort:
```
% ssh  test-ibm-aix71-ppc64_be-1 /opt/freeware/bin/tap2junit -V
usage: tap2junit [-h] --input INPUT --output OUTPUT
tap2junit: error: argument --input/-i is required
```

Interesting the build still passed.

10.x: https://ci.nodejs.org/job/node-test-commit-aix/27421/nodes=aix71-ppc64/console failed, looks like a timeout.

I'll find where the path is supposed to be set.

**Comment by richardlau** [comment]
> Interesting the build still passed.
> 

Probably because the tests passed and we don't have the following checked in the post build steps:
![image](https://user-images.githubusercontent.com/5445507/71216507-93f43680-22b2-11ea-90b3-aa0be8cbb8b5.png)

One could argue that the build passing is accurate (the tests did pass but our post build tap->junit conversion failed).

**Comment by sam-github** [comment]
I modified the post-build step pictured above to include /opt/freeware/bin, that shouldn't affect any of the compilation stages, where PATH is sometimes used to search for compilers.

```
#/bin/bash -x +e
export PATH=/opt/freeware/bin:$PATH
mkdir out/junit || true
tap2junit -i test.tap -o out/junit/test.xml
tap2junit -i cctest.tap -o out/junit/cctest.xml || true
rm -Rf out/Release/obj.target
```

**Comment by sam-github** [comment]
Also, the VersionSelector.groovy depends on a plugin to export node versions as env vars, I enabled it:

![image](https://user-images.githubusercontent.com/17607/71217120-82d70580-2271-11ea-95b6-22e738a42bba.png)

**Comment by sam-github** [comment]
^-- FTR, @richardlau found that.

Now, groovy is respected: https://ci.nodejs.org/job/node-test-commit-aix/27423/console  is a 10.x branch build, and its only on AIX6.1.

https://ci.nodejs.org/job/node-test-commit-aix/27424/ is a master/14.x build, it was run on AIX7.1 and 6.1, as it should.

https://ci.nodejs.org/job/node-test-commit-aix/27425/console is a 13.x build, it ran, correctly, only on 6.1 (and then I cancelled it)

So that's good, we can now control versions via the groove script.

**Comment by richardlau** [comment]
> 
> 
> ^-- FTR, @richardlau found that.

Also FTR the plugin source is https://github.com/nodejs/node-version-jenkins-plugin.

**Comment by sam-github** [comment]
https://ci.nodejs.org/job/node-test-commit-aix/27424/ passed, and found tap2junit. Still one problem:
```
15:26:50 + tap2junit -i test.tap -o out/junit/test.xml
15:26:55 + tap2junit -i cctest.tap -o out/junit/cctest.xml
15:26:55 usage: tap2junit [-h] --input INPUT --output OUTPUT
15:26:55 tap2junit: error: argument --input/-i: can't open 'cctest.tap': [Errno 2] No such file or directory: 'cctest.tap'
15:26:55 + true
```
- https://ci.nodejs.org/job/node-test-commit-aix/27424/nodes=aix71-ppc64/console

I haven't had time to look into whether cctest should actually exist.

Kicked off a top-level node-test-commit, to check it builds all the way down to node-test-commit-aix on both 6.1 and 7.1:
- https://ci.nodejs.org/job/node-test-commit/34118/

**Comment by richardlau** [comment]
Ah the cctest thing is kind of expected. In the older release lines gtest (which cctest uses) wrote output in tap format which we convert using tap2junit but later versions of gtest [dropped tap support](https://github.com/nodejs/node/pull/27231#discussion_r275177098) so in later release lines cctest writes directly to xml (with no tap file). The job supports both, hence the `|| true`.

(I did notice in the macOS job the equivalent is
```console
if [ -f "cctest.tap" ]; then
  tap2junit -i cctest.tap -o out/junit/cctest.xml
fi
```
which is a bit cleaner than `|| true` as it avoids the error being output when the tap file is not present.)

**Comment by richardlau** [comment]
(And also https://github.com/nodejs/node/pull/27231#issuecomment-540034693 -- We could backport the updated gtest to 10.x and then when 8.x goes EOL we can simplify the jobs to not expect cctest.tap.)

**Comment by richardlau** [comment]
> 
> Kicked off a top-level node-test-commit, to check it builds all the way down to node-test-commit-aix on both 6.1 and 7.1:
> 
> * https://ci.nodejs.org/job/node-test-commit/34118/

The failing addon test was also seen on one of the old machines and has an issue raised: https://github.com/nodejs/node/issues/31061

**Comment by sam-github** [comment]
FTR, looking OK in ci.nodejs.org, now working on ci-release.nodejs.org, have a build running there ATM.

**Comment by sam-github** [comment]
Got a 14.x build passing, trying 13.x:
- https://ci-release.nodejs.org/job/iojs+release/4975/
- https://ci-release.nodejs.org/job/iojs+release/4974/nodes=aix71-ppc64/

**Comment by sam-github** [comment]
@nodejs/releasers We will convert citgm to use AIX7.1 on ***all*** platforms (instead of AIX6.1) after the January 7th releases are complete.

Note that Node.js (by its own support statements) doesn't support AIX6.1, only AIX7.1 and later, so running citgm on supported platforms is preferrable, even though the release was built on an older platform in the expectation of forward binary compatibility.

Using AIX7.1 will allow the removal of most of the AIX specific shell code in the citgm-smoker build steps (though it will still need to call gmake instead of make).

If there are any concerns with the timing of this, please tell us, thanks!

**Comment by richardlau** [comment]
> @nodejs/releasers We will convert citgm to use AIX7.1 on _**all**_ platforms (instead of AIX6.1) after the January 7th releases are complete.
> 
> Note that Node.js (by its own support statements) doesn't support AIX6.1, only AIX7.1 and later, so running citgm on supported platforms is preferrable, even though the release was built on an older platform in the expectation of forward binary compatibility.
> 

We can use citgm-smoker-nobuild, which runs CITGM against an already built release/nightly, to test forward compatibility.

**Comment by AshCripps** [comment]
12.x now uses aix 7.1 for release, final one to add is 10.x

`citgm-smoker` and `citgm-smoker-nobuild` now have AIX71 added to them and will run AIX71 on 12.x and above. Running a test run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2215/

**Comment by richardlau** [comment]
The https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2215/nodes=aix71-ppc64/testReport/junit/(root)/citgm/node_report_v2_2_9/ looks new. I'll run a comparison with Node.js 10 (which should still run on both AIX 6.1 and 7.1 still) to check.

**Comment by richardlau** [comment]
eek @AshCripps citgm-smoker-nobuild on AIX looks broken in a very scary way:
e.g. https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/718/nodes=aix71-ppc64/consoleFull
```console
11:58:05 ++ uname -s
11:58:05 + '[' AIX = AIX ']'
11:58:05 ++ uname -v
11:58:05 + '[' 7 = '6]'
11:58:05 /tmp/jenkins6520255993216933805.sh: line 13: [: missing `]'
11:58:05 + export 'CITGM_COMMAND=citgm node-report'
11:58:05 + CITGM_COMMAND='citgm node-report'
11:58:05 + pgrep node
11:58:05 /tmp/jenkins6520255993216933805.sh: line 21: pgrep: command not found
11:58:05 + xargs kill -9
11:58:05 + mkdir
11:58:05 Usage: mkdir [-p] [-e] [-m mode] Directory ...
11:58:05 + true
11:58:05 + rm -Rf /admin /aha /audit /bin /dev /esa /etc /export /home /lib /lost+found /lpp /mnt /opt /pconsole /proc /run /sbin /smit.log /smit.script /smit.transaction /tftpboot /tmp /u /unix /usr /var
11:58:05 rm: 0653-609 Cannot remove /admin/lost+found.
11:58:05 The file access permissions do not allow the specified action.
11:58:05 rm: 0653-602 Cannot read /admin/tmp/.workdir.11534490.11993228_1.
11:58:05 rm: 0653-611 Directory /admin/tmp is not empty.
11:58:05 rm: 0653-611 Directory /admin is not empty.
11:58:05 rm: 0653-609 Cannot remove /aha/evProds.list.
11:58:05 Operation not permitted.
...
```

**Comment by richardlau** [comment]
![image](https://user-images.githubusercontent.com/5445507/72172742-d995b200-33cd-11ea-8e1a-880b05fd0e69.png)

There's two issues here:
- Missing space character after `"6"`
- `temp` is not set on AIX 7.1 due to the way the `if` statements are nested

I'll fix both.

**Comment by richardlau** [comment]
Here's a citgm-smoker-nobuild run for `node-report` that shows it passing on AIX 6.1 but not AIX 7.1: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/719/

The relevant error is
```console
not ok 23 - Checking machine name in report header section contains os.hostname()
           ---
           found: >-
             Event: JavaScript API, location: "TriggerReport"
           
             Filename: node-report.20200110.121808.14811156.001.txt
           
             Dump event time:  2020/01/10 12:18:08
           
             Module load time: 2020/01/10 12:18:08
           
             Process ID: 14811156
           
             Command line: /home/iojs/build/workspace/citgm-smoker-nobuild/node/bin/node
             /home/iojs/tmp/citgm_tmp/29d18be0-64d0-45c6-9189-1cffb65eec28/node-report/test/test-api-bad-processobj.js
             child
           
           
             Node.js version: v10.18.1
           
           
             node-report version: 2.2.9 (built against Node.js v10.18.1, 64 bit)
           
           
             OS version: AIX 7.1
           
           
             Machine: p158a06 00CCB1C24C00
           pattern: '/Machine: test-ibm-aix71-ppc64_be-2/'
           at:
             line: 136
             column: 7
             file: test/common.js
             function: validateContent
           stack: |
             Object.validateContent (test/common.js:136:7)
             fs.readFile (test/common.js:51:47)
           source: |
             t.match(nodeReportSection,
           ...
```

Namely a mismatch between the expected `test-ibm-aix71-ppc64_be-2` and actual `p158a06`. I'll need to remind myself which API calls are used in the test and `node-report` itself to retrieve the host info.

**Comment by sam-github** [comment]
@richardlau @AshCripps I thought perhaps the machine did not have its hostname set correctly, but it did:
```
% ssh test-ibm-aix71-ppc64_be-2 hostname
test-ibm-aix71-ppc64_be-2.nodejs.org
```

**Comment by richardlau** [comment]
@sam-github It's a mismatch between the following in `node-report`:
The report uses the values returned by [`uname()`](https://github.com/nodejs/node-report/blob/86c64a5c75ccc35f7fdc844993aee75e7d7d5905/src/node_report.cc#L461) in the C++ layer while the test uses [`os.hostname()`](https://github.com/nodejs/node-report/blob/86c64a5c75ccc35f7fdc844993aee75e7d7d5905/test/common.js#L135-L139) at Node.js level which ends up being `gethostname()` at the C++ layer. 

I think `uname()` results should match the `uname` command in the shell but no idea what config on AIX affects the C `gethostname()` call and why there is therefore a discrepency between the API's on our AIX 7.1 vs AIX 6.1 hosts.

Looking at the `node-report` code again it looks like on z/OS we prepend the result of `gethostname()` to the `Machine:` line in the report and that would probably be a simple fix if we do the same for AIX. I'll open a `node-report` PR.

FWIW this isn't an issue with the diagnositics report in core as it consistently uses libuv functions which we can't use in the standalone report module as they only appeared during the 10.x releases (so older 10.x releases don't have the libuv functions and neither do 8.x or 6.x (which are End-of-Life so technically we don't have to worry about but I'd rather not intentionally break them without good reason)).

**Comment by richardlau** [comment]
FWIW this is the discrepancy:
test-osuosl-aix61-ppc64_be-3:
```console
# uname -n
power8-nodejs4
# hostname
power8-nodejs4.osuosl.org
#
```

test-ibm-aix71-ppc64_be-2
```console
$ uname -n
p158a06
$ hostname
test-ibm-aix71-ppc64_be-2.nodejs.org
$
```

but as I said above I'll PR an update to `node-report`.

**Comment by richardlau** [comment]
https://github.com/nodejs/node-report/pull/141 should fix `node-report` so the tests pass on the AIX 7.1 nodes.

**Comment by sam-github** [comment]
@richardlau If node-report is passing, can this be closed?

**Comment by richardlau** [comment]
> 
> 
> @richardlau If node-report is passing, can this be closed?

@sam-github Were we also going to switch 10.x to build releases on AIX 7.1?
https://github.com/nodejs/build/blob/76c481610f57a822601188a372d9aae4f76dfb84/jenkins/scripts/VersionSelectorScript.groovy#L93

**Comment by richardlau** [comment]
Closing as done.

The last step of building 10.x on AIX 7.1 was done a while ago via https://github.com/nodejs/build/pull/2184:

https://github.com/nodejs/build/blob/41d831de68ee0e65f5dd78763f8a3b71190fac40/jenkins/scripts/VersionSelectorScript.groovy#L92-L93

We removed the AIX 6.1 machines in https://github.com/nodejs/build/issues/2273.
