### ISSUE TITLE
CITGM permission problems on AIX (aix61-ppc64)

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#2119]
This is ongoing for maybe a week or two that CITGM is having permission issues on AIX. I explicitly opted out of running the tests on that as work around but it would be great to fix that.

Example failure from yesterday: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2174/nodes=aix61-ppc64/testReport/junit/(root)/citgm/_nearform_bubbleprof/

**Comment by AshCripps** [comment]
Fixed ownership issue on all AIX 6.1 boxes.

I think issues involving the ramdisks should be fixed by moving onto the AIX7.1 boxes which dont have them.

@rsam @richardlau what do we need to do to get CITGM running on the 7.1 boxes?

**Comment by richardlau** [comment]
@AshCripps The two CITGM jobs use VersionSelectorScript.groovy so adding the label for AIX 7.1 would start running the jobs on those boxes where the script allows. There is an additional complication as the jobs have logic in them for AIX to use the ramdisks which we’ll need to guard for AIX 6.1 while we transition.

**Comment by AshCripps** [comment]
I can see there is a couple of ``if [ `uname -s`	 = "AIX" ]; then`` in the configuration for citgm-smoker.

If I add the 7.1 label we could change those statements to something like ``if [ `uname -s`	 = "AIX" && `uname -v`  = "6"]; then`` then we could ensure that the job only tries to use ramdisk on AIX61

(note: im not familar with the syntax in the jenkins job so no idea if that will work)

**Comment by richardlau** [comment]
I think the label ends up in a `$nodes` so it might be simpler to check that for the AIX 6.1 case.

**Comment by AshCripps** [comment]
Is that variable accesible inside the scripts that are run on the machines? if thats the case it would be much simpler to make use of that.

**Comment by sam-github** [comment]
I added this to our todo checklist. A temporary fix for the `/ramdisk0` usage in AIX 6.1 might be to just do `ln -s /home/iojs /ramdisk0`. I did a quick `git grep -i aix`, and I don't see any relevant refs to AIX, so likely its only the job config which causes the ramdisk to be used. 

@targos

**Comment by sam-github** [comment]
ci: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2179 (but won't start until the current citgm completes)

**Comment by AshCripps** [comment]
ran a v12 ci: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2180/
14.x doesn't build on AIX61 any more so it was just skipped in Sam's run but there was no more permission issues.

Closing now as the permission issues is fixed, any work to include AIX71 in CITGM can be done under #2110. Feel free to reopen if the issue reappears.
