### ISSUE TITLE
jenkins backup

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#212]
I know there's probably some script running somewhere somehow, but making this a bit more visible probably wouldn't hurt.

**Comment by rvagg** [comment]
```
rsync jenkins@ci.nodejs.org:/var/lib/jenkins/ /var/backups/jenkins/ \
  -avz --times --perms --delete --exclude='workspace*/' --exclude='archive/'
```

I haven't actually put this in crontab yet, I _intend_ to, I've run it manually on the main webserver which has plenty of space (nodejs.org).

**Comment by orangemocha** [comment]
Related thought: it would be nice to have the scripts config in source control.

**Comment by rvagg** [comment]
+1, since nobody but admins can actually see, critique or suggest changes to them .. lots of xml though!

**Comment by jbergstroem** [comment]
I think there's too many moving bits at the moment to have them committed. If we look back at our review pace we'd be waiting to get stuff done. Improve review pace or decrease tinkering pace?

**Comment by orangemocha** [comment]
True, it's not that simple. We would almost need a development/staging jenkins to test the changes, spit out the scripts, then review those for merge into the repo and the production jenkins. I don't think that's a priority right now. 

I plan to look into secondary masters to improve the availability, maybe at that point I will look into this workflow.

For now, it would be great if they could just be published somewhere (GithHub?), even if manually.

**Comment by jbergstroem** [comment]
As of writing the backup is `~50G`. Digitalocean takes 4 rolling weekly backups of the vm. Perhaps set up a vm somewhere running `rsnapshot` with ~300G space? should cover us for a 7d, 4w, 6m routine. I guess we could also ask ourselves if we need logs that old ([there's a plugin for that](https://wiki.jenkins-ci.org/display/JENKINS/Discard+Old+Build+plugin)).

**Comment by orangemocha** [comment]
Do you know what takes that much space? Is it mostly logs? I think the logs are not that critical, but the configuration/scripts are. It probably makes sense to treat them separately and have more up-to-date backups for the configuration only. 

Ideally, I'd like to be able to replicate the configuration to a secondary master for improved availability.

**Comment by jbergstroem** [comment]
It's pretty much only logs (99% of size)

**Comment by rvagg** [comment]
I've just put this in the crontab on the nodejs.org webserver:

```
*/15 *  * * *   root    rsync jenkins@ci.nodejs.org:/var/lib/jenkins/ /var/backups/jenkins/ -aqz --times --perms --delete --exclude='workspace*/' --exclude='archive/'
```

perhaps we could just use it as a backup Jenkins? Have it installed and ready to start at a moment's notice and just change DNS to make the slaves point to it. Although I'm not convinced we need to be so prepared for this, being down for a few hours once in a blue moon isn't really a big deal. Just spinning up a new server, rsyncing those files onto it and going from there is probably good enough.

**Comment by jbergstroem** [comment]
I'm ok with failover -- the current environment works well enough; just want to figure out the occasional gateway timeouts. Also, reducing how log we store logs would improve quality of life handling jenkins (cold storage?)

**Comment by orangemocha** [comment]
Well, the master is a single point of failure right now and those outages are not so rare.

>Have it installed and ready to start at a moment's notice and just change DNS to make the slaves point to it.

I was thinking more of a server that would be always up and usable, like ci2.nodejs.org. That way there is no need to do anything specific to failover, and runs from each master their own unique URLs.

**Comment by orangemocha** [comment]
It certainly sounds reasonable not to store logs forever. And if the backups for the logs are not so frequent I think that's ok too.

**Comment by rvagg** [comment]
> I was thinking more of a server that would be always up and usable, like ci2.nodejs.org. That way there is no need to do anything specific to failover, and runs from each master their own unique URLs.

We'd have to move the slaves off using slave.jar to using ssh to make this workable, we have a constraint on running multiple instances of java on the smaller Pi's. I'm concerned about @jbergstroem's reports of finding a heap of zombie ssh-agent processes on the Jenkins server recently since they are likely from the ssh slaves that have been recently added (Windows I think).

**Comment by orangemocha** [comment]
> we have a constraint on running multiple instances of java on the smaller Pi's

I see. @joaocgreis believes that ssh solves the disconnect issue (we don't have have it set up for the Windows slaves actually, and that's why those machines are disconnecting so often).  So this seems worth pursuing.. hopefully the ssh-agent zombie side effect can be addressed and we are not trading one issue for another :)

**Comment by jbergstroem** [comment]
I killed all agents and restarted jenkins yesterday. Haven't seen any stray `ssh-agent` since.

**Comment by jbergstroem** [comment]
So, I identified the issue with `ci` being the DO backup by comparing kernel stack trace timestamps with the DO backup window. We've now disabled DO image backups since we backup our jenkins anyway.

**Comment by jbergstroem** [comment]
I've now enabled backups to the new ci server (well, from `iojs-www`), as well as renaming the old backup (lives in `/var/backups`). I also took the liberty of running one. Closing since we have a running backup. Reopen if I missed something.
