### ISSUE TITLE
Disable v8.x jobs in CI

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2120]
WIth v8.x now EOL I assume its a good time to start disabling jobs in CI, but I am not sure of what the process is. I notice there is an [archive of v6.x-staging](https://ci.nodejs.org/view/All/job/archive-node-daily-v6.x-staging/) so I assume we archive the daily job. 

I also know we keep configuration around for 6 months after EOL so is it just a process of disabling/removing daily timers for now?

**Comment by AshCripps** [comment]
We could take the chance to remove some random jobs which I dont think are used anymore.

Examples:
https://ci.nodejs.org/view/All/job/benchmark-node-micro-benchmarks-gareth/
https://ci.nodejs.org/view/All/job/benchmark-footprint-6.x/

**Comment by sam-github** [comment]
I don't think there is any point to archiving v8.x jobs, we won't ever bring them back, I suggest deleting:
- https://ci.nodejs.org/view/All/job/node-daily-v8.x-staging/
- https://ci.nodejs.org/view/All/job/node-test-napi-modules-citgm-v8.x/
- https://ci.nodejs.org/view/All/job/benchmark-footprint-8.x/
- https://ci.nodejs.org/view/All/job/archive-node-daily-v6.x-staging/
- https://ci.nodejs.org/view/All/job/benchmark-footprint-6.x/

I disabled them for the moment.

**Comment by AshCripps** [comment]
@nodejs/build any objection to the deletion of the jobs mentioned above?

also any objection to the deletion of the `archived-` prefixed [jobs](https://ci.nodejs.org/view/All/)
They were disabled in https://github.com/nodejs/build/issues/1874#issuecomment-515138213 over 6 months ago and theres been no outcry that ive seen so I assume they can be removed from jenkins

**Comment by Trott** [comment]
I can't imagine there's a problem with removing the 8.x jobs, but maybe be sure to notify @nodejs/releasers? (Oh, hey, now they're notified.)

No objection from me for deleting the 6-months-ago-archived jobs.

**Comment by AshCripps** [comment]
I have deleted the following jobs:

- archive-libuv-test-pipeline
- archive-node-daily-v6.x-staging
- archive-node-stress-single-test
- archive-node-test-commit-unified 
- archive-node-test-known-issues  
- archive-node-test-npm
- archived-node-test-commitmsg  
- archived-test-post-build-status-update
- node-daily-staging-v8.x
- benchmark-footprint-6.x
- benchmark-footprint-8.x
- benchmark-node-micro-benchmarks-gareth


While im at it theres loads of jobs with peoples names that dont seem to be used anymore, im going to collate a list of them all and ping the owners to see if they still need them to tidy our jenkins up a bit

**Comment by richardlau** [comment]
Of the jobs linked to in this issue, only https://ci.nodejs.org/view/All/job/node-test-napi-modules-citgm-v8.x/ remains.
