### ISSUE TITLE
citgm-smoker-nobuild not working

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2125]
I'm not sure if it used to.

Last failed:
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/703/console

Earliest fail with a log:
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/698/console

All are:
```
20:44:20 Building remotely on test-packetnet-ubuntu1604-x64-1 (Ubuntu Ubuntu-16.04 amd64-Ubuntu jenkins-workspace amd64-Ubuntu-16.04 16.04 amd64) in workspace /home/iojs/build/workspace/citgm-smoker-nobuild
20:44:20 FATAL: null
20:44:20 java.lang.NullPointerException
20:44:20 	at hudson.plugins.templateproject.ProxySCM.checkout(ProxySCM.java:92)
20:44:20 	at hudson.scm.SCM.checkout(SCM.java:504)
20:44:20 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1209)
20:44:20 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
20:44:20 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
20:44:20 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
20:44:20 	at hudson.model.Run.execute(Run.java:1816)
20:44:20 	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
20:44:20 	at hudson.model.ResourceController.execute(ResourceController.java:97)
20:44:20 	at hudson.model.Executor.run(Executor.java:429)
```

This might be related to a change @richardlau made on2019-12-19_20-14-05 :
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/jobConfigHistory/showDiffFiles?timestamp1=2019-12-19_20-12-31&timestamp2=2019-12-19_20-14-05

**Comment by sam-github** [comment]
<img width="864" alt="Screenshot 2020-01-03 at 16 21 21" src="https://user-images.githubusercontent.com/17607/71735892-7b346680-2e04-11ea-97c7-7cfeb869ac9a.png">
Changed that to None, will try a build, see if that helps.

**Comment by sam-github** [comment]
seemed to have helped a bit: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/704/console

**Comment by AshCripps** [comment]
is that job working properly? looks like the builds fail immediately after one test failure?

**Comment by sam-github** [comment]
I don't know, but doesn't look right to me, either. At this point, perhaps we should wait for the people with more experience setting the citgm jobs up to step in.

**Comment by BethGriggs** [comment]
@AshCripps that was the expected behaviour for that run - I wanted to check whether moment was failing on all platforms before skipping it in https://github.com/nodejs/citgm/pull/777

Parameters now working as expected - https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/nodes=rhel7-s390x/704

**Comment by richardlau** [comment]
> This might be related to a change @richardlau made on2019-12-19_20-14-05 :
> 
> * https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/jobConfigHistory/showDiffFiles?timestamp1=2019-12-19_20-12-31&timestamp2=2019-12-19_20-14-05

Sorry about that — I must have inadvertently clicked the radio button.

**Comment by sam-github** [comment]
OK, I was worried something else would break. It sounds like switching back to an scm of `none` was the right fix.

@BethGriggs can you close if this is now working as expected?
