### ISSUE TITLE
Removal of disabled personal Jenkins jobs

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2129]
As per https://github.com/nodejs/build/issues/2120#issuecomment-572502990 here is my (_long_) list of disabled personal jenkins job so we can get a clearer idea of if these jobs are needed or can be removed. Please can you check the boxes if the job should stay or it can go.

@nodejs/build I know some of these people are no longer tied to the project anymore so I would appreciate your input on their jobs.

Hopefully this helps to clean up the jenkins a bit.

| User | Job name | Please Keep | Can be deleted |
| --- | --- | --- | --- |
| @gdams | [~node-test-commit-aix-gdams~](https://ci.nodejs.org/view/All/job/node-test-commit-aix-gdams/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| --- | --- | --- | --- |
| @maclover7  | [~maclover7-nodegyp-test-commit~](https://ci.nodejs.org/job/maclover7-nodegyp-test-commit/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| maclover7 | [~maclover7-nodegyp-pull-request~](https://ci.nodejs.org/job/maclover7-nodegyp-test-pull-request/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| maclover7 | [~node-test-commit-custom-suites-maclover7~](https://ci.nodejs.org/job/node-test-commit-custom-suites-maclover7/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| --- | --- | --- | --- | 
| @sam-github  | [~node-test-commit-linuxone-sam-github~](https://ci.nodejs.org/job/node-test-commit-linuxone-sam-github/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| --- | --- | --- | --- |
| @mhdawson  | [~node-test-commit-linuxone-mdawson-test~](https://ci.nodejs.org/job/node-test-commit-linuxone-mdawson-test/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| mhdawson | [~node-test-commit-osx-mdawson~](https://ci.nodejs.org/job/node-test-commit-osx-mdawson/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| mhdawson | [~node-test-commit-plinux-mdawson-centos7~](https://ci.nodejs.org/job/node-test-commit-plinux-mdawson-centos7/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| mhdawson | [~node-test-commit-v8-linux-mdawson~](https://ci.nodejs.org/job/node-test-commit-v8-linux-mdawson/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| --- | --- | --- | --- |
| @targos  | [~node-test-commit-osx-targos~](https://ci.nodejs.org/job/node-test-commit-osx-targos/)  | <ul> <li> [ ] </ul> | <ul> <li> [x] </ul> |
| --- | --- | --- | --- |
| @mmarchini  | [~mmarchini-node-test-pr~](https://ci.nodejs.org/job/mmarchini-node-test-pr/)  | <ul> <li> [ ] </ul> | <ul> <li> [x] </ul> |
| --- | --- | --- | --- |
| @refack  | [~refack-benchmark-node-micro-benchmarks-compare~](https://ci.nodejs.org/job/refack-benchmark-node-micro-benchmarks-compare/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| refack  | [~refack-test-commit-linuxone~](https://ci.nodejs.org/job/refack-test-commit-linuxone/)  | <ul> <li> [ ] </ul> | <ul> <li> [X] </ul> |
| --- | --- | --- | --- |
| @rvagg  | [rvagg-test-commit-linux-containered](https://ci.nodejs.org/job/rvagg-test-commit-linux-containered/)  | <ul> <li> [X] </ul> | <ul> <li> [ ] </ul> |
| rvagg | [rv-test-commit-linux-docker](https://ci.nodejs.org/job/rv-test-commit-linux-docker/) (Im assuming this one is yours) | <ul> <li> [X] </ul> | <ul> <li> [ ] </ul> |

**Comment by mhdawson** [comment]
@AshCripps thanks for doing this.

**Comment by sam-github** [comment]
deleted mine and gdams' aix/linuxone jobs

**Comment by sam-github** [comment]
@nodejs/lts do you actually use https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-v10.x-staging/ or https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-v12.x-staging/  ? I don't think they are used, once commits are pushed onto staging, node-test-commit is used with a specific ref to test how it goes, nobody waits until the next morning.

Can we delete them?

**Comment by BethGriggs** [comment]
@rsam I use those jobs

**Comment by BethGriggs** [comment]
@sam-github, I do use those jobs

**Comment by mmarchini** [comment]
Feel free to remove `mmarchini-node-test-pr`

**Comment by rvagg** [comment]
my two are still in use for proposed new feature and some testing, will remove when the associated pull request here is closed

**Comment by AshCripps** [comment]
@nodejs/build any objections to me removing the remaining 5 personal jobs in jenkins?

**Comment by mhdawson** [comment]
+1 for removing the remaining 5 personal jobs

**Comment by AshCripps** [comment]
All jobs that could be removed, have been removed :tada: 

Thanks everyone for their responses!
