### ISSUE TITLE
CI machines for citgm

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#213]
@jasnell  mentioned we'd like to get automation going for citgm and might need some machines. I can provide them from softlayer but wondered if these machines should be dedicated for citgm or if we should just use machines from the existing pool and then add machines to the existing pool to accommodate the load.

If the later then I can add an additional ubuntu machine (assume it should be 1404) and one additional windows machine with windows server 2012 standard.

@jbergstroem , @rvagg  what's your take on whether we should use the shared pool or dedicate some machines to citgm

**Comment by rvagg** [comment]
I think we can just reuse the machines we use for general test runs, it's basically the same thing, see https://ci.nodejs.org/job/smoker/ for an initial attempt at putting citgm in there, feel free to take that and make it betterer and add additional test hosts.

**Comment by jbergstroem** [comment]
@mhdawson whats the status on these machines?

**Comment by mhdawson** [comment]
The last comment was that we could just use the machines that are used for general test runs.  ie no special machines would be required.

**Comment by jbergstroem** [comment]
Thinking `iojs-softlayers-benchmark` is suitable for this? If so, are we done here?

**Comment by jbergstroem** [comment]
Oops, wrong button.

**Comment by mhdawson** [comment]
I think the suggestion was that it could just run on any of the existing machines. Unless there is disagreement on that point then we could just close this.   The main objection I could see is if the test will run for a long time.

**Comment by mhdawson** [comment]
Based on suggestions I'm going to just close this
