### ISSUE TITLE
feature: add ability to run CITGM on rc builds to citgm-smoker-nobuild

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2130]
The job currently enables us to run CITGM on `nightly` and `release` build -  would it be possible to have that extended to include `rc` builds? This would be helpful when rerunning various CITGM platforms/modules on a release proposals (rather than rebuilding the release each time we can build an `rc` and can rerun CITGM against that). 

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild

**Comment by targos** [comment]
+1, and while we're at it, also add `v8-canary` to the list

**Comment by richardlau** [comment]
Added `rc`, `v8-canary` and `test`:
https://ci.nodejs.org/job/citgm-smoker-nobuild/jobConfigHistory/showDiffFiles?timestamp1=2020-01-10_12-25-15&timestamp2=2020-01-13_12-54-19

Some test builds:
rc: https://ci.nodejs.org/job/citgm-smoker-nobuild/721/ (s390x failure is probably okay, as it was from a build before we switched to building with devtoolset)
v8-canary: https://ci.nodejs.org/job/citgm-smoker-nobuild/722/
release: https://ci.nodejs.org/job/citgm-smoker-nobuild/723/

**Comment by richardlau** [comment]
Changes appear to be working (in that the jobs downloaded the expected builds from the respective download folders).
