### ISSUE TITLE
Nightly coverage build failed to upload

### ISSUE THREAD

**Issue by bcoe** [nodejs/build#2134]
It looks like we failed to upload our nightly C++ and Node.js coverage:

https://coverage.nodejs.org/coverage-dcbf9da0edf95451/index.html

Just hypothesising, I'm wondering if we ran out of space somewhere?

**Comment by mhdawson** [comment]
Does look like the rsyncs are timing out.  It really needs some cleanup scripts but never have gotten to the top of the list.  Will try to do some cleanup.

**Comment by mhdawson** [comment]
Cleaned up and kicked off job to see if its ok now: https://ci.nodejs.org/job/node-test-commit-linux-coverage-daily/.

We should have the results from the last 15 runs

**Comment by bcoe** [comment]
thanks @mhdawson, does it make sense for @Trott and I to try to get us closer to being able to use coveralls.io for C++ too, and to perhaps retire that upload process?

I'm not feeling that we're 100% of the way there yet.

**Comment by mhdawson** [comment]
Last 15 results are back up.

@bcoe I'd be happy to have something I don't need to periodically fix up:).  My only concern would be depending on an external company so we'd want broader TSC/collaborator input on that.

**Comment by mhdawson** [comment]
Closing the issue as problem has been resolved.
