### ISSUE TITLE
V8 + cmake CI jobs

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#2139]
I'm in the process of cmaking all the things. Would it be possible and acceptable to set up linux+macos+windows CI jobs for https://github.com/bnoordhuis/v8-cmake?

It's still a work in progress but it would be good to get some continuous testing. I'm happy to move it to the nodejs org if that's considered more appropriate than a personal account.

**Comment by mhdawson** [comment]
It's not clear to me what you want clones of. Since you have v8 in the name it makes me think it might be https://ci.nodejs.org/job/node-test-commit-v8-linux/, however, we only have that on linux. 

Is it the main node.js jobs like https://ci.nodejs.org/job/node-test-commit-linux/ instead ?

**Comment by richardlau** [comment]
No objections from me. I'm not sure if we have cmake installed on Linux/macOS on the CI machines (I think the libuv Linux cmake job unpacks cmake as part of the job). As Michael points out we don't currently build V8 on Windows or macOS.

If you're happy with just x64 then you could run CI on GitHub Actions

**Comment by bnoordhuis** [comment]
@richardlau I'd like to get coverage for other architectures as well, at least on linux (arm, arm64, ppc64, s390 - undecided on ia32.)

That said, it's a good suggestion. Maybe I can use that in the interim.

> It's not clear to me what you want clones of. 

@mhdawson Not sure why you use the word "clones." I'd like CI jobs that build the cmake-ified V8 on the Big Three.

**Comment by sam-github** [comment]
"clone" := copy an existing job, hack it slightly to point at your repos, but I looked at  https://github.com/bnoordhuis/v8-cmake/blob/master/README.md#build, and I'm guessing you need a new job that does the commands described there?

@bnoordhuis you have build machine access already, but are not in  https://github.com/nodejs/build#jenkins-admins , shall I just add you to that and you can create the jobs?  Or would you like someone else to take a shot at job creation, maybe @AshCripps ?

I've no opinion on the location of the repo, I'm ok with building one from your account, particularly since you are already a build-wg member, so already have shell acess to ci machines.

**Comment by sam-github** [comment]
And... I just saw 

> on the Big Three.

Doing github actions or .travis for mac/win/linux is probably the easiest way for everyone until wide platform support is needed.

**Comment by richardlau** [comment]
If there are no objections from anyone else in the WG I don’t mind creating a job (and giving @bnoordhuis permissions to edit it once it is set up) but it would be next week at the earliest as I’m currently with relatives for the Lunar New Year.

**Comment by rvagg** [comment]
No objections from me. Getting cmake onto everything and in ansible will be the bigger problem.

**Comment by bnoordhuis** [comment]
I have v8-cmake running on GH Actions now and I'm pretty pleased with it. It's a lot easier to work with than Jenkins.

Actions has a concept of [self-hosted runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners). If there was a way to e.g. expose the ppc or arm machines as external runners, I'd be in CI heaven.

If that's not an option, I'll see if I can hack something together using qemu and cross-compile toolchains.

**Comment by mhdawson** [comment]
Unfortunately, the self-hosted runners have a dependency on .net.  I had talked to the power team about seeing if we could get them running but last I checked it was not possible yet.
