### ISSUE TITLE
doc cleanup in progress

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2151]
Just a note, after @AshCripps  centralized admin processes into GOVERNANCE.md, I did a search of the repo for other docs, and found some I'd never even realized existed. I think the READMEs deep in the repo that are strongly associated with a specific tool are reasonable, ditto for the ansible docs in ansible/, but in the absence of a strong reason for the contrary, its generally better to have our docs in one place for ease of discovery and maintenance.

Its probably worth having a TOC in the top-level README.md, I might take a shot at that once these PRs have landed and the layout is more stable.

- ansible/aix61-standalone/manualBootstrap.md: obsolete, to be deleted soon
- ansible/aix61-standalone/README.md: obsolete, to be deleted soon
- ansible/MANUAL_STEPS.md: ok
- ansible/README.md: ok
- ansible/www-standalone/README.md:
- ansible/www-standalone/tools/metrics/public-index.md:
- ansible/www-standalone/tools/promote/README.md:
- backup/README.md:
- doc/process/jenkins_job_configuration_access.md: move https://github.com/nodejs/build/pull/2147
- doc/windows-visualstudio-supported-versions.md: clean up https://github.com/nodejs/build/pull/2148
- jenkins/doc/add-worker-firewall-entry.md: move https://github.com/nodejs/build/pull/2149
- jenkins/jobs.md: move https://github.com/nodejs/build/pull/2150
- jenkins/scripts/coverage/README.md:

**Comment by richardlau** [comment]
+1 to a TOC. 

I don't object to things being documented in separate files where it makes sense to do so as long as there's no duplication and they are referenced/indexed from the top-level README/GOVERNANCE.

**Comment by sam-github** [comment]
Note that what I have a problem with isn't _seperate files_, its the indistinguishable-from-random location of those files. I'm not sure how I could justify the organizational guidelines which leads to `doc/jenkins-guide.md` and `jenkins/doc/add-worker-firewall-entry.md` and `jenkins/jobs.md` being in three different directories.

The locations are just historical, and no longer helpful.

**Comment by mhdawson** [comment]
+1 for a TOC and moving docs into a better structure.  I'm sure it made sense when each was added forr some reason, but we can probably better organize now.

**Comment by sam-github** [comment]
also: https://github.com/nodejs/build/pull/2156
