### ISSUE TITLE
Lockdown of CI for Feb 2020 security releases

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2155]
https://nodejs.org/en/blog/vulnerability/february-2020-security-releases/

> Releases will be available at, or shortly after, Tuesday, February 4th, 2020.

**Comment by sam-github** [comment]
auth matrix before:

![image](https://user-images.githubusercontent.com/17607/73761204-5c86ff80-4723-11ea-888f-61b626508a93.png)

**Comment by BethGriggs** [comment]
Releases are out - CI can be opened back up

**Comment by sam-github** [comment]
@richardlau https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#after-the-release says I can use https://ci.nodejs.org/jobConfigHistory/history?name=config to revert the config back to its old state. Do you know how? I don't see such an option in the UI. Perhaps I just delete the two entries at the top that are changes I made?

**Comment by richardlau** [comment]
> 
> 
> @richardlau https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#after-the-release says I can use https://ci.nodejs.org/jobConfigHistory/history?name=config to revert the config back to its old state. Do you know how? I don't see such an option in the UI. Perhaps I just delete the two entries at the top that are changes I made?

Sorry, I don't know. I don't see any obvious options either.

**Comment by sam-github** [comment]
Thanks for looking. Delete didn't work, it just deletes the config history. Redoing manually.

**Comment by richardlau** [comment]
I guess we should update the guide.

**Comment by sam-github** [comment]
auth matrix after:

![image](https://user-images.githubusercontent.com/17607/73962128-b3770b00-48c2-11ea-8750-e88c24219425.png)

**Comment by sam-github** [comment]
@MylesBorins I think you usually do this? or @rvagg?

PTAL to confirm I've done it correctly. There are some minor differences, in particular, the before has some "light gray" checks in boxes. I'm not sure how to make that happen, or if I need to.

This process needs documenting, @MylesBorins is it you who usually does this?

https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#after-the-release is somewhat vague on the details.

I couldn't find a way to restore to before the changes, that would've been ideal.

Doing it manually, I had to read the `nodejs*build` and `nodejs*Collaborators` group by typing in (case-sensitive!) those group names -- it looks like the groups auto-removed from the table when all perms for them were removed.

**Comment by rvagg** [comment]
Looks good @sam-github - over time this has become more complicated, when we first started doing this is was just a few groups but now it's getting out of hand. I don't know if there's a good way to do a restore other than manually, but next time I guess try and keep removals to a minimum, just Collaborators Authenticated Users and _maybe_ build, although build can be helpful when things break if you can accept a slightly wider audience.

In the past it's mainly been myself and Refael taking care of this process. Glad you're able to do it now @sam-github, I hope you don't mind.

**Comment by sam-github** [comment]
Its unlocked, but lets leave this open until I update the process docs and screenshots.
