### ISSUE TITLE
remove ppcle-ubuntu1404?

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2159]
We no longer build ppcle Linux releases on Ubuntu with the End-of-Life of Node.js 8:
https://github.com/nodejs/build/blob/4464fa7c9bc8da11e7e9d29301028a5f790d4e64/jenkins/scripts/VersionSelectorScript.groovy#L37

We test on `centos7-ppcle` for Node.js 10 onwards (i.e. all current supported Node.js versions). Time to retire `ppcle-ubuntu1404` and remove from the CI? At the very least we could stop testing on it on the more recent release lines.

List of jobs to be updated on the public test CI based on https://github.com/nodejs/jenkins-config-test/ and the following shell script:
```
-bash-4.2$ grep ppcle-ubuntu1404 jobs/*  | awk -F'[/:]' '{ print "- [ ] "$2 }' | sort -u
```

- [x] citgm-abi-smoker-forward-compat.xml
- [x] citgm-abi-smoker.xml
- [x] citgm-continuous-integration.xml
- [x] citgm-smoker-nobuild.xml
- [x] citgm-smoker-pipeline.xml
- [x] citgm-smoker-private.xml
- [x] citgm-smoker-rebuild.xml
- [x] citgm-smoker-v10.x.xml
- [x] citgm-smoker-v12.x.xml
- [x] citgm-smoker.xml
- [x] citgm-smoker-yarn.xml
- [x] libuv-test-commit-linux.xml
- [x] llnode-continuous-integration.xml
- [x] llnode-pipeline.xml
- [x] node-inspect.xml
- [x] nodereport-continuous-integration-latest.xml
- [x] node-stress-single-test.xml
- [x] node-test-commit-plinux.xml
- [x] node-test-commit-v8-linux.xml
- [x] node-test-napi-modules-citgm-v8.x.xml
- [x] node-test-napi-modules-citgm.xml
- [x] node-test-node-addon-api-new.xml
- [x] node-test-node-addon-api.xml
- [x] readable-stream-continuous-integration.xml
- [x] readable-stream-pipeline.xml
- [x] string_decoder-continuous-integration.xml
- [x] string_decoder-pipeline.xml

release CI:
```
-bash-4.2$ grep ppcle-ubuntu1404 jobs/*  | awk -F'[/:]' '{ print "- [ ] "$2 }' | sort -u
```

- [ ] iojs+release-joaocgreis.xml <-- job doesn't appear to exist anymore?
- [x] iojs+release-mdawson-major.xml
- [ ] iojs+release-mdawson-osx.xml <-- job doesn't appear to exist anymore?
- [x] iojs+release-mdawson-test-centosppc.xml
- [x] iojs+release-mdawson-test.xml
- [ ] iojs+release-new-osx-temp.xml <-- job doesn't appear to exist anymore?
- [x] iojs+release-ppcle-only.xml
- [ ] iojs+release-sam-github.xml <-- job doesn't appear to exist anymore?
- [x] iojs+release.xml

**Comment by richardlau** [comment]
cc @nodejs/platform-ppc

**Comment by sam-github** [comment]
I think we should remove it. I went end-of-support in April 2019. The centos builds run on it, if anyone is running it, but we don't need it in CI.

**Comment by mhdawson** [comment]
+1 to removing.

**Comment by richardlau** [comment]
Via https://github.com/nodejs/jenkins-config-test/ here are the current references to `ppcle-ubuntu1404`:

```
-bash-4.2$ grep ppcle-ubuntu1404 jobs/*
jobs/citgm-abi-smoker-forward-compat.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-abi-smoker.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-continuous-integration.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-smoker-nobuild.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-smoker-pipeline.xml:debian8-64 fedora-last-latest-x64 fedora-latest-x64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x aix61-ppc64
jobs/citgm-smoker-private.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-smoker-rebuild.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-smoker-v10.x.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-smoker-v12.x.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-smoker.xml:        <string>ppcle-ubuntu1404</string>
jobs/citgm-smoker-yarn.xml:        <string>ppcle-ubuntu1404</string>
jobs/libuv-test-commit-linux.xml:        <string>ppcle-ubuntu1404</string>
jobs/llnode-continuous-integration.xml:alpine-latest-x64 debian8-64 debian9-64 fedora-latest-x64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x smartos16-64 smartos15-64 win10 win2012r2</description>
jobs/llnode-pipeline.xml:      debian8-64 fedora22 fedora23 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x aix61-ppc64 ppcbe-ubuntu1404 smartos16-64 smartos15-64 win10 win2012r2</description>
jobs/node-inspect.xml:          <description>Space-separated list of nodes, e.g. debian8-64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x aix61-ppc64 smartos16-64 smartos15-64 win10 win2012r2</description>
jobs/node-inspect.xml:      description: &apos;Space-separated list of nodes, e.g. debian8-64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x aix61-ppc64 smartos16-64 smartos15-64 win10 win2012r2&apos;,
jobs/nodereport-continuous-integration-latest.xml:        <string>ppcle-ubuntu1404</string>
jobs/node-stress-single-test.xml:        <string>ppcle-ubuntu1404</string>
jobs/node-test-commit-plinux.xml:        <string>ppcle-ubuntu1404</string>
jobs/node-test-commit-v8-linux.xml:        <string>ppcle-ubuntu1404</string>
jobs/node-test-napi-modules-citgm-v8.x.xml:        <string>ppcle-ubuntu1404</string>
jobs/node-test-napi-modules-citgm.xml:        <string>ppcle-ubuntu1404</string>
jobs/node-test-node-addon-api-new.xml:debian8-64 fedora-last-latest-x64 fedora-latest-x64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel7-s390x
jobs/node-test-node-addon-api-new.xml:        <string>ppcle-ubuntu1404</string>
jobs/node-test-node-addon-api.xml:debian8-64 fedora-last-latest-x64 fedora-latest-x64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel7-s390x
jobs/node-test-node-addon-api.xml:        <string>ppcle-ubuntu1404</string>
jobs/readable-stream-continuous-integration.xml:debian8-64 fedora-latest-x64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x aix61-ppc64
jobs/readable-stream-pipeline.xml:alpine-latest-x64 debian8-64 fedora-latest-x64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x aix61-ppc64
jobs/string_decoder-continuous-integration.xml:debian8-64 fedora-latest-x64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x aix61-ppc64
jobs/string_decoder-pipeline.xml:alpine-latest-x64 debian8-64 fedora-latest-x64 osx1010 ppcle-ubuntu1404 ubuntu1404-64 ubuntu1604-64 rhel72-s390x aix61-ppc64
-bash-4.2$
```

**Comment by richardlau** [comment]
Removed the above references (updating to centos7-ppcle where necessary). Need to sweep through any references in the release CI before updating VersionSelectorScript.groovy and the compiler selector -- needs access to the release Jenkins (which I might get under https://github.com/nodejs/build/issues/2286).

**Comment by richardlau** [comment]
Done the release CI jobs -- there appear to be jobs in the jenkins-config-release backup that are no longer in https://ci-release.nodejs.org/ and I'm presuming have been deleted.

**Comment by richardlau** [comment]
Follow up PR to remove from `select-compiler.sh` and `VersionSelectorScript.groovy` scripts: https://github.com/nodejs/build/pull/2292
