### ISSUE TITLE
Proposal that release team have more access to release resources

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2169]
The release  team lacks access to some resources that they interact with while doing releases.

Specifically, they have limited access to node-www, where releases are uploaded, and they are not [jenkins admins](https://github.com/nodejs/build#jenkins-admins).

I don't have infra access, so I can't verify exactly what access they have to node-www, but not enough to delete old rc candidates, see https://github.com/nodejs/build/issues/2162

I know they can't can't lock or unlock CI while doing security releases, https://github.com/nodejs/build/issues/2155

The release team builds the releases, so there is a large amount of trust placed in them. I assume  they could inject malevolent code into releases while landing commits, probably could upload binaries patched with malware, etc. We trust them not to do this, so it looks to me to that giving them some more authority to fix problems that arise during the release process would be helpful.

I'm neither on the release team, or the build-infra team, so I may misunderstand the current scope of their power, but I'd like to suggest that either all (or perhaps some) of the release team be given jenkins-admin capabilities, and node-www access.

@nodejs/build, @nodejs/releasers, and @nodejs/tsc  what do you think? Helpful, or a burdensome increase in scope :-)//.

**Comment by rvagg** [comment]
Can you discuss what access to node-www they would need and what they would do with it? I've been pushing in the opposite direction because the release team is not regularly trimmed and there's a lot of old keys laying around with access to node-www so I've been switching ownership to root of things owned by the user they have access to now so releases get locked in place and are unmodifiable.

**Comment by sam-github** [comment]
Sufficient access to solve #2162 to remove old rcs.

Again, I perhaps misunderstand the release team's powers, but if they have the ability to push binaries to node-www, shouldn't the team be trimmed to ones that actually need to do that?

**Comment by rvagg** [comment]
> Sufficient access to solve #2162 to remove old rcs.

That's not how it was resolved though, we haven't removed anything in the release directory and I'm still hesitant to give them more ability to mess with live files unless we are clear with policies about what needs to be kept and what isn't.

In fact, that main way I initially freed up space was to remove things that were stale in staging. The release team has access to do this. But the setup on the server is not simple and I doubt anyone would be brave enough to go do such a thing.

If we can find an intersection between release team and sysadmin expertise and knowledge of how these things are set up then we should expand in that direction. Currently this role is being served by non-release team members (well non-active): myself, Michael and Joao (Johan has access too and could probably figure things out in an emergency). We're roughly distributed around the globe so mostly have good coverage when things go bad.

We don't really have well established channels to raise problems like this (I only discovered it when I went through my GitHub notifications late in the day, a few hours after I was active and could have taken care of it!). Maybe that's something we could work on too?

> Again, I perhaps misunderstand the release team's powers, but if they have the ability to push binaries to node-www, shouldn't the team be trimmed to ones that actually need to do that?

Well this gets to an important point for this discussion - that team is not a very organised team, it's a lose collection of people who have been given access at some point by the TSC. It merged with the LTS WG (IIRC) but I'm not sure you could properly call it an active working group these days. The team itself doesn't put much effort into trimming its list; that's arguably not even part of its role. If we raise the level of access of this team then we'd probably want it to be more organised and strict in its delegation of responsibility. Maybe this is a TSC role though? I'm not super keen for Build to take on a duration role for Release membership.

* See https://github.com/nodejs/release#lts-team-members for the list of members of that team (is that even an accurate representation of the GitHub team?). Compare to the people you know who have released in the past 12 months. Even compare to people active in this org!
* See https://github.com/nodejs/Release/issues/499 for my recent attempt to clean this up. I don't have a lot of clarity in those responses and haven't yet taken action on it. But action based on that is going to be me taking a strong line with people who _haven't_ responded.

Also, a bunch of SSH keys were put on the server without identifiers, further complicating the trimming process.

(This would have been a nice place for KeyBox to be inserted).

**Comment by sam-github** [comment]
And given the lack of @nodejs/releasers response here, it doesn't sound like they think more access would be helpful, either.

**Comment by targos** [comment]
Yeah, I don't think more access would have helped me much in that case and I think it's good that the release directory is protected as much as possible.
IMO, the solution to the issue we had is as @rvagg proposed in https://github.com/nodejs/build/issues/2162#issuecomment-582659214: have an automatic removal of nightlies after some time.
