### ISSUE TITLE
Add field for LTS in /dist/index.json

### ISSUE THREAD

**Issue by phillipj** [nodejs/build#217]
Would it be possible to distinguish LTS from stable releases as mentioned in [new.nodejs.org #200 comment](https://github.com/nodejs/new.nodejs.org/issues/200#issuecomment-146051237)? Or possibly  a generic `policy` field containing `stable | lts | maintenance` as mentioned in [node PR #3343](https://github.com/nodejs/node/pull/3343) for each release?

**Comment by rvagg** [comment]
thanks for the reminder, see #218
