### ISSUE TITLE
libuv: grant CI permissions to collaborator

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#2170]
I'm trying to add @erw7 to https://ci.nodejs.org/job/libuv-test-commit/configure but I can't get Jenkins to actually remember his entry. He should have the same permissions as @vtjnash.

**Comment by richardlau** [comment]
Do they not fall under the already defined permissions for `libuv`?

**Comment by bnoordhuis** [comment]
I believe that only applies to people in the core libuv team, not `@libuv/windows`.

**Comment by richardlau** [comment]
> I believe that only applies to people in the core libuv team, not `@libuv/windows`.

Ah right. I could add `libuv*Collaborators`?

**Comment by richardlau** [comment]
According to https://ci.nodejs.org/user/erw7/ @erw7 is a member of:
> Groups:
> - libuv
> - libuv*Collaborators
> - libuv*windows

so should have been covered by the existing `libuv` entry.

**Comment by bnoordhuis** [comment]
I'll follow up with @erw7. Thanks for checking, Richard.
