### ISSUE TITLE
Introduction: I'm Dave. How can I help?

### ISSUE THREAD

**Issue by davidstanke** [nodejs/build#2171]
Hi folks!

My name is [Dave Stanke](https://stanke.dev) and I want to help out with Node build infra. I was the CTO at a startup for many years, overseeing engineering, operations, and product. In 2014, I joined Google as a product manager. For the past two years, I’ve been a Developer Advocate for Google Cloud (on a team adjacent to @MylesBorins 's), focused on the DevOps/SRE space, with particular attention to CI/CD. I know my way around Jenkins and a few other tools. Being an ops type, I don’t write much code, unless YAML counts as code. (It does not. -_Ed._) But when I do, Node is increasingly my tool of choice. I live in New Jersey, I eat a lot of yogurt, and I’m eager to pitch in. I have a lot to learn about how we operate around here, and my primary goal for now is to Do No Harm. Thank you in advance for answering questions and helping me ease into productivity.

@mhdawson helped me come up with a couple of starter projects. I want to share them here and get feedback from the group:

1.  Review [build issues](https://github.com/nodejs/build/issues) and make a list of things I could investigate. You’ll find a first pass below; I would love feedback. Specifically, I’m looking for things that have minimal risk, require minimal access, and yet are of use to the group. Also, anything time-sensitive is a bad choice until I learn my way around. Feel free to add things!

1. Document people and responsibilities within this group. If any artifacts like this exist, please let me know. If not, I hope you’ll tolerate me reaching out to inquire about your contributions. The goal is to assemble a comprehensive catalog of “[Task W] is performed under [Conditions X] by [Persons Y, Z].”

Please let me know if you have any questions or concerns. I look forward to getting to know you!
Dave

**Comment by davidstanke** [comment]
### Some issues I might be able to help on:
#2151 doc cleanup in progress [restructure docs and add a TOC]
#1393 Document or automate macOS release machine setup
#2166 CI comment ends up in wrong repo
#2088 Remote call failure
#2049 daily builds are failing
#1847 tap2junit fails on test input when tests time out
#1969 Can use of the "resume build" button be tracked? 
#1938 Switch coverage.nodejs.org to an HTML table
#1793 Benchmarks in CI produce erroneous results

**Comment by sam-github** [comment]
Hi @davidstanke its great to have more people involved.

Some of those issues require access you don't have (yet), but some don't. It might be reasonable to do some of the tidying tasks below that don't require access or take very long, it will allow you to dip your toes into CI/build and get a sense for how it works for the project, and see some of the disparate parts.

> #2151 doc cleanup in progress [restructure docs and add a TOC]

A review of the docs with fresh eyes would be great, feel free to PR any improvements, and if you wanted to make a TOC in the top-level README.md as well, that would be much appreciated.

> #1393 Document or automate macOS release machine setup

This might be hard to do without actually setting up a machine, which requires test machine access.

> #2166 CI comment ends up in wrong repo

Requires jenkins-admin access.

> #2088 Remote call failure

Probably needs jenkins-admin and test machine ssh access.

> #2049 daily builds are failing

Its still a sea of red :-(/  https://ci.nodejs.org/job/node-daily-master/

Fixing is mostly a node problem, but is driven by reports of [flaky tests](https://github.com/nodejs/node/issues?q=is%3Aopen+is%3Aissue+label%3A%22CI+%2F+flaky+test%22).

Reporting does not require access, just ability to read Node.js test results, and a side-effect of finding and reporting issues there as flaky tests to nodejs/node is getting familiar with the CI as it looks to developers reading their PR results and wondering how it has anything to do with their code.

> #1847 tap2junit fails on test input when tests time out

Probably just needs some python coding and PR to the tap2junit repo, no ssh access required. Pretty sure its reproable standalone with description in the report.

> #1969 Can use of the "resume build" button be tracked?

If your jenkins background gives you some suggestions, please weigh in on the issue!

> #1793 Benchmarks in CI produce erroneous results

Almost certainly requires test machine ssh access.

**Comment by davidstanke** [comment]
Thanks for the additional info! I'll definitely look to start with things that require the least access. I also plan to start attending the Build WG meetings when I can (starting tomorrow), so I'll be listening for opportunities there as well.

**Comment by rvagg** [comment]
There's also this which is blocked by technical problems that have yet to be figured out yet. If we can get it working then it could be a major change to the way we offer CI to Node: https://github.com/nodejs/build/pull/1982 + https://github.com/nodejs/node/pull/30057

@john-yan offered to get involved too but I haven't had the time to make a "reproduce locally" case for it. All of the code is in those 2 PRs plus a small bit of Jenkins scriptery which I think I've documented already (but if not then I can provide).

**Comment by sam-github** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1029662 is also a build-wg related issue that is hard to get progress on. We can't push it without chromium team involvement, @davidstanke do you have any interactions with that team? Having someone with a foot in both worlds would really help in getting progress on that. cc: @miladfarca

**Comment by davidstanke** [comment]
Heya @sam-github ! I've crossed paths with Chromium build team folks once or twice. I will see if I can unblock that one.

@rvagg I love what's happening there in #1982. I definitely want to be of use there, though I need to learn the ropes before I want to attempt anything called "major changes." ;-)

Thanks for the pointers!

**Comment by sam-github** [comment]
Hey @davidstanke, how's it going?  I'm available to do a video call if you need to get past any blockers.

**Comment by davidstanke** [comment]
Hi! Will you look at the time... a whole year has gone by. So, I apologize for leaving this thread idle. As you can probably guess, _something_ kind of weird happened this year and completely scrambled my priorities and availability. So, I don't expect I'll be able to contribute here after all. :( Thank you to the folks like @mhdawson and @sam-github who were patient and generous with their time in helping me start onboarding.

Sadly, I think I off-boarded a long time ago, so I'll say good-bye and thanks again. This is a great community and I wish you every success.
