### ISSUE TITLE
ci,libuv: http://ci.nodejs.org/downloads/zos/gyp.tar.gz?

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#2172]
Some of the libuv buildbots seem to use a... bespoke?... copy of gyp:

https://ci.nodejs.org/job/libuv-test-commit-osx/1748/nodes=osx1011/console
```
+ mkdir build/gyp
+ curl -s http://ci.nodejs.org/downloads/zos/gyp.tar.gz
+ tar xvf - -C build/gyp/
```
```
$ curl -q --head http://ci.nodejs.org/downloads/zos/gyp.tar.gz | grep Last-Modified
Last-Modified: Wed, 27 Sep 2017 21:43:14 GMT
```
Does anyone know/remember why things are set up this way? I was thinking of extracting node's tools/gyp to https://github.com/libuv/gyp (so people can still build with a somewhat maintained version of gyp) and then switch over the CI to use that.

(Libuv's readme currently points people to chromium's obsolete copy of gyp.)

**Comment by bnoordhuis** [comment]
Similar question for the Windows buildbots:
```
08:44:24 C:\workspace\libuv-test-commit-windows\nodes\win2008r2-vs2017>xcopy c:\gyp build\gyp /e /i /h /c /q /y
```

**Comment by richardlau** [comment]
> Does anyone know/remember why things are set up this way?

I have no idea why the macOS builds would be pulling down the http://ci.nodejs.org/downloads/zos/gyp.tar.gz as that's presumably a copy of gyp with patches for z/OS. 

> 
> ```
> $ curl -q --head http://ci.nodejs.org/downloads/zos/gyp.tar.gz | grep Last-Modified
> Last-Modified: Wed, 27 Sep 2017 21:43:14 GMT
> ```

The above last modified puts this in the timeframe when z/OS support was initially upstreamed to gyp (https://chromium-review.googlesource.com/c/external/gyp/+/644712/). As far as I'm aware none of the z/OS patches for gyp are in Node.js' `tools/gyp` (which is probably an indication of how often we updated gyp in Node.js), although they did make it into node-gyp (https://github.com/nodejs/node-gyp/pull/1276).

**Comment by richardlau** [comment]
cc @nodejs/platform-s390

**Comment by richardlau** [comment]
Another reason for using the tarball on z/OS is that the z/OS port of git doesn't support https URLs: https://forum.rocketsoftware.com/t/git-and-https-repositories/482.

**Comment by rvagg** [comment]
Re macOS + z/OS: 🤷‍♂ another Jenkins mystery we'll never solve I suspect. Let's get that switched, perhaps a genuine mistake on someone's part.

Re Windows, what's the problem there? Don't you need to add in a GYP to make it compile with GYP? IIRC we setup a bunch of the libuv build machines with static GYP installs that we copied into place.

Re GYP version:

* https://github.com/nodejs/node-gyp/pull/1975
* https://github.com/nodejs/node/pull/30563

Hopefully we'll have _one true GYP_ sooner than later. I want to cut a node-gyp@7 with that PR merged soon.

**Comment by bnoordhuis** [comment]
> Re Windows, what's the problem there?

That it's not cloned from anywhere but copied from the local file system. It makes me wonder how old that copy of gyp is. :-)

FWIW, the consensus within the libuv team is that we'll just drop support for GYP and move the build files downstream so I'll go ahead and close out the issue. Cheers!

**Comment by richardlau** [comment]
> 
> 
> Another reason for using the tarball on z/OS is that the z/OS port of git doesn't support https URLs: https://forum.rocketsoftware.com/t/git-and-https-repositories/482.

https://github.com/nodejs/build/blob/4058b56f9e8f33711596867c66485b2ba44bae72/ansible/roles/jenkins-worker/tasks/main.yml#L207-L209
