### ISSUE TITLE
Macstadium macs running out of diskspace

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2173]
On `test-macstadium-macos-10.11-x64-2` a build failed due to running out of space. Whilest investigating I came across some weirdness.

```
test-macstadium-macos10:/ root# df -h
Filesystem      Size   Used  Avail Capacity  iused  ifree %iused  Mounted on
/dev/disk0s2    49Gi   48Gi  1.5Gi    98% 12516492 380804   97%   /
devfs          175Ki  175Ki    0Bi   100%      604      0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0      0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0      0  100%   /home
```

`df -h` is reporting around 48G of usage but

```
test-macstadium-macos10:/ root# du -sh *
796M	Applications
4.9G	Library
  0B	Network
4.7G	System
 13G	Users
4.0K	Volumes
2.5M	bin
  0B	cores
4.0K	dev
4.0K	etc
1.0K	home
4.0K	installer.failurerequests
1.0K	net
3.5G	private
1.0M	sbin
4.0K	tmp
1.3G	usr
4.0K	var
test-macstadium-macos10:/ root#
```

`du -sh *` only reports around 28G of usage, which means theres around 20G of missing storage?

From a quick bit of googling a likely candiate is time machine backups taking up space because they are "hidden" from the user, but I need to do some more research into this so I can find out if this is the cause.

This is also an issue on the other 10.11 machine, but in the meantime if the builds fail again clearing the workspaces on the machine will resolve the issue

**Comment by Trott** [comment]
If I'm not mistaken, `du -sh *` will omit directories and files that start with `.`. So maybe check for that?

**Comment by AshCripps** [comment]
> If I'm not mistaken, `du -sh *` will omit directories and files that start with `.`. So maybe check for that?

You're spot on 

```
test-macstadium-macos10:/ root# du -hsc $(ls -A)
  0B	.DS_Store
8.0K	.Spotlight-V100
  0B	.Trashes
  0B	.file
 16G	.fseventsd
  0B	.vol
796M	Applications
4.9G	Library
  0B	Network
4.7G	System
6.7G	Users
4.0K	Volumes
2.5M	bin
  0B	cores
4.0K	dev
4.0K	etc
1.0K	home
4.0K	installer.failurerequests
1.0K	net
3.5G	private
1.0M	sbin
4.0K	tmp
1.3G	usr
4.0K	var
 38G	total
```

Looks like `.fseventsd` is the culprit

**Comment by AshCripps** [comment]
looks to be a load of file system event notifications, I should be able to delete anything older than a year to free up some space. We should probably look into turning this off as we dont have any use for time machine I think seeing as we can just reansible machines.

**Comment by AshCripps** [comment]
ive removed anything older that 150 days - there wasnt much over a year old. Freed up about 10G space now looks like:

```
sh-3.2# df -h
Filesystem      Size   Used  Avail Capacity iused   ifree %iused  Mounted on
/dev/disk0s2    49Gi   36Gi   13Gi    74% 9521143 3376153   74%   /
devfs          175Ki  175Ki    0Bi   100%     604       0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%       0       0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0       0  100%   /home
sh-3.2# du -hsc $(ls -A)
  0B	.DS_Store
8.0K	.Spotlight-V100
  0B	.Trashes
  0B	.file
6.7G	.fseventsd
  0B	.vol
796M	Applications
4.9G	Library
  0B	Network
4.7G	System
 11G	Users
4.0K	Volumes
2.5M	bin
  0B	cores
4.0K	dev
4.0K	etc
1.0K	home
4.0K	installer.failurerequests
1.0K	net
3.5G	private
1.0M	sbin
4.0K	tmp
1.3G	usr
4.0K	var
 33G	total
sh-3.2#
```

Will go through the other macs and see what state they are in and free up some space if needed on them, then will look into disabling this feature all together if possible

**Comment by AshCripps** [comment]
Checked through the other macs, they dont seem to be affected by this issue and I cant find any easy way of turning it off (just warnings of "you will break this"). So im closing this now as there is enough space on the machines and will just keep an eye out for an reoccurance.
