### ISSUE TITLE
ci,libuv: decommission ubuntu1404-gyp-{32,64}

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#2174]
The following jobs can be removed from https://ci.nodejs.org/job/libuv-test-commit/:

* ubuntu1404-gyp-32
* ubuntu1404-gyp-64

14.04 is out of support and libuv is about to drop support for gyp so no point in keeping them around.

Refs: https://github.com/libuv/libuv/pull/2682

**Comment by richardlau** [comment]
Gone!

FTR they're were in https://ci.nodejs.org/job/libuv-test-commit-linux/:
![image](https://user-images.githubusercontent.com/5445507/74272947-74541a00-4d07-11ea-8b36-a3c4892eb7ca.png)

Should I remove `ubuntu1404-*` (the non-gyp variants) too (there'd still be `ubuntu1604-*` left)?

**Comment by bnoordhuis** [comment]
Thanks! Yes, the other ubuntu1404's can go too.

**Comment by richardlau** [comment]
Done. I've taken out the gyp conditionals in the shell scripts too. 
Test build: https://ci.nodejs.org/job/libuv-test-commit-linux/1823/

**Comment by richardlau** [comment]
FYI while I was editing I tried replacing `make check` with `make distcheck` for https://github.com/nodejs/build/issues/1910 but almost all platforms failed https://ci.nodejs.org/job/libuv-test-commit-linux/1822/ so I changed it back.

**Comment by richardlau** [comment]
Ah thinking about It I probably should have run against libuv/libuv v1.x instead of bnoordhuis/libuv drop-gyp so I don't know if it's an issue with https://github.com/libuv/libuv/pull/2682.

**Comment by bnoordhuis** [comment]
Good that you mention it, that's indeed breakage from my PR. I'll fix that.

**Comment by richardlau** [comment]
I toggled back to `make distcheck` and ran on libuv/libuv v1.x and that failed differently (test failures). I'll take that conversation over to https://github.com/nodejs/build/issues/1910.

**Comment by bnoordhuis** [comment]
Fixed, closing.
