### ISSUE TITLE
Add Universal Base Image (UBI) build to CI system

### ISSUE THREAD

**Issue by danbev** [nodejs/build#2176]
### Description
This issue purposes adding a build for Universal Base Image (UBI) 8.1, which is based on RHEL, to the CI system. 

### Motivation
The motivation for doing this is that UBI 8.1 contains a system OpenSSL version that has FIPS support and this build would be configured to dynamically link to that OpenSSL version. This would allow us to exercise the FIPS code path which is currently not done. This is not something that happens often but there has been one occasion where code was committed to master which failed to compiler when fips was enabled: https://github.com/nodejs/node/commit/17d87d522c674362a4769d20c05cb0f1daf10e7f

### Docker build instructions
```console
$ docker pull registry.access.redhat.com/ubi8:8.1
$ docker run --ipc=host -ti registry.access.redhat.com/ubi8:8.1 /bin/bash
$ yum install -y git gcc-c++ which make python3 openssl-devel procps-ng
$ git clone https://github.com/nodejs/node.git
$ cd node
$ update-crypto-policies --set LEGACY
$ export OPENSSL_ENABLE_MD5_VERIFY=true
$ ./configure --openssl-system-ca-path=/etc/pki/tls/certs/ca-bundle.crt --shared-openssl --openssl-is-fips
$ make -j8 test
```
 Currently there is one test failure which is covered by https://github.com/nodejs/node/pull/31715

**Comment by rvagg** [comment]
Nice! Do you have time to set up a preliminary version of a Dockerfile for this? See the Dockerfiles in here: https://github.com/nodejs/build/tree/master/ansible/roles/docker/templates, the one that it might be close to is ubuntu1804_sharedlibs.Dockerfile.j2 where we previously had FIPS tests running. Basically the image needs to be set up so that a Node repo can be mounted and compiled, the environment variables tell it where to link. Might not be needed for this image though if it's the default openssl installed I suppose.

Do you know if you can `FROM registry.access.redhat.com/ubi8:8.1` in a Dockerfile? If not then we'll have to do some extra Ansible work to pull from a custom registry.

**Comment by richardlau** [comment]
@rvagg I’ll take a look at this.

**Comment by richardlau** [comment]
> Do you know if you can `FROM registry.access.redhat.com/ubi8:8.1` in a Dockerfile? If not then we'll have to do some extra Ansible work to pull from a custom registry.

From my preliminary experiments It appears that you can.

**Comment by danbev** [comment]
> For my own education, why is this `LEGACY` and not `FIPS`

Sorry, about the late reply (I forgot that I had an email filter set up). This is to enable other test to pass which would not otherwise if the security policy was set to `DEFAULT` or `FIPS`.

**Comment by richardlau** [comment]
@danbev 
We now have four UBI 8.1 containers in the CI based off the Dockerfile template in [`ansible/roles/docker/templates/ubi81.Dockerfile.j2`](https://github.com/nodejs/build/blob/master/ansible/roles/docker/templates/ubi81.Dockerfile.j2):
- [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/computer/test-digitalocean-ubi81_container-x64-1/)
- [test-digitalocean-ubi81_container-x64-2](https://ci.nodejs.org/computer/test-digitalocean-ubi81_container-x64-2/)
- [test-joyent-ubi81_container-x64-1](https://ci.nodejs.org/computer/test-joyent-ubi81_container-x64-1)
- [test-softlayer-ubi81_container-x64-1](https://ci.nodejs.org/computer/test-softlayer-ubi81_container-x64-1/)

[node-test-commit-linux-containered](https://ci.nodejs.org/job/node-test-commit-linux-containered/) has been extended to build on them for Node.js >= 13.

e.g. this build is against current `master`: https://ci.nodejs.org/job/node-test-commit-linux-containered/18480/nodes=ubi81_sharedlibs_openssl111fips_x64/ (all tests passed)

**Comment by danbev** [comment]
@richardlau Very nice :tada: Thank you very much for setting this up!
