### ISSUE TITLE
Centos 7 socket hang up multiple times on 12.16.1 release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2178]
My gut is that this is an infra issue, but it does only appear to be happening with the 12.16.1 release right now :(

https://ci.nodejs.org/job/node-test-commit-linux/nodes=centos7-64-gcc6/32867/console
https://ci.nodejs.org/job/node-test-commit-linux/nodes=centos7-64-gcc6/32868/console
https://ci.nodejs.org/job/node-test-commit-linux/nodes=centos7-64-gcc6/32869/console

```
10:43:47 Error: socket hang up
10:43:47     at connResetException (internal/errors.js:604:14)
10:43:47     at TLSSocket.socketCloseListener (_http_client.js:400:25)
10:43:47     at TLSSocket.emit (events.js:333:22)
10:43:47     at net.js:668:12
10:43:47     at TCP.done (_tls_wrap.js:556:7) {
10:43:47   code: 'ECONNRESET'
10:43:47 }
```

**Comment by rvagg** [comment]
Those are all on the same machine, test-softlayer-centos7-x64-1, so there's a chance at least it's an infra problem. Build history of the two machines of this type make it look like this one _might_ be more flaky than the other, but we can't isolate 12.x runs unfortunately:

https://ci.nodejs.org/computer/test-rackspace-centos7-x64-1/builds
https://ci.nodejs.org/computer/test-softlayer-centos7-x64-1/builds

I've updated the machine, cleared the workspace and rebooted, 🤞
