### ISSUE TITLE
Why did download metrics drop significantly around October 2019?

### ISSUE THREAD

**Issue by golopot** [nodejs/build#2179]
The download counts of node has dropped significant around October 2019, as shown in https://nodejs.org/metrics/. What happens? Does node.js lost half of its users in one day?

![total](https://user-images.githubusercontent.com/16285118/74613239-80950880-5147-11ea-9243-859a90654b71.png)

**Comment by richardlau** [comment]
We switched to serving downloads via CDN but the metrics scripts haven't been modified yet. See https://github.com/nodejs/build/pull/2025 for some background.
