### ISSUE TITLE
Access to VM?

### ISSUE THREAD

**Issue by ronag** [nodejs/build#2186]
I am struggling with resolving a bug specific to a specific build on CI. In particular [this PR](https://github.com/nodejs/node/pull/31806) fails on [two specific platforms ](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/1877/) and currently I have no viable way of debugging this.

Is it possible to get access to a VM or a VM image of the failing environments that I can use to quickly change, build end debug?

Alternatively some other way that this can be more easily debugged? Currently I'm left with guessing fixes and pushing to the repo in order to restart the specific CI job and hoping it passes.

For Linux it's possible to get around this using Docker. However, Windows has no such option that I am aware of and is usually more complicated to setup for someone not familiar with the platform. I'm a MacOS user.

**Comment by sam-github** [comment]
Process for temporary access is here: https://github.com/nodejs/build/blob/master/GOVERNANCE.md#temporary-access

It is possible, you would have to provide the exact name of the test machine you want access to, and your ssh key.

**Comment by ronag** [comment]
> you would have to provide the exact name of the test machine you want access to

I'm not sure how to determine this but I would need access to a machine where the test fails as seen here https://ci.nodejs.org/job/node-test-binary-windows-js-suites/1877/.

> and your ssh key

I'm not quite sure how to share this. Over mail?

I might need a little help with getting started here...

**Comment by sam-github** [comment]
There were multiple failures in that job, but one is https://ci.nodejs.org/job/node-test-binary-windows-js-suites/1877/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2019/, you can see the host on the top right:  test-azure_msft-win10_vcbt2015-x64-4 in that case.

I can't ssh into that host, though, so I don't think I can help get you access.

Public ssh keys are shareable in public, here would be fine, though you appear to only have one key, so that should be useable: https://github.com/ronag.keys (many of us have multiple).

@nodejs/platform-windows can anyone help ronag out?

**Comment by joaocgreis** [comment]
@ronag I've created a test machine that you can use. I'll follow up with credentials by email.

From the configurations that failed, it seemed that the problem might be VS2019 and not any particular Windows version. However, I tried to run the binary of both VS2017 and VS2019, and it seems the test is very flaky in both.

@sam-github Windows does not use ssh, it's username and password. Thanks for following up here! For this, I ended up creating a new machine from scratch but for simpler issues we can simply create a new user in a machine and remove it from CI.

**Comment by ronag** [comment]
Thanks!

**Comment by joaocgreis** [comment]
@ronag feel free to keep the machine as long as you need it. We usually keep the issue open here to track access, so I'll reopen. Thanks!

**Comment by ronag** [comment]
@joaocgreis: Thank you the related issues have been fixed. I no longer require the VM.

**Comment by joaocgreis** [comment]
Removed the machine. Thanks!
