### ISSUE TITLE
dist-indexer.js: 'modules version' is not parsed correctly

### ISSUE THREAD

**Issue by fhemberger** [nodejs/build#219]
[dist-indexer.js#L402](https://github.com/nodejs/build/blob/master/setup/www/tools/dist-indexer/dist-indexer.js#L402) should probably use `parseInt(modules, 10)+''`, as some module numbers are saved as hex values:

![](https://cloud.githubusercontent.com/assets/153481/10485445/7e37e27e-728a-11e5-8be8-49d017151348.png)
![](https://cloud.githubusercontent.com/assets/153481/10485446/7e3f0e78-728a-11e5-9de2-b7b6cbc2fab4.png)

**Comment by rvagg** [comment]
hmm, this was intentional in core (I haven't done a `git blame` to see who did it) and those are the exported values, it's correct either way but perhaps more friendly just showing an integer

/cc @bnoordhuis @maxogden thoughts on this?

**Comment by maxogden** [comment]
the web UI (https://nodejs.org/en/download/releases/) just displays the data from https://nodejs.org/dist/index.json and does not modify it at all

**Comment by fhemberger** [comment]
@maxogden Yes, the question is, do we need to fix the generator (are those values on purpose?) or do we fix this on the website, when importing index.json?

**Comment by rvagg** [comment]
Well my question is whether a "fix" is even needed. I'm at +0 on that question.

**Comment by fhemberger** [comment]
It looks weird having the majority of releases using decimal values and a handful using hex notation instead. Can we please adjust this at least on the website?

**Comment by fhemberger** [comment]
Adding an explanation to nodejs.org, let's keep it this way.
