### ISSUE TITLE
Move refack to Emiritus

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2192]
I checked with @refack, he is OK if we move him to Emiritus and remove him from the various build-wg teams.

He made major contributions to the build-wg during his time, and I'd like to publicly thank him for that. Cheers!

This is probably a good test run of the offboarding process, too. I'll do that next week after a couple thumbs ups.

### Offboarding issue checklist

(Remove items if not applicable)

- [x] Remove their GPG key from `test` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `release` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `infra` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `infra-macstadium` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `github-bot` group in `nodejs-private/secrets`
- [x] Remove them from build teams they are a member of:
    - [x] nodejs/build
    - [x] nodejs/build-release
    - [x] nodejs/build-infra
    - [x] nodejs/jenkins-admins
    - [x] nodejs/jenkins-release-admins
    - [x] nodejs-private/build
- [x] PR changes to [README.md](./README.md#build-wg-members) to move the member to emeritus status
- [x] Run `ncu-team sync README.md` to validate the user has been removed from the build teams
- [x] Remove them from the [`nodejs/email`](https://github.com/nodejs/email) alias

**Comment by mhdawson** [comment]
@refack thanks for all the help/work over the years.

**Comment by sam-github** [comment]
https://github.com/nodejs/email/pull/158 <--- needs approval
