### ISSUE TITLE
Request URL redirect: Node.js case studies

### ISSUE THREAD

**Issue by brianwarner** [nodejs/build#2194]
As expected when decommissioning foundation.nodejs.org, we ran into a few circumstances where links to content should be preserved after putting the redirects in place.

Would it be possible to add redirects on the foundation.nodejs.org subdomain for the following docs?  Thanks!

https://foundation.nodejs.org/wp-content/uploads/sites/50/2017/09/Node_CaseStudy_Nasa_FNL.pdf -> https://openjsf.org/wp-content/uploads/sites/84/2020/02/Case_Study-Node.js-NASA.pdf 

https://foundation.nodejs.org/wp-content/uploads/sites/50/2017/09/Node_CaseStudy_Fusion_Final.pdf  -> https://openjsf.org/wp-content/uploads/sites/84/2020/02/Case_Study-Node.js-Fusion.pdf

https://foundation.nodejs.org/wp-content/uploads/sites/50/2017/09/Node_CaseStudy_Walmart_final-1.pdf -> https://openjsf.org/wp-content/uploads/sites/84/2020/02/Case_Study-Node.js-Walmart.pdf

https://foundation.nodejs.org/wp-content/uploads/sites/50/2017/09/Node_CaseStudy_HomeAway.pdf -> https://openjsf.org/wp-content/uploads/sites/84/2020/02/Case_Study-Node.js-HomeAway.pdf

https://foundation.nodejs.org/wp-content/uploads/sites/50/2017/09/Node_CapitalOne_FINAL_casestudy.pdf -> https://openjsf.org/wp-content/uploads/sites/84/2020/02/Case_Study-Node.js-CapitalOne.pdf

**Comment by sam-github** [comment]
to: @nodejs/build-infra

**Comment by rvagg** [comment]
@brianwarner please review https://github.com/nodejs/build/pull/2195
