### ISSUE TITLE
Add João Reis to "release acl"

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#220]
Currently @jbergstroem (me), @rvagg and @orangemocha are the only ones that have access to `-release` machines and secrets tied to release in our shared-secrets repository (using dotgpg). I'd like to extend this group with João Reis (@joaocgreis).

We've yet to implement a similar ACL for our ansible setup so there's no real PR to review, but rather see this as a proposal to extend trust.

**Comment by rvagg** [comment]
+1 from me for @joaocgreis, he's become indispensable for operations and already has access to many of the machines in question

**Comment by orangemocha** [comment]
Absolutely agree!

**Comment by jbergstroem** [comment]
Great. I'll add him to the secrets repo and have this in mind when doing some work on ansible next.

**Comment by joaocgreis** [comment]
Thanks!
