### ISSUE TITLE
PR testing being spawned from benchmark node

### ISSUE THREAD

**Issue by mscdex** [nodejs/build#221]
A couple weeks ago the `iojs-softlayer-benchmark` node was added to Jenkins and had been mistakenly added as the new "master" node that all PRs executed on/from. I think @jbergstroem fixed this earlier this week, but it looks like the benchmark node is back as "master" again somehow.

Is this something that matters or should I not bother checking/creating issues about it?

**Comment by jbergstroem** [comment]
@mscdex following up; is this still a thing?

**Comment by mscdex** [comment]
At the moment it's back on master.

**Comment by jbergstroem** [comment]
good. reopen/ping if it goes the other way again.
