### ISSUE TITLE
Jenkins security update (was: [Incident] Jenkins is going to shut down)

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2213]
Is this a planned shutdown? @nodejs/jenkins-admins 

![img-2020-03-09-151106](https://user-images.githubusercontent.com/4048656/76262101-b7c37a80-6218-11ea-9e18-34229d6a5786.png)

Builds won't start because of it:

![img-2020-03-09-151522](https://user-images.githubusercontent.com/4048656/76262149-d0cc2b80-6218-11ea-9e4b-48ed458db778.png)

**Comment by rvagg** [comment]
Yes, me trying to do a restart after a security upgrade. Will update here shortly.

**Comment by rvagg** [comment]
After some false starts, I've update Jenkins & plugins today, as per security advisory: https://jenkins.io/security/advisory/2020-03-09/

I probably did it too early in the day when there were too many people trying to use it, I know it caused confusion and hassle for a few folks (@mmarchini and @MylesBorins included). Apologies for that!

**Comment by MylesBorins** [comment]
No prob! Was easy enough to clean up jobs once I realized what was going on.

A fun journey!
