### ISSUE TITLE
test-ibm-aix71-ppc64_be-2 is not connected

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2215]
Several jobs were stuck waiting for agent to be available, but we only have one agent online (out of two) for  aix71-ppc64. ssh to the instance works, I tried to restart jenkins but it didn't work.

`jenkins_console.log` has only one line:

```
$ tail jenkins_console.log
Error: Unable to access jarfile /home/iojs/slave.jar
```

Not sure how to proceed. Should I just run ansible to re-provision that instance?

https://ci.nodejs.org/computer/test-ibm-aix71-ppc64_be-2/

cc @nodejs/platform-aix (not sure if this is the right team to cc)

**Comment by sam-github** [comment]
It is connected now. Did you do something? Is it possible it was just being updated at the time you checked?

**Comment by richardlau** [comment]
I tried to run the [`jenkins/worker/upgrade-jar.yml`](https://github.com/nodejs/build/blob/55714b80ab6aed964da19501900d53d2704ee831/ansible/playbooks/jenkins/worker/upgrade-jar.yml) playbook to get the jar on there. It errored while trying to restart Jenkins:

```
-bash-4.2$ ansible-playbook -l test-ibm-aix71-ppc64_be-2 playbooks/jenkins/worker/upgrade-jar.yml
[DEPRECATION WARNING]: DEFAULT_SQUASH_ACTIONS option, Loop squashing is deprecated and this configuration will no longer be used , use a list directly with the module
argument instead. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

You need a passphrase to unlock the secret key for
user: "Richard Lau <riclau@uk.ibm.com>"
4096-bit RSA key, ID C5979DCC, created 2019-10-28 (main key ID C17AB93C)

 [ERROR]: WARNING: cannot load /home/users/riclau/sandbox/github/secrets/build/infra/inventory.yml WARNING: cannot load
/home/users/riclau/sandbox/github/secrets/build/release/inventory.yml


PLAY [test] ****************************************************************************************************************************************************************

TASK [download slave.jar] **************************************************************************************************************************************************
[WARNING]: Platform aix on host test-ibm-aix71-ppc64_be-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

ok: [test-ibm-aix71-ppc64_be-2]

TASK [restart jenkins] *****************************************************************************************************************************************************
fatal: [test-ibm-aix71-ppc64_be-2]: FAILED! => {"changed": false, "msg": "0513-086 The jenkins Group is not on file.\n"}

PLAY RECAP *****************************************************************************************************************************************************************
test-ibm-aix71-ppc64_be-2  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

-bash-4.2$
```

I logged into `test-ibm-aix71-ppc64_be-2` and ran `sudo /etc/rc.d/rc2.d/S20jenkins start` which appears to have restarted the agent.

**Comment by sam-github** [comment]
> Should I just run ansible to re-provision that instance?

Please, no, that is like fly swatting with a machete!

AIX uses traditional unix init scripts (ubuntu uses upstart, centos uses systemd... every sys is different in terms of its native init system).

`/etc/rc.d/rc2.d/S20jenkins start` will start jenkins (cat the file to see what it does) (not that this is needed now)

**Comment by sam-github** [comment]
Thanks @richardlau
