### ISSUE TITLE
request for access to all release machine, and ci(-release).nodejs.org

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2220]
It would help to troubleshoot https://github.com/nodejs/build/issues/2217#issuecomment-597749402

I don't necessarily want to sign up to maintain those systems, but I think I have sufficient expertise with Unix systems to see what is wrong, and perhaps even do service restarts if its necessary and we document it.

Specifically, I request access to:
- https://github.com/nodejs-private/secrets/tree/master/build/release (and auth to use those keys to ssh - or rdp for windows? - into the release machines)
- `nodejs_build_infra{.pub}` (ssh key for [all infra](https://github.com/nodejs-private/secrets/blob/master/build/infra/README.md#table-of-contents)), or "special access" where my ssh key goes on ci-release.nodejs.org and ci.nodejs.org

**Comment by mhdawson** [comment]
I'm +1 for giving Sam more access. There have been a few times were @rvagg and myself have been a bottleneck recently (firewall issue #2217 and release issue #2222). He's been active in the project, the build wg for quite some time now and is on the TSC.  @nodejs/build thoughts?

**Comment by rvagg** [comment]
+1, Sam seems to have been available at the time of day when both you and I have been unavailable (my morning, your evening), so I guess adding Pacfic TZ would broaden our availability span around the globe a bit better.

**Comment by Trott** [comment]
+1

**Comment by sam-github** [comment]
Thanks for the +1s. What happens next? Someone will add my key to secrets/build/release, please?

Then I can take a shot at https://github.com/nodejs/build/issues/2242 which needs release ssh access.

**Comment by rvagg** [comment]
https://github.com/nodejs-private/secrets/pull/94

Done, ssh key is in there, I think maybe you need to add yourself to a github team too to get https://github.com/nodejs/build/#release-admins to update, and also the `jenkins-release-admins` team for full Jenkins if you don't have that yet.
