### ISSUE TITLE
nodejs.org is not updating

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2222]
after release went out and blog post landed, still showing old version of 13.x

**Comment by nschonni** [comment]
Can someone with permissions try this again https://github.com/nodejs/build/issues/2123#issuecomment-570987532
/cc @rvagg

**Comment by mhdawson** [comment]
Ok, ran `sudo systemctl restart github-webhook` as suggested in the comment above.

**Comment by mhdawson** [comment]
@MylesBorins tells me its fixed. Glad it was a simple fix.

**Comment by rvagg** [comment]
for future reference, https://nodejs.org/github-webhook.log is a good first place to look to diagnose these kinds of things, I don't know if it has anything interesting in this instance but if it did it'd probably be at the bottom of the file—timestamps at least would be interesting to tell if it's still receiving pings from the webhook
