### ISSUE TITLE
aix release builds are not triggering for (at least) 13.x

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2223]
Opening here so build-wg is aware of the issue, and [what I did](https://github.com/nodejs/node/pull/32185#issuecomment-598349773) to try to fix it.

**Comment by richardlau** [comment]
Is 12.x broken too? The reported issue was 13.x.

**Comment by sam-github** [comment]
Typo, sorry, I fixed the subject. I'd expect it affects all release lines, I didn't see anything release line specific in regex conditions.

**Comment by mhdawson** [comment]
@sam-github has this been resolved?
