### ISSUE TITLE
Jenkins linking to wrong child Job

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2224]
For this run https://ci.nodejs.org/job/node-test-pull-request/29714/ I got a failure on `parallel/test-tls-keylog-tlsv13` on `ubuntu1804_sharedlibs_openssl110_x64`. While investigating, I noticed that the failing `ubuntu1804_sharedlibs_openssl110_x64` job linked on Jenkins is not the job I started:

![image](https://user-images.githubusercontent.com/4048656/76580639-e0a07580-648d-11ea-9798-335d1d9f453a.png)
(https://ci.nodejs.org/job/node-test-commit-linux-containered/18606/)

![image](https://user-images.githubusercontent.com/4048656/76580666-fb72ea00-648d-11ea-96dd-cba58d4aa47d.png)
(https://ci.nodejs.org/job/node-test-commit-linux-containered/18606/)

Am I missing something? Should I ignore `ubuntu1804_sharedlibs_openssl110_x64` because the icon is transparent (in which case we need update `ncu-ci`)?

**Comment by rvagg** [comment]
This is a Jenkins UI failure ... it's slightly transparent meaning it wasn't run on this job, https://github.com/nodejs/build/blob/master/jenkins/scripts/VersionSelectorScript.groovy excludes openssl110 for >= 12.

I know this is not ideal, but to be absolutely sure if you're confused at this in future, look at the build number, it should carry over to the direct child builds. So you're looking at node-test-commit-linux-containered 18606, but hover over the openssl110 job and you'll see it linking to 18601. If it's not 18606 then it's not relevant.

We do use a custom theme, from http://afonsof.com/jenkins-material-theme/, it's probably quite possible to tweak the CSS to make this better. We manually paste in CSS to our Jenkins instances from that theme generator so it's just as easy to edit the CSS.

**Comment by mmarchini** [comment]
Thanks. I'll see if we can improve this on `ncu-ci` as well.

**Comment by richardlau** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-11373 (marked `wontfix` 😞 )

**Comment by mmarchini** [comment]
Ok, I understand the rationale here (and probably there's nothing we can do), but this makes no sense (build shows as still running, but subjob was not started by it):

![img-2020-03-13-220944](https://user-images.githubusercontent.com/4048656/76675551-b75c1400-6577-11ea-8d15-b7eb73f951ab.png)

![img-2020-03-13-221002](https://user-images.githubusercontent.com/4048656/76675550-b75c1400-6577-11ea-8d00-31de95657d86.png)

![img-2020-03-13-221010](https://user-images.githubusercontent.com/4048656/76675549-b6c37d80-6577-11ea-9de7-a5f7023a2e30.png)

![img-2020-03-13-221018](https://user-images.githubusercontent.com/4048656/76675548-b6c37d80-6577-11ea-9f3e-93151659ef50.png)

**Comment by mmarchini** [comment]
probably not actionable
