### ISSUE TITLE
Publish the index.json/tab file as an NPM package

### ISSUE THREAD

**Issue by nschonni** [nodejs/build#2225]
The file is used in a few places that I know of like the nodejs.org repo as a datasource. Currently it's usually pulled down during builds as an untracked git file, or as a checked-in file that is out of date.
If the regeneration of the file could pushed as an 1.0.x NPM package, it could be tracked like other dependencies and manipulated like a regular package.json dependency and auto-updated by DependaBot.
Maybe the package could be called `node-releases`, and also bundle in the schedule.json from the nodejs/release repo.

**Comment by rvagg** [comment]
That already exists: https://github.com/chicoxyzzy/node-releases and seems to be just what you're wanting, even with the release schedule.json!
What would be neat is if someone contributed a GitHub Action that checked for updates and published a new version automatically, that'd close the loop entirely.

**Comment by nschonni** [comment]
Thanks for pointing that one out. I'll take a look at the automation over there

**Comment by nschonni** [comment]
Would it make sense to transfer here if the author is interested?

**Comment by rvagg** [comment]
(personal opinion) probably not, if the author is active and responsive and it can be made as helpful as people need. I think the way I'd do it would be with a cron anyway, rather than pushing directly from the server, so GitHub Actions is a pretty solid solution to keeping it up to date since it can cron _and_ `npm publish`.

**Comment by nschonni** [comment]
Fair enough. I've PR'd the cron job, and opened issues for the Unofficial Builds and ChakraCore released. I'll close this off and keep pushing that way
