### ISSUE TITLE
`git-rebase` failing due to "unable to create temporary object directory"

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2233]
The last 12 runs of https://ci.nodejs.org/job/git-rebase/ failed because of the error below:

```
08:56:53 error: unpack failed: unable to create temporary object directory
08:56:53 To binary_tmp@169.60.150.88:binary_tmp.git
08:56:53  ! [remote rejected] jenkins-node-test-commit-windows-fanned-932a3e1ce5fbd7b63ed24f24171658e85fb755ca -> jenkins-node-test-commit-windows-fanned-932a3e1ce5fbd7b63ed24f24171658e85fb755ca (unpacker error)
08:56:53 error: failed to push some refs to 'binary_tmp@169.60.150.88:binary_tmp.git'
08:56:53 Build step 'Execute shell' marked build as failure
```

**Comment by mmarchini** [comment]
169.60.150.88 is the IP of `test-softlayer-debian9-x64-1`, the same instance that had the ro root issue earlier today. This is probably related?

**Comment by rvagg** [comment]
no, it's test-softlayer-ubuntu1604-x64-1, our 3rd jenkins-workspace host. Let me switch to one of the new 18.04 ones (although I'm fixing other problems on them right now!)

**Comment by mmarchini** [comment]
True, I misread our inventory file...

**Comment by rvagg** [comment]
Switched to 147.75.66.203, which is test-packetnet-ubuntu1804-x64-1

Working: https://ci.nodejs.org/job/node-test-commit-windows-fanned/34726/
