### ISSUE TITLE
osx1011 Python error

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2238]
osx tests have been failing for the past ~12h on osx1011. The stack trace is:

```
07:09:15 ERROR:root:code for hash sha512 was not found.
07:09:15 Traceback (most recent call last):
07:09:15   File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
07:09:15     globals()[__func_name] = __get_hash(__func_name)
07:09:15   File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
07:09:15     raise ValueError('unsupported hash type ' + name)
07:09:15 ValueError: unsupported hash type sha512
07:09:15 Traceback (most recent call last):
07:09:15   File "tools/inspector_protocol/code_generator.py", line 690, in <module>
07:09:15     main()
07:09:15   File "tools/inspector_protocol/code_generator.py", line 574, in main
07:09:15     jinja_env = initialize_jinja_env(jinja_dir, config.protocol.output, config)
07:09:15   File "tools/inspector_protocol/code_generator.py", line 177, in initialize_jinja_env
07:09:15     import jinja2
07:09:15   File "/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1011/tools/inspector_protocol/jinja2/__init__.py", line 36, in <module>
07:09:15     from jinja2.loaders import BaseLoader, FileSystemLoader, PackageLoader, \
07:09:15   File "/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1011/tools/inspector_protocol/jinja2/loaders.py", line 16, in <module>
07:09:15     from hashlib import sha1
07:09:15 ImportError: cannot import name sha1
```

Looking at our issue tracker, it seems we made some changes to OSX recently (installed cmake)? Could this be a side effect (the timestamps match)? Maybe some other dependency got corrupted while installing cmake. Or is this unrelated? cc @AshCripps

**Comment by mmarchini** [comment]
Saw suggestions online to reinstall Python using `brew reinstall python@2`, but it seems like Homebrew made it harder to install Python 2 since it's going EOL. Looking at alternatives

**Comment by mmarchini** [comment]
Seems to be working: https://ci.nodejs.org/job/node-test-commit-osx/32769/nodes=osx1011/console

It's building, before it was failing on `./configure`.

**Comment by mmarchini** [comment]
Based on that, maybe we should bump the priority on moving to Python 3 on OS X? I'm pretty sure our ansible scripts will not work to reprovision the machines if they try to install Python 2.

**Comment by richardlau** [comment]
> 
> 
> Based on that, maybe we should bump the priority on moving to Python 3 on OS X? I'm pretty sure our ansible scripts will not work to reprovision the machines if they try to install Python 2.

Efforts are underway to set up new macOS test and release machines (see https://github.com/nodejs/build/issues/2188 and https://github.com/nodejs/build/issues/2236). It would probably make sense for those to only have Python 3.

**Comment by AshCripps** [comment]
The latest macs added (10.15s at Nearform) have both python2 and python3:

```
administrator@test-nearform-macos10 ~ % python -V
Python 2.7.16
administrator@test-nearform-macos10 ~ % python3 -V
Python 3.7.7
administrator@test-nearform-macos10 ~ % which python
/usr/bin/python
administrator@test-nearform-macos10 ~ % which python3
/usr/local/bin/python3
administrator@test-nearform-macos10 ~ %
```

Only python3 is installed through brew https://github.com/nodejs/build/blob/162daa4e4a3c0393323cdfc39b0aec9bb6748fa4/ansible/roles/baselayout/vars/main.yml#L99-L101
So I guess the python2 is there in the base mac image (which I made late 2019/early 2020) so hopefully the new ones in ORKA don't have python2

**Comment by mmarchini** [comment]
I forgot to fix `test-macstadium-macos10.11-x64-1` yesterday, but it should be working now.

**Comment by mmarchini** [comment]
Closing as this seems to be resolved
