### ISSUE TITLE
Jenkins update, March 25th

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2239]
> The Jenkins project plans to publish new Jenkins releases (weekly, LTS 2.204.6, and LTS 2.222.1) on Wednesday, March 25. These updates will contain fixes for security issues present in current versions of Jenkins. The highest severity is "High". The security advisory will be issued at the same time to provide further information.

I'll try and handle this one a bit more carefully this time! Between midday and the afternoon my time is usually dead time so I'll just be careful to watch for active collaborators and communicate more clearly.

**Comment by richardlau** [comment]
Hopefully the releases planned for the 24th won't be delayed into 25th (🤞).
cc FYI @nodejs/releasers

**Comment by richardlau** [comment]
This happened. We're currently on Jenkins ver. 2.222.4.
