### ISSUE TITLE
Build WG Meeting 2015-10-20: call for agenda items

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#224]
This is a request for agenda items for the next occurrence of the Build WG meeting.

**Meeting Time:** 8PM Tuesday October 20th UTC, or in your local timezone:
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20151020T20&p1=%3A

### Agenda
Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.
* Currently empty

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

If there are no agenda items by end-of-day Monday, the meeting will be canceled.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by rvagg** [comment]
@orangemocha can you check the calendar entry you created? It's coming up as 6am Tuesday for me and it should be 7am Wednesday, I'm not sure if this is lost in translation between calendaring systems or a simple mistake.

**Comment by orangemocha** [comment]
Updated the event to be at 8pm UTC, every 3 weeks on Tuesday. Also updated the title (sorry for the double update).

I sent the new invitation starting November 10th, assuming tomorrow's instance would be canceled. There is still time to submit agenda items though.

**Comment by orangemocha** [comment]
Since there are no items on the agenda, tomorrow's meeting is cancelled! The next occurrence is scheduled for November 10th.
