### ISSUE TITLE
May I please have access to one FreeBSD and one OSX machine?

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#2240]
I would like to manually test a change to the large pages mapping code that would render it more readable.

**Comment by gabrielschulhof** [comment]
https://github.com/nodejs/node/pull/32396

**Comment by sam-github** [comment]
OK by me, one other build-wg member want to give a thumbs up? criteria: https://github.com/nodejs/build/blob/master/GOVERNANCE.md#temporary-access

@gabrielschulhof 

1. test-digitalocean-freebsd11-x64-2 be ok for you?
1. You only have one ssh key at https://github.com/gabrielschulhof.keys, that's the one you want to use?

**Comment by gabrielschulhof** [comment]
@sam-github both of those machine should be OK. I would indeed like to use the one key that is published there. Thanks!

**Comment by bnoordhuis** [comment]
> one other build-wg member want to give a thumbs up?

Thumbs up given.

**Comment by richardlau** [comment]
+1

**Comment by sam-github** [comment]
@gabrielschulhof added your keys to the 2 machines discussed above

pls leave this issue open until you are done, then remove the keys, then close it.

Thanks.

**Comment by gabrielschulhof** [comment]
@sam-github thank you! I think I actually don't want OSX 10.12, because we don't test on it, at least AFAICT from https://ci.nodejs.org/job/node-test-commit-osx/32865/. It doesn't seem to build on 10.12: https://github.com/nodejs/node/issues/32447

May I please have access to a 10.10, 10.11, or 10.15 machine instead?

**Comment by gabrielschulhof** [comment]
@sam-github I have removed my key from test-macstadium-macos10.12-x64-1.

**Comment by sam-github** [comment]
I was about to put your keys on test-macstadium-macos10.10-x64-1 and I see it has your keys on it already :-)

**Comment by gabrielschulhof** [comment]
@sam-github OK. Thanks! I'll be sure to remove it when I'm done.

**Comment by gabrielschulhof** [comment]
@richardlau @sam-github given https://github.com/nodejs/node/issues/32467#issuecomment-603503731 can you please add my key to an OSX 10.15 machine? I have removed my key from test-macstadium-macos10.10-x64-1.

**Comment by richardlau** [comment]
@gabrielschulhof I've added your key to `test-nearform-macos10.15-x64-1`.

**Comment by gabrielschulhof** [comment]
@richardlau thanks!

**Comment by gabrielschulhof** [comment]
@richardlau I tried to log in but it asks for a password. My public key doesn't seem to be working.

**Comment by gabrielschulhof** [comment]
@sam-github ↑

**Comment by richardlau** [comment]
That's odd... I placed the contents of https://github.com/gabrielschulhof.keys in the `authorized_keys` file. @AshCripps / @sam-github could you double check `test-nearform-macos10.15-x64-1`?

**Comment by AshCripps** [comment]
Its still on the machine and I can still login. Thought I would check because I just updated it incase I broke something

**Comment by gabrielschulhof** [comment]
@richardlau I followed the same procedure as for test-digitalocean-freebsd11-x64-2. That is, I grabbed the coordinates from inventory.yml and added a host entry to my ~/.ssh/config and then tried to log in.

**Comment by gabrielschulhof** [comment]
FWIW `diff -u <(cat ~/.ssh/id_rsa.pub) <(wget -qO- https://github.com/gabrielschulhof.keys)` produces no results, therefore the two are identical.

**Comment by AshCripps** [comment]
> @richardlau I followed the same procedure as for test-digitalocean-freebsd11-x64-2. That is, I grabbed the coordinates from inventory.yml and added a host entry to my ~/.ssh/config and then tried to log in.

Can you share your `~/.ssh/config` entry for it @gabrielschulhof?

**Comment by gabrielschulhof** [comment]
@AshCripps 
```
host test-nearform-macos10.15-x64-1
	Hostname 83.147.191.69
	User administrator
```

**Comment by AshCripps** [comment]
`test-nearform-macos10.15-x64-1` is `83.147.191.70` you are trying to log into the release machine

**Comment by gabrielschulhof** [comment]
I @AshCripps thanks! I had indeed been looking at the release section of inventory.yml.

**Comment by gabrielschulhof** [comment]
There we go. Thanks again!

**Comment by gabrielschulhof** [comment]
@sam-github @richardlau @AshCripps thank you for giving me access! I am done using the machines. Please remove my public keys, as I did not want to risk messing up the config files on the systems.

**Comment by sam-github** [comment]
I removed keys from machines listed in this thread.
