### ISSUE TITLE
No headers on v10.x release builds

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2244]
The v10.x RC builds do not seem to be producing headers or source tarball (https://github.com/nodejs/node/pull/31984#issuecomment-603155995) 

The CI runs passed both times - https://ci-release.nodejs.org/job/iojs+release/5775/console

https://nodejs.org/download/rc/v10.20.0-rc.0/
https://nodejs.org/download/rc/v10.20.0-rc.1/

**Comment by BethGriggs** [comment]
I couldn't see any headers from the Artifacts from my release build

```
15:02:48 Skipping osx1011-release-tar for Node.js 10
15:02:48 Skipping centos6-32-gcc6 for Node.js 10
15:02:48 Skipping ppcle-ubuntu1404-release-64 for Node.js 10
15:02:48 Skipping smartos18-release for Node.js 10
15:02:48 Skipping cross-compiler-armv7-gcc-6 for Node.js 10
15:02:48 Skipping centos6-64-gcc48 for Node.js 10
15:02:48 Skipping aix61-ppc64 for Node.js 10
15:02:48 Skipping pi1-docker for Node.js 10
15:02:48 Skipping vs2019-x86 for Node.js 10
15:02:48 Skipping centos7-64-gcc6 for Node.js 10
15:02:48 Skipping osx1015-release-tar for Node.js 10
15:02:48 Skipping osx1011-release-sources for Node.js 10
15:02:48 Skipping centos7-release-sources for Node.js 10
15:02:48 Skipping osx1015-release-pkg for Node.js 10
15:02:48 Skipping osx1011-release-pkg for Node.js 10
15:02:48 Skipping centos6-32-gcc48 for Node.js 10
15:02:48 Skipping vs2019-x64 for Node.js 10
15:02:48 Skipping smartos15-release for Node.js 10
15:02:48 Skipping centos7-arm64-gcc48 for Node.js 10
15:02:48 Running nodes
15:02:48 Triggering iojs+release » cross-compiler-armv7-gcc-4.9.4
15:02:48 Triggering iojs+release » centos7-ppcle-release-64
15:02:48 Triggering iojs+release » vs2017-x86
15:02:48 Triggering iojs+release » rhel7-s390x-release
15:02:48 Triggering iojs+release » osx1010-release-tar
15:02:48 Triggering iojs+release » centos7-arm64-gcc6
15:02:48 Triggering iojs+release » centos6-64-gcc6
15:02:48 Triggering iojs+release » smartos17-release
15:02:48 Triggering iojs+release » aix71-ppc64
15:02:48 Triggering iojs+release » osx1010-release-pkg
15:02:48 Triggering iojs+release » cross-compiler-armv6-gcc-4.9.4
15:02:48 Triggering iojs+release » vs2017-x64
```

**Comment by rvagg** [comment]
Not just headers, source .tar.?z too. They come from the same builder, which is missing from the list.

The `osx1010-release-sources` label removed 12 days ago, sadly no other metadata regarding why it was removed. https://github.com/nodejs/jenkins-config-release/commit/5f687bc98dc02368b42a388299dcc3e5550048ae#diff-4ed5e2318ff207efda2edc8d96fe238a

I have edits on approx the same day and was messing with osx for >= 13.x builds so it's possibly my fault - sorry! I've put the label back.

* I've run just that builder on your release: https://ci-release.nodejs.org/job/iojs+release/nodes=osx1010-release-sources/5780/ the output should be available in staging for you as soon as that's done.
* I've also done it on the rc-1 which should automatically show up on the website, maybe you want to wait to see that there before proceeding too: https://ci-release.nodejs.org/job/iojs+release/nodes=osx1010-release-sources/5781/

**Comment by BethGriggs** [comment]
Thanks @rvagg - I had to spin the new builds for today's date and the source artificats are back. :)
