### ISSUE TITLE
Fedora-latest-x64 failures for 13.x releasee

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2249]
https://ci.nodejs.org/job/node-test-commit-linux/33730/nodes=fedora-latest-x64/console
https://ci.nodejs.org/job/node-test-commit-linux/33721/nodes=fedora-latest-x64/

Two examplese of the same failure

**Comment by rvagg** [comment]
can't tell exactly what this is, could be oom for compiler maybe? they're only 2G of memory but they're certainly not alone in that. I've done an update and full cleanup on both machines and restarted them, 🤞
