### ISSUE TITLE
Test Coverage?

### ISSUE THREAD

**Issue by DavidTPate** [nodejs/build#225]
Hey there!

I'm looking for some ways to get involved, and it looks like there is code coverage on the roadmap but as best as I can tell there isn't any progress with it. It seems to me that the `build` WG is the place where such progress would be made, so I wanted to check here and see if you guys knew of anything in progress or if there had been anything more about it published out there.

I took a look through TSC notes and your meeting notes here but wasn't able to find anything particularly related to code coverage.

**Comment by jbergstroem** [comment]
Hey! What are your thoughts on the matter? Outlining how your solution would look could be a great way to getting involved.

**Comment by mhdawson** [comment]
I'm not aware of any work on that front but do think its important/interesting.  As jbergstroem mentions a good first step would be to document what you think the next steps would be.

**Comment by DavidTPate** [comment]
Cool, I'll do some additional digging into the testing pipeline that's running right now. IIRC it uses Python to orchestrate everything, so that's likely where instrumentation would be added. It seems like it will take 2 different solutions to determine the coverage of the Javascript & C++ code.

**Comment by rvagg** [comment]
@chrisdickinson began some work on code coverage, perhaps we can pester him for his code.

**Comment by balupton** [comment]
I'm also wondering about this. Would be very insightful to know how much of node.js is actually tested. Including the deps.

**Comment by evanlucas** [comment]
Last I checked, the js was ~72% covered. It was a nightmare to setup, but I'll see if I can do it again

**Comment by jbergstroem** [comment]
@balupton the reason it hasn't been tackled is because no one has stepped up and written any code. Feel free to chip in if you have the time!

**Comment by evanlucas** [comment]
Woah I was way off. More like 85% https://nodejs-coverage-sduffwsopa.now.sh/

That's really old though. I'll try and post the changes I had to make tomorrow.

**Comment by rvagg** [comment]
This might be a good thread to move over to https://github.com/nodejs/testing, it may even be something already on the radar for them, also the Testing Working Group is a great place to get involved and contributing some coverage tooling would be an excellent start.

**Comment by santigimeno** [comment]
> This might be a good thread to move over to https://github.com/nodejs/testing, it may even be something already on the radar for them

Yes, it was something we had on the radar, but no work has been done yet.

> Testing Working Group is a great place to get involved and contributing some coverage tooling would be an excellent start.

Yes, it would be great having more people involved! :D

**Comment by evanlucas** [comment]
For anyone interested, https://github.com/evanlucas/node/commit/2d69f4b02ff945f44a2891986b8d31b1a960f2dd is what I used to generate that. You'll also have to install `istanbul`. https://nodejs-coverage-kvhhcskvtz.now.sh/ is the results for current master branch.

**Comment by santigimeno** [comment]
This is great. Thank you!

**Comment by mhdawson** [comment]
Coverage work progressed in an issue over in the testing WG:  https://github.com/nodejs/testing/issues/36.  Closing this issue.  Please re-open if you disagree.
