### ISSUE TITLE
release-softlayer-centos6-x64-1 is offline

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2267]
https://ci-release.nodejs.org/computer/release-softlayer-centos6-x64-1/

```
Connection was broken

java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:179)
	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:795)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The v10.20.0-rc.2 is waiting on this machine to become available - https://ci-release.nodejs.org/job/iojs+release/5820/console

**Comment by sam-github** [comment]
The machine appears to be down:
```
build/ansible (centos7-devtoolset-8 $ u=) % ssh release-softlayer-centos6-x64-1
^C
build/ansible (centos7-devtoolset-8 $ u=) % grep -A 4 release-softlayer-centos6-x64-1 ~/.ssh/config 
Host release-softlayer-centos6-x64-1 
  HostName 169.62.77.228
  IdentityFile ~/.ssh/nodejs_build_release
  User root

build/ansible (centos7-devtoolset-8 $ u=) % ping 169.62.77.228
PING 169.62.77.228 (169.62.77.228) 56(84) bytes of data.
^C
--- 169.62.77.228 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4095ms
```

It never rains but it pours!

@nodejs/build-infra  Sorry... but any chance  one of you can restart that machine?

**Comment by rvagg** [comment]
@sam-github you have access now don't you?

so this machine has been a persistent trouble, there's no good restart mechanism for jenkins and for some reason monit never got installed properly, maybe our ansible scripts aren't working properly for centos6.

anyway, I've manually added a monit config in there and reloaded monit and Java is back up and running now and hopefully it'll be a bit more reliable in future.

**Comment by sam-github** [comment]
@rvagg  OK, my local ssh config was wrong. I wonder if something is wrong with the write-ssh-config.yml playbook. I just ran it after I got release auth.

**Comment by rvagg** [comment]
@sam-github what was wrong with it? I've had intermittent problems with it across my machines, mostly it works but occasionally the ssh config will be wrong. I thought it was likely a Python and/or Ansible version thing, or related to Linux vs macOS, but never pinned it down.

**Comment by sam-github** [comment]
169.62.77.228 isn't the current IP of that machine, its now 50.97.245.10
