### ISSUE TITLE
Jenkins build history doesn't get updated

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#227]
The build history panel shows the latest build as being from September 23rd. I think this happened after a recent Jenkins upgrade (guessing on Sep 23rd?).

There is a workaround: clicking on the trend link takes you to a page where all the recent history is displayed.

I scanned through 
https://issues.jenkins-ci.org/browse/JENKINS-19720?jql=text%20~%20%22build%20history%22 but couldn't find an issue describing this very problem. I will open a new issue there.

Should we consider a downgrade? @nodejs/build

**Comment by rmg** [comment]
The build order issue is reported as fixed in the latest Jenkins (1.634, released Oct. 18).. I'll post an update when I confirm whether or not it fixes the problem on my own Jenkins server.

**Comment by rmg** [comment]
Seemed to do the trick on my server, so we should either upgrade or downgrade.

BTW, Jenkins changelog points to https://issues.jenkins-ci.org/browse/JENKINS-30899 as the issue tracking this.

**Comment by orangemocha** [comment]
Thanks @rmg! @nodejs/jenkins-admins  , any concerns with upgrading? Are backups up to date?

**Comment by jbergstroem** [comment]
New version deployed.
