### ISSUE TITLE
remove aix61-ppc64 from CI

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2273]
Refs: https://github.com/libuv/libuv/issues/2765

Remove references to `aix64-ppc64` so that the machines can be freed up and potentially reimaged with an in-support version of AIX (either 7.1 or 7.2). We should no longer be build/testing on AIX 6.1 (which is out of support) and should already be build/testing on > AIX 7.1.

For the public test CI, based on https://github.com/nodejs/jenkins-config-test/ and the following shell script:

```
-bash-4.2$ grep aix61-ppc jobs/*  | awk -F'[/:]' '{ print "- [ ] "$2 }' | sort -u
```

These are the jobs that need updating:
- [x] citgm-abi-smoker.xml
- [x] citgm-smoker-nobuild.xml
- [x] citgm-smoker-pipeline.xml
- [x] citgm-smoker-private.xml
- [x] citgm-smoker-v10.x.xml
- [x] citgm-smoker-v12.x.xml
- [x] citgm-smoker.xml
- [x] llnode-pipeline.xml
- [x] node-inspect.xml
- [x] nodereport-continuous-integration-latest.xml
- [x] node-stress-single-test.xml
- [x] node-test-commit-aix.xml
- [x] node-test-node-addon-api-new.xml
- [x] node-test-node-addon-api.xml
- [x] readable-stream-continuous-integration.xml
- [x] readable-stream-pipeline.xml
- [x] string_decoder-continuous-integration.xml
- [x] string_decoder-pipeline.xml

I'll update these but I don't have visibility of the release CI/job backup repository so would need someone else (@sam-github ?) to update the release:

- [x] check-java-version.xml
- [x] iojs+release-joaocgreis.xml
- [x] iojs+release-mdawson-major.xml
- [x] iojs+release.xml

**Comment by richardlau** [comment]
@sam-github run the bash script in the description for this PR but against https://github.com/nodejs/jenkins-config-release (which I assume you've now done as you've edited the list in) and then remove/update the references to `aix61-ppc64` for those jobs (and if you could please check them off when done). I'll do the jobs on the test CI and then when they're all done PR a change to remove `aix61-ppc64` from the VersionSelectorScript.groovy file.

**Comment by sam-github** [comment]
I unchecked the `aix61-ppc64` label in configuration matrix for the ci-release jobs, the label was  already unchecked for check-java-version.xml.

**Comment by richardlau** [comment]
Believe all references to aix61-ppc64 have been removed from both test and release (thanks @sam-github ) CI's. Will open a PR to update the VersionSelectorScript.groovy and select compiler scripts.

**Comment by richardlau** [comment]
Follow up PR to remove from `select-compiler.sh` and `VersionSelectorScript.groovy` scripts: https://github.com/nodejs/build/pull/2292
