### ISSUE TITLE
Automating Email Notifications when there is an "incident"

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2274]
Hey All,

Was talking with @mhdawson about ways to improve communication that would minimize overhead / work for folks (as well as limit room for error). The idea is for a new issue template for `incidents` paired with a github action to email folks that triggers when the `incident` label is added to an issue. We could also use the `incident` tag in conjunction with the github api to automate portions of the  status page being discussed in https://github.com/nodejs/build/issues/2265

As there are many "incidents" and not all require large scale escalation it may make sense to have multiple labels to increase granularity

Thoughts?

**Comment by richardlau** [comment]
If we’re automatically emailing then I think we’d definitely want finer granularity.

**Comment by sam-github** [comment]
I'm generally in favour of automation, so exploring this seems reasonable.

Who would be emailed, and how would people subscibe? All the build-wg were already emailed, so its not the build project itself.

Are you thinking something like https://groups.google.com/forum/#!forum/nodejs-sec, but for infra?

We definitely don't want that _too_ automated, or anyone could open an incident about  _(insert spam topic here)_  and it would be mailed to that entire list.

We don't want to have to update too many places, I'm hearing requests for emails, requests for tweeks, for a status page, for pinned issues, for a nodejs.org banner... Getting the word out is nice, but having to manually sync to all those places would be unreasonable. We need a shorter list, or some tooling to make the reporting *1*-to-many.

**Comment by sam-github** [comment]
@MylesBorins Perhaps the issue can broaden to "automating communication to community", to discuss the other possibilities, like #2265 ? Or should we add that other one to the agenda by itself? I think communication in general is going to be on the agenda.

I labelled and updated the issue description.

**Comment by MylesBorins** [comment]
@sam-github I was actually originally thinking about notifying the TSC but notifying interested community members is not entirely out of scope

**Comment by mhdawson** [comment]
> We definitely don't want that too automated

I think that only collaborators can add tags, so that might ensure that there is some review before it goes on the status page. I'd be temped leave it at that (ie requiring a collaborator to tag the issue) until/if it becomes an issue/problem.

**Comment by MattIPv4** [comment]
The emailing portion of this could likely be achieved through the status page.

If all the relevant components are added and some form of automation is set up so that folks can create incidents for components (or manual incident creation), users should be able to subscribe to specific components on the status page so that they get emails when incidents happen that affect that component.
