### ISSUE TITLE
v12.x LTS expected assets need updating

### ISSUE THREAD

**Issue by codebytere** [nodejs/build#2276]
Discovered during the latest v12.16.2 release:

```sh
# Promoting v12.16.2...
... Checking assets
... Expecting a total of 39 assets for v12.x
... 40 assets waiting in staging
... 0 assets already promoted
 ✓  Complete set of expected assets in place for v12.x
 ✖  The following assets were found in staging but are not expected for v12.x:
    • docs/previous-versions.json
    Does the expected assets list for v12.x need to be updated?
    https://github.com/nodejs/build/tree/master/ansible/www-standalone/tools/promote/expected_assets/v12.x
```

I think that just means adding the new asset [here](https://github.com/nodejs/build/blob/master/ansible/www-standalone/tools/promote/expected_assets/v12.x)?

**Comment by targos** [comment]
This was added in https://github.com/nodejs/node/pull/32518

@richardlau is it expected to be part of the published assets?

**Comment by richardlau** [comment]
> This was added in [nodejs/node#32518](https://github.com/nodejs/node/pull/32518)
> 
> @richardlau is it expected to be part of the published assets?

Didn’t expect that. The file doesn’t need to be there as it’s only used in building the docs and not referenced by the built docs.

**Comment by codebytere** [comment]
Hmm - is there a solution moving forward that's not just adding it to expected assets?

**Comment by richardlau** [comment]
> 
> 
> Hmm - is there a solution moving forward that's not just adding it to expected assets?

https://github.com/nodejs/node/pull/32728 moves (and renames) the file so that it is outside of `out/doc` which should prevent it being published.

**Comment by codebytere** [comment]
Thanks @richardlau - I'll close my PR!

**Comment by rvagg** [comment]
can I just say, yay 🍾 for expected-assets, working really nicely if it's even picking up things like this.
