### ISSUE TITLE
iojs+release doesn't call configure with --verbose, so compiler versions not reported

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2281]
The job does call `gcc --version`, but that's not guaranteed to be the compiler that is configured, AFAICT.

--verbose should be added to the configure flags.

I'll look at this. It quite possibly affects other jobs that are calling configure, so I'll do a dredge through the job XML to find the locations that need changing.

See: https://github.com/nodejs/node/pull/32715

**Comment by richardlau** [comment]
I don’t have visibility of the jobs but it’s possible they do not call configure directly. The Makefile target that builds the tarballs calls configure: https://github.com/nodejs/node/blob/dccdc51788bd5337f9fd80441ef52932383a2441/Makefile#L1163-L1172

**Comment by rvagg** [comment]
They all do `make binary-upload` (or `tar-upload`, or `headers-upload`, or `doc-upload`), but they also have `CONFIG_FLAGS` which is currently `--download-path=${HOME}/node-icu/` for all of them I think. We can just add `--verbose` in there I suppose? Would that be safe all the way back to Node 10?

**Comment by richardlau** [comment]
> They all do `make binary-upload` (or `tar-upload`, or `headers-upload`, or `doc-upload`), but they also have `CONFIG_FLAGS` which is currently `--download-path=${HOME}/node-icu/` for all of them I think. We can just add `--verbose` in there I suppose? Would that be safe all the way back to Node 10?

Yes, 10.x supports the `--verbose` flag: https://github.com/nodejs/node/blob/670f3dbecdfa289942a02543c81c223a76b5af01/configure.py#L575

**Comment by richardlau** [comment]
`--download-path=${HOME}/node-icu/` could probably go as all supported releases should be using the in-tree ICU's (either small for Node.js 10/12 or full for 13+). (On the otherhand it's benign if we keep it.)

**Comment by sam-github** [comment]
OK, `CONFIG_FLAGS` is defined repeatedly, and was missing on AIX (I added it). It now has `--verbose` appended, build: https://ci-release.nodejs.org/job/iojs+release/5897/  (10.x)

I noticed this while looking at an AIX build to confirm that CONFIG_FLAGS was empty:
```
01:00:39 + '[' Xnightly == Xrc ']'
01:00:39 + '[X' == Xdocker ']'
01:00:39 /tmp/jenkins2601478034381801002.sh: line 29: [X: command not found
01:00:39 + echo ostype=AIX72
01:00:39 ostype=AIX72
```

I think its because the AIX jobs have `if ["X${OSVARIANT}" == "Xdocker" ]; then` when they should have `if [[ "X${OSVARIANT}" == "Xdocker" ]]; then`. AIX builds never happen on Docker, it doesn't matter, but I could fix the syntax. Or, should I just delete it?

**Comment by sam-github** [comment]
It looks like adding `--verbose` didn't break anything, but it isn't as useful on 10.x, I  backported the compiler detection PR.

**Comment by sam-github** [comment]
ci-release build was green, but will leave open as a reminder of https://github.com/nodejs/build/issues/2281#issuecomment-613034229

**Comment by richardlau** [comment]
> OK, `CONFIG_FLAGS` is defined repeatedly, and was missing on AIX (I added it). It now has `--verbose` appended, build: https://ci-release.nodejs.org/job/iojs+release/5897/ (10.x)
> 
> I noticed this while looking at an AIX build to confirm that CONFIG_FLAGS was empty:
> 
> ```
> 01:00:39 + '[' Xnightly == Xrc ']'
> 01:00:39 + '[X' == Xdocker ']'
> 01:00:39 /tmp/jenkins2601478034381801002.sh: line 29: [X: command not found
> 01:00:39 + echo ostype=AIX72
> 01:00:39 ostype=AIX72
> ```
> 
> I think its because the AIX jobs have `if ["X${OSVARIANT}" == "Xdocker" ]; then` when they should have `if [[ "X${OSVARIANT}" == "Xdocker" ]]; then`. AIX builds never happen on Docker, it doesn't matter, but I could fix the syntax. Or, should I just delete it?

Single square bracket should be okay but needs a space between the opening square bracket and the double quote.

**Comment by sam-github** [comment]
OK, added single space.
