### ISSUE TITLE
release-nearform-macos10.15-x64-1 offline disk low

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2284]
Copying from https://github.com/nodejs/build/issues/2280#issuecomment-612007594 (sorry, should have just made a new issue in the first place)

And now we now have a bunch of jobs that are in limbo because they're waiting for 10.15 https://ci-release.nodejs.org/computer/release-nearform-macos10.15-x64-1/

> Disk space is too low. Only 0.029GB left on /Users/iojs/build.

```
Filesystem      Size   Used  Avail Capacity iused     ifree %iused  Mounted on
/dev/disk1s5    51Gi   10Gi   39Mi   100%  483463 536625897    0%   /
```

huh? this is that crazy macos cache thing isn't it? anyone know how to fix it? @AshCripps @richardlau ?

----

@richardlau:

> #2173 (comment)? I'm not really a macOS person -- the first time I tried to recreate what @AshCripps did I didn't realize you needed to be root (and not the default Administrator or iojs accounts) to get look at .fseventsd (if that's the issue this time).

---

@AshCripps: 

> Ill also log onto the host see if its at fault

**Comment by AshCripps** [comment]
The host machine is fine has 66GB of room so the issue is on the machine itself

**Comment by rvagg** [comment]
```
# du -hsc $(ls -A)
  0B	.DS_Store
  0B	.VolumeIcon.icns
  0B	.file
 10M	.fseventsd
  0B	.vol
9.4G	Applications
5.4G	Library
 50G	System
 15G	Users
  0B	Volumes
2.4M	bin
  0B	cores
4.5K	dev
  0B	etc
  0B	home
  0B	opt
8.8G	private
1016K	sbin
  0B	tmp
1.2G	usr
  0B	var
 90G	total
```

**Comment by rvagg** [comment]
I'm heading off for the evening. I've brought the node back online to see what it does but it may get bumped again. Someone with jenkins-release-admins access may need to bring it back online again if/when it's rectified: https://ci-release.nodejs.org/computer/release-nearform-macos10.15-x64-1/

**Comment by AshCripps** [comment]
50G in system? I wonder if ive left the catalina image or something stupid on there

**Comment by rvagg** [comment]
your key is in that machine as administrator still, so if you could take a look that would be good

**Comment by AshCripps** [comment]
So looking into it im not sure we have an issue beside just actually running out of space.
Catalina seems to have introduced a read-only system folder which stores all the operating system files to make them immuatable and to protect the user, this includes /. User data is then mounted under /System/Volumes/Data which is why we df -h reports weirdness. it seems to think theres around 35G missing from / when its actually used in the mounted /System/Volumes/Data folder for the user.
example output 
```sh
sh-3.2# df -h
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s5    51Gi   10Gi  2.3Gi    82%  483463  536625897    0%   /
devfs          186Ki  186Ki    0Bi   100%     644          0  100%   /dev
/dev/disk1s1    51Gi   34Gi  2.3Gi    94%  570621  536538739    0%   /System/Volumes/Data
/dev/disk1s4    51Gi  4.0Gi  2.3Gi    64%       5  537109355    0%   /private/var/vm
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
/dev/disk2s3   8.2Gi  7.6Gi  554Mi    94%    1060 4294966219    0%   /Volumes/Install macOS Catalina
```

But when you run diskutil to look at the apfs (Apple Filesystems) `/` is mounted as a system directory (immuatable) and `/System/Volumes/Data` is mounted as data (user files)

```
sh-3.2# diskutil apfs list
APFS Container (1 found)
|
+-- Container disk1 A6D36C10-F3D8-4A18-B123-00F9361CFF33
    ====================================================
    APFS Container Reference:     disk1
    Size (Capacity Ceiling):      54999998464 B (55.0 GB)
    Capacity In Use By Volumes:   52570992640 B (52.6 GB) (95.6% used)
    Capacity Not Allocated:       2429005824 B (2.4 GB) (4.4% free)
    |
    +-< Physical Store disk0s2 25B8F381-DC5C-40C4-BCF2-9B22412964BE
    |   -----------------------------------------------------------
    |   APFS Physical Store Disk:   disk0s2
    |   Size:                       54999998464 B (55.0 GB)
    |
    +-> Volume disk1s1 0A81F3B1-51D9-3335-B3E3-169C3640360D
    |   ---------------------------------------------------
    |   APFS Volume Disk (Role):   disk1s1 (Data)
    |   Name:                      Macintosh HD - Data (Case-insensitive)
    |   Mount Point:               /System/Volumes/Data
    |   Capacity Consumed:         36838895616 B (36.8 GB)
    |   FileVault:                 No
    |
    +-> Volume disk1s2 85CCF587-3818-41CC-A201-4514A72CABA6
    |   ---------------------------------------------------
    |   APFS Volume Disk (Role):   disk1s2 (Preboot)
    |   Name:                      Preboot (Case-insensitive)
    |   Mount Point:               Not Mounted
    |   Capacity Consumed:         83947520 B (83.9 MB)
    |   FileVault:                 No
    |
    +-> Volume disk1s3 7CE5424E-D62B-493F-85F1-4DCBC0D826CC
    |   ---------------------------------------------------
    |   APFS Volume Disk (Role):   disk1s3 (Recovery)
    |   Name:                      Recovery (Case-insensitive)
    |   Mount Point:               Not Mounted
    |   Capacity Consumed:         528543744 B (528.5 MB)
    |   FileVault:                 No
    |
    +-> Volume disk1s4 F388B6DA-E11B-4E9F-B354-F98A043298FB
    |   ---------------------------------------------------
    |   APFS Volume Disk (Role):   disk1s4 (VM)
    |   Name:                      VM (Case-insensitive)
    |   Mount Point:               /private/var/vm
    |   Capacity Consumed:         4296548352 B (4.3 GB)
    |   FileVault:                 No
    |
    +-> Volume disk1s5 ED7807D6-4575-4E07-89B1-F3C1576ED618
        ---------------------------------------------------
        APFS Volume Disk (Role):   disk1s5 (System)
        Name:                      Macintosh HD (Case-insensitive)
        Mount Point:               /
        Capacity Consumed:         10702733312 B (10.7 GB)
        FileVault:                 No
```

So im not sure if this is anything beyond Apple doing Apple things. Saying that I will increase the size of the disk to give us some headroom (already did this for the test machines to update them)

**Comment by AshCripps** [comment]
Increased disk by 10GB, restarted and repartioned the machine should be good to go for a while now

**Comment by richardlau** [comment]
@AshCripps Thanks for doing this on a bank holiday.
