### ISSUE TITLE
nominate Richard Lau for jenkins-release-admin team

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2286]
He's been active in the build-wg for quite a while, and he's one of the more capable maintainers of Jenkins we have, but not having access to ci-release.nodejs.org means he has to ping one of https://github.com/nodejs/build#release-jenkins-admins to find out what's going on over there.

It also improves our TZ coverage, since he's in Europe.

**Comment by addaleax** [comment]
SGTM

**Comment by mhdawson** [comment]
+1 from me.

**Comment by rvagg** [comment]
yes pls, also wouldn't mind getting him into build_release secrets too, if we can couple that with this elevation.

**Comment by joaocgreis** [comment]
+1 for both the jenkins-release-admin team and release access level.

**Comment by gireeshpunathil** [comment]
+1 to both

**Comment by sam-github** [comment]
release secrets: https://github.com/nodejs-private/secrets/pull/101  @richardlau try them out pls

**Comment by richardlau** [comment]
> release secrets: [nodejs-private/secrets#101](https://github.com/nodejs-private/secrets/pull/101) @richardlau try them out pls

Will do so after dinner.

**Comment by richardlau** [comment]
> 
> 
> release secrets: [nodejs-private/secrets#101](https://github.com/nodejs-private/secrets/pull/101) @richardlau try them out pls

Thank you. I have access.

**Comment by MylesBorins** [comment]
+1
