### ISSUE TITLE
Jenkins config change request: allow rebasing onto a Pull Request ref

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2294]
If we try to set `REBASE_ONTO` to a ref to a Pull Request, we get the following error:

```
14:34:05 + git rev-parse refs/pull/32889/head
14:34:05 fatal: ambiguous argument 'refs/pull/32889/head': unknown revision or path not in the working tree.
14:34:05 Use '--' to separate paths from revisions, like this:
14:34:05 'git <command> [<revision>...] -- [<file>...]'
14:34:05 refs/pull/32889/head
14:34:05 Build step 'Execute shell' marked build as failure
```

The error happens because `git` won't fetch GitHub Pull Request refs by default. To avoid this error and enable rebasing onto PRs, we need to fetch the ref first:

```diff
--- checkout.old.sh     2020-04-16 14:39:12.042429877 -0700
+++ checkout.sh 2020-04-16 14:38:58.174203510 -0700
@@ -12,11 +12,11 @@
 
 git status
 git rev-parse HEAD
-git rev-parse $REBASE_ONTO
 
 if [ -n "${REBASE_ONTO}" ]; then
+  git fetch ${REBASE_ONTO}
   git rebase --abort || true
-  git rebase --committer-date-is-author-date $REBASE_ONTO
+  git rebase --committer-date-is-author-date FETCH_HEAD
 fi
 
 if [ -n "${POST_REBASE_SHA1_CHECK}" ]; then
```

Is this a reasonable change to our Jenkins configs?

**Comment by rvagg** [comment]
seems reasonable, but does it need a remote in the `git fetch` to be robust?

**Comment by mmarchini** [comment]
Yes it does, nice catch.

**Comment by rvagg** [comment]
I didn't write that code originally and don't really touch it, so I don't feel entirely comfortable saying it'd be a safe replacement. I think @joaocgreis may have his head around it more than most of us so might be able to give input.

**Comment by joaocgreis** [comment]
The issue here is that REBASE_ONTO is frequently a commit hash. Git doesn't allow fetching a specific commit, but this might have changed in recent versions. So, to improve we need something that works with both a hash and a ref. So, perhaps something like:
```
(git fetch ${REBASE_ONTO} && git branch -f jenkins_rebase_tmp FETCH_HEAD) || git branch -f jenkins_rebase_tmp ${REBASE_ONTO}
```
and then rebase on top of `jenkins_rebase_tmp`.

Note this is done on `git_rebase` for the fanned jobs and on each individual job for all others, so there are a lot of places to change.
