### ISSUE TITLE
CNAME for status.nodejs.org

### ISSUE THREAD

**Issue by MattIPv4** [nodejs/build#2298]
Pulling this request out into its own issue from https://github.com/nodejs/build/issues/2265#issuecomment-614856603

To continue the setup of the new status page, we'd like to enable it on `status.nodejs.org`. To do this, a DNS entry needs to be added for the `status` subdomain, with a CNAME record that points to `rxy2rhgm8q1n.stspg-customer.com`.

A preview of the status page that will be displayed on this subdomain can currently be found at https://nodejs1.statuspage.io/

**Comment by Trott** [comment]
@rvagg Is this something only you are able to handle?

**Comment by rvagg** [comment]
this is handled by cloudflare, so those with access can edit these
I've added status -> rxy2rhgm8q1n.stspg-customer.com CNAME.

**Comment by MattIPv4** [comment]
Thank you! Looks like we're good to go: https://status.nodejs.org/
