### ISSUE TITLE
node-test-commit-linux-containerd consistently failing debug build with OOM

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2300]
Example from daily master: https://ci.nodejs.org/job/node-test-commit-linux-containered/19652/nodes=ubuntu1804_sharedlibs_debug_x64/console

```
test-commit-linux-containered/out/Debug/obj.target/tools/v8_gypfiles/libv8_compiler.a /home/iojs/build/workspace/node-test-commit-linux-containered/out/Debug/obj.target/tools/v8_gypfiles/libv8_initializers.a -lm -ldl -Wl,--end-group
00:13:50 collect2: fatal error: ld terminated with signal 9 [Killed]
00:13:50 compilation terminated.
00:13:50 /usr/bin/ld: error: /home/iojs/build/workspace/node-test-commit-linux-containered/out/Debug/mkcodecache(.debug_info) is too large (0x26a5a8ad bytes)
00:13:50 mkcodecache.target.mk:208: recipe for target '/home/iojs/build/workspace/node-test-commit-linux-containered/out/Debug/mkcodecache' failed
```

This looks like an OOM on a debug link, its fairly common on  node dailies:
- https://ci.nodejs.org/job/node-daily-master/1910/ for example

Can also be seen in job history for that config:
- https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1804_sharedlibs_debug_x64/

@rvagg suggestions for fixing? is more memory possible?

cc: @BethGriggs

**Comment by rvagg** [comment]
Yeah, all of the failures in the first page of https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1804_sharedlibs_debug_x64/ are on the Joyent docker host. It's underpowered compared to the DO ones but it has fewer containers running on it to compensate. Maybe adding the cross compiler just pushes it over the edge.

FTR there are 3 ways we can tweak these hosts:

1. Increase the base VM size to deal with increased capacity (difficult on some providers, I think this is why the Joyent machine is smaller)
2. Decrease the number of containers running on the VM, see secrets/test/inventory.yml for the list on each: the DO machines have 12, the SoftLayer and Joyent ones have 11, but not all of these are actively used. The number of `ubuntu1804_sharedlibs` containers can easily be reduced and that just reduces the probability that there'll be _too many_ concurrent jobs running on the host.
3. Change `JOBS` inside the containers. Each of these hosts have it set to `4`, this is also done in secrets/test/inventory.yml with `server_jobs: 4`.

I think for the Joyent host a combination of 2 and 3 might be a good approach for now. Reduce the number of sharedlibs containers by 1 and decrease `JOBS` to `3` should get both the probability of high concurrency down and also the absolute maximum `gcc` concurrent jobs down too. I'll run that now but will have to do a server restart which can be awkward with so many nodes attached from a single host.

**Comment by rvagg** [comment]
made those changes, here's hoping that's enough to deal with this, reopen if this persists
