### ISSUE TITLE
Planned outage for test-osuosl-aix72-ppc64_be-2

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2305]
FYI @nodejs/libuv 

This coming Monday, April 27th,  test-osuosl-aix72-ppc64_be-2 will be taken down so that the hardware its running on can get some routine maintenance. Its predicted it will occur sometime during the day, Oregon (US) time, and take about 4 hours.

libuv-test-commit-aix uses this machine for xlc builds, and is the only user.

https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-2/builds

Sorry for the disruption, it should be fairly brief.

**Comment by sam-github** [comment]
Got this early this morning, it looks like it was partially sucessful, but there will need to be another update.

```
The firmware update was successful on Monday and all of the systems restarted.  However, not all of the updates were able to complete during the maintenance window so Michael plans another maintenance window

Thursday, 30 April 2020, 0600 GMT - 1200 GMT

This will update the firmware on the I/O adapters: RAID, Ethernet and HDD.

Please plan accordingly and alert the relevant Open Source communities.
```

**Comment by richardlau** [comment]
@sam-github Did the additional update happen?

**Comment by sam-github** [comment]
I believe so, but another is planned, #2329
