### ISSUE TITLE
How are the API docs and i18n versions published

### ISSUE THREAD

**Issue by nschonni** [nodejs/build#2307]
Cross linking with https://github.com/nodejs/i18n/issues/315 as we're trying to figure out what versions to keep around or re-add.
I poked around a little here, and I know the githook is used for publishing the other nodejs.org built content, but I'm not finding where the docs or i18n versions are published.

**Comment by rvagg** [comment]
I don't know anything about i18n docs other than what the website does, but for nodejs.org/api and nodejs.org/docs they're symlinking into the release directories.

https://github.com/nodejs/nodejs-latest-linker is run after releases and it maintains a directory that's just symlinks, /home/dist/nodejs/docs, which is exposed as https://nodejs.org/docs/ and each of those directories are links into the release docs directory. https://nodejs.org/docs/v14.0.0/ for example is what you get if you go to https://nodejs.org/download/release/v14.0.0/docs/. There's also the same `latest-vx.x` directories which do the same thing, and a special `latest` directory that links to the latest release build by version number (usually Current, except in those awkward moments where there's a switch to LTS before a new Current comes out). nginx is configured to serve `/home/dist/nodejs/docs/latest/api` as nodejs.org/api, which is where we get the most commonly used API docs from.

Does that help? I don't know where the i18n docs figure in that process if they're not part of the nodejs/node repo, perhaps that content is being shunted through nodejs/nodejs.org, check out the build script there maybe?

**Comment by nschonni** [comment]
Thanks, that is helpful. I get the feeling that the i18n stuff might be orphaned content right now if that is the case. There probably needs to be some sort of language selector along with some re-write rules developed if the i18n content is going to be directly integrated with the existing docs content.

Not sure if they're is a good place in the `docs/` folder to describe the current setup in case someone else tries to figure this out later

**Comment by rvagg** [comment]
> Not sure if they're is a good place in the docs/ folder to describe the current setup in case someone else tries to figure this out later

if you mean in this repo then 👍, moar docs = moar good, if you have the time to contribute that would be great
