### ISSUE TITLE
Request access to release secrets for AshCripps

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2310]
Needed for doing https://github.com/nodejs/build/blob/master/ansible/MANUAL_STEPS.md#signing-certificates

see: https://github.com/nodejs/build/issues/2309#issuecomment-618537735

@AshCripps has access already to some of the secrets because he can ssh into a subset of the machines, but isn't in the dotgpg group to see the whole set. Given his level of ssh access and the type of machine maintenance he's doing, I think this would be helpful.

**Comment by richardlau** [comment]
+1. Makes sense given that's he's been creating the new release macs.

**Comment by mhdawson** [comment]
+1
