### ISSUE TITLE
many jobs waiting for `jenkins-workspace`

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2312]
Reported by @BethGriggs. Several jobs were queued up "waiting for next available executor for `jenkins-workspace`".

I've restarted the Jenkins agent on [test-packetnet-ubuntu1804-x64-1](https://ci.nodejs.org/computer/test-packetnet-ubuntu1804-x64-1/) as per https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#general-issues-with-jenkins-agent-normal-machines-edition. 

[test-packetnet-ubuntu1804-x64-2](https://ci.nodejs.org/computer/test-packetnet-ubuntu1804-x64-2) appeared to be online and processing jobs when I checked it.

**Comment by richardlau** [comment]
According to https://ci.nodejs.org/label/jenkins-workspace/ there are five nodes with the `jenkins-workspace` label:
- test-packetnet-ubuntu1604-x64-1 
- test-packetnet-ubuntu1604-x64-2 
- test-packetnet-ubuntu1804-x64-1 
- test-packetnet-ubuntu1804-x64-2 
- test-softlayer-ubuntu1604-x64-1

The two ubuntu1804 nodes are now online and processing jobs.

The two packetnet ubuntu1604 are intentionally disconnected ("Disconnected by rvagg : retiring"). @rvagg should the softlayer ubuntu1604 node be running (it's not currently)?

**Comment by rvagg** [comment]
Increasing the number of parallel jobs those machines can handle is also an acceptable solution. They're set fairly low at the moment.

**Comment by rvagg** [comment]
1604 nodes intentionally disconnected. Need to reprovision at least one new 1804 one, a job I obviously forgot to get around to! Will try and get it done tomorrow.

**Comment by richardlau** [comment]
> 
> 
> 1604 nodes intentionally disconnected. Need to reprovision at least one new 1804 one, a job I obviously forgot to get around to! Will try and get it done tomorrow.

Have marked [test-softlayer-ubuntu1604-x64-1](https://ci.nodejs.org/computer/test-softlayer-ubuntu1604-x64-1/) offline in Jenkins with a reason pointing to the above comment.

**Comment by richardlau** [comment]
Job queue has dropped from 212 waiting jobs to 136 so this should resolve itself over time. Will check again in an hour or so.

**Comment by richardlau** [comment]
Queue is now 43, so should be back to normal in a couple of hours.
