### ISSUE TITLE
Metrics dip?

### ISSUE THREAD

**Issue by bnb** [nodejs/build#2314]
I just opened up the metrics site for the first time in quite a while and it seems that there's a humungous dip across all metrics.

I'm curious if this is an issue with the metrics themselves or some external factor that dramatically changed the numbers?

https://nodejs.org/metrics/

**Comment by MylesBorins** [comment]
My understanding is that we had a giant dip when we switched to serving the assets from a CDN (cloudflare). If I recall we have not yet properly fixed how we are logging in take. There was an issue, I thought, but I couldn't find it with a quick search

**Comment by rvagg** [comment]
dupe https://github.com/nodejs/TSC/issues/794

WIP, Ash has joined the effort too
