### ISSUE TITLE
citgm-smoker-pipeline jobs cannot start properly

### ISSUE THREAD

**Issue by targos** [nodejs/build#2318]
@nodejs/citgm-admins 

Example: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/96/

Subjobs fail with a Java stack trace:

```
org.apache.commons.jelly.JellyTagException: jar:file:/var/lib/jenkins/plugins/show-build-parameters/WEB-INF/lib/classes.jar!/jenkins/plugins/show_build_parameters/ShowParametersBuildAction/summary.jelly:30:67: <st:include> org.apache.commons.jelly.JellyTagException: jar:file:/var/cache/jenkins/war/WEB-INF/lib/jenkins-core-2.222.1.jar!/lib/form/entry.jelly:77:23: <d:invokeBody> org.apache.commons.jelly.JellyTagException: jar:file:/var/lib/jenkins/plugins/matrix-combinations-parameter/WEB-INF/lib/matrix-combinations-parameter.jar!/hudson/plugins/matrix_configuration_parameter/taglib/matrix.jelly:51:27: <d:invokeBody> No such property: all for class: groovy.lang.Binding
	at org.apache.commons.jelly.impl.TagScript.handleException(TagScript.java:726)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:281)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
```
- https://ci.nodejs.org/job/citgm-smoker-nobuild/773/

**Comment by richardlau** [comment]
In the main pipeline console there is this:
```
The parameter 'MACHINES' did not have the type expected by citgm-smoker-nobuild. Converting to Matrix Combinations Parameter.
```

I think what is happening is that there’s a mismatch between the `MACHINES` parameter in the pipeline (a string) and in the downstream job (a matrix parameter) where `all` is not a valid value. I don’t know if this broke on a Jenkins update or an update we did to the downstream job.

We might be able to fix this by detecting `all` in the pipeline and then omitting passing that on (omitting should result in the default value of the downstream job being used). I’ll try it out later this afternoon when I turn on my computer.

**Comment by richardlau** [comment]
I've not been able to successfully convert any value of `MACHINES` (e.g. `rhel7-s390x`) into a matrix combination parameter that works in the downstream job (tried following https://issues.jenkins-ci.org/browse/JENKINS-41036 but it started the job on all machines). I've taken the `MACHINES` parameter out of the pipeline job for now -- i.e. for now there's no way for us to filter the machines at the pipeline level.

**Comment by targos** [comment]
It's better than nothing, thanks!
