### ISSUE TITLE
update citgm jobs

### ISSUE THREAD

**Issue by targos** [nodejs/build#2319]
@nodejs/citgm-admins 

Please remove Node.js v8 and add v14 to:
* https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/build
* https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration-pipeline/build
* https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/build

**Comment by richardlau** [comment]
Done!

**Comment by targos** [comment]
Thank you :)
