### ISSUE TITLE
incident: git being removed from centos7-ppc64 hosts

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2321]
This has been failing builds since I re-ansibled the hosts in the process of https://github.com/nodejs/build/pull/2320

https://github.com/nodejs/build/blob/1f89d391408fa3932b6ba64671ac6d7654cddea9/ansible/roles/baselayout/tasks/main.yml#L69-L73 seems to be removing git, but I'm not sure why.

```
TASK [baselayout : centos | remove existing git package] **************************************
changed: [test-osuosl-centos7-ppc64_le-1]  
```

https://github.com/nodejs/build/commit/7cac270fecaace4315dd1f9c26bb5ea2075c378f seems to be the source. I've added usage of direct package installs of git at https://github.com/nodejs/build/blob/1f89d391408fa3932b6ba64671ac6d7654cddea9/ansible/roles/baselayout/vars/main.yml#L44-L46, I suspect that upstream packages are now git 1.8, so the code to remove it and curl an rpm package down could be removed.

And looking at that commit, I realize its the source of the "os arch"  capability I'm asking about in https://github.com/nodejs/build/pull/2320/files#r419577643, where I'm not sure how to find the correct "arch" strings.

There also might be an order dependency here, since git is both installed by package using the package vars, and removed, its hard to know the winner.

In the short term, I just parallel-ssh installed git onto osuosl-centos7-ppc64_le machines, but since any ansible run will remove it, a fix that achieves the desired effect across all the `centos7*` is needed.

**Comment by sam-github** [comment]
I tried `centos7_ppc` and `centos7_ppc64le` (what uname says, `ppc64le`), but they didn't match arch either.

**Comment by targos** [comment]
It looks like git is still missing from at least one of the hosts: https://ci.nodejs.org/job/node-test-commit-plinux/32735/nodes=centos7-ppcle/console

**Comment by sam-github** [comment]
I'm sorry, I was experimenting, trying to find the arch string ansible uses for these hosts, and forgot that every ansible run removes git. Its back.

**Comment by sam-github** [comment]
@rvagg any thoughts on the right way to sort this out?

**Comment by richardlau** [comment]
To debug what the value of a variable is (e.g. `arch`):
```
$ ansible -m debug -a "var=arch"  test-osuosl-centos7-*
...
test-osuosl-centos7-ppc64_le-2 | SUCCESS => {
    "arch": "ppc64"
}
test-osuosl-centos7-ppc64_le-1 | SUCCESS => {
    "arch": "ppc64"
}
```
or `os`:
```
-bash-4.2$ ansible -m debug -a "var=os"  test-osuosl-centos7-*
...
test-osuosl-centos7-ppc64_le-2 | SUCCESS => {
    "os": "centos7"
}
test-osuosl-centos7-ppc64_le-1 | SUCCESS => {
    "os": "centos7"
}
```

For installing packages I think the `os_arch` combinations are ignored? At least it looks like this is the step that installs packages: https://github.com/nodejs/build/blob/1f89d391408fa3932b6ba64671ac6d7654cddea9/ansible/roles/baselayout/tasks/main.yml#L75-L84

which loops through
1. `packages[os]`, i.e. `centos7` for the ppcle machines, https://github.com/nodejs/build/blob/1f89d391408fa3932b6ba64671ac6d7654cddea9/ansible/roles/baselayout/vars/main.yml#L48-L50
1. `packages[os|stripversion]`, i.e. `centos` for the ppcle machines, (no currently defined variable)
1. `common_packages`, i.e. https://github.com/nodejs/build/blob/1f89d391408fa3932b6ba64671ac6d7654cddea9/ansible/roles/baselayout/vars/main.yml#L30-L32

compare with the macOS step which does loop through `os+'_'+arch` first: https://github.com/nodejs/build/blob/1f89d391408fa3932b6ba64671ac6d7654cddea9/ansible/roles/baselayout/tasks/main.yml#L86-L97

**Comment by sam-github** [comment]
I think #2320 fixes this now.

**Comment by rvagg** [comment]
Iirc we removed got and opted for one that cane with devtools (? Or somewhere) because it was newer and supported features we wanted or dealt with security concerns, or something.

I don’t mind the approach in #2320 as long as we look out for reasons that the standard `git` might be a problem.
