### ISSUE TITLE
PSA: Scheduled maintanence of our orka environment

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2323]
Just received this email:

```
Hi Ashley,

Your 4th node is ready to be configured. This will require downtime in your environment. Is there a good maintenance window that works for you? Any running VMs will need to be spun down. 
```

As this is quite disruptive we need to be careful with the timing, ive asked them to send back a rough timeframe for the downtime but in the meantime @nodejs/build any ideas of a good timeframe?

**Comment by richardlau** [comment]
@AshCripps If possible try to avoid release and release candidate dates (see the stickies on https://github.com/nodejs/Release/issues for upcoming planned dates).

CC @nodejs/releasers

**Comment by AshCripps** [comment]
ive been given the option of 1pm EST today or is that too soon @richardlau

**Comment by richardlau** [comment]
I think it should be okay.

**Comment by AshCripps** [comment]
Ive picked 1pm EST today

**Comment by sam-github** [comment]
SGTM. also, won't builds continue on the nearform machines even if orka is down?

**Comment by AshCripps** [comment]
> SGTM. also, won't builds continue on the nearform machines even if orka is down?

You're right I had glossed over that fact.

**Comment by AshCripps** [comment]
So, uh, turns out this maintenance was for *AdoptOpenJDK* not us. Some wires were crossed and my name was given in mistake. Closing this issue now but will reopen if we are given any maintenance.

**Comment by AshCripps** [comment]
They are upgrading us to Orka v 1.2.0 which should be non disruptive, scheduled for 1PM EST

**Comment by AshCripps** [comment]
Orka is upgraded, if you want to make use of the cli features download the latest cli here - https://orkadocs.macstadium.com/docs/orka-v120
