### ISSUE TITLE
SSL certificate issues

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#233]
A few people have reported issues regarding to ssl certificates. I triaged it to lacking SNI support. According to [Wikipedia](https://en.wikipedia.org/wiki/Server_Name_Indication) the only client that seems remotely close would be wget, with the first supported release roughly three years ago (unless some distros compile clients specifically without certain features of x509).

The way to solve this is adding an additional IP for each SSL host we use (which in practise would mean one for iojs and one for nodejs) or moving SSL termination to Cloudflare which would require us to upgrade to a pro or business account.

I'm not sure how widespread this issue is, but either of above solution should be pretty easy to implement.

**Comment by Starefossen** [comment]
Here is the [SSL Server Test report for nodejs.org](https://www.ssllabs.com/ssltest/analyze.html?d=nodejs.org&s=104.20.23.46&latest), at least on the browser side almost all of them support SNI.

**Comment by jbergstroem** [comment]
connecting to the default vhost won't help them since that would return the wrong certificate for iojs.org (`*.nodejs.org`)

**Comment by jbergstroem** [comment]
It looks like the vm's at travis-ci.org seems to have a too old version of `wget`.

**Comment by ljharb** [comment]
This issue affects all travis-ci VMs that aren't in their new "container" format (ie, `sudo: false` is the new one) - and it may indeed affect the new ones also, but I haven't checked.

**Comment by Starefossen** [comment]
So this issue is limited to old wget-users downloading io.js binaries? Mostly through travis ci which there apparently exists a workaround for?

**Comment by jbergstroem** [comment]
That'd be my conclusion based on wikipedia. We for instance have this issue on our centos5 slaves; but again limited to wget.

**Comment by rvagg** [comment]
I've just tried out the new "Floating IP" DO feature on the web server, it now has 45.55.98.129 pointing to it, _but_ the server doesn't appear to be aware of this, it's obviously just a datacenter routing thing rather than going all the way down to the server like it can with AWS. So I'm not sure we're going to be able to do the separate IP thing unless we have a separate server which is a pain since we've gone through the process of integrating everything.

**Comment by jbergstroem** [comment]
@rvagg doesn't that just mean we can assign another ip with network setup? I can try.

**Comment by rvagg** [comment]
you can try I guess, I have left it on there for this kind of tinkering

**Comment by jbergstroem** [comment]
So, the anchor ip you set up locally is where we want to point iojs (or nodejs, but i prefer messing up the prior). Not sure how to automate all of this ansible though. I'll look at that first.

**Comment by jbergstroem** [comment]
OK, this likely needs to happen:

1. cloudflare: upgrade iojs.org to a business account and upload the certificate
2. cloudflare: change iojs.org to listen at the anchor public ip address 
3. nginx: make iojs listen at the internal anchor address
4. (probably optional) nginx: make nodejs listen at the default public address

**Comment by rvagg** [comment]
I recently downgraded iojs.org to a personal account because I discovered that my personal credit card was being charged $200/month for the pleasure of it being a business account...

**Comment by ljharb** [comment]
@rvagg how recently? Perhaps that's what triggered these SSL issues.

**Comment by rvagg** [comment]
pretty sure it's unrelated, we didn't lose any features that we were using as far as I know

**Comment by jbergstroem** [comment]
As far as i know, going from business to free or using business won't affect SNI. What we need is an enterprise account to get our own ip.

**Comment by ljharb** [comment]
ah, gotcha

**Comment by Trott** [comment]
@nodejs/build @jbergstroem Should this remain open?

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
