### ISSUE TITLE
FYI: node.js sec release june 2nd

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2331]
Please keep an eye on the issue tracker in case ci incidents come up during release process.

Also, ci will be locked down the day before the release is built.

**Comment by targos** [comment]
@nodejs/jenkins-admins please lock down CI ASAP, we are almost ready to test the releases.

**Comment by richardlau** [comment]
> 
> 
> @nodejs/jenkins-admins please lock down CI ASAP, we are almost ready to test the releases.

I'll do this. Just let me reread https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#security-releases first to remind myself what to do.

**Comment by richardlau** [comment]
CI is now locked down.

**Comment by targos** [comment]
Releases are out. CI can be unlocked.

**Comment by richardlau** [comment]
CI should now be unlocked.

**Comment by mscdex** [comment]
CI access still seems to be denied?

**Comment by sam-github** [comment]
What, specifically?

https://github.com/nodejs/build/blob/master/static-assets/jenkins-authorization-normal.png is what it should be

https://ci.nodejs.org/configureSecurity/ is what it is

The look aligned.

I have too much admin access, so its hard for me to test what a collaborator would see.

**Comment by mscdex** [comment]
It was showing "Access Denied" for the test PR job for example. However now it's showing a 404 for the same page.

**Comment by mscdex** [comment]
Visiting the main CI site, all of the category tabs show no jobs associated with each one except for libuv and post-mortem. The "All" tab just show a few extra jobs not found on any other tab, like "node-inspect".

**Comment by sam-github** [comment]
@rvagg Do you have any idea what's going on? I've tried to make things as they should be, but no luck.

**Comment by targos** [comment]
I had to click on the "log in" button to see all jobs. usually the login is automatic

**Comment by mscdex** [comment]
It showed me as logged in, but I logged out and then back in and it seems to be working now. That's bizarre...

**Comment by richardlau** [comment]
I think it was a GitHub blip with logins: https://www.githubstatus.com/incidents/q3cfsrp1qb6l

**Comment by sam-github** [comment]
Interesting, yes, I was also prompted for login, which I don't normally see.
