### ISSUE TITLE
nominate AshCripps for ci-release admin access

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2333]
He maintains a number of the release machines, and has release machine CI access:  https://github.com/nodejs-private/secrets/tree/master/build/release/.gpg

That he doesn't have https://github.com/nodejs/build#release-admins access is likely an oversight.

It would be useful to him when adding machines or checking their connectivity status after responding to incidents, updating the systems, ansibiling, etc. As-is, he has to ask someone else to do these final checks.

**Comment by AshCripps** [comment]
Turns out I already have this, closing.
