### ISSUE TITLE
offboard sam-github from build-wg

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2339]
Hi folks. I'm not expecting to have time to work on the build going forward. @AshCripps and @richardlau are well able to continue anything I was working on. Its been a pleasure to help out where I could. If something comes up where some bit of information is missing that only I have (I really don't expect that), please don't hesitate to reach out to me, and I'll do my best.

I'll offboard myself to save you all the work :-)

Cheers!

### Offboarding issue checklist

(Remove items if not applicable)

- [x] Remove their GPG key from `test` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `release` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `infra` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `infra-macstadium` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `github-bot` group in `nodejs-private/secrets`
- [x] Remove them from build teams they are a member of:
    - [x] nodejs/build
    - [x] nodejs/build-release
    - [x] nodejs/build-infra
    - [x] nodejs/jenkins-admins
    - [x] nodejs/jenkins-release-admins
    - [x] nodejs-private/build
- [x] PR changes to [README.md](./README.md#build-wg-members) to move the member to emeritus status
- [x] Run `ncu team sync` to vaildate the user has been removed from the build teams
- [x] Remove them from the [`nodejs/email`](https://github.com/nodejs/email) alias

**Comment by richardlau** [comment]
Thanks @sam-github for everything you’ve done.

**Comment by sam-github** [comment]
Sorry, I can't remove my secret keys. That makes sense, dotgpg can't encrrypt the file with a key if that key isn't allowed to decrypt the file.

I'll do the github stuff.

**Comment by sam-github** [comment]
sigh.

```
w/build (master u=) % ncu-team sync README.md
✔  Received member information of nodejs/build
✔  Received member information of nodejs/build-infra
✔  Received member information of nodejs/jenkins-admins
✔  Received member information of nodejs/jenkins-release-admins
✔  Received member information of nodejs/github-bot
Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (fs.js:940:3)
    at exports.writeFile (/home/sam/.nvm/versions/node/v12.16.3/lib/node_modules/node-core-utils/lib/file.js:18:8)
    at Function.TeamInfo.syncFile (/home/sam/.nvm/versions/node/v12.16.3/lib/node_modules/node-core-utils/lib/team_info.js:61:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/sam/.nvm/versions/node/v12.16.3/lib/node_modules/node-core-utils/bin/ncu-team:64:7) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT'
}
```
