### ISSUE TITLE
z/OS hosts offline

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2345]
All of our z/OS hosts are offline. I can ssh into them and have tried restarting the Jenkins agent, but the agent is unable to connect back to https://ci.nodejs.org. We see this in the agent logs (`/u/iojs/jenkins.log`:
```
Caused by: java.security.cert.CertPathValidatorException: The certificate issued by CN=USERTrust RSA Certification Authority, O=The USERTRUST Network, L=Jersey City, ST=New Jersey, C=US is not trusted; internal cause is:
        java.security.cert.CertPathValidatorException: Certificate chaining error
        at com.ibm.security.cert.BasicChecker.<init>(BasicChecker.java:111)
```

Which looks like it's related to those root certs that expired at the end of May: https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020 which also caused issues in https://github.com/nodejs/build/pull/2337.

**Comment by rvagg** [comment]
Is it possible this might be fixed on the hosts? I removed the expired certificates from the chain but it looks like this host wants a complete chain. I think the only option there is to regenerate the cert from scratch.

**Comment by richardlau** [comment]
I've reached out internally in IBM for advice. One of the things I'm looking at is whether we can update Java since what we're currently running was built in 2016.
```
IOJS:/u/iojs: >/usr/lpp/java/J8.0_64/bin/java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pmz6480sr3fp22-20161213_02(SR3 FP22))
IBM J9 VM (build 2.8, JRE 1.8.0 z/OS s390x-64 Compressed References 20161209_329148 (JIT enabled, AOT enabled)
J9VM - R28_20161209_1345_B329148
JIT  - tr.r14.java.green_20161207_128946
GC   - R28_20161209_1345_B329148_CMPRSS
J9CL - 20161209_329148)
JCL - 20161213_01 based on Oracle jdk8u111-b14
IOJS:/u/iojs: >
```
(I don't think that was installed via ansible.)

**Comment by richardlau** [comment]
After some investigation it appears that this should be resolved by updating the version of Java we are using to include APAR IJ05800 (which adds the "USERTrust RSA Certification Authority" to the Java's cacerts): https://www.ibm.com/support/pages/apar/IJ05800

We currently are running Java 8 SR3 FP22 (see [previous post](https://github.com/nodejs/build/issues/2345#issuecomment-641217133)). According to https://developer.ibm.com/javasdk/support/zos/ the latest available Java 8 is SR6 FP10.

I've sent an email to our contact for marist to see if we can get Java updated.

**Comment by richardlau** [comment]
For reasons updating the system Java is tricky (to the extent that we're being asked if we can move to a z/OS 2.4 system (we're currently on z/OS 2.2)). 

I'm going to try to mitigate in the meantime by unpacking a more recent Java locally and running the Jenkins agent with that. I've done so on `test-marist-zos13-s390x-1`, which is running builds. I'll look at what we need to update in the ansible scripts.

**Comment by richardlau** [comment]
This was addressed by https://github.com/nodejs/build/pull/2346.
