### ISSUE TITLE
Another massive drop in download numbers

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2349]
https://nodejs.org/metrics/summaries/country.png

Haven't dug into the actual metrics yet but it seems to have happened around ~April

Any idea?

**Comment by AshCripps** [comment]
I am working with @rvagg and @jbergstroem to bring the metrics back in https://github.com/nodejs/build/pull/2025.

I can see all the data its just not visible to the world yet, coincidentally I think the latest drop conicides with I picked up the work and Rod turned off the rsync jobs that were filling up the metrics server.

**Comment by AshCripps** [comment]
Closing, I have a google bucket with the numbers available from last week (backfilling will come at a later date) and we are having dicusssion on how best to expose these. On a side note if anyone would like to see them feel free to message me and I can provide the links.
