### ISSUE TITLE
Test installers somehow

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#235]
I dunno how exactly this would work, but it sure would be great.

See https://github.com/nodejs/node/issues/3606 on issues changing even minimal installer stuff can create.

@pmuellr Linked this to me, maybe it could help verifing everything. at least on OS X: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/installer.8.html

**Comment by Fishrock123** [comment]
Also, I think this is something we can only really do on the CI accurately.

**Comment by jbergstroem** [comment]
Sounds like we'd want to perfect an uninstaller on each os for this to run smoothly.

**Comment by orangemocha** [comment]
> Sounds like we'd want to perfect an uninstaller on each os for this to run smoothly.

.. or using VMs or containers that are reset at the beginning of each run.

**Comment by jbergstroem** [comment]
@orangemocha that won't really solve the users problem which most likely tied to old stuff laying around. We should essentially test:
 - install version X then Y
 - uninstall version X then install Y
 - install version Y
 - uninstall version Y

Then rinse&repeat for a multitude of versions.

**Comment by orangemocha** [comment]
I see what you mean. I was suggesting that we would need to be able to reset things to a clean state because if any of those uninstalls failed it could affect subsequent tests and, even worse, subsequent runs.

**Comment by Trott** [comment]
@nodejs/build @Fishrock123 Should this remain open?

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
