### ISSUE TITLE
Device busy on `test-requireio_joeyvandijk-debian10-armv7l_pi2-1` and `test-requireio_piccoloaiutante-debian10-arm64_pi3-1`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2352]
```console
16:41:11 + '[' -d .git ']'
16:41:11 + git clean -fdx
16:41:16 warning: failed to remove out/Release/.nfs00000000018c38000000068d: Device or resource busy
16:41:16 Removing out/junit
```

Just restarted both agents. `test-requireio_joeyvandijk-debian10-armv7l_pi2-1` is back online, `test-requireio--piccoloaiutante-debian10-arm64--pi3-1` isn't yet (it's been almost 10 minutes), the agent might have more problems. I've marked the node as offline for now.

**Comment by mmarchini** [comment]
Jenkins says `test-requireio--piccoloaiutante-debian10-arm64--pi3-1` is connected, but I can't ssh into it. If others can though, feel free to mark the agent as online.

**Comment by rvagg** [comment]
Most of the 3s were offline (couldn't ssh) so I've power cycled them and they're all back online (except the one that has bigger problems). I'm not sure what's up with that, there was a 2 offline as well but the rest of the cluster was fine. Hopefully not a sign of general instability among the 3s, which are more heavily used.
