### ISSUE TITLE
CI jobs with --experimental-quic

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#2353]
The experimental QUIC support has landed in nodejs/node main branch. This is not built by default. It requires the use of the `--experimental-quic` configure flag to be enabled. It would be fantastic if we could have a set of jobs specific to QUIC on a subset of linux, mac, and windows machines that enable the `--experimental-quic` flag so that we can run CI on relevant PRs.  (for Windows, the flag is `vcbuild experimental-quic`)

**Comment by jasnell** [comment]
Note: none of the sharedlibs-openssl jobs should be included in the set of jobs using the `--experimental-quic` config.

**Comment by mmarchini** [comment]
https://ci.nodejs.org/job/node-test-commit/ with `CONFIG_FLAG=--experimental-quic` should work (well, for *nix jobs, I don't know about Windows). Would that be enough? Creating a new job (especially one that is not part of `node-test-pull-request`) can increase maintenance burden on the WG.

**Comment by jasnell** [comment]
It works, but since that includes the sharedlibs-openssl we won't ever get a completely green run since we cannot use quic with the shared openssl build

**Comment by rvagg** [comment]
> we cannot use quic with the shared openssl build

What's the hang-up on this? Is it the age of the openssl we have in sharedlibs? I haven't updated it in a while and could go ahead and do that to be more reasonably reflective of what people are likely using in the wild.

**Comment by richardlau** [comment]
> 
> 
> > we cannot use quic with the shared openssl build
> 
> What's the hang-up on this? Is it the age of the openssl we have in sharedlibs? I haven't updated it in a while and could go ahead and do that to be more reasonably reflective of what people are likely using in the wild.

My understanding (https://github.com/nodejs/node/issues/29817#issuecomment-572645297) is that quic support in OpenSSL won't arrive until OpenSSL 3.0 at the earliest and for Node.js the embedded OpenSSL has been patched (https://github.com/nodejs/node/pull/32377). So Node.js' quic support won't work with stock OpenSSL 1.1.1 (which is one of the reasons it's behind a non-default configure flag).

**Comment by rvagg** [comment]
Ah, well if that's the case then maybe someone wants to hack together a bit of bash in https://ci.nodejs.org/view/All/job/node-test-commit-linux-containered/ (in the `ubuntu1804_sharedlibs_openssl111_x64` job, I think that's all that's run for master) to exclude shared openssl when someone passes the `--experimental-quic` `CONFIG_FLAGS`. That'd at least help get to green.
