### ISSUE TITLE
Meeting to discuss build WG help

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2354]
As discussed we've been asking the Board to see what they can do in terms of lining up additional Build WG members as well as having some of the routine work be handled through paid resources.

We are exploring an option through the Linux foundation. We shared the initial potential scope for paid resources that we put together earlier and they are asking for a meeting to gather more info about what we have, how we run them etc.

I'm opening this to see who from the build WG team would like to be invited to that meeting.  

I'll leave it open for a week and then we'll go ahead and schedule with those who have responded.

**Comment by mhdawson** [comment]
@nodejs/build one more call for interest.

**Comment by AshCripps** [comment]
@mhdawson what would discussion be about? just how build is run and what our day to day looks like?

**Comment by jbergstroem** [comment]
Not very clear to me what the expectations would be either.

**Comment by mhdawson** [comment]
I forwarded Brian from the foundation the "jenkins care and feeding scope" that we'd reviewed earlier. They said they would like to get together to better understand our infra. So to answer the question it is to better help them understand what we have, answer any questions etc.

**Comment by AshCripps** [comment]
in that case I don't mind attending

**Comment by jbergstroem** [comment]
I can join too.

**Comment by rvagg** [comment]
I've been holding off from this because my attendance is going to screw up timeslot planning. Maybe send me the invite when you arrive at a time but I'm not likely to show up if it's earlier than ~10pm UTC.

**Comment by mhdawson** [comment]
@brianwarner I think we are ready to schedule the meeting. I'd suggest we try for 6PM EST which is 10UTC.  I know that will mean it's late for @AshCripps but I can catch him up afterwards.

**Comment by mmarchini** [comment]
I can try to attend depending on the date (otherwise I'll read the notes afterwards)

**Comment by mhdawson** [comment]
This is long stale, closing.
