### ISSUE TITLE
Remove chakracore CI jobs?

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#2355]
Given that the node-chakracore repository is now archived and that effort has been discontinued, the numerous chakracore related CI jobs can be cleaned up and removed, and the associated @nodejs/node-chakracore and @nodejs/node-chakracore-admins teams can be deleted.

**Comment by rvagg** [comment]
This just needs someone from @nodejs/jenkins-admins to do the work. There's also some remnants in ci-release too that could be removed. I already moved the cron jobs for nightlies previously.

**Comment by jbergstroem** [comment]
(note: remove these jobs from disk too, not sure if removing the job will do this)

**Comment by joaocgreis** [comment]
Removed 9 jobs from test and 1 from release. Had to update the backup script to support new and deleted jobs, so many older unrelated changes appear in these commits:
- https://github.com/nodejs/jenkins-config-test/commit/2fd3bdef1f72cfe4ebc25aa43aceeb502e8398cf
- https://github.com/nodejs/jenkins-config-release/commit/46ecbe91dad1f0f9809788b7dbcaf32febf5fb80

Confirmed the jobs were removed from disk by Jenkins.
