### ISSUE TITLE
Proposal to move the early build call to a more EU friendly slot

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2356]
@nodejs/build with a few of us being in the european time zones I would like to propose moving the early build call to a more eu friendly timeslot (i.e. within the european working day).

Im suggesting to just move the early build call as the later one is a good time slot for @rvagg. 

I want to see what peoples opinions are first before posting a doodle or something to get a better idea of times.

**Comment by rvagg** [comment]
The current early slot is no good for me anyway and I've been skipping it entirely, so if you want to move it earlier then it won't impact me. When we go through the next DST switch it would move into a more manageable slot, but we've for a way to go before then.

**Comment by mhdawson** [comment]
I'm good with it moving earlier as well.

**Comment by AshCripps** [comment]
@nodejs/build Ive set up a [doodle](https://doodle.com/poll/9yf24nz5kpeigg9a) with some options if people could vote or maybe suggest others that would be great.

**Comment by AshCripps** [comment]
<img width="71" alt="image" src="https://user-images.githubusercontent.com/26796102/90261471-e509f980-de44-11ea-965b-b540ec9c3bd9.png">
 
Weve had five responses and the most popular result was 13:00-14:00 London time (BST)
