### ISSUE TITLE
Node.js Build working group audit

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2357]
5 months after https://github.com/nodejs/build/issues/2140 im finally getting round to this.

@nodejs/build Please comment here if you are planning to remain active within the working group or are happy to be moved to emeritus.

I plan to wait ~2 weeks before pinging members who havent responded individually. After a month member will be automatically moved to emertius.

Reminder as per our [Governance](https://github.com/nodejs/build/blob/master/GOVERNANCE.md#wg-membership) emeritus members will be welcomed back if they wish to return.

**Comment by richardlau** [comment]
Am planning to remain active.

**Comment by mmarchini** [comment]
I haven't been much active in the WG in a while except for occasionally responding to incidents (i.e. rebooting machines mostly). I'll try to remain active, but can't really promise anything at the moment. If folks think it's better for me to move to emeritus I'm fine with that as long as I can retain access to test machines, as it has been quite useful to unblock PRs when there's an infra issue.

**Comment by AshCripps** [comment]
@mmarchini Personally im not looking for everyone to be active-active. (contributing to the node org as whole is good enough for me), this is more to clean up our access from people who have left the project.

**Comment by MylesBorins** [comment]
I have not been super active but do appreciate the permissions that I get in CI from being a member. Happy to move to emeritus if folks prefer, but would like to remain a member if there are no complaints

**Comment by jbergstroem** [comment]
I would like to stay around if possible.

**Comment by AshCripps** [comment]
@MylesBorins that's completely your choice with regards to moving to emeritus, the Jenkins access is separate so it's just whether you would like to keep the machine access and recieving pings when something goes wrong.

@jbergstroem as a member of build infra I don't think we could afford to lose you :).

**Comment by phillipj** [comment]
I'd like to be able to maintain and access the host where @nodejs-github-bot is located.

Sadly don't have time to contribute in other build concerns. If you'd prefer removing me from the build team to reduce my privileges and insight, that would be fine with me as long as I can ping others to get help with updating my SSH key etc when needed.

**Comment by rvagg** [comment]
active

**Comment by mhdawson** [comment]
active

**Comment by Trott** [comment]
active (or at least active-ish)

**Comment by joaocgreis** [comment]
active (though not much this month)

**Comment by AshCripps** [comment]
Ping those who havent responded yet:
@LucaLanziani 
@bnoordhuis 
@addaleax 
@Starefossen 
@maclover7 
@joyeecheung 
@gireeshpunathil

**Comment by bnoordhuis** [comment]
Active(ish)

**Comment by LucaLanziani** [comment]
Thanks for the ping @AshCripps , I've tried my best but it's proven hard to find the time so I think it's for the best if I get removed from the working group.

Thanks everyone for the opportunity and sorry for not coming forward sooner about this. Hopefully things will change in the future and I will be able to help a bit here ;).

**Comment by Starefossen** [comment]
I haven’t been much active lately but if there are interest for moving more of the build and test infrastructure towards Infrastructure as Code with Terraform and/or Kubernetes I would love to help out with that.

**Comment by AshCripps** [comment]
FInal warning ping:

@addaleax
@maclover7
@joyeecheung
@gireeshpunathil

Ill start the removal processes on monday if I havent heard otherwise

**Comment by joyeecheung** [comment]
I plan to remain active(ish)

**Comment by AshCripps** [comment]
Audit complete. Offboarding being tracked in #2390.
