### ISSUE TITLE
Node.js jenkins-admins audit 

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2358]
5 months after #2140 im finally getting round to this.

@nodejs/jenkins-admins Please comment here if you still require this access or happy to be moved to emeritus

I plan to wait ~2 weeks before pinging members who havent responded individually. After a month member will be automatically moved to emertius.

**Comment by richardlau** [comment]
Please keep my access.

**Comment by mhdawson** [comment]
Please keep my access

**Comment by jbergstroem** [comment]
I can probably drop my admin access to jenkins at this point.

**Comment by MylesBorins** [comment]
please keep my access

**Comment by rvagg** [comment]
access

**Comment by Trott** [comment]
please keep

**Comment by jbergstroem** [comment]
"edit:" Seeing how it was useful just now to debug some disk related issues, I think I'll stay around for a bit longer.

**Comment by joaocgreis** [comment]
Please keep my access.

**Comment by AshCripps** [comment]
Ping those who havent responded:
@maclover7 
@joyeecheung

**Comment by mmarchini** [comment]
Joyee is on vacation, I'd suggest wait until she's back for a response.

**Comment by joyeecheung** [comment]
Please keep my access (thanks @mmarchini for responding for me ;)

**Comment by AshCripps** [comment]
Audit complete. Offboarding being tracked in #2390.
