### ISSUE TITLE
 test-softlayer-debian9-x64-1 offline

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2360]
Agent is offline and rebooting the agent doesnt bring it back.

Trying to use bash on the system throws out a read-only filesystem error - going to follow the instructions [here](https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#read-only-filesystem)

**Comment by AshCripps** [comment]
getting this error 
```
root@test-softlayer-debian9-x64-1:~# e2fsck -y /dev/xvda2
e2fsck 1.43.4 (31-Jan-2017)
/dev/xvda2: recovering journal
e2fsck: Bad magic number in super-block while trying to re-open /dev/xvda2

/dev/xvda2: ********** WARNING: Filesystem still has errors **********

root@test-softlayer-debian9-x64-1:~#
```

possibly more worrying of an error

**Comment by rvagg** [comment]
did an OS reload in IBM cloud and a reinstall with Ansible, it's back online now
