### ISSUE TITLE
Upgrade openssl to 1.1.1g on ubuntu1804_sharedlibs_openssl111_x64

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#2363]
Refs: https://github.com/nodejs/node/pull/33981#issuecomment-647107568 - [this CI run](https://ci.nodejs.org/job/node-test-commit-linux-containered/20895/nodes=ubuntu1804_sharedlibs_openssl111_x64/consoleFull) specifically

I'm 90% sure that's caused by that buildbot using openssl 1.1.1b in `/opt/openssl-1.1.1b`. Can it be upgraded to 1.1.1g?

Alternatively, Ubuntu 18.04 has a security back-port of 1.1.1 according to https://launchpad.net/ubuntu/bionic/+source/openssl and that gets us closer to testing what the distros link against.

**Comment by richardlau** [comment]
Yes, it can. Relevant lines in ansible are https://github.com/nodejs/build/blob/d4b074cd221cce329ee1f31292e3114845390a56/ansible/roles/docker/templates/ubuntu1804_sharedlibs.Dockerfile.j2#L57-L65

PR's welcome 😄.

**Comment by richardlau** [comment]
(To clarify, the ansible template will first need to be updated and then one of https://github.com/nodejs/build#jenkins-admins will need to reansible the sharedlib containers.)

**Comment by rvagg** [comment]
I'll do it. May as well do Alpine 3.12 while I'm there.

**Comment by rvagg** [comment]
Upgraded to 1.1.1g, see #2364, but seeing failures on test-crypto-authenticated-stream on master, https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1804_sharedlibs_openssl111_x64/20939/, so I don't think the problem is in https://github.com/nodejs/node/pull/33981, it's on master already.
