### ISSUE TITLE
Resume Build option for Release Builds

### ISSUE THREAD

**Issue by codebytere** [nodejs/build#2371]
Would it be possible to add the ability to resume build for release jobs, a la:

<img width="196" alt="Screen Shot 2020-06-30 at 12 29 09 PM" src="https://user-images.githubusercontent.com/2036040/86168635-5841f100-bacd-11ea-8157-41a48c04edd0.png">

In my current case, i have one failure: https://ci-release.nodejs.org/job/iojs+release/6144/nodes=osx1015-release-tar/console

while all other jobs passed: https://ci-release.nodejs.org/job/iojs+release/6144

and it would be awesome if it was more intuitive to rerun the one build.

**Comment by richardlau** [comment]
Unfortunately I'm not sure this is possible without recreating the job from scratch. 

Resume build is a feature from the Multijob plugin (https://issues.jenkins-ci.org/browse/JENKINS-30505). 

node-test-pull-request and node-test-commit are [multijob](https://wiki.jenkins.io/pages/viewpage.action?pageId=59510168) projects whereas the iojs+release is a [multi-configuration (i.e. matrix)](https://wiki.jenkins.io/display/JENKINS/Building+a+matrix+project) project. The type of project is selected when it is created -- AFAIK there's no way to convert from one type to another.

![image](https://user-images.githubusercontent.com/5445507/86184082-4c851780-bb2b-11ea-8dfb-cb45e3963508.png)

![image](https://user-images.githubusercontent.com/5445507/86184135-69214f80-bb2b-11ea-9d32-69689ca550f5.png)

![image](https://user-images.githubusercontent.com/5445507/86184203-8c4bff00-bb2b-11ea-91a0-397c76b80d55.png)

**Comment by mhdawson** [comment]
Even if we have to recreate from scratch I could see this being quite helpful.

**Comment by rvagg** [comment]
I think right now you can untick builds you don't want run if you do a re-run can't you? It's not ideal, but at least it doesn't force you to rerun everything and you can just rerun an individual builder if you want.
