### ISSUE TITLE
PSA: Maintanence of AIX7.1 Machines in CI

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2378]
On Monday 17th August all of our AIX7.1 machines will be taken down at 6AM ET for maintanence and will be brought back up by the end of the day.

I will disable the agents in jenkins before the window to prevent jenkins jobs being held up.

**Comment by richardlau** [comment]
I've disabled https://ci.nodejs.org/job/node-test-commit-aix/ and marked the two AIX 7.1 test machines offline.

**Comment by richardlau** [comment]
Machines are now back online. I've reenabled the job.
