### ISSUE TITLE
Cross-compliling addon for napi benchmark on Raspberry Pi

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2382]
I'm adding benchmark tests to CI in https://github.com/nodejs/node/pull/34288. The napi benchmark fails on Raspberry Pi because the result of the `bench-addons-build` task in Makefile needs to be available to the machine executing the test.

**Comment by rvagg** [comment]
So what files need to be included? This should all be possible by fixing up https://ci.nodejs.org/view/All/job/node-cross-compile/ and adding in whatever files are needed. Currently it goes like this:

```sh
BINARY_FILES="config.gypi icu_config.gypi node out/Release/node out/Release/openssl-cli"
if [ -f out/Release/libnode_test_engine.so ]; then
  BINARY_FILES="${BINARY_FILES} out/Release/libnode_test_engine.so"
fi

md5sum out/Release/node
rm -rf binary
mkdir -p binary
tar cf binary/binary.tar ${BINARY_FILES}
xz -9v binary/binary.tar
```

The binary/binary.tar.xz gets added to a git pack and pushed to the shared git repo. Then on the Pi side it gets fetched from that repo and unpacked. So whatever's in it gets unpacked into a raw source checkout. We could just add more `if [ -f ...` blocks if you have other files to include and it'll always attempt to include those whenever a cross is run.

**Comment by Trott** [comment]
Looks like it just needed some Makefile changes that have happened. (@richardlau pointed out that the prerequisite build step and the test itself should have been added to the native suites job and not the JS suites job. WIth that change, everything seems to be working.) It's passing in CI now. Sorry for the noise.
