### ISSUE TITLE
Auditing @nodejs/platform-windows

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2389]
Hi, @nodejs/platform-windows! If you're still active and want to be pinged on windows issues, can you please respond here?  A single word comment of "active" or "stay" or "remain" or something like that is fine. Thanks!

Refs: https://github.com/nodejs/admin/issues/518

**Comment by joaocgreis** [comment]
stay

**Comment by Trott** [comment]
Time to close the loop on this one. Kept the five folks who commented. Removed the five who didn't. 

@jdalton @digitalinfinity @piscisaureus @RReverser @seishun If this is an oversight and you want to stay on the platform-windows team, leave a comment here and I'll add you back!
