### ISSUE TITLE
Use non-standard ssh port

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#239]
We'd avoid a million bruteforce attempts by just switching ssh port (and making sure password auth is disabled). This should be part of every setup.

**Comment by TheAlphaNerd** [comment]
Do we have something like [fail2ban](http://www.fail2ban.org/wiki/index.php/Main_Page) set up on the server?

I've had fantastic success minimizing bruteforce attacks with it

**Comment by jbergstroem** [comment]
@TheAlphaNerd nope. adding all its variations on all of our hosts is somewhat tedious. feel free to PR, but changing port would be the simplest way to avoid bruteforce stuff.

**Comment by TheAlphaNerd** [comment]
I just took a quick perusal... please correct me if I am wrong here

* build/setup is a set of ansible scripts used for creating each of the platforms we are testing on?
* each platform has its own playbook
* adding a meta service such as fail2ban would require adding it to each service
   * testing as well

**Comment by jbergstroem** [comment]
@TheAlphaNerd correct. not sure how well abstracted the firewall implementations are either (ipfw on freebsd, pf on solaris, etc).

**Comment by Starefossen** [comment]
If insecure password auth is disabled, as it should be, what is the benefit by moving to an non-standard port? Just wondering. Is the brute force attempts a DDoS concern? Obviously they will never be successful in brute forcing RSS SSH keys.

**Comment by bnoordhuis** [comment]
Your sshd logs not getting flooded is one.

**Comment by jbergstroem** [comment]
@Starefossen: at one of our boxes when i logged in earlier today:
> There were 1047183 failed login attempts since the last successful login.

The question for me is "why not". A poorly configured client sounds like the least of our issues.

**Comment by jbergstroem** [comment]
Here's another one:
> Last failed login: Mon Nov  9 11:18:15 UTC 2015 from a.b.c.d on ssh:notty
> There were 14542 failed login attempts since the last successful login.

(that's 10 hours)

**Comment by Starefossen** [comment]
Yes, that is quite a lot of failed login attempts. I guess "why not".

**Comment by imjacobclark** [comment]
This should be pretty standard to do in the ansible-playbook, pseudo code where the host ssh config lives in `/etc/ssh/sshd_config`.

ansible-vars: 
```ansible
ubuntu_common_ssh_port: 9999
```

ansible-playbook
```
- name: Change ssh port
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^Port\s"
              line="Port {{ common_ssh_port }}"
              state=present
  notify: Restart ssh
```

Is this something I could pick up? 

Are there any docs over the best way to get everything working locally to test any changes? Or is it just a case of working through Ansible on a vanilla VM, provision and test that way?

**Comment by jbergstroem** [comment]
You would have to check for 9999 or 22 as well when connecting, right (otherwise you wouldn't know if the port needs to change)?

I usually test on local ansible with bhyve vm's.

**Comment by imjacobclark** [comment]
Yes that's correct, I guess if you know which resource you're connecting to, you would know the port number too, prevents 22 spam/bruit force attacks as a minimum prevention.

**Comment by jbergstroem** [comment]
`^Port` might not work; default configs usually does `# Port`; How about `^(#\s)?Port\s`?

**Comment by imjacobclark** [comment]
Ah yes quite right. I'll pick this up!

**Comment by jbergstroem** [comment]
I'm still not sure how to catch connection errors from ansible's `ansible_ssh_port` (just `ssh_port` in ansible 2.0 which we will be targetting) so a connection fail to 12345 would make us try 22 and run the ssh job though.

**Comment by Trott** [comment]
@nodejs/build @jbergstroem Seems do-able but just needs a committed person to make it happen maybe?

**Comment by maclover7** [comment]
Closing for now as something that would be nice to have, but seems to not currently be within our means. If someone wants to tackle this, please feel free to reopen.
