### ISSUE TITLE
Offboard inactive members

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2390]
Follow on from #2357 and #2358 

Checklist for the offboarding of the following members:

@LucaLanziani  (build)
@maclover7 (build and jenkins)
@addaleax (build)
@gireeshpunathil (build)

Thank you all for your contributions and you will be welcomed back if you wish to return!

### Offboarding issue checklist

- [x] Remove their GPG key from `test` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `release` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `infra` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `infra-macstadium` group in `nodejs-private/secrets`
- [x] Remove their GPG key from `github-bot` group in `nodejs-private/secrets`
- [x] Remove them from build teams they are a member of:
    - [x] nodejs/build
    - [x] nodejs/build-release
    - [x] nodejs/build-infra
    - [x] nodejs/jenkins-admins
    - [x] nodejs/jenkins-release-admins
    - [x] nodejs-private/build
- [x] PR changes to [README.md](./README.md#build-wg-members) to move the member to emeritus status
- [x] Run `ncu-team sync README.md` to validate the user has been removed from the build teams
- [x] Remove them from the [`nodejs/email`](https://github.com/nodejs/email) alias

**Comment by AshCripps** [comment]
@nodejs/build anyone had any experience as to when I tried to clean up these keys from secrets it deleted the inventory.yml file as well? (I did also try to clean up an old keys of georges that was still left in the folder)

**Comment by jbergstroem** [comment]
@AshCripps haven't seen that. Did you use `dotgpg rm` to remove the keys?

**Comment by AshCripps** [comment]
yep I did get some gem errors though - 
```
/Library/Ruby/Gems/2.3.0/gems/gpgme-2.0.19/lib/gpgme/ctx.rb:385:in `import_keys': Too many open files (GPGME::Error)
```

**Comment by rvagg** [comment]
Silly low open files limit on macos, you need to increase the limit, `ulimit -n 10000` or something. There's a more advanced command that sets it permanently but I don't have that at hand. Check out a clean copy of the repo, lift the limit in your current shell and run it again.

**Comment by AshCripps** [comment]
Removed from the secrets repo - all except luca's key got `not a valid gpg key` for that one.
Will need someone to remove @maclover7's key from githubbot secrets as I dont have access and then someone to remove the above from the github teams as im not a maintainer.

**Comment by rvagg** [comment]
done

**Comment by AshCripps** [comment]
Can the one of the members of build with TSC overlord powers remove the poeple at the top of the issue from the respective teams please? @mhdawson @Trott @mmarchini

**Comment by mhdawson** [comment]
@AshCripps done, does not look like there is a **nodejs/build-release** team, was that the right name?

**Comment by AshCripps** [comment]
build-release is referring to secrets team I believe

**Comment by mhdawson** [comment]
@AshCripps there is no team specifically related to secrets but those in the `nodejs-private/build` team have access to the secrets repo. I've remove the inactive members from that team so I think we should be good.

**Comment by mmarchini** [comment]
Is build-release referring to the private keys instead?

**Comment by AshCripps** [comment]
> Is build-release referring to the private keys instead of a team?

sorry yes its referring to those you have access to the keys - theres no "team" as such cause there doesnt need to be.

**Comment by AshCripps** [comment]
Closing as complete.
