### ISSUE TITLE
Update version of Java 8 on AIX and Linux on Power CI machines

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2393]
_Originally posted by @richardlau in https://github.com/nodejs/build/issues/2387#issuecomment-662366511_:
> ... update the version of Java 8 that we're using -- we're currently using https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u192-b12 which is from October 2018 (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u262-b10 is the current Java 8).
https://github.com/nodejs/build/blob/9cf3680add6ee833cff9bdf855d5c9ab70c1532a/ansible/roles/java-base/tasks/main.yml#L124-L129

- [ ] Update ansible scripts
- [ ] Run ansible to update
  - [ ] test-ibm-aix71-ppc64_be-1
  - [ ] test-ibm-aix71-ppc64_be-2
  - [ ] test-osuosl-centos7-ppc64_le-1
  - [ ] test-osuosl-centos7-ppc64_le-2

We're currently using binaries from https://github.com/AdoptOpenJDK/openjdk8-releases/ on most of the IBM platforms in the CI (other platforms are using package managers). We've hardcoded URLs into [`ansible/roles/java-base/tasks/main.yml`](https://github.com/nodejs/build/blob/9cf3680add6ee833cff9bdf855d5c9ab70c1532a/ansible/roles/java-base/tasks/main.yml) and these link directly to a specific version of Java 8.

i.e.
- AIX https://github.com/nodejs/build/blob/9cf3680add6ee833cff9bdf855d5c9ab70c1532a/ansible/roles/java-base/tasks/main.yml#L124-L129 

- Linux on Power https://github.com/nodejs/build/blob/9cf3680add6ee833cff9bdf855d5c9ab70c1532a/ansible/roles/java-base/tasks/main.yml#L35-L39)

- LinuxONE https://github.com/nodejs/build/blob/9cf3680add6ee833cff9bdf855d5c9ab70c1532a/ansible/roles/java-base/tasks/main.yml#L64-L68

The versions being used on AIX and Linux on Power are circa 2018 (the LinuxONE version is from January of this year so is reasonably up to date):
- May 2018: https://github.com/AdoptOpenJDK/openjdk8-releases/releases/tag/jdk8u172-b11
- October 2018: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u192-b12

At this time the most recent version of Java 8 is either:
- https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u262-b10
- https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u262-b10_openj9-0.21.0 (if we want to switch to J9 like we have done for LinuxONE)

**Comment by sxa** [comment]
As mentioned to Richard the adoptopenjdk project [has an API](https://api.adoptopenjdk.net) which can be used to download the java binaries. There is also the option to use the [AdoptOpenJDK RPM/DEB repositories](https://adoptopenjdk.net/installation.html#linux-pkg) but for simplicity and consistency across Operating Systems using the tarballs may be the better bet. Ref https://github.com/nodejs/build/pull/2143 where we switched the Node.js Linux/s390x systems to use AdoptOpenJDK's OpenJ9 variant due to the performance benefits of using a jenkins agent with a working JIT
