### ISSUE TITLE
Add @richardlau as a new active releaser

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2395]
Figured this should be a separate issue from https://github.com/nodejs/Release/issues/499 and https://github.com/nodejs/Release/pull/588 for visibility.

I'm being onboarded as a new releaser https://github.com/nodejs/Release/issues/585 and am now at the stage where I've been added to various additional GitHub teams as per https://github.com/nodejs/Release/blob/master/GOVERNANCE.md#adding-new-releasers. This also says:
> Have a single, high quality SSH key added to the "dist" user on the primary www server (see below for guidelines regarding SSH key quality).
> ...
> The public key can be shared with an existing member of the releasers team to be placed on the www server for access to the "dist" user. The private key should be kept very secure and not shared with anyone. Any actual or suspected compromise of the private key should be reported immediately and the key should be entirely removed from use.

So could someone from @nodejs/releasers please add my public ssh key (https://github.com/richardlau.keys) please?

**Comment by rvagg** [comment]
done, will be good to have someone new from build on there to have full visibility into the pipeline, maybe you can help improve the tooling while you have your head in there

**Comment by richardlau** [comment]
Thank you.
