### ISSUE TITLE
libuv: stop using `-j` flag to `cmake --build .` with `make`, and/or use `ninja`

### ISSUE THREAD

**Issue by vtjnash** [nodejs/build#2402]
(moving here from https://github.com/libuv/libuv/issues/2930)

https://ci.nodejs.org/job/libuv-test-commit-osx-cmake/ appears to often failing because it's doing `cmake --build . -j`, which is causing the bots to exceed their physical/virtual memory limits while running the compiler. The `-j` parameter needs some limit when using the `make` backend, or it needs to switch to another backend like `-G Ninja` (which will ignore the flag). Thanks!

**Comment by rvagg** [comment]
👍 thanks for catching that @vtjnash, we have a `$JOBS` on each of our CI machines and normally use that whenever we use `-j` or `JOBS=` but that's been left off in this instance. I've inserted that back and you should see a `-j 2` now on these runs I think.

https://ci.nodejs.org/job/libuv-test-commit-osx-cmake/177/ is a repeat of the last green run, https://ci.nodejs.org/job/libuv-test-commit-osx-cmake/174/, to confirm this is working properly. Please close this issue if you agree it's fixed now.

**Comment by vtjnash** [comment]
Yep, that looks good now. (well, it says `-j4`, but that should be good)
