### ISSUE TITLE
Need to update CITGM Jenkins job to support npm flag for new peer dep behavior

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2406]
Using CITGM to test out npm 7 and need to introduce a new toggle to turn on / off the new peer dep behavior.

I'm doing some local experiments first to figure out the best way to implement this and if we need to do anything in CITGM itself

**Comment by richardlau** [comment]
Can this be implemented as a CITGM flag? The current jobs give a string parameter to specify the CITGM command used.

**Comment by MylesBorins** [comment]
@richardlau it likely will have to be implemented in CITGM. Still doing a bit of local work to figure out how to best implement

**Comment by targos** [comment]
@MylesBorins would you still like to pursue this?

**Comment by MylesBorins** [comment]
Not at this time
