### ISSUE TITLE
create a script that generate a full ssh config

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#241]
it'd be great to get a full list of all hosts related to build by traversing all build scripts. lets script this.

**Comment by rvagg** [comment]
What we need is a consistent way of recording host information, at the moment it's a little bit scattered, most of it is in README.md files in the various ansible directories but I'm not sure that's optimal either. Perhaps we need to focus on beefing up the Ansible Inventory as the single-point-of-truth?

**Comment by gibfahn** [comment]
This is done, script is [write-ssh-config.yml](https://github.com/nodejs/build/blob/master/ansible/playbooks/write-ssh-config.yml), and inventory is [inventory.yml](https://github.com/nodejs/build/blob/master/ansible/inventory.yml).
