### ISSUE TITLE
Add hidden parameters to node-test-pull-request to help test github-bot/automation

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2411]
Add a new hidden optional parameter to `node-test-pull-request` to set the webhook URL where Jenkins will post build status updated. This will allow devs working on automation to test and debug it properly.

The parameter being optional should help avoid breakage across jobs. The parameter being hidden protects users from accidentally filling it, and developers working on automation will trigger CI via API calls (we can add a parameter to `ncu-ci run` to help).

AFAIK we don't send any sensitive data on these posts, which means it should be safe to send to an arbitrary server. If we do send something like an authentication token, we can have two parameters and if the URL is set the user needs to set the token as well.

Adding it to `node-test-pull-request` should be enough at first, but I'm willing to help add this parameter across all jobs (I just don't have the required permissions to do so).

Any objections?

**Comment by mhdawson** [comment]
No objections from me.
