### ISSUE TITLE
Options for enabling `NODE_DEBUG` and `NODE_DEBUG_NATIVE` env vars in CI jobs

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#2414]
In a position again where I'm seeing failures only in CI on various environments. It is very difficult to track down the specific issue given the lack of debug output. The code is instrumented to output debug information when the `NODE_DEBUG_NATIVE` environment variable is used but there's currently no way to set that on a CI job.

**Comment by richardlau** [comment]
@jasnell I've added two new `NODE_DEBUG` and `NODE_DEBUG_NATIVE` string parameters to 
- https://ci.nodejs.org/job/node-test-pull-request/
- https://ci.nodejs.org/job/node-test-commit/

These should get set as environment variables.

**Comment by jasnell** [comment]
Thank you!

**Comment by richardlau** [comment]
I think this is done, but feel free to reopen if not.
