### ISSUE TITLE
Truncated logs, non-working "Resume Build", and absence of a message posted to the PR with a link to the job

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#2416]
Seen with https://ci.nodejs.org/job/node-test-pull-request/32854/:

- logs are truncated, so I cannot see what caused the build to fail
- Resume Build doesn't seem to be doing anything
- The CI does not comment with a link to the job on the PR

**Comment by richardlau** [comment]
>     * The CI does not comment with a link to the job on the PR

This one is https://github.com/nodejs/build/issues/2413.

**Comment by richardlau** [comment]
@nodejs/build-infra According to https://ci.nodejs.org/log/all it looks like we're out of disk space again.
e.g.
```
Aug 19, 2020 2:33:53 PM WARNING jenkins.model.PeepholePermalink updateCache

failed to update /var/lib/jenkins/jobs/node-test-pull-request/builds/permalinks
java.io.IOException: No space left on device
...
Aug 19, 2020 2:33:53 PM SEVERE hudson.model.Run execute

Failed to save build record
java.io.IOException: No space left on device
```

**Comment by joaocgreis** [comment]
This should be fixed now. The https://ci.nodejs.org/view/All/job/node-compile-windows/ saves very large artifacts, so the default rotation period of 21 days enforced by the backup server is too large for it. I've changed the job settings in Jenkins to only 10 days, specifically for this job. After running one job the free space in the CI server has gone up to 37%.

![image](https://user-images.githubusercontent.com/134460/90696005-70cfbb80-e273-11ea-8743-53451f84d3cf.png)
