### ISSUE TITLE
Add DMARC TXT records for node.js and io.js domains

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2419]
Discussed with @rvagg and @jbergstroem we want to start the process of enabling DMARC on our domains manged through cloudflare.

Generated the following TXT records using: https://dmarcguide.globalcyberalliance.org/#

## Nodejs.org

_dmarc.nodejs.org. IN TXT "v=DMARC1; p=none; rua=mailto:build@iojs.org; ruf=mailto:build@iojs.org; sp=none; ri=86400"

## iojs.org

_dmarc.iojs.org. IN TXT "v=DMARC1; p=none; rua=mailto:build@iojs.org; ruf=mailto:build@iojs.org; sp=none; ri=86400"

This enables in "test" mode where it should not break anything but will send reports that will let us tell if things will break. Once we confirm it won't break things we'll enable at the next level.

Added through cloudflare UI as text records for each domain.

**Comment by mhdawson** [comment]
Leaving this open as we should update to enable a stricter mode once we are comfortable from the reports that nothing should be broken by a stricter level.

**Comment by mhdawson** [comment]
From the reports over the last few days I don't see any fails for iojs.org and a couple for node.js.  The failures for node.js seem to be for different IPs and I can't correlate them to anything that I'm aware should be ok.

@rvagg, @jbergstroem, @nodejs/build any concerns with updating so that emails that fail DMARC are rejected ?

**Comment by Trott** [comment]
> @rvagg, @jbergstroem, @nodejs/build any concerns with updating so that emails that fail DMARC are rejected ?

Normally, I wouldn't weigh in on this sort of thing (since I wouldn't be the one dealing with the fallout should something go wrong), but since you pinged the build team: I'm 👍 on updating at this time.

**Comment by rvagg** [comment]
I haven't been looking at them so don't have much of an opinion. I have been saving the daily files though if someone from build or TSC or security wants to take a look at what's in them and contribute to the discussion here.

**Comment by jbergstroem** [comment]
> I haven't been looking at them so don't have much of an opinion. I have been saving the daily files though if someone from build or TSC or security wants to take a look at what's in them and contribute to the discussion here.

We could always pass them to another email that stores it on a disk someplace for later processing?

**Comment by mhdawson** [comment]
@jbergstroem what kind of processing do you have in mind. If we have things set up correctly (SPF) it should not affect the flow of legitimate email. I don't think we want to wait to long before switching on reject.

**Comment by mhdawson** [comment]
I'd like to turn this on at this point.  There seems to be an uptick in what look like random IPs being reported possibly due to the article in the register as well as additional people creating hacker one reports about spoofing.  

@jbergstroem @rvagg any objections. If I don't hear any I'll plan to enable early next week. If you both confirm you don't have concerns I'll possibly do it earlier.

**Comment by mhdawson** [comment]
Reviewing more of the files, one entry that we might need a fix for:

-<record>


-<row>

<source_ip>209.85.220.69</source_ip>

<count>4</count>


-<policy_evaluated>

<disposition>none</disposition>

<dkim>fail</dkim>

<spf>fail</spf>


-<reason>

<type>local_policy</type>

<comment>arc=pass</comment>

</reason>

</policy_evaluated>

</row>


-<identifiers>

<header_from>nodejs.org</header_from>

</identifiers>


-<auth_results>


-<dkim>

<domain>linuxfoundation.org</domain>

<result>pass</result>

<selector>google</selector>

</dkim>


-<spf>

<domain>linuxfoundation.org</domain>

<result>pass</result>

</spf>

</auth_results>

</record>

@rvagg do you know if there is some forwarding from the linuxfoundation.org that might need some extra setup?

**Comment by jbergstroem** [comment]
> @jbergstroem what kind of processing do you have in mind. If we have things set up correctly (SPF) it should not affect the flow of legitimate email. I don't think we want to wait to long before switching on reject.

Statistics, visibility. I say go ahead with reject regardless.

**Comment by rvagg** [comment]
@mhdawson I don't know, perhaps we throw it over the wall to them and get helpdesk@ to deal with it. Our SFP is the following:

```
v=spf1 include:aspmx.googlemail.com -all
```

Maybe tell them if they need something additional to work for mail they send as `@nodejs.org` then let us know, otherwise it's going to be locked in and they may get rejections. What might they be sending out as `@nodejs.org` that we need to account for? Marketing spam, surveys, ... ?

**Comment by mhdawson** [comment]
Talked to Brian and it might be related to some gsuite accounts that were created at one point but we don't think they are being actively used and many of the people they were created for are not active in the project anymore. 

I'll plan to enable and if we need to add records due to rejections we can look at that when/if people report issues.

**Comment by mhdawson** [comment]
Updated DMARC to reject those that fail now.

## Nodejs.org

_dmarc.nodejs.org. IN TXT "v=DMARC1; p=reject; rua=mailto:build@iojs.org; ruf=mailto:build@iojs.org; sp=reject; ri=86400"

## iojs.org

_dmarc.iojs.org. IN TXT "v=DMARC1; p=reject; rua=mailto:build@iojs.org; ruf=mailto:build@iojs.org; sp=reject; ri=86400"

**Comment by mhdawson** [comment]
Will leave this open for a week or so in case we have problems reported.

**Comment by niftylettuce** [comment]
❤️
