### ISSUE TITLE
move configurable parts of freebsd init script to sysconfig

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#242]
lets avoid modifying the init script by moving the configurable parts to its sysconfig counterpart

**Comment by rvagg** [comment]
whatever, I just find it hard to keep track of where "sysconfig" is across the various OS' and distros, /etc/sysconfig, /etc/defaults, /opt/foo/bar/what.

**Comment by jbergstroem** [comment]
Valid point. That's probably something that should live in README.md though

**Comment by jbergstroem** [comment]
Filing this as nitpick since we're not supposed to edit any files anyway.
