### ISSUE TITLE
MacOS binary distribution is slow to start on Catalina (10.15)

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2422]
If you download the tarball of the MacOS binary and attempt to run on Catalina (10.15) there is a multi second delay until it starts. I believe that this is due to the binary not being notarized. We noticed something similar with the jstime binary

https://github.com/jstime/jstime/issues/30

**Comment by mmarchini** [comment]
I thought our packages were notarized already: https://github.com/nodejs/node/pull/31459

**Comment by AshCripps** [comment]
Our binarys are notorized but maybe the latest build failed notorization?

**Comment by mmarchini** [comment]
@MylesBorins can you try with previous releases?

**Comment by richardlau** [comment]
I think we only notarize the pkg distribution and not the tarballs.

**Comment by MylesBorins** [comment]
AFAIK we do only notarize the .pkg. @mmarchini  it is my understanding that all binary releases will now be slow on Catalina due to not being notarized, I just tested with v8.9.4 and replicated the behavior (release is 2+ years old). Although I'm a bit perplexed as to why this doesn't happen with nvm which AFAIK redistributes our binaries.

/cc @ljharb is nvm doing anything special?

**Comment by ljharb** [comment]
All nvm does is download a tarball and extract it; it's possible that using the command line doesn't check the notarization?

**Comment by MylesBorins** [comment]
@ljharb I'm using the command line, so that's what is so strange here... perhaps it is the indirection?

**Comment by MylesBorins** [comment]
OMG, it is literally just not being in the download folder 😂

Testing locally. A binary in the download folder runs super slow, one out of it doesn't WHAT!

**Comment by rvagg** [comment]
All of our binaries are signed, with entitlements baked in, even in the tarball. Notarization is for packages, you can't do it to a tarball (unless something's changed recently). Currently the notarization handling on the client side is through the installer process, when you're doing things like unpacking tarballs, or copying a file onto your computer from elsewhere (rsync, scp, etc.), you're bypassing all of that. I imagine Apple might want to change that over time to push everything through their notarization process but that's going to be tricky for them to pull off without annoying a lot of people and breaking their unix-ish usability.

**Comment by MylesBorins** [comment]
I had found this article about notarizing a golang binary, maybe it will be helpful. With that said it seems like the binaries are only slow the first time they are run in a directory that isn't `~/Downloads`. Very odd.


https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/

**Comment by rvagg** [comment]
right, but the notarization is stapled to the package, not the binary, when you install that notarization information gets extracted and associated with where the binary is installed, tarballs bypass this, they are signed but the notarization information is not included anywhere

**Comment by MylesBorins** [comment]
@rvagg thanks for clarifying. FWIW it does not seem like the signature plays a role in subsequent runs of the binary

**Comment by ljharb** [comment]
@MylesBorins it's also possible that files downloaded by browsers are marked with an extended attribute, and that's what makes them slow? It might be worth seeing if the presence of `com.apply.quarantine` is the cause: https://www.jamf.com/jamf-nation/articles/59/managing-file-quarantine-attributes

**Comment by MylesBorins** [comment]
@ljharb I just downloaded via wget instead of browser, same behavior

* slow as heck start up on every load
* move the file to another directory, run it twice, not longer slow
* move it back to ~/Download and it isn't slow
