### ISSUE TITLE
Add new AIX7.2 machines

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2424]
This machine is running an old TL level which is due to go EOL next month and as part of adding new AIX72 machines we are updating it to a more recent TL and doing some other general maintanence.

@aixtools can you comment here with your rough timeline of the outage so I can open an issue in libuv to notify them of the outage.

**Comment by aixtools** [comment]
Once I know the level desired I can give a better estimate - two to four
hours once I get started is expected, 8 hours if things go horribly wrong.

And, I'll work in a way I can go back to the old if something completely
unexpected occurs.

Also, I recommend saving anything you want saved - before I start.

Michael

**Comment by aixtools** [comment]
OK. As part of redoing the nodejs AIX infrastructure at OSU - I will 'offline' the current image. While it will not be simple (for me), should it turn out that there are certain files that are missed - I'll be able to recover them from the backup for you.

Unless someone objects - this image will go offline either Friday or Monday (9 October or 12 October).

**Comment by aixtools** [comment]
OK - so what this has become: Add for AIX 7.2 systems. 

The system with the NodeJS label test-osuosl-aix72-ppc64_be-2 will be reinstalled. The existing image will go offline on Monday 12 October sometime after 0600 CUT.

When it comes up, it will have a base AIX install image - no ansible configs will be run against it by myself.

There will be three other servers installed - identical except for hostname.

The names will be p8-aix2-nodejsXX.osuosl.org (where XX == {01, 02, 03, 04}, respectively.

**Comment by aixtools** [comment]
FYI: The remaining 3 systems are ready for further configuration.

**Comment by aixtools** [comment]
```
root@nim.bak:[/home/root]hosts-osu.ksh | grep nodejs
# osu_hostname: p8-aix2-nodejs01.osuosl.org osu_netaddr: 140.211.9.30
140.211.9.30  p8-aix2-nodejs01 p8-aix2-nodejs01.osuosl.org
# osu_hostname: p8-aix2-nodejs02.osuosl.org osu_netaddr: 140.211.9.131
140.211.9.131  p8-aix2-nodejs02 p8-aix2-nodejs02.osuosl.org
# osu_hostname: p8-aix2-nodejs03.osuosl.org osu_netaddr: 140.211.9.101
140.211.9.101  p8-aix2-nodejs03 p8-aix2-nodejs03.osuosl.org
# osu_hostname: p8-aix2-nodejs04.osuosl.org osu_netaddr: 140.211.9.77
140.211.9.77  p8-aix2-nodejs04 p8-aix2-nodejs04.osuosl.org
```
