### ISSUE TITLE
Need temporary access to MacOS 10.14 and 10.15 machines to test npm regression

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2434]
Hey All,

I'd like to get both myself and @ruyadorno access to the MacOS testing infrastructure so we can help identify a regression in npm 7 that is only manifesting in CITGM on OSX.

Aware that we need to wait until the current security release it out the door.

Would someone be able to help us navigate this? I feel like i may already have all the necessary access as part of the build team, but honestly don't remember exactly how to connect. We would need to do something to get Ruy access

**Comment by AshCripps** [comment]
@MylesBorins you are in the build team and I can see your key in the test folder of secrets so you should be able to decrypt the SSH key. [here](https://github.com/nodejs/build/blob/master/doc/ssh.md) are some instructions on logging in to the machines (basically an ansible playbook to fill out your ssh config then you should be able to just `shh test-*host*`). If the instructions arent that clear (its been a while since I ran through them) just give a shout and we should able to help

**Comment by MylesBorins** [comment]
@AshCripps it does not appear my key is included in the https://github.com/nodejs-private/secrets/tree/master/build/infra-mac directory so I can't get the details for the macs

I tried https://github.com/nodejs-private/secrets/blob/master/build/test/nodejs_build_test as the key for https://github.com/nodejs/build/blob/master/ansible/inventory.yml#L64 but it didn't work

**Comment by rvagg** [comment]
^ this is why running the `write-ssh-config.yml` ansible job is handy @MylesBorins. The one you've linked to is a `release-*` machine so you shouldn't be able to access it. Scroll down to the `test-*` machines and you'll see a batch of them: https://github.com/nodejs/build/blob/master/ansible/inventory.yml#L193-L197

Take note of the port number though if doing this manually (something `write-ssh-config.yml` will take care of for you). You should be able to do this kind of thing:

```
ssh administrator@199.7.167.100 -p 8824 -i ~/.ssh/nodejs_build_test
```

Probably best to `sudo su iojs` to perform testing tasks. And if you're going to be doing heavy work we might be best to take the machine you're on out of CI so it's not disruptive and you get it to yourself. Let us know if you need that.

**Comment by MylesBorins** [comment]
@rvagg thanks for the insight. Unfortunately both dotpgp and the instructions for getting ansible setup are broken on 10.15, at least following the instructions as written. I ended up just manually going through things since it was faster than figuring out how to get the tools working.

If I find some spare time I'll go through the steps again and try and update the docs

**Comment by AshCripps** [comment]
@MylesBorins does that mean you have access now? does Ruy need access as well or is it fine with just you?

Also can you give a heads up of which machines you are using? im looking into some issues with the macs and dont want to trip over you if I have to clear some space.

**Comment by MylesBorins** [comment]
I'm in the gibson :hacker-man:

https://ci.nodejs.org/computer/test-orka-macos10.15-x64-1/ is the specific node, I've taken it temporarily offline so other work wouldn't trample. Will put it back online when I'm not working on it

**Comment by MylesBorins** [comment]
FTR I've gotten off https://ci.nodejs.org/computer/test-orka-macos10.15-x64-1/ and on to https://ci.nodejs.org/computer/test-orka-macos10.14-x64-3/

Will clean up and bring it back online when I'm done for the day, but may need to do more work on it throughout the week

**Comment by MylesBorins** [comment]
Taking https://ci.nodejs.org/computer/test-orka-macos10.14-x64-3/  offline again. will update when online

**Comment by MylesBorins** [comment]
Cleanup up machine and put it back online a bit ago, sorry for not updating.

We found the bug!!!! Closing
