### ISSUE TITLE
FYI: rejected request to add Slack integration to this repo

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2440]
Just FYI, we received a direct request to add a Slack integration to this repository. I rejected it as it didn't follow our GitHub App request policy. If it was someone from this repo please let me know.

**Comment by mmarchini** [comment]
ok just confirmed the user is active here

@aixtools we received your request to add the Slack integration to this repository, but we can't move forward unless the request follows our [GitHub App policy](https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANAGEMENT_POLICY.md). You'll need to open an issue on [nodejs/admin](https://github.com/nodejs/admin) requesting us to add the app with the following information:

- the application to be installed, token to be created or secret to be added
  - in the case of secrets, don't share the value on the issue, share just details on how it will be used
- for apps and personal tokens, the permissions that it requires
- the repositories for which the app will be installed or the secrets will be added

**Comment by AshCripps** [comment]
Closing. I spoke to Michael and it was unintentional click of a button, sorry!
