### ISSUE TITLE
PSA testing new AIX7.1 machines

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2441]
im looking into replacing our (Non OSUOSL) AIX machines with AIX7.1 machines from a differenet source. As part of this work Im going to hook up a machine or 2 to the CI for testing build times to ensure we dont add a bottleneck.

**Comment by richardlau** [comment]
Have added an entry for `test-ibm-aix71-ppc64_be-3` to the CI firewall.

**Comment by AshCripps** [comment]
machines are added and will be switched over some time this week
