### ISSUE TITLE
can we give up  very old version toolchain? 

### ISSUE THREAD

**Issue by anlexN** [nodejs/build#2446]
gcc/g++ should be > 9, remove python 2 and something like this.

if so, i think nodejs can be lighter and better

**Comment by AshCripps** [comment]
see - #2445 we plan to move to GCC8 for 16.x and as far as im aware node is python3 compatable at this point

**Comment by rvagg** [comment]
@anlexN we're dealing with a very diverse and complex ecosystem here, making big jumps is just impossible. Particularly with newer GCC, we wipe out entire classes of operating systems that we can support. We also have hardware that we support that don't have newer toolchains. So we have to move fairly slowly and balance our need for _newer features_ with _maximal compatibility_. This is quite different to a browser environment where time horizons are much shorter.

Python 3 compatibility should be across the board. If you see any gaps then feel free to fill them. Removing Python 2 support isn't really on our radar, but then again we also don't have many people investing in our Python toolchain pieces so if that's a passion of yours then I invite you to get involved and improve the situation. If you have concrete plans then feel free to propose them, you might be able to generate interesting discussion. Just keep in mind that we're dealing with a very complex and broad beast with many conflicting requirements and we're trying to find a good place in the middle that works for all, all while balancing the meagre people time that is available to perform any changes.

**Comment by anlexN** [comment]
can you tell me what very complex and broad beast with many conflicting requirements?

**Comment by AshCripps** [comment]
We support over 6 different architectures, some of which are very _unique_ in terms of what toolchains they support so its never easy to just make a jump across the board. We also support our LTS versions for ~3 years and we keep them as stable as possible thereforce we cant drop/change the toolchain without a extreme reason and it will be a breaking change.

**Comment by anlexN** [comment]
whether have variant nodejs that satisfy my requirement?
