### ISSUE TITLE
Why do we set hostnames in ansible scripts?

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2447]
title. Setting up some AIX machines and im getting test failures on all socket tests - see https://ci.nodejs.org/job/node-test-commit-aix-ashcripps/nodes=test-ibm-aix71-ppc64_be-3/5/console. The IP the machine is trying to connect to `138.197.224.240` resolves to `dist-libuv.org` which seems really odd to me.

so I just wanted to know is there a reason we set the hostname? im hoping to just blow that away and set it to something more correct but wanted to check if I did that would it stop the machine working in the ci? Also if anyone can shed a light on why its picked the libuv address that would be interesting to know too. 

cc @rvagg @jbergstroem

**Comment by richardlau** [comment]
I don't know the reason. We are explicitly setting the hostname on AIX for something under `*.nodejs.org` and that's probably why the name resolves to that IP address.

https://github.com/nodejs/build/blob/06c83e72a359ff8b24e5b04bf071656f6325c2e3/ansible/roles/baselayout/tasks/main.yml#L31-L33

**Comment by jbergstroem** [comment]
When initially creating this, the hostname was an identifier of the machine, where it was hosted and what it did. We then had an ansible script that wrote configuration to your `.ssh/config` so you could quickly ssh into boxes by using their hostnames. I'm sure the script is around but I haven't tested it in.. long.

**Comment by jbergstroem** [comment]
When initially creating this, the hostname was an identifier of the machine, where it was hosted and what it did. We then had an ansible script that wrote configuration to your `.ssh/config` so you could quickly ssh into boxes by using their hostnames. I'm sure the script is around but I haven't tested it in.. long.

- inventory parser/generator (hostname definition): https://github.com/nodejs/build/blob/master/ansible/plugins/inventory/nodejs_yaml.py
- ssh config generator: https://github.com/nodejs/build/blob/master/ansible/plugins/library/ssh_config.py

**Comment by AshCripps** [comment]
if its thats for the SSH config and stuff (Which I agree is very useful I use that all the time) is it possible to drop the `.nodejs.org` off the end of the scripts? I think thats the part thats breaking this tests as it resolves to an actual domain then and I think that suffix is only added to AIX and macos currently.

**Comment by AshCripps** [comment]
I can confirm removing the `.nodejs.org` from the hostname got me a passing test suite - Ill open a PR tomorrow to remove it from ansible as I dont think its needed and is now causing breakages

**Comment by rvagg** [comment]
Change hostname on the machine to whatever you like, it shouldn't impact anything on our end. It's mainly in there for the convenience when having to deal with a lot of machines, often with random, or bad names coming our of our various infra providers. This all dates back to a time when we didn't have a good method for consistently naming things. @jbergstroem came up with a good scheme and we've stuck with it. It's usually helpful to set up machines properly (and nice that `hostname` tells us the correct thing), but mostly useful on _our_ end, not the machine's end.

This is one Chesterton's fence that can be tinkered with, thanks for checking!

**Comment by rvagg** [comment]
Re 138.197.224.240 -> dist.libuv.org, because it's our web server and it hosts a bunch of names, that one included. I don't know who's indexing IP->name mappings that might give you that one first, it could be one of a bunch of names. It's correct name according to ansible should be infra-digitalocean-ubuntu1604-x64-1. But that's only useful for internal purposes.

**Comment by AshCripps** [comment]
opened a PR to remove the problematic part - https://github.com/nodejs/build/pull/2448 its weird it only causes failures on AIX but ill put that down to AIX being weird more than anything else.
