### ISSUE TITLE
All machines at nearform are offline

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2451]
Looks like all the machines hosted by nearform are offline in jenkins.  I could still ssh into test-nearform_intel-ubuntu1604-x64-1 eariler

I'd tried restarting the agent earlier when I thought it was just one, and the failure was that it could not connect to the CI. 

I checked that the IP was in the firewall so thinking its a problem on the nearform network side.

@jasnell can you check if there is something going on?

**Comment by mhdawson** [comment]
@jasnell, @mcollina can you see if there is any known issue on the Nearform side

**Comment by jasnell** [comment]
Checking... Will get back once I hear from our sysadmin

**Comment by mcollina** [comment]
We are undergoing some maintenance on our own network.

**Comment by jasnell** [comment]
Ok, so... it is sounding like the fans on the intel benchmarking machine may be going out. The machine was shutdown, possibly due to overheating. We're going to continue to monitor it but it should be up now if you can give it a try.

The mac minis appear to be running fine. Please let me know if you're having issues with those.

**Comment by jasnell** [comment]
Can someone confirm if they are able to access the servers now

**Comment by AshCripps** [comment]
@jasnell I can log in to the systems however none of them can connect to our jenkins server - they are in the firewall so they should connect just fine.

**Comment by jasnell** [comment]
hmmm... ok... let me connect you directly with our sysops.... expect an email soon

**Comment by mhdawson** [comment]
@AshCripps thanks for following up. What you reported was the same as I saw.  We could ssh in, but they could not connect to the CI despite being in the firewall config.

**Comment by AshCripps** [comment]
Eamonn restarted the firewall at nearform's end and the machines are back up and now connecting to the CI 🎉 I also checked and brought the release mac back online. Closing.
