### ISSUE TITLE
CI not starting any jobs - out of space

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2453]
trying to start https://ci.nodejs.org/job/node-test-commit-aix-ashcripps/ and I just get page refreshes and according to [grafana](https://grafana.nodejs.org/d/000000127/system-health?orgId=1&refresh=1m) looks like the CI system is out of space 
<img width="133" alt="image" src="https://user-images.githubusercontent.com/26796102/94918187-f74dfe80-04a9-11eb-863e-0ec885925778.png">

@nodejs/build-infra

**Comment by rvagg** [comment]
I think the backup server has filled up which has stopped the automatic cleanup:

```
zones/6dbfb615-b1ac-4f9a-8006-2cb45b87e4cb  3.0T  3.0T     0 100% /
```

@jbergstroem halp!

I'm running the cleanup scripts manually and will restart ci afterward.

FYI on the backup server, the cleanup script is called from /var/spool/cron/crontabs/root, I'm running:

```sh
/root/backup_scripts/remove_old.sh ci.nodejs.org
/root/backup_scripts/remove_old.sh ci-release.nodejs.org
```

**Comment by rvagg** [comment]
done and restarted, and I've updated Jenkins plugins while I was in there:

WMI Windows Agents
Trilead API
Git client
Git
Pipeline: Nodes and Processes
Bitbucket Branch Source
JUnit
Pipeline: Basic Steps
Groovy
SCM API
Git client
Lockable Resources
Matrix Project
Role-based Authorization Strategy

This will mean a second restart which I'll get sorted out when this current queue is emptied.

**Comment by AshCripps** [comment]
Thanks a lot @rvagg sorry to disturb your evening!
