### ISSUE TITLE
Stalled builds (Can't cancel?)

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#246]
https://ci.nodejs.org/job/node-test-commit/1069/

Looks like the CI is stalling, I don't seem to be able to cancel the tasks either.

cc @nodejs/build

**Comment by joaocgreis** [comment]
That build and the 5 after it (up to including 1074) were waiting for executors that are not yet online. I was able to cancel them without any problem. Might be a problem with permissions, would be good to have a look from someone familiar with it.

**Comment by cjihrig** [comment]
Can someone please post here once PRs are good to be tested through the CI again?

**Comment by Fishrock123** [comment]
@joaocgreis are those still waiting to spin up?

**Comment by jbergstroem** [comment]
@Fishrock123 yeah, they are still to be spun up. We will post an update to https://github.com/nodejs/node/issues/3709 in a few hours.

The reason you can't cancel is because we switched to the github authenticator plugin and an issue with permissions mapping.

**Comment by jbergstroem** [comment]
Fixed; was an issue with the github authentication plugin.
