### ISSUE TITLE
DigiCert replacing intermediate CA certs

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2461]
We were impacted by the first round of this, they've just announced a second. I don't know if we'll be impacted and don't have time to figure it out. We use a wildcard *.nodejs.org (can't recall if we still use a *.iojs.org, maybe that got switched to LetsEncrypt). Here's some bits from the email, if someone else wants to start assessing that'd be great:

---

This email is to inform you on November 2, DigiCert is replacing its second set of intermediate CA certificates (ICAs).

Note: Certificate Authorities (CAs) use intermediate CA certificates (ICAs) to issue certificates such as your SSL/TLS certificates. An ICA certificate links your certificate to the trusted root certificate enabling browsers and other applications to trust it.

For a list of the ICA certificates being replaced on November 2, 2020, see our [DigiCert ICA Update KB article](https://app.updates.digicert.com/e/er?om_ext_cid=dc_email_7010z000000ypURAAY_8204&s=1701211846&lid=6373&elqTrackId=85fe00ea2fb744768a037114df9d41ee&elq=56387806e18949e88248d3ed271d53e4&elqaid=8204&elqat=1).

## How does this affect me?

Rolling out new ICAs does not affect existing certificates. We don't remove an old ICA from certificate stores until all the certificates issued from it have expired. This means active certificates issued from the replaced ICA will continue to be trusted.

However, it will affect those certificates if you reissue them as they will be issued from the new ICA. We advise you to always include the provided ICA with every certificate you install. This has always been the recommended best practice to ensure ICA replacements go unnoticed.

## No action is required unless you do any of the following:

 * Pin the old versions of the intermediate CA certificates
 * Hard code the acceptance of the old versions of the intermediate CA certificates
 * Operate a trust store that includes the old versions of the intermediate CA certificates

If you do any of the above, we recommend updating your environment as soon as possible. [Stop pinning](https://app.updates.digicert.com/e/er?om_ext_cid=dc_email_7010z000000ypURAAY_8204&s=1701211846&lid=6377&elqTrackId=f0e7b290d3094a4e9b02124ab0967c6a&elq=56387806e18949e88248d3ed271d53e4&elqaid=8204&elqat=1) and hard coding ICAs or make the necessary changes to ensure certificates issued from the new ICAs are trusted (in other words, can chain up to their updated ICA and trusted root).

## Intermediate CA certificate replacements

Make sure to monitor the pages listed below. These are active pages and will be updated regularly with ICA certificate replacement information and copies of DigiCert roots and intermediate CA certificates.

 * [DigiCert ICA Update](https://app.updates.digicert.com/e/er?om_ext_cid=dc_email_7010z000000ypURAAY_8204&s=1701211846&lid=6373&elqTrackId=edda7f34c73444c3adafa791b83b2b2d&elq=56387806e18949e88248d3ed271d53e4&elqaid=8204&elqat=1)
 * [DigiCert Trusted Root Authority Certificates](https://app.updates.digicert.com/e/er?om_ext_cid=dc_email_7010z000000ypURAAY_8204&s=1701211846&lid=4887&elqTrackId=b990870f66a040feb84b01e251e32d62&elq=56387806e18949e88248d3ed271d53e4&elqaid=8204&elqat=1)

## Why is DigiCert replacing intermediate CA certificates?

We are replacing ICAs to:

 * Promote customer agility with ICA replacement
 * Reduce the scope of certificate issuance from any given ICA to mitigate the impact of changes in industry standards and CA/Browser Forum guidelines to intermediate and end-entity certificates
 * Improve the security of the Internet by ensuring all ICAs operate using the latest improvements

If you have additional questions, please contact your account manager or our support team.

Best regards,
DigiCert Product Team

**Comment by AshCripps** [comment]
@rvagg can you elaborate on the first round? I do seem to remember some cert issues but cant find anything on the issue tracker except for some java certs that changed when we did a jenkins update - https://github.com/nodejs/build/issues/2384

**Comment by rvagg** [comment]
I can't remember, sorry, I have fog-brain about this but I seem to remember something coming in via nodejs.org with people reporting https rejection errors which resulted in intermediate cert change. https://github.com/nodejs-private/secrets/pull/51 is the last PR that seems to have made a material change to our secrets, but that's making me wonder whether we're out of sync on the server and secrets. I suppose somebody (me) should check that.

**Comment by mhdawson** [comment]
I think we would know by know if this had affected us as the change was to take place Nov 2020 which is 10 months ago. Closing
