### ISSUE TITLE
Extra slashes in links in the console output

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/build#2465]
I was glancing through the logs [here](https://ci.nodejs.org/job/node-test-commit/41591/console) and noticed that the links of the build numbers and the statuses have an extra slash.
The build number link should be changed to this:
```diff
- https://ci.nodejs.org/job/node-test-linter/37369//
+ https://ci.nodejs.org/job/node-test-linter/37369/
```
and the status link should be changed to this:
```diff
- https://ci.nodejs.org/job/node-test-linter/37369//console
+ https://ci.nodejs.org/job/node-test-linter/37369/console
```
Is this the correct repo where I can fix this? If not, can someone please help me find out where I can fix this? Thanks. :slightly_smiling_face:

**Comment by rvagg** [comment]
These are all generated by Jenkins, unless you want to go chasing up the relevant Jenkins plugin that's creating those links I don't think there's a whole lot we can do.
