### ISSUE TITLE
Planned downtime for OSUOSL hosted AIX systems: 09 November 2020

### ISSUE THREAD

**Issue by aixtools** [nodejs/build#2466]
POWER System maintenance - to occur on 9 November 2020, starting at approximately 07.00 GMT.

Please advise if there are any show-stoppers.

**Comment by aixtools** [comment]
I had the systems down - but they are up again. An unexpected blocker prevents me from doing the planned maintenance.

I'll reschedule. To accomplish the planned update I have to move all the partitions to a different server. Need to plan those moves first.

**Comment by mhdawson** [comment]
This is long past the date mentioned, closing.
