### ISSUE TITLE
PSA: removing an errant file from staging on the www server

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2467]
@nodejs/build-infra @nodejs/releasers TL;DR This issue is recording (for traceability) that there's an errant file in staging on the www server, an explanation on how it got there and that I'm removing it. 

During the promotion of Node.js 10.23.0 and 14.15.0 today we noticed (I did this live during today's Release mentoring call) that there is a staged `osx-x64-pkg` asset in v14.13.1:
```
# Checking for releases ...
Found the following releases / builds ready to promote:
 * v10.23.0: aix-ppc64 headers linux-arm64 linux-armv6l linux-armv7l linux-ppc64le linux-s390x linux-x64 osx-x64-pkg osx-x64-tar src sunos-x64 win-x64-7z win-x64-msi win-x64-zip win-x86-7z win-x86-msi win-x86-zip
 * v14.13.1: osx-x64-pkg
 * v14.15.0: aix-ppc64 headers linux-arm64 linux-armv7l linux-ppc64le linux-s390x linux-x64 osx-x64-pkg osx-x64-tar src win-x64-7z win-x64-msi win-x64-zip win-x86-7z win-x86-msi win-x86-zip
```
(@BethGriggs mentioned that she also noticed it when releasing Node.js 15.)

https://nodejs.org/dist/v14.13.1/node-v14.13.1.pkg exists, but so does:
```
root@infra-digitalocean-ubuntu1604-x64-1:~# ls -al /home/staging/nodejs/release/v14.13.1/
total 31384
drwxrwxr-x  2 staging staging     4096 Oct 14 17:48 .
drwxrwxr-x 45 staging staging     4096 Oct 27 10:39 ..
-rw-rw-r--  1 staging staging 32125100 Oct 14 17:48 node-v14.13.1.pkg
-rw-rw-r--  1 staging staging        0 Oct 14 17:48 node-v14.13.1.pkg.done
root@infra-digitalocean-ubuntu1604-x64-1:~#
```
which has a different shasum from the one in https://nodejs.org/dist/v14.13.1/SHASUMS256.txt:
```
root@infra-digitalocean-ubuntu1604-x64-1:~# sha256sum /home/staging/nodejs/release/v14.13.1/node-v14.13.1.pkg
ee14a1874e54d165bb58c23395d9f09b79da420d45d1d17ae49723b029c1a297  /home/staging/nodejs/release/v14.13.1/node-v14.13.1.pkg
root@infra-digitalocean-ubuntu1604-x64-1:~#
```

After some detective work I was able to track down the `iojs+release` job that created it: https://ci-release.nodejs.org/job/iojs+release/6388/nodes=osx1015-release-pkg/
Curiously that job was requested with [`disttype` `test`](https://ci-release.nodejs.org/job/iojs+release/6388/nodes=osx1015-release-pkg/parameters/) but ended up being uploaded to `release`(!):
```
Notarization complete! Notarized files:
  - node-v14.13.1.pkg (notarized and stapled)
ssh node-www "mkdir -p nodejs/release/v14.13.1"
chmod 664 node-v14.13.1.pkg
scp -p node-v14.13.1.pkg node-www:nodejs/release/v14.13.1/node-v14.13.1.pkg
ssh node-www "touch nodejs/release/v14.13.1/node-v14.13.1.pkg.done"
+ DESTCPU=x64
```
This was because of the same reason as https://github.com/nodejs/node-v8/issues/179#issuecomment-710966884 where https://ci-release.nodejs.org/job/iojs+release/jobConfigHistory/showDiffFiles?timestamp1=2020-06-16_04-30-06&timestamp2=2020-10-14_10-09-35 inadvertently broke the line continuation in the job config so the `DISTTYPE` wasn't being set. I've already fixed it in https://ci-release.nodejs.org/job/iojs+release/jobConfigHistory/showDiffFiles?timestamp1=2020-10-14_10-09-35&timestamp2=2020-10-17_08-28-59 ten days ago so it shouldn't happen again.

**Comment by richardlau** [comment]
I've removed the file:
```
root@infra-digitalocean-ubuntu1604-x64-1:~# cd /home/staging/nodejs/release/v14.13.1/
root@infra-digitalocean-ubuntu1604-x64-1:/home/staging/nodejs/release/v14.13.1# ls -al
total 31384
drwxrwxr-x  2 staging staging     4096 Oct 14 17:48 .
drwxrwxr-x 45 staging staging     4096 Oct 27 10:39 ..
-rw-rw-r--  1 staging staging 32125100 Oct 14 17:48 node-v14.13.1.pkg
-rw-rw-r--  1 staging staging        0 Oct 14 17:48 node-v14.13.1.pkg.done
root@infra-digitalocean-ubuntu1604-x64-1:/home/staging/nodejs/release/v14.13.1# rm node-v14.13.1.pkg*
root@infra-digitalocean-ubuntu1604-x64-1:/home/staging/nodejs/release/v14.13.1# ls -al
total 8
drwxrwxr-x  2 staging staging 4096 Oct 27 21:01 .
drwxrwxr-x 45 staging staging 4096 Oct 27 10:39 ..
root@infra-digitalocean-ubuntu1604-x64-1:/home/staging/nodejs/release/v14.13.1#
```

and it no longer shows when running the release script:
```
bash-4.2$ tools/release.sh 
# Selecting GPG key ...
You have multiple GPG keys:
...

# Checking for releases ...
No releases to promote!
bash-4.2$
```

**Comment by rvagg** [comment]
Very impressive detective work here @richardlau! Makes me **very** happy to see someone else understanding enough of the pieces of this puzzle and having the access to fix it.
