### ISSUE TITLE
too many threads on libuv-test-aix-cmake

### ISSUE THREAD

**Issue by vtjnash** [nodejs/build#2476]
I'm seeing the identical problem as https://github.com/nodejs/build/issues/2402 (@rvagg), but on the https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/250/ worker with the missing JOBS variable. Thanks!

**Comment by mhdawson** [comment]
@AshCripps can you take  a look at this one ?

**Comment by AshCripps** [comment]
Added the variable https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/253/ passed

**Comment by richardlau** [comment]
@AshCripps We'll need to set `JOBS` as well for the AIX nodes in Jenkins. [`ansible/roles/jenkins-worker/templates/aix.rc2.j2`](https://github.com/nodejs/build/blob/master/ansible/roles/jenkins-worker/templates/aix.rc2.j2) is probably the best place to do so based on the Jenkins start scripts for other platforms. 

FWIW it looks like the failing job (https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/250/) was the only one to run on the new AIX image (`test-ibm-aix71-ppc64_be-4`) as Jenkins appears to prefer `test-ibm-aix71-ppc64_be-2`/`test-ibm-aix71-ppc64_be-1`: https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/nodes=aix71-ppc64/buildTimeTrend
The new image probably either has more CPU's or [SMT](https://en.wikipedia.org/wiki/Simultaneous_multithreading) per CPU pushing the build over the edge with `-j` without a capped number.

**Comment by AshCripps** [comment]
@richardlau the machines have the same amount of CPUs. question is why would we need to set it for these ones and not the older ones?

**Comment by richardlau** [comment]
> @richardlau the machines have the same amount of CPUs. question is why would we need to set it for these ones and not the older ones?

@AshCripps 🤷:
```
$ ssh test-ibm-aix71-ppc64_be-2  'python -c "import multiprocessing; print(multiprocessing.cpu_count())"'
16
$ ssh test-ibm-aix71-ppc64_be-4  'python -c "import multiprocessing; print(multiprocessing.cpu_count())"'
32
$
```
or with `node`:
```
$ ssh test-ibm-aix71-ppc64_be-2 '/home/iojs/build/workspace/node-test-commit-aix/nodes/aix71-ppc64/out/Release/node -p "os.cpus().length"'
16
$ ssh test-ibm-aix71-ppc64_be-4 '/home/iojs/build/workspace/node-test-commit-aix/nodes/aix71-ppc64/out/Release/node -p "os.cpus().length"'
32
$ 
```
if `cmake` is doing something similar for `-j` (with no number) then there's a difference.

**Comment by AshCripps** [comment]
interesting as they should both be 4 cpus so no idea where 16 or 32 comes from. what would even set `JOBS` to? 4? or this 16?

**Comment by richardlau** [comment]
I would go with 4 but we could try 16. I have a vague recollection we've hardcoded some numbers into some of the Jenkins jobs when we should have gone for setting `JOBS` via ansible and that hardcoded number was in single digits (maybe 5 or 2).

**Comment by mhdawson** [comment]
I was thinking that the most likely probable was that we were missing the config in Ansible.  From that I remember we were limiting to 5 in the past but that was for the OSU machines. We should probably use something which is 1 to 1.5 times the number of CPUs.

**Comment by richardlau** [comment]
@mhdawson @AshCripps opened https://github.com/nodejs/build/pull/2477 for ansible changes.

**Comment by AshCripps** [comment]
https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/nodes=aix71-ppc64/265/console The job now picks up the jobs variable on the one machine I set it on and gets further but I dont know if the errors are related or not?

**Comment by vtjnash** [comment]
The error appears to be unrelated, though I don't know why that should fail. It appears it's refusing to switch the tty to raw mode, which isn't a failure I've seen before elsewhere.

**Comment by richardlau** [comment]
> https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/nodes=aix71-ppc64/265/console The job now picks up the jobs variable on the one machine I set it on and gets further but I dont know if the errors are related or not?

@AshCripps Are you still logged into the shell terminal that you restarted the Jenkins agent with? If so then a tty will be found when it's not expected to be.

**Comment by AshCripps** [comment]
.......yes I am

**Comment by AshCripps** [comment]
https://ci.nodejs.org/job/libuv-test-commit-aix-cmake/nodes=aix71-ppc64/269/console looks better 😄
