### ISSUE TITLE
Node.js security releases Nov 16

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2478]
As per Node.js security release process this is the heads up to the @nodejs/build working group that there will be a security release Nov 16.  

@richardlau can you help with the CI lock/unlock ?

**Comment by richardlau** [comment]
@mhdawson Yes, I'll coordinate with the releasers.

**Comment by richardlau** [comment]
CI is now locked.

**Comment by richardlau** [comment]
CI is now unlocked.
