### ISSUE TITLE
Softlayer datacenter closures

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2480]
Got an email from IBM cloud stating the following:

```
As part of this modernization strategy, we have determined it is necessary to close select datacenters unsuitable for upgrading, including the decision to close the following facilities on September 3, 2021.
* HOU02
* DAL05 – POD2 (other PODs in DAL05 are not impacted)
* WDC01 – POD3 and POD4 (other PODs in WDC01 are not impacted)
```

From a very brief glance we have only one machine possibly affected but its a machine I can't find in the inventory:

![image](https://user-images.githubusercontent.com/26796102/99412351-87c29000-28ec-11eb-873c-e64f5a3dbee0.png)

As you can see in the image it seems with have two machines with the same name and the one in our inventory is the first one at the Washington datacenter. Anyone have idea why we have these duplicate machine and if they can be safely removed?

**Comment by rvagg** [comment]
Check the IP addresses against inventory.yml to see what's in use and what isn't. It might have been a replacement server but the old one wasn't deleted.

if I'm reading VersionSelectorScript right, centos6 won't be needed after Node 10 is retired in April, and they're announcing this change for September. So we _could_ just sweep this all under the rug until then and do a complete removal of cento6 in May and be done with it.

**Comment by AshCripps** [comment]
Richard pointed me to https://github.com/nodejs/build/issues/1074#issuecomment-365724152 which points to it being a replacement server.

**Comment by AshCripps** [comment]
Closing, deadline passed and machine is already gone/replaced I believe.
