### ISSUE TITLE
PSA: ORKA Maintanence Window

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2482]
@nodejs/build @nodejs/releasers Our ORKA environment will be going under maintenance to transfer our existing environment to an new updated cluster - this is disruptive and will require a 24hr downtime to complete. This means we will be without 10.14 macs and most of our 10.15 macs but will still have the nearform machines for releases if needed. The machines will need to be recreated after but should have the same networking as before and our custom images saved in storage.

They are targeting the week of December 7th - 11th.

Does anyone have any concerns with this window or preferred days?

**Comment by richardlau** [comment]
In terms of preferred days we usually aim for releases on Tuesdays so it might be an idea to aim for the latter part of the week if possible.

**Comment by AshCripps** [comment]
ok so if I go back and say "pick a date between the 9th and 11th" that should be ok for everyone?

**Comment by richardlau** [comment]
> ok so if I go back and say "pick a date between the 9th and 11th" that should be ok for everyone?

:+1: from me.

**Comment by mhdawson** [comment]
Lets say 10-11th just to give some breathing room after Tuesday.

**Comment by AshCripps** [comment]
Ive updated the ticket and said 10-11th will update with the exact timeframe they come back with

**Comment by Trott** [comment]
I guess this can be closed now?
