### ISSUE TITLE
No space left on ARM CI

### ISSUE THREAD

**Issue by aduh95** [nodejs/build#2486]
I've noticed all CI on node repo are failing recently with this log trace for `node-test-binary-arm-12+` test suite:

```
18:13:40 Running as SYSTEM
18:13:40 [EnvInject] - Loading node environment variables.
18:13:40 Building remotely on test-requireio_ceejbot-debian10-armv7l_pi2-1 (arm-Raspbian-10 pi2-docker Raspbian Raspbian-10 arm-Raspbian arm 10) in workspace /home/iojs/build/workspace/node-test-binary-arm
18:13:41 FATAL: /home/iojs/build/workspace/node-test-binary-arm@tmp/secretFiles/171826a4-fade-4ee9-bd80-e9ab3012a174: No space left on device
```

https://ci.nodejs.org/job/node-test-binary-arm-12+/8467/RUN_SUBSET=addons,label=pi2-docker/console

**Comment by richardlau** [comment]
I've deleted a few of the workspaces to free up some space.

**Comment by Trott** [comment]
This seems to be resolved so I'll close it. Obviously, open it if I'm wrong and we want to leave it open until there's some automated something or other to prevent this or whatever.
