### ISSUE TITLE
Heads up of Security releases Jan 4 2021

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2498]
As per security release process this is a heads up that there will be security releases Jan 4 2020 and we'll need people from build to lock/unlock ci and to support and build issues we see.

**Comment by richardlau** [comment]
I've volunteered to handle some of the releases so I'll also handle locking/unlocking the CI 😄.

**Comment by mhdawson** [comment]
@richardlau Thanks!

**Comment by richardlau** [comment]
CI has been unlocked.
