### ISSUE TITLE
Fedora 23 support/vm

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#250]
Fedora23 is out and digital ocean recently added it. Unfortunately, the ansible script [for fedora22] fails for me. I've added it to the cluster with some patching; below is what needs to be updated:
1. python needs to be installed before using ansible (`dnf install -y python`)
2. working with the new package manager – `dnf` – fails
3. `id` in jenkins.service needs to be expanded
4. increasing file descriptor limits fail: `failed: [iojs-build-fedora23-1] => (item=*         hard    nofile      500000) => {"failed": true, "item": "*         hard    nofile      500000"}
   msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!`

**Comment by jbergstroem** [comment]
lets get it done:

1. python: lets use `raw` similar to what I did [here](https://github.com/nodejs/build/pull/228/files#diff-15eb5f14a10ef05c622b8abda9477763R15)
2. upstream ansible issue. we need to call yum
3. (solved)
4. just add libselinux-python to deps

**Comment by jbergstroem** [comment]
FYI - I've pushed this to my ansible 2.0 branch (set to be out early january). It streamlines package management which makes things much simpler. I have a pre-check that bootstraps python if its missing for hosts that needs it.

**Comment by maclover7** [comment]
Closing this in favor of #962 since it seems like we're at the stage of removing support for this, not adding it 😄
