### ISSUE TITLE
PSA marked the orka release machine offline

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2501]
At the request of @BethGriggs I've marked https://ci-release.nodejs.org/computer/release-orka-macos10.15-x64-1/ offline as it's failing pkg builds, e.g. https://ci-release.nodejs.org/job/iojs+release/nodes=osx1015-release-pkg/6531/console

```
22:06:56 + /Users/iojs/.gon/gon_0.2.2 -log-level=info gon-config.json
22:06:56 ==> 🍎  Notarizing...
22:06:56     Path: node-v14.15.2.pkg
22:06:56     Submitting file for notarization...
22:06:56 2020-12-15T14:06:58.448-0800 [INFO]  notarize: submitting file for notarization: file=node-v14.15.2.pkg command_path=/usr/bin/xcrun command_args=[xcrun, altool, --notarize-app, --primary-bundle-id, org.nodejs.pkg.v14.15.2, -u, build@iojs.org, -p, @env:NOTARIZATION_PASSWORD, -f, node-v14.15.2.pkg, --output-format, xml]
22:06:56 2020-12-15T14:06:58.463-0800 [INFO]  notarize: notarization submission complete: output= err="exit status 72"
22:06:56     Error notarizing
22:06:56 
22:06:56 ❗️ Error notarizing:
22:06:56 
22:06:56 1 error occurred:
22:06:56 	* error submitting for notarization:
22:06:56 
22:06:56 xcrun: error: unable to find utility "altool", not a developer tool or in PATH
22:06:56 
22:06:56 
22:06:56 
22:06:56 make: *** [node-v14.15.2.pkg] Error 1
```

cc @AshCripps

**Comment by rvagg** [comment]
IIRC this is because the full Xcode is required on these machines. I think I had to write up instructions in the docs in this repo about how to get this done, specifically for this.

**Comment by AshCripps** [comment]
This is likely on me (sorry @BethGriggs!) I think what likely to have happened is vms "reset" to the base image which didnt have full xcode on and I didnt notice. Ill look into installing xcode today.

**Comment by AshCripps** [comment]
Xcode installed and https://ci-release.nodejs.org/job/iojs+release/6535/nodes=osx1015-release-pkg/console notorised but the build failed?

**Comment by AshCripps** [comment]
nvm again on me - I have added the node-www ssh setup apparently

**Comment by AshCripps** [comment]
ssh setup added and verified
