### ISSUE TITLE
test-packetnet-centos7-arm64-1 and 2 are offline

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2503]
https://ci.nodejs.org/job/node-test-commit-arm/ hasn't ~~passed~~ run in almost 2 days :(

**Comment by richardlau** [comment]
The release machine is also offline. I can't ssh into any of them (connection time out).

**Comment by mhdawson** [comment]
I can't ping any of them. I logged into the dashboard and it references a console but I can seem to access them from that either.

I've rebooted one of them and it seemed to come back on-line so I'm rebooting the rest.

**Comment by mhdawson** [comment]
They all seem to be back up now, closing.

**Comment by vielmetti** [comment]
Glad to see these are back online. There was an incident with a detailed writeup at https://status.equinixmetal.com/incidents/pfgmgy1fnjcp that may well have been a contributing cause.
