### ISSUE TITLE
Remote call on JNLP4-connect failed

### ISSUE THREAD

**Issue by targos** [nodejs/build#2516]
See https://ci.nodejs.org/job/citgm-smoker-nobuild/1000/nodes=ubuntu1404-64/console

I've seen this error multiple times with citgm-smoker-nobuild, I think always on the same host (test-digitalocean-ubuntu1404-x64-1)

https://ci.nodejs.org/computer/test-digitalocean-ubuntu1404-x64-1/builds

```
17:10:43 FATAL: Remote call on JNLP4-connect connection from 45.55.252.223/45.55.252.223:46127 failed
17:10:43 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 45.55.252.223/45.55.252.223:46127
17:10:43 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
17:10:43 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
17:10:43 		at hudson.remoting.Channel.call(Channel.java:1001)
17:10:43 		at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1147)
17:10:43 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
17:10:43 		at hudson.model.Run.execute(Run.java:1907)
17:10:43 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
17:10:43 		at hudson.model.ResourceController.execute(ResourceController.java:97)
17:10:43 		at hudson.model.Executor.run(Executor.java:429)
```

**Comment by richardlau** [comment]
It looks like another instance of https://github.com/nodejs/build/issues/2510. It was probably missed because the build history suggests the regular CI for daily Node.js 10.x builds are going to the other `ubuntu1404-64` host which isn't exhibiting the issue. I'll restart the Jenkins agent which should fix it.

**Comment by richardlau** [comment]
Restarted the agent.
Test rebuild: https://ci.nodejs.org/job/citgm-smoker-nobuild/1008/nodes=ubuntu1404-64/

**Comment by richardlau** [comment]
Test build passed.

**Comment by targos** [comment]
Thanks!
