### ISSUE TITLE
Problem with pi3-docker cluster

### ISSUE THREAD

**Issue by targos** [nodejs/build#2523]
The workers all seem blocked on `git checkout -f refs/remotes/jenkins_tmp`: https://ci.nodejs.org/job/node-test-binary-arm-12+/RUN_SUBSET=1,label=pi3-docker/9053/console

**Comment by targos** [comment]
@nodejs/build-infra

**Comment by targos** [comment]
Okay, it's not blocked, but takes an extremely long time. In the linked example, the command took 40 minutes to run.

**Comment by rvagg** [comment]
closing as dupe of #2365 (maybe not precisely a dupe, but let's have one issue to talk about this stuff)
