### ISSUE TITLE
Apple Intermediate Certificate Update

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2528]
> Starting January 28, 2021, the digital certificates you use to sign your software for installation on Apple devices, submit apps to the App Store, and connect to certain Apple services will be issued from a new intermediate Apple Worldwide Developer Relations certificate (expiring 2030). This new intermediate certificate will not affect the availability or functionality of apps you’re already distributing on the App Store. And you can continue to use your existing certificates until they expire. 
> 
> If you’re running Xcode 11.4.1 or later, you’ll receive the updated certificate automatically when you sign an app after January 28, 2021. If you’re running an earlier release of Xcode and need to generate new certificates, download and install the new intermediate certificate and utilize the command line to sign your app. You can also archive your build with your existing Xcode version and sign it for distribution with Xcode 11.4.1 or later. 
> 
> The current intermediate certificate (expiring in 2023), will continue to issue certain Apple services certificates, including Apple Push Notification service (APNs) SSL certificates and Apple Wallet pass signing certificates. Keep both versions installed on your development systems and servers until later this year. 

https://developer.apple.com/support/wwdr-intermediate-certificate/

Developer ID Installer and Developer ID Application are not impacted. We don't use the App Store. I'm just not sure how/if this might impact notarization. Perhaps we're not impacted, but if someone else wants to dig deeper into this to figure out whether we're impacted then that would be helpful!

**Comment by mhdawson** [comment]
It been quite some time since Jan 2021 so I think we would know if this had affected us by now. Closing, please let me know if you think was not the right thing to do.
