### ISSUE TITLE
Organising access to machines

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#254]
They way we get access to machines at the moment is a bit of a mess;
1. we have the script that collects keys from github based on provided users
2. we have a shared key for joyent
3. we have a shared key for osuosl/softlayer
4. we have a key for release machines
5. we have modified authorized_hosts on machines where we've temporarily given people access
6. we have a few extra keys as part of the jenkins and release process

I suggest we do the following:
1. create one key we use to access most slaves. this is for the build team only
2. create a key used to access release slaves. again, build team only but a limited subset
3. when providing temporary access, make sure we revoke that once done (just so we have a known state)

**Comment by mhdawson** [comment]
Ideally we could automate the removal of temporary access.  Maybe something that would delete additional users 1-2 weeks after they are created. Alternatively something that would centrally the temporary additions so it would be easy to review/delete those that are no longer required

**Comment by rvagg** [comment]
yep, shared keys are fine by me, the secrets repo seems to be working well for sharing

**Comment by rmg** [comment]
There should be a mechanism for refreshing the keys pulled from github in the event that a user has removed one due to it being compromised. Ideally they would notify everyone, but considering these keys are publicly available it's basically impossible for them to notify everyone we should adopt a good netizen approach ourselves if possible.

**Comment by jbergstroem** [comment]
@rvagg If we're running with shared  we should create different subfolders in the secrets repo to delegate trust, no?

- build-test
- build-release
- build-infra? (current)

Also, I'm guessing an even smaller subset of people have access to infra?

**Comment by rvagg** [comment]
Currently we have secrets/build and secrets/build/release, both are managed with different keys, the subfolders seems to work OK with dotgpg, is there anything here that doesn't fit within those two layers? Non-release stuff just goes in secrets/build and is shared with a wider group.

**Comment by jbergstroem** [comment]
Just wanted to make sure we didn't have issues with recursion. I'm happy with whatever

**Comment by rvagg** [comment]
I'm pretty sure we don't, although it does feel a little awkward whenever I dive in there so I wouldn't be opposed to a reorg. So far we haven't had a use beyond _build_ for the secrets repo so I'm fine with spreading out in there more than we currently are.

**Comment by jbergstroem** [comment]
Should we move the reorganising to the other repo?

I see four set of keys now:
 - release access keys (only accessible by people that handle release-related business)

**Comment by jbergstroem** [comment]
One benefit of having infra access keys is that people in that trust chain can be part of automating setting up new slaves (adding to ci firewall, etc).

**Comment by jbergstroem** [comment]
This is now work in progress. If you're part of the build group you know what repo to access in order to fetch the keys.

@mhdawson brought up that having a benchmark group for handling access to the benchmark machines could be a thing. I'm +1. Anyone else?

**Comment by jbergstroem** [comment]
Will create a benchmark group once we look into redeploying the machines.

**Comment by gdams** [comment]
If you are looking for a nice solution for SSH key management, we are using http://sshkeybox.com/ in AdoptOpenJDK. It works really nicely as we can add all of our hosts, add users keys to machine groups and really easily add/revoke access. If you are interested I'd be happy to demo it to you!

**Comment by maclover7** [comment]
I believe this can be closed since we have https://github.com/nodejs-private/secrets/tree/master/build now. Please reopen if I'm wrong.
