### ISSUE TITLE
nodejs.org's build link error?

### ISSUE THREAD

**Issue by MaledongGit** [nodejs/build#2545]
I notice that there comes a link at nodejs.org:
https://github.com/nodejs/nodejs.org#deployment

It says:
![image](https://user-images.githubusercontent.com/52018749/108360470-38ae3300-722c-11eb-93dc-d24348282eb5.png)

But this link cannot open.... should this be changed to your current route? So what's the new link now? I'm not sure whether it has something to do with the group....

**Comment by richardlau** [comment]
https://github.com/nodejs/build/tree/master/ansible/www-standalone (or https://github.com/nodejs/build/tree/HEAD/ansible/www-standalone) (see https://github.com/nodejs/build/pull/1620 for when it was moved).

**Comment by MaledongGit** [comment]
Thanks @richardlau, I'll fix it and let you see the result ;)
