### ISSUE TITLE
Heads up of Security releases Feb 23 2021

### ISSUE THREAD

**Issue by danbev** [nodejs/build#2546]
As per security release process this is a heads up that there will be security releases Feb 23 2021 and we'll need people from build to lock/unlock ci and to support and build issues we see.

**Comment by richardlau** [comment]
I could possibly lockdown the CI on Monday morning to allow time for CI runs but I won't be available during the day on Monday to keep an eye on the CI or respond to any issues (I will be available on Tuesday).

**Comment by richardlau** [comment]
Pre-announced the CI lockdown: https://github.com/orgs/nodejs/teams/collaborators/discussions/120

**Comment by richardlau** [comment]
CI is now locked down.

**Comment by richardlau** [comment]
CI is now unlocked.
