### ISSUE TITLE
buildbot slaves naming convention

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#255]
Lets start off the day with some classic bikeshedding (I'm yellow), shall we?

We currently have two ways of referencing a slave; for instance:
- iojs-linter-1 (ansible) and  iojs-digitalocean-freebsd-linter-1 (jenkins)
- iojs-build-fedora22 (ansible); iojs-digitalocean-fedora22-1 (jenkins)

Suggesting we first of all reduce to one name, but also use a more consistent naming scheme, all in lowercase.

The main benefit of this is that we can reuse the id throughout ansible; init scripts (hooking up to jenkins), ansible-inventory, .ssh/hosts and so on.

The other benefit is that we can make assumptions based on the name – os version, flavour (release) and so on – to take different routes through a playbook. For instance adding different ssh keys for release bots.

```
$project-$vm_provider-$os$os_version-$architecture-($flavour-)$unique_id
```

- **$project**: nodejs (other alternatives: libuv?)
- **$vm_provider**: where does it live/who sponsors? (digitalocean, joyent, rackspace, softlayer, etc)
- **$os**: os or flavour (freebsd, fedora, debian, ubuntu, smartos, ...)
- **$os_version**: current os version (14.04, 22, etc) -- note: this is slightly problematic since it can go out of date; we've previously done updates to bots such as freebsd 10.1 to 10.2 and similar
- **$architecture**: cpu architecture (x86, x64, ppcle, armv7, etc)
- **($flavour)**: optional argument reserved for specific flavours such as release bots.
- **$unique_id**: an increment that guarantees uniqueness should one hardware provider host multiple of the same type

Open questions:
- possibly make $flavour required and add "test" as default to make it easier to parse?

**Comment by jbergstroem** [comment]
After giving it some thought, lets stick test/release second and make it required, similar to what we have today:
`$project-$flavour-$vm_provider-$os$os_version-$architecture-$unique_id`

**Comment by rvagg** [comment]
Looks good to me, brackets are a problem so I like your last version better, I'm not too fussed as long as those donating the resources get named. We do have one awkward situation of hosting being provided by a different party to the donater—most of the ARM machines are hosted by NodeSource but have been donated by third-parties, I've put names on the end of the string when doing this in jenkins in order to give them full credit.

**Comment by mhdawson** [comment]
Last one looks good to me as well.

**Comment by orangemocha** [comment]
Sounds great. Only knit, as @rvagg pointed out, is about $vm_provider: where does it live/who sponsors are not necessarily the same. I think it's worth keeping both pieces of information.

**Comment by jbergstroem** [comment]
- Do we actually need project?
- I'm a bit undecided regarding architecture -- some providers call 64-bit x64, others x86_64 or amd64. How about we use what's passed to node instead (x86, x64, armv7, etc)? This way we can map that to specific stuff in each ansible script.

**Comment by rvagg** [comment]
> Do we actually need project?

maybe not, it's just more characters eh?

> architecture ... How about we use what's passed to node

+1

**Comment by joaocgreis** [comment]
@jbergstroem +1 for dropping the project. About the architecture, `process.arch` is only `arm` in all the raspberries, so how would we distinguish pi1 from pi2? Is there some command somewhere that we can use for this? `tools/utils.py` distinguishes the two, but not `armv7` and `armv8`. 

Regarding hosting/donator: should we just split `$vm_provider` into `$hosting-$donator`, omitting one if they are the same?

So:
```
$flavour-$hosting-$donator-$os$os_version-$architecture-$unique_id
test-nodesource-continuationlabs-raspbian-wheezy-arm-6
test-msft-win10-x64-1
```

I assume we separate `$os-$os_version` if `$os_version` is not numeric.

**Comment by jbergstroem** [comment]
@joaocgreis the problem with optionally omitting parts makes it harder to parse.

**Comment by jbergstroem** [comment]
Ok, I'm going to proceed on using this convention for all bots forward. I'll open a PR for documenting this. The "final" form is currently as follows:

`$type-$provider{_$sponsor}-$os-$architecture-$uniqueidentifier`

- $type: outlines the purpose of this machine. These types are the one's I found so far: release,test,lint,benchmark
- $provider: hosting and/or hardware provider. Currently: nodesource, digitalocean, rackspace, joyent, ibm, softlayer (should this be ibm or is it different?), voxer, ns (nodesource?) and scaleway
- $sponsor: optional if hardware is provided by someone specific
- $os: name of os including major (we're targeting toolchain abi here, no?) version, for instance freebsd10, centos5, fedora23 and so on
- $architecture: what architecture the host os/hardware runs. This might differ from the actual job (think cross-compilation). The options here are available through `./configure --help` in node.
- $unique_id: should always be 1 unless two or more similar machines are deployed on the same provider. If so, increment it.

**Comment by orangemocha** [comment]
Not sure if like the purpose in there, as a machine can have multiple purposes and the purpose can easily change.

We might also want to capture few optional machine characteristics, like rpi, or the compiler version (eg VS2015).

We also have the option of using labels, which is probably a good idea since there are so many facets in this categorization.

So what if we used the machine name for immutable characteristics, and rely on labels for the rest?

Purpose would be a better fit for a label, I think.

**Comment by jbergstroem** [comment]
I haven't seen too many examples of a machine switching (or having multiple) purposes. Release machines are the obvious off limits-reusage, lint machines are intentionally deployed on lesser hardware and some test machines are deployed with specific toolchains. All in all, I'd rather improve tooling for quicker deploys of hardware (which I am) instead of doing multi-purpose stuff.

I think labels could help for stuff like toolchain and convenience stuff (rpi, etc). I personally don't care if we're testing on a rpi or rpi2 but there should definitely be information somewhere. It's just irrelevant from a deployment perspective when setting the bot up.

**Comment by jbergstroem** [comment]
Closing this. We've already more than halfway through the slaves in terms of redeploying/renaming.
