### ISSUE TITLE
github-bot logs flooded w/"request socket closed" from Jenkins

### ISSUE THREAD

**Issue by phillipj** [nodejs/build#2551]
Looking at the @nodejs-github-bot logs today, I noticed a flood of warnings related to Jenkins posting job statuses to it:

```json
{
  "level": 40,
  "req": {
    "method": "POST",
    "url": "/node/jenkins/end",
    "headers": {
      "content-type": "application/json; charset=UTF-8",
      "content-length": "242",
      "host": "github-bot.nodejs.org:3333",
      "connection": "Keep-Alive",
      "user-agent": "Apache-HttpClient/4.5.13 (Java/1.8.0_275)",
      "accept-encoding": "gzip,deflate"
    },
    "query": {},
    "remoteAddress": "::ffff:147.75.66.203",
    "remotePort": 35416
  },
  "res": {
    "statusCode": 400,
    "header": "HTTP/1.1 400 Bad Request\r\nX-Powered-By: Express\r\nX-Request-Id: da5da100-78f2-11eb-934a-d358fd6d2198\r\nDate: Sat, 27 Feb 2021 11:56:40 GMT\r\nConnection: keep-alive\r\nKeep-Alive: timeout=5\r\nContent-Length: 46\r\n\r\n"
  },
  "duration": 2.220507,
  "msg": "request socket closed",
  "time": "2021-02-27T11:56:40.595Z",
  "v": 0
}
```

Assuming these requests comes from: https://github.com/nodejs/build/blob/9957995e56387ed2b827b6d591b81c6d3efab74e/jenkins/pipelines/post-build-status-update.jenkinsfile#L65-L78

I'm wondering if there's any traces on Jenkins' logs? Majority of these requests seems to come from `147.75.66.203`.

**Comment by phillipj** [comment]
Worth mentioning this seems to happen from other Jenkins IPs as well, and in some cases when the response code is `200` as opposed to `400` as shown in the log example above.

**Comment by rvagg** [comment]
The IP is test-packetnet-ubuntu1804-x64-1, and it's probably overrepresented because that's where the majority of these "workspace" jobs are executed since it's first in the list (and it doesn't seem to round-robin very well)
