### ISSUE TITLE
FYI - Cloud flare cleanp

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2553]
Removed a few entries that I believe were pointing to machines that used to be in the joyent datacenters but are long gone:

For node.org

type  | name  | IP v4 address   | TTL   | Proxy Status
-- | -- | -- | -- | --
A | centos | 165.225.130.68 | Auto | DNS only
A | jenkins | 165.225.128.59 | Auto | DNS only
A | smartos | 165.225.128.184 | Auto | DNS only
A | ubuntu | 165.225.130.75 | Auto | DNS only

For iojs.org, this one was likely broken a long time ago, but since nobody
complained just removed. unencrypted.nodejs.org still works.

type  | name  | IP v4 address   | TTL   | Proxy Status
-- | -- | -- | -- | --
A | unencrypted | 72.2.119.21 | Auto | DNS only

**Comment by richardlau** [comment]
@mhdawson I think we can close this off?

**Comment by mhdawson** [comment]
Closing.
