### ISSUE TITLE
Access for @AshCripps  to install download metrics scripts

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2556]
@AshCripps has been working on the scripts to gather/publish the download metrics again. These need to go on the main Webserver.  

I'd like to ask for temporary access for @AshCripps so that he can do this.

**Comment by richardlau** [comment]
+1

**Comment by richardlau** [comment]
Does this need to stay open? I'd have no objections to making whatever temporary access @AshCripps was given permanent.

**Comment by AshCripps** [comment]
I dont think access was ever given as I decided to go with a different approach so im going to go ahead and close.
