### ISSUE TITLE
Loopback interface for FreeBSD bots

### ISSUE THREAD

**Issue by saghul** [nodejs/build#256]
Some libuv tests fail because of this: https://github.com/libuv/libuv/issues/128#issuecomment-156114196

**Comment by jbergstroem** [comment]
Known limitation in some scenarios. We will solve this by avoid using:
1. triton at joyent (loopback and broadcast not available for use)
2. freebsd jails

We currently have one freebsd runner at digital ocean and one at joyent. I will retire the joyent one and replace it with a new setup at DO.

**Comment by jbergstroem** [comment]
This shouldn't be an issue any longer -- the two remaining freebsd bots are not run in triton or jails.

**Comment by saghul** [comment]
Will test and report back, thanks Johan!
