### ISSUE TITLE
citgm-smoker doesn't include Windows with vs2019

### ISSUE THREAD

**Issue by targos** [nodejs/build#2560]
See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2643/
Nothing is running on Windows.

**Comment by targos** [comment]
@nodejs/citgm-admins

**Comment by richardlau** [comment]
I've added win10-vs2019 and win2012r2-vs2019 labels to the job.

**Comment by richardlau** [comment]
Here's a run with the most recent Node.js 16 rc build: https://ci.nodejs.org/job/citgm-smoker-nobuild/1063/

**Comment by richardlau** [comment]
Okay apparently I can't read. I've added win-vs2019 to the citgm-smoker job too.

**Comment by richardlau** [comment]
Build on current master: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2651/

**Comment by richardlau** [comment]
> Build on current master: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2651/

Well that failed as the job has an explicit check to match VS versions to Node.js majors. Have added VS2019 for Node.js 14 and later.
Requested another run: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2652/
