### ISSUE TITLE
FreeBSD infra failure

### ISSUE THREAD

**Issue by jayaddison** [nodejs/build#2563]
This issue appears similar in symptom to #1895.

During the FreeBSD build of nodejs/node#37688, there was a build failure in the [`node-test-commit-freebsd` job](https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd11-x64/38552/):

```
10:43:09 tap2junit: error: argument --input/-i: can't open 'cctest.tap': [Errno 2] No such file or directory: 'cctest.tap'
```

**Comment by richardlau** [comment]
The `tap2junit` error can be ignored. It's run with `|| true` so will not fail the build when it fails. 
```
tap2junit -i cctest.tap -o out/junit/cctest.xml || true
```
Older Node.js releases wrote test results out to `cctest.tap` and this bit of code converted them to JUnit format for uploading to Jenkins. The more current major versions of Node.js output the `cctest.xml` file directly.

**Comment by jayaddison** [comment]
Thanks @richardlau; I'll go ahead and close this issue.
