### ISSUE TITLE
Alternatives to Jenkins?

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#257]
More a question than an issue: Given the ongoing issues with Jenkins, are there reasonable alternatives we could explore? Obviously continuing our current platform support is critical. What are the key requirements we have for the CI environment? /cc @nodejs/ctc

**Comment by rvagg** [comment]
buildbot is probably the most reasonable alternative, I actually started off with buildbot when we first spun this all up in node-forward but discovered that I was spending waaaaay to much time hacking Python than moving forward since that's how you have to configure it. It has come up in discussions on IRC this week though, we all have Jenkins fatigue (on top of existing Java fatigue for me).

**Comment by jasnell** [comment]
Yep, truthfully this is getting to be far too painful. Jenkins is... not fun. If we could get a couple more folks helping with the python slinging, would it be reasonable to switch? @mhdawson ... what do you think? Any opinions here?

**Comment by mscdex** [comment]
Let's write one in node!

**Comment by rvagg** [comment]
See extensive discussion @ https://github.com/nodejs/build/issues/4 (which I'd rather have left open, but it did kind of go stale)

**Comment by Trott** [comment]
@mscdex If you have a lot of free time to donate to such a project, there's this: https://github.com/fishin/ficion

**Comment by mscdex** [comment]
@Trott Just briefly looking at the code, the fishing theme is confusing, but I'm not even sure what state the project is in or how to really use it.

**Comment by Trott** [comment]
@mscdex If you're serious about wanting to know more, you can email the author at lloyd.benson@gmail.com. (I wasn't sure if you're "Let's write one in Node!" was tongue-in-cheek or not.)

**Comment by mscdex** [comment]
I was partially serious.

**Comment by mscdex** [comment]
Do we have a list somewhere of what our needs and wants are in a CI solution?

**Comment by mikeal** [comment]
It's kind of a amazing to me that nobody has written something like this yet being that Node.js is sort of ideal for this use case.

**Comment by misterdjules** [comment]
@mikeal https://github.com/Strider-CD/strider.

**Comment by TheAlphaNerd** [comment]
Sounds like it could be a good foundation level project.

**Comment by jbergstroem** [comment]
I'm happy to be part of either setting buildbot up or writing a more formal outline for what would be needed to build our own. One approach could be reusing the buildbot (nine) architecture and replace as we go -- if replace is really necessary. The nine frontend is confusing to me, but slaves, masters and configuring them are pretty straightforward.

**Comment by mhdawson** [comment]
@jasnell I don't know of a better alternative and I wonder if we'll just end up complaining about any other choice we make after having used it for a while.

**Comment by jasnell** [comment]
@mhdawson good point ;-) I do think, however, it would be worthwhile, when time is available, to at least investigate a handful of options -- or, at the very least, get an outline of the requirements together.

**Comment by mscdex** [comment]
@orangemocha Well, I would bet there are more node.js developers amongst us than Java developers, so I'm not sure how many contributions would be made to Jenkins (compared to a node-based solution).

As far as TeamCity goes, I saw that the other day. They do have an [Enterprise license for open source projects](https://www.jetbrains.com/buy/opensource/?product=teamcity) that is free, provided all of their requirements are met. Does someone want to play with a copy of TeamCity using the free license to get a feel for it and see how well it would work for us (andhow many modifications we'd need to make)?

**Comment by Fishrock123** [comment]
I spent some time back at NodeConf.eu talking to @lloydbenson about https://github.com/fishin/ficion, but it's mostly just early stages.

I think it would be possible to build something much better than jenkins, maybe in node. I think we also talked about this at the collaborator summit.

I'd be willing to try to move a significant amount of my time to such an effort, if possible and if that was a decided on thing we wanted to try to do.

I think it's fit to be a foundation project.

**Comment by Fishrock123** [comment]
Also I don't have two reliable computers at the current time, which makes trying to dev a CI-like thing difficult. That will change soon.

**Comment by mscdex** [comment]
@Fishrock123 or use virtual machines :-)

I might be interested in pitching in as long as it's something we want to invest in and we know exactly what we want from a CI system.

**Comment by jasnell** [comment]
ditto. happy to help on this. I can help provide some VM space for development.

**Comment by rmg** [comment]
Building a better CI was literally the reason I came to node, just over 4 years ago... and I _still_ haven't had time. _mutters something about priorities..._

**Comment by rmg** [comment]
That is to say, "Count me in"

**Comment by Fishrock123** [comment]
Perhaps we can re-use some of ficion but would prefer to make sure it is the way we like it?

In specific, I would prefer if it was as simple as possible, and attempting to be as real-time and as failure-proof (i.e. retries, multiple failure statuses, etc) as possible.

**Comment by jasnell** [comment]
let's start by brainstorming/listing the requirements we'd have, then we can compare that against where ficion is currently at.

**Comment by yorkie** [comment]
I guess https://github.com/travis-ci/travis-ci is a good referable example.

**Comment by rmg** [comment]
@yorkie thanks, I honestly had no idea so much of Travis's infrastructure was actually open source! And MIT license, even :-)

**Comment by DavidTPate** [comment]
I'd love to be involved in building it we just need to figure out what all we need out of the gate.

**Comment by Fishrock123** [comment]
So, some steps for this:

- Let's make a repo. Is `CI` a good enough name? or `new-CI`?
- Possibly do some pre-investigations of requirements and potential candidates before we think too much about building our own.
  - Personally, I'd like to keep it slim.
- Schedule a meeting to discuss what we collect.

Thoughts?

**Comment by jasnell** [comment]
* +1 for `nodejs/CI`
* An Issue or requirements.md doc in the new CI ought to be sufficient for brainstorming requirements (+1 on keeping it absolutely minimal)
* +1 for a meeting. Personally tho, my time will be limited over the next three weeks due to holiday and conferences.

**Comment by cjihrig** [comment]
+1 from me too. Do we need a group so that we can @ mention all interested parties?

**Comment by targos** [comment]
I'm interested in this too.

**Comment by Trott** [comment]
I'm interested as well.

**Comment by Fishrock123** [comment]
Moving to https://github.com/nodejs/CI/pull/1 and https://github.com/nodejs/CI/issues/2

**Comment by jimmont** [comment]
Github now has actions as well, see:
https://github.com/features/actions
https://github.com/actions
