### ISSUE TITLE
'localhost' not resolved to '::1' on smartos18?

### ISSUE THREAD

**Issue by treysis** [nodejs/build#2570]
Hey,

it seems like `localhost` isn't _always_ resolved to `::1` on `smartos18`, so tests fail, while they pass on all other systems, including `smartos17`. E.g. listening on `localhost` seems to mean listening on `::1`, but when connecting to the debugger, it is trying `127.0.0.1`. Maybe missing entry for `::1     localhost` in `/etc/hosts`?

See: https://ci.nodejs.org/job/node-test-pull-request/36703/

**Comment by treysis** [comment]
This shouldn't take long to solve?

**Comment by rvagg** [comment]
They were reprovisioned only last week because of a datacentre shutdown we had to quickly react to! I can't connect to the host in question from the CI job, perhaps we still haven't got the inventory sorted out with new addresses. But we do have `::1` mapping set up in our general Ansible tasks because this used to be a widespread inconsistency, so this _should_ have been done when the machines were reprovisioned: https://github.com/nodejs/build/blob/master/ansible/roles/jenkins-worker/tasks/main.yml#L44-L49

**Comment by richardlau** [comment]
https://github.com/nodejs/build/pull/2568 updates the IP addresses in the inventory. `/etc/hosts` on both machines contain the `::1` mapping:
```
$ ssh test-joyent-smartos18-x64-3 -C "cat /etc/hosts"
::1             localhost
127.0.0.1       localhost localhost.local loghost d894f3c6-d09a-c9df-d7ae-b6f613d9b413
::1 localhost.localdomain localhost
$ ssh test-joyent-smartos18-x64-4 -C "cat /etc/hosts"
::1             localhost
127.0.0.1       localhost localhost.local loghost db3664d7-dd31-c233-cafb-df79efb9d069
::1 localhost.localdomain localhost
$
```

**Comment by treysis** [comment]
Alright, thanks for the info. Then we should check again why the test suite tries to resolve localhost to `127.0.0.1` or if that is working now.

**Comment by treysis** [comment]
Weird. I am still getting errors with the test suite:
```
19:18:09 not ok 1625 parallel/test-net-writable
19:18:09   ---
19:18:09   duration_ms: 0.887
19:18:09   severity: fail
19:18:09   exitcode: 1
19:18:09   stack: |-
19:18:09     node:events:346
19:18:09           throw er; // Unhandled 'error' event
19:18:09           ^
19:18:09     
19:18:09     Error: connect ECONNREFUSED 127.0.0.1:46447
19:18:09         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1143:16)
19:18:09     Emitted 'error' event on Socket instance at:
19:18:09         at emitErrorNT (node:internal/streams/destroy:195:8)
19:18:09         at emitErrorCloseNT (node:internal/streams/destroy:160:3)
19:18:09         at processTicksAndRejections (node:internal/process/task_queues:81:21) {
19:18:09       errno: -146,
19:18:09       code: 'ECONNREFUSED',
19:18:09       syscall: 'connect',
19:18:09       address: '127.0.0.1',
19:18:09       port: 46447
19:18:09     }
```
The line is:
```
const socket = net.connect(this.address().port, 'localhost');
```

**Comment by treysis** [comment]
Does the SmartOS have a public IPv6 address? I tried to test a little bit and it seems it is only resolving localhost to `::1` if there is a public IPv6 configured? Can you confirm this?

**Comment by bahamat** [comment]
@treysis None of these hosts have a public IPv6 address. At this point, adding IPv6 would be difficult.

Where actually are these tests that are failing? I don't see them in the master branch and the PR only has diffs.

**Comment by bahamat** [comment]
For what it’s worth, I’m using this test in the smartos18 CI zone, and the result is *always* `::1`.

```
#!/usr/bin/env node

var dns = require('dns');

dns.lookup('localhost', {
    family: 0,
    verbatim: true
  }, function (e, a, f) {
    var now =  new Date();
    console.log(
      JSON.stringify({
        date: now,
        err: e,
        address: a,
        family: f
      })
    );
  }
);
```

If I could get access to a copy of the specific binary that’s exhibiting the problem I can try to look into this further.

**Comment by treysis** [comment]
It's not a specific binary. We try to merge a PR that sets `verbatim = true` by default to ease IPv6 migration.

However, this causes a lot of jobs to fail, and one was the SmartOS18-CI which would resolve `localhost` to `127.0.0.1`. But as it seems this only happens due to `AI_ADDRCONFIG`-flag being set for the `net.connect` method on everything but Windows. So it isn't the case using `dns.lookup`, which only happens _after_ `net.connect` (i.e. it is invoked by `net.connect`). So, I actually assume that the SmartOS18-CI is working correctly and as designed. So it's rather related to `glibc` or whatever equivalent Unix uses. However, it has been proposed to drop `AI_ADDRCONFIG` and this is the way we are seeming to go forward.

I wonder, however, why this is different on the Linux-CIs. They resolve to `::1`.

**Comment by richardlau** [comment]
Is there anything remaining to be done here?

**Comment by treysis** [comment]
Not that I am aware of. I think this can be closed. Should there be something, I'll open a new issue.
