### ISSUE TITLE
Last nightly build lacks some binaries

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/build#2577]
Not sure if the build is in progress, sorry if so. Please, compare:

https://nodejs.org/download/nightly/v16.0.0-nightly20210316640fe94354/
https://nodejs.org/download/nightly/v16.0.0-nightly20210317da4b23354f/

**Comment by vsemozhetbyt** [comment]
BTW, when I tried to load a missing file like https://nodejs.org/download/nightly/v16.0.0-nightly20210317da4b23354f/win-x64/node.exe , I've got 404.

**Comment by rvagg** [comment]
you might have tried too early @vsemozhetbyt, nightlies roll in over time, not all at once. They should be all there within ~30 mins (or maybe up to an hour, there's a couple of async things that can cause delay). The file is there now.

**Comment by rvagg** [comment]
for clarity - the various build servers for each of these binaries will upload them to "staging" when they're done, there's a very large differential in speed of the builds, and some of them require the same machine so are done in serial. There's a process on the main web server that looks for builds to promote (and create a SHASUMS for) on a regular cadence and that's when they appear in the nightly directory. This runs every 30 minutes now I think (we extended it recently, I think it was 5 minutes but now it's much slower to avoid some race conditions). Flushing out the Cloudflare cache is done at promotion time for any of these builds so the delay is in build+promote. So, basically, for the latest nightlies, a bit of patience and they should all show up if they are going to show up.

**Comment by vsemozhetbyt** [comment]
Thank you for clarifying!
