### ISSUE TITLE
Offline macs

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2578]
The following macOS CI hosts are currently offline in Jenkins:
https://ci.nodejs.org/computer/test-nearform-macos10.15-x64-2/
https://ci.nodejs.org/computer/test-nearform-macos10.15-x64-3/
https://ci.nodejs.org/computer/test-orka-macos10.15-x64-2/

The two offline nearform macs are out of space:
![image](https://user-images.githubusercontent.com/5445507/111463373-6b5a2700-8717-11eb-9785-a95c942a3620.png)
![image](https://user-images.githubusercontent.com/5445507/111463417-76ad5280-8717-11eb-80ca-9516e5918d63.png)

The orka machine is unreachable:
```
$ ssh test-orka-macos10.15-x64-2
ssh: connect to host 199.7.167.99 port 8823: No route to host
$
```

cc @AshCripps

**Comment by richardlau** [comment]
`./Library/Caches/node-gyp` for the `iojs` user on `test-nearform-macos10.15-x64-2` was taking up 1.2 GiB so I removed it and brought it back online in Jenkins. It's currently running https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/39533/.

The equivalent folder on `test-nearform-macos10.15-x64-3` is only 176MiB.

**Comment by richardlau** [comment]
```
administrator@test-nearform-macos10 ~ % du -hs /Users/iojs/build/workspace/*
3.0M    /Users/iojs/build/workspace/citgm-smoker
173M    /Users/iojs/build/workspace/citgm-smoker-nobuild
 12G    /Users/iojs/build/workspace/node-stress-single-test
7.0G    /Users/iojs/build/workspace/node-test-commit-osx
208M    /Users/iojs/build/workspace/node-test-node-addon-api-new
administrator@test-nearform-macos10 ~ %
```

I have no idea if 12G is normal for a macOS Node.js build. I could remove the node-stress-single-test workspace but we'd likely run out of space again the next time the job is run.

**Comment by richardlau** [comment]
I've wiped out the node-stress-single-test workspace on the two nearform macs and marked them online but they appear to have gone offline again in Jenkins still reporting low space 😕.

**Comment by AshCripps** [comment]
is there a way we could remove the nearform macs from `node-stress-single-test` they are always tight on space and that job always wipes them out. The Orka machines on the other hand have plenty of space

**Comment by richardlau** [comment]
It's currently done off the `osx1015` label.

**Comment by richardlau** [comment]
I've added a post build task to the stress job to run `make distclean` on mac OS like we do at the end of the `node-test-commit-osx` job: https://github.com/nodejs/jenkins-config-test/commit/90ec1180ce67e5501d679e365fa678a6101e08c8
That should shrink the disk usage when the job finishes.

**Comment by richardlau** [comment]
The nearform macs are now all back online.

`test-orka-macos10.15-x64-2` is still unreachable.

**Comment by richardlau** [comment]
@AshCripps friendly ping re. `test-orka-macos10.15-x64-2`.

**Comment by AshCripps** [comment]
Rebooted `test-orka-macos10.15-x64-2` from inside orka and its come back. sorry for letting this slip off my radar!
