### ISSUE TITLE
Moved node-test-commit-linux-as-shared-lib to ubuntu1804-64

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2586]
Quick PSA that I've updated https://ci.nodejs.org/job/node-test-commit-linux-as-shared-lib/ so that it builds on `ubuntu1804-64` instead of `ubuntu1404-64`: https://github.com/nodejs/jenkins-config-test/compare/7dbbbc2af66cb696532dfcf6963497ff09b67d70...97a1bfec56f98e436c6fbf849ff844d8a1f4c92a

It was a fairly quick change while I was editing the job for https://github.com/nodejs/build/issues/2576 and it appears to have fixed a big sea of red due to the compiler on the `ubuntu1404-64` machines being too old (gcc/g++ 4.9.4). Given that it has been broken for so long I'm not sure anyone is looking at this job anymore? cc @yhwang (who apparently gets emails on failures) @mhdawson 

![image](https://user-images.githubusercontent.com/5445507/112049631-cc369480-8b47-11eb-9490-9c6c3ff7f5d1.png)

**Comment by mhdawson** [comment]
@richardlau  + 1 on having moved that.
