### ISSUE TITLE
CentOS 5 release machine changes

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#259]
I'm noting this here in an issue because I don't have time to mess with the Ansible configs while I push forward on v0.12 and v0.10 builds.

/etc/sysconfig/jenkins now has this `JENKINS_ENV="PRE_1_PATH=/home/iojs/bin:$PATH ARCH=....`, and the Jenkins config for the release jobs overwrite `PATH` if `PRE_1_PATH` exists and it's a <= v0.12 build.

**Comment by rvagg** [comment]
Also, `xz` is needed on these machines as we discovered today #258

**Comment by jbergstroem** [comment]
Is this how we juggle gcc?

**Comment by rvagg** [comment]
```
if [[ "X$PRE_1_PATH" != "X" && $NODE_VERSION =~ ^[0] ]]; then
  export PATH=$PRE_1_PATH
fi
```

yep

**Comment by jbergstroem** [comment]
its almost like we should invert this? i mean, we do the exact same thing to "enable" gcc48.

**Comment by rvagg** [comment]
maybe but I've taken the approach that >=v4.x releases are going to be more frequent and will soon be the only releases we're pushing and that <=v0.12 releases are the exception

**Comment by jbergstroem** [comment]
Yeah, its just that double negation is kind of awkward. Perhaps create functions available through env that's called `gcc48` and `gcc41` we call regardless of default?

**Comment by rvagg** [comment]
we can easily add `POST_1_PATH` and do the same there, I'd be happy to do that. Not so sure about using gcc version numbers because they are not consistent across the *nix environments we have.

**Comment by jbergstroem** [comment]
@rvagg i didn't see this being used everywhere, just the exceptions which are centos5 and 6(gcc44, right?).

**Comment by rvagg** [comment]
mm, in practice it's turned out to be the only thing needed for <=0.12

**Comment by jbergstroem** [comment]
How about we do this instead:
```bash
if [[ $NODE_VERSION =~ ^[0] ]]; then
  export PATH=${PATH//\/opt\/rh\/devtoolset-2\/root\/usr\/bin:/}
fi
```
..then remove all the PRE_ variable stuff? I don't see above path changing anytime soon, and if it doesn't match we should be fine anyway.

**Comment by rvagg** [comment]
fine, I guess. would be nice to be testing 0.10 and 0.12 with vanilla compilers on wheezy but since I don't think we're doing that then whatever.

**Comment by jbergstroem** [comment]
Just implemented this. If things blow up for 0.x you know who to blame.
