### ISSUE TITLE
AIX test result weirdness

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2590]
I'm looking at https://ci.nodejs.org/job/node-test-commit-aix/35827/nodes=aix72-ppc64/console and the console results are strange with apparent missing durations:

```
02:46:35 ok 2360 parallel/test-tls-client-getephemeralkeyinfo
02:46:35   ---
02:46:35   duration_ms: 0.431
02:46:35   ...
02:46:35 ok 2361 parallel/test-tls-client-reject
02:46:35   ---
02:46:35   duration_ms: 0.348
02:46:35   ...
02:46:35 ok 2362 parallel/test-tls-client-renegotiation-13
02:46:35 ok 2363 parallel/test-tls-client-reject-12
02:46:35 ok 2364 parallel/test-tls-client-resume-12
02:46:35 ok 2365 parallel/test-tls-client-renegotiation-limit
02:46:35 ok 2366 parallel/test-tls-client-resume
```

And the end results is a failed run for reasons I can't quickly ascertain. (I have not dug in on this, though.)

@nodejs/platform-aix

**Comment by richardlau** [comment]
That is weird.... if it was simply truncated I'd put it down to the disk space issue we resolved inhttps://github.com/nodejs/build/issues/2592#issuecomment-806835606 but the missing durations is odd. 

I guess we keep an eye out for whether it reoccurs in the next day or so and close out if it doesn't?

**Comment by Trott** [comment]
> I guess we keep an eye out for whether it reoccurs in the next day or so and close out if it doesn't?

I say we close this and re-open it if it recurs. (Closing now, but re-open if you think that's hasty of me.)
