### ISSUE TITLE
CI is not permitting new jobs

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2592]
Tried starting node-test-pull-request jobs via both Resume Build and Build With Parameters and nothing happened. No error or anything, but no CI job started either. I'm guessing a disk somewhere is full?

**Comment by richardlau** [comment]
Yeah, grafana showed that the rootfs was full. Logged into the backup server and ran the [backup script](https://github.com/nodejs/build/issues/2453#issuecomment-702690181)... it errored but appears to have freed up space.

```
# /root/backup_scripts/remove_old.sh ci.nodejs.org
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 No valid crumb was included in the request</title>
</head>
<body><h2>HTTP ERROR 403 No valid crumb was included in the request</h2>
<table>
<tr><th>URI:</th><td>/reload</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>No valid crumb was included in the request</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.33.v20201020</a><hr/>

</body>
</html>
```

**Comment by Trott** [comment]
I'm able to start jobs again. Thank you!

**Comment by richardlau** [comment]
Grafana showed the rootfs being full again.
![image](https://user-images.githubusercontent.com/5445507/118704899-82002580-b80f-11eb-8700-32ae2e3cb077.png)

I've run the script again to free up space.
