### ISSUE TITLE
persistent segmentation fault on test-joyent-smartos18-x64-3

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2595]
Example:

https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos18-64/38120/console

```
06:37:58 make[2]: *** [node.target.mk:26: /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos18-64/out/Release/obj/gen/node_snapshot.cc] Segmentation Fault (core dumped)
06:37:59 make[2]: *** Deleting file '/home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos18-64/out/Release/obj/gen/node_snapshot.cc'
06:37:59 make[2]: *** Waiting for unfinished jobs....
06:37:59 rm f71b4feac756fed9c21d6d0842d85be9a315b43b.intermediate c0d3688cf3ff7adec2011795c8cab739f9a19e66.intermediate b9fe59ad2f44d0ae02d580e48d6c8b810c7b326f.intermediate 5c94200d472ffe7dad90f9432e8a8c4499483bc4.intermediate
06:37:59 make[1]: *** [Makefile:104: node] Error 2
06:37:59 make: *** [Makefile:531: build-ci] Error 2
06:37:59 Build step 'Execute shell' marked build as failure
06:37:59 Performing Post build task...
06:38:04 Match found for : : True
06:38:04 Logical operation result is TRUE
06:38:04 Running script  : #/bin/bash
06:38:04 
06:38:04 set -x
06:38:04 mkdir -p out/junit
06:38:04 tap2junit -i test.tap -o out/junit/test.xml
06:38:04 tap2junit -i cctest.tap -o out/junit/cctest.xml
06:38:04 [smartos18-64] $ /bin/sh -xe /var/tmp/jenkins2820086363702493187.sh
06:38:04 + set -x
06:38:04 + mkdir -p out/junit
06:38:04 + tap2junit -i test.tap -o out/junit/test.xml
06:38:04 + tap2junit -i cctest.tap -o out/junit/cctest.xml
06:38:10 usage: tap2junit [-h] --input INPUT --output OUTPUT
06:38:10 tap2junit: error: argument --input/-i: can't open 'cctest.tap': [Errno 2] No such file or directory: 'cctest.tap'
06:38:10 POST BUILD TASK : FAILURE
06:38:10 END OF POST BUILD TASK : 0
06:38:10 Recording test results
06:38:10 [Checks API] No suitable checks publisher found.
06:38:12 Collecting metadata...
06:38:12 Metadata collection done.
06:38:12 Notifying upstream projects of job completion
06:38:12 Finished: FAILURE
```

**Comment by Trott** [comment]
Removing workspaces to see if it works when they are rebuilt.

**Comment by Trott** [comment]
And now it's a different error:

```
06:53:00 Started by upstream project "node-test-commit-smartos" build number 38121
06:53:00 originally caused by:
06:53:00  Started by upstream project "node-test-commit" build number 45399
06:53:00  originally caused by:
06:53:00   Started by upstream project "node-test-pull-request" build number 36991
06:53:00   originally caused by:
06:53:00    Started by user Rich Trott
06:53:00    Started by upstream project "node-test-pull-request" build number 36990
06:53:00    originally caused by:
06:53:00     Started by user Darshan Sen
06:53:00 Running as SYSTEM
06:53:00 [EnvInject] - Loading node environment variables.
06:53:00 Building remotely on test-joyent-smartos18-x64-3 (5.11 amd64-sunos-5.11 smartos18-64 amd64-sunos sunos amd64 sunos-5.11) in workspace /home/iojs/build/workspace/node-test-commit-smartos/nodes/smartos18-64
06:53:00 Triggering projects: post-build-status-update
06:53:00 [smartos18-64] $ /bin/sh -xe /var/tmp/jenkins8593858392396726531.sh
06:53:00 + . ./build/jenkins/scripts/node-test-commit-pre.sh
06:53:00 /var/tmp/jenkins8593858392396726531.sh[4]: .: ./build/jenkins/scripts/node-test-commit-pre.sh: cannot open [No such file or directory]
06:53:00 Build step 'Execute shell' marked build as failure
06:53:00 Performing Post build task...
06:53:00 Match found for : : True
06:53:00 Logical operation result is TRUE
06:53:00 Running script  : #/bin/bash
06:53:00 
06:53:00 set -x
06:53:00 mkdir -p out/junit
06:53:00 tap2junit -i test.tap -o out/junit/test.xml
06:53:00 tap2junit -i cctest.tap -o out/junit/cctest.xml
06:53:00 [smartos18-64] $ /bin/sh -xe /var/tmp/jenkins8910767703866177162.sh
06:53:00 + set -x
06:53:00 + mkdir -p out/junit
06:53:00 + tap2junit -i test.tap -o out/junit/test.xml
06:53:01 usage: tap2junit [-h] --input INPUT --output OUTPUT
06:53:01 tap2junit: error: argument --input/-i: can't open 'test.tap': [Errno 2] No such file or directory: 'test.tap'
06:53:01 POST BUILD TASK : FAILURE
06:53:01 END OF POST BUILD TASK : 0
06:53:01 Recording test results
06:53:01 ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
06:53:01 Collecting metadata...
06:53:01 Metadata collection done.
06:53:01 Notifying upstream projects of job completion
06:53:01 Finished: FAILURE
```

**Comment by Trott** [comment]
Going to try a reboot next because 
¯\\_(ツ)_/¯

**Comment by richardlau** [comment]
> Removing workspaces to see if it works when they are rebuilt.

So the Multiple SCMs plugin was removed during the recent Jenkins update (https://github.com/nodejs/build/issues/2593) which has meant https://ci.nodejs.org/job/node-test-commit-smartos has stopped checking out any code... which probably means all those builds since the update but before the workspace was wiped was continually building the last checked out code before the the plugin was removed.

**Comment by Trott** [comment]
Nope, still failing.Not sure what to do next. @nodejs/platform-smartos

**Comment by richardlau** [comment]
Based on our config backups in https://github.com/nodejs/jenkins-config-test potentially the node-update-v8-canary job is also affected by the removal of the Multiple SCMs plugin:

```
$ grep MultiSCM jobs/*.xml
jobs/node-test-commit-smartos.xml:  <scm class="org.jenkinsci.plugins.multiplescms.MultiSCM" plugin="multiple-scms@0.6">
jobs/node-update-v8-canary.xml:  <scm class="org.jenkinsci.plugins.multiplescms.MultiSCM" plugin="multiple-scms@0.6">
$
```

I don't think we need the Multiple SCMs plugin... working on updating those jobs to use the git SCM like most of our other jobs do.

**Comment by richardlau** [comment]
Updated https://ci.nodejs.org/job/node-test-commit-smartos/ so code is now checked out (based on the same logic we use for https://ci.nodejs.org/job/node-test-commit-linux/) https://github.com/nodejs/jenkins-config-test/compare/0008862972de6f4d390b14032d5e7edfecb641c5...88ab6f6755154e4f2e524505c6000e4bf624ccc2

Test build against master: https://ci.nodejs.org/job/node-test-commit-smartos/38131/
Appears to be back to the segmentation fault 😞

**Comment by richardlau** [comment]
Updated https://ci.nodejs.org/job/node-update-v8-canary/ https://github.com/nodejs/jenkins-config-test/commit/a31815c252bbb25b5d79cb7a85308c9942cdd13b

Test build: https://ci.nodejs.org/job/node-update-v8-canary/1706/

**Comment by targos** [comment]
Wow, I'm happy that you noticed it for v8-canary. I was wondering why the build failed in CI while it was fine on my computer!

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/ is affected too... it didn't show up in the `grep` in https://github.com/nodejs/build/issues/2595#issuecomment-808254863 as I'd already saved the job to add `-p` to the `mkdir out/junit` and Jenkins also deleted the MultiSCM references. Updating the job now.

**Comment by richardlau** [comment]
> Wow, I'm happy that you noticed it for v8-canary. I was wondering why the build failed in CI while it was fine on my computer!

@targos @ryzokuken FYI (in case I've missed something) the config for node-update-v8-canary was using MultiSCM to clone/check out https://github.com/nodejs/node.git and the build repository specified by job parameters. I couldn't find any references to the checked out build repository so at the moment the job does not.

**Comment by targos** [comment]
It was checking out the build repository to run https://github.com/nodejs/build/blob/master/jenkins/scripts/node-update-v8-canary.sh 
I don't remember why but at some point it was changed to write the script directly in the job configuration.

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/ updated https://github.com/nodejs/jenkins-config-test/commit/512a867e4b64d04a59975f3612d599991c225732

Test build: https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/19885/

**Comment by richardlau** [comment]
I believe all affected jobs have been fixed -- the test builds at least passed and did check out code as expected. Feel free to reopen if anything's been missed.

**Comment by Trott** [comment]
Not sure if it's related, but it looks like benchmark-node-micro-benchmarks all started failing around the same time.

**Comment by richardlau** [comment]
> Not sure if it's related, but it looks like benchmark-node-micro-benchmarks all started failing around the same time.

@Trott Most of the failures are:
```
18:37:04 ++ curl -L https://github.com/nodejs/node/pull/37888.patch
18:37:04 ++ git apply -3
18:37:04   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
18:37:04                                  Dload  Upload   Total   Spent    Left  Speed
18:37:04 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   139  100   139    0     0    246      0 --:--:-- --:--:-- --:--:--   246
18:37:05 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
18:37:05 fatal: unrecognized input
```
which looks to be because https://github.com/nodejs/node/pull/37888.patch is empty.

**Comment by Trott** [comment]
> which looks to be because https://github.com/nodejs/node/pull/37888.patch is empty.

D'oh! Of course. Thanks.

**Comment by Trott** [comment]
> which looks to be because https://github.com/nodejs/node/pull/37888.patch is empty.

D'oh! Of course. Thanks.
