### ISSUE TITLE
CI job request: daily coverage job without Intl

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2596]
What do we all think about the idea of trying to set up a third test coverage job (to go along with the Linux one and the Windows one) to run Node.js compiled without Intl support? That would allow us to complete coverage in files like lib/internal/util/inspect.js.html. There's already a Jenkins job that does tests without Intl (https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu1804_sharedlibs_withoutintl_x64/). I think we'd just need to modify it to do coverage, run nightly, and push results to the right place(s).

**Comment by richardlau** [comment]
As I understand the current status on this one, there's an in progress attempt to do this as a GitHub action: https://github.com/nodejs/node/pull/37954

FWIW the Windows coverage job looks to have been broken for some time https://github.com/nodejs/build/issues/2645

**Comment by Trott** [comment]
Still not ready to give up on this...

**Comment by targos** [comment]
@Trott can we close now that https://github.com/nodejs/node/pull/37954 has landed?

**Comment by Trott** [comment]
> @Trott can we close now that [nodejs/node#37954](https://github.com/nodejs/node/pull/37954) has landed?

If there's consensus to abandon our own coverage in coverage.nodejs.org and rely on codecov.,io, then yes. If not, then we probably want to get it added to coverage.nodejs.org. I'm fine if you close this.
