### ISSUE TITLE
node-stress-single-test: timeouts and/or run durations?

### ISSUE THREAD

**Issue by Trott** [nodejs/build#260]
For https://github.com/nodejs/node/issues/3881, I'm trying to run a test only about 100 times to get a baseline failure rate. The test fails by timing out on CI a lot so 100 seemed like enough times to see a good number of failures on a Pi. It's taken hours and only gotten through the test 70 times or so with no failures at all. This leads me to believe that timeouts for all tests are not enforced on the stress tests the way they are for `node-test-commit`.

OK, no problem, I'll look and see how long each test run took! But that's not printed for the stress tests the way it is for `node-test-commit`.

This is not exactly urgent as there are some simple hacks/workarounds I can do for this, but in the interest of making the `node-stress-single-test` as useful as possible, can we at least get a duration printed for individual test runs, if not timeouts identical to what is enforced in the other `node-test-commit`? 

cc:  @joaocgreis

**Comment by joaocgreis** [comment]
Tests in `node-stress-single-test` are run directly with node, without using `test.py`. Hence timeouts are not enforced at all. I just changed it to print the approximate duration of the test, that was easy to do.

To do this properly, however, would be to change `test.py` to run some test a number of times, optionally running all other tests as it does now or skipping them. I'll keep this in my work list, but don't have the time right now. Perhaps this is a good first task for the testing WG? Ping me if you need more changes in the jenkins job, that I can do fairly quickly.

**Comment by jbergstroem** [comment]
fwiw, I saw a pretty long running test on the rpi's (3500 iterations done after ~6 hours) the other day.

**Comment by rvagg** [comment]
I killed one that was about that many iterations yesterday cause it was the only thing holding up a jenkins restart
