### ISSUE TITLE
Heads-up: Jenkins security updates on Wednesday April 7th

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2604]
> The Jenkins project plans to publish new Jenkins releases (weekly and LTS 2.277.2) on Wednesday, April 7. These updates will contain fixes for security issues present in current versions of Jenkins. The highest severity is "Medium". The security advisory will be issued at the same time to provide further information.

I should be around to handle this I think.

**Comment by richardlau** [comment]
Done, see https://github.com/nodejs/build/issues/2615.
