### ISSUE TITLE
Increase Jenkins timeout for node-test-commit-arm

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2605]
test.py has a default timeout for ARM processors of 240 seconds but the Jenkins job node-test-commit-arm times out at 180 seconds.

![image](https://user-images.githubusercontent.com/718899/113482828-3955fe00-9455-11eb-853d-90a1c4fb3e31.png)

In https://github.com/nodejs/node/pull/34289, I'm running pummel jobs on ARM and Jenkins is timing out before `test.py` which then kills the entire task. So I'm increasing it to 300ms. 

![image](https://user-images.githubusercontent.com/718899/113482977-ec265c00-9455-11eb-85df-664a92e1b9d1.png)

We may need to bump it up further because `test.py` is going to give extra time for `pummel` tests but we'll do that when the problem actually shows up.

I'm not sure if I need to document this change anywhere or if it needs to go in a configuration file somewhere or what? Or is this issue enough?

**Comment by richardlau** [comment]
Issue is the best we can do at the moment.

Perhaps optionally, if you can locate it, reference the commit in the config backup repository that captures the change — https://github.com/nodejs/jenkins-config-test/commit/3976bfabedb81c7488ec1b218db6664ea0aa844c in this particular case.
