### ISSUE TITLE
Release CI losing ssh connection with staging box

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#2609]
While building releases today I've seen multiple jobs failing with an error like the below while trying to upload assets to the staging box.

```
11:13:19 ssh_exchange_identification: Connection closed by remote host
```

**Comment by richardlau** [comment]
@nodejs/build-infra Any ideas on this one? I've verified that I can log into both of the release macOS hosts, `sudo` to `iojs` and then ssh to `node-www` successfully. It doesn't look like the connections are consistently being dropped (most of the jobs are succeeding). I also checked that we have not run out of space on `node-www` (we're good there).

**Comment by richardlau** [comment]
I wonder if we're hitting some sort of simultaneous connection limit due to starting 3/4 [iojs+release](https://ci-release.nodejs.org/job/iojs+release/) runs at the same time 🤷.

**Comment by MylesBorins** [comment]
@richardlau that very well may be the case.

**Comment by MylesBorins** [comment]
FWIW I have still seen a bunch of failures without running multiple full release jobs, so I think there might be something going on with the connection ¯\\\_(ツ)\_/¯

**Comment by MylesBorins** [comment]
This is now happening when I connect to do the promotion script with the following error

```
kex_exchange_identification: Connection closed by remote host
```

Might be something going on with the ssh-agent?

**Comment by mhdawson** [comment]
@richardlau at this point lets see if we can recreate on Wednesday, I'm wondering if maybe one of our providers is having an issue (firewalls or whatever)

**Comment by richardlau** [comment]
This is still happening (affecting both today's nightly and v8-canary builds). It's not consistent (most sub jobs were able to connect and upload) and it's not the same hosts that are failing.

As I mentioned earlier I'm going to need help to diagnose this further. I had a quick glance at `/var/log/auth.log` and there are a lot of failed log in attempts to various invalid userids -- I don't know if that's normal for an Internet accessible server.

**Comment by rvagg** [comment]
> As I mentioned earlier I'm going to need help to diagnose this further. I had a quick glance at /var/log/auth.log and there are a lot of failed log in attempts to various invalid userids -- I don't know if that's normal for an Internet accessible server.

yes, very normal.

I suspect this could be the problem:

<img width="931" alt="Screenshot 2021-04-08 151758" src="https://user-images.githubusercontent.com/495647/113972255-b16d5b00-987d-11eb-9174-3efa439af92c.png">

I've done a `killall rsync`, then decided to just reboot the server to clean up any process cruft that may have built up that I'm not seeing. But this isn't the first time we've seen something like this.

So here's an easy TODO for someone with access. This sync job is triggered by /etc/crontab:

```
* */4   * * *   nodejs  /home/nodejs/sync-benchmarking.sh
```

It needs to be converted into a systemd timer so a new job won't be started if an old job is running.

**Comment by rvagg** [comment]
^ to clarify - this is ssh clients and lots of rsync jobs, I don't know for sure that this would be causing the upload problems since it's not sshd getting involved, but it could be that the server was just approaching that point of _too much_.

**Comment by mhdawson** [comment]
We likely need to clean out the coverage data. @richardlau did I take you through that at one point ? I seem to remember doing it with somebody.

**Comment by richardlau** [comment]
@mhdawson You did indeed. I'll add to my todo list.

**Comment by mhdawson** [comment]
@richardlau thanks!
