### ISSUE TITLE
ubuntu1804_sharedlibs_container-x64-4 needs to be recreated

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2611]
Something was wrong with ubuntu1804_sharedlibs_container-x64-4. I logged into test-softlayer-ubuntu1804-docker-x64-1 to try to fix it and ended up making it worse by somehow removing/stopping/something the docker container entirely. I'm sure the fix here is simple. Maybe there's an ansible playbook that needs to be run?

Relevant status page: https://ci.nodejs.org/computer/test-softlayer-ubuntu1804_sharedlibs_container-x64-4/

**Comment by Trott** [comment]
Looks like it's recreated and running again. 
¯\\_(ツ)_/¯

**Comment by Trott** [comment]
Argh, but now this is happening with ubuntu1804_sharedlibs_container-x64-4:

```
Error: ENOSPC: no space left on device, copyfile '/home/iojs/build/workspace/node-test-commit-linux-containered/out/Debug/node' -> '/home/iojs/tmp/.tmp.407/node-copy.exe
```

And:

> Disk space is too low. Only 0.007GB left on /home/iojs/build.

**Comment by Trott** [comment]
I removed all the workspaces and got it down to this, but I wonder if it's going to fill up again:

```
/dev/xvda2       99G   76G   19G  81% /home/iojs
```

**Comment by richardlau** [comment]
Removing the workspaces is the right way to resolve this for the moment. We have https://github.com/nodejs/build/issues/2494 open as a longer term tracker. It appears that the softlayer docker host has less total disk space and cannot have two debug builds (across any two of its five containers) at the same time. 

https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#fixing-machines-with-docker documents most of the common commands to use on our docker hosts, e.g. if you need to restart the containers.
