### ISSUE TITLE
Request to join build working group

### ISSUE THREAD

**Issue by sxa** [nodejs/build#2617]
Hi,

I'm an existing node collaborator working for Red Hat and I have, ummm "many years" of extensive cross-platform system admin experience including on platforms such as AIX. This likely makes me a good person to have on to look at "weird" problems. I'm also interested in working to resolve any perceived single points of failure in knowledge of the systems that the WG uses.  In recent years I have worked on the infrastructure for the AdoptOpenJDK project including managing our jenkins CI/CD instance (I'd been keen to help towards [upgrading your java](https://github.com/nodejs/build/issues/2492)!) and am interested in formally joining this workgroup in order to share more expertise, best practices etc. in order to help both projects (albeit not full time!). I try to follow the WG recordings and would be keen to join in with future ones.

Hopefully the experience described above allows me to be sufficiently trusted for access. I'm also interested in the RISC-V platform which there have been some discussions about elsewhere (although my current machines are unavailable so I can't currently help with that effort) so if we were able to secure hardware specifically for this project I'm very keen to get that going. As a user of a Windows/aarch64 laptop I also have an interest in that as a secondary platform :-) Like @rvagg I have a pile of various SBCs kicking around ([pi stack](https://twitter.com/sxaTech/status/1338150308069990402), [other ones](https://twitter.com/sxaTech/status/1272263254203674626)) ;-)

**Comment by richardlau** [comment]
+1 from me. I've worked with @sxa for a number of years (prior to his AdoptOpenJDK involvement we were on the same Node.js team at IBM) and will vouch for his competency.

**Comment by mhdawson** [comment]
+1 from me.

**Comment by rvagg** [comment]
+1

**Comment by AshCripps** [comment]
Enough time has passed I would say this Stewart is accepted, congrats @sxa! 

What I would like to propose is giving him test access but also jenkins admin access for the test ci off the bat, he has a proven track record at adopt with the management of their jenkins and I personally have turned to him with queries about issues I have faced. He also expressed an interest in some ideas/improvements that could be made.

any objections @nodejs/build?

**Comment by richardlau** [comment]
SGTM
