### ISSUE TITLE
`release-nearform-macos11.0-arm64-1` unable to find utility "altool"

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2641]
I'm marking [`release-nearform-macos11.0-arm64-1`](https://ci-release.nodejs.org/computer/release-nearform-macos11.0-arm64-1/) offline in ci-release as it is failing to notarize pkg builds. The orka machine appears to be ok.

e.g. https://ci-release.nodejs.org/job/iojs+release/nodes=osx11-release-pkg/6857/console
```
07:44:10 2021-04-30T07:44:10.289+0100 [INFO]  notarize: notarization submission complete: output= err="exit status 72"
07:44:10     Error notarizing
07:44:10 
07:44:10 ❗️ Error notarizing:
07:44:10 
07:44:10 1 error occurred:
07:44:10 	* error submitting for notarization:
07:44:10 
07:44:10 xcrun: error: unable to find utility "altool", not a developer tool or in PATH
```

Xcode setup issue, similar to https://github.com/nodejs/build/issues/2501?
cc @AshCripps 

The macstadium hosted machine appears to be ok.

![image](https://user-images.githubusercontent.com/5445507/116799939-88df2680-aaf4-11eb-938a-1a8b06753eee.png)

**Comment by AshCripps** [comment]
Brought the node back online as this should be fixed. The xcode path was pointing to a CLI instance, pointed it back to the full xcode and was able to find `xcodebuild` and `xcrun`
