### ISSUE TITLE
Update CITGM job defaults

### ISSUE THREAD

**Issue by targos** [nodejs/build#2643]
@nodejs/citgm-admins Please update the following jobs:

- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/build?delay=0sec
  - Default to v16
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/build?delay=0sec
  - Default to v12 v14 v16
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration/build?delay=0sec
  - Set NODE_VERSION options to v12, v14, v16
  - Set default NODE_VERSION to v16
- https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration-pipeline/build?delay=0sec
  - Default NODE_VERSIONS to v12 v14 v16
  - Default GIT_REMOTE_REF to refs/heads/main

**Comment by richardlau** [comment]
All done. It might be good to revisit https://github.com/orgs/nodejs/teams/citgm-admins membership at some point.

**Comment by targos** [comment]
I'd be happy to become part of the team if that's possible without too much bureaucracy :)

**Comment by richardlau** [comment]
It's a GitHub group. I think @MylesBorins has the maintainer role for it. From a Build POV membership decision would be the WG governing the jobs (Release in this case): https://github.com/nodejs/build/blob/master/GOVERNANCE.md#jenkins-job-configuration-access
As a long standing TSC member you would meet all of the considerations we suggest for granting job editing permissions.

**Comment by MylesBorins** [comment]
+1 to adding @targos

**Comment by targos** [comment]
Thanks for updating the jobs! I opened https://github.com/nodejs/Release/issues/668 to join the citgm-admins team.
