### ISSUE TITLE
node-test-commit-windows-coverage-daily looks broken

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2645]
@nodejs/coverage-admins https://ci.nodejs.org/job/node-test-commit-windows-coverage-daily/ looks broken. 
e.g. https://ci.nodejs.org/job/node-test-commit-windows-coverage-daily/535/
➡️ https://ci.nodejs.org/job/node-compile-windows/40368/
All compile subjobs fail:
```
"NODEJS_MAJOR_VERSION parameter (14) does not match output of tools\getnodeversion.py (17)"
```
so I imagine this has been broken since Node.js 15. Looks like `NODEJS_MAJOR_VERSION` doesn't get set for the compile job so defaults to `14` leading to the mismatch.

**Comment by richardlau** [comment]
ping @nodejs/coverage-admins again.

**Comment by Trott** [comment]
One way to resolve this issue would be to retire our Jenkins-generated coverage and rely on https://app.codecov.io/gh/nodejs/node which is generated by GitHub Actions.

**Comment by Trott** [comment]
> One way to resolve this issue would be to retire our Jenkins-generated coverage and rely on https://app.codecov.io/gh/nodejs/node which is generated by GitHub Actions.

Argh, although I guess that would mean no C++ coverage?

**Comment by Trott** [comment]
Is the problem that an expectation of Node.js 14 is coded somewhere (maybe in an environment variable set by the job?) but running this on the master branch compiles Node.js 18 and the job errors because of that?:

```
20:01:43 > for /F "delims=." %a in ('python tools\getnodeversion.py') do if not "%a" == "14" (
20:01:43 echo "NODEJS_MAJOR_VERSION parameter (14) does not match output of tools\getnodeversion.py (%a)"  
20:01:43  exit /b 1 
20:01:43 ) 
20:01:43 
20:01:43 > if not "18" == "14" (
20:01:43 echo "NODEJS_MAJOR_VERSION parameter (14) does not match output of tools\getnodeversion.py (18)"  
20:01:43  exit /b 1 
20:01:43 ) 
20:01:43 "NODEJS_MAJOR_VERSION parameter (14) does not match output of tools\getnodeversion.py (18)"
20:01:43 
```
