### ISSUE TITLE
lastpass or 1password instead of secrets repo?

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2647]
Comment from @mmarchini in the #nodejs-dev channel of the OpenJS Foundation Slack while troubleshooting the bot/token issue that is keeping the commit queue from working:

> I would love to see us moving out of nodejs-private/secrets and into 1password/lastpass for credentials

Thoughts?

**Comment by bnb** [comment]
Happy to help get the TSC more set up with the Enterprise 1Password org that they comped for us if that'd be helpful.

**Comment by targos** [comment]
1Password has a feature for using secrets in automation https://1password.com/secrets/
That said, it doesn't necessarily have to be "password manager instead of secrets repo". Both could be kept for different needs.

**Comment by mmarchini** [comment]
Also, I was thinking more for account access (GitHub account for our bot, account for cloud providers, etc.) than for ssh access.

**Comment by jbergstroem** [comment]
I'd love 1P too - I use it for everything/
