### ISSUE TITLE
Can we decomission `infra-softlayer-ubuntu1404-x64-2`?

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2650]
`infra-softlayer-ubuntu1404-x64-2` is a bare metal machine in softlayer and it isnt doing anything, its even disconnected in softlayer and I think it had been for a while. Is it ok to decommission this machine and clear up the resources?

**Comment by richardlau** [comment]
I believe that despite the `infra-` prefix this is (was?) a benchmarking machine. At one point we were building V8 on it (https://github.com/nodejs/build/issues/1381, https://github.com/nodejs/build/issues/1970). 

I think gcc requirements have forced us off that machine and the jobs that were using it are now using the nearform benchmarking machines.

**Comment by rvagg** [comment]
Yep, was benchmarking, I think it was the first softlayer machine we provisioned in fact! That's all it was doing and we kept it because it was stable hardware to benchmark on, but afaik we can decommission now.

**Comment by mhdawson** [comment]
+1 to removing. It crashed as while back and we were not able to recover so we should remove so that we can use the resources (cost) associated with this in a different way.

**Comment by AshCripps** [comment]
Ticket has been updated saying the server was reclaimed
