### ISSUE TITLE
AIX 7.2 CI job is very unstable

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/build#2658]
https://ci.nodejs.org/job/node-test-commit-aix/buildTimeTrend

![image](https://user-images.githubusercontent.com/3759816/119369797-276f3980-bce7-11eb-9fef-6b8d9ff358fd.png)

Found in https://github.com/nodejs/node/pull/38751.

Not sure related to https://github.com/nodejs/build/issues/2621

cc @richardlau

**Comment by AshCripps** [comment]
Machine had loads of hanging processes - cleared them up and started a test build which seems to have progressed further than the failures. https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/36884/console

**Comment by AshCripps** [comment]
Job passed, closing. Reopen if it goes unstable again.
