### ISSUE TITLE
arm slaves: make sure nfs reconnects

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#267]
Two of the slaves (node-nodesource-raspbian-wheezy-pi1p-4-bengl and node-nodesource-raspbian-wheezy-pi1p-5-bengl) was disconnected because they had less than 2G free disk space (which is set up as part of jenkins monitoring). When looking closer at the issue, the nfs volume for /home/iojs/build was not mounted, probably related to a reboot. 

We should:
1. make sure the ansible scripts for the arm bots automounts nfs
2. have nfs volumes reconnect (perhaps use autofs)?

(ping @rvagg)

**Comment by rvagg** [comment]
they should be set up to reconnect but those two machines in particular seem to have trouble with this and I don't know why!

**Comment by jbergstroem** [comment]
did the nfs disconnect or was it something else?

**Comment by rvagg** [comment]
I _think_ it was when I rebooted the nfs master and the rest of them auto reconnected but these two are really stubborn.

**Comment by jbergstroem** [comment]
Lets close this for now then? If you see it again, perhaps put dmesg output in here so we can troubleshoot.

**Comment by rvagg** [comment]
no, I'd like to leave it open, these two machines are consistently problematic with nfs and something needs to be fixed. They usually take a very long time to boot because they can't get their mounts connected and then come up without them mounted and I have to do it manually.

**Comment by maclover7** [comment]
ping @jbergstroem @rvagg -- should this stay open?

**Comment by rvagg** [comment]
nfs has been really solid since my last refactor, I'm pretty happy with it now

**Comment by rvagg** [comment]
oh, and the problem really was about boot-time connections, most/all of the time it failed and needed manual intervention so it required me remembering to check regularly. We've solved that with some unfortunate hackery but it works much better than all of the official ways (see setup/raspberry-pi if you want gory details)
