### ISSUE TITLE
Always failing command in node-test-commit-v8-linux

### ISSUE THREAD

**Issue by targos** [nodejs/build#2679]
See https://ci.nodejs.org/job/node-test-commit-v8-linux/nodes=benchmark-ubuntu1604-intel-64,v8test=v8test/4077/console

```
14:31:09 + rm deps/v8/test/mjsunit/d8-os.js
14:31:09 rm: cannot remove 'deps/v8/test/mjsunit/d8-os.js': No such file or directory
```

The file is now located in `deps/v8/test/mjsunit/d8/d8-os.js`, but I suppose we can stop trying to delete it as it doesn't seem to cause any issues.

**Comment by richardlau** [comment]
Has the file been moved in Node.js 12? If it has we can get rid of the line, otherwise we'll need to keep it around... or I can comment out the line and we see if the CI breaks with earlier release lines.

**Comment by targos** [comment]
It has been moved between Node.js 8 and Node.js 10

**Comment by targos** [comment]
https://github.com/nodejs/node/blob/v8.x/deps/v8/test/mjsunit/d8-os.js
https://github.com/nodejs/node/blob/v10.x/deps/v8/test/mjsunit/d8/d8-os.js

**Comment by richardlau** [comment]
Okay, have deleted the following out of the job config:
```
  # when run under jenkins the d8-os.js test hangs because signals don't set to the process when a os.process times out
  # it works just fine when run from the command line so its not an issue with v8 itself.  I'd like to figure out why
  # it fails under jenkins but so far have not managed to so remove this test before running
  rm deps/v8/test/mjsunit/d8-os.js || true
```
