### ISSUE TITLE
Apple notarizing error during release: "You must first sign the relevant contracts online"

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2685]
@danielleadams reported via IRC/Slack:

```
13:27:01     Error notarizing
13:27:01 
13:27:01 ❗️ Error notarizing:
13:27:01 
13:27:01 1 error occurred:
13:27:01 	* 1 error occurred:
13:27:01 	* You must first sign the relevant contracts online. (1048) (1048)
```

This happened before (#2271), seems like someone with access to the build@ Apple ID (so @mhdawson or @rvagg, I don't think anyone else on @nodejs/build-infra has the 2FA setup). Michael or Rod can you sing the thing to unblock the release? We should figure out broader access to it later.

(I'll try to sign through my account but I doubt it'll work based on Rod's comment on #2271)

**Comment by rvagg** [comment]
womp womp ... yet again they fail to notify us in any way prior to this and just start auto-rejecting our notarizations.

I've logged in and got the red banner and clicked their button:

<img width="1034" alt="Screenshot 2021-06-23 124558" src="https://user-images.githubusercontent.com/495647/123027336-02263600-d421-11eb-9f14-6ae4377c12db.png">

Here's the agreement we're saying yes to if anyone cares to read it:

[Apple_Developer_Program_License_Agreement_T742K2QM52.pdf](https://github.com/nodejs/build/files/6698553/Apple_Developer_Program_License_Agreement_T742K2QM52.pdf)

I've requested a rebuild of the pkg @ https://ci-release.nodejs.org/job/iojs+release/6974/ /cc @danielleadams

**Comment by rvagg** [comment]
got a successful build for v16.4.0 https://ci-release.nodejs.org/job/iojs+release/6974/nodes=osx11-release-pkg/console
