### ISSUE TITLE
#node-build IRC channel

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2687]
The project as a whole appears to be migrating from Freenode: https://github.com/nodejs/TSC/issues/1031
References to #node-build were removed from the core repo in https://github.com/nodejs/node/pull/39047

Our README still references the channel:
> Chat with us! We use IRC: #node-build at Freenode.

We should discuss whether to follow suite. I understand Freenode did a mass channel purge just over a week ago (https://www.devever.net/~hl/freenode_suicide) and all registered channels and nicknames were dropped.

I think our options are:
1. Stay on #node-build on Freenode. The rest of the project is moving/has moved away. 
2. Move the channel to libera.chat. This is where the #node.js channel went. If we moved here it would be good to re-establish the IRC bridge.
3. Move to some other IRC network. I'm not sure why we'd do this over Freenode (status quo) or libera (where the project is moving to).
4. Move off IRC altogether. Options here include:
a. #build on node-js.slack.com. This still exists. This Slack is a free tier Slack so has limited preserved history (is that an issue?).
b. Move to the OpenJS Foundation Slack (openjs-foundation.slack.com). This is a paid tier Slack so preserves history. A number of other working groups (e.g. Release who are probably one of the constituents most likely to want to talk to someone from Build) have a channel in this Slack. It might be possible to use Slack Connect to bridge the channel between openjs-foundation.slack.com and node-js.slack.com so you would not need to be logged into two different Slack workspaces. 
c. Something else (Discord/Gitter/Matrix/etc). Same as 3 -- I'm not sure what the benefits here would be (it would be yet another thing to have to log into).
5. Drop all "realtime" chat and force communication to GitHub issues (maybe enable discussions?).

**Comment by richardlau** [comment]
I personally haven't used Freenode since the bridge to #build on node-js.slack.com was set up -- I'm not even sure if the bridge is still working. Would be good to hear opinions of anyone still using IRC.

**Comment by AshCripps** [comment]
ive personally never once logged into the IRC so im in favour of slack, dont mind either instance but I have set up an alerting channel from our grafana on the open-js slack

**Comment by mhdawson** [comment]
I'm on slack and keep up better there. Have only been able to intermittently keep up on IRC. Long way of saying my preference is slack.

**Comment by ljharb** [comment]
The bridge was working until recently when freenode dropped all nick and channel data.

It seems like 4.b might be the best option, with Slack Connect if someone doesn’t want to join the OpenJS slack workspace, and if someone still doesn’t want to use slack at all then it can be bridged to libera at that time.

**Comment by sxa** [comment]
It seems 4a is the option that we've gravitated towards. I posted a message in the IRC channel a few weeks back saying we were going to stop using it and to ask people to comment on here if they had any concerns, although I don't think any of the current build group were in there. We can aim to have a final discussion on this in next week's WG meeting, so last call for comments :-)

We could look at moving to the OpenJSF slack, but I'd suggest that given the team seem to be using the Node one at the moment, that can be a separate discussion if we feel it's warranted.

**Comment by ljharb** [comment]
Freenode's had a few disruptions since this was posted and the #node-build channel on it has been empty for months. On Libera, there's only 1 other person in it besides me, also for months.

**Comment by sxa** [comment]
Closing as the channel is not going to be ressurected for now, all discussed actions have taken place and all relevant users are now on Slack.

If we choose to move to the foundation slack at some point for the extended history, we can discuss that separately.
