### ISSUE TITLE
Heads up of Security releases July 1st 2021                                        

### ISSUE THREAD

**Issue by danbev** [nodejs/build#2691]
As per security release process this is a heads up that there will be security releases July 1st 2021 and we'll need people from build to lock/unlock ci and to support and build issues we see.

**Comment by richardlau** [comment]
Since I'm doing some of the releases I'll take care of locking/unlocking the CI.

**Comment by richardlau** [comment]
Announced the CI will be locked down from Wednesday morning: https://github.com/orgs/nodejs/teams/collaborators/discussions/124

**Comment by richardlau** [comment]
Security releases are out. I'm currently estimating whether I feel confident enough to update Jenkins to pick up the Jenkins security release https://github.com/nodejs/build/issues/2688 before unlocking.

**Comment by richardlau** [comment]
I've updated Jenkins but not any of the plugins (https://github.com/nodejs/build/issues/2688#issuecomment-872462941).

CI has been unlocked.
