### ISSUE TITLE
Windows Signing Certificate

### ISSUE THREAD

**Issue by mikeal** [nodejs/build#271]
It seems that our Windows build is still using the NodeSource signing cert, I thought we got one for the foundation? Did we just not swap it out yet?

Also, are there any other builds that we haven't been able to migrate to a foundation cert yet?

**Comment by joaocgreis** [comment]
Both the MSI and the EXE of 5.1 are signed by Node.js Foundation. Did we miss something?

**Comment by rvagg** [comment]
I'm pretty sure @joaocgreis reprovisioned the Windows release machines and they only have the Node.js Foundation certs on them now, which installers are you looking at @mikeal?

**Comment by jbergstroem** [comment]
Just following up here. Is there anything else we need to do?

**Comment by rvagg** [comment]
nada
