### ISSUE TITLE
`test-nearform_intel-ubuntu1604-x64-1` and `test-nearform_intel-ubuntu1604-x64-2` offline

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2725]
The two benchmark machines at NearForm are currently disconnected in Jenkins
- https://ci.nodejs.org/computer/test-nearform_intel-ubuntu1604-x64-1/
- https://ci.nodejs.org/computer/test-nearform_intel-ubuntu1604-x64-2/

Trying to ssh into them results in
```
ssh: connect to host 92.51.196.114 port 22: No route to host
```

Anyone know who to contact here? (cc @mcollina @AshCripps )

**Comment by AshCripps** [comment]
ill email our contact at Nearform IT now see if they can figure out whats going on.

**Comment by AshCripps** [comment]
Systems should be back online
