### ISSUE TITLE
Set up new Ampere Altra machines in the build farm to replace older packetnet systems

### ISSUE THREAD

**Issue by sxa** [nodejs/build#2729]
Equinix (formerly packet) are replacing their older aarch64 hardware and consolidating us on new 160-core Ampere Altra systems. This issue will track progress/deployments/miration on the new machines.

My intention is to prototype creating multiple docker containers underneath a base OS of Ubuntu 20.04 (to allow a wider range of OSs to be used) to allow a wider range of testing. Unlike the ThunderX system we had previously these also support the 32-bit armv7 instruction set, so we can also look at running docker containers that could build and test our `armv7l` builds on these systems which could allow us to reduce our reliance on the raspberry pi systems.

(Ref https://github.com/nodejs/build/issues/2708 as the machine that will likely be the first to be decommissioned)

**Comment by sxa** [comment]
Successful test-commit run on two docker images on the machine, however there were issues running the playbooks:
- [The hostname cannot be changed](https://github.com/nodejs/build/blob/fcb12f9d2a72fcb4db7e437b0d95f184e9ac0561/ansible/roles/baselayout/tasks/main.yml#L18)
- [The systemd-timesyncd service](https://github.com/nodejs/build/blob/master/ansible/roles/baselayout/tasks/partials/ntp/systemd.yml) cannot be started (Though I expect having it running on the host will be adequate!)
- `::1` cannot be added to `/etc/hosts` for [ipv6 compat](https://github.com/nodejs/build/blob/fcb12f9d2a72fcb4db7e437b0d95f184e9ac0561/ansible/roles/jenkins-worker/tasks/main.yml#L53)
- On Ubuntu 20.04 there is no packet python-pip, only python-pip3 so [this task fails](https://github.com/nodejs/build/blob/master/ansible/roles/jenkins-worker/tasks/partials/tap2junit/ubuntu.yml)
- We cannot easily start the jenkins agent as service [the task](https://github.com/nodejs/build/blob/fcb12f9d2a72fcb4db7e437b0d95f184e9ac0561/ansible/roles/jenkins-worker/tasks/main.yml#L411) says the service doesnt' exist, so I've initiated them manually via nohup for now.

**Comment by richardlau** [comment]
> * On Ubuntu 20.04 there is no package with the name `python-pip`, only `python-pip3` so [this task fails](https://github.com/nodejs/build/blob/master/ansible/roles/jenkins-worker/tasks/partials/tap2junit/ubuntu.yml)

You could copy `ansible/roles/jenkins-worker/tasks/partials/tap2junit/ubuntu.yml` as `ansible/roles/jenkins-worker/tasks/partials/tap2junit/ubuntu2004.yml` and update the copy.

> * We cannot easily start the jenkins agent as service [the task](https://github.com/nodejs/build/blob/fcb12f9d2a72fcb4db7e437b0d95f184e9ac0561/ansible/roles/jenkins-worker/tasks/main.yml#L411) says the service doesnt' exist, so I've initiated them manually via nohup for now.

If using Docker it might make sense to follow a similar framework to what we do on the x64 containers? See
- https://github.com/nodejs/build/blob/master/ansible/playbooks/jenkins/docker-host.yaml
- https://github.com/nodejs/build/tree/master/ansible/roles/docker

These run the Jenkins agent directly in the containers, see the templates in https://github.com/nodejs/build/tree/master/ansible/roles/docker/templates. The host running the containers gets a service to start the containers.
- https://github.com/nodejs/build/blob/fcb12f9d2a72fcb4db7e437b0d95f184e9ac0561/ansible/roles/docker/tasks/main.yml#L163-L169
- https://github.com/nodejs/build/blob/master/ansible/roles/docker/templates/jenkins.service.j2

**Comment by sxa** [comment]
Yep that will probably be the better option :-)

**Comment by sxa** [comment]
Note: Also required the `--sysctl net.ipv4.ip_unprivileged_port_start=1024` option when starting the container to allow the `privileged-port` tests to pass.

**Comment by rvagg** [comment]
@sxa please try and use or extend the existing docker-host setup we have in Ansible; if you see opportunity for improvement then that's great and of course there'll be some things that are necessarily different for the new environment. What we want to avoid is duplication, doing essentially the same thing but in multiple ways .. we have enough of that with our mixed infra already!
Let me know if you need help grokking what it's doing now.

**Comment by sxa** [comment]
Absolutely @rvagg - this was the first time I'd used the ansible scripts directly myself so I wanted to do some experiments/education within statically generated docker containers and separate jenkins jobs on the system while I had a clean machine to play with before integrating the machine fully sicen they're easy to regenerate. Certainly don't want to add unnecessary complexity.
> there'll be some things that are necessarily different for the new environment

Hopefully not too many :-)

**Comment by sxa** [comment]
@rvagg I've stuck a couple of *DRAFT* PRs in to support creating containers on the new system and am setting them up accordingly as I write this (nothing that can't be undone obviously). We'll have three of these new servers to replace the previous ones. We'll need to look at what to do to replace `release-packetnet-centos7-arm64-1` since I dont' think the systems currently have the option for CentOS7 deployment, and my preference would probably be to carve up the third one in the same way as the first one I'm working on but would be good to have your input on whether you agree with doing that.

**Comment by sxa** [comment]
As of yesterday one of the Ubuntu 16.04 machines has been decomissioned (it had been marked offline for a few weeks): https://github.com/nodejs/build/issues/2708 - the rest were still fully active during the security release.

The following docker images on the first Altra are now live:
- [test-equinix-centos7_container-arm64-1](https://ci.nodejs.org/computer/test-equinix-centos7_container-arm64-1/)
- [test-equinix-ubuntu1804_container-arm64-1](https://ci.nodejs.org/computer/test-equinix-ubuntu1804_container-arm64-1/)
- [test-equinix-ubuntu1804_sharedlibs_container-arm64-1](https://ci.nodejs.org/computer/test-equinix-ubuntu1804_sharedlibs_container-arm64-1/)
- [test-equinix-ubuntu1804_sharedlibs_container-arm64-2](https://ci.nodejs.org/computer/test-equinix-ubuntu1804_sharedlibs_container-arm64-2/)
- [test-equinix-ubuntu1804_sharedlibs_container-arm64-3](https://ci.nodejs.org/computer/test-equinix-ubuntu1804_sharedlibs_container-arm64-3/)
- [test-equinix-ubuntu1804_sharedlibs_container-arm64-3](https://ci.nodejs.org/computer/test-equinix-ubuntu2004_container-arm64-1/)
- [test-equinix-ubuntu2004_sharedlibs_container-arm64-2](https://ci.nodejs.org/computer/test-equinix-ubuntu2004_sharedlibs_container-arm64-2/)
- [test-equinix-ubuntu2004_sharedlibs_container-arm64-3](https://ci.nodejs.org/computer/test-equinix-ubuntu2004_sharedlibs_container-arm64-3/)

The Ubuntu ones have been live for a few days and seem to be working ok, subject to needing the `python-is-python3` package installed to avoid problems with build sof earlier node versions.

The CentOS one has just been made live today after adding the `centos7-arm64-gcc*` labels required to do the compiler selection properly. The PR for the dockerfile used to set these up is at https://github.com/nodejs/build/pull/2738 and while I don't like the way I'm pulling down the gcc6 compiler stuff in there it does work so I propose merging that, then looking at whether we can have a better solution for the future.

I have marked the old CentOS7 boxes offline in jenkins for now to test all runs on the new CentOS7 system.
- https://ci.nodejs.org/computer/test-packetnet-centos7-arm64-1
- https://ci.nodejs.org/computer/test-packetnet-centos7-arm64-2

I've also removed the `ubuntu1604-arm64` label from the job matrix in node-test-commit-arm so we will no longer be testing on the out-of-support Ubuntu 16.04 now that we have 18.04 and 20.04 (We could also add 21.04...) If the CentOS image deployed to day shows no problems I'll look at extended the number of those that we're running, then look at deploying a second Altra.

**Comment by richardlau** [comment]
Is the plan to run anything on the sharedlib containers?

**Comment by sxa** [comment]
The node-test-commit-arm jobs should be able to run on them - the first one I'd set up with the tags was `-3` on both of them. We can also rebalance towards CentOS more on the second one. I was planning to try and run that one with CentOS8 as the host OS instead of Ubuntu just for a mix (and to use the CentOS kernel version to give us more coverage) unless anyone things that's not a good idea

**Comment by mhdawson** [comment]
Just one container for centos7 ? Sounds like we had a couple of machines before?

**Comment by richardlau** [comment]
@mhdawson That would be one container per machine giving us two containers in the test CI (replacing the two existing Packet centos7 machines).

**Comment by mhdawson** [comment]
@richardlau k, got it.

**Comment by sxa** [comment]
Updated the following jobs so they will be ok on the new systems.
- https://ci.nodejs.org/job/libuv-test-commit-linux/
- https://ci.nodejs.org/job/node-stress-single-test/

The libuv job needed some extra prereqs as per https://github.com/nodejs/build/pull/2744
The node-stress-single-tests was fixed to ubuntu 16.04 so I've switched that to run on 20.04.

I'm going to formally decommission the following today:

- https://ci.nodejs.org/computer/test-packetnet-ubuntu1604-arm64-2/
- https://ci.nodejs.org/computer/test-packetnet-centos7-arm64-1/
- https://ci.nodejs.org/computer/test-packetnet-centos7-arm64-2

**Comment by sxa** [comment]
At this point the outstanding actions will be to set up the second Altra for build/test and the extra machine to replace the release ThunderX box.

**Comment by sxa** [comment]
(Splitting off the release machine into a separate issue as shown above)

The second build/test Altra test-equinix-centos8-arm64-1(139.178.85.13) has now been provisioned. Will need to be tested to see how well the dockerhost setup works on CentOS8 but worst case we can switch it to ubuntu 20.04 like the other one :-)

**Comment by sxa** [comment]
Release machine now decomissioned:
- release-packetnet-centos7-arm64-1

**Comment by sxa** [comment]
I've been experimenting today with one of the other things I mentioend in the description of this issue - running armv7l OS images in containers on these new hosts. We've done this successfully at the Adoptium project and it's looking promising here so far too: https://github.com/nodejs/build/issues/2775

**Comment by sxa** [comment]
arm32 container live and included in the main [node-test-commit-arm](https://ci.nodejs.org/job/node-test-commit-arm/) job under the `ubuntu2004-armv7l` configuration. We will probably wish to expand the distribution list included so that we can run on a distribution that supports running jobs against node 12.x (Ref [this PR](https://github.com/nodejs/build/pull/2776))

**Comment by richardlau** [comment]
I've set up the second altra (https://github.com/nodejs/build/issues/2820 and https://github.com/nodejs/build/pull/2828).

**Comment by richardlau** [comment]
@sxa We're currently setting up RHEL 8 CI instances to replace CentOS 7 for Node.js. Any thoughts on how we should handle the release machine for ARM 64? We'll need to be able to keep building Node.js 12/14/16 on CentOS 7 but also build Node.js 18 onwards on RHEL 8.

We have hit one issue in V8 canary (https://github.com/nodejs/node-v8/issues/220) that suggested an incompatibility with the kernel (too old) in CentOS 7 which I think means we wouldn't be able to run a RHEL 8 container on top of CentOS 7 as it would still be using the older kernel.
