### ISSUE TITLE
Lockdown of CI for security releases

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2735]
Locking down CI for the next 24 hours or so for the security release.

/cc @MylesBorins

**Comment by Trott** [comment]
Here's the before screenshot:

![image](https://user-images.githubusercontent.com/718899/131372873-fc2a4689-f300-4db9-841f-5043f1ad9700.png)


TODO: Update https://github.com/nodejs/build/blob/3f5e9887c043caae902456b7f3624e5ec878510c/doc/jenkins-guide.md#security-releases with that image.

**Comment by Trott** [comment]
And the after screenshot:

![image](https://user-images.githubusercontent.com/718899/131373290-b0339d86-4365-4898-afd6-a824cd99bac3.png)

**Comment by Trott** [comment]
OK, lockdown procedure complete.  Only Jenkins Admins, Releasers, and Security Triage groups should have access now. (Thanks, @richardlau, for pointing out the documentation to do this!)

**Comment by MylesBorins** [comment]
CI is back to normal... go test ya'll
