### ISSUE TITLE
nodejs.org LB flapping

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#2742]
_Updated with task list from below:_

* [ ] Upgrade the machines beyond 16.04 - OR convince Ubuntu to give us an org subscription to ESM (I've sent an email to the best contacts I have, but they're a bit detached from anything related to ESM management)
* [ ] Upsize the disk on www-backup
* [ ] Change the benchmark rsync to a systemd timer, or remove it entirely if it's no longer being used
* [ ] Fix configuration of backup-www to add coverage.nodejs.org (and anything else missing) as per #2747

----

_Original:_

On the day of the security releases this week I was bombarded with LB flapping notifications from Cloudflare. It's happening again today. This is not uncommon and usually resolves in a short period. It seems that the main web server hits some threshold and is unable to respond enough to the edge nodes so it flaps over to the backup web server. This might need investigation, although I'm not sure exactly what to look for as I went through trying to figure out this DigitalOcean threshold problem before we disabled the pass-through for downloads on Cloudflare (when we really had exceeded the threshold).

At a minimum, we probably should tend to the backup server and make sure it's healthy and that the flapping isn't going to have negative consequences. I've not touched it in a while, it probably needs updates, make sure that disks aren't full, make sure that files are properly in sync and staying in sync.

Recent LB notifications / logs / alerts should be accessible in Cloudflare for our account for those with access.

**Comment by AshCripps** [comment]
Is the unecrypted server the backup in this case? because its looking _very_ full

<img width="793" alt="image" src="https://user-images.githubusercontent.com/26796102/131812354-7c9be73e-d5f3-45b3-8327-c1ff41b9cfc5.png">

**Comment by rvagg** [comment]
Yeah, unencrypted is the backup .. we have 19G space left and need to come up with a strategy to deal with that ASAP. A disk bump is the obvious choice, but I don't recall how difficult that is in the Joyent infra.

I think I know what the main problem is, it's the darn benchmark rsync job, I just killed 180 processes that look like this:

```
nodejs    2496  0.1  0.1  48448 27872 ?        S    04:01   0:23 rsync -aqz --delete benchmark:coverage-out/out/ /home/www/coverage/
nodejs    2497  0.0  0.0  45052  5360 ?        S    04:01   0:00 ssh benchmark rsync --server --sender -logDtprze.iLsfx . coverage-out/out/
nodejs    2498  0.2  0.0  64896 11384 ?        S    04:01   0:35 rsync -aqz --delete benchmark:coverage-out/out/ /home/www/coverage/
nodejs    2516  0.1  0.1  48512 27908 ?        S    04:02   0:22 rsync -aqz --delete benchmark:coverage-out/out/ /home/www/coverage/
nodejs    2517  0.0  0.0  45200  5312 ?        S    04:02   0:00 ssh benchmark rsync --server --sender -logDtprze.iLsfx . coverage-out/out/
nodejs    2518  0.2  0.0  64892 13800 ?        S    04:02   0:33 rsync -aqz --delete benchmark:coverage-out/out/ /home/www/coverage/
nodejs    2715  0.1  0.1  52600 31016 ?        S    04:03   0:20 rsync -aqz --delete benchmark:coverage-out/out/ /home/www/coverage/
```

We need to convert that from a crontab job to a systemd timer so it won't double-up.. Do we still need this job though, @mhdawson do you know?

I've just installed system updates on both www and www-backup and rebooted both machines.

So, some items to do that are not so easy!

* [ ] Upgrade the machines beyond 16.04 - OR convince Ubuntu to give us an org subscription to ESM (I've sent an email to the best contacts I have, but they're a bit detached from anything related to ESM management)
* [ ] Upsize the disk on www-backup
* [ ] Change the benchmark rsync to a systemd timer, or remove it entirely if it's no longer being used

**Comment by mhdawson** [comment]
@rvagg benchmarks are no more, but the rsync is still needed for the code coverage data.

@richardlau if I remember correctly I think you did a cleanup a while back, we may want to schedule doing this on a more regular basis. How long ago did you do the last one if you can remember?

**Comment by mhdawson** [comment]
I terms of the coverage data the earliest entry is 26/5/21 so seems like we may be able to handle a only couple of months of data before the rsync starts to back up.  Maybe we should plan a clean up every 2 months and/or try to automate the cleanup.

**Comment by richardlau** [comment]
I did a cleanup at the end of April: https://github.com/nodejs/build/issues/2636#issuecomment-829724392
Automation sounds like the way to go. I can take a look at that next week.

**Comment by rvagg** [comment]
Flapping still occurring on a regular basis, more regular than it has previously. We've either hit some new threshold or we have a new behaviour that we don't yet have an explanation for.

**Comment by ljharb** [comment]
This might be causing consistent timeouts for this job: https://github.com/ljharb/travis-ci/runs/3517852175?check_suite_focus=true

**Comment by richardlau** [comment]
I'm currently cleaning up the coverage data.

**Comment by richardlau** [comment]
I have run the cleanup scripts for the coverage data which should temporarily fix the rsyncs backing up into each other. I'll look at what we'd need to do to convert the crontab to a systemd timer. 

Disk space on unencrypted is still an issue you can see on the disk usage graph the effect of the coverage data cleanup but this is only a tiny fraction of the space usage on unencrypted:
![image](https://user-images.githubusercontent.com/5445507/132259079-f7b16e58-ade8-44c5-9d79-0da2c74068f4.png)

<details>
<summary>Disk space usage details</summary>

```
root@623f2056-2097-cfb9-a604-83918ab3ca0c:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/zfsds0     2.5T  2.5T   16G 100% /
/dev/zfsds0     2.5T  2.5T   16G 100% /checkpoints/bbennett-migr-s1
/dev/zfsds0     2.5T  2.5T   16G 100% /checkpoints/bbennett-migr-s2
/dev/zfsds0     2.5T  2.5T   16G 100% /checkpoints/bbennett-migr-s3
/dev/zfsds0     2.5T  2.5T   16G 100% /checkpoints/bbennett-migr-s4
/dev/zfsds0     2.5T  2.5T   16G 100% /checkpoints/bbennett-migr-s5
devtmpfs         98G     0   98G   0% /dev
tmpfs            98G  4.0K   98G   1% /dev/shm
tmpfs            98G   81M   98G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            98G  4.0K   98G   1% /sys/fs/cgroup
cgroup           98G     0   98G   0% /sys/fs/cgroup/systemd
/native/usr     433M  391M   43M  91% /native/usr
root@623f2056-2097-cfb9-a604-83918ab3ca0c:~# du -hs /home/*
2.5T    /home/dist
784M    /home/www
root@623f2056-2097-cfb9-a604-83918ab3ca0c:~#
```

Coverage data lives in `/home/www`:
```
root@623f2056-2097-cfb9-a604-83918ab3ca0c:~# du -hs /home/www/*
1.0K    /home/www/benchmarking
2.0M    /home/www/benchmarking-old
131M    /home/www/coverage
430M    /home/www/github
625K    /home/www/iojs
221M    /home/www/nodejs
root@623f2056-2097-cfb9-a604-83918ab3ca0c:~#
```

`/home/dist` is the downloads:
```
root@623f2056-2097-cfb9-a604-83918ab3ca0c:~# du -hs /home/dist/*
30G     /home/dist/iojs
1.6G    /home/dist/metrics-notravis
2.4T    /home/dist/nodejs
2.0K    /home/dist/www
root@623f2056-2097-cfb9-a604-83918ab3ca0c:~# du -hs /home/dist/nodejs/*
139G    /home/dist/nodejs/chakracore-nightly
766M    /home/dist/nodejs/chakracore-rc
4.3G    /home/dist/nodejs/chakracore-release
18M     /home/dist/nodejs/docs
512     /home/dist/nodejs/next-nightly
1.4T    /home/dist/nodejs/nightly
117G    /home/dist/nodejs/rc
214G    /home/dist/nodejs/release
71G     /home/dist/nodejs/test
470G    /home/dist/nodejs/v8-canary
root@623f2056-2097-cfb9-a604-83918ab3ca0c:~#
```

</details>

**Comment by richardlau** [comment]
Oh ouch, I've just spotted an issue with our crontab:
```
* */4   * * *   nodejs  /home/nodejs/sync-benchmarking.sh
```
That's every minute for each fourth hour (😱), not the presumably intended once every four hours. I'm going to change it to 
```
0 */4   * * *   nodejs  /home/nodejs/sync-benchmarking.sh
```

**Comment by richardlau** [comment]
Edited the crontab and also documented in https://github.com/nodejs/build/pull/2750.

**Comment by rvagg** [comment]
Still flapping.

I've pulled up the task list to the top of this issue, anyone else can feel free to edit that. I've added the config problem noted in #2747 as a TODO. I used some existing Canonical contacts to find a new person that I had a chat with yesterday regarding Ubuntu ESM and the good news is that they're very interested in supporting us. I just need to get some additional details to them and we should be able to get these servers, and any others stuck on 16.04, onto ESM. Will keep everyone informed of progress on that front.

**Comment by rvagg** [comment]
Here's 7 day analytics from DO for the server:

<img width="977" alt="Screenshot 2021-09-07 at 11 25 30 am" src="https://user-images.githubusercontent.com/495647/132270523-ff58f69c-0f76-4b0e-b4cb-615a10ce4c9e.png">
<img width="977" alt="Screenshot 2021-09-07 at 11 25 39 am" src="https://user-images.githubusercontent.com/495647/132270522-9c39ea86-0c93-4044-8a86-339016572dc1.png">
<img width="977" alt="Screenshot 2021-09-07 at 11 25 48 am" src="https://user-images.githubusercontent.com/495647/132270518-1f5b52cb-6627-4eba-b222-e8296ec27f98.png">

**Comment by rvagg** [comment]
Here's the LB analytics for Sept. If someone wants to do a correspondence analysis of these two sources of data that might suggest next steps.

<img width="647" alt="Screenshot 2021-09-07 at 11 31 13 am" src="https://user-images.githubusercontent.com/495647/132270893-681f8e41-c062-4cb4-bb13-8b279466e104.png">
<img width="644" alt="Screenshot 2021-09-07 at 11 31 28 am" src="https://user-images.githubusercontent.com/495647/132270902-7480f2a6-a701-4054-b678-c021d877b546.png">
<img width="646" alt="Screenshot 2021-09-07 at 11 31 43 am" src="https://user-images.githubusercontent.com/495647/132270906-155bbb94-335f-4a03-9c3c-5654f6fc792c.png">
<img width="644" alt="Screenshot 2021-09-07 at 11 32 22 am" src="https://user-images.githubusercontent.com/495647/132270911-b99dcf83-8a5d-4a0c-b491-420188df420e.png">

**Comment by rvagg** [comment]
Regarding the names above - I don't know where the names "main" and "digitalocean" derive from, they're not in our load balance config, perhaps they're adjacent somewhere or remnants of an older configuration that I can't see through the UI. _Or_ it might just be how cloudflare presents a parent loadbalancer (?? although it's called "nodejs.org" in our config). The ones ones of primary concern are "server1" within "DO". Our config has "DO" and "Joyent" and each of those has a "server1" origin. So "server1" in "DO" is the machine we're discussing here and you can see it flipping in and out of health.

**Comment by rvagg** [comment]
Figured out "main" and "digitalocean" - it's a pool that's configured but not used, I think we used it prior to the current config we had but obviously you have to delete pools as a separate action, so I've done that now.

I've made the LB monitors a tiny bit more lax in case this is just a load thing that we can weather.

Was

<img width="1091" alt="Screenshot 2021-09-07 at 11 55 10 am" src="https://user-images.githubusercontent.com/495647/132272698-11482726-2b36-4f10-bbb3-121eb79a2dfb.png">

Now

<img width="1069" alt="Screenshot 2021-09-07 at 11 56 47 am" src="https://user-images.githubusercontent.com/495647/132272656-e077dc69-b7a2-4bcd-ab42-77b1d72e7fdb.png">

**Comment by rvagg** [comment]
Some additional notes:

Since I've just got a new batch of notifications and have started doing a live log follow, is that a significant amount of our traffic is from Artifactory instances located all over the world, trying to fetch npm packages from /dist/.

Perhaps jFrog have shipped a version, or someone has documented a config, that thinks it can get npm packages direct from our server - note that this is bypassing Cloudflare, they're using our IP address or the DNS name we use for direct connections. Lots and lots of 404s, but combined with the constant bombardment from Cloudflare Health from each of their edge nodes combined with this it scrolls pretty fast. Maybe we should try and reach out to them, does anyone have an active jFrog contact? I could go fishing for some older ones, I think I even have the CEO but might not pull that one yet.

---

Also, while writing the above, we had another timeout. nginx logs go dead as Cloudflare decides it's lost, which it's not, and it doesn't even seem to be able to contact it. Trying to contact it directly via HTTP resulted in a delay, so it does appear to be related to network connectivity for nginx - even though I was active and had no trouble interacting via ssh.. very weird.

And another interesting pice of data: I've got 3 batches of notifications in my inbox for now, one at 11.30 (my time), one at 11:45/6, one at 12:01. Sounds like a 15 minute timer, eh? We have two crontab jobs running at these intervals, the rsync one that @richardlau just fixed up, and the old metrics "download-counts.sh" runner that's still trying to build metrics from nginx logs which I think we should be able to disable.

This also in `dmesg` (grepping for `rsync` after I noticed it in there):

```
[77274.415464] INFO: task rsync:3550 blocked for more than 120 seconds.
[77274.415565] rsync           D ffff8800a0d77c58     0  3550   2557 0x00000000
[77274.415658] INFO: task rsync:17131 blocked for more than 120 seconds.
[77274.415726] rsync           D ffff8800d3eefc58     0 17131  17129 0x00000000
[77274.415760] INFO: task rsync:17182 blocked for more than 120 seconds.
[77274.415813] rsync           D ffff88003bde7c58     0 17182  17176 0x00000000
[77274.415846] INFO: task rsync:17404 blocked for more than 120 seconds.
[77274.415897] rsync           D ffff880056283c58     0 17404  17400 0x00000000
[77274.415933] INFO: task rsync:17509 blocked for more than 120 seconds.
[77274.415985] rsync           D ffff880271687c58     0 17509  17505 0x00000000
[77274.416021] INFO: task rsync:17565 blocked for more than 120 seconds.
[77274.416102] rsync           D ffff8800aecd3c58     0 17565  17561 0x00000000
[77274.416159] INFO: task rsync:17740 blocked for more than 120 seconds.
[77274.416239] rsync           D ffff8800d044bc58     0 17740  17735 0x00000000
[77274.416282] INFO: task rsync:17789 blocked for more than 120 seconds.
[77274.416347] rsync           D ffff8800116cfc58     0 17789  17785 0x00000000
[77274.416383] INFO: task rsync:18041 blocked for more than 120 seconds.
[77274.416436] rsync           D ffff88004ecb3c58     0 18041  18035 0x00000000
[77274.416468] INFO: task rsync:18092 blocked for more than 120 seconds.
[77274.416521] rsync           D ffff880051513c58     0 18092  18088 0x00000000
```

Each one of these has a whole call trace attached too:

```
[77274.415464] INFO: task rsync:3550 blocked for more than 120 seconds.
[77274.415507]       Not tainted 4.4.0-210-generic #242-Ubuntu
[77274.415534] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[77274.415565] rsync           D ffff8800a0d77c58     0  3550   2557 0x00000000
[77274.415570]  ffff8800a0d77c58 2f2f2f2f2f2f2f2f ffff88040d789c80 ffff8804064d1c80
[77274.415573]  ffff8800a0d78000 ffff880293c7f7b4 ffff8804064d1c80 00000000ffffffff
[77274.415575]  ffff880293c7f7b8 ffff8800a0d77c70 ffffffff81867065 ffff880293c7f7b0
[77274.415578] Call Trace:
[77274.415605]  [<ffffffff81867065>] schedule+0x35/0x80
[77274.415609]  [<ffffffff818673be>] schedule_preempt_disabled+0xe/0x10
[77274.415612]  [<ffffffff81869257>] __mutex_lock_slowpath+0xb7/0x130
[77274.415615]  [<ffffffff818692ef>] mutex_lock+0x1f/0x30
[77274.415625]  [<ffffffff8122adfa>] path_openat+0x51a/0x1360
[77274.415628]  [<ffffffff8122d811>] do_filp_open+0x91/0x100
[77274.415637]  [<ffffffff81221fd3>] ? cp_new_stat+0x153/0x180
[77274.415644]  [<ffffffff8123b5c7>] ? __alloc_fd+0xc7/0x190
[77274.415648]  [<ffffffff8121b998>] do_sys_open+0x138/0x2a0
[77274.415652]  [<ffffffff8121bb1e>] SyS_open+0x1e/0x20
[77274.415654]  [<ffffffff8186bb5b>] entry_SYSCALL_64_fastpath+0x22/0xd0
```

Currently scratching my head on this one, but maybe getting closer.
