### ISSUE TITLE
going to coverage.nodejs.org loads the nodejs.org website and not the coverage stats

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2747]
¯\\_(ツ)_/¯

**Comment by rvagg** [comment]
I suspect this could be #2742 related, our backup-www may not have that server name configured to properly serve that content. It's currently working for me but I have a pile of emails from CF telling me about our LB switching back and forth.

Immediate fix would be to take care of backup-www and make sure it has what it needs. But we have some other larger problems than that to deal with here (including backup-www reaching critical disk level which coverage data may push further than we're comfortable with!).

**Comment by Trott** [comment]
It's working for me now too, so I guess I'll close this for now, as there are other issues to tackle. Thanks!
