### ISSUE TITLE
`node.exe` processes blocking some Windows hosts

### ISSUE THREAD

**Issue by targos** [nodejs/build#2748]
Example: https://ci.nodejs.org/job/node-test-binary-windows-native-suites/10227/nodes=win2012r2-vs2015-COMPILED_BY-vs2019-x86/console
```
18:06:40 C:\workspace\node-test-binary-windows-native-suites>taskkill /t /f /fi "IMAGENAME eq node.exe" 
18:06:40 ERROR: The process with PID 3460 (child process of PID 3004) could not be terminated.
18:06:40 Reason: There is no running instance of the task.
```

**Comment by GeoffreyBooth** [comment]
Another example: https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2012r2-vs2015-COMPILED_BY-vs2019-x86/10236/console

**Comment by targos** [comment]
@nodejs/build-infra

**Comment by gengjiawen** [comment]
Another https://ci.nodejs.org/job/node-test-binary-windows-native-suites/10242/nodes=win2012r2-vs2015-COMPILED_BY-vs2019-x86/console

**Comment by richardlau** [comment]
Failures looks to be happening on `test-azure_msft-win10_vcbt2015-x64-2`. I've force rebooted it via https://ci.nodejs.org/view/All/job/windows-update-reboot/ (https://github.com/nodejs/build/blob/master/doc/jenkins-guide.md#windows).

**Comment by richardlau** [comment]
`test-rackspace-win2012r2_vs2015-x64-1` as well (also now force rebooted).

**Comment by richardlau** [comment]
We've now had eight passing https://ci.nodejs.org/job/node-test-binary-windows-native-suites/ runs in a row so I'm going to close this as now resolved.
