### ISSUE TITLE
CI visibility for outsiders

### ISSUE THREAD

**Issue by saghul** [nodejs/build#275]
Looks like something has changed and users can no longer see the result of a CI run (at least for the libuv jobs). Is this intentional? Can we make them plublicly visible? Thanks!

**Comment by bnoordhuis** [comment]
It was made private to test the security release.  It should be public again though.

**Comment by saghul** [comment]
Oh, I didn't know that. Thanks for the heads up!

**Comment by jbergstroem** [comment]
Yep, set back to public as of ~12 hours ago.
