### ISSUE TITLE
gcc 8.3 on SmartOS

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2757]
My attempt to get gcc8 on the SmartOS 18 hosts (https://github.com/nodejs/build/pull/2754) to unblock moving Node.js to C++17 (https://github.com/nodejs/node/pull/38807) hasn't worked -- Node.js builds (current master) crash running `torque`:
e.g. https://ci.nodejs.org/job/node-test-commit-smartos/40445/
```
11:26:44 make[2]: *** [tools/v8_gypfiles/run_torque.target.mk:17: b9fe59ad2f44d0ae02d580e48d6c8b810c7b326f.intermediate] Segmentation Fault (core dumped)
```

I've opened a PR to revert: https://github.com/nodejs/build/pull/2756

It looks like the latest version of gcc available (`pkgin search gcc`) on the SmartOS 18 hosts is gcc 8.2, which is below the baseline required compiler for Node.js 16 (gcc 8.3). `pkgin update` tells us we're on `2018Q4`:
```
[root@d894f3c6-d09a-c9df-d7ae-b6f613d9b413 ~]# pkgin update
processing remote summary (https://pkgsrc.joyent.com/packages/SmartOS/2018Q4/x86_64/All)...
database for https://pkgsrc.joyent.com/packages/SmartOS/2018Q4/x86_64/All is up-to-date
[root@d894f3c6-d09a-c9df-d7ae-b6f613d9b413 ~]#
```
I found https://github.com/nodejs/build/issues/222 as a past issue referring to the package database so I don't know if it's something we'd ever change (vs. reprovisioning). 

I will readily admit that this is now on the limit of my knowledge about SmartOS.

**Comment by bahamat** [comment]
OK, so our 18.4 image has gcc7 a newer gcc is non-trivial due to the way `GCC_REQD` works. Best recommendation at this point is to move builds to 19.4, which has gcc8.3.

If you need help standing up a 19.4 image, I can be available for that.

**Comment by richardlau** [comment]
Assuming we need to work within the existing allocation of machines for SmartOS, we should probably keep the existing smartos18 hosts so as to not disturb Node.js 12 (where we're still building release binaries) but the smartos17 hosts could be replaced now that Node.js 10 is End-of-Life. 
https://github.com/nodejs/build/blob/61b074e950a04fc6587cacb614e2fbf032bdf204/jenkins/scripts/VersionSelectorScript.groovy#L88-L92

Is replacing/updating from 17->19 feasible? Can it be done from a root ssh session on the existing hosts? I don't think I have access to anything other than being able to ssh into the machines -- the "figure out how we can reboot/manage the new machines (ie is there a management system we'll have access to)" task in https://github.com/nodejs/build/issues/2552 isn't checked off.

**Comment by richardlau** [comment]
We've migrated the smartos17 hosts to smartos19 and I've opened https://github.com/nodejs/build/pull/2771 for corresponding Ansible changes. Unfortunately builds are crashing on this set up with gcc8 as well:

- Node.js master crashes when running `torque`: https://ci.nodejs.org/job/node-test-commit-smartos-richardlau/12/nodes=smartos19-64/console
```
16:36:59 make[2]: *** [tools/v8_gypfiles/run_torque.target.mk:17: 0419ce9f59fa87936c08822450bc51ccc1c6ab81.intermediate] Segmentation Fault (core dumped)
16:37:00 make[2]: *** Deleting file '0419ce9f59fa87936c08822450bc51ccc1c6ab81.intermediate'
16:37:00 make[2]: *** Waiting for unfinished jobs....
16:37:00 rm eebebf194a80591c355217ab13918466ac5ef6e3.intermediate 5c5ce6448da9d006dfa693a4b049927cbb5e2f06.intermediate
16:37:04 make[1]: *** [Makefile:110: node] Error 2
16:37:04 make: *** [Makefile:529: build-ci] Error 2
```
- Node.js 14 crashes building addons: https://ci.nodejs.org/job/node-test-commit-smartos-richardlau/5/nodes=smartos19-64/console
```
16:45:10 make[1]: *** [Makefile:444: benchmark/napi/.buildstamp] Segmentation Fault (core dumped)
16:45:10 make: *** [Makefile:540: run-ci] Error 2
16:45:10 Build step 'Execute shell' marked build as failure
```

In both cases we're getting relocation warnings which we don't see on smartos18 with gcc7.
e.g. 
```
16:36:53 ld: warning: relocation warning: R_AMD64_32: file /home/iojs/build/workspace/node-test-commit-smartos-richardlau/nodes/smartos19-64/out/Release/obj.target/tools/v8_gypfiles/libtorque_base.a(csa-generator.o): section [2].rela.text: symbol .gnu.linkonce.r._ZN2v88internal6torque19TorqueCodeGenerator20DefinitionToVariableB5cxx11ERKNS1_18DefinitionLocationE.str1.1 (section): relocation against discarded COMDAT section [75].gnu.linkonce.r._ZN2v88internal6torque19TorqueCodeGenerator20DefinitionToVariableB5cxx11ERKNS1_18DefinitionLocationE.str1.1: symbol not found, relocation ignored
```

**Comment by bahamat** [comment]
Can you try gcc9?

**Comment by richardlau** [comment]
I don't see gcc9 in the list of available packages (https://pkgsrc.joyent.com/packages/SmartOS/2019Q4/x86_64/All)

**Comment by richardlau** [comment]
We've updated one of the machines to Q42020 and trying with gcc9: https://ci.nodejs.org/job/node-test-commit-smartos-richardlau/14/nodes=smartos20-64/console

**Comment by richardlau** [comment]
Builds look good with gcc9 on Q42020. Waiting on @bahamat to update the remaining two hosts to the same level and then I'll update/close out https://github.com/nodejs/build/pull/2771.

**Comment by richardlau** [comment]
(Previously smartos17) Machines have been updated to smartos 20.04.0 with gcc9.
