### ISSUE TITLE
Node.js Coverity project membership

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2765]
Earlier this month I fixed (https://github.com/nodejs/build/issues/2183) the [node-daily-coverity](https://ci.nodejs.org/job/node-daily-coverity/) job which runs static analysis on the Node.js core project. In order to do that I had to be added as a "maintainer/owner" of the Node.js project on Coverity (joining the existing admins, @jbergstroem and @rvagg ) to be able to download the Coverity build tool (needed for https://github.com/nodejs/build/blob/master/ansible/MANUAL_STEPS.md#jenkins-workspace). I've opened this issue to discuss how we want to manage the Node.js project on Coverity, namely:

1) Should all @nodejs/build-infra members be able to download the build tool (which may mean they would have to be owners) so they can follow the steps described in https://github.com/nodejs/build/blob/master/ansible/MANUAL_STEPS.md#jenkins-workspace if needed? FWIW before I was added as an owner I checked with @mhdawson and he doesn't currently have access to the build tool download.

2) Do we have a policy on who should be granted "contributor/member" membership of the Coverity Node.js project (to be able to view the defects, etc.)? Currently there are 3 pending applications (1 current TSC and 2 TSC emeriti) all from 2017:

![image](https://user-images.githubusercontent.com/5445507/134042116-da5a28b1-255e-4d2d-8eff-b70b6b0b3e34.png)

**Comment by mhdawson** [comment]
I think at least the build-infra should be owners and I'd be ok with more people being owners as well. I don't think it exposes too much (let me know if I'm wrong on that) and we could possibly have any build team member who is interested added as an owner.

**Comment by jbergstroem** [comment]
> I don't think it exposes too much (let me know if I'm wrong on that) and we could possibly have any build team member who is interested added as an owner.

Nothing that other nodejs build members wouldn't have access to afaik.

**Comment by richardlau** [comment]
I'd be okay with anyone in the TSC being an owner as well. We've had a couple of issues raised from @Trott (https://github.com/nodejs/build/issues/2827, https://github.com/nodejs/build/issues/2825) relating to the collaborator offboarding process and it would be sensible to ease the process for whoever is likely to be doing offboarding.

**Comment by Trott** [comment]
> it would be sensible to ease the process for whoever is likely to be doing offboarding.

I'm almost always the person that does offboarding, so it's probably OK to have it be just me for the moment. But we could decide to make this part of the onboarding/offboarding for TSC members and have all TSC folks have access.

**Comment by Trott** [comment]
I think we can close this (but re-open it if you want to talk more about it or make more changes, @richardlau!). I'm one of the admins now, and I just did a housecleaning. Membership is now 13 collaborators + 2 members of the build-infra group.
