### ISSUE TITLE
node-test-commit-osx-arm reports wrong check to github

### ISSUE THREAD

**Issue by targos** [nodejs/build#2766]
See in https://github.com/nodejs/node/pull/40178

The failure for [`node-test-commit-osx-arm`](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/2896/) is reported as `node-test-commit-osx` instead.

**Comment by richardlau** [comment]
I've added a `-arm` suffix onto the identifier passed to the GitHub bot for this job.

Audit link: https://github.com/nodejs/jenkins-config-test/commit/6cca92311b2bd95ef7adc3497f5d1b0b181628fd

**Comment by richardlau** [comment]
![image](https://user-images.githubusercontent.com/5445507/134673795-80fa4865-5998-4efb-8d4c-83c54fcb8f06.png)
