### ISSUE TITLE
Update freeBSD machines

### ISSUE THREAD

**Issue by AshCripps** [nodejs/build#2768]
https://github.com/nodejs/node/pull/40179 wants to update the minimum support version past what we have in CI.

Seeing as the version we have goes EOL at the end of the month and freeBSD is an experimental platform we should be able to just replace the v11 machines with v12.2

Any volunteers?

**Comment by richardlau** [comment]
I've taken the old `test-digitalocean-freebsd11-x64-1` offline in Jenkins and reimaged it to FreeBSD 12 and am in the process of updating/running our Ansible scripts against it.
