### ISSUE TITLE
Windows CI consistent failures

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2782]
A few Windows tests seem to have started failing consistently on CI in the last 48 hours or so. I tried to do a bisect between the last good node-daily-master run and the first bad one, but now re-running the last good one results in a failure. So I suspect/hope the issue is with the Jenkins hosts and they just need to be rebooted or a workspace needs to be cleared or something like that.

Here's node-daily-master on 4bd8e0efa05112d29de241142ccca3c2dcfb8175 failing on Windows today in the same way CI has been failing in Windows for the last few days. https://ci.nodejs.org/job/node-test-commit/49087/

And here it is succeeding on the same commit a couple days ago. https://ci.nodejs.org/job/node-test-commit/49046/

**Comment by Trott** [comment]
Running git-clean-windows: https://ci.nodejs.org/view/All/job/git-clean-windows/234/

**Comment by richardlau** [comment]
ouch, looks like https://ci.nodejs.org/view/All/job/windows-update-reboot/1744/ updated the machines to Python 3.
https://ci.nodejs.org/job/node-compile-windows/42300/nodes=win-vs2019/
```
18:33:41 > python configure  --with-ltcg "--download=all" --with-intl=full-icu --dest-cpu=x64 --verbose 
18:33:41 Please use python3.9 or python3.8 or python3.7 or python3.6.
18:33:41 Node.js configure: Found Python 3.10.0...
```
We might need to expedite https://github.com/nodejs/node/pull/40296 if there's no easy way to roll back to 3.9 (cc @joaocgreis ) -- I've resumed the CI for that and the Windows job is https://ci.nodejs.org/job/node-test-commit-windows-fanned/44743/

**Comment by Trott** [comment]
> ouch, looks like https://ci.nodejs.org/view/All/job/windows-update-reboot/1744/ updated the machines to Python 3.10:

😱

> We might need to expedite nodejs/node#40296 if there's no easy way to roll back to 3.9 (cc @joaocgreis ) -- I've resumed the CI for that and the Windows job is https://ci.nodejs.org/job/node-test-commit-windows-fanned/44743/

Well, the Windows tests that were timing out are `passing` there, so that's progress!
