### ISSUE TITLE
Release Node.js on the Microsoft Store?

### ISSUE THREAD

**Issue by targos** [nodejs/build#2790]
The new Microsoft Store now supports a lot of different kinds of apps. I don't know if it would be a good idea to distribute Node.js in it, but it seems worth having the discussion.

https://blogs.windows.com/windowsexperience/2021/06/24/building-a-new-open-microsoft-store-on-windows-11/
https://blogs.windows.com/windowsdeveloper/2021/09/28/microsoft-store-more-apps-more-open/
https://developer.microsoft.com/en-us/microsoft-store/

**Comment by targos** [comment]
> Do we have enough volunteers to keep the process working?

We can look for volunteers if we agree on it.

**Comment by richardlau** [comment]
> > Does it need to be via build? For example, we are not involved with the winget Node.js packages.
> 
> Maybe not. I assumed that we would have to sign the app using an account owned by build.

I guess the question there is whether we can reuse the msi we already build/sign or would need an additional signing step.
