### ISSUE TITLE
AWX template for rebuild/refresh the website

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2792]
Following the [Build Helper](https://github.com/nodejs/build/blob/master/doc/build-helper.md) work with AWX, I'd like to suggest a template that would force rebuild/refresh the website. 

Having a button to click to force rebuild would help when we need to propagate a post, and occasionally we hit issues where the refresh/rebuild hasn't worked. Recently when I hit an issue I managed to resend the web hook payload, but that requires elevated permissions on the nodejs/nodejs.org repository.

**Comment by mhdawson** [comment]
This would be really useful, great suggestion!
