### ISSUE TITLE
Consistent failures on Windows 10 CI machines

### ISSUE THREAD

**Issue by mscdex** [nodejs/build#2794]
https://ci.nodejs.org/job/node-test-binary-windows-js-suites/11689/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/console
https://ci.nodejs.org/job/node-test-binary-windows-native-suites/10631/nodes=win10-vcbt2015-COMPILED_BY-vs2019/console

Those same machines also seem to not have nasm installed on them.

The [win2012 machine has nasm installed and actually ran the tests](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/11689/RUN_SUBSET=3,nodes=win2012r2-COMPILED_BY-vs2019-x86/console) for the same PR.

**Comment by richardlau** [comment]
test-azure_msft-win10_vcbt2015-x64-1  
https://ci.nodejs.org/job/windows-update-reboot/label=test-azure_msft-win10_vcbt2015-x64-1/1757/
https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2019/11694/console
