### ISSUE TITLE
Add v5.x to REBASE_ONTO dropdown

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#280]
[Build with Parameters](https://ci.nodejs.org/job/node-test-pull-request/build?delay=0sec) has no option for v5.x in the REBASE_ONTO dropdown.

[Note to self: https://github.com/nodejs/node/pull/4231]

**Comment by rvagg** [comment]
@orangemocha or @joaocgreis can either of you take this one please?

**Comment by orangemocha** [comment]
done!
