### ISSUE TITLE
Jenkins configuration change for node-test-binary-windows-js-suites

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2801]
I increased the timeout for [node-test-binary-windows-js-suites](https://ci.nodejs.org/job/node-test-binary-windows-js-suites) from 600 seconds to 900 seconds. Should this be documented somewhere? I'm not sure if/how we track config changes. (And I'm fairly certain this is not the first time I've asked. Sorry!)

**Comment by Trott** [comment]
Ref: https://github.com/nodejs/node/pull/40684

**Comment by richardlau** [comment]
> I increased the timeout for [node-test-binary-windows-js-suites](https://ci.nodejs.org/job/node-test-binary-windows-js-suites) from 600 seconds to 900 seconds. Should this be documented somewhere? I'm not sure if/how we track config changes. (And I'm fairly certain this is not the first time I've asked. Sorry!)

I think issue raised to document the change is sufficient (so we can search for it if needed). We have a cron job to backup the Jenkins config (FWIW your change is captured in https://github.com/nodejs/jenkins-config-test/commit/d21a56afe468d322063a9a6fad3e15b780772afb).
