### ISSUE TITLE
Update "Packet" as "Equinix Metal"

### ISSUE THREAD

**Issue by vielmetti** [nodejs/build#2802]
Naming is hard!

About a year ago, Packet took on the Equinix Metal name as part of its acquisition by Equinix.

The relevant lines of text are at 

https://github.com/nodejs/build/blame/master/README.md#L213-L215

A follow up PR would correct that text.

**Comment by mhdawson** [comment]
@vielmetti I think you were saying you'll submit a PR to make that update? If so sounds good.

**Comment by sxa** [comment]
We'd also likely want to update the names in jenkins etc. which are currently a bit of a mix (mostly my doing as I've created the new Ampere systems as `equinix` in anticipation of the others being changed later)

**Comment by sxa** [comment]
Machines will likely be replaced at some point so it is unlikely we will do a global name change on all of them. Keeping this open as a reminder to do any that aren't replaced.
