### ISSUE TITLE
Access for @sxa mac infra

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2806]
@AshCripps has been helping to keep our OSX infra going over the last few years. We had split out the keys to be able to access the OSX infra into https://github.com/nodejs-private/secrets/tree/master/build/infra-mac so that he could have access without being an `infra Admin`.

Unfortunately @AshCripps is leaving Red Hat and may not have time (or at least as much time) to continue help on the OSX front.

@sxa (another Red Hatter) has volunteered to help on that front, but would need access to the OSX infra to be able to do that.  He is currently a member of the build team and does similar work for the Adoptium project.  

It would be good for @AshCripps to be able to do some handover with @sxa before he leaves so I'm opening this issue to see if it would be ok for us to give @sxa access to infra-mac like @AshCripps had.

@rvagg, @joaocgreis, @jbergstroem, @mmarchini, @richardlau

**Comment by richardlau** [comment]
+1 from me with a disclaimer that we do work for the same employer (Red Hat) and were previously both on the same Node.js team inside IBM when we worked there.

**Comment by AshCripps** [comment]
Ive added Stewart to the mac secrets in https://github.com/nodejs-private/secrets/pull/190.

As an FYI I dont currently plan to leave the project nor does my employee plan on blocking me contributing - I just have no idea what my time will be like untill I actually start at the end of the month. I will always be available by email if im needed for something however.
