### ISSUE TITLE
Device or resource busy on Pi's

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2807]
From [#build on Slack](https://node-js.slack.com/archives/C16SCB5JQ/p1637023714041300)
> trott  00:48
> Some Pi devices are perma-red because of "device busy" (NFS?) issues. For example: https://ci.nodejs.org/computer/test-requireio_joeyvandijk-debian10-armv7l_pi2-2/builds

e.g. https://ci.nodejs.org/job/node-test-binary-arm-12+/13205/RUN_SUBSET=1,label=pi2-docker/console
```
11:02:32 + git clean -fdx
11:02:38 warning: failed to remove out/Release/.nfs00000000016a2106000053f4: Device or resource busy
11:02:38 
11:02:38 real	0m6.266s
11:02:38 user	0m0.372s
11:02:38 sys	0m1.838s
11:02:39 Build step 'Execute shell' marked build as failure
```

I've just logged into `test-requireio_joeyvandijk-debian10-armv7l_pi2-2` and this process from 3 days ago looks like the culprit keeping the device locked:
```console
pi@test-requireio--joeyvandijk-debian10-armv7l--pi2-2:~ $ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
...
iojs      8999   864  0 Nov13 ?        00:00:00 /home/iojs/build/workspace/node-test-binary-arm/out/Release/openssl-cli s_server -accept 0 -cert /home/iojs/
```
full command line
```console
pi@test-requireio--joeyvandijk-debian10-armv7l--pi2-2:~ $ ps -ef | grep iojs
iojs      8999   864  0 Nov13 ?        00:00:00 /home/iojs/build/workspace/node-test-binary-arm/out/Release/openssl-cli s_server -accept 0 -cert /home/iojs/build/workspace/node-test-binary-arm/test/fixtures/keys/agent4-cert.pem -key /home/iojs/build/workspace/node-test-binary-arm/test/fixtures/keys/agent4-key.pem
```

The https://ci.nodejs.org/job/node-test-binary-arm-12+/ job does attempt to clean up `node` processes before running tests but this won't clear `openssl-cli` -- e.g. from the same job https://ci.nodejs.org/job/node-test-binary-arm-12+/13205/RUN_SUBSET=1,label=pi2-docker/console
```console
11:00:38 + pgrep -a node
11:00:38 + echo 'No node process running.'
11:00:38 No node process running.
11:00:39 [node-test-binary-arm] $ /bin/bash -ex /tmp/jenkins5262197693915878272.sh
11:00:39 + rm -rf RUN_SUBSET
11:00:39 + case $label in
11:00:39 + REF=cc-armv7
11:00:39 + ps -ef
11:00:39 + grep '\[node\] <defunct>'
11:00:39 + xargs -rl kill
11:00:39 + awk '{print $2}'
11:00:39 + ps -ef
11:00:39 + grep 'Release\/node'
11:00:39 + xargs -rl kill
11:00:39 + awk '{print $2}'
11:00:39 + git --version
```

I'll try widening the `grep` from `'Release\/node'` to ` 'out\/Release\/'`.

**Comment by rvagg** [comment]
👍 that sounds look a good idea, should be pretty safe to kill everything that matches that

**Comment by richardlau** [comment]
Change made 
Audit trail: https://github.com/nodejs/jenkins-config-test/commit/f84c705e1d96e8c0c712e19341aa193eae776f2f

**Comment by richardlau** [comment]
Most recent builds have been green 🎉.
