### ISSUE TITLE
More performant host for ubuntu1804_sharedlibs_debug_x64 ?

### ISSUE THREAD

**Issue by targos** [nodejs/build#2812]
This build often errors while linking (https://ci.nodejs.org/job/node-test-commit-linux-containered/29637/nodes=ubuntu1804_sharedlibs_debug_x64/console): `collect2: fatal error: ld terminated with signal 9 [Killed]`
This is probably due to not having enough memory available.
It's also extremely slow (takes more than 1.5 hours).

**Comment by targos** [comment]
Another job that takes a very long time: https://ci.nodejs.org/job/node-test-commit-linux-containered/29637/nodes=ubi81_sharedlibs_openssl111fips_x64/

**Comment by mhdawson** [comment]
We moved this job to our larger arm machines, so I think this can be closed. Please let us know if you think that was not the right thing to do.
