### ISSUE TITLE
Access for @sxa to openstack for OSUOSL

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2814]
I'd like to add @sxa to the people who can log in/manage our machines at OSUOSL (our power CI machines) through the openstack UI?

@rvagg, @richardlau, @jbergstroem, @mmarchini, @joaocgreis  any concerns with me doing that ?

**Comment by richardlau** [comment]
+1 from me. I believe @sxa already has access to the Adoptium machines at OSUOSL through the same openstack (albeit under a different project).

**Comment by mhdawson** [comment]
@rvagg any concerns?

**Comment by rvagg** [comment]
nope, sorry, I thought I emoji +1'd this already

**Comment by mhdawson** [comment]
Sent request to OSU to get @sxa access
