### ISSUE TITLE
equinix arm containers offline

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2820]
Currently all equinix hosted arm containers are offline.
![image](https://user-images.githubusercontent.com/5445507/144845572-658db127-7e7d-457d-a0ef-66ffa2fe640c.png)

I'm unable to ssh into the host
```console
$ ssh test-equinix-ubuntu2004_docker-arm64-1
ssh: connect to host 145.40.81.219 port 22: Connection timed out
$
```

**Comment by richardlau** [comment]
I'm also currently unable to log into equinix -- currently talking to equinix via the webchat on the login page.

**Comment by richardlau** [comment]
I can log in now. The machine appears to be up but I still can't ssh into it. I tried to reboot it in the Equinix Metal web UI but still can't ssh into it.

The `SOS - Serial Over SSH` for the server does appear to work but I don't know what to do there as it doesn't seem to be a regular login.

**Comment by Trott** [comment]
@nodejs/platform-arm

**Comment by richardlau** [comment]
I had a chat with @sxa (who's not feeling 100% today, get well soon).

Rebooting the server while connected to the `SOS - Serial Over SSH` ends up on this screen 😕 :
```
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (American Megatrends, 0x0005000F)
map: No mapping found.
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell>
```

To try to unblock this:
- I am going to attempt to reinstall the other test-equinix machine which is currently not being used (it's running CentOS 8 which will no longer be supported after the end of this month) as another docker host.
- @sxa is going to see if we can somehow recover the existing `test-equinix-ubuntu2004_docker-arm64-1`.

**Comment by richardlau** [comment]
okay... I'm not exactly sure what I've done but typing `exit` a few times in the `Serial Over SSH`  session seems to have brought `test-equinix-ubuntu2004_docker-arm64-1` back.

First `exit` from the prompt above lead to 
```
Shell> exit
Checkpoint AD
Checkpoint D9
ERROR: Boot option loading failed
```
and then
```console
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (American Megatrends, 0x0005000F)
Mapping table
      FS0: Alias(s):HD0b:;BLK1:
          PcieRoot(0xA0000)/Pci(0x1,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)/HD(1,GPT,03595DD0-4527-4978-9105-27BF2E46F855,0x800,0xFA000)
     BLK0: Alias(s):
          PcieRoot(0xA0000)/Pci(0x1,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)
     BLK2: Alias(s):
          PcieRoot(0xA0000)/Pci(0x1,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)/HD(2,GPT,D9C07E22-D66F-4296-9148-6E9609177BF7,0xFA800,0x11E293A)
     BLK3: Alias(s):
          PcieRoot(0xA0000)/Pci(0x1,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-00-00-00-00-00-00-00)/HD(3,GPT,72E6D110-B626-41CF-B2F9-8969CDCA31E9,0x12DD800,0x6E9A428F)




Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell>
```
which is different from before (mapping table now, whatever that is (disks?)). Exiting from that led to a grub boot loader menu where I let it boot into GNU/Linux which led to a login prompt:
```console
Shell> exit
Checkpoint AD
error: no suitable video mode found.

                             GNU GRUB  version 2.04

 ����������������������������������������������������������������������������Ŀ
 �*GNU/Linux                                                                  �
 � Advanced options for GNU/Linux                                             �
 � UEFI Firmware Settings                                                     �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 ������������������������������������������������������������������������������

      Use the  and  keys to select which entry is highlighted.
      Press enter to boot the selected OS, `e' to edit the commands
      before booting or `c' for a command-line. ESC to return previous
      menu.

[    0.781840] tpm_crb MSFT0101:00: [Firmware Bug]: ACPI region does not cover the entire command/response buffer. [mem 0x88500000-0x88500fff flags 0x201] vs 88500038 1000
[    0.867243] cma: cma_alloc: alloc failed, req-size: 256 pages, ret: -12
[    0.873914] cma: cma_alloc: alloc failed, req-size: 256 pages, ret: -12
[    0.880565] cma: cma_alloc: alloc failed, req-size: 256 pages, ret: -12
[    0.887217] cma: cma_alloc: alloc failed, req-size: 128 pages, ret: -12
[    0.894691] cma: cma_alloc: alloc failed, req-size: 256 pages, ret: -12
[    0.901349] cma: cma_alloc: alloc failed, req-size: 256 pages, ret: -12
[    0.908001] cma: cma_alloc: alloc failed, req-size: 256 pages, ret: -12
[    0.914651] cma: cma_alloc: alloc failed, req-size: 128 pages, ret: -12

Ubuntu 20.04.3 LTS test-equinix-ubuntu2004-docker-arm64-1 ttyAMA0

test-equinix-ubuntu2004-docker-arm64-1 login:
```

**Comment by vielmetti** [comment]
Glad to hear that the system is up, but I'm hopeful that we can
get it to a point where it reboots without the need for manual
intervention.

The specific error message I'm zeroing in on is

```
[Firmware Bug]: ACPI region does not cover the entire command/response buffer.
```

In searching for some commentary on this issue, I came across

http://www.kennydrobnack.com/blog/2018/04/15/diving-back-into-ubuntu-linux-and-smashing-into-acpi-errors-with-ubuntu-18-04/

which recommends setting `acpi_osi=!` as one of the boot options.

**Comment by richardlau** [comment]
Trying to reinstall `test-equinix-centos8-arm64-1` and replace the CentOS 8 install with Ubuntu 20.04 but it doesn't seem to work as expected -- the host goes through deprovisioning but is coming back still as CentOS 8 afterwards:
![image](https://user-images.githubusercontent.com/5445507/144907344-8bdfde89-5b94-4cc1-bf9d-0f502463c35c.png)

![image](https://user-images.githubusercontent.com/5445507/144907513-d0ad9f72-135a-4bc2-b7da-5f340581f7cb.png)

![image](https://user-images.githubusercontent.com/5445507/144908325-01623a0b-4a8b-47f8-a350-6f98c024dd5a.png)

**Comment by richardlau** [comment]
I tried reinstalling again today and it worked 🎉. Setting up the second test host now.

**Comment by richardlau** [comment]
I've applied https://gist.github.com/vielmetti/dafb5128ef7535c218f6d963c5bc624e to the reprovisioned test-equinix-ubuntu2004-arm64-2.

**Comment by vielmetti** [comment]
Glad this got sorted out.
