### ISSUE TITLE
Mac Stadium outage for upgrade Dec 16, 9-11 ET

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2823]
An orka upgrade is required for the infra that supports some of our MacOS machines.

This time seemed to be the best of what was offered as I did not think waiting until the week before the holidays made sense.

Info related to the upgrade from MacStadium

```console
In order to complete your upgrade as smoothly as possible, please review the following:

We require a minimum 2 hour maintenance window to perform the upgrade. We have time slots (EST) to chose from Monday-Thursday.
The API will be unreachable during the maintenance window. Please pause all CI/CD functions during the maintenance window.
Prior to starting the maintenance window, any running VMs need to be saved by you and your team (orka image save or orka image commit).
For upgrades to 1.7, all VMs will need to be shutdown from the cluster and drained prior to the start maintenance window.
There is no impact to your images, VM configs or ISOs performing this upgrade.
We will notify you as soon as the upgrade is completed!
```

@AshCripps any chance you will be around in terms of helping out with the pre/post activities?

**Comment by AshCripps** [comment]
Yep I should be available to help out.

**Comment by mhdawson** [comment]
@AshCripps thanks, we should try to get one of use (Me, Richard or sxa) to watch while you do the steps as some knowledge transfer.

**Comment by rvagg** [comment]
Expect some possible downtime this week:

> We can wait to perform the full upgrade until next Thursday, however, we can temporarily fix the cert issue by applying a patch that should have minimal impact and prevent an outage this week. We would need your permission to execute this. Please let us know.

I've just told them to go ahead and do what they need and we'll manage on our end.

**Comment by mhdawson** [comment]
@rvagg thanks for the update. I wonder if we can swap in the build email so that we all get the updates?

**Comment by rvagg** [comment]
> We have patched the certificate issue and the cluster should be good. We still plan on upgrading the cluster and expanding it next Thursday during the scheduled window. Let us know if you have any questions prior to then.

Yeah, I'd like to swap the emails on this account, not sure how though. Will try and figure it out this week.

**Comment by mhdawson** [comment]
@AshCripps the interval starts at 9ET so I think the shutdown steps will be needed beforehand. Maybe you can do that and then you can help us walk through bringing things back up after the upgrade around 11ET?  If that makes sense I'll send out an invite.

**Comment by rvagg** [comment]
FYI I've added @mhdawson @richardlau @sxa to our MacStadium account. I'm not sure you'll get emails but Michael managed to log in somehow so it works. You should all get the emails that I've been getting each time a ticket has action in their system.

**Comment by richardlau** [comment]
I can confirm that I got an email from MacStadium and was able to log in.

**Comment by AshCripps** [comment]
@mhdawson is there a list of preshutdown steps they want done? im not in any email communication.

**Comment by mhdawson** [comment]
This is what was in the notice (from top comment in this issue)

Prior to starting the maintenance window, any running VMs need to be saved by you and your team (orka image save or orka image commit).
For upgrades to 1.7, all VMs will need to be shutdown from the cluster and drained prior to the start maintenance window.

I think we should assume we are having an upgrade to 1.7 to be safe?

**Comment by mhdawson** [comment]
@AshCripps

**Comment by AshCripps** [comment]
ok I think its probs worth blowing the vms away and starting afresh anyway as some are in a weird state of brokeness - there are base images already though so should be ok.

**Comment by mhdawson** [comment]
Sending an invite for 11 so that we can bring things back up together.

**Comment by mhdawson** [comment]
@AshCripps can you send me your new email so that I can add you to the invite?

**Comment by AshCripps** [comment]
@mhdawson sent it to you on slack.

**Comment by AshCripps** [comment]
All vms stopped and removed from the nodes for the upgrade - all disconnected the agents in ci in the meantime.

**Comment by mhdawson** [comment]
Unfortunately it's taken longer than the planned outage and the enviroinment won't be ready until another half hour or so. At that point its too late for the build members in the UK so we'll be out until tomorrow.

**Comment by AshCripps** [comment]
@rvagg Can you add me to the macstadium account aswell please?

**Comment by mhdawson** [comment]
@AshCripps I just added you. You should have an invite to your email.

**Comment by richardlau** [comment]
Looks like the orka macOS 10.15 are exhibiting https://github.com/nodejs/build/issues/2728 again.
e.g. https://ci.nodejs.org/job/node-test-commit-osx/43159/nodes=osx1015/console
```console
06:00:46 python ./configure --verbose 
06:00:50 No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
06:00:50 
06:00:50 No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
06:00:50 
06:00:50 No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
06:00:50 
06:00:50 gyp: No Xcode or CLT version detected!
```

**Comment by mhdawson** [comment]
@richardlau, @sxa as an update for this issue, I'm assuming the orka macOS machines are back right?

**Comment by mhdawson** [comment]
@AshCripps

**Comment by richardlau** [comment]
@mhdawson Yes... although there's an issue building Node.js 12 (possibly 14 as well but we don't build that daily) -- a reocurrence of https://github.com/nodejs/build/issues/2728.

v14.x-staging test build: https://ci.nodejs.org/job/node-test-commit-osx/43171/

**Comment by richardlau** [comment]
> possibly 14 as well but we don't build that daily
> 
> v14.x-staging test build: https://ci.nodejs.org/job/node-test-commit-osx/43171/

14.x fails same way on one of the orka 10.15 machines (presume all the orka ones are the same)
```console
11:15:15 No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
11:15:15 
11:15:15 No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
11:15:15 
11:15:15 No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
11:15:15 
11:15:15 gyp: No Xcode or CLT version detected!
11:15:15 gyp ERR! configure error 
11:15:15 gyp ERR! stack Error: `gyp` failed with exit code: 1
11:15:15 gyp ERR! stack     at ChildProcess.onCpExit (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/lib/configure.js:351:16)
11:15:15 gyp ERR! stack    
```

**Comment by AshCripps** [comment]
This has to be a fault with gyp right? the xcode tools are installed on the machines. (Side note im reinstalling the release machine ive made a mistake and reset it)

**Comment by richardlau** [comment]
@AshCripps If I'm reading https://github.com/nodejs/build/issues/2728 correctly it sounds like Apple changed the way later versions of Xcode register themselves resulting in the older versions of gyp being unable to detect Xcode. Later versions of gyp were fixed but the complication with 12 and 14 is that they're on npm 6 which has an older version of node-gyp (5.1.0).

**Comment by richardlau** [comment]
I've manually installed `Command Line Tools for Xcode 11.5` on the macOS 10.15 Orka instances and PR'ed the steps into https://github.com/nodejs/build/pull/2855.

**Comment by richardlau** [comment]
Test builds (with Node.js 12)
- test-orka-macos10.15-x64-1
  - https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=osx1015/5216/ ✔️ (compare to previous failing https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=osx1015/5206/)
- test-orka-macos10.15-x64-2
  - https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/43518/ ✔️ (compare to previous failing https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/43476/)
