### ISSUE TITLE
remove coverity access for silverwind

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2825]
I doubt they had access, but if they did, can you please remove them? If they didn't, please close this issue. 😄 

Is there any way for me to check who has coverity access? @mhdawson

**Comment by richardlau** [comment]
> I doubt they had access, but if they did, can you please remove them? If they didn't, please close this issue. 😄

AFAICT silverwind doesn't have access.

> 
> Is there any way for me to check who has coverity access? 

They would be listed on https://scan.coverity.com/projects/node-js?tab=members if they have access. I'm not sure if that page is visible to non-admins. FWIW @Trott AFAICT it doesn't look like you have access either
