### ISSUE TITLE
coverity access check

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2827]
Can someone please check if `@watson` has access to coverity and if so please remove it? (This is part of the collaborator offboarding process.) Thanks.

@nodejs/build

**Comment by Trott** [comment]
Also, if it's possible to give me (and perhaps other folks on TSC) read-only access to "who can see the coverity stuff", that would reduce a little big of friction in this process!

**Comment by Trott** [comment]
@richardlau has confirmed no coverity access. Closing. Thanks!

**Comment by mhdawson** [comment]
@Trott I added you to coverity as a member. Can you check if you can see https://scan.coverity.com/projects/node-js?tab=members. If not I'll upgrade your account so you can.
