### ISSUE TITLE
Cloudflare captchas break automated tooling, like nvm

### ISSUE THREAD

**Issue by ljharb** [nodejs/build#2834]
Captchas under https://nodejs.org/dist break things like nvm (https://github.com/nvm-sh/nvm/issues/2694)

Since that content is highly CDN-able, is there a reason there's captchas enabled on that URL segment at all?

**Comment by nschonni** [comment]
Think you meant https://github.com/nvm-sh/nvm/issues/2694

**Comment by richardlau** [comment]
@rvagg @jbergstroem Do you know if this is something we turned on deliberately?

**Comment by jbergstroem** [comment]
> @rvagg @jbergstroem Do you know if this is something we turned on deliberately?

Its usually related to the security level chosen for the account. Based on the level you can also choose how to deal with said traffic; drop, captcha, etc.

We can review security settings but as far as I know there hasn't been any changes to this recently. Lets check the audit logs.

**Comment by ljharb** [comment]
It definitely could be an old change; it’s just that a user newly encountered it and reported it.

**Comment by jbergstroem** [comment]
So, the best we can do in our current level (business) is "essentially off"; whereas enterprise accounts would get "off" as an option. I can check in with our account exec's and see if that is possible. They have been very helpful in enabling other (enterprise-only) features in the past on request.

**Comment by ljharb** [comment]
It'd also be fine to have most of nodejs.org on "essentially off" and "/dist" on "off", since only nodejs.org/dist is really something programmatic tools are expected to use, if that's an option.

**Comment by jbergstroem** [comment]
@ljharb yes, agreed. I'm checking with our contacts at cloudflare if we can get the "off" setting made available.

**Comment by ljharb** [comment]
@jbergstroem happy new year! any chance we've heard back?

**Comment by fredpotvin-platformsh** [comment]
It's possible to [configure Cloudflare page rules](https://support.cloudflare.com/hc/en-us/articles/218411427-Understanding-and-configuring-Cloudflare-Page-Rules-Page-Rules-Tutorial-) to set customer security levels, and other security settings, which can lead to the CAPTCHA appearing.

Given the URL that needs to be "unblocked" is on a single path `/dist`, it looks like this would be an approach that works.

**Comment by jbergstroem** [comment]
> It's possible to [configure Cloudflare page rules](https://support.cloudflare.com/hc/en-us/articles/218411427-Understanding-and-configuring-Cloudflare-Page-Rules-Page-Rules-Tutorial-) to set custom security levels, and other security settings, which can lead to the CAPTCHA appearing.

Unfortunately not "off" unless you're using an enterprise account:
<img width="769" alt="Screen Shot 2022-03-24 at 11 00 39 AM" src="https://user-images.githubusercontent.com/176984/159933004-1947b94a-aa0d-4cd3-8601-5e1c910824ad.png">

More info here: https://support.cloudflare.com/hc/en-us/articles/200170056-Understanding-the-Cloudflare-Security-Level

I will revisit now.

**Comment by jww-cw** [comment]
is it possible to disable security entirely?

![image](https://user-images.githubusercontent.com/44017120/159935309-f8e3d13a-3b08-40cd-91b7-562ac09b31ef.png)

**Comment by fredpotvin-platformsh** [comment]
I don't feel like this is going to help contribute to a solution, but it's Cloudflare guide on how to deal with CAPTCHA, so, I feel like it's a least related enough so that I post it. [Community Tip - Best Practices For Captcha Challenges](https://community.cloudflare.com/t/community-tip-best-practices-for-captcha-challenges/56301)

**Comment by alexthunder3** [comment]
Hello!
Did anything change today? We've started getting cloudflare captchas on a few of our projects. They are hosted on platform.sh, so i fear a lot more projects will start getting impacted soon..

**Comment by jbergstroem** [comment]
> Did anything change today? 

No changes as far as I am aware of. Let me check the audit log.

**Comment by fredpotvin-platformsh** [comment]
> Hello! Did anything change today? We've started getting cloudflare captchas on a few of our projects. They are hosted on platform.sh, so i fear a lot more projects will start getting impacted soon..

Indeed. This problem effected some projects hosted on Platform.sh. Our public incident report => https://status.platform.sh/incidents/bp6khw4pm490

Cloudflare was returning 403 to build containers on some project using nodejs.org domain.

It's now working properly. An RCA will be published as soon as it's available. Usually it takes 2 weeks to publish.

**Comment by mhdawson** [comment]
> It's now working properly. An RCA will be published as soon as it's available. Usually it takes 2 weeks to publish.

Does this mean the issue is resolve? I'm not 100% sure having read through the issue.

**Comment by fredpotvin-platformsh** [comment]
> > It's now working properly. An RCA will be published as soon as it's available. Usually it takes 2 weeks to publish.
> 
> Does this mean the issue is resolve? I'm not 100% sure having read through the issue.

Calls to nodejs.org might still get CAPTCHA, from any server, if Cloudflare decide to block the host, for whatever reasons. Which can include Platform.sh servers, but isn't happening at the moment. So, it resolve for us and our customers.

**Comment by ljharb** [comment]
This is still an occasional, albeit rare, issue.

**Comment by ljharb** [comment]
Bump, until captchas are completely disabled on endpoints that are expected to be used programmatically.

**Comment by ovflowd** [comment]
That rule sounds good to me. Is that a Security Rule?

**Comment by targos** [comment]
It's a Configuration Rule: https://dash.cloudflare.com/07be8d2fbc940503ca1be344714cb0d1/nodejs.org/rules/configuration-rules

**Comment by ovflowd** [comment]
Looks good to me.

**Comment by ljharb** [comment]
Awesome, that seems perfect!

**Comment by richardlau** [comment]
+1 to the proposed rule change.

**Comment by anonrig** [comment]
+1 on the proposed rule addition

**Comment by targos** [comment]
The new rule is enabled.

**Comment by ljharb** [comment]
Awesome, thanks!
