### ISSUE TITLE
Renew Apple developer program membership

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2836]
We got this message today (22 Dec)

Please note that your Apple Developer Program membership expires in 30 days. Renew your membership to keep your apps on the App Store, submit new apps, utilize advanced app capabilities, and get personal technical support.

@brianwarner I think you likely helped us pay for this last year.  Are you set up to log in an renew/pay or do you need help from one of us to do that?

**Comment by rvagg** [comment]
I believe Brian is set up as administrator for this. Google Calendar says he's out till the 7th so we'd better make sure we get it figured out in that small window of time

**Comment by mhdawson** [comment]
@brianwarner  let me know if you need any help completing this and if not please confirm once complete.

**Comment by brianwarner** [comment]
Thanks @mhdawson and @rvagg, I'll be back in the office on Thursday and will take care of it then.

**Comment by brianwarner** [comment]
I just logged in and it says "Your Account Holder, Roderick Vagg, must renew your membership to keep your access to program benefits and services." :-)

Rod, I think I have the credentials. I'll try them and see what happens. If not, I'll send you a temporary credit card number to use to pay for it directly.

**Comment by mhdawson** [comment]
@brianwarner I can log in with the right account to do the renewal. Will try to ping in slack.

**Comment by mhdawson** [comment]
Got the card number from Brian, renewed and we got confirmation:

Your Apple Developer Program membership has been renewed for another year and your membership details are below. We look forward to the innovative new apps you'll bring to Apple platforms.

Team Name: Node.js Foundation
Team ID: XXXXXXXXXXXX (removed, not sure if its sensitive, but better safe than sorry)
Activation Date: January 21, 2022
Expiration Date: January 21, 2023

Best regards,
Apple Developer Relations

**Comment by mhdawson** [comment]
Complete, closing.
