### ISSUE TITLE
xz compressed binaries for 0.10.x and 0.12.x

### ISSUE THREAD

**Issue by chorrell** [nodejs/build#284]
Hi!

Would it be possible to include xz compressed binaries for 0.10.x and 0.12.x? Currently there's only gunzip compressed files available in (for example) https://nodejs.org/dist/v0.10.41/ and https://nodejs.org/dist/v0.12.9/

I've been looking into switching to  xz binaries for the docker-node image (see nodejs/docker-node/issues/77) and I'd like to eventually do that for all versions, not just 4.2.x and 5.3.x.

**Comment by jbergstroem** [comment]
We're using (almost) the same infra to build both, so the stack is there. I guess the question is rather why we possibly shouldn't do it. @rvagg?

**Comment by mscdex** [comment]
Having an xz tarball for the source code would be good too.

**Comment by rvagg** [comment]
The initial reason for not doing it was to get as close to parity with previous 0.10 and 0.12 builds as possible. Beyond that, there's the awkwardness of providing them 1/2 way through a major line, any tool that uses `xz` would either need to hard-wire a check for the exact version when we turned it on or check for existence. Perhaps that's not a problem. I don't actually have a very strong opinion on this atm.

So far during December, 9.985% of `.tar.?z` downloads of v4 and v5 have been for `.tar.xz`. That's not huge but it does suggest growing demand.

@ljharb is nvm using the .xz downloads?

**Comment by ljharb** [comment]
Yes, @jbergstroem added support for them in https://github.com/creationix/nvm/pull/823. It hasn't been in use in travis-ci for long.

I suspect usage will grow very quickly if https://github.com/creationix/nvm/pull/823/files#diff-e1e8e036966ad5aaf7709712cd5d8ee3R2235 can be expanded to include more versions, and that change hits travis.

**Comment by jbergstroem** [comment]
I reckon everyone should use `tar.xz` if possible (most packagers seems to) but I can see how most people will make the assumption that `tar.xz` is available throughout all versions if we started doing it halfway through a major.

**Comment by jbergstroem** [comment]
Fixed!
