### ISSUE TITLE
Notarization is broken

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2841]
Looks like Notarization started failing on 28 December 2021, starting with [build 8172](https://ci-release.nodejs.org/job/iojs+release/nodes=osx11-release-pkg/8172/console) and on both the Orka and NearForm hosted release machines:
<details>

![image](https://user-images.githubusercontent.com/5445507/148055347-fd81240a-348f-44fc-a0d2-44a1456601d2.png)
</details>

e.g. https://ci-release.nodejs.org/job/iojs+release/nodes=osx11-release-pkg/8187/console
```console
10:50:31 " err="exit status 1"
10:50:31     Error notarizing
10:50:31 
10:50:31 ❗️ Error notarizing:
10:50:31 
10:50:31 1 error occurred:
10:50:31 	* 1 error occurred:
10:50:31 	* You must first sign the relevant contracts online. (1048) (1048)
```

**Comment by mhdawson** [comment]
@rvagg my guess this is because of some agreement that we have to accept.

I tried logging in to the developer account, but I think only the account holder can accept. This is the message I see:

```
The Apple Developer Program License Agreement has been updated.

In order to access certain membership resources, Roderick Vagg must accept the latest license agreement.
```

**Comment by rvagg** [comment]
It's the build@iojs.org account that needs to sign it, which you should have access to. I've just logged in to that account and was able to accept the agreement there. Will try and redo the last nightly to see if it goes OK.

**Comment by mhdawson** [comment]
@rvagg let me try logging in with build@iojs.org, I had assumed I had to log in as me for the 2FA.

**Comment by mhdawson** [comment]
@rvagg ok that worked. I forgot you had added me to the build@iojs.org for 2FA.

**Comment by mhdawson** [comment]
Also looks like the job @rvagg kicked off worked ok as it's green in the release ci.
