### ISSUE TITLE
Heads up of Node.js security releases 10 January 2022

### ISSUE THREAD

**Issue by bengl** [nodejs/build#2844]
As per security release process this is a heads up that there will be security releases 10 January 2022 and we'll need people from build to lock/unlock ci and to support and build issues we see.

**Comment by richardlau** [comment]
I've announced the planned CI lockdown in https://github.com/orgs/nodejs/teams/collaborators/discussions/134

**Comment by richardlau** [comment]
CI has now been locked down.
I can see https://ci.nodejs.org/job/node-test-commit-arm/ has been failing for the last two days. Investigating.

**Comment by richardlau** [comment]
Looks like the git checkout has got corrupted,
e.g. https://ci.nodejs.org/job/node-test-commit-arm/40199/nodes=centos7-arm64-gcc8/console
```console
09:25:07 Caused by: hudson.plugins.git.GitException: Command "git fetch --no-tags --progress git@github.com:nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/41451/head:refs/remotes/origin/_jenkins_local_branch" returned status code 128:
09:25:07 stdout: 
09:25:07 stderr: error: object file .git/objects/6e/cf9413bdaa72f2f2e4a8dfd9dfff1b7f522cd0 is empty
09:25:07 error: unable to find 6ecf9413bdaa72f2f2e4a8dfd9dfff1b7f522cd0
09:25:07 error: object file .git/objects/6e/cf9413bdaa72f2f2e4a8dfd9dfff1b7f522cd0 is empty
09:25:07 fatal: loose object 6ecf9413bdaa72f2f2e4a8dfd9dfff1b7f522cd0 (stored in .git/objects/6e/cf9413bdaa72f2f2e4a8dfd9dfff1b7f522cd0) is corrupt
09:25:07 
```

I've wiped the workspace for node-test-commit-arm and the test build appears to have at least started: https://ci.nodejs.org/job/node-test-commit-arm/40200/

**Comment by richardlau** [comment]
I've unlocked the CI.
