### ISSUE TITLE
disk space issue on Windows host

### ISSUE THREAD

**Issue by targos** [nodejs/build#2851]
https://ci.nodejs.org/job/node-compile-windows/43524/nodes=win-vs2019/console

```
14:58:48 FileTracker : error FTK1005: could not write rooting file marker to the file tracking log file: C:\workspace\node-compile-windows\node\out\Release\obj\mkcodecache\mkcodecache.tlog\link.read.1.tlog. There is not enough space on the disk. [C:\workspace\node-compile-windows\node\mkcodecache.vcxproj]
14:58:48   
14:58:48   
14:58:48   
14:58:48 FileTracker : error FTK1005: could not write rooting file marker to the file tracking log file: C:\workspace\node-compile-windows\node\out\Release\obj\mkcodecache\mkcodecache.tlog\link.write.1.tlog. There is not enough space on the disk. [C:\workspace\node-compile-windows\node\mkcodecache.vcxproj]
14:58:48   
14:58:48   
14:58:48   
14:58:48 FileTracker : error FTK1005: could not write rooting file marker to the file tracking log file: C:\workspace\node-compile-windows\node\out\Release\obj\mkcodecache\mkcodecache.tlog\link.read.2.tlog. There is not enough space on the disk. [C:\workspace\node-compile-windows\node\mkcodecache.vcxproj]
14:58:48   
14:58:48   
14:58:48   
14:58:48   node_pch.cc
14:58:51 C:\workspace\node-compile-windows\node\src\inspector_agent.h(117,35): fatal error C1088: Cannot flush compiler intermediate file: 'C:\Users\ADMINI~1\AppData\Local\Temp\_CL_ee28435cdb': No space left on device [C:\workspace\node-compile-windows\node\cctest.vcxproj]
14:58:51 
```

**Comment by targos** [comment]
https://ci.nodejs.org/job/node-compile-windows/43527/nodes=win-vs2019-arm64/console

**Comment by targos** [comment]
https://ci.nodejs.org/job/node-compile-windows/43535/nodes=win-vs2019-arm64/console

Is the error actually misleading and caused by the V8 update that all these runs are testing?

**Comment by richardlau** [comment]
> https://ci.nodejs.org/job/node-compile-windows/43524/nodes=win-vs2019/console
> 

I logged into https://ci.nodejs.org/computer/test-rackspace-win2012r2_vs2019-x64-1/ and `C:\workspace` is taking up 112 GB of the 160GB disk which seems large. I'm wondering if part of the problem is that https://ci.nodejs.org/job/git-clean-windows/ has been failing and potentially not cleaning all the workspaces,

e.g. https://ci.nodejs.org/job/git-clean-windows/253/label=test-rackspace-win2012r2_vs2019-x64-1/console
```console
+ for job in node-compile-windows-debug node-test-binary-windows-js-suites node-test-binary-windows-native-suites
+ mkdir -p node-test-binary-windows-native-suites/node
+ cp -r node-compile-windows/node/.git node-test-binary-windows-native-suites/node

real	0m1.025s
user	0m0.046s
sys	0m0.890s
+ cd node-test-binary-windows-native-suites/node
+ git checkout -B master refs/remotes/GitHub/master
M	doc/api/tls.md
Branch 'master' set up to track remote branch 'master' from 'GitHub'.
Your branch is up to date with 'GitHub/master'.
Reset branch 'master'

real	0m45.392s
user	0m0.000s
sys	0m0.015s
+ git reset --hard
HEAD is now at b2edcfee460 doc: remove statement about client private keys

real	0m0.552s
user	0m0.000s
sys	0m0.015s
+ git clean -fdx
warning: failed to remove Release/node.exe: Invalid argument
warning: failed to remove test/addons/cpu-profiler-crash/build/Release/binding.node: Invalid argument

real	0m0.432s
user	0m0.000s
sys	0m0.015s
Build step 'Execute shell' marked build as failure
```

**Comment by richardlau** [comment]
Disk usage for `C:\workspace` on test-rackspace-win2012r2_vs2019-x64-1:
```console
20G     delete_1642299055
16G     delete_1642323600
0       git-clean-windows
15G     node-compile-windows
13G     node-compile-windows-debug
0       node-compile-windows-debug@tmp
0       node-compile-windows@tmp
5.2G    node-test-binary-windows-js-suites
0       node-test-binary-windows-js-suites@tmp
3.4G    node-test-binary-windows-native-suites
0       node-test-binary-windows-native-suites@tmp
17G     reis-compile-windows
19G     reis-compile-windows-debug
0       reis-compile-windows-debug@tmp
0       reis-compile-windows@tmp
3.8G    reis-test-binary-windows-js-suites
0       reis-test-binary-windows-js-suites@tmp
5.1G    reis-test-binary-windows-native-suites
0       reis-test-binary-windows-native-suites@tmp
4.0K    windows-update-reboot
```
I've killed the running `node.exe` process and removed the two `delete_` directories.

**Comment by targos** [comment]
Can I try to rerun the job now?

**Comment by richardlau** [comment]
Rerunning https://ci.nodejs.org/job/git-clean-windows/label=test-rackspace-win2012r2_vs2019-x64-1/254/console.

**Comment by richardlau** [comment]
> Can I try to rerun the job now?

There was 35G free on test-rackspace-win2012r2_vs2019-x64-1 after I cleaned out the two directories but before I reran the git-clean-windows job (currently running). That's not the only machine[1] in the CI that should be able to run node-compile-windows so it's possible the other machine(s) were okay for space.

[1] https://ci.nodejs.org/label/win-vs2019-arm64/

**Comment by targos** [comment]
> Rerunning https://ci.nodejs.org/job/git-clean-windows/label=test-rackspace-win2012r2_vs2019-x64-1/254/console.

The clean job is private. Did it succeed?

**Comment by richardlau** [comment]
Yes. we're now at 65GB free on the machine, which should hopefully be enough. If not we might need to remove/scrub the `reis-` directories (cc @joaocgreis ).

**Comment by targos** [comment]
Rerun of my job: https://ci.nodejs.org/job/node-test-pull-request/42020/

**Comment by targos** [comment]
seems good. thanks!
