### ISSUE TITLE
Jenkins is down

### ISSUE THREAD

**Issue by benjamingr** [nodejs/build#2853]
Hey, @nodejs/build - I can't seem to access ci.nodejs.org and am getting `ERR_CONNECTION_TIMED_OUT`, thought this was report-worthy :)

**Comment by benjamingr** [comment]
Seems to be back up?

**Comment by rvagg** [comment]
currently working for me, but I did upgrade it today so it's possible there's something dodgy going on .. we'll monitor the situation
