### ISSUE TITLE
Access to ARM x86 VM

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#2856]
I'm trying to resolve: https://github.com/nodejs/node/pull/41502 but there is a test that only seems to occur on ARM x86. However, I do not have access to any machine where I can reproduce and debug. Would it be possible for me to gain temporary access to such a VM?

**Comment by sxa** [comment]
@nodejs/build Do we have an easy way to grant users temporary access to the pi cluster? The docker image I have on the arm host doesn't run an sshd daemon. This problem seems to be only happening on arm32 and some windows machines.

**Comment by richardlau** [comment]
> @nodejs/build Do we have an easy way to grant users temporary access to the pi cluster? The docker image I have on the arm host doesn't run an sshd daemon. This problem seems to be only happening on arm32 and some windows machines.

Easy is subjective but some prior notes on giving access through the jump host from a previous request are in https://github.com/nodejs/build/issues/2598 (start from https://github.com/nodejs/build/issues/2598#issuecomment-812537447). You'd still need to use Docker on the pi's though, so it might still be easier to add to the arm64 host and then give instructions on how to get into the container from there.

**Comment by sxa** [comment]
@RafaelGSS I've sent you a DM on twitter with another solution for getting access to one of my (not Nodejs.org) machines that replicates the problem - it's probably in your "message requests" folder. If you send your ssh key across I can give you access

**Comment by Trott** [comment]
> @RafaelGSS I've sent you a DM on twitter with another solution for getting access to one of my (not Nodejs.org) machines that replicates the problem - it's probably in your "message requests" folder. If you send your ssh key across I can give you access

@sxa You can get a GitHub users public keys by appending `.keys` to the URL for their profile. So for @RafaelGSS, their keys are at https://github.com/RafaelGSS.keys. (This assumes that their GitHub SSH keys are also their general SSH keys, but that is usually the case.)

**Comment by sxa** [comment]
> @sxa You can get a GitHub user's public keys by appending `.keys` to the URL for their profile. So for @RafaelGSS, their keys are at https://github.com/RafaelGSS.keys. (This assumes that their GitHub SSH keys are also their general SSH keys, but that is usually the case.)

Good shout - I'll chuck them on just now to save some time! Thanks

**Comment by RafaelGSS** [comment]
Thank you, folks. I'm currently far from my machine, but soon as I arrive I'll check it out.

**Comment by RafaelGSS** [comment]
I got access and fixed the ARM issue, thank you again. Closing.

**Comment by Trott** [comment]
Let's leave it open until @sxa or someone else confirms that the keys have been removed from the hosts.

**Comment by mmarchini** [comment]
@sxa can you confirm that the key was removed from your machine, and that it was not added to any Node.js hosts?

**Comment by sxa** [comment]
Yep now removed, and it was not added to any Node.js hosts :-) Cloaing.
