### ISSUE TITLE
Add `rr` to linux CI machines

### ISSUE THREAD

**Issue by vtjnash** [nodejs/build#2861]
If the underlying hardware and VM supports it (https://github.com/rr-debugger/rr#system-requirements), it would be amazing to have `rr` installed on these machines by default from https://github.com/rr-debugger/rr/compare/master...Keno:kf/forci8, run the test step under `rr record --nested=detach`, and then upload the result artifacts (e.g. from `rr pack`) somewhere for a couple days for ready downloading and debugging. There are pre-built binaries that might even work everywhere already available at https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases

This would likely allow us to quickly solve a couple remaining intermittent issues in libuv. While I could possibly alter the libuv build files to run under `rr` manually, if they can detect that the machine has support, the making of `rr` files available to everyone who are using this CI system might be so much better!

**Comment by mmarchini** [comment]
is that a libuv-specific request? I think `rr` wouldn't provide much value to Node.js (with the exception of maybe cctests)

**Comment by vtjnash** [comment]
I do mostly work on libuv. However rr supports nodejs and V8 directly also, and can be used for JavaScript debugging. I had sent this idea to one of the rr developers and they replied: It makes even more sense for nodejs proper [relative to other CI systems I help support that use rr], because pernosco has V8 integration.
(Referring there to the post-rr visualization tool here: https://robert.ocallahan.org/2020/05/omniscient-js-debugging-in-pernosco.html?m=1)

**Comment by mhdawson** [comment]
From the docs > (VMware and KVM are known to work; Xen does not.)

I'm not sure we know what hypervisors are used by our hosting providers.

> While I could possibly alter the libuv build files to run under rr manually

That might be a good first step, both to show what would be needed in the build jobs as well as test out across our providers.
