### ISSUE TITLE
libuv-in-node job no longer supports Resume builds

### ISSUE THREAD

**Issue by cjihrig** [nodejs/build#2862]
I ran the libuv-in-node job: https://ci.nodejs.org/view/libuv/job/libuv-in-node/201/

There were failures, so I attempted a Resume build: https://ci.nodejs.org/view/libuv/job/libuv-in-node/202/

The Resume build failed immediately with:

```
fatal: remote error: 
   is not a valid repository name
  Visit https://support.github.com/ for help
```

**Comment by richardlau** [comment]
The bit that is failing from https://ci.nodejs.org/view/libuv/job/libuv-in-node/202/console is 
```console
+ git push git@github.com:libuv/binary_tmp@147.75.66.203:binary_tmp.git.git +refs/remotes/origin/master:refs/heads/master +jenkins-libuv-in-node-202
fatal: remote error: 
   is not a valid repository name
  Visit https://support.github.com/ for help
```

From https://ci.nodejs.org/view/libuv/job/libuv-in-node/201/console the corresponding line looks like this:
```console
+ git push git@github.com:libuv/ci-tmp-libuv-node.git +refs/remotes/origin/master:refs/heads/master +jenkins-libuv-in-node-201
To github.com:libuv/ci-tmp-libuv-node.git
   f436f6f55e..359c93d3ab  origin/master -> master
```

and in the [job config](https://ci.nodejs.org/view/libuv/job/libuv-in-node/configure):
```console
git push git@github.com:${TEMP_USER}/${TEMP_REPO}.git +refs/remotes/origin/master:refs/heads/master +$BUILD_TAG
```
where
![image](https://user-images.githubusercontent.com/5445507/152783924-62cc8e0c-5ff2-4a6a-b254-aa14e018b5c5.png)

If we look at the environment variables for both jobs, 
- https://ci.nodejs.org/view/libuv/job/libuv-in-node/201/injectedEnvVars/
- https://ci.nodejs.org/view/libuv/job/libuv-in-node/202/injectedEnvVars/

we see that `TEMP_REPO` is set to `binary_tmp@147.75.66.203:binary_tmp.git` which matches the erroring build (but note it's also the reported value in the passing build). So where has this value for `TEMP_REPO` come from? It's set by us as a [global Jenkins variable](https://github.com/nodejs/build/issues/1193#issuecomment-375998537). This suggests that for the resumed build either the value set for `TEMP_REPO` in the job config wasn't applied or the global setting took priority. If resuming this job worked before then it's possible that a recent Jenkins update has broken it.

I think the simplest thing to do looks like to rename the environment variable being used in the job to a different name to the one being set globally as the `git@github.com:${TEMP_USER}/${TEMP_REPO}.git` part of the job config suggests that it is expecting to always push to a GitHub hosted repository.

**Comment by richardlau** [comment]
I've changed the environment variable being used by the job (audit trail https://github.com/nodejs/jenkins-config-test/commit/317da7ee63cb892f4c5836a3b668f7c45cad9579).

Resumed https://ci.nodejs.org/view/libuv/job/libuv-in-node/201/ as https://ci.nodejs.org/view/libuv/job/libuv-in-node/205/ which appears to be running.

**Comment by cjihrig** [comment]
Thanks @richardlau. It appears to be working now, so I'll close this out.
