### ISSUE TITLE
Move to OpenJS Foundation Slack?

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2875]
The OpenJS Foundation has a paid [Slack server](https://openjs-foundation.slack.com/) available for projects to use ([invite](https://slack-invite.openjsf.org/)), which means we have access to more features (more integrations etc) as well as infinite chat history. Does anyone oppose to moving the #build channel from NodeSlackers to OpenJS Foundation Slack? I tried using Slack Connect but both organizations need to be paid tier for it to work.

**Comment by mhdawson** [comment]
+1 to move top the OpenJS Slack. I need to be active there anyway so it would be easier for me.

**Comment by BethGriggs** [comment]
Is there an update or any more feedback on this? 

It just I find myself and others end up cross-posting about the same issues across both workspaces. With #nodejs-release and #nodejs-dev in the OpenJS Slack, it might be nice for #nodejs-build to be in there too so we can more easily share/link messages across channels.

**Comment by sxa555** [comment]
Like you I'm in both of them, so I can't think of a good reason not to
shift it across especially if it gains the benefit of permanent history, so
I'm +1.

**Comment by mhdawson** [comment]
@nodejs/build one more ping to see if there are any concerns on moving over.

**Comment by sxa** [comment]
(Have pinged the slack channel to see if there are any extra views from people who aren't watching this issue)

**Comment by AshCripps** [comment]
+1 on the move, But when we make can we post a message pointing people to the new channel and then lock the old channel to stop people posting where we will miss it?

**Comment by richardlau** [comment]
I've gone ahead and created [#nodejs-build](https://openjs-foundation.slack.com/archives/C03BJP63CH0) in the OpenJS Foundation Slack. I have no idea if it's possible to lock the channel in NodeSlackers.

**Comment by Trott** [comment]
> I have no idea if it's possible to lock the channel in NodeSlackers.

In Slack parlance, the thing to do is probably to _archive_ that channel. It will still be searchable, but people won't be able to join or post. I'll see if I can find out who an admin for that Slack is and if they would be willing to archive the channel after posting an `@channel` message to everyone gets notified about the move. (I don't think unprivileged users can post `@channel` messages in that Slack.)

**Comment by Trott** [comment]
> > I have no idea if it's possible to lock the channel in NodeSlackers.
> 
> In Slack parlance, the thing to do is probably to _archive_ that channel. It will still be searchable, but people won't be able to join or post. I'll see if I can find out who an admin for that Slack is and if they would be willing to archive the channel after posting an `@channel` message to everyone gets notified about the move. (I don't think unprivileged users can post `@channel` messages in that Slack.)

@ljharb You are one of the admins in Nodeslackers, right?

**Comment by ljharb** [comment]
Done. Let me know if any further changes are needed.

**Comment by richardlau** [comment]
Doc updates: https://github.com/nodejs/build/pull/2928
