### ISSUE TITLE
Removing the 'rebuild' plugin from jenkins

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#288]
There's a very compelling reason to remove the rebuild plugin from Jenkins which I'll avoid posting publicly. Any reasons we require it to stick around?

**Comment by joaocgreis** [comment]
If you mean the "Rebuilder" plugin, it's there but not enabled. The compelling reason comes from the MultiJob plugin, and that one we need for everything.

**Comment by jbergstroem** [comment]
I disabled the plugin 2 days ago. Reopen if you need it.
