### ISSUE TITLE
Broken job node-test-commit-v8-linux?

### ISSUE THREAD

**Issue by targos** [nodejs/build#2880]
https://ci.nodejs.org/job/node-test-commit-v8-linux/

Last nightly run failed: https://ci.nodejs.org/job/node-test-commit-v8-linux/4535/
Also manual run from V8 9.9: https://ci.nodejs.org/job/node-test-commit-v8-linux/4536/

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/node-test-commit-v8-linux/4535/nodes=rhel7-s390x,v8test=v8test/console
```console
10:35:58 + ../../tools/v8/fetch_deps.py .
10:35:58 Cloning into '/data/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools'...
10:36:08 Traceback (most recent call last):
10:36:08   File "/data/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/gclient.py", line 108, in <module>
10:36:08     import gclient_scm
10:36:08   File "/data/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/gclient_scm.py", line 29, in <module>
10:36:08     import gerrit_util
10:36:08   File "/data/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/gerrit_util.py", line 16, in <module>
10:36:08     import httplib2
10:36:08 ImportError: No module named httplib2
10:36:08 Checking out depot_tools.
10:36:08 Traceback (most recent call last):
10:36:08   File "../../tools/v8/fetch_deps.py", line 100, in <module>
10:36:08     FetchDeps(sys.argv[1])
10:36:08   File "../../tools/v8/fetch_deps.py", line 72, in FetchDeps
10:36:08     depot_tools = node_common.EnsureDepotTools(v8_path, True)
10:36:08   File "/data/iojs/build/workspace/node-test-commit-v8-linux/tools/v8/node_common.py", line 40, in EnsureDepotTools
10:36:08     depot_tools = _Get(v8_path)
10:36:08   File "/data/iojs/build/workspace/node-test-commit-v8-linux/tools/v8/node_common.py", line 37, in _Get
10:36:08     cwd=depot_tools)
10:36:08   File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
10:36:08     raise CalledProcessError(retcode, cmd, output=output)
10:36:08 subprocess.CalledProcessError: Command '['/usr/bin/python', '/data/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/gclient.py', 'metrics', '--opt-out']' returned non-zero exit status 1
10:36:08 make: *** [Makefile:280: v8] Error 1
```
@miladfarca I think you mentioned that V8's gclient now has an additional Python dependency (httplib2)?

**Comment by miladfarca** [comment]
Yes it's related to this CL: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3490488, actual import is under `gerrit_util`. I just installed pip and did a `pip3 install httplib2` to resolve it.

**Comment by richardlau** [comment]
I've made changes to our Ansible scripts to install `httplib2` on all the CI hosts that can build V8. RHEL 7 s390x was particularly difficult.

PR: https://github.com/nodejs/build/pull/2881
Test build: https://ci.nodejs.org/job/node-test-commit-v8-linux/4540/

The newly added RHEL 8 s390x instances will need the `select-compiler.sh` script changes in the PR merged -- I'd overlooked how `tools/make-v8.sh` expects `gcc`/`g++` on the path to point to the actual binaries and not the `ccache` shims. A test build with the updated `select-compiler.sh` passed: https://ci.nodejs.org/job/richardlau-node-test-commit-v8-linux/58/

**Comment by richardlau** [comment]
I'll temporarily remove rhel8-s390x until https://github.com/nodejs/build/pull/2881 is merged.
