### ISSUE TITLE
Shared access to MacStadium orka

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2885]
In recent work we discovered that only the person who created a specific machine instance in orka can then later manage the instance (reboot, start/stop, etc.)

We should figure out an approach that lets multiple build members have access, either through a shared credentials or some other way.

@AshCripps any suggestions for what you think would work best?

**Comment by AshCripps** [comment]
We all have shared access through the credentials in secrets, the issue lies in the "owner" of machines - only they can manage their instances and when I asked macstadium about this they said that was how it was meant to work.

**Comment by richardlau** [comment]
@AshCripps Could the "owner" of the machines not also be a shared credential with details in secrets?

**Comment by AshCripps** [comment]
I dont see why it couldnt be.

**Comment by mhdawson** [comment]
@AshCripps would it be possible to make the "owner" of the current machines that you created a shared credential or would we need to create a new one and recreate the machines?

**Comment by AshCripps** [comment]
The current owner is tied to my email - need to look into changing it to a build email (Im sure ive changed my email once before)

**Comment by mhdawson** [comment]
@AshCripps thanks!

**Comment by mhdawson** [comment]
@AshCripps any update?

**Comment by AshCripps** [comment]
Switched my account to `build@iojs.org` and stuck the password in secrets https://github.com/nodejs-private/secrets/pull/210.

@richardlau let me know if that works for you.

**Comment by mhdawson** [comment]
@AshCripps many thanks!
