### ISSUE TITLE
Remove post-1-release jenkins tag

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#289]
We should remove the `post-1-release` jenkins tag to simplify logic. As far as I know, the only tag we need is to differentiate builders for old (0.10, 0.12) versions of nodejs, for which we have `pre-1-release`.

What I'm suggesting is that we modify this logic in the jenkins job:

``` bash
if [[ \
    ( $NODE_LABELS =~ pre-1-release  && $NODE_VERSION =~ ^[0] ) \
 || ( $NODE_LABELS =~ post-1-release && $NODE_VERSION =~ ^[^0] ) \
]]; then
```

**Comment by jbergstroem** [comment]
(ping @rvagg)

**Comment by jbergstroem** [comment]
We now do this:
```bash
if [[ \
    ( $NODE_LABELS =~ pre-1-release && $NODE_VERSION =~ ^[0] ) \
 || ( $NODE_VERSION =~ ^[^0] ) \
]]; then
```

**Comment by jbergstroem** [comment]
It would perhaps be simpler just to exit instead of scoping the rest?

**Comment by rvagg** [comment]
yes, probably, that'd be fine I think

**Comment by jbergstroem** [comment]
Just a heads up; tried landing this in the jobs but it's flawed. Will rewrite, post here and redeploy.

**Comment by gibfahn** [comment]
Seems the tag is still there: https://ci-release.nodejs.org/label/post-1-release/

😞

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.

**Comment by refack** [comment]
> Seems the tag is still there: [ci-release.nodejs.org/label/post-1-release](https://ci-release.nodejs.org/label/post-1-release/)
> 
> 😞

FTR it's a phantasm. Jenkins show that page for host/label/* i.e. https://ci-release.nodejs.org/label/refael-like-tp-walk-in-the-woods/
