### ISSUE TITLE
access to windows vm

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/build#2891]
I want fix https://github.com/nodejs/node/pull/42115.

But I need a windows vm since I don't have windows machine (switched to m1 mac)

cc @joaocgreis @targos

**Comment by targos** [comment]
+1

**Comment by mhdawson** [comment]
+1 from me

**Comment by gengjiawen** [comment]
I see https://github.com/nodejs/build/issues/2186#issuecomment-589087237. @joaocgreis Once you are set, you can send test vm info to my email.

**Comment by targos** [comment]
@nodejs/build-infra

**Comment by richardlau** [comment]
+1, although I have no idea how to go about this for Windows.

**Comment by joaocgreis** [comment]
I'm very sorry for the delay here. I've sent login credentials to @gengjiawen , I hope they're still useful.

@richardlau for this I've provisioned a dedicated machine (Ansible script without the Jenkins part). Another option would be to remove a machine from CI and create a regular user account that could be removed when no longer needed.

**Comment by gengjiawen** [comment]
> I'm very sorry for the delay here. I've sent login credentials to @gengjiawen , I hope they're still useful.
> 
> @richardlau for this I've provisioned a dedicated machine (Ansible script without the Jenkins part). Another option would be to remove a machine from CI and create a regular user account that could be removed when no longer needed.

Thx. I have fixed v8 the issue (still other issues on arm ). Also tried the login process :) works good.
