### ISSUE TITLE
Make sure all init scripts has JOBS and NODE_TEST_DIR

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#291]
We should populate the environment variable `JOBS` through ansible facts. This way we can better control parallelism in both compilation and upcoming testing.

**Comment by jbergstroem** [comment]
..also, now that `NODE_COMMON_PIPE` is superseded by `NODE_TEST_DIR`, we should set these in the init scripts as well. The path should point to a temporary folder which is on the same filesystem as where nodejs is built (it for instance needs to be `/home/iojs/build` on arm since its mounted through nfs).

**Comment by jbergstroem** [comment]
Question: now that these commits has been merged to 0.10 and 0.12 branches, do we want to continue supporting `NODE_COMMON_PIPE` moving forward in CI? Not setting it will potentially generate a fail for really old stuff; but I don't really see where or why we'd test against older branches.

**Comment by gibfahn** [comment]
>Question [...] do we want to continue supporting NODE_COMMON_PIPE moving forward in CI?

No! We should definitely remove this going forward.

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
