### ISSUE TITLE
Access for @KevinEady to debian 8 test VM

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2919]
We've had trouble recreating a CI failure in https://github.com/nodejs/node-addon-api/issues/1150.

While it seems to occur regularly in CI runs on debian 8, we can't recreate locally. I'd like to request temporary access for @KevinEady based on section https://github.com/nodejs/node-addon-api/issues/1150 of our goverance.

In terms of:

- Does the scope and size of the need justify providing access.
- Is the individual a collaborator. If so then access should be allowed provided the first point is satisfied.
- Length and consistency of involvement with Node.js working groups and/or community.
- Consequences to the individual in case of misbehaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way ?
- Are there collaborators who work with the individual and can vouch for them.

I believe the need justifies the scope of the access requested (1 test machine), he's a long time contributor to the Node-api effort, and I'm confident he will take appropriate care while using the machine.

**Comment by mhdawson** [comment]
@nodejs/build any concerns or +1s?

**Comment by richardlau** [comment]
+1

**Comment by mhdawson** [comment]
@KevinEady, I'm out until next Tuesday and we should probably avoid release day. Would 10 ET on Wednesday the 20th be a good time to take a look together? In advance of that if you send me your ssh key I can add to one of the machines in case you have a chance to investigate before then?

**Comment by KevinEady** [comment]
Hi @mhdawson , I have sent you my public key over email. I will have time this long weekend over the holiday so if you can set up access on the machine I can take a look. 

20 April does not work for me as I have a lot of work meetings on that Wednesday. The following Thursday, 21 April works for me.

**Comment by mhdawson** [comment]
@KevinEady sorry must have been after I left for the weekend. Will plan to add your key today.

**Comment by mhdawson** [comment]
I've added @KevinEady 's key to test-digitalocean-debian8-x64-1 and set up his own directory/user. I have not disabled the machine from the CI since we only have 2 debian8 machines in the ci.

**Comment by mhdawson** [comment]
@KevinEady I think you are done with the machine. If you can confirm I'll remove your key and clean up the directory I created for you.

**Comment by mhdawson** [comment]
Checked today his key is no longer there, closing.
