### ISSUE TITLE
Access to @ShogunPanda to ubuntu2004-armv7l test VM

### ISSUE THREAD

**Issue by ShogunPanda** [nodejs/build#2923]
I have a test failing in https://ci.nodejs.org/job/node-test-pull-request/43447/ and I could not reproduce it locally.

Can you please grant me the access to the machine to debug?

PS: Sorry to bother, v18 code freeze is today so this is kinda an urgent request.

**Comment by sxa** [comment]
Is the one you have access to under https://github.com/nodejs/build/issues/2888 not adequate?

**Comment by ShogunPanda** [comment]
Sorry, I thought the access expired and I didn't even tried. I'll just use that one then. Closing this.
