### ISSUE TITLE
Access to @ShogunPanda to freebsd12-x64 test VM

### ISSUE THREAD

**Issue by ShogunPanda** [nodejs/build#2929]
I have a flaky test in https://github.com/nodejs/node/issues/42741 and I could not reproduce it locally.

Can you please grant me the access to the machine to debug?

**Comment by Trott** [comment]
+1 

@nodejs/build

**Comment by richardlau** [comment]
+1

@ShogunPanda I've added your ssh key to test-digitalocean-freebsd12-x64-1 https://github.com/nodejs/build/blob/b6230d51305d97fa10246895dac5900a561911da/ansible/inventory.yml#L130
You should be able to login with `ssh freebsd@45.55.90.237`. CI builds run as the `iojs` user (`sudo -s su - iojs` after you log in).

**Comment by richardlau** [comment]
@ShogunPanda Are you done with that machine?

**Comment by ShogunPanda** [comment]
Yes, I should be done, thanks.

**Comment by richardlau** [comment]
Okay thanks. I have removed your key from the machine.
