### ISSUE TITLE
test-joyent-smartos14-x86-1 is painfully slow

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#293]
For some reason its more than twice as slow as its 64-bit counterpart. It has 8 vcpu cores and 8G of ram, so resources shouldn't be the issue. I'll try and redeploy to a new instance and see if that helps.

Example here: https://ci.nodejs.org/job/node-test-commit-smartos/752/

**Comment by rvagg** [comment]
some input from @nodejs/platform-solaris might be helpful here, I've also noticed how slow it is and assumed we had slower machines there now but apparently not! The speed-up when enabling parallel tests was also unimpressive: https://github.com/nodejs/node/pull/4476

**Comment by jbergstroem** [comment]
Seems to be better now. I'll close this but will keep monitoring.
