### ISSUE TITLE
benchmark-node-micro-benchmarks unavailable

### ISSUE THREAD

**Issue by ShogunPanda** [nodejs/build#2944]
Hello!
It seems that benchmark-node-micro-benchmarks is unavailable as all worker machines are reported down.

See: https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/

**Comment by targos** [comment]
@nodejs/build-infra

**Comment by richardlau** [comment]
I can't ssh into either of them (unreachable). I'll dig out our NearForm contact and send an email.

**Comment by ShogunPanda** [comment]
I think the machines came back up. Shall we close this?

**Comment by richardlau** [comment]
> I think the machines came back up. Shall we close this?

I've opened https://github.com/nodejs/build/issues/2951 to track the macOS machines (which are still unreachable). The two benchmark machines are indeed back up.
