### ISSUE TITLE
Configuration history plugin

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/build#295]
https://wiki.jenkins-ci.org/display/JENKINS/JobConfigHistory+Plugin

The above plugin would allow us to maintain a history of configuration changes and simplify the process of reverting changes

**Comment by jbergstroem** [comment]
The discussion came up as the result of doing changes to a job and wanting to revert. The suggested procedure here is to copy a job if you're uncomfortable-ness of editing "live".

Fwiw, my position is `-0`; I'm not a big fan of how we are wordpress:ing our jenkins setup with plugins and would like to shrink what plugins we use, not grow them.

**Comment by TheAlphaNerd** [comment]
@jbergstroem is there a way to get this functionality (reverting changes) without adding a plugin?

**Comment by rvagg** [comment]
We could achieve this with a smarter backup system that saves differentials or incrementals, they are really all just XML files on the server.

**Comment by jbergstroem** [comment]
Yep. I'd like to get [rsnapshot](http://rsnapshot.org) rolling. Perhaps fiddle with rsync depth to avoid job history? The other option would be looking at how long we store build logs.

**Comment by jbergstroem** [comment]
We've as of last Wednesday deployed a configuration history plugin. Closing.

**Comment by TheAlphaNerd** [comment]
🎉🎉🎉`
