### ISSUE TITLE
node-test-binary-armv7l stuck

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2959]
Looks like this platform on Jenkins has been stalled for around 30 hours or something like that. https://ci.nodejs.org/job/node-test-binary-armv7l/ As of right now, there are 15 Jenkins runs waiting for it to start.

**Comment by richardlau** [comment]
I've logged into the OOB console and exited the UEFI CLI on both machines.

**Comment by Trott** [comment]
Optimistically closing, but please re-open if my optimism is unjustified.
