### ISSUE TITLE
FreeBSD release binaries for amd64 and arm64 possible (need it to add FreeBSD support to Bazel's rules_nodejs)?

### ISSUE THREAD

**Issue by yesudeep** [nodejs/build#2965]
I'm currently working on a feature addition to Bazel's `rules_nodejs` where we're reading https://nodejs.org/dist/index.json to fetch the different versions of nodejs binaries to build code hermetically on FreeBSD. However, while working on my PR, I've realized that there are no official binaries for FreeBSD.

Would it be possible to add these to the release process?

References:
1. PR in question that adds FreeBSD support for rules_nodejs: https://github.com/bazelbuild/rules_nodejs/pull/2991 
2. Both arm64 and amd64 are Tier 1 platforms supported by FreeBSD: https://www.freebsd.org/platforms/

**Comment by knz** [comment]
I think this is still current.
