### ISSUE TITLE
centos5: path to >=python 2.6

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/build#297]
centos5-64 is blowing up when trying to run citgm, the errors from level seem to be telling

```
error:                     | prebuild ERR! stack Error: Python executable      
error:                     | "/usr/bin/python2" is v2.4.3, which is not        
error:                     | supported by gyp. 
```

From [this CI run](https://ci.nodejs.org/job/thealphanerd-smoker/14/nodes=centos5-64/consoleFull)

**Comment by jbergstroem** [comment]
You need to call python from `python` since we override default path on systems that ships too old versions (which we override by installer newer ones)

**Comment by TheAlphaNerd** [comment]
what would be the best way to do this if we are calling citgm, which is then running npm in a child process?

Would simply including the env var when running the process work?

```PYTHON=python citgm-all``` ?

**Comment by jbergstroem** [comment]
Actually, that's why we pass python through the environment variable `PYTHON` to the build system on centos5. We essentially do `export PATH=/home/iojs/bin:$PATH` and call `python`.

```bash
[root@node-centos5-32 ~]# python -V
Python 2.4.3
[root@node-centos5-32 ~]# /usr/bin/python -V
Python 2.4.3
[root@node-centos5-32 ~]# /usr/bin/python2 -V
Python 2.4.3
[root@node-centos5-32 ~]# /usr/bin/python26 -V
Python 2.6.8
[root@node-centos5-32 ~]# /home/iojs/bin/python -V
Python 2.6.8
[root@node-centos5-32 ~]# ls -al /home/iojs/bin/python
lrwxrwxrwx 1 iojs root 17 Nov 11 20:03 /home/iojs/bin/python -> /usr/bin/python26
```

**Comment by TheAlphaNerd** [comment]
maybe you can take some time with me tomorrow and try and get centos working. I think I have just about everything "workingish" aside from windows, which I have not yet attempted

**Comment by jbergstroem** [comment]
@TheAlphaNerd give what you wrote a try (`PYTHON=python $foo`) and let me know how it works. Happy to help out.

**Comment by jbergstroem** [comment]
@TheAlphaNerd did you get it going?

**Comment by TheAlphaNerd** [comment]
@jbergstroem I ended up chasing some other bugs on ppc last week. I'll revisit this after wrapping up the 5.4.1 release

**Comment by jbergstroem** [comment]
Updated title to better reflect the issue.

**Comment by jbergstroem** [comment]
ping!

**Comment by TheAlphaNerd** [comment]
@jbergstroem I'll take a look at this tomorrow :D

**Comment by jbergstroem** [comment]
ping @thealphanerd. I think we can close this :)

**Comment by jbergstroem** [comment]
@TheAlphaNerd anything to report?

**Comment by TheAlphaNerd** [comment]
I have not tried getting citgm working on centos after this. I'll close this and reopen if we hit this again
