### ISSUE TITLE
Migrate away from 'master' as the jenkins CI controller node name

### ISSUE THREAD

**Issue by sxa** [nodejs/build#2971]
### What is the problem this feature will solve?

Remove all references to 'master' in jenkins. We have made the changein default branch name in all our repositories so to be consistent we should switch the name in jenkins too.
This is recommended by jenkins: https://www.jenkins.io/doc/book/managing/built-in-node-migration/

### What is the feature you are proposing to solve the problem?

Click the migration button in jenkins to migrage from `master` to `build-in` as the controller's node. I don't think we have any executors on the controller host, so I suspect this will have no impactL

### What alternatives have you considered?

Leaving it as-is and ignoring the warning :-)

**Comment by mhdawson** [comment]
Is there anything more needed than:

> Click the migration button in jenkins to migrage from masger to build-in as the controller's node

Is there any risk in doing this?

**Comment by mhdawson** [comment]
ok, then +1 lets pick a time and do it.

**Comment by richardlau** [comment]
This may have been done when I updated the CI servers in https://github.com/nodejs/build/issues/2984.
