### ISSUE TITLE
Windows download single exe

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#299]
I'm wondering what the history is behind the non-installer package for Windows being a single Node exe versus a zip that includes npm etc.  The tar.gz for other platforms includes a more complete install so I was wondering why the difference ?

**Comment by rvagg** [comment]
before my time, my guess is that it dates back to pre-installer days, perhaps even pre-bundled-npm days

**Comment by bnoordhuis** [comment]
> perhaps even pre-bundled-npm days

^ That.

**Comment by mhdawson** [comment]
So I guess the question is whether it still makes sense to provide just the exe or whether a zip would make more sense ?

**Comment by rvagg** [comment]
Seems to be in wide use: https://github.com/coreybutler/nvm-windows/blob/master/src/nvm.go#L333-L348

`node.lib` is used by node-gyp too

using the download stats, for Q4 2015:

```
$ cat nodejs.org-access.log.20151* | awk '/\.msi,v/ { msi++ } /\.exe,v/ { exe++ } END { printf "msi=%s, exe=%s, %s%\n", msi, exe, (exe / (exe + msi)) * 100 }'
msi=4765206, exe=890241, 15.7413%
```

That's surprisingly big. I don't think we can do anything here without more information on how and why it's being used.
