### ISSUE TITLE
Onboarding F3n67u to the build wg

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/build#3003]
While I was onboarding @F3n67u as a collaborator yesterday, I followed the [onboarding guide in the core repo](https://github.com/nodejs/node/blob/main/onboarding.md) and it mentions this:

https://github.com/nodejs/node/blob/main/onboarding.md#fifteen-minutes-before-the-onboarding-session

> ## Fifteen minutes before the onboarding session
> 
> * Prior to the onboarding session, add the new Collaborator to
>   [the collaborators team](https://github.com/orgs/nodejs/teams/collaborators).
> * Ask them if they want to join any subsystem teams. See
>   [Who to CC in the issue tracker][who-to-cc].

Feng expressed interest in joining the Build WG, so I assumed that I was supposed to add him there and I did so. However, now I realize that the build repo has its own [governance](https://github.com/nodejs/build/blob/main/GOVERNANCE.md) and [onboarding](https://github.com/nodejs/build/blob/main/ONBOARDING.md) documents, so I feel that maybe that was not the right thing to do, so I have removed Feng from the build team.

I wanted to know what should be done here. Is anyone else from the @nodejs/build team going to onboard Feng to this group or is there anything else that we should do first?

**Comment by Trott** [comment]
I added `build-agenda` label so this at least gets on the next meeting agenda if no one replies between now and then.

**Comment by mhdawson** [comment]
We should probably fix that onbording guidance there are probably a number of teams which require more than just showing interest as a prereq for being added.

**Comment by targos** [comment]
Maybe the docs should link to https://github.com/orgs/nodejs/teams/core/teams for a list of what we consider "subsystem teams"

**Comment by RaisinTen** [comment]
> https://github.com/orgs/nodejs/teams/core/teams

That page is not visible to people who are not members of the org, so they would have lesser time to decide which teams they would like to join. Previously, they had days to decide but if we do this, it would be a 15 minute window. This might not be a problem but I thought we should take that into consideration.

**Comment by mhdawson** [comment]
I don't think it should be a big deal if they have 15 mins to decide, they would have access after being a org member and could later ask to join a team?

**Comment by RaisinTen** [comment]
Sent https://github.com/nodejs/node/pull/44024 to fix the onboarding doc.

**Comment by mhdawson** [comment]
@RaisinTen thanks!

**Comment by UlisesGascon** [comment]
As agreed in #3299 I will close this issue.
