### ISSUE TITLE
Install docker on subset of test machines

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#301]
As discussed in latest build WG meeting, in order to be able to run tests on certains OS's (like Alpine - see https://github.com/nodejs/build/issues/75) we need docker to be installed on a subset of the test machines.

We should likely start by adding it as a dependency in Ansible for our ubuntu 14 machines which are fairly recent and which run docker well.

**Comment by jbergstroem** [comment]
quick question: how do we then automate installing alpine/similar on top of docker? is it part of the same build script?

**Comment by Vanuan** [comment]
@jbergstroem distribution installation is always a part of Dockerfiles. No ansible scripts needed. Here's a pull request that passes locally, but fails due to resource constraints:
https://github.com/nodejs/docker-node/pull/156

**Comment by Vanuan** [comment]
The problematic part is how to publish binaries from docker to dist/ archives.

**Comment by Vanuan** [comment]
So there are 4 dockerfiles needed:
1. Dockerfile that include build tools to build distributed binaries for each version (release delivery  to https://nodejs.org/dist/).
2. Dockerfile that include build tools to build distributed binaries for latest version (continuous delivery to  https://nodejs.org/dist/).
3. Dockerfile that include build tools and test tools to run tests (continuous integration)
4. Dockerfile that include binaries from https://nodejs.org/dist/ and deploy them to Docker Hub

**Comment by Vanuan** [comment]
Number 4 in that list is this: https://github.com/nodejs/docker-node/pull/156
But it should be triggered either regularly by the publish hook to https://nodejs.org/dist/

Number 3 is what this issue is for.

Number 1 & 2 should be handled in https://github.com/nodejs/build/issues/75

**Comment by Vanuan** [comment]
Number 3 is presumably being fixed by #437

**Comment by mhdawson** [comment]
I think this issue can be closed as the motivation was to get alpine runs into the ci and it looks like they are there.
