### ISSUE TITLE
azure win10 vs2019 machines have been timing out in debugger tests

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#3014]
See https://github.com/nodejs/reliability/issues/354 for reference, it seems the earliest CI run that exhibited this was https://ci.nodejs.org/job/node-test-binary-windows-js-suites/16283/, which is for a PR that hasn't landed rebased on top of a doc commit https://github.com/nodejs/node/commit/dcc9589e5ed36d511466fd43ea1f4b9c1f567899 so it might be infra issues.

**Comment by joyeecheung** [comment]
The daily master build on the commit prior to the doc commit was also green on those machines: https://github.com/nodejs/node/commit/5e57d24d325f0aea74394f78ebdc06857cca77b1

**Comment by joyeecheung** [comment]
I do not know how to log into those machines, but I suspect that there might be some stale Node.js processes running there that blocks the port 9229.

**Comment by richardlau** [comment]
I couldn't see any stale Node.js processes still running on [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/computer/test-azure_msft-win10_vs2019-x64-1/) or [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/computer/test-azure_msft-win10_vs2019-x64-2/) but I've just scheduled a reboot of both machines.

**Comment by joyeecheung** [comment]
The failures still showed up with https://github.com/nodejs/node/pull/44342, so there must be something else that is causing the time out. Also I noticed that this only happes with test-azure_msft-win10_vs2019-x64-1 and -2, the tests don't fail on -3.

**Comment by joyeecheung** [comment]
Looking at the build history, this seems to happen more with test-azure_msft-win10_vs2019-x64-1, and somewhat less frequently with -2. -3 and -4 seem to be immune to that.

**Comment by richardlau** [comment]
FWIW -1 and -2 did get rebooted (https://github.com/nodejs/build/issues/3014#issuecomment-1222306233) so whatever the problem is it has persisted, or recreated itself, across the reboot.

**Comment by joyeecheung** [comment]
Another observation: it seems sometimes these failures are accompanied by a few random failures from other tests that involve timeouts, e.g. sequential/test-heap-prof, parallel/test-child-process-exec-timeout, See https://github.com/nodejs/reliability/issues/354

**Comment by tniessen** [comment]
It's been failing almost every time, making it difficult to land PRs:

<p align="center">
<img alt="Windows build trend showing lots of failures" src="https://user-images.githubusercontent.com/3109072/186136415-0e324b29-953d-4f4b-a93c-5d987c4d603e.png">
</p>

**Comment by joyeecheung** [comment]
Looks like the flakes are now gone, the only recent repros in the reliability issues came from resumed builds. I'll close this issue.

**Comment by tniessen** [comment]
Thank you for working on this @joyeecheung :)
