### ISSUE TITLE
Access to Windows Server 2012 R2 VM

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#3018]
The PR https://github.com/nodejs/node/pull/44074 makes the `test-net-server-max-connections` flaky on `win2012r2-COMPILED_BY-vs2019-x86`. However, since I don't have that machine locally, I'd need to get access to a similar build to investigate this behaviour. Is that possible?

**Comment by mhdawson** [comment]
+1 from me. 

@joaocgreis can you help get access?

**Comment by RafaelGSS** [comment]
I got access internally. Thanks!
