### ISSUE TITLE
release jobs: compress document folder before scp:ing

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#302]
We're currently recursively scp:ing the doc folder when doing releases. If we tarball:ed it before copying it over we'd reduce the time taken dramatically.

**Comment by jbergstroem** [comment]
come to think of it: `rsync` would probably be even quicker.

**Comment by jbergstroem** [comment]
@rvagg do you see us generating docs from a windows box? I reckon rsync is baseline on every os we have as part of ci besides that.

**Comment by rvagg** [comment]
> do you see us generating docs from a windows box

no no no, no

**Comment by jbergstroem** [comment]
Ok, lets switch to rsync then.

**Comment by rvagg** [comment]
I still don't see what's wrong with `scp`

**Comment by jbergstroem** [comment]
Nothing wrong; its just the good 'ol :turtle: vs :rabbit2: :+1:

**Comment by jbergstroem** [comment]
Let me run a test or two to quantify

**Comment by rvagg** [comment]
when you compare it to the time it takes to run `PackageMaker` or watch the Windows linker at work, scp'ing docs is a trivial task and the slave that does that ends way before both the .pkg and .msi slaves, not to mention the arm slaves.

**Comment by jbergstroem** [comment]
`real    0m4.394s`

I'm just going to go with the kids and say "lol". The reason I started witch-hunt was because I saw the release job 'freezing' at this line. It was likely doing something post that line (compressing with xz or whatever). Closing.
