### ISSUE TITLE
node-test-binary-armv7l pending indefinitely: All nodes of label ‘ubuntu2004-armv7l’ are offline

### ISSUE THREAD

**Issue by tniessen** [nodejs/build#3022]
None of the `node-test-binary-armv7l` jobs started today have completed:

![build overview showing that none of the recent builds have completed](https://user-images.githubusercontent.com/3109072/187084162-cf0d4dd8-87a4-4493-92e4-b4f5ad805bed.png)

Each shows two jobs pending indefinitely.

**Comment by tniessen** [comment]
Jenkins shows: `All nodes of label ‘ubuntu2004-armv7l’ are offline`

**Comment by joyeecheung** [comment]
I wondered if we could just disable node-test-binary-armv7l  - but it looks like node-test-commit-arm is getting stuck, too, so if we disable them we won't have arm coverage in the CI

**Comment by joyeecheung** [comment]
Previous incidents: https://github.com/nodejs/build/issues/2894

**Comment by tniessen** [comment]
@nodejs/build This incident appears to have started more than 48 hours ago and is still ongoing.

None of the last 27 `node-test-commit-arm-fanned` jobs have completed. `node-test-pull-request` has also been blocked for more than 48 hours. Jenkins shows a build queue of 155 tasks.

**Comment by sxa** [comment]
I've brought https://ci.nodejs.org/computer/test%2Dequinix%2Dubuntu2004%5Fcontainer%2Darmv7l%2D2/ back online to start clearing the backlog - currently on job [#43454](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2004-armv7l/43454/) and there is a queue up to #43483 so it'll take a while to clear at about 20 minutes each. I'll close this issue and continue the analysis in the original issue to avoid fragmentation.
