### ISSUE TITLE
citgm-smoker-pipeline broken by Jenkins update

### ISSUE THREAD

**Issue by targos** [nodejs/build#3023]
Example:
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-pipeline/190/
https://ci.nodejs.org/job/citgm-smoker-nobuild/1365/console

```
08:12:19 Building remotely on [test-packetnet-ubuntu1804-x64-1](https://ci.nodejs.org/computer/test-packetnet-ubuntu1804-x64-1) (Ubuntu amd64-Ubuntu jenkins-workspace 18.04 amd64-Ubuntu-18.04 Ubuntu-18.04 amd64) in workspace /home/iojs/build/workspace/citgm-smoker-nobuild
08:12:19 using NODE_VERSION: [118, 49, 52]
08:12:19 sliced: 118, 49, 52]
08:12:19 split : [118,, 49,, 52]]
08:12:19 FATAL: For input string: "118,"
08:12:19 java.lang.NumberFormatException: For input string: "118,"
08:12:19 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
```

**Comment by targos** [comment]
@nodejs/jenkins-admins

**Comment by sxa** [comment]
https://github.com/nodejs/build/pull/3019/files was the fix used to fix what I believe was the same issue elsewhere so it's likely we'll need to change something to `new String(...)` here too.

**Comment by sxa** [comment]
Fix ready. I've modified the offending job to run from my branch in the meantime so that it hopefully won't constantly run red, but I'm still running some tests to verify that it does what it should.
