### ISSUE TITLE
Backups for benchmark data

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#303]
We will be capturing benchmark data daily into an mysql database on the benchmarking data machine.

What/where/how is the best place to backup up this data ?

**Comment by rvagg** [comment]
probably do a daily `mysqldump`, compress the output and we'll rsync it off the machine with the same ssh key we'll use to get the data onto the web. we don't have a clear strategy for this yet and are currently copying things between machines but we need to get more organised with backups from www, jenkins and now this.

**Comment by jbergstroem** [comment]
I'll have a think about backup over the weekend and put together my thoughts.

**Comment by mhdawson** [comment]
Sounds good.   As an FYI I'm away all next week so I won't respond to any comments until the week of the 25th.

**Comment by mhdawson** [comment]
Ok so backups are now setup to generate new back up in /home/benchmark/backups on the benchmark data machine

There will be 2 files in that directory:

backup-current - latest backup
backup-previous - backup from the previous day

**Comment by mhdawson** [comment]
@jbergstroem  can you let me know what I need to do to get these backup files mirrored into the overall backup solution you are working on in https://github.com/nodejs/build/issues/308

**Comment by jbergstroem** [comment]
@mhdawson my thoughts were to run mysqldump over the wire (see [this comment](https://github.com/nodejs/build/issues/308#issuecomment-173438546)). If you create a user that has read only access to the database and copy the backup pubkey from the secrets repo we should be ready to go.
