### ISSUE TITLE
Heads up of Node.js security releases 22nd September 2022 

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/build#3032]
As per the Node.js security release process this is the FYI that there is going to be a security release on 22nd September 2022.

**Comment by richardlau** [comment]
I'll lock the CI down tomorrow (21 September 2022).

**Comment by vdeturckheim** [comment]
Thanks @richardlau let me know if you want me to update the message in Jenkins when it is done and thanks a lot for opening the [discussion](https://github.com/orgs/nodejs/teams/collaborators/discussions/155)

**Comment by richardlau** [comment]
CI has now been locked down.

**Comment by vdeturckheim** [comment]
Some fixes of the security releases have been recently updated and the Node.js security team still needs an extra day of work to ensure the binaries are ready to release.
We would like to thank you for your patience and understanding.
The releases are now planned for September 23rd 2022.

This means the CI will need to stay under embargo for one extra day.

**Comment by vdeturckheim** [comment]
@richardlau the releases have been done, we can remove embargo. Thanks a lot!

**Comment by richardlau** [comment]
While the CI is locked down I'm going to try to swap over some servers that we need to migrate https://github.com/nodejs/build/pull/3036. Shouldn't take too long 🤞.

**Comment by richardlau** [comment]
CI is now unlocked.

FYI @nodejs/build I've swapped out the two jenkins-workspace machines that are data facilities earmarked for closure (https://github.com/nodejs/build/issues/3028) onto freshly created machines. This includes moving the binary temp git repository that was on jenkins-workspace-4 (test-packetnet-ubuntu1804-x64-1) to the new jenkins-workspace-7 (test-equinix-ubuntu2204-x64-1).
