### ISSUE TITLE
Jenkins is not starting any jobs, saying it is going to reboot, but not rebooting after an hour so far

### ISSUE THREAD

**Issue by Trott** [nodejs/build#3038]
From [Slack](https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1663977203167639):

> Anyone have an idea why Jenkins says it's going to be rebooted for around an hour now but hasn't gone down for the reboot but in the meantime is refusing to start new jobs?
> 
> Would hate for that to be the status through the weekend.....
> 
> If it goes on for a few hours, I might try rebooting it and hoping I don't make things worse. But I'll try to resist that terrible temptation.
> 
> I'll also put this in an issue.

**Comment by Trott** [comment]
Maybe related to https://github.com/nodejs/build/issues/3037?

**Comment by richardlau** [comment]
I requested a Jenkins restart -- it was waiting for the in progress jobs to finish.

**Comment by Trott** [comment]
Looks like it restarted.
