### ISSUE TITLE
Give @nodejs/npm similar ci access to Node.js collaborators

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#3040]
This is broken out from another discussion. I'd like to have the npm team get CI access so that they can do integration testing with CI + CITGM without requiring a commit bit. I'm thinking we could mimic the current permissions of Node.js collaborators to accomplish this (just make a new rule). Thoughts?

/cc @mhdawson

**Comment by joyeecheung** [comment]
+1 to giving the npm team CI access (this + triage access i.e. being able to add the commit queue label should be enough in most cases to land commits anyway).

**Comment by mhdawson** [comment]
+1 from me. I think helping the npm team run test across the platforms/operating system in our CI would be good and I think we can trust that team to do the right thing in terms of running Ci jobs.

**Comment by MylesBorins** [comment]
I can take the action item of setting this up in jenkins if folks have no concerns.

**Comment by MylesBorins** [comment]
It's been almost a week (and parental leave is looming), unless there is an objection I'm going to go ahead and setup these permission at the end of the day.

**Comment by MylesBorins** [comment]
I've gone ahead and updated permissions for @nodejs/npm to have CI access. Closing issue
