### ISSUE TITLE
Onboarding Stewart Addison to build-infra

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3041]
Checklist from https://github.com/nodejs/build/issues/2426

* [x] Add to secrets/build/infra, secrets/build/infra-mac and secrets/build/release
* [x] Add to admin@, accounts@ and build@ in email/iojs.org/aliases.json https://github.com/nodejs/email/pull/198
* [x] Github  team membership: Doc: https://github.com/nodejs/build/pull/3042
  * [x] nodejs/build-infra
  * [x] nodejs/jenkins-admins
  * [x] nodejs/jenkins-release-admins
* [ ] Optional but recommended: DigitalOcean team membership (I think our admin_logins.md is wrong, we give access via individual accounts to the team)
* [ ] Optional: IBM Cloud team membership
* [ ] Optional: Equinix team membership (we may have to request this if it's needed / wanted)
* [ ] Optional: add phone # to Apple root account for 2fa (must be done while in direct contact with someone who has access)
* [ ] Discuss relationship with the LF - expenses, helpdesk, other?
* Discuss donor relationships, contacts, limits, sensitivities, deals, etc.
  - [ ] DigitalOcean
  - [ ] Rackspace
  - [ ] MacStadium
  - [ ] IBM / Softlayer
  - [ ] Microsoft / Azure
  - [ ] Scaleway
  - [ ] Joyent
  - [ ] Cloudflare
  - [ ] OSUOSL
  - [ ] Equinix / ARM
  - [ ] nearForm
* Discuss various pieces of infra:
  - [ ] Primary www server - _lots to discuss, probably need to itemise some of this_
  - [ ] Backup www server / unencrypted
  - [ ] Backup server
  - [ ] ci and ci-release - including firewall, disk space management, .. other?
  - [ ] nearForm hosted servers (benchmark & Apple)
  - [ ] ARM cluster?
  - [ ] gh-bot
  - [ ] unofficial-builds
* [ ] Discuss release pipeline?

**Comment by targos** [comment]
@richardlau What's the status on this?

**Comment by richardlau** [comment]
This was done.
