### ISSUE TITLE
PSA: decommissioning of Node.js 12 infrastructure

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3048]
According to [`README.md`](https://github.com/nodejs/build/blob/main/README.md#ci-software) in this repository:
> The Build WG will keep build configuration required for a release line for 6 months after the release goes End-of-Life, in case further build or test runs are required. After that the configuration will be removed.

Node.js 12 went End-of-Life in April so we're approaching the end of the 6 month period and in all likelihood we're not going to be building Node.js 12 again. I plan to start cleaning up really old CI infrastructure that we kept around for Node.js 12 that is no longer used.

- [x] Disable https://ci.nodejs.org/job/node-daily-v12.x-staging/. This has been running daily to give some indication that the builds still work. Replace this with a daily job for v14.x so we're testing the earliest infrastructure we need to keep running.
- [ ] Identify and remove platforms from the CI that are no longer required for Node.js 14 onwards. This will help with things like https://github.com/nodejs/build/issues/3030 where End-of-Life operating systems do not provide later versions of Java in their package repositories.

**Comment by mhdawson** [comment]
Thanks for doing this.
