### ISSUE TITLE
Softlayer reboots

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#305]
Copy pasted message below. We'll be rebooting Saturday.

Our Systems Engineers have been notified of a potential vulnerability affecting Virtual Server Instances (VSIs). We have been working nonstop with our technology partners to prepare a remediation. The remediation will require maintenance to hypervisor nodes and a reboot of the virtual server instances on those nodes. Listed below you will find the master schedule for when maintenance will be applied on a data center basis. We will post real-time progress updates in the subsequent data center-specific maintenance notifications. Customers can watch those either via the portal, or via email (if subscribed). New Virtual Machines provisioned before the maintenance will be included in reboots.

#### Saturday, December 12
- 15:00 UTC - SYD01
- 17:00 UTC - HKG02
- 20:00 UTC - CHE01
- 23:00 UTC - AMS01

#### Sunday, December 13
- 00:00 UTC - LON02
- 04:00 UTC - SAO01
- 05:00 UTC - TOR01
- 06:00 UTC - DAL05
- 08:00 UTC - SJC01
- 14:00 UTC - MEL01
- 17:00 UTC - SNG01
- 23:00 UTC - FRA02

#### Monday, December 14
- 05:00 UTC - WDC01
- 06:00 UTC - DAL09
- 16:00 UTC - TOK02
- 23:00 UTC - PAR01

#### Tuesday, December 15
- 04:00 UTC - DAL06
- 05:00 UTC - MON01
- 05:00 UTC - WDC04
- 06:00 UTC - HOU02
- 08:00 UTC - MEX01
- 08:00 UTC - SEA01
- 23:00 UTC - AMS03

#### Wednesday, December 16
- 07:00 UTC - DAL01
- 08:00 UTC - SJC03
- 23:00 UTC - MIL01

**Comment by mhdawson** [comment]
? It says December ? 


Regards



Michael Dawson
 770 Palladium Drive

J9VM Software Developer
 Ottawa, Ontario K2B 8K1
Master Inventor
 Canada
QWM
 

IBM Software Group, Application and Integration Middleware Software
 

Phone:
+1-613-270-4793
 

e-mail:
michael_dawson@ca.ibm.com

**Comment by jbergstroem** [comment]
Haha; didn't even consider that -- just assumed it was related to the openssh issues that's been flying around. I will update this once I get a proper email.

**Comment by jbergstroem** [comment]
We passed the period. Closing.
