### ISSUE TITLE
V8 tests need svn installed 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#306]
Early work to enable V8 testing from the Node tree for https://github.com/nodejs/build/issues/199 shows that we need svn installed on the test machines

https://ci.nodejs.org/job/mdawson-RunV8TestsInNode/8/console

I checked on the machines where I had run the tests before and our internal machines were we (IBM) build v8 regularly and see that we do have svn installed.

Any objects to installing svn on the test machines.  If not I can go ahead and add it to the ansible templates.  Having done that do we need to re-image or would we just install by hand ?

**Comment by rvagg** [comment]
such pain ... we had to use svn in our internal CI system a while back and it was so painful that we ended up working around it completely. iirc Windows was the worst.

**Comment by jbergstroem** [comment]
Do we want to run v8 on all our test machines or a limited subset?

**Comment by mhdawson** [comment]
Unless there is a reason to avoid svn I'd think it would just be easier to enable on all machines as opposed to limiting to a subset.

**Comment by mhdawson** [comment]
PR here to start adding https://github.com/nodejs/build/pull/330
