### ISSUE TITLE
Heads up of Node.js security releases 3rd November 2022

### ISSUE THREAD

**Issue by juanarbol** [nodejs/build#3063]
Heads up of Node.js security releases 3 November 2022

As per security release process this is a heads up that there will be security releases 3 November 2022 and we'll need people from build to lock/unlock ci and to support and build issues we see.

**Comment by richardlau** [comment]
I'll be around to handle this.

**Comment by richardlau** [comment]
I've opened a PR to update the before/after security matrix for Jenkins to accommodate the recent addition of the npm team: https://github.com/nodejs/build/pull/3064

**Comment by richardlau** [comment]
CI has been unlocked.
