### ISSUE TITLE
ci.nodejs.org is down

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3065]
I’m seeing multiple ci failures on different pull requests including https://github.com/nodejs/node/pull/45294. 

And I’m seeing a Access denied on ci.nodejs.org 

Full message:

Access Denied

anonrig is missing the Overall/Read permission

**Comment by richardlau** [comment]
CI is currently locked down to prepare security releases and access is restricted until the releases are done: https://github.com/orgs/nodejs/teams/collaborators/discussions/158
