### ISSUE TITLE
Access to the node-test-commit-linux-containered/ubuntu1804_sharedlibs_zlib_x64/ machine

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#3066]
The CI is failing weirdly on this machine, I'd like to jump in and debug.

**Comment by richardlau** [comment]
@nodejs/build FYI I've added @RafaelGSS 's ssh key to test-digitalocean-ubuntu1804_docker-x64-2 to allow him to look at the failing sharedlib builds for the security release.

**Comment by RafaelGSS** [comment]
I think we can close this one. However, looks reasonable to create another one referring to `ccache` storing results for non-zero exit codes. We've faced this issue on the security release, where we were seeing constantly a linker error.

**Comment by richardlau** [comment]
Key has been removed from test-digitalocean-ubuntu1804_docker-x64-2.
