### ISSUE TITLE
No space left on Windows arm64 host

### ISSUE THREAD

**Issue by targos** [nodejs/build#3069]
https://ci.nodejs.org/job/node-compile-windows/47824/nodes=win-vs2019-arm64/

```
 error C2471: cannot update program database
```

https://ci.nodejs.org/job/node-compile-windows/47825/nodes=win-vs2019-arm64/

```
fatal error C1088: Cannot flush compiler intermediate file: 'C:\Users\ADMINI~1\AppData\Local\Temp\_CL_8e3d7aa8ex': No space left on device
```

**Comment by joaocgreis** [comment]
https://ci.nodejs.org/view/All/job/git-clean-windows/ was failing when the disk was already full. I fixed that, hopefully this issue is fixed and won't repeat.
