### ISSUE TITLE
ppcbe-fedora20 consistent pass on one host, consistent fail on the other

### ISSUE THREAD

**Issue by Trott** [nodejs/build#307]
It appears that  iojs-ibm-ppcbe-fedora20-64-1 passes Ci no problem but  iojs-ibm-ppcbe-fedora20-64-2 has the same three tests time out every time. Any idea what's up with that?

64-1 successes: 
* https://ci.nodejs.org/job/node-test-commit-plinux/895/nodes=ppcbe-fedora20/ 
* https://ci.nodejs.org/job/node-test-commit-plinux/899/nodes=ppcbe-fedora20/ 

64-2 failures: 
* https://ci.nodejs.org/job/node-test-commit-plinux/900/nodes=ppcbe-fedora20/ 
* https://ci.nodejs.org/job/node-test-commit-plinux/898/nodes=ppcbe-fedora20/ 
* https://ci.nodejs.org/job/node-test-commit-plinux/897/nodes=ppcbe-fedora20/

**Comment by jbergstroem** [comment]
The only difference I could find was a trailing npm process at 2 that's been running for a week and consuming all cpu at all cores. Sweet!

**Comment by Trott** [comment]
Looks like it's fixed. Thanks! I'm going to close this (because, hey, it can always be re-opened).
