### ISSUE TITLE
Request access to rhel8-x64 machines for @manekinekko

### ISSUE THREAD

**Issue by cjihrig** [nodejs/build#3070]
@manekinekko is working on creating a TAP parser in https://github.com/nodejs/node/pull/43525 and running into test flakiness (https://ci.nodejs.org/job/node-test-commit-linux/48328/nodes=rhel8-x64/testReport/junit/(root)/test/parallel_test_runner_run/). It would be nice if they could access the machine to try to debug.

**Comment by manekinekko** [comment]
Thanks @cjihrig!

**Comment by mhdawson** [comment]
Based on our governance (https://github.com/nodejs/build/blob/main/GOVERNANCE.md#temporary-access) we should answer these questions:

* Does the scope and size of the need justify providing access.
* Is the individual a Node.js collaborator? If so then access should be allowed provided the first point is satisfied.
* Length and consistency of involvement with Node.js working groups and/or community.
* Consequences to the individual in case of mis-behaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer? Would being banned from involvement in the Node.js community negatively affect them personally in some other way?
* Are there collaborators who work with the individual and can vouch for them.

@cjihrig would it be possible for you to fill that in?

**Comment by cjihrig** [comment]
> Does the scope and size of the need justify providing access.

I think so. I guess this is subjective.

> Is the individual a Node.js collaborator? If so then access should be allowed provided the first point is satisfied.

No

> Length and consistency of involvement with Node.js working groups and/or community.

Since early 2021, but somewhat inconsistent from what I can tell.

> Consequences to the individual in case of mis-behaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer? Would being banned from involvement in the Node.js community negatively affect them personally in some other way?

They work at Microsoft, so I think there would be consequences.

> Are there collaborators who work with the individual and can vouch for them.

@fhinkel?

@manekinekko let me know if I missed anything.

**Comment by manekinekko** [comment]
@cjihrig that's correct.

> Does the scope and size of the need justify providing access.

For context, I am unable to reproduce locally the failing test on Jenkins. 

If there is any other way to investigate those failing tests other than getting access to the CI machine, I am happy to figure out a different way (eg. I can spin up my own vm)

**Comment by cjihrig** [comment]
Closing. A stress test shows that access is probably not needed.
