### ISSUE TITLE
marked test-digitalocean-ubuntu1804-x64-1 as temporarily offline

### ISSUE THREAD

**Issue by Trott** [nodejs/build#3072]
Ref: https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1667755736836489

Builds are failing
e.g. https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu1804-64/48392/console
```
18:36:56 /home/iojs/build/workspace/node-test-commit-linux/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/statem/statem_srvr.o: In function `tls_process_client_key_exchange':
18:36:56 statem_srvr.c:(.text+0x5b89): undefined reference to `ossl_gost18_cke_cipher_nid'
18:36:56 statem_srvr.c:(.text+0x5ba3): undefined reference to `ossl_gost_ukm'
18:36:56 collect2: error: ld returned 1 exit status
18:36:56 deps/openssl/openssl-cli.target.mk:289: recipe for target '/home/iojs/build/workspace/node-test-commit-linux/out/Release/openssl-cli' failed
18:36:56 make[2]: *** [/home/iojs/build/workspace/node-test-commit-linux/out/Release/openssl-cli] Error 1
18:36:56 make[2]: *** Waiting for unfinished jobs....
```

**Comment by Trott** [comment]
Marking it offline seems to have forced jobs to use the Joyent host which is working.

**Comment by mhdawson** [comment]
@BethGriggs I thought from the earlier discussion it was just one of the container machines versus one of the 3 test machines that was causing the issue. Did I misunderstand ?

**Comment by mhdawson** [comment]
@BethGriggs thanks for the clarification.

**Comment by richardlau** [comment]
This is believed to be a poisoned ccache. 

I've logged onto the machine and tried to rebuild the node-test-commit-linux workspace. That failed with the link error. I then manually set [`CCACHE_RECACHE`](https://ccache.dev/manual/latest.html#_corrupt_object_files) to ignore previous compilation results. This build succeeded. 

Host has been reenabled and is building https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu1804-64/48621/

**Comment by richardlau** [comment]
Recent builds on this host have passed.
