### ISSUE TITLE
Request to join the Build WG

### ISSUE THREAD

**Issue by targos** [nodejs/build#3073]
👋🏻 I'm asking to become a member of the Build WG. In particular, I'd like to be able to help maintaining Jenkins, keep the infra up-to-date, investigate CI failures, etc.

**Comment by mhdawson** [comment]
As a long time TSC member and a very active collaborator in the project I think we should onboard @targos directly as build team member. @nodejs/build any concerns? Otherwise I think we should move forward once @richardlau is back next week.

**Comment by Trott** [comment]
+100 This makes me very happy.

**Comment by richardlau** [comment]
I've added @targos to the build team over in nodejs-private and added his gpg key to the same areas I have access to. Also added to the GitHub teams for Jenkins admin access and build-infra.

**Comment by targos** [comment]
Thanks 🙇🏻. Now the difficult part will be to find time to learn everything I need to be useful!

**Comment by targos** [comment]
Is there a 1Password vault or all secrets are in the secrets repo?

**Comment by richardlau** [comment]
> Is there a 1Password vault or all secrets are in the secrets repo?

For build they're all in the secrets repo.
