### ISSUE TITLE
Upgrade to gcc@4.9 in test-rackspace-centos7-x64-1 for libuv

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#3074]
So it doesn't [fail](https://ci.nodejs.org/job/libuv-test-commit-linux-cmake/1243/nodes=centos7-64/console).
```
11:02:04 make[2]: *** [CMakeFiles/uv.dir/src/unix/async.c.o] Error 1
11:02:04 make[2]: *** Waiting for unfinished jobs....
11:02:04 /home/iojs/build/workspace/libuv-test-commit-linux-cmake/nodes/centos7-64/src/unix/tty.c:25:23: fatal error: stdatomic.h: No such file or directory
11:02:04  #include <stdatomic.h>
11:02:04                        ^
11:02:04 compilation terminated.
11:02:05 /home/iojs/build/workspace/libuv-test-commit-linux-cmake/nodes/centos7-64/src/unix/tty.c:25:23: fatal error: stdatomic.h: No such file or directory
11:02:05  #include <stdatomic.h>
11:02:05                        ^
11:02:05 compilation terminated.
```
Thanks!

**Comment by richardlau** [comment]
Short of compiling gcc 4.9 from source I don't think it's going to be easy to get that onto our CentOS 7 machines. CentOS 7 defaults to gcc 4.8.5. On our CI we have developer toolsets 6 (gcc 6.3.1) and 8 (8.3.1) installed for various versions of Node.js -- would one of those versions suffice?

**Comment by bnoordhuis** [comment]
Either should suffice.  stdatomic.h was added in gcc 4.9.

**Comment by vtjnash** [comment]
bump?

**Comment by richardlau** [comment]
Updating the jobs to use devtoolset-8 on centos/rhel 7.

**Comment by richardlau** [comment]
Both test jobs passed, so I'll optimistically close this out.
