### ISSUE TITLE
`node-test-commit-custom-suites-freestyle` silently broken?

### ISSUE THREAD

**Issue by targos** [nodejs/build#3078]
It fails as yellow most of the time in less than two minutes while building `openssl-cli`. 

For example: https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/27943/console

```
10:29:12 /home/iojs/build/workspace/node-test-commit-custom-suites-freestyle/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/statem/statem_srvr.o: In function `tls_process_client_key_exchange':
10:29:12 statem_srvr.c:(.text+0x5b89): undefined reference to `ossl_gost18_cke_cipher_nid'
10:29:12 statem_srvr.c:(.text+0x5ba3): undefined reference to `ossl_gost_ukm'
10:29:12 collect2: error: ld returned 1 exit status
10:29:12 deps/openssl/openssl-cli.target.mk:289: recipe for target '/home/iojs/build/workspace/node-test-commit-custom-suites-freestyle/out/Release/openssl-cli' failed
10:29:12 make[2]: *** [/home/iojs/build/workspace/node-test-commit-custom-suites-freestyle/out/Release/openssl-cli] Error 1
```

**Comment by richardlau** [comment]
Two issues here:
- https://github.com/nodejs/build/issues/3072 (although that didn't have the example failure captured in the issue (I've now updated))
- For reasons I don't remember failures for the worker threads CI are treated as unstable rather than failures. Perhaps this is unnecessary now. 
![image](https://user-images.githubusercontent.com/5445507/202193516-11ed1a02-e547-4662-860c-1982f5549d8d.png)

**Comment by richardlau** [comment]
I've edited the job to remove the outdated checks that were setting an exit value of 2 and removed the "Exit code to set build unstable". 

Added a checkbox to enable `CCACHE_RECACHE` to be set and am rebuilding on the failing host ([test-ibm-ubuntu1804-x64-2](https://ci.nodejs.org/computer/test-ibm-ubuntu1804-x64-2/)) with it set: https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/27947/console

**Comment by richardlau** [comment]
Recent builds are green: 
![image](https://user-images.githubusercontent.com/5445507/202271721-c94b1e76-adfc-43b7-ae8a-77daf69ae688.png)
