### ISSUE TITLE
Backup - the complete edition

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#308]
Lets tackle this thing once and for all. I think there's three things we should accomplish with this issue; one being _how_ to backup, second _where_ and third _what_.

### How 

My preferred tool for managing backups is [rsnapshot](http://rsnapshot.org). It makes rotating daily/weekly/monthly a breeze and manages directory structures by hard symlinking stuff (meaning it doesn't store the same file twice). Not sure about options here, feel free to add your own. If we're backing up databases we can just pipe mysqldump/pg_dump to xz and store it in a folder.

If we were to use rsync, we'd create a specific backup ssh keypair and either create a user for backing up (forces us to run through permission) or use root (boo). 

#### Where

Luckfully the sponsors we have available to us have lots of storage. I'd like to avoid object storage since it makes using rsync harder. This means the best case scenario would be using a provider that allows us to grow a disk (no need to waste costs on 1T when we'd consume 50G). The option closest to mind would be smartos on joyent which through zones/zfs allows us to transparently (read: admin click) grow the disk. We should start with ~300G and try to expand around the 75% rule. A cron job that reminds us about disk consumption would likely be helpful.

#### What

Assuming I've forgotten most stuff, here's what we want to store:

 - nodejs/iojs www
   - copy of `/home/www` - so we quickly can redeploy as well as archiving binaries
   - `/var/log/nginx/*` - this is already logrotated
 - jenkins host
   - `/var/lib/jenkins` - this is a tricky one. I'd like to make exceptions for all build history -- this accumulates around 170G at the moment.
  - `/var/log/nginx/jenkins-access.log` access logs for jenkins
 - benchmarking host
   - mysqldump of raw data

Please add more here -- I'd personally like to avoid backing up stuff we can regenerate; but if it saves us time it might be worth it.

##### Open questions

 - (jenkins host) where do we store /etc/defaults/jenkins? suggesting part of ansible scripts
 - (www host) how do we treat the cold storage in /home/nodejs/cloudfuse?

I can attempt to PR an ansible playbook that would set up this host at joyent (and edit hosts to copy ssh key/modify permission as needed) after we've agreed on what path we should choose.

**Comment by jbergstroem** [comment]
To elaborate on the jenkins folder; this is the storage distribution:
```bash
$ /var/lib/jenkins# du -d1 -h .
60K	./secrets
8.0K	./userContent
1.2M	./logs
684K	./nodes
12M	./fingerprints
872K	./config-history
168G	./jobs
1.3M	./updates
2.0M	./users
8.0K	./init.groovy.d
128M	./plugins
168G	.
```

The job folders looks slightly different depending on what plugin we call the through (axis, multijob, etc) but the gist of a job would look something like this:
```bash
$ /var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes# ls -al centos5-32/builds/1834/
total 2396
drwxr-xr-x    3 jenkins jenkins    4096 Jan 16 01:40 .
drwxr-x--- 1829 jenkins jenkins   32768 Jan 18 22:03 ..
-rw-r--r--    1 jenkins jenkins  671595 Jan 16 01:40 build.xml
-rw-r--r--    1 jenkins jenkins     734 Jan 16 01:31 changelog.xml
-rw-r--r--    1 jenkins jenkins    1616 Jan 16 01:40 injectedEnvVars.txt
-rw-r--r--    1 jenkins jenkins 1725938 Jan 16 01:40 log
drwxr-xr-x    2 jenkins jenkins    4096 Jan 16 01:40 tap-master-files
```

I'll experiment a bit with exports, but I wouldn't have a problem with excluding everything sans `$job/config.xml` (which is the config for that job) as part of the backup job.

**Comment by jbergstroem** [comment]
#### Some kind of actionlist/todo/work in progress/god knows

Outstanding:
 - [ ] create backup keys/users
 - [ ] decide how to handle old jobs in jenkins before we write backup scripts

##### cold storage things:
 - /home/jenkins/old jenkins.tar.xz which lives at new ci host
 - /var/log/nginx/old which contains old nginx access logs for nodejs

##### key parts of rsnapshot.conf
```ini
link_dest	1

interval	daily		7
interval	weekly		4
interval	monthly		12

rsync_long_args	--timeout=300 --delete --numeric-ids --no-relative --delete-excluded --no-owner --no-group
ssh_args	-F /path/to/ssh-config-with-hosts-and-keys

backup_script	/path/to/below/database-script.sh						db/
backup			user@www-host:/var/log/nginx/nodejs.org-access.log*		logs/nodejs
backup			user@www-host:/var/log/nginx/iojs.org-access.log*		logs/iojs
backup			user@www-host:/var/log/nginx/libuv.org-access.log*		logs/iojs
```

##### database backup script
```bash
#!/bin/bash

ARGS="-F /path/to/ssh-config-for-db"
DB_ARGS="--single-transaction --extended-insert=FALSE -u backup_user"
DATE=$(date '+%Y%m%d@%M%S')

ssh ${ARGS} ${host} "mysqldump ${DB_ARGS} ${database} | xz -c" > benchmark-${DATE}.tar.xz
```

**Comment by jbergstroem** [comment]
Quick update; I've got a server running on joyent where I've now copied the cold storage stuff. The readme currently contains:

#### nodejs backup directory

This folder contains both 'cold storage' files/folders as well as periodically synced content (generated by [rsnapshot](http://rsnapshot.org)).

Try to keep the list of items up to date since this likely still stay manual.

##### Table of contents

| filename                            | description                                             |
|-------------------------------------|---------------------------------------------------------|
| archive/                            | a folder meant for cold storage; ie no periodic updates |
| archive/nodejs-logs                 | contains compressed logfiles from the old nodejs server |
| archive/old-jenkins.tar.xz          | a full copy of jenkins pre-security-vulnerability       |

**Comment by mhdawson** [comment]
+1 for rsync for backups, I like it and use it at home.  

One suggestion is that we might want to have 2 copies with different providers.  Once we have it setup for 1 it should be trivial to add the other. 

That way if we have issues with one provider we
 * can still carry on doing backups with the other provider
 * can still restore from the other provider



I'm assuming that storage in the vms (ex joyent) is not backed-up/guaranteed  to be available.

**Comment by jbergstroem** [comment]
@mhdawson i'm all for it. Not sure which vm provider to use; 500G+ is starting to be expensive (I guess that's when providers want you to go to object storage).

**Comment by rvagg** [comment]
Additional directories on nodejs.org we need to save:

* /home/dist/nodejs/ (binaries, vital, most important thing we can save!)
* /home/dist/iojs/ (binaries)
* /home/dist/metrics/ (questionable, they are generated from the log files but can take a day or more to generate, nearly 10G atm)
* /home/nodejs/old/ (historical stuff from Joyent server, worth keeping, won't ever change though)
* /home/libuv/www/dist/

I'm also a fan of just bundling up and storing /etc/ since it's so small and often contains stuff that you wish you kept but didn't realise wasn't stored anywhere else.

**Comment by rvagg** [comment]
also note the `libuv` -> `iojs` in the config you posted @jbergstroem 

```
backup          user@www-host:/var/log/nginx/nodejs.org-access.log*     logs/nodejs
backup          user@www-host:/var/log/nginx/iojs.org-access.log*       logs/iojs
backup          user@www-host:/var/log/nginx/libuv.org-access.log*      logs/iojs
```

**Comment by jbergstroem** [comment]
@rvagg correct indeed -- poor copy paste. I'll post the final config here before the actual rsync. I reckon we'll want to keep access logs indefinitely.

**Comment by mhdawson** [comment]
Some data from discussion with jbergstroem
1) a softlayer vm with 1TB storage 1CPU and 1GB ram is only $82/month + $45 to take traffic from 250G to 1T per month
2) a softlayer dedicate machine with 2 500GB disks is $180/month, probably also additional $ for traffic over 250G
3) softlayer network storage with low i/o speed is $150/month for 1T

I'm thinking 1) might be a reasonable option for one of the mirrors.

**Comment by rvagg** [comment]
@jbergstroem I'm +1 on your suggested approach and am keen for you to move forward in the way you see appropriate, I'd like to have a look after the fact to sanity check that we're getting what we need backed up. I have no opinion on _where_ it should be backed up to except that it'd probably be good if we didn't do it in DO and probably not in Rackspace either cause of our existing high usage level. So Softlayer or Joyent or .. whatever, great.
Let me know where I can help along the way!

**Comment by jbergstroem** [comment]
Thanks, @rvagg. I'll file a PR with the config once I move closer. And yeah, review is much appreciated.

Also, just so I don't forget:
 - [ ] exclude jenkins workspaces (currently 60G) from rsync

**Comment by jbergstroem** [comment]
Fyi - while testing/running a rsync with exclude [`rsync --exclude "workspace*" -avz -e ssh foo@bar:/var/lib/jenkins .`] on our current setup (33 days of jobs) ended up consuming 53Gb. Once I get all variations of build folders (there's a few) we'll be slightly smaller.

**Comment by jbergstroem** [comment]
@rvagg one thing that' id appreciate some help with would be doing some kind of inventory of what we want to back up (and possibly how long -- I can for instance see how we'd never want to have release tarballs as part of a 1y backup rotation) for the www-host.

**Comment by jbergstroem** [comment]
@rvagg does this mean we don't care about cloudfuse stuff?

**Comment by rvagg** [comment]
I think it best to consider cloudfuse a failed experiment. I'm not happy with the reliability of the fuse mount nor the fact that it's a pure object-store that can't deal with fs metadata so that all gets lost.

**Comment by jbergstroem** [comment]
Moar:
- [ ] run "delete-jobs" as part of a (successful) rsync from rsnapshot
- [ ] back up the new jenkins release-master

**Comment by jbergstroem** [comment]
Just an update -- will file a PR after I've sorted reloading jenkins after the cleanup job (needs github credentials). Here's the latest readme which should cover what we're doing at the moment:

---

# nodejs backup directory

This folder contains both 'cold storage' files/folders as well as
periodically synced content [generated by rsnapshot].

Try to keep below up to date.

### servers that are actively backed up

 - ci.nodejs.org: the main jenkins server. full backup of /var/lib/jenkins (rotated)
 - ci-release.nodejs.org: release jenkins server. full backup of /var/lib/jenkins (rotated)
 - iojs-softlayer-benchmark: benchmark server. mysql dump (rotated)
 - iojs-www: www server for nodejs.org/iojs.org.
   - /home/dist/iojs: all artifacts for iojs.org (mirror, no rotation/deletion)
   - /home/dist/nodejs: all artifacts for nodejs.org (mirror, no rotation/deletion)
   - /home/libuv/www/dist: all artifacts for libuv.org (mirror, no rotation/deletion)
   - /var/log/nginx: all logs for nodejs, iojs and libuv (rotated)

### table of contents

| filename                            | description                                             |
|-------------------------------------|---------------------------------------------------------|
| archive/                            | archived content                                        |
| archive/nodejs-logs                 | contains compressed logfiles from the old nodejs server |
| archive/old-jenkins.tar.xz          | a full copy of jenkins pre-security-vulnerability       |
| mirror/                             | backed up content indended for non-rotation             |
| periodic/                           | periodically updated storage managed by rsnapshot       |
