### ISSUE TITLE
macstadium macos11 immediate closed connection 

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3084]
I try to connect to `test-macstadium-macos11.0-arm64-3` and `test-macstadium-macos11.0-arm64-4` but the connection is closed right after has been stablished. I don't see nothing weird in the logs, just after the passphrase the connection is closed 
```
➜  ~ ssh test-macstadium-macos11.0-arm64-3 -vvv
OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/vlixes/.ssh/config
....
Enter passphrase for key '/Users/vlixes/.ssh/nodejs_build_test':
debug3: send packet: type 50
Connection closed by 207.254.38.86 port 22
```

Not sure if it is a misconfiguration in my local machine or a remote machine issue. Other ssh connections are working fine, including `test-nearform-macos11.0-arm64-1`.

**Comment by targos** [comment]
I believe this is fixed?

**Comment by UlisesGascon** [comment]
I just did a test few minutes ago:
- `test-macstadium-macos11.0-arm64-4` keep closing the connection once stablished
- `test-macstadium-macos11.0-arm64-3` is asking for plain pass in state of the ssh key (this is new). I checked my local settings and the ssh/config is the same for both. I tried some pass from secrets repo inventory and it didn't work

**Comment by richardlau** [comment]
If we can't get into these, do we need to rebuild them?

**Comment by UlisesGascon** [comment]
🎉 Both machines are now online and the **new credentials** are working. 

I am closing this issue, as the re-ansible steps are managed in this one https://github.com/nodejs/build/issues/3179#issuecomment-1421499359
