### ISSUE TITLE
Automated monthly contribution reports

### ISSUE THREAD

**Issue by mikeal** [nodejs/build#309]
For several repos (core and the website at the very least) it would be great to have an issue posted each month with an automated contribution report.

@bengl just wrote a great module that will help :) https://github.com/bengl/contribution-report

**Comment by jbergstroem** [comment]
@mikeal are you referring to the build group creating a monthly report or do mean that the script should be hosted as part of the build repo?

**Comment by mikeal** [comment]
We just need it to run in an automated way and post an issue each month, so we need some scripts somewhere in cron with a github token that can post the issues.

**Comment by jbergstroem** [comment]
gotcha. we'll deploy something somewhere once the scripts are in place.

**Comment by jbergstroem** [comment]
@mikeal is there a PR/issue somewhere to track progress of scripts?

**Comment by mikeal** [comment]
huh?

**Comment by jbergstroem** [comment]
@mikeal as I understood it, we were to deploy scripts that generated the contribution reports which is why I asked if these are stored/written somewhere else.

**Comment by mikeal** [comment]
ahhh. no, i wrote some code as a one-off for a few reports. nothing has been written to the https://github.com/bengl/contribution-report module and nothing has been written yet that will actually log the issue.

**Comment by mikeal** [comment]
awesome :)

**Comment by maclover7** [comment]
ping -- is this still needed?

**Comment by gibfahn** [comment]
Seems like a job for @nodejs/automation 😁 .

**Comment by ev1stensberg** [comment]
I can help out with this if wanted

**Comment by joyeecheung** [comment]
@ev1stensberg The previous effort seems to be stalled so I'd say go ahead!

**Comment by ev1stensberg** [comment]
Awesome, will pick it up during the weekend @joyeecheung 👍

**Comment by ev1stensberg** [comment]
Where do you want the script for this placed? Which repo?

**Comment by gibfahn** [comment]
@ev1stensberg probably nodejs/automation would be the best place for it.

**Comment by joyeecheung** [comment]
@ev1stensberg If the automation repo is going to be the monorepo, mind that https://github.com/nodejs/automation/pull/9 is trying to use lerna to manage things...

**Comment by ev1stensberg** [comment]
May be better to setup monorepo first, and then add respective folders @joyeecheung ?

**Comment by joyeecheung** [comment]
@ev1stensberg You don't have to wait for that really, I think we are going to migrate existing repos to the monorepo anyway with git subtrees (if we are going to have a monorepo at all)

**Comment by maclover7** [comment]
Going to close this for now, nothing really actionable here. As far as I can tell, there has not been a real need for this lately. Please reopen if I am incorrect, although there may be a better repo for this issue to live in.
