### ISSUE TITLE
Rename macOS machines for macOS 11 and higher

### ISSUE THREAD

**Issue by targos** [nodejs/build#3091]
https://ci.nodejs.org/label/11.6/

**Comment by AshCripps** [comment]
likely an auto generated label - there are some plugins thats generate labels based on what os the machine reports as etc. so that machine is likely running macos 11.6.

**Comment by targos** [comment]
Ah, I see. So should we rename the nodes to remove the version number after the dot if it can be updated?

**Comment by AshCripps** [comment]
Not really sure if theres any value in that - we only use the labels we add manually im not actually sure why we have the auto ones ive always ignored them.

**Comment by targos** [comment]
Yeah, but my point is that `test-nearform-macos11.0-arm64-1` is confusing. I thought it was locked to 11.0, but it can actually be on a higher version.
There's even `test-orka-macos11-x64-1` without the `.0` so the naming is also inconsistent.

**Comment by AshCripps** [comment]
oh yeah that was my mistake when I added that machine apple werent very clear what the naming scheme would be arm was 11 but intel was 10.16 so I thought the arm OS would go 11.1 11.2 like the 10.x but not long after they merged it all to 11 and then the later versions become 12, 13 etc. So I agree we should fix that.

**Comment by targos** [comment]
I'd still like to do it.
