### ISSUE TITLE
Limit jenkins job history

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#311]
I'd like to add [another plugin](https://wiki.jenkins-ci.org/display/JENKINS/Discard+Old+Build+plugin) to jenkins (yay) so we can control how many jobs we should have laying around. At the moment we're consuming ~150gb which essentially consists of artefacts (think releases, test output, ..) and build logs. There's no real reason to keep this for old builds since we're moving so fast. Also, it makes backups (#308) very painful. 

I'd like to enable the plugin and experiment with having ~30 failed builds and 20 successful builds for every job type. Thoughts?

**Comment by bnoordhuis** [comment]
Seems fine to me.  If there is a way to make it time-based, i.e. number of days, that's arguably a little more convenient than number of builds.

**Comment by jbergstroem** [comment]
Yeah, you can combine both days and no of builds (including type of build status). Check the plugin page for a few combinations.

**Comment by bnoordhuis** [comment]
Yes, I saw that.  I mean making it time-based if that's not too onerous on storage requirements.

**Comment by jbergstroem** [comment]
Right now we have unlimited. Since November 11 we've grown with 70G; so just using that timespan we'd go from ~150G storage to <50G.

**Comment by jbergstroem** [comment]
How about we start with 30 days on all jobs and tweak as we go?

**Comment by jbergstroem** [comment]
I'm not sure; but I suspect reducing job history will have a positive outcome on java memory consumption (based on what I've seen in memory dumps). Does anyone think this is a bad idea? Different limits? cc @nodejs/build

**Comment by joaocgreis** [comment]
30 days might even be too much for successful/unstable builds, so sure, go ahead. For failed builds I'd be comfortable with 180 days. I understand that might not have a huge impact given the amount of failed builds we have, so go with 30 days on all jobs and perhaps open an issue in the main repo to warn collaborators. Is it possible to keep a single backup of everything, made when this plugin is enabled?

**Comment by mhdawson** [comment]
One option we have used is to delete the generate artifacts for builds that pass at the end of the job.  That would let us have a longer history.

**Comment by jbergstroem** [comment]
@mhdawson job history is likely related to the recent jenkins slowness. I'd like to cut that down if we don't really use it.

**Comment by jbergstroem** [comment]
@joaocgreis the plan was to back everything up before activating the job.

**Comment by joaocgreis** [comment]
Sounds like a good plan then!

**Comment by jbergstroem** [comment]
I'll proceed with this in the coming days. Hopefully we'll get a more performant jenkins as a result.

**Comment by jbergstroem** [comment]
Proceeding with this now. I'll go with 30 days or keeping 10 builds and see how we go. Might be good to have some history for tooling surrounding CI.

**Comment by jbergstroem** [comment]
There doesn't seem to be a "minimum amount of builds to keep" which is what I was gunning for. I'll leave it at 30 days for now and see if we can get upstream to add it.

**Comment by jbergstroem** [comment]
I'm pretty sure that didn't work as intended. I added a post-build task to the `node-test-pull-request` job that were supposed to discard all type of builds older than 30 days. I ended up with 4 visible jobs through ci and 8 jobs on disk:
```
drwxr-xr-x  2 jenkins jenkins  4096 Jan 15 19:34 1257
drwxr-x---  2 jenkins jenkins  4096 Aug 23 07:13 133
drwxr-xr-x  2 jenkins jenkins  4096 Jan 25 12:46 1370
drwxr-xr-x  2 jenkins jenkins  4096 Jan 27 14:21 1397
drwxr-xr-x  2 jenkins jenkins  4096 Jan 27 17:07 1405
drwxr-xr-x  2 jenkins jenkins  4096 Jan 27 17:38 1406
drwxr-xr-x  2 jenkins jenkins  4096 Nov 10 16:41 693
drwxr-xr-x  2 jenkins jenkins  4096 Nov 10 18:52 697
lrwxrwxrwx  1 jenkins jenkins     4 Jan 27 14:21 lastFailedBuild -> 1397
lrwxrwxrwx  1 jenkins jenkins     4 Jan 27 17:38 lastStableBuild -> 1406
lrwxrwxrwx  1 jenkins jenkins     4 Jan 27 17:38 lastSuccessfulBuild -> 1406
lrwxrwxrwx  1 jenkins jenkins     4 Jan 25 12:46 lastUnstableBuild -> 1370
lrwxrwxrwx  1 jenkins jenkins     4 Jan 27 14:21 lastUnsuccessfulBuild -> 1397
-rw-r-----  1 jenkins jenkins     0 Jul  7  2015 legacyIds
```

I can't identify a reliable pattern as to what that plugin decided to do; so I'm going to rsync the job history back and reload jenkins. My next step is manually deleting jobs on disk and see how that works. I'm starting to suspect that we'll be more reliable writing some bash scripts for this.

**Comment by jbergstroem** [comment]
After further tinkering; deleting stuff in job folders (slightly different based multijob or no) and reloading the jenkins configuration seems to work fine. I'll put some scripting together and post it here for review; hopefully we can get a pretty quick LGTM so we can also establish that reducing job history will have a positive impact on jenkins performance.

**Comment by jbergstroem** [comment]
Also, reloading jenkins configuration from disk doesn't seem to affect the running state (builds or jobs in queue) so adding a reload at the end of the cronjob/however we choose to deploy seems to be a winning combo.

**Comment by jbergstroem** [comment]
So, how about something like:
```bash
#!/bin/sh
DAYS=30
ROOTDIR=/var/lib/jenkins/jobs
JOBS=$ROOTDIR/*/builds/
MULTIJOBS=$ROOTDIR/*/configurations/axis-nodes/*/builds/
# append when sure: -exec rm -rf "{}" \;
find $JOBS $MULTIJOBS -maxdepth 1 -type d -mtime +$DAYS
curl https://ci.nodejs.org/reload # including magic session somehow
```

**Comment by jbergstroem** [comment]
Was hoping for jenkins accepting a unix signal for reloading disk but no. It'll have to be token based and sincewe run the github auth plugin we'll have to control tokens from there. The alternative would be restarting but that's not graceful.

**Comment by rvagg** [comment]
You're going to need `-mindepth 1` in there as well to avoid it matching actual `build` directories as it does now for older jobs, and just to be safe.

**Comment by jbergstroem** [comment]
@rvagg yep, I noticed that but jenkins doesn't really mind if the folder doesn't exist (just creates one) which is why I left it. I'll update.

**Comment by joaocgreis** [comment]
LGTM. According to the man page, that will only delete files modified exactly 30 days ago, so this needs to run everyday. We can safely assume that happens for now, but it would be nice to find a better solution.

Suggestion: I would make a simple log of what's being deleted, something like:

```diff
 MULTIJOBS=$ROOTDIR/*/configurations/axis-nodes/*/builds/
+LOGDIR=$ROOTDIR/log
+LOGFILE=$LOGDIR/histclean_$(date -u +"%Y%m%d-%H%M%SZ").log.xz
-# append when sure: -exec rm -rf "{}" \;
+# append when sure: -print -exec rm -rf "{}" \; |& xz > $LOGFILE
 find $JOBS $MULTIJOBS -maxdepth 1 -type d -mtime +$DAYS
```

**Comment by rvagg** [comment]
The `+` prefix for `$DAYS` turns it in to "more than `$DAYS`", without it, it would mean "exactly `$DAYS`".

**Comment by jbergstroem** [comment]
@joaocgreis got this error: `./test.sh: 10: ./test.sh: Syntax error: "&" unexpected`. I've saved a list of all deleted folders for now.

**Comment by joaocgreis** [comment]
@jbergstroem you're using dash, ` |& ` is not available there. Replace it by ` 2>&1 | `, that should work.

**Comment by jbergstroem** [comment]
@joaocgreis yeah; I just saved it separately in the name of progress. I'll spend some more time on a cron job and post it in a PR later.

**Comment by jbergstroem** [comment]
todo: needs axis jobs as well.

**Comment by jbergstroem** [comment]
I think we should run this as a post-script in the backup routine. That way we'll make sure whatever's deleted remains in backup as part of the rotation.

**Comment by jbergstroem** [comment]
This was implemented as part of the backup routine. Closing.

**Comment by joaocgreis** [comment]
@jbergstroem the axis jobs are accumulating, what about something like `find $ROOTDIR -name builds -type d -exec find '{}' -mindepth 1 -maxdepth 1 -type d -mtime +$DAYS \;` ?
