### ISSUE TITLE
Request access to benchmark CI

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3118]
Our benchmark CI runs on Ubuntu 16.04 and my pull request to add `simdutf` had a vague issue. I'd like to get access to the machine to understand the root cause of the issue.

Referencing https://github.com/nodejs/node/pull/45803#issuecomment-1355593507

**Comment by sxa** [comment]
Added key to anonrig@92.51.196.115 ([test-nearform_intel-ubuntu1604-x64-2](https://ci.nodejs.org/computer/test-nearform_intel-ubuntu1604-x64-2)) so you should be able to log in there, although @targos has marked it offline in jenkins for an upgrade so it's availability may not be clear :-)

**Comment by targos** [comment]
This machine is longer running on Ubuntu 16.04. I started upgrading it to 18.04 yesterday (https://github.com/nodejs/build/pull/3122)

**Comment by anonrig** [comment]
I don't have access anymore. Would someone be able to add me back? @nodejs/build

**Comment by targos** [comment]
What do you need access for?

**Comment by anonrig** [comment]
@targos Run benchmarks specifically for URL parser, as well as understand the architecture/processor of the benchmark CI machine.

**Comment by targos** [comment]
> Run benchmarks specifically for URL parser

Can't you use the existing CI job(s) for that?

> understand the architecture/processor of the benchmark CI machine

Hardware is described here: https://github.com/nodejs/build/issues/791#issuecomment-316206973

Note that the machine is [currently offline](https://github.com/nodejs/build/issues/3149#issuecomment-1408606045), so that explains why you can't access it.

**Comment by anonrig** [comment]
> Can't you use the existing CI job(s) for that?

Unfortunately, going through the flow of CI jobs while trying to improve a certain part of Node is too time-consuming and having direct access to the resources (where the user does not have the necessary computing power to run the benchmark) will resolve the friction of contributing to performance-critical problems in Node.js
