### ISSUE TITLE
Ansible Jenkins macos10.x machines challenges

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3119]
When We were working on #3112, I discovered that Ansible scripts are not working properly for `macos10.14` and `macos10.15`.

The first time I tried to run the script I got an error related to brew cask:
```
TASK [package-upgrade : Add AdoptOpenJDK Java Repo] *********************************************************************************************************
ok: [test-orka-macos10.14-x64-2]

TASK [package-upgrade : Update Casks]  

...
Deleted Formulae\npython\n\nYou have 12 outdated formulae and 1 outdated cask installed.\nYou can upgrade them with brew upgrade\nor list them with brew outdated.\n\nError: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead."}
```

In the next attempt the script stops at this stage:

![Captura de Pantalla 2022-12-17 a las 11 05 24](https://user-images.githubusercontent.com/5110813/208240949-bf1f4c8a-b90d-402e-b446-2f7b1d0a557e.png)

I can confirm that the playbook works perfect for `macos11` machines.

**Comment by targos** [comment]
I'm pretty sure that's because of https://github.com/nodejs/build/issues/3087
