### ISSUE TITLE
Update Nearform mac minis to supported macOS

### ISSUE THREAD

**Issue by targos** [nodejs/build#3121]
They are currently still on 10.14. I'm updating them to 10.15 using the ISO we have for the VMs.

For later versions, I think we need to be careful because of VMware support:

Status:
- NodeMacMini1: Update to macOS 13 (Ventura) and VMware Fusion 13 Pro finished.
- NodeMacMini2: Update to macOS 13 (Ventura) and VMware Fusion 13 Pro finished.

<details>

<summary>
https://kb.vmware.com/s/article/2088571
</summary>

![image](https://user-images.githubusercontent.com/2352663/208294439-58d954fe-1fb2-4305-9ec8-9c1af9a6e471.png)

</details>

If I understand the table correctly, we will need a license for a more recent version of Fusion (ideally 13.x).
Do we have a free license? How can we get one for a newer version?

**Comment by targos** [comment]
Ping @AshCripps @rvagg based on the discussion in https://github.com/nodejs/build/issues/1695

**Comment by AshCripps** [comment]
We did not have a free license we had Brian purchase it for us from the foundation for both machines. I do remember there being something on those machines some time ago about updating the version is that possible? I dont know if the license is a "license to use this thing" or a "license to use this thing at x version"

**Comment by targos** [comment]
This is what I see on the machines:
![image](https://user-images.githubusercontent.com/2352663/208442746-1818ff49-98db-4370-b1f9-aa4e9202d97a.png)

"Learn More..." opens the VMware store in Safari.

**Comment by mhdawson** [comment]
I don't have insight into whether we need a new licence for VMware fusion or not (hopefully at most an upgrade?). If we do we can talk to the Foundation about paying for what is needed.

**Comment by targos** [comment]
We need a to buy new license (don't know if need the "pro" or "player" version). There's an upgrade discount for because we have a valid license for version 11.

**Comment by targos** [comment]
@mhdawson 
> can you confirm we need 2 licences (one for each Mac at NearForm).

I'm not sure. I just checked on both Macs and it seems that they are configured with the same license key.

**Comment by mhdawson** [comment]
From here I guess it comes down to whether what we are doing is considered commercial or not -https://kb.vmware.com/s/article/80561#:~:text=VMware%20Fusion%20for%20personal%20use%3A&text=You%20may%20install%20and%20use,that%20you%20own%20or%20control.

For non-commercial it can be installed on up to 3 machines.

@targos have you seen any info on our vmware licences in the files in the secrets repo that cover the mac or admin setups?

**Comment by targos** [comment]
> have you seen any info on our vmware licences in the files in the secrets repo that cover the mac or admin setups?

I don't remember seeing anything, but I haven't searched for it specifically.

**Comment by lukeschantz** [comment]
Please forward me any license info or email records you have and I will figure out how to handle the upgrades. lschantz@linuxfoundation.org

**Comment by lukeschantz** [comment]
Thank you @targos for forwarding that information.  I have made a ticket to purchase the VMWare upgrade and will report back when it is complete.

**Comment by lukeschantz** [comment]
Checking into see if anyone has the account information that was used to purchase the VMWare Fusion license.  As it is not managed by LF IT.  Also, I was not able to upgrade that the license from the account associated with my email.  Would be great if someone could provide the login credentials or at very least which email was used.  Please advise. In the meantime I am going to reach out to Brian Warner and see if recalls the account info as it is not in our password vaults.  Additionally, I did make a ticket with VMWare but it has been a day and I haven't gotten a reply.

**Comment by lukeschantz** [comment]
Good news.  I heard back from VMWare and Brian Warner.  We are in the midst of attempting to transfer the license which is locked in an account with a depreciated email address.  If we can't transfer it in a reasonable period of time; I  will buy a fresh license.

**Comment by lukeschantz** [comment]
Upgrade is complete!  Same serial for 2 seats of the license.

**Comment by targos** [comment]
Thank you!

**Comment by targos** [comment]
I was able to update NodeMacMini2 smoothly: Catalina (10.15) to Monterey (11) using the "Install macOS Monterey" app, then Monterey to Ventura (12.1) using regular Software Update. I then installed VMware Fusion 13 Pro with the new license key.
I'll put the VMs back online in a couple of hours and I'll let a few builds run on them before doing the same with the other mac mini.

**Comment by targos** [comment]
Update finished on both macs. Thanks everyone!
