### ISSUE TITLE
Recreate `test-nearform-macos10.15-x64-3`

### ISSUE THREAD

**Issue by targos** [nodejs/build#3124]
The VM has been unable to boot for some time, so I deleted it and created a new one from scratch.

I expect difficulties to bring it to a good state, because macOS 10.15 is no longer supported by Apple and Homebrew.

Done:
- Install Command line tools for XCode (manually, the install script run by Ansible was hanging)
- Install Homebrew

Current status:
- Finished

**Comment by targos** [comment]
Well, it seems to have worked! The node is online: https://ci.nodejs.org/computer/test-nearform-macos10.15-x64-3/

**Comment by UlisesGascon** [comment]
Great work @targos !! 🎉
