### ISSUE TITLE
nearform release macos 10.15 disk full

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3132]
e.g. https://ci-release.nodejs.org/job/iojs+release/nodes=osx1015-release-tar/9021/console
```
06:00:15 Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url https://github.com/nodejs/node.git" returned status code 255:
06:00:15 stdout: 
06:00:15 stderr: error: could not lock config file .git/config: No space left on device
```

**Comment by targos** [comment]
`Xcode.app` uses almost 10GB. Is it necessary for releases?

**Comment by targos** [comment]
I restarted the VM. It now has 5.3Gi available and is back online.

**Comment by richardlau** [comment]
> `Xcode.app` uses almost 10GB. Is it necessary for releases?

Full Xcode is needed for releases for notarization. It's documented under https://github.com/nodejs/build/blob/main/ansible/MANUAL_STEPS.md#macos-release-machines. We may need to do those steps on the orka macOS 10.15 VM when we bring it back -- I don't remember if the base image has that set up.
