### ISSUE TITLE
Access to Windows 10 vs2019

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#3137]
Hi!

Can I get access to a windows 10 machine? I need to investigate https://ci.nodejs.org/job/node-test-binary-windows-js-suites/18388/console

**Comment by mhdawson** [comment]
@joaocgreis is that something you can help with?

**Comment by mhdawson** [comment]
+1 in terms of giving access @RafaelGSS is on the TSC and giving access to investigate a machine is covered by https://github.com/nodejs/build/blob/main/GOVERNANCE.md#special-access-requests

**Comment by StefanStojanovic** [comment]
@RafaelGSS you should have an email with credentials to a machine you can use. Please let me know when you're no longer using it, or if you have any issues. Thanks!

**Comment by RafaelGSS** [comment]
> @RafaelGSS you should have an email with credentials to a machine you can use. Please let me know when you're no longer using it, or if you have any issues. Thanks!

Hi Stefan! I've just received it. But, I'll only use it next week. Thank you!

**Comment by StefanStojanovic** [comment]
Hi @RafaelGSS. Do you still need the machine created for this investigation?

**Comment by RafaelGSS** [comment]
Oh, sorry! I don't need it anymore. Thank you!

**Comment by StefanStojanovic** [comment]
OK. Machine deleted.
