### ISSUE TITLE
windows-update-reboot fails since Dec 24

### ISSUE THREAD

**Issue by targos** [nodejs/build#3138]
https://ci.nodejs.org/job/windows-update-reboot/

**Comment by targos** [comment]
Error:

```
10:00:16 nasm v2.16.01 [Approved]
10:00:16 nasm package files upgrade completed. Performing other installation steps.
10:00:17 Installing 64-bit nasm...
10:00:18 nasm has been installed.
10:00:18 ERROR: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'NewName'. Specified method is not supported.
10:00:18 The upgrade of nasm was NOT successful.
10:00:18 Error while running 'C:\ProgramData\chocolatey\lib\nasm\tools\chocolateyinstall.ps1'.
```

**Comment by targos** [comment]
nasm 2.16.01 was released on 2022-12-21.

**Comment by targos** [comment]
The chocolatey package was updated on 2022-12-23: https://community.chocolatey.org/packages/nasm

**Comment by targos** [comment]
How do you connect to the Windows machines? I tried ssh but it doesn't seem to work.

**Comment by targos** [comment]
I think the problem is here:


https://github.com/teknowledgist/Chocolatey-packages/blob/69d6ca2ec3d4dcdbb1ed5d746fefbd750ad4e349/automatic/nasm/tools/chocolateyinstall.ps1#L30-L31

There are probably two folders that match `Netwide Assembler*`

**Comment by richardlau** [comment]
> How do you connect to the Windows machines? I tried ssh but it doesn't seem to work.

RDP. `ansible/playbooks/write-ssh-config.yml` will write config for Remmina but if you want to use another RDP client the usernames and passwords are in the inventory files in the secrets repository.

**Comment by joaocgreis** [comment]
I've uninstalled and re-installed nasm on all machines, the job is passing now.

I don't know what will happen when a new version of the package is released, might make sense to report the issue.

**Comment by targos** [comment]
OK thank you @joaocgreis. I think we can close this for now.

**Comment by targos** [comment]
It's broken again.

**Comment by joaocgreis** [comment]
Fixed by changing the script to uninstall and install nasm as separate steps if it fails to update. Ideally, the issue would be fixed upstream, but this was what was possible to do now.
