### ISSUE TITLE
Membership audit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#3144]
The beginning of the year is a good time to do a membership audit.  @nodejs/build please comment if you plan to be active in 2023 or not.  We will try to collect the responses and move people who are not going to be active to emeritus by the end of the month.

[@AshCripps](https://github.com/AshCripps) - Ash Cripps
[@jbergstroem](https://github.com/jbergstroem) - Johan Bergström
[@joaocgreis](https://github.com/joaocgreis) - João Reis
[@joyeecheung](https://github.com/joyeecheung) - Joyee Cheung
[@mhdawson](https://github.com/mhdawson) - Michael Dawson
[@MylesBorins](https://github.com/MylesBorins) - Myles Borins
[@node-forward-build](https://github.com/node-forward-build) - node-forward build infrastructure
[@phillipj](https://github.com/phillipj) - Phillip Johnsen
[@richardlau](https://github.com/richardlau) - Richard Lau
[@rvagg](https://github.com/rvagg) - Rod Vagg
[@Starefossen](https://github.com/Starefossen) - Hans Kristian Flaatten
[@sxa](https://github.com/sxa) - Stewart X Addison
[@targos](https://github.com/targos) - Michaël Zasso
[@Trott](https://github.com/Trott) - Rich Trott
[@UlisesGascon](https://github.com/UlisesGascon) - Ulises Gascón

**Comment by mhdawson** [comment]
I plan to be active.

**Comment by targos** [comment]
I plan to be active.

**Comment by richardlau** [comment]
I plan to be active.

**Comment by rvagg** [comment]
~active(ish), I would probably be fine with stepping away from this but I think there's too much context in my head to disappear; I still keep an eye on what's going on and drop in where I see the need but am decreasing my involvement over time

**Comment by phillipj** [comment]
I probably won't contribute actively, but happy to answer if there's questions/help needed regarding the github-bot or related GitHub Actions.

**Comment by UlisesGascon** [comment]
I plan to be active.

**Comment by sxa** [comment]
Active

**Comment by Trott** [comment]
Active-ish. You can remove me if it's helpful to do so.

**Comment by jbergstroem** [comment]
I am changing jobs; will probably make a return March.

**Comment by AshCripps** [comment]
I plan to be around somewhat.

**Comment by mhdawson** [comment]
Based on the responses we should move the following people to emeritus. We can always add them back if they should in the active list:

[@joyeecheung](https://github.com/joyeecheung) - Joyee Cheung
[@phillipj](https://github.com/phillipj) - Phillip Johnsen
[@Starefossen](https://github.com/Starefossen) - Hans Kristian Flaatten

**Comment by mhdawson** [comment]
PR for move to emeritus - https://github.com/nodejs/build/pull/3369

**Comment by mhdawson** [comment]
@UlisesGascon will do the GPG steps
@ Michael will do the other steps

**Comment by MylesBorins** [comment]
You can move me to emeritus

**Comment by jbergstroem** [comment]
I think its time for me to move into emeritus as well.

**Comment by mhdawson** [comment]
Audit and moves to emeritus complete, closing.
