### ISSUE TITLE
Request: don't rerun flakes on Resume Builds

### ISSUE THREAD

**Issue by cjihrig** [nodejs/build#3147]
Is it possible to change the behavior of Resume Builds to only re-run non-flaky failures and count the flaky failures as passed?

**Comment by targos** [comment]
IIUC, the "Resume Build" feature comes from the [Multijob plugin](https://github.com/jenkinsci/tikal-multijob-plugin) (deprecated btw).

I don't see any configuration option that seems relevant to your request.

/cc @richardlau ?

**Comment by richardlau** [comment]
I'm not aware of anything either.

**Comment by cjihrig** [comment]
That's unfortunate. I'll close this out then.
