### ISSUE TITLE
Nearform machines are offline

### ISSUE THREAD

**Issue by targos** [nodejs/build#3149]
I'm unable to connect to it using VNC. The other machine is reachable and it looks like it was rebooted yesterday.

**Comment by targos** [comment]
The benchmark machines are also down:
![image](https://user-images.githubusercontent.com/2352663/211346916-8d6ef0b6-c4b1-4d9c-be60-7bb2d413e70a.png)

**Comment by targos** [comment]
@RafaelGSS maybe you can help? I don't know who at NearForm can fix this or how to contact them.

**Comment by efrisby** [comment]
Hi, there seems to have been a power outage and they haven't come back online. We are getting someone into HQ to resolve this as soon as possible. Thanks

**Comment by mhdawson** [comment]
@richardlau do we have the current contact at NearForm documented somewhere in the build repo (I'm asking since I know you've contacted them in the past)?  If not that might make sense for cases like this.

**Comment by richardlau** [comment]
@mhdawson I've updated the encrypted admin_logins file in the secrets repo.

**Comment by efrisby** [comment]
Hi, the two NearForm intel servers are now online, the devices needed to be physically powered on, looks like a power failure in the building and they failed to come back on. If any issues let me know. Thanks

**Comment by targos** [comment]
Perfect, thank you!

**Comment by targos** [comment]
It happened again. The macs are online (I set them up to restart automatically after power failure) but the intel machines aren't.

**Comment by targos** [comment]
Ping @efrisby

**Comment by anonrig** [comment]
From @targos's previous tag, I assume that the benchmark machine is considered a Nearform machine. @nodejs/build Is there any update or plan to bring it back online? It plays a crucial part in the @nodejs/performance team. Can we prioritize this issue and add `build-agenda` label to this issue?

**Comment by targos** [comment]
The benchmark machines are both online. All Nearform machines are online now so I'll close.
