### ISSUE TITLE
GitHub OAuth permissions for CI

### ISSUE THREAD

**Issue by roth-mike** [nodejs/build#3150]
This is my first time contributing to node and saw that the GitHub CI application asks for organization access as well as team boards which feels unnecessary. I guess it's logical that Node.js to check that I'm in Node.js organization but it's quite suspicious that it asks for team board permission as shown in the screenshot below.

![Google Chrome_20230109_v0955 2](https://user-images.githubusercontent.com/22750062/211352773-ab88ff29-0bb1-4d6b-b7b5-b310c1d8a065.png)

**Comment by targos** [comment]
We need to access team membership. Permissions in Jenkins are based on that.

**Comment by UlisesGascon** [comment]
I also think that the permission requested are correct, base on the recommendation.

I will close the issue. @roth-mike, feel free to reopen the issue if you have more questions 😉.
