### ISSUE TITLE
Cloud flare health monitor notification update required.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#3153]
Message from Cloudflare

Hi,

We will soon be migrating Load Balancing Health Monitor notification setup to Cloudflare’s centralized Notifications Service. Your Cloudflare account(s) NodeJS have domain(s) with existing Health Monitor notifications that need to be migrated.

This change will not affect your existing Health Monitor configurations. It only affects existing Health Monitor notifications for pool or origin health changes. For help migrating your notifications, refer to our [help documentation](https://developers.cloudflare.com/load-balancing/reference/migration-guides/health-monitor-notifications/).

What is changing and why?

Cloudflare’s account-level Notifications Service is now the centralized location for most Cloudflare services. In the interest of consistency and streamlined administration, we are moving Load Balancing Health Monitor notifications to Cloudflare’s Notifications Service. This change also gives you more options for notification delivery through the use of Webhooks and will allow users to tie multiple Pools to the same notification. The new notifications will be managed at the account level instead of zone-level.

Migration Timeline

Over the next six (6) months, we will support the legacy system, giving you time to transition your Health Monitor notifications to Cloudflare’s Notifications Service. Customers can expect the following timeline for the phasing out of existing Health Monitor notifications:
For now, customers subscribed to legacy emails will continue to receive them unchanged, so any parsing infrastructure will still work. From within a Load Balancing Pool, you will see two options for configuring notifications: the legacy format and a deep link to the Notifications dashboard. We highly recommend to begin moving your notifications over to the new system! We will send a reminder once a month each month for the next six months.
On January 23rd, 2023, we will disable the legacy method for the configuration of email notifications within Load Balancing Pools.
On March 21st, 2023, we will stop sending legacy emails. Adding new emails at the `/notification_email` endpoint will no longer send email notifications for health changes for your pools and/or origins.
We strongly encourage all you to [migrate your existing Health Monitor notifications](https://developers.cloudflare.com/load-balancing/reference/migration-guides/health-monitor-notifications/) to Cloudflare’s centralized Notifications Service within this timeframe to avoid lapses in alerts.

**Comment by mhdawson** [comment]
I'll take a look at adjusting the configuration

**Comment by mhdawson** [comment]
Ok, I updated the notifications to use the new approach and notifications should now be going to the build@iojs.org email

**Comment by targos** [comment]
Do we really care about these alerts? They are already quite noisy.

**Comment by rvagg** [comment]
yeah, but they shouldn't be - we shouldn't get any notifications if things are going well but they don't go well and that's a persistent problem that should be fixed

IMO there's something wrong with the main DO server and it gets locked up occasionally under relatively high load when it should be able to handle it. I think I recall looking into this and seeing IRQ or DMA errors or something in the system logs which were out of place. They coincided with rsync jobs too I think, something about the filesystem conflicting with .. I don't know. But it's not healthy and maxxes out when it should have capacity.
