### ISSUE TITLE
`v8-canary` builds are not promoted

### ISSUE THREAD

**Issue by targos** [nodejs/build#3155]
`12:03:04 scp -p node-v20.0.0-v8-canary20230118b1865daaaf-linux-x64.tar.xz node-www:nodejs/custom/v20.0.0-v8-canary20230118b1865daaaf/node-v20.0.0-v8-canary20230118b1865daaaf-linux-x64.tar.xz`

The last build to be in the correct folder is https://nodejs.org/download/v8-canary/v20.0.0-v8-canary202212266b2b946a63/

**Comment by targos** [comment]
I don't know how it's supposed to work. The build from 20221226 was also copied to this `custom` folder, so the problem is somewhere else.

https://ci-release.nodejs.org/job/iojs+release/9034/nodes=rhel8-x64-release/console

**Comment by richardlau** [comment]
@targos It's supposed to be done by the [promotion scripts](https://github.com/nodejs/build/tree/main/ansible/www-standalone/tools/promote) which run on the web server:

https://github.com/nodejs/build/blob/5c30993afb9ce5a91ec9d99de3b213f825603988/ansible/www-standalone/tools/promote/promote_nightly.sh#L40-L44

https://github.com/nodejs/build/blob/5c30993afb9ce5a91ec9d99de3b213f825603988/ansible/www-standalone/tools/promote/settings#L16-L18

**Comment by targos** [comment]
@richardlau thanks! I just tried to run the promotion script manually and it gave me this error:

```
Promoting v20.0.0-v8-canary20230106a9a748cca4/node-v20.0.0-v8-canary20230106a9a748cca4-x86.msi...
Promoting v20.0.0-v8-canary20230106a9a748cca4/win-x64...
cp: cannot create regular file '/home/dist/nodejs/v8-canary/v20.0.0-v8-canary20230106a9a748cca4/win-x64/node.lib': File exists
cp: cannot create regular file '/home/dist/nodejs/v8-canary/v20.0.0-v8-canary20230106a9a748cca4/win-x64/node_pdb.7z': File exists
```

So I deleted `/home/dist/nodejs/v8-canary/v20.0.0-v8-canary20230106a9a748cca4/`

Running the script again fails with `/home/dist/nodejs/v8-canary/v20.0.0-v8-canary20230112987ab62287` (it didn't try to promote the release from 20230106 this time...

Should I continue to remove the problematic folders and rerun?

**Comment by richardlau** [comment]
@targos Do you know if the script is already running in the background (it's on a cron timer)? `File exists` sounds like something already tried to promote the build.

**Comment by richardlau** [comment]
On the other hand I don't suppose it's the end of the world if we do (accidentally) remove v8 canary builds 🙂.

FWIW we have [another script](https://github.com/nodejs/build/blob/5c30993afb9ce5a91ec9d99de3b213f825603988/ansible/www-standalone/resources/scripts/dist-perms) which changes the owner of the files under `/home/dist` that are older than a week https://github.com/nodejs/build/pull/2020. This may account for some permission issues as the promote script is run as `dist`.

**Comment by targos** [comment]
> 

Yeah, but the weird thing is that these folders aren't visible on the website.

**Comment by targos** [comment]
```
# ps aux | grep promote | grep -v grep
dist     20194  0.0  0.0   4500   556 ?        Ss    2021   0:00 /bin/sh -c    /home/staging/tools/promote/promote_nightly.sh nodejs
dist     20196  0.0  0.0  13104  2092 ?        S     2021   0:00 bash /home/staging/tools/promote/promote_nightly.sh nodejs
dist     23099  0.0  0.0  12812  1664 ?        S     2021   0:00 bash /home/staging/tools/promote/_resha.sh nodejs /home/dist/nodejs/v8-canary v18.0.0-v8-canary202112276385a63910
```

I killed these but being from 2021 they're certainly unrelated

**Comment by richardlau** [comment]
@targos Direct or via the CloudFlare CDN (i.e. nodejs.org)? There's a five minute delay for CF as we invalidate the CF CDN cache on a five minute timer (if we queue a CDN purge).

**Comment by targos** [comment]
@richardlau via the CDN. Direct shows them 👍🏻 

I ran the promotion script again (without deleting anything else) and it finished without errors 🤷🏻
