### ISSUE TITLE
Windows machines all offline

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3160]
A small sampling of the build history for the machines indicates that https://ci.nodejs.org/job/windows-update-reboot/2230/ was the last job ran, and for the ones I looked at in Jenkins that job run updated the Java Temurin package:

e.g. https://ci.nodejs.org/job/windows-update-reboot/2230/label=test-azure_msft-win2016_vs2017-x64-3/console
```
Progress: 100% - Completed download of C:\Users\zaerwujhppwk\AppData\Local\Temp\1\chocolatey\Temurin17\17.0.6.1000\OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10.msi (160.19 MB).
09:01:09 Download of OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10.msi (160.19 MB) completed.
09:01:13 Hashes match.
09:01:13 Installing Temurin17...
09:01:16 FATAL: command execution failed
09:01:16 java.nio.channels.ClosedChannelException
```

cc @StefanStojanovic @joaocgreis

**Comment by joaocgreis** [comment]
Looks like the JVM tried to update without stopping Jenkins, and it didn't go too well. I rebooted the machines and they seem good now, so hopefully that's it. Let's see if this was a one-time thing or if it'll happen in future updates...

Thanks for the ping @richardlau !
