### ISSUE TITLE
`node-test-binary-windows-native-suites` broken on `test-azure_msft-win10_vs2019-x64-2`

### ISSUE THREAD

**Issue by targos** [nodejs/build#3174]
It fails always: https://ci.nodejs.org/computer/test-azure_msft-win10_vs2019-x64-2/builds

**Comment by targos** [comment]
I always struggle to understand what makes a Windows job actually fail.

Example job: https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win10-vs2019-COMPILED_BY-vs2019/16544/console

**Comment by targos** [comment]
@nodejs/platform-windows

**Comment by anonrig** [comment]
This issue blocks https://github.com/nodejs/node/pull/46410. (cc @lemire)

**Comment by richardlau** [comment]
> I always struggle to understand what makes a Windows job actually fail.
> 
> Example job: https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win10-vs2019-COMPILED_BY-vs2019/16544/console

Relevant bits from the job log:
```console
23:03:43 > taskkill /t /f /fi "IMAGENAME eq node.exe" 
23:03:43 ERROR: The process with PID 8712 (child process of PID 7420) could not be terminated.
23:03:43 Reason: There is no running instance of the task.
...
23:03:44 > git clean -dffx 
23:03:44 warning: failed to remove Release/node.exe: Invalid argument
23:03:44 warning: failed to remove test/addons/cpu-profiler-crash/build/Release/binding.node: Invalid argument
```
This usually means there's a running process left behind on the machine which is preventing git from cleaning the checkout. I'm not sure what `taskkill` cannot kill it.

I've logged into the machine with RDP (using Remmina) and can see via Task Manager that there is indeed a Node.js process running while no build is in progress. 
![image](https://user-images.githubusercontent.com/5445507/216977505-fd1d0050-7e7c-410b-8bc5-2b6bc67ae7cc.png)
I've killed the process via "End task". 

Another (more drastic) option may be to run https://ci.nodejs.org/view/housekeeping/job/windows-update-reboot/ and force the machine to reboot which would also make the running Node.js process go away.

**Comment by richardlau** [comment]
Well https://ci.nodejs.org/job/node-test-binary-windows-native-suites/16628/nodes=win10-vs2019-COMPILED_BY-vs2019/ ran on the machine and failed with an actual test failure.

**Comment by joaocgreis** [comment]
Looking at https://ci.nodejs.org/computer/test-azure_msft-win10_vs2019-x64-2/builds , I believe @richardlau fixed this.
