### ISSUE TITLE
Investigate Jenkins OAuth permissions caching

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#318]
romankl has had trouble with his Jenkins access, being denied proper collaborator access even though he's a collaborator.  After deleting his OAuth token it now works. It seems that Jenkins may be catching GitHub teams. 
If this is the case then we should either find a way to fix that so users can move in and out of teams and have Jenkins recognise the switch or make it part of onboarding that you should delete your token of you gave one. 

It seems like a bit of a security oversight for Jenkins to not be checking teams with each login. This isn't something that should be cached.

**Comment by jbergstroem** [comment]
Anyone with interest in some java digging should perhaps have a quick look in the $source and file an upstream bug?

**Comment by maclover7** [comment]
ping -- is this still needed?

**Comment by gibfahn** [comment]
@refack did your jenkins-admins upgrade work okay? If so then I think this can be closed.

**Comment by refack** [comment]
Mine, and I assume @maclover7 and @joyeecheung's ass well. So closing
