### ISSUE TITLE
Any help needed?

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3182]
Hi @nodejs/build ,

I'm quite frustrated with the flaky tests & broken CI machines and come to a conclusion to get out of my comfort zone to learn as much as I can, to resolve as much as problems as possible. 

The question is: What can I do to help?

**Comment by UlisesGascon** [comment]
I will love to help here, I have access to all the test machines and I can provide you support.

**Comment by mhdawson** [comment]
In terms of flaky tests it's not necessarily build related, its looking at the tests and fixing the test themselves.

In terms of CI machine issues, would be great if you two want to see what you can do to improve.

**Comment by vtjnash** [comment]
I will put out an idea / request again to get rr working on the CI bots, where supported. We do it for JuliaLang projects and it has let us catch and fix many one-in-1000 type of flaky bugs that previously plagued CI reliability.
