### ISSUE TITLE
Question: musl (Alpine) Support Tier

### ISSUE THREAD

**Issue by jackson-miller-tbol** [nodejs/build#3183]
Please forgive me if this is the wrong place to post this question.

My company is having a discussion on the proper way to use node in our containers and the current [support tier](https://github.com/nodejs/node/blob/main/BUILDING.md#platform-list) for Alpine came up.  I was surprised to see it in Experimental given how prominent it seems to be.

I found a comment on [the Platform Requirements for 17.x issue](https://github.com/nodejs/build/issues/2740#issuecomment-911111958_) that talked about how it may already qualify for Tier 2, but how there was still need for dedicated support owners.  I couldn't find anything newer on this, has there been any change here?

Thanks

**Comment by mhdawson** [comment]
Nothing changed as far as I know. It's experimental and I don't know of people stepping up to change that.
