### ISSUE TITLE
Heads up of Node.js security releases 14 Feb 2023

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#3186]
As per security release process this is a heads up that there will be security releases 14 Feb 2023 and we'll need people from build to lock/unlock ci and to support and build issues we see.

The request is to lock down the CI immediately as the Releasers need more time to prep/validate the changes in the security release than normal. We understand this will impact collaborators but the agreement was that it is necessary this time in order to hit our target date.

**Comment by mhdawson** [comment]
@richardlau FYI

**Comment by richardlau** [comment]
CI has been unlocked: https://github.com/orgs/nodejs/teams/collaborators/discussions/162/comments/3
