### ISSUE TITLE
jenkins: git issues

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#319]
A few of our most common "infra-related errors" is tied to fetching git. We should try and update the jenkins-related plugins to see if it helps. Since our strategy is to hold off updating plugins (and jenkins in general) I'd like the go-ahead from others to see how it goes.

**Comment by rvagg** [comment]
fine by me, I think @joaocgreis is the one impacted here most since some of his setup is the reason we're holding off

**Comment by jbergstroem** [comment]
I recall part of reason for avoiding future updates was issues related to updating the multijob plugin. The sad part here is that there seems to be 10+ issues filed upstream and main author hasn't done anything about it in months. I think we have other issues with the multijob plugin at the moment since a lot of the older jobs seems to have issues (see 'old data' through jenkins settings). Basically Choose Your Null Pointer Exception.

**Comment by jbergstroem** [comment]
Here are the plugins I want to update:
<img width="879" alt="screen shot 2016-02-01 at 12 07 00 pm" src="https://cloud.githubusercontent.com/assets/176984/12706576/5888d832-c8dc-11e5-93ba-81e1cac2ee21.png">

**Comment by rvagg** [comment]
I don't recall any concerns with those ones if you want to upgrade selectively

**Comment by jbergstroem** [comment]
Yes, that'd be the plan. I just did a full backup and will try updating/restarting shortly

**Comment by jbergstroem** [comment]
..and updated. Doesn't seem to be any issues at least: https://ci.nodejs.org/job/node-test-commit/2017/

**Comment by jbergstroem** [comment]
still no issues. Closing. Please reopen if you find anything related to git.
