### ISSUE TITLE
coverage website returns `403 Forbidden`

### ISSUE THREAD

**Issue by targos** [nodejs/build#3190]
Reported by @anonrig on Slack

Example: https://coverage.nodejs.org/coverage-1579ff4f95f01237/index.html
Last good page (2022-12-31): https://coverage.nodejs.org/coverage-4830a6cf2aa14144/index.html

The permissions on the newer folders are different:
```
# ls -lh | grep 1579ff
drwx------ 2 nodejs nodejs 4.0K Feb  2 16:59 coverage-1579ff4f95f01237
# ls -lh | grep 4830a6c
drwxr-xr-x 3 nodejs nodejs  20K Jan  2 04:27 coverage-4830a6cf2aa14144
```

**Comment by mhdawson** [comment]
So the issue of needing to clear out data could explain why no results since the 2nd, but not the 403 issue

**Comment by richardlau** [comment]
> So the issue of needing to clear out data could explain why no results since the 2nd, but not the 403 issue

The 403 errors will be because of the permissions difference that @targos mentions in the issue description. Why there is a permissions difference would need investigation... it may be related to one of the rsync processes being unable to complete.

**Comment by richardlau** [comment]
coverage.nodejs.org [now redirects to codecov.io](https://github.com/nodejs/build/pull/3145#discussion_r1197985902). We're no longer maintaining our own coverage website.
