### ISSUE TITLE
Access to ARM Debug

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#3202]
May I have access to the following machine https://ci.nodejs.org/job/node-test-commit-arm-debug/6439/?

I would like to investigate why it's failing as OOM. Reference PR: https://github.com/nodejs/node/pull/44004

**Comment by richardlau** [comment]
I've added @RafaelGSS 's ssh key to the docker host test-equinix-ubuntu2004-docker-arm64-1.

@RafaelGSS the debug build runs in a container. Log into the docker host machine:
```console
ssh root@145.40.81.219
```
then enter the container (for https://ci.nodejs.org/job/node-test-commit-arm-debug/6439/nodes=ubuntu2004_debug-arm64/ this ran in `test-equinix-ubuntu2004_sharedlibs_container-arm64-3`):
```console
docker exec -it node-ci-test-equinix-ubuntu2004_sharedlibs_container-arm64-3 bash
```

Once inside the container, change into the workspace directory:
```console
cd /home/iojs/build/workspace/node-test-commit-arm-debug
```

You can see the failures running the full test command:
```console
/usr/bin/python3 tools/test.py -j 16 -p tap --logfile test.tap --mode=debug --flaky-tests=dontcare  default pummel addons js-native-api node-api benchmark 
```
or without the test runner (note the Debug version of `node` is used -- the failure doesn't occur if `out/Release/node` is used):
```console
~/build/workspace/node-test-commit-arm-debug$ ./out/Debug/node --experimental-permission --allow-fs-read=* --allow-child-process test/para
llel/test-permission-deny-child-process.js
FATAL ERROR: v8::Array::Cast Value is not an Array
 1: 0xaaaae121c2b8 node::DumpBacktrace(_IO_FILE*) [./out/Debug/node]
 2: 0xaaaae131eab0 node::Abort() [./out/Debug/node]
 3: 0xaaaae131f87c node::OOMErrorHandler(char const*, v8::OOMDetails const&) [./out/Debug/node]
 4: 0xaaaae1606290 v8::Utils::ReportApiFailure(char const*, char const*) [./out/Debug/node]
 5: 0xaaaae11d2030 v8::Array::Cast(v8::Value*) [./out/Debug/node]
 6: 0xaaaae11dc1c0 v8::Local<v8::Array> v8::Local<v8::Array>::Cast<v8::Value>(v8::Local<v8::Value>) [./out/Debug/node]
 7: 0xaaaae149e538  [./out/Debug/node]
 8: 0xaaaae16d6ba4 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [./out/Debug/node]
 9: 0xaaaae16d745c  [./out/Debug/node]
10: 0xaaaae16dab7c v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [./out/Debug/node]
11: 0xaaaae26e1bcc  [./out/Debug/node]
Aborted (core dumped)
```

**Comment by RafaelGSS** [comment]
@richardlau I've fixed the issue. Thank you!

**Comment by richardlau** [comment]
Key has been removed from the docker host and the container reenabled in the CI.
