### ISSUE TITLE
test-rackspace-win2012r2_vs2015-x64-1 marked offline for repeated failures

### ISSUE THREAD

**Issue by Trott** [nodejs/build#3208]
See https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1677423083098439 for context and https://ci.nodejs.org/computer/test-rackspace-win2012r2_vs2015-x64-1/ for the current offline/online status of the node. I took it offline to see if the problem was that particular node or not, and it seems like it is, because a re-run of the job on test-rackspace-win2012r2_vs2019-x64-2 finally passed.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/718899/221429218-de336123-6132-4ba2-ac6c-b882981451f1.png">

**Comment by joaocgreis** [comment]
I believe I got this fixed, there was a node process stuck on the machine. Might be related to https://github.com/nodejs/build/issues/3174. Looks stable now, if you notice this on any machine please let me know.
