### ISSUE TITLE
Access to jenkins through github tokens

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#321]
We currently rely on github authentication for access to jenkins. This is required for a few (some upcoming) things such as the binary builder, backup jobs and pull request poller.

It's not super clear how this works; perhaps @joaocgreis could elaborate, then we figure out how to delegate access to this user and tokens (possibly through our secrets?).

**Comment by rvagg** [comment]
@Starefossen is already using this in his slave checker simply by authing with a github token presumably on his own github account. If we have some piece of infra that needs shared access then we should use a shared github account, I've made at least one but I can't remember what it was called (probably iojs-something), @joaocgreis has one too. We should pick one and put login credentials into secrets/infra.

**Comment by Starefossen** [comment]
Yes, the slave checking is currently done with a personal GitHub token from my user account https://github.com/Starefossen/jenkins-monitor/blob/master/lib/jenkins.js#L26. The GitHub token needs at least `user:email  Access user email addresses (read-only)` permissions in order to authenticate successfully.

**Comment by jbergstroem** [comment]
The tricky part is also that we have different access levels. Collaborators in `nodejs/node` shouldn't be able to reload jenkins for instance which means that the user we tie to this setup must be infra level. I'm not sure how much the token ACL affects what Jenkins cares about seeing how the ACL in Jenkins mostly handles their own permissions based on user/group lookup.

**Comment by joaocgreis** [comment]
The shared user @nodejs-ci is used for jenkins to access the temporary repo. It is controlled by the ci@iojs.org email (https://github.com/nodejs/email/pull/2) and the password and key are in the secrets repo. The key to be considered from there is `ci-iojs-org-id_rsa-github`, there is another key `ci-iojs-org-id_rsa-slaves` but it is only used for the cross compile server and will be deleted soon.

Feel free to use the credentials in secrets to create tokens. Right now the key is only for the temporary repo and compile server, but it can be moved to infra level if needed.

**Comment by jbergstroem** [comment]
While doing the backup stuff I revisited this. What's actually required is 'roles' so jenkins can see that you are in the right group, but that's the only permission it needs.

**Comment by jbergstroem** [comment]
I think we have everything in place with regards to tokens and apps to share access. Closing.
