### ISSUE TITLE
Access to ubuntu2004-arm64

### ISSUE THREAD

**Issue by ShogunPanda** [nodejs/build#3215]
Hi! I'd like to get access to the machine above to debug failing tests of PR #46790.
I try to run those tests on a M2 Max MBP Pro and on a Hetzner virtual Linux server but could not reproduce the failures.

**Comment by mhdawson** [comment]
I think we have to give access to the base machnine and then you can use docker exec to get into one of the running images.

**Comment by mhdawson** [comment]
And +1 from me as well.

**Comment by targos** [comment]
@ShogunPanda do you still need access+

**Comment by ShogunPanda** [comment]
Yes I do, thanks

**Comment by mhdawson** [comment]
@ShogunPanda if you send me your ssh key I'll add it to the host and give you instructions how to get into the machine.

**Comment by ShogunPanda** [comment]
I think I'm done with this machine. I now need access to smartos20-64.
Do I need to file a new issue or can you directly help me?

**Comment by mhdawson** [comment]
@ShogunPanda which smartos machine do you want access to?

**Comment by targos** [comment]
I took https://ci.nodejs.org/manage/computer/test-equinix_mnx-smartos20-x64-3/ offline and added @ShogunPanda's keys.

**Comment by ShogunPanda** [comment]
@targos @mhdawson I'm also done there.
The only outstanding failure right now is instead in `test-rackspace-win2012r2_vs2017-x64-4`.
Can I get access to that as well? (not sure how it works for a Windows machine)

**Comment by targos** [comment]
Keys removed from `test-equinix_mnx-smartos20-x64-3` and node is back online.
@mhdawson I'll let you cleanup the Docker host as I don't know which one it is and what you did on it.

**Comment by ShogunPanda** [comment]
@joaocgreis How does it work for Win machines? Can I still get access?

**Comment by ShogunPanda** [comment]
Nevermind. Everything was sorted. Closing this.

**Comment by targos** [comment]
Keeping open until the keys have been cleaned up.

**Comment by mhdawson** [comment]
I should have posted, I already remove @ShogunPanda's key from the docker host, closing.

**Comment by anonrig** [comment]
> I think I'm done with this machine. I now need access to smartos20-64. Do I need to file a new issue or can you directly help me?

Adding `smartos` label due to this comment.
