### ISSUE TITLE
Ambiguous security permissions

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3217]
Follow on from https://github.com/nodejs/build/issues/3176#issuecomment-1464193154:

> One of the things we need to now address is that version 3 of the [Matrix Authorization Strategy plugin](https://github.com/jenkinsci/matrix-auth-plugin/releases/tag/matrix-auth-3.0) now requires permissions to be declared as for groups or users otherwise they are marked as ambiguous. A list of jobs that need to be updated can be found at https://ci.nodejs.org/administrativeMonitor/org.jenkinsci.plugins.matrixauth.AmbiguityMonitor/.
> 
> Fortunately the remediation is fairly simple but we need to do it for every job listed. As an example, for 
> [node-test-pull-request](https://ci.nodejs.org/job/node-test-pull-request), go into the "Configure" tab for the job and you'll see this:
> ![image](https://user-images.githubusercontent.com/5445507/224392223-050822f1-a2a8-4339-86e6-821eda4c1602.png)
> The rows in orange with a ⚠️ symbol are the ambiguous ones. On the far right of the row, after the red cross, are two icons -- one for mitigating the entry as a user, and the other for mitigating as a group. For almost all of these I expect we'd be mitigating as a group (these should reflect GitHub groups as we are using GitHub Authentication).

**Comment by targos** [comment]
All jobs updated.
