### ISSUE TITLE
High number of 404s downloading node in our CI environment

### ISSUE THREAD

**Issue by gmishkin** [nodejs/build#3227]
URL in our case: https://nodejs.org/dist/v16.18.0/node-v16.18.0-linux-x64.tar.xz

I came here and saw #3224 and the timing lines up with when we started noticing it about an hour ago.

Update: now seeing some `522` status codes

**Comment by nschonni** [comment]
This is probably a better repo, but follow https://github.com/nodejs/nodejs.org/issues/5149 as that is were the updates are going

**Comment by tniessen** [comment]
https://status.nodejs.org/

**Comment by ovflowd** [comment]
Duplicate of #5149.
