### ISSUE TITLE
File system on `/` on the www server is over 90% used

### ISSUE THREAD

**Issue by sxa** [nodejs/build#3229]
NOTE: This is separate to https://github.com/nodejs/build/issues/3125 which was related to the `/home` file system on the machine.

The `/` file system on the node-www server is 315Gb and is running with only 5.5Gb free. This has been picked up by Grafana. Looking around the biggest consumers of space are `/var/lib/docker` and `/var/log/nginx` (183Gb) - I'll take these in turn as they probably both need to be addressed:

### /var/lib/docker

Running `docker images` shows that we are creating about two images each month on average and this has been happening for the last six years. Here is the start of the output from docker images:
```
root@infra-digitalocean-ubuntu1604-x64-1:/var/lib/docker# docker images
REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
node         lts       37b4077cbd8a   7 days ago      997MB
node         <none>    45ffe1fa9234   2 weeks ago     997MB
node         <none>    c8907212ebaa   3 weeks ago     997MB
node         <none>    57e47e9243f0   3 weeks ago     996MB
node         <none>    451d8f004bba   4 weeks ago     996MB
node         <none>    ee7f11c56c16   5 weeks ago     996MB
```
This is possibly as a result of the website builder code at https://github.com/nodejs/build/blob/f16ef55df84e998449f891b2a78d01a756e85f23/ansible/www-standalone/resources/scripts/build-site.sh#L40

I would propose that we ensure we are running a regular purge (possibly after each build of the web site) to clear up the old images since I can't imagine there is a good reason for keeping them.

### /var/log/nginx
This directory is using about 143Gb and has compressed server logs going back to 2015
```
root@infra-digitalocean-ubuntu1604-x64-1:/var/log/nginx# du -sk /var/log/nginx/* | sort -n | tail
1052	/var/log/nginx/access.log.20180120.1516451101.xz
3812	/var/log/nginx/access.log.20230315.1678883929
5176	/var/log/nginx/access.log.20161121.1479732942.xz
36568	/var/log/nginx/benchmarking
136568	/var/log/nginx/libuv
497672	/var/log/nginx/coverage
2352332	/var/log/nginx/old
5634648	/var/log/nginx/nodejs-backup
35943060	/var/log/nginx/iojs
146262884	/var/log/nginx/nodejs
root@infra-digitalocean-ubuntu1604-x64-1:/var/log/nginx# 
```
Since I don't believe we have any policy on this I think it's fair to say it's just storing everything with no clearup policy. This is likely undesirable. Does anyone think we need to retain logs this far back? Should we just store the last month / year / some other value?

Note: Each daily log under `nodejs` is about 1Gb worth of data which compresses to around the 50Mb mark. The others are as follows (snapshot of March 14th):
```
root@infra-digitalocean-ubuntu1604-x64-1:/var/log/nginx# ls -ld */*access*20230314*xz
-rw-r----- 1 www-data adm    14612 Mar 15 06:53 benchmarking/benchmarking.nodejs.org-access.log.20230314.1678797433.xz
-rw-r----- 1 www-data adm   485896 Mar 15 07:03 coverage/coverage.nodejs.org-access.log.20230314.1678797433.xz
-rw-r----- 1 www-data adm 38677856 Mar 15 07:03 iojs/iojs.org-access.log.20230314.1678797433.xz
-rw-r----- 1 www-data adm    91960 Mar 15 07:03 libuv/libuv.org-access.log.20230314.1678797433.xz
-rw-r----- 1 www-data adm  3792352 Mar 15 06:25 nodejs-backup/nodejs.org-access.log.20230314.1678796703.xz
-rw-r----- 1 www-data adm 59560452 Mar 15 07:03 nodejs/nodejs.org-access.log.20230314.1678797433.xz
root@infra-digitalocean-ubuntu1604-x64-1:/var/log/nginx# 
```

**Comment by targos** [comment]
```
# docker image prune
...
Total reclaimed space: 81.24GB
```

**Comment by targos** [comment]
After pruning containers and images again:
```
Total reclaimed space: 17.52GB
```

**Comment by richardlau** [comment]
The Docker images were used to rebuild the website when we were self-hosting. Now the website is on Vercel and we no longer trigger the webhook to rebuild the website on the www server (and thus are not creating new containers).
