### ISSUE TITLE
CLI wrapper to rebase, pre-fill and run CI on PRs

### ISSUE THREAD

**Issue by silverwind** [nodejs/build#325]
Spawned off https://github.com/nodejs/build/issues/324#issuecomment-182066646

The basic idea would be a CLI script that does:

1) Take a PR number argument
2) Pull patches from Github
3) Aks y/N if commits shall be squashed
4) Rebase commits and apply metadata (use GitHub API to parse for LGTMs)
5) Preview commit messages and ask y/N if they shall be further edited in $EDITOR
7) Start a Jenkins job, possibly authorized through a user's SSH key or other token
8) Sleep the process until Jenkins is complete
9) If CI is green, ask y/N whether the commits shall be landed

The only step on which I'm unsure on how to do would be step 5. Can anyone think of a git workflow to add metadata to existing commits without `rebase --interactive`?

cc: @jbergstroem

**Comment by Trott** [comment]
Maybe add a commit message linting/validation step that makes sure the final message:

* has a first line that is not empty and is at least 50 chars long
* has a first line that matches a regular expression along the lines of this (untested): `/^[a-z,]+: \w.*/`
* has a blank second line
* has a non-blank third line
* has a blank line before the metadata
* has metadata consistent with what it knows about the PR (e.g., PR-URL exists and is correct)
* has at least one Reviewed-by metadata line
* individuals in Reviewed-by metadata are in fact collaborators (basically compare against a whitelist of people who can give a `LGTM` that counts)
* all non-metadata lines are shorter than 72 chars

**Comment by jbergstroem** [comment]
Excellent list by @trott. I'd like to add:
 - metadata ordering (suggesting: PR-URL -> Fixes -> Refs -> Reviewed-By)

It'd be really nice to have a LGTM validation/"check" (ok/not ok to land); but I think it's too hard to make realistic LGTM counts seeing how new commits could introduce new code.

**Comment by refack** [comment]
Cross ref: #705 

There's an issue of racing with humans/concurrent jobs. That's where the concept of a queue comes into play.

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
