### ISSUE TITLE
CITGM daily job?

### ISSUE THREAD

**Issue by Trott** [nodejs/build#327]
It would be great, I think, if there was a daily CITGM job in CI similar to `node-daily-master`. /cc @TheAlphaNerd

**Comment by jasnell** [comment]
+1

**Comment by rvagg** [comment]
sooo .. just to raise one point of concern; allowing third-party code to run on our CI machines opens us up to new injection points for malicious actors. We (mostly) keep our release machines separate but we are dealing with the integrity of our testing system here. Before we go too hard on citgm I wouldn't mind us considering the security implications a bit more and finding ways to mitigate the risks. Some examples could include running separate dedicated machines for citgm runs, or even just running dedicated citgm Jenkins slaves under separate user accounts on our machines to limit the impact.

**Comment by Trott** [comment]
@rvagg Good point, unfortunately.

**Comment by jbergstroem** [comment]
I think the real impact is that jobs has access to environment. In fact, its probably even likely for some test or test runner out there to dump the environment so its easier to "debug" (think libuv diagnostic info pre-run but verbose). There's a lot of trust issues here.
