### ISSUE TITLE
I took test-ibm-ubuntu1804-x64-1 offline as it was failing `pip --no-user` and so lints were never passing

### ISSUE THREAD

**Issue by Trott** [nodejs/build#3273]
I was pinged in Slack by @qard about the lint job failing repeatedly. I took it to #nodejs-build and you can see the conversation at https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1680236357000469.

test-ibm-ubuntu-1804-x64-1 was getting a lot of this:

```
python3 -m pip install --no-user --upgrade -t tools/pip/site-packages flake8 || \
21:24:11 	python3 -m pip install --no-user --upgrade --system -t tools/pip/site-packages flake8
21:24:12 
21:24:12 Usage:   
21:24:12   /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
21:24:12   /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
21:24:12   /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
21:24:12   /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
21:24:12   /usr/bin/python3 -m pip install [options] <archive url/path> ...
21:24:12 
21:24:12 no such option: --no-user
```

When I took it offline and the job ended up running on test-equinix-ubuntu2204-x64-1, it passed.

@nodejs/python (I'm guessing/hoping @cclauss will have an immediate recommended/preferred solution. I'm not sure if pip doesn't support `no-user` anymore or if the version of pip we're running on that machine must be an old one or something else.)

**Comment by MoLow** [comment]
caused & fixed by https://github.com/nodejs/build/pull/3272

**Comment by cclauss** [comment]
The error summary was `no such option: --no-user`

% `pip install --help | grep user`
```
  --user                      Install to the Python user install directory for
  --root-user-action <root_user_action>
                              Action if pip is run as a root user. By default,
                              environment variables and user configuration.
                              scheme://[user:passwd@]proxy.server:port.
```
