### ISSUE TITLE
Node.js 14 builds broken (missing `python` on Ubuntu 18.04 containers)

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3275]
Starting with the 31 March builds, https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-v14.x-staging/177/, the Node.js 14 build has been failing on Ubuntu 18.04 containers:
e.g.
- https://ci.nodejs.org/job/node-test-commit-linux-containered/36920/
- https://ci.nodejs.org/job/node-test-commit-arm/46804/

https://ci.nodejs.org/job/node-test-commit-linux-containered/36920/nodes=ubuntu1804_sharedlibs_shared_x64/console
```console
11:03:33 + make run-ci -j 4
11:03:33 /bin/sh: 1: python: not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 make: python: Command not found
11:03:33 python ./configure --verbose  --shared
11:03:33 make: python: Command not found
11:03:33 Makefile:526: recipe for target 'build-ci' failed
11:03:33 make: *** [build-ci] Error 127
```

**Comment by MoLow** [comment]
should we backport https://github.com/nodejs/node/pull/37764
or should we revert some of the changes in https://github.com/nodejs/build/pull/3272 and https://github.com/nodejs/build/pull/3269 ?

**Comment by richardlau** [comment]
> should we backport [nodejs/node#37764](https://github.com/nodejs/node/pull/37764) or should we revert some of the changes in #3272 and #3269 ?

Backporting https://github.com/nodejs/node/pull/37764 would be breaking for Node.js 14.

I think maybe we could restore `python-pip` to the Dockerfile, or try installing `python`. We can keep tap2junit installed with `pip3`, but we need to have `python` available for Node.js 14.
