### ISSUE TITLE
Benchmark CI tries to pull from http

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3277]
Here's the log running on https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/1316/console

```
00:00:06.413 ++ git clone http://github.com/nodejs/node.git
00:00:06.413 Cloning into 'node'...
00:00:08.726 warning: redirecting to https://github.com/nodejs/node.git/
```

**Comment by targos** [comment]
From here: https://github.com/nodejs/benchmarking/blob/master/experimental/benchmarks/community-benchmark/run.sh

**Comment by anonrig** [comment]
> From here: https://github.com/nodejs/benchmarking/blob/master/experimental/benchmarks/community-benchmark/run.sh

Since the repository is archived, GitHub won't allow any changes to be done to the repository. Should we move the appropriate files to the build repository? @nodejs/build

**Comment by richardlau** [comment]
We can always unarchive. I think the script would be better off in a repository other than build unless you really want changes to it to be bottlenecked on the build team.

**Comment by anonrig** [comment]
> We can always unarchive. I think the script would be better off in a repository other than build unless you really want changes to it to be bottlenecked on the build team.

@richardlau I think we should keep it under nodejs/build.
