### ISSUE TITLE
Create a job for http-parser

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#328]
Picked up [an error](https://github.com/nodejs/http-parser/pull/279) while looking into bumping http-parser. It was bumped inside of nodejs ahead of its own repository (which could be another topic). @jasnell suggested we test it more regularly so lets start with setting up a job that runs the test suite on our supported platforms.

**Comment by jasnell** [comment]
+1.
FWIW, the bump inside nodejs before http-parser was because, at the time, we didn't have http-parser-private, which I've since fixed :-) ... in the future we can do the fixes in http-parser-private first.

**Comment by maclover7** [comment]
This is a thing now: [http-parser-test](https://ci.nodejs.org/view/MyJobs/job/http-parser-test/) 🎉
