### ISSUE TITLE
ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3282]
Test: `node-test-commit-osx`
Machine: osx1015
Logs: https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/51450/console

```
00:20:21.275     AssertionError [ERR_ASSERTION]: ifError got unwanted exception: ENOSPC: no space left on device, write
00:20:21.275         at Object.callback (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/test/pummel/test-fs-readfile-tostring-fail.js:31:37)
00:20:21.275         at callback (node:internal/streams/writable:562:21)
00:20:21.275         at onwriteError (node:internal/streams/writable:425:3)
00:20:21.275         at onwrite (node:internal/streams/writable:467:7)
00:20:21.275         at node:internal/fs/streams:439:14
00:20:21.275         at FSReqCallback.wrapper [as oncomplete] (node:fs:958:5) {
00:20:21.275       generatedMessage: false,
00:20:21.275       code: 'ERR_ASSERTION',
00:20:21.275       actual: [Error: ENOSPC: no space left on device, write] {
00:20:21.275         errno: -28,
00:20:21.275         code: 'ENOSPC',
00:20:21.275         syscall: 'write'
00:20:21.275       },
00:20:21.275       expected: null,
00:20:21.275       operator: 'ifError'
00:20:21.275     }
00:20:21.275     
```

**Comment by MoLow** [comment]
checking

**Comment by anonrig** [comment]
It seems like this is a regression. Would it make sense & easy to deploy and have a Slack notification whenever the space size is critical in all of our machines?

**Comment by Trott** [comment]
Oh, that's a pummel test. It is intentionally using a lot of disk space, probably.....

**Comment by MoLow** [comment]
```
administrator@test-nearform-macos10 ~ % df -h
Filesystem      Size   Used  Avail Capacity iused     ifree %iused  Mounted on
/dev/disk1s5    51Gi   10Gi   16Gi    40%  488456 536620904    0%   /
devfs          186Ki  186Ki    0Bi   100%     643         0  100%   /dev
/dev/disk1s1    51Gi   23Gi   16Gi    59% 1083722 536025638    0%   /System/Volumes/Data
/dev/disk1s4    51Gi  1.0Gi   16Gi     6%       2 537109358    0%   /private/var/vm
map auto_home    0Bi    0Bi    0Bi   100%       0         0  100%   /System/Volumes/Data/home
```

**Comment by anonrig** [comment]
> If you don't have access to the machine itself, you can sometimes free up some space by clearing out workspaces in the GitHub interface, IIRC.

@Trott Can this be done by collaborators as well? If yes, how can we do it (in the future)?

**Comment by Trott** [comment]
> > If you don't have access to the machine itself, you can sometimes free up some space by clearing out workspaces in the GitHub interface, IIRC.
> 
> @Trott Can this be done by collaborators as well? If yes, how can we do it (in the future)?

I'm not seeing it in the interface, so maybe I'm wrong.

**Comment by Trott** [comment]
I'll remove the node-stress-single-test workspace based on this, but this is not a long-term answer....

```
administrator@test-nearform-macos10 workspace % du -sh *
161M	citgm-smoker
 47M	libuv-test-commit-osx-cmake
1.5G	node-stress-single-test
329M	node-test-node-addon-api-new
administrator@test-nearform-macos10 workspace %
```

**Comment by MoLow** [comment]
I followed the recommendations at https://github.com/nodejs/build/blob/main/doc/jenkins-guide.md#out-of-space
now the disk space is:
```
bash-3.2$ df -h
Filesystem      Size   Used  Avail Capacity iused     ifree %iused  Mounted on
/dev/disk1s5    51Gi   10Gi   18Gi    37%  488456 536620904    0%   /
devfs          186Ki  186Ki    0Bi   100%     644         0  100%   /dev
/dev/disk1s1    51Gi   21Gi   18Gi    55% 1032538 536076822    0%   /System/Volumes/Data
/dev/disk1s4    51Gi  1.0Gi   18Gi     6%       2 537109358    0%   /private/var/vm
map auto_home    0Bi    0Bi    0Bi   100%       0         0  100%   /System/Volumes/Data/hom
```

didn't seem to make a lot of a difference

**Comment by Trott** [comment]
`test-fs-largefile` in the `pummel` suite has this at the end:

```javascript
} catch (e) {
  if (e.code !== 'ENOSPC') {
    throw e;
  }
  common.skip('insufficient disk space');
}
```

Maybe `test-fs-readfile-tostring-fail` needs something similar? (Or maybe it doesn't because the test is different--I haven't looked--but something to consider!)

**Comment by sxa** [comment]
> didn't seem to make a lot of a difference

LGTM - there's no problems with creating files in the iojs homedir, so as far as I can see the machine is happy just now. If you see it again let us know.

**Comment by targos** [comment]
The disk doesn't seem to be close to full. I don't understand the CI error in this case.

**Comment by sxa** [comment]
Agreed https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/51455/consoleFull seemed to run through on the same machine without problems, so I'm happy to close thiis and it can be reopened if it recurs. (I'm assuming no catastrophic failure caused any huge core dumps within the workspace or something like that!)

**Comment by richardlau** [comment]
FWIW IIRC `test-fs-largefile` attempts to write a 5GB file.

**Comment by richardlau** [comment]
Ah sorry, nvm, I see this is about `test-fs-readfile-tostring-fail` instead (which is probably also writing several GB, but I think that may have been based on the max string size).
