### ISSUE TITLE
Resetting Nearform Windows ARM64 machines.

### ISSUE THREAD

**Issue by StefanStojanovic** [nodejs/build#3286]
Currently, 2 Nearform Windows ARM64 machines in CI are not used: [test-nearform_arm-win10_vs2019-arm64-1](https://ci.nodejs.org/manage/computer/test-nearform_arm-win10_vs2019-arm64-1/) and [test-nearform_arm-win10_vs2019-arm64-2](https://ci.nodejs.org/manage/computer/test-nearform_arm-win10_vs2019-arm64-2/). They were configured manually, so they are not in line with the other machines setup via Ansible scripts. Can we reset them to a clean state, so I can configure them through Ansible and include them in test jobs for Windows on ARM?

cc @jasnell @nodejs/platform-windows-arm 

Refs: https://github.com/nodejs/build/issues/2540

**Comment by jasnell** [comment]
I've no access to these machines any longer. @RafaelGSS maybe?

**Comment by StefanStojanovic** [comment]
Hi @sxa. Since those machines were set up manually I think their reliability is questionable. As I recall, they were used to test things out in the beginning and a few different approaches were used. I do not remember everything now, but when I started working on them I remember having some issues e.g. VS 2019 and 2022 were both installed, Python was not on the correct version, Jenkins was started via NSSM, etc. While working on those issues, we got Azure VMs so I shifted my focus to them.

My concern is that all those manual changes could have left some leftovers which may affect their behavior. Honestly, I do not know what's the state of those machines now and since the Azure machines we have cover our needs for now, I'm hesitant to try adding Nearform machines for testing. If they were reset and set up cleanly adding them would not be a problem in my opinion.

Btw, I have access to those machines too, but as you said, for reinstalling them I need someone on-site.

**Comment by sxa** [comment]
@StefanStojanovic Yep totally agree with all of that :-) And yes when the Linaro team started actively working on this we were using those machines to see what could make things work so they're no longer as clean from the perspective of the playbooks as they would otherwise be.

> I'm hesitant to try adding Nearform machines for testing.

Have they been actively excluded? I assumed they were still being used in the jobs even though this cleanup hasn't been done.

**Comment by StefanStojanovic** [comment]
> Have they been actively excluded? I assumed they were still being used in the jobs even though this cleanup hasn't been done.

Since Azure ARM64 machines are Windows 11, their labels start with `win11-...`. On the other hand, Nearform machines were created as Windows 10 (although they were upgraded to Windows 11 at some point), so their labels start with `win10-...`. We've configured test jobs to use only Azure machines.

**Comment by sxa** [comment]
Gotcha - we had it running on the `node-test-commit-...` jobs on the NearForm machines with the win10 labels but I see that's been changed now.

**Comment by RafaelGSS** [comment]
cc @efrisby

**Comment by StefanStojanovic** [comment]
Closing this, since the Nearform machines are removed from the CI and the build repo.
