### ISSUE TITLE
test-softlayer-debian10-x64-1 offline in Jenkins

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3289]
[test-softlayer-debian10-x64-1](https://ci.nodejs.org/manage/computer/test-softlayer-debian10-x64-1/) is offline in Jenkins, which means we're down to a single debian10-x64 machine (over in Rackspace).

> Disk space is too low. Only 0.151GB left on /home/iojs/build.

**Comment by targos** [comment]
I deleted `/home/iojs/.cache/node-gyp` (2.7G), `/var/log/auth.log` (3.1G) and cleared `/var/log/btmp` (2.6G).

A few minutes after doing it `/var/log/auth.log` is already at 2.3K, so we might want to enable fail2ban or change the ssh port.

**Comment by richardlau** [comment]
And/or maybe use logrotate.
