### ISSUE TITLE
Default downloads for linux still tar.gz on main node page

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#329]
@sxa555 mentioned that when you hit the main page (https://nodejs.org/en/) with a linux machine the downloads are still tar.gz even though the default on the download page has been switched to tar.xz

**Comment by mhdawson** [comment]
@rvagg

**Comment by jbergstroem** [comment]
Should this perhaps be filed to the website repo?

**Comment by rvagg** [comment]
filed fix @ https://github.com/nodejs/nodejs.org/issues/516

**Comment by rvagg** [comment]
:boom: fixed
