### ISSUE TITLE
Update Xcode to v13.x for releases

### ISSUE THREAD

**Issue by targos** [nodejs/build#3311]
Necessary to support C++20: https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes
According to https://en.wikipedia.org/wiki/Xcode#Xcode_11.0_-_14.x_(since_SwiftUI_framework), it should be possible to install version 13.2.1 on macOS 11.

**Comment by richardlau** [comment]
I don't use macOS so I have no idea.

**Comment by UlisesGascon** [comment]
Sounds good to me, as Node20 target is MacOS 11 👍

**Comment by targos** [comment]
I just checked on `test-nearform-macos11.0-arm64-1` and Software Update Tool wants to install it by default:

```
# softwareupdate -l
Software Update Tool

Finding available software
Software Update found the following new or updated software:
* Label: Command Line Tools for Xcode-13.2
	Title: Command Line Tools for Xcode, Version: 13.2, Size: 577329K, Recommended: YES,
* Label: macOS Big Sur 11.7.6-20G1231
	Title: macOS Big Sur 11.7.6, Version: 11.7.6, Size: 2707544K, Recommended: YES, Action: restart,
```

**Comment by targos** [comment]
This would not only affect Node.js 20. The arm64 binary is built with macOS 11 on all supported release lines.

**Comment by targos** [comment]
If there are no objections, I will do the update before the next release of Node.js 20 (which is scheduled for next week). It will be easy to revert in case of issues.

**Comment by targos** [comment]
Updated:
- [release-macstadium-macos11.0-arm64-1](https://ci-release.nodejs.org/manage/computer/release-macstadium-macos11.0-arm64-1/)
- [release-nearform-macos11.0-arm64-1](https://ci-release.nodejs.org/manage/computer/release-nearform-macos11.0-arm64-1/)
- [release-orka-macos11-x64-1](https://ci-release.nodejs.org/manage/computer/release-orka-macos11-x64-1/)

**Comment by targos** [comment]
Test build: https://ci-release.nodejs.org/job/iojs+release/9327/
