### ISSUE TITLE
Missing or unselected GCC 10 on many hosts - Blocks V8 updates!

### ISSUE THREAD

**Issue by targos** [nodejs/build#3317]
Easy to spot because GCC 8 and 9 don't support `-std=gnu++20`

Latest C++20 CI: https://ci.nodejs.org/job/node-test-pull-request/56278/

Things remaining to update:

- [x] [Debian](https://github.com/nodejs/build/issues/3499)
- [x] Ubuntu 18.04
  - [x] [Ubuntu 18.04 sharedlib containers](https://github.com/nodejs/build/issues/2933)
- [x] https://ci.nodejs.org/label/ubi81_sharedlibs_openssl111fips_x64/
- [x] armv7l (despite Ubuntu 20.04)

**Comment by targos** [comment]
Should be easy to fix on SmartOS 20:

```
# pkgin se gcc10
gcc10-10.3.0         The GNU Compiler Collection (GCC) - 10.x Release Series
gcc10-libs-10.3.0    The GNU Compiler Collection (GCC) support shared libraries
```

**Comment by richardlau** [comment]
> * [ ]  armv7l (despite Ubuntu 20.04)

Ah this one is because the select-compiler changes we made were to the section where `"$SELECT_ARCH" = "ARM64"` which won't be true for armv7l. I think my preference is to work towards adding x64 Ubuntu 20.04 into the test CI matrix and then move the compiler selection for Ubuntu 20.04 so that it is not architecture specific.

**Comment by targos** [comment]
Just found that https://ci.nodejs.org/label/ubi81_sharedlibs_openssl111fips_x64/ are still on GCC 8

**Comment by targos** [comment]
^ @anonrig is looking into it.

**Comment by targos** [comment]
Chromium now officially supports C++20: https://chromium-review.googlesource.com/c/chromium/src/+/4217486

**Comment by targos** [comment]
Adding build agenda for awareness. This is now blocking further V8 upgrades.

**Comment by targos** [comment]
We need to select the right compiler on `ubi81`: https://ci.nodejs.org/job/node-test-commit-linux-containered/40782/nodes=ubi81_sharedlibs_openssl111fips_x64/console

@richardlau Can you help with that?

**Comment by richardlau** [comment]
> We need to select the right compiler on `ubi81`: https://ci.nodejs.org/job/node-test-commit-linux-containered/40782/nodes=ubi81_sharedlibs_openssl111fips_x64/console
> 
> @richardlau Can you help with that?

Opened https://github.com/nodejs/build/pull/3590

**Comment by targos** [comment]
We're close!

I think this one just needs another update to `select-compiler.sh`?

https://ci.nodejs.org/job/node-test-commit-arm/50418/nodes=ubuntu2004-armv7l/console

**Comment by richardlau** [comment]
> We're close!
> 
> I think this one just needs another update to `select-compiler.sh`?
> 
> https://ci.nodejs.org/job/node-test-commit-arm/50418/nodes=ubuntu2004-armv7l/console

Yes, I think so. `gcc-10` should be available https://github.com/nodejs/build/blob/e2440ff9e544ec968fe8ac7adf2740e494c7ab2b/ansible/roles/docker/templates/ubuntu2004_armv7l.Dockerfile.j2#L19-L20
It looks like currently `select-compiler.sh` isn't aware of armv7l so it doesn't actually select anything (i.e. leaves things as default) https://github.com/nodejs/build/blob/e2440ff9e544ec968fe8ac7adf2740e494c7ab2b/jenkins/scripts/select-compiler.sh#L19-L26

**Comment by targos** [comment]
`select-compiler.sh` was not run in https://ci.nodejs.org/job/node-test-binary-armv7l/9214/RUN_SUBSET=native,nodes=ubuntu2004-armv7l/console

**Comment by targos** [comment]
@richardlau is this the correct fix, in https://ci.nodejs.org/job/node-test-binary-armv7l/configure:

![CleanShot 2023-12-13 at 13 28 55](https://github.com/nodejs/build/assets/2352663/cf1d47a2-430f-46e0-9e2f-7ca414336a7f)

**Comment by richardlau** [comment]
@targos Yes, that looks good.

**Comment by targos** [comment]
Done!

Resumed build: https://ci.nodejs.org/job/node-test-pull-request/56278/

**Comment by targos** [comment]
I believe this is done 🎉
