### ISSUE TITLE
`switch ‘-msign-return-address=all’ is no longer supported`

### ISSUE THREAD

**Issue by targos** [nodejs/build#3319]
https://ci-release.nodejs.org/job/iojs+release/9304/nodes=rhel8-arm64-release/console

I wonder if it means that we build without this protection at the moment.

Related to https://github.com/nodejs/node/issues/42888 and https://github.com/nodejs/node/pull/45756

**Comment by richardlau** [comment]
We could change it to `-mbranch-protection` -- it will break anything running gcc 8 but for Node.js 20 we bumped the requirement to gcc 10. Would probably need https://github.com/nodejs/build/issues/3317 to be addressed for the Ubuntu arm64 hosts.

**Comment by richardlau** [comment]
I did think about altering `configure.py` to choose the appropriate flag based on gcc version (since `configure.py` does check that) but https://github.com/nodejs/node/pull/45756 would move setting the flag out of `configure.py` into the gyp files.
