### ISSUE TITLE
Release CI upload failure

### ISSUE THREAD

**Issue by StefanStojanovic** [nodejs/build#3324]
The [iojs+release](https://ci-release.nodejs.org/job/iojs+release/) job occasionally fails when nodes connect to the staging server to upload binaries. I first noticed this on Windows configurations, but afterward saw it happening on other platforms too.

To investigate this, I've created the [mefi-ssh-test](https://ci-release.nodejs.org/job/mefi-ssh-test/) job. Although I reproduced the same error in some runs I couldn't make any progress with it. I worked with @joaocgreis, and we tried changing the SSH config on the staging server (we increased MaxStartups from 5 to 20, and later reverted it), but that didn't help.

Another issue when tracking SSH connections is that all access is done through a CloudFlare proxy, so I can't see the real IPs trying to connect to the server. I noticed though that even with the IP filter in place there are a lot of failed connection attempts.

If anyone has some other ideas that can be tried to fix this feel free to share them. By the look of things, some changes should be made to the staging server to avoid these problems with establishing and maintaining SSH connections.

**Comment by richardlau** [comment]
> 
> Another issue when tracking SSH connections is that all access is done through a CloudFlare proxy, so I can't see the real IPs trying to connect to the server. I noticed though that even with the IP filter in place there are a lot of failed connection attempts.

That should not be the case -- the release machines should be going directly to the staging server through a non-proxied subdomain.
