### ISSUE TITLE
Enable ccache for AIX

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#333]
Reminder that we still need to do this

**Comment by jbergstroem** [comment]
Did you try compiling it manually? We have an [ansible script for this](https://github.com/nodejs/build/blob/4a1107f9419163ffd1d5af60093c3f0ab7bc5412/setup/ansible-tasks/ccache.yaml) you could use as part of a playbook.

**Comment by mhdawson** [comment]
Thanks for the pointer I've not looked at how we'd do it yet but opened this to make sure we did not forget.

Will try to find some time to check this out.

**Comment by mhdawson** [comment]
@jbergstroem compiled/installed it and after apply one fix which should come in the next release it seems to be working.  I added the build/install instructions to https://github.com/nodejs/build/pull/323 so closing
