### ISSUE TITLE
All Azure machines are offline

### ISSUE THREAD

**Issue by targos** [nodejs/build#3334]
/cc @StefanStojanovic 

https://ci.nodejs.org/computer/

![CleanShot 2023-05-01 at 15 17 09](https://user-images.githubusercontent.com/2352663/235456776-63dca565-8f78-456a-9d6f-28ba609f6d24.png)

**Comment by StefanStojanovic** [comment]
The issue was the `Temurin17` update. I'll investigate possibilities to ensure it is only updated when Jenkins is not running. The test CI build queue dropped to its regular size yesterday, so AFAIK this is fixed.
