### ISSUE TITLE
Granting Jenkins access to node-charkacore WG

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#334]
Ref: https://github.com/nodejs/node-chakracore/issues/18
Ref: https://github.com/nodejs/node/pull/4765#issuecomment-179868492

@nodejs/jenkins-admins 

Asking for permission to grant @nodejes/node-chakracore, who are the maintainers of https://github.com/nodejs/node-chakracore access to CI as we do for the nodejs/collaborators group.

**Comment by jbergstroem** [comment]
Sounds good to me.

**Comment by rvagg** [comment]
That's OK but it means you can't be as liberal when adding members to that team, it can't serve as a backdoor to Jenkins access. The Collaborators gating process is a handy way to make it difficult for malicious actors to get Jenkins access so you can't just go adding anyone to this new team because they put up their hand to help.

**Comment by jbergstroem** [comment]
@rvagg I assumed that members of chakra-core would follow the same collaboration/contribution guidelines as node.js. Is this not the case?

**Comment by orangemocha** [comment]
Duly noted, @rvagg . The plan is for the collaboration guidelines to be as close as possible to the guidelines for Node.js. Currently the team is comprised of existing Node.js collaborators + a few Microsoft employees who worked on the project before. I am comfortable that the current team meets the trust standards, and will keep this in mind before admitting any new collaborators.

On a related note, it would be in the interest of the build & testing efforts in Node.js to be able to grant Jenkins access to more individuals, so we should think of ways that we can sandbox their activities and mitigate the security concerns. https://github.com/nodejs/build/issues/331 is on the wg-agenda for next Tuesday's meeting and it can serve as a starting point for this discussion.

**Comment by orangemocha** [comment]
Moving forward with this (on Monday) unless there are any objections. The bar for joining the node-charkacore group will be kept in line with that for nodejs/collaborators.

**Comment by orangemocha** [comment]
Done. The members of nodejs/node-chakracore now have the same access to Jenkins as do nodejs/collaborators.
