### ISSUE TITLE
"write github.com entry in known_hosts" fails on FreeBSD

### ISSUE THREAD

**Issue by targos** [nodejs/build#3340]
```
TASK [github : write github.com entry in known_hosts] ***************************************************************************************************************************************
fatal: [test-digitalocean-freebsd12-x64-1]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid file mode: A+user:iojs:rx:allow\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.14/user_guide/become.html#risks-of-becoming-an-unprivileged-user"}
```

**Comment by richardlau** [comment]
FWIW this appears to be due to FreeBSD's zfs support not supporting POSIX acl's. 

https://docs.ansible.com/ansible-core/2.16/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user
> Although the Solaris ZFS filesystem has filesystem ACLs, the ACLs are not POSIX.1e filesystem acls (they are NFSv4 ACLs instead). Ansible cannot use these ACLs to manage its temp file permissions so you may have to resort to [the world_readable_temp option](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/sh_shell.html#parameter-world_readable_temp) if the remote machines use ZFS.
