### ISSUE TITLE
Problem sending coverity report

### ISSUE THREAD

**Issue by targos** [nodejs/build#3343]
https://ci.nodejs.org/view/All/job/node-daily-coverity/2626/console

```
+ VERSION=v21.0.0-pre-76ae7be78d
+ FILE=nodejs-v21.0.0-pre-76ae7be78d.tar.gz
+ tar -czf nodejs-v21.0.0-pre-76ae7be78d.tar.gz cov-int
+ set +x
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
+ rm -rf nodejs-v21.0.0-pre-76ae7be78d.tar.gz cov-int
```

**Comment by richardlau** [comment]
Not sure how big our tarball is currently, but other projects have run into the same issue within the last month:
- https://community.synopsys.com/s/question/0D5Hr00006UoTDtKAN/413-request-entity-too-large-error-when-uploading-covbuild-artifacts
- https://community.synopsys.com/s/question/0D5Hr00006Uo2htKAB/the-last-2-weeks-our-coverity-scan-build-failed-with-the-error-below-it-worked-before-the-zip-we-upload-is-2864mb-so-yes-it-is-large

We may need to contact support.

Separately we might also want to make these failures fail the build.

**Comment by mhdawson** [comment]
Send this email to `scan-admin@coverity.com` based on request to do that in the issues @richardlau mentioned:

```text 
The Node.js project is getting errors trying to upload scan results:
+ ./node --version
+ git rev-parse --short HEAD
+ VERSION=v21.0.0-pre-f36461dc6a
+ FILE=nodejs-v21.0.0-pre-f36461dc6a.tar.gz
+ tar -czf nodejs-v21.0.0-pre-f36461dc6a.tar.gz cov-int
+ set +x
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
More details in https://github.com/nodejs/build/issues/3343.

Seems like other projects had the same issue and were asked to reach out to this email to get the upload size limit increased. 

Can you do that for the Node.js project?
```

**Comment by mhdawson** [comment]
Emailed again as follow up.

**Comment by mhdawson** [comment]
Also trying to register in the Synopsys community to be able to report there as well.

**Comment by mhdawson** [comment]
Created this case - https://community.synopsys.com/s/case/500Hr00001VqtfjIAB/coverity-scan-uploads-failing

**Comment by mhdawson** [comment]
From coverity team

Hi Michael,

We will have the API in place by the end of next week. We will keep you posted.

 

Regards,

Alex Johnson

**Comment by mhdawson** [comment]
URL to upload manually - https://scan.coverity.com/projects/node/builds/new

**Comment by mhdawson** [comment]
Correct URL to upload - https://scan.coverity.com/projects/node-js/builds/new

**Comment by mhdawson** [comment]
Uploaded a build manually last week, and uploading one today

**Comment by richardlau** [comment]
There's a new API on https://scan.coverity.com/projects/node-js/builds/new?tab=url but it looks like we'd need to make the tarball available on a publicly accessible URL to use it.

**Comment by richardlau** [comment]
Ah there's also more instructions on https://scan.coverity.com/projects/node-js/builds/new in the section
> 2. If the build size exceeds `500MB`, upload limits come into effect.
>   To upload larger builds, please do the following:

**Comment by richardlau** [comment]
I've edited the job to use the [new API](https://github.com/nodejs/build/issues/3343#issuecomment-1602676534) documented on https://scan.coverity.com/projects/node-js/builds/new. This requires adding `jq` to the [jenkins-workspace](https://ci.nodejs.org/label/jenkins-workspace/) machines, which I've added to the Ansible scripts in https://github.com/nodejs/build/pull/3397.

Kicked off a new build: https://ci.nodejs.org/job/node-daily-coverity/2679/

**Comment by richardlau** [comment]
> Kicked off a new build: https://ci.nodejs.org/job/node-daily-coverity/2680/

This looks like it has worked and the scan and analysis for v21.0.0-pre-b352e0c36a is on https://scan.coverity.com/projects/node-js.

Since we're limited to one build submission per 24 hours, the next scheduled run of https://ci.nodejs.org/job/node-daily-coverity/ is expected to fail to upload as it will occur within the 24 hour period.

**Comment by richardlau** [comment]
> Since we're limited to one build submission per 24 hours, the next scheduled run of https://ci.nodejs.org/job/node-daily-coverity/ is expected to fail to upload as it will occur within the 24 hour period.

https://ci.nodejs.org/job/node-daily-coverity/2681/console failed as expected
```console
The build submission quota for this project has been reached. Next submission permitted on or after 2023-Jun-23  7:56 PM UTC
parse error: Invalid numeric literal at line 1, column 4
Build step 'Execute shell' marked build as failure
```

Let's check the next scheduled build succeeds, and then we can probably close this out.

**Comment by mhdawson** [comment]
I received an email saying the new API was ready and we'd have to update the endpoint we use. Interestingly the scan on the 22nd passed without me doing anything. The scan for the 23rd failed with this message:

```shell
The build submission quota for this project has been reached. Next submission permitted on or after 2023-Jun-23  7:56 PM UTC
parse error: Invalid numeric literal at line 1, column 4
Build step 'Execute shell' marked build as failure
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
Finished: FAILURE
```
I plan to look at the new instructions for uploading next week to see how easy it will be to update.

**Comment by richardlau** [comment]
@mhdawson See my posts above yours -- I've switched the CI job to use the new API which is how the scan from the 22nd got uploaded.

**Comment by mhdawson** [comment]
ah ok, I just got the scan email but did not read through the history. Great to see you have already adjusted it to use the new API, explains why it started working :)
