### ISSUE TITLE
test-rackspace-win2012r2_vs2019-x64-3 freezes when pulling from git

### ISSUE THREAD

**Issue by MoLow** [nodejs/build#3344]
https://ci.nodejs.org/job/node-test-binary-windows-native-suites/17941/nodes=win2012r2-vs2019-COMPILED_BY-vs2019-x86/console

```
14:59:51 > git fetch --prune --no-tags binary_tmp@147.75.72.255:binary_tmp.git +refs/heads/jenkins-node-test-commit-windows-fanned-decc4d8e3a7bc7a7845cd8ddcc211bb9c3fef1f1-bin-win-vs2019-x86:refs/remotes/jenkins_tmp 
15:00:00 Warning: Permanently added '147.75.72.255' (ED25519) to the list of known hosts.
15:20:16 Terminate batch job (Y/N)? 
15:20:16 
15:20:16 > if errorlevel 1 (
```

**Comment by MoLow** [comment]
I have marked this node as unavailable for now

**Comment by targos** [comment]
I had to put it back online, otherwise it blocks https://ci.nodejs.org/job/windows-update-reboot/

**Comment by targos** [comment]
Got stuck in the windows-update-reboot job itself for the same reason: https://ci.nodejs.org/job/git-clean-windows/label=test-rackspace-win2012r2_vs2019-x64-3/336/console

I cancelled the job and removed the label from its config:
<img width="391" alt="CleanShot 2023-05-07 at 10 59 10@2x" src="https://user-images.githubusercontent.com/2352663/236668063-79764d8c-c05f-457e-89ef-e4d820808535.png">

**Comment by StefanStojanovic** [comment]
As a part of [updating Windows CI](https://github.com/nodejs/build/issues/3373) this branch has been deleted. Closing the issue.
