### ISSUE TITLE
Update Alpine Linux containers to supported versions

### ISSUE THREAD

**Issue by targos** [nodejs/build#3349]
We currently have 6 containers, on Alpine 3.11 (labeled last-latest) and 3.12 (labeled latest).

- [x] https://ci.nodejs.org/manage/computer/test-digitalocean-alpine311_container-x64-1/ -> https://ci.nodejs.org/manage/computer/test-digitalocean-alpine315_container-x64-1/
- [x] https://ci.nodejs.org/manage/computer/test-digitalocean-alpine311_container-x64-2/ -> https://ci.nodejs.org/manage/computer/test-digitalocean-alpine315_container-x64-2/
- [x] https://ci.nodejs.org/manage/computer/test-softlayer-alpine311_container-x64-1/ -> https://ci.nodejs.org/manage/computer/test-softlayer-alpine315_container-x64-1/
- [x] https://ci.nodejs.org/manage/computer/test-digitalocean-alpine312_container-x64-1/ -> https://ci.nodejs.org/manage/computer/test-digitalocean-alpine318_container-x64-1/
- [x] https://ci.nodejs.org/manage/computer/test-digitalocean-alpine312_container-x64-2/ -> https://ci.nodejs.org/manage/computer/test-digitalocean-alpine318_container-x64-2/
- [x] https://ci.nodejs.org/manage/computer/test-softlayer-alpine312_container-x64-1/ -> https://ci.nodejs.org/manage/computer/test-softlayer-alpine318_container-x64-1/

<img width="782" alt="CleanShot 2023-05-21 at 09 50 44@2x" src="https://github.com/nodejs/build/assets/2352663/71ed4ec1-010d-4605-afa2-caa3bd9b3d85">

**Comment by richardlau** [comment]
FWIW the unofficial musl builds (used by @nodejs/docker ) are done with 3.15: https://github.com/nodejs/unofficial-builds/blob/6fa7a643e6ebdafb719ae0734bb7f8fdcae0e59e/recipes/musl/Dockerfile#L1

There's also https://github.com/nodejs/node/blob/4040a904dedfae8e1a60cc29ed78aab7945d272f/BUILDING.md?plain=1#L106, which may need updating (or is already out of date?).

**Comment by targos** [comment]
Do you think we should put 3.15 as last-latest and 3.17 as latest?

**Comment by targos** [comment]
Is there a simple way to generate the Dockefile from the `.j2` templates locally in order to test the Docker build?

**Comment by richardlau** [comment]
> Do you think we should put 3.15 as last-latest and 3.17 as latest?

SGTM



> Is there a simple way to generate the Dockefile from the `.j2` templates locally in order to test the Docker build?

Not that I'm aware of -- in the past I've manually substituted the templated values.

**Comment by targos** [comment]
PR for the new Dockerfiles: https://github.com/nodejs/build/pull/3351
Update to the secrets repo: https://github.com/nodejs-private/secrets/pull/265

I created 6 new Jenkins agents (by copying the old ones):
- https://ci.nodejs.org/manage/computer/test-digitalocean-alpine315_container-x64-1/
- https://ci.nodejs.org/manage/computer/test-digitalocean-alpine315_container-x64-2/
- https://ci.nodejs.org/manage/computer/test-softlayer-alpine315_container-x64-1/
- https://ci.nodejs.org/manage/computer/test-digitalocean-alpine317_container-x64-1/
- https://ci.nodejs.org/manage/computer/test-digitalocean-alpine317_container-x64-2/
- https://ci.nodejs.org/manage/computer/test-softlayer-alpine317_container-x64-1/

**Comment by targos** [comment]
I've never deployed Docker hosts, and it's not clear to me what needs to be done.
I see there is some manual steps [here](https://github.com/nodejs/build/blob/main/ansible/MANUAL_STEPS.md#docker-hosts) but I don't know exactly when to run them and if other steps are needed.

**Comment by targos** [comment]
BTW, Alpine 3.18.0 was released last week. I can skip 3.17, wdyt?

**Comment by PeterDaveHello** [comment]
Sounds great?

**Comment by targos** [comment]
@sxa We're keeping 3.15 to test on the same version that's used for unofficial releases.

**Comment by targos** [comment]
I still need help to deploy the new containers. Anyone?

**Comment by richardlau** [comment]
> I've never deployed Docker hosts, and it's not clear to me what needs to be done. I see there are some manual steps [here](https://github.com/nodejs/build/blob/main/ansible/MANUAL_STEPS.md#docker-hosts) but I don't know exactly when to run them and if other steps are needed.

The non-disruptive way would be to identify a docker host to update, mark all of its containers offline in Jenkins (I don't know of a bulk way of doing this), run through those manual steps and then run the updated `ansible/playbooks/jenkins/docker-host.yaml` playbook for the host being updated. 

I've been lazy in the past and just run the playbook, which may interrupt any in flight jobs on Jenkins running in any of the affected containers. You may need to restart the containers afterwards https://github.com/nodejs/build/blob/main/doc/jenkins-guide.md#fixing-machines-with-docker

**Comment by targos** [comment]
I ran the manual steps on `test-digitalocean-ubuntu1804_docker-x64-1`.
Now I just tried to run the playbook, but Ansible isn't able to ssh into the machine (I'm still able to ssh from my terminal):

```
fatal: [test-digitalocean-ubuntu1804_docker-x64-1]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via scp: Executing: program /usr/bin/ssh host 134.209.55.216, user (unspecified), command sftp\nOpenSSH_9.0p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /dev/null\r\ndebug2: resolve_canonicalize: hostname 134.209.55.216 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/mzasso/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/mzasso/.ssh/known_hosts2'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 19586\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\nscp: Connection closed\r\n",
    "unreachable": true
}
```

**Comment by targos** [comment]
Seems to be https://github.com/ansible/ansible/issues/78600

**Comment by targos** [comment]
https://ci.nodejs.org/manage/computer/test-digitalocean-alpine315_container-x64-1/ and https://ci.nodejs.org/manage/computer/test-digitalocean-alpine318_container-x64-1/ are online 🎉 

CI runs:
- https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/52158/
- https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/52158/

**Comment by targos** [comment]
Both ended with SUCCESS !

**Comment by targos** [comment]
Now working on `test-digitalocean-ubuntu1804_docker-x64-2`

**Comment by targos** [comment]
All done!
