### ISSUE TITLE
Problems accessing dist.libuv.org

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#3353]
We're in the process of releasing libuv `v1.45.0` and one of the steps of our release process involves publishing our assets to `dist.libuv.org` and we're not able to access that machine. Thanks to the help from @richardlau and @BethGriggs we were able to identify the jump machine to access the box (see [this](https://github.com/libuv/libuv/issues/3887#issuecomment-1542625383) for reference), but unfortunately some of our previous releasers (@bnoordhuis and @cjihrig specifically) have not been able to access to it. Could you provide some help? Thanks!

**Comment by targos** [comment]
Who needs access and what are their public keys?
We cleaned up authorized keys some time ago and I guess we didn't take libuv into account.

**Comment by santigimeno** [comment]
> Who needs access and what are their public keys? We cleaned up authorized keys some time ago and I guess we didn't take libuv into account.

That'd be me, as I was going to take care of the current release, and probably @cjihrig and @vtjnash which have been our previous releasers (@bnoordhuis don't know if you're interested). Let us know what's the best way to send our pubkeys.

**Comment by targos** [comment]
I could add the ones from https://github.com/santigimeno.keys and https://github.com/cjihrig.keys ?
The second key from https://github.com/vtjnash.keys is already authorized btw.

**Comment by santigimeno** [comment]
Adding mine works

**Comment by targos** [comment]
I added your key

**Comment by santigimeno** [comment]
> I added your key

I have access now. Thanks!

**Comment by bnoordhuis** [comment]
> @bnoordhuis don't know if you're interested

Seems I did my last release in September 2013 so yeah, no, I'm good. :-)

**Comment by santigimeno** [comment]
This is done. Thanks!
