### ISSUE TITLE
Access to test-rackspace-fedora32-x64-1

### ISSUE THREAD

**Issue by ShogunPanda** [nodejs/build#3354]
See: https://github.com/nodejs/node/issues/48000#issuecomment-1547531467

**Comment by targos** [comment]
```
ssh iojs@119.9.51.79
cd build/workspace/node-test-commit-linux
out/Release/node tools/doc/versions.mjs
```

Be patient with the latency, the machine is in Australia.

**Comment by ShogunPanda** [comment]
@targos I'm done with the machine, you can remove my key. Thanks!

**Comment by targos** [comment]
Key removed.
