### ISSUE TITLE
Wrong GCC version selected on centos7-64

### ISSUE THREAD

**Issue by targos** [nodejs/build#3365]
See https://ci.nodejs.org/job/node-stress-single-test/397/nodes=centos7-64/console

Build failed because it didn't select a GCC version and defaulted to gcc 4.8.

I found this because I'm looking into removing the `centos7-64-gcc48` label from CI and config files.

**Comment by richardlau** [comment]
I opened https://github.com/nodejs/build/issues/2847 previously -- stale bot closed it.
From memory the stress job wasn't using neither the VersionSelectorScript.groovy nor select-compiler.sh script. I think the select-compiler.sh script also doesn't handle centos7 as before we had select-compiler.sh we did compiler selection via labels.

**Comment by richardlau** [comment]
I think we're only using gcc-8 on centos7 now for Node.js 16? (We were using gcc-6 for Node.js 14.)
In which case we could swap the centos7-64 label from the stress job with centos7-64-gcc8.
Ideally we'd still need to use VersionSelector as well so that we don't end up trying to build, e.g. Node.js 20, on centos7.

**Comment by richardlau** [comment]
ah on second thoughts that probably won't work as the default compiler on CentOS 7 is gcc 4 (IIRC) and we'd need something (either select-compiler or the job definition) to use devtoolset-8.

**Comment by richardlau** [comment]
I've added VersionSelectorScript.groovy to node-stress-single-test, which prevents running on the the centos7 machines for Node.js >18.x. 
We still need a select-compiler/job edit to use devtoolset-8 for Node.js 16.x stress runs on centos7/rhel7.

**Comment by targos** [comment]
Not sure if this is still relevant.

**Comment by richardlau** [comment]
This is no longer relevant. We only have one centos7-64 machine left in the CI and nothing should be using it (and I plan to migrate it to something else).
