### ISSUE TITLE
arm8-ubuntu1404 going offline during builds

### ISSUE THREAD

**Issue by Trott** [nodejs/build#337]
Maybe I'm just being alarmist, but it appears that `arm8-ubuntu1404` goes offline during CI runs more often than is ideal. (Or maybe I'm just noticing it and it's a typical frequency for all hosts?)
- [job 2239](https://ci.nodejs.org/job/node-test-commit-arm/2239/nodes=armv8-ubuntu1404/console)
- [job 2286](https://ci.nodejs.org/job/node-test-commit-arm/2286/nodes=armv8-ubuntu1404/console)
- [job 2298](https://ci.nodejs.org/job/node-test-commit-arm/2298/nodes=armv8-ubuntu1404/console)

**Comment by jbergstroem** [comment]
Same place as well. I wonder if it dumps or something. I can look into it later.

**Comment by rvagg** [comment]
that's weird, I've rebooted the machine (xgene-2), hopefully that does the trick
