### ISSUE TITLE
Setup Terraform Cloud account

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3370]
Based on the discussion in https://github.com/nodejs/build/issues/3270#issuecomment-1562947464. cc: @nodejs/build

I will need help to setup the [Terraform Cloud Account](https://portal.cloud.hashicorp.com/sign-in) for Node.js Org. This account will be used to create a Team in Terraform Cloud and provide access to individual accounts. Can you create the account using the `*@iojs.org` email? 

**Additional steps**
- [x] Add my personal account to the team as well as `Workspace Administrator level`. [This guide can help](https://developer.hashicorp.com/terraform/tutorials/cloud/cloud-permissions) or I can do it if you share the credentials for Terraform Cloud
- [x] I will generate a token for the GitHub actions that will sync the terraform state

**Comment by targos** [comment]
Reopening until the credentials have been somehow shared with @nodejs/build-infra

**Comment by UlisesGascon** [comment]
There is no option to scope the Terraform Cloud. So any personal token might have access to all the workspaces in all the organizations as the user.

I suggest to create an account with a build team email or another alias and generate the personal token from that account for the Github Actions part 🤔

**Comment by targos** [comment]
>  create an account with a build team email or another alias

Isn't it what this issue was about?

**Comment by UlisesGascon** [comment]
> Isn't it what this issue was about?

Yes, that is correct. I expected to generate a token on behalf of the organization, but the current Terraform Cloud settings only allow me to generate tokens as myself. The next step will be to add a new member to the organization who is not a personal account and generate the token from that account. Is there a better way to manage this scenario?

**Comment by targos** [comment]
The [API Tokens page](https://app.terraform.io/app/nodejs/settings/authentication-tokens) recommends to create Team Tokens for CI/CD. What's wrong with that?

**Comment by UlisesGascon** [comment]
🤦 I didn't show that in the UI. Thanks @targos! 

I created a team API Token and it is working as expected.
![Captura de pantalla 2023-06-13 a las 9 26 31](https://github.com/nodejs/build/assets/5110813/0db7e4b7-1163-4416-974f-2e3fabca27a8)

I was not so sure about the expiration that we need, so I used a short one for now.

**Comment by targos** [comment]
> Reopening until the credentials have been somehow shared with https://github.com/orgs/nodejs/teams/build-infra

Done in the secrets repo.
