### ISSUE TITLE
Windows CI changes

### ISSUE THREAD

**Issue by StefanStojanovic** [nodejs/build#3373]
@nodejs/build

Over the following weeks, I will be making changes in Windows CI. The effort will mostly be aimed at removing Win2012-R2 machines and replacing them with newer versions of Windows. I'll also try adding VS2022 for building Node.js v20 since I've had initial success with it [in the CI](https://ci.nodejs.org/view/All/search/?q=mefi-).

I will try to keep `node-test-commit-windows-*` working all the time, but expect jobs to queue for longer periods when the number of machines is reduced.

I will try to keep other jobs working as well, but please let me know if something is not working as expected.

**Comment by nschonni** [comment]
Isn't it still the declared supported version for v16 https://github.com/nodejs/build/blob/main/doc/windows-visualstudio-supported-versions.md#for-running-nodejs. Node 16 will hit EOL in September (just ahead of 2012 EOL), so I would think it would get cleaned up then

**Comment by nschonni** [comment]
@StefanStojanovic thanks, makes sense!

**Comment by StefanStojanovic** [comment]
An update on the progress:
* We've deleted some old machines and removed them from the inventory.
* We've created some new machines and started setting them up to be added to the CI
* The new machines in release CI (6 of them) are already connected to Jenkins. We're planning to test them and when we're confident, change the old ones with the new ones.
* The new machines for test CI (10 of them) are being set up for connecting to Jenkins. Once that's done, We plan to test them, and when confident, add them mainly to the compilation jobs, but also to test jobs.

**Comment by sxa** [comment]
@StefanStojanovic Is there a reason for having six in the release CI? I can imagine one of each architecture and maybe a backup of each, but six superficially sounds a little excessive for that instance. Are the new ones now a mix of 2012 and 2022?

**Comment by StefanStojanovic** [comment]
There are 3 `Win2019_VS2019` machines. The idea is for them to replace the 2 `Win2012r2_VS2019` we're currently using, and yes, as you thought, there is one for each architecture since ARM64 is now built. The other 3 machines are `Win2022_VS2022`. My initial tests for compilation [here](https://ci.nodejs.org/view/All/job/mefi-node-compile-windows-vs2022/) and testing [here](https://ci.nodejs.org/view/All/job/mefi-node-test-binary-windows-js-suites-vs2022/) and [here](https://ci.nodejs.org/view/All/job/mefi-node-test-binary-windows-native-suites-vs2022/) showed promising results, so we plan to enable VS2022 compilation in CI, first in the test, but eventually in the release as well.

**Comment by StefanStojanovic** [comment]
Since all of the Windows CI changes are now finished in both providers (Rackspace and Azure), I'm closing this issue.
