### ISSUE TITLE
No nightly downloads since 6 June

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3378]
https://nodejs.org/download/nightly/ shows that the last nightly available is [v21.0.0-nightly202306061b4ce6981d](https://nodejs.org/download/nightly/v21.0.0-nightly202306061b4ce6981d/)
![image](https://github.com/nodejs/build/assets/5445507/f1f32567-38d6-4f47-9f81-0d47ed8b4da4)

I suspect this is fallout from https://github.com/nodejs/build/issues/3375 -- we have macOS x64 binaries in https://nodejs.org/download/nightly/v21.0.0-nightly20230526847b9e0884/ but not in https://nodejs.org/download/nightly/v21.0.0-nightly20230527be469d85da/ onwards. My suspicion is that we had pending macOS x64 release builds in the release CI that completed once the macOS 11 x64 release machine was back online which have been uploaded to staging but promotion is failing to promote as they are in directories that are now have a different owner (IIRC we change the owner after seven days (to reduce the likelihood of past releases being tampered with) and the macOS release machine was offline for longer than that).

If that is the case our options are probably one of:
- Change the owner back on the older download directories so that the promotion script can write to them and move things across from staging. The owner should get reset again by the cron job (I don't remember how often this runs so we may need to be careful the owner doesn't get changed back again to the more restricted one while the promotion script is running).
- Remove the assets from staging that cannot be moved over to the download directory.
- Manually move the assets that the promotion script is unable to move.

Refs: https://github.com/nodejs/node-addon-api/issues/1328

**Comment by mhdawson** [comment]
> Change the owner back on the older download directories so that the promotion script can write to them and move things across from staging. The owner should get reset again by the cron job (I don't remember how often this runs so we may need to be careful the owner doesn't get changed back again to the more restricted one while the promotion script is running).

Seems resonable to me.

**Comment by richardlau** [comment]
This should be fixed now, and nightlies available up to [today](https://nodejs.org/download/nightly/v21.0.0-nightly20230613d402e2ab78/).
