### ISSUE TITLE
Heads up of Node.js security releases 20 June 2023

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#3380]
As per the Node.js security release process, this is the FYI that there is going to be a security release 20 June 2023

https://github.com/nodejs/nodejs.org/pull/5434

**Comment by richardlau** [comment]
@RafaelGSS Is the usual 48 hour CI lockdown sufficient, or was more time desired?

**Comment by RafaelGSS** [comment]
Since I'll be the only releaser. I feel more confident locking the CI by this thursday.

**Comment by richardlau** [comment]
I've posted an announcement to the collaborators announcing our intention to lock the CI down from Thursday: https://github.com/nodejs/collaborators/discussions/166

**Comment by richardlau** [comment]
CI has now been locked down.

**Comment by richardlau** [comment]
CI has now been unlocked.
