### ISSUE TITLE
NearForm Benchmarking Servers

### ISSUE THREAD

**Issue by efrisby** [nodejs/build#3390]
Hi, 

We are making a number of changes to the NearForm HQ comms setup, reducing services and dependencies. We only have a few staff that use the building so we are scaling back operations and systems hosted HQ. 

A result of this will have an impact on the devices that NearForm host for the Node Benchmarking testing, currently they are connected via our firewall and each device is configured with their own public ip. With the change, we are taking out the current firewall and looking to simplify the network setup. 

What we would like to find out, is there the possibility of either moving these devices to another site that someone might have available or if we keep these existing devices, what recommendation would you advise regarding connectivity. At the moment they have public ip's assigned to each to allow connection, is that a requirement or is having the device online and having internet access enough. 

The first question we would like to confirm is, are these devices a requirement for the future and who needs to connect to them if they are. Perhaps if we can get those questions answered, we can go from there. 

Thanks,
Eamonn

**Comment by mhdawson** [comment]
I think the main use for the benchmarking servers is for the https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-micro-benchmarks/ jobs.  

@richardlau do you know if they are used for other jobs as well?

In terms of moving them, we don't have another physical location for machines, that's why NearForm volunteered in the first place based discussion with Intel.

In terms of who needs to connect to them through ssh. The build team needs that level of access. So they need to be accessible from the internet for the build team to ssh in, but for some other machines that through some sort of proxy where there is one public IP and each machine is accessed by using a different port.

**Comment by richardlau** [comment]
> 
> @richardlau do you know if they are used for other jobs as well?
> 

We also use the Intel benchmark machines to test/build V8 in https://ci.nodejs.org/job/node-test-commit-v8-linux/. The last time I checked we were able to run the x64 builds of that on our other rhel8-x64 machines albeit at a longer build time.

> A result of this will have an impact on the devices that NearForm host for the Node Benchmarking testing

@efrisby Just to confirm, is this just restricted to the Intel Xeon servers with IP addresses:
- 92.51.196.114
- 92.51.196.115

or does it also include other machines (e.g. macs, Windows) used by Node.js hosted at NearForm?

**Comment by mhdawson** [comment]
@richardlau thanks for confirming that we use them for other jobs as well.

**Comment by efrisbyus** [comment]
@richardlau @mhdawson @RafaelGSS 

Hi all, sorry about the long detail in replying to this issue. We have been doing considerable updates to NearForm HQ network where the Nodejs benchmarking machines are based. 

Part of the work been carried out includes installing a new fibre internet line with a new service provider, the result of which will mean we will have a brand new public IP range that will need to be applied to all current benchmarking machines we have in NearForm HQ. 

For records here are the devices and current IP addresses that we currently host: 

Intel® Xeon® Processor E5-2600 (92.51.196.114)
Intel® Xeon® Processor E5-2600 (92.51.196.115)

Mac Mini (83.147.191.66)
Mac Mini (83.147.191.67)
Mac Mini (83.147.191.75)
Mac Mini (83.147.191.76)

Surface Pro machine (83.147.191.73)
Surface Pro machine (83.147.191.74)

On the Mac Mini machines there are also a number of Virtual Machines with the IP address as follows: 

83.147.191.69
83.147.191.70
83.147.191.71
83.147.191.72


Once the new Fibre line is configured, the above devices will be configured with new public ip addresses. Can we please confirm who this information needs to be provided to as it will have an impact on connections and testing. 

**Also, as part of the restructure of NearForm HQ network, would it be possible to make the proposal of moving the benchmarking to a dedicated server in the cloud that the testing could be carried out on. I can look into NearForm covering the cost but if it would be possible if one of the nodejs community could get a rough costing how much this would be per month I can raise this request in NearForm to see if we can cover the charge?** 

If you can confirm the changes above, if we need to plan the change of IP addresses to the new IP range, I can confirm the date of the change in the next week or two. 

Thanks,
Eamonn

**Comment by mhdawson** [comment]
I think there was some discussion though email. We also discussed in the build WG meeting today @efrisby is this still something that needs to move forward?

**Comment by mhdawson** [comment]
We believe we can close this as it is superseded by https://github.com/nodejs/build/issues/3615. @efrisby please let us know if that is not the case and we will reopen.
