### ISSUE TITLE
Notarization failing on macOS

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3393]
e.g. https://ci-release.nodejs.org/job/iojs+release/nodes=osx11-release-pkg/9440/console

```console
19:03:27 1 error occurred:
19:03:27 	* 1 error occurred:
19:03:27 	* You must first sign the relevant contracts online. (1048) (1048)
```

Probably requires someone to sign into Build's Apple account and check if there are updated license terms to accept. Unfortunately I'm no longer able to do so.

**Comment by RafaelGSS** [comment]
Waiting for this resolution to push security releases out.

**Comment by mhdawson** [comment]
There was an agreement and I accepted it.

@RafaelGSS can you check if its working now?

**Comment by RafaelGSS** [comment]
osx is fixed. We're having issues with [centos7-ppcle-release-64](https://ci-release.nodejs.org/job/iojs+release/9442/nodes=centos7-ppcle-release-64/) now.

**Comment by richardlau** [comment]
https://ci-release.nodejs.org/job/iojs+release/nodes=osx11-release-pkg/9442/ successfully notarized.

Opened https://github.com/nodejs/build/issues/3394 for centos7-ppcle-release-64.
