### ISSUE TITLE
Drop modules.nodejs.org and packages.nodejs.org CNAME mappings?

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3395]
We have CNAME mappings for modules.nodejs.org and packages.nodejs.org in our Cloudflare account. These supposedly redirect to npmjs.org, but are not working due to Cloudflare's security policy:

![image](https://github.com/nodejs/build/assets/5445507/2328b0ca-66f0-48d7-91d0-eea80d93e407)

We could replace these with Cloudflare Page Rules but we only have a limited number of those (13 left out of 50 and we'll need some of those for https://github.com/nodejs/build/issues/3366). As far as I know we have had no reports/complaints about either of the two broken mappings and I can't find references to either of them in GitHub for the nodejs org -- perhaps we should just drop them completely and fall back to the generic subdomain mapping back to the nodejs.org website?

cc @nodejs/build-infra FYI @nodejs/tsc @nodejs/npm 

Refs: https://github.com/nodejs/build/pull/3391#discussion_r1236284669
Refs: https://github.com/nodejs/build/pull/3391#discussion_r1236285111

**Comment by targos** [comment]
It would be nice to know when they stopped working, but I think we can just drop them.

**Comment by wraithgar** [comment]
My guess is they stopped working when npm moved from fastly to cloudflare, many many years ago.  The same thing happened to yarn's "registry" when we made the move.  I haave pinged our registry/infrastructure team to see if there was any recent change here just in case.

Putting my security hat on it's probably best not to CNAME out to infrastructure you don't own or control.  Deleting these would be best.

**Comment by mcollina** [comment]
+1 to delete

**Comment by jbergstroem** [comment]
I see no problem with removing these.

**Comment by richardlau** [comment]
Since there have been no objections, I have deleted the CNAME entries for `modules.nodejs.org` and `packages.nodejs.org`.

<details>

![image](https://github.com/nodejs/build/assets/5445507/731c5312-0b0f-497d-a999-76148407db1c)
![image](https://github.com/nodejs/build/assets/5445507/ef0a92b6-ed2c-45fd-a4d1-a887371b5720)

</details>
