### ISSUE TITLE
DNS Wildcard problem?

### ISSUE THREAD

**Issue by bl-ue** [nodejs/build#3404]
Problem:
https://asdfiasdfuaspdajlrg.nodejs.org/ is a valid URL.  You can put anything in place of `asdfiasdfuaspdajlrg`.

**Comment by ovflowd** [comment]
I'm transferring this to @nodejs/build as this is a CloudFlare configuration issue.

**Comment by richardlau** [comment]
> The tricky part is finding the legacy reason for why adding a wildcard in the first place. I can look around a bit.

@jbergstroem I don't suppose you ever found out why the wildcard was added?

**Comment by jbergstroem** [comment]
> > The tricky part is finding the legacy reason for why adding a wildcard in the first place. I can look around a bit.
> 
> @jbergstroem I don't suppose you ever found out why the wildcard was added?

Unfortunately, no.

**Comment by richardlau** [comment]
I've tried searches on https://github.com/nodejs/build and https://github.com/nodejs/iojs.org but couldn't find anything indicating why we have the wildcard CNAME entry for nodejs.org. In the absence of any evidence as to what it was for, I'm leaning towards removing it and seeing if anyone notices/complains.

**Comment by MoLow** [comment]
I think we discussed in the TSC meeting adding a 301 redirect rule to all undefined DNS records to just redirect them to www.nodejs.org. AFAIK cloudflare has this built-in

**Comment by richardlau** [comment]
Actually I think I may have a theory... in https://github.com/nodejs/build/blob/main/ansible/www-standalone/resources/config/nodejs.org?plain=1 we have a number of subdomains being redirected in nginx, e.g. docs.nodejs.org https://github.com/nodejs/build/blob/621e46250781d93ef86d7a828ed2c732765dc3ee/ansible/www-standalone/resources/config/nodejs.org?plain=1#L355 that we do not have explicit CNAME entries for.  So we should probably first add explicit CNAME entries for those subdomains before removing the wildcard so that those redirects continue to work. Some of these could be turned into Cloudflare rules.

**Comment by targos** [comment]
We found out yesterday that a few subdomains are (ab)used to directly access our server: `registry.nodejs.org` (our old friend, the broken Artifactory setup) `capacitacioni-release.nodejs.org` `kdxwif.cn.nodejs.org` `sticky.nodejs.org` `shaikon.com.nodejs.org`.
Removing the wildcard should help to reduce load issues on the server.

**Comment by targos** [comment]
List of `server_name` (based on files in `ansible/www-standalone/resources/config`) that are not explicitly defined in Cloudflare DNS:

- [ ] `benchmarking.nodejs.org`
- [ ] `docs.nodejs.org`
- [ ] `api.nodejs.org`
- [ ] `dist.nodejs.org`
- [ ] `blog.nodejs.org`

**Comment by richardlau** [comment]
> * [ ]  `benchmarking.nodejs.org`

I think we used to have a CNAME for this but it was removed https://github.com/nodejs/build/issues/2485

**Comment by richardlau** [comment]
I've added CNAME entries for everything in https://github.com/nodejs/build/issues/3404#issuecomment-1632032073.

I've just removed the * CNAME entry. FTR it looked like this:
![image](https://github.com/nodejs/build/assets/5445507/eae0401b-ff5b-4c3d-9fa6-52de0ed3ddf2)

**Comment by richardlau** [comment]
It looks like enabling proxy on `blog.nodejs.org` breaks test/internet/test-dns.js: https://github.com/nodejs/node/issues/48868
`dns.resolveCname()` is returning `ENODATA` for any of our proxied CNAME entries.

We did not have proxy enabled on the now removed `*.nodejs.org` CNAME entry that used to catch `blog.nodejs.org`. I've turned off proxy status just for `blog.nodejs.org`.
