### ISSUE TITLE
Request timeout while downloading Node v14.20.0 tar.gz file - Breaking CI 

### ISSUE THREAD

**Issue by samueldcarvalho** [nodejs/build#3408]
My CI pipeline is breaking caused by a slow Node v14.20 tar.gz file download. Trying to do this manually by the link below, i got the same problem (a slow download). I realized the problem is a req timeout in the download step.  

The pipeline downloads Node by this link: https://nodejs.org/dist/v16.20.0/node-v16.20.0-linux-x64.tar.gz

Have any reason or problem in Node CDN for causin this problem? It's just for me? I'm downloading from Brazil.

**Comment by samueldcarvalho** [comment]
Problem apparently was fixed. Thanks.

**Comment by nschonni** [comment]
Note that Node 14 is now EOL, so it no longer receives any support
