### ISSUE TITLE
Turn on Smart Tier Caching in Cloudflare?

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3409]
Refs: https://developers.cloudflare.com/cache/how-to/tiered-cache/

During the [discussion in #nodejs-build in Slack](https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1688458152494889) it was noted we had "a lot of CF servers" connected to the origin web server. 

Cloudflare has an option for Smart Tier Caching, which promises
> This practice improves bandwidth efficiency by limiting the number of data centers that can ask the origin for content, reduces origin load, and makes websites more cost-effective to operate.

It may be worth turning this on.

cc @nodejs/build-infra

**Comment by targos** [comment]
+1

**Comment by MoLow** [comment]
+1

**Comment by richardlau** [comment]
I've now switched this on for nodejs.org (under Caching->Tiered Cache).
