### ISSUE TITLE
Redesign Cloudflare cache purging

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3410]
I believe most of the server issues we're currently having with nodejs.org stem from our rather crude "purge everything" strategy. This is currently done by [`ansible/www-standalone/resources/scripts/cdn-purge.sh.j2`](https://github.com/nodejs/build/blob/HEAD/ansible/www-standalone/resources/scripts/cdn-purge.sh.j2) (which [runs every five minutes](https://github.com/nodejs/build/blob/322121334e8344daf7520d405239597f6505662f/ansible/www-standalone/tasks/site-setup.yaml#L103)) if a purge has been locally queued.

Purges are queued by calling [`ansible/www-standalone/resources/scripts/queue-cdn-purge.sh`](https://github.com/nodejs/build/blob/HEAD/ansible/www-standalone/resources/scripts/queue-cdn-purge.sh). This is done every time:
- the website is rebuilt https://github.com/nodejs/build/blob/322121334e8344daf7520d405239597f6505662f/ansible/www-standalone/resources/scripts/build-site.sh#L61. This also includes when the website index HTML page is detected as being older than `index.json` which triggers a website rebuild (I believe this is so the website picks up the most recent current and LTS releases for the download buttons/pages) https://github.com/nodejs/build/blob/322121334e8344daf7520d405239597f6505662f/ansible/www-standalone/resources/scripts/check-build-site.sh#L16
- a release is promoted (during shasum creation) https://github.com/nodejs/build/blob/322121334e8344daf7520d405239597f6505662f/ansible/www-standalone/tools/promote/resha_release.sh#L28
- a build (e.g. nightly/V8 canary/release) is promoted https://github.com/nodejs/build/blob/322121334e8344daf7520d405239597f6505662f/ansible/www-standalone/tools/promote/_promote.sh#L61. Note that nightly/V8 canary builds get [promoted every 30 mins](https://github.com/nodejs/build/blob/322121334e8344daf7520d405239597f6505662f/ansible/www-standalone/tasks/site-setup.yaml#L101) which may mean an iojs+release build can have multiple promotions depending on when the sub-builds complete and upload their assets to staging.

To give an idea of frequency, these are the cdn-purges from today (including the Node.js 20.4.0 release):
```text
2023-07-05T06:35:01+00:00, nodejs, promote
2023-07-05T07:35:01+00:00, nodejs, promote
2023-07-05T11:05:01+00:00, nodejs, promote
2023-07-05T12:35:01+00:00, nodejs, promote
2023-07-05T13:35:02+00:00, nodejs, promote
2023-07-05T14:00:01+00:00, nodejs, promote resha_release
2023-07-05T14:55:01+00:00, nodejs, build-site
2023-07-05T16:30:01+00:00, nodejs, build-site
``` 

The first two "promote"s are from the nightly build, the next three from the V8 canary, and the last "promote" (and "resha_release") from the manual promotion of 20.4.0. The subsequent "build-sites" are from merging https://github.com/nodejs/nodejs.org/pull/5473 and https://github.com/nodejs/nodejs.org/pull/5474 respectively.

Purging everything is rather heavy handed, but our current options in Cloudflare are to either purge everything (as we are doing) or purge a list of static URLs (there are further options only available for enterprise accounts which we do not have access to). Switching to a more selective cache purge requires us to determine what URLs to purge for all of the above scenarios that we are currently purging everything.

**Comment by richardlau** [comment]
I guess an interesting question would be, what would happen if we didn't purge the Cloudflare cache at all? One assumes that that may lead to getting stale pages/content (may even vary depending on what CF server you end up connecting to). Would new builds/releases not show up as 404 not founds are cached?

We could temporarily comment out https://github.com/nodejs/build/blob/917f85f0791a06caeb8246ea6d79df28fbf479ce/ansible/www-standalone/resources/scripts/cdn-purge.sh.j2#L43-L49 or the cron job that runs that script on the 5 min timer https://github.com/nodejs/build/blob/322121334e8344daf7520d405239597f6505662f/ansible/www-standalone/tasks/site-setup.yaml#L103.

**Comment by richardlau** [comment]
Now that we have a CF enterprise account, we have more purging options available to us, but that still requires engineering work to determine what (if anything) needs to be purged and pass that information between `queue-cdn-purge.sh` and `cdn-purge.sh` (or design something else completely) and make the relevant CF API call.

**Comment by nschonni** [comment]
The only thing I can think of that might need a low expiry would be the index.tab/json. 

I can't think of anything that really would need to be purged unless the cache got poisoned.

**Comment by targos** [comment]
Also directory indexes

**Comment by nschonni** [comment]
Was looking for something else, and found a little previous discussion over in https://github.com/nodejs/build/issues/2375 too

**Comment by targos** [comment]
And for the website, all the generated html pages. JS and CSS chunks should be fine since they have content hashes in their file names.

**Comment by targos** [comment]
There are also all "latest" symlinks like https://nodejs.org/docs/latest, https://nodejs.org/dist/latest/, https://nodejs.org/dist/latest-v20.x/, etc.

**Comment by targos** [comment]
Note that we now have access to enterprise features such as:
- [Purge by URL prefix](https://developers.cloudflare.com/cache/how-to/purge-cache/purge_by_prefix/)
- [Purge by cache-tags](https://developers.cloudflare.com/cache/how-to/purge-cache/purge-by-tags/)
