### ISSUE TITLE
Release CI Windows changes

### ISSUE THREAD

**Issue by StefanStojanovic** [nodejs/build#3411]
As I've mentioned in https://github.com/nodejs/build/issues/3373, there are six new Windows machines in the release CI. Half of them are planned to replace old VS2019 machines, and the other half to add VS2022 support. I've set these machines up and run the initial tests, but they are not used in any jobs. I plan to enable them and disable the old VS2019 machines (they'll get deleted eventually, although I do not want to rush this).

I plan to do this in 2 days, on Friday afternoon, unless there are some objections to that. If anyone has any concerns, please raise them here. Thanks in advance!

**Comment by targos** [comment]
@StefanStojanovic I don't know if it's related, but [windows-update-reboot](https://ci-release.nodejs.org/job/windows-update-reboot/2252/console) is stuck.

**Comment by StefanStojanovic** [comment]
> @StefanStojanovic I don't know if it's related, but [windows-update-reboot](https://ci-release.nodejs.org/job/windows-update-reboot/2252/console) is stuck.

Yes, it's related. That happens because I set new VS2019 machines temporarily offline, then reenable them once a day so [`windows-update-reboot`](https://ci-release.nodejs.org/job/windows-update-reboot/) can pass.

**Comment by StefanStojanovic** [comment]
I just wanted to add another comment, to explain my concerns about this topic. New and old machines are not completely identical, first and the most obvious difference is that they use different versions of Windows. Another one is that they have different versions of Windows 10 SDK installed, and there are probably some other differences as well.

My concern is that the new build of Node.js will not work as the old one on all platforms. I tested this and didn't encounter any issues, but there're always possibilities to be proven wrong. For that reason, the two old machines will stay there disabled for some time, so that if needed, we can turn them back on while reconfiguring new machines.

**Comment by StefanStojanovic** [comment]
Closing this since the machines are enabled and I landed changes in the secrets repo today.
