### ISSUE TITLE
node-stress-single-test-fips

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#343]
I recently updated the normal fips test and this one may need to be updated as well. Before doing that I wanted to talk to whoever setup it up as its not been run in a long time.  So far I've not figured out who created it from the info in the job.

**Comment by mhdawson** [comment]
@orangemocha  any chance it was you ?

**Comment by orangemocha** [comment]
@joaocgreis implemented node-stress-single-test, not sure who implemented the fips version.

**Comment by joaocgreis** [comment]
I implemented it, to help with https://github.com/nodejs/node/issues/4200 . @mhdawson feel free to go ahead and update it

**Comment by mhdawson** [comment]
Ok updated and passing run: https://ci.nodejs.org/job/node-stress-single-test-fips/4/
