### ISSUE TITLE
Missing trademark policy

### ISSUE THREAD

**Issue by mcollina** [nodejs/build#3434]
The old Node.js website had a page that included our logos and the trademark policy.
I can't find this anymore

**Comment by richardlau** [comment]
Added 
![image](https://github.com/nodejs/build/assets/5445507/b77d5bc7-46c0-4bc2-a640-675e61b6a533)

based on the above and also our nginx rules:
https://github.com/nodejs/build/blob/f7e0f90a55b0c866041668e4285a16274f1e36f7/ansible/www-standalone/resources/config/nodejs.org?plain=1#L330
https://github.com/nodejs/build/blob/f7e0f90a55b0c866041668e4285a16274f1e36f7/ansible/www-standalone/resources/config/nodejs.org?plain=1#L341
https://github.com/nodejs/build/blob/f7e0f90a55b0c866041668e4285a16274f1e36f7/ansible/www-standalone/resources/config/nodejs.org?plain=1#L357

**Comment by richardlau** [comment]
FWIW a direct link to the trademark policy is in the footer of the current nodejs.org website:
![image](https://github.com/nodejs/build/assets/5445507/fe33a507-3a24-49c8-8d38-b16ca74d3748)

**Comment by ovflowd** [comment]
@richardlau both `regexes` do not have a `^` at the beginning so I suppose anything matching these URLs will redirect there...

Including links like https://nodejs.org/dist/v0.6.4/docs/trademark-policy.pdf (which still exist)

**Comment by richardlau** [comment]
> I guess that's fine? But just raising awareness that this rule has more implications than the examples above.

It was deliberate for the second one to catch e.g. `/en/about/trademark` (i.e. with the language in the URL).

I'm inclined to leave it but if anyone finds a link that probably shouldn't be redirected by that rule we can amend the rules. Equally I won't stand in the way of anyone else changing the rules as appropriate.

**Comment by ovflowd** [comment]
> It was deliberate for the second one to catch e.g. /en/about/trademark (i.e. with the language in the URL).

second one is fine, it's more about the first one 🤔 

> I'm inclined to leave it but if anyone finds a link that probably shouldn't be redirected by that rule we can amend the rules. Equally I won't stand in the way of anyone else changing the rules as appropriate.

Sure sounds good to me.
