### ISSUE TITLE
Almost all the windows machines are DOWN

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3435]
### Overview

This incident started the last Friday, seems like all the testing windows machines are currently down, in the release ci some windows machines are running.

[Slack discussion](https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1690699618239899)

#### Release machines

![Captura de pantalla 2023-07-30 a las 19 33 15](https://github.com/nodejs/build/assets/5110813/425f9d7c-7869-48af-95a2-a73b336952fb)

#### Test machines

![Captura de pantalla 2023-07-30 a las 19 33 52](https://github.com/nodejs/build/assets/5110813/37e70a01-5e55-4469-9a42-60c4a72600b0)
![Captura de pantalla 2023-07-30 a las 19 34 54](https://github.com/nodejs/build/assets/5110813/c9728310-b6a5-4c6a-8592-8a294d1b69df)

### Next steps

- [ ] Reboot all the machines

**Comment by UlisesGascon** [comment]
Seems like the root cause is a connectivity issue, I will check Azure and Rackspace

![Captura de pantalla 2023-07-30 a las 19 50 38](https://github.com/nodejs/build/assets/5110813/8008e701-c0e4-49bb-9d77-fa96d4a8a929)

**Comment by UlisesGascon** [comment]
I rebooted the machines in Azure and Rackspace. Overall, around 20 machines are back. Most of the down machuines currently are from Rackspace

### Relese
![Captura de pantalla 2023-07-30 a las 20 31 38](https://github.com/nodejs/build/assets/5110813/f67e610a-180f-4c3f-bee2-690b77135b76)



### Testing
![Captura de pantalla 2023-07-30 a las 20 30 09](https://github.com/nodejs/build/assets/5110813/026cd39d-7d67-4ef7-984c-47d6199ad233)
![Captura de pantalla 2023-07-30 a las 20 30 34](https://github.com/nodejs/build/assets/5110813/17975a87-64a1-4464-adf3-8e3a38d12e72)


@nodejs/build: I will suggest to check more in detail the root cause and the logs from the machine to check by the connection with Jenkins is not properly stablished.

**Comment by rluvaton** [comment]
This may be related to recent Jenkins upgrade (Cc @targos )

**Comment by StefanStojanovic** [comment]
A quick update: I continued what @UlisesGascon started and went through machines and got all of them except a few back online. Looks like the worst has passed, but this should be investigated so we know the root cause.

**Comment by UlisesGascon** [comment]
Thanks a lot @StefanStojanovic!

**Comment by mhdawson** [comment]
Discussed in the Build WG meeting, agreed to close. Will re-open if we get another similar outage.
