### ISSUE TITLE
Typo in Cloudflare needs fixing

### ISSUE THREAD

**Issue by Trott** [nodejs/build#3438]
Not sure how much of a problem this is causing, but seems like it might be a source of our frequent 500 errors issue.

Our Cloudflare config caches the non-existent `downloads` directory instead of the `download` directory. I do not have access to fix it. @mhdawson is out-of-office. It's very late in Europe/Africa/Asia. So I'm hoping @rvagg or @jbergstroem have access and can fix it.

![image](https://github.com/nodejs/build/assets/718899/e7e8d62d-a260-49de-80ae-1171cf4d6849)

**Comment by ovflowd** [comment]
Quick note that this Rule can be edited on: Caching > Cache Rules on Cloudflare

**Comment by Trott** [comment]
And in case any Europe/Africa/Asia folks who have access happen to be working late/early: @nodejs/build-infra

**Comment by UlisesGascon** [comment]
I can fix it @Trott. Let me try 👍

**Comment by UlisesGascon** [comment]
Rule updated!

![Captura de pantalla 2023-08-01 a las 8 02 09](https://github.com/nodejs/build/assets/5110813/bd12055e-51af-432f-a8d1-dcc3af57caf9)
