### ISSUE TITLE
Cannot access previous tap results for citgm

### ISSUE THREAD

**Issue by evanlucas** [nodejs/build#345]
We can view the tap extended test results of each individual build, but it seems that when pulling the plain text version, only the latest is available.

https://ci.nodejs.org/job/thealphanerd-tap-smoker/nodes=fedora21/7/tapResults/ 

Clicking the File: smoker/test.tap only shows the results from the latest build. It would be awesome if we could get plain text tap results for each individual build without having to parse html

**Comment by TheAlphaNerd** [comment]
@evanlucas can you share with me a tap result that has past results so I can compare?

There is a file created everytime afaik, and that file is new every time

**Comment by evanlucas** [comment]
https://ci.nodejs.org/job/thealphanerd-tap-smoker/nodes=fedora21/4/tapResults/ is a good one. The tap results shows 5 failures, but the tap file only shows 1

**Comment by TheAlphaNerd** [comment]
OHHHH I get it now... the tap file it is writing is permanent on the machine and getting over written each time... that is odd

**Comment by maclover7** [comment]
ping @evanlucas @MylesBorins -- is this still an issue? It looks like the `thealphanerd-tap-smoker` job doesn't exist anymore on ci.nodejs.org.

**Comment by refack** [comment]
AFAIK the job has been migrated from pure tap to [tap2junit](https://github.com/jbergstroem/tap2junit) and now Jenkins keeps the full results for us.

Closing, but if anyone knows otherwise, please reopen.
