### ISSUE TITLE
Request for read only access to cloudflare

### ISSUE THREAD

**Issue by MoLow** [nodejs/build#3455]
I want to get more involved in the website / downloads infra, starting with a better understanding of the current layout

Refs: https://github.com/nodejs/build/pull/3454

**Comment by UlisesGascon** [comment]
cc: @nodejs/build

**Comment by richardlau** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by mhdawson** [comment]
I think - https://github.com/nodejs/build/pull/3454 will cover this as @MoLow should have full access soon.

**Comment by richardlau** [comment]
@MoLow Since we're adding you to build-infra, I've invited you to our CloudFlare account with full privileges.
