### ISSUE TITLE
https://nodejs.org/dist/v14.15.1/node-v14.15.1-linux-x64.tar.xz is throwing 500 Error.

### ISSUE THREAD

**Issue by ahsanra** [nodejs/build#3456]
Pipeline breaks when this happens and it is happening, i think its is a cache issue.
https://nodejs.org/dist/v14.15.1/node-v14.15.1-linux-x64.tar.xz

on https://nodejs.org/dist/v14.15.1/

**Comment by UlisesGascon** [comment]
Thanks for reporting @ahsanra! I can confirm the 500 error. The other binaries for the same release are working fine 

```
curl --head https://nodejs.org/dist/v14.15.1/node-v14.15.1-linux-x64.tar.xz
HTTP/2 500
date: Thu, 17 Aug 2023 12:48:05 GMT
content-type: text/html
cf-cache-status: HIT
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 7f82078348e33851-MAD
```

```
curl --head https://nodejs.org/dist/v14.15.1/node-v14.15.1-win-x64.zip
HTTP/2 200
date: Thu, 17 Aug 2023 12:48:50 GMT
content-type: application/zip
content-length: 28785461
last-modified: Mon, 16 Nov 2020 11:33:09 GMT
etag: "5fb26375-1b73b35"
cache-control: public, max-age=3600, s-maxage=14400
cf-cache-status: HIT
accept-ranges: bytes
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 7f82089cbcb53670-MAD
```

**Comment by targos** [comment]
Wait, error 500 is cached? This is unexpected. /cc @ovflowd

**Comment by ovflowd** [comment]
> Wait, error 500 is cached? This is unexpected. /cc @ovflowd

🤷

We haven't changed NGINX configuration, and /dist cache rules come from NGINX... As you can see on the 2nd request.

I genuinely doubt that 5XX errors are being cached, but sounds like a Cloudflare-only cache? Not sure what to do here.

cc @MattIPv4 any suggestion?

**Comment by targos** [comment]
There is no cache-control header, so I think it depends on CF config, which change quite a bit when the site was migrated to Vercel

**Comment by MattIPv4** [comment]
Just looked through the NGINX config, and I think actually we may only set no-cache for 404s? Would appreciate another set of eyes reading through it to confirm though.

Albeit, Cloudflare by default won't cache a 500, but if the default cache header in NGINX is being applied or if Cloudflare is configured to cache everything, then I could see this happening.

We should probably add a location block to handle all other errors in NGINX and make sure a no-cache is set?

**Comment by targos** [comment]
Cloudflare is configured to "respect origin".

Also, they shouldn't cache 500 by default:

![CleanShot 2023-08-17 at 15 09 19](https://github.com/nodejs/build/assets/2352663/44b9aff4-0058-47c6-aa7c-3a5d0ddbca68)

**Comment by ovflowd** [comment]
Nope, @MoLow the cURL requests that @UlisesGascon shown clearly state a cache there. Even if it's a short cache.

**Comment by MattIPv4** [comment]
The cURL output is honestly rather odd, a cache hit from Cloudflare, but with no age/expiry etc... I don't think I've ever seen that before. But as I said, it does somewhat line up with what I think the configuration is, where we've told Cloudflare it is "eligible for caching" and to "respect the origin", but the origin didn't set a specific cache control etc.

**Comment by MoLow** [comment]
> Nope, @MoLow the cURL requests that @UlisesGascon shown clearly state a cache there. Even if it's a short cache.

is that `cf-cache-status: HIT`?

**Comment by riosje** [comment]
Hello guys thanks for taking care on this

I think you would need to purge some additional URLs at Cloudflare or purge the whole thing.

I'm experiencing error 500 with `node-v16.19.1-linux-x64.tar.xz`
```SHELL
curl --no-progress-meter -JRL --fail-with-body -o node-v16.9.1-linux-x64.tar.xz https://nodejs.org/dist/v16.9.1/node-v16.9.1-linux-x64.tar.xz
curl: (22) The requested URL returned error: 500
```

This is the cache status
```
< etag: "63ee50bd-15703c4"
< cache-control: public, max-age=3600, s-maxage=14400
< cf-cache-status: HIT
< age: 11624
```

**Comment by ovflowd** [comment]
We haven't done anything yet.

**Comment by riosje** [comment]
Hi @ovflowd, I don't know what you mean exactly with `We haven't done anything yet.` but there is clearly wrong behavior from Cloudflare side by caching that URL paths with`HTTP 500 ERROR` and it requires to be purged to access properly the objects from any edge location.

**Comment by ovflowd** [comment]
Have you read this issue? Please do so. We have plans to address these issues, and to be clear, these are recurring issues. Clearing the cache will not solve what you're facing.

I mentioned that we haven't deployed any of the changes that we have planned to address some of these issues.

**Comment by ahsanra** [comment]
I would like to close the issue with a thanks to @MoLow @ovflowd @UlisesGascon @targos. 

The issue is resolved for now and should be taken cater at a wider level.
