### ISSUE TITLE
Request for read-only access to Cloudflare

### ISSUE THREAD

**Issue by MattIPv4** [nodejs/build#3457]
👋 I've been lurking and trying to help out quite a bit now with the NGINX/origin side of things for the site and its downloads, and would appreciate having read-only access to get a better sense of where things are at (both configuration and traffic flow) without having to rely on screenshots from other folks in Slack/issues when triaging issues like #3456.

**Comment by UlisesGascon** [comment]
+1 @MattIPv4 has been doing a great job in the slack channels and helping us 👍

**Comment by mhdawson** [comment]
I'm good with read-only access. We want to get the config into GitHub through terraform where it wouldbe public anyway.

**Comment by MattIPv4** [comment]
Yah, getting the config into Terraform would be great so everyone can see it and create PRs for it. The other big thing that read-only access to Cf gives though is access to the analytics for the domain and the load balancer configs, so I can take a look at response codes to see if the origin is doing well, check if the LB has failed over etc. :)

**Comment by targos** [comment]
+1

**Comment by richardlau** [comment]
@MattIPv4 I've invited you to our CloudFlare account with the Administrator Read Only role.

**Comment by MattIPv4** [comment]
Received and accepted, thank you!
