### ISSUE TITLE
missing signed checksum files for v0.1.14

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3468]
While working in https://github.com/UlisesGascon/nodejs-distribution-system-monitoring/issues/6 I discovered that [v0.1.14](https://nodejs.org/dist/v0.1.14/https://nodejs.org/dist/v0.1.14/) does not include the files: `SHASUMS256.txt.asc`, `SHASUMS256.txt.sig`. Actually there is a single binary, so I assume that this release is different than others.

![Captura de pantalla 2023-08-21 a las 20 07 59](https://github.com/nodejs/build/assets/5110813/142462c6-7efb-485a-bd26-41523e12872c)

**Comment by richardlau** [comment]
@UlisesGascon For historic releases there's not much we can do about them. Pre-convergence (i.e. earlier than iojs or Node.js 4) releases were done internally by Joyent, and followed different processes, possibly following manual steps. I do know some of the tooling we have (including the old pre-next.js Node.js website) had all sorts of special cases for Node.js 0.12 and 0.10 and didn't even consider the releases before those.

I don't know from which release that gpg signatures started being used.
