### ISSUE TITLE
[Payments] Cloudflare invoice CFUSA7717437

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3474]
We received an email in `build@iojs.org` about this:

> We have been unable to process your renewal payment (Invoice # CFUSA7717437). This usually occurs when your bank issues a new card, your existing card has expired, or a billing error caused by your bank. We will try again automatically on August 27.
>
> **Will my service be affected?**
>
>Yes, Cloudflare has resumed charging all outstanding invoices as of January 18, 2023. If we do not receive payment 5 days after your invoice is issued, your payment services will be downgraded.
>
>Ongoing payment issues may cause an interruption in service. To avoid a service interruption, please take a moment to review or update your billing information. If you haven't set up a backup payment method yet, consider adding one to avoid future payment issues.

The invoice total amount is `6,68 US$`. Checking the payment information, seems like the credit card has expired in `08/20`, so I assume that we have a sponsorship in place (so we don't directly pay the invoices).

cc: @nodejs/build @bensternthal

**Comment by ovflowd** [comment]
@UlisesGascon we shouldn't be invoiced with anything. cc @jasnell

**Comment by UlisesGascon** [comment]
Discussion ongoing in Slack. [Link](https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1693138536600899)

**Comment by UlisesGascon** [comment]
This has been solved, Cloudflare team has extended the sponsorship to cover **$100/month for cache reserve free usage** and we got an email confirmation.

>  Dear Customer:
>
> This email is to confirm that you recently changed your subscription to Cache Reserve - No Cost.
If you think you received the email in error, please contact us at the Support Portal for assistance.
>
>Sincerely.
>The Cloudflare team 

This issue is considered close, I will keep monitoring the email in case that we detect any additional email regarding the previous invoice.

**Comment by richardlau** [comment]
We appear to have got another email ten hours ago 😞.

**Comment by ovflowd** [comment]
What does the email say? Something bad?

**Comment by richardlau** [comment]
Pretty much what the one in the description said (with updated dates):

> We were unable to process your renewal payment (invoice # CFUSA7717437). This typically happens when your bank issues a new card, your existing card has expired, or because of a billing error caused by your bank. We'll automatically try again on August 31.
> 
> **Will my service be impacted?**
> Yes, Cloudflare has resumed collecting payment on all outstanding invoices starting on Jan 18, 2023. If we do not receive payment 5 days after your invoice is issued, your paid services will be downgraded.
> 
> Continued payment failures may result in a service disruption. To avoid a service disruption, take a moment to review or update your billing information. If you have not yet set up a backup payment method, consider adding one to avoid future payment failures.

**Comment by MoLow** [comment]
I really hope this gets sorted out before we pull the plug on the r2 migration

**Comment by UlisesGascon** [comment]
The invoice appears to be unpaid in the dashboard, so probably that is the reason behind the last email that Richard has mentioned.
![Screenshot 2023-08-30 at 18 17 08](https://github.com/nodejs/build/assets/5110813/388ab9da-bd7a-4117-954f-f1c30b935ad9)
