### ISSUE TITLE
Change Cloudflare notification lang to english

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3476]
Emails are now received in Spanish.

**Comment by ovflowd** [comment]
> Emails are now received in Spanish.

It may be for you. It could probably detect locales? Or is it for everyone?

**Comment by richardlau** [comment]
The emails are going to the build email alias -- they've been in Spanish since the website moved to Vercel. Prior to that the emails were in English.

**Comment by ovflowd** [comment]
I doubt Vercel has anything to do with this 👀 but I assume maybe it was because of Ulisses logging in?

**Comment by richardlau** [comment]
> I doubt Vercel has anything to do with this 👀 but I assume maybe it was because of Ulisses logging in?

I was merely remarking on the timeframe. Most likely it was @UlisesGascon logging into Cloudflare as part of the migration (I think there were changes, e.g. around the load balancer (to update the origin names)) -- I don't think think anyone else with access would be using Spanish.

**Comment by UlisesGascon** [comment]
> I was merely remarking on the timeframe. Most likely it was @UlisesGascon logging into Cloudflare as part of the migration (I think there were changes, e.g. around the load balancer (to update the origin names)) -- I don't think think anyone else with access would be using Spanish.

Yes, that is the correct timeframe. I just changed my local OS settings to English (this will also solve my Jenkins UI issues) and I logged in with the build team account, so I assume everything is now in English. By the way, the settings in Cloudflare were set to "English", so I assume this change was triggered by a bug. I think I didn't have English as the fallback language in my browser because I manually removed it to test i18n in another project some time ago.

I will keep this issue open until we receive a new email from Cloudflare in English.

**Comment by ovflowd** [comment]
> > I doubt Vercel has anything to do with this 👀 but I assume maybe it was because of Ulisses logging in?
> 
> I was merely remarking on the timeframe. Most likely it was @UlisesGascon logging into Cloudflare as part of the migration (I think there were changes, e.g. around the load balancer (to update the origin names)) -- I don't think think anyone else with access would be using Spanish.

Ah gotcha, I misread you then.

**Comment by UlisesGascon** [comment]
Confirmed, it is in english now 🎉
