### ISSUE TITLE
Benchmarking www update clobers graph data

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#348]
We had our first updated today and I've noticed that the update clobers the graph data which will only be updated up to 6 hours later. 

We could address by removing the dummy charts in www/charts in the benchmarking repo but having them there makes it easier to validate changes off line as it allows you to clone the repo, then open the page directly and see what it look like.

Would it be possible to exclude the transfer of the www/charts part or maybe kick off a sync from the benchmark machine immediately after a www update.

@rvagg

**Comment by rvagg** [comment]
see https://github.com/nodejs/build/pull/344
