### ISSUE TITLE
Distributed benchmarking CI

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#3483]
Hey folks,

As most of you know, we don't run the benchmarking CI on every release because running all the suites takes days. That's mostly because we rely on a null-hypothesis algorithm to guarantee the confidence of our benchmark ([I briefly wrote about it](https://blog.rafaelgss.dev/preparing-and-evaluating-benchmarks)). While the optimization of this approach can be complex and not worth it, I wonder if we can distribute the benchmark in several machines (ideally each machine runs 2 namespaces), so we can start using it often on releases and measure regressions. 

I know that we have a limited number of machines and IIRC benchmark machines are provided by Nearform. I'm opening this issue to discuss what are the challenges to improve it.

**Comment by joyeecheung** [comment]
Maybe we can also identify a subset of the benchmark that can be finished in a reasonable amount of time (or with a config that make them finish in a reasonable amount of time), and then gradually growing that list...
