### ISSUE TITLE
Regular Meeting frequency/time update

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3503]
We had discussed this in several places (slack, offline...) and I think make sense to create a proper issue to find a good time slot that works for most of us (cc: @nodejs/build). 

Currently the Meetings are every few weeks (3 weeks if I remember well) in different days and timezones (Tuesdays as Wednesdays). Here are the last ones as example: #3500 and #3479. 

I think currently one of them is quite out of the Americas/Europe timezone and the other one is quite early for Americas. Do we want to change them? What works best for you?

**Comment by sxa** [comment]
Taking into account a recent post on the build mailing list it makes sense to stop using the 2200 UTC slot now since that that is usually the most difficult one. The one in that slot that you referenced had three declines in it. And while the 1200UTC one is quite early (0800) for those in Eastern time, I would likely be unable to make it in the hour after that due to another recurring meeting (Two hours later might be ok though if that was desired)

**Comment by richardlau** [comment]
+1 for dropping/moving the UTC 10pm Wednesday meeting -- those just are not happening. The last few I joined at that time were just @mhdawson and myself and the slot is inconvenient for both of us.

**Comment by mhdawson** [comment]
+1, neither time works for me right now.

**Comment by targos** [comment]
UTC 12:00 doesn't seem ideal. Close to lunch break in EU, very early in NA.

**Comment by UlisesGascon** [comment]
@nodejs/build I created a poll with the UTC times to see what time works better for the team. Please vote 🙏 

https://poll-maker.com/poll4974500x0229494a-152

**Comment by sxa** [comment]
Wednesday afternoon is quite horrible for me with calls so chances are I'd miss many of them if that's when it was held. Also if it's fixed in UTC then regardless of which option I choose I'm going to have a definite regular conflict for six months of the year due to time zone differences.

**Comment by UlisesGascon** [comment]
Seems like UTC 2 PM is the best slot based on the poll results. Should we do the change?


<img width="789" alt="Screenshot 2023-10-31 at 12 47 50" src="https://github.com/nodejs/build/assets/5110813/c95628cc-4b93-4c54-9201-d4b99c0526c0">

**Comment by MoLow** [comment]
+1

**Comment by anonrig** [comment]
+1 to UTC 2PM

**Comment by sxa** [comment]
I've just voted for 1200 and 1500UTC which evens it out at 18% for all options other than 2PM which has 25%, but that slot would completely exclude me.
What was the reason for moving it from Tuesday to Wednesday?

**Comment by sxa** [comment]
> It's not moving from Tuesday to Wednesday. IIUC the proposal is to move the time, but keep alternating between Tuesdays and Wednesdays.

Gotcha - I'd misinterpreted the [earlier comment](https://github.com/nodejs/build/issues/3503#issuecomment-1770206884).

**Comment by UlisesGascon** [comment]
@mhdawson do you know how to update the calendar and the issue generation? I am not sure where we need to do the change 🤔

**Comment by mhdawson** [comment]
To make sure I understand it should be UTC at 2PM UTC alternating between Tuesday and Wednesday every three weeks?

If so I can go ahead and update the calendar to reflect that.

**Comment by mhdawson** [comment]
@UlisesGascon calendar is updated. Let me know if it does not look updated to you, otherwise we should be good to go.

**Comment by UlisesGascon** [comment]
> @UlisesGascon calendar is updated. Let me know if it does not look updated to you, otherwise we should be good to go.

I can see the changes in the online version https://calendar.google.com/calendar/u/0/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98@group.calendar.google.com 👍.

I will close the issue then.

Thanks a lot @mhdawson!
