### ISSUE TITLE
arm CI for v0.12 was lost

### ISSUE THREAD

**Issue by shigeki** [nodejs/build#352]
node-test-commit-arm is not shown in https://ci.nodejs.org/job/node-test-commit/2543/ which is the CI for v0.12. 

Is there any troubles or the arm CI is not supported for v0.12?

**Comment by shigeki** [comment]
Ref for original PR: https://github.com/nodejs/node/pull/5712

**Comment by bnoordhuis** [comment]
I think it's not supported.  We put a lot of effort in the ARM builds but that was never back-ported to v0.10 and v0.12. That's also why there are no binaries for those release lines.

**Comment by shigeki** [comment]
I've got it. I thought I had ever seen CI for arm running on v0.12 for sometime ago. But it was wrong.
