### ISSUE TITLE
Security release planned for October 13 2023

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#3521]
Details in https://github.com/nodejs/nodejs.org/pull/5989.  As per security release creating issue to ask for support in CI lock/unlock and availability to fix CI issues

Believe @richardlau has already locked the CI.

**Comment by richardlau** [comment]
Yes, CI has already been locked down.
Refs: https://github.com/nodejs/collaborators/discussions/177

**Comment by richardlau** [comment]
CI has been unlocked.
I took the liberty of updating it to Jenkins 2.414.2 before unlocking.
