### ISSUE TITLE
ORKA maintenance 10/19/23 between 4-8AM EST

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3526]
We received a notification in the email inbox about it:

> Hello. We are reaching out to let you know that we will be performing a maintenance on your Orka environment on 10/19/23 between 4AM EST and 8AM EST that may cause the API of your Orka cluster to become unresponsive for a small time. This maintenance is required as we roll out a new monitoring solution that is integrated into our backend asset management tools as well as presenting enhanced metrics to you directly through the MacStadium portal. We apologize for the inconvenience and will notify you once the maintenance is complete. Thank you for your understanding.

- [Ticket in macstadium](https://portal.macstadium.com/support-center/tickets/SERVICE-171324)

**Implications**

Not sure if this will affect the Orka nodes as we only use the API to start/stop/redeploy... but the API is not used once the machines are deployed and operational. 

**This may impact the following machines**

- [release-orka-macos10.15-x64-1](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L93)
- [release-orka-macos11-x64-1](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L93)
- [test-orka-macos10.15-x64-1](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L279)
- [test-orka-macos10.15-x64-2](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L279)
- [test-orka-macos11-x64-1](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L279)
- [test-orka-macos11-x64-2](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L279)
- [test-orka-macos12-x64-1](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L279)

**Next actions**

Currently, we don't need to perform any preparation. Just wait until the maintenance is concluded and review that the machines are back online.

[jenkins-alerts](https://github.com/nodejs/jenkins-alerts) will check these downtimes and recovery, but only for the test machines. The release machines are not yet monitored (see: https://github.com/nodejs/jenkins-alerts/pull/262).

**Comment by mhdawson** [comment]
Thanks for the detailed heads up/explanation.

**Comment by UlisesGascon** [comment]
So, the maintenance is completed and no downtime or issues were reported/detected. 🙌

> Hello,
> The maintenance has been completed successfully and your cluster is now ready for production.
You should now be able to see metrics in the Analytics tab of your Orka cluster in the Portal.
Please let us know if everything is working as expected.
>
>Best regards,
>MacStadium Support

**Comment by UlisesGascon** [comment]
BTW.. the new UI is fantastic. We can check storage details that previously required contact support. As well we have many additional details about k8s including our pods 🙌

![Screenshot 2023-10-19 at 13 16 38](https://github.com/nodejs/build/assets/5110813/4d665e7b-9569-4d62-8532-85783cc0fb54)
