### ISSUE TITLE
Enable Travis on citgm

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/build#353]
I'd like to use travis to run CI on the unit test suite of citgm.

**Comment by rvagg** [comment]
The website WG wanted it enabled on nodejs.org and never managed to get agreement to enable third-party apps on the org. There's a bot that does it now, @phillipj could probably help getting it running here too: https://github.com/nodejs/nodejs.org/issues/355#issuecomment-189020365

**Comment by TheAlphaNerd** [comment]
awesome... that's definitely enough to run with
