### ISSUE TITLE
Windows machines in the CI are down

### ISSUE THREAD

**Issue by StefanStojanovic** [nodejs/build#3546]
Almost all of the Windows machines in the CI are down. From what I saw on a few of them, this is because of the Temurin17 update. I'll go through all of them and bring them back up. After this is done I'll close this issue and open a ticket for fixing a root cause (Temurin17 update).

**Comment by sxa** [comment]
What's doing the update? Temurin doesn't have any in-built upgrade facility.
Do you know what the error/failure was? Was it the package manager we're using that failed to update or an issue with the Temurin build itself?

**Comment by targos** [comment]
It's handled by Chocolatey. You can see an example failure here: https://ci.nodejs.org/view/All/job/windows-update-reboot/2534/label=test-azure_msft-win2022_vs2019-x64-1/console

**Comment by sxa** [comment]
Interesting ... Not clear what might have gone wrong there, but I've just tried an clean install of an earlier MSI and been able to update it with the MSI (Not using chocolatey) without issues (albeit from the UI)

**Comment by StefanStojanovic** [comment]
All of the machines are back online. Now regarding my investigation - the `windows-update-reboot` job is to be blamed (as @targos already pointed out). What I saw after logging in is `Terminate batch job (Y/N)?` in the Jenkins CMD window. Luckily, Temurin is not updated that often, but we should definitely find a way to fix this, as once it updates it breaks the entire Windows CI. I'll open another issue for that and the discussion can continue there.

**Comment by sxa** [comment]
FYI Temurin 17 will get an update once every 3 months (It's a regular cadence from the upstream openjdk project).
Every so often there will be an intermediate release for a critical bug fix or security patch in addition to that but it doesn't happen too often.
