### ISSUE TITLE
Raspberry Pi donations (1 B+, 2 B, 3 B)

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#355]
## Why?

It's true that the Node.js Foundation isn't short on finances and Raspberry Pi's aren't exactly expensive. However, Node is a community-directed project and we want to enable as many avenues as possible for community input. We know there are many people out there passionate about Node running on low-power ARM devices and want to see that support remain first-class and so far, support via donations has been fantastic and we have built a community around our hardware.

We also want to avoid the risk of _"the Foundation will do it"_ or _"the Foundation will pay for it"_ which will lead to a slow erosion of community ownership and impetus. The Foundation exists to facilitate community activity, not own it, so let's put our money where our mouths (and hearts) are and pitch in!

Lastly, there are a number of smaller companies, and companies that only have a small stake in Node that want to be able to contribute but not at the financial level of Foundation membership. Contributing hardware has proven to be a great avenue for those companies to contribute.
## What do I get out of it if I donate?

Warm fuzzies and respect from your peers!

We do our best to highlight the individuals and companies that contribute. If you look at the Build Working Group README you can see a full list of infrastructure providers and hardware donaters: https://github.com/nodejs/build#infrastructure-providers

Also have a peek at our list of computers at: http://ci.nodejs.org/computer/ and you'll see company names and GitHub usernames acknowledging folks who have contributed. These computer names show up in every test and build run through our CI infrastructure so the core team and contributors are regularly reminded of the great folk who have given resources to Node! We also have a second CI server for release builds that is not publicly available but there is a small amount of hardware in there that also has similar identifiers _(two Raspberry Pi 1 B+'s, donated by myself and @andineck, are responsible for all ARMv6 builds available at nodejs.org; that makes me pretty proud!)_.

Probably the most important benefit you get is a more solid Node.js! The more resources we can dedicate to testing and building Node, the better it's going to be.
## What does the project need?

We currently have a cluster of 8 **Raspberry Pi 1 B+** boards, two of which are dedicated to release builds, leaving 6 for general testing. We have a cluster of 11 **Raspberry Pi 2** boards that are dedicated to testing. _See the [nodejs/build README](https://github.com/nodejs/build#infrastructure-providers) for details of other hardware we use, we're open to donations of other types of hardware, just reach out and we'll let you know if we can use it._

To speed up our test runs, we parallelise them across our Raspberry Pi's, we split them into batches of 4 so the test suite finishes in approximately 1/4 of the time it takes to do it on a single machine. With the two release PI 1 B+'s out of action, we can't do two parallel test jobs simultaneously at full speed as we're only working with 6. So, ideally we'd like to get that up to at least 8 and to 12 if we can manage it. An additional Pi 2 would get us to 12, which would be nice. Additional boards above this would be nice for extra redundancy in case of total hardware failures (we haven't had a case of this yet).

We would also like to start building a Raspberry Pi 3 cluster. We already test ARMv8 / AARCH64 / ARM64 using 3 sweet [X-Gene](https://www.apm.com/products/data-center/x-gene-family/x-gene/) servers donated by ARM but the Pi 3 is a different beast (particularly given that it's still forced to run in [32-bit mode](https://www.linux.com/news/embedded-mobile/mobile-linux/890125-raspberry-pi-3-still-essentially-a-32-bit-sbc-for-now) for now) and is likely to be the most popular target for Node of available ARMv8 hardware in the near future at least.
### Raspberry Pi 3

**Target:** 8 to 12
**_Pledged so far:**_ 11 confirmed
- [Raspberry Pi 3 + 16G MicroSD](http://au.element14.com/raspberry-pi/rpi3-modb-16gb-noobs/raspberry-pi-3-model-b16gb-noobs/dp/2525228) $68 AUD
- [Enclosure](http://au.element14.com/raspberry-pi/raspberry-pi3-case/enclosure-raspberry-pi-3-white/dp/2519567) $12.64 AUD
- **Total: $88.70 AUD (inc tax) / $67.32 USD**
### Raspberry Pi 2

**Target:** 1
**_Pledged so far:**_ 0
- [Raspberry Pi 2](http://au.rs-online.com/web/p/products/8326274/) $51.45 AUD
- [8GB MicroSD w/ NOOBS](http://au.rs-online.com/web/p/secure-digital-cards/9176317/) $14.74 AUD
- [Enclosure](http://au.rs-online.com/web/p/products/8787594/) $10.11 AUD
- **Total: $83.93 AUD (inc tax) / $64.04 USD**
### Raspberry Pi 1 B+

**Target:** 6
**_Pledged so far:**_ 4 confirmed, _possibly 2 more unconfirmed_
- [Raspberry Pi 1 B+](http://au.rs-online.com/web/p/products/8111284/) $37.78 AUD
- [8GB MicroSD w/ NOOBS](http://au.rs-online.com/web/p/secure-digital-cards/9176317/) $14.74 AUD
- [Enclosure](http://au.rs-online.com/web/p/products/8787594/) $10.11 AUD
- **Total: $68.89 AUD (inc tax) / $52.58 USD**
### Other hardware

These are costs that [NodeSource](https://nodesource.com/), and I personally have covered in the past as the cluster has grown. Donations for any of these components would be greatly appreciated!

**_Pledged so far:**_ both items below have been pledged
- [USB power](http://www.scorptec.com.au/product/Power_&_Chargers/Batteries_&_Chargers/57405-MB-CHGR10U-BLK), [USB cables](http://www.scorptec.com.au/product/Cables/USB/37431-307161) and [network cables](http://www.scorptec.com.au/product/Cables/Network/39543-341509) for 10 devices including freight charges $197 AUD / $150.17 USD
- [Network switch](https://www.pccasegear.com/products/26570/d-link-dgs-1024d-24-port-gigabit-switch) to expand when we run out of ports after 8 new devices, including freight for $159 AUD / $121.23 USD
## How to donate

You can either choose one (or more) of the options above, or you can simply throw an arbitrary amount of money at the project if you like and we'll figure out how best to spend it and make sure we give you credit for the donation.

There are two ways to donate:
### Money

I prefer to receive financial donations via PayPal. Email me first @ rod@vagg.org and I'll give you further details on how to proceed.
### Hardware

If you have one of the pieces of hardware above that you would like to donate, or you have related hardware that you think may be useful, please contact us, either by responding in this issue or emailing me directly @ rod@vagg.org and we'll let you know if we can work with it and then tell you where to send it (it'll involve postage to Australia so be prepared for that).

You can also opt for buying pieces of hardware yourself instead of handing over the money to me, contact me @ rod@vagg.org and I'll give you shipping details.

**Comment by indieisaconcept** [comment]
@rvagg I have a B+ I've never really used which you can have. It's just been sitting in a draw. It doesn't have the enclosure listed though - its one of [these](http://www.modmypi.com/raspberry-pi/cases/modmypi-single-colour/modmypi-modular-rpi-b-plus-case-black).

**Comment by rvagg** [comment]
@indieisaconcept great! Enclosure doesn't matter too much, it makes them easier to stack and mount if they are consistent but it's not a big deal. We even have a Pi 2 that's running without an enclosure at the moment (I have a TODO on that). Are you going to be at Node.ninjas on the 7th? I've been thinking about heading up for that one. Either way, you're on my chase-down list now and I'll get it from you one way or another!

**Comment by indieisaconcept** [comment]
@rvagg should be there - happy to post if you need it sooner.

**Comment by mhdawson** [comment]
I'm in for providing 1 pi, whichever type is the highest priority.

**Comment by williamkapke** [comment]
I'll get these sent out as soon as I get the address:
- 3 x (Raspberry Pi 3 + memory + enclosure)
- USB power, USB cables and network cables for 10 devices
- Network switch

FYI: 
[Raspberry Pi 2 Model B](http://au.rs-online.com/web/p/products/8326274/)
> On back order for despatch 19/08/2016, delivery within 5 working days from despatch date.

[Raspberry Pi Model B+](http://au.rs-online.com/web/p/products/8111284/)
> On back order for despatch 27/05/2016, delivery within 5 working days from despatch date.

**Comment by jasnell** [comment]
@rvagg ... I have an extra Pi 2 I'm not using. I see you're going to be at collab summit in two weeks so I'll give it to you then when I see you.

**Comment by chriswiggins** [comment]
@rvagg I've sent you an email about donations :+1

**Comment by rvagg** [comment]
I've updated the OP with approximations on what have been pledged so far. I'm not willing to be firm until I actually get them but it's going well. I also have received a large open cash donation which we can use to fill in gaps or purchase some of the incidentals around the outside (like proper cable ties instead of the random items I've been using instead). And to acknowledge @williamkapke point about backordering for older Pis - yes, that's unfortunate and I was aware of this but it's because none of the downstream suppliers are stocking them in any meaningful quantity, my normal supplier (element14) even requires orders of >150 to get them in at all. It seems that RS are batching up orders to the Raspberry Pi Foundation so they can get them in the bulk lots that they are available in and not have to sit on unused stock. That's OK because we have a _working_ cluster atm but we need additional hardware in the pipeline at least.

Still keen to hear from new folks who would like to join the donors list!

**Comment by rvagg** [comment]
fwiw I've started tracking all donations, including funds and in-kind donations of hardware, in a double-entry spreadsheet along with an inventory of what we've been given. I've shared with core members of the build team. I'm not sure yet if it's appropriate to make it public but I did want to let everyone know that there is _some_ level of accountability here and that it's not pouring into a black hole.

**Comment by jbergstroem** [comment]
@rvagg suggesting you add a UPS to above list. If there are monetary donations I'd see that as a pretty good investment.

**Comment by rvagg** [comment]
@jbergstroem did that yesterday! Got a sizable cash donation from @davglass and have so far used it to buy a UPS, some power and cable management equipment and another Pi 3. Got a couple more Pi 3's donated this morning so we're starting to have a nice cluster on the way in. @williamkapke is donating extra networking and USB power equipment too. Backlogs on all Pi hardware though so we'll have to be patient.

One thing that I'm looking forward to is Raspbian Jessie testing with the Pi 3's. So far we only have Raspbian Wheezy coverage on Pi.

**Comment by notthetup** [comment]
@rvagg Would love to donate a RPi3. Emailing you.

**Comment by piccoloaiutante** [comment]
@rvagg i'm happy to provide money for Raspberry Pi 3. I've just emailed to you :-).

**Comment by andineck** [comment]
I think this is a great thing. That you open it up to the community, so that everyone can be involved (even though it might be less work to just buy it with the foundation money).

I would love to donate 1 PI (what ever is still needed).

**Comment by rvagg** [comment]
@andineck if you want to go again then I'd recommend either a Pi 1 (2 or 3 more would be nice) or Pi 2 (1 more to round out to 12), we're getting close to having the upper target for Pi 3's already. Email me if you want to do it via $$, or you can just use the same info you used previously to order and have the delivery go to me, I'm still at the same address, follow the links above to RS for the older Pi's.

**Comment by andineck** [comment]
@rvagg sorry for my very late reply. If the Pi 1 is still required, I would cover the costs via $$ (otherwise I would go for a Pi 2).
If you can send me the Amount, and paypal Account, that would be great.


intesso engineering gmbh
Bahnhofstrasse 5
8447 Dachsen

Tel. 		+41 52 654 32 33
Fax 		+41 52 654 32 34
Mobile 	+41 79 742 92 10
Email 	andi.neck@intesso.com <mailto:andi.neck@intesso.com>
Skype 	andineck

**Comment by rvagg** [comment]
Hey folks, quick update, there's still back-order in place for older pi's and some of the newer ones but so far we have:

* Networking, power and cable management miscellaneous components c/o @davglass financial contribution
* Pi 1 B+ c/o @indieisaconcept in place and _nearly_ in CI but there's a hiccup with NFS that I haven't resolved yet
* Pi 2 c/o @jasnell in place and in CI
* 6 Pi 3's c/o @davglass, 2 from Pivotal Agency (https://www.pivotalagency.com.au/), 3 from @williamkapke, in place and hooked up to CI but not doing anything yet, we need to figure out how to construct the Pi 3 build job yet (/cc @joaocgreis who will probably need to assist in figuring out cross-compile).

Will keep you informed as we progress. @andineck I'll ping you when I have a better handle on the Pi 1 situation, we have Pi 2's up to 12 now so it's just the 1 B+'s that I'm concerned about but we may be close to 12 already with incomings.

**Comment by rvagg** [comment]
oh, and also to that, we got:

* UPS (!) c/o @davglass
* USB power and networking components c/o @williamkapke

**Comment by joaocgreis** [comment]
@nodejs/build @nodejs/jenkins-admins 

I added the Pi 3 to https://ci.nodejs.org/job/node-test-binary-arm/ . It tests the same armv6 binary that is tested on Pi 1 and 2. The cross compiling server is relatively prepared to compile different binaries for each, if we want to do that.

**Comment by rvagg** [comment]
@joaocgreis can we do armv7 on the Pi2 and Pi3's? Hopefully we'll be able to switch to arm64 on the Pi3's when that whole drama gets sorted out.

**Comment by joaocgreis** [comment]
Done. Compiling with `-march=armv6zk` to run on the Pi1 and `-march=armv7-a` to run on the Pi2 and 3.

**Comment by rvagg** [comment]
Received the outstanding 5 Raspberry Pi 3's today, bringing the total up to 11. I'll be setting them up this week. They are care of securogroup.com, @notthetup + @sayanee, @piccoloaiutante and @kahwee. We still have 4 outstanding Pi 1's on backorder and a network switch still to be received.

**Comment by piccoloaiutante** [comment]
excellent @rvagg

**Comment by rvagg** [comment]
Outstanding Pi3's are all set up now, we have a cluster of 11 so far:

* https://ci.nodejs.org/computer/test-nodesource_davglass-debian8-arm_pi3-1/ - @davglass
* https://ci.nodejs.org/computer/test-nodesource_kahwee-debian8-arm_pi3-1/ - @kahwee
* https://ci.nodejs.org/computer/test-nodesource_notthetup_sayanee-debian8-arm_pi3-1/ @notthetup & @sayanee 
* https://ci.nodejs.org/computer/test-nodesource_piccoloaiutante-debian8-arm_pi3-1/ - @piccoloaiutante 
* https://ci.nodejs.org/computer/test-nodesource_pivotalagency-debian8-arm_pi3-1/ - @ksflyinghigh / @wearepvtl
* https://ci.nodejs.org/computer/test-nodesource_pivotalagency-debian8-arm_pi3-2/ - @ksflyinghigh / @wearepvtl
* https://ci.nodejs.org/computer/test-nodesource_securogroup-debian8-arm_pi3-1/ - @chriswiggins / @securogroup 
* https://ci.nodejs.org/computer/test-nodesource_securogroup-debian8-arm_pi3-2/ - @chriswiggins / @securogroup 
* https://ci.nodejs.org/computer/test-nodesource_williamkapke-debian8-arm_pi3-1/ - @williamkapke 
* https://ci.nodejs.org/computer/test-nodesource_williamkapke-debian8-arm_pi3-2/ - @williamkapke 
* https://ci.nodejs.org/computer/test-nodesource_williamkapke-debian8-arm_pi3-3/ - @williamkapke 

An additional Pi 1 B+:
* https://ci.nodejs.org/computer/test-nodesource_indieisaconcept-debian7-arm_pi1p-1/ - @indieisaconcept 

An additional Pi 2:
* https://ci.nodejs.org/computer/test-nodesource_jasnell-debian7-arm_pi2-1/ - @jasnell

With additional resources (networking, power, cables, UPS, cable ties, replacement & spare MicroSD cards) provided by @davglass and @williamkapke.

Still pending 4 Pi 1 B+'s on backorder, c/o @mhdawson, @chriswiggins / @securogroup and @chrislea. While RS Components still has these listed as on backorder with a deliver date mid-June, they have pushed that date back twice now and I tried to order another and they rejected that immediately. I assumed they were waiting for enough orders to warrant a batch of 1000 from the Pi Foundation but perhaps that's wrong and we're going to have trouble getting them. What sucks about this is that the Pi 1 B+'s are the ones we have the fewest of so are the biggest bottleneck and we have the least redundancy, they are also the ones we build ARMv6 binaries off for nodejs.org (we don't even build binaries on the 2's or 3's). I've found a small supplier in AU that say they have a few in stock still but they are selling them at a slight premium. I've contacted the Raspberry Pi Foundation directly to see if they might be kind enough to just donate a bunch to us. Will wait for a response from them before I act. I'll also need to contact RS to get an answer about the backordered ones.

Take-away for everyone in this thread - put the word out that if folks have Pi 1 B+'s laying around then we'd love for them to be donated to the project! We don't need original Pi 1's, they are too slow, these are the second generation B+'s that we need. This is what they look like: https://www.element14.com/community/servlet/JiveServlet/downloadImage/102-78141-4-227912/1362-900/b%2Bmarking.jpg

**Comment by rvagg** [comment]
Woohoo! RS just got the B+'s back in stock and they are apparently now shipping the ones I'm without. I'm also thinking about using some of the additional funds we have to get a few more since these are a bottleneck for us and we have 2 out of action for the release cluster.

**Comment by notthetup** [comment]
Hey @rvagg,

I have a couple of RPi B and one RPi B+ that I have no use for. They belong to @coffeesam and he's willing to donate it to the build cluster. Do you think it will work if I ship them to you? I have shipped stuff from SG to AU before. It's not that expensive.

**Comment by rvagg** [comment]
That'd be great @notthetup, we can't use the B's, we had two in the beginning but had to retire them because they are too slow to be useful.
I'll send you the address.

**Comment by rvagg** [comment]
OK, it's been a while but I've got 3 new Pi B+'s set up and running in the cluster:

* https://ci.nodejs.org/computer/test-nodesource_mhdawson-debian7-arm_pi1p-1/ thanks to @mhdawson!
* https://ci.nodejs.org/computer/test-nodesource_securogroup-debian7-arm_pi1p-1/ thanks to @chriswiggins / @securogroup
* https://ci.nodejs.org/computer/test-nodesource_securogroup-debian7-arm_pi1p-2/ thanks to @chriswiggins / @securogroup

Bringing our total to 12 B+'s, which is great. _But_, since we have two of those out of general use thanks to being partitioned off for making release builds, we're effectively at 10. I'm supposed to have a 4th donation thanks to @chrislea but for some reason RS hasn't got a record of that order so I'm going to have to dig up the transaction to see if they took my money for it! I think I'll use some additional @davglass money to purchase another which will bring our total to 14!

We've also had an SD card failure from one of the existing B+'s and I'm all out of spares so I'll have to go and order a bunch more of those (I'm sure there will be plenty more failures in our future!).

**Comment by rvagg** [comment]
Phew, got @chrislea's B+ today along with another one I ordered on behalf of @davglass. https://ci.nodejs.org/computer/test-nodesource_chrislea-debian7-arm_pi1p-1/ & https://ci.nodejs.org/computer/test-nodesource_davglass-debian7-arm_pi1p-1/, bringing the total of B+s to 14! 2 of those are isolated from the rest for doing release builds (the armv6l binaries on nodejs.org) leaving 12 in the test cluster for running tests in groups of 4 at a time so we can do 3 separate test jobs simultaneously. So we now have 14 B+'s, 12 2's and 11 3's. It'd be nice to add the extra 3 but mainly for symmetry, since they run so much faster than the rest they are not the bottleneck by any means.

Below are some photos that I took recently (without the additional 2 B+'s), for your viewing pleasure! Most of them have the names of the donor on them to help with identification, fwiw. From left to right we have the B+'s, 2's, 3's, 3 x Odroid XU's and 3 x AppliedMicro X-Gene's (armv8) with a UPS on top of them.

I'll get updated details and perhaps photos onto the [README](https://github.com/nodejs/build) soon to reflect all our new donors and the state of things. I also think a page on nodejs.org with similar information about our cluster and all our wonderful donors, individual and corporate, would be good too. I'll leave this issue open until the documentation is all done, but that's the last thing left to do!

![node_arm_cluster_201609-6](https://cloud.githubusercontent.com/assets/495647/18666345/b882a3dc-7f6e-11e6-863b-a437fc86c104.jpg)
![node_arm_cluster_201609-4](https://cloud.githubusercontent.com/assets/495647/18666347/b88919b0-7f6e-11e6-86dd-c53705a33573.jpg)
![node_arm_cluster_201609-5](https://cloud.githubusercontent.com/assets/495647/18666346/b886a7f2-7f6e-11e6-9cf7-4d0723f0f3cc.jpg)

**Comment by phillipj** [comment]
Very cool to see these how these boxes are organized, thanks for sharing!

**Comment by Trott** [comment]
Should this remain open?

**Comment by rvagg** [comment]
No, but we may need a new drive soon to get some more Pi3's if we're going to start using them for release builds. Can do that as a separate thing though.
