### ISSUE TITLE
`release-orka-macos11-x64-1` is missconfigured

### ISSUE THREAD

**Issue by targos** [nodejs/build#3550]
https://ci-release.nodejs.org/computer/release%2Dorka%2Dmacos11%2Dx64%2D1/

This is blocking release jobs.

**Comment by richardlau** [comment]
I think the machine has been reset and will need to be rebuilt (unless there's a backup we can restore from @UlisesGascon), or the IP addresses have somehow been swapped around:
```console
$ ssh release-orka-macos11-x64-1
Password:

$ ssh -i ~/.ssh/nodejs_build_test release-orka-macos11-x64-1
Last login: Wed Nov  1 05:29:39 2023 from 10.221.188.14
administrator@test-orka-macos11-x64-1 ~ %
```
Note that the machine thinks it is a test machine.

**Comment by richardlau** [comment]
Tried to reansible machine. Failed:
```

TASK [baselayout : install packages (macos)] ********************************************************************************************************************************************************************
failed: [release-orka-macos11-x64-1] (item=cmake,python,ccache) => {"ansible_loop_var": "package", "changed": false, "msg": "Warning: python@3.10 3.10.9 already installed.", "package": "cmake,python,ccache"}
ok: [release-orka-macos11-x64-1] => (item=automake,bash,libtool) => {"ansible_loop_var": "package", "changed": false, "changed_pkgs": [], "msg": "Changed: 0, Unchanged: 3", "package": "automake,bash,libtool", "unchanged_pkgs": ["automake", "bash", "libtool"]}

PLAY RECAP ******************************************************************************************************************************************************************************************************
release-orka-macos11-x64-1 : ok=18   changed=6    unreachable=0    failed=1    skipped=12   rescued=0    ignored=0
```

**Comment by richardlau** [comment]
I've stopped the Jenkins agent for now on release-orka-macos11-x64-1 -- I've edited `/Users/iojs/start.sh` so that it no longer has the secret for test-orka-macos11-x64-1 so won't pretend to be it if the agent attempts to restart. The machine needs to be reansibled+manual steps (for signing etc). @UlisesGascon is this something you can look at?

**Comment by UlisesGascon** [comment]
I am checking the machine in Orka, some notes:


1. The machine seems to be properly located (in the first node), so the internal IP and the external IP from [the inventory](https://github.com/nodejs/build/blob/main/ansible/inventory.yml#L93) are matching `10.221.188.14:8822 -> 199.7.167.100:8822`


![Screenshot 2023-11-06 at 10 32 07](https://github.com/nodejs/build/assets/5110813/24962f71-d0bc-46cd-8a97-dcffd40eb979)

2. We have a base image (`macos11-x64-1_11012023`) that can be used to generate a new machine but is quiet outdated (`11/01/2023`), so we will need to fully re-ansible the image and upgrade Java version and so on.
![Screenshot 2023-11-06 at 10 32 36](https://github.com/nodejs/build/assets/5110813/b46740c8-a3d3-4416-8f30-7c0ff7d1026e)

> I've stopped the Jenkins agent for now on release-orka-macos11-x64-1 -- I've edited /Users/iojs/start.sh so that it no longer has the secret for test-orka-macos11-x64-1 so won't pretend to be it if the agent attempts to restart. The machine needs to be reansibled+manual steps (for signing etc). @UlisesGascon is this something you can look at?

I see the Jenkins agent working in https://ci-release.nodejs.org/computer/release-orka-macos11-x64-1/. I was trying to see if the jenkins node and the machine are the same by comparing the `ifconfig` output:

<img width="1223" alt="Screenshot 2023-11-06 at 10 35 28" src="https://github.com/nodejs/build/assets/5110813/6e90ee11-5170-46e6-9626-9d439c1f5d7f">

![Screenshot 2023-11-06 at 10 49 30](https://github.com/nodejs/build/assets/5110813/71d224be-e77e-4458-be21-799e58aa0188)

So, I think is the same machine (`192.168.122.2`). Maybe the agent is back and running properly? 🤔

**Comment by richardlau** [comment]
> So, I think is the same machine (`192.168.122.2`). Maybe the agent is back and running properly? 🤔

It's failing builds https://ci-release.nodejs.org/computer/release%2Dorka%2Dmacos11%2Dx64%2D1/builds.

**Comment by UlisesGascon** [comment]
I will try to re-configure the machine and check if the builds are passing properly. I was thinking that maybe we can consider to add an additional machine in orka for releases, like `release-orka-macos11-x64-2` so at least we have some redundancy because currently this is the only machine for macos Intel combination 🤔

**Comment by UlisesGascon** [comment]
Seems like I was able to re-ansible the machine:

```
TASK [fail if node is in the path - please uninstall it] *********************************************************************
skipping: [release-orka-macos11-x64-1] => {"changed": false, "false_condition": "os|startswith(\"win\")", "skip_reason": "Conditional result was False"}

PLAY RECAP *******************************************************************************************************************
release-orka-macos11-x64-1 : ok=46   changed=8    unreachable=0    failed=0    skipped=112  rescued=0    ignored=0   
```

I will monitor the pipeline to see if now is passing 🤞

**Comment by UlisesGascon** [comment]
The issue persist, I will try to patch the machine manually.

**Comment by UlisesGascon** [comment]
I managed to solve the sign issues by following the manual steps in the doc. Currently there is an error in the last job regarding `direct.nodejs.org:22` availability that is not related to this issue and is affecting the other machines.

```
20:03:41 ssh: connect to host direct.nodejs.org port 22: Connection timed out
20:03:41 make: *** [Makefile:1279: binary-upload] Error 255
20:03:41 Build step 'Conditional steps (multiple)' marked build as failure
```

I will close the issue as the machine is back and capable of signing the binaries 👍
