### ISSUE TITLE
`Cannot open include file: 'stddef.h': No such file or directory` on `win2016-vs2015-COMPILED_BY-vs2019-x86` for Node.js 18 builds

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3554]
Node.js 18 builds are consistently failing on Windows in [node-test-binary-windows-native-suites](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/) for `win2016-vs2015-COMPILED_BY-vs2019-x86`
e.g. https://ci.nodejs.org/job/node-test-binary-windows-native-suites/20206/nodes=win2016-vs2015-COMPILED_BY-vs2019-x86/console (from https://ci.nodejs.org/job/node-test-commit-windows-fanned/58999/):
```console
04:21:39     "C:\\workspace\\node-test-binary-windows-native-suites\\node\\deps\\v8\\include\\v8.h(18): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory [C:\\workspace\\node-test-binary-windows-native-suites\\node\\test\\addons\\04_object_factory\\build\\addon.vcxproj]\r\n",
04:21:39   stderr: 'gyp info it worked if it ends with ok\n' +
```

@StefanStojanovic

**Comment by targos** [comment]
This is relatively new. Here is a successful run I had two days ago on the staging branch: https://ci.nodejs.org/view/All/job/node-test-commit/66202/

**Comment by richardlau** [comment]
> This is relatively new. Here is a successful run I had two days ago on the staging branch: https://ci.nodejs.org/view/All/job/node-test-commit/66202/

`win2016-vs2015-COMPILED_BY-vs2019-x86` looks to be recently added. From the successful https://ci.nodejs.org/job/node-test-binary-windows-native-suites/20177/console we can see that it ran on win2012r2 labels rather than the newer win2016 ones for the x86 builds.
```
09:51:26 Skipping win11-vs2022-arm64-COMPILED_BY-vs2019-arm64 for Node.js 18
09:51:26 Skipping win2022-vs2019-COMPILED_BY-vs2022 for Node.js 18
09:51:26 Skipping win11-vs2022-arm64-COMPILED_BY-vs2022-arm64 for Node.js 18
09:51:26 Skipping win2016-vs2017-COMPILED_BY-vs2022-x86 for Node.js 18
09:51:26 Skipping win2019-vs2019-COMPILED_BY-vs2022 for Node.js 18
09:51:26 Running nodes
09:51:26 Triggering [node-test-binary-windows-native-suites » win2012r2-vs2015-COMPILED_BY-vs2019-x86](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2012r2-vs2015-COMPILED_BY-vs2019-x86/)
09:51:26 Triggering [node-test-binary-windows-native-suites » win2012r2-vs2019-COMPILED_BY-vs2019-x86](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2012r2-vs2019-COMPILED_BY-vs2019-x86/)
09:51:26 Triggering [node-test-binary-windows-native-suites » win2022-vs2019-COMPILED_BY-vs2019](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2022-vs2019-COMPILED_BY-vs2019/)
09:56:20 Completed [node-test-binary-windows-native-suites » win2012r2-vs2015-COMPILED_BY-vs2019-x86](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2012r2-vs2015-COMPILED_BY-vs2019-x86/) SUCCESS
09:56:44 Completed [node-test-binary-windows-native-suites » win2012r2-vs2019-COMPILED_BY-vs2019-x86](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2012r2-vs2019-COMPILED_BY-vs2019-x86/) SUCCESS
09:56:52 Completed [node-test-binary-windows-native-suites » win2022-vs2019-COMPILED_BY-vs2019](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2022-vs2019-COMPILED_BY-vs2019/) SUCCESS
```

**Comment by StefanStojanovic** [comment]
Thanks for bringing this to my attention @richardlau, yes Win2016_VS2015 machines are new and I had some difficulties setting them up, mostly related to installing VS2015. For now, I've reverted back to using Win2012r2 machines until I fix this. I assume it is missing something from the VS although I'll have to investigate it further.

**Comment by StefanStojanovic** [comment]
I made changes and tried running `vcbuild.bat release noprojgen nobuild ignore-flaky test-ci-native`. Since it passed I reenabled those machines for [node-test-binary-windows-native-suites](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/) but also left Win2012r2 machines active just in case. After I see it passing in the CI as well, I'll exclude the old machines and close this issue

**Comment by StefanStojanovic** [comment]
Closing this, since [the job](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2015-COMPILED_BY-vs2019-x86/) has been passing for the last few days.
