### ISSUE TITLE
Odd build failures on rhel8-ppc64le

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3556]
Yesterday (1 Nov 2023) several builds on rhel8-ppc64le failed in odd ways across several of the machines. Today's builds (2 Nov 2023 from ~2:30am GMT) look okay but I'm raising this issue to track in case the problems reoccur.

![image](https://github.com/nodejs/build/assets/5445507/8d5ebfef-cdd7-4833-a2a9-cf29e108e096)

e.g.
- https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/50643/console [test-osuosl-rhel8-ppc64_le-1](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-1)
  - Also similar https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/50651/console [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-4)
  - https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/50652/console [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-2)
```console
15:24:28 In file included from ../deps/v8/src/objects/name-inl.h:13,
15:24:28                  from ../deps/v8/src/objects/lookup-cache-inl.h:10,
15:24:28                  from ../deps/v8/src/objects/descriptor-array-inl.h:15,
15:24:28                  from ../deps/v8/src/objects/field-index-inl.h:8,
15:24:28                  from ../deps/v8/src/objects/js-objects-inl.h:13,
15:24:28                  from ../deps/v8/src/objects/api-callbacks-inl.h:13,
15:24:28                  from ../deps/v8/src/objects/map-inl.h:9,
15:24:28                  from ../deps/v8/src/objects/instance-type-inl.h:11,
15:24:28                  from ../deps/v8/src/objects/js-proxy-inl.h:8,
15:24:28                  from ../deps/v8/src/objects/objects-inl.h:29,
15:24:28                  from ../deps/v8/src/heap/new-spaces-inl.h:13,
15:24:28                  from ../deps/v8/src/heap/heap-inl.h:31,
15:24:28                  from ../deps/v8/src/init/setup-isolate-full.cc:10:
15:24:28 ../deps/v8/src/objects/string-inl.h:1091:1: internal compiler error: Segmentation fault
15:24:28  }
15:24:28  ^
15:24:28 Please submit a full bug report,
15:24:28 with preprocessed source if appropriate.
15:24:28 See <http://bugzilla.redhat.com/bugzilla> for instructions.
15:24:28 The bug is not reproducible, so it is likely a hardware or OS problem.
```

- https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/50644/console [test-osuosl-rhel8-ppc64_le-1](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-1)
- Also https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/50654/console [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-2)
```console
15:13:11 Inconsistency detected by ld.so: dl-fini.c: 91: _dl_fini: Assertion `ns != LM_ID_BASE || i == nloaded' failed!
15:13:11 make[2]: *** [tools/icu/icui18n.target.mk:356: /home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/out/Release/obj.target/icui18n/deps/icu-small/source/i18n/dcfmtsym.o] Error 127
15:13:11 make[2]: *** Waiting for unfinished jobs....
```

- https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/50645/console [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-4)
- Also https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/50650/console [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-4)
```console
15:36:11 collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
15:36:11 compilation terminated.
15:36:11 make[2]: *** [node_mksnapshot.target.mk:278: /home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/out/Release/node_mksnapshot] Error 1
15:36:11 make[2]: *** Waiting for unfinished jobs....
```

**Comment by richardlau** [comment]
No reoccurrences since. Closing for now.

**Comment by aduh95** [comment]
I see it again on https://ci.nodejs.org/job/node-test-commit-arm-debug/20093/nodes=ubuntu2204_debug-arm64/console, looks like it's not specific to rhel

**Comment by joyeecheung** [comment]
According to @ryanaslett on slack this is triggered by ccache warmup on the new azure machines, so they are running out of memory, which is different from the issue. 

https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1756262736382399

> I went ahead and removed the debug labels from all the existing azure nodes, so those should stop OOMing and disrupting builds. I'll build a couple new machines with more cpu/memory and start getting those into the rotation. we will probably not have them fully running builds when we lose our equinix machines, so there may be a window of time where the debug builds on arm are either incredibly slow or worse, still failing (Im boosting the hosts from 16GB to 64GB of host memory)
