### ISSUE TITLE
Ensure a minimum of 4GB of RAM on CI hosts?

### ISSUE THREAD

**Issue by targos** [nodejs/build#3558]
2GB is usually not enough to compile V8 and we have to restart CI jobs until they pass (thanks to ccache)

![CleanShot 2023-11-04 at 17 18 55@2x](https://github.com/nodejs/build/assets/2352663/31ca1473-7200-4dc1-9ce1-2ec8b424a2c5)

I'd like to upgrade the recent DO hosts that I created to 4GB instead of 2GB.

Another option could be to enable swap, but I suppose we prefer to avoid that if we can to avoid slowing down jobs?

Refs: https://github.com/nodejs/build/pull/3557

**Comment by richardlau** [comment]
> 2GB is usually not enough to compile V8 and we have to restart CI jobs until they pass (thanks to ccache)

👍 See also https://github.com/nodejs/build/issues/3520.

> Another option could be to enable swap, but I suppose we prefer to avoid that if we can to avoid slowing down jobs?

Avoiding swap would be preferable. I think the only thing to be watchful for would be increased costs (for the providers where we're using up credits). If we do add swap, I added a task to the bootstrap role to do so in https://github.com/nodejs/build/pull/3522.

**Comment by targos** [comment]
>  I think the only thing to be watchful for would be increased costs (for the providers where we're using up credits). 

For DO, I'm going to open an issue soon. We have several machines that cost a lot and are underused or even unused

**Comment by richardlau** [comment]
With the most recent V8 updates for Node.js 22 we've found that even 4GB is borderline and for many of the 4GB machines we've had to also add 2GB swap.
IIRC most of the providers scale memory with CPUs. We need to be careful if we also increase the number of CPUs as that may require even more memory if the build is compiling more things in parallel.

**Comment by mhdawson** [comment]
I think moving up to 4G makes sense, agreed with @richardlau that we don't want to accidentally increase the parallelism which would defeat the goal of increasing the available memory.

**Comment by richardlau** [comment]
I've just added 2GB of swap to the two DigitalOcean-hosted Ubuntu 22.04 x64 machines (https://github.com/nodejs/build/pull/3877). They already had 4 GB of RAM and were failing due to the OOM killer. Builds on the IBM hosted machines were not failing -- those also have 4 GB of RAM but unlike DO, IBM provisioned them with 2 GB of swap on creation.

**Comment by targos** [comment]
I'll close this. It seems that the right thing to do is add swap, not memory (because memory usually scales with CPUs)
