### ISSUE TITLE
Update `www` server to Ubuntu >=18.04

### ISSUE THREAD

**Issue by targos** [nodejs/build#3564]
I'm sitting with @ovflowd and @flakey5 and we started a journey to upgrade the `www` server.
One of the reasons is to maybe fix the SSL issues that we have with Cloudflare R2 (https://github.com/nodejs/build/issues/3559)

To do:
- [x] Check that the latest releases are available on `unencrypted.nodejs.org`
- [x] Force the trafic on `unencrypted.nodejs.org`
  - Disabled DO in https://dash.cloudflare.com/07be8d2fbc940503ca1be344714cb0d1/nodejs.org/traffic/load-balancing
- [x] Shutdown the DO server
- [x] Make a snapshot in DO (https://cloud.digitalocean.com/droplets/128526115/snapshots?i=9e6877)
- [x] Do the Ubuntu upgrade(s)
  - [x] 18.04
  - [x] 20.04
  - [x] 22.04
- [x] Verify the web server
- [x] Enable trafic again on DO

**Comment by targos** [comment]
To generate the snapshot faster, I moved the nginx logs: `mv /var/log/nginx /home/logs/nginx`

**Comment by ovflowd** [comment]
*nightmare

**Comment by targos** [comment]
It's done 🎉
