### ISSUE TITLE
ssh: connect to host direct.nodejs.org port 22: Operation timed out

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3566]
Seems like there are some connectivity issues in this job: https://ci-release.nodejs.org/job/iojs+release/9759/

Same error in multiple machines: [osx11-release-pkg](https://ci-release.nodejs.org/job/iojs+release/9759/nodes=osx11-release-pkg/console), [rhel8-ppc64le-release](https://ci-release.nodejs.org/job/iojs+release/9759/nodes=rhel8-ppc64le-release/console)

```
20:01:29 ssh node-www "mkdir -p nodejs/custom/v22.0.0-v8-canary20231107b2b007f9ac"
20:03:41 ssh: connect to host direct.nodejs.org port 22: Connection timed out
20:03:41 make: *** [Makefile:1279: binary-upload] Error 255
20:03:41 Build step 'Conditional steps (multiple)' marked build as failure
20:03:42 Archiving artifacts
```

**Comment by richardlau** [comment]
The server is being upgraded and is currently shutdown. See https://github.com/nodejs/build/issues/3564 for progress.

**Comment by targos** [comment]
Upgrade work will continue today.

**Comment by targos** [comment]
This is fixed. Today's canary and nightly releases are uploaded correctly.
