### ISSUE TITLE
test-orka-macos11-x64-1 out of disk?

### ISSUE THREAD

**Issue by kvakil** [nodejs/build#3568]
Tests on test-orka-macos11-x64-1 have been failing recently:

* https://ci.nodejs.org/job/node-test-commit-osx/55572/nodes=osx11-x64/
* https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/55584/
* https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/55583/
* https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/55577/

The failures all look like this:

```
05:56:23     Wrote single executable preparation blob to sea-prep.blob
05:56:23     [process 16718]: --- stderr ---
05:56:23     error: /Library/Developer/CommandLineTools/usr/bin/codesign_allocate: can't write output file: /Users/iojs/node-tmp/.tmp.4020/sea.cstemp (No space left on device)
05:56:23     /Users/iojs/node-tmp/.tmp.4020/sea: the codesign_allocate helper tool cannot be found or used
05:56:23     
05:56:23     [process 16718]: --- stdout ---
```

or this:

```
03:11:38 mkdir: Release/obj.target/test_typedarray/: No space left on device
```

**Comment by UlisesGascon** [comment]
I will check the machine

**Comment by targos** [comment]
The other orka machine is also offline for the same reason (I reopened the related issue today)

**Comment by UlisesGascon** [comment]
This machine should be fine by now ;)
