### ISSUE TITLE
Make signature of SHA256SUMs with a known trusted key

### ISSUE THREAD

**Issue by ghostbar** [nodejs/build#357]
The `SHASUMS256.txt` uses to be signed by people who have done releases before, I got them in my keyring and now someone else's does it, signs it with their signature which I don't know, nor has the signature of the other people I have trusted from before on their releases.

Basically, that signature is meaningless.

So there should be an established trusted signature for stuff like this, and maybe give subkeys of it to people that can do releases.

**Comment by TheAlphaNerd** [comment]
@ghostbar there have been new individuals (such as myself) added to the release team and all their public key's are available in the README. Have you updated your keys?

**Comment by ghostbar** [comment]
@TheAlphaNerd I can see that, I did indeed update it, but then again: who signs those changes?

That's why I said the signature is becoming meaningless, basically the chain of trust is being broken and that's the basis of gpg signatures.

Therefore, my proposal, of a known signature, and only somebody already trusted can make changes on that key when giving subkeys. Turns out, there have been attacks before on GitHub, so I can't blindly trust on a change in a github repo README.

**Comment by TheAlphaNerd** [comment]
@ghostbar I have mixed feelings regarding that statement. There is ample documentation as to how individuals are on boarded to the release group. Perhaps we should be signing any commit that modifies that list though.

If I am following you correctly, you would prefer to see a single master key, and that all signatories are signing the releases using a subkey of that?

/cc @nodejs/ctc @mikeal

**Comment by ghostbar** [comment]
I see that as a good idea, specially for letting CI tools do their job with less intervention from individuals.

And solves the issue of trust, I can see your key and Evan's got created at this year and at the end of 2015 respectively and have no signatures on it. I don't know you, how can I be sure it's your key if someone else from the release team haven't signed yours?

This would be solved as well by using a master key for the release team and giving subkeys of it to the people that can do releases. Not only I don't need to check on each release if a new key got added but I know the individual signing the release can be trusted.

I know it may seem paranoid, but that's how gpg keys should be used (creating a network of trust), so I see a win on using it right.

**Comment by bnoordhuis** [comment]
I forgot the issue number but master keys have been discussed before.  IIRC, the reason we didn't go with that is because no one was sure who should manage the master key.

(Saying "The Node.js Foundation" is mu; at the end of the day, it's still one or more individuals that hold the master key.)

**Comment by ChALkeR** [comment]
Why would we want master keys? The chain could be fixed just by signing the list of new keys with keys from the old list each time a new key is added to the list.

More specifically, can we host the list of trusted keys somewhere, signed by each key from that list?

@ghostbar would that fix your concerns?

**Comment by ghostbar** [comment]
Yes, indeed that would solve the trust issue @ChALkeR, as I said in my first message the first alert I got was: this release is signed with a key I do not know and is not signed by the other keys I have trusted in the past (and in fact, isn't signed by anyone, at all). And as the title says, I would like to have signatures from a trusted key, which means someone else that's already trusted signed it. (The more, the better)

The master key would be an ideal solution for less human interaction when new members get added to the release team.

**Comment by rvagg** [comment]
fwiw I've signed the keys of the other members of the release team and uploaded them to the main keyserver pool, they should be propagated already if you want to `gpg --refresh-keys --keyserver pool.sks-keyservers.net`.

> can we host the list of trusted keys somewhere

We host a list of fingerprints on the README, this should be considered a trusted source, changing the README requires jumping through the various hoops we have.

```
curl -sL https://raw.githubusercontent.com/nodejs/node/master/README.md | grep ^gpg
```

will get you all of the keys you need to trust at the moment in order to be able to verify the signed SHASUMS files. These even get hardwired into the Dockerfiles maintained by the default `node` images: https://github.com/nodejs/docker-node/blob/master/4.4/Dockerfile

The release team shouldn't change very often but when it does, a sig will be added to the README, that's the authoritative location to get them.

**Comment by jbergstroem** [comment]
We could alternatively create a new file in the repo that contains the keys and always commit to it signed (`git commit -S`). That would avoid the 'github hacked' or 'who just force pushed' scenario.

**Comment by ghostbar** [comment]
Thank you @rvagg; having the keys signed already, the releases are definitely signed by a trusted key, so I'm gonna close this issue.
