### ISSUE TITLE
Your DigiCert Code Signing certificate expires at 12/18/2023

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3573]
Email received in `accounts@iojs.org` from `admin@digicert.com` with subject `Your DigiCert Code Signing certificate expires in 30 days (Order # 58846884)`. 

**Expiration date on 12/18/2023**

Are we aware of it? Do we need to manage the renew manually?

**Comment by richardlau** [comment]
Yes, see https://github.com/nodejs/build/issues/3491.
