### ISSUE TITLE
Problem with `ubuntu2004-armv7l` fanned tests

### ISSUE THREAD

**Issue by targos** [nodejs/build#3583]
It's very red today:

![CleanShot 2023-12-07 at 18 04 59@2x](https://github.com/nodejs/build/assets/2352663/2b3ceae9-ec78-4e07-a244-aa8bc61a428b)

https://ci.nodejs.org/job/node-test-binary-armv7l/9128/RUN_SUBSET=js,nodes=ubuntu2004-armv7l/console

```
16:34:30 fatal: packfile .git/objects/pack/pack-207d4868e013714b498339e2a101d4884e36ae8d.pack cannot be mapped: Cannot allocate memory
```

**Comment by richardlau** [comment]
This appears to be only happening on [test-equinix-ubuntu2004_container-armv7l-1](https://ci.nodejs.org/computer/test-equinix-ubuntu2004_container-armv7l-1/). 

I tried restarting the container but the problem persists: https://ci.nodejs.org/job/node-test-binary-armv7l/9148/RUN_SUBSET=js,nodes=ubuntu2004-armv7l/console

Removed the `node-test-binary-armv7l` workspace from `/home/iojs/test-equinix-ubuntu2004_container-armv7l-1/`: https://ci.nodejs.org/job/node-test-binary-armv7l/9149/RUN_SUBSET=js,nodes=ubuntu2004-armv7l/console
