### ISSUE TITLE
No space left on test-orka-macos11-x64-2

### ISSUE THREAD

**Issue by aduh95** [nodejs/build#3592]
https://ci.nodejs.org/job/node-test-commit-osx/56245/nodes=osx11-x64/console

**Comment by UlisesGascon** [comment]
It has been an on going issue for a while, [see](https://github.com/nodejs/jenkins-alerts/issues?page=1&q=test-orka-macos11-x64-2+has+low+disk+space).

**Comment by ryanaslett** [comment]
This machine has been cleaned up and should last until replacement.
