### ISSUE TITLE
Adding linux on Z machines to CI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#360]
This is to help provide visibility/track progress of adding z machines to the CI.

I have 3 machines to add to the CI.  These are to support including linuz on Z in the Node/libuv builds.  It should be possible to run the builds for libuv now and it will be possible to run Node builds when version 5.1 comes into one of the Node branches.  Also plan some advance work to have hybrid Node builds before then.   This issue will track adding the test machines, a separate issue will cover added the release machine when this is appropriate.

- [x] add to firewall rules so machines can connect to CI
- [x] hook up test machines to CI
- [x] create ansible scripts to configure machines
- [X] document links to console for management/restart etc.
- [x] add private keys to secrets repo (or equivalent add test keys)
- [x] add ccache (seems this package is not in the default list for rhel)
- [X] add machines to libuv tests
- [x] node test builds
- [x] identify people to accept terms and get them to accept
- [x] Make sure all of the above it committed/landed

**Comment by mhdawson** [comment]
PR for ansible scripts to configure machines

**Comment by mhdawson** [comment]
Libuv tests now include linuxOne under the linux runs, all green

**Comment by mhdawson** [comment]
PR to add ccache https://github.com/nodejs/build/pull/373

**Comment by mhdawson** [comment]
Job for Node tests is ready here:  https://ci.nodejs.org/job/node-test-commit-linuxone-mdawson/

Today I can build it with my branch (mhdawson/io.js linuxone3) as that branch contains lkgr from google as of ~ March 25 + some later patches from the google repos for z along with an updated version of master from @ofrobots that was updated to work with that level of V8 and the recent changes for Node itself landed under: https://github.com/nodejs/node/pull/5941.

So I think that job is as ready as we can be until master or v6 can be built with the 5.1 version of v8.

**Comment by mhdawson** [comment]
Provide link to console/userid/password to @jbergstroem  who will add to the right place

Added the test keys to the 2 test machines

**Comment by mhdawson** [comment]
So all that is left at this point until we need a release machine (which we can handle separately) are for the outstanding build PR's to land and  the Terms and Conditions from Marist so that myself, @jbergstroem and @rvagg can accept them

**Comment by ofrobots** [comment]
Great! As someone who has worked a lot with zArch in the past, I am somewhat amused by the issue number this ended up at :smile:. 

For others who might not have context: [link](https://en.wikipedia.org/wiki/IBM_System/360).

**Comment by mhdawson** [comment]
Issue opened to track last issue of accepting terms: https://github.com/nodejs/build/issues/386

**Comment by mhdawson** [comment]
All done, closing.
