### ISSUE TITLE
Redirect http://docs.libuv.org -> https://docs.libuv.org

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#3609]
As noted [here](https://github.com/libuv/libuv/discussions/4284), the docs subdomain doesn't auto-redirect to HTTPS whereas the main domain does.

**Comment by targos** [comment]
Are you sure it's handled by the Build WG? `nslookup docs.libuv.org` points to `readthedocs.io`.

**Comment by richardlau** [comment]
@saghul (based on https://github.com/libuv/libuv/issues/4088)

**Comment by saghul** [comment]
👋  Yep, I set that up. Looks like auto-ssl is supported: https://docs.readthedocs.io/en/stable/custom-domains.html#features I'll take a look!

@bnoordhuis I think this probably belongs in libuv/libuv

**Comment by saghul** [comment]
Fixed right now btw!
