### ISSUE TITLE
FYI Jenkins security release 24 January 2024

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3611]
https://groups.google.com/g/jenkinsci-advisories/c/QZiecB2ArMs/m/sDvJWIdHBQAJ?utm_medium=email&utm_source=footer

> The Jenkins project plans to publish new Jenkins releases (weekly and LTS 2.426.3) on Wednesday, January 24. These updates will contain fixes for security issues present in current versions of Jenkins. The highest severity is "Critical". The security advisory will be issued at the same time to provide further information.
> 
> Additionally, we will provide a workaround for anyone unable to immediately update Jenkins.

**Comment by targos** [comment]
The release is now out.

https://www.jenkins.io/security/advisory/2024-01-24/
