### ISSUE TITLE
All OSX machines are offline 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#3612]
All OSX machines are offline - see https://github.com/nodejs/node/pull/51491 for more discussion

**Comment by MoLow** [comment]
seems kike the issue is with disk space?https://ci.nodejs.org/manage/computer/
<img width="1520" alt="image" src="https://github.com/nodejs/build/assets/8221854/afe524f1-e539-40aa-8201-19ca3f51fd3d">
https://github.com/nodejs/jenkins-alerts/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by mhdawson** [comment]
Rebooted https://ci.nodejs.org/computer/test%2Dorka%2Dmacos11%2Dx64%2D1/ which I think is what's needed in some of these cases.

**Comment by mhdawson** [comment]
I guess its more than a reboot that is needed

**Comment by mhdawson** [comment]
From https://github.com/nodejs/build/issues/3089 running cleaner.sh on one of the machines and then rebooted it

**Comment by mhdawson** [comment]
ran cleaner.sh and rebooted the other one

**Comment by mhdawson** [comment]
The two machines that were blocking are both online, closing.
