### ISSUE TITLE
`Cannot run program "git" (in directory "/home/iojs/build/workspace/node-test-commit-linux"): error=2, No such file or directory` on test-digitalocean-fedora38-x64-2

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3614]
Builds on [test-digitalocean-fedora38-x64-2](https://ci.nodejs.org/computer/test%2Ddigitalocean%2Dfedora38%2Dx64%2D2/) are failing due to errors running `git`.
e.g.
https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/55892/console
```console
15:39:04 Cloning repository git@github.com:nodejs/node.git
15:39:04  > git init /home/iojs/build/workspace/node-test-commit-linux # timeout=10
15:39:04 ERROR: Error cloning remote repo 'origin'
15:39:04 hudson.plugins.git.GitException: Could not init /home/iojs/build/workspace/node-test-commit-linux
...
15:39:04 Caused by: hudson.plugins.git.GitException: Error performing git command: git init /home/iojs/build/workspace/node-test-commit-linux
...
15:39:04 Caused by: java.io.IOException: Cannot run program "git" (in directory "/home/iojs/build/workspace/node-test-commit-linux"): error=2, No such file or directory
...
15:39:04 Caused by: java.io.IOException: error=2, No such file or directory
...
```

**Comment by richardlau** [comment]
I've restarted the Jenkins agent via Ansible:
```console
ansible-playbook --limit test-digitalocean-fedora38-x64-2 -vv ansible/playbooks/jenkins/worker/restart-agent.yml
```
Test build: https://ci.nodejs.org/job/node-test-commit-linux/55894/nodes=fedora-latest-x64/

**Comment by richardlau** [comment]
My best guess is that this is related to the dnf updates that occurred around 12:53 today (according to `/var/logs/dnf.log` on the machine). Although `git` wasn't updated, `glibc` and `openjdk` were.

**Comment by richardlau** [comment]
> Test build: https://ci.nodejs.org/job/node-test-commit-linux/55894/nodes=fedora-latest-x64/

Build succeeded.

**Comment by targos** [comment]
It's my fault. I often try to upgrade dependencies on the fedoras to see if it helps with the compilation issues with have on recent V8 versions.
What should I do in the future to avoid this?

**Comment by richardlau** [comment]
> It's my fault. I often try to upgrade dependencies on the fedoras to see if it helps with the compilation issues with have on recent V8 versions. What should I do in the future to avoid this?

If you have time, check (either trigger or wait for the next run) a subsequent build checks out and starts to build. Or to be safe either restart the agent or the machine.

Anecdotally I think `openjdk` updates tend to be a good reason to restart the agent.
