### ISSUE TITLE
Nomination of @abmusse to Build WG

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3618]
I was talking online to @abmusse today about https://github.com/nodejs/jenkins-alerts/issues/1217 and it turns out that while he has access to the IBM i machines at iinthecloud, he does not have access to the rzkh machine. Rather than ad-hoc access to machines, I'd like to propose to formalize his access and grant him test level access.

For some background, he works for IBM and for the last year been involved in upstream Node.js/libuv work, initially on IBM i but more recently expanding to other platforms. @mhdawson and I (both Red Hat) meet with him regularly online and can vouch for him.

He is not (yet) a Node.js collaborator, but FWIW his PR's in:
- nodejs/node: https://github.com/nodejs/node/pulls?q=is%3Apr+author%3Aabmusse
- libuv: https://github.com/libuv/libuv/pulls?q=is%3Apr+author%3Aabmusse
- and even one PR in nodejs/build: https://github.com/nodejs/build/pulls?q=is%3Apr+author%3Aabmusse

CC @nodejs/build. Feel free to send any concerns/questions to me (either in private or comments to this issue).

**Comment by UlisesGascon** [comment]
+1 from me

**Comment by mhdawson** [comment]
+1 from me.

**Comment by sxa** [comment]
+1

**Comment by richardlau** [comment]
Discussed in today's WG meeting. No objections (either in the meeting or expressed privately). Proceeding with the onboarding:

### Onboarding to build-test issue checklist

- [ ] Email the new member and obtain their public GPG key
- [ ] Add them to the `test` group in `nodejs-private/secrets`
- [ ] Add them to the `nodejs/build` and `nodejs-private/build` GitHub teams
- [ ] Before the meeting the Onboardee is to:
  - [ ] Install Ruby and the `dotgpg` gem
  - [ ] Install Python and Ansible
  - [ ] Read [`resources.md`](./doc/resources.md), [`jenkins-guide.md`](./doc/jenkins-guide.md),
    [`GOVERNANCE.md`](./GOVERNANCE.md) and have any questions ready
- [ ] Schedule a meeting with the member to:
    - [ ] Walk them through the infrastructure and what other members do
    - [ ] Explain how to decrypt nodejs/secrets
    - [ ] Practice SSH access to the organization's machines. See [`ssh.md`](./doc/ssh.md).
    - [ ] Practice running the `jenkins/worker/create.yml` playbook on one of the machines in the test CI cluster
    - [ ] Answer any questions they may have
- [ ] PR changes to [README.md](./README.md#build-wg-members) to add the member to build-test
