### ISSUE TITLE
Request access to some ci boxes to debug libuv crash

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#3626]
We're in the process of releasing [libuv@1.48.0](https://github.com/libuv/libuv/issues/4248) needed for the Nodejs security release of this week and we're observing a crash in the `test/sequential/test-performance-eventloopdelay.js` test in different boxes. Having access to some of those would really help, as it's not so easily reproducible locally. The builbots I'm talking about are:
- [debian11-x64](https://ci.nodejs.org/job/node-test-commit-linux/56052/nodes=debian11-x64/testReport/junit/(root)/sequential/test_performance_eventloopdelay/).
- [alpine-latest-x64](https://ci.nodejs.org/job/node-test-commit-linux/56052/nodes=alpine-latest-x64/testReport/junit/(root)/sequential/test_performance_eventloopdelay/).
- [fedora-last-latest-x64](https://ci.nodejs.org/job/node-test-commit-linux/56052/nodes=fedora-last-latest-x64/testReport/junit/(root)/sequential/test_performance_eventloopdelay/)
- [rhel8-x64](https://ci.nodejs.org/job/node-test-commit-linux/56052/nodes=rhel8-x64/testReport/junit/(root)/sequential/test_performance_eventloopdelay/).
- [ubi81_sharedlibs_openssl111fips_x64](https://ci.nodejs.org/job/node-test-commit-linux-containered/41529/nodes=ubi81_sharedlibs_openssl111fips_x64/testReport/junit/(root)/sequential/test_performance_eventloopdelay/).

Thanks

**Comment by richardlau** [comment]
@santigimeno I've added your key to [test-ibm-rhel8-x64-1](https://ci.nodejs.org/computer/test%2Dibm%2Drhel8%2Dx64%2D1/) -- I've sent more details as a DM in Slack.
