### ISSUE TITLE
Request access to locked CI 

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/build#3628]
Hello I'm working on the security release:

- https://github.com/nodejs-private/node-private/pull/545
- https://github.com/nodejs-private/node-private/pull/544

I'd like to have access to the locked CI as also part of my job of automating the security release.

**Comment by richardlau** [comment]
I've explicitly added @marco-ippolito to the security matrix as he's not in one of the existing teams (security-triage or releasers).
Let's keep this issue open to remind ourselves to tidy up afterwards.

**Comment by marco-ippolito** [comment]
@richardlau I guess this is fixed?
