### ISSUE TITLE
Access to CITGM under embargo to all TSC

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#3631]
Hey folks!

During this security release, access to CITGM for all TSC was found to be necessary during the review of the final binary. Considering TSC also has access to patches and reports, we are not exposing anything sensitive by adding the entire group as a viewer.

Ref: https://openjs-foundation.slack.com/archives/C027PSG2PJR/p1707862827771969

cc: @nodejs/tsc

**Comment by aduh95** [comment]
Small correction: all TSC voting members have access to the patches and reports, most regular TSC members do not.

**Comment by RafaelGSS** [comment]
Yes, that's correct. We could give access to all voting members.

**Comment by RafaelGSS** [comment]
SGTM
