### ISSUE TITLE
Jenkins volume full on ci-release

### ISSUE THREAD

**Issue by targos** [nodejs/build#3632]
There's an alert on https://ci-release.nodejs.org/administrativeMonitor/hudsonHomeIsFull/

```
# df -h | grep jenkins
/dev/xvdc1      295G  275G  4.6G  99% /var/lib/jenkins
```

**Comment by richardlau** [comment]
There is a [`remove_old.sh`](https://github.com/nodejs/build/blob/main/backup/backup_scripts/remove_old.sh) script that is supposed to be run periodically on `backup`. It should be deleting things older than [21 days](https://github.com/nodejs/build/blob/e8876cc3b02ae4a8228011f050512880177ad717/backup/backup_scripts/remove_old.sh#L18).
https://github.com/nodejs/build/blob/e8876cc3b02ae4a8228011f050512880177ad717/backup/backup_scripts/remove_old.sh#L24
https://github.com/nodejs/build/blob/e8876cc3b02ae4a8228011f050512880177ad717/backup/README.md?plain=1#L55

**Comment by targos** [comment]
Volume is now full.
