### ISSUE TITLE
Source INTL data locally for citgm

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/build#364]
This may also apply to all of CI if it isn't being done, but I am not sure.

I find a non trivial amount of time is spent grabbing this resource on every box. It is also a waste of bandwidth.

How would we going about sourcing a local file for INTL

**Comment by jbergstroem** [comment]
If you're referring to the icu download we already have a local setup for all machines -- perhaps have a look at the other test jobs.

**Comment by TheAlphaNerd** [comment]
@jbergstroem how is that being done?

For the CI job's I'm seeing
```
NODE_TEST_DIR=${HOME}/node-tmp make run-ci -j $(getconf _NPROCESSORS_ONLN)
```

**Comment by TheAlphaNerd** [comment]
@jbergstroem I just dug into the build script for `test-commit-osx` and `test-commit-linux` and both are doing the same setup as mentioned above.

AFAIK there isn't anywhere that is testing ICU in CI.

/cc @srloomis

**Comment by jbergstroem** [comment]
Sorry -- poor memory. In release jobs we do stuff like:
```bash
CONFIG_FLAGS="--download-path=${HOME}/node-icu/"
mkdir -p ${HOME}/node-icu/
...
```

**Comment by TheAlphaNerd** [comment]
so we are doing that. but we are still fetching on everything make

**Comment by jbergstroem** [comment]
If so, it should only be fetched once.

**Comment by TheAlphaNerd** [comment]
nailed it this time... was putting the config_flags in the wrong place :smile:

I'm going to audit the other code and make sure we are not making the same mistake there too
