### ISSUE TITLE
Jenkins requires to change how agents are connected

### ISSUE THREAD

**Issue by targos** [nodejs/build#3640]
After https://github.com/nodejs/build/issues/3637:

- The `-jnlpUrl` argument has been deprecated.
- Work directory options should be passed as command-line options instead of being set in Jenkins.

See https://www.jenkins.io/doc/upgrade-guide/2.440/#upgrade-to-the-latest-version-of-remoting

**Comment by targos** [comment]
I had a look at a few nodes and they all seem to have the same deprecated options:
![image](https://github.com/nodejs/build/assets/2352663/ed625041-7459-42f1-a74d-83cd41fdc336)

I don't know if we need to replicate that in command-line options.

**Comment by sxa** [comment]
I haven't looked at that side of it yet but I agree that it sounds like we'd need to replicate that with command-line alternatives if we want to keep them.

I suppose the real question is: Do we still need those options?

**Comment by richardlau** [comment]
I have no idea what those options do.
