### ISSUE TITLE
node-test-linter broken due to CRLF in markdown files

### ISSUE THREAD

**Issue by targos** [nodejs/build#3656]
https://ci.nodejs.org/job/node-test-linter/
Example: https://ci.nodejs.org/job/node-test-linter/53842/console

**Comment by targos** [comment]
It seems related to https://github.com/nodejs/node/pull/52161, but CI wasn't run on that PR.

**Comment by richardlau** [comment]
> It seems related to [nodejs/node#52161](https://github.com/nodejs/node/pull/52161), but CI wasn't run on that PR.

Looks like this was run against that PR? https://ci.nodejs.org/job/node-test-linter/53839/

**Comment by richardlau** [comment]
> > It seems related to [nodejs/node#52161](https://github.com/nodejs/node/pull/52161), but CI wasn't run on that PR.
> 
> Looks like this was run against that PR? https://ci.nodejs.org/job/node-test-linter/53839/

Although I am confused how we then had subsequent passing builds before https://ci.nodejs.org/job/node-test-linter/53842/console

**Comment by targos** [comment]
I see only one subsequent passing build, which was started at the same time and ran in another workspace (`node-test-linter@2`): https://ci.nodejs.org/job/node-test-linter/53841/console

**Comment by targos** [comment]
I wiped out the workspace.

/cc @StefanStojanovic since it seems you started the first failing run.

**Comment by StefanStojanovic** [comment]
hey @targos, yes I was the one to run that job to check if it would fail on that PR or not. after I saw it failed I told @huseyinacacak-janea to mark the PR as draft and ensure the linter job passes. Sorry to have broken CI, it should be fixed now.
