### ISSUE TITLE
Jenkins v2.0

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/build#366]
https://jenkins.io/2.0/

Is this something we might want to upgrade to? Seems like they have much better support for CD, which is some of the stuff we have been talking about wanting to do (re: auto landing etc)

**Comment by jbergstroem** [comment]
Seeing how we've had our share of issues with Jenkins I'd say welet it brew for a while. The pipeline stuff is pretty interesting, looking forward to migrating towards that.

**Comment by ChALkeR** [comment]
From the security point of view, I would prefer not to see auto landing from Jenkins.

**Comment by jbergstroem** [comment]
Borderline gossip-y, but there's some valuable information in this thread with regards to 2.0: https://news.ycombinator.com/item?id=11362058

**Comment by rvagg** [comment]
FYI our release Jenkins, which is pretty well protected from public access, was inadvertently updated to Jenkins 2.7. They marked that branch as "lts" and started pushing it out via their apt repo so we magically went from 1.5 to 2.7 without warning. @jbergstroem and I agreed to let it be and experiment with it a little. It seems to work OK and has pushed out nightlies and the last v4.5 RC. @jbergstroem has even gone all out and applied a custom theme to it .. yay?

We'll experiment with this for a while and maybe roll it out to ci.nodejs.org when we're comfortable. So far so good, but ci-release.nodejs.org is significantly less complex than ci.nodejs.org is!

heads-up @nodejs/release folks

**Comment by jbergstroem** [comment]
We're now running jenkins 2.x at both ci and ci-release.
