### ISSUE TITLE
OS X buildbots/ci: call to action

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#367]
Our current state of testing on OS X is (and has been for a while) uncertain. The machines provided by Voxer (which as been serving us fine up to recently) has no more support, meaning should they die or run into issues we can't manage remote, we're out of luck.

Also, OS X coverage is poor. We're currently testing and releasing on 10.10, but since Node.js is "officially" (TBD) supporting 10.7 and up, we should cover these. In order to establish what our lowest supported OS X will be; vm's should be in place to verify that.

Finally, we've been seeing traffic related issues at Voxer – tests timing out because of poor network latency – an issue out of our reach.

We've been exploring two options:
- invest in a few mac minis
  - good: much resources
  - bad: we can't get hold of older versions of OS X
  - good/bad (depending on how you see it): we require dedicated hosting such as macminicolo, macminivault
- go with a vm provider such as macstadium
  - good: they provide a wide range of os x
  - good: managed hosting and no investment in hardware required
  - bad: more expensive (estimated cost: $800/mo)

Additionally, we've reached out to a few potential sponsors that could help us with either option - but nothing is locked in so far.

My suggestion would be the following setup:
- 2x 10.7 4G ram 2vcpu (~40G disk)
- 2x 10.8 4G ram 2vcpu (~40G disk)
- 2x 10.9 4G ram 2vcpu (~40G disk)
- 2x 10.10 4G ram 2vcpu (~40G disk)
- 2x 10.11 4G ram 2vcpu (~40G disk)
- 2x 10.10 2G ram 2vcpu for release (~40G disk)

I've managed to run our test suite on a jenkins 2G vm (10.10) but I think we'll be running into memory issues. If we're virtualising, I guess 3G would work fine as well. If we have enough room we should probably look at additionally adding a 8G vm for v8.

We need to act to avoid downtime and also be able to improve our quality of OS X support. How do we move forward?

**Comment by jbergstroem** [comment]
Just going to put this thread here; shows how important it is for us to start testing on more versions: https://github.com/nodejs/node/issues/5731

**Comment by ChALkeR** [comment]
Do we really want to support 10.7 and 10.8? Google does not support those from Chrome 50, that's v8 5.0 which is in Node.js 6.0. Also, 10.7 and 10.8 do not receive security updates from Apple.

**Comment by jbergstroem** [comment]
@ChALkeR we still have 4.x to care about.

**Comment by jbergstroem** [comment]
I'm happy to revisit requirements; but at this stage we need to define them and uphold them. We kind of do neithier :)

**Comment by orangemocha** [comment]
As stated in this issue, our ability to test Node.js on OSX is at risk. The Build WG would like to reach out to any companies interested in providing support for OSX resources - before asking the Foundation to allocate budget for it, but we are unsure about what channels to pursue. Escalating to @nodejs/tsc .

**Comment by orangemocha** [comment]
...and @mikeal

**Comment by doug-wade** [comment]
We here at [Redfin](https://github.com/redfin) have identified ~10 machines that we'd be able to allocate for node.js testing.  How do we discuss whether this meets the need and how the logistics might work?

**Comment by jbergstroem** [comment]
@doug-wade Amazing news -- lets have a chat! Whats your preferred medium? I'm [irc](jbergstroem@freenode) or [email](bugs at bergstroem dot nu). We can do Skype too.

**Comment by doug-wade** [comment]
@jbergstroem I sent you an email about scheduling some Skype time

**Comment by jbergstroem** [comment]
@doug-wade sweet, will get right back to you.

**Comment by Fishrock123** [comment]
Any progress here?

**Comment by rvagg** [comment]
nothing worth reporting

**Comment by jbergstroem** [comment]
Taking this off the wg-agenda for now. Not that it isn't important, but lets bring it back once we have updates

**Comment by Trott** [comment]
Should this remain open?

**Comment by rvagg** [comment]
ibm folks are helping with the new osx infra, we're still not in a great place with our osx infra but at least we're moving in the right direction
