### ISSUE TITLE
node-test-commit-osx not executing jobs

### ISSUE THREAD

**Issue by tniessen** [nodejs/build#3673]
Some jobs have been queued for about 20 hours. Within the last 48 hours, only two jobs succeeded (one green, one yellow).

Build trend:

![image](https://github.com/nodejs/build/assets/3109072/fb1a77d3-1ede-4fcb-a456-c2536348fa92)

cc @nodejs/build-infra

**Comment by UlisesGascon** [comment]
Thanks for reporting it, @tniessen.

I believe we can resolve this by restoring the empty space in:
- https://github.com/nodejs/jenkins-alerts/issues/1486
- https://github.com/nodejs/jenkins-alerts/issues/1475

I won't be able to address it immediately, but I can take a look at it tomorrow evening (potentially). However, if anyone from the team would like to handle it, feel free to do so.

**Comment by targos** [comment]
I ran the cleanup script and rebooted the machines. They are taking jobs again.

I wonder if the long-term solution could be to disable core dumps: https://discussions.apple.com/thread/251230370?sortBy=best
