### ISSUE TITLE
Upgrade `test-digitalocean-ubuntu1804_docker-x64-2` to Ubuntu 22.04

### ISSUE THREAD

**Issue by targos** [nodejs/build#3681]
And also the `ubuntu1804_sharedlibs` in it + delete `test-digitalocean-ubuntu1604_container-x64-2`

Any reason not to do it?
If it's fine, I'll make the change.

**Comment by richardlau** [comment]
SGTM

**Comment by targos** [comment]
Done.

**Comment by targos** [comment]
I removed the following containers:
- test-digitalocean-ubuntu1604_container-x64-2
- test-digitalocean-ubuntu1804_container-x64-2
- test-digitalocean-ubuntu1804_arm_cross_container-x64-2

**Comment by targos** [comment]
Now both digitalocean-ubuntu2204_docker-x64 machines run the same set of containers.
