### ISSUE TITLE
Corrupted v22.0.0 Windows ARM64 7z file

### ISSUE THREAD

**Issue by targos** [nodejs/build#3695]
https://nodejs.org/download/release/v22.0.0/node-v22.0.0-win-arm64.7z

I tried to extract it from Windows and macOS. Both fail.

**Comment by richardlau** [comment]
On Windows 11 I can extract https://nodejs.org/download/release/v22.0.0/node-v22.0.0-win-arm64.7z with 7zip 23.01 without errors but attempting to do so via Windows Explorer errors
![image](https://github.com/nodejs/build/assets/5445507/d9a021a9-bb6c-4d62-ac65-4b72d600e817)

cc @StefanStojanovic

**Comment by StefanStojanovic** [comment]
@richardlau the default extractor application Windows 11 uses from Windows Explorer probably doesn't fully support 7z files by default - we are using the latest 7zip (v23.01) to make those files so the chance is probably even smaller.

Depends on how you look at it, but the way I see it, we have both `zip` and `7z` files, and zip works fine from Windows Explorer. 7z is smaller in size, but you may not be able to extract it out of the box without some other extractor app than the default one. It looks like a reasonable trade-off. The main issue I see here is that Windows offers you to extract it via Explorer, but cannot do it.

**Comment by targos** [comment]
I'm ready to accept the trade-off if we don't have a choice. If we can tweak the call to 7zip so that it creates a backwards-compatible file, it would be better.

**Comment by StefanStojanovic** [comment]
I'll see what I can do. Two options I see now, before starting are:

1. Change the 7zip call - This is a part of `vcbuild.bat` so we'd have to apply it in all LTS branches.
2. Downgrade 7zip on compilation machines and lock its version. This would be done via Ansible.

I'm more in favor of the second option as it fixes the infrastructure that caused the issue because part of `vcbuild.bat` responsible for creating `.7z` files hasn't been changed in the last 6 years.

**Comment by StefanStojanovic** [comment]
I've investigated this further and only the ARM64 `.7z` file has issues, In addition, the file causing problems is the `node.exe`. I don't know exactly why, but I assume it has something to do with it being an ARM64 binary. All of this was observed with v23.01 (latest)

Afterward, I started downgrading `7-zip` until I could locally produce a file that could be exported on Windows 11 with its default file extractor app. Luckily, it was the previous version (v22.01), so not a huge downgrade after all.

With all these findings, I still suggest using the second approach:

> Downgrade 7zip on compilation machines and lock its version. This would be done via Ansible.

This would fix the issue with all future releases, but the ones already affected would still not work. Should we upload the new ARM64 `.7z` files, or we can leave it like that?

**Comment by richardlau** [comment]
> 
> This would fix the issue with all future releases, but the ones already affected would still not work. Should we upload the new ARM64 `.7z` files, or we can leave it like that?

I think we'd have to leave it -- new files would mean new shasums and our shasums are signed (by the releaser who did the releases).

**Comment by targos** [comment]
Related: https://support.microsoft.com/en-us/topic/june-25-2024-kb5039302-os-builds-22621-3810-and-22631-3810-preview-0ab34e3f-bca9-4a52-a1a4-404bf8162f58

> New! This update affects File Explorer. You can now create 7-Zip and Tape Archive (TAR) files using the context menu.

I guess it means that we will soon be able to create 7-Zip archives without installing the 7-Zip software.
