### ISSUE TITLE
New libuv test jobs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#372]
In a response to https://github.com/libuv/libuv/issues/795 @saghul asked for jobs which could be used to run the libuv tests individually for different os's like linux, osx, smartos etc.

That seemed reasonable so I created these new jobs:

https://ci.nodejs.org/job/libuv-test-commit/

https://ci.nodejs.org/job/libuv-test-commit-AIX/
https://ci.nodejs.org/job/libuv-test-commit-linux/
https://ci.nodejs.org/job/libuv-test-commit-osx/
https://ci.nodejs.org/job/libuv-test-commit-smartos/
https://ci.nodejs.org/job/libuv-test-commit-windows/

Using the logic from the existing libuv job - https://ci.nodejs.org/job/libuv+any-pr+multi/

The first one runs the others, but the individual ones can also be run on their own.

The names are patterned off what we nave for the node tests.

They are parametrized but by default will test the v1.x branch as that is what
the instructions in the readme suggest people should test against.

The new jobs do have failures but I believe in the same places as the existing job.

Opening this issue for awareness and review/comment.

**Comment by cjihrig** [comment]
Thanks @mhdawson

**Comment by saghul** [comment]
Thanks @mhdawson this will be really helpful!

**Comment by jbergstroem** [comment]
..now we only have to get tests passing :-)

**Comment by mhdawson** [comment]
Agreed on the tests.  We are working on the AIX ones.  Down to 6 from a larger number (would have been 4 if new functionality was not being added in parallel)

**Comment by mhdawson** [comment]
Ok given no objections/complains about what I have @saghul should we tell contributors to start using https://ci.nodejs.org/job/libuv-test-commit/ instead of the pre-existing job ?

**Comment by saghul** [comment]
I'd say so!

**Comment by mhdawson** [comment]
@nodejs/collaborators FYI, there are new libuv CI jobs as outlined in this issue that should now be used instead of the previous https://ci.nodejs.org/job/libuv+any-pr+multi/ job when running the libuv tests.

**Comment by jbergstroem** [comment]
FreeBSD was missing from the job matrix, so I added it: https://ci.nodejs.org/job/libuv-test-commit-freebsd/

**Comment by jbergstroem** [comment]
@michaeldawson: Btw, no need for the conditional steps in the subjobs (that checks ostype).

**Comment by mhdawson** [comment]
@jbergstroem FreeBSD was covered under linux.  I was on the edge as to whether to break it out or not.  Now that its separate it should be removed from the linux job

**Comment by jbergstroem** [comment]
Oh, didn't know. Sorry.

**Comment by mhdawson** [comment]
Removed freeBSD from linux group, closing as complete

**Comment by rvagg** [comment]
/cc @nodejs/build

also @joaocgreis would you mind sanity checking the setup since you're our resident multi job expert?

**Comment by joaocgreis** [comment]
@mhdawson I cannot edit the osx job, can you check the permissions for jenkins-admins?

All others look fine.

**Comment by jbergstroem** [comment]
@joaocgreis My bad. Fixed.

**Comment by joaocgreis** [comment]
@jbergstroem Thanks!

All LGTM.
