### ISSUE TITLE
`jenkins-workspace` tasks don't work on existing workers

### ISSUE THREAD

**Issue by targos** [nodejs/build#3732]
Even after https://github.com/nodejs/build/pull/3722, it fails at this step:

```
TASK [jenkins-workspace : Initialize Git repository] *******************************************************************
fatal: [test-equinix-ubuntu2204-x64-2]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --bare https://github.com/nodejs/node /home/binary_tmp/binary_tmp.git", "msg": "Cloning into bare repository '/home/binary_tmp/binary_tmp.git'...\nfatal: Invalid path '/home/iojs/build': Permission denied", "rc": 128, "stderr": "Cloning into bare repository '/home/binary_tmp/binary_tmp.git'...\nfatal: Invalid path '/home/iojs/build': Permission denied\n", "stderr_lines": ["Cloning into bare repository '/home/binary_tmp/binary_tmp.git'...", "fatal: Invalid path '/home/iojs/build': Permission denied"], "stdout": "", "stdout_lines": []}
```

**Comment by richardlau** [comment]
I think a lot of this weirdness is coming from 
https://github.com/nodejs/build/blob/97b592a35b272a0a7b19583dca3a4d59fe6ff1f2/ansible/roles/jenkins-workspace/tasks/main.yml#L42-L43
which means we're trying to create a git repository owned by `binary_tmp` into a directory under the home for a different user, `iojs`.

For the current machines, the comment about partitions only applies to the IBM hosted machine where the bigger disk is mounted at `/home/iojs`. I'm not sure why we couldn't mount the disk at `/home` instead and then just create the git repository under the home directory of the `binary_tmp` user.
