### ISSUE TITLE
Next Build WG Meeting (scheduled for 2016-04-05)

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#375]
**Meeting Time:** 8PM Tuesday April 5th UTC, or in your local timezone:
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20160405T20&p1=%3A

### Where
* To be announced

### Agenda
Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* OS X buildbots/ci: call to action [https://github.com/nodejs/build/issues/367]

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by orangemocha** [comment]
Folks, I'll be at the VM summit at the time of this meeting next Tuesday, and I think @rvagg , @mhdawson will also be attending (in person or remotely). 

I don't think that should let the rest of the team stop from meeting, but it would be up to the team to decide. Suggested options:

1. Have the meeting with the current schedule (facilitator needed)
2. Reschedule for the following week (and shift the recurring schedule of one week)
3. Skip this occurrence

**Comment by mhdawson** [comment]
I'll be a the vm summit as well.

**Comment by jbergstroem** [comment]
I can facilitate, but we'd be a pretty small gathering. Perhaps do a hands up so we know? (✋🏻)

**Comment by jbergstroem** [comment]
Unless the summit people find time I suggest we postpone this meeting.

**Comment by orangemocha** [comment]
I take it this meeting was not had.
