### ISSUE TITLE
Missing `npx` command in machines

### ISSUE THREAD

**Issue by mcollina** [nodejs/build#3759]
When running the CITGM job, the `npx` command is not available sometimes:

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3444/nodes=win-vs2022/testReport/junit/(root)/citgm/pino_v9_1_0/

How is it possible?

**Comment by richardlau** [comment]
> 
> Test build: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3446/nodes=win-vs2022/

I think this is now fixed -- at least Pino passed on that build.
