### ISSUE TITLE
release-voxer-osx1010-x64-1 fails to build pkg

### ISSUE THREAD

**Issue by evanlucas** [nodejs/build#376]
When cutting a release, if the osx tar build runs on release-voxer-osx1010-x64-1, the .pkg is not created. If run on release-voxer-osx1010-x64-2, it is created.

**Comment by TheAlphaNerd** [comment]
it is also worth noting that these are the tarball machines, not the .pkg machines... which are no producing the .pkg or headers either

**Comment by jbergstroem** [comment]
Is this still a problem?

**Comment by jbergstroem** [comment]
Closing. Reopen if this still is an issue.
