### ISSUE TITLE
Job result status not displayed in Jenkins (Chromium browsers)

### ISSUE THREAD

**Issue by targos** [nodejs/build#3762]
We lost the colored dots.

![image](https://github.com/nodejs/build/assets/2352663/9f029f9f-cbaf-4be3-928b-2347c4de176a)

**Comment by richardlau** [comment]
FWIW I still see the icons in Firefox 115.12.0esr on Windows 11 but they don't appear in Edge 126.0.2592.56 (same Windows 11 machine).

With both Firefox and Edge, I'm still seeing the icons on the release CI.

**Comment by richardlau** [comment]
> With both Firefox and Edge, I'm still seeing the icons on the release CI.

Speculatively, it might be limited to MultiJob jobs (we don't have any on the release CI)?
At least for me the Matrix based jobs, e.g. [node-test-commit-linux](https://ci.nodejs.org/job/node-test-commit-linux) still appear to be showing icons (although the alignment looks a bit off).

**Comment by targos** [comment]
I just updated Jenkins to 2.452.2 and all plugins. This is still an issue (only on Chromium browsers).

**Comment by richardlau** [comment]
@marco-ippolito drew my attention to https://ci-release.nodejs.org/job/iojs+release/10285/ no longer showing faded status icons for the skipped platforms, e.g.
![image](https://github.com/nodejs/build/assets/5445507/a5717956-7c5b-4474-bea6-eb4e803c7599)

Note the skipped platforms are no longer distinguishable from the platforms that were run. (Also the alignment is off.)

```
11:09:06 Node.js major version: 20
11:09:06 Node.js version: 20.15.0
11:09:06 Skipping cross-compiler-ubuntu1804-armv7-gcc-8 for Node.js 20
11:09:06 Skipping vs2022-arm64 for Node.js 20
11:09:06 Skipping cross-compiler-rhel8-armv7-gcc-8-glibc-2.28 for Node.js 20
11:09:06 Skipping smartos18-release for Node.js 20
11:09:06 Skipping cross-compiler-ubuntu1804-armv7-gcc-6 for Node.js 20
11:09:06 Skipping vs2022-x64 for Node.js 20
11:09:06 Skipping vs2022-x86 for Node.js 20
11:09:06 Running nodes
```

**Comment by richardlau** [comment]
I'm seeing the status icons now with Edge 126.0.2592.68.

**Comment by targos** [comment]
Same here with Chromium Engine Version 126.0.6478.127
