### ISSUE TITLE
PPC BE release machine/PPC BE in standard releases

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#377]
We had been using fedora machines for testing PPC BE but after discussion that is not appropriate for the release machines.  There are limited choices available today on OSUOSL so we are going to look at using ubuntu 14.04.  

That will mean that the binaries won't necessarily run on earlier releases but given the dependency on the 4.8.3 compiler users who want a supported configuration will likely be running on recent distro's.  As long as the binaries will run on rhel7.1 in addition to ubuntu 14.04 I think it will be acceptable.  We can always adjust if there  is a real need from the community for support of earlier versions.

The required steps to complete this would be:

- [x] provision ubuntu 14.04 machine at osuosl
- [x] build on ubuntu 14.04
- [x] validate binary runs on rhel7.1
- [x] Update ansible files to install additional required modules
- [x] move test machines over to ubuntu 14.04 for BE and add to jenkins
- [x] provision ubuntu 14.04 BE release machine + add to jenkins
- [x] validate tests run/pass as they are on fedora
- [x] add release jobs/scripts etc
- [ ] add to subsequent releases
- [ ] update download page to point to releases in download directory and update wording on download page

**Comment by mhdawson** [comment]
Created an ubuntu 14.04 machine quite a while ago but 64 bit compiles were failing.  Took a while to get back to looking at it but the problem seems to have been:
  - 32 bit is still the default for 14.04 for PPC (different from other platforms)
  - even compiling hello world failed
  - you need g++-multilib to get the 64 bit components (for x86 this would give you the 32 bit components instead)

After adding g++-multilib I have successfully build/run the tests and they all passed.

**Comment by mhdawson** [comment]
I just ran citgm-all on one of our PPC BE RHEL 7.0 machines.  Nothing unexpected so seems like its reasonable to build on ubuntu 14.04 and get RHEL support as well.

**Comment by mhdawson** [comment]
PR here for required core ansible updates: https://github.com/nodejs/build/pull/382

**Comment by mhdawson** [comment]
Hooked up one ubu 14 be test machine and validated builds/tests ok under CI:

**Comment by mhdawson** [comment]
building new test and release machine now

**Comment by mhdawson** [comment]
second test machine moved over (test-osuosl-ubuntu14-ppc64_be-2), build to validate all is ok:  https://ci.nodejs.org/job/node-test-commit-plinux/2022/nodes=ppcbe-ubuntu1404/

**Comment by mhdawson** [comment]
Noticed I had not move all the config over from my earlier test job to force 64 bit on be, added that and new runs to validate:
https://ci.nodejs.org/job/node-test-commit-plinux/2023/
https://ci.nodejs.org/job/node-test-commit-plinux/2024/

**Comment by mhdawson** [comment]
@thealphanerd I tried assigning it to you but was not able for some reason

**Comment by TheAlphaNerd** [comment]
perhaps it is because I have not submitted a commit on this repo...

**Comment by jbergstroem** [comment]
Ok, I've:
 - made sure we have hte right keyset for access
 - downloaded icu to `/home/iojs/node-icu`
 - added key pair so it can access [and upload] to `node-www`.

**Comment by mhdawson** [comment]
@jbergstroem thanks, marked the step for setting up the release machine as complete.

**Comment by TheAlphaNerd** [comment]
Just clarifying the next steps that will likely need to be done

- [ ] Create temporary fork of release job
- [ ] enable `ppcbe-ubuntu1404-release-64`
- [ ] run tests to ensure that build works (with help from @mhdawson)
- [ ] enable `ppcbe-ubuntu1404-release-64` in production release job
- [ ] Update website to support new build

@rvagg does that sounds reasonable?
@jbergstroem any complaints to me cloning the build job? I'd run the build exclusively as "test" and like only enable the single platform we are targeting

**Comment by mhdawson** [comment]
Myles had create a test release job but there were issues in that it looks like it was running out of memory.  I investigated and with @jbergstroem figured out the issue was the concurrency setting (see https://github.com/nodejs/build/issues/385).  Binary was successfully built/published here:  https://nodejs.org/download/nightly/v5.11.1-nightly2016050299920480ae/

Next step is to validate the binaries look ok.

**Comment by mhdawson** [comment]
Ran the core tests and citgm on the binaries.

1) CITGM and only modules marked flaky or the known eslint ppc test issue due to the phantomjs dependency in the eslint test had issues
2) The core tests passed except with a small number which fail in the same way on the corresponding x86 build.  I believe they are related to either running dev tests on release binary or being a 5.x nightly.
3) Install and test of the heapdump modules (which requires compilation as it is a native addon) was successful.

So the net is that the binary looks good.

**Comment by mhdawson** [comment]
So I believe next step is to enable in the release job, see the nighties be generated and then included in next release.   Hoping we can do that as soon as current security releases go out.

**Comment by mhdawson** [comment]
Looks like the security releases went out @rvagg @jbergstroem any objections to adding ppc be to the release job so we start to get regular nightlies ?

**Comment by jbergstroem** [comment]
I'm ok with it.

**Comment by rvagg** [comment]
ubuntu 14.04 makes me ok so +1

**Comment by jbergstroem** [comment]
We've retired the fedora20 release slave. it remains to be deleted from our test environment though.

**Comment by mhdawson** [comment]
Ok, added to regular release job, we'll track how it goes over the next few days

**Comment by mhdawson** [comment]
Nightlies for 7 and 5 built ok last night, did a simple sanity check and they look ok.

**Comment by jbergstroem** [comment]
Great! perhaps ping the website team to update links for upcoming releases?

**Comment by rvagg** [comment]
fine by me

**Comment by mhdawson** [comment]
@TheAlphaNerd had volunteered to put together the PR for the website, expect it soon

**Comment by mhdawson** [comment]
Ok this is done, closing
