### ISSUE TITLE
metrics: use buildpack instead of Dockerfiles

### ISSUE THREAD

**Issue by trivikr** [nodejs/build#3775]
### Is your feature request related to a problem? Please describe.

The metrics code run on Google Cloud Run is managed using Dockerfile.
* https://github.com/nodejs/build/blob/main/ansible/roles/metrics/files/summaries/Dockerfile
* https://github.com/nodejs/build/blob/main/ansible/roles/metrics/files/index-generator/Dockerfile
* https://github.com/nodejs/build/blob/main/ansible/roles/metrics/files/process-cloudflare/Dockerfile

These Dockerfiles need to be managed while upgrading Node.js, or making any other changes in application.
For example, here is a PR which upgrades Node.js versions from 14 to 20 https://github.com/nodejs/build/pull/3767

### Describe the solution you'd like
Use buildpack instead of Dockerfiles
https://cloud.google.com/docs/buildpacks/build-application#node.js

**Comment by targos** [comment]
I'm not sure it's an advantage tbh

**Comment by trivikr** [comment]
The only advantage would be the absence of Dockerfiles in the source code.
The Node.js version is only required to be defined in package.json, and buildpack will handle managing the version.

**Comment by targos** [comment]
> The only advantage would be the absence of Dockerfiles in the source code.

That's what I don't see as an advantage. Cloud run works with Docker containers, and for the majority of developers, containers are built using Dockerfiles, not some obscure (to me at least) Google tool.

**Comment by trivikr** [comment]
I agree. It's better to stick with Dockerfiles since:
* It's a standard for building containers in the industry. If the setup is moved to another container solution on GCP or some other cloud, it'll be easy to migrate Dockerfiles.
* Using a Dockerfile is the [first recommendation](https://cloud.google.com/run/docs/building/containers#building_using_a_dockerfile) for building containers in GCP documentation (before buildpack)
