### ISSUE TITLE
Enable travis-ci for docker-node repo

### ISSUE THREAD

**Issue by chorrell** [nodejs/build#378]
Hi there,

I hope this is the right place for this :) 

I want to enable a simple Docker image build test for https://github.com/nodejs/docker-node using Travis-CI. It will help streamline our workflow when updating the image as the test builds will happen automatically. I did a test over here on a fork to make sure it actually worked;

- https://travis-ci.org/chorrell/docker-node
- https://github.com/chorrell/docker-node/tree/travis-ci
- https://travis-ci.org/chorrell/docker-node/builds/120693505

Here's the relevant PR to add the appropriate .travis.yml file to the repo:

https://github.com/nodejs/docker-node/pull/139

**Comment by jbergstroem** [comment]
I think this could just as well belong with the docker-node repo seeing how it doesn't really involve ci or our infrastructure. My only remark to such a PR would be making a distinction wrt testing that building works versus running a test pass within that docker container. A badge wouldn't necessarily explain this.

**Comment by chorrell** [comment]
So apparently I was a bit confused about how to go about setting this up -- I assumed the the build group had some kind of access that I didn't but it turns out third-party app integrations were disabled for the org:

https://github.com/nodejs/nodejs.org/issues/355#issuecomment-159252846

I think I've managed to figure out what I need to do to get this working:

https://travis-ci.org/nodejs/docker-node/builds/120784170

RE: the badge

Yeah, good point. It's not really necessary so I'll just not bother adding it since it may cause some confusion.
