### ISSUE TITLE
macOS builds failing to notarize

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3790]
Starting yesterday, macOS nightly/release builds have failed to notarize:

e.g. https://ci-release.nodejs.org/job/iojs+release/nodes=osx11-release-pkg/10296/console
```
08:03:33 Submitting node-v23.0.0-nightly20240626eca806b54a.pkg for notarization...
08:03:33 Conducting pre-submission checks for node-v23.0.0-nightly20240626eca806b54a.pkg and initiating connection to the Apple notary service...
08:03:34 Error: HTTP status code: 403. A required agreement is missing or has expired. This request requires an in-effect agreement that has not been signed or has expired. Ensure your team has signed the necessary legal agreements and that they are not expired.
08:03:34 Notarization node-v23.0.0-nightly20240626eca806b54a.pkg failed.
```

This will block planned releases of [Node.js 22.4.0](https://github.com/nodejs/node/pull/53583) (cc @targos ) and the [upcoming security release](https://github.com/nodejs/build/issues/3778) (cc @RafaelGSS)

This will probably need someone with access to our Apple Developer account to sign in and accept the updated agreement.
cc @nodejs/build-infra

**Comment by UlisesGascon** [comment]
I will work on it now, following the previous steps in https://github.com/nodejs/build/issues/3605

**Comment by UlisesGascon** [comment]
I just accepted the new agreement, so it should be fine by now. I will let this issue open until we confirm that the CI is passing correctly :+1:

**Comment by richardlau** [comment]
Today's build was successfully notarized. Thanks.
