### ISSUE TITLE
Access to Windows Machine

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/build#3795]
I need access to the windows win-10-vs2019 to diagnostic https://ci.nodejs.org/job/node-test-binary-windows-js-suites/28385/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2019/testReport/junit/(root)/parallel/test_child_process_spawn_windows_batch_file/ error.

Thanks!

**Comment by StefanStojanovic** [comment]
I can set it up for you later during the day. Is that time window OK for you?

**Comment by RafaelGSS** [comment]
Ok

**Comment by StefanStojanovic** [comment]
@RafaelGSS I've created the machine, but Node.js can no longer be compiled with VS 2019 (only VS 2022 now), so you cannot use that machine for the compilation of your branch, You can still of course download the binaries you want and run the tests. Is that enough for you? I've sent you the access parameters via email. If you need any more help, please don't hesitate to let me know. Regards.

**Comment by RafaelGSS** [comment]
I could reproduce it in the machine you provided! Patch is on the way, thank you.

**Comment by StefanStojanovic** [comment]
Hey @RafaelGSS I'll be OOF from Thursday, so I wanted to check if you need something else from me while I'm still here.

**Comment by RafaelGSS** [comment]
I have finished the debugging. Thank you!
