### ISSUE TITLE
macOS 11 arm64 machines offline

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3796]
![image](https://github.com/nodejs/build/assets/5445507/eceb3ef8-a55f-4d63-beec-18615c680bb9)

Both macOS 11 arm64 machines are offline in Jenkins
- [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/computer/test%2Dmacstadium%2Dmacos11.0%2Darm64%2D3/) 
- [test-macstadium-macos11.0-arm64-4](https://ci.nodejs.org/computer/test%2Dmacstadium%2Dmacos11.0%2Darm64%2D4/)

I'm unable to ssh into either of them:
```console
$ ssh test-macstadium-macos11.0-arm64-4
Connection closed by 207.254.38.89 port 22
$
```

cc @nodejs/build-infra

**Comment by targos** [comment]
Refs:
- https://github.com/nodejs/build/issues/3685
- https://github.com/nodejs/build/issues/3667

**Comment by richardlau** [comment]
Ah right, forgot these were known and that we'd disabled the CI job for macOS arm64.

**Comment by richardlau** [comment]
Closing as duplicate.
