### ISSUE TITLE
AIX machine timing out doing git checkout

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#381]
Latest AIX runs seem to be timing out during git checkout.

Investigating

**Comment by mhdawson** [comment]
Seems to be consistent, also don't anything that looks like it changed in terms of config or timeouts although I do see that the timeout configured for git only seems to apply to some of the operations but that is not new.

**Comment by mhdawson** [comment]
Will try a reboot to see if that helps

**Comment by mhdawson** [comment]
Still timed out even after reboot.  Will contact David (at IBM) who provided this temporary machine to see if he can ask the provider if there are issues.  

@jbergstroem in the mean time do you think it would be ok for me to bump the global git timeout to see if that helps as the local one does not seem to apply to the git step that is timing out.

**Comment by jbergstroem** [comment]
@mhdawson you mean on the machine? Feel free (you're referring to `git config --global`, no?) imo.

**Comment by mhdawson** [comment]
I was not thinking about git config --gobal but instead the jenkins level config for timeouts but I'll see if the --global works

**Comment by mhdawson** [comment]
Ready more I was pretty sure it was jenkins/plug-in timing out.  Tried adding this when starting the slave:

<PRE>
-Dorg.jenkinsci.plugins.gitclient.Git.timeOut=30
</PRE>

and also upped the memory for the jvm (hoping this speeds things up)

The combination seems to have resolved the issue.  Will validate and then update the ansible files

**Comment by jbergstroem** [comment]
Did you test them separately? It'd be nice to avoid having to bump ram since we likely want to use the same over all machines (so we can put it at a shared variable file at some stage).

**Comment by mhdawson** [comment]
I'll try to do that next week

**Comment by mhdawson** [comment]
Build with heap size changed back to 128m https://ci.nodejs.org/job/node-test-commit-aix/120/

**Comment by mhdawson** [comment]
The build with the smaller heap size was ok, so removed that change.  See PR for rest of discussion.

**Comment by mhdawson** [comment]
Have extended the timeout under https://github.com/nodejs/build/pull/383 closing
