### ISSUE TITLE
write-ssh-config playbook seems incompatible with Python venv

### ISSUE THREAD

**Issue by targos** [nodejs/build#3821]
To reproduce, in a checkout of this repo:

```bash
python3 -m venv .venv
. .venv/bin/activate
pip install ansible Jinja2
ansible-playbook ansible/playbooks/write-ssh-config.yml
```

Errors with: `/bin/sh: /usr/bin/env python3: No such file or directory`

I can work around it by editing the shebang of `ssh_config.py` to be a direct absolute path to `.venv/bin/python3`.

**Comment by richardlau** [comment]
Maybe https://github.com/ansible/ansible/issues/82535#issuecomment-2178091072?

https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#python-shebang-utf-8-coding says to use
```
#!/usr/bin/python
```

**Comment by targos** [comment]
Thanks, I opened https://github.com/nodejs/build/pull/3824
