### ISSUE TITLE
`Failed to find the WiX Toolset Visual Studio 2019 Extension` for Node.js 18 daily builds

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3825]
The last two [node-daily-v18.x-staging](https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-v18.x-staging/) builds have failed to compile on Windows:

- https://ci.nodejs.org/job/node-compile-windows/56855/nodes=win-vs2019-x86/console
- https://ci.nodejs.org/job/node-compile-windows/56878/nodes=win-vs2019/console

e.g.
```
10:03:35 Looking for WiX installation for Visual Studio 2019...
10:03:35 Failed to find the WiX Toolset Visual Studio 2019 Extension
10:03:35 
10:03:35 > echo Failed to find a suitable Visual Studio installation. 
10:03:35 Failed to find a suitable Visual Studio installation.
10:03:35 
10:03:35 > echo Try to run in a "Developer Command Prompt" or consult 
10:03:35 Try to run in a "Developer Command Prompt" or consult
10:03:35 
10:03:35 > echo https://github.com/nodejs/node/blob/HEAD/BUILDING.md#windows 
10:03:35 https://github.com/nodejs/node/blob/HEAD/BUILDING.md#windows
```

Both ran on [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/computer/test-rackspace-win2019_vs2019-x64-4).
For comparison, https://ci.nodejs.org/job/node-compile-windows/56839/nodes=win-vs2019/ ran on 9 July on the same machine and passed.

According to the [build history](https://ci.nodejs.org/computer/test%2Drackspace%2Dwin2019%5Fvs2019%2Dx64%2D4/builds), https://ci.nodejs.org/job/windows-update-reboot/label=test-rackspace-win2019_vs2019-x64-4/2765/console ran immediately prior to 
https://ci.nodejs.org/job/node-compile-windows/56855/nodes=win-vs2019-x86/console and looks to have updated Visual Studio 2019.
```
09:04:34 visualstudio2019community has been installed.
09:04:34   visualstudio2019community may be able to be automatically uninstalled.
09:04:34  The upgrade of visualstudio2019community was successful.
09:04:34   Deployed to 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community'
09:04:35 visualstudio2019-workload-nativedesktop v1.0.1 is the latest version available based on your source(s).
09:04:35 visualstudio-installer v2.0.3 is the latest version available based on your source(s).
09:04:35 wixtoolset v3.14.1 is the latest version available based on your source(s).
09:04:35 
09:04:35 Chocolatey upgraded 1/31 packages. 
09:04:35  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
09:04:35 
09:04:35 Upgraded:
09:04:35  - visualstudio2019community v16.11.37
```

cc @StefanStojanovic

**Comment by StefanStojanovic** [comment]
Thanks for reporting this. I investigated this yesterday, and strangely enough, the WiX 3 extension was missing on 3 VS2019 compilation machines, out of 4. I've fixed this and as I see yesterday and today, the compilation passed in the [node-daily-v18.x-staging](https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-v18.x-staging/) job. Closing the issue since it seems fixed.
