### ISSUE TITLE
Are the lint jobs actually required for "node-test-pull-request"

### ISSUE THREAD

**Issue by juanarbol** [nodejs/build#3843]
GitHub actions run the linters, normally a GH actions is triggered for each pull request. Not sure fi the CI needs to run the linters again if the GH actions already gave the results of linter.

**Comment by richardlau** [comment]
I would prefer to keep the ability to run the linters in Jenkins because it would preserve our ability to separate from GitHub (worst-case, hopefully never happens scenario).
