### ISSUE TITLE
Rebuild ubuntu2204 Docker containers

### ISSUE THREAD

**Issue by targos** [nodejs/build#3855]
Refs: https://github.com/nodejs/build/pull/3846#issuecomment-2270369654

- [x] on `test-digitalocean-ubuntu2204_docker-x64-1`
- [x] on `test-digitalocean-ubuntu2204_docker-x64-2`
- [x] on `test-ibm-ubuntu2204_docker-x64-1`

**Comment by richardlau** [comment]
I'm rebuilding the containers now.

**Comment by richardlau** [comment]
Containers rebuilt and restarted.
