### ISSUE TITLE
Accept terms of use for linuxOne machines

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#386]
My contact has said:

the cloud team responded that you and people in the community should just read the public T&Cs 
https://developer.ibm.com/linuxone/terms-of-use/ and send an email back to us acknowledging their agreement.

One note is that the 90 day limit does not apply to us and the machines will remain as they are ongoing.

I'm thinking that the best people to do this on behalf of the committee are myself, Rodd and Johan.

@rvagg, @jbergstroem could you review and forward your agreement to me and I'll forward on with my agreement. If you have any questions/concerns about the agreement let me know.

**Comment by jbergstroem** [comment]
@mhdawson: Suggesting we add @joaocgreis as well since he is in our infra team (meaning he has access to it)?

**Comment by mhdawson** [comment]
@jbergstroem.  Makes sense.  We could add everybody who has access but I thought that would be unmanageable so was thinking it would be reasonable if we just had a specific subset.  Having said that adding  @joacgreis as the infra team makes sense to me.

**Comment by joaocgreis** [comment]
@mhdawson I won't be able to attend the WG meeting today, let me know if you need something else from me. Thanks!

**Comment by mhdawson** [comment]
@joaocgreis got your email, it looks good to me.

**Comment by jbergstroem** [comment]
I've sent my email as well.

**Comment by mhdawson** [comment]
Received/forwarded for everybody now.
