### ISSUE TITLE
Add Jenkins Plugin for Orka 

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3860]
As agreed on the new [Orka](https://github.com/nodejs/build/issues/3686#issuecomment-2278119351) strategy we want to use Ephemeral Agents. In order to do that Jenkins will communicate directly with the Orka Cluster using [this plugin](https://plugins.jenkins.io/macstadium-orka/).

I want to ask for an approval to add this plugin in both jenkins instances. This won't cost any downtime as the current Orka won't be affected just the new Orka cluster.

cc: @ryanaslett @nodejs/build-infra

**Comment by targos** [comment]
sgtm

**Comment by richardlau** [comment]
+1

**Comment by UlisesGascon** [comment]
The plugins were added, so I close this issue.
