### ISSUE TITLE
Insufficient disk space to compile on Windows

### ISSUE THREAD

**Issue by targos** [nodejs/build#3867]
Examples:
- https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/57654/
- https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/57657/
- https://ci.nodejs.org/job/node-compile-windows/57665/nodes=win-vs2022-arm64/

@StefanStojanovic

**Comment by StefanStojanovic** [comment]
Thanks for the heads up. We have [git-clean-windows](https://ci.nodejs.org/view/housekeeping/job/git-clean-windows/) to take care of this and it runs weekly. It is usually good at keeping this running smoothly but has a weak spot. It only processes jobs starting with `node-` so it doesn't catch the jobs we create (eg. I prefix mine with `mefi-`). I'll create an issue for myself to investigate that job and find a way to enable it to catch a broader range of jobs.

Back to this issue - I went through all of the `Win2022-VS2022` machines and cleaned left over jobs manually, so I'm closing this issue now.
