### ISSUE TITLE
Proposal: Drop support for MacOS prior to 13

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/build#3876]
As discussed in [#3874](https://github.com/nodejs/build/pull/3874) (thanks @targos), it seems like we can rethink our strategy on supporting legacy versions of macOS.

**Current Situation:**
In Node:
- Node 18 is tested on macOS 10.15, but since the change in the signing process, the signature is done on macOS 11.
- Node 20 is tested and released on macOS 11.
- Node 22 is tested and released on macOS 11.

**Context:**
- Both macOS 10.15 and macOS 11 are EOL ([end of life dates](https://endoflife.date/macos)):
  - macOS 10.15 reached EOL on 12 Sep 2022.
  - macOS 11 reached EOL on 26 Sep 2023.
- Homebrew no longer supports these versions, which means VM image building takes long hours, as we need to build all the OS dependencies from source, resulting in many errors.
- Orka does not support macOS 11 ARM ([related issue](https://github.com/nodejs/build/issues/3686#issuecomment-2313708231)).
- Not migrating MacOS 10.15 and 11 will save us a lot of time

**Proposal:**

cc: @nodejs/build, do you agree on dropping support for macOS 10.15 and 11? We propose using macOS 13 as the minimum version for Node 18 to Node 23.

Obviously, we will implement this deprecation progressively as part of the [issue #3686](https://github.com/nodejs/build/issues/3686) plan to avoid disruptions.

**Comment by targos** [comment]
I am obviously in favor.
The `-mmacosx-version-min` flag should still make the builds compatible with the older versions.

https://github.com/nodejs/node/blob/4f14eb15454b9f6ae7f0145947debd2c79a2a84f/common.gypi#L630C12-L630C36

**Comment by mhdawson** [comment]
@targos thanks that answers the question I was just about to ask. As long as the configuration maintains the same minimum osx version (which you confirmed it does) I'm +1 as well.

**Comment by sxa** [comment]
SGTM on the basis of continuing to use the `-mmacosx-version-min` flag to target the same as we do already. So this will become a policy of not actively testing on out-of-support versions of macos as opposed to removing the ability to run on them 👍🏻 I can't see any issue there.

**Comment by UlisesGascon** [comment]
Thanks for all the feedback :heart: !

Seems like we are very align on this, so I will close it and move on to MacOS 13. I will include `-mmacosx-version-min` in the pending tasks for https://github.com/nodejs/build/issues/3686 so we keep it in the radar.
