### ISSUE TITLE
Request access to ubuntu2204-armv7l box

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#3895]
I'm in the process of releasing the new libuv version and while running the `libuv-in-node` CI I run into issues with some `preadv` tests that might be relevant to the release: https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/54701/#showFailuresLink. Would love to have access to one of those boxes to debug the issue. Thanks

**Comment by UlisesGascon** [comment]
+1 from me. cc: @nodejs/build

**Comment by mhdawson** [comment]
+1 from  me

**Comment by mhdawson** [comment]
@ryanaslett is getting @santigimeno's key onto the box so he can access something you could help with?

**Comment by richardlau** [comment]
I'll get this set up.

**Comment by santigimeno** [comment]
Thanks! I'm in

**Comment by santigimeno** [comment]
I can't find any text editors in the containers nor I cannot install anything. Can you help me with that? Thanks

**Comment by richardlau** [comment]
The files in `/home/iojs` in the container are mounted from `/home/iojs/test-equinix-ubuntu2204_container-armv7l-1/`.

ssh into the host as the iojs user:
```
ssh -tt root@145.40.81.219 sudo -u iojs bash
```

and once logged in,
```
cd /home/iojs/test-equinix-ubuntu2204_container-armv7l-1/build/workspace/node-test-commit-arm/
```

Please only edit files and don't run any compilation in the host outside of the container. (FWIW Also note that the host is arm64 (not armv7) but that should be an issue for editing text.)

**Comment by santigimeno** [comment]
@richardlau how feasible would be having some debugging tools installed in the container. I'm thinking `gdb`, `strace`. Thanks

**Comment by richardlau** [comment]
> @richardlau how feasible would be having some debugging tools installed in the container. I'm thinking `gdb`, `strace`. Thanks

@santigimeno I've installed `gdb` and `strace` into the container.

**Comment by santigimeno** [comment]
Thanks

**Comment by santigimeno** [comment]
@richardlau I won't be needing this anymore. Thanks!

**Comment by richardlau** [comment]
I've removed @santigimeno 's key from the host machine and reset the container.
