### ISSUE TITLE
Optimize disk usage by gzipping on disk build logs

### ISSUE THREAD

**Issue by ryanaslett** [nodejs/build#3899]
Jenkins supports displaying gzipped build logs, and the majority of our disk usage is the log files from existing builds.

Proposal: add a cronjob to gzip any on disk log file older than 7 days (since it adds a small amount of review overhead to decompress the log)

`cd /var/lib/jenkins/jobs; find * -name "log" -mtime +7|xargs gzip -9v '{}'`

That will probably free up a *lot* of space.

**Comment by ryanaslett** [comment]
Also, I tested this to verify it works:
![image](https://github.com/user-attachments/assets/bd977045-4187-4482-9a80-fbf147b26052)

and https://ci.nodejs.org/job/node-test-commit-osx-ulises-macstadium-test/nodes=osx13-x64/lastBuild/console is the console log of the gzipped file.

**Comment by richardlau** [comment]
+1.

Anecdotally I think the logs for [post-build-status-update](https://ci.nodejs.org/job/post-build-status-update/) are already gzipped on the disk, and Jenkins can't display them, e.g. https://ci.nodejs.org/job/post-build-status-update/2414373/execution/node/16/log/
```
java.io.FileNotFoundException: /var/lib/jenkins/jobs/post-build-status-update/builds/2414373/log (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
...
```

**Comment by ryanaslett** [comment]
Hmm. interesting. jenkins doesnt seem to think those are gzipped. I wonder if its the difference between a pipeline job and a regular one.

**Comment by richardlau** [comment]
Yes, we don't have many pipeline jobs because there was pushback years ago to the BlueOcean interface for viewing pipeline steps. So most jobs are a combination of matrix + multijob. However the [multijob plugin is deprecated](https://github.com/nodejs/build/issues/3181) so there's a risk that will stop working in the future and we'd be forced to migrate (FWIW losing the "resume CI" functionality that we get from that plugin that collaborators are relying on to get CI's passing).

**Comment by ryanaslett** [comment]
Hmm. I see. 

So when we *eventually* need to move off the multijob plugin, we may find ourselves needing to use pipelines to replace it, and may find ourselves needing more disk space at that time.

**Comment by richardlau** [comment]
I guess https://issues.jenkins.io/browse/JENKINS-54678 (found from reading through Adoptium's experience https://github.com/eclipse-openj9/openj9/issues/3573). Unfortunately it sounds like Compress Build Log is unmaintained (up for adoption).

**Comment by ryanaslett** [comment]
Interesting that they found that the pipeline logs work by symlinking the log.gz to a bare log filename.

I tested it and it works for the main console log, but still fails on the individual log portions (probably something to do with the log-index and jenkins pipeline log viewer not expecting gzipped log files.

So.. final proposed cron change is stick with just the node dirs:

`find . -type f -name "log" -path "./node*/*" -mtime +7|xargs gzip -9v '{}'`

I'd like to do this soon as the ci server is basically full even after cleansing

**Comment by mhdawson** [comment]
+1 on gzipping on the understanding they are still viewable (which is my understanding based on the discussion in the thread).

**Comment by ryanaslett** [comment]
I didnt see anything for managing ci.nodejs.org via ansible, so I just opened a PR to house the script and i'll manually add the crontab when this pr is accepted: https://github.com/nodejs/build/pull/3902

**Comment by richardlau** [comment]
> I didnt see anything for managing ci.nodejs.org via ansible, so I just opened a PR to house the script and i'll manually add the crontab when this pr is accepted: #3902

We have [playbooks](https://github.com/nodejs/build/tree/main/ansible/playbooks/jenkins/host) but I don't think they do much set up.

**Comment by ryanaslett** [comment]
Thanks. I had to make a tweak to the script after some changes (the paths in the find didnt work how I had remembered) https://github.com/nodejs/build/pull/3905 

This is running now on ci, and we're already down to 77% disk usage and its still running.

**Comment by ryanaslett** [comment]
That bought us a lot of room. Finished and we're down to 58% utilized. The cron is setup and will run at 5am daily.
