### ISSUE TITLE
Enable CSRF protection in jenkins

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#390]
Email from upstream this morning that recommended that all sites enable CSRF: https://wiki.jenkins-ci.org/display/JENKINS/CSRF+Protection. Since we have other default auth mechanisms in place I think we're in a pretty good position, but it wouldn't hurt. Since it requires some measure because we're [running nginx](https://issues.jenkins-ci.org/browse/JENKINS-23793), I'll just add this issue as a reminder.

**Comment by ChALkeR** [comment]
Wait, what? Do I get this right that we got CSRF protection disabled?

**Comment by jbergstroem** [comment]
The setting got introduced somewhere in the 1.x series and defaulted to off. I'm currently in transit but will be back tonight; will likely test and implement it then.

**Comment by jbergstroem** [comment]
This is now enabled on both deploys. It might end up being problematic for rest access (upstream says). Ping @Starefossen, @nodejs/build. If you find any issues, let me know.

**Comment by jbergstroem** [comment]
Closing since it's resolved, but post updates here should issues arise.

**Comment by evanlucas** [comment]
Just an FYI, my cli tool to fetch/submit jenkins jobs for our CI (https://github.com/evanlucas/nodejs-ci-ctl) is still working properly even with this enabled.

**Comment by ChALkeR** [comment]
@jbergstroem 
> The setting got introduced somewhere in the 1.x series and defaulted to off.

Sigh. Jenkins…

Good that it's enabled now, thanks!

**Comment by ChALkeR** [comment]
@evanlucas What API does it use?

**Comment by evanlucas** [comment]
Just the Jenkins REST API
