### ISSUE TITLE
Request access to win11 compiled by VS2022

### ISSUE THREAD

**Issue by jakecastelli** [nodejs/build#3901]
Jason @jazelly and myself are working on this PR https://github.com/nodejs/node/pull/54653, the test works on Mac and Linux but not windows. Jason has a windows PC and it passed locally but consistently fail on CI due to memory access violation.

Would be great to have access to the "win11 compiled by VS2022" machine to debug.

**Comment by mhdawson** [comment]
+1 from me

**Comment by UlisesGascon** [comment]
+1 from me.

**Comment by jakecastelli** [comment]
Thanks @StefanStojanovic! My email address is `jake.yuesong@gmail.com`, it will be ok to send credentials either to me or Jason (yes, his email is the same in his GH profile) 👍

**Comment by StefanStojanovic** [comment]
Hey @jakecastelli, I've created the machine. I just need to run a setup on it, and then I'll send you the credentials.

**Comment by StefanStojanovic** [comment]
@jakecastelli I've sent the credentials in an email.

**Comment by jakecastelli** [comment]
Hi @StefanStojanovic we have finished using the windows machine to debug and Jason had successfully found and resolved the issue. 🙏 Please feel free to delete the VM when you have time, thanks again everyone!
