### ISSUE TITLE
git-rebase job is failing consistently

### ISSUE THREAD

**Issue by cjihrig** [nodejs/build#3910]
Looking at https://ci.nodejs.org/job/node-test-pull-request/, it appears that all of the runs have been failing. I believe the cause is that the git-rebase job is consistently failing: https://ci.nodejs.org/job/git-rebase/113464/console

**Comment by targos** [comment]
I put [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/computer/test%2Dmnx%2Dubuntu2204%2Dx64%2D1/) offline to work on it.
