### ISSUE TITLE
Update OS on `ci-release`

### ISSUE THREAD

**Issue by targos** [nodejs/build#3922]
It's still running on Ubuntu 20.04, which will be EoL in 6 months. Jenkins is warning us.

**Comment by richardlau** [comment]
FWIW we have to rebuild this machine in another data center by March next year (i.e. before Ubuntu 20.04 goes End-of-Life in April 2025): https://github.com/nodejs/build/issues/3852

**Comment by richardlau** [comment]
Some more history -- the reason this is running Ubuntu 20.04 rather than 22.04 is that at the time I did the upgrade (from 18.04) the machine didn't have enough disk space to upgrade from 20.04 to 22.04: https://github.com/nodejs/build/issues/2984#issuecomment-1228714422

**Comment by targos** [comment]
https://github.com/nodejs/build/issues/3852
