### ISSUE TITLE
Request access to ubuntu2204-armv7l box again

### ISSUE THREAD

**Issue by santigimeno** [nodejs/build#3924]
Sorry for opening this request again. Still we're having issues when trying to upgrade [libuv](https://github.com/nodejs/node/pull/55114) https://ci.nodejs.org/job/node-test-binary-armv7l/14013/#showFailuresLink. Those failing `compile-cache` are failing consistently in there and would love to take a look. Thanks!

**Comment by richardlau** [comment]
@santigimeno Done. Same details as per https://github.com/nodejs/build/issues/3895.

**Comment by santigimeno** [comment]
@richardlau hopefully this is finally done. Thanks!

**Comment by richardlau** [comment]
Keys removed from the host.
