### ISSUE TITLE
Update Jenkins LTS 2.479.1

### ISSUE THREAD

**Issue by targos** [nodejs/build#3946]
https://www.jenkins.io/doc/upgrade-guide/2.479/

This update requires Java 17 on all nodes. Unfortunately e still have Java 11 on some CI hosts.

Also:

> The minimum required Remoting version has been updated to [3107.v665000b_51092](https://github.com/jenkinsci/remoting/releases/tag/3107.v665000b_51092).

**Comment by richardlau** [comment]
Refs: https://github.com/nodejs/build/issues/3916
for the platforms still running agents with Java 11.

**Comment by targos** [comment]
I did the update on ci-release.
As expected, `release-osuosl-centos7-arm64-1` is now disconnected.
`release-macstadium-macos11.0-arm64-1` too (it has a too old remoting version), but I think it's also unused since we moved to the new Orka cluster.

**Comment by targos** [comment]
I just updated https://ci.nodejs.org.
