### ISSUE TITLE
Talk about the Build WG at Interactive

### ISSUE THREAD

**Issue by mikeal** [nodejs/build#395]
Heya,

We had a great talk last month about the Benchmarking WG and it made me realize that we need more talks about the work happening in all the working groups.

Please submit talks! https://www.conferenceabstracts.com/cfp2/login.asp?EventKey=VSIHQOEU

**Comment by TheAlphaNerd** [comment]
I'll likely be submitting a talk about the work being done on smoke-testing + citgm.

@mikeal is there a preference for different material at each event, or is there a want to have repeated material to give attendees at both locations an opportunity to see the content?

**Comment by mhdawson** [comment]
My take was doing this in multiple venues would make sense as even in cases were its some of the same people there will be updates of progress since the last time.  

Not directly related to this issue but as a FYI, We have submitted WG talks to node summit and plan to submit to the Node interactive events (just need the final ok) to cover the following:
  Benchmarking 
  Post-Mortem
  
Does make me think I should see if @stefanmb and Ian Halliday  who volunteered to move module API work forward  can co-submit one for the API WG.

**Comment by mhdawson** [comment]
@jbergstroem, @rvagg , @orangemocha , @joaocgreis are you interested in submitting a talk on this front.  I'm happy to do so but think you 4 are more active so if possible would make sense for you to do it.

**Comment by jbergstroem** [comment]
@mhdawson bad timing for me; count me out.

**Comment by rvagg** [comment]
@joaocgreis & @orangemocha are the other top candidates for this, I'd like to hear if either of them would like to do this first?

**Comment by jbergstroem** [comment]
(I'm happy to review/prepare slides pre if needed though)

**Comment by joaocgreis** [comment]
It's not possible for me. Thanks!

**Comment by orangemocha** [comment]
I can't commit to it either, sorry.

**Comment by TheAlphaNerd** [comment]
I'm open to talk about the smoke testing and ci work I've been doing. Not
exactly the same as some of the deeper build infra, but thought I'd throw
that out there

**Comment by mhdawson** [comment]
Call for paper closes May 13 as an FYI.  @jbergstroem  in terms of timing are both the EU and US times a no go ? It does not necessarily need to be the same person which presents at each of the conferences.

**Comment by jbergstroem** [comment]
@mhdawson unfortunately, yes. I will be working from Latin America for a while and need to be on location.

**Comment by mhdawson** [comment]
@rvagg just a reminder that you only have a few days left if you want to submit a proposal

**Comment by rvagg** [comment]
over to you @mhdawson, looks like everyone else is out at this stage

**Comment by mhdawson** [comment]
Ok. Do we as a team think its a good idea ?  If so I assume people are willing to collaborate to put together the deck.  I'm ok with delivering but want it to reflect this groups message.

**Comment by rvagg** [comment]
Yes, it's a good idea, whenever I've presented information about what we do either in online form or spoken form, people love it. There's some fascinating nerdy goodness about the work we do here and many people find it exciting to be able to look inside. We should be able to collaborate.

**Comment by jbergstroem** [comment]
Count me in, as long as we're doing it in comic sans or times new roman 🌈

**Comment by mhdawson** [comment]
Ok sounds good. How about this for an abstract (please suggest revisions/updates) 

Keeping the Node.js community insfrastructure humming - 
an update from the build Workgroup

The build workgroup (https://github.com/nodejs/build/) has the
mission to provide Node.js Foundation projects with solid computing
infrastructure covering a wide range of platforms and different
software stacks.  In this talk we will introduce the
general philosophy of how infrastructure is sourced, the
overall picture of the infrastructure, some of the interesting
interactions and,  just as important, how you might get involved.
Come learn about the infrastructure that powers
the delivery of Node.js !


Can I also include you two (Rodd, Johan) as secondary presenters to reflect
your contribution to the deck and just in case you do make 
it to the conference ?  Also I think I should likely add anybody
else who might make it but cannot commit just in case.

**Comment by rvagg** [comment]
@mhdawson sounds good, feel free to include me, I may be there if we do a collaborator summit thingo too. In the abstract you could highlight more how we have built this massive CI infrastructure entirely through donations from companies and individuals, that's a great story IMO.

**Comment by jbergstroem** [comment]
Get me in there too. Again, unlikely I will make it.

I'm with @rvagg; please put a strong emphasis on sponsors/donators; ideally I'd like a slide or two showcasing the visibility amongst the community you can grow by chipping in. A solid and diversified infrastructure is a key part of making Node.js reliable on all platforms.

**Comment by mhdawson** [comment]
Ok, tweaked as follows to emphasize those points:

The build workgroup (https://github.com/nodejs/build/) has the
mission to provide Node.js Foundation projects with solid computing
infrastructure covering a wide range of platforms and different
software stacks. In this talk we will introduce the
general philosophy of how infrastructure is sourced, which has
a strong focus on community donations, the
overall picture of the substantial infrastructure we've manged
to build using this approach, some of the interesting
interactions and, just as important, how you might get involved.
Come learn about the infrastructure that powers
the delivery of Node.js !

**Comment by mhdawson** [comment]
Will submit, today so we don't miss the deadline, I can easily update the abstract at least until the end of Friday when the CFP closes.

**Comment by mhdawson** [comment]
@Rodd, @jbergstroem 
You two should receive emails asking you to complete your speaker profiles

**Comment by mhdawson** [comment]
Submissions were made to Node interactive EU and US so closing this issue.

**Comment by mhdawson** [comment]
Submissions were made to node interactive EU and US so closing this issue
