### ISSUE TITLE
node-test-commit is broken

### ISSUE THREAD

**Issue by aduh95** [nodejs/build#3959]
It looks like all jobs are failing is less than a second, starting with https://ci.nodejs.org/job/node-test-commit/75761/

```
00:00:00.379 Honoring refspec on initial clone
00:00:00.423 Cloning repository git@github.com:nodejs/node.git
00:00:00.423  > git init /home/iojs/build/workspace/node-test-commit # timeout=10
00:00:00.427 ERROR: Error cloning remote repo 'origin'
00:00:00.427 hudson.plugins.git.GitException: Could not init /home/iojs/build/workspace/node-test-commit
```

**Comment by targos** [comment]
/cc @nodejs/build-infra

I'm in a meeting the whole day and cannot investigate this.

**Comment by mhdawson** [comment]
@ryanaslett is this something you could take a look at?

**Comment by ryanaslett** [comment]
I did some preliminary investigation into this and it appears as though all three of our jenkins workspace machines can no longer connect to github.

All the clone urls are git@github.com, and result in 

```git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

So either the url's changed in the build and they used to be https urls, or something changed on the workspace machines to remove the private keys.

**Comment by mhdawson** [comment]
Earlier issue where we had trouble with connectivity from jenkins to GitHub, but this looks different- https://github.com/nodejs/build/issues/3254

**Comment by mhdawson** [comment]
Being looking at the keys/steup with Ryan to try to understand what might have changed, have followed some threads but no answer yet.

**Comment by mhdawson** [comment]
Looks like packages were updated yesterday (by looking at /var/log/dpkg.log) on `test-ibm-ubuntu2204-x64-3` were some of the failures were being seen. 

Possible that it ran/failed so fast that all jobs were running failing there.

Have restarted the jenkins agent and job seems to be running now.  Looks ike it was just that that `git` just failing to run from java running the agent after the system updates like was the case in the issue mentioned earlier

**Comment by mhdawson** [comment]
This job seems to be running ok - https://ci.nodejs.org/job/node-test-commit/75781/

Will leave this open until we confirm that we see jobs running ok across the different workspace machines.

**Comment by ljharb** [comment]
still seeing the same issue on https://ci.nodejs.org/job/node-test-pull-request/63546/

**Comment by aduh95** [comment]
The issue for `node-test-commit` is resolved, but there are still other jobs impacted

**Comment by targos** [comment]
I updated and rebooted all 4 [ubuntu2204](https://ci.nodejs.org/label/ubuntu2204-64/) hosts

**Comment by aduh95** [comment]
That seems to have fixed it, https://ci.nodejs.org/job/node-test-pull-request/63552/ doesn’t have the issue. Closing now, thanks everyone.

**Comment by ljharb** [comment]
fwiw, https://ci.nodejs.org/job/node-test-pull-request/63557/ still has the same issue.

**Comment by aduh95** [comment]
> fwiw, https://ci.nodejs.org/job/node-test-pull-request/63557/ still has the same issue.

No it does not

**Comment by ljharb** [comment]
hmm - maybe i linked to the wrong thing. https://ci.nodejs.org/job/node-test-commit/75799/console ?

**Comment by aduh95** [comment]
I don't see any anywhere in those logs anything related to a connection problem with github.com, AFAICT it's working fine

**Comment by ljharb** [comment]
alrighty, i'll dig into it, maybe it's an actual failure. sorry for the noise :-)
