### ISSUE TITLE
Compilation broken on Windows with VS 17.12

### ISSUE THREAD

**Issue by StefanStojanovic** [nodejs/build#3963]
VS 2022 v17.12 (released Nov 12) cannot compile Node.js with MSVC. I'm working on making a simple reproduceable example to open an issue in `developercommunity.visualstudio.com`.

cc @nodejs/platform-windows

Refs: https://github.com/nodejs/build/issues/3739

**Comment by StefanStojanovic** [comment]
Here is the [developer community issue](https://developercommunity.visualstudio.com/t/Regression-in-MSVC-v1712:-Compilation-E/10794016).

**Comment by Flarna** [comment]
Received 17.12.2 today and it seems problem is fixed there.

**Comment by targos** [comment]
https://github.com/nodejs/node/pull/56151 Landed so I've re-enabled the Windows workflows.

**Comment by StefanStojanovic** [comment]
I plan to unpin Visual Studio version in our CI machines and will close this issue once that is done.

**Comment by StefanStojanovic** [comment]
I've updated VS versions to the latest on all test and release CI machines. Will follow it for a few days and close if all is OK.

**Comment by StefanStojanovic** [comment]
Closing since all is alright in the CI.
