### ISSUE TITLE
Agent `release-rackspace-win2019_vs2019-x64-1` is offline

### ISSUE THREAD

**Issue by targos** [nodejs/build#3970]
https://ci-release.nodejs.org/computer/release-rackspace-win2019_vs2019-x64-1/

Blocking https://ci-release.nodejs.org/job/windows-update-reboot/

/cc @StefanStojanovic

**Comment by StefanStojanovic** [comment]
Thanks for letting me know. I fixed it by resetting Jenkins on the machine. Closing this now.
