### ISSUE TITLE
Would it be possible to utilize travis (or simlar service) for more continuous parts of our CI?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#398]
A tool to validate our commits has been created by @evanlucas 

https://github.com/evanlucas/core-validate-commit

It would be VERY straight forward to get this running on travis on every PR. 

At the very least it would be nice to have some sort of environment with node that we could use for CI jobs without having to do any compilation.

**Comment by jbergstroem** [comment]
My idea is to get this as part of the github bot and have that run on all commits to all PR. Travis is great but we have the horsepower to pull this of with our own infrastructure and I kind of like the idea of having that independence. 

Btw, all for increasing checks on all commits. I think linting and commit message checks should be done on a per-commit basis for all pr's; CI results would come in second.

**Comment by jbergstroem** [comment]
Just an update here: We have a job that we will be integrating somehow shortly: https://ci.nodejs.org/job/node-test-commitmsg/
