### ISSUE TITLE
Picking the right CI tooling

### ISSUE THREAD

**Issue by andrewlow** [nodejs/build#4]
Today Node is built using Jenkins. 

Given the scale of what we want to do with Node, should we take this opportunity to consider a new CI tool?

If yes, we should generate a list of candidates and discuss.

**Comment by bnoordhuis** [comment]
Is there still anything actionable here?  If not, I move to close.

I know @piscisaureus has opinions on how to make interaction with the CI more effective and I personally would like to see us start using something like https://github.com/graydon/bors but perhaps that's something for a new issue.

**Comment by objarni** [comment]
Pardon my ignorance, but what about Travis CI...? I thought node.js was an open source project?

**Comment by bnoordhuis** [comment]
@objarni Its matrix of architecture/platform/distro/etc. is not good enough for our purposes.  It's also very flaky for anything that's timing sensitive or I/O-heavy.  Libuv used it for a while and it was terrible.

I'm going to close the issue, I think it ran its course.  Last real action was in November.

**Comment by objarni** [comment]
OK, thank you.

**Comment by Fishrock123** [comment]
Jenkins. (See https://jenkins-iojs.nodesource.com/)

That being said Jenkins is a consistent pain and I definitely wouldn't mind making a Node CI some day.

**Comment by cjihrig** [comment]
@Fishrock123 it's still in the very early stages, but @lloydbenson has started working on this - https://github.com/fishin/ficion.

**Comment by Fishrock123** [comment]
Oooh, sweet, I'll check out the code later. :D
