### ISSUE TITLE
integrating npm tests into CI

### ISSUE THREAD

**Issue by othiym23** [nodejs/build#40]
I've been [doing some work](https://github.com/npm/node/commit/97ab327a243f353b2e95ae490e088b0ba9357ebf) to make it so npm tests can be run as part of the overall build process for Node / io.js, preferably without too many side effects. It's kinda tough to mirror the behavior of a CI environment, so it would be great if somebody could either point me at a Vagrant image / Docker container, or get me access to a subset of the build environments so I have something to hammer on while I'm getting things sorted out.

also a windows ci environment would be great thanks

**Comment by rmg** [comment]
@othiym23 the docker images being used for CI are in https://github.com/iojs/build-containers and _think_ you should be able to just pull them down and run them against any iojs checkout.

**Comment by rmg** [comment]
As in `docker run -itv /local/path/to/iojs:/opt/iojs --rm iojs/build:iojs-ubuntu-trusty` where /local/path/to/iojs is the iojs checkout you're modifying to run npm's tests as part of the core tests.

**Comment by othiym23** [comment]
Thanks, @rmg! Consider this a tracking issue for me to keep everyone up to date on my progress getting npm tests working properly with CI.

**Comment by rmg** [comment]
Happy to help :-)

**Comment by rvagg** [comment]
@othiym23 how about this instead: let me give you access to the io.js Jenkins and you can trigger builds across all the platforms by pointing it to your local (or npm) fork of io.js, then you can tinker all you want to get them right prior to a PR to io.js. I'm just about to add a bunch of new collaborators to Jenkins so I'll add you to the list while I'm at it.

**Comment by othiym23** [comment]
@rvagg Sounds good. Right now I'm working on getting all of npm's tests passing on Travis under iojs and node 0.12; it turns out that there may be a bug in the new Keep-Alive support on `http.Agent`. Once I can get npm's tests all-green in that environment, I'll start working on getting the builds right in io.js's CI environment. Let me know if / where I need to send you an SSH key.

**Comment by jbergstroem** [comment]
This nowadays lives in the [citgm repo](http://github.com/nodejs/citgm/).
