### ISSUE TITLE
MySQL?

### ISSUE THREAD

**Issue by mikeal** [nodejs/build#402]
Heya,

I'm looking at using a modified Ghost instance for the foundation micro-site but I need a MySQL database to connect it to (default is sqlite but I'm pretty sure that's a no-go for our deploy setup).

What would it take to stand something like this up?

**Comment by ChALkeR** [comment]
@mikeal Btw, is SQLite really a no-go? It's a mostly static site as I understand it, and proper server-side caching should reduce the load on the database to an absolute minimum. Or am I missing anything?

**Comment by jbergstroem** [comment]
Ghost seems to support SQLite out of the box!

**Comment by maclover7** [comment]
Is this okay to close?

**Comment by refack** [comment]
Since then there was talk about either using hosted Ghost or even WP ( :shudder: ) - https://github.com/nodejs/nodejs.org/issues/1349
