### ISSUE TITLE
Remove ubuntu15 slave?

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#410]
I'd like to kill the ubuntu15 slave seeing how ubuntu1604 (love the naming) is out. We have a ubuntu16 bot as part of our CI (#408) and I'd like to add a 32-bit slave as well. Should rule out the need for testing against ubuntu15. Thoughts?

**Comment by bnoordhuis** [comment]
Sounds reasonable to me.

**Comment by rvagg** [comment]
kill

**Comment by mhdawson** [comment]
Sounds reasonable to me too.

**Comment by jbergstroem** [comment]
Gone!

**Comment by jbergstroem** [comment]
Oops; perhaps a bit premature. It's gone from jenkins, but we still need this to be merged: #408.

**Comment by jbergstroem** [comment]
Just merged the PR but forgot to reference this. Closing.
