### ISSUE TITLE
Add v8 test job to Node.js tab in CI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#413]
Any objections to adding https://ci.nodejs.org/view/All/job/node-test-commit-v8-linux/ to the node.js tab ?

@jbergstroem I think you regrouped them into the tabs so would like your input

**Comment by jbergstroem** [comment]
No opinion really; feel free.

The main thing I wanted to do with the 'default' view was to keep it as small as relevant for most people as possible.

**Comment by mhdawson** [comment]
Ok added, thanks.
