### ISSUE TITLE
All hosts need ::1 to point to localhost

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#415]
See https://github.com/nodejs/node/pull/6654#issuecomment-218395029 for more info. Thinking a combo of ansible's `lineinfile` and `/etc/hosts`.

**Comment by Fishrock123** [comment]
@jbergstroem Still an issue?

**Comment by jbergstroem** [comment]
@Fishrock123 yes, will likely persist until we've done something about it through ansible.

**Comment by jbergstroem** [comment]
Would lineinfile /etc/hosts `::1 localhost.localdomain localhost`  ish be enough?

**Comment by Trott** [comment]
@jbergstroem I think so-ish.

**Comment by jbergstroem** [comment]
I've added `::1 localhost.localdomain localhost` to all /etc/hosts test machines that lives at softlayer.

**Comment by Trott** [comment]
I believe this can be closed. If I'm wrong, by all means, re-open.
