### ISSUE TITLE
Retire Fedora21?

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#416]
Fedora 21 [EOL'ed last year](https://fedoraproject.org/wiki/End_of_life). How about we cut it from the build farm? I know there's no harm in keeping it, but that strategy could have developers spend extra time fixing bugs for platforms that upstream dropped support for (ok, lets just pretend that OS X isn't in this discussion).

**Comment by bnoordhuis** [comment]
Sounds reasonable.  I did wonder why it was still around.

**Comment by ChALkeR** [comment]
+1 for dropping support for anything that doesn't get security updates anymore.

**Comment by jbergstroem** [comment]
Anyone from the build group wants to chip in?

**Comment by rvagg** [comment]
I'm *sure* I fired off a +1, but can't find it, this is the second issue where this has happened in nodejs/build recently so I'm either having mental or technical problems.

+1 from me, we probably need to make an official policy of killing off any Linux distro that has its upstream support dropped so we don't even need to ask these questions.

**Comment by jbergstroem** [comment]
@rvagg fwiw I've had cases where I swear I posted a comment but later finding that it wasn't there.

**Comment by ChALkeR** [comment]
@jbergstroem @rvagg Btw, I remember having similar issues about two weeks ago, and those turned out to be actually GitHub lags — https://twitter.com/githubstatus/status/724933464273903622.

**Comment by jbergstroem** [comment]
@rvagg I believe we need a policy for all platforms/versions. I think as soon as we land in a new OS X environment we should define what we will support (which hopefully equates to what we test and have tested for a while).

I will retire this today and open a new issue about formal support.

**Comment by jbergstroem** [comment]
Retired.
