### ISSUE TITLE
The error of "Syntax error: word unexpected (expecting ")") " would be found when Compiled the node.js

### ISSUE THREAD

**Issue by endyvee** [nodejs/build#418]
When compiled the nodejs for Android on Ubuntu 12.04, and the follow error information would be found, please help to resolve it, or how to fix it, thanks :)

icu_small.json: icutrim.py config: Trim down ICU to just a certain locale set, needed for node.js use.
/home/test/Downloads/node-master/out/Release/icupkg: 1: /home/test/Downloads/node-master/out/Release/icupkg: Syntax error: word unexpected (expecting ")")
FAILED: /home/test/Downloads/node-master/out/Release/icupkg -tl ../../deps/icu-small/source/data/in/icudt57l.dat /home/test/Downloads/node-master/out/Release/obj/gen/icutmp/icudt57l.dat
make[1]: *** [/home/test/Downloads/node-master/out/Release/obj/gen/icutmp/icudt57l.dat] Error 1
make[1]: Leaving directory `/home/test/Downloads/node-master/out'
make: *** [node] Error 2

**Comment by wanghaiquan** [comment]
mask

**Comment by bnoordhuis** [comment]
Can you report that over here: https://github.com/nodejs/node/issues?  This bug tracker is for CI infra and such, not for problems with building node (although I can understand why you thought that.)

I will say that Android is not a supported platform so you'll probably be asked to investigate yourself.
