### ISSUE TITLE
Request for Docs: Guide for compilation on FreeBSD

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs/build#422]
I have looked arounds the webs and this repo to find some info on how to compile node on a fresh installation of FreeBSD for dev-purposes.

Can you help out here? Also I would write a guide for it on the main repo's wiki

**Comment by bnoordhuis** [comment]
I think `./configure && make install` is all you really need to do, although most people install node from ports.

It used to be that you had to install libexecinfo first but in FreeBSD 11 it's part of the base system, I think.

**Comment by eljefedelrodeodeljefe** [comment]
Okay. I think the Vagrant image I was using ran FreeBSD 10, that would explain it. My question would aim primarily on prerequisites, which seem to be more missing in a blank box in comparison to Linux and OS X. I will dig into it through running `./configure && make install` then. Thanks!

**Comment by santigimeno** [comment]
In `FreeBSD 10` I had also to set the `CC` env variable to the desired compiler.

**Comment by jbergstroem** [comment]
@eljefedelrodeodeljefe `gmake` is the only prereq on FreeBSD 9 and up. As @santigimeno mentioned, depending on your environment you might want to pass `CC=clang CXX=clang++` if you want to choose compiler, but I recall cc/cxx symlinks to clang.
