### ISSUE TITLE
Access to AIX/Power/LinuxOne machines for IwuzHere

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#423]
I'm going to be getting Imran to help me keep the infrastructure for those platforms going.  It would make it a lot easier if I could give him access to those machines.  

He is a Node.js collaborator so under the discussion we've had for https://github.com/nodejs/build/pull/354 he'd be a candidate for "ongoing access".  Longer term I also have the goal to bring him on as a member of the build working group.

@nodejs/build what do you think ?

**Comment by bnoordhuis** [comment]
Not a build member but since Imran is already doing the AIX work for libuv, I think it makes sense.

**Comment by jbergstroem** [comment]
So what we would do here is provide him access to the nodejs_build_test key (add his gpg to the correct subfolder of secrets), right?

**Comment by mhdawson** [comment]
That's what I had in mind.

**Comment by rvagg** [comment]
Is @IwuzHere an IBM person?

**Comment by mhdawson** [comment]
Imran Iqbal, he works in my team with me here in Ottawa.

**Comment by rvagg** [comment]
great, that's easier to establish trust then, +1 from me for adding to nodejs_build_test.

**Comment by jbergstroem** [comment]
How about we make these things a bit more formal and accept through WG meetup? Suggesting for agenda.

**Comment by mhdawson** [comment]
@jbergstroem sounds good to me.

**Comment by jbergstroem** [comment]
I guess this also raises the question for onboarding. Lets have a think about a few things we should make sure every member of the build crew understands before venturing into the unknown.
