### ISSUE TITLE
Jenkins job cleanup

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#426]
In the interests of _attempting_ to trim Jenkins down a more manageable size, I'd like those of us who have admin access to Jenkins and have private jobs configured that are not for general use to please remove them if they are not required.

* @jbergstroem you have https://ci.nodejs.org/view/All/job/jbergstroem-test-commit-debug/
* @mhdawson you have two with your name on them https://ci.nodejs.org/view/All/job/mdawson-testh/ and https://ci.nodejs.org/view/All/job/mdawson-testh-mod/
* @orangemocha you have three https://ci.nodejs.org/view/All/job/orangemocha-compile-windows/, https://ci.nodejs.org/view/All/job/orangemocha-test-pull-request/ and https://ci.nodejs.org/view/All/job/orangemocha-testtest/
* @joaocgreis you have a bunch https://ci.nodejs.org/view/All/job/reis-libuv-windows/, https://ci.nodejs.org/view/All/job/reis-node-compile-windows-chakra/, https://ci.nodejs.org/view/All/job/reis-node-compile-windows-chakra-2/, https://ci.nodejs.org/view/All/job/reis-node-test-binary-windows-chakra/, https://ci.nodejs.org/view/All/job/reis-node-test-commit-windows-fanned-chakra/, https://ci.nodejs.org/view/All/job/reis-test-arm-fanned/ and https://ci.nodejs.org/view/All/job/reis-test-binary-arm/
@thealphanerd you have three but one of them is for general use, would you mind renaming `thealphanerd-smoker` to just `smoker` or something more generic? You also have https://ci.nodejs.org/view/All/job/thealphanerd-npm/ and https://ci.nodejs.org/view/All/job/thealphanerd-smoker-ppc/

You don't *have to* remove these, just do a mental audit of what you need to keep, these are not free because Jenkins has to load lots of .xml junk from disk for each of them and we're really pushing the limits of Jenkins performance with our cluster.

@jbergstroem I think we should be more aggressive with build trimming, we have nearly 500 builds in the last 30 days for node-test-commit alone. I can't find where we set this though.

**Comment by jbergstroem** [comment]
@rvagg it's part of the backup job. I can lower it to 20?

**Comment by TheAlphaNerd** [comment]
@rvagg should we take this opportunity to rename the smoker?

**Comment by joaocgreis** [comment]
Removed old jobs, now I only have 6, all work in progress. Will keep this in mind.

@jbergstroem +1 for 20.

**Comment by orangemocha** [comment]
I deleted my jobs, they were no longer useful. Thanks!

**Comment by mhdawson** [comment]
Delete the 2 with my name on them.  Had been on the edge of doing that and this was  the last push I needed.

**Comment by rvagg** [comment]
@jbergstroem 20 sounds good for now

**Comment by rvagg** [comment]
@nodejs/testing in case you weren't aware, we clean out Jenkins builds after 30 days and are now talking about going down to 20, simply because Jenkins doesn't really scale in the way we need. If you're linking to build output in issues and you think you may want to retain the output for future reference you should probably be copying and pasting directly into issues rather than relying on them being available next time you need them.

**Comment by santigimeno** [comment]
@rvagg Thanks for the heads up.

**Comment by mhdawson** [comment]
Just seeing if we can close this one out. @jbergstroem @joaocgreis do you still need the remaining ones with your names ?

**Comment by jbergstroem** [comment]
@mhdawson yes i want mine

**Comment by joaocgreis** [comment]
I still need the ones with my name as well. I'll go ahead and close, please reopen if I missed anything.
