### ISSUE TITLE
Jenkins git-rebase job not working on node-private

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#435]
@joaocgreis this one is yours to deal with I think, I'm not sure of the best path forward.

git-rebase used by the fanned jobs (Windows and ARM) is using SSH Agent for the ci@iojs.org key to auth against the binary GitHub repo, yet it's depended upon up the chain by node-test-commit-private which uses the node-private key to auth against nodejs/node-private.

So either we need to come up with one key that can access both (node-private needs to remain pretty secure), or we find a way to use both in the same job so that the node-private key can get used for reads and ci@iojs.org for writes. Thoughts?

**Comment by rvagg** [comment]
https://ci.nodejs.org/view/All/job/node-test-commit-private/79/ is an example of a (cleanly) failing build, only the Windows fanned job is in play here but this is why it fails (well, I'm not _entirely_ sure this is the reason but it seems like a fair guess).

**Comment by joaocgreis** [comment]
@rvagg I just moved @nodejs-ci to infra level, so you can use it.

**Comment by rvagg** [comment]
@joaocgreis is @nodejs-ci the one known as `ci@iojs.org` in Jenkins? GitHub says it already has access to node-private.

**Comment by rvagg** [comment]
And it fails with the same problem

**Comment by joaocgreis** [comment]
The problem was a corrupt git workspace. It's quite rare but has happened in the past. Should be fixed now.
