### ISSUE TITLE
Build WG meeting 2016-06-28

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#438]
**Meeting Time:** 8PM Tuesday June 28th UTC, or in your local timezone:
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20160628T20&p1=%3A

### Where
* Hangouts on Air, for participants: https://hangouts.google.com/hangouts/_/hoaevent/AP36tYdSla01t12wLtpS5guuUiX_l2PXwjCVvI7AZbBkTjJSRKFWnA?eid=100598160817214911030&hl=en
* Youtube stream, for viewers:http://www.youtube.com/watch?v=0yRT8h2WDJw
* Minutes document: https://docs.google.com/document/d/1RyDrB5OKXGpe5NszvKe6kbrwxKTwi_93ARye8pYI0Bs/edit?usp=sharing

### Agenda
Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* OS X buildbots/ci: call to action [https://github.com/nodejs/build/issues/367]
* rsync endpoint to mirror the releases [https://github.com/nodejs/build/issues/55]
* Run and deploy nodejs-github-bot [https://github.com/nodejs/build/issues/404]

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by orangemocha** [comment]
I am going to be on vacation from June 20th to June 30th, so I won't be able to attend this one. Perhaps @mhdawson or @jbergstroem can facilitate?

Note that the meeting is scheduled for June 28th. I posted the issue with more advance notice than usual

**Comment by mhdawson** [comment]
I'm happy to facilitate

**Comment by jbergstroem** [comment]
I'm not quite sure on my whereabouts either. Can hopefully attend but I will know next week.

**Comment by mhdawson** [comment]
Added hangouts/youtube links

**Comment by jbergstroem** [comment]
I won't make it. Sorry. I'll try to update issues tomorrow with updates.

**Comment by williamkapke** [comment]
Hey @nodejs/build - I hope everyone got a chance to review #404 for the meeting today. It is the foundation of many tasks I'm passionately wanting to pursue.

**Comment by mhdawson** [comment]
@williamkapke we are pretty small group in the WG meeting this week as quite a few people are away on vacation.  I can see the specific action you'd like is whether the build WG can include the work to manage the bots.   @jbergstroem what's your take on that based on the discussions you've had so far ? I feel like we don't want to just defer until the next meeting with William is waiting on a answer to know how to proceed.  I'm not sure when everybody is back from vacation but maybe we can try to find a time to discuss this specific issue.  I'll try to ping people next week to see if we have enough people back to find a time to set something up.

**Comment by mhdawson** [comment]
PR for meeting minutes: https://github.com/nodejs/build/pull/443

**Comment by williamkapke** [comment]
Thank you for the update @mhdawson. I am a big fan of taking _a little of something_ rather _than all of nothing_. So I'm hoping just this WG can start with:
1) decide on whether the WG feels it is within their domain (or is even interested) in taking on this responsibility
2) a run down of thoughts on the "What are the next steps needed?" section I posted here: https://github.com/nodejs/build/issues/404#issuecomment-225752703

I am, unfortunately, a 1 man effort on the org automation parts and it isn't a flashy project- so it isn't a priority for many. So, I very much appreciate the effort to move this forward.

My hope was to complete some of the org automation tasks and try to schedule some talks later this year to show them off- but I don't think that timeline will workout for that. Instead, I think I may need to try to use the time to collaborate face-to-face with anyone that will help.

I will be at CascadiaFest, Node Summit, Node Interactive EU and US + Collaborator Summits, NodeConf EU... and more if anyone is interested.

**Comment by mhdawson** [comment]
Minutes landed here: https://github.com/nodejs/build/pull/443

**Comment by mhdawson** [comment]
@williamkapke have talked to @jbergstroem and he had a few ideas to pursue before getting back to you, don't think it will be too much longer.

**Comment by williamkapke** [comment]
@mhdawson Thank you for the update!

**Comment by jbergstroem** [comment]
The plan is to get @phillipj on board and have him set it up!

**Comment by mhdawson** [comment]
Ok I think I can close this now.
