### ISSUE TITLE
ARMv8 binaries too new for some legitimate targets

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#439]
We're building ARMv8 binaries on Ubuntu 14.04 which has libc 2.19 but libc added ARMv8 support in 2.17 (see _Version history_ table on [this page](https://en.wikipedia.org/wiki/GNU_C_Library) and bookmark it, it's super helpful).

I received an email about our binaries not working for someone using 2.17 and I enquired about their distro. It seems that building embedded distros using [yocto](https://www.yoctoproject.org/) is something that people do and they end up with an older libc when doing so. e.g. see [this from Linaro](https://wiki.linaro.org/HowTo/ARMv8/OpenEmbedded) on how to put together a rootfs for an embedded system.

I'm not sure what to do with this information unfortunately. The boxes we build on, that ARM donated, are pre-release X-Gene's and come with Ubuntu 14.04 and I don't dare change anything about them because I _hate_ dealing with the serial console garbage. Perhaps there's a way to run LXC or Docker images on ARMv8 and load something like this?

We also have the Odroid C2 boxes now, care of miniNodes, they're much lower power and come with a custom Ubuntu 16.04, so that's even further from ideal but maybe it more easily enables some creative container solution.

I don't believe this is a priority to solve yet as I don't believe we have enough information on how common this might be or whether the problem will disappear soon enough when Yocto (or whatever else folks use) updates. It's something for us to investigate however we can, though, because I don't want to be removing a chunk of embedded devs out of Node because their natural toolchains aren't supported by our builds.

/cc @nodejs/hardware

**Comment by vielmetti** [comment]
@rvagg - is this still an issue, getting build machines for ARMv8 builds? If so I have some ideas. Let me know the current state of affairs and how things have changed in the past 6 mo.
