### ISSUE TITLE
Benchmarking infrastructure

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#44]
Since we already have an issue to kick-start the performance tracking (#11), I thought it might be good to kick-start one about finding ways to reliably measure this over time. I think we can all agree that the lowest possible requirement is full access and control of hardware; so the discussion is rather about what would warrant benchmarking.

My end goal would be to measure the improvement (or decrease) of how io.js performs in "real" environments. This would include being run from different os:es, hardware or emulation/virtualisation/jails. In terms of prioritisation, my hunch is that the most common scenario would be a virtualised linux environment (kvm and xen), followed by linux hardware, then windows and other derivatives (fbsd, docker, ..). Since each environment requires different "warm up" phases, it might take a while to get this right. Additionally, we should probably try to reuse the [build artefacts](https://iojs.org/download/nightly/).

Using parts of [are we fast yet](http://arewefastyet.com) could be a quick way to get a frontend rolling.

I think this could be a relevant topic for the upcoming build meeting.

**Comment by rvagg** [comment]
@jbergstroem yep, although I see a benchmarking & perf working group in our near future too, would love @trevnorris and @brycebaril to get involved in that too but I'm pretty sure they aren't as interested in infrastructure concerns. Build's responsibility should be providing and maintaining the hardware.

Let's discuss bootstrapping the effort in #43

**Comment by trevnorris** [comment]
@rvagg I'm interested in helping where I can. While I can offer a better benchmarking suit then what io.js currently has, not sure how much I can help in terms of recording/reporting that data longitudinally.

**Comment by jbergstroem** [comment]
We now have hardware available through https://ci.nodejs.org and a working group active at https://github.com/nodejs/benchmarking/. Awesome! :+1:
