### ISSUE TITLE
Node installer built in Electron

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#440]
So there have been many threads about the variety of ways in which our installer is less than perfect. Dealing with installer frameworks is kind of the worst.

Would anyone be interested in exploring an alternative installer built with electron?

**Comment by ore** [comment]
what about the file size? will it go up? i mean, this is _electron_ we're talking about here

**Comment by Fishrock123** [comment]
@ore Probably but it could act like a sort of version installer. Could have an option of which version from in it. Also it doesn't make the binaries go up in size at all, probably.

Do consider how many problems we've had which the current installer programs... they are just a mess all around, especially for OS X.

**Comment by ore** [comment]
@Fishrock123 yeah, that was my only concern pretty much. a multi-version installer sounds nice and reduces efforts on the website!

**Comment by TheAlphaNerd** [comment]
```
     osx - 117.3 mb
  linux32 -  60.3 mb
  linux64 -  55.2 mb
 win ia32 -  47.8 mb
  win x64 -  66.2 mb
```
This is the application size for various deploy targets taken from https://github.com/electron/electron/issues/2003#issuecomment-135592382

I do think @Fishrock123's point is a good one though... this could be a one time installer and updater as opposed to what we have now

**Comment by ore** [comment]
just imagine! we'll be the first project of this size to only have _one_ download button on our website!

**Comment by mikeal** [comment]
We could also end the install with onboarding into documentation on how to use Node.js.

Also, we could include a version switcher, that would make things really nice.

**Comment by TheAlphaNerd** [comment]
in theory the docs could be embedded in the application

**Comment by evanlucas** [comment]
The biggest issue I've seen with OS X installers seems to be dependent on whether node/npm are owned by root. Can you get administrator access via electron on OS X?

**Comment by TheAlphaNerd** [comment]
Looks like there is a discussion about this alread

https://github.com/electron-userland/electron-packager/issues/33

/cc @maxogden

**Comment by TheAlphaNerd** [comment]
I'm not 100% this is what we want, but --> https://github.com/electron-userland/electron-builder

Seems to be capable of making a `.dmg`. It should be able to make a `.msi` but there is currently a bug they are fixing

**Comment by eljefedelrodeodeljefe** [comment]
I'd be in support for @mikeal's point of the version manager.
Also: installing headers (`process.realease.headersUrl`) for a respective version in a normalized place would be helpful on all the platforms.

**Comment by eljefedelrodeodeljefe** [comment]
From https://github.com/nodejs/node/issues/7371: should include clean uninstallers.

**Comment by MylesBorins** [comment]
it is happening https://github.com/nodejs/installer
