### ISSUE TITLE
More specific version Download Logs?

### ISSUE THREAD

**Issue by bnb** [nodejs/build#442]
Hello! 

I am curious how detailed the access logs are for /download/release. Specifically, are they precise enough to tell how many times each Minor release has been downloaded?

Source of this question is this discussion: https://twitter.com/Fishrock123/status/747544483391209472

**Comment by Fishrock123** [comment]
cc @rvagg

**Comment by Fishrock123** [comment]
@bnb Also I'm pretty sure the answer is yes, but not 100% sure lol

**Comment by jbergstroem** [comment]
Yes, since its part of path:
```
1.1.1.1 - - [04/Jul/2016:18:34:42 -0400] "GET /download/release/v4.1.2/node-v4.1.2-headers.tar.gz HTTP/1.1" 200 468778 "-" "node-gyp v3.0.3 (node v4.1.2)" "1.1.1.1"
1.1.1.1 - - [04/Jul/2016:18:34:47 -0400] "GET /download/nightly/v5.7.1-nightly201602271ecbdec2cf/node-v5.7.1-nightly201602271ecbdec2cf-linux-armv7l.tar.gz HTTP/1.1" 200 11597789 "-" "github.com/cnpm/mirrors.robot@1.0.0" "1.1.1.1"
1.1.1.1 - - [04/Jul/2016:18:34:47 -0400] "GET /download/release/v6.2.2/node-v6.2.2-headers.tar.gz HTTP/1.1" 200 474770 "-" "node-gyp v3.3.1 (node v6.2.2)" "1.1.1.1"
1.1.1.1 - - [04/Jul/2016:18:34:49 -0400] "GET /download/release/v5.11.1/node-v5.11.1-headers.tar.gz HTTP/1.1" 200 472366 "-" "node-gyp v3.3.1 (node v5.11.1)" "1.1.1.1"
```

Anyone keen on writing log parsers? :)

**Comment by rvagg** [comment]
Yes, this is possible. Read all about what's available @ https://nodejs.org/metrics/, there is a https://nodejs.org/metrics/logs/ directory that contains the logs in as raw form as we can provide without giving up too much user information (but please read the main page for details on how this all works).

So, if you just wanted to look at yesterday's downloads and see what specific versions got more downloads then you could do something like:

```sh
curl -sL https://nodejs.org/metrics/logs/nodejs.org-access.log.20160703.1467564509.csv \
  | awk -F, '(NR > 1 && $5 != ""){versions[$5]++} END{for (v in versions) { print versions[v], v }}' \
  | sort -n
```

(note that "yesterday" is a fuzzy concept, even though the file has 20160703 in it it's not precisely the logs for just that day, see the main notes for details on this).

You'll need to download all of those individual log files for the period you're interested in and concatenate them when processing. For now you'll have to do some scraping to get them but we'll be introducing an easier mechanism to get resources list this .. stay tuned.

The log processing used to create these files as well as the summary aggregates is at https://github.com/nodejs/build/tree/master/setup/www/tools/metrics if you're interested in seeing how the sausage is formed and perhaps making suggestions for improvements.
