### ISSUE TITLE
Add LinuxOne to nightly builds

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#445]
When master moved up to V8 v5.1 I added LinuxOne to the regular regression runs.  The builds on LinuxOne have been green since then: https://ci.nodejs.org/job/node-test-commit-linuxone/

I'd like to add building/uploading binaries for LinuxOne to the nightly release jobs.

- [x] connect up release linxuxOne machine to the release CI
- [x] separate release job with linuxOne as target (copy of standard job)
- [x] validate binary runs other machines
- [x] add to standard release job
- [x] validate linuxOne included in nightlies and binaries are ok
- [x] validate linuxOne is in next stable and looks ok.

**Comment by mhdawson** [comment]
Ok ran test job here: https://ci-release.nodejs.org/job/iojs+release-s390/2/nodes=rhel72-s390x-release/console

and it built ok, but it looks like it needs additional keys/setup as a release machine to be able to publish the binaries.

@jbergstroem  can you do the final configuration required for the release machine ? 

Its https://ci-release.nodejs.org/computer/release-linuxonecc-rhel72-s390x-1/ and currently has the test key on it.

**Comment by jbergstroem** [comment]
I can do the last bits this week.

**Comment by jbergstroem** [comment]
@mhdawson I just tried logging into it with the test key but wasn't able to. Is it perhaps non-root?

**Comment by mhdawson** [comment]
my bad I'd missed the step of adding the test key.  Should be ok now.

**Comment by mhdawson** [comment]
Ok Nightly built ok here:  https://nodejs.org/download/nightly/v6.4.1-nightly20160825723fa9637c/

**Comment by mhdawson** [comment]
Ran CITGM on binary from nightly on one of our internal RHEL 7.1 linuxOne machines and things look ok.

**Comment by mhdawson** [comment]
Ok need to guard so that only builds on 6.x and higher for linuxOne.

This seems to do the trick:

if [[ $ARCH =~ s390x && ${NODE_VERSION%%.*} -lt "6" ]]; then
  echo "Not building $disttype on linuxOne slave as only supported on v.6x and later"
  exit 0
fi

@jbergstroem that look ok with you ?  If so you ok with me adding that to the release build script and then adding linuxOne to the set of machines we build for ?

**Comment by jbergstroem** [comment]
@mhdawson LGTM; perhaps change message to (typo) `...as only supported on v6.x and later`

**Comment by jbergstroem** [comment]
@mhdawson also, how about simplifying the expansion to `${NODE_VERSION:0:1}`?

**Comment by mhdawson** [comment]
Ok incorporate comments and added to the regular release CI job.  Will check tomorrow to see how nightlies went.

**Comment by mhdawson** [comment]
Did a check on the nightlies  using CITGM on our local linuxOne RHEL71 boxes and I don't see anything unexpected that is not marked as flaky.

Once we have a stable that goes out, I'll sniff check that and then close this issue.

**Comment by mhdawson** [comment]
Ok linuxOne was included in the 6.7.0 release and quick check that I could uncompress and get to prompt indicates its ok.

Closing.
