### ISSUE TITLE
Invite @phillipj to the build group

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#447]
I'd like to invite @phillipj to join us in the build group. He's been contributing for a while ([PR](https://github.com/nodejs/build/pulls?q=is%3Apr+author%3Aphillipj), [issues](https://github.com/nodejs/build/issues?utf8=✓&q=is%3Aissue%20author%3Aphillipj)) and is active in the github bot space. Since we're closing in on deploying it, I felt it would be good to `+1` the crew.

My idea is that we get him in the test access group but elevate the infra machine the bot will run on so he can help handle deploy and general availability. Thoughts?

(ping @phillipj)

**Comment by rvagg** [comment]
+1, @phillipj has been a huge help for the website WG and has proven his personal investment in Node over all that time.

**Comment by mhdawson** [comment]
+1 from me

**Comment by phillipj** [comment]
Thanks for the invite, I would be honored! It would be nice to get the bot up-n-running on the project's infra, and probably tinker with nginx once in a while for nodejs.org & friends.

**Comment by TheAlphaNerd** [comment]
+1

**Comment by jbergstroem** [comment]
Unless anyone has any objections we should vote and welcome @phillipj ass part of the next meeting.

**Comment by rvagg** [comment]
+1 although I'd like to invite _all_ of @phillipj, not just that particular part of him

**Comment by jbergstroem** [comment]
@phillipj joined with https://github.com/nodejs/build/pull/455
