### ISSUE TITLE
release, PPC machines can't access direct.nodejs.org

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#449]
Nightlies seem to have started failing (July 13) as folllows:

https://ci-release.nodejs.org/job/iojs+release/nodes=ppcbe-ubuntu1404-release-64/1006/console

ppc64
rm -rf node-v6.3.1-nightly201607134480b14fda-linux-ppc64
gzip -c -f -9 node-v6.3.1-nightly201607134480b14fda-linux-ppc64.tar > node-v6.3.1-nightly201607134480b14fda-linux-ppc64.tar.gz
xz -c -f -9 node-v6.3.1-nightly201607134480b14fda-linux-ppc64.tar > node-v6.3.1-nightly201607134480b14fda-linux-ppc64.tar.xz
rm node-v6.3.1-nightly201607134480b14fda-linux-ppc64.tar
ssh node-www "mkdir -p nodejs/nightly/v6.3.1-nightly201607134480b14fda"
ssh: connect to host direct.nodejs.org port 22: Connection timed out
make: *** [binary-upload] Error 255
Build step 'Conditional steps (multiple)' marked build as failure
Skipped archiving because build is not successful
Notifying upstream projects of job completion
Finished: FAILURE

**Comment by mhdawson** [comment]
@jbergstroem don't think this would be a PPC issue but something like a firewall issue

**Comment by TheAlphaNerd** [comment]
It would appear that both the rc build and nightly on the 12th worked without issue. I have a new rc build going right now, if we see it fail I'll make a note of it in this comment

**Comment by jbergstroem** [comment]
We don't firewall 22. Network issues?

**Comment by mhdawson** [comment]
Looks like it was ok in the run mentioned by @TheAlphaNerd.  The 2 failures were within 1 and 1/2 hours of each other so may it was something to do with the network.  In any case will close and we can re-open if it re-occurs.
