### ISSUE TITLE
Build WG meeting 2016-07-19

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#450]
**Meeting Time:** 8PM Tuesday July 19th UTC, or in your local timezone:
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20160719T20&p1=%3A

### Where
* Hangouts on Air, for participants: https://hangouts.google.com/hangouts/_/hoaevent/AP36tYf9dTdEzTVCXwx98dHkni3xdMaJcjPJI3GxW5uolNlhiIV2ng
* Youtube stream, for viewers: http://www.youtube.com/watch?v=pQYqVXfhG-w
* Minutes document: https://docs.google.com/document/d/1o5YOyTUI48RlJQ3KztyENNbvATlRtrLBasEqqw32Uos/edit?usp=sharing (work in progress)

### Agenda
Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* Invite @phillipj to the build group [https://github.com/nodejs/build/issues/447]
* Alpine Linux / Docker Build [https://github.com/nodejs/build/issues/75]
* How can a project qualify for access to the build infrastructure? [https://github.com/nodejs/build/issues/448]
* OS X buildbots/ci: call to action [https://github.com/nodejs/build/issues/367]
* rsync endpoint to mirror the releases [https://github.com/nodejs/build/issues/55]
* Run and deploy nodejs-github-bot [https://github.com/nodejs/build/issues/404]

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by orangemocha** [comment]
Folks, due to other pressing work priorities I most likely won’t be able to attend these meetings on a regular basis. I haven’t been doing much work in build lately, and @joaocgreis has been doing a great job at handling the Windows stuff (and beyond). Secondarily, I also need to cut back on the number of late night meetings on my calendar.

Would someone else be willing to facilitate these going forward?

**Comment by phillipj** [comment]
I'm on vacation until august, so I won't be able to join the meeting.

**Comment by jbergstroem** [comment]
I'll be around. Although @phillipj won't be here I would still like to vote him in (unless anyone raises objections that is).

**Comment by jbergstroem** [comment]
@orangemocha I don't have access to the nodejs youtube or google account; perhaps Rod can do it?

**Comment by rvagg** [comment]
Yeah, I'll try and roll out of bed for this one @jbergstroem, hangout and live feed links are in OP, I haven't done document, if you have a link to the last one perhaps you can copy it, along with permissions, and make a new one for us?

**Comment by jbergstroem** [comment]
I'll set it up.

**Comment by mhdawson** [comment]
In the future I can also help setup the meeting as I have access to the accounts.

**Comment by jbergstroem** [comment]
@mhdawson sounds good.
