### ISSUE TITLE
Temporary Additional PPC machines

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#451]
osu is validating a new openstack environment that is intended to replace the one we currently run our vm on for PPC.

This issue is a heads update that I'm going to add a couple of machines from the new environment to validate the work/integrate as expected.  

Once the validation is complete the environment will be re-built so we'll have to delete/re-add so we won't remove the existing machines in the old environment until the migration is complete.

**Comment by mhdawson** [comment]
Adding   140.211.168.35/Slave test-osuosl-ubuntu14-ppc64_le-3, initialized through new openstack and ansible configuration complete.  Just need to add to firewall to enable.

**Comment by jbergstroem** [comment]
These have been added to the firewall.

**Comment by mhdawson** [comment]
Also added 140.211.168.37/test-osuosl-ubuntu14-ppc64_le-4  (Johan also added to firewall)

**Comment by mhdawson** [comment]
So far node and v8 tests on the new machines look good.

**Comment by mhdawson** [comment]
Ok now starting to add the permanent machines so will disable the test ones to start.

Disabled

https://ci.nodejs.org/computer/test-osuosl-ubuntu14-ppc64_le-3/
https://ci.nodejs.org/computer/test-osuosl-ubuntu14-ppc64_le-4/

**Comment by mhdawson** [comment]
These machines have now been deleted. Closing
