### ISSUE TITLE
PPC machines in paused state (Currently OK)

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#452]
Machines from the original infra are all in paused state.  Currently includes:

test-osuosl-ubuntu14-ppc64_be-1
test-osuosl-ubuntu14-ppc64_be-2
test-osuosl-ubuntu14-ppc64_le-1 
test-osuosl-ubuntu14-ppc64_le-2

Its only affecting building be as we have 2 temporary machines from another infrastructure.

The release machines are also still on-line as I believe they are on a different node.

This has occurred a few times and I hope should be resolved once Lance at osu gets in later today.

Will use this issue to track until it is no longer re-occuring

**Comment by mhdawson** [comment]
I've asked for a BE 14.04 image in the new environment so that I can add some temporary machines there as well.

**Comment by mhdawson** [comment]
Manged to get one of the be machines back online

**Comment by mhdawson** [comment]
soft rebooted another machine which came online, but then the be one seems to be off line so back to mo BE machines, trying to see if I can get the be one working

**Comment by mhdawson** [comment]
Trying to get at least one BE machine by pausing the le one that came back and then soft-rebooting one of the be ones.

**Comment by jbergstroem** [comment]
@mhdawson rebooting doesn't seem to work -- I've tried that a few times. Thinking the host is out of disk again like last time?

**Comment by mhdawson** [comment]
Agreed it must the same issue as before. I had managed to get one back on-line by turning off an le machine that was running and then rebooting the be one.  But they are all off line again so I've pulled be from the plinux tests for the node regression test.

**Comment by mhdawson** [comment]
Message for osu is that they are working on it but not sure if it will be resolved today.

There are also some BE 14.04 images but they don't quite look right as the keys are not getting injected as expected so I'm hesitant to use them until that gets resolved

**Comment by mhdawson** [comment]
Space cleaned up and all machines back online, adding PPC BE back to the jobs

**Comment by mhdawson** [comment]
Have not seen issues for ~ 1 week so closing.
