### ISSUE TITLE
Off-line machine notification not working

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#454]
I don't seem to be getting emails when machines go offline.

Talking to Johan sounds like the same for him. 

@Starefossen

**Comment by Starefossen** [comment]
I am currently looking into it. Monitoring service is online but not sending out emails as it is supposed to. 

Will keep you guys posted.

**Comment by Starefossen** [comment]
Sendgrid had marked outgoing emails from the monitor as spam, I have marked them as safe and emptied the queue and they should start getting through from now on own. Sorry for the missing emails.

**Comment by jbergstroem** [comment]
Seems to be working now. Closing.
