### ISSUE TITLE
Windows CI builds timing out almost every time...

### ISSUE THREAD

**Issue by Trott** [nodejs/build#456]
https://ci.nodejs.org/job/node-test-binary-windows/

Over the last 5 hours, 5 out of 7 of the node-test-binary-windows jobs have timed out after 30 minutes with no tests run.  I have never seen this before, but uh, yeah, thought I ought to make a note...

**Comment by joaocgreis** [comment]
The master workspace needed to be cleaned up. Done, seems to be ok now. Please reopen if it's not, or if this happens again. And thanks for reporting!

So far this "workspace needs to be cleaned" failures have been rare and I haven't seen a pattern, so I guess  we have to keep cleaning manually when we see this.

**Comment by Trott** [comment]
Hooray! Thanks for fixing that! After 10 consecutive days of failed node-daily-master jobs, we finally got a green one again this morning!

**Comment by jbergstroem** [comment]
@joaocgreis can we create a cronjob for this?

**Comment by joaocgreis** [comment]
@jbergstroem Jenkins should not be running when the workspaces are cleaned. Can we do this in the script that launches Jenkins? (where is that?) The command should be something like (untested):
```
find /var/lib/jenkins/jobs -mindepth 2 -maxdepth 2 -name workspace\* -type d -print -exec rm -rf '{}' \;
```

**Comment by jbergstroem** [comment]
@joaocgreis the init script is provided by upstream, you can probs find it in `/etc/init.d` but it will likely be replaced on update. Seeing how we rarely restart host (well at least thats the ideal scenario) - is there another way?

**Comment by joaocgreis** [comment]
@jbergstroem this is rare enough that just when we restart jenkins should be enough. I've been looking for a way to run things when nothing else is running, but no luck. (Also wanted to clean the temp repo).

But for the slaves this might be doable with a job, I'll investigate.

**Comment by joaocgreis** [comment]
Found a way to run a script in master after the job, that does not make the job fail. Will delete `.git` if it is >=5Gb, so it is created again in the next run in a clean state.
