### ISSUE TITLE
Missing Windows files for v7.0.0 nightlies

### ISSUE THREAD

**Issue by mscdex** [nodejs/build#460]
Specifically, it looks like since [v7.0.0-nightly2016071311b23068cd](https://nodejs.org/download/nightly/v7.0.0-nightly2016071311b23068cd/) there have been no Windows files included. [v7.0.0-nightly20160712ef1f7661c7](https://nodejs.org/download/nightly/v7.0.0-nightly20160712ef1f7661c7/) was the last to have them.

**Comment by joaocgreis** [comment]
@mscdex that is a known issue. https://github.com/nodejs/node/pull/7798 has landed today, if there are no further issues then tonight the files will be back.

**Comment by mscdex** [comment]
Ah ok, thanks.

**Comment by joaocgreis** [comment]
They're back: https://nodejs.org/download/nightly/v7.0.0-nightly2016080329e49fc286/
