### ISSUE TITLE
Build meeting 2016-08-09

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#462]
**Meeting Time:** 8PM Tuesday August 9th UTC, or in your local timezone:
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20160809T20&p1=%3A

Apologies for the late arrangement. If we as a result can't gather enough people I suggest we postpone.

### Where
* Hangouts on Air, for participants: https://hangouts.google.com/hangouts/_/hoaevent/AP36tYcbyZqYbXz2zUStin--r10Xch6BnK4yM3V15glVy1kyTVBNxg?eid=100598160817214911030&hl=en&authuser=0
* Youtube stream, for viewers: http://www.youtube.com/watch?v=EnLoylo8EHI
* Event: https://plus.google.com/events/cgoiccibh79r01uis7ulnmf3uj0
* Minutes document: https://docs.google.com/document/d/1tWDLu-Yhr2FQYsrrgsYEzDeVxewf3jnhReM_csg_IZ4/edit?usp=sharing

### Agenda
Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* How can a project qualify for access to the build infrastructure? #448 
* Run and deploy nodejs-github-bot #404
* OS X buildbots/ci: call to action #367 
* rsync endpoint to mirror the releases #55
* Alpine Linux / Docker Build #75

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by Starefossen** [comment]
I'll be there.

**Comment by mhdawson** [comment]
I'll be there
It would also be a good time to get feedback on the presentation for Node Interactive
