### ISSUE TITLE
Access to AIX machines to provide coverage

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#470]
# While I was away on vacation the firewall config for the AIX machines was dropped somehow and then AIX was removed from the CI runs.

We need more coverage to investigate issues on AIX.  In this case it only took a few minutes to investigate and then the fix to the firewall config to get things going again.

I'd like to get @gibm access limited to the AIX machines (or possibly AIX and PPC machines)

He works at IBM.  He meets some of the requirements for temporary access in: https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md based on this subset of the criteria:
- Consequences to the individual in case of mis-bahaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way
  - He works at IBM in the Node.js Runtime technologies group. Being banned would definitely have an impact
- Are there collaborators who work with the individual and can vouch for them.
  - I'll vouch for him
- Length and consistency of involvement with Node.js working groups and/or community.
  - This one is a little weaker as he is new to our team.  So far he has contributed (opened,  
    commented, etc on 42 issues since April 2016)

@nodejs/build can I get an approver ?

**Comment by joaocgreis** [comment]
> Length and consistency of involvement with Node.js working groups and/or community.
> This one is a little weaker

Not at all, @gibm has been helpful all around! Giving him access sounds good to me.

**Comment by gibfahn** [comment]
@joaocgreis Thanks! Just FYI, I merged my work/other Github accounts under @gibfahn, so using that rather than @gibm.

**Comment by jbergstroem** [comment]
Just a heads up: me/@joaocgreis figured out why machines sometimes 'fell out' of iptables. Fixed!

**Comment by mhdawson** [comment]
@joaocgreis can I take your response as the second required approver ? If so my default path would be to add his key to the AIX/PPC machines as that limits access to just the required set.

@nodejs/build FYI, if @joaocgreis acts as the second app rover I'll go ahead in the next few days unless I hear objections before then.

**Comment by joaocgreis** [comment]
@mhdawson sure, I approve. (Sorry if I was not clear before)

**Comment by mhdawson** [comment]
Ok, @gibfahn keys are on the AIX machines and I'll look at adding him to the PPC ones.  Sounds like he is going to be onboarded as a collaborator.  At that point I'll probably ask that we just get him access in the manner that we would give ongoing access to a collaborator instead.

**Comment by mhdawson** [comment]
Since Gibson is now a collaborator I'd like to propose we just give him access to the test keys so that he has access to the PPC, AIX and 390 machines. Will discuss in WG meting today.

**Comment by Trott** [comment]
> Since Gibson is now a collaborator I'd like to propose we just give him access to the test keys so that he has access to the PPC, AIX and 390 machines. Will discuss in WG meting today.

SGTM

**Comment by jbergstroem** [comment]
Suggesting we close this in favour of #514 (once landed)

**Comment by mhdawson** [comment]
Agreed
