### ISSUE TITLE
new PPC machines

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#473]
We now have access to new production openstack system at osuosl.

Need to create new machines to replace the originals and the temporary ones.

This is is to track progress on that.

- [X] Add le test machines
- [x] Add be test machines
- [x] Add new le release machine
- [x] Add new be release machine
- [x] Remove old machines
- [x] Rename test machines
- [x] Rename release machines
- [x] free up machines in old infrastructure
- [x] Update ansible files

**Comment by mhdawson** [comment]
Ok have added test le machines: 

https://ci.nodejs.org/computer/test-osuosl-ubuntu14-ppc64_le-5/
https://ci.nodejs.org/computer/test-osuosl-ubuntu14-ppc64_le-6/

**Comment by jbergstroem** [comment]
nitpick but perhaps we can rename them back to lowest unique id once done?

**Comment by mhdawson** [comment]
Sure once, we have the final set I can do the renames

**Comment by mhdawson** [comment]
new release machine created and configured through ansible:

https://ci-release.nodejs.org/computer/release-osuosl-ubuntu14-ppc64_le-2/

@jbergstroem can you:

- [ ] replace ssh test key with release key
- [ ] Add firewall entries
- [ ] add required keys etc needed for publishing releases.


Once you do that I'll temporarily disable the current machine and run a nightly type build to validate it works ok.

**Comment by jbergstroem** [comment]
Ok, I'll do it after the meeting.

**Comment by mhdawson** [comment]
Sorry IP for release-osuosl-ubuntu14-ppc64_le-2 is 140.211.168.66

**Comment by jbergstroem** [comment]
`release-osuosl-ubuntu14-ppc64_le-2` is ready to go.

**Comment by mhdawson** [comment]
Ok just added and ansible is running on them:

@jbergstroem can you add these to the firewall as well

TEST
	test-osuosl-ubuntu14-ppc64_be-3/140.211.168.74
        test-osuosl-ubuntu14-ppc64_be-4/140.211.168.75

RELEASE
         release-osuosl-ubuntu14-ppc64_be-2/140.211.168.76

**Comment by mhdawson** [comment]
@jbergstroem  trying to check out 	release-osuosl-ubuntu14-ppc64_le-2/	release-osuosl-ubuntu14-ppc64_be-2
They don't seem to be connected and I can't log into them anymore
to see if the agent is up or if it would be a firewall issue

**Comment by jbergstroem** [comment]
Fixed. They disconnected when I restarted `ci-release` earlier today and referenced `https://ci.nodejs.org` in the init scripts.

**Comment by mhdawson** [comment]
Thanks, ran a separate job to validate and seemed to generate/push ok so will move regular release job over to using the new machines

**Comment by mhdawson** [comment]
Ok, have rename all of the test machines.  @jbergstroem since I don't have access can you rename the release ones ? 

Once that's done I'll submit the ansiable config file changes to reflect the new ips.

**Comment by jbergstroem** [comment]
ok, both release -2 machines have been renamed.

**Comment by mhdawson** [comment]
As last step PR to update ips for PPC machines in ansible config: https://github.com/nodejs/build/pull/507
