### ISSUE TITLE
Build WG meeting 2016-08-30

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#474]
**Meeting Time:** 8PM Tuesday August 30th UTC, or in your local timezone:
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20160830T20&p1=%3A

### Where
* Hangouts on Air, for participants: https://hangouts.google.com/hangouts/_/hoaevent/AP36tYfOUN-VgervByMOkRj9SpukzKndyyCF3SJK1KHSnXFxbYinSw 
* Youtube stream, for viewers: http://www.youtube.com/watch?v=p6viQ2HyGqk 
* Event: TBA
* Minutes document: https://docs.google.com/document/d/1CLQdvgSzXNBYCJP67JDX5JZMZtfo_g3lQJC26yZ8s6U/edit

### Agenda
Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* How can a project qualify for access to the build infrastructure? #448 
* OS X buildbots/ci: call to action #367 
* rsync endpoint to mirror the releases #55 
* Add docs required by TSC nodejs/github-bot#66
* Process for determining supported platforms nodejs/node#8265
* TAP Plugin issues on Jenkins #453

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by Starefossen** [comment]
Should we put nodejs/github-bot#66 on the agenda for this meeting?

**Comment by Trott** [comment]
Maybe this too? https://github.com/nodejs/node/issues/8265

**Comment by jbergstroem** [comment]
Added both.

**Comment by jbergstroem** [comment]
@TheAlphaNerd suggested we added #453, so I did.

**Comment by gibfahn** [comment]
@jbergstroem So is there a hangouts link?

**Comment by jbergstroem** [comment]
Links to be published! Apologies for the slight delay

**Comment by rvagg** [comment]
https://hangouts.google.com/hangouts/_/hoaevent/AP36tYfOUN-VgervByMOkRj9SpukzKndyyCF3SJK1KHSnXFxbYinSw for participation

http://www.youtube.com/watch?v=p6viQ2HyGqk for lurking

**Comment by mhdawson** [comment]
PR for minutes here: https://github.com/nodejs/build/pull/485

**Comment by mhdawson** [comment]
minutes landed, closing
