### ISSUE TITLE
Add linux ppc and linuxone to node-stress-single-test

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#479]
Recent discussion was around adding AIX to this job.  When I went to look it seemed like it had already been added.

But I did notice that linuxOne and PPC BE seemed to be missing.  Going to add those under this issue.

**Comment by mhdawson** [comment]
Added linuxOne as rhel72-s390x, job ran ok here: 

https://ci.nodejs.org/job/node-stress-single-test/876/

**Comment by jbergstroem** [comment]
LGTM -- I guess we're waiting on the new osuosl setup to land so we can redeploy be/le stuff before adding it to stress?

**Comment by mhdawson** [comment]
LE is already there, and BE I was just about to add, we should be able to get the new stuff going while making sure we always have a good set of machines.

**Comment by mhdawson** [comment]
BE added, successful run: https://ci.nodejs.org/job/node-stress-single-test/877/nodes=ppcbe-ubuntu1404/
