### ISSUE TITLE
GCC 6 coverage

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#480]
Hi everyone, it would be pretty cool if we could get CI coverage for running the Node.js tests, and ideally the `test-commit-v8-linux` job too, with binaries built by GCC 6. That would have very likely helped to catch issues like https://github.com/nodejs/node/issues/8310 or https://github.com/nodejs/node/issues/6272 a bit earlier.

Any chance that’s possible?

**Comment by jbergstroem** [comment]
fedora24 runs gcc 6.1.1:
```
[root@test-rackspace-fedora24-x64-1 ~]# cc --version
cc (GCC) 6.1.1 20160621 (Red Hat 6.1.1-3)
```

Do we need something newer? What suitable distribution?

**Comment by targos** [comment]
There is already a machine with fedora 24 in `test-commit-linux`and this system has GCC 6 by default.

**Comment by addaleax** [comment]
No, 6.1.1 is what I have, too. Could something like that be included in `test-commit-v8-linux` runs?

**Comment by jbergstroem** [comment]
@addaleax done.

**Comment by jbergstroem** [comment]
I need to redeploy one of the fedora24 slaves seeing how we need a beefier vm to run tests on. I'll update this issue when done.

**Comment by jbergstroem** [comment]
Done! Part of the suite as of now: https://ci.nodejs.org/job/node-test-commit-v8-linux/
