### ISSUE TITLE
Support for running node-test-commit-v8-linux with independent toolchain

### ISSUE THREAD

**Issue by addaleax** [nodejs/build#482]
V8 loads its own version of clang when running its tests, and so does the `node-test-commit-v8-linux` job (but not a normal `make test-v8` in a node chechkout). It would be pretty cool if we could get support for running with the already-installed toolchain, although it might mean having to modify the compiler flags a bit (removing `-Werror` seems to do the trick when running gcc instead of clang).

**Comment by bnoordhuis** [comment]
I build V8 locally with gcc and it's a bit of a pain.  At times you have to build with `make GYPFLAGS="-Dclang=0"` which then becomes `make GYPFLAGS="-Dclang=0 -Dwerror='' -Dv8_enable_gdbjit=1 ..."` because `make werror=no gbdjit=on ...` doesn't work when you override GYPFLAGS.

**Comment by Trott** [comment]
@addaleax Is this still an issue? Should it remain open?
