### ISSUE TITLE
build group membership reminder!

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#489]
Hi, build group. I thought it could be nice to revisit the membership list every now and then; especially seeing how we get "default" trust in the Node.js infrastructure as well as **access to stuff**. Take a moment and think about the last six months, what you've contributed or worked on; the meetings you've attended and then consider the coming six. If you're still keen and want to be an active member – a comment in this issue would be the perfect start.

/cc: @jbergstroem, @geek, @ghostbar, @joaocgreis, @kenperkins, @mhdawson, @orangemocha, @othiym23, @phillipj, @rmg, @rvagg, @Starefossen, @TheAlphaNerd

**Comment by jbergstroem** [comment]
(I'm still super keen)

**Comment by TheAlphaNerd** [comment]
o/

**Comment by joaocgreis** [comment]
Count me in.

**Comment by Starefossen** [comment]
Still keen 😅

**Comment by phillipj** [comment]
I'm keen! 🤘

**Comment by orangemocha** [comment]
I probably won't be active. If that changes, hopefully I can reapply for membership :smile:

**Comment by rmg** [comment]
I haven't been as active as I'd hoped, and I don't imagine that will be changing in the near future. Probably best to remove me as well. :-(

I'll still be "around" if anyone needs me, though :-)

**Comment by ghostbar** [comment]
I haven't been active doing stuff here directly, but on alpine and keeping nodejs external apks for compatibility. If that's compatible in any way with what needs to be done here, let me know. Otherwise, I should be removed.

**Comment by geek** [comment]
I am ready to be an active participant!

**Comment by mhdawson** [comment]
I'm still active

**Comment by rvagg** [comment]
you have my sword

**Comment by jbergstroem** [comment]
Lets keep this going another week to get travellers/busy people a chance to respond. I'll make an attempt to sum up and file a PR as a result. Note: this will also force us to redeploy keys and change passwords (which is a good thing!).

**Comment by gibfahn** [comment]
Not a member of the build team, but I'm definitely planning to be active!

**Comment by piccoloaiutante** [comment]
I have no contribution at the moment but i'm willing to contribute :-)

**Comment by jbergstroem** [comment]
So, summing up -- here's the replies from our current team:

Remaining:
 - @jbergstroem
 - @TheAlphaNerd 
 - @joaocgreis 
 - @Starefossen 
 - @phillipj 
 - @geek 
 - @mhdawson 
 - @rvagg

Leaving: 
 - @orangemocha
 - @rmg 
 - @ghostbar 
 
No reply (implied leave):
 - @kenperkins 
 - @othiym23 
 
I'll keep this open for another few days giving people not having replied yet a chance to do so.

To those who are leaving: thank you for both your efforts and deciding to step down. You're obviously welcome back at any time should you find the time to help out! One of the main reasons I wanted to get this initiative going is to make sure we actively maintain and protect our infrastructure, including secrets. I will be re-rolling our shared test keys in as a result of closing this issue seeing how we haven't done so in almost a year.

Finally, one thing I had in mind was perhaps creating a document that outlines responsibilities/areas of interest -- @Trott recently mentioned that he'd like to know how to generally ping if host $x goes down or host $y are experiencing problems. A list that for instance mentions pinging @mhdawson or @jbergstroem should ppc hosts  have issues would benefit all collaborators and likely improve the feedback when things go bad. I'll create another issue about this if people think its a good idea.

Also, feedback on this procedure is also greatly appreciated!

**Comment by rmg** [comment]
Reminder: when/before this gets closed, the actual @nodejs/build group members list should be updated to reflect the results :-)

**Comment by jbergstroem** [comment]
@rmg yep, thought I'd follow up with a PR past! Thanks for reminding me.

**Comment by jbergstroem** [comment]
I've now updated all memberships and teams. Key updates in progress. To those taking a leave: thank you for all your work - wouldn't be here today without it.
