### ISSUE TITLE
Add AIX to nightly builds

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#490]
We have good AIX hardware now, which is being exercised in the regular regression runs.

This issue is to track adding the AIX release machine and adding AIX to the nightlies.

- [x] connect up release AIX machine to the release CI
- [x] separate release job with AIX as target (copy of standard job)
- [x] validate binary runs other machines
- [x] add to standard release job
- [x] validate AIX included in nightlies and binaries are ok
- [ ] validate AIX is in next stable and looks ok.

**Comment by mhdawson** [comment]
AIX release machine has base configuration and entry added here to the release ci:

https://ci-release.nodejs.org/computer/release-osuosl-aix61-ppc64_be-1/

and the slave shows as connected.

I believe the next step is to add the keys required to push to the download site and replace the test key with the release machine ssh key @jbergstroem.

**Comment by jbergstroem** [comment]
What's the ip of `release-osuosl-aix61-ppc64_be-1`?

**Comment by mhdawson** [comment]
Ok created a separate release job, and validated binaries were built/published ok.  

Now added to standard release job.  Will check tomorrow to make sure the nightlies are ok tonight and include AIX.

**Comment by mhdawson** [comment]
AIX is showing up in nightlies

**Comment by mhdawson** [comment]
AIX was included in 6.7.0 and looks ok so closing.
