### ISSUE TITLE
libuv: centos6-64: java.io.IOException: remote file operation failed

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#491]
Failing as of today (?).  Examples:

https://ci.nodejs.org/job/libuv-test-commit-linux/148/nodes=centos6-64/console
https://ci.nodejs.org/job/libuv-test-commit-linux/148/nodes=centos6-64-gcc44/console

**Comment by jbergstroem** [comment]
Not sure what's going on here (tried building and got the same issues) -- restarting jenkins slaves and trying again seems to fix it. Great.. I'll close but please reopen if you see the same issue again.
