### ISSUE TITLE
Invite @Trott to the build team

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#497]
Rich has been key in keeping a close track at our CI, making sure that machines works as intended. I reckon its time he joins us to fix the errors he finds as well!

**Comment by TheAlphaNerd** [comment]
+1

**Comment by Starefossen** [comment]
LGTM 👏

**Comment by Trott** [comment]
Thanks. This would be great.

**Comment by phillipj** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by jbergstroem** [comment]
The build WG decided to vote @Trott into our (not so) secret society! Glad to have you onboard.
