### ISSUE TITLE
AIX Machines: access for David Edelsohn

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#508]
David Edelsohn is part of the AIX team within IBM and has agreed to help in maintaining the AIX machines as OSU.

To be able to do this effectively we'd like David to have ongoing access to the test and release machines.

For ongoing access based on our doc here:https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md
-  Does the scope and size of the need justify providing access.
  We need help in managing the AIX machines 
  -  We need specialized AIX OS knowledge that we don't have in the collaborator community at this point so I believe the answer here is yes.
-   Is the individual a collaborator. If so then access should be allowed provided the first point is satisfied.
  - David is not a collaborator
-  Length and consistency of involvement with Node.js working groups and/or community.  Consequences to the individual in case of mis-behaviour. 
  - David is part of IBM and consequences for mis-behaving would be severe in terms of IBM 
-   Are there collaborators who work with the individual and can vouch for them.
  - I'll  vouch for David.

**Comment by jbergstroem** [comment]
I'm not sure if you're asking about giving him access to the `test-` key (ref: ongoing) or just adding his key to test-osuosl-aix*? I'm ok with the second option seeing how you vouch for him.

**Comment by mhdawson** [comment]
It is the second - add his key to those machines.

His request was access to the release machine as well as we'll need his support there as well.  I guess the more consistent way would be to give him access when needed to that machine but we should at least agree here that it can happen when necessary.

**Comment by mhdawson** [comment]
@nodejs/build any objections ?  Otherwise I'll consider approved for access to the test machines by @jbergstroem's ok.

**Comment by mhdawson** [comment]
David's key are installed on test madchines so closing.
