### ISSUE TITLE
ubuntu1604-arm64 build failures...

### ISSUE THREAD

**Issue by Trott** [nodejs/build#509]
...and nothing but build failures.

@jbergstroem removed it from node-test-commit-arm and will rebuild tomorrow, if I'm understanding everything correctly.

Trying to clear the ccache resulted in:

```
ccache: error: lstat /home/iojs/.ccache/1/4/a2e65550066b7cf1e5bbfa56a9462b-527790.d failed: Input/output error
```

Here's a sample failure: https://ci.nodejs.org/job/node-test-commit-arm/5310/nodes=ubuntu1604-arm64/

That was the 9th consecutive build failure over a six hour period of time.

**Comment by jbergstroem** [comment]
I've rebuilt 1 and 3. Putting them back on. Re-open if they start failing.

**Comment by jbergstroem** [comment]
Looks like we're getting an incorrect cpu core value: https://ci.nodejs.org/job/node-test-commit-arm/5402/nodes=ubuntu1604-arm64/console

I don't have time to fix this now; will remove from arm job for now.

**Comment by jbergstroem** [comment]
Re-imaged them. Closing!
