### ISSUE TITLE
Collect a list of resources

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#51]
In order to get some things done, it'd be good to get a full list of what resources are available (and where). Based on that, I'd like to:
- update the main readme.md (platforms and builders)
- start digging into access redundancy (ref last meeting about 1+ access to all resources)
- look at how which resources would be better suited for certain things (performance tracking, tests for all PR's, etc)

I can create a list from what @rvagg mentioned on the meeting, but think it'd be even better if @rvagg perhaps kicked this list off? How about:
- hostname, location (sponsored by), hardware/vm assigned resources

**Comment by rvagg** [comment]
actually a lot of it is here already: https://jenkins-iojs.nodesource.com/computer/

all of the connected hosts are being used in some way and their names should indicate what they do and who is sponsoring them. I can tweak if you come up with an initial list. Unfortunately I don't have much time for this at the moment as I'm preparing for a flight tomorrow and full week (at least) ahead of me.

**Comment by jbergstroem** [comment]
Ok, I'll use that as a baseline.

**Comment by jbergstroem** [comment]
I think what we want to do here is an ansible script that collects info (through gather_facts) and updates the README.md programatically.

**Comment by gibfahn** [comment]
I think this can/should be closed. We have a basic list, and if we want more info we should open a more targeted issue.
