### ISSUE TITLE
temporary access to @brendanashworth

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#511]
Brendan wanted access to work with https://github.com/nodejs/node/pull/7946. The latest CI indicates that he needs access to (at least) a FreeBSD host. Can I get some more people approving him getting temporary access?

**Comment by joaocgreis** [comment]
@jbergstroem that's good news, I approve.

**Comment by Trott** [comment]
:+1:

**Comment by TheAlphaNerd** [comment]
lgtm

**Comment by mhdawson** [comment]
LGTM

**Comment by jbergstroem** [comment]
I've now added his key to `test-joyent-freebsd10-x64-2`.

**Comment by jbergstroem** [comment]
@brendanashworth: still need access?

**Comment by brendanashworth** [comment]
@jbergstroem sorry! I do not. Thanks!

**Comment by jbergstroem** [comment]
Removed. Closing.
