### ISSUE TITLE
Add download testing 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#513]
After a recent release and issue was opened identifying that the tar.gz was corrupted. There were suggestions in https://github.com/nodejs/node/issues/8814 that we could have an automated job/process that automatically checks the download binaries

**Comment by mhdawson** [comment]
@gibfahn @richardlau FYI

**Comment by jbergstroem** [comment]
How about adding a step after creating it instead? something like:
```console
# either
$ gunzip -t $foo.tar.gz && echo $?   # xz supports -t as well
# ..or
$ tar -zxf $foo.tar.gz &> /dev/null && echo $?
```

**Comment by mhdawson** [comment]
This looks like a similar issue that we did not notice for smartos as well https://github.com/nodejs/build/issues/585.

Having a regular job that validates we can download/unzip all of the current releases might help.

**Comment by gibfahn** [comment]
Do we generate md5 checksums for the builds? Seems like something that might be worth doing if we don't.

**Comment by gdams** [comment]
@mhdawson I'd be happy to quickly script one of these up. I wrote a similar job to automate checking the md5 checksums of the IBM Node releases

**Comment by mhdawson** [comment]
@gdams that would be great.  Once you have the script we can look at setting up the ci to run it.  

I can think of a couple of different levels we could valid to:

1) Download and validate unzip works
2) Actually run "hello world", this would mean we'd need to download/unzip on the machine where the version can run.

2) would be great, but 1 would also go a long way to making sure things are ok.

**Comment by gdams** [comment]
Okay so to start with I have written a simple bash tool that will scrape the download dir for a certain node version and check all of the sha sums. Where abouts would it make sense to store this script?

**Comment by gibfahn** [comment]
@gdams I'd put it in [`tools/`](https://github.com/nodejs/node/tree/master/tools)

**Comment by mhdawson** [comment]
Ok the script rocks. I've updated the CI job so that it can be used to:

Run tests on all current shipping releases (StreamandVersion = release)
Run tests on all current shipping releases and nightly releases (StreamAndVersion = latest)
Run tests on the lastest of a particular stream (ex v6) either shipping or nightly (StreamAndVersion = vX, were X is the stream), use 2nd selection box to select Nightly or Release
Run tests on a specific level (shipping or nightly) (StreamAndVersion = vY, were Y is the specific version ex v8.4.1), use 2nd selection box to select Nightly or Release

https://ci.nodejs.org/view/All/job/validate-downloads/

Have also configured to run nightly.

**Comment by mhdawson** [comment]
The other thing we should setup is who gets emails on failures, I'm thinking the release team but we probably need to check with them if they are ok/want that.

**Comment by mhdawson** [comment]
Ok job is setup and scheduled to run nightly.  Now we need to make sure the release team is aware its a tool they can use and discuss who should be on the email notification list for when it fails.

What I suggest is that we add an email alias called

```
download-validation-alert
```

and then we can add those interested/willing to get notifications of failures.

My initial thought is that it potentially makes sense to include people from the release team as well as some people from the build team.  The rational for adding the release is if a release needs to be fixed, then   one of them will have to be involved.  The rational for the build team is that if there is an infra problem or a problem with the job itself then the build team may need to help with that.

I've opened this PR to create the alias and will update with those who would like to be added: https://github.com/nodejs/email/pull/54.  Goal is to get initial list landed early next week.

I've opened this PR as initial doc for the job: https://github.com/nodejs/build/pull/849

@nodejs/build @nodejs/release please let me know if you want to be added to the notification alias.

**Comment by maclover7** [comment]
ping @mhdawson -- can this be closed? It looks like the job has been running well and everything's working okay.

**Comment by mhdawson** [comment]
Yes, closing
