### ISSUE TITLE
Add Gibson to Build WG

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#514]
This issue is to discuss/vote on adding @gibfahn to the build WG.

Please either LGTM or discuss.  Final discussion/review is planned to take place in the next WG meeting.

**Comment by mhdawson** [comment]
LGTM

**Comment by TheAlphaNerd** [comment]
LGTM

**Comment by jbergstroem** [comment]
LGTM

**Comment by Trott** [comment]
LGTM

**Comment by joaocgreis** [comment]
LGTM

**Comment by TheAlphaNerd** [comment]
@nodejs/build can we give @gibfan access to jenkins while we wait for this to be voted? There is some work I could use his help on

**Comment by joaocgreis** [comment]
Do we have or inherit a process for adding WG members from somewhere? Do we need a formal vote? The meetings are great to move stalled issues and discuss stuff, but we should be able to make decisions on GH issues. This has been open for 23 days without any objection, I do not see a reason not to move forward.

**Comment by gibfahn** [comment]
So it looks like the people who haven't voted are: @rvagg @geek @phillipj @Starefossen

**Comment by Starefossen** [comment]
LGTM 🎉

**Comment by phillipj** [comment]
LGTM 

> This has been open for 23 days without any objection, I do not see a reason not to move forward.

Completely agree!

**Comment by jbergstroem** [comment]
@joaocgreis not really a formal process other than the tradition of attempting to vote on our meetings. I agree that this shouldn't hold up Getting Work Done and I believe we have consensus with the two last votes. Perhaps have all members add their vote post-addition as well.

@gibfahn can you ping me on irc?
