### ISSUE TITLE
release/index.json for v6.8.1 has invalid modules value

### ISSUE THREAD

**Issue by phillipj** [nodejs/build#519]
As reported in https://github.com/nodejs/nodejs.org/issues/969, the v6.8.1 release has `modules: null` in https://nodejs.org/download/release/index.json.

I assume the `modules` value originates from [fetchModVersion() in dist-indexer.js](https://github.com/nodejs/build/blob/master/setup/www/tools/dist-indexer/dist-indexer.js#L268). I've manually tested the regexes in that method against `node_version.h` and `node.h`, where the former seems to match perfectly fine, meaning it should *not* have resolved the modules value to `null`.

Any thoughts on how this might have happened? Could we execute dist-indexer.js manually to see if it was a temporary glitch, and the correct modules value gets resolved now?

**Comment by phillipj** [comment]
Just noticed v6.8.1 also has `zlib: null`

**Comment by targos** [comment]
It's also missing the `npm` property

**Comment by targos** [comment]
And `uv` is an empty string

**Comment by rvagg** [comment]
I've run it again and it's updated. This can happen if the tag is not pushed to the public repo before being promoted. @evanlucas I think you did 6.8.1, do you recall if this happened?

**Comment by evanlucas** [comment]
Looking back, I may not have pushed the tag when I promoted

**Comment by rvagg** [comment]
pretty sure https://github.com/nodejs/node/issues/9142 will solve this
