### ISSUE TITLE
Temporary access to AIX release machine for Michael Dawson

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#520]
Seems like the config of the AIX release machine left in one bit of configuration which means on reboot that console input is needed to get the machine going again.

We've validated that the issue does not exist on the machines in the test infra and we are pretty sure we know what the issue is.  We just need to comment out or remove this line:

```
install_assist:2:wait:/usr/sbin/install_assist /dev/console 2>&1  
```

from the /etc/inittab file.  Commenting out can be done by inserting the ':' in the first column of the line.

I'll go ahead and do this when we don't have release going out but I'll need my key to be added back to the machine to be able to do that.

**Comment by jbergstroem** [comment]
It looks like this on the aix release host: `install_assist:2:wait:/usr/sbin/install_assist </dev/console >/dev/console 2>&1`

**Comment by mhdawson** [comment]
Ok, even though the line is slightly different I think we still need to comment it out or remove that line.

**Comment by jbergstroem** [comment]
Is there anything else actionable here? (me and Michael did some irc talk)

**Comment by jbergstroem** [comment]
Closing this; I believe the issues have been fixed.

**Comment by mhdawson** [comment]
Agreed
