### ISSUE TITLE
Remove most environment variables from jenkins

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#521]
We should strive to remove as many environment variables from jenkins configuration as possible. This is because generalization of stuff like jobs or tmp dir might be different per worker. As part of this, lets verify that variables exists in each environment at every worker (part of the ansible refactor).

These include (add more as we find):
- node_tmp_dir
- node_common_port
- jobs/`-j`
- python

**Comment by joaocgreis** [comment]
SGTM
