### ISSUE TITLE
Build WG meeting 01-11-2016

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#522]
### When

November 1st 2016, 8pm UTC: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20161101T20&p1=%3A

### Where
- Hangouts on Air, for participants: TBA
- Youtube stream, for viewers: TBA
- Minutes document: https://docs.google.com/document/d/1IdeSfCJOT_cwlt4prb_Qv42Yn96jzunBt22pJfankDg/edit?usp=sharing

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.
- Add Gibson to Build WG #514
- file and directory names for downloads #515
- Draft text for HSTS communication #484
- TAP Plugin issues on Jenkins #453
- rsync endpoint to mirror the releases #55
- Looking for issue good for first contribution #495 
- Access to AIX machines to provide coverage #470

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by jbergstroem** [comment]
Unfortunately, I will have to give a pardon for this one.

**Comment by joaocgreis** [comment]
I won't be able to attend today, sorry.

**Comment by Starefossen** [comment]
I haven't had much time for Build related stuff as of lately, sorry. But I can help facilitate the meeting if we decide not to cancel this one.

**Comment by geek** [comment]
I am also unavailable today. 

Thanks,
Wyatt

**Comment by rvagg** [comment]
With so many bails I think we should punt on this meeting and I'll stay on bed. @mhdawson you ok with that?

**Comment by rvagg** [comment]
Cancelling. Let's try and resolve some of these things async.
