### ISSUE TITLE
Build nightlies of Node-ChakraCore

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#527]
Node.js on ChakraCore (https://github.com/nodejs/node-chakracore) is becoming increasingly stable. Hence, it is our intention to provide users with an easy way to start experimenting with the latest version, by providing experimental nightly builds. For now, this will include a Windows version and a Linux version build from the `xplat` branch.

If there are no objections, I will soon move forward with this. My current plan is to follow these steps:

- [x] Skip the `nodejs-nightly-builder` step altogether (see next item).
- [x] Create a new job in ci-release. It is not yet time to integrate with `iojs+release`, and it's better to have a dedicated job that can take any modifications or workarounds for now. This allows us to skip the `nodejs-nightly-builder` step above.
- [x] Create https://nodejs.org/download/chakracore-nightly/ (staging + dist rootdirs)
- [x] Add `chakracore-nightly` to `promote_nightly.sh` (+ `settings`)
- [x] Open PR with Ansible changes to make the changes public. Does not need to land since this is not definitive. (Update: https://github.com/nodejs/build/pull/547)

Please let me know of any suggestions.

cc @nodejs/node-chakracore @nodejs/build @joshgav @digitalinfinity

**Comment by mhdawson** [comment]
nightly builds seem reasonable to me.

**Comment by jbergstroem** [comment]
I'd like to see this end up in the nightly job at some point, but having it separate to speed up development makes sense.

**Comment by joaocgreis** [comment]
Windows nightly releases are already in place. However, Linux releases cannot be built out of our current release servers, because the `xplat` branch [requires a more recent OS and some dependencies](https://github.com/nodejs/node-chakracore/tree/dd5a011356bac0b0ceb67fbdda32af5f8958c2db#linux).

In order to disturb or current infra as little as possible, I plan to create a new release server with Ubuntu 16.04 only for ChakraCore. I accept full responsibility for maintaining it (@orangemocha can be a backup if absolutely necessary). @nodejs/build any objections?

**Comment by joaocgreis** [comment]
Ubuntu release server done, deployed using https://github.com/janeasystems/build/commit/8c8d28c1d9a1c7caecf50c70b558b052a5c27dad . Will follow with a OS X server if there are no objections.

**Comment by joaocgreis** [comment]
OS X server deployed using https://github.com/nodejs/build/tree/master/setup/osx and `brew install cmake icu4c`. Nightlies available for Windows, Linux and OS X: https://nodejs.org/download/chakracore-nightly/v7.0.0-nightly20161129efeaf88f0c/

**Comment by joaocgreis** [comment]
Node-ChakraCore has reduced external dependencies, so OSX nightlies are now being released from the OSX release server.

**Comment by joaocgreis** [comment]
Node-ChakraCore now supports Ubuntu 14.04. Deployed a Ubuntu 14.04 release server to replace 16.04 with https://github.com/janeasystems/build/commit/622ea305cccf4c06a9a7648e1dd0f4205ef8cb9b .
