### ISSUE TITLE
Do we want a logo?

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#529]
<p align="center">
<img width="400" alt="artboard 1 2x" src="https://cloud.githubusercontent.com/assets/176984/20235231/1f934034-a86b-11e6-9ed5-65d047864f80.png">

</p>

Just did this for reasons I'm still not sure about. Do we even want or need a logo? I imagine printing stickers and putting them on my toaster which hopefully will run jenkins in a near future.

Edit: database icon -> shovel (poorly outlined by me).
Edit2: Shovel upgrade! Made from scratch (needs work though; scales awfully)

**Comment by mhdawson** [comment]
I think it would be cool to have some stickers :)  We'd probably have to get the ok from somebody in the foundation for the design.

**Comment by gibfahn** [comment]
I can't say we need this, but definitely want that sticker. 

`<bikeshedAlert>`Maybe less text? Something like `Node.js Build WG`?`</bikeshedAlert>`

**Comment by TheAlphaNerd** [comment]
I'd be into something super minimal... something we can put on a hex sticker. What about just the gears or the shovel?

**Comment by jbergstroem** [comment]
@gibfahn we could always make the text optional if stickers would be a reality. I just saw the symbol/text as a way to consolidate a readme/etc.

**Comment by jbergstroem** [comment]
I'll prepare a hex shovel, the symbol and the text for use if we end up doing it!

**Comment by bnb** [comment]
Love this idea! Would be super fun to start getting NodeSchool-esque logos for each WG. They have a [HexDex](https://nodeschool.io/hexdex.html) with all the logos - maybe the Org could do something similar, starting with the Build WG?

**Comment by jbergstroem** [comment]
Well, our shovel aint got shit on those hexdex:es -- I'll see what I can do :)

**Comment by rvagg** [comment]
@jbergstroem get us a hex ASAP and I'll get some printed before Node Interactive, I have some other hexes to print as well so may as well do it at the same time. Vector would be nice of course.

**Comment by TheAlphaNerd** [comment]
@jbergstroem I've made some hexes before so let me know if you want some support

**Comment by jbergstroem** [comment]
@TheAlphaNerd no issues with dimensions; bigger issues with skill.

**Comment by jbergstroem** [comment]
[wip.pdf](https://github.com/nodejs/build/files/606720/wip.pdf)

Here's the PDF is someone wants to chip in.

**Comment by mikeal** [comment]
Can someone send an email to the trademark alias to get this approved as derivative :)

**Comment by mhdawson** [comment]
A good opportunity to print them https://www.stickermule.com/ca/p/831c7240

**Comment by maclover7** [comment]
ping -- should this stay open?

**Comment by bnb** [comment]
@maclover7 this issue has been referenced in discussion around https://github.com/nodejs/community-committee/issues/212 - I don't think it needs to stay open for that discussion to move forward, but just a heads up 😊

**Comment by gibfahn** [comment]
>ping -- should this stay open?

What do you think? My view is that having a logo would be good, so it should stay open until we actually have one. But maybe we don't need one (in which case we should agree that and close it).

Maybe this should be on the wg-agenda for the next meeting if it's been forgotten. Probably needs a champion though (someone to work out next steps).

**Comment by gdams** [comment]
I'm going to try and re kindle the fire on this issue. I personally feel that having our own logo would be a great idea and as @mhdawson has mentioned, it would also be a good opportunity to create stickers which the WG members could have. It ties in nicely with some of the other discussions about how to raise awareness of the build WG and how to give them more recognition in the foundation.

**Comment by mhdawson** [comment]
I've mentioned it as a possible first one for the https://github.com/nodejs/badges initiative.  Having said that I think I could just ask for approval for the logo suggested originally if we all agree its good.

**Comment by Trott** [comment]
Anyone who wants should feel free to pursue this, but I don't think we need this as an open issue in the tracker at this time.
