### ISSUE TITLE
Skip BSD 11 for v4.x

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/build#530]
BSD11 cannot compile v4.x. Can we get a no-op for that platform for CI?

**Comment by jbergstroem** [comment]
I'd optimally like to get this fixed but I don't have time to look into it. Does this look ok?

<img width="998" alt="screen shot 2016-11-11 at 6 30 20 pm" src="https://cloud.githubusercontent.com/assets/176984/20230876/f004521e-a83c-11e6-8245-b667c79e76de.png">

**Comment by TheAlphaNerd** [comment]
lgtm

**Comment by jbergstroem** [comment]
Ok, in place now. Please ping me when it messes up (it will).
