### ISSUE TITLE
Resizing AIX machines - 10 AM Nov 14

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#532]
When the AIX machines were installed, they were not given the requested resources.  We need to take them down for a short period in order to be able to resize.

Planning to do the 2 test machines today at 10 AM.

**Comment by jbergstroem** [comment]
Cool. Please update the readme for automating the install if need-be as well. Finally, if you could install the latest available python 2.7.xx that includes pip it would be awesome.

**Comment by mhdawson** [comment]
OS updates we should handle through a different issue as I've had many dependency issues so installing the latest may not be as straight forward as would be nice.

We would need your help to do the resize on the release machine since I can't log in to take it of lf line.  You going to be around the next 30 mins ?

**Comment by jbergstroem** [comment]
Since we will be requiring pip to install tap2junit at some stage (junit xml output from test runners) I hope the install won't have any issues. According to http://www.aixtools.net/index.php/python, recent releases should have `pip` installed?

**Comment by jbergstroem** [comment]
I will be available on IRC in about 30 minutes from now.

**Comment by mhdawson** [comment]
In terms of what we are doing now, it is resizing the physical resources assigned to the machine
so outside of the OS and does not affect the install instructions

**Comment by jbergstroem** [comment]
Oh, gotcha.

**Comment by mhdawson** [comment]
In terms of dependencies its more that if there are any shared dependencies it can have a ripple effect, last time I had a lot of work (many hours) to get to a state that worked with a new package.  Hopefully it will be smoother this time.  

I'll open a new issue to install a python with pip.  I assume it should still be in the 2.7 line ?

**Comment by mhdawson** [comment]
test machines resized, back on-online  and builds when through ok on test machines. 
release machine resized, back on-line and custom test release built ok.
