### ISSUE TITLE
Install latest python 2.7 with pip on AIX

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#533]
From @jbergstroem 

Since we will be requiring pip to install tap2junit at some stage (junit xml output from test runners) I hope the install won't have any issues. According to http://www.aixtools.net/index.php/python, recent releases should have pip installed?

**Comment by gibfahn** [comment]
@gdams has used pip on AIX before, he's going to try getting it working on a temporary machine so we can work out the process.

**Comment by edelsohn** [comment]
I have Python pip installed on my AIX systems. I was able to bootstrap with get-pip.py.  There is a typo / bug in the sysconfigdata built on AIX for some Python releases.

**Comment by gdams** [comment]
okay so I got pip working on aix. Firstly download `https://bootstrap.pypa.io/get-pip.py` and then just run `python get-pip.py` and then just ensure that `/opt/freeware/bin` is in the path

**Comment by jbergstroem** [comment]
great news! can we get this in as part of the ansible task

**Comment by gibfahn** [comment]
@jbergstroem So, my plan is:

 1. Install pip manually on one of the test machines and document in [setup/aix61/manualBootstrap.txt](https://github.com/nodejs/build/blob/master/setup/aix61/manualBootstrap.txt).
 2. If nothing is broken after a week, install on the other test machine and ask you to install on the release machine.
 3. Once Ansible is setup on AIX (see https://github.com/nodejs/build/issues/551) add it to the Ansible scripts.

**Comment by gibfahn** [comment]
I've installed pip on `power8-nodejs3.osuosl.org` (which I'm pretty sure is `test-osuosl-aix61-ppc64_be-1`). Pip itself seems to be working fine, my issue with curl is documented in #551.

What I did:

```bash
curl -O https://bootstrap.pypa.io/get-pip.py 
scp get-pip.py test-osuosl-aix61-ppc64_be-1:/home/gib

ssh test-osuosl-aix61-ppc64_be-1
bash
python /home/gib/get-pip.py
export PATH=/opt/freeware/bin:$PATH
pip
```

**Comment by sxa555** [comment]
I thought I'd added this comment yesterday but apparently not - might be better to symlink /opt/freeware/bin/pip to /usr/bin/pip to avoid having to tweak the path - that would make it consistent with how a lot of the other freeware tools get installed.

**Comment by gibfahn** [comment]
Makes sense, I'll update the script (and the docs)

**Comment by gibfahn** [comment]
I've now installed pip on `power8-nodejs2.osuosl.org` (which I'm pretty sure is `test-osuosl-aix61-ppc64_be-2`). Pip itself seems to be working fine, but I had to change the LIBPATH fix, as what works for curl doesn't work for python.

What I did:

```bash
ssh test-osuosl-aix61-ppc64_be-2
bash
LIBPATH=/usr/lib curl https://bootstrap.pypa.io/get-pip.py | python
ln -s /opt/freeware/bin/pip /usr/bin/pip
pip # You should get the pip options
```

@mhdawson can you install `pip` on the release AIX machine? @jbergstroem does that make sense as the next step? I don't think there have been any issues with the machine that's had `pip` on it for the last three weeks.

**Comment by gibfahn** [comment]
PR to update the LIBPATH instructions: https://github.com/nodejs/build/pull/629/commits

**Comment by gibfahn** [comment]
Updating the release machine will be covered in https://github.com/nodejs/build/issues/630, so this can be closed.
