### ISSUE TITLE
Jenkins agent Autostart on AIX

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#534]
Seems that what I put in place does not actually autostart the jenkins agent on AIX

Getting suggestions from our AIX expert (David Edelsohn) on what we should do instead.  In the mean time on reboot of an AIX machine you need to run

/etc/rc.d/rc2.d/S20jenkins start

Note they do not need to be/nor should be rebooted very often. I think they had been running for more than a few months when we took them down today to resize the underlying machines.

**Comment by gibfahn** [comment]
ping @mhdawson , we should talk to @edelsohn about how to get something auto-running on boot.

**Comment by edelsohn** [comment]
https://www.ibm.com/developerworks/aix/library/au-aix-autostartup-shutdown-scripts/index.html
http://www-01.ibm.com/support/docview.wss?uid=isg3T1000661

**Comment by sam-github** [comment]
jenkins rc.d script restarts jenkins on reboot of aix ATM
