### ISSUE TITLE
Document policy for CITGM modules

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#535]
Currently we don't have a policy documented for the requirements of a module to be included in CITGM. To the best of my knowledge we have both **HARD** and _SOFT_ requirements

---
### Hard Requirements

* Module source code must be on github
* Published versions must include a tag on github
* The test process must be executable with only the commands `npm install && npm test` using the extracted tarball mentioned above
* The tests pass on supported Major release lines
* The maintainers of the module remain responsive when there are problems

### Soft Requirements

* The module must be actively used by the community
OR
* The module must be heavily depended on
OR
* The module must cover unique portions of our API
OR
* The module fits into a key category (e.g. Testing, Streams, Monitoring, etc.) 
OR 
* The module is under the Node.js foundation github org
OR
* The module is identified as an important module by a Node.js Working Group
---

So I'd like to just verify with everyone that they are ok with these requirements, and then figure out where they should live.

**Comment by GeorgeAdams95** [comment]
I would change to 
"The test process must be executable with only the commands `git clone $url && npm install && npm test`" because as I understand it you are only planning to support github

**Comment by TheAlphaNerd** [comment]
@GeorgeAdams95 this is not the case as we get a tarball from github, we do not git clone.

**Comment by GeorgeAdams95** [comment]
okay then:
"The test process must be executable with only the commands `npm install https://github.com/x/y/release.tar.gz && npm test`"

**Comment by TheAlphaNerd** [comment]
changed the copy to `The test process must be executable with only the commands npm install && npm test for the extracted tarball mentioned above`

**Comment by mhdawson** [comment]
@TheAlphaNerd and I discussed and the current version has a +1 from me.

**Comment by gibfahn** [comment]
This LGTM. I'd have thought it should live in the CitGM repo, but no strong opinions.

**Comment by TheAlphaNerd** [comment]
@gibfahn the policy could live there. I think we just need to document it

**Comment by mhdawson** [comment]
I guess the question is what more do we need to close on this ?

**Comment by gibfahn** [comment]
Maybe a couple more reviews? @nodejs/citgm

**Comment by mhdawson** [comment]
@nodejs/citgm @nodejs/build please comment.  Myles do you want to put together a PR for this ?  I'm also happy to do it.  I figure it should go into the CITGM readme.

**Comment by gdams** [comment]
LGTM, and yeah +1 for this living in the citgm repo

**Comment by gibfahn** [comment]
CITGM PR: https://github.com/nodejs/citgm/pull/310

**Comment by gibfahn** [comment]
CitGM PR has landed
