### ISSUE TITLE
Add node-test-commit-linux-coverage to Node.js jenkins page

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#536]
I'd like to add https://ci.nodejs.org/view/All/job/node-test-commit-linux-coverage/ to the Node.js jenkins page (https://ci.nodejs.org/).  Its consistently green and needs to stay that way in order to support: https://coverage.nodejs.org/

Objections, agreement ?

**Comment by jbergstroem** [comment]
no objections.

**Comment by jbergstroem** [comment]
Perhaps its time to pull all the sub-jobs to test-commit/test-pr? Ideally, the front page should fit all relevant jobs without scrolling.

**Comment by mhdawson** [comment]
Moving the sub-jobs makes sense to me provide that the main job mostly passes.   Another option might be to have one tab for regression and then one for "nightly" jobs that would include the benchmark and coverage ones.  

My main desire is to be able to look at a page and know that if something's not green it should be and needs to be investigated.  

If there was a way that could rollup the other pages that would be even better but not sure jenkins can do that.

**Comment by mhdawson** [comment]
Since there are no objections this was added to the page a while back.  Closing this and we can discuss a larger refactor when needed.
