### ISSUE TITLE
nodejs.org/metrics not plotting v7 downloads

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#540]
Download numbers for v7 do not appear to be showing up in the per-version graph.

**Comment by rvagg** [comment]
This one? https://nodejs.org/metrics/summaries/version.png

![screenshot from 2016-11-19 11-14-20](https://cloud.githubusercontent.com/assets/495647/20451035/5627f502-ae49-11e6-829f-8c0cbe12c7f3.png)

Just need to zoom in I guess. Unfortunately the green is the same as 0.12!

If someone wants to optimise the list of colours then head over to https://github.com/nodejs/build/blob/master/setup/www/tools/metrics/plot.gp#L12-L19 and put in a PR. I'm far from a colour expert and just grabbed someone else's list that I thought looked good on a graph.

To test your work, grab that file (plot.gp) then run this:

```
$ for t in country version arch os total; do curl -sLO https://nodejs.org/metrics/summaries/${t}.csv; done
$ gnuplot -e "inputdir='./'; outputdir='./'" plot.gp 
```

and you'll end up with .png files for each of them. Help from @nodejs/website experts would be neat.

**Comment by mweagle** [comment]
Handy tool for color selection: https://color.adobe.com/

**Comment by maclover7** [comment]
Is this okay to close?

**Comment by maclover7** [comment]
It seems you like you can see the downloads okay, the colors are just a little messy. Going to close for now, but if someone wants to update the color to something different please reopen.
