### ISSUE TITLE
Travel funding for Collaborators to attend Summit in December

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/build#543]
Hey All,

I wanted to make sure you were all aware of this thread from the TSC repo 

https://github.com/nodejs/TSC/issues/166

TLDR active collaborators in this working group who want to participate in the summit, but cannot get funding from their employers, should feel free to apply

**Comment by Fishrock123** [comment]
@nodejs/build if you really want to come we can probably still squeeze you in but time is running low.

**Comment by jbergstroem** [comment]
I had high hopes for being able to squeeze in two days but it looks like I won't be able to make it :(

**Comment by jbergstroem** [comment]
Summit over, closing.
