### ISSUE TITLE
github bot failed to redeploy

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#544]
After I pushed https://github.com/nodejs/github-bot/commit/015096fa2813e4b23fb9b02866c6ab5d9c53a00f looking at the logs it never redeployed. It had previously redeployed for the older commits though...

cc @nodejs/build, @phillipj

**Comment by jbergstroem** [comment]
@Fishrock123 i'm not sure if it autodeploys. lets see what the norwegian says.

**Comment by rvagg** [comment]
![screen shot 2016-11-17 at 11 32 18 am](https://cloud.githubusercontent.com/assets/495647/20371531/98f57aee-acb9-11e6-9ff0-8227e2946e1b.png)

The webhook service on the machine is running and I've asked GitHub to redeliver it and it's worked and the logs on that server says it's updated now.

A blip with that machine I guess .. `*shrug*`

**Comment by phillipj** [comment]
Have you experienced things like this before? Can't remember noticing similar blips with nodejs.org which more or less has the exact same webhook setup...

One thought for later might be to expose the webhook logs for easier debugging for github-bot team members who doesn't have access to the bot server.

**Comment by rvagg** [comment]
Nope, can't say I have! Perhaps it's due to this particular machine, it's size, resource constraints, network, something like that. Pretty odd but looking in the webhook record on GitHub it's certainly a one-off.
