### ISSUE TITLE
osx1010-release-pkg failing

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#549]
Has failed in last 3 builds (since nightly on Nov 18):

 Example on :  release-voxer-osx1010-x64-1

https://ci-release.nodejs.org/job/iojs+release/nodes=osx1010-release-pkg/1352
```
installing /Users/iojs/build/ws/out/dist-osx/usr/local/include/node/zlib.h
SIGN="Developer ID Application: Node.js Foundation" PKGDIR="out/dist-osx" bash tools/osx-codesign.sh
+ set -e
+ '[' 'XDeveloper ID Application: Node.js Foundation' == X ']'
+ codesign -s 'Developer ID Application: Node.js Foundation' out/dist-osx/usr/local/bin/node
CSSM_SignData returned: 800108E6
out/dist-osx/usr/local/bin/node: errSecInternalComponent
make: *** [node-v8.0.0-nightly20161120440057eae0.pkg] Error 1
Build step 'Conditional steps (multiple)' marked build as failure
```

**Comment by mhdawson** [comment]
Just ran ok on release-voxer-osx1010-x64-2.  The 3 failures were on release-voxer-osx1010-x64-1 so good chance its related to the machine.

**Comment by mhdawson** [comment]
Ran again on release-voxer-osx1010-x64-1 and failed so almost certainly something on that machine. @jbergstreom,  @rvagg

**Comment by rvagg** [comment]
OK, I'll take it out of the pool until I can figure out what the deal is

**Comment by rvagg** [comment]
two of the machines failing .. different reasons but both for signing, have taken them offline for now until I figure it all out and test that they work, we still have a third that seems to work but needs to do a double shift to get the osx assets built.

**Comment by maclover7** [comment]
ping -- is still needed?

**Comment by gibfahn** [comment]
Don't think this is still failing.
