### ISSUE TITLE
Benchmarking www mirror not working ? 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#556]
We updated https://github.com/nodejs/benchmarking/blob/master/www/index.html 3 days ago but it does not seem to have been mirrored to the [https://benchmarking.nodejs.org/](https://benchmarking.nodejs.org/) as expected.

**Comment by mhdawson** [comment]
@rvagg

**Comment by rvagg** [comment]
Our rsync is: `rsync -aqz --delete benchmark:charts/ /home/www/benchmarking/charts/`

Is `index.html` in the root of /home/benchmark/? if we change it to `rsync -aqz --delete benchmark: /home/www/benchmarking/` aren't we going to pick up a lot of guff in /home/benchmark? Perhaps we should shift this all to a subdirectory so we can do a full rsync?

**Comment by mhdawson** [comment]
index.html is in https://github.com/nodejs/benchmarking/tree/master/www.  

What I though was set up was that there were 2 transfers:

1) The first from https://github.com/nodejs/benchmarking/tree/master/www
2) The mirror from the benchmarking machine to get the latest charts which I think is the one you show above.

I thought 1) was possibley setup as a trigger that would push changes when they were committed to the repo.  And I think it worked in the past as there have been a few updates to the index.html file.

**Comment by mhdawson** [comment]
@rvagg, would it make sense to manually transfer over the updated index.html while we figure out whats up ?

**Comment by jbergstroem** [comment]
Not sure if it helps but it looks like images are updated (last update: dec 6) while index.html still remains unchanged as of oct 12.

**Comment by mhdawson** [comment]
@jbergstroem correct.  The graphs are regularly updated. index.html comes from a different place (the benchmarking repo) and it should be updated when the version in the repo changes.

Is that something you can help with or something I can help with (I'm thinking I don't have enough access)

**Comment by mhdawson** [comment]
@jbergstroem still does not not seem to be showing up.  I'm wondering if it might make sense to expand the set of people who can chase down these kinds of issues.

**Comment by jbergstroem** [comment]
@mhdawson you're absolutely right. I still haven't looked at it, and to be frank haven't really prior  this either. What @rvagg seems to mention above is relevant though; index.html is from the parent directory and isn't being picked up in the rsync. Perhaps it can be moved into the "charts" directory and link to images in the same folder? that way it would be easier to rsync?

**Comment by mhdawson** [comment]
Looks like @jbergstroem resolved yesterday and updated occurred last night. Closing.
