### ISSUE TITLE
AIX; ran out of space on /tmp

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#560]
A job failed today because we ran out of /tmp space on test-osuosl-aix61-ppc64_be-2

https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/2438/

Cleaned it up. 

Creating this issue to document and as a place we can capture if it repeats.  And if so figure out how to avoid going forward.

**Comment by mhdawson** [comment]
Seems to have run out again. Not sure why we are having problems today.  The only thing I can think of is maybe the CITGM runs mean we need more /tmp space

https://ci.nodejs.org/job/node-test-commit-aix/2445/nodes=aix61-ppc64/console

**Comment by mhdawson** [comment]
Bumped both aix machines /tmp size with

 chfs -a size=+300000 /tmp

it were ok after that we'll have to add to the Ansible jobs

**Comment by mhdawson** [comment]
Has been ok for the last 5 days and free space on /tmp still looks good on both machines.  Closing.

**Comment by gibfahn** [comment]
be-1 has run out of space again, there was quite a lot of `npm-` and `watchify` directories in there, but most of the space was from these:

```bash
bash-4.3# df -m .
Filesystem    MB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd3         320.00      0.00  100%    45608    62% /tmp
bash-4.3# du -sm * | sort -nr
71.33   6276db7c-1da8-4420-92aa-862871c797c5
37.26   bab451f4-488c-4a61-9587-32ac224457c3
33.22   06d521bd-f86e-4b75-a5f8-4e674344ba6c
23.22   1ab1e7e7-5d0a-48b1-928c-32deb0c9321d
22.31   ced3faad-d7ed-4049-bfb5-1bd9cca4dd02
21.04   17969024-e3e0-40ad-9650-ff2e89cca9c4
16.08   77fa230b-6b7e-446f-a722-89abc740e8ff
12.70   09815a7c-3c6b-42f0-814a-25bd55bd4a53
9.16    cfc64c98-b52e-4fda-8084-a0f2f5cce5b7
6.97    2573b430-09d5-46b6-96a7-fb2a4811616a
6.64    5f91a8f0-93ac-4442-9484-8919374910fd
3.64    4e5af01d-33b8-40c0-998a-964c69b90718
2.13    da43158e-8bdb-4c42-b9ab-0a180f8e2b9d
1.93    baa44f63-92b2-48ca-8b0b-6095d74f756a
1.30    a6f64f82-b7b6-4536-a4c1-9d8d34f72dfd
1.15    074b3e8a-9498-421c-9eaa-2f20954d6744
1.07    npm-2753104-c178f83e
0.92    npm-2752980-c06b9028
```

**Comment by gibfahn** [comment]
I've removed the citgm stuff, so as long as we fix the `/tmp` issues before we add AIX to the citgm runs we should be okay.

```bash
bash-4.3# df -m .
Filesystem    MB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd3         320.00    295.38    8%      680     1% /tmp
```
