### ISSUE TITLE
set git author for the github-bot

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#561]
See https://github.com/nodejs/github-bot/issues/100

I wasn't able to get it to work by setting it globally, but setting it in the cloned node repo worked.

```
git config user.name "nodejs-github-bot"
git config user.email "github-bot@nodejs.org"
```

**Comment by phillipj** [comment]
I'll take a look asap. Any idea why author needs be set when the bot
doesn't try to commit anything?

**Comment by Fishrock123** [comment]
@phillipj Technically it does "commit" stuff -- using `git am` applies with the user as the commiter.

**Comment by phillipj** [comment]
Ah right! I'll try to get it done tonight. Setting that config locally to
that repo rather than global seems fine to you @Fishrock123?

**Comment by Fishrock123** [comment]
@phillipj Either or should be fine. On-repo might be simpler since I could not get globally to work on that machine.

**Comment by phillipj** [comment]
Opened a PR fixing this permanently. It seems to have been set correctly on the server tho, I assume someone has logged in and fixed it by hand.

**Comment by Fishrock123** [comment]
@phillipj (That was me)

**Comment by phillipj** [comment]
Fixed in https://github.com/nodejs/build/commit/857f5900f3cde69080f4f64b2c725bca2d24728f
