### ISSUE TITLE
backup host is running out of space

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#563]
Logged in the other day and saw that we passed 90% disk space (currently sitting at 1.4T). I've redeployed a new host with ~3T storage and are making it ready for replacing. Will update progress here.

**Comment by jbergstroem** [comment]
Rsync complete (yes, I forgot to pass `-H` the first run) . Doing another manual rotation to verify that everything works, but it looks good so far.

**Comment by Fishrock123** [comment]
@jbergstroem Is this complete now?

**Comment by jbergstroem** [comment]
Yes; transfer and first periodic finished on new host. Just want to verify manually before retiring.

**Comment by jbergstroem** [comment]
Just did one more semi-random check that backups works (untar, check contents) and hardlinks usage works as previously. Below output is from a small script that finds duplicates for inodes:

```console

$ ./checkfile.sh /backup/periodic/daily.4/ci.nodejs.org/jobs/node-test-commit/builds/6657/              

Item: /[23186367] = /backup/periodic/daily.4/ci.nodejs.org/jobs/node-test-commit/builds/6657/build.xml
     -> /backup/periodic/daily.2/ci.nodejs.org/jobs/node-test-commit/builds/6657/build.xml
     -> /backup/periodic/daily.5/ci.nodejs.org/jobs/node-test-commit/builds/6657/build.xml
     -> /backup/periodic/daily.1/ci.nodejs.org/jobs/node-test-commit/builds/6657/build.xml
     -> /backup/periodic/daily.6/ci.nodejs.org/jobs/node-test-commit/builds/6657/build.xml
     -> /backup/periodic/daily.3/ci.nodejs.org/jobs/node-test-commit/builds/6657/build.xml
     -> /backup/periodic/weekly.0/ci.nodejs.org/jobs/node-test-commit/builds/6657/build.xml
```

Next step is shutting down the old machine and updating the inventory, but since that's not related to daily backups running (and verified restorable), I'll close this.
