### ISSUE TITLE
temporary access for @matthewloring to smartos

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#568]
@matthewloring needs access to smartos to debug related to [this issue](https://github.com/nodejs/node/pull/9304#issuecomment-266869568). can we get some hands up from the build group?

**Comment by mhdawson** [comment]
+1 from me.

**Comment by jbergstroem** [comment]
I've provided him access to `test-joyent-smartos16-x64-2` as well as basic instructions.

**Comment by gibfahn** [comment]
+1

**Comment by matthewloring** [comment]
I've finished diagnosing the issue and posted an update here: https://github.com/nodejs/node/pull/9304. You're welcome to revoke access now. Thanks!

**Comment by jbergstroem** [comment]
@matthewloring how about we keep the access until the pr is merged? If upstream files a patch I reckon you'd want to test anyway?

**Comment by matthewloring** [comment]
As long as that's ok on your end it would definitely be more convenient for me. I was going to re-request once there was a patch to try.

**Comment by jbergstroem** [comment]
Lets keep it open then.

**Comment by matthewloring** [comment]
This can be closed now.

**Comment by rvagg** [comment]
revoked

thanks @matthewloring!
