### ISSUE TITLE
Enable CI/CD for PRs to iojs/website

### ISSUE THREAD

**Issue by kenperkins** [nodejs/build#57]
Would be nice to have pull requests to iojs/website automatically trigger a build and deployment to a staging server and then comment in the PR With the link to an ephemeral domain.

**Comment by wblankenship** [comment]
The concern was raised during the first WG meeting about running untrusted code on a PR. This was in reference to the iojs codebase though.

That being said, with the website repo, I don't see a reason why we couldn't offload the work to TravisCI or Codeship.

**Comment by jbergstroem** [comment]
I like the approach suggested by @rvagg about having trusted collaborators for full runs within our own ci.

**Comment by wblankenship** [comment]
Would that be overkill for a website repository?

**Comment by jbergstroem** [comment]
Sorry, I somehow missed that this was only about `website`. Yeah, overkill indeed.

**Comment by wblankenship** [comment]
`website` does not have any unit tests and we do not have access to the settings for that repo. If we did propose this to the website WG, what would be the scope of the build team's involvement?

- [ ] Give build team access to website repo to configure and maintain CI.
- [ ] Setup CI server for website repo.
- [ ] CI ensures gulp task completes without error (no guarantee what it generated is correct).
- [ ] Develop unit tests for website repo.
- [ ] Deploy upon a successful CI test after merging into master.

**Comment by rvagg** [comment]
you'd better file an issue over at iojs/website to get buy-in for this, no point in pushing forward if they don't care

**Comment by kenperkins** [comment]
Good point @rvagg, added https://github.com/iojs/website/issues/231

**Comment by mikeal** [comment]
This is a "nice-to-have" but at the top of our list right now is just to trigger the gulp build on each commit/re-deploy so we can stop checking in "rebuild" commits all the time :)

**Comment by kenperkins** [comment]
@mikeal I wasn't capturing this necessarily for "right now" but just to make sure it's in an issue. Do we have an issue for auto build on commit?

**Comment by jbergstroem** [comment]
Arguing that https://github.com/nodejs/build/issues/236 is more relevant and contains more info. Also, auto-testing PR's are ways off. Closing.
