### ISSUE TITLE
test/arm reported as failure when it passed for a PR

### ISSUE THREAD

**Issue by targos** [nodejs/build#572]
Examples:
- https://github.com/nodejs/node/pull/10301
- https://github.com/nodejs/node/pull/10317

**Comment by gibfahn** [comment]
Hmm, this is still happening, https://github.com/nodejs/node/pull/10517 (https://ci.nodejs.org/job/node-test-commit/6915/) for a CI run that's still in Jenkins.

**Comment by jbergstroem** [comment]
Can confirm. The jenkins script for notifying is likely to blame and I've looked at it a few times; can't quite figure it out. Still on it.

**Comment by joaocgreis** [comment]
Should be fixed. It was running the two scripts (for success and failure) unconditionally, so it would mark it as success and immediately mark it as failure. I tested with a success, I don't have a PR that fails to test.

**Comment by joaocgreis** [comment]
AIX was reporting success when the job fails, so I changed it as well but did not test (cc @mhdawson)

**Comment by gibfahn** [comment]
I've confirmed that the AIX reporting is fixed.

 | Before/After Fix | PR | CI Job | PR Reported | CI Reported |
| --- | --- | --- | --- | --- | 
| Before | [11852](https://github.com/nodejs/node/pull/11852) | [8483](https://ci.nodejs.org/job/node-test-commit/8483/) | 💚  | 🔴  | 
| After | [9163](https://github.com/nodejs/node/pull/9163) | [8493](https://ci.nodejs.org/job/node-test-commit/8493/) | 🔴  | 🔴  | 
| After | [11856](https://github.com/nodejs/node/pull/11856) | [8495](https://ci.nodejs.org/job/node-test-commit/8495/) | 💚  | 💚  |

**Comment by joaocgreis** [comment]
@gibfahn thanks!
