### ISSUE TITLE
Show 'Change' Log of a Project more than the Limit

### ISSUE THREAD

**Issue by ArivRedgrape** [nodejs/build#573]
Hi,

We have a jenkins build job 'xxxxx' which limits the No. of builds to keep as 5. 

However whenever I check the change log (ie. list of checkins for a particular build#) it is showing only for the last 5 build.

Could anyone help to get the last 30 days Change log ONLY - I don't want the builds to be occupying the space.? or is increasing the "Max # of build to keep" is the only option to retain the changelogs?

Thanks in advance,
Ariv

**Comment by gibfahn** [comment]
This seems like a general Jenkins question. Is this related to the Node.js Jenkins build farm (https://ci.nodejs.org/)? Assuming it's not, I'll close this. Let me know if I'm mistaken.

For general Jenkins questions, you should probably try [stackoverflow](http://stackoverflow.com/questions/tagged/jenkins), which has a lot of Jenkins questions already.
