### ISSUE TITLE
Build WG meeting 20-12-2016

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#574]
### When

December 20th 2016, 8pm UTC: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Build+WG+Meeting&iso=20161220T20&p1=%3A

### Where
- Hangouts on Air, for participants: https://hangouts.google.com/call/t4tq4yjfhvhwdmndreid5gv6yme
- Youtube stream, for viewers: https://www.youtube.com/watch?v=-93fTN8M2BE
- Minutes document: https://docs.google.com/document/d/1-joUlwaNYirwDlG9sFUyrHKa43ljgRPpj5o-Ygv9JRc

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.
- file and directory names for downloads #515
- Draft text for HSTS communication #484
- TAP Plugin issues on Jenkins #453
- rsync endpoint to mirror the releases #55
- Looking for issue good for first contribution #495 

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by Trott** [comment]
I'll likely be missing this one, I'm afraid.

**Comment by piccoloaiutante** [comment]
I'll be missing it but I just wanted to say that the PR for optimising windows provisioning in Ansible is almost ready. I didn't open it yet because I'm still missing a full testing on Windows 2008 server R2. I tried many times but I wasn't able to run Ansible script over it. @joaocgreis are you able to make a test over this platform? Should I open the PR?  I already tested it on windows server 2012 and windows 10 and it worked.

**Comment by joaocgreis** [comment]
@piccoloaiutante please open the PR, I can test it on 2008R2. Thanks!

**Comment by piccoloaiutante** [comment]
@joaocgreis done https://github.com/nodejs/build/pull/576 . Let me know if you need anything else. Thanks!

**Comment by gibfahn** [comment]
PR for minutes: #577

**Comment by gibfahn** [comment]
Minutes merged, closing this...
