### ISSUE TITLE
Correctly identify pLinux LE and BE in the Github CI plugin

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#575]
Sometimes the Github plugin for CI runs shows a `linux-ppc` and a `ppc-linux`. `linux-ppc` seems to cover pLinux-BE and pLinux-LE, and `ppc-linux` seems to only cover pLinux-LE. If both pass, only the `ppc-linux` tag is shown.

I assume this is something that is configured in the jobs, but as I can't see the configuration I can't confirm. 

![image](https://cloud.githubusercontent.com/assets/15943089/21323061/d9517caa-c613-11e6-8933-721b6a3e6155.png)

Example of a job with both: https://github.com/nodejs/node/pull/10318

cc/ @sam-github

**Comment by jbergstroem** [comment]
They were indeed not consistent. I've fixed it in the jenkins job. Closing; reopen if you still see it!
