### ISSUE TITLE
ci host is running out of space

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#578]
Every worker generates about 3-4mb of logs for a PR. Since we're averaging 15-20 jobs a day these tend to stack up. Two actionables:

1. Expand disk space on ci host (currently 300G)
2. Revisit the 'compress logs after completion' plugin which doesn't seem to work

**Comment by maclover7** [comment]
ping -- does this need to stay open?

**Comment by rvagg** [comment]
no! fixed this completely by introducing the 2 jenkins-worker hosts!
