### ISSUE TITLE
fedora 25!

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#579]
Almost a month old. Kid grew up quick!

Seeing how fedora22 eol'ed in july, how about we retire it while introducing 25?

**Comment by gibfahn** [comment]
+1 to retiring fedora 22 if it's been EOL for 6 months. Does that mean it won't be supported in 8 (so it will be supported until v6 EOL)?

**Comment by jbergstroem** [comment]
Since this is still floating I'm not sure how we'll handle 'official' support: https://github.com/nodejs/node/pull/8922

**Comment by jbergstroem** [comment]
Also, I don't think we are specific in terms of os'es we support or don't other than what we build against.

**Comment by jbergstroem** [comment]
I have two vm's on rackspace running; worked fine with the current refactor. Attaching them to jenkins tomorrow!

**Comment by jbergstroem** [comment]
build just passed: https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora25-x64/6938/

Does anyone object against retiring 22? No document to update in main repo, so to speak..

**Comment by jbergstroem** [comment]
> @jbergstroe said:
> Does anyone object against retiring 22? No document to update in main repo, so to speak..

Actually, let me check with libuv first..

**Comment by jbergstroem** [comment]
ping @saghul, @bnoordhuis, ?

**Comment by saghul** [comment]
No objections from me!

**Comment by bnoordhuis** [comment]
Likewise.

**Comment by jbergstroem** [comment]
Cool. I'll go ahead and retire fedora 22 shortly then.

**Comment by maclover7** [comment]
22 has been removed from ci.nodejs.org as far as I can see, 25 has been added, so I think this is done now. Going to give this a close, please reopen if necessary.
