### ISSUE TITLE
releases - blocked on release-digitalocean-cento5-x64

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#581]
release-digitalocean-cento5-x64 seems to have been offline since jan 1

Nightly builds from Jan 1 and Jan 2 are still running waiting on that machine.

**Comment by mhdawson** [comment]
@rvagg @jbergstroem can one of you take a look as I don't have access to the release machines.

**Comment by jbergstroem** [comment]
It's back online. Must've rebooted and jenkins never came back online.

**Comment by mhdawson** [comment]
Thanks ! nightly jobs complete closing.
