### ISSUE TITLE
temporary test server access for @thefourtheye

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#583]
In order to resolve issues for a set of hosts with stalling tests related to https://github.com/nodejs/node/pull/10456, @thefourtheye is requesting access to a few machines. 

@thefourtheye could you perhaps list the one's you want to do further investigation with so we can approve and arrange it?

**Comment by thefourtheye** [comment]
Whenever I run CI on that PR, the leftover processes will be there in almost all the machines. So I'll have to clean them in all of them. I am fixing them case by case basis, e.g https://github.com/nodejs/node/pull/10597 fixes SmartOS failures (hopefully).

Is it possible to get permissions for all of them?

**Comment by jbergstroem** [comment]
Since Linux looks mostly ok, how about we for instance start with smartos, plinux and windows? I can facilitate the former; not sure how we create temporary accounts for windows. @joaocgreis?

**Comment by Trott** [comment]
The only ones that I noticed stalled jobs on were SmartOS and FreeBSD, so I'd be sure to include access to those two at a minimum.

**Comment by jbergstroem** [comment]
@Trott: @thefourtheye mentioned he was running FreeBSD locally and that the failures/stalls was similar across os'es. I think he's doing local testing at the moment.

**Comment by thefourtheye** [comment]
Setting up the FreeBSD vm in a slow internet connection. I'll update the status about that tomorrow.

**Comment by mhdawson** [comment]
Let me or @gibfahn know when you need access to plinux/aix

**Comment by jbergstroem** [comment]
I can arrange it as well; seems like we have me and @mhdawson (so far?) approving your access.

**Comment by gibfahn** [comment]
+1 to giving @thefourtheye access

**Comment by joaocgreis** [comment]
I also approve giving @thefourtheye access. According to our docs, giving temporary access to a collaborator can be done immediately, so I went ahead and created a temporary account on a Windows machine (emailed credentials). Given that stalling tests can interfere with normal CI runs, I disconnected the machine from CI.

**Comment by jbergstroem** [comment]
@joaocgreis true. I will help facilitate the rest on demand, as well as making a note here on when access is granted and finally revoked.

**Comment by mhdawson** [comment]
To confirm +1 from me.

**Comment by thefourtheye** [comment]
Thanks people :-) I finally managed to setup a FreeBSD instance locally and test this. https://github.com/nodejs/node/pull/10822 looks like fixes it. PTAL.

**Comment by joaocgreis** [comment]
@thefourtheye Still using the machine? If you are, no rush, just let me know when you're done!

**Comment by gibfahn** [comment]
ping @thefourtheye @joaocgreis , I think this can be revoked now.

**Comment by thefourtheye** [comment]
@gibfahn @joaocgreis Yes, this can be revoked now. Thanks :-)
