### ISSUE TITLE
Jenkins access for CitGM team

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#584]
Now that #554 has landed we can start giving teams access to their Jenkins jobs. For the CitGM team the jobs beginning with `citgm-` are the ones that the CitGM team should have permissions for. If no-one objects we should set the run/modify permissions for these jobs to the @nodejs/citgm team.

#### Jobs:
 - https://ci.nodejs.org/view/All/job/citgm-smoker-yarn/
 - https://ci.nodejs.org/view/All/job/citgm-smoker-rebuild/
 - https://ci.nodejs.org/view/All/job/citgm-smoker/
 - https://ci.nodejs.org/view/All/job/citgm-abi-smoker/

#### People in the citgm team:
 - @bengl
 - @bzoz
 - @gdams
 - @gibfahn
 - @jasnell 
 - @MylesBorins

**Comment by gibfahn** [comment]
@nodejs/build any objections/thoughts? It'd be really useful to get this approved/done so that @gdams and @bzoz can run citgm jobs.

**Comment by gdams** [comment]
This would be really useful

**Comment by jbergstroem** [comment]
sounds good to me.

**Comment by mhdawson** [comment]
+1 from me

**Comment by gdams** [comment]
@mhdawson do you have the permissions to give us access to the CI or do we need to CC someone else?

**Comment by mhdawson** [comment]
I'm looking at it right now :). If you are around I'll ping you in a few minutes to see if you can try it out for me.

**Comment by gdams** [comment]
@mhdawson I'm on slack for the next hour or so :)

**Comment by mhdawson** [comment]
Ok as per doc, access to start jobs has been grated to all members of the citgm team.  Will now setup citgm-admin team, add Myles as initial member and let citgm team use process to nominate others that will be able to create/modify jobs.

**Comment by mhdawson** [comment]
Ok, create citgm-admins and the 4 CITGM jobs are now configured so that they can be created/modified by the members of that group.  Initially I've made Myles the only member of the group.

**Comment by mhdawson** [comment]
Ok, CITGM team went through process and George is now in the citgm-admins group and seems to be able to edit jobs.  Going to close this and we can reopen if something more is required.
