### ISSUE TITLE
4.7.1 release missing x64 sunos packages

### ISSUE THREAD

**Issue by geek** [nodejs/build#585]
https://nodejs.org/dist/v4.7.1/ is missing the following packages

- node-v4.7.1-sunos-x64.tar.xz
- node-v4.7.1-sunos-x64.tar.gz

**Comment by MylesBorins** [comment]
I don't even see sunos as a machine in the ci-release infra

/cc @jbergstroem

**Comment by gibfahn** [comment]
Looks like https://nodejs.org/dist/v4.7.0/ is the same (and probably previous ones as well)

**Comment by jbergstroem** [comment]
smartos machine are added with respective smartos-XX tags. 13 is used for 0.x (pre-1.x tag) and 14 for 1.x and forward (post-1.x tag; subject to change as of v8 55 -- using smartos15 jenkins tag for unknown reasons). They are later matched with [OSTYPE=solaris](https://github.com/nodejs/build/blob/master/setup/smartos/resources/jenkins_manifest.xml.j2#L21). So, I'm not sure why that conditional isn't triggering.

**Comment by joaocgreis** [comment]
The conditional was triggering fine, but there was a subtle error in the x64 portion of the script (line brake "`\`" with a space after it). Should be fixed now: https://nodejs.org/download/test/v4.7.1-test201701051035318070/ . Please reopen if not.
