### ISSUE TITLE
Ongoing access to Kunal Pathak to Jenkins jobs and new Windows Server 2016 test slaves

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#587]
@kunalspathak would like to set up a few Windows Server 2016 instances for testing and add them to the Windows job in CI. He will help us with maintaining those machines afterwards.

Hence, I'd like him to be added to the @nodejs/jenkins-admins team, and let him keep access to the new slaves he creates. 

Kunal is not a core collaborator, but has been maintaining and very active in https://github.com/nodejs/node-chakracore since it was created. He is a Microsoft employee so consequences of misbehavior would be severe, and I can vouch for him.

Ref: https://github.com/nodejs/build/tree/master/doc/process

cc @nodejs/build

**Comment by mhdawson** [comment]
+1 from me.

**Comment by gibfahn** [comment]
+1

**Comment by jbergstroem** [comment]
Me too; +1

**Comment by kunalspathak** [comment]
It seems people are in favor of giving me Jenkins access :)
@mhdawson , can you please give me access?

**Comment by mhdawson** [comment]
Ok added.

**Comment by joaocgreis** [comment]
Windows Server 2016 is now added to the CI matrix.

Thanks @kunalspathak !
