### ISSUE TITLE
Reproducable builds

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#589]
This is a task for someone to pick up who has the time and interest in this area. It's likely not going to be a small job even to get to a proposal of what we need to do.

1. Research what is possible and required for us to produce reproducable builds
2. Draft a proposal for how we need to change our build architecture and published artifacts to share reproducible build data with the public so anyone can compile binaries that are byte-for-byte identical to what we produce.

Some starting points: https://reproducible-builds.org/ and the work Debian has been doing to switch their published artifacts to reproducables: https://wiki.debian.org/ReproducibleBuilds

**Comment by gibfahn** [comment]
This node-gyp issue seems related: https://github.com/nodejs/node-gyp/issues/1100

**Comment by Trott** [comment]
Still something we'd like to do, I imagine? Should we put this on the agenda for a meeting or something to try to get some traction? Maybe this is an opportunity for someone to be a mentor to an eager individual via the mentorship program that's just getting started?

**Comment by lrvick** [comment]
My org is very interested in this. I have done reproducible build work for other projects, and even a list of known issues would go a long way to help me know what path to take.

**Comment by refack** [comment]
Hello @lrvick, would you be willing to help us and break down the items required for us to achieve this? That would be a great help, and very much appreciated.

**Comment by ChALkeR** [comment]
I took a look at this.

The benefit of introducing baseline reproducible builds would not only meaningful to ensure trust, but also for other scenarios, e.g.:
1. Once builds in a certain environment are reproducible, we could detect when and how switching/updating the environment affects build result.
2. It could be useful for testing -- tooling changes often shouldn't affect the build result, and if they do -- something wrong happened.

I checked what happens with two subsequent builds now on mac in the same environment, and things are not that bad:
1. File modification timestamps go into `*.pyc` files and affect the build result. That could be negated by targeting reproducibility for tarballs (which preserve timestamps) for now, and postponing git checkouts.
2. Environment should be controlled -- compiler versions etc. affect the build result. This is easiest controlled on Linux.
3. _Two_ generated `*.cc` files differ each time: `node_code_cache.cc` and `node_snapshot.cc`. Those are not reproducible, we should target that first, I believe. The latter one could be disabled by a config option.
4. All generated binary files are different, while object files all match except for those two files above. Something is happening on the linker stage. Not yet confirmed this on Linux.

Imo, we could target the first step baseline for reproducible builds for now as: fixed environment, Linux-only (easiest to control environment on), from a same tgz.

That baseline should not be _very_ hard, I presume, and even that could be valuable on its own, and could result in producing reproducible builds for Linux releases once the environment is fixated.

**Comment by ChALkeR** [comment]
Just tested on Linux (with same restrictions), results:
```
Files node-v12.8.0-1/node and node-v12.8.0-2/node differ
Files node-v12.8.0-1/out/Release/node and node-v12.8.0-2/out/Release/node differ
Files node-v12.8.0-1/out/Release/obj/gen/node_code_cache.cc and node-v12.8.0-2/out/Release/obj/gen/node_code_cache.cc differ
Files node-v12.8.0-1/out/Release/obj/gen/node_snapshot.cc and node-v12.8.0-2/out/Release/obj/gen/node_snapshot.cc differ
Files node-v12.8.0-1/out/Release/obj.target/node/gen/node_code_cache.o and node-v12.8.0-2/out/Release/obj.target/node/gen/node_code_cache.o differ
Files node-v12.8.0-1/out/Release/obj.target/node/gen/node_snapshot.o and node-v12.8.0-2/out/Release/obj.target/node/gen/node_snapshot.o differ
```

Looks like the linker issue could be macOS-specific, but we have an issue with unreproducible `node_code_cache.cc` and `node_snapshot.cc` generation. That is a blocker for reproducible builds afaik, and it should be fixed first.

**Comment by ChALkeR** [comment]
https://github.com/nodejs/node/issues/29108 is not fixed (thanks, @bnoordhuis), and two consequent builds from the same archive in the same dir on linux now produce identical results (given the same environment).

The next step should be fixing the enviroment and the build path.

* Removing the "unpack from archive" restriction produces differences only in `*.pyc` files (due to source file modification timestamps being present there) that are artifacts of the build process are not distributed. That restriction could be safely ignored, I suppose.
* Removing the "build from the same path" restriction produces differences in generated binaries. That is something that could perhaps be fixed on Node.js core side, but I am not yet sure if that is a blocker here.

**Comment by sam-github** [comment]
@ChALkeR is this ongoing? complete? Closable as stale?
