### ISSUE TITLE
Incorrect SHASUM method listed for 4.4.7

### ISSUE THREAD

**Issue by mpstein** [nodejs/build#592]
* **Version**: 4.4.7
* **Link**: https://nodejs.org/dist/v4.4.7/SHASUMS256.txt.asc

The CRCs for the NodeJS version 4.4.7 downloads are listed as being hashed via SHA1 when they are hashed using SHA256. Please see the header on [NodeJS 4.4.7 SHA verification](https://nodejs.org/dist/v4.4.7/SHASUMS256.txt.asc).

**Comment by MylesBorins** [comment]
Fixed
