### ISSUE TITLE
Document nightlies

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#593]
There was a recent question about what nightly builds we generate.  

The node core readme says:

Nightly: Versions of code in this repository on the current Current branch, automatically built every 24-hours where changes exist. Use with caution.

In the past I think I've seen us generate ones for both master and current.  Looking in https://nodejs.org/download/nightly/ there also seem to be recent'sh ones for 6.x (ex https://nodejs.org/download/nightly/v6.9.5-nightly201701061a47e5f409/)

Would like to use this issue to capture what we are/should be doing.

I was thinking that a nightly for master and current was what we were doing, and what makes the most sense to me.

Once we capture the info here I think we should also doc how they are triggered (if they are not already) and make any needed updates to the node core readme.  I'll volunteer to do that once we capture what it is/should be.  

Appologies in advance if it is capture somewhere already and I've just not found it.

**Comment by mhdawson** [comment]
We generate nightlies when there is a code change

For 4 and 6 the nightlies make sense if they come off the staging branches

4,6,7 and master

João will point me at the scripts and I'll put together a PR to doc

**Comment by joaocgreis** [comment]
Nightlies are started by the www server, as configured here: https://github.com/nodejs/build/blob/2ac05fe/setup/www/tasks/tools.yaml#L9-L30 .

This uses `nodejs-nightly-builder` from https://github.com/nodejs/nodejs-nightly-builder .

The `crontab` in the server matches the Ansible script, so we are releasing nightlies from the `v6.x`, `v7.x` and `master` branches. This was introduced by @rvagg in https://github.com/nodejs/build/commit/9678bd21937e71020b828b362edecfbec0a920b2 , before there was a `nightly-builder` but I don't know how it was started.

I think that building nightlies from all active `*-staging` branches (and `master`) would make more sense, perhaps @nodejs/lts wants to weight in on this.

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
