### ISSUE TITLE
skip v8 on smartos14

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#595]
As part of landing https://github.com/nodejs/node/pull/9618 we need to skip running it on smartos14 since support is dropped. I don't know a convenient way of dropping out of a build early without running into fails based on subsequent tasks (collecting tap, etc). If anyone have suggestions on how to bail early that'd be helpful. The other option is to make all subsequent tasks not fail on previous build status (making assumptions) but requires a refactor.

**Comment by targos** [comment]
There is also ubuntu1204-clang341-64 to skip

**Comment by targos** [comment]
I am willing to help here. Is there anything I can do?

**Comment by targos** [comment]
Perhaps we can use https://wiki.jenkins-ci.org/display/JENKINS/Conditional+BuildStep+Plugin and read https://github.com/nodejs/node/blob/master/src/node_version.h#L4 ?

**Comment by jbergstroem** [comment]
In release builds to distinguish workers based on node version we currently do something like:
```console
NODE_VERSION=$(python tools/getnodeversion.py)

if [[ $ARCH =~ s390x && ${NODE_VERSION:0:1} -lt "6" ]]; then
  echo "Not building $disttype on linuxOne slave as only supported on v6.x and later"
  exit 0
fi
```

The tricky part is exiting a job early. Perhaps its not tricky at all -- I just don't know how to do it without failing the job.

**Comment by gibfahn** [comment]
It's a bit of a hack, but if the problem with exiting early is that the TAP plugin won't find a tap file, you could always generate a file with a single skipped test, something like:

```bash
cat >"test.tap" <<-EOF
1..1
ok 1 # SKIP Not building $disttype on linuxOne slave
EOF
```

That way it'd show up yellow (if you wanted it green you could just not use the skip). Not sure if that'd be enough to work.

**Comment by ofrobots** [comment]
Is there anything that can be done to move this forward? V8 5.5 was released more than a month ago but we haven't been able to land it in master because of this issue. Being able to release Node.js nightly builds with the latest stable V8 helps find bugs early.

**Comment by mhdawson** [comment]
I have this in the v8 nightly test jobs:
```
 # 390 is only supported on v6 and later for now
 MAJOR_VERSION=`cat src/node_version.h |grep "#define NODE_MAJOR_VERSION" | awk '{ print $3}'`
 if [ "$MAJOR_VERSION" -lt "6" ]; then
   RUN_TESTS="DONT_RUN"
 fi
fi
```

if [ "$RUN_TESTS" = "RUN" ]; then
  #make -j $(getconf _NPROCESSORS_ONLN) v8 $DISABLE_V8_I18N_OPTION DESTCPU=$DESTCPU ARCH=$DESTCPU.release $ADDITIONAL_CLANG_OPTIONS

  # when run under jenkins the d8-os.js test hangs because signals don't set to the process when a os.process times out
  # it works just fine when run from the command line so its not an issue with v8 itself.  I'd like to figure out why
  # it fails under jenkins but so far have not managed to so remove this test before running
  rm deps/v8/test/mjsunit/d8-os.js || true
  make -j $(getconf _NPROCESSORS_ONLN) test-v8 $DISABLE_V8_I18N_OPTION DESTCPU=$DESTCPU ARCH=$DESTCPU.release $ADDITIONAL_CLANG_OPTIONS ENABLE_V8_TAP=True V8_EXTRA_TEST_OPTIONS="--progress=dots --timeout=120" 
else
  echo $SKIP_MESSAGE
  # fake out so we don't get failures
  echo '<testsuite tests="1"><testcase name="none/none.none test were skipped" time="0.001"/></testsuite>' >v8-tap.xml
fi

**Comment by mhdawson** [comment]
Which fakes out the tap file as @gibfahn suggested

**Comment by jbergstroem** [comment]
@mhdawson perhaps you can edit the node-test-smartos job and add it?

**Comment by jbergstroem** [comment]
Unless anyone else from the build group steps up I'll do my best to get this accomplished in the coming day.

**Comment by mhdawson** [comment]
Starting up update now. 

First step is cloned job I can test it out on.

**Comment by mhdawson** [comment]
Just running some tests now, should be ready soon.

**Comment by mhdawson** [comment]
Main job updated, running CI on original PR that was blocked: https://ci.nodejs.org/job/node-test-pull-request/6052/

**Comment by mhdawson** [comment]
the 2 smartos platforms ran/green reporting that tests were skipped as not supported, other platforms running so this should be done closing and we can reopen if there is some later problem.

**Comment by jbergstroem** [comment]
@mhdawson great work; thanks for helping out.

**Comment by mhdawson** [comment]
ok I see there is still work for ubuntu1204-clang341-64, I only did the smartos part

**Comment by mhdawson** [comment]
for ubuntu1204-clang341-64 is it that we don't support this for Node vergions > 8

**Comment by mhdawson** [comment]
Testing skip of build/test for linux flavors with clang in the name for Node version >8.  Once I get confirmation that is what we need I'll swap into the regular job.

**Comment by mhdawson** [comment]
Ok, tests look good, ready to swap into regular job, just want to confirm with @jbergstroem that simply skipping ubuntu1204-clang341-64 for Node version >8 is the right thing to do.

**Comment by jbergstroem** [comment]
@mhdawson yeah, that's what I read out of it as well.

**Comment by targos** [comment]
Thanks for doing this @mhdawson !
I think skipping is the correct thing to do. There is no good reason to keep supporting this clang version.

**Comment by mhdawson** [comment]
Ok CI run on PR where issue was raised was all green, closing.
