### ISSUE TITLE
temporary access to joyent-alpine34 for @santigimeno

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#597]
There's currently a few failed tests on alpine34 in libuv-land: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-linux/nodes=alpine34-x64/228/console

I would like to provide @santigimeno temporary access to a host to debug these.

edit: wrong github username, lazy copy&paste from irc.

**Comment by bnoordhuis** [comment]
Good idea, +1, but I think you mean @santigimeno?

**Comment by Trott** [comment]
+1 💯 👍

**Comment by jbergstroem** [comment]
Sweet. I'll set it up.

**Comment by santigimeno** [comment]
I'm done for the moment. Thanks!

**Comment by jbergstroem** [comment]
> @santigimeno said:
> I'm done for the moment. Thanks!

Revoked access. 

The issue here is that the LX layer provided by joyent is behaving differently from other linux kernels. See https://github.com/libuv/libuv/issues/1206 for more info.
