### ISSUE TITLE
Build jobs for ABI stable module API work

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#604]
Its now the time that we should be setting up ci jobs to test the ABI stable module API.  The current plan is to merge (under build flag) in time for version 8 and if we use the standard infrastructure we will then be able to easily merge testing into the regression process.

Unless there are objects this would be the plan:

1) create a new team called abi-stable-node-admins who will be able to modify/configure jobs.  There is already an existing team called 'abi-stable-node' with the members actively contributing to the work.
2) Add the members who will be working to configure the ci jobs to abi-stable-node-admins 
3) Create 2 blank jobs that can be filled in by those in abi-stable-node-admins 
4) Configure the blank jobs as outlined in https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md so that the jobs can b run by those in the abi-stable-node team, and can be configured/modified by those in abi-stable-node-admins.

@nodejs/build sound good ?

**Comment by mhdawson** [comment]
Assume not comments is no objection since this is in line with the agreed policy, will start to setup today.

**Comment by gibfahn** [comment]
SGTM as long as it's documented

**Comment by joaocgreis** [comment]
SGTM. You'll have to know what type of job to create (Freestyle, Multiconfig, Multijob) when creating them because that can't be changed later without deleting and re-creating.

**Comment by gibfahn** [comment]
>You'll have to know what type of job to create (Freestyle, Multiconfig, Multijob)

Presumably for CI the jobs will probably all be multiconfig jobs

**Comment by mhdawson** [comment]
Ended up cloning existing node.js core jobs since they fit what was needed.

Leaving issue open until we get the docs in place across CITGM/node-report and post-mortem

**Comment by Trott** [comment]
It has been more than two years since there was activity on this issue. Should it remain open?

**Comment by mhdawson** [comment]
This can be closed.  The jobs have been created and have been running for a long time,
