### ISSUE TITLE
Build WG meeting Feb 7 2017

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#607]
### When

Feb 7, 2017 3 PM EST 

### Where
- Hangouts on Air, for participants:  https://hangouts.google.com/hangouts/_/ytl/oefFhZpJxiAGtWAMfxo8i_v2SgNTVM7T6cwLkWeAX1M=?eid=100598160817214911030&hl=en_US&authuser=0
- Youtube stream, for viewers:  http://youtu.be/iQzSe3aaL0U
- Minutes document: https://docs.google.com/document/d/1A4Uv3gYoNxZONbRe6P_h36tphQotkObq8neHIXxJhrg/edit?usp=sharing

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

file and directory names for downloads:https://github.com/nodejs/build/issues/515
Draft text for HSTS communication https://github.com/nodejs/build/issues/484
TAP Plugin issues on Jenkins: https://github.com/nodejs/build/issues/453
rsync endpoint to mirror the releases: https://github.com/nodejs/build/issues/55

Document nightlies: https://github.com/nodejs/build/issues/593
Reproducable builds: https://github.com/nodejs/build/issues/589
Cache CI downloads: https://github.com/nodejs/build/issues/599

If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by mhdawson** [comment]
@nodejs/build please chime in if you can make it.

**Comment by Trott** [comment]
I'll be missing this one.

**Comment by jbergstroem** [comment]
It'll be clutch for me -- if it's on I will be a few mins late.

**Comment by mhdawson** [comment]
Give the response lets make it next week instead.
 @nodejs/build please chime in if you can make Feb 7 at 3 EST.

**Comment by Trott** [comment]
The Feb 7 time is also bad for me (at least as of now) but hopefully it works for others....

**Comment by mhdawson** [comment]
Ok so lets do it today, I'll set up the hangout

**Comment by mhdawson** [comment]
@nodejs/build updated with hangouts info for meeting today.

**Comment by piccoloaiutante** [comment]
@mhdawson can you add me to the hangout?

**Comment by mhdawson** [comment]
Link to new hangout https://hangouts.google.com/hangouts/_/ytl/oefFhZpJxiAGtWAMfxo8i_v2SgNTVM7T6cwLkWeAX1M=?eid=100598160817214911030&hl=en_US&authuser=0

@piccoloaiutante you should be able to join the meeting is open

**Comment by mhdawson** [comment]
Link for those that just want to watch http://youtu.be/iQzSe3aaL0U

**Comment by mhdawson** [comment]
PR for minutes https://github.com/nodejs/build/pull/620

**Comment by gibfahn** [comment]
Minutes landed.
