### ISSUE TITLE
Release Feed

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#608]
Would it be possible to create a feed that we could ping whenever we promote a build?

Things that could be included

* Links to releases
* SHA's of releases
* Version of release

**Comment by feriancek** [comment]
RSS ftw

**Comment by mhart** [comment]
I use this atm: https://nodejs.org/en/feed/blog.xml

**Comment by mhart** [comment]
(would love emails though tbh)

**Comment by rrijnberk** [comment]
I think it would be nice to have an update channel with issue numbers and tags so it would be possible to create hooks for updates that are personally relevant

**Comment by jasnell** [comment]
There's always this: https://github.com/nodejs/node/releases.atom

**Comment by rvagg** [comment]
@MylesBorins given that we have the RSS for the releases on the blog, can you be more specific on what you'd like to see that isn't available there? Perhaps a more specific format containing the items in parsable form? Also the use-case would be helpful here too.

Email is an interesting one, we could trigger that from the server whenever a new blog post goes live, pull out the data from the post and email that. We'd have to allow signups from arbitrary people though so either we need to write something new or use an existing service. We have mail capabilities via rackspace but nothing beyond basic there. Suggestions welcome!

**Comment by MylesBorins** [comment]
I was unaware of the RSS for the Blog... my thought was a feed directly tied to the release promotion that included the meta data I mentioned above. The use case would be to enable others to automate their build infra that does stuff when we release e.g. docker-node, IBM sdk, google sdk

**Comment by chorrell** [comment]
Being able to automate the docker-node updates would be great!

**Comment by MylesBorins** [comment]
ping regarding release feed
