### ISSUE TITLE
CI jobs for postmortem group

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#610]
Setting up initial jobs for post-mortem WG in https://github.com/nodejs/build/issues/594

To allow members of the postmortem WG to be able to run/configure these jobs plan to set up as per https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md

Unless there are objects this would be the plan:

* create a new team called post-mortem-admins who will be able to modify/configure jobs. There is already
  an existing team called 'post-mortem' with the members actively contributing to the work.
*  Add the members who will be working to configure the ci jobs to post-mortem-admins
* Modify job setup under #594 so that it can be accessed by those in the post-mortem and post-mortem-admins team
  
@nodejs/build let me know if there are any objections.

**Comment by gibfahn** [comment]
SGTM, but we should make sure this is documented (probably in the post-mortem repo README).

**Comment by mhdawson** [comment]
@gibfahn is there the plan to do the equivalent for citgm.  If so I'd like to just copy the text to do what we need for the post-mortem README.

**Comment by mhdawson** [comment]
teams created, added Richard C to admin team initially as I think he'll be the first person from the post-mortem team that may need to modify the post-mortem jobs. The post-mortem WG can add additional people as needed.

**Comment by mhdawson** [comment]
Jobs are in place, just leaving this open until we close on the doc. @gibfahn @gdams can one of you update the CITGM readme to doc the jobs used there and then I'll replicate that to the node-report repo.

**Comment by maclover7** [comment]
Job was created: https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/
