### ISSUE TITLE
Do we have any IPv4 only hosts?

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#612]
We've been seeing a number of failures in CI due to machines without IPv6 failing to run tests that had passed CI runs before landing (e.g. https://github.com/nodejs/node/pull/10854).

I *think* that this means that we don't have any machines that don't have IPv6 capability. If this is the case I think it would be useful to add at least one for CI runs.

cc/ @mhdawson

**Comment by jbergstroem** [comment]
I don't think so but we could always set one up I guess?

**Comment by gibfahn** [comment]
Maybe we could just disable IPv6 on one of our Linux boxes?

**Comment by maclover7** [comment]
ping @gibfahn, is still an issue

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
