### ISSUE TITLE
[ci/osx] xcode-select: error: tool 'xcodebuild' requires Xcode

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#615]
See e.g. https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1010/7664/console:
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

**Comment by gibfahn** [comment]
I think this is a duplicate of https://github.com/nodejs/node-gyp/issues/569#issuecomment-259421050 (also see https://github.com/nodejs/node-gyp/pull/1057). Basically the xcodebuild tool is only available in the full Xcode version, but it doesn't actually seem to be doing anything in node=gyp.

So the proper fix would be to submit a version of https://github.com/nodejs/node-gyp/pull/1057 to gyp, but in the meantime the errors can be ignored.

**Comment by bnoordhuis** [comment]
I don't remember seeing them before though.  Did something change on the OS X buildbot?

**Comment by thefourtheye** [comment]
> xcodebuild tool is only available in the full Xcode version

Actually `xcodebuild` expects XCode to be available, but it found just Command line tools. I recently uninstalled XCode while helping someone (https://twitter.com/dFourthi/status/828154632077668352), and I started getting this message after that. It doesn't affect the build though.

**Comment by bnoordhuis** [comment]
Okay, if it isn't really a bug I'll go ahead and close.  Thanks for the replies.

**Comment by saraahmad1114** [comment]
I have Xcode installed and that was one of the very first things I installed but I am still getting this error, I have a whole project running on xcode, so I don't know what else to do

**Comment by gibfahn** [comment]
>I have Xcode installed and that was one of the very first things I installed but I am still getting this error, I have a whole project running on xcode, so I don't know what else to do

Unless your build fails, I wouldn't worry about it.
