### ISSUE TITLE
Add Build Status Plugin to ci.nodejs.org

### ISSUE THREAD

**Issue by gdams** [nodejs/build#618]
We should add the build status plugin to ci.nodejs.org so that modules can include their ci badges in the readme file. https://wiki.jenkins-ci.org/display/JENKINS/Embeddable+Build+Status+Plugin

**Comment by gibfahn** [comment]
@phillipj thoughts on using this? It'd work pretty well with the automatic build status stuff in https://github.com/nodejs/citgm/issues/358.

**Comment by jbergstroem** [comment]
I'm `-0`. Not a badge fan and/or user myself.

**Comment by gibfahn** [comment]
Having looked at it in greater detail, this wouldn't work (at least for the citgm use case) as it would  just show the status of the last build run. The last build run will usually have been on a PR, so it won't actually show us the current status of `master` unless we duplicate the citgm job (which is a bad idea imo).
