### ISSUE TITLE
provide @phillipj temporary (?) access as jenkins-admin on ci.nodejs.org

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#622]
Phillip (part of the build team) wants to help out with debugging the arm/arm-fanned ghost fail as well as adding extended functionality to the citgm suite. If this is temporary or if we should elevate his access to jenkins-admins could also be part of the discussion.

**Comment by joaocgreis** [comment]
SGTM. Do we also have fails in `arm-fanned`? I've only seen them on `arm`.

He's already on the Build WG and his work is related, I'm ok with permanent access.

**Comment by joaocgreis** [comment]
cc @nodejs/jenkins-admins

**Comment by gibfahn** [comment]
LGTM (not sure if my vote counts...)

**Comment by Trott** [comment]
+1

**Comment by thefourtheye** [comment]
+1

**Comment by jbergstroem** [comment]
@phillipj you cool with getting elevated access and working full-time as jenkins admin? 😄

**Comment by thefourtheye** [comment]
![](http://i3.kym-cdn.com/photos/images/facebook/000/933/852/18f.jpg)

**Comment by phillipj** [comment]
> @phillipj you cool with getting elevated access and working full-time as jenkins admin? 😄

Full-time? Sure, who needs a paid job anyway..

In all seriousness, I cannot promise to do more than github-bot related things ATM. After hopefully fixing what is needed for ARM and citgm, I'm fine with the access being revoked if that sounds best for the current admins.

**Comment by mhdawson** [comment]
+1 from me.

**Comment by jbergstroem** [comment]
Cool; @mhdawson can you add him to the group?

**Comment by mhdawson** [comment]
@jbergstroem added.

**Comment by phillipj** [comment]
Thanks!

**Comment by jbergstroem** [comment]
Assom - closing. Ping me if you need help/assistance. It might be good to copy jobs when you start modifying even though we have the config history plugin.
