### ISSUE TITLE
Release Jenkins access for Italo A. Casas

### ISSUE THREAD

**Issue by italoacasas** [nodejs/build#623]
Hi everyone, I need access to the Release Jenkins (https://ci-release.nodejs.org/job/iojs+release/)

- As describe in the [documentation](https://github.com/nodejs/node/blob/master/doc/releases.md#1-jenkins-release-access) I should request access here. cc: @nodejs/build
- With the authorization of TSC??, I'm going to cc: @nodejs/ctc instead since all the process to be part of the release team was handled by that CTC and maybe the documentation is not accurate in this case?

**Comment by gibfahn** [comment]
Probably makes sense to cc/ @nodejs/release  and @nodejs/tsc  as well. I don't think we've had new releasers in a while, so the process won't have been very thoroughly tested. We should probably write up an access document and put it in [doc/process/](https://github.com/nodejs/build/tree/master/doc/process).

+1 from me anyway (as an @nodejs/build member).

I think @mhdawson has a list of questions we normally ask for `build` access, I assume we could do something similar for `release` access.

**Comment by bnoordhuis** [comment]
+1.  Hard making releases without access to the release CI job.

**Comment by thefourtheye** [comment]
+1

**Comment by jbergstroem** [comment]
LGTM as well. Someone with elevated github access needs to add him to the proper group.

**Comment by evanlucas** [comment]
I went ahead and added to the releases team

**Comment by jbergstroem** [comment]
@italoacasas can you confirm having access to ci-release.nodejs.org?

**Comment by italoacasas** [comment]
@jbergstroem confirmed!

**Comment by jbergstroem** [comment]
Awesome! Closing.

**Comment by italoacasas** [comment]
Thanks everyone.
