### ISSUE TITLE
Build jobs for  node-inspect under auspices of diagnostics WG.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#625]
Its now the time that we should be setting up ci jobs to test the https://github.com/nodejs/node-inspect module. 

Unless there are objects this would be the plan:

* create a new team called diagnostics-admins who will be able to modify/configure jobs. There is already an existing team called 'diagnostics'.
*  Add the members who will be working to configure the ci jobs to diagnostics-admins
*  Create an initial job to test node-inspect
*  Configure the initial test job so that the jobs can be run by those in the diagnostics team, and can be configured/modified by those in diagnostics-admins.

@nodejs/build sound good ?

**Comment by gibfahn** [comment]
Is the plan to make everyone in `diagnostics` a member of `diagnostics-admins`, or only a subset? If the latter, you should probably list the initial members here.

LGTM anyway.

**Comment by mhdawson** [comment]
I'm not sure who would need to be part of the diagnostics-admin, need feedback from them.  Once I add one the team can then self-managed as per the process.

I was not planning on adding add, just a subset.

**Comment by mhdawson** [comment]
Starting to rough in job here: https://ci.nodejs.org/view/x%20-%20Diagnostics/job/node-inspect-continuous-integration/

**Comment by gibfahn** [comment]
@mhdawson see https://github.com/nodejs/node-report/issues/18#issuecomment-280234054, I've re-evaluated, and I think the hassle citgm adds isn't worth the benefit for single module testing. I'd like to make it simpler, but for now I think it's probably better to just not use it at all.

Also for these jobs (`node-inspect` and `node-report`) I think we need a way to trigger builds on `v4`, `v6`, `v7`, and master with one job (which will hopefully soon be triggered on new PRs automatically). I think the easiest way might be a flow which triggers one job 4 times (with different node branch parameters), but I'm not sure.

It'd be helpful to have access to the Jenkins jobs to see how things are implemented. However we do it, we should try to be consistent across all the node modules we `npm test` (at least `citgm`, `node-report`, `node-inspect`).

**Comment by mhdawson** [comment]
If you have time to work on your suggestions for the jobs, since you are part of the build WG I'm happy to give you access to one or more.  Do you want to start with node-report ?

**Comment by mhdawson** [comment]
Should be no surprises since they are a clone of the CITGM job you worked on, and they could use more optimization improvement.

**Comment by gibfahn** [comment]
>Do you want to start with node-report ?

SGTM

**Comment by rvagg** [comment]
Sounds OK but please keep `diagnostics-admins` access fairly exclusive as it gives you pretty broad control over our test infra and the ability to get away with nefarious activity while mostly covering your tracks. Also make sure they can't edit any of the other jobs, only diagnostics ones! I assume the list is pretty small here anyway? Maybe only a couple of people?

**Comment by gibfahn** [comment]
>Sounds OK but please keep diagnostics-admins access fairly exclusive as it gives you pretty broad control over our test infra and the ability to get away with nefarious activity while mostly covering your tracks.

Has anyone looked at using the new `Jenkinsfile` options (equivalent of `.travis.yml` files) in Jenkins 2 to see whether we could put our configurations in there? If we could then it wouldn't be necessary for people to have access to the CI, they could just submit PRs to update the `Jenkinsfile` configs.

**Comment by mhdawson** [comment]
@rvagg configuration is in line with: https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md.  It limits config to specific jobs for the WG/team to the corresponding "admins" team.   In terms of who gets added to the "admins" team I start with a small set but its delegated as per that process to the team itself.

**Comment by mhdawson** [comment]
@gibfahn you should now be able to view/configure https://ci.nodejs.org/view/post-mortem/job/nodereport-continuous-integration/configure.

**Comment by Trott** [comment]
`node-inspect` + tests are now in Node.js core. Closing. Feel free to re-open if there's something I'm missing. Thanks!
