### ISSUE TITLE
Make regular canary builds with V8 lkgr

### ISSUE THREAD

**Issue by targos** [nodejs/build#626]
There are more and more people who would like to try and use Node.js with the most recent V8 version available. (\[1\], \[2\])

I propose that we maintain a [`canary`](https://github.com/nodejs/node/commits/canary) branch, regularly updated, based on master and upgraded to the latest version of V8. I have already created the branch and applied patches on top of it (most of them cherry-picked from [V8's fork](https://github.com/v8/node/commits/vee-eight-lkgr), thank you @ofrobots et al!).
CI is running [here](https://ci.nodejs.org/job/node-test-commit/7923/) and looks very promising.
From this branch, we should be able to build canary binaries and publish them to https://nodejs.org/download/.
I also created another branch, [`canary-base`](https://github.com/nodejs/node/commits/canary-base), that is currently exactly the same. The idea is that an automated tool would manage the canary branch, while we use canary-base to manually push fixes.

Here is the general workflow that this tool would follow:
1. `git remote update`
2. `git reset --hard nodejs/master`
3. Use [`update-v8`](https://github.com/targos/update-v8) to upgrade to the latest V8 version
4. Cherry-pick commits from `canary-base`
5. `git push --force nodejs canary`

I think it would be valuable for everyone to setup all of this:
- Possibility for people who like to live on the edge to get an easy access to the latest features.
- More testers of the latest master / V8.
- Sooner detection of breaking changes from V8 that affect platform that are not tested by them.
- Easy starting point for Node.js collaborators who want to start implementing things ahead of time with new V8 APIs.

/cc @nodejs/build @nodejs/v8 @ljharb

[[1]](https://twitter.com/_gsathya/status/831757302910873600) [[2]](https://twitter.com/OH_NOES/status/823544800259424257)

**Comment by mhdawson** [comment]
Seems like a reasonable idea to me.

**Comment by ofrobots** [comment]
Thanks for writing this up / working on this. It would be great to have a canary build of Node.js available so that we can flow node canary feedback to the V8 team before the V8 dev branches solidify into the beta/stable branches.

A question about the work-flow you proposed: how would the cherry-picking from `canary-base` work? It sounds like this would be an automated process. How would the tool know what commits should be cherry-picked?

**Comment by bmeurer** [comment]
I like this idea a lot! Looking forward to Node Canary.

**Comment by hashseed** [comment]
Looking forward to this!

How does automating updating to the newest V8 including its dependencies look like? Internally we were thinking of writing a script to do this, and have it checked into the V8 repository. Does that sound like something you are already working on?

**Comment by hashseed** [comment]
I wonder whether it makes sense to port the update-v8 script to python. Requiring Node.js to be able to update Node.js feels weird. Especially if we are looking into checking it into V8 to be able to keep it in sync with V8's version: V8 would have a circular dependency on Node.js.

**Comment by targos** [comment]
I don't speak python. That's why I wrote it in JS in the first place :).

> Requiring Node.js to be able to update Node.js feels weird

It doesn't feel so weird to me. We already need Node.js to be able to lint Node.js with ESLint.

> Does it make sense to check in part of update-v8 into V8 itself?

I think it would make a lot of sense to have the list of dependencies in V8 (ideally as a JSON). It is currently here: https://github.com/targos/update-v8/blob/master/src/constants.js#L14-L49
I'm not so sure for the rest of the script. It is more coupled to Node than V8 (directory structure, commit messages). I don't know if other V8 users could benefit from it.

**Comment by targos** [comment]
> How would the tool know what commits should be cherry-picked?

All the commits after the last V8 update. Something like:
```
git cherry-pick `git log canary-base -1 --format=format:%H --grep "deps: update V8"`...canary-base
```

**Comment by gibfahn** [comment]
We should try to get this up and running in the Collab Summit.

with @piccoloaiutante @targos @fhinkel

**Comment by targos** [comment]
The nightly test job works fine and allowed to find and fix quickly some issues.
[Latest run is almost green](https://ci.nodejs.org/job/node-test-commit-node-v8/30/) (known issue on FreeBSD: https://github.com/nodejs/node-v8/issues/1, https://github.com/nodejs/build/issues/723).

@gibfahn would you like to help me setup the nightly build?

**Comment by gibfahn** [comment]
>@gibfahn would you like to help me setup the nightly build?

So this would be adding a trigger to the release CI job to upload builds every night? I can definitely help with that, but I'll add this to the Build WG agenda tonight to make sure there are no objections.

**Comment by targos** [comment]
Yes. I'm thinking about a new https://nodejs.org/download/v8-nightly/ similar to https://nodejs.org/download/chakracore-nightly/

**Comment by rvagg** [comment]
fyi I have this on my plate, still working on it, it's not a trivial task unfortunately because it also involves the `Makefile` in core. In the meeting we talked about using "v8-canary" since it roughly aligns with the V8 in Chrome Canary. I'm fine with either that or "v8-nightly". Can we get a consensus here on naming?

**Comment by gibfahn** [comment]
I prefer `v8-canary`, I think it better conveys that it's V8 canary and Node master/nightly.

**Comment by targos** [comment]
v8-canary is fine for me

**Comment by kfarnung** [comment]
+1 on `v8-canary`.  `chakracore-nightly` tracks a relatively stable version of ChakraCore (just like normal node nightly builds).

**Comment by piccoloaiutante** [comment]
+1 for `v8-canary` also for me

**Comment by rvagg** [comment]
OK folks, here it is https://nodejs.org/download/v8-canary/

I did some pretty heavy refactoring of the Jenkins iojs+release job on ci-release to make this work nicely but in the process I cleaned up a bunch of old cruft and made it easier to trigger.

I haven't automated this yet, I'll need to do some small tweaks to nightly-builder to handle this nicely, that shouldn't take much effort though.

I wanted to get y'all thinking about how the messaging for this might go—using these builds is going to be a huge mess if you're using addons. They may compile but you're not going to get ABI stability, even across v8-canary versions, and it could potentially break every 6 weeks. So perhaps we could think about a blog post that describes what this is, why you might tinker with them and what kind of breakage you should expect and how to deal with that.

**Comment by rvagg** [comment]
```
$ node -p process.versions
{ http_parser: '2.7.0',
  node: '9.0.0-v8-canary20170609cd40078f1f',
  v8: '6.1.101',
  uv: '1.12.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '58',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```

**Comment by rvagg** [comment]
To add to what I said above about messaging—you may not want to promote this too much, I can see people getting much more tangled in this than they would in our slower and more controlled `master` process that leads to `nightly` builds. Let's have a talk about limiting uninformed user problems first.

**Comment by rvagg** [comment]
https://twitter.com/mathias/status/873204105161961473

So much for taking it gently

**Comment by mathiasbynens** [comment]
My apologies, @rvagg — I was unaware of your request to “not promote this too much” when I posted that.

I’d assume those opting in to canary builds know what to expect, analogous to Chrome Canary: you’re giving up stability for a more bleeding-edge feature set.

I agree that a blog post would help clarify the difference between nightly and canary builds. 👍

**Comment by rvagg** [comment]
Yeah, no biggie, I'll try and find time soon to draft up a post for you all to review

**Comment by rvagg** [comment]
PRs to support this in the dist tooling we use:
 * https://github.com/nodejs/nodejs-dist-indexer/pull/4
 * https://github.com/nodejs/nodejs-nightly-builder/pull/1

They're active on the server now and we have working [index.tab](https://nodejs.org/download/v8-canary/index.tab) and [index.json](https://nodejs.org/download/v8-canary/index.json) files and there's a cron job in to trigger a job for this every day _if_there's a new commit on nodejs/node-v8/canary. One's running now as I'm writing this and will show up eventually soonish.

**Comment by targos** [comment]
@gibfahn I have a problem with the `node-update-v8-canary` job on one of the fedora boxes. It fails consistently because "a cherry-pick or revert is already in progress": https://ci.nodejs.org/view/All/job/node-update-v8-canary/78/console
I cannot reproduce this locally and when the job runs on the other box, it works fine. I don't understand how this can happen because we do `git reset --hard origin/master` before the update and I think that should abort any cherry-pick that is in progress...

**Comment by gibfahn** [comment]
@targos odd, it looks like something got messed up in the workspace. I cleaned it out and reran, and now I'm getting: https://ci.nodejs.org/view/All/job/node-update-v8-canary/80/console

```bash
 > git fetch --tags --progress git@github.com:nodejs/node.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/canary^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/canary^{commit} # timeout=10
 > git rev-parse origin/canary^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
```

Shouldn't it be looking for `canary-base` in nodejs/node?

**Comment by targos** [comment]
> Shouldn't it be looking for `canary-base` in nodejs/node?

Indeed. I changed the config. Trying a new run: https://ci.nodejs.org/view/All/job/node-update-v8-canary/82/console

**Comment by gibfahn** [comment]
>Trying a new run:

Looks like that went better.

LMK if it happens again, I had a look on the machine and none of the directories seemed to have a cherry-pick in progress. 

If you have the ability to see the `Wipe Out Current Workspace` button in the [`Workspace` tab](https://ci.nodejs.org/view/All/job/node-update-v8-canary/ws/#) of the job, I recommend wiping and rerunning as a first resort if something starts going wrong. Things seem to get corrupted fairly often in Jenkins.

**Comment by targos** [comment]
The daily update/test and nightly build work well. I think this can be closed. Thanks everyone for the help!

**Comment by targos** [comment]
Ah! We still haven't posted anything on the blog about this. @rvagg would you still like to do this draft?

**Comment by richardlau** [comment]
I can't test this right now, but I think you should be able to work around this by [pointing node-gyp at your Node.js installation](https://github.com/nodejs/node-gyp#configuration) which should in theory already include the relevant headers.

e.g. `export npm_config_nodedir=/path/to/node`

**Comment by aalexand** [comment]
@mmarchini It worked for me - thanks!
