### ISSUE TITLE
*.pkg macOS nightlies are missing

### ISSUE THREAD

**Issue by stevenvachon** [nodejs/build#627]
for the last few days:
https://nodejs.org/download/nightly/v8.0.0-nightly20170214ac602a251a/
https://nodejs.org/download/nightly/v8.0.0-nightly201702152ba4eeadbb/
https://nodejs.org/download/nightly/v8.0.0-nightly20170216642eec162d/

yet recent PRs for [nodejs/node](https://github.com/nodejs/node) are passing their macOS builds on CI

**Comment by indutny** [comment]
There are `-darwin.tgz` files in those folders. Is it what you are looking for?

**Comment by stevenvachon** [comment]
I'm looking for *.pkg files

**Comment by stevenvachon** [comment]
All previous nightlies have *.pkg files.

**Comment by Trott** [comment]
@nodejs/build

**Comment by mhdawson** [comment]
Last few nightly release job runs show red for OSX. 

Looks like it might be an issue related to signing.  I think we need either @rvagg or @jbergstroem to take a look.

**Comment by rvagg** [comment]
```
+ codesign -s 'Developer ID Application: Node.js Foundation' out/dist-osx/usr/local/bin/node
out/dist-osx/usr/local/bin/node: timestamps differ by 1.21717e+06 seconds - check your system clock
```

System clock hasn't been updating on this set of machines for some reason, I've given it a kick and they now appear to be syncing properly.

Ran the latest one again and it's working properly, see .pkg @ https://nodejs.org/download/nightly/v8.0.0-nightly20170218ca37ec084a/

**Comment by stevenvachon** [comment]
*.pkg is missing again: https://nodejs.org/download/nightly/v8.0.0-nightly201702238e8fbd80d0/
