### ISSUE TITLE
Build ARMv7 binaries on Wheezy-based distro

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#63]
https://cloud.online.net/ is probably the way to go but slower than the ODROID XU3 we're using in CI now, that can be solved with ccache for the most part I think though.

**Comment by samkrew** [comment]
@rvagg Hello, Is there any progress ?

**Comment by rvagg** [comment]
no ... I was going to use the Raspbian Wheezy repo to get gcc 4.8 but that appears to have disappeared from the list so now I either need to compile or find a new source for it, that's the blocker here

also, @julianduque handed me a BBB a few weeks ago so I'll hook that up to CI soon too.

**Comment by julianduque** [comment]
\o/

**Comment by popasquat89** [comment]
Are there any updates for getting this working?

**Comment by Trott** [comment]
This issue has been dormant for over a year. Any chance it's either been resolved by now or else is unlikely to be resolved before the Wheezy distro is EOL'ed? Maybe a candidate for a `help wanted` tag?
