### ISSUE TITLE
Add pip to AIX release machine

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#630]
Add pip to AIX release machine.  Its already been added to the test machines.  

As per manual install instructions:  https://github.com/nodejs/build/blob/master/setup/aix61/manualBootstrap.md as updated by: https://github.com/nodejs/build/pull/629

 ```bash
LIBPATH=/usr/lib curl https://bootstrap.pypa.io/get-pip.py | python
 ln -s /opt/freeware/bin/pip /usr/bin/pip
```

**Comment by mhdawson** [comment]
@jbergstroem can you take a look at this as we don't have access to the release machines.

**Comment by jbergstroem** [comment]
Sure, but do we need to? `pip` (unless we use it for more things i'm unaware of) is to pave way for the `tap2junit` script I wrote which is only used in testing.

**Comment by gibfahn** [comment]
Makes sense, if we don't need it then we can close.
