### ISSUE TITLE
added italo's key to dist machine

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#632]
To allow him to promote the v7.x release I have added his key to the dist machine. Please let me know if there is a process I should have followed if I have stepped on any toes.

**Comment by jbergstroem** [comment]
There's really no procedure (I know of :); its mostly manual work. Seeing how he's part of @nodejs/release he should have been added as part of joining the group.

**Comment by MylesBorins** [comment]
we should likely make an on boarding guide

**Comment by jbergstroem** [comment]
> @MylesBorins said:
> we should likely make an on boarding guide

yeah; for all "levels" of participation. I attempted it for the build group membership with @Trott rott and @Starefossen – should probably summarize that someplace.
