### ISSUE TITLE
Make dist/ backups incremental

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#635]
We currently do a `rsync --delete -a...` when backing up `/dist/` from our dist machine. This should probably be incremental to save us from cases where new dist artifacts accidentally gets provisioned.

**Comment by Trott** [comment]
Ping @nodejs/build: This seems like something someone with the right awareness of where all the pieces are can check on and probably address relatively quickly? Or maybe I'm missing a subtlety here?

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
