### ISSUE TITLE
Create new flow job for CITGM

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#639]
On request of CiTGM team by @gdams:

Create a flow job so that we can launch runs on multiple node versions.  

As per https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md a member of the build team has to do this for the external teams.

**Comment by mhdawson** [comment]
Just confirming what type we need as I don't see flow in the options for a new job.  Maybe its not under NewJob ?

**Comment by mhdawson** [comment]
Guessing is the "Pipleline" option but will confirm before creating.

**Comment by mhdawson** [comment]
Job created here: https://ci.nodejs.org/job/citgm-flow/

**Comment by gibfahn** [comment]
Name changed to https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration-flow/
