### ISSUE TITLE
Build WG meeting Mar 7 3 PM EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#640]
### When

Tuesday March 7 2017 3 PM EST 

### Where
- Hangouts on Air, for participants:  https://hangouts.google.com/hangouts/_/ytl/nIHGuM4xqsCuNs-64_MB-jd5fqKt2g_YhamrTxifLPY=?eid=100598160817214911030
- Youtube stream, for viewers: https://www.youtube.com/watch?v=8RhgJMn5R88
- Minutes doc: https://docs.google.com/document/d/1H92tArttCPi8EFO2Guz8lWY0kydA-RRHwXe0VIEKn3w/edit

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* file and directory names for downloads - [515](https://github.com/nodejs/build/issues/515)
* Draft text for HSTS communication - [484](https://github.com/nodejs/build/issues/484)
* TAP Plugin issues on Jenkins - [453](https://github.com/nodejs/build/issues/453)
If there are any items that you would like to discuss at the meeting, please tag new or existing issues with the `wg-agenda` label, or simply post them in a comment here.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

**Comment by jbergstroem** [comment]
Thanks for preparing this. I will attend; adding to calendar.

**Comment by gibfahn** [comment]
Is the plan to start recurring every 3 weeks again?

**Comment by jbergstroem** [comment]
@gibfahn correct.

**Comment by joaocgreis** [comment]
I will attend today.

**Comment by mhdawson** [comment]
Yes we should be back on the recurring 3 week schedule, believe it is as on the community google calendar.

**Comment by mhdawson** [comment]
meeting link : https://hangouts.google.com/hangouts/_/ytl/nIHGuM4xqsCuNs-64_MB-jd5fqKt2g_YhamrTxifLPY=?eid=100598160817214911030&hl=en_US&authuser=0

**Comment by gibfahn** [comment]
Supported platforms PR: https://github.com/nodejs/node/pull/8922

**Comment by mhdawson** [comment]
Minutes for last meeting: https://github.com/nodejs/build/pull/651

**Comment by mhdawson** [comment]
Minutes landed, closing
