### ISSUE TITLE
Enable Benchmarking WG team management of benchmarking jobs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#641]
We've had benchmarking jobs for a while.  

We should apply https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md to then so other build team members can help manage/fix/improve the jobs.

Unless there are objects this would be the plan:

* create a new team called benchmarking-admins who will be able to modify/configure jobs. There is already an existing team called 'benchmarking".
*  Add the members who will be working to configure the ci jobs to benchmarking-admins (initiall just @mhdawson and @CurryKitten)
*  *  Configure the existing benchmarking jobs so that the jobs can be run by those in the benchmarking team, and can be configured/modified by those in benchmarking-admins.

@nodejs/build sound good ?

**Comment by gibfahn** [comment]
Sounds good to me

**Comment by jbergstroem** [comment]
SGTM

**Comment by jbergstroem** [comment]
(just adding so i don't forget: I need to introduce the `benchmark-` naming in the ansible refactor so we can make an assumption about ssh keys.

**Comment by mhdawson** [comment]
Ok team created and jobs configured to allow teams appropriate level of access.

**Comment by jbergstroem** [comment]
@mhdawson we need ssh keys as well, right?

**Comment by mhdawson** [comment]
Yes figured we'd cover that under https://github.com/nodejs/build/issues/642
