### ISSUE TITLE
Benchmarking team access to Benchmarking machines

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#642]
We'd discussed giving access to the appropriate benchmarking team members access to the benchmarking machines through ssh as opposed to using the test keys.

I think it makes sense to do that now.  I'd suggest that we use the same approach as for the test keys but replicate for the benchmarking keys.  I"d also suggest that we make it so that only those in the benchmarking-admins have access to the keys (that group will be set up as part of https://github.com/nodejs/build/issues/641.

@jbergstroem is there a list of things we have to do in order to set this up and which ones will I be able to do ?

**Comment by jbergstroem** [comment]
Sounds good to me. I can look at creating a new subfolder in the secrets repo with keys. Speaking of; who lives in `benchmark-admins`?

**Comment by gibfahn** [comment]
>Speaking of; who lives in benchmark-admins?

Will be decided in https://github.com/nodejs/build/issues/641

**Comment by jbergstroem** [comment]
@gibfahn: ok; i'll wait until that lands before creating the group then!

**Comment by Trott** [comment]
Seems like this can be closed given its long dormancy, but by all means re-open and/or comment if I'm wrong about that.

**Comment by refack** [comment]
Superseded by https://github.com/nodejs/build/issues/1665
