### ISSUE TITLE
test-joyent-freebsd10-x64-1 low disk space on /usr/home/iojs/build

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#645]
https://ci.nodejs.org/computer/test-joyent-freebsd10-x64-1/ was offline, I assume it needs a cleanup or a disk space increase.

**All other FreeBSD hosts [matching label `freebsd10-64` seem to be offline](https://ci.nodejs.org/label/freebsd10-64/), so this is somewhat urgent issue.**

<br/>

![image](https://cloud.githubusercontent.com/assets/15943089/23833972/2730f630-0746-11e7-8c3c-b67a13ec7373.png)

**Comment by gibfahn** [comment]
```
root@test-joyent-freebsd10-x64-1:~ # df -h
Filesystem      Size    Used   Avail Capacity  Mounted on
/dev/vtbd0p2    9.2G    7.1G    1.4G    84%    /
devfs           1.0K    1.0K      0B   100%    /dev
/dev/vtbd1p1     48G     32M     45G     0%    /data
```

**Comment by gibfahn** [comment]
```
root@test-joyent-freebsd10-x64-1:/usr/home/iojs/build/workspace # du -sh *
 30M	libuv-test-commit-freebsd
789M	node-stress-single-test
893M	node-test-commit-freebsd
```

I just ran `node-stress-single-test` on FreeBSD, so I suspect that's what pushed it over the edge.

cc/ @jbergstroem

**Comment by Trott** [comment]
FreeBSD 10 jobs in CI seem to not be running now. As a "I have no idea what I'm doing, guess I'll restart something" move, I restarted Jenkins on test-joyent-freebsd10-x64-1. No change, though.

**Comment by gibfahn** [comment]
![image](https://cloud.githubusercontent.com/assets/15943089/23845633/2821f582-07c1-11e7-9440-bb63d18c91dd.png)

@Trott short term fix is to keep clicking the "Bring this node back online" button. Proper fix is to clean up some space on the machine.

If the jobs are getting queued up find which label they want to run on, do a label search for that label (e.g. https://ci.nodejs.org/label/freebsd10-64/) and then work out what's up with those machines.

**Comment by jbergstroem** [comment]
Looks like the disk is mounted at `/data`. Don't recall this previously. I will look at mounting `/usr/home` to `/data` and mount binding it. Probably need to review other joyent hosts too.

**Comment by gibfahn** [comment]
@jbergstroem do you know why [test-digitalocean-freebsd10-x64-1](https://ci.nodejs.org/computer/test-digitalocean-freebsd10-x64-1/) is offline? Having neither of them means that no PRs will actually run unless someone keeps hitting the `Bring This Node Back Online` button. Currently it's me doing it.

**Comment by jbergstroem** [comment]
@gibfahn yes. digitalocean took it down for maintenance and now its not coming back up. potentially some bug with network config as provided by DO. support suggests to log in with console but seeing how we don't rely on root password I'm stuck there. I will redeploy or log into single user mode this week.

**Comment by jbergstroem** [comment]
Still can't quite explain why the mount that used to be `/usr/home` is now `/data`; but i moved the contents to the new volume and mounted it through fstab. I'll revisit the other VMs shortly.
