### ISSUE TITLE
Jenkins bug?

### ISSUE THREAD

**Issue by targos** [nodejs/build#647]
In https://ci.nodejs.org/job/node-compile-windows/7432/:
The `win-vs2013` job was skipped but it is still clickable and redirects to another earlier build (7420).

**Comment by joaocgreis** [comment]
This is not a but, it's just a "feature" of Jenkins that is confusing in our use case. When the build is skipped, the green icon is shaded (`<img ... style="opacity:0.5"`), it should look like this:
![image](https://cloud.githubusercontent.com/assets/134460/23863911/e40bc1d2-0808-11e7-999c-387ae0355b1b.png)
Compare with a successful build that should look like this:
![image](https://cloud.githubusercontent.com/assets/134460/23863945/fdeacd0a-0808-11e7-9ca1-f32ec85becd7.png)

I don't think there's much we can do about this. Unless perhaps split the `node-compile-windows` job, but that would make it harder to maintain and we'd have to figure out how to trigger the correct one.

**Comment by targos** [comment]
I see. Thank you for the explanation.
