### ISSUE TITLE
HTTP forward and CNAME for newsletter

### ISSUE THREAD

**Issue by mikeal** [nodejs/build#648]
Heya,

We'd like `newsletter.nodejs.org` to point to http://us14.campaign-archive2.com/home/?u=c7c2e114a827812354112c23b&id=f006b61f29 . We need something setup similar to what we have for `interactive.nodejs.org`. It's just a few clicks and copy pastes in the Cloudflare dashboard :)

Original issue is here https://github.com/nodejs/nodejs.org/issues/1142

**Comment by jbergstroem** [comment]
I can set it up unless anyone from the build group has opinions on how it should be done. I'll wait around for a day or three.

**Comment by mikeal** [comment]
The initial request has been sitting for like 20 days already, so the quicker the better ;)

**Comment by jbergstroem** [comment]
So, I looked at it (over at cloudflare) and it's not handled through there -- rather in our [nginx config](https://github.com/nodejs/build/blame/master/setup/www/resources/config/nodejs.org#L163).

We should probably add SSL redirects for both as well.

**Comment by mikeal** [comment]
Unfortunately the newsletter listing page isn't available in TLS. However, the link to signup which actually accepts personal information you may not want to leak is TLS.

**Comment by jbergstroem** [comment]
@mikeal was just referring to capturing `https://newsletter.nodejs.org` in our redirect rule as well. It would land in `default_server` otherwise; likely implying `nodejs.org`.

**Comment by mikeal** [comment]
ahhhhh

**Comment by mikeal** [comment]
poke :)

**Comment by rvagg** [comment]
pls review @mikeal @jbergstroem https://github.com/nodejs/build/pull/652
