### ISSUE TITLE
Add Kunal Pathak to Build WG

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#649]
This issue is to discuss adding @kunalspathak to the Build WG.

Kunal has added Windows Server 2016 to our build matrix in CI (https://github.com/nodejs/build/issues/587, https://github.com/libuv/libuv/issues/1245) and will keep maintaining those servers. 

We can have a vote on the next WG meeting if consensus is not reached here.

cc @nodejs/build

**Comment by joaocgreis** [comment]
Approved in today's meeting (https://github.com/nodejs/build/issues/660). I'll move forward with adding to secrets.

@kunalspathak can you file a PR adding yourself to the list in README.md?

**Comment by joaocgreis** [comment]
Can someone with permission add @kunalspathak to https://github.com/orgs/nodejs/teams/build ? (@jbergstroem @mhdawson perhaps)

**Comment by jbergstroem** [comment]
Added!

**Comment by joaocgreis** [comment]
Thanks! This is done then!
