### ISSUE TITLE
Add ramdisk to AIX machines

### ISSUE THREAD

**Issue by gdams** [nodejs/build#661]
Following issues with citgm being particularly slow, I am going to add a ramdisk to power8-aix-nodejs2.osuosl.org to see if this helps increase performance. 

cc/ @mhdawson @gibfahn

**Comment by gibfahn** [comment]
So we're starting with `power8-nodejs2.osuosl.org` (a.k.a. `test-osuosl-aix61-ppc64_be-2`). If everything works okay we can try with the other test machine, `power8-nodejs1.osuosl.org` (a.k.a. `test-osuosl-aix61-ppc64_be-3`)

**Comment by gibfahn** [comment]
If we go ahead with this, we need to make sure we update the Ansible script (and temporarily the manual instructions).

**Comment by gdams** [comment]
okay so running citgm on the ramdisk was much quicker (less than 20 minutes)

**Comment by gdams** [comment]
commands to add the ramdisk:
```bash
mkramdisk 4G
mkfs -V jfs2 /dev/ramdisk0 
mkdir -p /ramdisk0
mount -V jfs2 -o log=NULL /dev/ramdisk0 /ramdisk0
```

**Comment by gdams** [comment]
from googling, this seems to be the easiest way to mount the ramdisk at startup: http://www.unix.com/aix/244552-how-can-we-re-mount-ram-disk-automatically-after-reboot-aix.html @edelsohn @mhdawson

**Comment by mhdawson** [comment]
@gdams, ramdisk.ksh seems to say '5M" is that correct or should it be 5G ?

A pull request against the build repo, adding ramdisk.ksh and updates to the ansible scripts to make it run on startup would be the best way to review

**Comment by gdams** [comment]
Oh sorry, it looks like @gibfahn edited my comment, take the configuration from the above comment that mentions 4G

**Comment by gibfahn** [comment]
>ramdisk.ksh seems to say '5M" is that correct or should it be 5G ?

I copied that verbatim from the linked website. Fixed now.

**Comment by gdams** [comment]
also added the same config to  power8-aix-nodejs3.osuosl.org

**Comment by gibfahn** [comment]
@gdams any chance you could PR this to the setup instructions?

**Comment by CJKwork** [comment]
On the adoptopenjdk infrastructure, I've created ksh scrip AIX_ramdisk.ksh and updated aix.yml to call it. It adds a 4Gb ramdisk, provided the ram is available.

**Comment by sam-github** [comment]
I'm looking at completing this task by adding the ramdisk entries, but I'm not sure what to do about /home/iojs/build/tools/jython (jython is the only thing in tools).

I don't know if its used, or what job creates it, or if it was created manually.

@nodejs/platform-aix If anyone has any ideas, please tell me. I've search the config for a few of the jobs that have run on aix recently (citgm smoker, test-commit-aix, etc) and find no reference to tools  or jython. I just did `mv /home/iojs/build/tools /home/iojs/build.tools`, I'll see if that causes any issues, or if its recreated.

**Comment by sam-github** [comment]
I unified ramdisk setup on the AIX machines.
