### ISSUE TITLE
Create matrix of "coverage" areas for build team

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#662]
This issue is to discuss and capture the areas that we want to ensure we have enough coverage in terms of people who can step in and help resolve issues.

As as starting list:

* Windows test workers
  * Currently active
     * 
  * Volunteering 
* Core unix test workers
* Arm test workers
* zLinux test workers
* PPC test workers
* AIX test workers
* SmartOS test workers

* Jenkins - jobs

* Jenkins - release infrastructure

* Jenkins - test infrastructure

* virtual machine management

* Website

* Secrets repo

* Release workers

* ansible playbooks

* backup routines

* backup machines

* github bot

* mail management 

* Identify certification management

* Cloudflare

Lets add until we are comfortable that we have the complete list. Goal would be to have that list for the next meeting in 3 weeks.

**Comment by jbergstroem** [comment]
- ansible playbooks
- backup routines
- backup machines

**Comment by joaocgreis** [comment]
- Release Jenkins - jobs
- Release Jenkins - infrastructure

And split Website into:
- Website - WWW
- Website - Nightlies (promoting, ...)
- Website - Releases

**Comment by refack** [comment]
Put me down for everything Windows.

**Comment by Trott** [comment]
Inactive for almost two years. Closing. Feel free to re-open if that's wrong and someone plans on actively completing this.
