### ISSUE TITLE
Task idea: automatically audit fail/pass ratio of each Jenkins node

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#664]
Here's something I'd love to have alongside the automatic uptime checking that we have in place for Jenkins nodes: figure out how to use the node/slave build list via the API and audit the pass/fail ratio of each. When a node has a certain ratio of fails to passes then we get notifications.

e.g. have a look at https://ci.nodejs.org/computer/test-requireio_bengl-debian7-arm_pi1p-1/builds which was having problems recently, there's a string of fails which were because of disk problems, I fixed it and it's back to mostly passes.

Most of the pings for help in #node-build on IRC are for these kinds of problems, where an individual node needs attention, but we could be detecting these ahead of time and getting email notifications to deal with them proactively.

In investigating this, the stumbling block I've hit is that I can't find an API endpoint for this data, there's nothing @ https://ci.nodejs.org/computer/test-requireio_bengl-debian7-arm_pi1p-1/builds/api/json, so perhaps someone who has time can investigate further?

**Comment by gibfahn** [comment]
We did something similar internally for monitoring machines.

The easiest way is probably just to monitor the node-test-commit job (you could also check other jobs), and write a quick script to work out whether the last X builds that ran on that machine failed. 

cc/ @mhdawson @bgriggs @akpotohwo

**Comment by Trott** [comment]
Related, I suppose:

https://nodejs-ci-health.mmarchini.me/#/job-summary
https://nodejs-ci-health.mmarchini.me/#/detailed-jobs

Not a node-by-node summary, but still pretty useful.

Anyway, given that this is inactive for almost 2 years, I'm going to close it. Feel free to re-open if you think that's the wrong thing to do. I'm mostly just panic-closing after noticing we have 228 issues open in this repo.
