### ISSUE TITLE
Create streams-admins and streams CI jobs

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#666]
Proposal for us to follow [the process for adding teams/projects to CI](https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuration_access.md) for the readable-stream nodejs project, as discussed in [the last build WG](https://github.com/nodejs/build/issues/660). This would be similar to what we've done for [CitGM](https://github.com/nodejs/build/issues/584), [benchmarking](https://github.com/nodejs/build/issues/641), and [node-inspect](https://github.com/nodejs/build/issues/625).

What needs to be done:
 - create the `streams-admins` group
 - create `streams-continuous-integration` (we can start by cloning [nodereport-continous-integration](https://ci.nodejs.org/view/All/job/nodereport-continuous-integration/))

Refs: https://github.com/nodejs/build/issues/657, https://github.com/nodejs/build/issues/655, https://github.com/nodejs/readable-stream/issues/270

cc/ @nodejs/streams

**Comment by gibfahn** [comment]
@mcollina Obviously there may be extra things we have to do later, but let's start by getting a job up and running.

**Comment by mcollina** [comment]
👍

**Comment by mcollina** [comment]
@gibfahn any update on the work you started during the Collab Summit?

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
