### ISSUE TITLE
Request to join the jenkins-admins team (gibfahn)

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#667]
Not sure what the process is for this, but I've been helping out with setting up CI for a lot of the new nodejs projects joining our CI (most recently in https://github.com/nodejs/build/issues/666), and it'd be really helpful to be able to create/edit jobs myself.

**Comment by mhdawson** [comment]
This would be good. I've added a number of the new jobs for WG's and it would be great if @gibfahn could help out too.

**Comment by jbergstroem** [comment]
`+1` from me.

**Comment by joaocgreis** [comment]
+1 from me as well.

**Comment by mhdawson** [comment]
Agreed in meeting today, I'll go ahead and add him

**Comment by jbergstroem** [comment]
@gibfahn with great power comes great responsibility :)

**Comment by mhdawson** [comment]
added
