### ISSUE TITLE
Temporary access to some windows box

### ISSUE THREAD

**Issue by indutny** [nodejs/build#671]
Hello!

I'd like to port [dukgyp][0] to Windows. An access to Windows machine would increase my development speed by infinite amount, since it is practically 0 now :wink:

[0]: https://github.com/indutny/dukgyp

**Comment by indutny** [comment]
cc @nodejs/build

**Comment by gibfahn** [comment]
SGTM

Would you need a CI job to test with? I'm thinking that it might be easier to just use Travis and Appveyor to start with.

**Comment by indutny** [comment]
Not sure if it is feasible, but remote desktop would be more helpful. I'll have to run it many many times, and CI will slow me down significantly.

**Comment by gibfahn** [comment]
Sorry, forgot to write also. Direct access with Remote Desktop SGTM. I was wondering if you'd also need a CI job.

**Comment by indutny** [comment]
No problem. I don't need CI at this point, just need to make it work.

**Comment by Trott** [comment]
SGTM

**Comment by refack** [comment]
@indutny need help with a live person in front of a windows machine?

**Comment by indutny** [comment]
@refack this is going to be "trial and error" until I will succeed :) Better get my hands on machine if we have one.

**Comment by indutny** [comment]
@refack but thanks for the offer!

**Comment by refack** [comment]
Also I have a some free credit, and a nice machine image on Azure if the org can't provide anything else.
In parallel to you getting RDP, I have the next two days free, give me an entry point and I'll dig. I'm very comfortable on Windows... 😉

**Comment by joaocgreis** [comment]
@indutny sent you an email with credentials. Let us know when you no longer need access.

**Comment by joaocgreis** [comment]
@indutny please let us know when you no longer need access, or when we can connect the machine back to CI even if you'd like to keep access. Thanks!

**Comment by joaocgreis** [comment]
@indutny the machine is back in the CI pool, let me know if you want to have it back exclusively.

**Comment by maclover7** [comment]
ping -- is access still needed?
