### ISSUE TITLE
Add the Rebuild Plugin to Jenkins (ci.nodejs.org)

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#672]
We use [the Rebuild plugin](https://wiki.jenkins-ci.org/display/JENKINS/Rebuild+Plugin) internally, and it's really helpful. It basically does a `Build now` and prepopulates the parameters with whatever they were set to in the job you are rebuilding. You can still change any you need to.

Basically it saves a lot of typing when you're trying to fix a job which has lots of parameters.

cc/ @gdams

**Comment by jbergstroem** [comment]
SGTM if it scratches an itch!

**Comment by refack** [comment]
Ping? I would use it quite often.
If it could be set to just re-populate the form and leave the "Submit" for manual clicking that would be great for `node-stress-single-test`. But that's a "nice-to-have".

**Comment by gibfahn** [comment]
>If it could be set to just re-populate the form and leave the "Submit" for manual clicking that would be great for node-stress-single-test. But that's a "nice-to-have".

Not quite sure what you mean, but when you press rebuild it pre-populates the parameters with whatever you set when you initially ran the build. That's kinda the whole point 😜

**Comment by refack** [comment]
> If it could be set to just re-populate the form and leave the "Submit" for manual clicking that would be great for node-stress-single-test. But that's a "nice-to-have".
> Not quite sure what you mean, but when you press rebuild it pre-populates the parameters with whatever you set when you initially ran the build. That's kinda the whole point 😜

I mean fill the form but not submit it. e.g. for `node-stress-single-test` you could start a job on one RUN_LABEL, then hit rebuild, change RUN_LABEL, and submit a second job...
But anyway, just activate it for the gen-pop.

**Comment by gibfahn** [comment]
>start a job on one RUN_LABEL, then hit rebuild, change RUN_LABEL, and submit a second job...

Yeah, that's how it works

**Comment by gdams** [comment]
SGTM

**Comment by gibfahn** [comment]
![image](https://user-images.githubusercontent.com/15943089/28408024-c87cdf9e-6d68-11e7-9696-717f4f5a6e12.png)

So this plugin is already installed, but just not enabled.

>[Rebuilder](http://wiki.jenkins-ci.org/display/JENKINS/Rebuild+Plugin) This plugin is for rebuilding a job using the same parameters. 1.25

I'm not entirely sure why it's called `Rebuilder` instead of `Rebuild Plugin`, but the link is the same.

I've enabled it, if anyone knows why it was disabled (and thinks it should continue to be disabled) please let me know.

**Comment by gibfahn** [comment]
It won't actually be enabled until Jenkins is next restarted. I'm not sure how we normally do that, am I okay to just click the `Restart Jenkins once no jobs are running` button?

**Comment by refack** [comment]
I found this:
![image](https://user-images.githubusercontent.com/96947/28494216-b1c18e1a-6ef5-11e7-9d33-06701945afa8.png)
Seems like it reruns the build with the same parameters, but "auto-submits"

**Comment by gibfahn** [comment]
Restarted and it's there, see:

# Rebuild

Rebuilds that job (like hitting `Build with Parameters` and then pre-filling all the parameters with the same values as that build.

![image](https://user-images.githubusercontent.com/15943089/28496560-00f8c52e-6fa1-11e7-89bd-4b788195bf9c.png)

# Rebuild last

Like clicking on the last build and clicking `Rebuild`.

![image](https://user-images.githubusercontent.com/15943089/28496537-4d7e636e-6fa0-11e7-979a-3c45d605b07c.png)

Note that you get the chance to change parameters before you run.

cc/ @nodejs/collaborators , I found this saves a lot of time when running jobs.

**Comment by refack** [comment]
Regarding restart, I just found its avalible to unauthenticated users
![image](https://user-images.githubusercontent.com/96947/28500906-0538da86-6f9f-11e7-89e6-aeba71291e5d.png)
Is that a security issue?

**Comment by Trott** [comment]
@refack 😱

**Comment by bnoordhuis** [comment]
https://ci.nodejs.org/job/node-test-pull-request/9310/ - "Started by anonymous user"

Although I'm not sure if it actually does anything.  The sub-jobs are done near instantaneously but with reported running times in the tens of minutes, except for an ARM job which seems stuck on something.

**Comment by gibfahn** [comment]
I think this is the (fixed in next release) bug report: https://issues.jenkins-ci.org/browse/JENKINS-36333

I don't think this has anything to do with the Rebuild Plugin, the `Resume Build` button was I think there before. I could be wrong though.

**Comment by rvagg** [comment]
btw I installed this really early on but it was removed because of this security problem, somehow we've lost this institutional knowledge and I'm not really sure how we retain it across people changes. Interesting data point nonetheless. Sorry I missed this issue and the fact that it was back again!

**Comment by refack** [comment]
IMHO the only issue with this is DOS, and that might be mitigated by that you can only `Resume` each job once.

**Comment by gibfahn** [comment]
>btw I installed this really early on but it was removed because of this security problem

@rvagg which security problem, am I wrong in saying:

>I don't think this has anything to do with the Rebuild Plugin, the `Resume Build` button was I think there before.
>https://issues.jenkins-ci.org/browse/JENKINS-36333
