### ISSUE TITLE
Root directory is full on the AIX test machines

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#673]
```
bash-4.3# df -m  
Filesystem    MB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd4         512.00      0.00  100%    17793    93% /
/dev/hd2        2880.00     65.11   98%    52093    70% /usr
/dev/hd9var      576.00    211.17   64%     6741    13% /var
/dev/hd3         320.00    288.90   10%     5965     6% /tmp
/dev/hd1          64.00     63.63    1%        7     1% /home2
/dev/hd11admin    128.00    127.63    1%        5     1% /admin
/proc                 -         -    -         -     -  /proc
/dev/hd10opt    1792.00    877.83   52%    17997     9% /opt
/dev/livedump    256.00    255.64    1%        4     1% /var/adm/ras/livedump
/dev/fslv00    57216.00  42857.32   26%   525148     5% /home
/aha                  -         -    -       533     2% /aha
/dev/ramdisk0   4096.00   4095.05    1%        4     1% /ramdisk0
```

Looks like the issue is these three directories:

```
bash-4.3# du -sm esa etc pconsole
136.98  esa
255.86  etc
94.55   pconsole
```

`136.98+255.86+94.55 = 487.39MB`, so those three directories are taking up pretty much all of the space.

**Comment by jbergstroem** [comment]
I brought this up with @mhdawson the other day as well. I'm not sure if this is a problem though? I don't know AIX standard layout well enough to say if its good or bad -- but the builder lives in `/home` which has lots of space.

**Comment by gibfahn** [comment]
@jbergstroem I guess the question is whether they're getting fuller.

**Comment by mhdawson** [comment]
Looking at another issue I see it says 
```
ksh: There is not enough space in the file system.
```
So I think we should add some space, because that seems like the system is unhappy, even if it does not affect our tests.  Will look at adding some space tomorrow.

**Comment by mhdawson** [comment]
Added space to both be-1 and be-2, complaining message no longer appears.

PR to add step to manual configuration: https://github.com/nodejs/build/pull/675

**Comment by mhdawson** [comment]
Landed PR to added manual step, closing for now.
