### ISSUE TITLE
Running out of space on /tmp on AIX machines

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#674]
A number of recent failures:

```
/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/.deps//home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/obj.target/node_base/src/backtrace_posix.o.d.raw   -c -o /home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/obj.target/node_base/src/backtrace_posix.o ../src/backtrace_posix.cc
/home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/out/Release/obj/gen/node_javascript.cc:64657:1: fatal error: error writing to /tmp//ccXObGxs.s: No space left on device
 }  // namespace node
 ^
```

**Comment by mhdawson** [comment]
One machine looked ok, but the other had a lot of old npm-* directories .  Thinking those might be due to cigtm runs.  I deleted them and we'll see if that fixes things up or if something has changed and we need more /tmp space

**Comment by mhdawson** [comment]
Noticed that deleting npm-* only freed up 2%.  Looks like this one is the bigger culpret:

**Comment by mhdawson** [comment]
deleting that freed up about 50%

**Comment by mhdawson** [comment]
@gibfahn are the directories in the form of 0629edd6-daca-4544-ac99-2ffc3a3f0052 tied to citgm, they seem to be taking a good portion of the space, and there are a number of them from yesterday.

**Comment by mhdawson** [comment]
Build to see if I've freed up enough space: https://ci.nodejs.org/job/node-test-commit-aix/4800/

**Comment by gibfahn** [comment]
@mhdawson yes, those directories are citgm's temp directories. A build was run without the temp directory settings properly configured, which is why they filled up. I thought I'd cleaned up both machines.

**Comment by mhdawson** [comment]
can you take a look and clean up the rest.  When I looked yesterday I only cleaned up enough to get the machines working again.

**Comment by mhdawson** [comment]
@gibfahn happened again.  Saw a failure over the weekend and tmp was full on test-osuosl-aix61-ppc64_be-2.  Lots of directories with watchify-xxxx but those did not contribute significantly to the space.

Issue still seemed to be the directories associated with citgm. Cleaned up all the directories with the command above.  I guess we'll see now if it continues to pile up.

**Comment by richardlau** [comment]
https://github.com/nodejs/build/issues/682

**Comment by Trott** [comment]
Just ran `rm -rf /tmp/*-*-*-*-* /tmp/npm-*` again now and that seems to have cleared things up. Obviously, needing a more permanent solution...

**Comment by gibfahn** [comment]
See https://github.com/nodejs/citgm/issues/396#issuecomment-293217118 , this shouldn't be happening if jobs are configured correctly.

**Comment by sam-github** [comment]
closing, stale issue.

current state is:

```
% parallel-ssh -i -h test-osuosl-aix61-ppc64_be du -s /tmp
[1] 09:38:53 [SUCCESS] test-osuosl-aix61-ppc64_be-1
361936  /tmp
[2] 09:38:53 [SUCCESS] test-osuosl-aix61-ppc64_be-2
541008  /tmp
[3] 09:38:53 [SUCCESS] test-osuosl-aix61-ppc64_be-3
1298880 /tmp
```
