### ISSUE TITLE
Request for temporary access to BSD systems 

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/build#677]
[Reference:] (https://github.com/libuv/libuv/pull/1279#discussion_r110334636)

I would like to have access to BSD systems (net, free, open, and any other supported variants) for development and testing (manual | CI automated) purpose as part of a libuv PR. Also appreciate a little tip on file system structure, anything special abut building, and running automated tests. Thanks in advance.

**Comment by bnoordhuis** [comment]
I can vouch for Gireesh.

> I would like to have access to BSD systems (net, free, open, and any other supported variants)

We have a FreeBSD buildbot but at the moment that's it.

**Comment by gibfahn** [comment]
SGTM

**Comment by mhdawson** [comment]
+1 from me

**Comment by jbergstroem** [comment]
No objections either if people from the libuv crowd like Ben says yes (which he did :). Does someone from the build team want to facilitate or should I do it?

**Comment by gibfahn** [comment]
I can add Gireesh's keys to a couple of the boxes, maybe [test-joyent-freebsd10-x64-1](https://ci.nodejs.org/computer/test-joyent-freebsd10-x64-1/) and [test-digitalocean-freebsd11-x64-1](https://ci.nodejs.org/computer/test-digitalocean-freebsd11-x64-1/), I'll discuss with @gireeshpunathil .

**Comment by jbergstroem** [comment]
@gibfahn please mark which boxes he gets access to in this issue and walk him through the procedure of using it. If need be, perhaps disconnect them from ci while he uses them (I most often don't have to though).

General guidelines:
 - since resources are shared with ci, please use them sparingly; copy a checkout, check disk/cpu usage etc.
 - avoid using root unless you have to (the iojs user is available and what we use for testing)
 - if you have to install packages (lldb, ..), remove them once done. if they don't exist in the package manager, let us know so we can manage state of the machine

**Comment by gibfahn** [comment]
I've added Gireesh's key to:
 - the `root` user on [test-joyent-freebsd10-x64-1](https://ci.nodejs.org/computer/test-joyent-freebsd10-x64-1/)
 - the `freebsd` user on [test-digitalocean-freebsd11-x64-1](https://ci.nodejs.org/computer/test-digitalocean-freebsd11-x64-1/)

We've been through all the above, and he should be good to go.

**Comment by jbergstroem** [comment]
Great!
@gireeshpunathil: thanks for helping out improving libuv :) let us know when you're done using the machines.

**Comment by gireeshpunathil** [comment]
sure, will do, thank you too.

**Comment by qbit** [comment]
There is also this now: https://github.com/joyent/openbsd-kvm-image-builder

[Hopefully](https://github.com/joyent/freebsd-kvm-image-builder/issues/1#issuecomment-303732957) the images show up on Joyent's production env soon!

**Comment by mhdawson** [comment]
@gireeshpunathil do you still need access ?

**Comment by gireeshpunathil** [comment]
The test runs in [#1279](https://github.com/libuv/libuv/pull/1279#issuecomment-305798351) indicated that the darwin code cannot run as it is in *BSD* systems as it is, and needs proper porting.

At the moment, the discussion is on in the PR about viability of PR in v1 vs. v2, so I think I will delay further work on this system(s) until that is resolved. So you may please revoke the access. Thanks!

**Comment by gibfahn** [comment]
Keys removed.
