### ISSUE TITLE
Not enough space on test-osuosl-aix61-ppc64_be-1

### ISSUE THREAD

**Issue by aqrln** [nodejs/build#682]
`node-test-commit-aix` failed with:

```
...
as: There is not enough space in the file system.
Assembler:
/tmp//cch3JIQ9.s: line 7506: 1252-161 A system problem occurred while processing file /tmp/asoYraea
...
```

(see https://ci.nodejs.org/job/node-test-commit-aix/4960/nodes=aix61-ppc64/console)

**Comment by richardlau** [comment]
https://github.com/nodejs/build/issues/674

**Comment by Trott** [comment]
Fixed with `rm -rf /tmp/*-*-*-*-* /tmp/npm-*` although a more permanent fix will have to be concocted. But that's a discussion for #674, so I'll close this. (Feel free to comment or re-open if you think it shouldn't be closed!)
