### ISSUE TITLE
Transfer Jenkins OAuth Application to nodejs (from rvagg)

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#687]
I noticed that the  ci.nodejs.org Jenkins Auth plugin is still owned by @rvagg. It would be good if we could transfer it to the Node.js org so it looks more official.

![image](https://cloud.githubusercontent.com/assets/15943089/25141759/798f3ab2-245c-11e7-81df-23ab01d86325.png)

Apparently you go Setting->Oauth->Transfer and then specify nodejs (cc/ @gdams who's done it before).

**Comment by gibfahn** [comment]
Adding `wg-agenda` to check that this is okay in the meeting.

**Comment by gibfahn** [comment]
Couple of points brought up in the meeting.

 - Is it an easy process?
   - As I noted above, it should be a two minute change.
 - Will there be any loss of data from moving it?
   - There shouldn't be, and in any case if we lose the cache that just means everyone has to click the button again, which isn't the end of the world.
 - Does the app know any sensitive information that we wouldn't want to be accessible to `nodejs` owners?
   - I think it just gets read access to email addresses, and org/team membership, so that shouldn't be too worrying.

**Comment by rvagg** [comment]
Fine by me, it was done under my name because nodejs is an org, not a user, but if this is possible then :+1:

**Comment by rvagg** [comment]
![screenshot 2017-04-19 12 37 09](https://cloud.githubusercontent.com/assets/495647/25161018/eef3770a-24fc-11e7-9f05-cfccc18b9c36.png)

OK, so it's possible to transfer to an org, the next question is permission. I don't know who gets access to the secret on this in the org, and we have a _lot_ of org members. Instead of trying to find a doc (I can't so far), how about we test. I've made a new OAuth app for the nodejs org, can you all report whether you can see this or not? https://github.com/organizations/nodejs/settings/applications/517086

**Comment by rvagg** [comment]
There's a second app btw, the Node.js Release Jenkins one

**Comment by gdams** [comment]
@rvagg I believe that it's only the owner of the org who has full permissions

**Comment by gibfahn** [comment]
>can you all report whether you can see this or not? 

I can't see it

**Comment by rvagg** [comment]
OK, well that's no good, since @gibfahn isn't even an org owner, we don't really want that key to be leaked

**Comment by gibfahn** [comment]
>OK, well that's no good, since @gibfahn isn't even an org owner, we don't really want that key to be leaked

To clarify, I am **not** able to see it, which suggests to me that it's only org owners who can.

**Comment by mhdawson** [comment]
I **can** see it.

**Comment by gibfahn** [comment]
ping @rvagg , given that I think we've established that only org owners can see it, maybe time to make the move?

cc/ @Trott

**Comment by Trott** [comment]
Came up again today onboarding @BridgeAR. Not a big deal, but don't want this to be forgotten about. kthxbai

**Comment by rvagg** [comment]
Well that was much easier than I thought, nothing needed to change on the Jenkins end, just needed to do the transfer on the GitHub side and didn't need to touch Jenkins. So all done!
