### ISSUE TITLE
meeting planning: Thumbs up / thumbs down

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#689]
(we should really have a template for creating meeting issues)

Lets use thumbs up/thumbs down for noting attendance to the meeting via the issue. 👍🏻 for "I will attend" and  👎🏻 for "not attending". This gives us the benefit of also seeing build member activity.

**Comment by gibfahn** [comment]
There were no objections to this at the meeting. Next steps are for someone to write up the meeting template and PR it to the build WG, and then we'll start doing this for future meetings.

@jbergstroem I can do the PR if you want (I'm already doing the minutes).

**Comment by rvagg** [comment]
I have a request re meetings too -- can we consider adjusting our time for it? DST has made it go back to 6am for me and that sucks so deeply (for me at least). I don't want to exclude folks but perhaps we could do a spreadsheet similar to what the CTC uses to find good meeting times and work out if there is a better time of day? @mhdawson do you have time to facilitate that? Perhaps copy the CTC one and leave you and I on it and have others fill it in. Alternatively perhaps we just expand the CTC one and include Build, I don't know if there's anything particularly sensitive there, what do you think @trott?

**Comment by Trott** [comment]
> I don't know if there's anything particularly sensitive there, what do you think @trott?

I wouldn't object, but I guess if you're asking my preference: separate spreadsheet. I don't know that sharing the link (and thus the data in the spreadsheet) is a violation of anyone's privacy, but it *feels* wrong to me. So just make a new one. But if you want to instead just add a Build tab, I'm not going to stop you.

**Comment by Trott** [comment]
Also: I've not been terribly active in the WG. I'd like to maintain some elevated privileges in Jenkins to take problematic hosts offline and to be able to log in to the machines to terminate stalled tests and stuff like that. If I can somehow do that without having the guilt of missing pretty much every WG meeting and not really participating, that would be awesome. On the other hand, if the two are tied closely together--like, you don't want someone who's not paying attention to Build WG matters to be able to mess things up--I get it.

**Comment by piccoloaiutante** [comment]
@gibfahn if you want i can go ahead with the PR for template. 

@rvagg yes 6AM sucks a lot, lets try to find a better timeframe.

**Comment by mhdawson** [comment]
Opened issue here to work on new time: https://github.com/nodejs/build/issues/698

**Comment by maclover7** [comment]
ping -- can this be closed?

**Comment by gibfahn** [comment]
Yep
