### ISSUE TITLE
Collaborator meeting in Berlin 4th-5th May

### ISSUE THREAD

**Issue by piccoloaiutante** [nodejs/build#690]
I'm trying to arrange a two hours slot for this WG during the next collaborator meeting in Berlin and I was wondering who is going to attend it. From the last standup I know that @mhdawson, @gibfahn and me will be there. Is there anyone else that is going to attend it?

**Comment by gibfahn** [comment]
@jbergstroem remotely! 

It'd be good to try to work out a rough agenda for what we should try to work on. 

One good goal might be to get everyone running Johan's refactor branch and flushing out bugs, with the aim of getting it landed.

**Comment by MylesBorins** [comment]
I'll be there

**Comment by santigimeno** [comment]
I'll be there too and would love to help even though I'm not a member. Would that be ok?

**Comment by gibfahn** [comment]
>I'll be there too and would love to help even though I'm not a member. Would that be ok?

👍 💯 Yes!

**Comment by jbergstroem** [comment]
> @gibfahn said:
> One good goal might be to get everyone running Johan's refactor branch and flushing out bugs, with the aim of getting it landed.

That'd be awesome. I can only assume that there's a lot of things fixed/new bugs introduced with ansible upgrades.

The big gaps are:
1. aix -- most of the setup scripts still seem fully manual
2. windows
3. its falling out of date; there's been a few changes to things like www we need to re-integrate

**Comment by refack** [comment]
I'm jealous of you all going. I can't leave the US :(
I'd be happy to join your session remotely to help with windows issues.

**Comment by refack** [comment]
P.S. VS2017

**Comment by gibfahn** [comment]
>aix -- most of the setup scripts still seem fully manual

FYI, we're looking at this, and I *think* we've got something working

**Comment by mhdawson** [comment]
Signed us up here, not sure what time was going to work for @jbergstroem  so just chose one after what I think his work hours were, Johan feel free to move. https://docs.google.com/spreadsheets/d/1gJoyiq0z6rjS7jEoHkRe6jte8Dd7ZBkwD3WjOh6djvQ/edit#gid=1606836561

**Comment by piccoloaiutante** [comment]
One thing we could also do is to identify one or two issues as `good-as-first-contribution` so that new comers can start helping the build group.

**Comment by refack** [comment]
Yes please!
