### ISSUE TITLE
Adding zOS machines to CI

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#693]
We have some zOS machines being made available through Marius University.

These will allow us to start testing the libuv zOS port which is already in the repos and position us to be able to build Node.js once the V8 port to zOS goes back into the v8 repos.

First step is to get build team members to acknowledge the terms an conditions. I'm going to send an email to:

* @rvagg 
* @jbergstroem 
* @joaocgreis 
* @mhdawson 

with the terms.

**Comment by gibfahn** [comment]
Please cc me as well, I'd like to help out with this.

**Comment by mhdawson** [comment]
@gibfahn sent terms to you.

**Comment by mhdawson** [comment]
Terms were acknowledged a while back.

Initial wip PR for adding configuration through ansible.
https://github.com/nodejs/build/pull/796

**Comment by mhdawson** [comment]
Machines have been added a while back, closing.
