### ISSUE TITLE
New meeting time for build WG

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#698]
Have created spreadsheet here: https://docs.google.com/spreadsheets/d/1E4Gb2dzu245nA8YTWFVXQQaYE-85HtzfZTeLFmpljBk/edit?usp=sharing

@nodejs/build please fill in your availability.

**Comment by piccoloaiutante** [comment]
@mhdawson should I add mine even if i'm not part of the WG?

**Comment by gibfahn** [comment]
>@mhdawson should I add mine even if i'm not part of the WG?

Yes!

**Comment by mhdawson** [comment]
@piccoloaiutante just to add to @gibfahn response.  Absolutely we want to take into account all regular attendees.

**Comment by mhdawson** [comment]
Hmm, no easy choice from the spreadsheet.  We may need to look at having 2 different times.

**Comment by mhdawson** [comment]
adding to agenda for this weeks meeting.

**Comment by mhdawson** [comment]
Ok agreed on alternating between 20 and 22 UTC.  I just updated the Foundation calendar.  Let me know if it does not match what's expected.  Closing.
