### ISSUE TITLE
Temporary access to 32-bit Linux box

### ISSUE THREAD

**Issue by targos** [nodejs/build#700]
Hello. To debug a segfault that my PR (https://github.com/nodejs/node/pull/12621) is causing, I would like a temporary access to one of the 32-bit Linux boxes. `centos5-32` would be nice.

**Comment by gibfahn** [comment]
SGTM

**Comment by mhdawson** [comment]
SGTM

**Comment by targos** [comment]
The issue has been fixed thanks to @addaleax. I do not need access anymore. Thanks!
