### ISSUE TITLE
VPN access to release Jenkins

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#701]
Johan and I have been discussing how we can increase the security of our release Jenkins. With the continual stream of Jenkins vulnerabilities we really want to lock it down as much as possible because the last thing any of us wants is to have to rebuild all of our release infrastructure just from a suspicion of a breach.

So, we already have fixed IP addresses for all of our release nodes and they are locked in via iptables for connecting to the master. We don't have that for HTTP access for Jenkins admins or release team members. There is a GitHub authentication step in between and it's theoretically locked to just admins and releasers, but that only affords a small amount of assurance since vulnerabilities could exist that get you past that step.

We're considering implementing VPN access to the release Jenkins server, which would mean that anyone needing to access the HTTP Jenkins interface would need to connect first to a VPN, otherwise they're blocked. It's not practical to set up all of the build nodes to connect this way but we have that fixed list of IPs that we can give a pass to. There's also the question of how we handle the GitHub OAuth process as I don't know if we can pin down GitHub's client to a particular IP or IP range. So we may have to get creative with implementing an HTTP firewall of sorts that blocks everything but OAuth pages unless you're from one of the build node IP addresses or have connected in via a VPN.

The cost here is twofold:

* Administrative, we'd need to set this up and maintain it and write up Ansible scripts for it all. We have some experience already on the team so it's not a huge deal, @jbergstroem has plenty of experience with Openswan and I've got OpenVPN, so we get a choice there (the former seems like a better option).
* User pain, and this is for @nodejs/release to help consider. Basically every time you need to cut a release, or a test or RC build, you'd need to be logged in to the VPN. We'd give you certificates and config and help you set it up, but it's yet another thing you'd need to bother with on your computer(s) in order to interact with the project. We have to weigh cost and benefit here and the benefit of security is pretty high I think so we just need to get a feel for the cost of the pain involved for @nodejs/release. So if anyone on that team has concerns please let us know. Otherwise we'll likely proceed with the assumption that it's not going to be a _huge_ deal to ask releasers to have a VPN client set up.

**Comment by cjihrig** [comment]
As annoying as it might be, I'm OK with the VPN requirement.

**Comment by mhdawson** [comment]
I'm not on the release team, but have done a fair amount in terms of configuring the jobs which I assume would required VPN access as well.  I'm ok with the VPM requirement as well.  I just hope the client can co-exist with other VPN clients as I have to use our corporate one as well.

**Comment by maclover7** [comment]
Closing for now as something that would be nice to have, but seems to not currently be within our means. If someone wants to tackle this, please feel free to reopen.
