### ISSUE TITLE
is it possible to mark out-of-matrix tests as gray?

### ISSUE THREAD

**Issue by refack** [nodejs/build#703]
Like in this case?
![image](https://cloud.githubusercontent.com/assets/96947/25529272/6c94cf1c-2bef-11e7-94e2-52b50eb2868a.png)

**Comment by refack** [comment]
maybe calling `java -Dhudson.util.ProcessTree.disable=true -jar jenkins.war`
as suggested in http://stackoverflow.com/questions/25655867/how-can-i-abort-a-jenkins-build

**Comment by gibfahn** [comment]
>To reliably kill processes spawned by a job during a build, Jenkins contains a bit of native code to list up such processes and kill them. This is tested on several platforms and architectures, but if you find a show-stopper problem because of this, you can disable this feature by setting a Java property named "hudson.util.ProcessTree.disable" to the value "true".

How does this mark out-of-matrix tests as grey?

I'm not entirely sure what issue you're asking for a fix for, but my guess is that you mean that when you go to https://ci.nodejs.org/job/node-test-commit-linux/ it doesn't show you the tests that haven't run yet for the latest build?

![image](https://cloud.githubusercontent.com/assets/15943089/25535170/0fdd83f6-2c2e-11e7-84c5-c7221c6c9c7d.png)

If you go to a specific build though (e.g. https://ci.nodejs.org/job/node-test-commit-linux/9475/) it does show builds that haven't run yet (or that weren't run with this configuration) as grey:

![image](https://cloud.githubusercontent.com/assets/15943089/25535188/1b872dc4-2c2e-11e7-98bf-72368d8ab124.png)

**Comment by gibfahn** [comment]
Of course that doesn't work for things where we're doing an `exit 0` within the tests. I think the answer is to skip things in the combination filter where possible.

**Comment by refack** [comment]
I mean cases like the screenshot in the first comment
```
Not building v8 on Windows 2008R2 with vs2013 as it is only supported up to v5.x
...
Finished: SUCCESS
```

**Comment by joaocgreis** [comment]
The screenshot is from `node-stress-single-test`, that uses a shallow structure of just one Jenkins job to do everything, for simplicity. It's debatable if this is an advantage going forward.

For the `node-test-*` jobs, this is skipped in combination filters (which in turn rises issues like https://github.com/nodejs/build/issues/647). This is only possible if there is a parent job that gets the version of node and passes it as a parameter to the subjobs, so it is not possible in the current structure of `node-stress-single-test`.

**Comment by refack** [comment]
Thanks @joaocgreis

**Comment by gibfahn** [comment]
>For the node-test-* jobs, this is skipped in combination filters (which in turn rises issues like #647). This is only possible if there is a parent job that gets the version of node and passes it as a parameter to the subjobs, so it is not possible in the current structure of node-stress-single-test.

As a workaround we could just assume any branch will have `v4` in the branch name if it's a `v4.x` branch (or equivalent for other major versions). That won't cover every case, but it allows us to skip things in the combination filter if the branch has the right name, and it'll work for all the official branches.

**Comment by refack** [comment]
I've digged just a little bit, but is there really no way to tell Jenkins to ignore the build from the build script?
