### ISSUE TITLE
questions: about Jenkins 

### ISSUE THREAD

**Issue by refack** [nodejs/build#707]
1. How long does it keep job logs? [this one](https://ci.nodejs.org/view/All/job/node-test-pull-request/7858/) disapeared after less the 9 hours?
2. Can you extend the cookie expiration, it seems like I need to login everytime I use it...

BTW: It's a fantastic tool, super super useful!!! 🥇 
Thanks!

**Comment by jbergstroem** [comment]
> @refack said:
> 1. How long does it keep job logs?

Currently 7 days as defined by our backup job (also: disk at 85% full)

> 2. Can you extend the cookie expiration, it seems like I need to login everytime I use it...

Can't find a setting for it. Sorry.

**Comment by refack** [comment]
Thanks!

**Comment by gibfahn** [comment]
>Can you extend the cookie expiration, it seems like I need to login everytime I use it...

Maybe this:

http://stackoverflow.com/questions/26407541/increase-the-jenkins-login-timeout
