### ISSUE TITLE
Temporary access to a FreeBSD host

### ISSUE THREAD

**Issue by targos** [nodejs/build#709]
I'd like to try to debug the build issue with [FreeBSD and V8 5.8](https://ci.nodejs.org/job/node-test-commit-freebsd/8704/nodes=freebsd10-64/console).

/cc @gibfahn

**Comment by mhdawson** [comment]
LGTM

**Comment by gibfahn** [comment]
LGTM, I can put his key on the machines.

**Comment by gibfahn** [comment]
Added a new label `access request`, as we seem to get a lot of these

**Comment by gibfahn** [comment]
Added @targos's key to the `freebsd` user on `test-digitalocean-freebsd11-x64-1` (`45.55.90.237`).

**Comment by fhinkel** [comment]
@targos Can you find out what compiler version we use there?

**Comment by gibfahn** [comment]
I think it's:

```
freebsd@test-digitalocean-freebsd11-x64-1:~ $ cc --version
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: x86_64-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by fhinkel** [comment]
Thanks!

**Comment by targos** [comment]
The issue has been fixed. You can revoke my access. Thanks!

**Comment by gibfahn** [comment]
Key removed.
