### ISSUE TITLE
Add Michele Capra (@piccoloaiutante) to the Build WG

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#711]
@piccoloaiutante has been helping out a lot with build stuff, I actually thought he was already a member.

As he's not, I propose we add him.

_**EDIT:**_ Not sure if we normally give justification, but just to be thorough:

- Michele works for Nearform, so there are plenty of Collaborators to vouch for him.
- He's already done a bunch of work for us, most recently at the collaborator summit.
- He's already a member of the org.

**Comment by joaocgreis** [comment]
+1! Michele has been participating and helpful for some months now, it's well about time we add him!

**Comment by mhdawson** [comment]
+1 from me as well.

**Comment by gibfahn** [comment]
@nodejs/build this is currently our only agenda item, so it'd be good if we could weigh in on this.

**Comment by gibfahn** [comment]
+1 from me (to be explicit)

**Comment by mhdawson** [comment]
Agreed in meeting, welcome. :)

**Comment by gibfahn** [comment]
@jbergstroem can you arrange the onboarding?

**Comment by gibfahn** [comment]
>@piccoloaiutante I assume you will be more active in the Windows category of things?

From what I understood @piccoloaiutante is cross-platform user (main machine is a mac etc.), he's just been doing lots of Windows stuff because that's where there were things to be done. But it definitely makes sense to have @joaocgreis involved anyway.

**Comment by jbergstroem** [comment]
Then I'll have first dibs :) I'll set it up

**Comment by piccoloaiutante** [comment]
Thank guys for the on boarding. Let say that my background is on windows but I've been using other operating systems for a while. Also for me it's easy to get new VM on my laptop on whatever windows version we want as I have and MSDN subscription.

**Comment by joaocgreis** [comment]
@jbergstroem happy to join, let me know when!

**Comment by jbergstroem** [comment]
Can you guys do tomorrow or Wednesday? Your later pm, my not-as-late pm?

**Comment by piccoloaiutante** [comment]
@jbergstroem Wednesday works for me, if it's not too long we ca do it after dinner around 9 PM CET if that is better for you.

**Comment by jbergstroem** [comment]
@piccoloaiutante 9pm CET is ok for me. @joaocgreis ?

**Comment by joaocgreis** [comment]
Works for me as well. I'm assuming you mean CEST, that is 7 PM UTC, 9 PM in Italy, 3 PM in Santiago.

**Comment by piccoloaiutante** [comment]
@joaocgreis yes i meant CEST :)

**Comment by jbergstroem** [comment]
SGTM!

**Comment by gibfahn** [comment]
@piccoloaiutante you're in the [build Github team](https://github.com/orgs/nodejs/teams/build/members), but not in [the README](https://github.com/nodejs/build#people). I assume you've been onboarded, so could you raise a PR that `Fixes:` this one adding yourself to the README?

**Comment by gibfahn** [comment]
ping @piccoloaiutante
