### ISSUE TITLE
jenkins: give little more CPU priority to the WEB UI

### ISSUE THREAD

**Issue by refack** [nodejs/build#713]
I'm not sure how the web server is set up, maybe it needs a lower `nice` value.
Or maybe you could shorten the task queue by one so there will always be a free core for the UI?

**Comment by jbergstroem** [comment]
I hear what you're asking, but its not that simple. We've done a lot of profiling of jenkins in the past, and one way to speed it up is to avoid using tap. This is not about the UI being slow; it's about waiting for jenkins to parse hundreds of XMLs. If you search for tap in the issue tracker you'll find a few issues about performance and additionally a stub to a solution (ask gibson if you're at the berlin summit!).

Going to close this, but if you have insights into the fact that it is indeed the UI, please reopen!

**Comment by refack** [comment]
Right now the build queue is empty but the UI is still sluggish 🤷‍♂️ (~1 minute from submit until new pages loads, and I got 500-timeouts several times looking at completed jobs)
We are all web devs here, and it's hard to believe Jenkins it that badly designed 😕 

![image](https://user-images.githubusercontent.com/96947/27957871-4d6a5072-62ee-11e7-8089-010bdb2032fb.png)

Let's write a new Node.js based CI 😉

**Comment by jbergstroem** [comment]
I personally still think that moving to buildbot would be the most mature move, but seeing how I have little time to put in at the moment I'm happy with any solution that is more performant.
