### ISSUE TITLE
Build WG meeting 9th May 2017 at 4 EST 

### ISSUE THREAD

**Issue by piccoloaiutante** [nodejs/build#716]
I'm putting this issue as reminder that there should be a meeting today as per schedule. I'm not sure if we want to have one since we had another unofficial one during collaborator summit in Berlin. Unfortunately I can't attend it today. I suggest to use 👍 and 👎 to see who can attend it.

**Comment by rvagg** [comment]
Did a 👎 cause I'm not going to get enough notice whether it goes ahead or not and I'm not a fan of needless 6am wakeups!

**Comment by joaocgreis** [comment]
cc @nodejs/build

**Comment by jbergstroem** [comment]
Can't join either. Sorry!

**Comment by joaocgreis** [comment]
The only issue with WG agenda is https://github.com/nodejs/build/issues/711 , I believe we can make progress through github if needed. I suggest we skip this week and schedule for May 30, 3 weeks from today.

**Comment by jbergstroem** [comment]
A summary of the summit would be nice to hear!

**Comment by piccoloaiutante** [comment]
I think that @mhdawson could have some notes about it.

**Comment by mhdawson** [comment]
I'll be writing up a short summary of the summit later today and will share in some form.

**Comment by piccoloaiutante** [comment]
@mhdawson let us know when your short summary is ready. I'll close this issue in the meantime.
