### ISSUE TITLE
Unable to access ci-release

### ISSUE THREAD

**Issue by jasnell** [nodejs/build#717]
Attempting to do the 8.0.0 release candidate build... unable to because of....

![image](https://cloud.githubusercontent.com/assets/439929/25917294/639655fc-357c-11e7-8389-aea3b72be5aa.png)

**Comment by gibfahn** [comment]
That's odd, the release team still have access according to the permissions, and you're definitely [still in the release team](https://github.com/orgs/nodejs/teams/release). @nodejs/release is anyone else having this issue?

![image](https://cloud.githubusercontent.com/assets/15943089/25923479/a8029d8c-35d5-11e7-94e6-905e0449315d.png)

**Comment by gibfahn** [comment]
The Github Auth plugin is currently on `0.26`, and there's a `0.27` available, no idea if that's relevant to anything.

![image](https://cloud.githubusercontent.com/assets/15943089/25923593/20984986-35d6-11e7-8ebc-1f058194de57.png)

**Comment by jbergstroem** [comment]
@jasnell has spesjul permissions on `ci` at least (not part of a group), so this might be a github acl thing?

**Comment by cjihrig** [comment]
>  is anyone else having this issue?

The release Jenkins seems to be working for me. It looks like @jasnell was able to get in and start a job.

**Comment by rvagg** [comment]
@jasnell not a solution per se but perhaps try navigating straight to https://ci-release.nodejs.org/job/iojs+release/ and see if you get anywhere, that shouldn't require "Overall" I think

**Comment by maclover7** [comment]
ping @jasnell -- can this be closed?
