### ISSUE TITLE
CITGM runs for 16 hours starving other jobs

### ISSUE THREAD

**Issue by refack** [nodejs/build#719]
How can I help?

![image](https://cloud.githubusercontent.com/assets/96947/26026364/97ff095e-37c7-11e7-9b76-67d331680014.png)

For example this one has been waiting for a fedore22 worker for 6 hours
![image](https://cloud.githubusercontent.com/assets/96947/26026395/feec050e-37c7-11e7-8766-715c277236e4.png)

**Comment by gibfahn** [comment]
This is a CitGM issue, so you should raise it on https://github.com/nodejs/citgm. We definitely need to work out what's going on and fix it.

**Comment by gibfahn** [comment]
Thanks, I'll close this for now, we can reopen if it turns out to be an infra issue.

**Comment by refack** [comment]
> We definitely need to work out what's going on and fix it.

[question] Is it a real problem to have more than one worker per platform? For example https://ci.nodejs.org/label/fedora22/ one is off-line?

**Comment by gibfahn** [comment]
>Is it a real problem to have more than one worker per platform?

Do you mean "Is it a problem to have _only_ one worker per platform"? If so then the answer is yes.

**Comment by gibfahn** [comment]
@Trott I see you took https://ci.nodejs.org/computer/test-rackspace-fedora22-x64-1/ offline as it was failing to build. Do you know if it's fixed?

**Comment by refack** [comment]
> Do you mean "Is it a problem to have only one worker per platform"? If so then the answer is yes.

Yes. Also is it a financial/human-bandwidth/whatevs problem to maintain redundancies? or an oversight?
Again, if I can help in anyway, I'm pretty much available.

**Comment by gibfahn** [comment]
>is it a financial/human-bandwidth/whatevs problem to maintain redundancies? or an oversight?

Maintaining the infra in general is a bandwidth problem, and yeah, there's definitely lots that needs doing. I'll see if I can find some ways to get you involved, we're always keen to have more people help out, it's just there's a lot of specific stuff to learn about how we've ended up doing things in Node.

**Comment by refack** [comment]
I do devops too 😊 , also don't need to see the "secrets"

**Comment by Trott** [comment]
> @Trott I see you took test-rackspace-fedora22-x64-1 offline as it was failing to build. Do you know if it's fixed?

@gibfahn Yikes! That was weeks ago! I have no idea if anyone fixed it or not. /ping @jbergstroem

**Comment by gibfahn** [comment]
>I do devops too 😊 , also don't need to see the "secrets"

The amount you can do without Jenkins or machine access is limited though. The [ansible work](https://github.com/nodejs/build/issues/712) is hopefully a good way in.
