### ISSUE TITLE
IPv6 localhost isn't defined in /etc/hosts on AIX

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#721]
[This `ws` test](https://github.com/websockets/ws/blob/master/test/WebSocket.test.js#L93-L103) is failing on CitGM because our AIX boxes are missing the `::1             localhost` line from `/etc/hosts`, despite having IPv6 enabled. I have confirmed that appending that line fixes the issue (I then removed it again).

```bash
bash-4.3$ node -e "require('dns').lookup('localhost', {family: 6}, (err, address, family) => console.log(err,address,family))"
{ Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost' } undefined undefined

bash-4.3$ echo "::1             localhost" >>/etc/hosts

bash-4.3$node -e "require('dns').lookup('localhost', {family: 6}, (err, address, family) => console.log(err,address,family))"
null '::1' 6
```

I'd suggest we add this to `/etc/hosts` on the machines, and also to the setup instructions.

cc/ @mhdawson

**Comment by mhdawson** [comment]
@gibfahn can you go ahead and do that ?

**Comment by gibfahn** [comment]
Added to both test machines, PR is #728

CI run on AIX to make sure everything's still kosher: https://ci.nodejs.org/job/node-test-commit-aix/5980/

**Comment by treysis** [comment]
I think this is also an issue on `smartos18`?

**Comment by treysis** [comment]
https://ci.nodejs.org/job/node-test-commit-smartos/37894/nodes=smartos18-64/console

**Comment by treysis** [comment]
I think `smartos18` is also affected by this in some way. The debugger is listening on `::1`, but the tests trying to connect to `127.0.01`.
