### ISSUE TITLE
update clang on FreeBSD 10

### ISSUE THREAD

**Issue by targos** [nodejs/build#723]
Ref: https://github.com/nodejs/node-v8/issues/1

Latest V8 cannot be compiled with version 3.4.1. We should try to update to 3.4.2 and see if that fixes the crash.

/cc @jbergstroem

**Comment by jbergstroem** [comment]
Ok, I will open a PR tomorrow.

**Comment by targos** [comment]
ping

**Comment by jbergstroem** [comment]
Truly sorry :( $wrk, etc etc. I will get to it as soon as I can; likely tomorrow morning.

**Comment by targos** [comment]
ping @nodejs/build (no worries @jbergstroem. I totally understand that you can be busy)

**Comment by Trott** [comment]
@gibfahn Did you mean to add the `wg-agenda` label or is `ctc-agenda` correct? If `ctc-agenda`, can you (or someone else) provide a short description of what you hope CTC will do? Thanks!

**Comment by joaocgreis** [comment]
Was `wg-agenda` and was already discussed in https://github.com/nodejs/build/issues/766

**Comment by kfarnung** [comment]
I'm going to be taking a look at it this week.

**Comment by kfarnung** [comment]
@targos I've taken a look at this and it's not too straightforward.  I have opened #772 for the first step, installing the `clang34` package, but there's a bit more subtlety to the builds on FreeBSD.  I'll keep working on this throughout the week.

As a side note, are the builds still failing with 3.4.1?  I don't see any indication of the original build issue in the CI or in my local builds.

**Comment by targos** [comment]
@kfarnung Thank you for looking into this.
The builds are failing with V8 6.0. You can try to reproduce with this branch: https://github.com/targos/node/tree/v8-6.0

The latest failure on CI is here: https://ci.nodejs.org/job/node-test-commit-freebsd/9863/nodes=freebsd10-64/console

**Comment by kfarnung** [comment]
Thanks @targos, that was the key.  I'm now able to repro the crash.  Unfortunately I'm still seeing the crash on 3.4.2, see attached, so I'm going to try 3.5 and 3.8 as well, just to see if any of the newer versions resolve the issue.

[freebsd10-clang34-output.txt](https://github.com/nodejs/build/files/1106655/freebsd10-clang34-output.txt)

**Comment by kfarnung** [comment]
@jbergstroem Is there any objection to upgrading clang to 3.8.1?  That's approximately the same version as FreeBSD 11 (which uses 3.8.0).

**Comment by jbergstroem** [comment]
@kfarnung I will have a chat with package maintainers in FreeBSD seeing how they should/would run into this as well.

**Comment by jbergstroem** [comment]
> @jbergstroem said:
> I will have a chat with package maintainers in FreeBSD seeing how they should/would run into this as well.

I've emailed with @bradleythughes (one of the node maintainers in ports/freebsd) about this and their build system can reproduce the same issues. The idea is to spend a bit of time seeing how feasible it is to fix this upstream (v8).

In general, is the v8 team moving forward with raising the lowest required clang version? @targos do you perhaps know?

**Comment by targos** [comment]
@jbergstroem I don't know if there is a lowest required clang version.
Note that the crash cannot be reproduced with V8 6.1 so you might be able to bisect V8 to find the fix.

**Comment by MylesBorins** [comment]
Can we get this upgrade? This is blocking us from the V8 6.0 release

**Comment by gibfahn** [comment]
>Note that the crash cannot be reproduced with V8 6.1 so you might be able to bisect V8 to find the fix.

Sounds like we need to bisect and then have that fix backported. Upgrading clang sounds good too, but a backport sounds quicker.

**Comment by MylesBorins** [comment]
@targos is doing this bisect something you can do?
@ofrobots perhaps you can help?

**Comment by targos** [comment]
The error message from https://github.com/nodejs/node-v8/issues/1#issue-227257916 mentions:
```
3.	../deps/v8/src/wasm/wasm-module.cc:2656:5: Generating code for declaration 'AsyncCompileJob::CompileTask<0>::CompileTask'
c++: error: unable to execute command: Segmentation fault (core dumped)
```

The code for AsyncCompileJob moved in https://github.com/v8/v8/commit/c7892d3577f53a707128bad7a392e05c2d904b60.
IMO it's highly probable that this is what "fixed" the crash. I will try to backport this commit.

**Comment by targos** [comment]
I give up. This file had too many changes between 6.0 and the refactoring...

**Comment by jbergstroem** [comment]
So, have we established a version we're going with?

**Comment by kfarnung** [comment]
If we want to stay with current OS packages then it's 3.8.1 (which is slightly ahead of the FreeBSD 11 machine which uses 3.8.0).

**Comment by gibfahn** [comment]
3.8.1 SGTM

**Comment by jbergstroem** [comment]
Ok, I can do the PR.

**Comment by kfarnung** [comment]
You can base it on https://github.com/nodejs/build/pull/772

**Comment by MylesBorins** [comment]
@targos I dug in a little bit more and it would appear the biggest change (aside from the giant refactor) was making `AsyncCompileJob::CompileTask` no longer a template class. I'm thinking that the bug in Clang is related to this

**Comment by MylesBorins** [comment]
OMG!!! I think I have a fix

<details>
From 70b4ec5249e7aa120f90e25188e0de636b4ae905 Mon Sep 17 00:00:00 2001
From: Myles Borins <mylesborins@google.com>
Date: Tue, 25 Jul 2017 16:13:38 -0700
Subject: [PATCH 1/1] v8: fix compilation error on BSD 10

AsyncCompileJob::CompileTask in the WebAssembly compiler pipeline
is a template function in V8 6.0. This appears to be the cause of
build failures on BSD 10 with Clang 3.4.1. In 6.1 a refactor modified
the method to no longer be a template function, which appears to fix
compilation. This patch backports the changes to the method and
updates how the function is called throughout the pipeline.

Fixes: https://github.com/nodejs/build/issues/723
Refs: https://github.com/v8/v8/commit/c7892d3577f53a707128bad7a392e05c2d904b60
---
 deps/v8/src/wasm/wasm-module.cc | 20 ++++++++++++--------
 1 file changed, 12 insertions(+), 8 deletions(-)

diff --git a/deps/v8/src/wasm/wasm-module.cc b/deps/v8/src/wasm/wasm-module.cc
index 4b346e6bc7..2f30bfedd3 100644
--- a/deps/v8/src/wasm/wasm-module.cc
+++ b/deps/v8/src/wasm/wasm-module.cc
@@ -2775,16 +2775,18 @@ class AsyncCompileJob {
 
   // A closure to run a compilation step (either as foreground or background
   // task) and schedule the next step(s), if any.
-  template <TaskType task_type>
   class CompileTask : NON_EXPORTED_BASE(public v8::Task) {
    public:
-    constexpr static TaskType type = task_type;
     AsyncCompileJob* job_ = nullptr;
     CompileTask() {}
     void Run() override = 0;  // Force sub-classes to override Run().
   };
 
-  class SyncCompileTask : public CompileTask<SYNC> {
+  class AsyncCompileTask : public CompileTask {
+
+  };
+
+  class SyncCompileTask : public CompileTask {
    public:
     void Run() final {
       SaveContext saved_context(job_->isolate_);
@@ -2798,7 +2800,8 @@ class AsyncCompileJob {
 
   template <typename Task, typename... Args>
   void DoSync(Args&&... args) {
-    static_assert(Task::type == SYNC, "Scheduled type must be sync");
+    static_assert(std::is_base_of<SyncCompileTask, Task>::value,
+                  "Scheduled type must be sync");
     Task* task = new Task(std::forward<Args>(args)...);
     task->job_ = this;
     V8::GetCurrentPlatform()->CallOnForegroundThread(
@@ -2807,7 +2810,8 @@ class AsyncCompileJob {
 
   template <typename Task, typename... Args>
   void DoAsync(Args&&... args) {
-    static_assert(Task::type == ASYNC, "Scheduled type must be async");
+    static_assert(std::is_base_of<AsyncCompileTask, Task>::value,
+                  "Scheduled type must be async");
     Task* task = new Task(std::forward<Args>(args)...);
     task->job_ = this;
     V8::GetCurrentPlatform()->CallOnBackgroundThread(
@@ -2817,7 +2821,7 @@ class AsyncCompileJob {
   //==========================================================================
   // Step 1: (async) Decode the module.
   //==========================================================================
-  class DecodeModule : public CompileTask<ASYNC> {
+  class DecodeModule : public AsyncCompileTask {
     void Run() override {
       ModuleResult result;
       {
@@ -2958,7 +2962,7 @@ class AsyncCompileJob {
   //==========================================================================
   // Step 3 (async x K tasks): Execute compilation units.
   //==========================================================================
-  class ExecuteCompilationUnits : public CompileTask<ASYNC> {
+  class ExecuteCompilationUnits : public AsyncCompileTask {
     void Run() override {
       TRACE_COMPILE("(3) Compiling...\n");
       for (;;) {
@@ -3011,7 +3015,7 @@ class AsyncCompileJob {
   //==========================================================================
   // Step 4b (async): Wait for all background tasks to finish.
   //==========================================================================
-  class WaitForBackgroundTasks : public CompileTask<ASYNC> {
+  class WaitForBackgroundTasks : public AsyncCompileTask {
    public:
     explicit WaitForBackgroundTasks(ErrorThrower thrower)
         : thrower_(std::move(thrower)) {}
-- 
2.13.3


</details>

**Comment by MylesBorins** [comment]
I think I have a fix

https://github.com/MylesBorins/node/commit/70b4ec5249e7aa120f90e25188e0de636b4ae905

**Comment by bnoordhuis** [comment]
@MylesBorins We updated the baseline to clang 3.4.2 for precisely the reason you describe in the commit log.

**Comment by MylesBorins** [comment]
I landed a fix upstream to V8 ... So we are good either way 😂

**Comment by ignisf** [comment]
@MylesBorins could you please link to your change in upstream V8?

**Comment by ignisf** [comment]
Ah, nvm, found it https://chromium-review.googlesource.com/c/v8/v8/+/585979

**Comment by targos** [comment]
I suppose this can be closed for now.
