### ISSUE TITLE
Potential Mac provider

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#724]
A colleague at IBM was co-coordinating hardware donations for https://adoptopenjdk.net/ and mentioned that several providers had donated vms for OSX.  They recommended we approach MacInCloud to see if the would do the same for Node.js.

@rvagg any concern if I approach them to see if they would be willing to donate ?

**Comment by mhdawson** [comment]
In further discussion he also mentioned macstadium, but I think that I remember @rvagg had already been talking to them.

**Comment by mhdawson** [comment]
@rvagg ping ?

**Comment by mhdawson** [comment]
@nodejs/build any objections ?  Otherwise I'll approach them to see if they might be an option.

**Comment by gibfahn** [comment]
SGTM. Probably worth reaching out to macstadium as well, just in case anything's changed since last time.

**Comment by piccoloaiutante** [comment]
SGTM too. I would go ahead to see if there is anyone that could support us..

**Comment by jbergstroem** [comment]
We have an open connection with macstadium; it just depends on us figuring out the way we can better show the support that is provided to us. @rvagg wanna chip in here?

**Comment by mhdawson** [comment]
Ok, I'll look to contact MacInCloud next week to see where that goes.

**Comment by refack** [comment]
Has anybody tried to contact Apple to see if they can help/allow us to run macOS as VM/Container? Since I have no corporate affiliation, I'll be happy to try.

**Comment by mhdawson** [comment]
Sent a follow up to MacInCloud

@refack I believe that @rvagg and @jbergstroem had both tried with Apple on several occasions without success.

**Comment by refack** [comment]
> @refack I believe that @rvagg and @jbergstroem had both tried with Apple on several occasions without success.

Good. Shame of Apple 😞

**Comment by maclover7** [comment]
ping @mhdawson -- is still needed?

**Comment by mhdawson** [comment]
MacCloud was open to donating but we've not gotten through setting up the other OSX donations we received. I'd still like multiple providers though so probably makes sense to keep open],

**Comment by sam-github** [comment]
Almost 2 years have passed with no further activity, I suggest we close.
