### ISSUE TITLE
New Node.js Store

### ISSUE THREAD

**Issue by serenam18** [nodejs/build#725]
Hello!

We have re-vamped our node.js store and need to repoint it.

Can you please point this new site, https://node-js-community-store.myshopify.com/

to: store.nodejs.org

Thank you so much for your help!

**Comment by mikeal** [comment]
I think this is just a Coudflare config thing. /cc @jbergstroem @rvagg 

We really need to stop getting orders to the old site.

**Comment by jbergstroem** [comment]
Just checked cloudflare:
<img width="684" alt="screen shot 2017-05-18 at 5 28 12 pm" src="https://cloud.githubusercontent.com/assets/176984/26224226/6546e370-3bef-11e7-8bad-ac6c0c0b4691.png">

..am I missing something? Are we all good?

**Comment by maclover7** [comment]
```
Jons-MacBook-Pro:~ jon$ dig store.nodejs.org

; <<>> DiG 9.8.3-P1 <<>> store.nodejs.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11492
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;store.nodejs.org.		IN	A

;; ANSWER SECTION:
store.nodejs.org.	299	IN	CNAME	node-js-community-store.myshopify.com.
node-js-community-store.myshopify.com. 3599 IN CNAME shops.myshopify.com.
shops.myshopify.com.	1799	IN	A	23.227.38.64

;; Query time: 76 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Nov  3 21:30:03 2017
;; MSG SIZE  rcvd: 121
```

Looks good to me -- going to close this out as completed.
