### ISSUE TITLE
Fix test-rackspace-fedora22-x64-1

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#730]
So [`test-rackspace-fedora22-x64-1`](https://ci.nodejs.org/computer/test-rackspace-fedora22-x64-1/) is still offline, apparently it was failing to build.

I think this is what is causing builds to back up at the moment, so it would be good to get it back.

@Trott I'm sure I brought this up somewhere a couple of days ago, but I can't find that comment for the life of me. Do you remember what exactly was failing?

@jbergstroem would it be easier to wipe the machine and respin, or would you want to do more investigation?

![image](https://cloud.githubusercontent.com/assets/15943089/26271084/4aa60be4-3cf9-11e7-9ec5-a6bcc11ae264.png)

**Comment by Trott** [comment]
@gibfahn https://github.com/nodejs/build/issues/719#issuecomment-301282466

**Comment by jbergstroem** [comment]
Wipe it!

**Comment by maclover7** [comment]
Machine looks to be back up and has successfully completed builds today -- can this be closed?
