### ISSUE TITLE
"Rebasing is not supported" for CITGM @ win10

### ISSUE THREAD

**Issue by refack** [nodejs/build#731]
When you want to run CITGM for a PR rebased on a ref that has a base line CITGM run
e.g. https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/808/nodes=win-vs2015/parameters/
```
c:\workspace\citgm-smoker\nodes\win-vs2015>IF DEFINED REBASE_ONTO (
echo Rebasing is not supported  
 exit /b 1 
) 
```

**Comment by joaocgreis** [comment]
Added, should be working now.

@nodejs/citgm I removed the `POST_REBASE_SHA1_CHECK` (it was introduced for accept-pr, was always broken and should be removed everywhere). Let me know if you used it for something.
