### ISSUE TITLE
All 3 macOS workers are down :(

### ISSUE THREAD

**Issue by refack** [nodejs/build#732]
As of 2017-05-21 2pm EDT
https://ci.nodejs.org/label/osx1010/
![image](https://cloud.githubusercontent.com/assets/96947/26288044/7aac754a-3e56-11e7-8070-06f06af99311.png)

**Comment by rvagg** [comment]
I'm working on it right now fyi

**Comment by refack** [comment]
BTW: I think I crashed it with https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/809/nodes=osx1010/

**Comment by rvagg** [comment]
whole machine was down, so something dramatic happened

all sorted now

**Comment by refack** [comment]
Bless your soul... 🙏
