### ISSUE TITLE
rejuvenate "citgm-smoker-nobuild" job

### ISSUE THREAD

**Issue by refack** [nodejs/build#733]

**Comment by gibfahn** [comment]
Are you talking about [citgm-smoker](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/) and [citgm-smoker-nobuild](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/)?

If so then yeah, we should make them identical. In fact there's no reason we shouldn't just have the one job. I set up `nobuild` because I didn't want to break the main smoker run while testing the `nobuild` version.

**Comment by refack** [comment]
<sub>Sorry clicked enter (read: submit form) 🤦‍♂️ when writing the title</sub>

## `citgm-smoker`:
* command: `citgm-all -J`
1. aix61-ppc64
2. debian8-64
3. fedora22
4. fedora23
5. osx1010
6. ppcbe-ubuntu1404
7. ppcle-ubuntu1404
8. rhel72-s390x
9. ubuntu1204-64
10. ubuntu1404-64
11. ubuntu1604-64
12. win-vs2015 __+__


## `citgm-smoker-nobuild`: 
* command: `citgm-all`
1. aix61-ppc64
2. centos5-64 __-__
3. debian8-64
4. fedora22
5. fedora23
6. osx1010
7. ppcbe-ubuntu1404
8. ppcle-ubuntu1404
9. rhel72-s390x
10. ubuntu1204-64
11. ubuntu1404-64
12. ubuntu1604-64

Also some just dont work:
e.g. `ubuntu1604-64`:
<details>
<pre>
Started by upstream project "citgm-smoker-nobuild" build number 145
originally caused by:
 Started by user Refael Ackermann
[EnvInject] - Loading node environment variables.
Building remotely on test-rackspace-ubuntu1604-x64-1 (ubuntu1604-64) in workspace /home/iojs/build/workspace/citgm-smoker-nobuild/MACHINE/ubuntu1604-64
[ubuntu1604-64] $ /bin/sh -xe /tmp/hudson6263762753138764280.sh
+ rm -rf /home/iojs/build/workspace/citgm-smoker-nobuild/MACHINE/ubuntu1604-64/*
+ [ Nightly == Nightly ]
/tmp/hudson6263762753138764280.sh: 4: [: Nightly: unexpected operator
+ DOWNLOAD_DIR=https://nodejs.org/download/release/
+ curl https://nodejs.org/download/release/
+ grep v8
+ sort -t. -k 1,1n -k 2,2n -k 3,3n
+ tail -1
+ cut -d" -f 2
+ tr -d /
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 51472    0 51472    0     0  34337      0 --:--:--  0:00:01 --:--:-- 34360
+ LINK=
+ OS=linux
+ ARCH=x64
+ EXT=tar.gz
+ curl -O https://nodejs.org/download/release//node--linux-x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  6227    0  6227    0     0   3170      0 --:--:--  0:00:01 --:--:--  3170
+ + tar xf -
gzip -cd node--linux-x64.tar.gz

gzip: node--linux-x64.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Notifying upstream projects of job completion
Finished: FAILURE
</pre>
</details>

**Comment by refack** [comment]
> Are you talking about citgm-smoker and citgm-smoker-nobuild?

I think it could be very useful job by using the nightly as a baseline, also for quick testing specific packages vs. platform.

**Comment by maclover7** [comment]
ping @refack -- is still needed?

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
