### ISSUE TITLE
help needed with CITGM-smoker@rhel72-s390x

### ISSUE THREAD

**Issue by refack** [nodejs/build#734]
https://ci.nodejs.org/job/citgm-smoker/nodes=rhel72-s390x/
From the console output it seems that the tests are finished (`sodium-native` is that last module to test)  but the run does not complete, so the results are not parsed.
/cc @nodejs/citgm maybe the process doesn't exit?

**Comment by refack** [comment]
Cross-Ref: https://github.com/nodejs/citgm/issues/423

**Comment by refack** [comment]
PR opened: nodejs/citgm#424
I'm keeping this open until confirmed fix.

**Comment by mhdawson** [comment]
Looks like nodejs/citgm#424 landed.  Closing.  Please re-open if thats not the right thing to do.

**Comment by refack** [comment]
👍 Yep, #424 solved this.
General issue covered by https://github.com/nodejs/citgm/issues/426
