### ISSUE TITLE
Build WG meeting 30th May 2017 at 4 EST

### ISSUE THREAD

**Issue by piccoloaiutante** [nodejs/build#737]
### When

May 30, 2017 4 PM EST - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20170530T20&p1=1440&ah=1)

### Where
- [Hangouts on Air, for participants](https://hangouts.google.com/hangouts/_/ytl/WnAkVlNCy469TJma6aMz8G74fekbMND1M9SNl9eJ0hE=?eid=100598160817214911030)
- [Youtube stream, for viewers](https://www.youtube.com/watch?v=5WV7TjUww-w)
- [Events page](https://www.youtube.com/my_live_events?filter=scheduled)
- [Minutes document](https://docs.google.com/document/d/12MnAxQ3c1_esF65SfqdR0TwzW0BlRZ2-lylzk-Fs4AU)
- [Previous meeting](https://github.com/nodejs/build/issues/690)

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* Add Michele Capra (@piccoloaiutante) to the Build WG [#711](https://github.com/nodejs/build/issues/711)
* Make regular canary builds with V8 lkgr [#626](https://github.com/nodejs/build/issues/626)
* New meeting time for build WG [#698](https://github.com/nodejs/build/issues/698)
<br/>

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by mhdawson** [comment]
I've created the youtube meeting, and will add the link for participants a few minutes before the meeting starts.

**Comment by mhdawson** [comment]
sorry I'm a bit late: https://hangouts.google.com/hangouts/_/ytl/WnAkVlNCy469TJma6aMz8G74fekbMND1M9SNl9eJ0hE

**Comment by kfarnung** [comment]
@mhdawson I'm not seeing the meeting participant link.

**Comment by piccoloaiutante** [comment]
i can't enter, it seems unauthorised

**Comment by mhdawson** [comment]
Let me cut/paste again

**Comment by mhdawson** [comment]
https://hangouts.google.com/hangouts/_/ytl/WnAkVlNCy469TJma6aMz8G74fekbMND1M9SNl9eJ0hE=?eid=100598160817214911030

**Comment by mhdawson** [comment]
For those watching will start broadcast in a few mins, just giving people a bit more time to join.

**Comment by refack** [comment]
You going on air? I love watching you guy 😄

**Comment by rvagg** [comment]
getting a 403 for the latest url

**Comment by gibfahn** [comment]
@rvagg Odd, it works for everyone else.

**Comment by rvagg** [comment]
nevermind .. copy/paste doesn't work for the url from github FOR SOME STUPID REASON

**Comment by mhdawson** [comment]
PR for minutes: https://github.com/nodejs/build/pull/745

**Comment by mhdawson** [comment]
Minutes landed, closing.
