### ISSUE TITLE
idea: maybe gate on results of `linuxone`

### ISSUE THREAD

**Issue by refack** [nodejs/build#739]
AFAICT `linuxone` can finish a run very quickly
![image](https://cloud.githubusercontent.com/assets/96947/26525961/16e889b0-4336-11e7-8e8f-fd8486995ed5.png)
hence it can be an excellent sanity tester.
1. Maybe have it as a gate for `node-test-commit`, if there is a failure (if possible check if it's related to change) don't fan out to the other platforms (saving on resources).
2. Maybe have it auto run for every commit on `master`, and ping authors (classic CI style)

**Comment by mhdawson** [comment]
Its an interesting idea.  linuxone does finish much faster than the others. @jbergstroem what's your thought ?

**Comment by maclover7** [comment]
ping -- any updates here?

**Comment by gibfahn** [comment]
I think the use of this in [node-test-pull-request-lite](https://ci.nodejs.org/job/node-test-pull-request-lite/) covers part of this, and the github-bot auto-run CI discussions cover the rest of it.

@refack correct me if I'm wrong :grin:.
