### ISSUE TITLE
Build prospectus for hardware donors

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#741]
A document of some kind listing the benefits that you can get from donating infrastructure to the project.

Current:

* Mention in our README, including logo for corporate donors
* Name in CI hosts that are publicly accessible and regularly discussed on the Node.js repo by contributors

Potential (please contribute to this list):

* Copy content onto our website (https://github.com/nodejs/nodejs.org/issues/1257)
* Regularly mentioned in blog posts and articles (point to examples, not making commitments on frequency or _actually getting mentioned_)
* Badge and/or authorised sponsorship wording they can list on their website, e.g. "Proud infrastructure sponsor of the Node.js project"
* Regular tweets from `@nodejs`

**Comment by rvagg** [comment]
* Mentions in conferences - gather a list of talks

**Comment by gibfahn** [comment]
For the website, something like https://adoptopenjdk.net/sponsors.html would be ideal.

**Comment by rvagg** [comment]
* Quotes from us for use on their material, within reason, e.g. scaleway quotes from me

**Comment by mhdawson** [comment]
Talked to Tracy about

* Badge and/or authorised sponsorship wording they can list on their website, e.g. "Proud infrastructure sponsor of the Node.js project"
* Regular tweets from @nodejs

Response was positive, and she's going to ask the team at the Foundation to look at how they can help make these happen.

**Comment by mhdawson** [comment]
Once we are ready on our side to generate tweets pointing to the donor list, we are ready to setup with Zibby at the foundation to start sending them out.  We can either wait until we've move it to nodejs.org or simply start with the pointer to the existing doc in our README.md.  I'm tempted to just start by pointing to the existing README.md and then update once we have moved.  Thoughts ?

**Comment by gdams** [comment]
yeah so as @gibfahn pointed out.... I've had a really strong reaction from companies when I have mentioned putting their logo on the website for AdoptOpenJDK(https://adoptopenjdk.net/sponsors.html). Over there we also started by using a github sponsors file but most of our sponsors seemed much more keen to be on the website

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
