### ISSUE TITLE
headers.tar.gz packages are missing from recent nightly builds

### ISSUE THREAD

**Issue by jasongin** [nodejs/build#743]
The nightly build directories from 4 days ago and prior include `headers.tar.gz/.xz` packages, as expected:
 - https://nodejs.org/download/nightly/v8.0.0-nightly20170527f84666f923/

But those packages are missing from the last 3 nightly builds:
 - https://nodejs.org/download/nightly/v8.0.0-nightly2017052890877003c1/
 - https://nodejs.org/download/nightly/v8.0.0-nightly2017052910913271bf/
 - https://nodejs.org/download/nightly/v8.0.0-nightly20170530effeff1843/

A significant effect is that, after installing the nightly build, `node-gyp` will fail to download the headers, and therefore fail to build native addons:

```
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v8.0.0-nightly20170530effeff1843/node-v8.0.0-nightly20170530effeff1843-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/travis/.nvs/nightly/8.0.0-nightly20170530effeff1843/x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:120:20)
gyp ERR! stack     at Request.emit (events.js:210:7)
gyp ERR! stack     at Request.onRequestResponse (/home/travis/.nvs/nightly/8.0.0-nightly20170530effeff1843/x64/lib/node_modules/npm/node_modules/request/request.js:1074:10)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:563:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:20)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! System Linux 4.8.12-040812-generic
gyp ERR! command "/home/travis/.nvs/nightly/8.0.0-nightly20170530effeff1843/x64/bin/node" "/home/travis/.nvs/nightly/8.0.0-nightly20170530effeff1843/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/jasongin/node-addon-api/test
gyp ERR! node -v v8.0.0-nightly20170530effeff1843
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
```

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node/issues/12719#issuecomment-304941983 is relevant, error when building the documentation with `make doc`:
```
/Users/iojs/build/ws/tools/doc/node_modules/marked/lib/marked.js:1062
      while (this.next().type !== 'list_item_end') {
                        ^

TypeError: Cannot read property 'type' of undefined
```

**Comment by mhdawson** [comment]
Strangely make doc seemed to fail before this PR landed and passed afterwareds https://github.com/nodejs/node/pull/13274

**Comment by mhdawson** [comment]
It failed in generating errors.md which was the one changed by that PR.

**Comment by mhdawson** [comment]
@jasongin can you check if last nights builds were ok ?   I'm  wondering if the PR I mentioned fixed the doc issue.

**Comment by gibfahn** [comment]
Header packages are there in the latest nightly (assuming this is the right one):

https://nodejs.org/download/nightly/v9.0.0-nightly20170531102e1aa4e3/

![image](https://cloud.githubusercontent.com/assets/15943089/26688778/86b49dca-46eb-11e7-9de4-e8dafa41bf41.png)

**Comment by jasongin** [comment]
Yes, the latest nightly build looks good. Closing.
