### ISSUE TITLE
jenkins: ping users

### ISSUE THREAD

**Issue by refack** [nodejs/build#746]
It would be nice if Jenkins would ping (i.e. e-mail) users, on job completion.
A possible list:
1. The user who started the job
2. For PRs the OP (or tell the bot to add a comment)
3. [future] for breakage on `master` all commit authors since last green

Since jobs take some time and some of us are a bit ADHD ( :shipit: me ⚡️ ) with melignent [tabitis](http://www.urbandictionary.com/define.php?term=tabitis)

![image](https://cloud.githubusercontent.com/assets/96947/26740293/f1ed3fea-47a2-11e7-8d9f-458e99c52816.png)
<sub>yes that's 68 open tabs, and that's only my `node` window</sub>

Sometimes I forget to follow up on jobs.

**Comment by rvagg** [comment]
We could add an optional email field in the build request page, since we have email infra working now and the IBM boys seem to be successfully using it post-build, perhaps it wouldn't be hard to add.

**Comment by refack** [comment]
I would be very appreciative 😍

**Comment by gibfahn** [comment]
I'd much rather not have emails on Job completion, I guess it'd be okay if it was opt-in (maybe another checkbox in node-test-pull-request.

I just go through the [PRs that I raised](https://github.com/pulls) and [the ones I've self-assigned](https://github.com/pulls/assigned) and check for any updates.

We're using the email notifications to signal that something's wrong with the IBM machines.

If we get to the point where the github bot is running PRs for us then the bot could edit its comment with the result of the build once it finishes. Do edited comments trigger another email notification?

**Comment by mcollina** [comment]
I'm 👍  on receiving an email field, and if you want to be notified you can just past your email there.
I'm 👎  on automatic emails.

@gibfahn editing comments do not trigger an email notification. I'd prefer a direct email than a comment in a gh pr.

**Comment by mhdawson** [comment]
An optional email field seems like a good idea to me.  If we get consensus I can take a look at doing that.  As long as we can use dynamic elements in the list of emails notifications get sent to it might be pretty easy.

**Comment by cjihrig** [comment]
I'm +1 on being able to opt in to getting an email on job completion.

**Comment by refack** [comment]
Opt in is great 💯

**Comment by refack** [comment]
> Do edited comments trigger another email notification?

Only if the edit has a new mention.

**Comment by mmarchini** [comment]
I like the optional e-mail idea. We could also have an optional webhook (if someone wants to get notified through Slack, for example).

Does Jenkins have the option to create custom fields for users? If so, we could let each user set up their preferred default behavior.

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
