### ISSUE TITLE
update `nodegyp-test-pull-request`

### ISSUE THREAD

**Issue by refack** [nodejs/build#747]
Re: https://github.com/nodejs/node-gyp/pull/1212
1. We should add `node8` to the fan
2. For `node-gyp@4.x.x` we will only support node >= 4
    `node-gyp@3` will go into "LTS"

So I assume we need a matrix?

**Comment by bnoordhuis** [comment]
I wasn't planning on maintaining  branches for v0.10 and v0.12 once we bump major.  Was anyone else and if so, why?

**Comment by joaocgreis** [comment]
- Added Node version 8
- Node versions 0.x will only run if node-gyp < 4 (so this will simply work if we ever create a v3.x branch)

I believe that takes care of it, so I'll close. Please reopen if I missed something.

**Comment by refack** [comment]
> I wasn't planning on maintaining branches for v0.10 and v0.12 once we bump major. Was anyone else and if so, why?

https://github.com/nodejs/node-gyp/pull/1212#issuecomment-305539119 If someone finds a new bug (especially on Windows, ["Windows user are not happy"](https://github.com/nodejs/node-gyp/issues/629) and all that Jazz) 🤷‍♂️ personally I have no problem helping them.
So maybe LTS is the wrong comparison, more like "lazy-copy-on-write-maintenance"?

**Comment by refack** [comment]
@joaocgreis 👍 Looking good
https://ci.nodejs.org/job/nodegyp-test-pull-request/27/

**Comment by refack** [comment]
Re: https://github.com/nodejs/node-gyp/commit/75cfae290fee1791a23fa68820ae5dd841e93e14
If I jumped the gun, shoot me.

**Comment by gibfahn** [comment]
>So maybe LTS is the wrong comparison, more like "lazy-copy-on-write-maintenance"?

I think the right statement is "we might consider doing another release on a case-by-case basis".
