### ISSUE TITLE
requesting access for test-requireio-osx1010-x64-1

### ISSUE THREAD

**Issue by Trott** [nodejs/build#752]
I would like to be able to access test-requireio-osx1010-x64-1 so I can test some things in the hopes of identifying the problem in https://github.com/nodejs/node/issues/13527.

My public ssh keys can be found at https://github.com/Trott.keys

**Comment by gibfahn** [comment]
SGTM

**Comment by gibfahn** [comment]
@Trott would you mind PRing the update to the inventory if you've got things working?

I understand from IRC that you've got the IP and the keys, you just need the user (which I assume will be `root`).

**Comment by Trott** [comment]
> I understand from IRC that you've got the IP and the keys, you just need the user (which I assume will be root).

`root` was my guess too but alas no...

**Comment by gibfahn** [comment]
>root was my guess too but alas no...(or I have something else set up wrong)

How did you get the IP address?

@jbergstroem in general how do we get the IP of a machine?

**Comment by rvagg** [comment]
@Trott it's not straightforward but this _should_ get you in:

```
Host jump-nodejs-arm
  User jump
  HostName vagg-arm.nodejs.org
  Port 2222
  IdentityFile ~/.ssh/nodejs_build_test
Host test-requireio-osx1010-x64-1
  HostName 192.168.2.210
  ProxyCommand ssh jump-nodejs-arm nc -q0 %h %p
  User iojs
  IdentityFile ~/.ssh/nodejs_build_test
```

**Comment by rvagg** [comment]
sorry, that's for your .ssh/config

**Comment by jbergstroem** [comment]
@gibfahn all machines should live in our inventory. This one doesn't.

**Comment by gibfahn** [comment]
>@gibfahn all machines should live in our inventory. This one doesn't.

Yeah, I meant how do we get the IP to add to the inventory. Using one of these from the [Script Console](https://ci.nodejs.org/computer/test-requireio-osx1010-x64-1/script) does seem to work, but of course it gave `192.168.2.210`, which I assumed was wrong (didn't think of the jump box). 

```groovy
println InetAddress.localHost.canonicalHostName
// or
println InetAddress.localHost.hostAddress
```

**Comment by gibfahn** [comment]
Followon question, at the moment the generated `~/.ssh/config` entries that use the jumpbox are of the form:

```
Host test-requireio_louiscntr-debian7-arm_pi2-1 
  HostName 192.168.2.68
  IdentityFile ~/.ssh/nodejs_build_test
  User pi
  ProxyCommand ssh -i ~/.ssh/nodejs_build_test -W %h:%p -p 2222 jump@vagg-arm.nodejs.org
```

The one @rvagg just posted seems like a nicer way to write it, could we convert the inventory ansible script to write configs like that? I'm happy to do the work if it's possible.

**Comment by Trott** [comment]
Thanks, @rvagg. That worked.

**Comment by rvagg** [comment]
@gibfahn I don't mind either way. The one you pasted doesn't require the parent Host entry though so perhaps it's nicer.
