### ISSUE TITLE
Releases should not be possible if release bit is not set

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#760]
This is something we could likely fix in the build process for release builds... it is also something we could work into the release scripts.

Thoughts?

**Comment by MylesBorins** [comment]
One way to check would be to regex the result of `node -p process.release.sourceUrl` for the string `release`.

It seems to me that doing this during the promotion stage might be too late as the tag will already be published.

As such I think it would make sense for this to happen in the release CI job... technically the job should simply fail if the bit isn't set

**Comment by MylesBorins** [comment]
ping @nodejs/build about how we could implement this

**Comment by joaocgreis** [comment]
This could be a check like and next to https://github.com/nodejs/node/blob/2f2f1cfa870c2153c811a7047d74c4a0bb8e5f2c/Makefile#L679-L683 . If DISTTYPE is release, `grep '^#define NODE_VERSION_IS_RELEASE 1$' src/node_version.h`.

We can also bake this into the release Jenkins script, but I believe it is better to have in the Makefile/vcbuild where it can be easily reviewed, if possible.

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
