### ISSUE TITLE
ARM 6 release backup hardware

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#765]
In recent discussions we talked about having build team members host raspberry PI B+s to act as secondary build machines in case the primary one is off line.

I have a PI B+ which is en route to me and I believe there are install instructions that I can follow.

The one issue was how to connect given that I don't have a dedicated ip (it would also likely need to use a different ssh port incoming as I'd want to keep 22 for my internal use just in case I need it).

@jbergstroem you mentioned we could use an ssh tunnel. Is there an existing server along with instructions on how to set up a client to connect to it ?

**Comment by mhdawson** [comment]
Received the hardware, followed instructions to install OS and currently running ansible

**Comment by mhdawson** [comment]
Ansible config complete

A few notes:

* There may be an issue with ansible 2 and the existing ansible scripts to install packages.  I had to do to make the following change in `ansible-playbook.yaml` to get the script to run with ansible 2:
```
@@ -58,7 +59,7 @@
         name: "{{ item }}"
         update_cache: yes
         state: latest
-      with_items: packages
+      with_items: "{{ packages }}"
       tags: general
```
* there are a bunch of warnings like this:

```
WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found:
git_version.stdout.find('{{ version }}') == -1
```


* I updated the script to skip setting up an APT proxy, which is probably fine since I'll only have the 1 machine.

* I updated the script to skip mount the nfs mounts as I don't have them.  @rvagg do you think I'll need an nfs server in order to avoid running too slowly or wearing out the SD card ?  Judging by how long it took to compile git I'm guessing the answer might be yes.

* I used the name `release-devrus_mhdawson-debian7-arm_pi1p-1`.  devrus is as close to a "provider" that I have :)

**Comment by mhdawson** [comment]
Ok added an nfs server to the local setup and re-ran ansible to include mounting instead of skipping.

@jbergstroem I think next step is to figure out the ssh tunnel.

**Comment by mhdawson** [comment]
@rvagg looks like the existing ARM6 release  raspberry PI's are off line.  Can you give them a kick ?

**Comment by mhdawson** [comment]
Ok, my raspberry pi is connected as release-devrus_mhdawson-debian7-arm_pi1p-1

I've already run a test job that builds on this new arm machine and its passed a few times.  For example: 

https://ci-release.nodejs.org/job/iojs+release-dawson-test/9/

I also did a quick check of downloading the resulting archive from the test directory and made sure it started on another ARM6 raspberry PI that I have.

PR for the Ansible tweaks I needed to support the ssh tunnel is here:  https://github.com/nodejs/build/pull/924

@nodejs/build is there anything else I should do before we enable this machine for use in regular release builds ?

**Comment by mhdawson** [comment]
@rvagg @jbergstroem I'm going to go ahead and enable the machine and we can validate that the nighlies are ok when they build on the machine.

**Comment by rvagg** [comment]
@mhdawson one thing I don't know if it's documented anywhere or not, you need the staging ssh set up. See one of the two existing release pi's for config and key:

```
pi@release-requireio--rvagg-debian7-arm--pi1p-1 ~ $ sudo cat /home/iojs/.ssh/config
Host iojs-www node-www
  HostName direct.nodejs.org
  User staging
  IdentityFile ~/.ssh/node-www-staging
```

You'll need /home/iojs/.ssh/node-www-staging and you'll need to `chmod 700 .ssh` and `chmod 600 .ssh/*` and then `ssh node-www` and make sure it works and that it goes into host_vars. If this isn't done it won't be able to upload binaries to the server.

**Comment by mhdawson** [comment]
I did some config based on info from @joaocgreis and had validated that test binaries were uploaded to the download server.

**Comment by mhdawson** [comment]
@rvagg checking now, there is a run going that has been running for 17 hours.  I had done a few tests runs and the first one was long, but the later ones varied between a couple of hours and 4-5.  

Is this normal for some runs to take a really long time ?

**Comment by mhdawson** [comment]
Seems like it completed ok...

**Comment by rvagg** [comment]
that is a long time .. I've been running these release machines overclocked so they have been artificially high and will probably take longer now I've reset them back down. ccache should help a bit but release builds tend to be unique enough in their defines that it doesn't get to reuse old object files. 4-6 hours would be what I expect for a normal release.

**Comment by mhdawson** [comment]
This is an example of a 16hr run on a different machine so maybe its normal https://ci-release.nodejs.org/job/iojs+release/nodes=pi1-raspbian-wheezy/2249/console

**Comment by mhdawson** [comment]
Not perfect but run times and reliability seems as good as other arm 6 release machines.
