### ISSUE TITLE
Build WG Meeting 20 June 2017

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#766]
Place holder as reminder for people that we have a meeting
tomorrow at 4PM EST as per the community calendar.  Will fill in rest of issue/minutes doc tomorrow unless somebody beats me to it.

### When

June 20, 2017 4 PM EST - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20170719T20&p1=1440&ah=1)

### Where
- [Hangouts on Air, for participants](https://hangouts.google.com/hangouts/_/ytl/y4OQMSvMpVpL1xSac4fdeA7i_bTFUWvXpDeUUN9HKfA=?eid=100598160817214911030)
- [Youtube stream, for viewers](https://www.youtube.com/watch?v=8B_XgEvIQt8)
- [Events page](https://www.youtube.com/my_live_events?filter=scheduled)
- [Minutes document](https://docs.google.com/document/d/1X-1MqXm9Z8TfN3fEbS_XpdeEn9ldeFmCulkA9DJnVtM/edit?usp=sharing)
- [Previous meeting](https://github.com/nodejs/build/issues/737)

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda)
and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* update clang on FreeBSD 10 [#723](https://github.com/nodejs/build/issues/723)

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by mhdawson** [comment]
@nodejs/build please indicate if you can make it by adding your thumbs up or down above.

**Comment by gibfahn** [comment]
We currently have no open issues, if people have stuff that they want to discuss please mark/raise things appropriately.

**Comment by rvagg** [comment]
I'll either be in transit or very jetlagged for this one, probably won't participate.

**Comment by piccoloaiutante** [comment]
This is a little bit too late for me so I'll skip it. @mhdawson in section "When" there is still 4pm EST, you might want to change it to 6pm EST.

**Comment by gibfahn** [comment]
>in section "When" there is still 4pm EST, you might want to change it to 6pm EST.

That was my bad, fixed (in future feel free to change it yourself!)

If Rod can't make this meeting, is there a chance we could move this to the eariler slot so EU people can attend? Is there anyone who was relying on the later timezone?

**Comment by mhdawson** [comment]
I'm ok with moving up. @jbergstroem does that work for you ?

**Comment by jbergstroem** [comment]
I can make it but happy to move. I have some work I'd like to finish regarding mac setup so I don't have to drag my tail into the agenda.

**Comment by mhdawson** [comment]
Ok lets move to 4 EST.  Even if we don't have agenda items I think going through the updates on what we are working on is good to give people outside the build WG insight into what we are actively working is good.  So it might be a short meeting but lets still have it.

**Comment by mhdawson** [comment]
Updated foundation calendar and youtube event and this issue to show 4 EST.

**Comment by gibfahn** [comment]
cc/ @piccoloaiutante @joaocgreis time might be more manageable for you guys now.

**Comment by piccoloaiutante** [comment]
Oh yes, for me it's better and i can join

**Comment by jbergstroem** [comment]
Bad news -- sucked into a meeting. I will make a summary here.

**Comment by mhdawson** [comment]
Link for participants - https://hangouts.google.com/hangouts/_/ytl/y4OQMSvMpVpL1xSac4fdeA7i_bTFUWvXpDeUUN9HKfA=?eid=100598160817214911030

**Comment by gibfahn** [comment]
Minutes: https://github.com/nodejs/build/pull/767
