### ISSUE TITLE
cctest failure in CI run

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/build#769]
I noticed that `cctest.exe` run failure doesn't show as test failure. For e.g. [here](https://ci.nodejs.org/job/node-test-binary-windows/RUN_SUBSET=0,VS_VERSION=vs2017,label=win2016/9404/console) is the CI run triggered for `node-chakracore` and it says test pass even if test case inside cctest hits an assert. Is there any reason of not having a post-build action step to parse `cctest.tap` output similar to `test.tap` output?

I think on non-windows, the `make` job will anyway fail if `cctest` fails, so this is only problem for windows.

**Comment by joaocgreis** [comment]
Looks like `cctest.tap` was not added to the Windows job as it probably should have been when it was added to others. It can be easily added, but only when cctest passes on Windows, to avoid breaking all runs.

**Comment by refack** [comment]
ping https://github.com/nodejs/node/pull/14111

**Comment by kunalspathak** [comment]
Updated jenkins job : https://ci.nodejs.org/job/node-test-binary-windows/jobConfigHistory/showDiffFiles?timestamp1=2017-06-25_20-05-00&timestamp2=2017-07-21_12-36-26
