### ISSUE TITLE
Proposed test for regular tweet thanking sponsors

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#771]
Note that we have limited characters so I this is what I could fit (7 characters remaining): 

>Thanks to those that keep the Node.js builds going through infrastructure donations. Check out the list here: https://github.com/nodejs/build#infrastructure-providers

This would be sent out from the Node.js Foundation account, and then we can re-tweet.

**Comment by mhdawson** [comment]
@nodejs/build please comment.  Would like to start having tweets go our monthly starting next week.

**Comment by gibfahn** [comment]
Wording LGTM

**Comment by piccoloaiutante** [comment]
Tweet looks good to me. I was wondering if we could convey the message of "give back to the community" but I wasn't able to come up with something meaningful in 140 chars 😄

**Comment by kunalspathak** [comment]
LGTM

**Comment by joaocgreis** [comment]
LGTM

**Comment by mhdawson** [comment]
Ok, I've landed the logos for Intel and MacStadium so going to ask that the tweet now be sent out monthly.

**Comment by mhdawson** [comment]
First tweet went out and should now go out monthly, closing.

**Comment by refack** [comment]
@mhdawson has this been going on? Can I help? Can @zibbykeaton help?

**Comment by ZibbyKeaton** [comment]
I post a tweet about it once a month - it will be coming out later this June, but here is May's tweet: https://twitter.com/nodejs/status/999772162335657984. If you want to retweet that would be great! I can also create a special hashtag for this effort, so it's easy to find on social when you want to give a retweet to it. Just let me know if that would be helpful to this group. We could even do #nodejsdonations (open to other hashtags as well).

**Comment by refack** [comment]
+1 on hashtag (just what I was thinking while I was trying to find the history)

**Comment by ZibbyKeaton** [comment]
Upcoming social posts have been updated with above hashtag for easier tracking :)

**Comment by mhdawson** [comment]
@ZibbyKeaton thanks :)
