### ISSUE TITLE
OS X setup updates

### ISSUE THREAD

**Issue by Trott** [nodejs/build#773]
`setup/osx/README.md` has our hosts at voxer, where we don't have hosts anymore, I don't think.

Additionally, consider adding the following `launchctl` commands so as to resolve https://github.com/nodejs/node/issues/13527:

As user iojs:

```
launchctl unload -w /System/Library/LaunchAgents/com.apple.ReportCrash.plist
sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.ReportCrash.Root.plist
```

(Or just run the second one as root, of course, rather than using sudo.)

This will disable the crash reporter. I doubt we ever look at the logs it creates or that we ever send them to Apple.

It's possible that this issue is specific to earlier versions of OS X and more recent versions may not need ReportCrash disabled like that for our test suite to pass. So, judgment call if we should just disable it all the time or if we want to take a more wait-and-see approach for MacStadium. 
¯\\_(ツ)_/¯

**Comment by mhdawson** [comment]
FYI for new OSX ansible scripts @gdams

**Comment by maclover7** [comment]
cc @gdams, should this be issue be closed as part of the new OSX playbook?

**Comment by maclover7** [comment]
Since we've moved to the new OSX Ansible playbooks, going on the hunch this has been solved. Please reopen if this appears again.
