### ISSUE TITLE
Moving DISTTYPEDIR to CI-Release script for Windows

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#776]
@gibfahn @jbergstroem @rvagg @mhdawson (or anyone else with access to ci-release): can you take a look at https://ci-release.nodejs.org/job/iojs+release/jobConfigHistory/showDiffFiles?timestamp1=2017-06-21_18-30-42&timestamp2=2017-06-28_13-11-55 ? I believe the change is right, but it's better to have a review.

It became necessary after https://github.com/nodejs/node/pull/13900 . I believe it is simpler to have `DISTTYPEDIR` set in the release script, but have no strong feelings about this.

This is currently under test with a nightly: https://ci-release.nodejs.org/job/iojs+release/1797/ (replaces the one that was automatically started and aborted by me, the job was not fixed yet). _EDIT:_ Nightly was correctly published.

**Comment by refack** [comment]
Ref: https://github.com/nodejs/node/pull/13969
I originally removed it from `vcbuild.bat` because it was set in a redefined subroutine (which seemed strange), and I could find any referance to it in our code base.
But is there any chance any downstream consumer still uses it (i.e. NVIDIA, Microsoft, or anyone who builds their own `node.exe`)?

**Comment by joaocgreis** [comment]
@refack that is possible, any staging server could be used in https://github.com/nodejs/node/blob/ef28d85611bcb1b0d91b6525b7c16517bf21020c/vcbuild.bat#L337-L346 . But I have no idea, never heard of a concrete case of anyone using our build scripts with their own infra.

**Comment by refack** [comment]
http://blog.sec-consult.com/2017/04/application-whitelisting-application.html
NVIDIA build `node.exe` and sign it with their own certificate 🤦‍♂️

**Comment by joaocgreis** [comment]
For that they only need to run `vcbuild sign` in a machine with the certificate installed. Uploading to a staging server goes a bit further :slightly_smiling_face:

**Comment by refack** [comment]
AFAICT the nightlies have been built (I looked in the `.xz` and the new `vcbuild.bat` is there)

**Comment by richardlau** [comment]
>  But I have no idea, never heard of a concrete case of anyone using our build scripts with their own infra.

IBM does to produce https://developer.ibm.com/node/sdk/.

**Comment by joaocgreis** [comment]
@richardlau in case you need to keep your infra in sync, my change above only adds `set DISTTYPEDIR=%DISTTYPE%` before calling `vcbuild.bat`.

**Comment by richardlau** [comment]
@joaocgreis I think `DISTTYPEDIR` is one of the things we don't use.

cc @gibfahn

**Comment by mhdawson** [comment]
@joaocgreis the change in the job likes like the right replacement for what was removed.  Having said that I don't quite understand why it was removed from the build script if we need it and other teams that build releases might need it as well.

**Comment by gibfahn** [comment]
>I originally removed it from vcbuild.bat because it was set in a redefined subroutine (which seemed strange), and I couldn't find any reference to it in our code base.

For posterity, according to [StackOverflow](https://stackoverflow.com/questions/31528295/batch-goto-label-with-duplicate-labels) this will only be used for [`getnodeversion`](https://github.com/nodejs/node/blob/v8.x/vcbuild.bat#L508-L552). 

>Having said that I don't quite understand why it was removed from the build script if we need it and other teams that build releases might need it as well.

It was removed accidentally, and is re-added in https://github.com/nodejs/node/pull/13969.

**Comment by gibfahn** [comment]
Just came across https://github.com/nodejs/node/issues/2084, which seems relevant. @joaocgreis I think your change still makes sense in that context.

**Comment by joaocgreis** [comment]
I believe this can be closed now. Please reopen if there's any issue.
