### ISSUE TITLE
GitHub authentication for Jenkins says its giving permission to rvagg

### ISSUE THREAD

**Issue by Trott** [nodejs/build#778]
"Node.js Jenkins" is owned by rvagg so when people first authenticate to ci.nodejs.org, his handle shows up as the entity you're giving permission to. This comes up sometimes in onboardings when people log on for the first time and are all "huh? wha?" about it.

Seems like it ought to be owned by nodejs org instead, ideally.

<img width="343" alt="screen shot 2017-06-30 at 8 48 45 am" src="https://user-images.githubusercontent.com/718899/27743465-f0ab1ca4-5d70-11e7-950d-568425abb93d.png">

**Comment by gibfahn** [comment]
Duplicate of https://github.com/nodejs/build/issues/687?

**Comment by Trott** [comment]
> Duplicate of #687?

Sure seems like it. I'll close.
