### ISSUE TITLE
re-enable tap output

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#78]
Making a note here for myself, @piscisaureus wanted TAP output reenabled on builds

**Comment by Fishrock123** [comment]
Looks like this caused the CI to get a bit funny? Is this only on the CI's end, or also core's?

**Comment by Fishrock123** [comment]
Ohh, looks like this was something else: https://github.com/iojs/io.js/issues/1527

**Comment by jbergstroem** [comment]
Going on a limb here and closing: FIXED
