### ISSUE TITLE
Build releases of Node-ChakraCore

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#781]
After https://github.com/nodejs/build/issues/527, Node-ChakraCore is releasing nightlies when the `v8.x` or `master` branch changes. Adding to this, it would be useful to mark versions that are more adequate for public consumption, with less known issues.

We would like to move forward by making available release builds of Node-ChakraCore. This will use the same infrastructure and Jenkins job as the nightlies, but published in a different folder in the server, https://nodejs.org/download/chakracore-release/.

Here is the current plan to make this happen:
- [x] Rename the Jenkins job to `node-chakracore` (removing `-nightlies`)
- [x] Add the `release` disttype to the Jenkins job
- [x] Configure the `www` server (similar to https://github.com/nodejs/build/pull/547, including automatic promotion)
- [x] Test with a release

It is not yet time to mirror the full release process of Node-V8. For now, this will use automatic promotion for simplicity. This will be reevaluated in the future, it might be better to move to a closer integration with Node-V8 instead of a parallel release process. Also note that for now there are no MSI packages of Node-ChakraCore to avoid conflicts (users can use the zip/7z package or [NVS](https://github.com/jasongin/nvs)).

I'm moving forward with this plan to unblock https://github.com/nodejs/node-chakracore/issues/324 and related issues. This issue can be used to gather feedback and suggestions, I can revert my changes if there are objections.

cc @nodejs/build @nodejs/node-chakracore

**Comment by joaocgreis** [comment]
First experimental release: https://nodejs.org/download/chakracore-release/v8.1.2/

**Comment by kunalspathak** [comment]
@joaocgreis  - I believe this can be closed now?

**Comment by joaocgreis** [comment]
Closing, if there's any issue with the releases we can reopen.
