### ISSUE TITLE
CI jobs for readable-stream group

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#782]
Setting up initial jobs for readable-stream WG in https://github.com/nodejs/build/issues/657

I'll create a `streams-admins` group following [our process]( https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md). That group will have edit access, `streams` will have run access.

  
@nodejs/build let me know if there are any objections.

**Comment by gibfahn** [comment]
cc/ @piccoloaiutante

**Comment by piccoloaiutante** [comment]
excellent, go ahead 👍

**Comment by piccoloaiutante** [comment]
@gibfahn let me know if you need any help on this

**Comment by gibfahn** [comment]
Created the [streams-admins](https://github.com/orgs/nodejs/teams/streams-admins/members) team and added @mcollina and @calvinmetcalf (and made both maintainers). 

I don't know enough about the WG to know who else will be active in maintaining Jenkins jobs. If anyone else should be added comment in this thread.

**Comment by gibfahn** [comment]
Gave the two teams the appropriate access to [readable-stream-continuous-integration](https://ci.nodejs.org/view/All/job/readable-stream-continuous-integration/), @mcollina please confirm you still have configure access.

**Comment by mcollina** [comment]
It is all working. I removed some unneeded machines and the ones that suffer from https://github.com/nodejs/build/pull/785.

Some things that I would like fixed:

* some sort of aggregated test results, so that we know what failed across the environments, currently it reports `no result`
* we need to be able to trigger this for all the Node.js versions at the same time, ideally from 0.8 to 8, and maybe even the latest nightly, can you help set that up as well?
* can we post the status of the build to github as well?

Overall it works very well, I had to fix a configuration on our side. If you want to test, use the `core-ci` branch (https://github.com/nodejs/readable-stream/pull/308).

**Comment by gibfahn** [comment]
Looks like @nodejs/streams didn't have build access (@nodejs/streams-admins did have edit access) because it's actually `@nodejs/Streams` with a capital S. Github lowercases everything, but the plugin doesn't. I've given both permutations (`streams` and `Streams`) access.

<br/>

>we need to be able to trigger this for all the Node.js versions at the same time, ideally from 0.8 to 8, and maybe even the latest nightly, can you help set that up as well?

What I've been doing for other projects is adding a pipeline that runs the job with a list of versions, current job is here: https://ci.nodejs.org/view/All/job/readable-stream-pipeline/. It doesn't do anything magical, it just splits the `NODE_VERSIONs` string by space, and spawns a job with each `NODE_VERSION`.

**Comment by gibfahn** [comment]
BTW, if you want to add or remove platforms you modify the `MACHINE` label expression. If you want to run on a subset of platforms as a one off you modify the `MACHINES` parameter.

**Comment by mcollina** [comment]
How can we have some form of aggregated test results for each platform and some reporting for the pipeline?

**Comment by gibfahn** [comment]
Sorry, I should have mentioned that I'm still working through your other requests!

**Comment by mcollina** [comment]
thanks @gibfahn!

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
