### ISSUE TITLE
Build WG Meeting 11 July 2017

### ISSUE THREAD

**Issue by piccoloaiutante** [nodejs/build#787]
Place holder as reminder for people that we have a meeting tomorrow at 4PM EST as per the community calendar.  Will fill in rest of issue/minutes doc tomorrow unless somebody beats me to it.

### When

July 11, 2017 4 PM EST - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20170711T20&p1=1440&ah=1)

### Where
- [Hangouts on Air, for participants](https://hangouts.google.com/hangouts/_/ytl/sIbFbCb9B53dNNs-VMRAwklq7gSR36H7VcCbgV8oXHg=?eid=100598160817214911030)
- [Youtube stream, for viewers](https://www.youtube.com/watch?v=N5YxsZvkMiY)
- [Events page](https://www.youtube.com/my_live_events)
- [Minutes document](https://docs.google.com/document/d/1g_EqrKAK3FWi4BnGCdXOUuzsjrxnzj08exy01nTxk5A/edit?usp=sharing)
- [Previous meeting](https://github.com/nodejs/build/issues/766)

### Agenda

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by gibfahn** [comment]
Going to be on a plane for this one.

**Comment by bnoordhuis** [comment]
Must be a serious agenda if you're going to fly out for it.

(I'll get my coat.)

**Comment by jbergstroem** [comment]
Just got a meeting :( I will update this issue with my activity.

**Comment by mhdawson** [comment]
I'll try to be there.

**Comment by piccoloaiutante** [comment]
if @mhdawson can't make it, @joaocgreis do you have access for streaming through official account?

**Comment by joaocgreis** [comment]
No, I don't have access to the official account.

There are no issues for the meeting (https://github.com/nodejs/build/labels/wg-agenda), so I don't know if we need to have the meeting today. Is there something else to discuss?

**Comment by piccoloaiutante** [comment]
To me it's just standup.

**Comment by mhdawson** [comment]
I'll be there now that security releases are out.

**Comment by piccoloaiutante** [comment]
@mhdawson do you want me to pr the minutes?

**Comment by gibfahn** [comment]
Minutes landed in https://github.com/nodejs/build/pull/810
