### ISSUE TITLE
Assess Fedora 26, retire old Fedora

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#788]
..is out. We should probably test on it.

https://fedoramagazine.org/fedora-26-is-here/

**Comment by rvagg** [comment]
FYI if someone wants to tackle this, ansible is the place to contribute.

As of yesterday Fedora 24 was retired, so we're now running 3 out of date versions - 22, 23 and 24, and we really should get rid of those. Does someone with Jenkins access want to disentangle them from the various jobs?

**Comment by jbergstroem** [comment]
My contribution hours will change in roughly a month so expect me to vacuum the bug tracker unless anyone beats me to the punch (anon: i know you can do it!).

**Comment by Trott** [comment]
We currently have Fedora 27 in CI now and https://github.com/nodejs/build/issues/962 is an open issue to retire 22, 23, and 24.

I'm going to close this, but please re-open if that's not the right thing to do.
