### ISSUE TITLE
TAP/TUN kernel module

### ISSUE THREAD

**Issue by CurlyMoo** [nodejs/build#792]
Do the build (linux) server have the TAP/TUN network kernel module built-in or available as a separate module that we can load? I'm trying to unittest some libuv code for which i need to initialize a temporary TAP device.

**Comment by gibfahn** [comment]
So this is related to https://github.com/libuv/libuv/pull/1412#issuecomment-314837122 right?

If you look at the [libuv job](https://ci.nodejs.org/job/libuv-test-commit-linux/365/), you'll see that we have a large number of platforms. Are you asking whether it's installed on all of them?

![image](https://user-images.githubusercontent.com/15943089/28153452-20c93082-67ae-11e7-8afb-bb59e9d009e2.png)

You can see the ansible scripts we use to set up machines [here](https://github.com/nodejs/build/tree/master/ansible), you may be able to tell from that. Also if you give me a command to run I can test it on the machines.

**Comment by maclover7** [comment]
Can this be closed?

**Comment by gibfahn** [comment]
I think so, @CurlyMoo let us know if you disagree.

**Comment by CurlyMoo** [comment]
If these modules won't become available then this topic isn't any use indeed.

**Comment by gibfahn** [comment]
>If these modules won't become available then this topic isn't any use indeed.

@CurlyMoo do you still have a use for these modules? If so then we should reopen. Assuming they're installable via the standard package managers then there's no reason we should include them in our Ansible config.

**Comment by CurlyMoo** [comment]
I want to use it to unittest some networking code.

**Comment by bnoordhuis** [comment]
You need root privileges (CAP_NET_ADMIN, technically speaking) to bring up a TAP interface so I don't know if this is going to work.

**Comment by CurlyMoo** [comment]
In order to properly test networking code, a dummy networking device would be great. So one option would be to enable one by default at boot time.

**Comment by maclover7** [comment]
Going to close this for now, since there doesn't seem to be anything immediately actionable -- please reopen if I'm wrong
