### ISSUE TITLE
Add core-validate-commit to node-test-pull-request

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#793]
Was thinking we should probably add core-validate-commit to node-test-pull-request to automate checks on the commit message.

**Comment by joaocgreis** [comment]
+1

I remember some discussion around this, but I can't find it. @evanlucas do you remember? If it was simply not ready at the time, is it now?

**Comment by gibfahn** [comment]
The job is there, it just needs to be included (as long as it's working). I see that @evanlucas has access to it.

https://ci.nodejs.org/job/node-test-commitmsg/

**Comment by gibfahn** [comment]
>@Trott thanks for the suggestion. Have installed it now. Do you use it when reviewing as well or just as a sanity check for the final land ?
>
>I also wonder if we could add running this to the node-test-pull-request in addition to the linter ?

@mhdawson in reply to https://github.com/nodejs/node/commit/d5b397c9b63507a5dcf6d1da47df2a090d3d73a0#commitcomment-23061905

I use it as a sanity check before landing. It'll fail before then anyway as it won't find the `PR-URL` or `Reviewed-By` lines. I think @refack has it set up as a pre-commit hook (so you can't commit without it being correct), though I could be misremembering.

**Comment by mcollina** [comment]
I am -1 with this change as proposed. This will fail for all the PRs on the first go, because they lack reviews and a PR url. It will just increase the amount of nit-picking, as we will likely require to fix those details by the author, while we currently fix them on landing.

If we can disable those checks for the job, then I am +1.

**Comment by refack** [comment]
> I think @refack has it set up as a pre-commit

`pre-push`, and it has a `if ($2.includes('/nodejs/node'))`.
I don't want to tie my hands completely.

**Comment by evanlucas** [comment]
> It'll fail before then anyway as it won't find the PR-URL or Reviewed-By lines. 

You can pass the `--no-validate-metadata` flag and it won't fail from a missing PR-URL or missing Reviewed-By.

The job that is there works pretty well. It can be run against a single commit or all of the commits for a PR. It becomes tricky with fixup commits though...

**Comment by fhinkel** [comment]
`core-validate-commit` is great! But iIrc it complains about Chromium backports because a line with the URL is too long.

**Comment by evanlucas** [comment]
@fhinkel I’ll try to get around to fixing that.

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.

**Comment by richardlau** [comment]
We are running `core-validate-commit` in Travis CI but it was recently marked as allowed to fail which means that you need to manually look at the Travis CI results (either the check tab on the PR page or in Travis itself) to see if it failed or not (the overall check status for Travis CI in the main tab on the PR page will be green even if the `core-validate-commit` run fails).
