### ISSUE TITLE
Run tests against the artifacts we ship

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#794]
We currently run tests on the commit we plan to ship, but we don't actually test the packages we create. which means we have no defence against issues like https://github.com/nodejs/node/issues/13667 or https://github.com/nodejs/node/issues/8814. 

<br/> 

#### Strawman proposal: 

We run the release job, it generates a set of tarballs/packages. We upload them to `nodejs.org` as usual, but don't promote them.

Then we can run the CI tests on them and make sure everything is kosher. If a test fails we can just rerun the CI without rebuilding.

<br/>
<br/>

This would probably be a pretty large amount of refactoring work, but I think it would have a real benefit for users.

Related: https://github.com/nodejs/build/issues/513

**Comment by mhdawson** [comment]
It would be good to run tests on what we ship. 

Is there a good way to break the changes down into manageable chunks ?    While not as good as the end goal it would be a step in the right direction.  Seems like you are already thinking along those lines.

#513 is a good first step and the next one might be to run full unit tests.

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
