### ISSUE TITLE
/ansible scripts fail on Centos 6

### ISSUE THREAD

**Issue by seishun** [nodejs/build#801]
When running `ansible/ansible-playbook playbooks/jenkins/worker/create.yml` on a Centos 6 host, I get the following error:

```
TASK [baselayout : disable sftp] *******************************************************************************************************
fatal: [test-softlayer-centos6-x64-1]: FAILED! => {"changed": false, "failed": true, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
```

If I install libselinux-python manually, then the following happens:

```
TASK [baselayout : repo : add scl devtoolset] ******************************************************************************************
fatal: [test-softlayer-centos6-x64-1]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: name"}
```

Judging by the comments in the file, it seems `ansible/roles/baselayout/tasks/partials/repo/centos6.yml` is unfinished.

**Comment by rvagg** [comment]
Oh, you know, I did this recently and ran into a ton of trouble because they've changed a bunch of stuff over at scientificlinux where we pull this from. Unfortunately I missed the memo that we'd finally made the switch to the new ansible stuff and did it in the old ansible tooling, I'd be grateful if you were able to do the conversion for me, otherwise just use the old playbook: https://github.com/nodejs/build/pull/740

**Comment by seishun** [comment]
Is the old playbook non-functional without #740?

**Comment by rvagg** [comment]
#740 is good to go, you could just use that to provision a centos6 machine, it's just not merged because ideally it should be against the new ansible infra instead.

**Comment by seishun** [comment]
Is it planned to be merged soon? Otherwise my PR will be blocked.

**Comment by rvagg** [comment]
@seishun I just merged it, better than nothing at this stage so if you want to PR against CeotOS6 setup then you'd better do it against the old Ansible playbook unless you're going to do the conversion but there's no requirement that you do.

**Comment by rvagg** [comment]
pretty sure this is fixed and has moved on to discussions about which devtoolset, https://github.com/nodejs/build/pull/1203 for one
