### ISSUE TITLE
Ability to do introspection on failures seems to have vanished

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#802]
in the past we would get an aggregate list of failures in CI... this no longer seems available, and I have to do a bunch of spelunking. Anyone else seeing this, or am I missing an obvious button?

**Comment by gibfahn** [comment]
Are you talking about the [`Aggregated Test Result`](https://ci.nodejs.org/job/node-test-commit/lastCompletedBuild/aggregatedTestReport/)? If so then yeah, those results disappear if one of the options is disabled on one of the subjobs. 

Output is:

>Fingerprinting not enabled on this build. Test aggregation requires fingerprinting.

**Comment by gibfahn** [comment]
I'd suggest we need to be enabling fingerprinting like so:

![image](https://user-images.githubusercontent.com/15943089/28343580-a5980ef4-6c50-11e7-83ea-a2f97dae2f3d.png)

**Comment by gibfahn** [comment]
On a related note, is there a reason we're using the `Jenkins Text Finder` plugin? The TAP plugin parses the results and marks the build as `UNSTABLE` if tests fail anyway.

**Comment by rvagg** [comment]
no objection from me if you want to give that a go @gibfahn, are you in jenkins-admins? re Jenkins Text Finder, I don't know who or why it's in there unfortunately.

**Comment by gibfahn** [comment]
>are you in jenkins-admins

Yes. I'll have a look.

**Comment by mhdawson** [comment]
The aggregate list sounds really useful :)  I'll look forward to trying it out.

**Comment by gibfahn** [comment]
I'll test it out in readable-stream-continuous-integration https://github.com/nodejs/build/issues/782 first.

**Comment by MylesBorins** [comment]
any traction on this? Having to dig into raw tap is a pretty bad ux

**Comment by gibfahn** [comment]
Enabling fingerprinting doesn't seem to actually work, at least not reliably. This irritates a lot of people, it's just waiting for someone to work out what the magic Jenkins formula is.

Alternatively we could just use `tap2junit`

**Comment by MylesBorins** [comment]
Do we have any insight into improving this? I noticed it was randomly working on a machine today
