### ISSUE TITLE
All pi1-raspbian-wheezy release nodes are down

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#803]
halp

https://ci-release.nodejs.org/job/iojs+release/nodes=pi1-raspbian-wheezy/

**Comment by MylesBorins** [comment]
Last successful build was July 11th

**Comment by rvagg** [comment]
restarted both of them, one had a bunch of unnecessary stuff on disk that was pushing it into "not enough disk" making it effectively offline, both working again now, thanks @MylesBorins
