### ISSUE TITLE
Optimize test scripts for CI job for windows

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/build#805]
2 things I noticed when working on adding check for `cctest.tap` failures in CI. We distribute the test cases in 4 groups (%RUN_SUBSET%) and each machine runs individual group. However all the groups run `cctest` and build the addons. Although not trivial, we can speed up the test job by running `cctest` on just 1 machine (need to figure out how) and also skip building addons if that group won't be testing `test-addons` or `test-addons-napi` unless there was historical reason for not doing it in this way.

**Comment by rvagg** [comment]
this is certainly a job for @joaocgreis, he's our multi-job master, the rest of us just :see_no_evil:

**Comment by maclover7** [comment]
ping @kunalspathak

**Comment by joaocgreis** [comment]
Let's leave this open. The Windows jobs will have to be updated to pipelines some time (I plan to do it when I find the time), this is a nice feature to include in that effort.

**Comment by joaocgreis** [comment]
This has been done for some time, and now included in https://github.com/nodejs/build/pull/2099.
