### ISSUE TITLE
Demo KeyBox at next WG Meeting

### ISSUE THREAD

**Issue by gdams** [nodejs/build#806]
I would like to demo [KeyBox](http://sshkeybox.com/) at the next Build WG meeting.

The main selling points to me:
1. It's free! (it's all apache 2 license)
2. It makes deploying new SSH keys very simple to all machines
3. It makes revoking access for a certain key very quick and simple (great for temp access)
4. It's very easy to audit who has access to what
5. It also has some exciting other features such as web based terminals and easy script deployment

My plan would be to set up a KeyBox server on a small linux machine and configure this for the community to manage all of their machines. I have been successfully using this system for managing key access to the [AdoptOpenJDK](https://adoptopenjdk.net/) build farm and think that it's a suitable candidate for the Node.js Community to also use. 

Please note that I am in no way affiliated with KeyBox, I just love how great it is!

**Comment by rvagg** [comment]
this sounds promising, we've the times where we've had to revoke and replace the global keys we use have been pretty painful (Ansible has helped somewhat) and giving temporary access to collaborators usually involves forgetting that they were given access and leaving their keys in place

**Comment by gdams** [comment]
@rvagg, this is the exact issue that I was experiencing with AdoptOpenJDK before I started using KeyBox

**Comment by mhdawson** [comment]
Lets plan to have on the agenda for the next meeting which is Aug 22nd at 4 EST.  Next week !

**Comment by gibfahn** [comment]
@gdams agreement on this was that waiting till next meeting (3 weeks, 12th September) is fine, but if we don't hit that target it might be worth arranging a one off meeting to demo this. If you're going to be busy by the 12th, we should maybe look at organising something (probably on a Tuesday evening).

**Comment by mhdawson** [comment]
Demo happened, closing

**Comment by gibfahn** [comment]
@mhdawson I think at the meeting we said we should keep this open for other feedback, and for progress on getting it running.

Obviously it can just be a new issue, but still.
