### ISSUE TITLE
Add zos to libuv builds

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#807]
Initial Z/os machine is in place and PR for ansible updates to configure is here:

This issue is to track adding a job to run the libuv tests.  Job is being worked on her: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-zos/

**Comment by mhdawson** [comment]
PR for ansible changes: https://github.com/nodejs/build/pull/796

**Comment by mhdawson** [comment]
Ok, 2 test machines have been added to CI and are running a nightly test on libuv.
Also added 1 release machine but will leave final configuration until we need it for release jobs.

Still need to:

- [ ] close out ansible changes.
- [ ] get libuv to green (only 2 current failures)
- [ ] add libuv as a platform in the regular libuv regression runs.

**Comment by maclover7** [comment]
ping @mhdawson -- can this be closed?

**Comment by mhdawson** [comment]
Yup, closing.
