### ISSUE TITLE
ci: ubuntu1604-arm64 missing from node-stress-single-test

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#813]
URL: https://ci.nodejs.org/job/node-stress-single-test/build?delay=0sec

Problem: There is no ubuntu1604-arm64 option in the RUN_LABEL dropdown.  Maybe others are missing too?

**Comment by gibfahn** [comment]
Looks like that list has to be manually updated (in two different places in the job). If you think of others let me know and I'll add them.

**Comment by gibfahn** [comment]
Reopen if there are others that need adding.
