### ISSUE TITLE
release CI issues?

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#815]
The CI seems to be having issues and I can't seem to be able to spawn a job to build armv6 8.2.1 artifacts: https://ci-release.nodejs.org/job/iojs+release/1886/console

Refs: https://github.com/nodejs/node/issues/13737#issuecomment-318688566

**Comment by rvagg** [comment]
Yikes, that's properly borked. On it, no promises on speed though.

**Comment by rvagg** [comment]
Did a minor server upgrade and restarted Jenkins, I think the Jenkins restart was all that was required. I triggered a full 8.2.1 @ https://ci-release.nodejs.org/job/iojs+release/1887/ and it looks like it's going through just fine, armv6 is building properly currently too.

If you want to promote just the armv6 binaries for 8.2.1 then let me know and I'll clean out the rest from staging.
