### ISSUE TITLE
now: armv7-ubuntu1404 machines are offline

### ISSUE THREAD

**Issue by refack** [nodejs/build#817]
https://ci.nodejs.org/job/node-test-commit-arm/nodes=armv7-ubuntu1404/
![image](https://user-images.githubusercontent.com/96947/28745432-693d5bbe-7446-11e7-9572-ce9128ac9668.png)

**Comment by Trott** [comment]
I totally get it if this has to wait until it's not a weekend somewhere, so feel free to ignore, but just in case this is the only thing that's keeping it from getting attention: @nodejs/build

**Comment by rvagg** [comment]
on it

**Comment by rvagg** [comment]
problems on all 3 of them! I can't bring them back online and am going to have to physically remove them and resolve whatever is going on, we've been having trouble with at least one of them for a while now but having all 3 goes down is a bit suspicious although perhaps explained by operating system updates. I've taken them out of node-test-linux-arm for now and will hopefully have them back online in the next few days.

**Comment by refack** [comment]
And now... the two `ubuntu1604-arm64` workers are down https://ci.nodejs.org/label/ubuntu1604-arm64/
@rvagg anyway to know if it's a "real" issue? that is if something new in the code causes the builds/tests to crash the machines?

**Comment by refack** [comment]
Not completely related, but there are two Windows jobs with > 2GB logs
* https://ci.nodejs.org/job/node-test-binary-windows/10196/RUN_SUBSET=1,VS_VERSION=vs2015,label=win2012r2/
* https://ci.nodejs.org/job/node-test-binary-windows/10197/RUN_SUBSET=0,VS_VERSION=vs2015,label=win2012r2/

**Comment by Trott** [comment]
node-test-commit-arm seems to be having real problems...

https://ci.nodejs.org/job/node-test-commit-arm/11219/console

```console
Started by upstream project "node-test-commit" build number 11472
originally caused by:
 Started by upstream project "node-test-pull-request" build number 9425
 originally caused by:
  Started by user Rich Trott
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/jobs/node-test-commit-arm/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/nodejs/node.git # timeout=10
Fetching upstream changes from https://github.com/nodejs/node.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/14536/head:refs/remotes/origin/_jenkins_local_branch # timeout=20
 > git rev-parse refs/remotes/origin/_jenkins_local_branch^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/refs/heads/_jenkins_local_branch^{commit} # timeout=10
Checking out Revision 1766db0f07098a4fc19271b00dda2cebab2c6f16 (refs/remotes/origin/_jenkins_local_branch)
Commit message: "test: refactor test-vm-new-script-new-context"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 1766db0f07098a4fc19271b00dda2cebab2c6f16
Using 'Changelog to branch' strategy.
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Triggering node-test-commit-arm » ubuntu1604-arm64
FATAL: null
java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:118)
	at hudson.model.ParametersAction.shouldSchedule(ParametersAction.java:228)
	at hudson.model.Queue.scheduleInternal(Queue.java:615)
	at hudson.model.Queue.schedule2(Queue.java:585)
	at hudson.matrix.MatrixConfiguration.scheduleBuild(MatrixConfiguration.java:512)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.scheduleConfigurationBuild(DefaultMatrixExecutionStrategyImpl.java:247)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.run(DefaultMatrixExecutionStrategyImpl.java:159)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:364)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:313)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by Trott** [comment]
https://ci.nodejs.org/job/node-test-commit-arm/ Build History looks like this...

<img width="321" alt="screen shot 2017-07-31 at 7 58 30 pm" src="https://user-images.githubusercontent.com/718899/28807496-abfdb094-762a-11e7-94e2-d88c3380394b.png">

**Comment by rvagg** [comment]
on it

**Comment by rvagg** [comment]
3 out of the 4 of them had problems, I think it might be related to the datacenter those are in as I've had more success with one of their Asian datacenters.

They're restarted, updated and I've cleaned out the workspace of the centos7 boxes because that seemed to be causing problems on one of them. https://ci.nodejs.org/job/node-test-commit-arm/11222/
