### ISSUE TITLE
Build WG Meeting 1 August 2017 

### ISSUE THREAD

**Issue by piccoloaiutante** [nodejs/build#819]
Place holder as reminder for people that we have a meeting tomorrow at 6 PM EST as per the community calendar.

### When

August 1, 2017 6 PM EST - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20170801T22&p1=1440&ah=1)

### Where
- [Hangouts on Air, for participants]()
- [Youtube stream, for viewers]()
- [Events page]()
- [Minutes document]()
- [Previous meeting](https://github.com/nodejs/build/issues/787)

### Agenda

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by piccoloaiutante** [comment]
As 6 PM EST it's a little bit late for me I won't be joining today's call. I'll post my update later during the day.

**Comment by joaocgreis** [comment]
I can't make it today. I have no progress to report, I haven't been around for the past couple of weeks and won't be for some more time (but please mention me if there's anything urgent).

**Comment by mhdawson** [comment]
@nodejs/build anybody else able to make it ?

**Comment by kunalspathak** [comment]
I might not be able to make today's meeting. Updates from me:
* test-v8 PR merged - https://github.com/nodejs/benchmarking/issues/124
* fixed cctest failure inclusion - https://github.com/nodejs/build/issues/769
* opened windows Jenkins CI job improvement - https://github.com/nodejs/build/issues/805
* investigated the arm failure . PR is merged https://github.com/nodejs/node/pull/14533

**Comment by rvagg** [comment]
I can make it, but not a great time to be focused, helping get kids off to school.

**Comment by mhdawson** [comment]
I'm distracted as well, so I'd be happy to skip until next time.

**Comment by rvagg** [comment]
OK then, I'll try and post an update here shortly. It's been a busy few weeks for me on infra and it's not looking like lessening any time soon.

**Comment by piccoloaiutante** [comment]
My update:

- been working on https://github.com/nodejs/build/pull/785 and implemented feedback over it
- started working again on a new module for generating remmina file https://github.com/jbergstroem/build/pull/2#issuecomment-298462706 .Will move this work against current master. 

I'll be on vacation soon so I won't be here for next standup on 22 of August.

**Comment by gibfahn** [comment]
Async meeting, so no minutes. Closing.
