### ISSUE TITLE
CI for testing release procedures

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/build#83]
Recently, we've had 2? failures due to release bugs.

I propose we set up CI tasks to run the release in a purely testing way. (So that we can go back and check though commits with it, unlike the nightly, which auto-publishes.)

cc @rvagg

**Comment by rvagg** [comment]
only 1 failure from release-related bugs, that makefile thing

I'm trying to think through how this could work and I just see many yaks to shave, perhaps you, or someone else could suggest a workflow that would make this doable and useful

**Comment by Fishrock123** [comment]
Makefile and vcbuild.bat would have been easier to narrow down like this.

I'm really just thinking of things that run the release procedures but throw out the builds.

**Comment by jbergstroem** [comment]
Does our release jobs cover this or are we missing something? (ping @rvagg)

**Comment by rvagg** [comment]
no, it creates release builds but they are not tests, the OP is about doing full release builds and testing that they install/unpack & work and I don't know how we can achieve that everywhere without making a huge mess.

**Comment by maclover7** [comment]
ping -- is this still needed?

**Comment by gibfahn** [comment]
>ping -- is this still needed?

I think this is still needed, but it'd require quite a lot of changes.

**Comment by mhdawson** [comment]
We now test the downloads nightly to validate the packages are ok, the next step might be to do extend this to allow us to run the test suite as well.

**Comment by Trott** [comment]
20 months the last comment... Is this still an issue that should remain open?

**Comment by mhdawson** [comment]
I think given the time lapse we can close.  One thing to note is that: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-LTS%20versions/ pulls down all of the latest LTS versions across platforms and uses them to validate node-addon-api.  If any of the binaries are not available or are not working one of its sub-components ends up failing.
