### ISSUE TITLE
create daily v6.x and v8.x jobs

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#834]
We currently have a daily job for master, v4.x, and coverify

It would be great to have a daily job for v6.x and v8.x

Could also be interesting to do a daily citgm as well.

**Comment by rvagg** [comment]
SGTM, we have plenty of downtime between Americans going to bed and Europeans waking up—Asia primetime, my afternoons when nobody is around and CI is very quiet!

**Comment by rvagg** [comment]
https://ci.nodejs.org/view/Node.js Daily/

Hooked up v6.x-staging and v8.x-staging to new jobs and made a new view to hold these daily jobs. They are now distributed as following in Eastern time (don't ask me why it's doing this in Eastern):

* 2am coverity https://ci.nodejs.org/view/Node.js Daily/job/node-daily-coverity/ (all green)
* 3am master https://ci.nodejs.org/view/Node.js Daily/job/node-daily-master/ (recent green)
* 4am v4.x-staging https://ci.nodejs.org/view/Node.js Daily/job/node-daily-v4.x-staging/ (some platform-specific consistent failures)
* 5am v6.x-staging https://ci.nodejs.org/view/Node.js Daily/job/node-daily-v6.x-staging/ (running first one now)
* 6am v8.x-staging https://ci.nodejs.org/view/Node.js Daily/job/node-daily-v8.x-staging/ (running first one now)

**Comment by mhdawson** [comment]
Great to see these. I had been thinking daily jobs for all shipping streams would be useful.
