### ISSUE TITLE
Temporary access to aix machines for me

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#835]
Have a rogue failure on v6.x, would be substantially faster to bisect on a box. How do I access the aix machines???

/Cc @nodejs/platform-aix

**Comment by gibfahn** [comment]
SGTM, I'll put your key on the machines

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
Add Myles key.

**Comment by MylesBorins** [comment]
fwiw getting an `ESRCH` error in parallel/test-child-process-detached when trying to kill child process in v6.x-staging

```
[ESRCH]
No process or process group can be found corresponding to that specified by pid.
```

**Comment by MylesBorins** [comment]
all done!

issue was a spurious common.noop in a fixture
