### ISSUE TITLE
Build WG Meeting 22 August 2017 

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#837]
### When

Aug 22, 2017 8 PM UTC - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20170822T20&p1=1440&ah=1)

### Where
- [Hangouts on Air, for participants](https://hangouts.google.com/hangouts/_/ytl/-3A12YAc4qSLIuSdimpjaIuJNcuVKuUOAqlwSXaUTho=?eid=100598160817214911030)
- [Youtube stream, for viewers](https://www.youtube.com/watch?v=WF7oa1heAko)
- [Events page](https://www.youtube.com/my_live_events?filter=scheduled)
- [Minutes document](https://docs.google.com/document/d/1hT7EXsa2esK1Gfq1znOu3Q-8FnhWLmWnIc0KpVZYuG0/edit?usp=sharing)
- [Previous meeting](https://github.com/nodejs/build/issues/819)

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* Create subteams to document release/infra/github-bot access [#826](https://github.com/nodejs/build/issues/826)
* Demo KeyBox at next WG Meeting [#806](https://github.com/nodejs/build/issues/806)
* tools: add download testing [#804](https://github.com/nodejs/build/pull/804)
* Migrate job configuration to pipeline files [#838](https://github.com/nodejs/build/issues/838)
* Jenkins update requiring Java 8 [#775](https://github.com/nodejs/build/issues/775)

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by refack** [comment]
Bug in agenda generator?
![image](https://user-images.githubusercontent.com/96947/29466848-52faa138-840c-11e7-8bab-969f5ff3819b.png)

Actual list:
* [Create subteams to document release/infra/github-bot access](https://github.com/nodejs/build/issues/826)
* [Demo KeyBox at next WG Meeting](https://github.com/nodejs/build/issues/806)

**Comment by gibfahn** [comment]
>Bug in agenda generator?

Refresh the page. There isn't actually a generator, I just copy it in from [the template](https://github.com/nodejs/build/blob/master/doc/templates/wg-meeting-issue-template.md) then add the items by following the links.

**Comment by mhdawson** [comment]
@jBarz FYI.

**Comment by refack** [comment]
so bug in ![image](https://user-images.githubusercontent.com/96947/29467306-f5c023ec-840d-11e7-9dff-ddc085144957.png) 😜

**Comment by gibfahn** [comment]
I guess. The point is that you can add your own agenda items though, so leaving it unfilled in is fine too.

**Comment by Trott** [comment]
@gibfahn I doubt making these agendas is a problem, but if I'm wrong and it *is* tedious, we can get you set up with [`make-node-meeting`](https://github.com/rvagg/make-node-meeting).

**Comment by gibfahn** [comment]
@Trott It's not massively tedious, but if there is automation then that would be great. The bigger issue is remembering to create the issue.

Does that get run on a schedule or is it run manually? I'd ideally like a bot that worked out meeting times from the calendar and created the issue, and then updated it when people added the tag to new issues.

Ideally it'd parse minutes and raise the PR automatically too.

**Comment by Trott** [comment]
> Does that get run on a schedule or is it run manually?

@gibfahn Manually, but I don't see why it can't be automated or at least put in a cron job that mails you the results so you get a reminder to open the issue via copy/paste from the email.

**Comment by gibfahn** [comment]
@mhdawson @joaocgreis @rvagg could someone with streaming/org permissions host the call?

**Comment by mhdawson** [comment]
About to start the meeting

**Comment by mhdawson** [comment]
https://hangouts.google.com/hangouts/_/ytl/-3A12YAc4qSLIuSdimpjaIuJNcuVKuUOAqlwSXaUTho=?eid=100598160817214911030

**Comment by gibfahn** [comment]
Any questions please post here
