### ISSUE TITLE
A job for testing node-addon-api

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/build#844]
We need a job for testing a commit in the node-addon-api repo. We're running into problems which could have been prevented with a CI:

https://github.com/nodejs/node-addon-api/issues/116
https://github.com/nodejs/node-addon-api/pull/115
https://github.com/nodejs/node-addon-api/pull/114

The job would not build Node.js at all, but would use nvm or nvs to grab the official release and test node-addon-napi against it.

**Comment by gabrielschulhof** [comment]
@mcollina, right?

**Comment by refack** [comment]
LGTM
(I would like to take a shot at implementing)

**Comment by mcollina** [comment]
@gabrielschulhof yes.

Thanks @refack!

**Comment by gibfahn** [comment]
I can help get you guys set up (creating Jenkin jobs etc), and then @refack can help with configuration stuff.

**Comment by gibfahn** [comment]
So I see that there is a bunch of n-api stuff already, see this [CI Tab with a bunch of jobs](https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/). I note that the access permissions are configured for [`nodejs/abi-stable-node-admins`](https://github.com/orgs/nodejs/teams/abi-stable-node-admins/members) and `nodejs/nodejs*abi-stable-node`, the latter doesn't exist any more.

So I'm guessing that the effort to add CI already started but stalled. Is that correct?

Assuming this is correct, I'd say we should:
- Rename `abi-stable-node-admins` to `n-api-admins` to be compatible with `n-api`
- Delete the existing jobs, which are based on `node-test-commit`
- Copy an existing "pull node, npm install, npm test" project, like `node-report` or `citgm`.
- Give `n-api` run access, and `n-api-admins` configure access (and also @refack so he can help out).

@nodejs/n-api can someone confirm that this is correct?

**Comment by gabrielschulhof** [comment]
That tab was for the abi-stable-node fork while we were preparing the initial N-API PR. Now that N-API is in, I don't think we need it anymore. @mhdawson knows more, but that's my general impression.

OTOH, node-addon-api is a separate npm package which will remain separate, so we will continue to need separate CI for it.

**Comment by mhdawson** [comment]
There are some jobs in there that are still needed and that we are working on.

The naming of the admins is because the team was renamed, since Sampson has been able to edit its possible that it is respecting both names

I'll delete the jobs we don't need

**Comment by mhdawson** [comment]
I still see the team which is called: 
abi-stable-node-admins which matches what the job is configured for.

**Comment by mhdawson** [comment]
The name also matches the repo abi-stable-node, and host jobs that test modules that test both modules that use the  node-addon-api and which use the N-API directly.

**Comment by mhdawson** [comment]
I'll create a new job which is configured like the others and add refack to the admins team so that he can help configure.

**Comment by mhdawson** [comment]
The other team though was renamed, at one point so I guess the admins one should match and it has less visible impact.

**Comment by mhdawson** [comment]
Reconfigured existing jobs
Added this job as a clone of the node-report one
Aded refack as n-api-admins so he can configure job.

**Comment by mhdawson** [comment]
@refack let us know if you need anything else.

**Comment by refack** [comment]
> @refack let us know if you need anything else.

Will do. Thanks!

**Comment by mhdawson** [comment]
Thank you for volunteering :).  I really like to have as much CI as possible and having somebody to help build it out is great.

**Comment by mhdawson** [comment]
oops missed pasting in the link to the new job. Its: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api/

**Comment by maclover7** [comment]
https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api/ has been created per above, going to close for now since this seems largely solved (and the job is green!)
