### ISSUE TITLE
Access to new mac infra for @gdams

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#851]
I'm trying to pull @gdams into help make progress on configuring our new mac infrastructure.

I'd at least like to get him access to the individual machines.

Broader access would be good and I'm thinking it might not be as much of a concern yet since the infra is not yet setup and being used in our builds.  We could look at doing things like changing keys etc. after the setup is complete.

As per the regular requirements in https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md:

* Does the scope and size of the need justify providing access.
  * _It is important that we make progress on bringing the mac infra online and we have not been able to progress that as fast as necessary -> Yes_
* Is the invidual a collaborator. If so then access should be allowed provided the first point is satisfied.
  * _He is not yet a collaborator, but has been active in the CitGM group and has already had some configuration access to the CI jobs managed by the CitGM team_
* Length and consistency of involvement with Node.js working groups and/or community.
  * _He has been contributing to CitGM over the last 6-12 months, and is part of the CITGM team._
* Consequences to the invidudal in case of mis-behaviour. For example, would they potentially lose their job if they were reported as mis-behaving to their employer ? Would being banned from involvement in the Node.js community negatively affect them personally in some other way?
  * _He works with me at IBM and there would be consequences._
* Are there collaborators who work with the individual and can vouch for them.
  * _I will vouch for him.  Other collaborators that may support as well include @gibfahn_

**Comment by gibfahn** [comment]
+1

I'd also note that we've given him access to AIX machines in the past https://github.com/nodejs/build/issues/616 https://github.com/nodejs/build/issues/661

**Comment by joaocgreis** [comment]
+1 for individual machines access. @gdams I believe you'd be welcome in the Build WG if you want to join, and keep access after this is done!

Also ok with infra access, but please make sure to revoke access when the machines go live (by updating the password, if I'm not missing anything). We must be much more careful at this level. cc @rvagg @jbergstroem

**Comment by joaocgreis** [comment]
To be clear, @mhdawson your intention is to share the credentials on `infra/macstadium.md`, right?

**Comment by gdams** [comment]
> I believe you'd be welcome in the Build WG if you want to join, and keep access after this is done!

@joaocgreis thanks for that! I am hoping to help set this up and then help setup a KeyBox instance for SSH key management so being in the build WG would be great!

**Comment by mhdawson** [comment]
@joaocgreis yes that is what I was thinking.  But of course wanted to see if other people on the build WG thought that would be ok or not.  If that is not ok then the fallback would be to just give him access to the machines themselves, but that will take more work as the firewall etc needs to be setup first.

**Comment by gdams** [comment]
@mhdawson shall I create another issue for adding me to the build WG? That way everyone can vote

**Comment by mhdawson** [comment]
@joaocgreis would you like to create the issue to add gdams to the build WG ?   Otherwise I can go it, just thinking that's better than self nomination.

**Comment by gibfahn** [comment]
>@joaocgreis would you like to create the issue to add gdams to the build WG ? Otherwise I can go it, just thinking that's better than self nomination.

I think if @gdams raises a PR to add himself to the README then that's fine (and people can use the PR reviews to comment).

**Comment by joaocgreis** [comment]
@mhdawson I'm ok with giving him only the macstadium password and reset it after he's done.

About joining, I don't think self nomination is a problem because we'd have to analyse the issue in exactly the same way. I'd have been happy to do it though, but I see I'm too late.

**Comment by mhdawson** [comment]
Seems like there are no objections but I'd feel more comfortable with at +1 from @jbergstroem  or @rvagg as well.

**Comment by rvagg** [comment]
Whoops! Yes, sorry, I very approve. I don't know if it'll help but perhaps we should schedule another day where we work collaboratively on this? My fear is that this vSphere stuff is such obscure specialised knowledge that only one person on the team (or not even on the team in this case I guess) will be the holder of that knowledge. It'd be great if we knew that more than one person knew how to wrangle this stuff for the future.

**Comment by gdams** [comment]
@rvagg let's see if https://github.com/nodejs/build/pull/860 gets approved and then I can hopefully work with you on putting together the new system?

**Comment by mhdawson** [comment]
I've got a time set next week with @gdams to ramp him up on what's in place already, outline key next steps and give me the access needed to get started.  At that point would be useful to have a working session if we can find a time everbody can make it.

**Comment by gibfahn** [comment]
@mhdawson did your onramp with @gdams happen? Would definitely be good to have a working session.

**Comment by mhdawson** [comment]
Yes, hooked him up maybe 2 weeks ago.  I'll follow up with him tomorrow/Monday and then we can see were we are.

**Comment by refack** [comment]
I'm assuming this has concluded

**Comment by mhdawson** [comment]
I think this should stay open until its complete and we have updated to revoke his access.

**Comment by mhdawson** [comment]
Yup, closing
