### ISSUE TITLE
CI jobs for Node-ChakraCore

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#854]
Node-ChakraCore has some resources in our CI infrastructure that so far have been mostly managed by me. I will continue helping as needed, but for some redundancy we should give a subset of @nodejs/node-chakracore members access as well, similarly to what has been done recently for other WGs.

I propose to create a new `nodejs/node-chakracore-admins` team with access to:
- edit the `chakracore-*` jobs on https://ci.nodejs.org/view/All/ (as described by [`jenkins_job_configuration_access.md`](https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuration_access.md))
- start runs of `node-chakracore` in CI-Release. Only `node-chakracore`, no other resources there should be accessible. @nodejs/build any objection to this?

@nodejs/node-chakracore who should be the initial members of the `node-chakracore-admins` team?

**Comment by refack** [comment]
+1
Also if they need extra help, I'd be happy to pitch in too.

**Comment by aruneshchandra** [comment]
Lets start with the following as admins for now:
@digitalinfinity
@kfarnung 
@jackhorton 
@mike-kaufman 
@MSLaguana

**Comment by joaocgreis** [comment]
Can someone with access please create `node-chakracore-admins` with the members listed above? (perhaps @mhdawson @Trott @rvagg ?) Thanks!

**Comment by mhdawson** [comment]
I created the team and added joao, Hitesh and Kyle, I don't know the other ids by sight.  Can you give us a bit of context of who they are, involvement in Node.js etc.

**Comment by mhdawson** [comment]
Also to note that I've made @joaocgreis a maintainer for the team.  @joaocgreis if that is ok with you I'll remove myself as a maintainer/group member.

**Comment by joaocgreis** [comment]
I've given @nodejs/node-chakracore-admins access to ci-release, but I've made sure this only applies to the `node-chakracore` job. Everything else remains hidden.

Jack Horton (@jackhorton), Mike Kaufman (@mike-kaufman) and Jimmy Thomson (@MSLaguana) are all part of @nodejs/chakracore and are active contributors to https://github.com/nodejs/node-chakracore . They are all Microsoft employees, and I believe working directly with @digitalinfinity and @kfarnung .

Also, going forward, the @nodejs/node-chakracore-admins team can be managed by opening issues in the node-chakracore repo. Only members of @nodejs/node-chakracore who are active collaborators can be accepted. @nodejs/build let me know if you think this needs an extra layer of approval, given that this team has access to ci-release. Since access is limited to one job, I believe this is enough.

@mhdawson let me know if you have any questions or if I can add them. I can be a maintainer of the team, feel free to remove yourself. Thanks for creating the team!

**Comment by gibfahn** [comment]
>@nodejs/build let me know if you think this needs an extra layer of approval, given that this team has access to ci-release.

So do the team have read access to https://ci-release.nodejs.org/job/iojs+release/ ? Ideally we'd make it so they couldn't even see that a build was happening, then there'd be 0 need for us to care about it. IDK if that's possible though.

**Comment by joaocgreis** [comment]
The team cannot see any job other than `node-chakracore`. I didn't check running jobs, but (unless Jenkins decides to surprise me) they should only be able to see the workers blocked by jobs they don't have access to. That's what happens in ci-test when private jobs are running.

**Comment by gibfahn** [comment]
Then no issue with node-chakracore-admins managing their group themselves.

**Comment by joaocgreis** [comment]
@mhdawson can you make clear if you have any objections or I can add the remaining members to @nodejs/node-chakracore-admins ? Thanks!

**Comment by mhdawson** [comment]
@joaocgreis its ok with me.

**Comment by joaocgreis** [comment]
All done. Thanks!

**Comment by kfarnung** [comment]
Thanks for taking care of this @joaocgreis!

**Comment by digitalinfinity** [comment]
Thanks @joaocgreis!
