### ISSUE TITLE
windows: expiring passwords

### ISSUE THREAD

**Issue by refack** [nodejs/build#858]
Just logged in to `test-rackspace-win2012r2-x64-10`
(had a previously crashed `git` so I had to `C:\workspace\node-compile-windows\label\win-vs2017\.git>rm index.lock`)
and I got "your password will expire today".

Do we cycle passwords? If not IMHO we should disable the password expiration policy.

/cc @joaocgreis

**Comment by joaocgreis** [comment]
We cycle passwords manually from time to time, but not with the frequency that Windows would like us to. I just ignore that warning. PR to disable in Ansible would be welcome!

Also, when git crashes, to be safe the best is to remove the whole workspace. Fist make sure the machine is not running anything and mark it temporarily offline. Then login and the whole `node-compile-windows`. Then bring the machine back online.

**Comment by Trott** [comment]
Seems like this can be closed, but by all means, re-open if I'm mistaken.
