### ISSUE TITLE
Temporary access to aix machines for me

### ISSUE THREAD

**Issue by ezequielgarcia** [nodejs/build#865]
As per @refack suggestion, would like to have access to the aix machine to inspect a linker error in https://github.com/nodejs/node/pull/12794.

Error link: https://ci.nodejs.org/job/node-test-commit-aix/8330/nodes=aix61-ppc64/console

**Comment by mhdawson** [comment]
Was wondering if you still needed this given that the CI was green, but understand that was because the test was excluded.

I think @gireeshpunathil was going to work with you and he's had access to the machines in the past so maybe re-enabling that access for him makes sense.

**Comment by ezequielgarcia** [comment]
Well, if I can get access to the machines I could bite the bullet and take a look. Maybe some rainy sunday or so :-)

**Comment by mhdawson** [comment]
Our standard process is outlined here: https://github.com/nodejs/build/blob/master/doc/process/special_access_to_build_resources.md

As part of that these are the questions we look to answer before giving access:

* Does the scope and size of the need justify providing access.
* Is the invidual a collaborator ?
* Length and consistency of involvement with Node.js working groups
  and/or community ?
* Consequences to the individual in case of mis-behavior. For example,
  would they potentially lose their job if they were reported as
  mis-behaving to their employer ? Would being banned from involvement
  in the Node.js community negatively affect them personally in some other
  way ?
* Are there collaborators who work with the individual and can vouch for
  them?

**Comment by refack** [comment]
I can vouch for @ezequielgarcia.
P.S. @ezequielgarcia we usually give limited time access, that is usually from the point you say you're on it, till the specific problem is resolved. So if we get the necessary OKs, we can still put it on hold, and you would ping me to add your key if and when you're available.

**Comment by gibfahn** [comment]
+1 to giving @ezequielgarcia access, though I would suggest working with someone else if you haven't used AIX before, it's UNIX but not exactly Linux. Feel free to ping in here if you want to look at it, and hopefully someone can pair-program on it.

On which note I think @jbarz was going to look at this.

**Comment by ezequielgarcia** [comment]
- Does the scope and size of the need justify providing access.
_Yes. Given I'm not familiar with AIX and don't have access to AIX hardware, I need it to find out what's the deal with the added dlopen test.
Same thing happened with OSX, it wasn't until I got myself a OSX platform that I could find the linker flags for the test to pass._

- Is the invidual a collaborator ?
_I'm a contributor._

- Length and consistency of involvement with Node.js working groups and/or community ?
_My involvement with Node.js started with https://github.com/nodejs/node/pull/12794._

- Consequences to the individual in case of mis-behavior.
_I'm not sure I would get fired. However, I'm proud of my FLOSS activities so I wouldn't do anything to harm my reputation._

- Are there collaborators who work with the individual and can vouch for
them?
_@refack has helped me recently. @gireeshpunathil offered to help on AIX too._

**Comment by jBarz** [comment]
I was able to find a fix I think. I will submit a PR

**Comment by ezequielgarcia** [comment]
I'm closing the issue, given @jBarz has taken the lead. Thanks a lot!

**Comment by refack** [comment]
@ezequielgarcia thanks for willing to follow up.
You're kind of dedication is rare.
Hats off 🎩
