### ISSUE TITLE
Ansible scripts needed for Benchmark Machines 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#868]
We need numpy, requests, eventlet installed on the benchmark marching to let us run DC-EIS.

I've given @uttampower an ansible introduction and he is going to start working on scripts for the benchmarking machines.  The first thing they will add to the configuration is these there modules.

In the mean time I've manually added them by running 

```bash
apt-get update
apt-get install python-pip
apt-get install python2.7-dev

pip install numpy
pip install requests (reports as already satisfied)
pip install eventlet
```

**Comment by rvagg** [comment]
I'm OK with pip _if we must_ have it, but often the popular packages are available via apt anyway, in this instance `python-numpy`, `python-requests` and `python-eventlet` all seem to be available in both 2.7 and 3 form.

**Comment by gibfahn** [comment]
>I'm OK with pip if we must have it, but often the popular packages are available via apt anyway, in this instance python-numpy, python-requests and python-eventlet all seem to be available in both 2.7 and 3 form.

We're hopefully moving towards tap2junit at some point, and I don't think that'll be available on apt (and yum etc.).

**Comment by mhdawson** [comment]
@rvagg 

so they can be installed with apt-get ie

apt-get install python-numpy
apt-get install python-request
apt-get install python-eventlet 

?

I had used pip as I believe it was already going to be available due to the need for tap2junit but when we work on the ansible scripts we can install the apt packages instead if they are available.

**Comment by rvagg** [comment]
Ah, well if we're using pip already then I guess it comes down to updating. apt-get is often run manually by myself and maybe others on our test machines but that's all for updating. If there's a pip update process it's unlikely to ever be run. Is that a problem? I don't know! I feel like this is one for the python folks among us to answer.
Sorry for the non-answer, my preference is still for apt-get install (`apt-get install python-numpy python-request python-eventlet -y`) but it's no big deal if we do it with pip _I guess_.

**Comment by gibfahn** [comment]
I'd prefer using `apt` where available too FWIW.

It would make sense to periodically rerun our ansible scripts (once we have them set up) to update everything.

**Comment by mhdawson** [comment]
@uttampower have you had a chance to start working on this yet ?

**Comment by maclover7** [comment]
Related issues: #821, #955

**Comment by mhdawson** [comment]
Related issue https://github.com/nodejs/build/issues/1147
