### ISSUE TITLE
How do you handle Authenticode signing?

### ISSUE THREAD

**Issue by Daniel15** [nodejs/build#874]
Hi!

I'm wondering if you can provide information on how the Node.js project performs Authenticode signing on the Windows .msi file? Do you perform it manually, or is it part of an automated release process? For [Yarn](https://yarnpkg.com/) we automated it as part of the release process, but we're going to have issues due to the new requirement of private keys having to be stored 'securely', such as on a smart card or cryptographically secure USB token.

So, I'm looking for advice as to how other projects are handling this requirement. Currently, Yarn is using an open-source code-signing certificate from Certum, and all renewals are required to store the private key on a cryptographic USB token, so there's no way to actually extract the private key and store it anywhere else.

> The Minimum Requirements specify that CAs shall ensure stronger protection for private keys. As such, all Code Signing Certificates, not just Extended Validation level, will require a USB token starting on January 30, 2017
> https://support.globalsign.com/customer/portal/articles/2705869-minimum-requirements-for-code-signing

> US trade body the Certificate Authority Security Council decided in December that "best practice" for code-signing certificates was to embed them in hardware devices, a policy endorsed with upcoming changes from Microsoft that kick in next week.
https://www.theregister.co.uk/2017/01/26/windows_code_signing_changes/

> Stronger protection for private keys: The best practice will be to use a FIPS 140-2 Level 2 HSM or equivalent. Studies show that code signing attacks are split evenly between issuing to bad publishers and issuing to good publishers that unknowingly allow their keys to be compromised. That enables an attacker to sign malware stating it was published by a legitimate company. Therefore, companies must either store keys in hardware they keep on premise hardware, or in a new secure cloud-based code signing cloud-based service.
https://www.helpnetsecurity.com/2016/12/12/code-signing-requirements/

(I haven't seen anything about this "cloud-based code signing service" though. Symantec have one (https://www.websecurity.symantec.com/code-signing/secure-app) but it's ridiculously expensive, and Azure Key Vault doesn't support code signing)

Also see https://github.com/yarnpkg/yarn/issues/4403

**Comment by gibfahn** [comment]
Maybe a question for @joaocgreis or @refack

**Comment by refack** [comment]
I'm not sure, but I believe the certificate is kept in the release server's Certificate Store, which is "FIPS 140-2 Level 2" compliant, as long as the hardware is kept on premise.

**Comment by refack** [comment]
Ohh, and as a second level of validation we publish the hashes of the released files in a publicly readable location (i.e. https://nodejs.org/download/release/v8.4.0/SHASUMS256.txt) which is anyway the most corss-platform way to validate the integritiy of binaries.

**Comment by Daniel15** [comment]
>  which is anyway the most corss-platform way to validate the integritiy of binaries.

That's true, however Windows shows scary warning messages unless the installer is Authenticode signed, so it's basically a requirement for any Windows app. For all non-Windows platforms, Yarn uses GPG signing.

**Comment by joaocgreis** [comment]
Our certificate is stored in the Windows Certificate Store. Signing is currently automated with `signtool`: [`EXE`](https://github.com/nodejs/node/blob/640b20616d2cdc46bc3df8703cdc1395578ff1b3/vcbuild.bat#L270), [`MSI`](https://github.com/nodejs/node/blob/640b20616d2cdc46bc3df8703cdc1395578ff1b3/vcbuild.bat#L352) (using [this `bat` file](https://github.com/nodejs/node/blob/640b20616d2cdc46bc3df8703cdc1395578ff1b3/tools/sign.bat) to try multiple timeservers).

However, our certificate expires next month, and if DigiCert has also moved to USB tokens, we have the same issue.

@rvagg I believe you the current certificate in 2015. How do we renew it? Can you renew it or check if DigiCert still provides the `.p12` file?

**Comment by Daniel15** [comment]
I just asked DigiCert about it and their support rep wasn't even aware of these changes 😛 . It sounds like they're still issuing regular certificate files at the moment. Maybe we should switch Yarn to a DigiCert certificate if they can still issue regular certificate files. Hmm.

> Signing is currently automated with signtool: EXE, MSI (using this bat file to try multiple timeservers).

Cool, that's pretty similar to what we do with Yarn at the moment (using osslsigncode rather than signtool, but it's pretty similar).

**Comment by rvagg** [comment]
https://github.com/nodejs/TSC/issues/347 thanks for expiry heads up @joaocgreis! I have nothing else useful to add here; I didn't know about this new requirement and hope that we can get away with renewal as is, and the description of how we do it is accurate.

**Comment by joaocgreis** [comment]
@rvagg let us know when you have the key, if it turns out to be USB we don't have much time to find a solution. Thanks!

**Comment by rvagg** [comment]
Got the cert paid for. @joaocgreis is going to be installing it on our release machines. Will report progress back here as that's done.

**Comment by joaocgreis** [comment]
Certificate is still being processed by DigiCert. I'll keep checking and install it when ready.

**Comment by joaocgreis** [comment]
Certificates installed and good until 2020.

@Daniel15 in response to the original issue here, we have a `.p12` file. The process is documented here: https://www.digicert.com/code-signing/installing-code-signing-certificate.htm , the last step is particularly relevant.

**Comment by Daniel15** [comment]
Thanks! I actually just got a code signing cert for Yarn from DigiCert as well. I'm glad they're still using regular certificate files because it means I don't have to change Yarn's signing process just yet 😃
