### ISSUE TITLE
assert node can be compiled as static / dynamic libraries

### ISSUE THREAD

**Issue by refack** [nodejs/build#879]
Refs: https://github.com/nodejs/node/issues/14158

At present our embedding story is very fragile since there is no CI job that asserts that the code can even be compiled at static / dynamic library (let alone validated with the test suite). There are also other build time configurations that aren't continually asserted (esp. `--without-intl` and `--without-ssl`).

I suggest adding the following (ordered according to my own biased priority):
1) add a daily job to just compile with `--shared` on linux + windows + macOS
2) add a daily job to just compile with `--enable-static` on linux + windows + macOS
3) add a daily job to build with `--without-ssl` and run tests on full matrix
4) add a daily job to build with `--without-intl` and run tests on full matrix

P.S. I'd be happy to work on those, but I need access.

**Comment by mhdawson** [comment]
I believe 1 and 2 should run on the full matrix as well.

I've been talking to @yhwang who is going to help get some testing in place for the shared library case, but a first step of a job doing compilation would be good.

I wish there was a way other than just cloning all of the existing jobs (as there are a lot of them) to get coverage across the full matrix.

**Comment by refack** [comment]
Maybe this could be parameterized?

**Comment by mhdawson** [comment]
@refack do you need anything more than us creating a job you can start with ?

**Comment by joaocgreis** [comment]
@refack I believe this will be good to build upon: https://ci.nodejs.org/view/All/job/refack-node-test-library/ can be set to run periodically when done.

At some time it might be a good idea to include a job (or multiple) in test-commit to test some of this, so I also cloned the linuxone job so you can take a look and perhaps explore this. https://ci.nodejs.org/job/refack-test-test-commit/

Let me know if you have trouble accessing.

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.

**Comment by refack** [comment]
Superseded by https://github.com/nodejs/build/pull/992 and related Jenkins work
