### ISSUE TITLE
Use ccache 'everywhere'

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/build#88]
I don't see the point of recompiling v8 for every new PR -- so I'd like to suggest we install ccache on all our slaves. Lets discuss here. I imagine a PR containing snippets for Jenkins, updates to ansible scripts and possibly init scripts. 

I've successfully tried it on FreeBSD and SmartOS, so the only missing architecture would be Windows which would require mingw.

**Comment by jbergstroem** [comment]
FWIW, @rvagg is already busy deploying this on newer buildbots :+1:

**Comment by wblankenship** [comment]
I've never used ccache but googling gave me this comforting description:

```
The most important aspect of a compiler cache is to always produce exactly the same output that the real compiler would produce. This includes providing exactly the same object files and exactly the same compiler warnings that would be produced if you use the real compiler. The only way you should be able to tell that you are using ccache is the speed.

ccache has been coded very carefully to try to provide these guarantees. However, if you experience any bugs, please report them.
```

Assuming it produces the same output, I don't see a reason why we shouldn't do this.

**Comment by jbergstroem** [comment]
We run ccache pretty much everywhere nowadays. I'll run through the bots and see what's left. I think the OS X one still doesn't use ccache and Windows is left out for lack of support.

**Comment by rvagg** [comment]
does ccache support llvm & OSX? I can put it on the OSX machines but I didn't think it supported it.

**Comment by jbergstroem** [comment]
@rvagg neither should be a problem (I'm running it on my desktop for iojs/nodejs):
```
$ ccache -s
cache directory                     /Users/jbergstroem/.ccache
primary config                      /Users/jbergstroem/.ccache/ccache.conf
secondary config      (readonly)    /usr/local/Cellar/ccache/3.2.1/etc/ccache.conf
cache hit (direct)                  3759
cache hit (preprocessed)             227
cache miss                          3066
called for link                       50
called for preprocessing             486
compile failed                         1
couldn't find the compiler            23
unsupported source language          123
no input file                         96
files in cache                      4242
cache size                         879.3 MB
max cache size                       1.0 GB
```

Just install through homebrew or similar and add it to path. Should "Just Work" (famous last words).

**Comment by jbergstroem** [comment]
The centos machines seems to lack ccache as well. I'll see what I can do.

**Comment by jbergstroem** [comment]
Mission accomplished
