### ISSUE TITLE
Tracking issue: Change 4 Windows 2008 machines to Visual Studio 2017

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#883]
All of our Windows 2008 test machines have Visual Studio 2013 installed: This ensures that the `test-addons` tests are run with VS2013, effectively testing VS2013 simultaneously with Windows 2008.

However, support for VS2013 was completely dropped in Node 9, but we still need to test Windows 2008. So, I plan to change 4 machines to the latest VS2017 and leave only 2 machines with VS2013 for LTS testing.

The current setup is already causing issues in https://github.com/nodejs/node/pull/15362, so I plan to move forward very soon unless there are objections.

Ref: https://github.com/nodejs/node/issues/13372
Ref: https://github.com/nodejs/node/pull/14764
Fixes: https://github.com/nodejs/node/pull/15362

**Comment by joaocgreis** [comment]
cc @refack @kunalspathak FYI

**Comment by refack** [comment]
Refs: https://github.com/nodejs/node/pull/13911 (I forgot about that)

**Comment by joaocgreis** [comment]
Done.

Also moved x86 testing to Windows 2012, because this leaves us with few Windows 2008 with each compiler.
