### ISSUE TITLE
ccache failure on ARM ODroid - out of memory

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#884]
https://ci.nodejs.org/job/node-test-commit-arm/12073/nodes=ubuntu1604-arm64_odroid_c2/console

```
ccache: error: x_calloc: Could not allocate 40 bytes
```

Opening so we can keep an eye on it in case is re-occurs.

**Comment by mhdawson** [comment]
Seems to be a persistent problem: https://ci.nodejs.org/job/node-test-commit-arm/12078/nodes=ubuntu1604-arm64_odroid_c2/console

@rvagg can you take a look ?

**Comment by bnoordhuis** [comment]
Still happening FWIW: https://ci.nodejs.org/job/node-test-commit-arm/12177/nodes=ubuntu1604-arm64_odroid_c2/console

Can it be taken offline until it's fixed?

**Comment by gibfahn** [comment]
Happy to take it offline if it's one machine, but if they're all having this problem then that's not really an option. 

The one @bnoordhuis posted was `test-mininodes-ubuntu1604-arm64_odroid_c2-2`. I've taken it offline, we'll see if the issue crops up again.

ping @rvagg

**Comment by bnoordhuis** [comment]
I've seen `g++: internal compiler error: Killed (program cc1plus)` a few times recently.  Probably the same OOM issue.

https://ci.nodejs.org/job/node-test-commit-arm/12880/nodes=ubuntu1604-arm64_odroid_c2/console

**Comment by rvagg** [comment]
I've updated and rebooted those C2 machines. They've been running for a lot longer than they normally do, we tend to have a lot of trouble with them. There were some `<defunct>` processes on there but nothing taking up much memory that would explain this.

**Comment by MylesBorins** [comment]
was getting the internal compiler error messages today and it was quite confusing while doing the release, should we take these boxes offline again?

https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu1604-arm64_odroid_c2/13015/

**Comment by maclover7** [comment]
Moving to more general odroid_c2 issue: #1093
