### ISSUE TITLE
nvm won't install node - "Binary download from https://nodejs.org/dist/node-v6.11.3.tar.gz failed, trying source."

### ISSUE THREAD

**Issue by benedictify** [nodejs/build#890]
I keep getting this message: 

~ :> nvm install 6.11.3
Clang v3.5+ detected! CC or CXX not specified, will use Clang as C/C++ compiler!
Downloading https://nodejs.org/dist/node-v6.11.3.tar.gz...
curl: (3) [globbing] bad range in column 32
Binary download from https://nodejs.org/dist/node-v6.11.3.tar.gz failed, trying source.
grep: /Users/Benedict/.nvm/.cache/src/node-\033[01;31m\033[Kv6.11.3\033[m\033[K/node-\033[01;31m\033[Kv6.11.3\033[m\033[K.tar.gz: No such file or directory
Provided file to checksum does not exist.

I'm a newbie to all of this so forgive me if there is an obvious problem. But as it is I can't get nvm to work. It happens no matter which version of node I try to install. "nvm install node" or "nvm install stable" give this message: 

~ :> nvm install node
grep: brackets ([ ]) not balanced
awk: nonterminated character class v0.12.18
                                            input record number 1, file
 source line number 3
Version 'node' not found - try `nvm ls-remote` to browse available versions.

**Comment by benedictify** [comment]
~ :> nvm ls

->       system
node -> stable (-> N/A) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.4 (-> N/A)
lts/boron -> v6.11.3 (-> N/A)


and

~ :> nvm --version
0.33.4

**Comment by ljharb** [comment]
I think this issue belongs on https://github.com/creationix/nvm instead. Please file it there, and fill out the issue template, and I'll be happy to help you later tonight :-)

**Comment by benedictify** [comment]
I meant to put it there! Thanks

**Comment by ljharb** [comment]
→ https://github.com/creationix/nvm/issues/1615
