### ISSUE TITLE
Add custom URL for youtube channel

### ISSUE THREAD

**Issue by gdams** [nodejs/build#892]
I'm not sure if this is the right place to raise this but the Node.js YouTube channel is currently at https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ

We should be able to get a custom URL as I believe that we meet all of the criteria laid out [here](https://support.google.com/youtube/answer/2657968?hl=en-GB).

**Comment by gibfahn** [comment]
Sounds like it just needs someone with access to do it. I think @mhdawson has access (not sure who else).

**Comment by bnb** [comment]
FWIW, wanted to say that admin access is needed for this. Unfortunately `nodejs` is taken, but it has very low activity and may be able to be gotten. I've discussed this in the past with @zibbykeaton of the Node.js Foundation, and we weren't able to land on anything concrete. That said, I'd very much like to see this get updated.

Going to tag @nodejs/community-committee on this, as I think it's an important thing for us to do as a community with a rather large amount of video content.

**Comment by ZibbyKeaton** [comment]
Yeah, this was something that I tried to solve awhile back, but never heard back from YouTube help - I will send them another note on this. Here's where I got stuck in case anyone knows how to solve this problem: I created a custom URL for the channel: http://www.youtube.com/c/nodejs-foundation, however when you search it uses the other URL and just automatically populates that URL vs our custom URL.

**Comment by refack** [comment]
I just tested and https://www.youtube.com/nodejs-foundation works as well (and hence https://www.youtube.com/nodejs-foundation/live) but clicking on the channel name on any screen does bring up https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ

From what I've seen on the youtube site that's the best we can do. I'm closing this issue for now, feel free to comment or reopen if I'm wrong
