### ISSUE TITLE
AIX is full

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#895]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/998/nodes=aix61-ppc64/console

```
npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.
npm ERR! AIX 6.1
```

**Comment by refack** [comment]
Same circumstances as https://github.com/nodejs/build/issues/872 (ramdrive full).
Cleared ramdrive on both machines.
Now CitGM finishes - https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/MACHINE=aix61-ppc64/190/console

**Comment by gibfahn** [comment]
Okay, so I guess we should have CitGM clean up after itself.

**Comment by refack** [comment]
Two extra pieces of information.
* One CitGM run consumes ~9% of the ramdisk
  ```
  /dev/ramdisk0   10485760   9575536    9%      279     1% /ramdisk0
  ```
* `/ramdisk0` is owned by `root` and is mod 755, so Jenkins can't create `/ramdisk0/citgm`
  ```
  drwxr-xr-x    4 root     system          256 Sep 22 15:07 .
  ```
  hence cleanup should be done with `rm -Rf /ramdisk0/citgm/*`
