### ISSUE TITLE
Benchmarking data machine rsync issues

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#896]
Twice in the last week the benchmarking machine has become non-responsive due to a large number of rsync processes.

 I saw this once before and thought it might have been due to a stale cron job but I removed the job at that point and it continue to re-occur.

All I can think of now is that for some reason the job pulling the charts is doing something strange ? @rvagg ?

I can paste the rsync command with the sender info but wanted to make sure that is not sensitive first.

**Comment by mhdawson** [comment]
Happened again today

**Comment by mhdawson** [comment]
And again today.

@rvagg which machine is it that the website runs on and does the rsync from the benchmarking machine.  Next time this happens I'd like to look on that machine to see if that gives me any more information as to what is going on.

**Comment by mhdawson** [comment]
It seems to be related to something that is running at around 6:25

From one of the syslog files, and saw the same pattern in another one as well.

```
Oct  2 05:17:06 nodejs-data2 CRON[367]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct  2 06:17:07 nodejs-data2 CRON[2380]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct  2 06:25:03 nodejs-data2 CRON[2606]: (root) CMD (test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily ))
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357360] rsync invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357367] rsync cpuset=/ mems_allowed=0
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357372] CPU: 0 PID: 29303 Comm: rsync Not tainted 3.13.0-65-generic #105-Ubuntu
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357375]  0000000000000000 ffff880008a07a98 ffffffff81723f80 ffff88000206c800
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357379]  ffff880008a07b20 ffffffff8171e587 ffffffff81067a16 ffff880008a07af8
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357381]  ffffffff810c79dc 00000000000000a9 ffff88003fe1ee28 0000000000000000
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357384] Call Trace:
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357395]  [<ffffffff81723f80>] dump_stack+0x45/0x56
Oct  2 06:27:25 nodejs-data2 kernel: [1203087.357399]  [<ffffffff8171e587>] dump_header+0x7f/0x1f1

```

**Comment by mhdawson** [comment]
I was thinking it could be something started by anacron but I don't see a config file:

```
root@nodejs-data2:/etc/cron.daily# cat /etc/anacrontab
cat: /etc/anacrontab: No such file or directory
```

**Comment by rvagg** [comment]
it's all done on the web server, there ~are~ were two `rsync` commands in /etc/crontab, one that grabs charts and the other that grabs coverage data. They are both run every 15 minutes.

The problem here is the coverage data! It's now up at 21G (!! should we trim that?) and apparently it has trouble doing a full scan of that in 15 minutes so they start to overlap and over time they slow each other down and then just lock the server up.

So what I've done, aside from a `killall rsync` on the benchmarking server, is implement a lock-file for the rsync so it won't be run if there's an existing one being run. Checkout #904 and review it for me, that's what's on the server now.

**Comment by mhdawson** [comment]
Just reading this now.  Trimming the coverage data probably makes sense, although maybe we can just stop the rsync for the older directories, unless its causing space issues on the web server.

Today I don't seem to be able to get into the machine at all. Trying to reboot ...

**Comment by mhdawson** [comment]
Once I get back in I'll move the older coverage data to a different directory as a short term solution.

**Comment by mhdawson** [comment]
#904 looks good and I've manually trimmed the data for now.  Will think a bit more about what makes sense in terms of how long we keep the data available.

**Comment by rvagg** [comment]
@mhdawson we could remove the `--delete` from the rsync and then just keep it trimmed on the benchmark server but keep historical on the web server. We then can at least manage space issues in one place and won't have the overhead for rsync. Maybe a cron job on the benchmark server to prune it to only the last couple of days.
