### ISSUE TITLE
CentOS 5

### ISSUE THREAD

**Issue by Trott** [nodejs/build#898]
Hi, @nodejs/build friends.

* CentOS 5 is an EOL operating system. See https://lists.centos.org/pipermail/centos-announce/2017-April/022350.html

* It has caused problems in CI at least once, resulting in @mcollina needing to make a test more complicated than it was. See https://github.com/nodejs/node/pull/15520.

* IIUC, it is not a supported operating system. See https://github.com/nodejs/node/pull/14795.

Given all of that, at what point do we remove it from Ci? Is this sort of thing documented anywhere? Is the Build WG the right collection of people to decide?

(Apologies in advance if this has all ben discussed already, which I think it has.)

**Comment by rvagg** [comment]
We are still building 4 and 6 binaries with CentOS 5 and we can't change that so we should continue to support it there, it's unlikely to cause too much trouble with the small incremental changes going in to 4 and 6, especially when 6 heads into Maintenance. CentOS6 is used for binaries of 8+.
Another problem we have is that we can't even deploy new CentOS5 machines so we're stuck with the ones we have for the life of 6. If we were to need to replace them for whatever reason then we'd have to hack together some workaround like a Docker container or a VM in a VM or some other hackery.
I'm +1 on removing it from the 8+ test mix though since we don't rely on it, leaving it for <8 test runs. Any objections to doing this since it's causing some grief?

**Comment by Trott** [comment]
@rvagg If I'm understanding you correctly, we can't remove CentOS 5 machines completely until Node.js 6.x is unsupported which won't be until April 2019. Is that right? Yikes! But, yeah, I get it.

**Comment by rvagg** [comment]
yerp, that's correct, kind of tied ourselves to a bit of a donkey with that one but it's a bit hard to change now

**Comment by gibfahn** [comment]
>I'm +1 on removing it from the 8+ test mix though since we don't rely on it, leaving it for <8 test runs. Any objections to doing this since it's causing some grief?

We should definitely do this.

**Comment by refack** [comment]
Seems like if push comes to shove we can at least provision a new CentOS5 machine on AWS (either a comunity AMI or [install our own](http://www.nixhat.com/2011/01/create-custom-centos-5x-ami-page1/))

**Comment by Trott** [comment]
Another CentOS 5-only flaky (and thus a probable argument for removing CentOS 5 from CI): https://github.com/nodejs/node/issues/14982

**Comment by gibfahn** [comment]
Okay, so I've replaced this code in https://ci.nodejs.org/job/node-test-commit-linux : 

```bash
# clang is only supported in Node versions 7 and lower
MAJOR_VERSION=`cat src/node_version.h |grep "#define NODE_MAJOR_VERSION" | awk '{ print $3}'`
RUN_TESTS="RUN"
echo $SMARTOS_VERSION
if [[ "$nodes" =~ ubuntu1204 && ${MAJOR_VERSION} -gt 7 ]]; then
  RUN_TESTS=DONT_RUN
  SKIP_MESSAGE="ubuntu1204 is not supported for version 8 and above, skipping"
elif [[ "$nodes" = fedora22 && ${MAJOR_VERSION} -gt 7 ]]; then
  RUN_TESTS=DONT_RUN
  SKIP_MESSAGE="fedora22 is not supported for version 8 and above, skipping"
fi
```

```bash
# clang is only supported in Node versions 7 and lower
MAJOR_VERSION=`cat src/node_version.h |grep "#define NODE_MAJOR_VERSION" | awk '{ print $3}'`
RUN_TESTS="RUN"
echo $SMARTOS_VERSION
if [[ ${MAJOR_VERSION} -gt 7 && "$nodes" =~ 'ubuntu1204|fedora22|centos5' ]]; then
  RUN_TESTS=DONT_RUN
  SKIP_MESSAGE="$nodes is not supported for version 8 and above, skipping"
fi
```

Please let me know if this is wrong!

**Comment by refack** [comment]
"if" sample:
https://ci.nodejs.org/job/node-test-commit-linux/12908/nodes=centos5-32/console
```
centos5-32 is not supported for version 8 and above, skipping
```
"else" sample:
https://ci.nodejs.org/job/node-test-commit-linux/12910/nodes=centos5-32/parameters/
```
python ./configure 
creating ./icu_config.gypi
* Using ICU in deps/icu-small
...
```
SGTM
