### ISSUE TITLE
Meeting this week

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#901]
The foundation calendar shows a meeting for us this week.

I can't make it due to travel to NI.  I suspect many other people will be affected as well.

We can either move to next week or skip until the next one.

**Comment by gibfahn** [comment]
Moving to next week sounds good.

👎 to indicate that I wouldn't be able to make the meeting, not that I disapprove of the issue btw.

**Comment by joaocgreis** [comment]
Moving or skipping both sound good to me.

@nodejs/build

**Comment by refack** [comment]
I'm home, so I'm ok with whatever...

**Comment by rvagg** [comment]
OK, I guess it's off then! That's fine. I'm available next week if we want to shift but if it's not in the calendar I may not remember!

**Comment by gdams** [comment]
I'm good with either week

**Comment by gibfahn** [comment]
@mhdawson can you update the calendar entry? Once that's done we can close this in favour of https://github.com/nodejs/build/issues/902.

**Comment by mhdawson** [comment]
Closing as meeting was held.
