### ISSUE TITLE
Build WG Meeting October 12 @ 10 PM UTC

### ISSUE THREAD

**Issue by gdams** [nodejs/build#902]
### When

Oct 12, 2017 10 PM UTC - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20171012T22&p1=1440)

### Where
- [Hangouts on Air, for participants](https://hangouts.google.com/hangouts/_/ytl/hWIYjh1xCx6xMT_pHYhdzJxLl6gVzZtRasf_GYfAfcU=?eid=100598160817214911030)
- [Link for those who want to watch](https://www.youtube.com/watch?v=miiov1RzXk8)
- [Events page](https://www.youtube.com/my_live_events?filter=scheduled)
- [Minutes document](https://docs.google.com/document/d/1Av6B74HokoewMPaziEncRFVLkqnbUCKoa56yLmCXrVU/edit#)
- [Previous meeting](https://github.com/nodejs/build/issues/875)

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda) and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

* assert node can be compiled as static / dynamic libraries [#806](https://github.com/nodejs/build/issues/879)
* tmp dir needed on ubuntu 1604 and fedora23 #873

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by Trott** [comment]
I used 😕 for "I might be able to make it."

(Nit: Change `Sep` to `Oct` in the issue text.)

**Comment by joaocgreis** [comment]
I see this will be on a Thursday instead of Tuesday as usual. I can attend this one, but if the intention is to keep on Thursdays I won't be able to attend after DST ends.

**Comment by gibfahn** [comment]
>but if the intention is to keep on Thursdays

I think this is just a one-off change due to Node Interactive.

**Comment by piccoloaiutante** [comment]
This is still a bit late for me (midnight), so I'll skip it.

**Comment by MylesBorins** [comment]
Can you please add https://github.com/nodejs/build/issues/873 to the agenda

**Comment by mhdawson** [comment]
It was a one-off change.

**Comment by mhdawson** [comment]
I created the hangout but I'm now only 50% likely to be able to make it.  Hoping we have somebody else who can start/run the hangout as even if I make it I won't be in a good place to be making sure the hangout is up and running.

**Comment by MylesBorins** [comment]
I unfortunately can't make it

**Comment by rvagg** [comment]
Doh! Sorry, just saw this conflicting with another meeting I have in this slot. Won't be able to make it.

**Comment by mhdawson** [comment]
link for attendees: https://hangouts.google.com/hangouts/_/ytl/hWIYjh1xCx6xMT_pHYhdzJxLl6gVzZtRasf_GYfAfcU=?eid=100598160817214911030

**Comment by joaocgreis** [comment]
Minutes document: https://docs.google.com/document/d/1Av6B74HokoewMPaziEncRFVLkqnbUCKoa56yLmCXrVU/edit?usp=sharing

**Comment by refack** [comment]
RE using "projects" as task lists:
I've created two projects "action items" - https://github.com/nodejs/build/projects/1
and "access" https://github.com/nodejs/build/projects/2
AFAICT all "access request" issues are triaged on the access board. The "action items" board is more complicated. Both are naïve and arbitrary, so your feedback is appreciated. 

H/T @MylesBorins
