### ISSUE TITLE
FR: symlink to latest nightly

### ISSUE THREAD

**Issue by refack** [nodejs/build#908]
(blahblahblah ***Windows*** blahblahblah ***2.5 hour build***) turns out I use the nightlies fairly frequently, but https://nodejs.org/download/nightly/ is unstructured, and even requires a tiny bit of parsing for automation. Could we create a symlink to the latest nightly?

**Comment by joaocgreis** [comment]
The compile jobs now archive artifacts - this will use some disk space in the CI host but should not be an issue.

Having the nightlies latest link might take some work, I suspect adding support to https://github.com/nodejs/nodejs-latest-linker and testing it well.

**Comment by rvagg** [comment]
latest-linker uses simple sorting to figure out the latest. One reason I didn't add nightly symlinks in the first place is that it's technically possible to have them out of order, two with the same date but commits sorting differently. But that'd only happen if we had some weird extended compile-duration problem with them or they were manually triggered so I guess it's not a big deal.
The other reason is, latest what? There are usually multiple branches going on in there, do we just do the latest master?

**Comment by joaocgreis** [comment]
>  possible to have them out of order, ... I guess it's not a big deal.

I agree.

> The other reason is, latest what? There are usually multiple branches going on in there, do we just do the latest master?

What makes sense to me is having exactly the same as for releases. `latest-v8.x` would be the nightly generated from `v8.x-staging`, `latest-v9.x` would be `master` now and become `v9.x-staging` at some point. `latest` would always be `master`, we could even call it `latest-master` instead of just `latest` (if the code for distinguishing nightlies from releases is easy enough, else just ignore this for now).

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
