### ISSUE TITLE
Short term cleanup of coverage data

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#909]
As per https://github.com/nodejs/build/issues/896 the size of the coverage data was causing issues for the rsync from the benchmarking machine to the web server.  

We'll come up with a longer term solution but for now my plan is to move the data to a different directory to avoids the large copies. 

Once thing I'm going to have to see is if we can avoid the copies while at the same time still taking advantage of the data that is already available on the web server machine.

**Comment by mhdawson** [comment]
hmm, looks like the rsync to the web server is destructive in that it removes data which is not in the source.  I'm going to restore a bit more history.

**Comment by mhdawson** [comment]
Actually I was fooled as due to the recent problems some results were not copied onto the benchmark data machine.  Older ones are ok...

**Comment by maclover7** [comment]
ping @mhdawson is still needed?

**Comment by BridgeAR** [comment]
Ping @mhdawson

**Comment by mhdawson** [comment]
We still need to add some automated cleanup but for now I'll close this.
