### ISSUE TITLE
Where to put infra contacts

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#913]
We have contacts with our infra providers (ex Cloudflare) which I don't think we have captured anywhere.

I know we don't necessarily want to put people's email info in the public repo but we should probably add to either the secrets repo or possibly build-private.  build-private has broader access and might make sense so more people to could reach out to the providers when we are having problems

As an alternative we could build a matrix of who in the build group has links to each provider and make sure we have enough people to cover each of them.  We should them probably document this matrix in the repo.

@rvagg what do you think ?

**Comment by joaocgreis** [comment]
Contacts are on the secrets repo in `build/infra/admin_logins.md`.

**Comment by joaocgreis** [comment]
There are no contacts there for Cloudflare, but there are for other providers so the Cloudflare section should probably be updated.

**Comment by jbergstroem** [comment]
I just added contact info to Cloudflare. Closing.

**Comment by mhdawson** [comment]
@jbergstroem thanks.
