### ISSUE TITLE
Have Rod walk rest of build team through Cloudflare setup

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#915]
I would be good to have @rvagg walk the rest of the build team through the Cloudflare setup so that we are better able to help document and resolve issues.

We can possibly schedule this for the next meeting.

**Comment by jbergstroem** [comment]
I can be part of this too.

**Comment by rvagg** [comment]
👍

**Comment by gibfahn** [comment]
And also take copious notes in the meeting which can then go into a doc somewhere.

**Comment by mhdawson** [comment]
Ok, lets plan to include this in the agenda for the next meeting.

**Comment by refack** [comment]
Done https://youtu.be/c2X8R50SR0w?t=2281
(Thanks @rvagg 💐)
