### ISSUE TITLE
now: PI incident

### ISSUE THREAD

**Issue by refack** [nodejs/build#917]
From IRC - http://logs.libuv.org/node-build/2017-10-14#02:59:41.488

Time | user | message
-- | -- | --
21:11:17 | jasnell | Ping Build Folk... https://ci.nodejs.org/job/node-test-binary-arm/10874/ looks like one of the arm wheezy bots is dead
21:11:21 | jasnell | failing consistently
02:59:41 | Trott | rvagg: ^^^^^^^
03:00:42 | Trott | Looks like it's spread to all the Pi builds?
03:01:05 | Trott | https://www.irccloud.com/pastebin/2vnd9sWs/
03:01:15 | Trott | (https://ci.nodejs.org/job/node-test-binary-arm/10886/RUN_SUBSET=addons,label=pi1-raspbian-wheezy/console)
03:01:26 | Trott | Looks like NFS or other file system failure?
03:23:12 | rvagg | Looking
03:32:12 | rvagg | ahh, "No space left on device"
03:32:37 | rvagg | jasnell's first failure had only the Pi1's failing because the 2's and 3's finished fast enough and the 1's were still running when it started to fill up too much
03:32:52 | rvagg | need to figure out why it's taking up so much space though
03:38:27 | rvagg | joaocgreis: node-test-binary-arm/.git is getting really big on a couple of these, in the order of 12G, can you check what's going on there, also could you drop some notes in here about where/what you're looking at? I really feel clueless on this and am not sure how I'd go about fixing it if you weren't around
03:42:32 | rvagg | ok, I've cleaned out the workspaces on all of the test pi's, this might create some warmup challenges on the next few runs so I'll kick off a master test job now to help with that
05:17:57 | Trott | Thanks, rvagg!
05:20:41 | Trott | Getting build failures on Pi with `error: bad index file sha1 signature` and `fatal: index file corrupt`. See https://ci.nodejs.org/job/node-test-binary-arm/10891/RUN_SUBSET=6,label=pi3-raspbian-jessie/console for an example.
05:21:23 | Trott | rvagg: Regarding ^^^^ would it make sense for me to take the failing ones offline or is it unlikely to be host-specific? (I guess I can wait a while and see if there's a correlation to hosts or not...)
05:24:40 | Trott | Seems to definitely correlate to test-requireio_williamkapke-debian8-arm_pi3-1 at least. Taking that one offline. rvagg
05:32:56 | rvagg | Trott: ok, yah take them offline when you see any kind of pattern and let me know so I can pull them out, do a destructive test on the SD card and reprovision with or without a replacenent.
05:33:47 | rvagg | Could still be related to the disk full. The delete took quite a while for all ~100G so maybe we got stuck midway and it corrupted.
06:49:37 | Trott | rvagg: I just took test-requireio_securogroup-debian7-arm_pi1p-1 offline too. Example failure there is https://ci.nodejs.org/job/node-test-binary-arm/10891/RUN_SUBSET=3,label=pi1-raspbian-wheezy/console:
06:49:56 | Trott | https://www.irccloud.com/pastebin/R7VuzNQl/
15:39:48 | joaocgreis | rvagg some notes then: re the pis: there is git-rpi-clean to clean the workspaces weekly. I had it running daily but could not keep up with pis going offline, the jenkins backlog was getting huge, so I changed it to weekly. If someone else in the wg notices a `git-rpi-clean` stuck in the work queue, please abort it and update the job to not run on that worker. When someone brings a pi back (usually rvagg or me
15:39:48 | joaocgreis | I guess), please update the job to run on it again.
15:40:03 | joaocgreis | I've updated the job to run on everything and am running it now, but it might take a while because there are node-test-commit running
15:40:27 | joaocgreis | I mean, to run on every pi
15:41:56 | joaocgreis | Also note it does move then delete, to do something like atomic delete and not leave corrupted git repos if it aborts or fails (sometimes deleting files fail, possibly because of nfs)
15:42:36 | joaocgreis | not sure if we should document this somewhere, the process might still evolve.. perhaps I should add a note about this to the onboarding?
15:47:42 | joaocgreis | also one note about checking jobs: those of us with infra access can grep all the jenkins jobs configs, so anyone: feel free to ping us if you want to make sure something is not being used anywhere or configured the same for all jobs or something like that
15:48:14 | joaocgreis | Trott: when you see that, don't hesitate to mark as offline right away and figure out if it's host related later (if the failures stop, it probably is). We have many pis, so even with many offline the jobs will still run (even if much slower) and not fail, which is better. Thanks for noticing these things quickly and acting!

**Comment by refack** [comment]
on `test-requireio_securogroup-debian7-arm_pi1p-1` I did the following:
* `git fsck` in `/home/iojs/.ccache/node.shared.reference`
* run the full `git fetch --no-tags file:...` in `/home/iojs/build/workspace/node-test-binary-arm`
* went to https://ci.nodejs.org/computer/test-requireio_securogroup-debian7-arm_pi1p-1/ to bring it back on-line, but it was already.

**Comment by joaocgreis** [comment]
@refack was this just to make a log or is something still not good?

**Comment by refack** [comment]
Just to log it, and document the conversation (that's why I closed it)

**Comment by gibfahn** [comment]
>Just to log it, and document the conversation (that's why I closed it)

We should do this more often if possible, Github logs are much easier to search than IRC IMO.
