### ISSUE TITLE
Validate "new" Ansible scripts for Power and add step to update to Java8

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#919]
We recently manually updated the Power machines so that they used java8. (See https://github.com/nodejs/build/issues/775)

I'm also not sure we have validated the "new" ansible scripts on for the power machines we should:

- [x] create new PPC le machine
- [x] update "new" ansible sxripts to add step to add/use java8 for PPC le and be
- [x] test "new" ansible scripts
- [x] swap new machine in as test worker
- [ ] destroy old worker
- [ ] create new PPC be machine
- [ ] update "new" ansible sxripts to add step to add/use java8 for PPC be and be
- [ ] test "new" ansible scripts
- [ ] test "new" ansible scripts
- [ ] swap new machine in as test worker
- [ ] destroy old worker

**Comment by maclover7** [comment]
Just a note, this can be closed once #1075 and #1101 land.

**Comment by mhdawson** [comment]
This should stay open a bit longer as once those land we still have BE to update the ansible scripts for.

As an update, new ansible script has landed and there is one new work in the CI that is setting the compiler level.  Will leave over the weekend and if it looks ok then proceed to updating the other 2 workers and removing the logic in the job to only set the compiler level on the currently updated machine.

**Comment by maclover7** [comment]
ping @mhdawson -- can you confirm we're good here?

**Comment by mhdawson** [comment]
I tried to say in the last post that we will still need time to go through the other steps, these will take a while.

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
