### ISSUE TITLE
now: both ubuntu1604-intel-64 are down

### ISSUE THREAD

**Issue by refack** [nodejs/build#921]
As of 2:00 PM Monday UTC both `test-nearform_intel-ubuntu1604-x64-1` & 2 are unresponsive
```
d:\code\node$ ssh test-nearform_intel-ubuntu1604-x64-2
ssh: connect to host 92.51.196.115 port 22: Connection timed out

d:\code\node$ ssh test-nearform_intel-ubuntu1604-x64-1
ssh: connect to host 92.51.196.114 port 22: Connection timed out
```
https://ci.nodejs.org/label/ubuntu1604-intel-64/

**Comment by mhdawson** [comment]
Machines are back.  Ireland (where they are hosted) was hit by a category 3 hurricane around the time of the outage...
