### ISSUE TITLE
A new CI job for linting and doc tests

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#929]
Previously https://github.com/nodejs/build/issues/887 , also see https://github.com/nodejs/node/pull/16208#issuecomment-337581773

> We can also consider joining linter CI and doc CI in a new CI job. Previously, we used linter CI also for benchmark PRs, but now we tend to make benchmarks fully testable, so the separate linter CI job remains useful only for the docs with code fragments. We can as well make these two CI joined in some special light CI job for docs.

I would like to help get this one set up.

**Comment by gibfahn** [comment]
Okay, so how should we do this?

I guess options are:

1. Run doc linting as part of the regular linter job, and then just run the linter only on doc PRs.
2. Have a new job to run the doc linting, and then have an option in `node-test-pull-request` to only run linter + doc linter (off by default).

How do you run the doc linting btw? I should really know, but I'm not sure. Is it a `make` target?

**Comment by joyeecheung** [comment]
@gibfahn A make target indeded.See https://github.com/nodejs/node/pull/16377 (need to fix the shell quirks first)

**Comment by joyeecheung** [comment]
It's already up and running in https://ci.nodejs.org/job/node-test-pull-request-lite/. This can be closed now.
