### ISSUE TITLE
CI Embargo for OCT 24 security release

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#935]
We'll likely have to close off CI to general collaborators tomorrow for 24 hours so we can build + test the next security release.

/cc @nodejs/collaborators

**Comment by jbergstroem** [comment]
Closing, we weren't affected.

**Comment by jbergstroem** [comment]
Oops, was referring to the wrong issue. Reopening.

**Comment by MylesBorins** [comment]
Has someone been able to lock down CI? We are ready to test

**Comment by benjamingr** [comment]
@MylesBorins I have access to the CI at the moment - so I guess no.

**Comment by gibfahn** [comment]
@MylesBorins so who should still have access? I can change, but not sure who to leave.

**Comment by gibfahn** [comment]
![image](https://user-images.githubusercontent.com/15943089/31899444-7f4a801a-b813-11e7-8c97-8b3d781c25da.png)

This is the current access list

**Comment by MylesBorins** [comment]
Jenkins admin and release makes sense

**Comment by gibfahn** [comment]
![image](https://user-images.githubusercontent.com/15943089/31900672-24ebf168-b817-11e7-9d2d-b94aa5347c62.png)

Should be done.

**Comment by benjamingr** [comment]
Can confirm
<img width="520" alt="screen shot 2017-10-23 at 19 27 15" src="https://user-images.githubusercontent.com/1315533/31900744-3084a0b8-b828-11e7-8d76-492ba702d026.png">

Good luck :)

**Comment by MylesBorins** [comment]
A++

We should keep this open until we remove the embargo tomorrow

**Comment by jbergstroem** [comment]
@MylesBorins possibly file a bug over in the nodejs/node repo for visibility as well (link here to keep discussion in the appropriate place)?

**Comment by MylesBorins** [comment]
@jbergstroem done

**Comment by gibfahn** [comment]
>@MylesBorins possibly file a bug over in the nodejs/node repo for visibility as well (link here to keep discussion in the appropriate place)?

TBH I think an issue here cc/ing nodejs/collaborators (i.e. this issue) should be fine.

**Comment by MylesBorins** [comment]
The release is done... you can have CI back

**Comment by gibfahn** [comment]
Access should be restored, could someone confirm?

**Comment by gibfahn** [comment]
Actually I'm going to leave this open till I document how to disable access

**Comment by refack** [comment]
I'm closing and opening a doc issue, so that we can close this and remove of incident board

**Comment by gibfahn** [comment]
@refack did you open the doc issue?

**Comment by refack** [comment]
> refack did you open the doc issue?

did now https://github.com/nodejs/build/issues/949
