### ISSUE TITLE
Build WG meeting 2017-10-24 22:00 pm UTC

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#939]
### When

Oct 24, 2017 22:00 UTC - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20171024T22&p1=1440&ah=1)

### Where
- [Hangouts on Air, for participants](https://hangouts.google.com/hangouts/_/ytl/44AbiRBv8QKglTqxiGwCAdqq-6PIaYtRhjoWTkD1n7E=?eid=100598160817214911030)
- [Youtube stream, for viewers](https://www.youtube.com/watch?v=c2X8R50SR0w)
- [Events page](https://www.youtube.com/my_live_events?filter=scheduled)
- [Minutes document](https://docs.google.com/document/d/1MIvQa-Cruv2ypHJsamstBkNtzwOnuUANeSV6iDp7k2s/edit?usp=sharing)
- [Previous meeting](https://github.com/nodejs/build/issues/902)

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda)
and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

- suggestion: investigate a commit-queue solution [#705](https://github.com/nodejs/build/issues/705)
- tmp dir needed on ubuntu 1604 and fedora23 [#873](https://github.com/nodejs/build/issues/873)
- assert node can be compiled as static / dynamic libraries [#879](https://github.com/nodejs/build/issues/879)
- Have Rod walk rest of build team through Cloudflare setup [#915](https://github.com/nodejs/build/issues/915)
- doc: update intel text in providers list (meta: negotiating wording for donor descriptions & contributions) [#912](https://github.com/nodejs/build/issues/912)
- ansible: use gcc 4.9 on CentOS 6 [#809](https://github.com/nodejs/build/pull/809)
- Make it easier for people to join the Build WG [#941](https://github.com/nodejs/build/issues/941)

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by refack** [comment]
Could we talk a bit the option of adding people to the WG without direct ssh access, but more geared towards helping the Automating SIG? (Also about having some DevOps sandbox machines, and even a sandbox Jenkins)?

**Comment by gibfahn** [comment]
@refack will raise issue.

**Comment by gibfahn** [comment]
@joyeecheung and @maclover7, as prospective members it'd be great if you could attend, assuming you have time. I know it's a bit last minute.

We should probably extend the invitation to anyone in nodejs/automation who's willing (join if you'd like). However I'd like to make sure everyone in build is okay with that before inviting, so we can discuss at this meeting and plan for next time if no objections.

**Comment by refack** [comment]
> We should probably extend the invitation to anyone in nodejs/automation who's willing (join if you'd like). However I'd like to make sure everyone in build is okay with that before inviting, so we can discuss at this meeting and plan for next time if no objections.

IMHO we should first talk in the current format about changing the format...

**Comment by rvagg** [comment]
@nodejs/automation ping, anyone's welcome to join this meeting in ~45 mins and we can discuss how Build can best support Automation efforts and what an optimal relationship might be between the two groups.

**Comment by rvagg** [comment]
I might be late to this, I have a quick but important meeting scheduled shortly beforehand

**Comment by ev1stensberg** [comment]
@rvagg Could I get an invite?

**Comment by gibfahn** [comment]
@ev1stensberg someone should post a link to the hangout a couple of minutes before it starts.

Speaking of which, @mhdawson are you hosting today?

**Comment by mhdawson** [comment]
Link for participants: https://hangouts.google.com/hangouts/_/ytl/44AbiRBv8QKglTqxiGwCAdqq-6PIaYtRhjoWTkD1n7E=?eid=100598160817214911030

**Comment by maclover7** [comment]
not sure if meeting has started yet, but is not streaming on youtube

**Comment by refack** [comment]
We're "cat herding"

**Comment by refack** [comment]
on now
