### ISSUE TITLE
Expand download validation to validate existing of all platforms

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#940]
We seem to fairly regularly get reports like this one (often on ARM)

https://github.com/nodejs/node-v8/issues/19#issuecomment-338344697

We have a download validation job, but it currently does not fail if a platform is missing.

May be useful to add validation that downloads for all platforms exist.

@gdams since you did most of the work in the download validation script.

**Comment by refack** [comment]
AFAICT checking nightlies (and canary nightlies) at least, is blocked by https://github.com/nodejs/build/issues/908

**Comment by targos** [comment]
For canary nightlies, I don't think we should block the download if a platform is missing.

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
