### ISSUE TITLE
Make it easier for people to join the Build WG

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#941]
I've been trying for a while to work out how we can help lower the barrier to entry for this WG, and https://github.com/nodejs/TSC/issues/392 and the setup of the nodejs/automation team means now seems like a good time to suggest this.

### Proposal

Split the test-access part of Build membership (and access to the secrets repo) into a subteam of build (in the same way we currently do release-access and infra-access). Then we can add people to the Build WG without worrying about who they are.

**Comment by mhdawson** [comment]
Discussed in latest (and I think in earlier meeting), no objections.  Gibson to raise PR explaining approach.

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
