### ISSUE TITLE
Why do we pass "-std=gnu++0x" to the compiler?

### ISSUE THREAD

**Issue by targos** [nodejs/build#945]
Ref: https://chromium-review.googlesource.com/c/v8/v8/+/728026#message-a337cd5c8611b2408a8972deb3d20528b5845be1

It seems that we should pass `-std=gnu++11` at least. Unless we support compilers that don't have this option?

**Comment by targos** [comment]
`-std=c++14` would be even better and Clang supports it since version 3.4: https://clang.llvm.org/cxx_status.html

**Comment by targos** [comment]
Ref: https://github.com/nodejs/node/commit/e43c109891d

I'm going to try and change this option to see if CI can pass.

**Comment by targos** [comment]
CI: https://ci.nodejs.org/job/node-test-commit/13446/

I already see that LinuxONE does not support it.

**Comment by targos** [comment]
@nodejs/build

**Comment by gibfahn** [comment]
cc/ @joransiu @jbarz

**Comment by targos** [comment]
So, by looking at [this build](https://ci.nodejs.org/job/node-cross-compile/11850/label=cc-armv6/console), I see that we are still compiling with GCC 4.8. but we officially [stopped to support it for Node 8](https://github.com/nodejs/node/commit/d13a65ad68c429884434cdcd94c52b79a6d69717).

New CI with `-std=gnu++11`: https://ci.nodejs.org/job/node-test-commit/13447/

**Comment by refack** [comment]
RE migration to a newer version: we're trying to balance the new requirements (GCC 4.9 for example is a "soft" requirement) and still keeping the old configuration for LTS node versions.
Refs: https://github.com/nodejs/build/pull/809
Refs: https://github.com/nodejs/build/pull/797
Refs: 

1) Some old platforms (CentOS5 & 6) don't have well supported binaries of newer GCC. 
2) changing the global GCC changes the global `stdlib++` which requires the users to upgrade, so we're trying figure out way to either have it side-by-side, or have multiple build-bots
3) getting prebuilt toolschains for 32bit environments is also a challenge. https://github.com/nodejs/build/issues/885

**Comment by targos** [comment]
From https://chromium-review.googlesource.com/c/v8/v8/+/728026#message-697b6bb5ae15281bdd7c9b457aa75b75ef8a14ea:

> C++14 is generally allowed in chromium (https://chromium-cpp.appspot.com/), hence also in V8. The only restriction is that it has to compile in GCC 4.8 (and all the other compilers we use on the bots). GCC 4.8 only supports C++11, so all code used by this compiler has to compile with c++11.

If CI is green, I'll start a new run with `-std=gnu++11` with the `canary` branch. If it is still green, I'll submit a PR to core.

**Comment by targos** [comment]
Canary build: https://ci.nodejs.org/view/MyJobs/job/node-test-commit-node-v8/193/

**Comment by targos** [comment]
It's looking good on osx with `-std=gnu++14`.

Here is a proposition that should work:
- Build with `-std=gnu++11` in GCC
- Build with `-std=gnu++14` in LLVM (including osx and freebsd)

@refack do you think it's possible to modify `common.gypi` do achieve that?

**Comment by refack** [comment]
> @refack do you think it's possible to modify common.gypi do achieve that?

Yep, I'll make a PR

**Comment by refack** [comment]
https://github.com/refack/node/compare/master...higher-c++-ver-by-default

https://ci.nodejs.org/job/node-test-commit/13465/

For now I see that `freebsd10` is not happy - `error: invalid value 'c++14' in '-std=c++14'`

**Comment by bnoordhuis** [comment]
> changing the global GCC changes the global stdlib++

Right, that might be a problem.  _Technically_ it already matters if you compile with 4.8.2 or 4.8.3 (libstdc++ 6.0.18 vs. 6.0.19; 4.9 is 6.0.20) but yeah.

**Comment by fhinkel** [comment]
I know this is closed already, but I would very much like it if we could go up to GCC 4.9. We can't use a bunch of C++14 feature in V8, because then Node wouldn't compile anymore with 4.8.

**Comment by targos** [comment]
@fhinkel do you mind opening a new issue? IMO It's important that we arrive to a conclusion before the release of Node 10.
