### ISSUE TITLE
Improve interaction process with non-WG members

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#946]
This was briefly brought up during the 2017-10-24 WG meeting.

There should be a more documented process for non-WG members to interact with non-WG members. This mainly falls into two categories: reporting downtime/outages ("911") and opening tickets that require WG action. Currently (as far as I know), there is no official written procedure for reporters to follow.

Does it make sense to come up with a list of all potential reasons non-WG members would contact the WG (Jenkins machine down, can't connect to nodejs.org, etc.), and then come up with a list of steps (post in IRC, create a GitHub issue, etc.) the reporter can try? A possible idea discussed during the meeting was to create a status.nodejs.org website to show the current infrastructure state, although that might be a separate discussion.

cc @gibfahn, this is what I meant in https://github.com/nodejs/build/pull/942#issuecomment-339332286, sorry if I was being obtuse 😞

**Comment by mhdawson** [comment]
Sounds like a good idea to me.

**Comment by rvagg** [comment]
I'd like to see https://github.com/nodejs/build/projects/1 used as much as possible for triaging. Perhaps we could also start using build@nodejs.org for 911-style things too?

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
