### ISSUE TITLE
Access for targos to investigate https://github.com/nodejs/build/issues/945

### ISSUE THREAD

**Issue by targos** [nodejs/build#948]
Hi @nodejs/build. I would like to have temporary ssh access to a FreeBSD 10 machine to investigate compiler flags for https://github.com/nodejs/build/issues/945.

**Comment by gibfahn** [comment]
SGTM

**Comment by targos** [comment]
Actually I'm not sure I need it anymore.

**Comment by gibfahn** [comment]
Reopen if you do.
