### ISSUE TITLE
Add an overview to help newcomers understand how Build is laid out

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#950]
I think a very short desc of what the Build WG is and does, and how the CI is set up.

    permission groups
    job scripts stuck in Jenkins
    /ansible/ is future
    /setup/ is past
    bot / email / website / CI
    CI test vs release

**Comment by ghinks** [comment]
# More than a short description required.
Firstly thank you Gibson for the talk at Node Interactive. I have taken the time to re-watch the talk you gave on the build wg a few times. Mostly to make sure that I am not missing things. I also watched the Working group on you tube on the 24th Oct. 

Some of the things said during the during the talk need more attention if you want to be able to on board people and get them involved. I want to get involved and help but as mentioned in the talk, it is hard to know where to begin.

The mission is to 
- build
- test
- benchmark
- release
- host 

( from the talk given)

But it is not self evident how these things are actually being achieved. What I think would really help is to take the most plain vanilla case and show how

- show how it is being built
- describe what and how it is tested
- how it is bench marked
...

I think a concrete set of steps for one example would work wonders.

I would be delighted to get involved and even write these descriptions but there would have to be a bit of hand holding to begin with as I really could not work out how these things are done from the Build WG github repo and the talk.
But I'd be delighted to try.

**Comment by ghinks** [comment]
I would still like to get involved in some way with the process.

**Comment by rvagg** [comment]
mm, I'd like to see a fresh new intake of folks that can help keep our infra alive and happy (at a minimum), we seem to be getting a bit short. Do we think docs is what it's going to take? Are we too opaque right now?

**Comment by ghinks** [comment]
I'll be honest. Most folks kind of like the more **glamorous stuff**. But I actually quite enjoy seeing a good process ticking along. I think that docs alone will not do it. In most cases it is about attracting and keeping the correct people. 
I heard Gibson talk in Vancouver and thought I could **get involved** here as it would not distract from my day time node duties. But after listening to the call **I could not fathom a way into what was going on**. 
So I think it is about how you **on-board** people. They (we) are here to help but do not know how to start helping.

**I am still grateful. Node is putting my kids through school!**

Just reach out to me and I'll try to help

**Comment by rvagg** [comment]
Cool, we need to sort this out because I know there are lots of people out there like yourself (and me!) that enjoy this kind of thing and it can be as casual as you need it to be.

**Comment by maclover7** [comment]
Largely solved by https://github.com/nodejs/build/blob/master/doc/services.md, closing for now

**Comment by refack** [comment]
I'd rather we keep this open. Seems to me that `services.md` is only part of the information that needs to be documented.

**Comment by maclover7** [comment]
@refack what else needs to be included?

**Comment by refack** [comment]
From the OP
* ~permission groups~
* job scripts stuck in Jenkins (refack: improve visibility of job logic)
* /ansible/ is future -> /setup/ is past
* ~bot / email /~ website ~/ CI~
* ~CI test vs release~

Maybe some stuff should be added to the onboarding doc, but IMO this task is not completed, and closing the issue will "sweep that under the rug"

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
