### ISSUE TITLE
osx1010 appears to be out of space

### ISSUE THREAD

**Issue by apapirovski** [nodejs/build#953]
Last few CI runs have all failed with a similar message, see: https://ci.nodejs.org/job/node-test-commit-osx/13613/nodes=osx1010/console

**Comment by apapirovski** [comment]
Looks like this isn't the first time in recent history: https://github.com/nodejs/build/issues/899

**Comment by refack** [comment]
@apapirovski the acute symptom should be alleviated.

As for the chronic problem, AFAICT the main culprit is the `.npm` cache. I think we should move it into the CitGM workspace, and clear it after a CitGM run.
Any objections?

**Comment by gibfahn** [comment]
@refack where is that currently stored, `/home/iojs/.npm`?

We should definitely be setting all the npm storage directories to be inside the job workspace for the CitGM jobs (with the exception of the tmpdir on AIX, which goes in the `/ramdisk0` dir). I thought we already were.

**Comment by refack** [comment]
Yes `/home/iojs/.npm` altought now it seems like it's only 4G (just millions of files).
Still jobs are worse:
```
  0B    ./check-java-version
3.7G    ./citgm-smoker
3.4G    ./citgm-smoker-private
3.4G    ./gibfahn-test-npm
 42M    ./libuv-test-commit-osx
109M    ./node-inspect-continuous-integration
  0B    ./node-test-commit-osx
3.3G    ./node-test-npm
```

**Comment by gibfahn** [comment]
`3.4G    ./gibfahn-test-npm`

You can clear that one up 😁

**Comment by maclover7** [comment]
ping -- are there are any further steps that need to be taken here?

**Comment by gibfahn** [comment]
Should be good for now.
