### ISSUE TITLE
Install wrk on the benchmark machine

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#955]
Hi, it appears that the benchmark machine does not have wrk or autocannon installed so right now it does not produce meaningful results on the HTTP benchmarks (See: https://github.com/nodejs/node/issues/16557). I have seen https://github.com/nodejs/build/issues/821#issuecomment-321236906 but have not figured out how/where to update the ansible scripts for the benchmark CI machine, I guess alternatively one would need to ssh to that server and manually install the dependencies? Right now I would prefer using wrk over autocannon, so the things needs to be done are basically equivalent to:

```
apt-get install wrk
```

Let me know if there are things that I can help with.

**Comment by maclover7** [comment]
ping -- has this been done?

**Comment by maclover7** [comment]
Ref #868, looks like no Ansible playbook yet for benchmark machines. I am more than happy to help mentor and get this done if that helps at all, I've been doing a lot recently with the Ansible scripts :)

**Comment by mhdawson** [comment]
@maclover7 it would be great if you could help get the ansible scripts created.

In the end I manually added wrk so closing this issue.
