### ISSUE TITLE
Upgrade ci-release to latest Jenkins

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#957]
Simple TODO item that needs to be done when we're not under the crunch to get releases out.

There's a bunch of releases this week, including possibly [OpenSSL upgrades](https://github.com/nodejs/Release/issues/271) at the end of the week or early next. Doing this upgrade after the OpenSSL releases (if there are any) should be sufficient.

There's been some strange behaviour on ci-release that _may_ be fixed with an upgrade.

**Comment by rvagg** [comment]
I've just done this .... but run into some hiccups. I forgot to confirm that we had Java 8 installed on all the workers before I did it and now I suspect that's why we have some machines failing to come back online.

@joaocgreis these two haven't come back online and they're not in secrets/build/release/windows-servers.md, could you have a look and also update the secrets file please?

* release-rackspace-win2012r2-x64-1
* release-rackspace-win2012r2-x64-2

@mhdawson @gibfahn release-marist-zos13-s390x-1 is down, it doesn't have the nodejs_build_release key in it and you can just use nodejs_build_test (that should be fixed). /u/iojs/start.sh appears to say that it's running Java 8 but I don't _think_ that it's running atm. It's not connected to ci-release anyway. Probably borked when the server went down and it doesn't have a auto-restart mechanism? Hard to tell, it's an alien environment for me and I can't work out how to restart the service as the IOJS user. Could someone @ IBM work out how to breathe life back into this thing please?

**Comment by rvagg** [comment]
false alarm maybe, none of those machines seem to be in iojs+release anyway so not critical? I'll leave it up to you guys cause you've obviously been responsible for adding them and know best what to do with them.

**Comment by joaocgreis** [comment]
@rvagg those are the 2 new machines I'm getting ready for VS2017 releases, created them only to grab the secret. Just ignore them for now.
