### ISSUE TITLE
Both release Pi's keep on flaking out

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#958]
This has been happening for a while now, perhaps getting more regular. Both release Pi's just lock up and drop out of ci-release, causing problems with the release job and delaying armv6 builds. I haven't investigated their consoles when they do this, just restart. I'm pretty sure I've checked their SD cards recently, even replacing one of them, but I don't have good enough records to say for sure (I'm starting to keep records better on this). Removing the overclocking might be in order for these machines .. but that's just a guess.

**Comment by rvagg** [comment]
One was overclocked to 950 and the other to 900, I've turned them both down to 700. They're building a lot slower but stability is going to be more important. If this makes a difference to stability I might try bringing it back up a tiny bit and see how it goes.

**Comment by gibfahn** [comment]
Given that we're promoting the other builds and then coming back for the Pis, I'd say that makes stability even more important vs speed. Not overclocking SGTM.

**Comment by mhdawson** [comment]
I've also just enabled https://ci-release.nodejs.org/computer/release-devrus_mhdawson-debian7-arm_pi1p-1/

Will keep an eye on it as I think it was overclocked based on the earlier guidance

**Comment by rvagg** [comment]
happy with the machines for now, resetting the overclocking seems to have done the trick
