### ISSUE TITLE
JDK 1.7 on Ubuntu 10.04

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#96]
This is now a problem with Jenkins, we can't use 1.6 or we get network errors.

The best way I've found to get 1.7 onto these machines is with:

```
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java7-installer
```

But of course the "installer" requires you to say yes to an EULA so this might be a bit tricky to ansiblise but I'm sure there's a way.

Done manually for now but need to automate.

**Comment by wblankenship** [comment]
:+1: the webupd8team PPA is the best way I've found documented to install official java repos on ubuntu.

I did find this script in the wild for java 1.5, will probably work here as well. It appears the installer looks for the presence of a file to ensure you have accepted the EULA, if the install fails you create that file and try again.

```
DEBIAN_FRONTEND=noninteractive apt-get install -y java5-sun-jre || :
debconf 'echo SET shared/accepted-sun-dlj-v1-1 true; echo $(read) >&2'
apt-get install -y java5-sun-jre
```

**Comment by rvagg** [comment]
10.04 has been retired from our cluster so thankfully we don't need to care about this
