### ISSUE TITLE
Remove Ubuntu 12.04

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#961]
EOL in April of this year.

We have 3 machines, Host test-digitalocean-ubuntu1204-x64-1, test-digitalocean-ubuntu1204-x64-2 and test-rackspace-ubuntu1204_clang341-x64-1.

It's in 40 of our Jenkins jobs and 20 of those have the `ubuntu1204` and/or `ubuntu1204-clang341-64` label as nodes to be run on.

Is there a reason we're delaying removing this that anyone can think of? How about libuv? /cc @saghul

**Comment by gibfahn** [comment]
No reason not to remove IMO. On the other hand if they're not having issues is there a reason to remove them? I'd be tempted to leave them, and just remove them from any jobs that have issues with them. We can retire them when they become an annoyance to maintain.

**Comment by rvagg** [comment]
Yeah, I'm pretty OK with this approach. As long as (a) we can continue to keep them maintained and (b) we don't lose the infra cause we can't start a new Ubuntu 12.04 on any of our providers if we needed it.

**Comment by seishun** [comment]
Two reasons to remove:

1. Adds noise in Jenkins and the nodejs/build repo.
2. Uses an outdated version of gcc.

**Comment by gibfahn** [comment]
>Adds noise in Jenkins and the nodejs/build repo.
>Uses an outdated version of gcc.

Only if it fails. And if it fails then yes, time to remove.

**Comment by rvagg** [comment]
https://www.ubuntu.com/support/esm

> In April 2017, Ubuntu 12.04 LTS reached its end-of-life. For Ubuntu Advantage customers who can not upgrade to a newer version of Ubuntu Server, Canonical is offering Ubuntu 12.04 ESM (Extended Security Maintenance). ESM provides ongoing security fixes for the kernel and essential packages through April 2019.

Apparently this is working out really well for Ubuntu and they are expanding ESM to all LTS lines and expanding the range of packages they are supporting beyond just `main`. So perhaps we don't retire 12.04 just yet. I'm going to reach out to Canonical about this to see if we can get some rough idea of the audience size, or something that will help us.

**Comment by mhdawson** [comment]
Waiting on update from @rvagg, removing agenda tag until there is one.

**Comment by sam-github** [comment]
Closing as stale, but if anyone wants to take this up feel free to reopen.
