### ISSUE TITLE
Nightlies built by wrong workers for v10

### ISSUE THREAD

**Issue by joaocgreis** [nodejs/build#965]
(Links to `ci-release` will only work for people with access.)

Comparing [the last v9](https://ci-release.nodejs.org/job/iojs+release/2188/) with [the first v10](https://ci-release.nodejs.org/job/iojs+release/2194/), there are some discrepancies:

- AIX was not built
- Linux was built by `centos5` instead of `centos6`
- LinuxOne was not built

I've fixed this by landing the `NODE_MAJOR_VERSION` part of https://github.com/nodejs/build/issues/885#issuecomment-333627609 (thanks @gibfahn), testing in https://ci-release.nodejs.org/job/iojs+release/2196/. Changes diff [here](https://ci-release.nodejs.org/job/iojs+release/jobConfigHistory/showDiffFiles?timestamp1=2017-10-31_11-26-08&timestamp2=2017-11-01_18-56-33). SmartOS already had a similar mechanism with slightly different variable names, would be good to homogenize if someone finds the time. Since it is not broken and issues with bash tend to be tricky, I left it as is.

I will check the nightlies again tomorrow and close this issue.

I don't know if we should rebuild today's nightlies. Rebuilding releases causes trouble, and while no one should be depending on nightlies stability, there is not a huge pressing need since this will be fixed tomorrow. If someone has a stronger opinion, feel free to comment or rebuild.

cc @nodejs/jenkins-admins

**Comment by rvagg** [comment]
rebuilding nightlies doesn't cause problems, at least nobody has ever complained, so feel free to reuse the same commit & date to test nightly rebuilds
