### ISSUE TITLE
Remove ARM64 Ubuntu 14.04 X-Gene servers from CI

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#966]
These are test-requireio_xgene-ubuntu1404-arm64-1, test-requireio_xgene-ubuntu1404-arm64-2 and release-requireio_xgene-ubuntu1404-arm64-1. They were donated by ARM when ARM64 servers were first being prototyped. They are an early version of the AppliedMicro X-Gene chip/board in prototype boxes and they helped us get our ARM64 support up to first-class. They're noisy and not power efficient and take up space in my garage and I've migrated all of their important work elsewhere over time. The releases are now done on a CentOS 7 @ packet.net and have been for some months now, so the release machine is sitting idle. One of the others was running NFS and jump host duties for the cluster but both of those tasks are handled by a FreeBSD machine I have down there too.

So, the only value they add now is running tests on a different OS. We have CentOS7 and Ubuntu 16.04 handled by Packet.net and Scaleway were offering to add some redundancy to that (I haven't followed up). I don't know if there's much Ubuntu 14.04 ARM64 in the wild, if any, as the server platform has only really matured since 16.04 was out, 14.04 was for earlier prototypes (afaik). Also worth noting that CentOS7 gives us libc 2.17 (December 2012 era) compat, Ubuntu 14.04 only gives us 2.19 (February 2014 era). So historically we're better off with the new CentOS7 machines.

**Comment by refack** [comment]
+1

**Comment by rvagg** [comment]
Removed & retired, I'll hang on to the hardware for a little while just in case we decide this was a bad idea!
