### ISSUE TITLE
Ubuntu non-LTS strategy

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#967]
We're a bit behind on Ubuntu. We have solid coverage of LTS and we have 16.10 in the mix too.

16.10 was EOL in July and I'd like to remove it to free up resources. Since we have 16.04 in the mix I think we can afford to ditch Ubuntu non-LTS more freely than we're agreeing with Fedora (@ #962) which doesn't do LTS.

After freeing up 16.10, I'd like to add 17.10 in their place. This would skip 17.04 but it's EOL in January anyway so IMO we've missed that boat.

18.04 will be LTS so we'll hang on to that one longer obviously. Then by the time we get to 18.10 we could replace the 17.10 (EOL in July) machines with it.

Thoughts on Ubuntu non-LTS strategy?

**Comment by rvagg** [comment]
I've gone ahead and swapped 16.10 for 17.10.

**Comment by gibfahn** [comment]
+1 on the strategy of maintaining coverage of the latest non-LTS build, and all their supported LTS builds.

**Comment by mhdawson** [comment]
Make sense to me, latest non LTS + LTS supported version.

**Comment by bnoordhuis** [comment]
Has 17.10 been deployed yet?  I can reliably trigger a kernel lockup from cctest with the x86_64 4.13 kernel (both -generic and -lowlatency) that has been fixed in the mainline 4.13.11 kernel.

**Comment by rvagg** [comment]
@bnoordhuis yes, we've had 17.10 in the [node-test-commit-linux](https://ci.nodejs.org/job/node-test-commit-linux/) mix for a week now, green and looking OK.

```
$ ssh test-joyent-ubuntu1710-x64-1 uname -a
Linux test-joyent-ubuntu1710-x64-1 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ ssh test-joyent-ubuntu1710-x64-2 uname -a
Linux test-joyent-ubuntu1710-x64-2 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mhdawson** [comment]
@nodejs/build discussed in last meeting.  No objections.

**Comment by refack** [comment]
Renewed issue for 2019 - https://github.com/nodejs/build/issues/1668
