### ISSUE TITLE
Continue supporting Ubuntu 10.04 (Lucid)?

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#97]
It reached EOL at the end of April so it's no longer supported by Ubuntu, do we just remove it from CI completely?

It's nice to have these older Linuxes around because it exposes some interesting problems, particularly for libuv, but if it's not going to get updates and if nobody's really going to use it in the wild then is there justification to keep it around?

**Comment by bnoordhuis** [comment]
I would say it can go.  The baseline is centos 5 / linux 2.6.18 and that shakes out most of the bugs.

**Comment by jbergstroem** [comment]
+1

**Comment by rvagg** [comment]
attn @iojs/collaborators: Ubuntu 10.04 is going to be pulled from CI because it's now beyond EOL. I don't expect this to impact you in any way but just so you're aware.

**Comment by Starefossen** [comment]
Ubuntu 10.04 CI configurations has been removed though #123 (f464251).
