### ISSUE TITLE
incident: node-test-commit is acting janky

### ISSUE THREAD

**Issue by refack** [nodejs/build#970]
* Several jobs report as Aborted even though they simply failed.
* I started a job that didn't register, but did trigger sub jobs (in screenshot a sub referencing 13694 that didn't exist for a while):

![screenshot 2017-11-02 004](https://user-images.githubusercontent.com/96947/32358608-d4246648-c01d-11e7-822b-0fc1cffb47da.png)

![image](https://user-images.githubusercontent.com/96947/32358637-263a31ce-c01e-11e7-8282-05468bdee96d.png)

I cleared the workspace and re-saved the job config, now everything seems fine 🤷‍♂️

**Comment by rvagg** [comment]
@refack did you mean to close this? could be to do with me messing with swapping ubuntu1610 for ubuntu1710, also changing the fedora config. Might need to restart Jenkins sometime to flush out all of these config changes that I've made on disk and requested a "reload" from the running Jenkins instance—I don't really trust that Jenkins does the right thing with that.
