### ISSUE TITLE
Delete unused labels

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#977]
There a few labels that have zero open or closed issues attached to them, would like to delete if okay, especially the CTC ones:

- `benchmarking-review` (`#0e8a16`)
- `ctc-agenda` (`#d4c5f9`)
- `ctc-review` (`#fef2c0`)
- `duplicate` (`#cccccc`)
- `wontfix` (`#ffffff`)

**Comment by rvagg** [comment]
sgtm

**Comment by gdams** [comment]
Is there any harm in having `duplicate` and `wontfix` labels? I know that we can always recreate them later.

**Comment by maclover7** [comment]
¯\_(ツ)_/¯ We can always readd them later on if we need them... my guess was to remove since they haven't been used yet.

**Comment by maclover7** [comment]
Removed for now, can always be added again later (names and colors are above).
