### ISSUE TITLE
http-parser and github-bot

### ISSUE THREAD

**Issue by maclover7** [nodejs/build#986]
Having issues when post-build-status-update is POSTing to github-bot:

```
21:11:00.803Z ERROR bot: Error while updating Jenkins / GitHub PR status (req_id=574bb8af-2745-47e3-b416-9b8d9f7f0371, pr=388, job=test, status=success)
    err: {
      "code": 404,
      "status": "Not Found",
      "message": "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/statuses/#create-a-status\"}"
```

Initial thought was authentication issue, since GitHub's API docs say that 404s can be returned if the user does not have proper permissions level. Discussed briefly, but @phillipj had to run, so logging this issue so this isn't forgotten.

**Comment by maclover7** [comment]
ping @phillipj, have you had a chance to look into this?

**Comment by phillipj** [comment]
@joyeecheung just found that the bot has to be added as collaborator to the repos we want it to push status updates to.

**Comment by joyeecheung** [comment]
Yes, the setup should be similar to https://github.com/nodejs/automation/blob/master/enable-travis-under-nodejs.md except it's a different CI to poll

**Comment by joyeecheung** [comment]
@maclover7 Which repo does the bot need to have access to? I can add it.

**Comment by maclover7** [comment]
@joyeecheung ah ok. If you could add nodejs/http-parser, that'd be amazing :)

**Comment by joyeecheung** [comment]
@maclover7 OK I've added the bots team to http-parser, can you check if it can update the status now?

**Comment by joyeecheung** [comment]
Also, http-parser does not seem to have setup the github webhook, doesn't it need one?

**Comment by maclover7** [comment]
Perfect, http-parser-test jobs seem to be updating properly now, thank you for your help!

> Also, http-parser does not seem to have setup the github webhook, doesn't it need one?

This was to allow ci.nodejs.org to sent status updates, not Travis CI :)

**Comment by joyeecheung** [comment]
@maclover7 I meant the PR & push events of http-parser would not be sent to the bot, since there are no hooks configured. But if the bot can get the events somehow then it's good.

**Comment by joyeecheung** [comment]
Ah, I see, the events would be manually triggered on the Jenkins UI, instead of being sent from GitHub.

**Comment by joyeecheung** [comment]
(Which reminds me: can we make the bot smarter? Like if the author is a collaborator and they put a keyword in the PR text then the bot will start the CI automatically and reply in the thread?)

**Comment by phillipj** [comment]
For sure.

I've had a go at triggering Jenkins builds by posting comments in PRs. It worked for a whole week or so in the CITGM repo, before we suddenly started seeing "permission denied" responses from Jenkins IIRC: https://github.com/nodejs/github-bot/issues/146

Mind mentioning that my impression is there's lots of discussions to be had before we can enable something like that on the nodejs/node repo because of the "certify safe" option: https://github.com/nodejs/github-bot/pull/128#issuecomment-287187944
