### ISSUE TITLE
Windows: evaluate CI-ing on Windows Containers and WSL

### ISSUE THREAD

**Issue by refack** [nodejs/build#991]
Windows Container have been GA on Windows Server 2016, for over a year, with both "Windows Server Core" and "NanoServer" as the contained OS.
It might be informative to CI in such containers (we already know of two bugs https://github.com/nodejs/node/issues/8897 and https://github.com/nodejs/node/issues/16603)

WSL went GA with "Windows 10 Fall Creators Update" last month and Has been available on Windows Server 2016 since August. Although WSL is ___not___ a production environment many people seem to be using, it at least for development ([10 issues labeled WSL](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=label%3A%22Windows%20Subsystem%20for%20Linux%20(WSL)%22%20))

I'll try to write an ansible script for bootstrapping such environments inside an existing Server2016.

**Comment by refack** [comment]
@StefanScherer do you have `ansible` fu? If not even a list of step for settings up a Windows Container Host and Spinning up a container?
Something like:
1. PS: `Enable-WindowsOptionalFeature -Online -FeatureName Containers`
2. install something
3. download and tag image
4. bind some port to the world
5. Setup `Windows RM` (as per http://docs.ansible.com/ansible/latest/intro_windows.html)
6. ...

**Comment by StefanScherer** [comment]
@refack I don't have an Ansible playbook, but can provide some steps how to install Docker.

With the steps in the docs ( https://store.docker.com/editions/enterprise/docker-ee-server-windows ) there are two relevant steps

```powershell
Install-Module DockerProvider -Force
Install-Package Docker -ProviderName DockerProvider -Force
```

This PowerShell module installs the Containers feature, downloads Docker binaries and installs the Windows service. 

A reboot is required after installing the Containers feature. After the reboot the docker.exe CLI is available in PATH (C:\Program Files\docker). All Docker relevant data can be found in C:\ProgramData\docker.

There is also a PowerShell module by Microsoft (DockerMsftProvider and DockerMsftProviderInsider), but the most recent versions are found with the module by Docker, Inc. (DockerProvider).
In https://github.com/OneGet/MicrosoftDockerProvider you find some more commands how to use these provider packages, eg. find all versions, install a specific version, update, etc.

In my Packer templates there are similar steps in [scripts/docker/2016/](https://github.com/StefanScherer/packer-windows/tree/my/scripts/docker/2016) if this two-liner doesn't work directly. The Hyper-V feature is not mandatory, but helps running older Docker images with older kernel versions.

For Windows Server 2016 LTS channel there are two Windows base images:
* microsoft/windowsservercore:10.0.14393.xxx (xxx=1770 at the moment) or latest
* microsoft/nanoserver:10.0.14393.xxx (xxx=1770 at the moment) or latest

For the Windows Server 1709 Semi-annual channel there are another two base images that fits the host kernel version:
* microsoft/windowsservercore:1709
* microsoft/nanoserver:1709
But you probably want to start with Windows Server 2016. But enhancing CI landscape to the newer Windows Server version might also be interesting to test with the newer Docker images.

Building and running containers then is straight forward.

```
docker run -d -p 3000:3000 stefanscherer/hello-stuttgart
```

Runs a small Node.js web server which listens on port 3000 and can be accessed either from another machine at port 3000 or on the same server with its container IP address. See https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/ for details.

Let me know if you need more information.

**Comment by StefanScherer** [comment]
To build Node.js images I use these scripts in AppVeyor at the moment:
1. https://github.com/StefanScherer/dockerfiles-windows/blob/master/node/build.ps1
2. https://github.com/StefanScherer/dockerfiles-windows/blob/master/node/test.ps1

Step 2 now tests node.exe in nanoserver containers and checks if exit code is fine and expected stdout matches :-)

**Comment by StefanScherer** [comment]
And yes WSL is coming to more and more developer machines on Windows 10. Microsoft also started to provide WSL on Windows Server 2016 so there might be even more adoption in the future.

**Comment by bnoordhuis** [comment]
I've commented on it before but I don't see the point in testing WSL.  It's an emulation layer; any issues that come up on WSL but not on native Linux are bugs that MS has to fix, not us.

**Comment by joaocgreis** [comment]
Creating a job to test on Windows containers sounds good.

Testing on WSL wouldn't be very useful, issues should be reported in https://github.com/Microsoft/WSL/issues, not here. A WSL job could perhaps be useful for comparison with Linux, but we shouldn't fix issues here.

**Comment by Trott** [comment]
Is this something that is likely to get traction and happen at some point? Or should we close this for now? (Containers seems high-value to me, but I could be wrong as I don't know how prevalent containers are in the Windows world.)
