### ISSUE TITLE
Changes to FIPS config

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#996]
FYI I've just done this on the [node-test-commit-linux-fips](https://ci.nodejs.org/job/node-test-commit-linux-fips) config:

```diff
281,284d280
< # individual steps that match &quot;make run-ci&quot; used in regular runs with
< # the additon of the --openssl-fips option
< # and validattion that we built in FIPS capable mode
<
288,289c284,291
< PYTHON=python ./configure --openssl-fips=$WORKSPACE/fipscanisterdir
< PYTHON=python FLAKY_TESTS=$FLAKY_TESTS_MODE $MAKE -j $(getconf _NPROCESSORS_ONLN)
---
> if [ -z ${JOBS+x} ]; then
>   export JOBS=$(getconf _NPROCESSORS_ONLN)
> fi
>
> # First run of test-ci inside of run-ci either runs with FIPS on in 4.X or 5.X
> # or with FIPS off in 6.X or later (as the default was changed)
>
> PYTHON=python NODE_TEST_DIR=${HOME}/node-tmp FLAKY_TESTS=$FLAKY_TESTS_MODE CONFIG_FLAGS=--openssl-fips=$WORKSPACE/fipscanisterdir $MAKE run-ci -j $JOBS
294,296c296,298
< export OPENSSL_VERSION=&quot;`out/Release/node -pe process.versions |grep openssl`&quot;
< echo &quot;Openssl Version: $OPENSSL_VERSION&quot;
< export FIPS_CAPABLE=&quot;`echo &quot;$OPENSSL_VERSION&quot; |grep fips`&quot;
---
> export OPENSSL_VERSION=&quot;`out/Release/node -pe process.versions | grep openssl`&quot;
> echo &quot;OpenSSL Version: $OPENSSL_VERSION&quot;
> export FIPS_CAPABLE=&quot;`echo &quot;$OPENSSL_VERSION&quot; | grep fips`&quot;
298c300,304
<   echo &quot;Not built as FIPS capable, exiting&quot;
---
>   FAIL_MSG=&quot;Not built as FIPS capable, exiting&quot;
>   echo $FAIL_MSG
>   # fake out so we don&amp;apos;t get failures
>   echo &quot;1..1&quot; &gt; ${WORKSPACE}/test.tap
>   echo &quot;not ok 1 $FAIL_MSG&quot; &gt;&gt; ${WORKSPACE}/test.tap
302,305d307
< NODE_VERSION=`out/Release/node --version |awk -F &quot;.&quot; &apos;{print $1}&apos; | sed &apos;s/v//g&apos;`
<
< # This either runs with FIPS on in 4.X or 5.X or with FIPS off in 6.X or later (as the default was changed)
< NODE_TEST_DIR=${HOME}/node-tmp PYTHON=python FLAKY_TESTS=$FLAKY_TESTS_MODE $MAKE test-ci -j $(getconf _NPROCESSORS_ONLN)
307a310,311
> NODE_VERSION=`out/Release/node --version |awk -F &quot;.&quot; &apos;{print $1}&apos; | sed &apos;s/v//g&apos;`
>
310c314
<   NODE_TEST_DIR=${HOME}/node-tmp PYTHON=python FLAKY_TESTS=$FLAKY_TESTS_MODE TEST_CI_ARGS=&quot;--node-args --enable-fips&quot; $MAKE test-ci -j $(getconf _NPROCESSORS_ONLN)
---
>   NODE_TEST_DIR=${HOME}/node-tmp PYTHON=python FLAKY_TESTS=$FLAKY_TESTS_MODE TEST_CI_ARGS=&quot;--node-args --enable-fips&quot; $MAKE test-ci -j $JOBS
```

The 3 main changes here are:
 * The use of `export JOBS`—we should be putting this in all our jobs because `-j` isn't enough to pass down to `test-ci` and friends, `PARALLEL_JOBS` is only set if `JOBS` is set and we end up with non-parallel test runs otherwise
 * The use of `run-ci` and `CONFIG_ARGS` instead of explicit `./configure` followed by `test-ci`. The only drawback here is that it does a full test run before checking if it was compiled with FIPS enabled which will then fail the job. Previously it would check for FIPS enabled status and exit early if it wasn't (I don't know if this has ever happened fwiw!). The second test run with FIPS `--node-args --enable-fips` happens after this check.
* It puts the non-FIPS failure into test.tap before exiting rather than simply `exit 1`. See https://ci.nodejs.org/job/node-test-commit-linux-fips/12533/nodes=ubuntu1404-64/ for a fake failure I made it do (also note the full test suite that's run but doesn't show up in test.tap since it's overwritten with `>`).

**Comment by mhdawson** [comment]
+1.  It would be really nice to get these kinds of changes out into pipelines or scripts to make them easier to track/review

**Comment by gibfahn** [comment]
>+1. It would be really nice to get these kinds of changes out into pipelines or scripts to make them easier to track/review

A good first step would be to put this in a shell script in this repo, then have the Jenkins jobs clone the repo and run the shell script.

Should be a low-impact change.

**Comment by maclover7** [comment]
Going to close for now, we are slowly moving to pipelines / scripts living in `jenkins/`.
