### ISSUE TITLE
rhel V8 test bot is failing during fetch of V8

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#998]
This has been failing since the Nov 11th nightly job

It fails during the phase 

`Fetching V8 from chromium.googlesource.com`

https://ci.nodejs.org/job/node-test-commit-v8-linux/1046/nodes=rhel72-s390x,v8test=v8test/console
https://ci.nodejs.org/job/node-test-commit-v8-linux/1047/nodes=rhel72-s390x,v8test=v8test/console

**Comment by refack** [comment]
seems like the linuxone bots are choking on IPv6 addresses:
```
$ time curl -v -4 --trace-time http://google.com > /dev/null

real    0m0.095s
user    0m0.004s
sys     0m0.006s
```

```
curl -v --trace-time http://google.com > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     013:24:19.184415 * About to connect() to google.com port 80 (#0)
13:24:19.184584 *   Trying 2607:f8b0:4006:811::200e...
  0     0    0     0    0     0      0      0 --:--:--  0:01:19 --:--:--     0
```
`0:01:19` and counting

**Comment by refack** [comment]
As a workaround I've set `/etc/gai.conf`. Should be removed when we know the problem is fixed.
@nodejs/platform-s390

**Comment by gibfahn** [comment]
Hmm, maybe an issue with the infra it's hosted on, not sure.

cc/ @mhdawson , we should probably ask Marist

**Comment by refack** [comment]
Just tested, and problem has been resolved. I moved `/etc/gai.conf` to `/etc/gai.conf.disabled`.
