### ISSUE TITLE
Build WG meeting 2017-11-14 21:00 pm UTC

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#999]
### When

Nov 14, 2017 21:00 UTC - [time in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Build+WG+Meeting&iso=20171114T21)

### Where
- [Hangouts on Air, for participants]
- [Youtube stream, for viewers]
- [Events page](https://www.youtube.com/my_live_events?filter=scheduled)
- [Minutes document]
- [Previous meeting](https://github.com/nodejs/build/issues/939)

### Agenda

Extracted from `wg-agenda` [issues](https://github.com/nodejs/build/issues?q=is%3Aopen+is%3Aissue+label%3Awg-agenda)
and [pull requests](https://github.com/nodejs/build/pulls?q=is%3Aopen+label%3Awg-agenda+is%3Apr) from this repo.

All welcome of course, primarily @nodejs/build focused but we're happy to expand.

Please 👍 if you can make the meeting, and 👎 if you cannot.

**Comment by rvagg** [comment]
Are we on?

**Comment by gibfahn** [comment]
@rvagg don't think anyone who can do the video is here.

**Comment by rvagg** [comment]
OK, let's skip this one eh? Awkward time of the morning for me anyway and I feel like we've been pretty good at staying in sync and making decisions on GitHub these past few weeks anyway.
